### PR TITLE
Fix array_has_all and array_has_any with empty array

### LINKED ISSUE #15038: array_has_any(column, []) with empty array throws RowConverter column schema mismatch, expected Utf8 got Int64
### Describe the bug

Executing `array_has_any(column_name, [])` results in an error:
```
ArrowError(InvalidArgumentError("RowConverter column schema mismatch, expected Utf8 got Int64"), None)
```

### To Reproduce

datafusion version "44.0"
```
use std::sync::Arc;
use datafusion::arrow::array::{Int32Array, StringArray, ArrayRef, ListArray};
use datafusion::arrow::datatypes::{DataType, Field, Schema};
use datafusion::arrow::record_batch::RecordBatch;
use datafusion::arrow::buffer::OffsetBuffer;
use datafusion::datasource::MemTable;
use datafusion::error::Result;
use datafusion::prelude::*;

#[tokio::main]
async fn main() -> Result<()> {
    // Create a simple datafusion table
    let ctx = SessionContext::new();
    
    let schema = Arc::new(Schema::new(vec![
        Field::new("id", DataType::Int32, false),
        Field::new("taxonomy", DataType::List(Arc::new(Field::new(
            "item", 
            DataType::Utf8, 
            true,
        ))), false),
    ]));
    
    let id_array = Arc::new(Int32Array::from(vec![1, 2, 3]));
    
    let values = Arc::new(StringArray::from(vec![
        "category_1", "category_2",  // For id=1
        "category_3",                // For id=2  
        "category_4"                 // For id=3
    ]));
    
    let offsets = OffsetBuffer::new(vec![0, 2, 3, 4].into());
    
    let field = Arc::new(Field::new("item", DataType::Utf8, true));
    let taxonomy_array = Arc::new(ListArray::new(field, offsets, values, None));
    
    let batch = RecordBatch::try_new(
        schema.clone(),
        vec![id_array, taxonomy_array],
    )?;
    
    let partitions = vec![vec![batch]];
    let table = MemTable::try_new(schema, partitions)?;
    ctx.register_table("test_table", Arc::new(table))?;
    
    println!("Original data:");
    let df = ctx.table("test_table").await?;
    df.show().await?;
    
    // Execute the problematic query with empty array
    println!("\nExecuting filter with empty array:");
    let query = "SELECT * FROM test_table WHERE array_has_any(taxonomy, [])";
    // print
    // Error: ArrowError(InvalidArgumentError("RowConverter column schema mismatch, expected Utf8 got Int64"), None)
    ctx.sql(query).await?.show().await?;
    Ok(())
}
```

### Expected behavior

The error message is misleading and does not clearly indicate that an empty array might be an invalid or unsupported input. The issue could be improved by either:
- Providing a more meaningful error message that explicitly states that an empty array is not a valid input.
- Handling the query more gracefully, ensuring that an empty array input does not cause a type mismatch in schema conversion.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LuQQiu**
## Which issue does this PR close?

- Closes #15038 

## What changes are included in this PR?

Fix array_has_any and array_has_all with empty array input

## Are these changes tested?

Added the unit test in array.slt

## Are there any user-facing changes?
NA

### CODE REVIEW

**Comment by LuQQiu** [comment]
@jayzhan211 Could you help approve the test workflows and review the PR? Thanks in advance

File: datafusion/functions-nested/src/array_has.rs [hunk 1]
```diff
@@ -439,6 +439,14 @@ fn array_has_all_and_any_dispatch<O: OffsetSizeTrait>(
 ) -> Result<ArrayRef> {
     let haystack = as_generic_list_array::<O>(haystack)?;
     let needle = as_generic_list_array::<O>(needle)?;
+    if needle.values().len() == 0 {
+        let result_value = match comparison_type {
+            ComparisonType::All => true,
+            ComparisonType::Any => false,
```
Comment (westonpace) [inline datafusion/functions-nested/src/array_has.rs:445]: It's weird to me that `All` is `true` and `Any` is `false` but I agree it matches the descriptions:

`array_has_all: Returns true if all elements of sub-array exist in array.`
`array_has_any: Returns true if any elements exist in both arrays.`

I guess, from a set perspective, we have "true if the intersection of the two sets has the same length as needle" (all) and "true if the intersection of the two sets is non-empty" (any).

File: datafusion/functions-nested/src/array_has.rs [hunk 2]
```diff
@@ -439,6 +439,14 @@ fn array_has_all_and_any_dispatch<O: OffsetSizeTrait>(
...
+        };
+        let result = BooleanArray::from(vec![result_value; haystack.len()]);
```
Comment (westonpace) [inline datafusion/functions-nested/src/array_has.rs:447]: Using `BooleanBuffer::new_set` and `BooleanBuffer::new_unset` should be slightly more efficient.

Comment (LuQQiu) [reply datafusion/functions-nested/src/array_has.rs:447]: Using 
```
    if needle.values().len() == 0 {
        return match comparison_type {
            ComparisonType::All => Ok(Arc::new(BooleanBuffer::new_set(haystack.len()))),
            ComparisonType::Any =>  Ok(Arc::new(BooleanBuffer::new_unset(haystack.len())))
        };
    }
```
Runs into
```
the trait bound `BooleanBuffer: arrow::array::Array` is not satisfied
the following other types implement trait `arrow::array::Array`:
  &T
  BooleanArray
  DictionaryArray<T>
  FixedSizeBinaryArray
  FixedSizeListArray
  GenericByteArray<T>
  GenericByteViewArray<T>
  GenericListArray<OffsetSize>
and 10 others
required for the cast from `std::sync::Arc<BooleanBuffer>` to `std::sync::Arc<dyn arrow::array::Array>`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20[0]?0#file:///Users/lu/Projects/Github/Work/datafusion/datafusion/functions-nested/src/array_has.rs)
```

Comment (alan910127) [reply datafusion/functions-nested/src/array_has.rs:447]: You should use `BooleanArray::from(BooleanBuffer::new_/* ... */)`

File: datafusion/functions-nested/src/array_has.rs (hunk 1 above)
Comment (jayzhan211) [reply datafusion/functions-nested/src/array_has.rs:445]:
```
D select array_has_any([1,2,3], []);
┌────────────────────────────────────────────────────────────┐
│ array_has_any(main.list_value(1, 2, 3), main.list_value()) │
│                          boolean                           │
├────────────────────────────────────────────────────────────┤
│ false                                                      │
└────────────────────────────────────────────────────────────┘
D select array_has_all([1,2,3], []);
┌────────────────────────────────────────────────────────────┐
│ array_has_all(main.list_value(1, 2, 3), main.list_value()) │
│                          boolean                           │
├────────────────────────────────────────────────────────────┤
│ true                                                       │
└────────────────────────────────────────────────────────────┘
```

LGTM

Comment (westonpace) [reply datafusion/functions-nested/src/array_has.rs:445]: Sorry, yes.  I just meant it was strange intuition (I was rambling).  I was not arguing correctness.  I agree this is good.

File: datafusion/functions-nested/src/array_has.rs (hunk 2 above)
Comment (LuQQiu) [reply datafusion/functions-nested/src/array_has.rs]: Thanks for the suggestion! Changed to use BooleanBuffer

**Review by Weijun-H — APPROVED** [review]
LGTM! Thanks @LuQQiu

File: datafusion/sqllogictest/test_files/array.slt [hunk 3]
```diff
@@ -5818,6 +5818,13 @@ false false false false
 false false false false
 false false false false
 
+query BB
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/array.slt:5821]: this query passes on main for me. In other words I don't think the test covers the bug fix 🤔 

```sql
DataFusion CLI v46.0.0
> select array_has_all(make_array(1,2,3), []),
       array_has_any(make_array(1,2,3), []);
+--------------------------------------------------------------------+--------------------------------------------------------------------+
| array_has_all(make_array(Int64(1),Int64(2),Int64(3)),make_array()) | array_has_any(make_array(Int64(1),Int64(2),Int64(3)),make_array()) |
+--------------------------------------------------------------------+--------------------------------------------------------------------+
| true                                                               | false                                                              |
+--------------------------------------------------------------------+--------------------------------------------------------------------+
1 row(s) fetched.
Elapsed 0.024 seconds.

```

Comment (LuQQiu) [reply datafusion/sqllogictest/test_files/array.slt:5821]: Thanks for catching that! Sorry not quite familar with the testing system yet
```
        main  cargo run --bin datafusion-cli                                                                     
DataFusion CLI v46.0.0
> select array_has_all(make_array('1','2','3'),[]), array_has_any(make_array('1','2','3'),[]);
Arrow error: Invalid argument error: RowConverter column schema mismatch, expected Utf8 got Int64
```
will add this test case

**Comment by alamb** [comment]
This PR appears to have some build / CI failures that are preventing it from merging so marking it as drat

@LuQQiu can you please resolve the issues so it can be merged?

**Comment by LuQQiu** [comment]
@alamb @Weijun-H Thanks for the review!

**Comment by alamb** [comment]
THanks again !

**Comment by LuQQiu** [comment]
Thanks for all the reviews and suggestions!
