### PR TITLE
fix: use total ordering in the min & max accumulator for floats

### LINKED ISSUE #8031: Inconsistent null handling in min/max
### Describe the bug

The `datafusion_physical_expr::aggregate::min_max::MinAccumulator` and `MaxAccumulator` appear to use different approaches to calculating the minimum and maximum at different times and this can lead to inconsistent results.

The min/max are extracted from batches using [`arrow_arith::aggregate::max`](https://arrow.apache.org/rust/arrow_arith/aggregate/fn.max.html) and [`arrow_arith::aggregate::min`](https://arrow.apache.org/rust/arrow_arith/aggregate/fn.min.html) which state:

> For floating point arrays any NaN values are considered to be greater than any other non-null value

Once these values are extracted from the batch they are then compared with the current `ScalarValue`.  I had assumed this was using the `PartialOrd` implementation of `ScalarValue` which uses total order (which would still be inconsistent).

However, it appears that [`f32::min`](https://doc.rust-lang.org/std/primitive.f32.html#method.min) and [`f32::max`](https://doc.rust-lang.org/std/primitive.f32.html#method.max) are used instead.  These methods give us a delightful, third interpretation of floating point ordering which is:

> If one of the arguments is NaN, then the other argument is returned.

This means that `min` considers `NaN` to be greater and `max` considers `NaN` to be smaller :dizzy_face: 

As a result, it seems the `MinAccumulator` is consistent (`NaN` is always greater) but not aligned with total ordering.  The `MaxAccumulator` is inconsistent and can give different results depending on how the data is batched up.

### To Reproduce

```
use std::sync::Arc;

use arrow::datatypes::DataType;
use arrow_array::{ArrayRef, Float32Array};
use datafusion::physical_plan::Accumulator;
use datafusion_physical_expr::expressions::MaxAccumulator;

pub fn main() {
    let pos_nan = f32::NAN;
    let zero = 0_f32;

    let vals: ArrayRef = Arc::new(Float32Array::from_iter_values(
        [zero, pos_nan].iter().copied(),
    ));

    // We accumulate the above two rows in two different ways.  First, we pass in both as a single batch
    // This will use `aggregate::max` which always puts `NaN` as the max
    let mut accumulator = MaxAccumulator::try_new(&DataType::Float32).unwrap();
    accumulator.update_batch(&[vals]).unwrap();
    dbg!(&accumulator.evaluate().unwrap()); // prints NaN

    // Next we pass the two values in two different batches.  This will use `f32.max` which never
    // puts `NaN` as the max
    let vals_a: ArrayRef = Arc::new(Float32Array::from_iter_values([pos_nan].iter().copied()));
    let vals_b: ArrayRef = Arc::new(Float32Array::from_iter_values([zero].iter().copied()));

    let mut accumulator = MaxAccumulator::try_new(&DataType::Float32).unwrap();
    accumulator.update_batch(&[vals_a]).unwrap();
    accumulator.update_batch(&[vals_b]).unwrap();
    dbg!(&accumulator.evaluate().unwrap()); // prints 0
}
```

### Expected behavior

My preference would be that everything be done in total order.  I am using `ScalarValue`'s `PartialOrd` internally and I would prefer that it be consistent with min & max.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by westonpace**
## Which issue does this PR close?

Closes #8031

## Rationale for this change

See the motivating issue.

## What changes are included in this PR?

The `MinAccumulator` and `MaxAccumlator` now use `ScalarValue::partial_cmp` to compare two float scalars instead of `f32::min` and `f32::max` (or `f64`).  This is an approach that was already being taken for intervals.

## Are these changes tested?

Yes, I added a unit test.  I did not see any existing benchmarks for the accumulators.  I'm not entirely certain if this approach is slower or not.  However, I think a performance regression is unlikely since this only changes how we compare the intermediate results.  I.e. given two arrays we will use the arrow kernels to find the min/max of the two arrays.  Then we only use this path to compare the result of those two calculations. (e.g. we are in per-batch space and not per-row space)

## Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by westonpace** [comment]
I had to change the `describe` test because the float / double columns have nans (or maybe -inf?).  This means that the `min`, which used to be a value, is now nan (which doesn't seem to display).

I wonder if describe should filter out nan values when calculating min/max?

**Comment by alamb** [comment]
> I had to change the `describe` test because the float / double columns have nans (or maybe -inf?). This means that the `min`, which used to be a value, is now nan (which doesn't seem to display).
> 
> I wonder if describe should filter out nan values when calculating min/max?

FWI I checed what postgres does:

```sql

postgres=# create table foo(x float);
CREATE TABLE

postgres=# insert into foo values (1), (2), ('NaN');
INSERT 0 3
postgres=# select * from foo;
  x
-----
   1
   2
 NaN
(3 rows)

postgres=# select min(x) from foo;
 min
-----
   1
(1 row)

postgres=# select max(x) from foo;
 max
-----
 NaN
(1 row)
```

So that suggests to me it treats `NaN` as the largest floating point value

**Comment by alamb** [comment]
BTW here is a test that shows inconsistent Nan handling for f32 and f64 (just to help make the current behavior clearer): https://github.com/apache/datafusion/pull/10634

**Comment by westonpace** [comment]
> So that suggests to me it treats NaN as the largest floating point value

If this is the case then there is divergence between postgres and arrow-rs.  Which takes priority?

**Comment by westonpace** [comment]
> So that suggests to me it treats NaN as the largest floating point value

This is confirmed in the latest version of the [postgres docs](https://www.postgresql.org/docs/current/datatype-numeric.html):

> IEEE 754 specifies that NaN should not compare equal to any other floating-point value (including NaN). In order to allow floating-point values to be sorted and used in tree-based indexes, PostgreSQL treats NaN values as equal, and greater than all non-NaN values.

**Comment by alamb** [comment]
> If this is the case then there is divergence between postgres and arrow-rs. Which takes priority?

I would personally suggest we do whatever is consistent with arrow (and easier) unless there is a compelling reason to do something different

**Comment by westonpace** [comment]
> @westonpace what is the status / plan with this PR? It has failing CI tests but is not marked as a draft. Are you still planning on working with it? Do you need help to push it along?

Thanks for the push.  I have now discovered sqllogictests :)

Turns out my approach didn't work because partial_cmp propagates nulls (and the previous impl ignored nulls).  I think I've got it fixed now.  The earlier describe test failure was also for this same reason (it was propagating a null, not a nan) and so I was able to revert that change.

**Comment by westonpace** [comment]
I suspect this means that the min/max function for intervals is also incorrectly propagating nulls but I tried to make a unit test for intervals and get an error that there is no accumulator for intervals and so I guess we can cross that bridge when we come to it.

**Comment by westonpace** [comment]
@alamb (See above reply, forgot to ping-reply you)

File: datafusion/physical-expr/src/aggregate/min_max.rs [hunk 1]
```diff
@@ -1103,3 +1117,36 @@ impl Accumulator for SlidingMinAccumulator {
...
+            Arc::new(Float32Array::from_iter_values([pos_nan].iter().copied()));
+        let vals_b: ArrayRef =
+            Arc::new(Float32Array::from_iter_values([zero].iter().copied()));
+
+        let mut accumulator = MaxAccumulator::try_new(&DataType::Float32).unwrap();
+        accumulator.update_batch(&[vals_a]).unwrap();
+        accumulator.update_batch(&[vals_b]).unwrap();
+        let split_batch_result = &accumulator.evaluate().unwrap();
+
+        assert_eq!(single_batch_result, split_batch_result);
```
Comment (alamb) [inline datafusion/physical-expr/src/aggregate/min_max.rs:1150]: I think it would be valuable to also test:
1. `min` 
2. the actul value of `single_batch_result` (to show if it is expected to produce nan or 0)

**Review by alamb — COMMENTED** [review]
Thank you @westonpace  -- this code looks great to me

I think we should add just a few more tests and this will be good to merge 🙏

File: datafusion/physical-expr/src/aggregate/min_max.rs [hunk 2]
```diff
@@ -1103,3 +1117,41 @@ impl Accumulator for SlidingMinAccumulator {
...
+mod tests {
+    use super::*;
+
+    #[test]
+    fn float_min_max_with_nans() {
+        let pos_nan = f32::NAN;
+        let zero = 0_f32;
+        let neg_inf = f32::NEG_INFINITY;
+
+        let check = |acc: &mut dyn Accumulator, values: &[&[f32]], expected: f32| {
```
Comment (alamb) [inline datafusion/physical-expr/src/aggregate/min_max.rs:1131]: 😍

**Review by alamb — APPROVED** [review]
Looks great to me -- thank you @westonpace
