### PR TITLE
Fix [Bug] Aggregate + TopK fails when asc = false

### LINKED ISSUE #16837: [Bug] Aggregate + TopK fails when asc = false
### Describe the bug

There's a rare case that a plan `TableScan -> Aggregate -> TopK` would fail to execute, and raise the following error:
```
Arrow error: Invalid argument error: column types must match schema types, expected Timestamp(Millisecond, Some("UTC")) but found Timestamp(Millisecond, None) at column index 0
```

This issue occurs IF AND ONLY IF all of the following conditions are met simultaneously:
1. Grouping by a timestamp column, where the timestamp column has a non-empty timezone.
2. Aggregating by a column other than the timestamp column (the aggregation column cannot be a timestamp column).
3. Sorting by this aggregation column.
4. The sorting is in descending order. (Ascending order does not trigger this bug.)
5. A non-zero Limit is applied.

### To Reproduce

I have written a unit test to reproduce the bug. The test consists of two cases:
1. Construct a plan `TableScan -> Aggregate -> TopK` with `asc = true`. Executing this plan is ok.
2. Construct the same plan but with `asc = false`, i.e. sort in descending order. Executing this plan would raise an error.

```rust

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use arrow_array::{Int32Array, RecordBatch, TimestampMillisecondArray};
    use arrow_cast::pretty::pretty_format_batches;
    use arrow_schema::{DataType, Field, Schema, TimeUnit};
    use datafusion::{
        catalog::MemTable, datasource::provider_as_source, functions_aggregate::min_max::max,
        physical_plan::collect, prelude::SessionContext,
    };
    use datafusion_common::DataFusionError;
    use datafusion_expr::{LogicalPlanBuilder, SortExpr, col};

    async fn test_aggregate_then_topk(asc: bool) -> datafusion_common::Result<()> {
        let schema = Arc::new(Schema::new(vec![
            Field::new(
                "ts",
                DataType::Timestamp(TimeUnit::Millisecond, Some("UTC".into())),
                false,
            ),
            Field::new("value", DataType::Int32, false),
        ]));
        let columns = vec![
            Arc::new(
                TimestampMillisecondArray::from(vec![1000, 2000, 3000])
                    .with_timezone("UTC".to_string()),
            ) as _,
            Arc::new(Int32Array::from(vec![1, 2, 3])) as _,
        ];
        let batch = RecordBatch::try_new(schema.clone(), columns).map_err(DataFusionError::from)?;
        let mem_table = MemTable::try_new(schema.clone(), vec![vec![batch]])?;

        let plan = LogicalPlanBuilder::scan("t", provider_as_source(Arc::new(mem_table)), None)?
            .aggregate(vec![col("ts")], vec![max(col("value")).alias("max_value")])?
            .sort_with_limit(vec![SortExpr::new(col("max_value"), asc, true)], Some(1))?
            .build()?;
        println!("{}", plan.display_indent());

        let session_state = SessionContext::new().state();
        let exec_plan = session_state.create_physical_plan(&plan).await?;
        let batches = collect(exec_plan, session_state.task_ctx()).await?;
        println!("{}", pretty_format_batches(&batches).unwrap());

        Ok(())
    }

    #[tokio::test]
    async fn test() {
        // Case 1: TableScan -> Aggregate -> Topk (asc = true)
        let result = test_aggregate_then_topk(true).await;
        assert!(result.is_ok());

        // Case 2: TableScan -> Aggregate -> Topk (asc = false)
        let result = test_aggregate_then_topk(false).await;
        assert!(result.is_err());
    }
}
```

### Expected behavior

_No response_

### Additional context

This bug is confirmed to exist both in the latest codebase (rev: 350c61b) and in the v48.0.0

### PR DESCRIPTION
**Pull request by avantgardnerio**
## Which issue does this PR close?

- Closes #16837.

## Rationale for this change

Solve issue 16837

## What changes are included in this PR?

Pass full datatype though to output in `PrimitiveHashTable`

## Are these changes tested?

A unit test was added. It failed, then it didn't.

## Are there any user-facing changes?

More queries should work.

### CODE REVIEW

**Comment by alamb** [comment]
@niebayes can you please help review this PR and ensure it solves your issue?

File: datafusion/physical-plan/src/aggregates/topk/hash_table.rs [hunk 1]
```diff
@@ -433,8 +440,27 @@ pub fn new_hash_table(
 #[cfg(test)]
 mod tests {
     use super::*;
+    use arrow::array::TimestampMillisecondArray;
+    use arrow_schema::TimeUnit;
     use std::collections::BTreeMap;
 
+    #[test]
+    fn should_emit_correct_type() -> Result<()> {
```
Comment (alamb) [inline datafusion/physical-plan/src/aggregates/topk/hash_table.rs:448]: I verified this test fails without the code change in this PR and thus conclude the test covers the change

```

assertion `left == right` failed
  left: Timestamp(Millisecond, None)
 right: Timestamp(Millisecond, Some("UTC"))

Left:  Timestamp(Millisecond, None)
Right: Timestamp(Millisecond, Some("UTC"))
<Click to see difference>
```

**Review by alamb — APPROVED** [review]
Thank you @avantgardnerio  -- this looks good to me

File: datafusion/physical-plan/src/aggregates/topk/hash_table.rs (hunk 1 above)
Comment (avantgardnerio) [reply datafusion/physical-plan/src/aggregates/topk/hash_table.rs:448]: Thanks. I started with @niebayes ' test and created this one instead because it covered the case and felt less like an e2e test.

**Comment by niebayes** [comment]
@avantgardnerio @alamb Thank you. I've confirmed this path solved the issue.
