### PR TITLE
Fix nullability of return value of array_agg

### LINKED ISSUE #11094: Nullability of array_agg
### Describe the bug

The logic for nullability for the return value of array_agg is currently correct. 

### To Reproduce

The current logic is here: https://github.com/apache/datafusion/blob/c7ac8b8221229b307bba434390ce1d19b7fb9358/datafusion/physical-expr/src/aggregate/array_agg.rs#L69-L76
it returns a list where the nullability depens on the input and the field in the list is always nullable. 

### Expected behavior

The fields nullability should depend on the input_nullability and the nullability of the list should be false.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by eejbyfeldt**
## Which issue does this PR close?

Closes #11094. 

## Rationale for this change

Currently the nullability of the value of the return type for the array_agg aggregate is wrong in two ways. Firstly the field inside the returned list is always nullable regardless of the input type and the actual list is only nullable depending on the input value. The correct behavior should be that the field in the list should depend on the input values nullabillity and the list field should not be nullable as the aggregate never returns null (it returns empty list instead).

## What changes are included in this PR?

In order to fix the nullability several changes are needed.

1. For the logical expr it is currently hard coded that all aggregates return nullable values, this is changed to be something that looked up based on the actual functions used.  For UDAF we will need to add a new customization point in the future to handle this case.

1. The return_type method for builtin aggregates got an additional argument `&[bool]` with the nullability of the the inputs. Without this is not possible to implement the function with correct nullability or array_agg.

1. Helper methods ScalarValue::new_list and `array_into_list_array`  currently always makes the field nullable. To make these more usable I added a nullable argument to them and renamed the existing version with a `_nullable` prefix.

## Are these changes tested?

Existing tests.

## Are there any user-facing changes?

Yes, this will change the nullability of array_aggs. And it changes the interface for some public methods `ScalarValue::new_list`, `ScalarValue::new_list_from_iter` and `array_into_list_array` to take a `nullable: bool` argument. 

Are these API breakages acceptable? Or should we leave the existing APIs as is and introduce new methods to fix the issue?

### CODE REVIEW

File: datafusion/expr/src/expr_schema.rs [hunk 1]
```diff
@@ -314,11 +322,17 @@ impl ExprSchemable for Expr {
                 }
             }
             Expr::Cast(Cast { expr, .. }) => expr.nullable(input_schema),
+            Expr::AggregateFunction(AggregateFunction { func_def, .. }) => {
+                match func_def {
+                    AggregateFunctionDefinition::BuiltIn(fun) => fun.nullable(),
+                    // TODO: UDF should be able to customize nullability
```
Comment (jayzhan211) [inline datafusion/expr/src/expr_schema.rs:328]: I'm not sure about that we need to customize nullability, can we get the nullabiity based on expression in the function?

Comment (jayzhan211) [reply datafusion/expr/src/expr_schema.rs:328]: Maybe we just need to add `field` to UDAFImpl, so they can define their own field

Comment (jayzhan211) [reply datafusion/expr/src/expr_schema.rs:328]: > I'm not sure about whether we need to customize nullability, can we get the nullabiity based on expression in the function?

I think probably ArrayAgg is the function that we need the nullability be `false` 🤔

**Review by jayzhan211 — DISMISSED** [review]
👍

**Review by alamb — COMMENTED** [review]
I wonder how this would look if we simply always made ScalarValue::List be nullable ?

Specifically is there a compelling usecase for specifying between nullable and non nullable lists? I am pretty sure none of the arrow kernels look at the nullability of the data type (they look at the actual null count of the actual data)

If we could make lists always nullable I suspect this PR could be made much simplar (and avoid the breaking API change)

**Comment by eejbyfeldt** [comment]
> I wonder how this would look if we simply always made ScalarValue::List be nullable ?

Feels like I might be missing what you mean by this. Because If you mean make the field inside the list nullable, my understanding is that this is basically the state of the code today? And that makes it not possible/hard to correctly propagate the nullability of expressions like `array_agg`.

> Specifically is there a compelling usecase for specifying between nullable and non nullable lists?

To clarify it is not the list that this fixes the nullable for, but the elements inside the list.

> I am pretty sure none of the arrow kernels look at the nullability of the data type (they look at the actual null count of the actual data)

I think this might be true. But my thinking that the nullability of columns is leveraged in the optimizer here for example is a transformation that uses the nullability:

https://github.com/apache/datafusion/blob/c7ac8b8221229b307bba434390ce1d19b7fb9358/datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs#L793-L800

so by maintaining the correct nullability we will allow for more simplifications.


> If we could make lists always nullable I suspect this PR could be made much simplar (and avoid the breaking API change)

If we want to avoid breaking the API it could be easily be done by adding new methods instad of changing the old ones. The reason I opted for breaking the API is that I suspect that each place we current API is a place where we are currently not correctly propagating the nullability.

File: datafusion/expr/src/expr_schema.rs (hunk 1 above)
Comment (eejbyfeldt) [reply datafusion/expr/src/expr_schema.rs:328]: > I'm not sure about whether we need to customize nullability, can we get the nullabiity based on expression in the function?

But that will need to get it from the specific UDAF implementation right?  

> If we need it, we can add field to UDAFImpl, so they can define their own field. state_field is already customizable

That would resolve it.

> I think probably ArrayAgg is the function that we need the nullability be `false` 🤔

There is also `count` and the the count like e.g approx_distinct etc.

**Comment by jayzhan211** [comment]
I think the `nullability` we get in the optimize rule you mentioned is actually always `true` for AggregateFuncion

https://github.com/apache/datafusion/blob/d44c7f2ac31100c3d66685336813e195edc4357f/datafusion/expr/src/expr_schema.rs#L317-L323

The `field` we changed is in the physical plan layer, I think the tradeoff is only losing the possible of physical plan optimization 🤔 .

**Comment by eejbyfeldt** [comment]
> I think the `nullability` we get in the logical optimize rule you mentioned is actually always `true` for AggregateFuncion
> 
> https://github.com/apache/datafusion/blob/d44c7f2ac31100c3d66685336813e195edc4357f/datafusion/expr/src/expr_schema.rs#L317-L323

This is something that is fixed/changed in this PR see:

https://github.com/apache/datafusion/blob/f4c7da3cde2a6d7bba51b41e4affc208f1b69913/datafusion/expr/src/expr_schema.rs#L325-L331

**Review by jayzhan211 — APPROVED** [review]
I agree that we are able to optimize logical plan based on whether the list is null or not.

File: datafusion/common/src/utils/mod.rs [hunk 2]
```diff
@@ -351,10 +351,19 @@ pub fn longest_consecutive_prefix<T: Borrow<usize>>(
...
+/// The field in the list array is nullable.
+pub fn array_into_list_array_nullable(arr: ArrayRef) -> ListArray {
+    array_into_list_array(arr, true)
+}
+
+/// Array Utils
+
+/// Wrap an array into a single element `ListArray`.
+/// For example `[1, 2, 3]` would be converted into `[[1, 2, 3]]`
+pub fn array_into_list_array(arr: ArrayRef, nullable: bool) -> ListArray {
```
Comment (jayzhan211) [inline datafusion/common/src/utils/mod.rs:363]: @eejbyfeldt I think the concern to merge this PR, is to minimize breaking change.

We could keep `array_into_list_array` as it is, but add `array_into_list_array_nullable` which is configurable on null. What do you think?

**Comment by jayzhan211** [comment]
Thanks @eejbyfeldt @alamb . I think we could move on with this.

Let's create a ticket to address UDAF nullability customization
