### PR TITLE
fix: CteWorkTable: properly apply TableProvider::scan projection argument

### LINKED ISSUE #18992: `CteWorkTable` does not properly apply projection
### Describe the bug

The `CteWorkTable`  discards the `projection` argument of the `TableProvider::scan` instead of properly applying it. It can cause issues when the projection is not the identity

### To Reproduce

Use `CteWorkTable` with a projection that is not the identity

Example of query plan where the optimizer create a projection:
```
RecursiveQuery: is_distinct=true
  Projection: quads.subject, quads.predicate, quads.object
    Inner Join: 98c0b23282ec3edfa32aea6fa0af5240 = quads.subject
      Projection: Binary("1,98,167,105,102,76,38,234,212,25,70,164,18,107,5,43,205") AS 98c0b23282ec3edfa32aea6fa0af5240
        EmptyRelation: rows=1
      TableScan: quads projection=[subject, predicate, object], full_filters=[quads.graph_name IS NULL]
  Projection: quads.subject, quads.predicate, quads.object
    Inner Join: cbd.object = quads.subject
      Filter: sparql:isBlank(cbd.object)
        TableScan: cbd projection=[object]
      TableScan: quads projection=[subject, predicate, object], full_filters=[quads.graph_name IS NULL]
```
Note the `TableScan: cbd projection=[object]` that is using `CteWorkTable

### Expected behavior

Projection properly applied

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Tpt**
It was previously ignored

## Which issue does this PR close?

- Closes #18992.

## Rationale for this change

All `TableProvider` implementations must support the `projection` argument of the `scan` method. This was not the case in `CteWorkTable`.

## What changes are included in this PR?

Minimal implementation of the projection support. The projection applied before the plan node return results. It might be nice to push it further inside of the recursion implementation to reduce memory consumption but I preferred to keep the fix minimal.

## Are these changes tested?

I have not figured out yet a nice SQL query to trigger an error without this change. Some existing queries in `cte.slt` have set projection (i.e. not `None`) so the code is very likely working. There is also a test on the projection itself in `WorkTableExec`

### CODE REVIEW

File: datafusion/physical-plan/src/work_table.rs
Comment (martin-g) [inline datafusion/physical-plan/src/work_table.rs:359]: It would be good to add a test case using projection.

File: datafusion/catalog/src/cte_worktable.rs [hunk 1]
```diff
@@ -86,15 +87,20 @@ impl TableProvider for CteWorkTable {
...
+        projection: Option<&Vec<usize>>,
+        filters: &[Expr],
+        limit: Option<usize>,
     ) -> Result<Arc<dyn ExecutionPlan>> {
-        // TODO: pushdown filters and limits
+        assert_or_internal_err!(
+            filters.is_empty(),
+            "CteWorkTable does not support pushing filters"
+        );
+        assert_or_internal_err!(limit.is_none(), "CteWorkTable pushing limit");
```
Comment (martin-g) [inline datafusion/catalog/src/cte_worktable.rs]: The error message is a bit unclear to me.
Maybe:

```suggestion
        assert_or_internal_err!(limit.is_none(), "CteWorkTable does not support limit pushdown");
```
?!

File: datafusion/physical-plan/src/work_table.rs [hunk 2]
```diff
@@ -103,25 +103,35 @@ pub struct WorkTableExec {
     name: String,
     /// The schema of the stream
     schema: SchemaRef,
+    /// Projection to apply to build the output stream from the recursion state
+    projection: Option<Vec<usize>>,
     /// The work table
     work_table: Arc<WorkTable>,
     /// Execution metrics
     metrics: ExecutionPlanMetricsSet,
     /// Cache holding plan properties like equivalences, output partitioning etc.
```
Comment (martin-g) [inline datafusion/physical-plan/src/work_table.rs:111]: The docstring is outdated now. The field is not named `cache` anymore.

Comment (Tpt) [reply datafusion/physical-plan/src/work_table.rs:111]: Indeed, I have moved back the field name to `cache` to stay consistent with a lot of other operator implementations: 69464d2b73919d79fdf8176dbfa7645ca66e5e2f

File: datafusion/physical-plan/src/work_table.rs
Comment (Tpt) [reply datafusion/physical-plan/src/work_table.rs:359]: Done! 304d40c2484e8873abbfd33be80a957be1e1257b

File: datafusion/catalog/src/cte_worktable.rs [hunk 3]
```diff
@@ -86,15 +87,23 @@ impl TableProvider for CteWorkTable {
     async fn scan(
         &self,
         _state: &dyn Session,
-        _projection: Option<&Vec<usize>>,
-        _filters: &[Expr],
-        _limit: Option<usize>,
+        projection: Option<&Vec<usize>>,
+        filters: &[Expr],
+        limit: Option<usize>,
     ) -> Result<Arc<dyn ExecutionPlan>> {
```
Comment (adriangb) [inline datafusion/catalog/src/cte_worktable.rs:90]: May I recommend we update to use `scan_with_args`?

Comment (Tpt) [reply datafusion/catalog/src/cte_worktable.rs:90]: Done!

Comment (adriangb) [reply datafusion/catalog/src/cte_worktable.rs:90]: Not quite what I meant: you'd implement `scan_with_args` and delete the `scan` implementation

Comment (Tpt) [reply datafusion/catalog/src/cte_worktable.rs:90]: Sadly the `scan` method does not have a default implementation in the trait so I have to implement it. I preferred to make it call `scan_with_args` but glad to do otherwise if you prefer.

Comment (adriangb) [reply datafusion/catalog/src/cte_worktable.rs:90]: Ah yes right I see. I don't think it will ever be called if you implement `scan_with_args`. But it's okay to leave the implementation here as you have.

**Comment by adriangb** [comment]
Is there a SQL reproducer for this? Could we add slt tests?

**Comment by Tpt** [comment]
> Is there a SQL reproducer for this? Could we add slt tests?

I spent more than an hour trying to reproduce it in SQL but failed, sadly. It's why I wrote an explicit test for projection. I encountered this issue while implementing SPARQL property paths on top of DataFusion.

File: datafusion/physical-plan/src/work_table.rs [hunk 4]
```diff
@@ -196,11 +206,22 @@ impl ExecutionPlan for WorkTableExec {
...
         );
-        let batch = self.work_table.take()?;
+        let ReservedBatches {
+            mut batches,
+            reservation,
+        } = self.work_table.take()?;
+        if let Some(projection) = &self.projection {
+            // We apply the projection
+            // TODO: it would be better to apply it as soon as possible and not only here
+            // TODO: an aggressive projection makes the memory reservation smaller, even if we do not edit it
```
Comment (adriangb) [inline datafusion/physical-plan/src/work_table.rs:218]: Could you expand on this a bit? Where would "as soon as possible" be? I'm not familiar with what WorkTableExec is or how it is used 🥲

Comment (Tpt) [reply datafusion/physical-plan/src/work_table.rs:218]: `WorkTableExec` is used for recursive CTEs. They are evaluated by executing the same query plan multiple time. The output of the previous iteration is injected as the value of the "work table" in the next iteration.

Here "as soon as possible" means that when we execute the previous iteration we don't need to save all the columns of the output of this iteration to feed them into the "work table" of the next iteration but only the columns that are actually needed.

**Comment by Tpt** [comment]
I have rebased the MR after the merge of #18956

**Review by Jefffrey — APPROVED** [review]

**Comment by Jefffrey** [comment]
Thanks @Tpt, @martin-g & @adriangb
