### PR TITLE
fix: try again to fix Miri in ParquetOpener

### LINKED ISSUE #21662: Stacked Borrows violation in `PushDecoderStreamState::transition`
### Describe the bug

Miri detects a Stacked Borrows violation in `datafusion-datasource-parquet/src/opener.rs` at line 1258:

```
self.decoder.push_ranges(ranges, data)?;
```

A `Unique` retag (mutable borrow) of the decoder is created, then invalidated by a `SharedReadOnly` retag at an `.await` point in the `unfold`-based stream. When the future resumes, the original `Unique` tag no longer exists in the borrow stack.

This was found while testing DataFusion 54.0 with [Apache DataFusion Comet](https://github.com/apache/datafusion-comet). Comet runs Miri in CI and caught this: [CI run](https://github.com/apache/datafusion-comet/actions/runs/24487781385/job/71566377807?pr=3916). DataFusion does not currently run Miri in its own CI.

### To Reproduce

Run Miri against any test that exercises the `PushDecoderStreamState` parquet stream path. In our case it was triggered by a test that calls `scan.execute(...).collect().await` on a parquet scan.

### Expected behavior

No undefined behavior under Miri's Stacked Borrows model.

### Miri output

```
error: Undefined Behavior: trying to retag from <28128923> for SharedReadWrite permission at alloc8513101[0x8], but that tag does not exist in the borrow stack for this location
    --> datafusion/datasource-parquet/src/opener.rs:1258:25
     |
1258 |                         self.decoder.push_ranges(ranges, data)?;
     |                         ^^^^^^^^^^^^ this error occurs as part of two-phase retag at alloc8513101[0x8..0x20]
     |
     = help: this indicates a potential bug in the program: it performed an invalid operation, but the Stacked Borrows rules it violated are still experimental
     = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
help: <28128923> was created by a Unique retag at offsets [0x8..0x20]
help: <28128923> was later invalidated at offsets [0x0..0x138] by a SharedReadOnly retag
```

### Additional context

The full backtrace points to `PushDecoderStreamState::transition` -> `RowGroupsPrunedParquetOpen::build_stream` closure -> `futures::stream::Unfold` poll. The aliasing violation occurs because the decoder is mutably re-borrowed across a yield point in the `unfold` stream.

### PR DESCRIPTION
**Pull request by mbutrovich**
## Which issue does this PR close?

- Closes #21662.

## Rationale for this change

#21663 removed the nested async block in `PushDecoderStreamState::transition` to fix a Stacked Borrows violation under miri. However, miri still flags the same violation because `&mut self` is still a single opaque borrow — inlining the async block alone doesn't let miri split the disjoint field borrows across the `.await` yield point.

Comet CI reproduces this reliably: https://github.com/apache/datafusion-comet/actions/runs/24518967597/job/71671004017?pr=3916

## What changes are included in this PR?

Change `PushDecoderStreamState::transition` to take `self` by value instead of `&mut self`. With `&mut self`, the generated future stores a mutable reference, and when `unfold` pins and polls it, miri sees the `&mut self` as a single opaque borrow that conflicts across the `.await` yield point. With owned `self`, the future owns the state directly — no reference means no Stacked Borrows conflict. The struct fields are all heap-allocated or reference-counted, so the move is just pointer-sized copies, not a deep copy.

## Are these changes tested?

Existing tests cover this code path. The fix is validated by miri passing in CI (the same test that currently fails: `test_nested_types_extract_missing_struct_names_missing_field`). We'll run Comet CI against this branch first to confirm the miri violation is resolved before merging.

## Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by mbutrovich** [comment]
Testing the fix in Comet CI: https://github.com/apache/datafusion-comet/pull/3960

**Comment by mbutrovich** [comment]
Miri is green in Comet CI with the latest commit: https://github.com/apache/datafusion-comet/actions/runs/24522903075/job/71685242268?pr=3960

File: datafusion/datasource-parquet/src/opener.rs [hunk 1]
```diff
@@ -1265,24 +1262,26 @@ impl PushDecoderStreamState {
...
+                        Err(e) => return Some((Err(e), self)),
                     }
                 }
                 Ok(DecodeResult::Data(batch)) => {
                     let mut timer = self.baseline_metrics.elapsed_compute().timer();
                     self.copy_arrow_reader_metrics();
                     let result = self.project_batch(&batch);
                     timer.stop();
-                    return Some(result);
+                    // Release the borrow on baseline_metrics before moving self
```
Comment (comphead) [inline datafusion/datasource-parquet/src/opener.rs:1276]: 👍

**Review by comphead — APPROVED** [review]
Thanks @mbutrovich IMO it is good to go.

File: datafusion/datasource-parquet/src/opener.rs [hunk 2]
```diff
@@ -1248,15 +1245,15 @@ impl PushDecoderStreamState {
     ///   fetched from the [`AsyncFileReader`] and fed back into the decoder.
     /// - [`Data`](DecodeResult::Data) – a decoded batch is projected and returned.
     /// - [`Finished`](DecodeResult::Finished) – signals end-of-stream (`None`).
-    async fn transition(&mut self) -> Option<Result<RecordBatch>> {
+    ///
+    /// Takes `self` by value (rather than `&mut self`) so the generated future
```
Comment (alamb) [inline datafusion/datasource-parquet/src/opener.rs:1249]: 👍 Makes esne to me
