### PR TITLE
fix: derive custome nullable for the spark last_day

### LINKED ISSUE #19153: spark `last_day` need to have custom nullability
### Describe the bug

the UDF uses the default `is_nullable` which is always true which is not the case

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kumarUjjawal**
## Which issue does this PR close?

- Closes #19153.
- Part of #19144 

## What changes are included in this PR?

- Spark `last_day` now reports schema using `return_field_from_args`
- Added unit tests

## Are these changes tested?

- All previouse tests pass
- Added new unit tests

### CODE REVIEW

File: datafusion/spark/src/function/datetime/last_day.rs [hunk 1]
```diff
@@ -60,7 +61,19 @@ impl ScalarUDFImpl for SparkLastDay {
     }
 
     fn return_type(&self, _arg_types: &[DataType]) -> Result<DataType> {
-        Ok(DataType::Date32)
+        internal_err!("return_field_from_args should be used instead")
+    }
+
+    fn return_field_from_args(&self, args: ReturnFieldArgs) -> Result<FieldRef> {
+        let Some(field) = args.arg_fields.first() else {
```
Comment (martin-g) [inline datafusion/spark/src/function/datetime/last_day.rs:68]: nit: Passing more than one argument fields will also pass this check.
