### PR TITLE
perf: Fix quadratic behavior of `to_array_of_size`

### LINKED ISSUE #18159: Avoid deep copying `Utf8View` array buffers in `ScalarValue::to_array_of_size()`
### Describe the bug

The `ScalarValue::to_array_of_size()` API is repeating a scalar value k times and convert it into a array of length `k`. For `ScalarValue::List` type with inner list type `Utf8View`, now it's doing deep copy for the `Utf8View` buffers.

Note copying the inner `Utf8View` array is inevitable due to the `ListArray` encoding, but deep copying the payload buffers can be avoided, only the views should be copied.

See the `List` implementation in https://github.com/apache/datafusion/blob/35b2e359f6703dedc6bf8ced3f0699d8a885d4df/datafusion/common/src/scalar/mod.rs#L2877

This caused performance regression in https://github.com/apache/datafusion/issues/18070

### To Reproduce

It can be verified easier by checking the implementation.

### Expected behavior

Doing shallow copy on `List` elements

### Additional context

_No response_

### LINKED ISSUE #20458: `ScalarValue::to_array_of_size` is slow for StringViewArray with many buffers
### Describe the bug

* `ScalarValue::to_array_of_size` calls `list_to_array_of_size` for list-like inputs
* `list_to_array_of_size` will be called with a one-element list containing an Arrow array type, and it does:
```rust
        let arrays = repeat_n(arr, size).collect::<Vec<_>>();
        let ret = match !arrays.is_empty() {
            true => arrow::compute::concat(arrays.as_slice())?,
            false => arr.slice(0, 0),
       };
```
* If the input is a `StringViewArray`, `repeat_n` will create `size` copies, each with their own data buffers. `concat` preserves those data buffers. So if the input is, say, a `StringViewArray` with 500 buffers and `size` is 1024, the result will have 500k buffers.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

We probably didn't see this problem before because DF doesn't usually call `ScalarValue::to_array_of_size` on a list whose underlying StringViewArray has many data buffers. I ran into this when working on #3781. It crops up in a scenario like 

```
SELECT ... FROM t WHERE array_has_any(f.c, (SELECT array_agg(...) FROM parquet_source_file))
```

The `array_agg` creates a `StringViewArray` with many data buffers. In current DF, this gets rewritten into a join, but after fixing #3781, `array_has_any` is instead invoked with the `array_agg` output as a scalar, so we go through this code path and run into some pain.

### PR DESCRIPTION
**Pull request by neilconway**
## Which issue does this PR close?

- Closes #20458.
- Closes #18159.

## Rationale for this change

When `array_to_size(n)` was called on a `List`-like object containing a `StringViewArray` with `b` data buffers, the previous implementation returned a list containing a `StringViewArray` with `n*b` buffers, which results in catastrophically bad performance if `b` grows even somewhat large.

This issue was previously noticed causing poor nested loop join performance. #18161 adjusted the NLJ code to avoid calling `to_array_of_size` for this reason, but didn't attempt to fix the underlying issue in `to_array_of_size`. This PR doesn't attempt to revert the change to the NLJ code: the special-case code added in #18161 is still slightly faster than `to_array_of_size` after this optimization. It might be possible to address that in a future PR.

## What changes are included in this PR?
* Instead of using `repeat_n` + `concat` to merge together `n` copies of the `StringViewArray`, we instead use `take`, which preserves the same number of buffers as the input `StringViewArray`.
* Add a new benchmark for this situation
* Add more unit tests for `to_array_of_size`

## Are these changes tested?

Yes and benchmarked.

## Are there any user-facing changes?

No.

## AI usage

Iterated on the problem with Claude Code; I understand the problem and the solution.

### CODE REVIEW

**Comment by neilconway** [comment]
Benchmarks:

```
group                                    array-of-size-opt                      array-of-size-vanilla
-----                                    -----------------                      ---------------------
list_to_array_of_size/1_buffer/1024      1.00  1870.0±30.72µs        ? ?/sec    3.77      7.1±0.05ms        ? ?/sec
list_to_array_of_size/1_buffer/256       1.00    337.9±4.16µs        ? ?/sec    1.77    599.8±5.17µs        ? ?/sec
list_to_array_of_size/50_buffers/1024    1.00  1945.4±23.28µs        ? ?/sec    65.93   128.3±1.06ms        ? ?/sec
list_to_array_of_size/50_buffers/256     1.00    364.7±4.31µs        ? ?/sec    22.76     8.3±0.07ms        ? ?/sec
```

**Comment by neilconway** [comment]
I see #18159 already exists for this issue; I'll be optimistic and claim this PR closes it... 😅

**Comment by neilconway** [comment]
We could consider backing out the special-case logic in NLJ that was introduced in #18161, but that will require some consideration and benchmarking first. I tried a quick hack to remove the NLJ workaround but it hurt performance on a microbenchmark by ~15%

**Comment by comphead** [comment]
@Dandandan FYI

File: datafusion/common/src/scalar/mod.rs [hunk 1]
```diff
@@ -3435,12 +3435,13 @@ impl ScalarValue {
...
-            true => arrow::compute::concat(arrays.as_slice())?,
-            false => arr.slice(0, 0),
-        };
-        Ok(ret)
+        if size == 0 {
+            return Ok(arr.slice(0, 0));
+        }
+
+        let n = arr.len() as u32;
+        let indices = UInt32Array::from_iter_values((0..size).flat_map(|_| 0..n));
```
Comment (comphead) [inline datafusion/common/src/scalar/mod.rs:3451]: perhaps we can document here 

```
Suppose inner array is [A, B, C] and you want size=3:

indices becomes: [0,1,2, 0,1,2, 0,1,2]
take produces: [A,B,C, A,B,C, A,B,C]
```

Comment (neilconway) [reply datafusion/common/src/scalar/mod.rs:3451]: Good idea! I added two examples in a comment.

File: datafusion/common/src/scalar/mod.rs [hunk 2]
```diff
@@ -3434,13 +3434,22 @@ impl ScalarValue {
...
-        Ok(ret)
+        if size == 0 {
+            return Ok(arr.slice(0, 0));
+        }
+
+        // Examples: given `arr = [[A, B, C]]` and `size = 3`, `indices = [0, 0, 0]` and
+        // the result is `[[A, B, C], [A, B, C], [A, B, C]]`.
+        //
+        // Given `arr = [[A, B], [C]]` and `size = 2`, `indices = [0, 1, 0, 1]` and the
+        // result is `[[A, B], [C], [A, B], [C]]`. (But in practice, we are always called
```
Comment (Jefffrey) [inline datafusion/common/src/scalar/mod.rs:3448]: Would it be better to explicitly check that `arr.len() == 1` so we don't need to cover edge cases that aren't meant to occur? (Which can lead to a bit simpler/readable code here)

Comment (neilconway) [reply datafusion/common/src/scalar/mod.rs:3448]: Personally, I'm inclined to leave it as-is: with the comment giving some examples, the behavior seems reasonably clear to me, and it's not more code to handle the `arr.len() > 1` case. But lmk if you disagree.

**Comment by alamb** [comment]
Looks good to me --  thanks @neilconway and @Jefffrey
