### PR TITLE
Minor: Add SMJ to TPCH benchmark usage

### LINKED ISSUE #10100: fix Sort Merge Join to pass TPCH tests
I was trying to mark the Sort Merge Join as stable and run TPCH tests with SMJ enforced. Got the issue below, we need to fix before returning to discuss SMJ stable status

To run benches 
`RESULTS_NAME=smj ./benchmarks/bench.sh run tpch_smj`

Depends on #10092

```
thread 'tokio-runtime-worker' panicked at datafusion/physical-plan/src/joins/sort_merge_join.rs:1357:22:
index out of bounds: the len is 0 but the index is 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at datafusion/physical-plan/src/joins/sort_merge_join.rs:1357:22:
index out of bounds: the len is 0 but the index is 1
thread 'tokio-runtime-worker' panicked at datafusion/physical-plan/src/joins/sort_merge_join.rs:1357:22:
index out of bounds: the len is 0 but the index is 1
thread 'tokio-runtime-worker' panicked at datafusion/physical-plan/src/joins/sort_merge_join.rs:1357:22:
index out of bounds: the len is 0 but the index is 1
Error: Context("Join Error", External(JoinError::Panic(Id(88693), ...)))
```
 
_Originally posted by @comphead in https://github.com/apache/arrow-datafusion/issues/9846#issuecomment-2057999488_

### PR DESCRIPTION
**Pull request by comphead**
## Which issue does this PR close?

Closes #10100 .

## Rationale for this change
Basically fix for #10380 fixed the issue, I just fixing also the usage info for SMJ

### CODE REVIEW

**Comment by comphead** [comment]
I checked the TPCH benchmarks passes with SMJ on and row counts are the same
```
RUST_BACKTRACE=1 RESULTS_NAME=smj ./benchmarks/bench.sh run tpch_smj
RUST_BACKTRACE=1 RESULTS_NAME=hj ./benchmarks/bench.sh run tpch
RUST_BACKTRACE=1 RESULTS_NAME=smj10 ./benchmarks/bench.sh run tpch_smj10
RUST_BACKTRACE=1 RESULTS_NAME=hj10 ./benchmarks/bench.sh run tpch10
```

File: benchmarks/bench.sh [hunk 1]
```diff
@@ -66,9 +66,11 @@ compare:      Compares results from benchmark runs
 * Benchmarks
 **********
 all(default): Data/Run/Compare for all benchmarks
-tpch:                   TPCH inspired benchmark on Scale Factor (SF) 1 (~1GB), single parquet file per table
+tpch:                   TPCH inspired benchmark on Scale Factor (SF) 1 (~1GB), single parquet file per table, hash join
+tpch_smj:               TPCH inspired benchmark on Scale Factor (SF) 1 (~1GB), single parquet file per table, sort merge join
 tpch_mem:               TPCH inspired benchmark on Scale Factor (SF) 1 (~1GB), query from memory
-tpch10:                 TPCH inspired benchmark on Scale Factor (SF) 10 (~10GB), single parquet file per table
+tpch10:                 TPCH inspired benchmark on Scale Factor (SF) 10 (~10GB), single parquet file per table, hash join
+tpch_smj10:             TPCH inspired benchmark on Scale Factor (SF) 10 (~10GB), single parquet file per table, sort merge join
```
Comment (comphead) [inline benchmarks/bench.sh:73]: I'm planning to get rid of tpch_smj* soon and get the hash join type from the user input any bench can run with a choice of join type

**Review by alamb — APPROVED** [review]
Thank you @comphead
