### PR TITLE
Do not unescape backslashes in datafusion-cli

### LINKED ISSUE #13286: Incorrect backslash treatment in string literals in DataFusion CLI
In standard SQL, the `\` character has no special meaning in `'...'` varchar literals.

In PostgreSQL
```
postgres=# SELECT '\', '\\'
postgres-# ;
 ?column? | ?column?
----------+----------
 \        | \\
(1 row)
```

in DataFusion sqllogictest the behavior is the same:

```
query T
SELECT '\'
----
\

query T
SELECT '\\'
----
\\

query T
SELECT '\\\'
----
\\\

query T
SELECT '\\\\'
----
\\\\
```

However, DataFusion CLI behaves differently

```
$ cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.15s
     Running `target/debug/datafusion-cli`
DataFusion CLI v43.0.0
> SELECT '\\';
+-----------+
| Utf8("\") |
+-----------+
| \         |
+-----------+
1 row(s) fetched.
Elapsed 0.049 seconds.

> SELECT '\';  🤔 Invalid statement: SQL error: TokenizerError("unsupported escape char: '\\''")
```

Given that DataFusion CLI is used a lot to test and verify DataFusion's behavior, it's super important for the CLI to behave correctly with respect to its input.

### PR DESCRIPTION
**Pull request by Lordworms**
## Which issue does this PR close?

- Closes #13286

### CODE REVIEW

**Comment by Lordworms** [comment]
I haven't find a good place to add tests, but here is the results
image

**Comment by Lordworms** [comment]
image

**Review by alamb — COMMENTED** [review]
Hi @Lordworms  -- thank you for this PR

I played around with it a bit locally and something still doesn't seem right

Specifically, postgres will treat `\1` like a literal string while this PR still tries to escape it...

```sql
postgres=# select '\1';
 ?column?
----------
 \1
(1 row)
```

But when I try in this PR:
```sql
select 'DataFusion CLI v45.0.0
> select '\';
+-----------+
| Utf8("\") |
+-----------+
| \         |
+-----------+
1 row(s) fetched.
Elapsed 0.013 seconds.

> select '\1';  🤔 Invalid statement: Execution error: Invalid escape sequence: \1
```

**Comment by alamb** [comment]
> I think this is correct, because postgresql treats line breaks, such as \t \0, as plain text, but in the original design of DataFusion, \t, \0 should be escaped, so for \1, since it cannot be escaped, an error will be thrown. I think the original purpose of this issue should be to fix single or multiple backslashes. I am not sure whether we should treat all input as plain text like postgresql.

I think you are right that this is the core question: "should `datafusion-cli` be doing any escaping / unescaping itself?"

If we want to behave like sqllogictest / postgres I think the answer is no. The escaping should happen with the sql supported syntax such as `b'...'` type literals 

Here is a proposed change to this PR that  I think fixes the bug by removing unescaping in datafusion-cli:
- https://github.com/Lordworms/arrow-datafusion/pull/3

I am not sure what I think about this to be honest.

File: datafusion-cli/src/helper.rs [hunk 1]
```diff
@@ -326,15 +326,6 @@ mod tests {
          )?;
         assert!(matches!(result, ValidationResult::Valid(None)));
 
-        // should be invalid
```
Comment (Lordworms) [inline datafusion-cli/src/helper.rs:313]: removed this check since it would throw error later
image

**Comment by findepi** [comment]
> I think you are right that this is the core question: "should `datafusion-cli` be doing any escaping / unescaping itself?"

no, the CLI should not do thos

> If we want to behave like sqllogictest / postgres I think the answer is no. The escaping should happen with the sql supported syntax such as `b'...'` type literals

yes, this should happen during/after SQL AST is built

in particular, there could be different kind of string literals: such that treat `\` as start of an escape sequence, and such that treat `\` as just a single backslash character

File: datafusion-cli/tests/cli_integration.rs [hunk 2]
```diff
@@ -39,6 +39,10 @@ fn init() {
     ["--command", "select 1; select 2;", "--format", "json", "-q"],
     "[{\"Int64(1)\":1}]\n[{\"Int64(2)\":2}]\n"
 )]
+#[case::exec_backslash(
+    ["--file", "tests/data/backslash.txt", "--format", "json", "-q"],
+    "[{\"Utf8(\\\"\\\\\\\")\":\"\\\\\",\"Utf8(\\\"\\\\\\\\\\\")\":\"\\\\\\\\\",\"Utf8(\\\"\\\\\\\\\\\\\\\\\\\\\\\")\":\"\\\\\\\\\\\\\\\\\\\\\",\"Utf8(\\\"dsdsds\\\\\\\\\\\\\\\\\\\")\":\"dsdsds\\\\\\\\\\\\\\\\\",\"Utf8(\\\"\\\\t\\\")\":\"\\\\t\",\"Utf8(\\\"\\\\0\\\")\":\"\\\\0\",\"Utf8(\\\"\\\\n\\\")\":\"\\\\n\"}]\n"
+)]
```
Comment (findepi) [inline datafusion-cli/tests/cli_integration.rs:45]: That's so many backslashes on a single line.
What does it test? How do we know it's really correct?
(when i test's semantics is debatable, it's prone to change later; it's better to have a test that "is obviously correct")

File: datafusion-cli/src/helper.rs [hunk 3]
```diff
@@ -166,40 +154,8 @@ impl Validator for CliHelper {
 
 impl Helper for CliHelper {}
 
-/// Unescape input string from readline.
-///
-/// The data read from stdio will be escaped, so we need to unescape the input before executing the input
-pub fn unescape_input(input: &str) -> datafusion::error::Result<String> {
```
Comment (findepi) [inline datafusion-cli/src/helper.rs:172]: So this function was the source of the bug. Per the comment above, someone had a reason to write it though. Do you maybe know what changed? Like, did we change how we obtain input lines?

File: datafusion-cli/src/helper.rs [hunk 4]
```diff
@@ -310,14 +266,13 @@ mod tests {
          )?;
         assert!(matches!(result, ValidationResult::Valid(None)));
 
-        // should be invalid
         let result = readline_direct(
-             Cursor::new(
-                 r"create external table test stored as csv location 'data.csv' options ('format.delimiter' '\u{07}');"
```
Comment (findepi) [inline datafusion-cli/src/helper.rs:316]: worth keeping this test case?

**Review by findepi — APPROVED** [review]

File: datafusion-cli/src/helper.rs (hunk 3 above)
Comment (alamb) [reply datafusion-cli/src/helper.rs:172]: One thing that might have changed is that sqlparser got much more sophistcated in handling escaping itself / added a bunch of handling for the escaping in the parser (like maybe \u{} style syntax 🤔 )

File: datafusion-cli/src/helper.rs (hunk 4 above)
Comment (Lordworms) [reply datafusion-cli/src/helper.rs:316]: no, the check is to validate  delimiter in create csv files using the unescape function. It will be verified when the external table is created later.

**Comment by alamb** [comment]
To @findepi 's point I am worried about people who used to rely on datafusion-cli escaping

It would be really nice to document how they should escape strings after this change. 

@Lordworms  do you know how to use  escaped strings with datafusion-cli now?

**Review by alamb — APPROVED** [review]
Thanks again @findepi and @Lordworms 

> To @findepi 's point I am worried about people who used to rely on datafusion-cli escaping
> 
> It would be really nice to document how they should escape strings after this change.
> 
> @Lordworms do you know how to use escaped strings with datafusion-cli now?

I did some research and  verified it is possible to use escaped strings with the `E` syntax. I propose updating the docs in this PR:
- https://github.com/apache/datafusion/pull/14934

I'll also add a note to the upgrade guide in 
- https://github.com/apache/datafusion/pull/14891
