### PR TITLE
simplify `array_has` UDF to `InList` expr when haystack is constant

### LINKED ISSUE #14533: `array_has` UDF performance is slow for smaller number of needles
### Describe the bug

When using `array_has` the performance is quite slow when there is a single needle or smaller needle amount to check for.

### To Reproduce

Here's an example:

```
DataFusion CLI v44.0.0
> CREATE TABLE test AS (SELECT substr(md5(i)::text, 1, 32) as haystack FROM generate_series(1, 100000) t(i));
0 row(s) fetched. 
Elapsed 0.015 seconds.

> SELECT * FROM test limit 1;
+----------------------------------+
| haystack                         |
+----------------------------------+
| 7f4b18de3cfeb9b4ac78c381ee2ad278 |
+----------------------------------+
1 row(s) fetched. 
Elapsed 0.005 seconds.
> SELECT count(*) FROM test WHERE haystack = '7f4b18de3cfeb9b4ac78c381ee2ad278';
+----------+
| count(*) |
+----------+
| 1        |
+----------+
1 row(s) fetched. 
Elapsed 0.001 seconds.

> SELECT count(*) FROM test WHERE haystack IN ('7f4b18de3cfeb9b4ac78c381ee2ad278');
+----------+
| count(*) |
+----------+
| 1        |
+----------+
1 row(s) fetched. 
Elapsed 0.002 seconds.

> SELECT count(*) FROM test WHERE haystack = ANY(['7f4b18de3cfeb9b4ac78c381ee2ad278']);
+----------+
| count(*) |
+----------+
| 1        |
+----------+
1 row(s) fetched. 
Elapsed 0.031 seconds.

> SELECT count(*) FROM test WHERE array_has(['7f4b18de3cfeb9b4ac78c381ee2ad278'], haystack);
+----------+
| count(*) |
+----------+
| 1        |
+----------+
1 row(s) fetched. 
Elapsed 0.032 seconds.
```

### Expected behavior

I'd expect that the `array_has` would be able to be pretty performant in this case.

### Additional context

I've actually got an optimization that will convert this into a binary expression limiting it to 10 values.  I'm wondering if there is a path forward to integrate this behaviour into the UDF itself, or if it exists as a separate optimization.

```rust
use datafusion::prelude::Expr;

const ARRAY_ARG_LIMIT: usize = 10;

/// converts `array_has(['val'], column)` into `trace_id = 'val'`
pub fn array_breakout(expr: &Expr) -> Option<Expr> {
    if let Expr::ScalarFunction(scalar_fn) = expr {
        if scalar_fn.name() == "array_has" && scalar_fn.args.len() == 2 {
            let array_exprs = args_from_make_array(&scalar_fn.args[0]);
            let expr_arg = &scalar_fn.args[1];
            if matches!(expr_arg, Expr::Column(_)) && array_exprs.len() <= ARRAY_ARG_LIMIT {
                return Some(
                    array_exprs
                        .iter()
                        .map(|val| val.clone().eq(expr_arg.clone()))
                        .reduce(Expr::or)
                        .unwrap_or_else(|| expr.clone()),
                );
            }
        }
    }

    None
}

fn args_from_make_array(expr: &Expr) -> &[Expr] {
    if let Expr::ScalarFunction(ref scalar_fn) = expr {
        if scalar_fn.name() == "make_array" {
            return &scalar_fn.args;
        }
    }

    &[]
}

#[cfg(test)]
mod tests {
    use arrow_schema::{DataType, Field, Schema};
    use datafusion::{common::DFSchema, prelude::SessionContext, sql::unparser::Unparser};

    use super::array_breakout;

    #[test]
    fn test_array_breakout() {
        let ctx = SessionContext::new();

        let schema = Schema::new(vec![
            Field::new("trace_id", DataType::Utf8, true)
        ]);
        let schema = DFSchema::try_from(schema).unwrap();
        let unparser = Unparser::default().with_pretty(true);

        let tests = [
            (
                "array_has(['0001'], trace_id)",
                Some("'0001' = trace_id")
            ),
            (
                "array_has(['0001', '0002'], trace_id)",
                Some("'0001' = trace_id OR '0002' = trace_id")
            ),
            (
                "array_has(['0001', '0002', '0003', '0004', '0005', '0006', '0007', '0008', '0009', '0010', '0011'], trace_id)",
                None
            )
        ];

        for (input_sql, output_sql) in tests {
            let input_expr = ctx.parse_sql_expr(input_sql, &schema).unwrap();
            let output_expr = array_breakout(&input_expr);

            if let Some(output_sql) = output_sql {
                let output = unparser.expr_to_sql(&output_expr.unwrap()).unwrap().to_string();
                assert_eq!(output, output_sql);
            } else {
                assert!(output_expr.is_none());
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by davidhewitt**
## Which issue does this PR close?

- Closes #14533 

## Rationale for this change

This PR indirectly addresses #14533 not by actually changing the `array_has` evaluation but instead by simplifying it to the equivalent `InList` expression where the haystack is not varying per-row.

The `array_has` udf has to operate row-by-row because it may have a varying haystack. The `InList` expression, on the other hand, can operate in a columnar fashion by evaluating each of the N haystack items for equality against the needle and OR the results. It looks to me list `InList` also supports some kind of `Set` optimization.

## What changes are included in this PR?

Add a `simplify` implementation to `array_has` UDF which will produce an `InList` expr when the haystack is a literal list.

## Are these changes tested?

Yes, see test additions in the diff.

I also reran the original example from #14533 and we see that now the last two statements are now on equivalent performance as the others.

```
> CREATE TABLE test AS (SELECT substr(md5(i)::text, 1, 32) as haystack FROM generate_series(1, 100000) t(i));
0 row(s) fetched. 
Elapsed 0.027 seconds.

> SELECT * FROM test limit 1;
+----------------------------------+
| haystack                         |
+----------------------------------+
| 7f4b18de3cfeb9b4ac78c381ee2ad278 |
+----------------------------------+
1 row(s) fetched. 
Elapsed 0.001 seconds.

> SELECT count(*) FROM test WHERE haystack = '7f4b18de3cfeb9b4ac78c381ee2ad278';
+----------+
| count(*) |
+----------+
| 1        |
+----------+
1 row(s) fetched. 
Elapsed 0.005 seconds.

> SELECT count(*) FROM test WHERE haystack IN ('7f4b18de3cfeb9b4ac78c381ee2ad278');
+----------+
| count(*) |
+----------+
| 1        |
+----------+
1 row(s) fetched. 
Elapsed 0.002 seconds.

> SELECT count(*) FROM test WHERE haystack = ANY(['7f4b18de3cfeb9b4ac78c381ee2ad278']);
+----------+
| count(*) |
+----------+
| 1        |
+----------+
1 row(s) fetched. 
Elapsed 0.001 seconds.

> SELECT count(*) FROM test WHERE array_has(['7f4b18de3cfeb9b4ac78c381ee2ad278'], haystack);
+----------+
| count(*) |
+----------+
| 1        |
+----------+
1 row(s) fetched. 
Elapsed 0.002 seconds.
```

I would be happy to contribute a benchmark, but because this involves first simplifying the UDF expression this looked somewhat nontrivial and I'd welcome advice on where to place it.

## Are there any user-facing changes?

Simplification results will change.

### CODE REVIEW

File: datafusion/functions-nested/src/array_has.rs [hunk 1]
```diff
@@ -121,6 +123,43 @@ impl ScalarUDFImpl for ArrayHas {
...
+                return Ok(ExprSimplifyResult::Simplified(Expr::InList(InList {
+                    expr: Box::new(needle),
+                    list,
+                    negated: false,
+                })));
+            }
+        }
+
+        // TODO: support LargeList / FixedSizeList?
+        // (not supported by `convert_array_to_scalar_vec`)
```
Comment (davidhewitt) [inline datafusion/functions-nested/src/array_has.rs:158]: Input wanted on whether this should be resolved (maybe by handling those data types in `convert_aray_to_scalar_vec`).

Comment (alamb) [reply datafusion/functions-nested/src/array_has.rs:158]: I suggest doing the work in a follow on ticket / PR. So that would mean:
1. Filing a ticket with a reproducer (perhaps modified from https://github.com/apache/datafusion/issues/14533)
2. leaving a TODO with a link to that ticket here

**Review by alamb — COMMENTED** [review]
Thanks @davidhewitt  -- this looks great to me other than needing some end to end .slt tests

Ideally the tests would 
1. Run the queries in https://github.com/apache/datafusion/issues/14533 (or point to where they are already run)
2. Do an `EXPLAIN ...` that shows the rewrite happening

The rationale is to make sure that this code is hooked up correctly when running queries

> It looks to me list InList also supports some kind of Set optimization.

Yes the inlist uses a hash table for larger element needles

File: datafusion/functions-nested/src/array_has.rs (hunk 1 above)
Comment (davidhewitt) [reply datafusion/functions-nested/src/array_has.rs]: Filed as #15389

File: datafusion/sqllogictest/test_files/array.slt [hunk 2]
```diff
@@ -5960,6 +5960,188 @@ true false true false false false true true false false true false true
...
+01)ProjectionExec: expr=[count(Int64(1))@0 as count(*)]
+02)--AggregateExec: mode=Final, gby=[], aggr=[count(Int64(1))]
+03)----CoalescePartitionsExec
+04)------AggregateExec: mode=Partial, gby=[], aggr=[count(Int64(1))]
+05)--------ProjectionExec: expr=[]
+06)----------CoalesceBatchesExec: target_batch_size=8192
+07)------------FilterExec: __common_expr_3@0 = __common_expr_3@0
+08)--------------ProjectionExec: expr=[substr(md5(CAST(value@0 AS Utf8)), 1, 32) as __common_expr_3]
+09)----------------RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=1
+10)------------------LazyMemoryExec: partitions=1, batch_generators=[generate_series: start=1, end=100000, batch_size=8192]
```
Comment (davidhewitt) [inline datafusion/sqllogictest/test_files/array.slt:6143]: I think this is probably #15387

File: datafusion/functions-nested/src/array_has.rs [hunk 3]
```diff
@@ -121,6 +124,52 @@ impl ScalarUDFImpl for ArrayHas {
...
+                    .collect();
+
+                return Ok(ExprSimplifyResult::Simplified(Expr::InList(InList {
+                    expr: Box::new(std::mem::take(needle)),
+                    list,
+                    negated: false,
+                })));
+            }
+        } else if let Expr::ScalarFunction(ScalarFunction { func, args }) = haystack {
+            // make_array has a static set of arguments, so we can pull the arguments out from it
```
Comment (alamb) [inline datafusion/functions-nested/src/array_has.rs:160]: I would expect that during constant evaluation make_array would be turned into a literal so this case would be unecessary

However, you wouldn't observe that simplification happening in unit tests (only in the slt tests when everything was put together)

File: datafusion/sqllogictest/test_files/array.slt [hunk 4]
```diff
@@ -5960,6 +5960,188 @@ true false true false false false true true false false true false true
 #----
 #true false true false false false true true false false true false true
 
+# rewrite various array_has operations to InList where the haystack is a literal list
+# NB that `col in (a, b, c)` is simplified to OR if there are <= 3 elements, so we make 4-element haystack lists
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/array.slt:5964]: 👍

File: datafusion/sqllogictest/test_files/array.slt [hunk 5]
```diff
@@ -5960,6 +5960,188 @@ true false true false false false true true false false true false true
...
+explain with test AS (SELECT substr(md5(i)::text, 1, 32) as needle FROM generate_series(1, 100000) t(i))
+select count(*) from test WHERE needle = ANY(['7f4b18de3cfeb9b4ac78c381ee2ad278', 'a', 'b', 'c']);
+----
+logical_plan
+01)Projection: count(Int64(1)) AS count(*)
+02)--Aggregate: groupBy=[[]], aggr=[[count(Int64(1))]]
+03)----SubqueryAlias: test
+04)------SubqueryAlias: t
+05)--------Projection:
+06)----------Filter: substr(CAST(md5(CAST(tmp_table.value AS Utf8)) AS Utf8), Int64(1), Int64(32)) IN ([Utf8View("7f4b18de3cfeb9b4ac78c381ee2ad278"), Utf8View("a"), Utf8View("b"), Utf8View("c")])
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/array.slt:6011]: that is cool to see

File: datafusion/functions-nested/src/array_has.rs (hunk 3 above)
Comment (alamb) [reply datafusion/functions-nested/src/array_has.rs:160]: I tested removing this case and the slt tests failed like this

```diff
Completed 113 test files in 3 seconds                                                                                                                                 External error: query result mismatch:
[SQL] explain with test AS (SELECT substr(md5(i)::text, 1, 32) as needle FROM generate_series(1, 100000) t(i))
select count(*) from test WHERE array_has([needle], needle);
[Diff] (-expected|+actual)
    logical_plan
    01)Projection: count(Int64(1)) AS count(*)
    02)--Aggregate: groupBy=[[]], aggr=[[count(Int64(1))]]
    03)----SubqueryAlias: test
    04)------SubqueryAlias: t
-   05)--------Projection:
-   06)----------Filter: __common_expr_3 = __common_expr_3
+   05)--------Projection:
+   06)----------Filter: array_has(make_array(__common_expr_3), __common_expr_3)
    07)------------Projection: substr(CAST(md5(CAST(tmp_table.value AS Utf8)) AS Utf8), Int64(1), Int64(32)) AS __common_expr_3
    08)--------------TableScan: tmp_table projection=[value]
    physical_plan
    01)ProjectionExec: expr=[count(Int64(1))@0 as count(*)]
    02)--AggregateExec: mode=Final, gby=[], aggr=[count(Int64(1))]
    03)----CoalescePartitionsExec
    04)------AggregateExec: mode=Partial, gby=[], aggr=[count(Int64(1))]
    05)--------ProjectionExec: expr=[]
    06)----------CoalesceBatchesExec: target_batch_size=8192
-   07)------------FilterExec: __common_expr_3@0 = __common_expr_3@0
+   07)------------FilterExec: array_has(make_array(__common_expr_3@0), __common_expr_3@0)
    08)--------------ProjectionExec: expr=[substr(md5(CAST(value@0 AS Utf8)), 1, 32) as __common_expr_3]
    09)----------------RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=1
    10)------------------LazyMemoryExec: partitions=1, batch_generators=[generate_series: start=1, end=100000, batch_size=8192]
at test_files/array.slt:6120
```

I found that unexpected but don't have time to look into it more now

**Review by alamb — APPROVED** [review]
Thank you @davidhewitt  -- this looks good to me

**Comment by alamb** [comment]
Thanks again @davidhewitt
