### PR TITLE
return absent stats when filters are pushed down

### LINKED ISSUE #12416: TableScanExec return exact stats when it contain's filters
### Describe the bug

I'm working on a project based on datafusion's `ListingTable` and `ParquetExec`. I've made some modifications to enable exact filter pushdown for parquet tables. 

When I execute a statement like `select count(*) from table where Age > 10 limit 10`, I noticed that in the physical plan, `TableScanExec` is replaced with a placeholder, causing the query to directly return the total number of rows in the table. 

Eventually, I found that `AggregateStatistics` was optimizing the query plan using stats, and `ParquetExec::statistics()` was returning stats as follows: `Rows=Exact(390616), Bytes=Absent, [(Col[0]: Min=Exact(Int16(0)) Max=Exact(Int16(55)) Null=Exact(0))]`. 
However, `ParquetExec` contains some filters, so the stats should be inexact or absent. 

Currently, datafusion's `ListingTable` supports inexact filter pushdown, so there would be a `FilterExec` outside the `TableScanExec`, which prevents incorrect optimization by `AggregateStatistics`. But, since filters can still exist within `ParquetExec`, returning exact stats is semantically incorrect.

### To Reproduce

Use the following code and print stats in `ParquetExec::statistics()`
```rust
use arrow::util::pretty::print_batches;
use arrow_schema::DataType;
use datafusion::error::Result;
use datafusion::physical_plan::display::DisplayableExecutionPlan;
use datafusion::physical_plan::{collect, ExecutionPlan};
use datafusion::{
    config::{ConfigField, TableParquetOptions},
    datasource::{file_format::parquet::ParquetFormat, listing::ListingOptions},
    prelude::*,
};
use std::sync::Arc;
use tokio;

#[tokio::main]
async fn main() -> datafusion::error::Result<()> {
    let ctx = SessionContext::new();
    ctx.state_ref()
        .write()
        .config_mut()
        .options_mut()
        .sql_parser
        .enable_ident_normalization = false;
    ctx.state_ref()
        .write()
        .config_mut()
        .options_mut()
        .execution
        .target_partitions = 1;
    let mut opts = TableParquetOptions::default();
    opts.set("pushdown_filters", "true").unwrap();
    let format = ParquetFormat::new().with_options(opts);
    let options = ListingOptions::new(Arc::new(format))
        .with_table_partition_cols(vec![("A".to_owned(), DataType::Int32)]);
    ctx.register_listing_table(
        "hits",
        "/path",
        options,
        None,
        None,
    )
    .await
    .unwrap();

    let pp = plan(&ctx, "select count(*) from hits where Age > 10")
        .await
        .unwrap();
    let rb = collect(pp, ctx.task_ctx()).await.unwrap();
    print_batches(&rb).unwrap();

    Ok(())
}

async fn plan(ctx: &SessionContext, sql: &str) -> Result<Arc<dyn ExecutionPlan>> {
    let now = std::time::Instant::now();
    let lp = Arc::new(ctx.state().create_logical_plan(sql).await?);
    println!("LogicalPlan:\n{:?}", lp);
    let state = ctx.state();
    let lp = state.optimize(&lp).unwrap();
    println!("Optimized LogicalPlan:\n{:?}", lp);
    let pp = state.create_physical_plan(&lp).await.unwrap();
    println!(
        "Plan duration: {}us. Optimized PhysicalPlan:\n{}",
        now.elapsed().as_micros(),
        DisplayableExecutionPlan::new(&*pp).indent(true)
    );
    Ok(pp)
}
```
You can find that `Rows` in stats is `Exact(n)`, but `n` may exceed the actual number of rows returned by ParquetExec, which is semantically incorrect.

### Expected behavior

I suggest adding the following code to the `statistics` method of some TableScanExec implementations

```rust
let stats = if self.pushdown_filters() && self.predicate.is_some() {
    self.projected_statistics.clone().into_inexact()
} else {
    self.projected_statistics.clone()
};
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by waruto210**
## Which issue does this PR close?

Closes #12416.

## Rationale for this change

Fix the bug mentioned in #12416.

## What changes are included in this PR?

Unlike what was mentioned in #12416, I chose to return absent stats because it's hard to know the selectivity of the filters, and also, for filters that can be resolved using only partition cols, there's no need to pushdown them to the TableScanExec, which would otherwise produce useless `unhandled` pruning predicate.

## Are these changes tested?

Yes

### CODE REVIEW

File: datafusion/physical-plan/src/execution_plan.rs [hunk 1]
```diff
@@ -379,6 +379,9 @@ pub trait ExecutionPlan: Debug + DisplayAs + Send + Sync {
     /// Returns statistics for this `ExecutionPlan` node. If statistics are not
     /// available, should return [`Statistics::new_unknown`] (the default), not
     /// an error.
+    ///
+    /// For TableScan executors, which supports filter pushdown, special attention
```
Comment (alamb) [inline datafusion/physical-plan/src/execution_plan.rs:383]: 💯

File: datafusion/core/src/datasource/physical_plan/parquet/mod.rs [hunk 2]
```diff
@@ -739,7 +739,17 @@ impl ExecutionPlan for ParquetExec {
     }
 
     fn statistics(&self) -> Result<Statistics> {
-        Ok(self.projected_statistics.clone())
+        // When filters are pushed down, we have no way of knowing the exact statistics.
+        // Note that pruning predicate is also a kind of filter pushdown.
+        let stats = if self.pruning_predicate.is_some()
+            || self.page_pruning_predicate.is_some()
```
Comment (alamb) [inline datafusion/core/src/datasource/physical_plan/parquet/mod.rs:745]: I think bloom filters should also belong in this list 🤔

File: datafusion/core/src/datasource/listing/table.rs [hunk 3]
```diff
@@ -817,6 +817,20 @@ impl TableProvider for ListingTable {
             .map(|col| Ok(self.table_schema.field_with_name(&col.0)?.clone()))
             .collect::<Result<Vec<_>>>()?;
 
+        // If the filters can be resolved using only partition cols, there is no need to
+        // pushdown it to TableScan, otherwise, `unhandled` pruning predicates will be generated
+        let table_partition_col_names = table_partition_cols
```
Comment (alamb) [inline datafusion/core/src/datasource/listing/table.rs:822]: This makes sense -- but I don't see a test for it. I also feel like this logic might be duplicated elsewhere(maybe the "can push filters code")? 

What would you think about updating the fields on `ListingTableProvider` somehow to reflect this knowledge a bit more centrally?

File: datafusion/core/src/datasource/physical_plan/parquet/mod.rs [hunk 4]
```diff
@@ -739,7 +739,17 @@ impl ExecutionPlan for ParquetExec {
...
+            || (self.predicate.is_some() && self.pushdown_filters())
+        {
+            Statistics::new_unknown(&self.schema())
```
Comment (alamb) [inline datafusion/core/src/datasource/physical_plan/parquet/mod.rs:748]: Rather than discarding all statistics, what do you think about marking any precisions as `Precision::Inexact`?

I am a bit concerned that we would simply discard the statistics entirely in the (very common) case of filter pushdown 🤔

File: datafusion/core/tests/sql/path_partition.rs [hunk 5]
```diff
@@ -491,7 +491,22 @@ async fn parquet_statistics() -> Result<()> {
     // stats for the first col are read from the parquet file
     assert_eq!(stat_cols[0].null_count, Precision::Exact(1));
     // TODO assert partition column stats once implemented (#1186)
-    assert_eq!(stat_cols[1], ColumnStatistics::new_unknown(),);
+    assert_eq!(stat_cols[1], ColumnStatistics::new_unknown());
+
+    //// WITH Filter PushDown to [`ParquetExec`] ////
```
Comment (alamb) [inline datafusion/core/tests/sql/path_partition.rs:496]: 💯  for the test, but it seems somewhat out of place in datafusion/core/tests/sql/path_partition.rs (which is testing partitioned files but this code is relevant to all)

Perhaps we could make a new test that just focused on the statistics for `ParquetExec` with pushdown filters

**Review by alamb — COMMENTED** [review]
Thank you @waruto210  -- I think this is a great start 

I left some comments -- let us know what you think

File: datafusion/core/src/datasource/physical_plan/parquet/mod.rs (hunk 2 above)
Comment (waruto210) [reply datafusion/core/src/datasource/physical_plan/parquet/mod.rs:745]: Bloom filters are used by `pruning_predicate `.

File: datafusion/core/src/datasource/listing/table.rs (hunk 3 above)
Comment (waruto210) [reply datafusion/core/src/datasource/listing/table.rs:822]: I conducted some tests and discovered that filters that can be resolved using only `table_partition_cols` generate `unhandled` predicates when creating `PruningPredicate`,  which causes `statistics()` to be unable to generate exact stats in some cases.

File: datafusion/core/src/datasource/physical_plan/parquet/mod.rs (hunk 4 above)
Comment (waruto210) [reply datafusion/core/src/datasource/physical_plan/parquet/mod.rs:748]: Using `Inexact` is also acceptable. I'm just concerned that when the filter's selectivity is very low, it might lead to wasteful memory allocation.

File: datafusion/core/src/datasource/listing/table.rs (hunk 3 above)
Comment (waruto210) [reply datafusion/core/src/datasource/listing/table.rs:822]: `filters` are passed as parameters to `ListingTable::scan`, so I believe storing `table_partition_col_names` or `filters` in ListingTable has no practical use. Additionally, I think the correctness of this change can be covered by existing tests, such as those in `datafusion/core/tests/sql/path_partition.rs`.

**Comment by waruto210** [comment]
@alamb PTAL

**Review by alamb — APPROVED** [review]
Thanks @waruto210 this looks good to me now

I do think it is worth considering more explicit test coverage for partition column pushdown, but I don't think it is required. 

Thanks again for the contribution

File: datafusion/core/src/datasource/listing/table.rs (hunk 3 above)
Comment (waruto210) [reply datafusion/core/src/datasource/listing/table.rs:824]: Thank you for your suggestion, I've added a new test named `parquet_partition_pruning_filter` in `datafusion/core/tests/sql/path_partition.rs`.

**Comment by alamb** [comment]
Thank you again @waruto210

File: datafusion/core/src/datasource/physical_plan/parquet/mod.rs [hunk 6]
```diff
@@ -741,7 +741,18 @@ impl ExecutionPlan for ParquetExec {
...
     fn statistics(&self) -> Result<Statistics> {
-        Ok(self.projected_statistics.clone())
+        // When filters are pushed down, we have no way of knowing the exact statistics.
+        // Note that pruning predicate is also a kind of filter pushdown.
+        // (bloom filters use `pruning_predicate` too)
+        let stats = if self.pruning_predicate.is_some()
+            || self.page_pruning_predicate.is_some()
+            || (self.predicate.is_some() && self.pushdown_filters())
+        {
+            self.projected_statistics.clone().to_inexact()
```
Comment (Dandandan) [inline datafusion/core/src/datasource/physical_plan/parquet/mod.rs:751]: Shouldn't we make this absent, unless we actually estimate it using pushed down filters? 🤔

Comment (waruto210) [reply datafusion/core/src/datasource/physical_plan/parquet/mod.rs:751]: I think your idea makes sense, but @alamb  seems to prefer using inexact.

Comment (alamb) [reply datafusion/core/src/datasource/physical_plan/parquet/mod.rs:751]: I thought that inexact was the least difference than we had

In terms of actually doing cardinality estimation of filters, I think that is its own very hard challenge -- there is some vestigal stuff in DataFusion, but if we wanted to make it better I think we should add some very simple implementation in DataFusion with an API to extend if/when needed
