### PR TITLE
Fix SMJ Left Anti Join when the join filter is set

### LINKED ISSUE #10380: Sort Merge Join. LeftAnti issues
### Describe the bug

SMJ LeftAnti join returns the wrong result

### To Reproduce

```
#[tokio::test]
    async fn test_anti() -> Result<()> {
        let ctx: SessionContext = SessionContext::new();

        let sql = "set datafusion.optimizer.prefer_hash_join = false;";
        let _ = ctx.sql(sql).await?.collect().await?;

        println!("=============================================================================");
        let sql = "set datafusion.execution.batch_size = 1";
        let _ = ctx.sql(sql).await?.collect().await?;

        let sql = "
            select * from (
            with
            t1 as (
                select 11 a, 12 b),
            t2 as (
                select 11 a, 13 b union all
                select 11 a, 14 b
                )
            select t1.* from t1 where not exists (select 1 from t2 where t2.a = t1.a and t2.b < t1.b)
            ) order by 1, 2;
        ";

        let actual = ctx.sql(sql).await?.collect().await?;
        let expected: Vec<&str> = vec![
            "+----+----+",
            "| a  | b  |",
            "+----+----+",
            "| 11 | 12 |",
            "+----+----+",
        ];
        datafusion_common::assert_batches_eq!(expected, &actual);

        Ok(())
    }
```

### Expected behavior

Test should pass

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by comphead**
## Which issue does this PR close?

Closes #10380.

## Rationale for this change

Fix issues when LeftAnti Join returned nothing when the join filter was set

## What changes are included in this PR?
Handled scenarios for LeftAntiJoin when join filter is set. Output the streaming row(left join side row) only if there is no corresponding filtered match from buffered data(right join side)

### CODE REVIEW

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 1]
```diff
@@ -1181,7 +1189,10 @@ impl SMJStream {
             let filter_columns = if chunk.buffered_batch_idx.is_some() {
                 if matches!(self.join_type, JoinType::Right) {
                     get_filter_column(&self.filter, &buffered_columns, &streamed_columns)
-                } else if matches!(self.join_type, JoinType::LeftSemi) {
+                } else if matches!(
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1192]: I wonder if we have to check (in the lines above) for RightAnti and RightSemi? 🤔

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 2]
```diff
@@ -1397,6 +1416,9 @@ fn get_filter_column(
             .map(|i| buffered_columns[i.index].clone())
             .collect::<Vec<_>>();
 
+        //        dbg!(&left_columns);
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1419]: this looks left over and could probably be removed

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 3]
```diff
@@ -1419,51 +1441,87 @@ fn get_buffered_columns(
...
             }
+            Some((corrected_mask.finish(), filter_matched_indices))
+        }
+        // LeftAnti semantics: return true if for every x in the collection, p(x) is false.
+        // the true(if any) flag needs to be set only once per streaming index
+        // to prevent duplicates in the output
+        JoinType::LeftAnti => {
+            // have we seen a filter match for a streaming index before
+            for i in 0..streamed_indices_length {
+                if mask.value(i) && !seen_as_true {
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1501]: I vaguely remember there are subtle semantics with respect to NULLs and Anti joins. It looks like this doe the right thing (looks for true values in the mask). However i wonder if you also should check if `mask.valid()` as well first ? 

This may not be necessary if mask is always non nullable. I am not sure

**Review by alamb — APPROVED** [review]
Thank you @comphead  -- this looks like an improvement to me. Queries now get correct answers that did not before.

I remember that Anti join semantics are quite subtle, and I am not sure I would catch subtle bugs in my review, but it seems to me that this code is an improvement to what is on main

nice work

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 1 above)
Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:1192]: I have a separate ticket for Right* joins, however I'm not sure how to build a right join on the sql level tbh. I will check it once we have Left* stabilized

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 3 above)
Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:1501]: There was a confusion between 0 and nulls, good point, I'll add it

**Comment by comphead** [comment]
> Thank you @comphead -- this looks like an improvement to me. Queries now get correct answers that did not before.
> 
> I remember that Anti join semantics are quite subtle, and I am not sure I would catch subtle bugs in my review, but it seems to me that this code is an improvement to what is on main
> 
> nice work

Thanks @alamb I have added the basic left anti join test cases to slt file. However once we resolve the https://github.com/apache/datafusion/issues/10659 it gonna be easier to find issues then we cannot imagine right away

**Comment by alamb** [comment]
Let's keep iterating on this code in subsequent PRs

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 4]
```diff
@@ -1419,51 +1438,87 @@ fn get_buffered_columns(
...
+                    && streamed_indices.value(i) != streamed_indices.value(i + 1)
+                {
+                    seen_as_true = false;
+                }
             }
+            Some((corrected_mask.finish(), filter_matched_indices))
+        }
+        // LeftAnti semantics: return true if for every x in the collection, p(x) is false.
+        // the true(if any) flag needs to be set only once per streaming index
+        // to prevent duplicates in the output
```
Comment (viirya) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1494]: It is unclear what `p(x)` is as there is no such variable. You can say "join filter" instead of a obscure term.

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 5]
```diff
@@ -1419,51 +1438,87 @@ fn get_buffered_columns(
...
+                if i < streamed_indices_length - 1
+                    && streamed_indices.value(i) != streamed_indices.value(i + 1)
+                {
+                    seen_as_true = false;
+                }
             }
+            Some((corrected_mask.finish(), filter_matched_indices))
+        }
+        // LeftAnti semantics: return true if for every x in the collection, p(x) is false.
+        // the true(if any) flag needs to be set only once per streaming index
```
Comment (viirya) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1493]: "the true(if any) flag" -> `seen_as_true` flag. We should keep the comment as direct and clear as possible.

**Comment by comphead** [comment]
Thanks @alamb and @viirya I'll address all of the comments in followup PR

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 6]
```diff
@@ -1419,51 +1438,87 @@ fn get_buffered_columns(
...
-            // if switched to next streaming index(e.g. from 0 to 1, or from 1 to 2), we reset seen_as_true flag
-            if i < streamed_indices_length - 1
-                && streamed_indices.value(i) != streamed_indices.value(i + 1)
-            {
-                seen_as_true = false;
+                // if switched to next streaming index(e.g. from 0 to 1, or from 1 to 2), we reset seen_as_true flag
+                if (i < streamed_indices_length - 1
+                    && streamed_indices.value(i) != streamed_indices.value(i + 1))
+                    || (i == streamed_indices_length - 1
+                        && *scanning_buffered_batch_idx == buffered_batches_len - 1)
```
Comment (viirya) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1507]: The second condition is not in the above comment.

Comment (viirya) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:1507]: Hmm, the second condition is for the last index in `streamed_indices` and last buffered batch. But in last buffered batch, there are many buffered indices. It is possible we are in the last buffered batch, but we still have more buffered indices to process. Isn't this put a value into `corrected_mask` too early so it could be incorrect?

Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:1507]: > Hmm, the second condition is for the last index in `streamed_indices` and last buffered batch. But in last buffered batch, there are many buffered indices. It is possible we are in the last buffered batch, but we still have more buffered indices to process. Isn't this put a value into `corrected_mask` too early so it could be incorrect?

Good point, I'll check that

Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:1507]: https://github.com/apache/datafusion/pull/10784
