### PR TITLE
fix: impl `handle_child_pushdown_result` for `SortExec`

### LINKED ISSUE #21526: filter not pushdown through sort in FilterPushdown
### Describe the bug

for the physical plan like below
```
FilterExec: log@1 LIKE %datafusion%, projection=[_timestamp@0]
  SortExec: expr=[_timestamp@0 DESC NULLS LAST], preserve_partitioning=[true]
    DataSourceExec: partitions=1, partition_sizes=[1]
```
then i try use `FilterPushdown` to pushdown the filter under the sort, but current not work
After FilterPushdown:
```
FilterExec: log@1 LIKE %datafusion%, projection=[_timestamp@0]
  SortExec: expr=[_timestamp@0 DESC NULLS LAST], preserve_partitioning=[true]
    DataSourceExec: partitions=1, partition_sizes=[1]
```

### To Reproduce

```rust
use std::sync::Arc;

use arrow::array::{RecordBatch, StringArray};
use arrow::compute::SortOptions;
use arrow::datatypes::{DataType, Field, Schema};
use datafusion::catalog::memory::MemorySourceConfig;
use datafusion::common::config::ConfigOptions;
use datafusion::physical_expr::expressions::{col, like, lit};
use datafusion::physical_expr_common::sort_expr::{LexOrdering, PhysicalSortExpr};
use datafusion::physical_optimizer::PhysicalOptimizerRule;
use datafusion::physical_optimizer::filter_pushdown::FilterPushdown;
use datafusion::physical_plan::displayable;
use datafusion::physical_plan::filter::FilterExecBuilder;
use datafusion::physical_plan::sorts::sort::SortExec;

/// Constructs and executes a physical plan equivalent to:
///
/// ```text
///   FilterExec: log@1 LIKE %datafusion%, projection=[_timestamp@0]
///     SortExec: expr=[_timestamp@0 DESC NULLS LAST], preserve_partitioning=[true]
///       DataSourceExec (MemoryExec): projection=[_timestamp, log]
/// ```
#[tokio::main]
async fn main() {
    let schema = Arc::new(Schema::new(vec![
        Field::new("_timestamp", DataType::Utf8, false),
        Field::new("log", DataType::Utf8, false),
    ]));

    let batch1 = RecordBatch::try_new(
        schema.clone(),
        vec![
            Arc::new(StringArray::from(vec!["2026-04-09T02:00:00Z"])),
            Arc::new(StringArray::from(vec!["starting datafusion query engine"])),
        ],
    )
    .unwrap();

    // DataSourceExec (MemoryExec): 1 partitions, projection=[_timestamp, log]
    let memory_exec =
        MemorySourceConfig::try_new_exec(&[vec![batch1]], schema.clone(), None).unwrap();

    // SortExec: expr=[_timestamp@0 DESC NULLS LAST], preserve_partitioning=[true]
    let sort_expr = PhysicalSortExpr::new(
        col("_timestamp", &schema).unwrap(),
        SortOptions {
            descending: true,
            nulls_first: false,
        },
    );
    let lex_ordering = LexOrdering::new(vec![sort_expr]).unwrap();
    let sort_exec = Arc::new(
        SortExec::new(lex_ordering, memory_exec).with_preserve_partitioning(true),
    );

    // FilterExec: log@1 LIKE %datafusion%, projection=[_timestamp@0], fetch=10
    let like_predicate = like(
        false, // not negated
        false, // case sensitive
        col("log", &schema).unwrap(),
        lit("%datafusion%"),
        &schema,
    )
    .unwrap();

    let filter_exec = Arc::new(
        FilterExecBuilder::new(like_predicate, sort_exec)
            .apply_projection(Some(vec![0])) // projection=[_timestamp@0]
            .unwrap()
            .build()
            .unwrap(),
    );

    // Print the physical plan
    let display = displayable(filter_exec.as_ref());
    println!("Physical plan:\n{}", display.indent(true));

    // Run filter pushdown optimization and print the optimized plan
    let config = ConfigOptions::default();
    let optimized_plan = FilterPushdown::new()
        .optimize(filter_exec.clone(), &config)
        .unwrap();
    let optimized_display = displayable(optimized_plan.as_ref());
    println!("After FilterPushdown:\n{}", optimized_display.indent(true));
}

```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by haohuaijin**
## Which issue does this PR close?

- Closes #21526.

## Rationale for this change

`FilterPushdown` does not push filters through `SortExec` because `SortExec` lacks an implementation of `handle_child_pushdown_result`. When a `FilterExec` sits above a plain `SortExec` (no fetch), the filter can safely be moved below the sort without changing semantics, since sorting preserves all rows. 

## What changes are included in this PR?

Implemented `handle_child_pushdown_result` for `SortExec` in `datafusion/physical-plan/src/sorts/sort.rs`:
   - For plain `SortExec` (no fetch) in the `Pre` phase: any filters not absorbed by the child are collected into a new `FilterExec` inserted between the `SortExec` and its child.
   - For `SortExec` with fetch (TopK) or non-`Pre` phases: filters are not absorbed, preserving correct TopK semantics where filtering after limiting would change results.

## Are these changes tested?

Added comprehensive tests in `datafusion/core/tests/physical_optimizer/filter_pushdown.rs` covering:
   - Filter pushdown through sort into a scan that supports pushdown
   - Filter pushdown through sort when scan does NOT support pushdown (FilterExec inserted between sort and scan)
   - Multiple conjunctive filters pushed through sort
   - Filter NOT pushed through sort with fetch (TopK)
   - Filter with projection pushed through sort
   - Filter pushdown preserving the `preserve_partitioning` flag
   - Filter with fetch limit propagated to SortExec (TopK conversion)

and one test case `test_filter_pushdown_through_sort_with_projection` for use LogicalPlanBuilder to reproduce.
not able to use sql to reproduce due to https://github.com/apache/datafusion/issues/15886

### CODE REVIEW

**Comment by haohuaijin** [comment]
the reproduce result in #21526, for this pr
```
Physical plan:
FilterExec: log@1 LIKE %datafusion%, projection=[_timestamp@0]
  SortExec: expr=[_timestamp@0 DESC NULLS LAST], preserve_partitioning=[true]
    DataSourceExec: partitions=1, partition_sizes=[1]

After FilterPushdown:
ProjectionExec: expr=[_timestamp@0 as _timestamp]
  SortExec: expr=[_timestamp@0 DESC NULLS LAST], preserve_partitioning=[true]
    FilterExec: log@1 LIKE %datafusion%
      DataSourceExec: partitions=1, partition_sizes=[1]
```

**Comment by haohuaijin** [comment]
cc @alamb @adriangb do you have time take a look 🙏

File: datafusion/core/tests/physical_optimizer/filter_pushdown.rs [hunk 1]
```diff
@@ -5146,3 +5150,350 @@ async fn test_hashjoin_dynamic_filter_pushdown_left_semi_join() {
     "
     );
 }
+
+// ==== Filter pushdown through SortExec tests ====
+
+/// FilterExec above a plain SortExec (no fetch) should be pushed below it.
+/// The scan supports pushdown, so the filter lands in the DataSourceExec.
+#[test]
```
Comment (adriangb) [inline datafusion/core/tests/physical_optimizer/filter_pushdown.rs:3054]: Can we add these as SLT tests instead?

File: datafusion/physical-plan/src/sorts/sort.rs [hunk 2]
```diff
@@ -1424,6 +1426,50 @@ impl ExecutionPlan for SortExec {
...
+    fn handle_child_pushdown_result(
+        &self,
+        phase: FilterPushdownPhase,
+        child_pushdown_result: ChildPushdownResult,
+        _config: &datafusion_common::config::ConfigOptions,
+    ) -> Result<FilterPushdownPropagation<Arc<dyn ExecutionPlan>>> {
+        // Only absorb filters in Pre phase for a plain sort (no fetch).
+        // A sort with fetch (TopK) must not accept filters: reordering
+        // filter vs. limit would change semantics.
+        if phase != FilterPushdownPhase::Pre || self.fetch.is_some() {
```
Comment (adriangb) [inline datafusion/physical-plan/src/sorts/sort.rs]: Could you explain why `FilterPushdownPhase::Post` should not be allowed, maybe with examples of where it would be incorrect?

File: datafusion/physical-plan/src/sorts/sort.rs [hunk 3]
```diff
@@ -1424,6 +1426,50 @@ impl ExecutionPlan for SortExec {
...
+        let new_sort = Arc::new(
+            SortExec::new(self.expr.clone(), new_child)
+                .with_fetch(self.fetch())
+                .with_preserve_partitioning(self.preserve_partitioning()),
+        ) as Arc<dyn ExecutionPlan>;
+
+        Ok(FilterPushdownPropagation {
+            filters: vec![PushedDown::Yes; child_pushdown_result.parent_filters.len()],
+            updated_node: Some(new_sort),
+        })
```
Comment (adriangb) [inline datafusion/physical-plan/src/sorts/sort.rs:1479]: Swapping the order from `FilterExec -> SortExec` to `SortExec -> FilterExec` makes sense to me 👍🏻

File: datafusion/core/tests/physical_optimizer/filter_pushdown.rs (hunk 1 above)
Comment (haohuaijin) [reply datafusion/core/tests/physical_optimizer/filter_pushdown.rs:3054]: due to 
- https://github.com/apache/datafusion/issues/15886 

the subquery's order by is removed by our sql parser layer, so i can't reproduce use sql

File: datafusion/physical-plan/src/sorts/sort.rs (hunk 2 above)
Comment (haohuaijin) [reply datafusion/physical-plan/src/sorts/sort.rs]: Good question, my initial though was that the swap of sort and filter is unrelated to dynamic filters, so I only do swap for pre pahse. but today when i reconsider this part, i find one incorrect example. i added this example in [10f1462](https://github.com/apache/datafusion/pull/21527/commits/10f14626f56c49da40d982d5382436f436c4cb9b)

if i remove the `phase != FilterPushdownPhase::Pre`, the result will like below, we insert the dynamic filter under the sort, before the datasource if datasource do not accept dynamic filter, 
```rust
    insta::assert_snapshot!(
        OptimizationTest::new(
            Arc::clone(&plan),
            FilterPushdown::new_post_optimization(),
            true
        ),
        @r"
    OptimizationTest:
      input:
        - HashJoinExec: mode=CollectLeft, join_type=Inner, on=[(a@0, a@0), (b@1, b@1)]
        -   DataSourceExec: file_groups={1 group: [[test.parquet]]}, projection=[a, b], file_type=test, pushdown_supported=true
        -   SortExec: expr=[a@0 ASC], preserve_partitioning=[false]
        -     DataSourceExec: file_groups={1 group: [[test.parquet]]}, projection=[a, b], file_type=test, pushdown_supported=false
      output:
        Ok:
          - HashJoinExec: mode=CollectLeft, join_type=Inner, on=[(a@0, a@0), (b@1, b@1)]
          -   DataSourceExec: file_groups={1 group: [[test.parquet]]}, projection=[a, b], file_type=test, pushdown_supported=true
          -   SortExec: expr=[a@0 ASC], preserve_partitioning=[false]
          -     FilterExec: DynamicFilter [ empty ]
          -       DataSourceExec: file_groups={1 group: [[test.parquet]]}, projection=[a, b], file_type=test, pushdown_supported=false
    "
    );
```

File: datafusion/core/tests/physical_optimizer/filter_pushdown.rs (hunk 1 above)
Comment (haohuaijin) [reply datafusion/core/tests/physical_optimizer/filter_pushdown.rs:3054]: i submit a pr to add the config https://github.com/apache/datafusion/pull/21614

**Comment by haohuaijin** [comment]
Thanks for your reviews @adriangb , i replyed for your comment.

File: datafusion/physical-plan/src/sorts/sort.rs (hunk 2 above)
Comment (adriangb) [reply datafusion/physical-plan/src/sorts/sort.rs]: Is that a problem?

Comment (haohuaijin) [reply datafusion/physical-plan/src/sorts/sort.rs]: not a problem, but current dynamic filter mostly integrated with `DataSourceExec`, and I’m not sure about the impact of this change. in theory, it can improve performance.

if you think ok, i can remove it.

Comment (adriangb) [reply datafusion/physical-plan/src/sorts/sort.rs]: Yeah I think we shouldn't do special handling if we don't need to.

Comment (haohuaijin) [reply datafusion/physical-plan/src/sorts/sort.rs]: done, removed in [e06bdc2](https://github.com/apache/datafusion/pull/21527/commits/e06bdc26f018e2a62ddba44c514901dc4555bbe0), ~but it affect some test case, solving it~, solved

Comment (haohuaijin) [reply datafusion/physical-plan/src/sorts/sort.rs]: update some .slt test case in [5c78f98](https://github.com/apache/datafusion/pull/21527/commits/5c78f98afacb0f3dde74a603abebbff972328f3e)

File: datafusion/sqllogictest/test_files/joins.slt [hunk 4]
```diff
@@ -4463,7 +4473,8 @@ physical_plan
 04)------FilterExec: b@1 > 3, projection=[a@0]
 05)--------DataSourceExec: partitions=2, partition_sizes=[1, 1]
 06)----SortExec: expr=[c@2 DESC NULLS LAST], preserve_partitioning=[true]
-07)------DataSourceExec: partitions=2, partition_sizes=[1, 1]
+07)------FilterExec: DynamicFilter [ empty ]
```
Comment (adriangb) [inline datafusion/sqllogictest/test_files/joins.slt:4476]: I’m curious why there aren’t being pushed down into the scan

Comment (haohuaijin) [reply datafusion/sqllogictest/test_files/joins.slt:4476]: the table is memory table, do not allow filter pushdown

Comment (adriangb) [reply datafusion/sqllogictest/test_files/joins.slt:4476]: Makes sense. I think it would be valuable to have some tests with a parquet source where the dynamic filter is pushed through.

Comment (haohuaijin) [reply datafusion/sqllogictest/test_files/joins.slt:4476]: make sense, added in [84912f5](https://github.com/apache/datafusion/pull/21527/commits/84912f5560560c2d0085daa9d9c46af9d55102a1)

File: datafusion/sqllogictest/test_files/dynamic_filter_pushdown_config.slt [hunk 5]
```diff
@@ -316,6 +316,56 @@ WHERE r.id IN (SELECT l.id FROM left_parquet l);
...
+04)------TableScan: left_parquet projection=[id, data]
+05)----SubqueryAlias: __correlated_sq_1
+06)------SubqueryAlias: r
+07)--------TableScan: right_parquet projection=[id]
+physical_plan
+01)HashJoinExec: mode=CollectLeft, join_type=RightSemi, on=[(id@0, id@0)]
+02)--DataSourceExec: file_groups={1 group: [[WORKSPACE_ROOT/datafusion/sqllogictest/test_files/scratch/dynamic_filter_pushdown_config/join_right.parquet]]}, projection=[id], file_type=parquet
+03)--SortExec: expr=[data@1 DESC], preserve_partitioning=[false]
+04)----FilterExec: DynamicFilter [ empty ]
+05)------DataSourceExec: file_groups={1 group: [[WORKSPACE_ROOT/datafusion/sqllogictest/test_files/scratch/dynamic_filter_pushdown_config/join_left.parquet]]}, projection=[id, data], file_type=parquet, predicate=DynamicFilter [ empty ]
```
Comment (haohuaijin) [inline datafusion/sqllogictest/test_files/dynamic_filter_pushdown_config.slt:341]: the `DataSourceExec's` `DynamicFilter` is apply to row group stats

**Review by adriangb — APPROVED** [review]
Thanks LGTM!
