### PR TITLE
fix: update schema's data type for `LogicalPlan::Values` after placeholder substitution

### LINKED ISSUE #18102: `SubqueryAlias`, `Values`, and/or `EmptyRelation` have incorrect schemas after replacing `Placeholder` values
### Describe the bug

When trying to bind parameters and execute queries like `"SELECT a, b FROM (VALUES ($1, $2)) AS t(a, b)"` and `"SELECT $1, $2"`, I get mismatched schemas and/or an error when I try to execute the query.

I think this is because the SubqueryAlias, Values, and/or EmptyRelation both cache their schema and this is not updated when updating parameter values. (There may be other logical plan items that cache their schemas too)

### To Reproduce

For SubqueryAlias:

```rust
let df = ctx.sql("SELECT a, b FROM (VALUES ($1, $2)) AS t(a, b)").await?;
let df_with_params_replaced = df.with_param_values(vec![
    ScalarValue::UInt32(Some(1)),
    ScalarValue::Utf8(Some("foofy".to_string())),
])?;
dbg!(df_with_params_replaced.clone().schema().as_arrow());
dbg!(df_with_params_replaced.collect().await?[0].schema());
#> Error: ArrowError(InvalidArgumentError("column types must match schema types, expected Null but found UInt32 at column index 0"), Some(""))
```

For EmptyRelation (mismatched schemas but execution works):

```rust
let df = ctx.sql("SELECT $1, $2").await?;
let df_with_params_replaced = df.with_param_values(vec![
    ScalarValue::UInt32(Some(1)),
    ScalarValue::Utf8(Some("foofy".to_string())),
])?;
dbg!(df_with_params_replaced.clone().schema().as_arrow());
dbg!(df_with_params_replaced.collect().await?[0].schema());
```

<details>

```
[datafusion/core/tests/sql/select.rs:333:5] df_with_params_replaced.clone().schema().as_arrow() = Schema {
    fields: [
        Field {
            name: "$1",
            data_type: Null,
            nullable: true,
            dict_id: 0,
            dict_is_ordered: false,
            metadata: {},
        },
        Field {
            name: "$2",
            data_type: Null,
            nullable: true,
            dict_id: 0,
            dict_is_ordered: false,
            metadata: {},
        },
    ],
    metadata: {},
}
[datafusion/core/tests/sql/select.rs:334:5] df_with_params_replaced.collect().await?[0].schema() = Schema {
    fields: [
        Field {
            name: "$1",
            data_type: UInt32,
            nullable: false,
            dict_id: 0,
            dict_is_ordered: false,
            metadata: {},
        },
        Field {
            name: "$2",
            data_type: Utf8,
            nullable: false,
            dict_id: 0,
            dict_is_ordered: false,
            metadata: {},
        },
    ],
    metadata: {},
}
```

</details>

### Expected behavior

I expected the schema and generated batches to match and the queries to execute without error.

### Additional context

Encountered whist writing tests for https://github.com/apache/datafusion/pull/17986

SubqueryAlias:

https://github.com/apache/datafusion/blob/7c3b0d0a68d89ba0ac079c7d9adaa3d52ece1c39/datafusion/expr/src/logical_plan/plan.rs#L2223-L2234

Values:

https://github.com/apache/datafusion/blob/7c3b0d0a68d89ba0ac079c7d9adaa3d52ece1c39/datafusion/expr/src/logical_plan/plan.rs#L2106-L2115

EmptyRelation:

https://github.com/apache/datafusion/blob/7c3b0d0a68d89ba0ac079c7d9adaa3d52ece1c39/datafusion/expr/src/logical_plan/plan.rs#L2049-L2058

Replacing Parameters:

https://github.com/apache/datafusion/blob/7c3b0d0a68d89ba0ac079c7d9adaa3d52ece1c39/datafusion/expr/src/logical_plan/plan.rs#L1448-L1478

### PR DESCRIPTION
**Pull request by dqkqd**
## Which issue does this PR close?

- Closes #18102.

## Rationale for this change

This prepare statements below (no type declaration) fails to execute.
```sql
DataFusion CLI v51.0.0
> PREPARE my_plan AS SELECT a, b FROM (VALUES ($1, $2)) AS t(a, b);
0 row(s) fetched.
Elapsed 0.005 seconds.

> EXECUTE my_plan(1, 2);
Arrow error: Invalid argument error: column types must match schema types, expected Null but found Int64 at column index 0
>
```

To make it works, schema's data type should be updated after replacing parameters.
But calling `recompute_schema` alone does not suffice because we skip recomputing schema for `LogicalPlan::Values`:
https://github.com/apache/datafusion/blob/97af468f3da63582f4bacef7d0d1fba4313aa7c4/datafusion/expr/src/logical_plan/plan.rs#L635-L638

## What changes are included in this PR?

- Update schema for `LogicalPlan::Values` manually.

## Are these changes tested?

Yes.

## Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by dqkqd** [comment]
@Jefffrey would you please review this.

**Review by Jefffrey — APPROVED** [review]

File: datafusion/expr/src/logical_plan/plan.rs [hunk 1]
```diff
@@ -1472,13 +1472,24 @@ impl LogicalPlan {
...
-            // always recompute the schema to ensure the changed in the schema's field should be
-            // poplulated to the plan's parent
-            .map_data(|plan| plan.recompute_schema())
+            .map_data(|plan| plan.update_schema_data_type())
         })
         .map(|res| res.data)
     }
 
+    /// Recompute schema fields' data type after replacing params, ensuring fields data type can be
+    /// updated according to the new parameters.
```
Comment (martin-g) [inline datafusion/expr/src/logical_plan/plan.rs:1481]: nit: I think the docstring could be more explicit why this method is needed. E.g. something like:
```
/// Recomputes schema fields' data type after replacing params, ensuring fields' data type can be
/// updated according to the new parameters. Unlike `recompute_schema()`, this method rebuilds
/// VALUES plans entirely to properly infer types from literal values after placeholder substitution.
```
This way the "FIXME" below could be removed.

Comment (martin-g) [reply datafusion/expr/src/logical_plan/plan.rs:1481]: Or the idea of the "FIXME" is to move this logic to `recompute_schema()` one day ?! If YES then better file an issue for that

Comment (dqkqd) [reply datafusion/expr/src/logical_plan/plan.rs:1481]: Thanks @martin-g. I will update it later today

Comment (dqkqd) [reply datafusion/expr/src/logical_plan/plan.rs:1481]: I updated the docstring, but I want to keep the comment to make it clear why `recompute_schema` shouldn't be called for `LogicalPlan::Values`.

**Comment by Jefffrey** [comment]
Thanks @dqkqd  & @martin-g
