### PR TITLE
Use partial aggregation schema for spilling to avoid column mismatch in GroupedHashAggregateStream

### LINKED ISSUE #13949: Schema error when spilling with multiple aggregations
### Describe the bug

There is an issue when using multiple aggregations and triggering a spill in a `GroupedHashAggregateStream`.

A query like `SELECT MIN(b), MAX(b) FROM table GROUP BY a` results in an error
```
ArrowError(InvalidArgumentError("number of columns(3) must match number of fields(2) in schema"), None)
```

The problematic schema is captured here: https://github.com/apache/datafusion/blob/9b5995fa024d95c19e1270447e13f3c9dd428c69/datafusion/physical-plan/src/aggregates/row_hash.rs#L967-L969
And the error gets thrown from `emit` here: https://github.com/apache/datafusion/blob/9b5995fa024d95c19e1270447e13f3c9dd428c69/datafusion/physical-plan/src/aggregates/row_hash.rs#L950
It takes the schema of the input batch and then uses that schema for the intermediate aggregate data to spill to disk. These schemas are clearly not going to match, but I can't quite grok where exactly things have gone wrong.

### To Reproduce

Below is a minimal example which should be analogous to a query like `SELECT MIN(b), MAX(b) FROM table GROUP BY a`. The `batch_size` and memory pool size are set small to trigger a spill.

```rust
use arrow::array::{Float64Array, RecordBatch, UInt32Array};
use arrow_schema::{DataType, Field, Schema};
use datafusion::execution::runtime_env::RuntimeEnvBuilder;
use datafusion::functions_aggregate::min_max::{max_udaf, min_udaf};
use datafusion::{
    execution::{memory_pool::FairSpillPool, TaskContext},
    physical_expr::aggregate::AggregateExprBuilder,
    physical_plan::{
        aggregates::{AggregateExec, AggregateMode, PhysicalGroupBy},
        common,
        expressions::col,
        memory::MemoryExec,
        udaf::AggregateFunctionExpr,
        ExecutionPlan,
    },
    prelude::SessionConfig,
};
use datafusion_common::Result;
use std::sync::Arc;

#[tokio::test]
async fn reproduce_spill_schema_error() -> Result<()> {
    let schema = Arc::new(Schema::new(vec![
        Field::new("a", DataType::UInt32, false),
        Field::new("b", DataType::Float64, false),
    ]));

    let batches = vec![
        RecordBatch::try_new(
            schema.clone(),
            vec![
                Arc::new(UInt32Array::from(vec![2, 3, 4, 4])),
                Arc::new(Float64Array::from(vec![1.0, 2.0, 3.0, 4.0])),
            ],
        )?,
        RecordBatch::try_new(
            schema.clone(),
            vec![
                Arc::new(UInt32Array::from(vec![2, 3, 3, 4])),
                Arc::new(Float64Array::from(vec![1.0, 2.0, 3.0, 4.0])),
            ],
        )?,
    ];
    let plan: Arc<dyn ExecutionPlan> =
        Arc::new(MemoryExec::try_new(&[batches], schema.clone(), None)?);

    let grouping_set = PhysicalGroupBy::new(
        vec![(col("a", &schema)?, "a".to_string())],
        vec![],
        vec![vec![false]],
    );

    let aggregates: Vec<Arc<AggregateFunctionExpr>> = vec![
        Arc::new(
            AggregateExprBuilder::new(min_udaf(), vec![col("b", &schema)?])
                .schema(schema.clone())
                .alias("MIN(b)")
                .build()?,
        ),
        Arc::new(
            AggregateExprBuilder::new(max_udaf(), vec![col("b", &schema)?])
                .schema(schema.clone())
                .alias("MAX(b)")
                .build()?,
        ),
    ];

    let single_aggregate = Arc::new(AggregateExec::try_new(
        AggregateMode::Single,
        grouping_set,
        aggregates,
        vec![None, None],
        plan,
        schema.clone(),
    )?);

    let batch_size = 2;
    let memory_pool = Arc::new(FairSpillPool::new(1600));
    let task_ctx = Arc::new(
        TaskContext::default()
            .with_session_config(SessionConfig::new().with_batch_size(batch_size))
            .with_runtime(Arc::new(
                RuntimeEnvBuilder::new()
                    .with_memory_pool(memory_pool)
                    .build()?,
            )),
    );

    let _result =
        common::collect(single_aggregate.execute(0, Arc::clone(&task_ctx))?).await?;
    Ok(())
}
```

### Expected behavior

I expect the test to complete successfully.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kosiew**
## Which issue does this PR close?

Closes #13949.

## Rationale for this change

When an aggregation operator spills intermediate (partial) state to disk, it needs a schema that includes both the group-by columns and partial-aggregator columns (e.g., partial sums, counts, etc.). Previously, the code used the original input schema for spilling, which does not match the additional columns representing aggregator states. As a result, reading back the spilled data caused a mismatch error:

```
ArrowError(InvalidArgumentError(
  "number of columns(3) must match number of fields(2) in schema"
))
```

This PR addresses that by introducing a partial aggregation schema that combines group columns and aggregator state columns, ensuring consistency when spilling and later reading the spilled data.

## What changes are included in this PR?

1. A new helper function, build_partial_agg_schema(), creates a partial schema by merging:

- Group-by fields
- Each aggregator’s internal “state fields”

2. The aggregate operator is updated to use this partial schema when spilling or merging spilled data rather than the original (input) schema, which fixes the column mismatch error.

## Are these changes tested?

Yes

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/core/src/dataframe/mod.rs [hunk 1]
```diff
@@ -2743,6 +2753,110 @@ mod tests {
...
+                .with_runtime(Arc::new(
+                    RuntimeEnvBuilder::new()
+                        .with_memory_pool(memory_pool)
+                        .build()?,
+                )),
+        );
+
+        let result =
+            common::collect(single_aggregate.execute(0, Arc::clone(&task_ctx))?).await?;
+
```
Comment (2010YOUY01) [inline datafusion/core/src/dataframe/mod.rs:2833]: I suggest to add an assertion here to make sure spilling actually happened for certain test cases like:
```rust
        let metrics = single_aggregate.metrics();
        // ...and assert some metrics inside like 'spill count' is > 0
```

**Review by 2010YOUY01 — COMMENTED** [review]
Thank you. I found the fix easy to follow 😄, and the change makes sense to me.

I have a suggestion to improve test coverage:
Since `min/max` only has one intermediate aggregate state (partial min/max), we should also test aggregate functions that produce more than one intermediate state, like `avg` (partial sum and count).
Duplicating the existing test and modifying one of the aggregate functions to avg should be sufficient.

File: datafusion/core/src/dataframe/mod.rs (hunk 1 above)
Comment (kosiew) [reply datafusion/core/src/dataframe/mod.rs:2838]: Thanks @2010YOUY01 for the review and suggestions.
I have implemented both.

File: datafusion/core/src/dataframe/mod.rs [hunk 2]
```diff
@@ -2743,6 +2754,143 @@ mod tests {
         Ok(())
     }
 
+    // test for https://github.com/apache/datafusion/issues/13949
+    async fn run_test_with_spill_pool_if_necessary(
```
Comment (korowa) [inline datafusion/core/src/dataframe/mod.rs:2758]: I suppose it'll be better to move this test to other aggregate tests in `datafusion/physical-plan/src/mod.rs`

File: datafusion/physical-plan/src/aggregates/row_hash.rs [hunk 3]
```diff
@@ -522,7 +527,7 @@ impl GroupedHashAggregateStream {
         let spill_state = SpillState {
             spills: vec![],
             spill_expr,
-            spill_schema: Arc::clone(&agg_schema),
+            spill_schema: partial_agg_schema,
```
Comment (korowa) [inline datafusion/physical-plan/src/aggregates/row_hash.rs:530]: It seems like the issue was related only to `AggregateMode::Single[Partitioned]` cases, since for both Final and FinalPartitioned, there is a [reassignment](https://github.com/apache/datafusion/blob/487b952cf1a748cc79724638f13e66761a6665e2/datafusion/physical-plan/src/aggregates/row_hash.rs#L969) right before spilling (the new value is a schema for Partial output which is exactly group_by + state fields). Perhaps we can remove this reassignment now and rely on original spill_schema value set on stream creation (before removing it, we need to ensure that spill schema will be equal to intermediate result schema for any aggregation mode which supports spilling)?

File: datafusion/physical-plan/src/aggregates/row_hash.rs [hunk 4]
```diff
@@ -802,6 +807,45 @@ impl RecordBatchStream for GroupedHashAggregateStream {
...
+///
+/// Therefore, when we spill these intermediate states or pass them to another
+/// aggregation operator, we must use a schema that includes both the group
+/// columns **and** the partial-state columns. Otherwise, using the original input
+/// schema to read partial states will result in a column-count mismatch error.
+///
+/// This helper function constructs such a schema:
+/// `[group_col_1, group_col_2, ..., state_col_1, state_col_2, ...]`
+/// so that partial aggregation data can be handled consistently.
+fn build_partial_agg_schema(
```
Comment (korowa) [inline datafusion/physical-plan/src/aggregates/row_hash.rs:830]: Perhaps instead of the new helper we could reuse [aggregates::create_schema](https://github.com/apache/datafusion/blob/487b952cf1a748cc79724638f13e66761a6665e2/datafusion/physical-plan/src/aggregates/mod.rs#L895)?

File: datafusion/physical-plan/src/aggregates/row_hash.rs (hunk 3 above)
Comment (kosiew) [reply datafusion/physical-plan/src/aggregates/row_hash.rs:530]: hi @korowa ,

> remove this reassignment now

As in remove these lines, am I correct? 

https://github.com/apache/datafusion/blob/487b952cf1a748cc79724638f13e66761a6665e2/datafusion/physical-plan/src/aggregates/row_hash.rs#L967C11-L969C60

File: datafusion/physical-plan/src/aggregates/row_hash.rs (hunk 4 above)
Comment (kosiew) [reply datafusion/physical-plan/src/aggregates/row_hash.rs:830]: I checked create_schema and it handles aggregates like MIN, MAX well but it does not handle  AVG which has multiple intermediate states (partial sum, partial count).

Comment (korowa) [reply datafusion/physical-plan/src/aggregates/row_hash.rs:830]: If I'm not mistaken, it should for `mode = AggregateMode::Partial` -- for this case it also returns state_fields instead of result field

Comment (kosiew) [reply datafusion/physical-plan/src/aggregates/row_hash.rs:830]: Aaa..... 🤔
 Thanks for the pointer. It does work.

File: datafusion/core/src/dataframe/mod.rs (hunk 2 above)
Comment (kosiew) [reply datafusion/core/src/dataframe/mod.rs:2758]: hi @korowa ,

ie datafusion/physical-plan/src/aggregates/mod.rs, am I correct?

File: datafusion/physical-plan/src/aggregates/row_hash.rs (hunk 3 above)
Comment (kosiew) [reply datafusion/physical-plan/src/aggregates/row_hash.rs:550]: Thanks for confirming.
 The lines are removed.

File: datafusion/core/src/dataframe/mod.rs (hunk 2 above)
Comment (korowa) [reply datafusion/core/src/dataframe/mod.rs]: My bad, yes, I meant aggregates/mod.rs

**Review by korowa — APPROVED** [review]
LGTM, thank you @kosiew @2010YOUY01

File: datafusion/core/src/dataframe/mod.rs [hunk 5]
```diff
@@ -43,6 +38,10 @@ use crate::physical_plan::{
     ExecutionPlan, SendableRecordBatchStream,
 };
 use crate::prelude::SessionContext;
+use std::any::Any;
```
Comment (korowa) [inline datafusion/core/src/dataframe/mod.rs:41]: minor: this import reordering can be reverted to leave the file unmodified

**Review by 2010YOUY01 — APPROVED** [review]

**Comment by alamb** [comment]
❤️

**Comment by Friede80** [comment]
Thanks for the rapid fix, @kosiew!
