### PR TITLE
Fix incorrect regex pattern in regex_replace_posix_groups

### LINKED ISSUE #19766: Incorrect regex pattern in regex_replace_posix_groups
### Describe the bug

The `regex_replace_posix_groups` method should replace patterns like `\4` with `${4}` but it's using the pattern `(\\)(\d*)` instead of `(\\)(\d+)`.

### To Reproduce

I added a test in the fix PR which replaces some pattern with "\\", currently this produces "${}" which is how I came across this bug.

### Expected behavior

Should just replace the pattern with "\"

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by GaneshPatil7517**
The `regex_replace_posix_groups` method was using the pattern `(\d*)` to match 
POSIX capture group references like `\1`. However, `*` matches zero or more 
digits, which caused a lone backslash `\` to incorrectly become `${}`.

Changed to `(\d+)` which requires at least one digit, fixing the issue.

Added unit tests to validate correct behavior.

- Fixes #19766

### CODE REVIEW

**Comment by kumarUjjawal** [comment]
Hi @GaneshPatil7517 Thank you for contribution. Please try to use the PR templates instead of the manual descriptions, it will allow the reviewers to easily understand the context.

**Comment by GaneshPatil7517** [comment]
> Hi @GaneshPatil7517 Thank you for contribution. Please try to use the PR templates instead of the manual descriptions, it will allow the reviewers to easily understand the context.

ok sir ill follow from you instruction....

**Comment by alamb** [comment]
FYI @shivbhatia10  -- is there any chance you would like to help review this PR too?

File: datafusion/functions/src/regex/regexpreplace.rs [hunk 1]
```diff
@@ -659,6 +661,28 @@ mod tests {
 
     use super::*;
 
+    #[test]
+    fn test_regex_replace_posix_groups() {
```
Comment (shivbhatia10) [inline datafusion/functions/src/regex/regexpreplace.rs:669]: I have checked that this test fails without the fix with the following error:

```
thread 'regex::regexpreplace::tests::test_regex_replace_posix_groups' (198889) panicked at datafusion/functions/src/regex/regexpreplace.rs:678:9:
assertion `left == right` failed
  left: "${}"
 right: "\\"
```

**Comment by GaneshPatil7517** [comment]
Thank you so much to all for feedback, all checks are passed successfully passed Excited to see it merged...

File: datafusion/functions/src/regex/regexpreplace.rs (hunk 1 above)
Comment (GaneshPatil7517) [reply datafusion/functions/src/regex/regexpreplace.rs:669]: ok ill fix it...

Comment (shivbhatia10) [reply datafusion/functions/src/regex/regexpreplace.rs:669]: ah no sorry I meant that the test fails without the fix, which is correct behaviour, there's nothing to fix

Comment (GaneshPatil7517) [reply datafusion/functions/src/regex/regexpreplace.rs:669]: ok no problem.....

File: datafusion/functions/src/regex/regexpreplace.rs [hunk 2]
```diff
@@ -659,6 +661,28 @@ mod tests {
...
+        // Test that \1, \2, etc. are replaced with ${1}, ${2}, etc.
+        assert_eq!(regex_replace_posix_groups(r"\1"), "${1}");
+        assert_eq!(regex_replace_posix_groups(r"\12"), "${12}");
+        assert_eq!(regex_replace_posix_groups(r"X\1Y"), "X${1}Y");
+        assert_eq!(regex_replace_posix_groups(r"\1\2"), "${1}${2}");
+
+        // Test double backslash (from SQL escaped strings like '\\1')
+        assert_eq!(regex_replace_posix_groups(r"\\1"), "${1}");
+        assert_eq!(regex_replace_posix_groups(r"X\\1Y"), "X${1}Y");
+        assert_eq!(regex_replace_posix_groups(r"\\1\\2"), "${1}${2}");
```
Comment (martin-g) [inline datafusion/functions/src/regex/regexpreplace.rs:679]: nit: you may also add a test case with 3 or 4 backslashes before the number to document the expected behavior in this case, e.g.:
```rust
assert_eq!(regex_replace_posix_groups(r"\\\1\\\\2"), "\${1}\\${2}");
```

Comment (GaneshPatil7517) [reply datafusion/functions/src/regex/regexpreplace.rs:679]: ok sir ill add it....

File: datafusion/functions/src/regex/regexpreplace.rs [hunk 3]
```diff
@@ -189,13 +189,15 @@ fn regexp_replace_func(args: &[ColumnarValue]) -> Result<ArrayRef> {
...
 
-/// replace POSIX capture groups (like \1) with Rust Regex group (like ${1})
+/// replace POSIX capture groups (like \1 or \\1) with Rust Regex group (like ${1})
 /// used by regexp_replace
+/// Handles both single backslash (\1) and double backslash (\\1) which can occur
+/// when SQL strings with escaped backslashes are passed through
 fn regex_replace_posix_groups(replacement: &str) -> String {
     static CAPTURE_GROUPS_RE_LOCK: LazyLock<Regex> =
-        LazyLock::new(|| Regex::new(r"(\\)(\d*)").unwrap());
+        LazyLock::new(|| Regex::new(r"\\{1,2}(\d+)").unwrap());
```
Comment (kosiew) [inline datafusion/functions/src/regex/regexpreplace.rs:202]: This also matches \0, which will be rewritten as ${0}. In Rust’s regex replacement syntax, ${0} substitutes the entire match, not a numbered capture.

Is \0 is meant to be a valid capture reference or treated literally? 
Let's add a test to explicitly document the behaviour of  \0

**Review by kosiew — COMMENTED** [review]
Thanks @GaneshPatil7517 for contributing.

File: datafusion/functions/src/regex/regexpreplace.rs (hunk 3 above)
Comment (GaneshPatil7517) [reply datafusion/functions/src/regex/regexpreplace.rs:202]: Thank you for the feedback Great catch on the \0 behavior.

I've added documentation and a test to explicitly document this behavior:

\0 is converted to ${0}, which in Rust's regex replacement syntax substitutes the entire match
This is consistent with POSIX behavior where \0 (or &) refers to the entire matched string
Added test cases:

// Test \0 behavior: \0 is converted to ${0}, which in Rust's regex
// replacement syntax substitutes the entire match. This is consistent
// with POSIX behavior where \0 (or &) refers to the entire matched string.
assert_eq!(regex_replace_posix_groups(r"\0"), "${0}");
assert_eq!(regex_replace_posix_groups(r"prefix\0suffix"), "prefix${0}suffix");

So \0 is intentionally treated as a valid capture reference (for the entire match), not literally. This aligns with standard regex behavior in most systems.

**Comment by alamb** [comment]
@martin-g and @kosiew -- is this PR ready to go?

**Comment by martin-g** [comment]
I think so, yes! 
Merging it!
