### PR TITLE
fix: make get_valid_types handle TypeSignature::Numeric correctly

### LINKED ISSUE #14059: Bug: get_valid_types handles TypeSignature::Numeric incorrectly
### Describe the bug

The `get_valid_types` function works correctly when the type signature is `TypeSignature::Numeric(n)` with n > 1. However, it behaves incorrectly when `n = 1`. 
This is because the function first attempts to coerce data types into a numeric type. Such coercion is only performed when the number of arguments is greater than 1, but it does not check if the single data type is numeric when there's only one argument.

### To Reproduce

You can write a simple unit test to reproduce the error:

```rust
    #[test]
    fn test_get_valid_types_numeric() -> Result<()> {
        let signature = TypeSignature::Numeric(1);

        // Returns ok while it's expected to return err.
        let got = get_valid_types(&signature, &[DataType::Binary]);
        assert!(got.is_ok());

        Ok(())
    }
```

### Expected behavior

The `get_valid_types` functions rejects non-numeric arguments when given `TypeSignature::Numeric(1)`.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by niebayes**
## Which issue does this PR close?

Closes #14059.

## What changes are included in this PR?

Make `get_valid_types` handle TypeSignature::Numeric(n) correctly, for various n.

## Are these changes tested?

Yes, added a unit test.

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/expr/src/type_coercion/functions.rs [hunk 1]
```diff
@@ -551,6 +551,10 @@ fn get_valid_types(
             // and their default type is double precision
             if logical_data_type == NativeType::Null {
                 valid_type = DataType::Float64;
+            } else if !logical_data_type.is_numeric() {
+                return plan_err!(
+                    "The signature expected NativeType::Numeric but received {logical_data_type}"
+                );
```
Comment (niebayes) [inline datafusion/expr/src/type_coercion/functions.rs:557]: I'm not entirely clear on the rationale for falling back to Float64 when the argument is of type Null. 
However, I choose to keep this logic and make it a short-circuit before the numeric check.

File: datafusion/physical-expr-common/src/sort_expr.rs [hunk 2]
```diff
@@ -291,9 +291,9 @@ impl PhysicalSortRequirement {
     /// Returns whether this requirement is equal or more specific than `other`.
     pub fn compatible(&self, other: &PhysicalSortRequirement) -> bool {
         self.expr.eq(&other.expr)
-            && other.options.map_or(true, |other_opts| {
-                self.options.map_or(false, |opts| opts == other_opts)
-            })
+            && other
+                .options
+                .map_or(true, |other_opts| self.options == Some(other_opts))
```
Comment (niebayes) [inline datafusion/physical-expr-common/src/sort_expr.rs:296]: fix clippy

File: datafusion/expr/src/type_coercion/functions.rs (hunk 1 above)
Comment (jayzhan211) [reply datafusion/expr/src/type_coercion/functions.rs:557]: f64 is chosen since it is the most compatible type of numeric

**Review by jayzhan211 — DISMISSED** [review]
👍🏻

**Comment by niebayes** [comment]
I need to bump Rust to 1.84 to pass CI

**Review by jayzhan211 — APPROVED** [review]
👍🏻

**Comment by jayzhan211** [comment]
Thanks @niebayes
