### PR TITLE
fix: filter pushdown when merge filter

### LINKED ISSUE #20109: FilterPushdown do not generate correct column index when merge FilterExec
### Describe the bug

i have a plan like below that have two consecutive FilterExec, so i use FilterPushdown two merge it, but after the merge and execute, it report error. if i not call FilterPushDown, the plan can output result.
```
Physical plan before pushdown filter:
FilterExec: event@0 = Ingestion, projection=[size@1]
  FilterExec: time@0 < 1770020321951000, projection=[event@1, size@2]
    DataSourceExec: partitions=1, partition_sizes=[11]
Get result before pushdown filter, result size: 8

Physical plan after pushdown filter:
ProjectionExec: expr=[size@1 as size]
  FilterExec: event@0 = Ingestion AND time@0 < 1770020321951000
    DataSourceExec: partitions=1, partition_sizes=[11]
Error: ArrowError(InvalidArgumentError("Invalid comparison operation: Int64 == Utf8"), Some(""))
```
the `event@0` is not correct, it should be `event@1`

### To Reproduce

```rust
use std::sync::Arc;

use datafusion::arrow::array::{Int64Array, RecordBatch, StringArray};
use datafusion::arrow::datatypes::{DataType, Field, Schema};
use datafusion::common::Result;
use datafusion::datasource::memory::MemorySourceConfig;
use datafusion::physical_expr::expressions::{BinaryExpr, col, lit};
use datafusion::physical_optimizer::PhysicalOptimizerRule;
use datafusion::physical_optimizer::filter_pushdown::FilterPushdown;
use datafusion::physical_plan::filter::FilterExec;
use datafusion::physical_plan::{ExecutionPlan, collect, displayable};
use datafusion::prelude::SessionContext;
use datafusion_expr::Operator;

#[tokio::main]
async fn main() -> Result<()> {
    // 1. Create data source
    let memory_exec = create_data_source();

    // 2. First FilterExec: time < 1770020321951000 with projection=[event@1, size@2]
    let timestamp_col = col("time", &memory_exec.schema())?;
    let upper_bound = lit(1770020321951000i64);
    let lt_expr = Arc::new(BinaryExpr::new(timestamp_col, Operator::Lt, upper_bound));
    let filter1_exec: Arc<dyn ExecutionPlan> = Arc::new(
        FilterExec::try_new(lt_expr, memory_exec)?.with_projection(Some(vec![1, 2]))?, // projection=[event@1, size@2]
    );

    // 3. Second FilterExec: event = 'Ingestion' with projection=[size]
    let event_col = col("event", &filter1_exec.schema())?;
    let ingestion_lit = lit("Ingestion");
    let event_filter = Arc::new(BinaryExpr::new(event_col, Operator::Eq, ingestion_lit));
    let filter2_exec: Arc<dyn ExecutionPlan> = Arc::new(
        FilterExec::try_new(event_filter, filter1_exec)?
            .with_projection(Some(vec![1]))?, // projection=[size@1]
    );

    println!("Physical plan before pushdown filter:");
    print!(
        "{}",
        displayable(filter2_exec.as_ref()).indent(true).to_string()
    );

    // Execute the plan
    let ctx = SessionContext::new();
    let result = collect(filter2_exec.clone(), ctx.task_ctx()).await?;

    println!(
        "Get result before pushdown filter, result size: {:?}\n",
        result.iter().fold(0, |acc, x| acc + x.num_rows())
    );

    // After pushdown filter
    let pushdown_filter = FilterPushdown::new();
    let optimized_plan =
        pushdown_filter.optimize(filter2_exec.clone(), ctx.state().config_options())?;

    println!("Physical plan after pushdown filter:");
    print!(
        "{}",
        displayable(optimized_plan.as_ref())
            .indent(true)
            .to_string(),
    );

    let result = collect(optimized_plan.clone(), ctx.task_ctx()).await?;
    println!("{:?}", result);

    Ok(())
}

fn create_data_source() -> Arc<dyn ExecutionPlan> {
    // Create schema: time, event, size
    let schema = Arc::new(Schema::new(vec![
        Field::new("time", DataType::Int64, false),
        Field::new("event", DataType::Utf8, false),
        Field::new("size", DataType::Int64, false),
    ]));

    // Create 11 batches of sample data to get partition_sizes=[11]
    let timestamps = vec![
        1770020021951000i64,
        1770020021951001,
        1770020021951002,
        1770020021951003,
        1770020021951004,
        1770020021951005,
        1770020021951006,
        1770020021951007,
        1770020021951008,
        1770020021951009,
        1770020021951010,
    ];
    let events = vec![
        "Ingestion",
        "Ingestion",
        "Query",
        "Ingestion",
        "Ingestion",
        "Query",
        "Ingestion",
        "Ingestion",
        "Ingestion",
        "Query",
        "Ingestion",
    ];
    let sizes = vec![100i64, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100];

    // Create 11 separate batches (one row each) to get partition_sizes=[11]
    let batches: Vec<RecordBatch> = (0..11)
        .map(|i| {
            RecordBatch::try_new(
                schema.clone(),
                vec![
                    Arc::new(Int64Array::from(vec![timestamps[i]])),
                    Arc::new(StringArray::from(vec![events[i]])),
                    Arc::new(Int64Array::from(vec![sizes[i]])),
                ],
            )
            .unwrap()
        })
        .collect();

    // Create MemorySourceConfig to create the data source
    MemorySourceConfig::try_new_exec(&[batches], schema.clone(), None).unwrap()
}
```

### Expected behavior

success run

### Additional context

test all version that have `FilterPushdown`, all not work

### PR DESCRIPTION
**Pull request by haohuaijin**
## Which issue does this PR close?

- Closes #20109

## Rationale for this change

see issue #20109

## What changes are included in this PR?

1. Remap parent filter expressions: When a FilterExec has a projection, remap unsupported parent filter expressions from output schema coordinates to input schema coordinates using `reassign_expr_columns()` before combining them with the current filter's predicates.

2. Preserve projection: When creating the merged FilterExec, preserve the original projection instead of discarding it .

## Are these changes tested?

yes, add some test case

### CODE REVIEW

**Comment by adriangb** [comment]
@haohuaijin please ping me when this is ready for review

**Comment by haohuaijin** [comment]
cc @adriangb, ready for reviews

File: datafusion/core/tests/physical_optimizer/filter_pushdown.rs [hunk 1]
```diff
@@ -3720,3 +3720,90 @@ async fn test_hashjoin_dynamic_filter_pushdown_is_used() {
         );
     }
 }
+
+/// related to https://github.com/apache/datafusion/issues/20109
```
Comment (adriangb) [inline datafusion/core/tests/physical_optimizer/filter_pushdown.rs]:
```suggestion
/// Regression test for https://github.com/apache/datafusion/issues/20109
```

File: datafusion/physical-plan/src/filter.rs [hunk 2]
```diff
@@ -623,10 +623,26 @@ impl ExecutionPlan for FilterExec {
...
-                matches!(f.all(), PushedDown::No).then_some(Arc::clone(&f.filter))
-            });
+        let mut unsupported_parent_filters: Vec<Arc<dyn PhysicalExpr>> =
+            child_pushdown_result
+                .parent_filters
+                .iter()
+                .filter_map(|f| {
+                    matches!(f.all(), PushedDown::No).then_some(Arc::clone(&f.filter))
+                })
+                .collect();
```
Comment (adriangb) [inline datafusion/physical-plan/src/filter.rs:633]: Note: this is the same code, just added the `mut` which caused a reformat.

File: datafusion/physical-plan/src/filter.rs [hunk 3]
```diff
@@ -623,10 +623,26 @@ impl ExecutionPlan for FilterExec {
...
+
+        // If this FilterExec has a projection, the unsupported parent filters
+        // are in the output schema (after projection) coordinates. We need to
+        // remap them to the input schema coordinates before combining with self filters.
+        if self.projection.is_some() {
```
Comment (adriangb) [inline datafusion/physical-plan/src/filter.rs:638]: 👍🏻 note that this is because filters get evaluated before the projection

File: datafusion/core/tests/physical_optimizer/filter_pushdown.rs [hunk 4]
```diff
@@ -3720,3 +3720,90 @@ async fn test_hashjoin_dynamic_filter_pushdown_is_used() {
...
+#[tokio::test]
+async fn test_filter_with_projection_pushdown() {
```
Comment (adriangb) [inline datafusion/core/tests/physical_optimizer/filter_pushdown.rs:3726]: Any chance you could add an SLT test that reproduces this? It could go in datafusion/sqllogictest/test_files/parquet_filter_pushdown.slt

**Comment by haohuaijin** [comment]
Thanks for you reviews @adriangb, i try add a SLT test, but use sql is hard to do.

**Comment by adriangb** [comment]
No worries. Let's merge this once CI passes.

**Comment by alamb** [comment]
🚀

**Comment by hengfeiyang** [comment]
Hi @alamb, Is it possible to release version 52.2.0? This issue has affected our online business, and we have temporarily disabled this feature. It would be great if a minor version could be released quickly.

**Comment by adriangb** [comment]
@hengfeiyang we can certainly put this on the docket for the next minor release, but we don’t tend to do more than 1 minor release per major version, so this may have to wait until the next major version if there aren’t many other fixes. Would you be able to point your system at a git commit or fork with this commit cherry picked? That’s what we do

**Comment by hengfeiyang** [comment]
Yes. definitely we can do that, actually we did that in the past if we can't get a release soon. just we don't like to use fork version if we can have official release. 

Thank you for you reply. we will use fork version before next release.

**Comment by alamb** [comment]
> Hi @alamb, Is it possible to release version 52.2.0? This issue has affected our online business, and we have temporarily disabled this feature. It would be great if a minor version could be released quickly.

I am happy to help support another release (run the voting, etc) if someone else is willing do make the tickets, backport and changelog PRs

**Comment by alamb** [comment]
(BTW I think I may also have a bug in 52 that I'll file tomorrow which might be good to fix too). I'll post here if I do

**Comment by alamb** [comment]
> > Hi @alamb, Is it possible to release version 52.2.0? This issue has affected our online business, and we have temporarily disabled this feature. It would be great if a minor version could be released quickly.
> 
> I am happy to help support another release (run the voting, etc) if someone else is willing do make the tickets, backport and changelog PRs

Update: Filed a ticket to track a next patch release
 - https://github.com/apache/datafusion/issues/20287
