### PR TITLE
fix: Fix Spark `slice` function `Null` type to `GenericListArray` casting issue

### LINKED ISSUE #20466: Fix Spark `slice` function `Null` type to `GenericListArray` casting issue
### Describe the bug

Currently, Spark `slice` function accepts Null Arrays and return `Null` for this particular queries. DataFusion-Spark `slice` function also needs to return `NULL` when Null Array is set.
**Spark Behavior** (tested with latest Spark master):
```
> SELECT slice(NULL, 1, 2);
+-----------------+
|slice(NULL, 1, 2)|
+-----------------+
|             null|
+-----------------+
```

**DF Behaviour:**
Current:
```
query error
SELECT slice(NULL, 1, 2);
----
DataFusion error: Internal error: could not cast array of type Null to arrow_array::array::list_array::GenericListArray<i32>.
This issue was likely caused by a bug in DataFusion's code. Please help us to resolve this by filing a bug report in our issue tracker: https://github.com/apache/datafusion/issues
```
New:
```
query ?
SELECT slice(NULL, 1, 2);
----
NULL
```

### To Reproduce

Explained under description section.

### Expected behavior

Explained under description section.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by erenavsarogullari**
## Which issue does this PR close?
- Closes #20466.

## Rationale for this change
Currently, Spark `slice` function accepts Null Arrays and return `Null` for this particular queries. DataFusion-Spark `slice` function also needs to return `NULL` when Null Array is set.
**Spark Behavior** (tested with latest Spark master):
```
> SELECT slice(NULL, 1, 2);
+-----------------+
|slice(NULL, 1, 2)|
+-----------------+
|             null|
+-----------------+
```

**DF Behaviour:**
Current:
```
query error
SELECT slice(NULL, 1, 2);
----
DataFusion error: Internal error: could not cast array of type Null to arrow_array::array::list_array::GenericListArray<i32>.
This issue was likely caused by a bug in DataFusion's code. Please help us to resolve this by filing a bug report in our issue tracker: https://github.com/apache/datafusion/issues
```
New:
```
query ?
SELECT slice(NULL, 1, 2);
----
NULL
```

## What changes are included in this PR?
Explained under first section.

## Are these changes tested?
Added new UT cases for both `slice.rs` and `slice.slt`.

## Are there any user-facing changes?
Yes, currently, `slice` function returns error message for `Null` Array inputs, however, expected behavior is to be returned `NULL` so end-user will get expected result instead of error message.

### CODE REVIEW

**Comment by Jefffrey** [comment]
Does Spark return null (void) or an array of null (void)?

I tested on PySpark 4.1.1

```python
>>> spark.sql("select slice(NULL, 1, 2) as a").printSchema()
root
 |-- a: array (nullable = true)
 |    |-- element: void (containsNull = true)
```

- Seems to suggest the latter?

**Comment by erenavsarogullari** [comment]
Spark returns `Array as (nullable = true / false)` and there are 2 representations as follows in terms of `input array` so it returns input array for both cases as either `NULL` or `[NULL]`:
**Case1:** input array is null (`array (nullable = true)`): 
```
+-----------------+
|slice(NULL, 1, 2)|
+-----------------+
|             NULL|
+-----------------+

root
 |-- slice(NULL, 1, 2): array (nullable = true)
 |    |-- element: void (containsNull = true)
```

**Case2:** input array has null element (`array (nullable = false)`):
```
+------------------------+
|slice(array(NULL), 1, 2)|
+------------------------+
|                  [NULL]|
+------------------------+

root
 |-- slice(array(NULL), 1, 2): array (nullable = false)
 |    |-- element: void (containsNull = true)
```

**Comment by Jefffrey** [comment]
This seems to suggest return type should be list of nulls instead of just null

File: datafusion/spark/src/function/array/slice.rs [hunk 1]
```diff
@@ -94,6 +96,10 @@ impl ScalarUDFImpl for SparkSlice {
         &self,
         mut func_args: ScalarFunctionArgs,
     ) -> Result<ColumnarValue> {
+        if func_args.args[0].data_type() == DataType::Null {
+            return Ok::<ColumnarValue, DataFusionError>(func_args.args[0].clone());
```
Comment (martin-g) [inline datafusion/spark/src/function/array/slice.rs]: Is there a need of the turbofish here ?

```suggestion
            return Ok(func_args.args[0].clone());
```
This will also make the new import of `DataFusionError` not needed

File: datafusion/spark/src/function/array/slice.rs [hunk 2]
```diff
@@ -94,6 +96,10 @@ impl ScalarUDFImpl for SparkSlice {
...
+        };
```
Comment (martin-g) [inline datafusion/spark/src/function/array/slice.rs]:
```suggestion
        }
```

File: datafusion/spark/src/function/array/slice.rs [hunk 3]
```diff
@@ -170,3 +176,40 @@ fn calculate_start_end(args: &[ArrayRef]) -> Result<(ArrayRef, ArrayRef)> {
...
+            return_field: Arc::new(Field::new(
+                "item",
+                List(FieldRef::new(Field::new_list_field(DataType::Int64, true))),
+                false,
+            )),
+            config_options: Arc::new(Default::default()),
+        };
+        let slice = SparkSlice::new();
+        let result = slice.invoke_with_args(args).unwrap();
+        assert!(result.to_array(1).unwrap() == Arc::new(NullArray::new(1)));
```
Comment (martin-g) [inline datafusion/spark/src/function/array/slice.rs]:
```suggestion
        assert_eq!(result.to_array(1).unwrap(), Arc::new(NullArray::new(1)));
```

File: datafusion/spark/src/function/array/slice.rs [hunk 4]
```diff
@@ -170,3 +176,40 @@ fn calculate_start_end(args: &[ArrayRef]) -> Result<(ArrayRef, ArrayRef)> {
...
+    #[test]
+    fn test_spark_slice_function_when_input_array_is_null() {
+        let input_args = vec![
+            ColumnarValue::Array(Arc::new(NullArray::new(1))),
+            ColumnarValue::Scalar(ScalarValue::Int64(Some(1))),
+            ColumnarValue::Scalar(ScalarValue::Int64(Some(3))),
+        ];
+
+        let args = ScalarFunctionArgs {
+            args: input_args.to_owned(),
```
Comment (martin-g) [inline datafusion/spark/src/function/array/slice.rs]:
```suggestion
            args: input_args,
```

File: datafusion/spark/src/function/array/slice.rs [hunk 5]
```diff
@@ -170,3 +176,40 @@ fn calculate_start_end(args: &[ArrayRef]) -> Result<(ArrayRef, ArrayRef)> {
...
+            arg_fields: vec![Arc::new(Field::new(
+                "item",
+                List(FieldRef::new(Field::new("", DataType::Int64, true))),
```
Comment (martin-g) [inline datafusion/spark/src/function/array/slice.rs]:
```suggestion
                List(FieldRef::new(Field::new("f", DataType::Int64, true))),
```
It looks weird to use an empty name for a field.

File: datafusion/spark/src/function/array/slice.rs [hunk 6]
```diff
@@ -170,3 +176,40 @@ fn calculate_start_end(args: &[ArrayRef]) -> Result<(ArrayRef, ArrayRef)> {
...
+                false,
+            ))],
+            number_rows: 0,
```
Comment (martin-g) [inline datafusion/spark/src/function/array/slice.rs]:
```suggestion
            number_rows: 1,
```
to match with the length of `NullArray::new(1)`

File: datafusion/spark/src/function/array/slice.rs (hunk 1 above)
Comment (erenavsarogullari) [reply datafusion/spark/src/function/array/slice.rs]: I had compile-time error for `turbofish` before but it does not require for the latest change-set. Also,  `DataFusionError` import has been removed.

**Comment by erenavsarogullari** [comment]
> This seems to suggest return type should be list of nulls instead of just null

Yes, latest fix aims to address this by returning `NullArray` instead of Scalar `Null` value.

**Comment by Jefffrey** [comment]
> > This seems to suggest return type should be list of nulls instead of just null
> 
> Yes, latest fix aims to address this by returning `NullArray` instead of Scalar `Null` value.

Sorry I don't see how this relates? I mean it seems to suggest that a `DataType::Null` input has a `DataType::List(Null)` output, according to my PySpark test. But maybe the test was incorrect, since perhaps Spark introduces some casts? Could we confirm the behaviour if we want to align with Spark here?

**Comment by erenavsarogullari** [comment]
@Jefffrey Sorry for the delay and thanks again for the review. I have just submitted the latest commit which returns `DataType::List(Null)` for `DataType::Null` input and added test cases verifying the output type.

File: datafusion/spark/src/function/array/slice.rs [hunk 7]
```diff
@@ -78,17 +78,28 @@ impl ScalarUDFImpl for SparkSlice {
...
     fn invoke_with_args(
         &self,
         mut func_args: ScalarFunctionArgs,
     ) -> Result<ColumnarValue> {
+        if func_args.args[0].data_type() == DataType::Null {
+            let len = match &func_args.args[0] {
+                ColumnarValue::Array(a) => a.len(),
+                ColumnarValue::Scalar(_) => func_args.number_rows,
+            };
+            return Ok(ColumnarValue::Array(list_null_array(len)));
```
Comment (Jefffrey) [inline datafusion/spark/src/function/array/slice.rs]:
```suggestion
            return Ok(ColumnarValue::Scalar(ScalarValue::new_null_list(
                DataType::Null,
                true,
                1,
            )));
```

**Review by Jefffrey — APPROVED** [review]

**Comment by erenavsarogullari** [comment]
Last review comment has been addressed and last CI run has been successful. Thanks for the reviews.

**Comment by Jefffrey** [comment]
Thanks @erenavsarogullari & @martin-g
