### PR TITLE
Fix: handle NULL input in lead/lag window function

### LINKED ISSUE #12717: Incorrect NULL handling in `lead` window function (SQLancer)
### Describe the bug

See the reproducer in datafusion-cli (compiled from the latest main, commit 0242767)
```
> create table t1(v1 int);
0 row(s) fetched.
Elapsed 0.015 seconds.

> insert into t1 values (1);
+-------+
| count |
+-------+
| 1     |
+-------+
1 row(s) fetched.
Elapsed 0.017 seconds.

> SELECT LEAD(NULL, 1, false) OVER () FROM t1;
Arrow error: Cast error: Casting from Boolean to Null not supported
```

### To Reproduce

_No response_

### Expected behavior

This query should be valid, NULL literal can be interpreted as a missing bool value, so 1st and 3rd arg in `lead()` function have  the same type

postgres result:
```
postgres=# create table t1(v1 int);
iCREATE TABLE
postgres=# insert into t1 values (1);
INSERT 0 1
postgres=# SELECT LEAD(NULL, 1, false) OVER () FROM t1;
 lead 
------
 f
(1 row)
```

### Additional context

Found by SQLancer https://github.com/apache/datafusion/issues/11030

### PR DESCRIPTION
**Pull request by HuSen8891**
## Which issue does this PR close?

Closes #12717 

## Are there any user-facing changes?

### CODE REVIEW

**Review by comphead — COMMENTED** [review]
Thanks @HuSen8891 
I have some feeling that we should fix the out_data_type earlier so it will serve both LAG/LEAD

**Comment by HuSen8891** [comment]
> Thanks @HuSen8891 I have some feeling that we should fix the out_data_type earlier so it will serve both LAG/LEAD

Thanks! handle NULL input in lag window function

File: datafusion/physical-plan/src/windows/mod.rs [hunk 1]
```diff
@@ -257,31 +257,55 @@ fn create_built_in_window_expr(
...
+                        let null_value = ScalarValue::try_from(value.data_type())?;
+                        arg = Arc::new(Literal::new(null_value));
+                        value
+                    }
+                    None => ScalarValue::try_from(DataType::Null)?,
+                },
+                _ => {
+                    get_casted_value(get_scalar_value_from_args(args, 2)?, out_data_type)?
+                }
+            };
```
Comment (jcsherin) [inline datafusion/physical-plan/src/windows/mod.rs:277]: I think concerns got intertwined here making this code a bit hard to read. Tbh this bit of code was hard to understand even in the absence of this fix 😅. 

I know because I had some difficult in correctly moving this code for parsing the window function arguments when converting it to a `WindowUDF`. See #12857. 

From my understanding there are two things happening here,
1. When `NULL` is passed as the expression (1st argument) we need to coerce it to be the type of the default value(if one is provided).
2. Like you rightly pointed out in the comments, there is no need to cast the default value to type of the 1st argument when it is `NULL`.

There is a dependency on the default value(3rd argument) in both of the cases.

We can compute them separately like this,
```suggestion
            let arg = coerce_default_type_if_null(args, out_data_type);
            let default_value =
                get_casted_value(get_scalar_value_from_args(args, 2)?, out_data_type)?;

```

In the first part, we coerce `NULL` to `DataType` of default value when one is provided,
```rust
/// For lead/lag window functions, when the expression (first argument)
/// is NULL, interpret it as a missing value which has the same type as
/// the default value.
///
/// See https://github.com/apache/datafusion/issues/12717
fn coerce_default_type_if_null(
    args: &[Arc<dyn PhysicalExpr>],
    expr_type: &DataType,
) -> Arc<dyn PhysicalExpr> {
    let expr = Arc::clone(&args[0]);
    let default_value = get_scalar_value_from_args(args, 2);

    if !expr_type.is_null() {
        expr
    } else {
        default_value
            .unwrap()
            .and_then(|value| {
                ScalarValue::try_from(value.data_type().clone())
                    .map(|sv| Arc::new(Literal::new(sv)) as Arc<dyn PhysicalExpr>)
                    .ok()
            })
            .unwrap_or(expr)
    }
}
```

And in the second part we push the null check into `get_casted_value` function. This benefits both lead/lag as they are the only users of `get_casted_value`. It looks like this,
```rust
/// For lead/lag window functions, the types of the 1st and 3rd
/// argument should match. So here we attempt to cast the default
/// value to the same type as the 1st argument.
///
/// This also handles the case where the 1st argument could be
/// a NULL value in which case avoid casting the 3rd argument.
///
/// See https://github.com/apache/datafusion/issues/12717
fn get_casted_value(
    default_value: Option<ScalarValue>,
    dtype: &DataType,
) -> Result<ScalarValue> {
    match (dtype.is_null(), &default_value) {
        (true, _) => Ok(default_value.unwrap_or(ScalarValue::Null)),
        (false, None) => ScalarValue::try_from(dtype.clone()),
        (false, Some(v)) => {
            if !v.data_type().is_null() {
                v.cast_to(dtype)
            } else {
                ScalarValue::try_from(dtype.clone())
            }
        }
    }
}
```

File: datafusion/sqllogictest/test_files/window.slt [hunk 2]
```diff
@@ -4932,4 +4932,52 @@ SELECT v1, NTH_VALUE(v2, 0) OVER (PARTITION BY v1 ORDER BY v2) FROM t;
 statement ok
 DROP TABLE t;
 
-## end test handle NULL and 0 of NTH_VALUE
\ No newline at end of file
+## end test handle NULL and 0 of NTH_VALUE
+
+## test handle NULL of lead
```
Comment (jcsherin) [inline datafusion/sqllogictest/test_files/window.slt:4937]: ❤️

File: datafusion/physical-plan/src/windows/mod.rs (hunk 1 above)
Comment (HuSen8891) [reply datafusion/physical-plan/src/windows/mod.rs]: Thanks！Refactor the code as described above.

File: datafusion/physical-plan/src/windows/mod.rs [hunk 3]
```diff
@@ -217,6 +217,41 @@ fn get_casted_value(
...
+    // Rewrites the NULL expression (1st argument) with an expression
+    // which is the same data type as the default value (3rd argument).
+    // Also rewrites the return type with the same data type as the
+    // default value.
+    //
+    // If a default value is not provided, or it is NULL the original
+    // expression (1st argument) and return type is returned without
+    // any modifications.
+    get_scalar_value_from_args(args, 2)
+        .unwrap()
```
Comment (jcsherin) [inline datafusion/physical-plan/src/windows/mod.rs:241]: Sorry, I should have avoided the use of `unwrap()` here which will panic 😅. Instead we should propagate the error up the call stack.

```suggestion
    get_scalar_value_from_args(args, 2)?
```

Inside `get_scalar_value_from_args` an error is returned if a `Literal` is not found at the specified index,
https://github.com/apache/datafusion/blob/f9e8e07e8a3af4f1f4836259c6f87636bc1b9631/datafusion/physical-plan/src/windows/mod.rs#L173-L176

For that we'll need to change the function signature to return a `Result<(Arc<dyn PhysicalExpr>, DataType)>` type.
```rust
fn rewrite_null_expr_and_data_type(
    args: &[Arc<dyn PhysicalExpr>],
    expr_type: &DataType,
) -> Result<(Arc<dyn PhysicalExpr>, DataType)> // <- wrapped in `Result()`
```

And the callers changed to do an early return in case of any errors.
```rust
            // rewrite NULL expression and the return datatype
            let (arg, out_data_type) =
                rewrite_null_expr_and_data_type(args, out_data_type)?; // <- adds `?`
```

File: datafusion/physical-plan/src/windows/mod.rs (hunk 1 above)
Comment (jcsherin) [reply datafusion/physical-plan/src/windows/mod.rs]: Thanks @HuSen8891. This refactor makes it easier to port this fix to #12857.

File: datafusion/physical-plan/src/windows/mod.rs [hunk 4]
```diff
@@ -217,6 +217,41 @@ fn get_casted_value(
     }
 }
 
+fn rewrite_null_expr_and_data_type(
+    args: &[Arc<dyn PhysicalExpr>],
+    expr_type: &DataType,
+) -> (Arc<dyn PhysicalExpr>, DataType) {
+    let expr = Arc::clone(&args[0]);
```
Comment (comphead) [inline datafusion/physical-plan/src/windows/mod.rs:224]: lets assert args are non empty before access the first element

File: datafusion/physical-plan/src/windows/mod.rs [hunk 5]
```diff
@@ -217,6 +217,41 @@ fn get_casted_value(
     }
 }
 
+fn rewrite_null_expr_and_data_type(
```
Comment (comphead) [inline datafusion/physical-plan/src/windows/mod.rs:220]: for the naming its little bit abstract however its still good name but to help  contributors understand what this method exactly doing lets add comments.

Having comments method increases chances that method can be reusable in future if the similar case shows up

Comment (jcsherin) [reply datafusion/physical-plan/src/windows/mod.rs:220]: > for the naming its little bit abstract however its still good name but to help contributors understand what this method exactly doing lets add comments.
> 
> Having comments method increases chances that method can be reusable in future if the similar case shows up

💯

File: datafusion/physical-plan/src/windows/mod.rs (hunk 4 above)
Comment (HuSen8891) [reply datafusion/physical-plan/src/windows/mod.rs:233]: Thanks. Fixed.

File: datafusion/physical-plan/src/windows/mod.rs [hunk 6]
```diff
@@ -217,6 +217,41 @@ fn get_casted_value(
...
+    assert!(!args.is_empty());
+    let expr = Arc::clone(&args[0]);
+
+    // The input expression and the return is type is unchanged
+    // when the input expression is not NULL.
+    if !expr_type.is_null() {
+        return Ok((expr, expr_type.clone()));
+    }
+
+    get_scalar_value_from_args(args, 2)?
```
Comment (jcsherin) [inline datafusion/physical-plan/src/windows/mod.rs:241]: 👍

**Review by comphead — APPROVED** [review]
lgtm thanks @HuSen8891

**Comment by jcsherin** [comment]
Thanks @HuSen8891 and @comphead 🙌

**Comment by alamb** [comment]
Thank you @HuSen8891 and @comphead  and @jcsherin  for the review
