### PR TITLE
fix: preserve duplicate GROUPING SETS rows

### LINKED ISSUE #21316: Duplicate `GROUPING SETS` rows are incorrectly collapsed during execution
### Describe the bug

When `GROUPING SETS` contains duplicate grouping lists, DataFusion incorrectly collapses them during execution. The repeated grouping sets share the same execution key and are merged together, causing rows to be lost.

This behavior differs from PostgreSQL, which preserves duplicate grouping sets and returns duplicated result rows.

### To Reproduce

Create the sample table:
```
create table duplicate_grouping_sets(deptno int, job varchar, sal int, comm int);
insert into duplicate_grouping_sets values
(10, 'CLERK', 1300, null),
(20, 'MANAGER', 3000, null);
```
Run the query:
```
select deptno, job, sal, sum(comm), grouping(deptno), grouping(job), grouping(sal)
from duplicate_grouping_sets
group by grouping sets ((deptno, job), (deptno, sal), (deptno, job))
order by deptno, job, sal, grouping(deptno), grouping(job), grouping(sal);
```
PostgreSQL preserves the duplicate grouping set and returns:
```
 deptno |   job   | sal  | sum | grouping | grouping | grouping
--------+---------+------+-----+----------+----------+----------
     10 | CLERK   |      |     |        0 |        0 |        1
     10 | CLERK   |      |     |        0 |        0 |        1
     10 |         | 1300 |     |        0 |        1 |        0
     20 | MANAGER |      |     |        0 |        0 |        1
     20 | MANAGER |      |     |        0 |        0 |        1
     20 |         | 3000 |     |        0 |        1 |        0
(6 rows)
```
DataFusion collapsed the duplicate (deptno, job) grouping set and returned only 4 rows for the same query shape.
```
+--------+---------+------+-----------------------------------+------------------------------------------+---------------------------------------+---------------------------------------+
| deptno | job     | sal  | sum(duplicate_grouping_sets.comm) | grouping(duplicate_grouping_sets.deptno) | grouping(duplicate_grouping_sets.job) | grouping(duplicate_grouping_sets.sal) |
+--------+---------+------+-----------------------------------+------------------------------------------+---------------------------------------+---------------------------------------+
| 10     | CLERK   | NULL | NULL                              | 0                                        | 0                                     | 1                                     |
| 10     | NULL    | 1300 | NULL                              | 0                                        | 1                                     | 0                                     |
| 20     | MANAGER | NULL | NULL                              | 0                                        | 0                                     | 1                                     |
| 20     | NULL    | 3000 | NULL                              | 0                                        | 1                                     | 0                                     |
+--------+---------+------+-----------------------------------+------------------------------------------+---------------------------------------+---------------------------------------+
```
Compare the result with PostgreSQL. PostgreSQL returns 6 rows, including the duplicate (deptno, job) grouping set, while DataFusion currently returns only 4 rows.

### Expected behavior

Duplicate GROUPING SETS entries should be preserved during execution, and the query result should match PostgreSQL behavior, returning duplicated rows when the grouping set list contains duplicates.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xiedeyantu**
## Which issue does this PR close?

- Closes #21316.

## Rationale for this change

`GROUPING SETS` with duplicate grouping lists were incorrectly collapsed during execution. The internal grouping id only encoded the semantic null mask, so repeated grouping sets shared the same execution key and were merged, which caused rows to be lost compared with PostgreSQL behavior.

For example, with:

```sql
create table duplicate_grouping_sets(deptno int, job varchar, sal int, comm int);
insert into duplicate_grouping_sets values
(10, 'CLERK', 1300, null),
(20, 'MANAGER', 3000, null);

select deptno, job, sal, sum(comm), grouping(deptno), grouping(job), grouping(sal)
from duplicate_grouping_sets
group by grouping sets ((deptno, job), (deptno, sal), (deptno, job))
order by deptno, job, sal, grouping(deptno), grouping(job), grouping(sal);
```

PostgreSQL preserves the duplicate grouping set and returns:

```text
 deptno |   job   | sal  | sum | grouping | grouping | grouping
--------+---------+------+-----+----------+----------+----------
     10 | CLERK   |      |     |        0 |        0 |        1
     10 | CLERK   |      |     |        0 |        0 |        1
     10 |         | 1300 |     |        0 |        1 |        0
     20 | MANAGER |      |     |        0 |        0 |        1
     20 | MANAGER |      |     |        0 |        0 |        1
     20 |         | 3000 |     |        0 |        1 |        0
(6 rows)
```

Before this fix, DataFusion collapsed the duplicate `(deptno, job)` grouping set and returned only 4 rows for the same query shape.

```text
+--------+---------+------+-----------------------------------+------------------------------------------+---------------------------------------+---------------------------------------+
| deptno | job     | sal  | sum(duplicate_grouping_sets.comm) | grouping(duplicate_grouping_sets.deptno) | grouping(duplicate_grouping_sets.job) | grouping(duplicate_grouping_sets.sal) |
+--------+---------+------+-----------------------------------+------------------------------------------+---------------------------------------+---------------------------------------+
| 10     | CLERK   | NULL | NULL                              | 0                                        | 0                                     | 1                                     |
| 10     | NULL    | 1300 | NULL                              | 0                                        | 1                                     | 0                                     |
| 20     | MANAGER | NULL | NULL                              | 0                                        | 0                                     | 1                                     |
| 20     | NULL    | 3000 | NULL                              | 0                                        | 1                                     | 0                                     |
+--------+---------+------+-----------------------------------+------------------------------------------+---------------------------------------+---------------------------------------+
```

## What changes are included in this PR?

- Preserve duplicate grouping sets by packing a duplicate ordinal into the high bits of `__grouping_id`, so repeated occurrences of the same grouping set pattern produce distinct execution keys.
- `GROUPING()` now reads the actual `__grouping_id` column type directly from the schema (via `Aggregate::grouping_id_type` rather than inferring bit width from the count of grouping expressions alone. This ensures bitmask literals are correctly sized when duplicate-ordinal bits widen the column type beyond what the expression count would imply.
- `GROUPING()` masks off the ordinal bits before returning the result, so the duplicate-ordinal encoding is invisible to user-facing SQL and semantics remain unchanged.
- Add regression coverage for the duplicate `GROUPING SETS` case in:
  - `datafusion/core/tests/sql/aggregates/basic.rs`
  - `datafusion/sqllogictest/test_files/group_by.slt`

## Are these changes tested?

- `cargo fmt --all`
- `cargo test -p datafusion duplicate_grouping_sets_are_preserved`
- `cargo test -p datafusion-physical-plan grouping_sets_preserve_duplicate_groups`
- `cargo test -p datafusion-physical-plan evaluate_group_by_supports_duplicate_grouping_sets_with_eight_columns`
- PostgreSQL validation against the same query/result shape

## Are there any user-facing changes?

- Yes. Queries that contain duplicate `GROUPING SETS` entries now return the correct duplicated result rows, matching PostgreSQL behavior.

### CODE REVIEW

**Comment by xiedeyantu** [comment]
Hi @alamb , there's another one here.

**Comment by alamb** [comment]
Thanks @xiedeyantu  -- this is great. As before, can you please:
1. File a ticket showing the bug and the postgres behavior as well? This will make it much easier / faster to review these PRs

**Comment by xiedeyantu** [comment]
> Thanks @xiedeyantu -- this is great. As before, can you please:
> 
> 1. File a ticket showing the bug and the postgres behavior as well? This will make it much easier / faster to review these PRs

I completely agree. I may not be very familiar with DataFusion's contribution process yet. Thank you for your thoughtful suggestions. I might add the necessary information in a few days, as I'm currently on vacation.

**Comment by alamb** [comment]
Thank you @xiedeyantu

File: datafusion/core/tests/sql/aggregates/basic.rs [hunk 1]
```diff
@@ -175,6 +175,57 @@ async fn count_aggregated_cube() -> Result<()> {
     Ok(())
 }
 
+#[tokio::test]
+async fn duplicate_grouping_sets_are_preserved() -> Result<()> {
```
Comment (neilconway) [inline datafusion/core/tests/sql/aggregates/basic.rs]: Seems like this duplicates the SLT test that this PR already adds, so I think it can be omitted.

File: datafusion/physical-plan/src/aggregates/mod.rs [hunk 2]
```diff
@@ -1937,15 +1937,53 @@ fn evaluate_optional(
...
+        16
+    } else if group.len() <= 32 {
+        32
+    } else {
+        64
+    };
+    let extra_bits = width_bits - group.len();
+    if extra_bits == 0 && group_ordinal > 0 {
+        return not_impl_err!(
+            "Duplicate grouping sets with more than {} grouping columns are not supported",
```
Comment (neilconway) [inline datafusion/physical-plan/src/aggregates/mod.rs]: If `group.len() == 64`, seems like this will produce an inaccurate error message ("more than 64" vs "64").

File: datafusion/physical-plan/src/aggregates/mod.rs [hunk 3]
```diff
@@ -1972,6 +2010,7 @@ pub fn evaluate_group_by(
     group_by: &PhysicalGroupBy,
     batch: &RecordBatch,
 ) -> Result<Vec<Vec<ArrayRef>>> {
+    let mut group_ordinals: HashMap<Vec<bool>, usize> = HashMap::new();
```
Comment (neilconway) [inline datafusion/physical-plan/src/aggregates/mod.rs]: `HashMap<&[bool], usize>` instead?

File: datafusion/physical-plan/src/aggregates/mod.rs [hunk 4]
```diff
@@ -1937,15 +1937,53 @@ fn evaluate_optional(
         .collect()
 }
 
-fn group_id_array(group: &[bool], batch: &RecordBatch) -> Result<ArrayRef> {
+fn group_id_array(
```
Comment (neilconway) [inline datafusion/physical-plan/src/aggregates/mod.rs:1964]: I think this function would benefit from some commentary: you need to read the implementation pretty carefully to understand the encoded bit format.

File: datafusion/physical-plan/src/aggregates/mod.rs [hunk 5]
```diff
@@ -1937,15 +1937,53 @@ fn evaluate_optional(
...
+        if group_ordinal >= max_group_ordinal {
+            return not_impl_err!(
+                "Duplicate grouping sets exceed the supported grouping id capacity"
+            );
+        }
+    }
     let group_id = group.iter().fold(0u64, |acc, &is_null| {
         (acc << 1) | if is_null { 1 } else { 0 }
     });
+    let group_id = if group.len() == 64 {
```
Comment (neilconway) [inline datafusion/physical-plan/src/aggregates/mod.rs]: Personally, I would opt for tightening the check on `group.len() > 64` to `group.len() >= 64` at the top of the function, which would simplify this logic.

**Review by neilconway — COMMENTED** [review]
It's a little unfortunate that we don't support duplicate grouping sets for 8/16/32 grouping columns. I guess there's no easy way around that?

`grouping_function_on_id` has this code:
```rust
      let grouping_id_column = Expr::Column(Column::from(Aggregate::INTERNAL_GROUPING_ID));
      // The grouping call is exactly our internal grouping id
      if args.len() == group_by_expr_count
          && args
              .iter()
              .rev()
              .enumerate()
              .all(|(idx, expr)| group_by_expr.get(expr) == Some(&idx))
      {
          return Ok(cast(grouping_id_column, DataType::Int32));
      }
```

We probably want to mask out the ordinal bits that this PR adds in to the grouping ID?

**Comment by xiedeyantu** [comment]
@neilconway Thank you for the thorough review. I will complete these modifications this weekend and update the problem description accordingly.

**Comment by xiedeyantu** [comment]
> Thanks @xiedeyantu -- this is great. As before, can you please:
> 
> 1. File a ticket showing the bug and the postgres behavior as well? This will make it much easier / faster to review these PRs

@alamb Apologies for the late reply. I have just updated the problem description in the PR.

**Comment by xiedeyantu** [comment]
> It's a little unfortunate that we don't support duplicate grouping sets for 8/16/32 grouping columns. I guess there's no easy way around that?
> 
> `grouping_function_on_id` has this code:
> 
> ```rust
>       let grouping_id_column = Expr::Column(Column::from(Aggregate::INTERNAL_GROUPING_ID));
>       // The grouping call is exactly our internal grouping id
>       if args.len() == group_by_expr_count
>           && args
>               .iter()
>               .rev()
>               .enumerate()
>               .all(|(idx, expr)| group_by_expr.get(expr) == Some(&idx))
>       {
>           return Ok(cast(grouping_id_column, DataType::Int32));
>       }
> ```
> 
> We probably want to mask out the ordinal bits that this PR adds in to the grouping ID?

@neilconway Apologies for the delayed response. I have reviewed all your thoughtful comments and agree that the approach using high-bit flags indeed has significant flaws. I have now refactored the entire logic and updated the PR description; if you have the time, could you please help review it again? Thank you!

**Comment by xiedeyantu** [comment]
@alamb Could you please take a look and let me know if my current revisions are okay?

**Comment by xiedeyantu** [comment]
@neilconway Could you please help me to have a look again?

File: datafusion/core/src/dataframe/mod.rs [hunk 6]
```diff
@@ -654,14 +654,14 @@ impl DataFrame {
             .aggregate(group_expr, aggr_expr)?
             .build()?;
         let plan = if is_grouping_set {
-            let grouping_id_pos = plan.schema().fields().len() - 1 - aggr_expr_len;
+            let grouping_id_pos = plan.schema().fields().len() - 2 - aggr_expr_len;
```
Comment (neilconway) [inline datafusion/core/src/dataframe/mod.rs]: `2` magic number in a few places is a bit inscrutable. Maybe create a named constant?

**Comment by xiedeyantu** [comment]
> Sorry for the delayed response, @xiedeyantu !
> 
> Thanks for revising this. I'm a bit concerned by the overhead here; we are added a `UInt32` column to _every_ query with grouping sets just to handle a relatively rare situation.
> 
> I actually liked the approach you took in the initial PR better; encoding duplicates into the high bits of the grouping ID is a nice approach. We'd just need to take care to mask out the high bits in the `GROUPING` function, and if possible it would be nice to avoid arbitrary limits like not supporting duplicate grouping sets for queries with 8/16/etc. grouping sets.
> 
> Alternatively we could represent grouping IDs as an index into the list of GROUPING SETS. That would provide an ID without concern for duplicates, and then we'd implement the `GROUPING` function with a `CASE` or similar construct.

@neilconway Thanks for your kind guidance. I have refactored this PR according to your comments. Due to the significant changes, I force-pushed​ the commit. I think this version is better than the previous one. If you have time, please take a look​ again. Sorry for making multiple changes.

File: datafusion/sql/src/unparser/utils.rs [hunk 7]
```diff
@@ -247,6 +247,11 @@ fn find_agg_expr<'a>(agg: &'a Aggregate, column: &Column) -> Result<Option<&'a E
                     )
                 }
                 Ordering::Greater => {
+                    if index < grouping_expr.len() + 1 {
```
Comment (neilconway) [inline datafusion/sql/src/unparser/utils.rs]: This seems like dead code? i.e., index > grouping_expr.len -> index >= (grouping_expr.len + 1)

File: datafusion/physical-plan/src/aggregates/mod.rs [hunk 8]
```diff
@@ -1942,25 +1945,74 @@ fn evaluate_optional(
...
     } else {
-        Ok(Arc::new(UInt64Array::from(vec![group_id; num_rows])))
+        Ok(Arc::new(UInt64Array::from(vec![full_id; num_rows])))
+    }
+}
+
+/// Returns the highest duplicate ordinal across all grouping sets.
+///
+/// The ordinal counts how many times a grouping-set pattern has already
+/// appeared before the current occurrence.  If the same `Vec<bool>` appears
```
Comment (neilconway) [inline datafusion/physical-plan/src/aggregates/mod.rs]: "the current occurrence" doesn't seem to make sense when you look at the function itself, it is talking about the call-site.

File: datafusion/physical-plan/src/aggregates/mod.rs [hunk 9]
```diff
@@ -1942,25 +1945,74 @@ fn evaluate_optional(
...
+/// three times the ordinals are 0, 1, 2 and this function returns 2.
+/// Returns 0 when no grouping set is duplicated.
+fn max_duplicate_ordinal(groups: &[Vec<bool>]) -> usize {
+    let mut counts: HashMap<&Vec<bool>, usize> = HashMap::new();
```
Comment (neilconway) [inline datafusion/physical-plan/src/aggregates/mod.rs]: `HashMap<&[bool], usize>`

File: datafusion/physical-plan/src/aggregates/mod.rs [hunk 10]
```diff
@@ -1942,25 +1945,74 @@ fn evaluate_optional(
...
+    for group in groups {
+        *counts.entry(group).or_insert(0) += 1;
     }
+    counts
+        .values()
+        .copied()
+        .max()
+        .unwrap_or(1)
+        .saturating_sub(1)
```
Comment (neilconway) [inline datafusion/physical-plan/src/aggregates/mod.rs]: `counts.into_values().max().unwrap_or(0).saturating_sub(1)`

File: datafusion/optimizer/src/analyzer/resolve_grouping_function.rs [hunk 11]
```diff
@@ -204,17 +204,26 @@ fn grouping_function_on_id(
             Expr::Literal(ScalarValue::from(value as u64), None)
         }
     };
-
     let grouping_id_column = Expr::Column(Column::from(Aggregate::INTERNAL_GROUPING_ID));
-    // The grouping call is exactly our internal grouping id
+    // The grouping call is exactly our internal grouping id — mask the ordinal
+    // bits (above position `n`) so only the semantic bitmask is visible.
+    let n = group_by_expr_count;
+    // (1 << n) - 1 masks the low n bits.  Use saturating arithmetic to handle n == 0.
```
Comment (neilconway) [inline datafusion/optimizer/src/analyzer/resolve_grouping_function.rs]: The code doesn't use saturating arithmetic?

Comment (neilconway) [reply datafusion/optimizer/src/analyzer/resolve_grouping_function.rs]: Although I don't think `wrapping_sub` is necessary anyway, `n == 0` -> `1 << 0` -> `1`, so it won't underflow.

File: datafusion/optimizer/src/analyzer/resolve_grouping_function.rs [hunk 12]
```diff
@@ -204,17 +204,26 @@ fn grouping_function_on_id(
...
+    let semantic_mask: u64 = if n >= 64 {
+        u64::MAX
+    } else {
+        (1u64 << n).wrapping_sub(1)
+    };
+    let masked_id =
```
Comment (neilconway) [inline datafusion/optimizer/src/analyzer/resolve_grouping_function.rs]: Don't compute this outside the `if` in which it is used.

**Review by neilconway — COMMENTED** [review]
Overall looks good!

**Comment by xiedeyantu** [comment]
@neilconway Thank you very much for your detailed review! I have addressed your comments line by line and included the changes in a single commit. Please take another look to see if everything now aligns with your feedback.

File: datafusion/physical-plan/src/aggregates/mod.rs [hunk 13]
```diff
@@ -397,6 +397,14 @@ impl PhysicalGroupBy {
         self.expr.len() + usize::from(self.has_grouping_set)
     }
 
+    /// Returns the Arrow data type of the `__grouping_id` column.
+    ///
+    /// The type is chosen to be wide enough to hold both the semantic bitmask
+    /// (in the low `n` bits) and the duplicate ordinal (in the high bits).
```
Comment (neilconway) [inline datafusion/physical-plan/src/aggregates/mod.rs]: Not clear what `n` is here based on the context of the function itself.

File: datafusion/optimizer/src/analyzer/resolve_grouping_function.rs [hunk 14]
```diff
@@ -204,17 +204,22 @@ fn grouping_function_on_id(
...
         }
     };
-
     let grouping_id_column = Expr::Column(Column::from(Aggregate::INTERNAL_GROUPING_ID));
-    // The grouping call is exactly our internal grouping id
+    // The grouping call is exactly our internal grouping id — mask the ordinal
+    // bits (above position `n`) so only the semantic bitmask is visible.
+    let n = group_by_expr_count;
+    // (1 << n) - 1 masks the low n bits.
+    let semantic_mask: u64 = if n >= 64 { u64::MAX } else { (1u64 << n) - 1 };
```
Comment (neilconway) [inline datafusion/optimizer/src/analyzer/resolve_grouping_function.rs]: As I suggested before, move this inside the `if`

File: datafusion/expr/src/logical_plan/plan.rs [hunk 15]
```diff
@@ -3737,6 +3686,24 @@ impl PartialOrd for Aggregate {
...
 
+/// Returns the highest duplicate ordinal across all grouping sets in `group_expr`.
+///
+/// The ordinal counts how many times a given grouping set pattern has already
+/// appeared before the current occurrence.  For example, if the same set
+/// appears three times the ordinals are 0, 1, 2 and this function returns 2.
+/// Returns 0 when no grouping set is duplicated.
+fn max_grouping_set_duplicate_ordinal(group_expr: &[Expr]) -> usize {
+    if let Some(Expr::GroupingSet(GroupingSet::GroupingSets(sets))) = group_expr.first() {
+        let mut counts: HashMap<&Vec<Expr>, usize> = HashMap::new();
```
Comment (neilconway) [inline datafusion/expr/src/logical_plan/plan.rs]: `HashMap<&[Expr], usize>`

File: datafusion/sqllogictest/test_files/group_by.slt [hunk 16]
```diff
@@ -5206,6 +5203,41 @@ NULL NULL 1
 statement ok
 drop table t;
 
+# regression: duplicate grouping sets must not be collapsed into one
```
Comment (neilconway) [inline datafusion/sqllogictest/test_files/group_by.slt:5206]: I think it's worth having a test case for the situation where adding the duplicate ordinal widens the size of the grouping ID field, that's a bit tricky.

File: datafusion/expr/src/logical_plan/plan.rs [hunk 17]
```diff
@@ -3737,6 +3686,24 @@ impl PartialOrd for Aggregate {
     }
 }
 
+/// Returns the highest duplicate ordinal across all grouping sets in `group_expr`.
+///
+/// The ordinal counts how many times a given grouping set pattern has already
+/// appeared before the current occurrence.  For example, if the same set
```
Comment (neilconway) [inline datafusion/expr/src/logical_plan/plan.rs]: I mentioned this before but "the current occurrence" is not well-defined in this context. Something like this instead:

```
/// The ordinal for each occurrence of a grouping set pattern is its 0-based index among
/// identical entries. For example, if the same set appears three times, the ordinals are
/// 0, 1, 2 and this function returns 2.
```

**Comment by xiedeyantu** [comment]
@neilconway I have made the changes based on the comments; could you please review it again? Thank you!

File: datafusion/physical-plan/src/aggregates/mod.rs [hunk 18]
```diff
@@ -1972,6 +2026,8 @@ pub fn evaluate_group_by(
     group_by: &PhysicalGroupBy,
     batch: &RecordBatch,
 ) -> Result<Vec<Vec<ArrayRef>>> {
+    let max_ordinal = max_duplicate_ordinal(&group_by.groups);
+    let mut ordinal_per_pattern: HashMap<&Vec<bool>, usize> = HashMap::new();
```
Comment (neilconway) [inline datafusion/physical-plan/src/aggregates/mod.rs]: `HashMap<&[bool], usize>`

File: datafusion/optimizer/src/analyzer/resolve_grouping_function.rs [hunk 19]
```diff
@@ -207,17 +207,21 @@ fn grouping_function_on_id(
             Expr::Literal(ScalarValue::from(value as u64), None)
         }
     };
```
Comment (neilconway) [inline datafusion/optimizer/src/analyzer/resolve_grouping_function.rs]: It's a little unfortunate that we'll undercount the required bit width here if there are duplicates in `group_by_expr`. Would it be easy to calculate the true width required, including dups?

File: datafusion/optimizer/src/analyzer/resolve_grouping_function.rs [hunk 20]
```diff
@@ -207,17 +207,21 @@ fn grouping_function_on_id(
...
             .iter()
             .rev()
             .enumerate()
             .all(|(idx, expr)| group_by_expr.get(expr) == Some(&idx))
     {
-        return Ok(cast(grouping_id_column, DataType::Int32));
+        let n = group_by_expr_count;
+        // Mask the ordinal bits above position `n` so only the semantic bitmask is visible.
+        // (1 << n) - 1 masks the low n bits.
+        let semantic_mask: u64 = if n >= 64 { u64::MAX } else { (1u64 << n) - 1 };
```
Comment (neilconway) [inline datafusion/optimizer/src/analyzer/resolve_grouping_function.rs]: `n >= 64` is rejected earlier, right? I wonder if it would be cleaner to just assert `n < 64` and then remove the conditional.

**Review by neilconway — APPROVED** [review]
A few minor nits but overall looks good!

File: datafusion/physical-plan/src/aggregates/mod.rs (hunk 4 above)
Comment (alamb) [reply datafusion/physical-plan/src/aggregates/mod.rs:1964]: the new comments help a lot

**Comment by neilconway** [comment]
@xiedeyantu Can you update the PR description? It still talks about the old approach.

**Comment by xiedeyantu** [comment]
@neilconway @alamb Thank you for the review! I've made revisions based on the comments. Please help me take another look.

File: datafusion/optimizer/src/analyzer/resolve_grouping_function.rs [hunk 21]
```diff
@@ -184,40 +191,43 @@ fn validate_args(
...
 
+    // Use the actual __grouping_id column type to size literals correctly. This
+    // accounts for duplicate-ordinal bits that `Aggregate::grouping_id_type`
+    // packs into the high bits of the column, which a simple count of grouping
+    // expressions would miss.
+    let literal = |value: usize| match &grouping_id_type {
+        DataType::UInt8 => Expr::Literal(ScalarValue::from(value as u8), None),
+        DataType::UInt16 => Expr::Literal(ScalarValue::from(value as u16), None),
+        DataType::UInt32 => Expr::Literal(ScalarValue::from(value as u32), None),
+        _ => Expr::Literal(ScalarValue::from(value as u64), None),
```
Comment (neilconway) [inline datafusion/optimizer/src/analyzer/resolve_grouping_function.rs]: Seems safer to have an explicit match arm for `DataType::UInt64` and then a fallthrough that raises an error message.

Comment (xiedeyantu) [reply datafusion/optimizer/src/analyzer/resolve_grouping_function.rs]: done!

**Comment by alamb** [comment]
Thank you @xiedeyantu and @neilconway
