### PR TITLE
fix: overcounting of memory in first/last.

### LINKED ISSUE #15923: overcounting of memory in first/last.
### Describe the bug

When aggregating first/last list over a column of lists, the first/last
accumulators hold the necessary scalar value as is, which points to the
list in the original input buffer.

This results in two issues:

1) We prevent the deallocation of the input arrays which might be
significantly larger than the single value we want to hold.

2) During aggreagtion with groups, many accumulators receive slices of the
same input buffer, resulting in all held values pointing to this buffer.
Then, when calculating the size of all accumulators we count the buffer
multiple times, since each accumulator considers it to be part of its own
allocation.

While 1 can be tolerated, 2 can easily result in an OOM for a small input with a few thousand groups.

### PR DESCRIPTION
**Pull request by ashdnazg**
## Which issue does this PR close?
- Closes #15923.

## Rationale for this change

When aggregating first/last list over a column of lists, the first/last
accumulators hold the necessary scalar value as is, which points to the
list in the original input buffer.

This results in two issues:

1) We prevent the deallocation of the input arrays which might be
significantly larger than the single value we want to hold.

2) During aggreagtion with groups, many accumulators receive slices of the
same input buffer, resulting in all held values pointing to this buffer.
Then, when calculating the size of all accumulators we count the buffer
multiple times, since each accumulator considers it to be part of its own
allocation.

## What changes are included in this PR?

The PR copies/compacts scalar values held by the first/last operators, such that they no longer hold the entire input buffer, thereby solving both 1 & 2.

## Are these changes tested?

Two tests are added.

## Are there any user-facing changes?

There's a new `compact` function, which might or might not be desired to be `pub`. I thought it might be useful somewhere else, but YMMV.

### CODE REVIEW

File: datafusion/common/src/scalar/mod.rs [hunk 1]
```diff
@@ -3415,6 +3415,100 @@ impl ScalarValue {
...
+            | ScalarValue::LargeBinary(_)
+            | ScalarValue::BinaryView(_) => (),
+            ScalarValue::FixedSizeList(arr) => {
+                let taken = arrow::compute::take(
+                    arr.as_ref(),
+                    &Int32Array::from_iter_values([0]),
+                    None,
+                )
+                .unwrap();
+                *Arc::make_mut(arr) = cast::as_fixed_size_list_array(&taken).clone();
```
Comment (ashdnazg) [inline datafusion/common/src/scalar/mod.rs:3472]: It's probably possible to make it more performant, but I don't want to invest into that unless we know it's necessary.

Comment (alamb) [reply datafusion/common/src/scalar/mod.rs:3472]: I think you might be able to use the very recently added `ScalarValue::force_copy` that @chenkovsky added in https://github.com/apache/datafusion/pull/15667 (like 10 minutes ago):

https://github.com/apache/datafusion/blob/7e898620461a4580422a63688351325e3eeb7e89/datafusion/common/src/scalar/mod.rs#L3441

It does the same thing for the same reason as I understand

Comment (alamb) [reply datafusion/common/src/scalar/mod.rs:3472]: though perhaps this approach is better (modify the existing scalar rather than force a copy 🤔 )

In any event I think we should not have both functions if we can avoid it

**Review by alamb — COMMENTED** [review]
Thank you @ashdnazg

File: datafusion/common/src/scalar/mod.rs (hunk 1 above)
Comment (ashdnazg) [reply datafusion/common/src/scalar/mod.rs:3472]: @chenkovsky copying is not the goal, though. If the array you're pointing to is already compact, you don't lose anything by holding a single copy of it instead of multiple.

As far as I understand, there's no reason to force clone all the non-array scalars in min/max and first/last.

Comment (ashdnazg) [reply datafusion/common/src/scalar/mod.rs:3472]: Definitely, I'm not contending that. I'm just saying there's no point in cloning string/byte vectors etc.
Is your goal to save memory or to not hold the input buffer?
Because if the array is already compact, why is it bad to hold the input buffer?

In any case, I am switching to using your `copy_array_data`, but keeping the in-place nature of compact and not cloning what we don't need.

File: datafusion/functions-aggregate/src/min_max.rs [hunk 2]
```diff
@@ -645,19 +645,29 @@ fn min_max_batch_struct(array: &ArrayRef, ordering: Ordering) -> Result<ScalarVa
...
 }
 
 macro_rules! min_max_struct {
     ($VALUE:expr, $DELTA:expr, $OP:ident) => {{
         if $VALUE.is_null() {
-            $DELTA.clone()
+            let mut delta_copy = $DELTA.clone();
+            // When the new value won we want to compact it to
+            // avoid storing the entire input
+            delta_copy.compact();
```
Comment (ashdnazg) [inline datafusion/functions-aggregate/src/min_max.rs:658]: I moved compaction here so it's only done if we're definitely going to keep a reference to the new value.

**Comment by ashdnazg** [comment]
@alamb @chenkovsky 
I pushed a version that uses `copy_array_data` to make sure `take` isn't doing anything funny (looking at the code, at the moment it doesn't, but the docs promise nothing). I also replaced the `force_clone()` calls with `compact()`.

One could improve the `compact` function in the future to avoid copying if it's unnecessary, but it's difficult to do this correctly (you need to go recursively into all arrays, offsets and buffers), so I decided it's probably not worth the effort at the moment.

File: datafusion/common/src/scalar/mod.rs [hunk 3]
```diff
@@ -3435,49 +3435,80 @@ impl ScalarValue {
                 .sum::<usize>()
     }
 
-    /// Performs a deep clone of the ScalarValue, creating new copies of all nested data structures.
-    /// This is different from the standard `clone()` which may share data through `Arc`.
-    /// Aggregation functions like `max` will cost a lot of memory if the data is not cloned.
-    pub fn force_clone(&self) -> Self {
+    /// Compacts the allocation referenced by `self` to the minimum, copying the data if
```
Comment (alamb) [inline datafusion/common/src/scalar/mod.rs:3438]: 👍

File: datafusion/functions-aggregate/src/first_last.rs [hunk 4]
```diff
@@ -827,9 +827,13 @@ impl FirstValueAccumulator {
     }
 
     // Updates state with the values in the given row.
-    fn update_with_new_row(&mut self, row: &[ScalarValue]) {
-        self.first = row[0].clone();
-        self.orderings = row[1..].to_vec();
+    fn update_with_new_row(&mut self, mut row: Vec<ScalarValue>) {
+        row.iter_mut().for_each(|s| {
```
Comment (alamb) [inline datafusion/functions-aggregate/src/first_last.rs:831]:
```suggestion
        // Ensure any Array based scalars hold have a single value to reduce memory pressure
        row.iter_mut().for_each(|s| {
```

File: datafusion/functions-aggregate/src/first_last.rs [hunk 5]
```diff
@@ -1226,9 +1232,13 @@ impl LastValueAccumulator {
     }
 
     // Updates state with the values in the given row.
-    fn update_with_new_row(&mut self, row: &[ScalarValue]) {
-        self.last = row[0].clone();
-        self.orderings = row[1..].to_vec();
+    fn update_with_new_row(&mut self, mut row: Vec<ScalarValue>) {
+        row.iter_mut().for_each(|s| {
```
Comment (alamb) [inline datafusion/functions-aggregate/src/first_last.rs:1236]:
```suggestion
        // Ensure any Array based scalars hold have a single value to reduce memory pressure
        row.iter_mut().for_each(|s| {
```

File: datafusion/functions-aggregate/src/first_last.rs [hunk 6]
```diff
@@ -1772,4 +1790,60 @@ mod tests {
...
+        let size2 = size_after_batch(&[Arc::new(batch2)])?;
+        assert_eq!(size1, size2);
+
+        Ok(())
+    }
+
+    #[test]
+    fn test_last_list_acc_size() -> Result<()> {
+        fn size_after_batch(values: &[ArrayRef]) -> Result<usize> {
+            let mut last_accumulator = FirstValueAccumulator::try_new(
```
Comment (alamb) [inline datafusion/functions-aggregate/src/first_last.rs:1825]: I think this is the wrong accumulator:

```suggestion
            let mut last_accumulator = LastValueAccumulator::try_new(
```

File: datafusion/functions-aggregate/src/min_max.rs (hunk 2 above)
Comment (alamb) [reply datafusion/functions-aggregate/src/min_max.rs:658]: it would be great to try and avoid the duplication in these min/max macros anyways (and instead use an Array)  -- no changes are neede din this PR, I am just observing

**Review by alamb — COMMENTED** [review]
Thanks @ashdnazg  -- this looks good to me. The only potential issue I see is that the typo in the test -- otherwise it looks good to me. I'll fire off some benchmarks to doubel check

**Comment by alamb** [comment]
🤖 `./gh_compare_branch.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/gh_compare_branch.sh) Running
Linux aal-dev 6.11.0-1013-gcp #13~24.04.1-Ubuntu SMP Wed Apr  2 16:34:16 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing first-last (db511504d776f2c5369b9e454b801881d83299f3) to f12ba602e3fcb3238229fccf8e419ec86ca74b1b [diff](https://github.com/apache/datafusion/compare/f12ba602e3fcb3238229fccf8e419ec86ca74b1b..db511504d776f2c5369b9e454b801881d83299f3)
Benchmarks: tpch_mem clickbench_partitioned clickbench_extended
Results will be posted here when complete

File: datafusion/functions-aggregate/src/first_last.rs (hunk 6 above)
Comment (eshed-flarion) [reply datafusion/functions-aggregate/src/first_last.rs:1825]: :facepalm:

**Comment by eshed-flarion** [comment]
@alamb fixed.

**Comment by ashdnazg** [comment]
@alamb fixed.

**Review by alamb — APPROVED** [review]
Thanks @ashdnazg  -- assuming the performance tests look good I think this one looks good

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
Comparing HEAD and first-last
--------------------
Benchmark clickbench_extended.json
--------------------
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ Query        ┃       HEAD ┃ first-last ┃    Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ QQuery 0     │  1963.07ms │  1949.75ms │ no change │
│ QQuery 1     │   744.70ms │   723.55ms │ no change │
│ QQuery 2     │  1495.89ms │  1434.26ms │ no change │
│ QQuery 3     │   708.87ms │   702.80ms │ no change │
│ QQuery 4     │  1495.21ms │  1475.90ms │ no change │
│ QQuery 5     │ 15444.08ms │ 15369.43ms │ no change │
│ QQuery 6     │  2119.75ms │  2059.58ms │ no change │
│ QQuery 7     │  2118.53ms │  2139.73ms │ no change │
└──────────────┴────────────┴────────────┴───────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Benchmark Summary         ┃            ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ Total Time (HEAD)         │ 26090.11ms │
│ Total Time (first-last)   │ 25855.01ms │
│ Average Time (HEAD)       │  3261.26ms │
│ Average Time (first-last) │  3231.88ms │
│ Queries Faster            │          0 │
│ Queries Slower            │          0 │
│ Queries with No Change    │          8 │
└───────────────────────────┴────────────┘
--------------------
Benchmark clickbench_partitioned.json
--------------------
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Query        ┃       HEAD ┃ first-last ┃        Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ QQuery 0     │     2.64ms │     2.67ms │     no change │
│ QQuery 1     │    37.81ms │    39.39ms │     no change │
│ QQuery 2     │    92.74ms │    94.23ms │     no change │
│ QQuery 3     │   100.07ms │   101.29ms │     no change │
│ QQuery 4     │   600.54ms │   588.44ms │     no change │
│ QQuery 5     │   861.94ms │   858.08ms │     no change │
│ QQuery 6     │     2.23ms │     2.29ms │     no change │
│ QQuery 7     │    45.52ms │    44.71ms │     no change │
│ QQuery 8     │   924.83ms │   907.51ms │     no change │
│ QQuery 9     │  1205.60ms │  1181.79ms │     no change │
│ QQuery 10    │   267.26ms │   267.05ms │     no change │
│ QQuery 11    │   306.34ms │   302.54ms │     no change │
│ QQuery 12    │   929.03ms │   913.76ms │     no change │
│ QQuery 13    │  1384.16ms │  1252.06ms │ +1.11x faster │
│ QQuery 14    │   856.10ms │   834.82ms │     no change │
│ QQuery 15    │   821.97ms │   823.12ms │     no change │
│ QQuery 16    │  1756.20ms │  1722.45ms │     no change │
│ QQuery 17    │  1630.31ms │  1599.56ms │     no change │
│ QQuery 18    │  3097.86ms │  3093.14ms │     no change │
│ QQuery 19    │    85.78ms │    86.04ms │     no change │
│ QQuery 20    │  1166.88ms │  1135.45ms │     no change │
│ QQuery 21    │  1356.47ms │  1329.31ms │     no change │
│ QQuery 22    │  2297.91ms │  2213.79ms │     no change │
│ QQuery 23    │  8573.79ms │  8443.98ms │     no change │
│ QQuery 24    │   480.54ms │   476.49ms │     no change │
│ QQuery 25    │   401.48ms │   388.76ms │     no change │
│ QQuery 26    │   552.16ms │   535.47ms │     no change │
│ QQuery 27    │  1629.15ms │  1586.57ms │     no change │
│ QQuery 28    │ 12717.20ms │ 12700.24ms │     no change │
│ QQuery 29    │   538.65ms │   536.55ms │     no change │
│ QQuery 30    │   843.33ms │   828.57ms │     no change │
│ QQuery 31    │   885.04ms │   860.23ms │     no change │
│ QQuery 32    │  2665.26ms │  2709.90ms │     no change │
│ QQuery 33    │  3371.18ms │  3385.10ms │     no change │
│ QQuery 34    │  3418.73ms │  3425.83ms │     no change │
│ QQuery 35    │  1285.15ms │  1300.10ms │     no change │
│ QQuery 36    │   128.09ms │   134.00ms │     no change │
│ QQuery 37    │    60.70ms │    57.72ms │     no change │
│ QQuery 38    │   126.54ms │   129.32ms │     no change │
│ QQuery 39    │   203.13ms │   200.80ms │     no change │
│ QQuery 40    │    47.73ms │    50.11ms │     no change │
│ QQuery 41    │    47.36ms │    48.22ms │     no change │
│ QQuery 42    │    41.02ms │    40.05ms │     no change │
└──────────────┴────────────┴────────────┴───────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Benchmark Summary         ┃            ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ Total Time (HEAD)         │ 57846.45ms │
│ Total Time (first-last)   │ 57231.51ms │
│ Average Time (HEAD)       │  1345.27ms │
│ Average Time (first-last) │  1330.97ms │
│ Queries Faster            │          1 │
│ Queries Slower            │          0 │
│ Queries with No Change    │         42 │
└───────────────────────────┴────────────┘
--------------------
Benchmark tpch_mem_sf1.json
--------------------
┏━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃ Query        ┃     HEAD ┃ first-last ┃       Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━┩
│ QQuery 1     │ 123.84ms │   125.41ms │    no change │
│ QQuery 2     │  23.86ms │    23.94ms │    no change │
│ QQuery 3     │  35.92ms │    35.52ms │    no change │
│ QQuery 4     │  20.78ms │    20.97ms │    no change │
│ QQuery 5     │  55.93ms │    57.19ms │    no change │
│ QQuery 6     │  12.48ms │    12.34ms │    no change │
│ QQuery 7     │ 104.35ms │    99.48ms │    no change │
│ QQuery 8     │  26.22ms │    27.74ms │ 1.06x slower │
│ QQuery 9     │  64.07ms │    65.57ms │    no change │
│ QQuery 10    │  56.51ms │    58.68ms │    no change │
│ QQuery 11    │  13.63ms │    13.24ms │    no change │
│ QQuery 12    │  44.21ms │    44.90ms │    no change │
│ QQuery 13    │  30.10ms │    31.23ms │    no change │
│ QQuery 14    │  10.31ms │     9.91ms │    no change │
│ QQuery 15    │  24.78ms │    25.52ms │    no change │
│ QQuery 16    │  22.75ms │    23.48ms │    no change │
│ QQuery 17    │ 100.73ms │   101.60ms │    no change │
│ QQuery 18    │ 229.94ms │   237.21ms │    no change │
│ QQuery 19    │  26.85ms │    27.67ms │    no change │
│ QQuery 20    │  38.48ms │    39.33ms │    no change │
│ QQuery 21    │ 170.36ms │   168.65ms │    no change │
│ QQuery 22    │  16.74ms │    16.72ms │    no change │
└──────────────┴──────────┴────────────┴──────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ Benchmark Summary         ┃           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ Total Time (HEAD)         │ 1252.84ms │
│ Total Time (first-last)   │ 1266.27ms │
│ Average Time (HEAD)       │   56.95ms │
│ Average Time (first-last) │   57.56ms │
│ Queries Faster            │         0 │
│ Queries Slower            │         1 │
│ Queries with No Change    │        21 │
└───────────────────────────┴───────────┘
```


</p>
</details>

**Comment by alamb** [comment]
Thanks again @ashdnazg
