### PR TITLE
fix: Support dictionary type in parquet metadata statistics.

### LINKED ISSUE #11145: Support `Dictionary` in Parquet Metadata Statistics
### Describe the bug

When a column has data type in `Dictionary`, the parquet metadata statistics returns `Exact(Dictionary(Int32, Utf8(NULL)))` for min and max values

### To Reproduce

Run the test below in this file:
https://github.com/apache/datafusion/blob/8216e32e87b2238d8814fe16215c8770d6c327c8/datafusion/core/src/datasource/file_format/parquet.rs#L1363

```rs
    #[tokio::test]
    async fn test_statistics_from_parquet_metadat_dictionary() -> Result<()> {
        // Data for column c_dic: ["a", "b", "c", "d"]
        let values = StringArray::from_iter_values(["a", "b", "c", "d"]);
        let keys = Int32Array::from_iter_values([0, 0, 1, 2]);
        let dic_array =
            DictionaryArray::<Int32Type>::try_new(keys, Arc::new(values)).unwrap();
        let boxed_array: Box<dyn arrow_array::Array> = Box::new(dic_array);
        let c_dic: ArrayRef = Arc::from(boxed_array);
        // Define the schema
        let field = Field::new(
            "c_dic",
            DataType::Dictionary(Box::new(DataType::Int32), Box::new(DataType::Utf8)),
            false,
        );
        let schema = Schema::new(vec![field]);
        // Create the RecordBatch
        let batch1 = RecordBatch::try_new(Arc::new(schema), vec![c_dic]).unwrap();

        // Use store_parquet to write each batch to its own file
        // . batch1 written into first file and includes:
        //    - column c_dic that has 4 rows with no null. Stats min and max of string column is missing for this test even the column has values
        let store = Arc::new(LocalFileSystem::new()) as _;
        let (files, _file_names) = store_parquet(vec![batch1], false).await?;

        let state = SessionContext::new().state();
        let format = ParquetFormat::default();
        let schema = format.infer_schema(&state, &store, &files).await.unwrap();

        // Fetch statistics for first file
        let pq_meta = fetch_parquet_metadata(store.as_ref(), &files[0], None).await?;
        let stats = statistics_from_parquet_meta(&pq_meta, schema.clone()).await?;
        assert_eq!(stats.num_rows, Precision::Exact(4));

        // column c_dic
        let c_dic_stats = &stats.column_statistics[0];

        let null_dic: ScalarValue = ScalarValue::Dictionary(
            Box::new(DataType::Int32),
            Box::new(ScalarValue::Utf8(None)),
        );

        assert_eq!(c_dic_stats.null_count, Precision::Exact(0));
        // BUG:
        // Expect:
        //   Exact(Dictionary(Int32, Utf8("a")))
        // Got:
        //   Exact(Dictionary(Int32, Utf8(NULL)))
        assert_eq!(c_dic_stats.max_value, Precision::Exact(null_dic.clone()));
        // BUG:
        // Expect:
        //   Exact(Dictionary(Int32, Utf8("d")))
        // Got:
        //   Exact(Dictionary(Int32, Utf8(NULL)))
        assert_eq!(c_dic_stats.min_value, Precision::Exact(null_dic.clone()));

        Ok(())
    }
```

### Expected behavior

Expect statistics to show the min and max values. For the reproducer given above, I'm expecting to get: 
- `max_value`: `Exact(Dictionary(Int32, Utf8("a")))`
- `min_value`: `Exact(Dictionary(Int32, Utf8("d")))`

### Additional context

The underlying statistics extraction code should have no problems extracting statistics from Dictionary columns

The code is 

https://github.com/apache/datafusion/blob/7e49ccf3dd3408bc9c4adb86f070d1e3d1f4c1e2/datafusion/core/src/datasource/physical_plan/parquet/statistics.rs#L452-L454

And the tests are here:

https://github.com/apache/datafusion/blob/7e49ccf3dd3408bc9c4adb86f070d1e3d1f4c1e2/datafusion/core/tests/parquet/arrow_statistics.rs#L1729-L1768

I wonder if something about the code that summarizes the statistics across row groups https://github.com/apache/datafusion/blob/7e49ccf3dd3408bc9c4adb86f070d1e3d1f4c1e2/datafusion/core/src/datasource/file_format/parquet.rs#L468-L495

doesn't handle dictionaries correctly 🤔

### PR DESCRIPTION
**Pull request by efredine**
## Which issue does this PR close?

Closes #11145.

## What changes are included in this PR?

Modifies `create_max_min_accs` to instantiate accumulators for unpacked data - the value DataType of the Dictionary. 

This bug is very similar to a previous bug that impacted the Min/Max aggregate functions. https://github.com/apache/datafusion/pull/1235

In addition, the `min_max_aggregate_data_type` fn is copied from https://github.com/apache/datafusion/blob/8216e32e87b2238d8814fe16215c8770d6c327c8/datafusion/physical-expr/src/aggregate/min_max.rs#L63-L73

I'm unsure if copying the function is the right thing to do in order to prevent coupling between the crates or if it should be moved to some core crate? It also seems like the dedicated min and max functions are to be refactored into a user defined functions?

## Are these changes tested?

Yes - a new test has been added.

## Are there any user-facing changes?

Currently implemented so the column statistics are returned as an unpacked type. So for `DataType::Dictionary(Int32, Utf8)` the min or max value is returned as `Exact(Utf8("a"))`. Would it be better to return it as `Exact(Dictionary(Int32, Utf8("a")))`? I'm unsure what the previous implementation would have returned and whether or not it was correct. But it's possible that returning it as an unpacked type would be a breaking change if it previously returned it as a Dictionary type. 

Happy to change the implementation to return a Dictionary type. I'm just unsure which offers the best experience.

### CODE REVIEW

File: datafusion/core/src/datasource/file_format/parquet.rs [hunk 1]
```diff
@@ -1439,6 +1441,57 @@ mod tests {
...
 
+    #[tokio::test]
+    async fn test_statistics_from_parquet_metadata_dictionary() -> Result<()> {
+        // Data for column c_dic: ["a", "b", "c", "d"]
+        let values = StringArray::from_iter_values(["a", "b", "c", "d"]);
+        let keys = Int32Array::from_iter_values([0, 0, 1, 2]);
+        let dic_array =
+            DictionaryArray::<Int32Type>::try_new(keys, Arc::new(values)).unwrap();
+        let boxed_array: Box<dyn arrow_array::Array> = Box::new(dic_array);
+        let c_dic: ArrayRef = Arc::from(boxed_array);
```
Comment (alamb) [inline datafusion/core/src/datasource/file_format/parquet.rs:1452]: I think you can make `c_dic` more simply here via

```rust
let c_dic: ArrayRef = Arc::new(dic_array)
```
The rules for using Arc and typcasting are somewhat fiddly

File: datafusion/core/src/datasource/file_format/parquet.rs [hunk 2]
```diff
@@ -1439,6 +1441,57 @@ mod tests {
...
+            false,
+        );
+        let schema = Schema::new(vec![field]);
+        // Create the RecordBatch
+        let batch1 = RecordBatch::try_new(Arc::new(schema), vec![c_dic]).unwrap();
+
+        // Use store_parquet to write each batch to its own file
+        // . batch1 written into first file and includes:
+        //    - column c_dic that has 4 rows with no null. Stats min and max of string column is missing for this test even the column has values
+        let store = Arc::new(LocalFileSystem::new()) as _;
```
Comment (alamb) [inline datafusion/core/src/datasource/file_format/parquet.rs:1467]: what is this needed for?

File: datafusion/core/src/datasource/file_format/parquet.rs [hunk 3]
```diff
@@ -1439,6 +1441,57 @@ mod tests {
...
+
+        // Define the schema
+        let field = Field::new(
+            "c_dic",
+            DataType::Dictionary(Box::new(DataType::Int32), Box::new(DataType::Utf8)),
+            false,
+        );
+        let schema = Schema::new(vec![field]);
+        // Create the RecordBatch
+        let batch1 = RecordBatch::try_new(Arc::new(schema), vec![c_dic]).unwrap();
```
Comment (alamb) [inline datafusion/core/src/datasource/file_format/parquet.rs:1462]: You can probably make this much shorter by using https://docs.rs/arrow/latest/arrow/record_batch/struct.RecordBatch.html#method.try_from_iter

Here is an example: https://github.com/apache/datafusion/blob/7a7797c891057c783680bade813d4ba2a49344b7/datafusion-examples/examples/expr_api.rs#L116

The benefit is that it will make the schema for you from the `ArrayRef`s (which already know their type)

There is also an example of this earlier in this file that might help https://github.com/apache/datafusion/pull/11169/files#diff-0761860da9ee8df947358b2589079cbf64690c6228cc27dd41a21fab27400f75R1361

**Review by alamb — APPROVED** [review]
Thank you @efredine  -- I think this PR fixes the bug 🙏 

I left some comments about how to improve the tests -- let me know what you think. I think we can also improve the test in a follow on PR as well

File: datafusion/core/src/datasource/file_format/parquet.rs [hunk 4]
```diff
@@ -1439,6 +1441,57 @@ mod tests {
         Ok(())
     }
 
+    #[tokio::test]
+    async fn test_statistics_from_parquet_metadata_dictionary() -> Result<()> {
+        // Data for column c_dic: ["a", "b", "c", "d"]
+        let values = StringArray::from_iter_values(["a", "b", "c", "d"]);
+        let keys = Int32Array::from_iter_values([0, 0, 1, 2]);
```
Comment (appletreeisyellow) [inline datafusion/core/src/datasource/file_format/parquet.rs:1448]:
```suggestion
        let keys = Int32Array::from_iter_values([0, 1, 2, 3]);
```
My bad that in my original test example I gave these confusing dictionary keys 😅 I think `0, 1, 2, 3` makes more sense since the dictionary values are `a, b, c, d` -- which in different values

File: datafusion/core/src/datasource/file_format/parquet.rs [hunk 5]
```diff
@@ -1439,6 +1441,57 @@ mod tests {
...
+        let stats = statistics_from_parquet_meta(&pq_meta, schema.clone()).await?;
+        assert_eq!(stats.num_rows, Precision::Exact(4));
+
+        // column c_dic
+        let c_dic_stats = &stats.column_statistics[0];
+
+        assert_eq!(c_dic_stats.null_count, Precision::Exact(0));
+        assert_eq!(
+            c_dic_stats.max_value,
+            Precision::Exact(Utf8(Some("c".into())))
```
Comment (appletreeisyellow) [inline datafusion/core/src/datasource/file_format/parquet.rs:1485]:
```suggestion
            Precision::Exact(Utf8(Some("d".into())))
```

To avoid any confusion, with the new dictionary keys, the max value is `"d"`

File: datafusion/core/src/datasource/file_format/parquet.rs (hunk 2 above)
Comment (appletreeisyellow) [reply datafusion/core/src/datasource/file_format/parquet.rs:1467]: This was from my original test example: https://github.com/apache/datafusion/issues/11145#issue-2378475063

I believe `store` is used to mimic an object store so that we can get table schema from a parquet file

**Review by appletreeisyellow — APPROVED** [review]
Thank you for fixing it! @efredine 💯

I left comments in the test to avoid confusions

**Comment by efredine** [comment]
Thanks @alamb @appletreeisyellow - I should have reviewed the tests more closely - thanks for the feedback. I will make the adjustments now.

File: datafusion/core/src/datasource/file_format/parquet.rs (hunk 3 above)
Comment (efredine) [reply datafusion/core/src/datasource/file_format/parquet.rs:1462]: Thanks for this - I think it will also turn out to be useful in simplifying some other tests I'm writing.

**Review by alamb — APPROVED** [review]
Thanks again @efredine  and @appletreeisyellow
