### PR TITLE
Fix: Align sort_merge_join filter output with join schema to fix right-anti panic

### LINKED ISSUE #18787: Panic when having right anti join with filter in `sort_merge_join` and different number of columns between each side
**I think we should add also fuzz tests for all join types with sort merge join with filter columns and different amount of columns and to add assertion in the test that sort merge join is actually used** 

### Describe the bug

Having panic:
```
thread 'tokio-runtime-worker' panicked at /Users/rluvaton/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arrow-array-56.2.0/src/record_batch.rs:609:22:
index out of bounds: the len is 2 but the index is 2
stack backtrace:
   0: __rustc::rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: arrow_array::record_batch::RecordBatch::column
   4: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   5: arrow_select::concat::concat_batches
   6: <datafusion_physical_plan::joins::sort_merge_join::stream::SortMergeJoinStream as futures_core::stream::Stream>::poll_next
   7: datafusion_common_runtime::trace_utils::trace_future::{{closure}}
   8: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   9: tokio::runtime::task::core::Core<T,S>::poll
  10: tokio::runtime::task::harness::Harness<T,S>::poll
  11: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  12: tokio::runtime::scheduler::multi_thread::worker::Context::run
  13: tokio::runtime::context::scoped::Scoped<T>::set
  14: tokio::runtime::context::runtime::enter_runtime
  15: tokio::runtime::scheduler::multi_thread::worker::run
  16: tokio::runtime::task::core::Core<T,S>::poll
  17: tokio::runtime::task::harness::Harness<T,S>::poll
  18: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### To Reproduce

```console
$ RUST_BACKTRACE=1 datafusion-cli
DataFusion CLI v50.3.0
> set datafusion.optimizer.prefer_hash_join = false;
0 row(s) fetched.
Elapsed 0.001 seconds.

> select * from (
with
t1 as (
    select 31 a, 32 b union all
    select 31 a, 33 b
),
t2 as (
    select 31 a, 32 b, 108 c union all
    select 31 a, 35 b, 109 c
)
select t2.* from t1 right anti join t2 on t1.a = t2.a and t1.b = t2.b and t1.b <= t2.c
) order by 1, 2;


thread 'tokio-runtime-worker' panicked at /Users/rluvaton/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arrow-array-56.2.0/src/record_batch.rs:609:22:
index out of bounds: the len is 2 but the index is 2
stack backtrace:
...
```

### Expected behavior

to not panic

### Additional context

While reviewing the PR below
- #18772

I checked about filter in sort merge join with different amount of columns for other join types and found this, so thank you @tglanz

### PR DESCRIPTION
**Pull request by kumarUjjawal**
## Which issue does this PR close?

- Closes #18787.

## Rationale for this change

Sort-merge joins assumed both inputs had the same width when applying filter results. With different column counts (like right-anti joins) we built batches that no longer matched the output schema, so Arrow panicked during concat_batches.

## What changes are included in this PR?

- Fix the null-row and filtered-row builders in SortMergeJoinStream to slice the streamed vs buffered columns using the correct widths, keeping every batch consistent with self.schema.
- Merge the semi/anti projection branch so it always projects the streamed-side columns expected in the output.

## Are these changes tested?

Manual testing and ran previous tests. 

Screenshot 2025-11-18 at 5 04 20 PM

### CODE REVIEW

**Comment by kumarUjjawal** [comment]
hmm, why is the test failing?

**Comment by rluvaton** [comment]
Looks like this include fixes created by, let's wait for it to be merged
- #18772 

Also, once merged can you update the fuzz tests for join:
similar to what he added here but add the for loop to the other tests as well:
`test_right_semi_join_1k_filtered`, `test_right_anti_join_1k_filtered`, `test_right_anti_join_1k_binary`, `test_right_anti_join_1k_binary_filtered`
https://github.com/apache/datafusion/pull/18772/files#diff-f8330244c576c142337679ecbeeb99e9016c2c7c54d7bae492144374e138a0b7

**Comment by rluvaton** [comment]
also, when fixing a bug, we require tests to be added that failed on main and pass on this pr

**Comment by kumarUjjawal** [comment]
> also, when fixing a bug, we require tests to be added that failed on main and pass on this pr

Sure will do.

File: datafusion/physical-plan/src/joins/sort_merge_join/stream.rs [hunk 1]
```diff
@@ -1566,6 +1566,7 @@ impl SortMergeJoinStream {
                         .columns()
                         .iter()
                         .skip(right_columns_length)
+                        .take(left_columns_length)
```
Comment (rluvaton) [inline datafusion/physical-plan/src/joins/sort_merge_join/stream.rs]: I don't think we should add it as we can lose columns or hide bugs if we the rest of the columns are not left

Comment (kumarUjjawal) [reply datafusion/physical-plan/src/joins/sort_merge_join/stream.rs]: Right, should I Drop the `.take(left_columns_length)` and add a sanity check like `assert_eq_or_internal_err!(..., left_columns_length, "..."))` before extending right_columns.

Comment (rluvaton) [reply datafusion/physical-plan/src/joins/sort_merge_join/stream.rs]: Yes
