### PR TITLE
fix: json scan performance on local files

### LINKED ISSUE #21450: Regression in  json performance for local files
I ran some tests with clickbench, reading from local files is worse:
```
[ec2-user@ip-172-31-0-185 datafusion]$ ./benchmarks/bench.sh compare json-test-on-main test-json-improvement
Comparing json-test-on-main and test-json-improvement
--------------------
Benchmark clickbench_2.json
--------------------
┏━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Query     ┃ json-test-on-main ┃ test-json-improvement ┃        Change ┃
┡━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ QQuery 0  │        2938.54 ms │           36468.92 ms │ 12.41x slower │
│ QQuery 1  │        4189.48 ms │           36706.26 ms │  8.76x slower │
│ QQuery 2  │        3021.24 ms │           36695.04 ms │ 12.15x slower │
│ QQuery 3  │              FAIL │                  FAIL │  incomparable │
│ QQuery 4  │        3518.24 ms │           37016.08 ms │ 10.52x slower │
│ QQuery 5  │        3138.41 ms │           37131.63 ms │ 11.83x slower │
│ QQuery 6  │              FAIL │                  FAIL │  incomparable │
│ QQuery 7  │        4191.68 ms │           36874.60 ms │  8.80x slower │
│ QQuery 8  │        4405.33 ms │           37054.97 ms │  8.41x slower │
│ QQuery 9  │        3473.41 ms │           37308.28 ms │ 10.74x slower │
│ QQuery 10 │        4351.06 ms │           36934.39 ms │  8.49x slower │
│ QQuery 11 │        3306.45 ms │           37101.39 ms │ 11.22x slower │
│ QQuery 12 │        3226.21 ms │           37235.60 ms │ 11.54x slower │
│ QQuery 13 │        3970.11 ms │           37244.27 ms │  9.38x slower │
│ QQuery 14 │        3246.59 ms │           37085.69 ms │ 11.42x slower │
│ QQuery 15 │        4563.53 ms │           37182.89 ms │  8.15x slower │
│ QQuery 16 │        4506.85 ms │           37391.07 ms │  8.30x slower │
│ QQuery 17 │        4377.16 ms │           37381.49 ms │  8.54x slower │
│ QQuery 18 │        3555.18 ms │           37603.25 ms │ 10.58x slower │
│ QQuery 19 │        4568.01 ms │           36996.50 ms │  8.10x slower │
│ QQuery 20 │        3193.87 ms │           37069.19 ms │ 11.61x slower │
│ QQuery 21 │        4415.33 ms │           37185.73 ms │  8.42x slower │
│ QQuery 22 │        3312.73 ms │           37190.81 ms │ 11.23x slower │
│ QQuery 23 │              FAIL │                  FAIL │  incomparable │
│ QQuery 24 │        4382.53 ms │           37093.81 ms │  8.46x slower │
│ QQuery 25 │        4339.69 ms │           37121.90 ms │  8.55x slower │
│ QQuery 26 │        4425.42 ms │           37106.02 ms │  8.38x slower │
│ QQuery 27 │        4505.30 ms │           37059.04 ms │  8.23x slower │
│ QQuery 28 │        3582.82 ms │           37409.12 ms │ 10.44x slower │
│ QQuery 29 │        4440.96 ms │           36868.93 ms │  8.30x slower │
│ QQuery 30 │        4675.71 ms │           37081.23 ms │  7.93x slower │
│ QQuery 31 │        4276.55 ms │           37165.64 ms │  8.69x slower │
│ QQuery 32 │        3615.42 ms │           37662.39 ms │ 10.42x slower │
│ QQuery 33 │        4446.09 ms │           37558.30 ms │  8.45x slower │
│ QQuery 34 │        4521.66 ms │           37647.72 ms │  8.33x slower │
│ QQuery 35 │        4321.41 ms │           37225.06 ms │  8.61x slower │
│ QQuery 36 │              FAIL │                  FAIL │  incomparable │
│ QQuery 37 │              FAIL │                  FAIL │  incomparable │
│ QQuery 38 │              FAIL │                  FAIL │  incomparable │
│ QQuery 39 │              FAIL │                  FAIL │  incomparable │
│ QQuery 40 │              FAIL │                  FAIL │  incomparable │
│ QQuery 41 │              FAIL │                  FAIL │  incomparable │
│ QQuery 42 │              FAIL │                  FAIL │  incomparable │
└───────────┴───────────────────┴───────────────────────┴───────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃ Benchmark Summary                    ┃              ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━┩
│ Total Time (json-test-on-main)       │  131002.95ms │
│ Total Time (test-json-improvement)   │ 1225857.24ms │
│ Average Time (json-test-on-main)     │    3969.79ms │
│ Average Time (test-json-improvement) │   37147.19ms │
│ Queries Faster                       │            0 │
│ Queries Slower                       │           33 │
│ Queries with No Change               │            0 │
│ Queries with Failure                 │           10 │
└──────────────────────────────────────┴──────────────┘
```
The issue is the `into_stream` function of objects store's `get_result` reads data in 8KiB chunks for local files, so we need to either replace it with custom code or use a completely separate path for local files, as it was done previously

_Originally posted by @ariel-miculas in https://github.com/apache/datafusion/issues/20823#issuecomment-4202604980_

### PR DESCRIPTION
**Pull request by ariel-miculas**
## Which issue does this PR close?

- Closes #21450

## Rationale for this change

The into_stream() implementation of GetResult (from arrow-rs-objectstore) fetches every 8KiB chunk using a spawn_blocking() task, resulting in a lot of scheduling overhead.

Fix this by reading the data directly from the async context, using a buffer size of 8KiBs. This avoids any context switch.

## Are these changes tested?

```
Validated that the initial reported overhead is now much smaller:
Comparing json-test-on-main and test-json-improvement
--------------------
Benchmark clickbench_2.json
--------------------
┏━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃ Query     ┃ json-test-on-main ┃ test-json-improvement ┃       Change ┃
┡━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━┩
│ QQuery 0  │        2421.62 ms │            2521.19 ms │    no change │
│ QQuery 1  │        2584.29 ms │            2729.98 ms │ 1.06x slower │
│ QQuery 2  │        2662.11 ms │            2782.29 ms │    no change │
│ QQuery 3  │              FAIL │                  FAIL │ incomparable │
│ QQuery 4  │        2764.78 ms │            2896.46 ms │    no change │
│ QQuery 5  │        2676.46 ms │            2758.01 ms │    no change │
│ QQuery 6  │              FAIL │                  FAIL │ incomparable │
│ QQuery 7  │        2684.50 ms │            2752.37 ms │    no change │
│ QQuery 8  │        2781.21 ms │            2827.46 ms │    no change │
│ QQuery 9  │        3039.17 ms │            3165.29 ms │    no change │
│ QQuery 10 │        2791.32 ms │            2843.44 ms │    no change │
│ QQuery 11 │        2839.05 ms │            3011.84 ms │ 1.06x slower │
│ QQuery 12 │        2691.51 ms │            2839.97 ms │ 1.06x slower │
│ QQuery 13 │        2768.57 ms │            2860.68 ms │    no change │
│ QQuery 14 │        2712.50 ms │            2856.80 ms │ 1.05x slower │
│ QQuery 15 │        2807.64 ms │            2888.94 ms │    no change │
│ QQuery 16 │        2774.87 ms │            2875.44 ms │    no change │
│ QQuery 17 │        2797.28 ms │            2850.17 ms │    no change │
│ QQuery 18 │        3017.75 ms │            3111.64 ms │    no change │
│ QQuery 19 │        2801.30 ms │            2927.25 ms │    no change │
│ QQuery 20 │        2743.43 ms │            2862.10 ms │    no change │
│ QQuery 21 │        2811.41 ms │            2906.42 ms │    no change │
│ QQuery 22 │        2953.66 ms │            3038.23 ms │    no change │
│ QQuery 23 │              FAIL │                  FAIL │ incomparable │
│ QQuery 24 │        2862.27 ms │            2940.31 ms │    no change │
│ QQuery 25 │        2763.40 ms │            2848.55 ms │    no change │
│ QQuery 26 │        2840.39 ms │            2950.47 ms │    no change │
│ QQuery 27 │        2886.70 ms │            2921.28 ms │    no change │
│ QQuery 28 │        3145.39 ms │            3221.27 ms │    no change │
│ QQuery 29 │        2821.87 ms │            2869.85 ms │    no change │
│ QQuery 30 │        2953.55 ms │            2990.15 ms │    no change │
│ QQuery 31 │        2997.81 ms │            3049.28 ms │    no change │
│ QQuery 32 │        2969.14 ms │            3126.79 ms │ 1.05x slower │
│ QQuery 33 │        2764.80 ms │            2866.63 ms │    no change │
│ QQuery 34 │        2828.77 ms │            2848.54 ms │    no change │
│ QQuery 35 │        2812.55 ms │            2793.79 ms │    no change │
│ QQuery 36 │              FAIL │                  FAIL │ incomparable │
│ QQuery 37 │              FAIL │                  FAIL │ incomparable │
│ QQuery 38 │              FAIL │                  FAIL │ incomparable │
│ QQuery 39 │              FAIL │                  FAIL │ incomparable │
│ QQuery 40 │              FAIL │                  FAIL │ incomparable │
│ QQuery 41 │              FAIL │                  FAIL │ incomparable │
│ QQuery 42 │              FAIL │                  FAIL │ incomparable │
└───────────┴───────────────────┴───────────────────────┴──────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Benchmark Summary                    ┃            ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ Total Time (json-test-on-main)       │ 92771.07ms │
│ Total Time (test-json-improvement)   │ 95732.89ms │
│ Average Time (json-test-on-main)     │  2811.24ms │
│ Average Time (test-json-improvement) │  2901.00ms │
│ Queries Faster                       │          0 │
│ Queries Slower                       │          5 │
│ Queries with No Change               │         28 │
│ Queries with Failure                 │         10 │
└──────────────────────────────────────┴────────────┘
``` 

and with SIMULATE_LATENCY:
```
--------------------
Benchmark clickbench_2.json
--------------------
┏━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Query     ┃ json-test-on-main ┃ test-json-improvement ┃        Change ┃
┡━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ QQuery 0  │        2795.68 ms │            2687.68 ms │     no change │
│ QQuery 1  │        2880.50 ms │            2768.30 ms │     no change │
│ QQuery 2  │        2960.75 ms │            2826.89 ms │     no change │
│ QQuery 3  │              FAIL │                  FAIL │  incomparable │
│ QQuery 4  │        3140.38 ms │            2963.15 ms │ +1.06x faster │
│ QQuery 5  │        2926.66 ms │            2830.43 ms │     no change │
│ QQuery 6  │              FAIL │                  FAIL │  incomparable │
│ QQuery 7  │        3026.29 ms │            2858.30 ms │ +1.06x faster │
│ QQuery 8  │        4302.35 ms │            2954.96 ms │ +1.46x faster │
│ QQuery 9  │        4439.83 ms │            3200.43 ms │ +1.39x faster │
│ QQuery 10 │        3028.32 ms │            2969.32 ms │     no change │
│ QQuery 11 │        3147.81 ms │            3040.74 ms │     no change │
│ QQuery 12 │        4169.45 ms │            2886.59 ms │ +1.44x faster │
│ QQuery 13 │        3839.01 ms │            2997.80 ms │ +1.28x faster │
│ QQuery 14 │        4086.30 ms │            2907.42 ms │ +1.41x faster │
│ QQuery 15 │        4308.07 ms │            3025.22 ms │ +1.42x faster │
│ QQuery 16 │        3084.89 ms │            2984.34 ms │     no change │
│ QQuery 17 │        4287.89 ms │            2984.27 ms │ +1.44x faster │
│ QQuery 18 │        3542.80 ms │            3144.98 ms │ +1.13x faster │
│ QQuery 19 │        4388.70 ms │            3014.37 ms │ +1.46x faster │
│ QQuery 20 │        3149.54 ms │            2986.73 ms │ +1.05x faster │
│ QQuery 21 │        3250.81 ms │            2906.60 ms │ +1.12x faster │
│ QQuery 22 │        3265.98 ms │            3122.25 ms │     no change │
│ QQuery 23 │              FAIL │                  FAIL │  incomparable │
│ QQuery 24 │        3066.52 ms │            2997.55 ms │     no change │
│ QQuery 25 │        4289.31 ms │            2884.22 ms │ +1.49x faster │
│ QQuery 26 │        4223.03 ms │            2933.16 ms │ +1.44x faster │
│ QQuery 27 │        3156.86 ms │            3001.17 ms │     no change │
│ QQuery 28 │        4831.42 ms │            3318.89 ms │ +1.46x faster │
│ QQuery 29 │        3252.45 ms │            4375.90 ms │  1.35x slower │
│ QQuery 30 │        4460.06 ms │            3153.77 ms │ +1.41x faster │
│ QQuery 31 │        4235.85 ms │            3171.58 ms │ +1.34x faster │
│ QQuery 32 │        3435.14 ms │            3202.64 ms │ +1.07x faster │
│ QQuery 33 │        3147.21 ms │            3031.54 ms │     no change │
│ QQuery 34 │        4378.41 ms │            3008.79 ms │ +1.46x faster │
│ QQuery 35 │        4224.36 ms │            2897.53 ms │ +1.46x faster │
│ QQuery 36 │              FAIL │                  FAIL │  incomparable │
│ QQuery 37 │              FAIL │                  FAIL │  incomparable │
│ QQuery 38 │              FAIL │                  FAIL │  incomparable │
│ QQuery 39 │              FAIL │                  FAIL │  incomparable │
│ QQuery 40 │              FAIL │                  FAIL │  incomparable │
│ QQuery 41 │              FAIL │                  FAIL │  incomparable │
│ QQuery 42 │              FAIL │                  FAIL │  incomparable │
└───────────┴───────────────────┴───────────────────────┴───────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┓
┃ Benchmark Summary                    ┃             ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━┩
│ Total Time (json-test-on-main)       │ 120722.63ms │
│ Total Time (test-json-improvement)   │ 100037.48ms │
│ Average Time (json-test-on-main)     │   3658.26ms │
│ Average Time (test-json-improvement) │   3031.44ms │
│ Queries Faster                       │          21 │
│ Queries Slower                       │           1 │
│ Queries with No Change               │          11 │
│ Queries with Failure                 │          10 │
└──────────────────────────────────────┴─────────────┘
```
For the tests I've used a c7a.16xlarge ec2 instance, with a trimmed down version of hits.json to 51G (original has 217 GiB), with a warm cache (by running `cat hits_50.json > /dev/null`)

## Are there any user-facing changes?
No

### CODE REVIEW

**Comment by ariel-miculas** [comment]
@Weijun-H please take a look

File: datafusion/datasource-json/src/boundary_stream.rs [hunk 1]
```diff
@@ -90,10 +90,52 @@ async fn get_stream(
     range: std::ops::Range<u64>,
 ) -> object_store::Result<BoxStream<'static, object_store::Result<Bytes>>> {
     let opts = GetOptions {
-        range: Some(GetRange::Bounded(range)),
+        range: Some(GetRange::Bounded(range.clone())),
         ..Default::default()
     };
     let result = store.get_opts(&location, opts).await?;
+
+    #[cfg(not(target_arch = "wasm32"))]
```
Comment (Dandandan) [inline datafusion/datasource-json/src/boundary_stream.rs:98]: Sounds like it may be improved upstream as well? Doing a spawn_blocking for each (small) read seems not great.

File: datafusion/datasource-json/src/boundary_stream.rs [hunk 2]
```diff
@@ -90,10 +90,52 @@ async fn get_stream(
...
+    if let GetResultPayload::File(mut file, _path) = result.payload {
+        use std::io::{Read, Seek, SeekFrom};
+        const CHUNK_SIZE: u64 = 8 * 1024;
```
Comment (Dandandan) [inline datafusion/datasource-json/src/boundary_stream.rs:101]: Is this ideal? Maybe a bit bigger gets higher throughput?

**Review by flarion-weijun — APPROVED** [review]

**Review by Weijun-H — APPROVED** [review]
LGTM, thanks @ariel-miculas

One suggestion before merge. Can we add a small test that exercises the `LocalFileSystem / GetResultPayload::File path`? The current tests seem to cover the stream-based path only, while this change is specifically for local files.

**Comment by Dandandan** [comment]
> and with SIMULATE_LATENCY:

Nice use of the feature :)

File: datafusion/datasource-json/src/boundary_stream.rs [hunk 3]
```diff
@@ -90,10 +90,52 @@ async fn get_stream(
...
+                        store: "local",
+                        source: Box::new(e),
+                    }
+                })?;
+
+                let mut buf = Vec::with_capacity(cap);
+                let read =
+                    (&mut file)
+                        .take(to_read)
+                        .read_to_end(&mut buf)
```
Comment (alamb) [inline datafusion/datasource-json/src/boundary_stream.rs:128]: This is blocking IO on a tokio task right?

File: datafusion/datasource-json/src/boundary_stream.rs [hunk 4]
```diff
@@ -90,10 +90,52 @@ async fn get_stream(
...
+        const CHUNK_SIZE: u64 = 8 * 1024;
+
+        file.seek(SeekFrom::Start(range.start)).map_err(|e| {
+            object_store::Error::Generic {
+                store: "local",
+                source: Box::new(e),
+            }
+        })?;
+
+        return Ok(futures::stream::try_unfold(
```
Comment (alamb) [inline datafusion/datasource-json/src/boundary_stream.rs:110]: I feel like the upstream object store tries to do the same thing

https://github.com/apache/arrow-rs-object-store/blob/v0.13.2/src/lib.rs#L1636-L1701

Which then calls local stream: https://github.com/apache/arrow-rs-object-store/blob/main/src/local.rs#L926


The major difference is that in object_store the work is done on a `spawn_blocking` thread rather than inline. 

I am a bit worried about doing blocking IO on the main thread here

I wonder if we could try the same approach as done upstream and run this on a different thread, but to Dandan's point:
1. Use a larger buffer for the read (e.g. 256k, then slice to 8k for the output)
2. buffer some of the IO to minimize the overhead (e.g. use [StreamExt::buffered](https://docs.rs/futures/latest/futures/stream/trait.StreamExt.html#method.buffered)

Comment (alamb) [reply datafusion/datasource-json/src/boundary_stream.rs:110]: Update: after some more review, it seems like the current GetResult::File path does blocking IO as well so this isn't a regression

🤷

**Review by alamb — APPROVED** [review]
THank you for this @ariel-miculas @Dandandan and @Weijun-H 

I agree with @Weijun-H 's suggestion for testing

Can you possible make a PR to add the benchmark you are using? I would love to see if we can help optimize this more

File: datafusion/datasource-json/src/boundary_stream.rs (hunk 4 above)
Comment (ariel-miculas) [reply datafusion/datasource-json/src/boundary_stream.rs:110]: Indeed, I implemented blocking IO on the GetResult::File path because that's how it worked previously. Other approaches I've considered:
* [block_in_place](https://docs.rs/tokio/latest/tokio/task/fn.block_in_place.html) - it panics with single-threaded tokio runtimes
* a single spawn_blocking thread with an [mpsc channel](https://docs.rs/tokio/latest/tokio/sync/mpsc/fn.channel.html) - this could work but not as straightforward, it requires more careful design, see https://github.com/apache/datafusion/pull/15654
* using tokio's ReaderStream - this would be similar to the existing `into_stream` approach, but the default buffer size (in tokio-1.50.0/src/io/blocking.rs) is 2MiB `DEFAULT_MAX_BUF_SIZE: usize = 2 * 1024 * 1024`; it still involves context switching overhead and it requires importing additional libraries, such as `tokio-util` and the `tokio fs` feature
```
    #[cfg(not(target_arch = "wasm32"))]
    if let GetResultPayload::File(file, _path) = result.payload {
        use std::io::SeekFrom;
        use tokio::io::{AsyncReadExt, AsyncSeekExt, BufReader};
        let mut tokio_file: tokio::fs::File = tokio::fs::File::from_std(file);
        tokio_file
            .seek(SeekFrom::Start(range.start))
            .await
            .map_err(|e| object_store::Error::Generic {
                store: "local",
                source: Box::new(e),
            })?;
        const BUF_SIZE: usize = 4 * 1024 * 1024; // 4 MiB
        let limited = tokio_file.take(range.end - range.start);
        return Ok(tokio_util::io::ReaderStream::with_capacity(
            BufReader::with_capacity(BUF_SIZE, limited),
            BUF_SIZE,
        )
        .map_err(|e| object_store::Error::Generic {
            store: "local",
            source: Box::new(e),
        })
        .boxed());
    }
```
* keep using `into_stream` but increase the buffer size (from the original 8KiB) - this would significantly reduce the number of context switches

I think there are better approaches, but since the original code was doing blocking IO in an async context (which it [probably shouldn't do](https://ryhl.io/blog/async-what-is-blocking/)), it would be difficult to achieve the same performance with any of these other approaches.

File: datafusion/datasource-json/src/boundary_stream.rs (hunk 2 above)
Comment (ariel-miculas) [reply datafusion/datasource-json/src/boundary_stream.rs:101]: I've picked this value because that's the default for both
*  `BufReader` (which is used when reading the entire json file as shown below)
```
                GetResultPayload::File(file, _) => {
                    let bytes = file_compression_type.convert_read(file)?;

                    if newline_delimited {
                        // NDJSON: use BufReader directly
                        let reader = BufReader::new(bytes);
                        let arrow_reader = ReaderBuilder::new(schema)
                            .with_batch_size(batch_size)
                            .build(reader)?;

                        Ok(futures::stream::iter(arrow_reader)
                            .map(|r| r.map_err(Into::into))
                            .boxed())
                    }
```
* object_store's `GetResult.into_stream`:
```
    pub fn into_stream(self) -> BoxStream<'static, Result<Bytes>> {
        match self.payload {
            #[cfg(all(feature = "fs", not(target_arch = "wasm32")))]
            GetResultPayload::File(file, path) => {
                const CHUNK_SIZE: usize = 8 * 1024;
                local::chunked_stream(file, path, self.range, CHUNK_SIZE)
            }
            GetResultPayload::Stream(s) => s,
        }
    }
```

I think this value should be kept in sync with the first bullet point (where we read the entire json file).

File: datafusion/datasource-json/src/boundary_stream.rs (hunk 1 above)
Comment (ariel-miculas) [reply datafusion/datasource-json/src/boundary_stream.rs:98]: opened https://github.com/apache/arrow-rs-object-store/issues/693

**Comment by alamb** [comment]
Thanks again @ariel-miculas and everyone
