### PR TITLE
[MAJOR] Equivalence System Overhaul

### LINKED ISSUE #13748: Exponential planning time (100s of seconds) with `UNION` and `ORDER BY` queries
### Describe the bug

Our internal system generates queries that look like the following

```sql
select c1, null as c2, ... null as cn from t ORDER BY c1
   UNION ALL
 select null as c1, c2, ... null as cn from t ORDER BY c2
 ...
 select null as c1, null as c2, ... cn from t ORDER BY cn
  ORDER BY c1, c2 ... CN
```

When there are 10 columns this takes 22 ms (in release mode) to plan (which is still quite a while)

When there are 100 columns, it takes over 2 minutes (!!) to plan, which basically caused two production incidents

Here are some timings with numbers of columns (you can see the exponential growth):

Running with 10 columns...completed in 22.65575ms
Running with 20 columns...completed in 107.885ms
Running with 30 columns...completed in 481.31775ms
Running with 40 columns...completed in 1.656844042s
Running with 50 columns...completed in 4.560470708s
Running with 60 columns...completed in 10.54814975s
Running with 70 columns...completed in 21.993968458s
Running with 80 columns...completed in 41.614843209s
Running with 90 columns...completed in 73.642939542s
Running with 100 columns...completed in 123.150163417s

### To Reproduce

With this data file (has 100 columns): [data.csv](https://github.com/user-attachments/files/18117240/data.csv)

## Create Table
```sql
CREATE EXTERNAL TABLE t STORED AS CSV LOCATION 'data.csv' WITH ORDER (c1)
```

## Run query
40 column version (this takes over a second to plan in release mode)
```
(SELECT c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c0)
  UNION ALL
(SELECT null as c0, c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c1)
  UNION ALL
(SELECT null as c0, null as c1, c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c2)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c3)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c4)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c5)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c6)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c7)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c8)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c9)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c10)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c11)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c12)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c13)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c14)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c15)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c16)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c17)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c18)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c19)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c20)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c21)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c22)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c23)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c24)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c25)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c26)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c27)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c28)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c29)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c30)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c31)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c32)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, c33, null as c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c33)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, c34, null as c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c34)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, c35, null as c36, null as c37, null as c38, null as c39 FROM t ORDER BY c35)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, c36, null as c37, null as c38, null as c39 FROM t ORDER BY c36)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, c37, null as c38, null as c39 FROM t ORDER BY c37)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, c38, null as c39 FROM t ORDER BY c38)
  UNION ALL
(SELECT null as c0, null as c1, null as c2, null as c3, null as c4, null as c5, null as c6, null as c7, null as c8, null as c9, null as c10, null as c11, null as c12, null as c13, null as c14, null as c15, null as c16, null as c17, null as c18, null as c19, null as c20, null as c21, null as c22, null as c23, null as c24, null as c25, null as c26, null as c27, null as c28, null as c29, null as c30, null as c31, null as c32, null as c33, null as c34, null as c35, null as c36, null as c37, null as c38, c39 FROM t ORDER BY c39)
ORDER BY c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c30, c31, c32, c33, c34, c35, c36, c37, c38, c39
```

### Expected behavior

I expect that the query plans within a second with 100 columns

### Additional context

The code spends an increasing amount of time in :

```
27.22 Gc  99.9%	-	                  datafusion_physical_expr::equivalence::properties::calculate_union::h9a6d0c834d33dfa8
27.20 Gc  99.9%	2.00 Mc	                   datafusion_physical_expr::equivalence::properties::UnionEquivalentOrderingBuilder::add_satisfied_orderings::haff5d34880826c26
27.20 Gc  99.8%	-	                    datafusion_physical_expr::equivalence::properties::EquivalenceProperties::ordering_satisfy_requirement::h7800d9c061e4551e
26.94 Gc  98.9%	2.00 Mc	                     datafusion_physical_expr::equivalence::properties::EquivalenceProperties::with_constants::h9b627573961f7ac1
26.72 Gc  98.1%	17.83 Mc	                      datafusion_physical_expr::equivalence::properties::EquivalenceProperties::discover_new_orderings::hdb50bd332b5dedd2
21.92 Gc  80.5%	3.85 Gc	                       datafusion_physical_expr::equivalence::ordering::OrderingEquivalenceClass::remove_redundant_entries::h3394f8a44ca387d2
2.52 Gc   9.2%	5.25 Mc	                       _$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..spec_from_iter..SpecFromIter$LT$T$C$I$GT$$GT$::from_iter::hb5d026af61b973ba
2.12 Gc   7.8%	2.03 Gc	                       _$LT$datafusion_physical_expr..expressions..column..Column$u20$as$u20$core..cmp..PartialEq$LT$dyn$u20$core..any..Any$GT$$GT$::eq::h7faccabfc76823d5
```

This particularly bad behavior was introduced in https://github.com/influxdata/arrow-datafusion/commit/577e4bba0f5838846862621e1f5318c949cff2cb / https://github.com/apache/datafusion/pull/12562 (🤦  myself) 

I think this is also what @berkaysynnada  was warning us in https://github.com/apache/datafusion/issues/12446#issuecomment-2368579422

### PR DESCRIPTION
**Pull request by ozankabak**
## Which issue does this PR close?

- Closes #13748.

## Rationale for this change

DF's theoretical approach to representing orderings, equivalences and constants is sound, but it suffers from many implementation problems that lead to various issues. Some of these issues include:
- High-complexity planning times for queries involving UNION and ORDER BY clauses (see the referred issue).
- A continuous stream of subtle bugs that arise from the fact that our objects allow multiple representations of the same underlying state (e.g. a non-existing ordering is sometimes represented by a `None` value for a type `Option<LexOrdering>`, and sometimes with a `Some` value with the payload being "empty").
- The inability to relay ordering preference information to optimizer rules such as `EnforceSorting`, which results in missed optimization opportunities. For example, a windowing operator prefers its input to be sorted w.r.t. both PARTITION BY and ORDER BY keys, but if the former is not available, it is still preferable to have just the latter instead of a fully unsorted input.

## What changes are included in this PR?

- The equivalence system is rewritten to solve the computational complexity problem. The new system avoids handling constants separately from other equivalences and treats them on an equal footing within the same mechanism, avoiding unnecessary work during `ordering_satisfy` checks. Also, the new system caches normalization results for equivalent orderings, which was one of the major sources of excessive computational complexity during sort enforcement.
- The `LexOrdering` and `LexRequirement` objects do not allow degenerate orderings anymore, whenever you see this object, you can be sure there will be *some* ordering. Possible absence of an ordering will henceforth be properly represented by an `Option<LexOrdering>`.
- The `OrderingRequirements` object is introduced to capture ordering preferences of operators.

## Are these changes tested?

Yes.

## Are there any user-facing changes?

Yes -- this is a major API change and will break old code. We spent months looking for ways to (1) break this PR down into smaller ones, (2) yet lump all API changes in one PR -- but couldn't find an effective way to do this.

Therefore, I invite all contributors who are also downstream stakeholders to help by participating in a "pre-scream" test. Please test and report how this PR breaks your code, so we can collectively prepare an upgrade guide for the community at large.

## Tips and Tricks for Reviewing

The "meat" of the code is in the following files:
- `datafusion/physical-expr-common/src/sort_expr.rs`: Definition of `OrderingRequirements`, changes to `LexOrdering` and friends.
- `datafusion/physical-plan/src/execution_plan.rs`: API change to `required_input_ordering`.
- `datafusion/physical-expr/src/equivalence`: Re-implementation of the equivalence system.
- `datafusion/functions-aggregate/src`: Effects of the above on aggregate function implementations.

The rest of the changes are "mandatory" propagative effects of fixing a fundamental low-level mechanism in a large codebase, and mostly trivial.

@alamb, @andygrove, @berkaysynnada -- feel free to tag others.

### CODE REVIEW

**Comment by alamb** [comment]
😮 

I will put this on my list to review asap

**Comment by alamb** [comment]
@wiedld  @xudong963 and @suremarc  perhaps you are also interested in this PR given your past interest in the equivalence code. Also cc @chenkovsky

**Comment by ozankabak** [comment]
Thanks for the quick response @alamb -- I added some reviewing tips and tricks to the PR body to help you guys out.

**Comment by xudong963** [comment]
One thing on my mind is that maybe it's better to hold up the PR until DF48 release, then we can have enough time to check and verify the PR after it merges.

**Comment by alamb** [comment]
I plan to begin a careful review of this PR today

File: datafusion/physical-expr-common/src/sort_expr.rs [hunk 1]
```diff
@@ -129,23 +138,55 @@ impl PhysicalSortExpr {
...
+            ColumnarValue::Array(array) => array,
+            ColumnarValue::Scalar(scalar) => scalar.to_array_of_size(batch.num_rows())?,
+        };
+        Ok(SortColumn {
+            values: array_to_sort,
+            options: Some(self.options),
+        })
+    }
+
+    /// Checks whether this sort expression satisfies the given `requirement`.
```
Comment (alamb) [inline datafusion/physical-expr-common/src/sort_expr.rs:155]: I really like these APIs. I think it would help future readers of we also linked to a definition of what "satisfies"  means

For example, maybe we could define precisely what "satisfies"  and "compatible" mean on the comments of `options_compatible` and then link to `options_compatible` in these comments

File: datafusion/physical-expr-common/src/sort_expr.rs [hunk 2]
```diff
@@ -159,38 +200,17 @@ impl Display for PhysicalSortExpr {
...
-
-    /// Checks whether this sort expression satisfies the given `requirement`.
-    /// If sort options are unspecified in `requirement`, only expressions are
-    /// compared for inequality.
-    pub fn satisfy(
-        &self,
-        requirement: &PhysicalSortRequirement,
-        schema: &Schema,
-    ) -> bool {
+/// Returns whether the given two [`SortOptions`] are compatible.
```
Comment (alamb) [inline datafusion/physical-expr-common/src/sort_expr.rs]: It would help to document what `nullable` means in this context -- I think if it is false it means the input is known not to have nulls

File: datafusion/physical-expr-common/src/sort_expr.rs [hunk 3]
```diff
@@ -334,177 +313,142 @@ fn to_str(options: &SortOptions) -> &str {
...
+///
+/// For example, a `vec![a ASC, b DESC]` represents a lexicographical ordering
+/// that first sorts by column `a` in ascending order, then by column `b` in
+/// descending order. The ordering is non-degenerate, meaning it contains at
+/// least one element, and it is duplicate-free, meaning it does not contain
+/// multiple entries for the same column.
+#[derive(Debug, Clone, PartialEq, Eq)]
+pub struct LexOrdering {
+    exprs: Vec<PhysicalSortExpr>,
+    set: HashSet<Arc<dyn PhysicalExpr>>,
```
Comment (alamb) [inline datafusion/physical-expr-common/src/sort_expr.rs:363]: I think it would help here to mention that `set` contains pointers to the same underlying PhysicalExpr in `exprs` and is included to allow quick insertion check

Also it occurs to me while reviewing this code that `ConstExpr` uses `IndexSet` instead of a Vec + HashSet. I wonder if that could be an improvement

File: datafusion/physical-expr-common/src/sort_expr.rs [hunk 4]
```diff
@@ -334,177 +313,142 @@ fn to_str(options: &SortOptions) -> &str {
...
 
-    /// Truncates the LexOrdering, keeping only the first `len` elements.
-    pub fn truncate(&mut self, len: usize) {
-        self.inner.truncate(len)
+    /// Add all elements from `iter` to the `LexOrdering`.
+    pub fn extend(&mut self, sort_exprs: impl IntoIterator<Item = PhysicalSortExpr>) {
+        for sort_expr in sort_exprs {
+            if self.set.insert(Arc::clone(&sort_expr.expr)) {
+                self.exprs.push(sort_expr);
+            }
```
Comment (alamb) [inline datafusion/physical-expr-common/src/sort_expr.rs]: Very minor: I think this is the same as `push`:
```suggestion
            self.push(sort_expr);
```

File: datafusion/physical-expr-common/src/sort_expr.rs [hunk 5]
```diff
@@ -334,177 +313,142 @@ fn to_str(options: &SortOptions) -> &str {
...
-        self.inner.len()
-    }
+/// This object represents a lexicographical ordering and contains a vector
+/// of `PhysicalSortExpr` objects.
+///
+/// For example, a `vec![a ASC, b DESC]` represents a lexicographical ordering
+/// that first sorts by column `a` in ascending order, then by column `b` in
+/// descending order. The ordering is non-degenerate, meaning it contains at
+/// least one element, and it is duplicate-free, meaning it does not contain
+/// multiple entries for the same column.
```
Comment (alamb) [inline datafusion/physical-expr-common/src/sort_expr.rs]: Here is a minor OCD formatting suggestion: 

```suggestion
/// descending order. 
///
/// # Invariants
/// The following always hold true for the orderings:
/// 1. It is non-degenerate, meaning it contains at least one element
/// 2. It is duplicate-free, meaning it does not contain multiple entries for the same column.
```

**Comment by alamb** [comment]
🤖 `./gh_compare_branch_bench.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/gh_compare_branch_bench.sh) Running
Linux aal-dev 6.11.0-1013-gcp #13~24.04.1-Ubuntu SMP Wed Apr  2 16:34:16 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing required-input-ordering (a75ae4464888d3317b5869eb7ae3aa8a5b150294) to 900279c5d189a62a5585210c64ab6868af4640e5 [diff](https://github.com/apache/datafusion/compare/900279c5d189a62a5585210c64ab6868af4640e5..a75ae4464888d3317b5869eb7ae3aa8a5b150294)
BENCH_NAME=sql_planner
BENCH_COMMAND=cargo bench --bench sql_planner
BENCH_FILTER=
BENCH_BRANCH_NAME=required-input-ordering
Results will be posted here when complete

File: datafusion/physical-expr-common/src/sort_expr.rs [hunk 6]
```diff
@@ -516,162 +460,240 @@ impl Display for LexOrdering {
...
+/// enforce uniqueness like the latter object.
+#[derive(Debug, Clone, PartialEq)]
+pub struct LexRequirement {
+    reqs: Vec<PhysicalSortRequirement>,
+}
+
+impl LexRequirement {
+    /// Creates a new [`LexRequirement`] from the given vector of sort expressions.
+    /// If the vector is empty, returns `None`.
+    pub fn new(reqs: impl IntoIterator<Item = PhysicalSortRequirement>) -> Option<Self> {
```
Comment (alamb) [inline datafusion/physical-expr-common/src/sort_expr.rs:523]: I think calling this `try_new` might be more "idiomatic" to signal it can return `None`

File: datafusion/physical-expr-common/src/sort_expr.rs [hunk 7]
```diff
@@ -516,162 +460,240 @@ impl Display for LexOrdering {
...
+impl From<LexRequirement> for LexOrdering {
+    fn from(value: LexRequirement) -> Self {
+        // Can construct directly as `value` is non-degenerate:
+        let (non_empty, ordering) = Self::construct(value.into_iter().map(Into::into));
+        debug_assert!(non_empty);
+        ordering
+    }
+}
+
+/// Represents a plan's input ordering requirements. Vector elements represent
```
Comment (alamb) [inline datafusion/physical-expr-common/src/sort_expr.rs:614]: This is so much nicer 😍 

Are there any restrictions on the requirements such as that there are no duplicate elements or that they are not empty? It seems the intention is that `Option<OrderingRequirement>` is used to represent no ordering requirement, and I think all the APIs require at least one LexRequirement.

It might be good to document that as another restriction

File: datafusion/physical-expr-common/src/sort_expr.rs [hunk 8]
```diff
@@ -516,162 +460,240 @@ impl Display for LexOrdering {
...
-
-impl FromIterator<PhysicalSortRequirement> for LexRequirement {
-    fn from_iter<T: IntoIterator<Item = PhysicalSortRequirement>>(iter: T) -> Self {
-        let mut lex_requirement = LexRequirement::new(vec![]);
 
-        for i in iter {
-            lex_requirement.inner.push(i);
+    /// Returns all alternatives as a vector of `LexRequirement` objects and a
+    /// boolean value indicating softness/hardness of the requirements.
+    pub fn get_alternatives(self) -> (Vec<LexRequirement>, bool) {
```
Comment (alamb) [inline datafusion/physical-expr-common/src/sort_expr.rs]: Maybe this could be called `into_alternates` to signal it consumes `self`

File: datafusion/functions-aggregate/src/first_last.rs [hunk 9]
```diff
@@ -782,14 +756,92 @@ where
         }
     }
 }
+
+#[derive(Debug)]
```
Comment (alamb) [inline datafusion/functions-aggregate/src/first_last.rs:764]: This is a neat idea -- could you please add some documentation? I think the idea is it simply takes the first value it sees (with no order)

File: datafusion/functions-aggregate/src/first_last.rs [hunk 10]
```diff
@@ -1195,13 +1234,90 @@ impl AggregateUDFImpl for LastValue {
     }
 }
 
+#[derive(Debug)]
+pub struct TrivialLastValueAccumulator {
```
Comment (alamb) [inline datafusion/functions-aggregate/src/first_last.rs:1246]: Likewise here it would help to add a note that this is used when there is no ordering and simply picks the last value that is seen

File: datafusion/physical-expr/src/equivalence/ordering.rs [hunk 11]
```diff
@@ -16,115 +16,76 @@
...
+/// │ 1 │ 4 │ 3 │ 1 │
+/// │ 2 │ 3 │ 3 │ 2 │
+/// │ 3 │ 1 │ 2 │ 2 │
+/// │ 3 │ 2 │ 1 │ 3 │
+/// └───┴───┴───┴───┘
 /// ```
 ///
-/// Here, both `vec![a ASC, b ASC]` and `vec![c DESC, d ASC]` describe the table
+/// Here, both `[a ASC, b ASC]` and `[c DESC, d ASC]` describe the table
 /// ordering. In this case, we say that these orderings are equivalent.
```
Comment (alamb) [inline datafusion/physical-expr/src/equivalence/ordering.rs:46]: I wonder would it help here to describe any requirements related to `orderings`? Specifically what does an empty `ordering` mean?

File: datafusion/physical-expr/src/equivalence/ordering.rs [hunk 12]
```diff
@@ -164,51 +124,40 @@ impl OrderingEquivalenceClass {
     /// For example, if `orderings[idx]` is `[a ASC, b ASC, c DESC]` and
     /// `orderings[pre_idx]` is `[b ASC, c DESC]`, then the function will trim
     /// `orderings[idx]` to `[a ASC]`.
-    fn resolve_overlap(&mut self, idx: usize, pre_idx: usize) -> bool {
+    fn resolve_overlap(&mut self, idx: usize, pre_idx: usize) -> Option<bool> {
```
Comment (alamb) [inline datafusion/physical-expr/src/equivalence/ordering.rs:136]: it would help to update this doc with what returning `None` means (it looks like it means there was no overlap? and `Some(res)` means there was overlap and `res` is if the ordering was actually truncated)

File: datafusion/core/tests/dataframe/mod.rs [hunk 13]
```diff
@@ -2581,7 +2581,7 @@ async fn test_count_wildcard_on_sort() -> Result<()> {
     |               |         TableScan: t1 projection=[b]                                                                       |
     | physical_plan | ProjectionExec: expr=[b@0 as b, count(*)@1 as count(*)]                                                    |
     |               |   SortPreservingMergeExec: [count(Int64(1))@2 ASC NULLS LAST]                                              |
-    |               |     SortExec: expr=[count(Int64(1))@2 ASC NULLS LAST], preserve_partitioning=[true]                        |
+    |               |     SortExec: expr=[count(*)@1 ASC NULLS LAST], preserve_partitioning=[true]                               |
```
Comment (alamb) [inline datafusion/core/tests/dataframe/mod.rs:2584]: It is not clear to me why this test changes, but it seems like an improvement to me

File: datafusion/sqllogictest/test_files/aggregate.slt [hunk 14]
```diff
@@ -173,9 +173,6 @@ SELECT approx_percentile_cont(c12) WITHIN GROUP (ORDER BY c12) FROM aggregate_te
 statement error DataFusion error: This feature is not implemented: Tdigest max_size value for 'APPROX_PERCENTILE_CONT' must be a literal
 SELECT approx_percentile_cont(0.95, c5) WITHIN GROUP (ORDER BY c12) FROM aggregate_test_100
 
-statement error DataFusion error: This feature is not implemented: Conflicting ordering requirements in aggregate functions is not supported
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/aggregate.slt:163]: Why was this test removed? I think it is still a valid test isn't it?

File: datafusion/sqllogictest/test_files/topk.slt [hunk 15]
```diff
@@ -370,7 +370,7 @@ query TT
 explain select number, letter, age, number as column4, letter as column5 from partial_sorted order by number desc, column4 desc, letter asc, column5 asc, age desc limit 3;
 ----
 physical_plan
-01)SortExec: TopK(fetch=3), expr=[number@0 DESC, column4@3 DESC, letter@1 ASC NULLS LAST, column5@4 ASC NULLS LAST, age@2 DESC], preserve_partitioning=[false], sort_prefix=[number@0 DESC, letter@1 ASC NULLS LAST]
+01)SortExec: TopK(fetch=3), expr=[number@0 DESC, letter@1 ASC NULLS LAST, age@2 DESC], preserve_partitioning=[false], sort_prefix=[number@0 DESC, letter@1 ASC NULLS LAST]
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/topk.slt:373]: this seems like a plan improvement 👍 as now there are fewer exprs in the sort expression (given the comments in the test, it seems like this was the expected results anyways)

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                                         main                                   required-input-ordering
-----                                         ----                                   -----------------------
logical_aggregate_with_join                   1.00    731.5±5.31µs        ? ?/sec    1.00    730.4±2.85µs        ? ?/sec
logical_select_all_from_1000                  1.01    125.1±0.22ms        ? ?/sec    1.00    124.3±0.50ms        ? ?/sec
logical_select_one_from_700                   1.00    411.1±1.44µs        ? ?/sec    1.00    411.1±1.53µs        ? ?/sec
logical_trivial_join_high_numbered_columns    1.00    375.1±1.38µs        ? ?/sec    1.00    375.0±6.11µs        ? ?/sec
logical_trivial_join_low_numbered_columns     1.01    361.3±1.64µs        ? ?/sec    1.00    359.1±2.25µs        ? ?/sec
physical_intersection                         1.00    840.3±3.07µs        ? ?/sec    1.02    854.0±4.38µs        ? ?/sec
physical_join_consider_sort                   1.00   1358.7±7.27µs        ? ?/sec    1.03   1400.3±5.71µs        ? ?/sec
physical_join_distinct                        1.00    350.4±1.86µs        ? ?/sec    1.00    351.6±2.31µs        ? ?/sec
physical_many_self_joins                      1.00     10.0±0.03ms        ? ?/sec    1.00     10.1±0.02ms        ? ?/sec
physical_plan_clickbench_all                  1.01    148.9±1.99ms        ? ?/sec    1.00    147.9±1.17ms        ? ?/sec
physical_plan_clickbench_q1                   1.00  1726.0±17.47µs        ? ?/sec    1.01  1735.0±22.65µs        ? ?/sec
physical_plan_clickbench_q10                  1.00      2.5±0.02ms        ? ?/sec    1.03      2.6±0.06ms        ? ?/sec
physical_plan_clickbench_q11                  1.00      2.6±0.03ms        ? ?/sec    1.02      2.6±0.03ms        ? ?/sec
physical_plan_clickbench_q12                  1.00      2.7±0.03ms        ? ?/sec    1.01      2.8±0.02ms        ? ?/sec
physical_plan_clickbench_q13                  1.00      2.4±0.03ms        ? ?/sec    1.01      2.4±0.03ms        ? ?/sec
physical_plan_clickbench_q14                  1.00      2.6±0.03ms        ? ?/sec    1.01      2.7±0.02ms        ? ?/sec
physical_plan_clickbench_q15                  1.00      2.5±0.03ms        ? ?/sec    1.02      2.5±0.03ms        ? ?/sec
physical_plan_clickbench_q16                  1.00      2.3±0.04ms        ? ?/sec    1.01      2.4±0.02ms        ? ?/sec
physical_plan_clickbench_q17                  1.00      2.5±0.03ms        ? ?/sec    1.04      2.5±0.02ms        ? ?/sec
physical_plan_clickbench_q18                  1.02      2.0±0.03ms        ? ?/sec    1.00  1998.0±27.62µs        ? ?/sec
physical_plan_clickbench_q19                  1.00      2.9±0.02ms        ? ?/sec    1.03      3.0±0.03ms        ? ?/sec
physical_plan_clickbench_q2                   1.00  1958.0±29.88µs        ? ?/sec    1.01  1968.1±27.08µs        ? ?/sec
physical_plan_clickbench_q20                  1.02  1709.3±22.03µs        ? ?/sec    1.00  1669.7±22.20µs        ? ?/sec
physical_plan_clickbench_q21                  1.00  1984.7±20.59µs        ? ?/sec    1.03      2.0±0.03ms        ? ?/sec
physical_plan_clickbench_q22                  1.00      2.7±0.04ms        ? ?/sec    1.01      2.7±0.02ms        ? ?/sec
physical_plan_clickbench_q23                  1.00      3.0±0.03ms        ? ?/sec    1.03      3.0±0.06ms        ? ?/sec
physical_plan_clickbench_q24                  1.00      4.7±0.03ms        ? ?/sec    1.00      4.7±0.02ms        ? ?/sec
physical_plan_clickbench_q25                  1.00      2.0±0.02ms        ? ?/sec    1.02      2.1±0.02ms        ? ?/sec
physical_plan_clickbench_q26                  1.00  1857.1±19.45µs        ? ?/sec    1.01  1871.1±18.16µs        ? ?/sec
physical_plan_clickbench_q27                  1.00      2.1±0.02ms        ? ?/sec    1.01      2.1±0.03ms        ? ?/sec
physical_plan_clickbench_q28                  1.00      2.9±0.03ms        ? ?/sec    1.01      3.0±0.05ms        ? ?/sec
physical_plan_clickbench_q29                  1.00      3.7±0.03ms        ? ?/sec    1.02      3.7±0.05ms        ? ?/sec
physical_plan_clickbench_q3                   1.00  1936.2±20.30µs        ? ?/sec    1.01  1953.3±21.10µs        ? ?/sec
physical_plan_clickbench_q30                  1.12     15.4±0.22ms        ? ?/sec    1.00     13.8±0.14ms        ? ?/sec
physical_plan_clickbench_q31                  1.00      3.0±0.03ms        ? ?/sec    1.00      2.9±0.03ms        ? ?/sec
physical_plan_clickbench_q32                  1.00      2.9±0.03ms        ? ?/sec    1.02      3.0±0.05ms        ? ?/sec
physical_plan_clickbench_q33                  1.00      2.5±0.02ms        ? ?/sec    1.01      2.5±0.02ms        ? ?/sec
physical_plan_clickbench_q34                  1.00      2.1±0.02ms        ? ?/sec    1.02      2.2±0.02ms        ? ?/sec
physical_plan_clickbench_q35                  1.00      2.2±0.02ms        ? ?/sec    1.02      2.3±0.03ms        ? ?/sec
physical_plan_clickbench_q36                  1.00      3.0±0.03ms        ? ?/sec    1.02      3.1±0.03ms        ? ?/sec
physical_plan_clickbench_q37                  1.00      3.1±0.03ms        ? ?/sec    1.01      3.1±0.02ms        ? ?/sec
physical_plan_clickbench_q38                  1.00      3.1±0.03ms        ? ?/sec    1.00      3.1±0.03ms        ? ?/sec
physical_plan_clickbench_q39                  1.00      2.8±0.03ms        ? ?/sec    1.00      2.8±0.02ms        ? ?/sec
physical_plan_clickbench_q4                   1.00  1676.1±20.68µs        ? ?/sec    1.01  1685.4±20.14µs        ? ?/sec
physical_plan_clickbench_q40                  1.00      3.5±0.03ms        ? ?/sec    1.01      3.5±0.01ms        ? ?/sec
physical_plan_clickbench_q41                  1.00      3.0±0.02ms        ? ?/sec    1.01      3.1±0.03ms        ? ?/sec
physical_plan_clickbench_q42                  1.01      3.0±0.03ms        ? ?/sec    1.00      3.0±0.02ms        ? ?/sec
physical_plan_clickbench_q43                  1.00      3.1±0.04ms        ? ?/sec    1.06      3.3±0.03ms        ? ?/sec
physical_plan_clickbench_q44                  1.01  1833.2±23.49µs        ? ?/sec    1.00  1820.9±17.43µs        ? ?/sec
physical_plan_clickbench_q45                  1.00  1835.8±24.12µs        ? ?/sec    1.00  1843.0±44.55µs        ? ?/sec
physical_plan_clickbench_q46                  1.00      2.3±0.02ms        ? ?/sec    1.01      2.3±0.02ms        ? ?/sec
physical_plan_clickbench_q47                  1.00      2.9±0.02ms        ? ?/sec    1.03      2.9±0.05ms        ? ?/sec
physical_plan_clickbench_q48                  1.00      3.5±0.03ms        ? ?/sec    1.02      3.5±0.06ms        ? ?/sec
physical_plan_clickbench_q49                  1.03      4.0±0.03ms        ? ?/sec    1.00      3.9±0.07ms        ? ?/sec
physical_plan_clickbench_q5                   1.00  1867.4±19.68µs        ? ?/sec    1.01  1886.0±23.34µs        ? ?/sec
physical_plan_clickbench_q50                  1.00      3.5±0.03ms        ? ?/sec    1.01      3.6±0.03ms        ? ?/sec
physical_plan_clickbench_q51                  1.00      2.4±0.02ms        ? ?/sec    1.01      2.4±0.02ms        ? ?/sec
physical_plan_clickbench_q52                  1.00      3.2±0.04ms        ? ?/sec    1.02      3.3±0.03ms        ? ?/sec
physical_plan_clickbench_q6                   1.00  1871.9±20.29µs        ? ?/sec    1.01  1889.0±21.57µs        ? ?/sec
physical_plan_clickbench_q7                   1.00  1732.6±17.57µs        ? ?/sec    1.00  1728.1±30.43µs        ? ?/sec
physical_plan_clickbench_q8                   1.00      2.4±0.02ms        ? ?/sec    1.03      2.5±0.03ms        ? ?/sec
physical_plan_clickbench_q9                   1.00      2.3±0.03ms        ? ?/sec    1.00      2.3±0.02ms        ? ?/sec
physical_plan_tpcds_all                       1.00   1098.4±6.12ms        ? ?/sec    1.03   1134.3±6.62ms        ? ?/sec
physical_plan_tpch_all                        1.00     65.3±0.16ms        ? ?/sec    1.04     67.9±0.24ms        ? ?/sec
physical_plan_tpch_q1                         1.00      2.2±0.03ms        ? ?/sec    1.03      2.3±0.02ms        ? ?/sec
physical_plan_tpch_q10                        1.00      3.3±0.02ms        ? ?/sec    1.06      3.5±0.04ms        ? ?/sec
physical_plan_tpch_q11                        1.00      3.5±0.01ms        ? ?/sec    1.05      3.7±0.07ms        ? ?/sec
physical_plan_tpch_q12                        1.00   1971.3±9.14µs        ? ?/sec    1.04      2.0±0.01ms        ? ?/sec
physical_plan_tpch_q13                        1.00  1497.8±13.37µs        ? ?/sec    1.06   1592.7±6.37µs        ? ?/sec
physical_plan_tpch_q14                        1.00      2.0±0.01ms        ? ?/sec    1.05      2.1±0.02ms        ? ?/sec
physical_plan_tpch_q16                        1.00      2.6±0.03ms        ? ?/sec    1.06      2.8±0.05ms        ? ?/sec
physical_plan_tpch_q17                        1.00      2.6±0.08ms        ? ?/sec    1.02      2.7±0.01ms        ? ?/sec
physical_plan_tpch_q18                        1.00      2.8±0.02ms        ? ?/sec    1.05      2.9±0.01ms        ? ?/sec
physical_plan_tpch_q19                        1.00      4.0±0.02ms        ? ?/sec    1.01      4.0±0.01ms        ? ?/sec
physical_plan_tpch_q2                         1.00      5.7±0.02ms        ? ?/sec    1.04      5.9±0.02ms        ? ?/sec
physical_plan_tpch_q20                        1.00      3.3±0.04ms        ? ?/sec    1.04      3.5±0.04ms        ? ?/sec
physical_plan_tpch_q21                        1.00      4.4±0.03ms        ? ?/sec    1.03      4.6±0.02ms        ? ?/sec
physical_plan_tpch_q22                        1.00      3.0±0.03ms        ? ?/sec    1.04      3.1±0.02ms        ? ?/sec
physical_plan_tpch_q3                         1.00      2.3±0.01ms        ? ?/sec    1.05      2.4±0.01ms        ? ?/sec
physical_plan_tpch_q4                         1.00  1668.8±15.02µs        ? ?/sec    1.04  1734.0±14.60µs        ? ?/sec
physical_plan_tpch_q5                         1.00      3.3±0.02ms        ? ?/sec    1.04      3.4±0.01ms        ? ?/sec
physical_plan_tpch_q6                         1.00    943.1±7.94µs        ? ?/sec    1.02    963.1±6.34µs        ? ?/sec
physical_plan_tpch_q7                         1.00      4.4±0.02ms        ? ?/sec    1.06      4.6±0.02ms        ? ?/sec
physical_plan_tpch_q8                         1.00      5.3±0.03ms        ? ?/sec    1.05      5.6±0.03ms        ? ?/sec
physical_plan_tpch_q9                         1.00      4.2±0.02ms        ? ?/sec    1.06      4.4±0.02ms        ? ?/sec
physical_select_aggregates_from_200           1.19     26.3±0.10ms        ? ?/sec    1.00     22.1±0.15ms        ? ?/sec
physical_select_all_from_1000                 1.01    139.5±0.33ms        ? ?/sec    1.00    138.6±0.27ms        ? ?/sec
physical_select_one_from_700                  1.00   1041.5±5.37µs        ? ?/sec    1.00   1036.6±4.65µs        ? ?/sec
physical_sorted_union_orderby                 1.36     63.9±0.39ms        ? ?/sec    1.00     47.0±0.31ms        ? ?/sec
physical_theta_join_consider_sort             1.00   1735.5±6.65µs        ? ?/sec    1.01   1760.8±8.88µs        ? ?/sec
physical_unnest_to_join                       1.00   1329.7±8.03µs        ? ?/sec    1.00   1336.1±8.43µs        ? ?/sec
with_param_values_many_columns                1.00    165.3±0.78µs        ? ?/sec    1.00    164.6±1.97µs        ? ?/sec
```


</p>
</details>

File: datafusion/sqllogictest/test_files/topk.slt [hunk 16]
```diff
@@ -380,7 +380,7 @@ explain select number + 1 as number_plus, number, number + 1 as other_number_plu
 ----
 physical_plan
 01)SortPreservingMergeExec: [number_plus@0 DESC, number@1 DESC, other_number_plus@2 DESC, age@3 ASC NULLS LAST], fetch=3
-02)--SortExec: TopK(fetch=3), expr=[number_plus@0 DESC, number@1 DESC, other_number_plus@2 DESC, age@3 ASC NULLS LAST], preserve_partitioning=[true], sort_prefix=[number_plus@0 DESC, number@1 DESC]
+02)--SortExec: TopK(fetch=3), expr=[number_plus@0 DESC, number@1 DESC, age@3 ASC NULLS LAST], preserve_partitioning=[true], sort_prefix=[number_plus@0 DESC, number@1 DESC]
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/topk.slt:383]: likewise this seems like an improvment

**Comment by alamb** [comment]
There are some pretty nice looking results in the benchmark results:
```
group                                         main                                   required-input-ordering
-----                                         ----                                   -----------------------
...
 physical_select_aggregates_from_200           1.19     26.3±0.10ms        ? ?/sec    1.00     22.1±0.15ms        ? ?/sec
...
physical_sorted_union_orderby                 1.36     63.9±0.39ms        ? ?/sec    1.00     47.0±0.31ms        ? ?/sec
```

There are a few that appear to get slightly slower -- I will rerun the benchmarks to see if it reproduces and run a profile locally

```
physical_plan_clickbench_q43                  1.00      3.1±0.04ms        ? ?/sec    1.06      3.3±0.03ms        ? ?/sec
physical_plan_tpch_q10                        1.00      3.3±0.02ms        ? ?/sec    1.06      3.5±0.04ms        ? ?/sec
physical_plan_tpch_q7                         1.00      4.4±0.02ms        ? ?/sec    1.06      4.6±0.02ms        ? ?/sec
```

**Comment by alamb** [comment]
🤖 `./gh_compare_branch_bench.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/gh_compare_branch_bench.sh) Running
Linux aal-dev 6.11.0-1013-gcp #13~24.04.1-Ubuntu SMP Wed Apr  2 16:34:16 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing required-input-ordering (a75ae4464888d3317b5869eb7ae3aa8a5b150294) to 900279c5d189a62a5585210c64ab6868af4640e5 [diff](https://github.com/apache/datafusion/compare/900279c5d189a62a5585210c64ab6868af4640e5..a75ae4464888d3317b5869eb7ae3aa8a5b150294)
BENCH_NAME=sql_planner
BENCH_COMMAND=cargo bench --bench sql_planner
BENCH_FILTER=
BENCH_BRANCH_NAME=required-input-ordering
Results will be posted here when complete

File: datafusion/core/src/datasource/listing/table.rs [hunk 17]
```diff
@@ -1053,25 +1051,9 @@ impl TableProvider for ListingTable {
...
-                    .into_iter()
-                    .cloned()
-                    .map(PhysicalSortRequirement::from)
-                    .collect::<Vec<_>>(),
-            ))
-        } else {
-            None
-        };
+        let orderings = self.try_create_output_ordering()?;
+        // It is sufficient to pass only one of the equivalent orderings:
```
Comment (alamb) [inline datafusion/core/src/datasource/listing/table.rs:1055]: maybe in the future (not this PR) the code could pass all the orderings and let the writer decide what to use

File: datafusion/core/tests/physical_optimizer/enforce_distribution.rs [hunk 18]
```diff
@@ -3208,10 +3215,11 @@ fn do_not_preserve_ordering_through_repartition() -> Result<()> {
 #[test]
 fn no_need_for_sort_after_filter() -> Result<()> {
     let schema = schema();
-    let sort_key = LexOrdering::new(vec![PhysicalSortExpr {
-        expr: col("c", &schema).unwrap(),
+    let sort_key: LexOrdering = [PhysicalSortExpr {
```
Comment (alamb) [inline datafusion/core/tests/physical_optimizer/enforce_distribution.rs:3218]: FWIW another way to write this that i find sometimes clearer is:

```rst
    let sort_key =  LexOrdering::from([PhysicalSortExpr { ...}]);
```

It also often avoids an extra line.

Totally not needed for this PR -- I am just pointing it out

File: datafusion/core/tests/physical_optimizer/enforce_sorting.rs [hunk 19]
```diff
@@ -210,24 +175,27 @@ async fn test_remove_unnecessary_sort5() -> Result<()> {
...
     let on = vec![(
         Arc::new(Column::new_with_schema("col_a", &left_schema)?) as _,
         Arc::new(Column::new_with_schema("c", &right_schema)?) as _,
     )];
     let join = hash_join_exec(left_input, right_input, on, None, &JoinType::Inner)?;
-    let physical_plan = sort_exec(vec![sort_expr("a", &join.schema())], join);
+    let physical_plan = sort_exec([sort_expr("a", &join.schema())].into(), join);
 
-    let expected_input = ["SortExec: expr=[a@2 ASC], preserve_partitioning=[false]",
+    let expected_input = [
```
Comment (alamb) [inline datafusion/core/tests/physical_optimizer/enforce_sorting.rs:188]: It is unfortunate we haven't rewritten these tests to insta yet

**Review by alamb — COMMENTED** [review]
First of all, thank you so much for this PR. It is am epic amount of work and I think cleans up a major rough edge of the code in DataFusion. 

I went through this PR as best I could. I realistically can't review all 7K lines in detail However, what I read I thought was really nicely done and easy to follow. 

I have a few more files to complete the review but so far it looks great

Screenshot 2025-06-02 at 3 57 26 PM


I had some small comments that I think would improve the code but nothing I think is required. 

I went through the following new APIs in detail:

> datafusion/physical-expr-common/src/sort_expr.rs: Definition of OrderingRequirements, changes to LexOrdering and friends.
> datafusion/physical-plan/src/execution_plan.rs: API change to required_input_ordering.
> datafusion/physical-expr/src/equivalence: Re-implementation of the equivalence system.
> datafusion/functions-aggregate/src: Effects of the above on aggregate function implementations.

I also reviewed all test changes and they looks good to me

## Thoughts:
1. We should add some sort of note in the upgrade guide about how users will have to change their code (we can do it as a follow on PR)

Also cc @akurmustafa / @mustafasrepo in case you haven't seen this yet

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                                         main                                   required-input-ordering
-----                                         ----                                   -----------------------
logical_aggregate_with_join                   1.01    736.0±4.72µs        ? ?/sec    1.00    730.8±3.47µs        ? ?/sec
logical_select_all_from_1000                  1.01    125.3±0.28ms        ? ?/sec    1.00    124.5±0.75ms        ? ?/sec
logical_select_one_from_700                   1.00    410.9±1.54µs        ? ?/sec    1.00    412.0±1.37µs        ? ?/sec
logical_trivial_join_high_numbered_columns    1.00    377.2±1.11µs        ? ?/sec    1.00    377.5±2.10µs        ? ?/sec
logical_trivial_join_low_numbered_columns     1.00    362.6±1.18µs        ? ?/sec    1.00    363.5±2.03µs        ? ?/sec
physical_intersection                         1.00    842.7±6.01µs        ? ?/sec    1.02   863.4±10.79µs        ? ?/sec
physical_join_consider_sort                   1.00   1356.9±5.64µs        ? ?/sec    1.03   1395.7±5.69µs        ? ?/sec
physical_join_distinct                        1.01    353.9±3.21µs        ? ?/sec    1.00    351.4±1.13µs        ? ?/sec
physical_many_self_joins                      1.00     10.1±0.02ms        ? ?/sec    1.00     10.1±0.04ms        ? ?/sec
physical_plan_clickbench_all                  1.00    146.6±1.33ms        ? ?/sec    1.01    148.4±1.44ms        ? ?/sec
physical_plan_clickbench_q1                   1.00  1705.1±20.55µs        ? ?/sec    1.01  1725.0±15.43µs        ? ?/sec
physical_plan_clickbench_q10                  1.00      2.5±0.03ms        ? ?/sec    1.02      2.5±0.04ms        ? ?/sec
physical_plan_clickbench_q11                  1.00      2.6±0.02ms        ? ?/sec    1.02      2.6±0.04ms        ? ?/sec
physical_plan_clickbench_q12                  1.00      2.7±0.04ms        ? ?/sec    1.03      2.8±0.02ms        ? ?/sec
physical_plan_clickbench_q13                  1.00      2.4±0.02ms        ? ?/sec    1.02      2.4±0.02ms        ? ?/sec
physical_plan_clickbench_q14                  1.00      2.6±0.02ms        ? ?/sec    1.03      2.6±0.03ms        ? ?/sec
physical_plan_clickbench_q15                  1.00      2.5±0.03ms        ? ?/sec    1.04      2.6±0.02ms        ? ?/sec
physical_plan_clickbench_q16                  1.00      2.3±0.03ms        ? ?/sec    1.05      2.4±0.04ms        ? ?/sec
physical_plan_clickbench_q17                  1.00      2.4±0.04ms        ? ?/sec    1.05      2.6±0.04ms        ? ?/sec
physical_plan_clickbench_q18                  1.00  1977.1±11.26µs        ? ?/sec    1.02      2.0±0.03ms        ? ?/sec
physical_plan_clickbench_q19                  1.00      2.9±0.01ms        ? ?/sec    1.05      3.0±0.02ms        ? ?/sec
physical_plan_clickbench_q2                   1.00  1957.0±25.76µs        ? ?/sec    1.02  1994.0±18.70µs        ? ?/sec
physical_plan_clickbench_q20                  1.00  1674.5±15.67µs        ? ?/sec    1.01  1683.8±25.23µs        ? ?/sec
physical_plan_clickbench_q21                  1.00  1993.9±24.54µs        ? ?/sec    1.00  1999.9±19.07µs        ? ?/sec
physical_plan_clickbench_q22                  1.00      2.6±0.03ms        ? ?/sec    1.02      2.7±0.01ms        ? ?/sec
physical_plan_clickbench_q23                  1.00      3.0±0.02ms        ? ?/sec    1.02      3.0±0.03ms        ? ?/sec
physical_plan_clickbench_q24                  1.00      4.7±0.03ms        ? ?/sec    1.02      4.7±0.04ms        ? ?/sec
physical_plan_clickbench_q25                  1.00      2.0±0.03ms        ? ?/sec    1.03      2.1±0.03ms        ? ?/sec
physical_plan_clickbench_q26                  1.00  1834.0±27.02µs        ? ?/sec    1.03  1887.5±26.64µs        ? ?/sec
physical_plan_clickbench_q27                  1.00      2.1±0.03ms        ? ?/sec    1.02      2.1±0.03ms        ? ?/sec
physical_plan_clickbench_q28                  1.00      2.9±0.03ms        ? ?/sec    1.01      3.0±0.03ms        ? ?/sec
physical_plan_clickbench_q29                  1.00      3.6±0.03ms        ? ?/sec    1.02      3.7±0.04ms        ? ?/sec
physical_plan_clickbench_q3                   1.00  1929.8±19.37µs        ? ?/sec    1.04      2.0±0.02ms        ? ?/sec
physical_plan_clickbench_q30                  1.09     15.1±0.15ms        ? ?/sec    1.00     13.9±0.13ms        ? ?/sec
physical_plan_clickbench_q31                  1.00      2.9±0.02ms        ? ?/sec    1.03      3.0±0.03ms        ? ?/sec
physical_plan_clickbench_q32                  1.00      2.9±0.02ms        ? ?/sec    1.02      3.0±0.02ms        ? ?/sec
physical_plan_clickbench_q33                  1.00      2.5±0.03ms        ? ?/sec    1.01      2.5±0.01ms        ? ?/sec
physical_plan_clickbench_q34                  1.00      2.1±0.02ms        ? ?/sec    1.03      2.2±0.02ms        ? ?/sec
physical_plan_clickbench_q35                  1.00      2.2±0.03ms        ? ?/sec    1.02      2.3±0.03ms        ? ?/sec
physical_plan_clickbench_q36                  1.00      3.0±0.03ms        ? ?/sec    1.02      3.1±0.03ms        ? ?/sec
physical_plan_clickbench_q37                  1.00      3.1±0.04ms        ? ?/sec    1.01      3.1±0.03ms        ? ?/sec
physical_plan_clickbench_q38                  1.00      3.1±0.03ms        ? ?/sec    1.02      3.1±0.03ms        ? ?/sec
physical_plan_clickbench_q39                  1.00      2.8±0.03ms        ? ?/sec    1.01      2.9±0.04ms        ? ?/sec
physical_plan_clickbench_q4                   1.00  1668.3±14.38µs        ? ?/sec    1.03  1714.2±24.87µs        ? ?/sec
physical_plan_clickbench_q40                  1.00      3.5±0.03ms        ? ?/sec    1.02      3.5±0.03ms        ? ?/sec
physical_plan_clickbench_q41                  1.00      3.0±0.02ms        ? ?/sec    1.02      3.1±0.03ms        ? ?/sec
physical_plan_clickbench_q42                  1.00      3.0±0.04ms        ? ?/sec    1.00      3.0±0.04ms        ? ?/sec
physical_plan_clickbench_q43                  1.00      3.1±0.04ms        ? ?/sec    1.07      3.3±0.11ms        ? ?/sec
physical_plan_clickbench_q44                  1.00  1830.7±25.31µs        ? ?/sec    1.00  1835.2±18.71µs        ? ?/sec
physical_plan_clickbench_q45                  1.00  1844.6±20.01µs        ? ?/sec    1.00  1844.1±30.61µs        ? ?/sec
physical_plan_clickbench_q46                  1.00      2.3±0.03ms        ? ?/sec    1.01      2.3±0.02ms        ? ?/sec
physical_plan_clickbench_q47                  1.00      2.9±0.03ms        ? ?/sec    1.01      2.9±0.03ms        ? ?/sec
physical_plan_clickbench_q48                  1.00      3.5±0.04ms        ? ?/sec    1.01      3.5±0.05ms        ? ?/sec
physical_plan_clickbench_q49                  1.03      3.9±0.04ms        ? ?/sec    1.00      3.8±0.03ms        ? ?/sec
physical_plan_clickbench_q5                   1.00  1882.5±26.37µs        ? ?/sec    1.02  1929.0±23.74µs        ? ?/sec
physical_plan_clickbench_q50                  1.00      3.5±0.02ms        ? ?/sec    1.00      3.6±0.02ms        ? ?/sec
physical_plan_clickbench_q51                  1.00      2.4±0.02ms        ? ?/sec    1.01      2.4±0.01ms        ? ?/sec
physical_plan_clickbench_q52                  1.00      3.2±0.03ms        ? ?/sec    1.02      3.3±0.02ms        ? ?/sec
physical_plan_clickbench_q6                   1.00  1865.0±14.75µs        ? ?/sec    1.03  1926.6±35.69µs        ? ?/sec
physical_plan_clickbench_q7                   1.00  1714.9±17.28µs        ? ?/sec    1.02  1747.1±25.25µs        ? ?/sec
physical_plan_clickbench_q8                   1.00      2.4±0.02ms        ? ?/sec    1.04      2.5±0.02ms        ? ?/sec
physical_plan_clickbench_q9                   1.00      2.3±0.03ms        ? ?/sec    1.02      2.4±0.03ms        ? ?/sec
physical_plan_tpcds_all                       1.00   1090.9±3.37ms        ? ?/sec    1.04   1129.2±7.87ms        ? ?/sec
physical_plan_tpch_all                        1.00     65.2±0.92ms        ? ?/sec    1.04     67.6±0.82ms        ? ?/sec
physical_plan_tpch_q1                         1.00      2.2±0.02ms        ? ?/sec    1.04      2.3±0.01ms        ? ?/sec
physical_plan_tpch_q10                        1.00      3.3±0.02ms        ? ?/sec    1.05      3.5±0.01ms        ? ?/sec
physical_plan_tpch_q11                        1.00      3.5±0.01ms        ? ?/sec    1.05      3.6±0.02ms        ? ?/sec
physical_plan_tpch_q12                        1.00   1962.6±9.99µs        ? ?/sec    1.04      2.0±0.02ms        ? ?/sec
physical_plan_tpch_q13                        1.00   1497.3±6.27µs        ? ?/sec    1.06  1579.9±25.05µs        ? ?/sec
physical_plan_tpch_q14                        1.00      2.0±0.01ms        ? ?/sec    1.05      2.1±0.02ms        ? ?/sec
physical_plan_tpch_q16                        1.00      2.6±0.01ms        ? ?/sec    1.05      2.7±0.02ms        ? ?/sec
physical_plan_tpch_q17                        1.00      2.6±0.01ms        ? ?/sec    1.02      2.6±0.01ms        ? ?/sec
physical_plan_tpch_q18                        1.00      2.8±0.01ms        ? ?/sec    1.05      2.9±0.03ms        ? ?/sec
physical_plan_tpch_q19                        1.00      4.0±0.03ms        ? ?/sec    1.01      4.0±0.03ms        ? ?/sec
physical_plan_tpch_q2                         1.00      5.7±0.03ms        ? ?/sec    1.04      5.9±0.01ms        ? ?/sec
physical_plan_tpch_q20                        1.00      3.3±0.04ms        ? ?/sec    1.03      3.4±0.01ms        ? ?/sec
physical_plan_tpch_q21                        1.00      4.4±0.03ms        ? ?/sec    1.03      4.5±0.06ms        ? ?/sec
physical_plan_tpch_q22                        1.00      3.0±0.03ms        ? ?/sec    1.03      3.1±0.03ms        ? ?/sec
physical_plan_tpch_q3                         1.00      2.3±0.01ms        ? ?/sec    1.05      2.4±0.03ms        ? ?/sec
physical_plan_tpch_q4                         1.00   1662.8±8.32µs        ? ?/sec    1.04  1729.9±12.29µs        ? ?/sec
physical_plan_tpch_q5                         1.00      3.2±0.01ms        ? ?/sec    1.04      3.4±0.03ms        ? ?/sec
physical_plan_tpch_q6                         1.00    944.0±7.01µs        ? ?/sec    1.02    964.7±6.33µs        ? ?/sec
physical_plan_tpch_q7                         1.00      4.4±0.02ms        ? ?/sec    1.05      4.6±0.03ms        ? ?/sec
physical_plan_tpch_q8                         1.00      5.3±0.05ms        ? ?/sec    1.03      5.5±0.02ms        ? ?/sec
physical_plan_tpch_q9                         1.00      4.2±0.01ms        ? ?/sec    1.05      4.4±0.03ms        ? ?/sec
physical_select_aggregates_from_200           1.19     26.1±0.07ms        ? ?/sec    1.00     21.9±0.08ms        ? ?/sec
physical_select_all_from_1000                 1.01    139.7±0.27ms        ? ?/sec    1.00    138.6±0.23ms        ? ?/sec
physical_select_one_from_700                  1.00   1038.2±5.50µs        ? ?/sec    1.01   1045.3±5.50µs        ? ?/sec
physical_sorted_union_orderby                 1.37     64.2±1.20ms        ? ?/sec    1.00     47.0±0.34ms        ? ?/sec
physical_theta_join_consider_sort             1.00   1736.6±7.42µs        ? ?/sec    1.01   1762.2±8.80µs        ? ?/sec
physical_unnest_to_join                       1.00  1329.5±14.09µs        ? ?/sec    1.01   1337.2±5.08µs        ? ?/sec
with_param_values_many_columns                1.01    166.3±1.24µs        ? ?/sec    1.00    164.2±0.89µs        ? ?/sec
```


</p>
</details>

File: datafusion/physical-expr/src/equivalence/class.rs [hunk 20]
```diff
@@ -175,307 +135,398 @@ impl ConstExpr {
...
-    /// all other expressions in this class
+    /// all other expressions in this class.
     pub fn push(&mut self, expr: Arc<dyn PhysicalExpr>) {
+        if let Some(lit) = expr.as_any().downcast_ref::<Literal>() {
+            let expr_across = AcrossPartitions::Uniform(Some(lit.value().clone()));
+            if let Some(across) = self.constant.as_mut() {
+                // TODO: Return an error if constant values do not agree.
+                if *across == AcrossPartitions::Heterogeneous {
+                    *across = expr_across;
+                }
```
Comment (viirya) [inline datafusion/physical-expr/src/equivalence/class.rs:210]: It is safer by checking the constant literal values are actually the same if the existing `constant` is `Uniform` and its value is known.

File: datafusion/physical-expr/src/equivalence/class.rs [hunk 21]
```diff
@@ -175,307 +135,398 @@ impl ConstExpr {
...
 
     /// Insert the expression into this class, meaning it is known to be equal to
-    /// all other expressions in this class
+    /// all other expressions in this class.
     pub fn push(&mut self, expr: Arc<dyn PhysicalExpr>) {
+        if let Some(lit) = expr.as_any().downcast_ref::<Literal>() {
+            let expr_across = AcrossPartitions::Uniform(Some(lit.value().clone()));
+            if let Some(across) = self.constant.as_mut() {
+                // TODO: Return an error if constant values do not agree.
+                if *across == AcrossPartitions::Heterogeneous {
```
Comment (viirya) [inline datafusion/physical-expr/src/equivalence/class.rs:208]: Why a new `Uniform` constant overwrites existing `Heterogeneous`? Shouldn't it be an error?

File: datafusion/catalog/src/listing_schema.rs [hunk 22]
```diff
@@ -143,7 +141,7 @@ impl ListingSchemaProvider {
                             order_exprs: vec![],
                             unbounded: false,
                             options: Default::default(),
-                            constraints: Constraints::empty(),
+                            constraints: Default::default(),
```
Comment (viirya) [inline datafusion/catalog/src/listing_schema.rs:144]: Shouldn't it be `Constraints::default()`?

File: datafusion/physical-expr/src/equivalence/properties/mod.rs [hunk 23]
```diff
@@ -190,382 +241,363 @@ impl EquivalenceProperties {
...
+                let expr_properties =
+                    equivalent_expr.get_properties(&child_properties)?;
+                if expr_properties.preserves_lex_ordering
+                    && expr_properties.sort_properties
+                        == SortProperties::Ordered(leading_ordering_options)
+                {
+                    // Assume that `[c ASC, a ASC, b ASC]` is among existing
+                    // orderings. If equality `c = f(a, b)` is given, ordering
+                    // `[a ASC, b ASC]` implies the ordering `[c ASC]`. Thus,
+                    // ordering `[a ASC, b ASC]` is also a valid ordering.
```
Comment (viirya) [inline datafusion/physical-expr/src/equivalence/properties/mod.rs:470]: I know you just rephrase these comments so the meaning is same. But I wonder if it is correct? Shouldn't it depend on what `f` is? If `f` is not monotonic increasing, how does `[a ASC, b ASC]` imply the ordering `[c ASC]`.

**Comment by alamb** [comment]
> 🤖 `./gh_compare_branch_bench.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/gh_compare_branch_bench.sh) Running

I think the planning slowdown is real and reproducible. 

I did some profiling and it seems it should be fairly easy to fix (we could do it in a follow on even) by optimizing the projection removal code:

Screenshot 2025-06-03 at 7 03 07 AM
Screenshot 2025-06-03 at 7 04 35 AM

File: datafusion/physical-expr/src/equivalence/properties/dependency.rs [hunk 24]
```diff
@@ -907,72 +796,13 @@ mod tests {
...
-            let (actual, _) = eq_properties.find_longest_permutation(&exprs);
+            let (actual, _) = eq_properties.find_longest_permutation(&exprs)?;
             assert_eq!(actual, expected);
         }
 
         Ok(())
     }
 
-    #[test]
-    fn test_get_finer() -> Result<()> {
```
Comment (alamb) [inline datafusion/physical-expr/src/equivalence/properties/dependency.rs:918]: Note to other reviewers, this test appears to have been moved down farther in the file and renamed to `test_requirements_compatible` (not removed)

File: datafusion/physical-expr/src/equivalence/properties/mod.rs [hunk 25]
```diff
@@ -125,40 +120,85 @@ use itertools::Itertools;
...
-    /// Expressions whose values are constant
-    ///
-    /// TODO: We do not need to track constants separately, they can be tracked
-    ///       inside `eq_group` as `Literal` expressions.
-    constants: Vec<ConstExpr>,
-    /// Table constraints
+    /// Cache storing equivalent sort expressions in normal form (i.e. without
+    /// constants/duplicates and in standard form) and a map associating leading
+    /// terms with full sort expressions.
+    oeq_cache: OrderingEquivalenceCache,
```
Comment (alamb) [inline datafusion/physical-expr/src/equivalence/properties/mod.rs:141]: 👍

File: datafusion/physical-expr/src/equivalence/properties/mod.rs (hunk 23 above)
Comment (alamb) [reply datafusion/physical-expr/src/equivalence/properties/mod.rs:470]: I agree that the example only holds when `f` preserves the lexographic ordering of a,b. In fact that I think the check for `expr_properties.preserves_lex_ordering`  is doing on line 463 above

**Comment by ozankabak** [comment]
Thanks for all the reviews. I will address them today 🚀 

With the computational complexity issue removed, I agree that we can progressively reduce the "constant factor" in running time over a few future PRs. To give reviewers some context: Complexity issue is solved by computing normalizations only once  (when equivalences are modified) and handling constants on an equal footing with other equivalences. This makes ordering checks fast, but some parts of the current codebase probably make modifications eagerly, which is the likely source of the small slowdown @alamb is seeing. I expect refactoring those parts of the code a little bit will mitigate this.

File: datafusion/physical-expr/src/equivalence/properties/mod.rs [hunk 26]
```diff
@@ -579,302 +611,289 @@ impl EquivalenceProperties {
...
+    fn common_sort_prefix_length(&self, normal_ordering: LexOrdering) -> Result<usize> {
+        let full_length = normal_ordering.len();
+        // Check whether the given ordering is satisfied by constraints:
+        if self.satisfied_by_constraints_ordering(&normal_ordering) {
+            // If constraints satisfy all sort expressions, return the full
+            // length:
+            return Ok(full_length);
+        }
+        let schema = self.schema();
+        let mut eq_properties = self.clone();
```
Comment (alamb) [inline datafusion/physical-expr/src/equivalence/properties/mod.rs:631]: I think you can avoid this clone by using `Cow` and only clone it if it needs to be updated
```diff
@@ -1157,7 +1158,8 @@ impl EquivalenceProperties {
         &self,
         exprs: &[Arc<dyn PhysicalExpr>],
     ) -> Result<(Vec<PhysicalSortExpr>, Vec<usize>)> {
-        let mut eq_properties = self.clone();
+        // Avoid cloing `self` if not necessary:
+        let mut eq_properties = Cow::Borrowed(self);
         let mut result = vec![];
         // The algorithm is as follows:
         // - Iterate over all the expressions and insert ordered expressions
@@ -1204,7 +1206,7 @@ impl EquivalenceProperties {
             // an implementation strategy confined to this function.
             for (PhysicalSortExpr { expr, .. }, idx) in &ordered_exprs {
                 let const_expr = ConstExpr::from(Arc::clone(expr));
-                eq_properties.add_constants(std::iter::once(const_expr))?;
+                eq_properties.to_mut().add_constants(std::iter::once(const_expr))?;
                 search_indices.shift_remove(idx);
             }
             // Add new ordered section to the state.
```

File: datafusion/physical-expr/src/equivalence/properties/mod.rs [hunk 27]
```diff
@@ -579,302 +611,289 @@ impl EquivalenceProperties {
...
-    /// In this case, we just substitute when the expression satisfy the following condition:
-    /// I. just have one column and is a CAST expression
-    /// TODO: Add one-to-ones analysis for monotonic ScalarFunctions.
-    /// TODO: we could precompute all the scenario that is computable, for example: atan(x + 1000) should also be substituted if
-    ///  x is DESC or ASC
-    /// After substitution, we may generate more than 1 `LexOrdering`. As an example,
-    /// `[a ASC, b ASC]` will turn into `[a ASC, b ASC], [CAST(a) ASC, b ASC]` when projection expressions `a, b, CAST(a)` is applied.
-    pub fn substitute_ordering_component(
-        &self,
+    /// TODO: Handle all scenarios that allow substitution; e.g. when `x` is
```
Comment (alamb) [inline datafusion/physical-expr/src/equivalence/properties/mod.rs:816]: I recommend we file a ticket to track this work and add a link to the ticket in the comments

**Review by alamb — APPROVED** [review]
I think this PR is good to merge as is -- thank you again for all the work

I think the code is much clearer and faster (and will be easier to work with going forward).

I also verified that the reproducer on https://github.com/apache/datafusion/issues/13748

If we are not able to resolve the planning time regression before merge, I think we should file a follow on ticket and I can help try and resolve it prior to the 49.0.0 release

Finally, here is a proposed small improvement I ran across while reviewing this PR
- https://github.com/synnada-ai/datafusion-upstream/pull/72#

# Performance Results
on main ( at 900279c5d189a62a5585210c64ab6868af4640e5)
```
Running with 10 columns...completed in 31.865667ms
Running with 20 columns...completed in 50.299667ms
Running with 30 columns...completed in 121.58075ms
Running with 40 columns...completed in 253.701875ms
Running with 50 columns...completed in 489.564584ms
Running with 60 columns...completed in 768.394167ms
Running with 70 columns...completed in 1.291121416s
Running with 80 columns...completed in 1.876029208s
Running with 90 columns...completed in 2.652548541s
Running with 100 columns...completed in 3.843196875s
```

on this branch 🚀 
```
Running with 10 columns...completed in 23.371333ms
Running with 20 columns...completed in 35.933167ms
Running with 30 columns...completed in 74.359083ms
Running with 40 columns...completed in 125.760666ms
Running with 50 columns...completed in 198.790375ms
Running with 60 columns...completed in 285.836584ms
Running with 70 columns...completed in 408.980167ms
Running with 80 columns...completed in 557.148791ms
Running with 90 columns...completed in 710.347208ms
Running with 100 columns...completed in 880.061541ms
```

File: datafusion/catalog/src/listing_schema.rs (hunk 22 above)
Comment (alamb) [reply datafusion/catalog/src/listing_schema.rs:144]: I think Default::default() is the same thing

Comment (viirya) [reply datafusion/catalog/src/listing_schema.rs:144]: I just suggest to have a consistent way to represent it...you can see there are a lot `Constraints::default()` below.

File: datafusion/physical-expr/src/equivalence/properties/mod.rs (hunk 23 above)
Comment (viirya) [reply datafusion/physical-expr/src/equivalence/properties/mod.rs:470]: Got it. I saw the `preserves_lex_ordering` check.

File: datafusion/sqllogictest/test_files/topk.slt (hunk 15 above)
Comment (viirya) [reply datafusion/sqllogictest/test_files/topk.slt:373]: So wondering why the previous one doesn't do what the comment said.

File: datafusion/physical-plan/src/sorts/sort.rs [hunk 28]
```diff
@@ -845,7 +840,7 @@ pub struct SortExec {
     /// Fetch highest/lowest n results
     fetch: Option<usize>,
     /// Normalized common sort prefix between the input and the sort expressions (only used with fetch)
-    common_sort_prefix: LexOrdering,
+    common_sort_prefix: Vec<PhysicalSortExpr>,
```
Comment (viirya) [inline datafusion/physical-plan/src/sorts/sort.rs:843]: `ExternalSorter`'s `expr` is changed from `PhysicalSortExpr`s to `LexOrdering`, but this changes from `LexOrdering` to `PhysicalSortExpr`s. Can you clarify the reason? Why not having a consistent representation for sort expressions?

File: datafusion/physical-expr-common/src/sort_expr.rs [hunk 29]
```diff
@@ -516,162 +460,240 @@ impl Display for LexOrdering {
...
+        let (non_empty, ordering) = Self::construct(value.into_iter().map(Into::into));
+        debug_assert!(non_empty);
+        ordering
+    }
+}
+
+/// Represents a plan's input ordering requirements. Vector elements represent
+/// alternative ordering requirements in the order of preference.
+#[derive(Debug, Clone, PartialEq)]
+pub enum OrderingRequirements {
```
Comment (viirya) [inline datafusion/physical-expr-common/src/sort_expr.rs:627]: I need to trace the change of `required_input_ordering` in other files here as it looks confusing at the first look between `LexRequirement` and `OrderingRequirements`. Maybe `InputOrderingRequirements` or `InputOrderingReq`?

Another question is, this looks like can be a separate change in API.

Is this also a required part of so called equivalence overhaul?

**Review by viirya — COMMENTED** [review]
I left some comments after (roughly) reviewing followed after @alamb's call on dev. 🙂 
It is roughly because the size of the changes. A 7000+ lines PR is too hard to review very in details.

Overall the change looks good and it solves the complexity issue reported. 👍 

Although the PR claims that it couldn't find an effective way to split it to smaller ones. I'm not very sure but I can see there are changes that are good to have but maybe not so urgent in just one shot, e.g., a lot of code refactors seems not core change, code comment rephrasing, API change that seems can be in separate works.

For such big overhaul, I still prefer and suggest we can it in incremental approach. It will help reviewing a lot.

File: datafusion/physical-expr-common/src/sort_expr.rs (hunk 2 above)
Comment (ozankabak) [reply datafusion/physical-expr-common/src/sort_expr.rs]: Agreed, will add a remark to the docstring.

File: datafusion/physical-expr-common/src/sort_expr.rs (hunk 5 above)
Comment (ozankabak) [reply datafusion/physical-expr-common/src/sort_expr.rs]: Looks good, will incorporate.

File: datafusion/physical-expr-common/src/sort_expr.rs (hunk 3 above)
Comment (ozankabak) [reply datafusion/physical-expr-common/src/sort_expr.rs:363]: Agreed, enriching comments accordingly.

File: datafusion/physical-expr-common/src/sort_expr.rs (hunk 4 above)
Comment (ozankabak) [reply datafusion/physical-expr-common/src/sort_expr.rs]: Right, updating accordingly.

File: datafusion/physical-expr-common/src/sort_expr.rs (hunk 1 above)
Comment (ozankabak) [reply datafusion/physical-expr-common/src/sort_expr.rs:155]: Agreed, I will add such clarifications.

File: datafusion/physical-expr-common/src/sort_expr.rs (hunk 6 above)
Comment (ozankabak) [reply datafusion/physical-expr-common/src/sort_expr.rs:523]: I initially thought so too, but seems like Rust's convention is to use `try_new` when returning a `Result`, and simply `new` when returning an `Option`. Here is an example from the standard library: https://doc.rust-lang.org/std/num/type.NonZeroU32.html

File: datafusion/physical-expr-common/src/sort_expr.rs (hunk 7 above)
Comment (ozankabak) [reply datafusion/physical-expr-common/src/sort_expr.rs:614]: Right, I will update the documentation to reflect this.

File: datafusion/physical-expr-common/src/sort_expr.rs (hunk 29 above)
Comment (ozankabak) [reply datafusion/physical-expr-common/src/sort_expr.rs:627]: We can change the name if there is a consensus on a better name. I don't really have a strong opinion on this. Regarding your last question, since `LexRequirement`s become non-degenerate, a lot of the call sites require updating. I tried organizing the changes relating to `OrderingRequirements` in a separate PR, but it didn't really reduce the diff because the call sites required updating anyway.

File: datafusion/physical-expr-common/src/sort_expr.rs (hunk 8 above)
Comment (ozankabak) [reply datafusion/physical-expr-common/src/sort_expr.rs]: Agreed, will follow your suggestion.

File: datafusion/functions-aggregate/src/first_last.rs (hunk 9 above)
Comment (ozankabak) [reply datafusion/functions-aggregate/src/first_last.rs:764]: Right -- will do.

File: datafusion/functions-aggregate/src/first_last.rs (hunk 10 above)
Comment (ozankabak) [reply datafusion/functions-aggregate/src/first_last.rs:1246]: Right, will do.

File: datafusion/physical-expr/src/equivalence/ordering.rs (hunk 11 above)
Comment (ozankabak) [reply datafusion/physical-expr/src/equivalence/ordering.rs:46]: An ordering equivalence class is basically a set of orderings, and if the table in question has no orderings, the set will be empty (which is a common/valid case). I will add some comments clarifying this.

File: datafusion/physical-expr/src/equivalence/ordering.rs (hunk 12 above)
Comment (ozankabak) [reply datafusion/physical-expr/src/equivalence/ordering.rs:136]: Exactly, will update the docstring accordingly.

File: datafusion/core/tests/dataframe/mod.rs (hunk 13 above)
Comment (ozankabak) [reply datafusion/core/tests/dataframe/mod.rs:2584]: IIRC this is a byproduct of how constants are handled (i.e. without special treatment in equivalence checks). It is indeed non-obvious, but is safe (unless I'm missing something).

File: datafusion/sqllogictest/test_files/aggregate.slt (hunk 14 above)
Comment (ozankabak) [reply datafusion/sqllogictest/test_files/aggregate.slt:163]: Actually not -- this query works now. I looked at what is going on and it seems like the requirements are not really conflicting, seems like the old equivalence system wasn't able to handle it.

It'd be great if you can double check as well, so we don't accidentally start accepting queries we can't currently execute correctly :)

File: datafusion/sqllogictest/test_files/topk.slt (hunk 15 above)
Comment (ozankabak) [reply datafusion/sqllogictest/test_files/topk.slt:373]: The old equivalence system was not performing normalizations in certain cases. Now, as we always store orderings in normal form (in addition to their original form), we don't miss these.

File: datafusion/core/src/datasource/listing/table.rs (hunk 17 above)
Comment (ozankabak) [reply datafusion/core/src/datasource/listing/table.rs:1055]: Agreed 👍

File: datafusion/core/tests/physical_optimizer/enforce_distribution.rs (hunk 18 above)
Comment (ozankabak) [reply datafusion/core/tests/physical_optimizer/enforce_distribution.rs:3218]: Agreed, let's keep this in mind in future PRs.

File: datafusion/core/tests/physical_optimizer/enforce_sorting.rs (hunk 19 above)
Comment (ozankabak) [reply datafusion/core/tests/physical_optimizer/enforce_sorting.rs:188]: Yep, let's make a push for those after we merge this PR

File: datafusion/physical-expr/src/equivalence/class.rs (hunk 21 above)
Comment (ozankabak) [reply datafusion/physical-expr/src/equivalence/class.rs:208]: No, in this case we get partition uniformity information about a constant we didn't have before, so we only update our "books".

File: datafusion/physical-expr/src/equivalence/class.rs (hunk 20 above)
Comment (ozankabak) [reply datafusion/physical-expr/src/equivalence/class.rs:210]: I agree 👍  It is indeed one of the follow-on TODOs to fix in the near term.

File: datafusion/catalog/src/listing_schema.rs (hunk 22 above)
Comment (ozankabak) [reply datafusion/catalog/src/listing_schema.rs:144]: I tried to conform to the existing style in the file. Some files use the `Default::default` pattern, while others use `TypeName::default` pattern. I agree that it'd be good if we have a uniform idiom for this case across the DF codebase. Maybe we can make this a PR in the future if there turns out to be a consensus on the style to use.

File: datafusion/physical-expr/src/equivalence/properties/mod.rs (hunk 27 above)
Comment (ozankabak) [reply datafusion/physical-expr/src/equivalence/properties/mod.rs:816]: Makes sense, will do.

File: datafusion/physical-plan/src/sorts/sort.rs (hunk 28 above)
Comment (ozankabak) [reply datafusion/physical-plan/src/sorts/sort.rs:843]: Good observation -- this is because we don't have a proper ordering here, it is just a prefix of sort expressions (which can be empty unlike an ordering).

**Comment by ozankabak** [comment]
Thanks for all the reviews. I went through each and sent a commit that addresses all the suggestions, I also tried to answer any questions I saw.

I will later resolve the conflicts and get this ready to go. I see that we are close to getting ready for the 48 release too, so it seems like we are making a good effort to align them in the way we want.

Thanks all 🚀

File: datafusion/physical-expr/src/equivalence/properties/mod.rs (hunk 26 above)
Comment (ozankabak) [reply datafusion/physical-expr/src/equivalence/properties/mod.rs:631]: I didn't really understand how this would help (probably because I'm tired after a long day :)), but we can make a tiny follow-on to do this if you think it will improve performance.

**Comment by ozankabak** [comment]
I removed the conflicts, this is in a good state now. Did we get to the 48 cut-off point yet?

**Comment by Omega359** [comment]
I plan on running my test suite against this side branch hopefully tomorrow or early next week to verify it.

**Comment by alamb** [comment]
> I removed the conflicts, this is in a good state now. Did we get to the 48 cut-off point yet?

~We are close I think~

Update yes I think main is open for new features and we can merge this one (though maybe it would be a good idea for @Omega359 to test before we do so)

**Comment by ozankabak** [comment]
I think there are some incoming big PRs, so I'd like to go ahead with this and help with fixing any issues @Omega359 finds after merge. In addition to the time cost of going through merges, I am fearful of accidentally introducing bugs every time I merge.

**Comment by ozankabak** [comment]
OK, I resolved the conflicts and all seems OK. Should we go ahead after CI passes?

**Comment by Omega359** [comment]
I'll be able to do my tests Sat afternoon or Sun morning. I'm good with doing that against either main or the branch.

**Comment by ozankabak** [comment]
Thanks @Omega359. Given that we didn't hear any concerns yesterday, I will go ahead and merge this.

Thanks everyone for all the reviews!

**Comment by alamb** [comment]
🚀  woohoo!

**Comment by Omega359** [comment]
fyi I did run this through my test suite and it seemed to work correctly :)

**Comment by alamb** [comment]
We found a regression related to this PR for `string_agg` not respecting `ORDER BY`
- https://github.com/apache/datafusion/issues/17011

@nuno-faria and @findepi  have prepared PRs to fix this, and it would be great if @ozankabak you or someone on your team could also help review it
- https://github.com/apache/datafusion/pull/17058

**Comment by berkaysynnada** [comment]
> We found a regression related to this PR for `string_agg` not respecting `ORDER BY`
> 
> * [`string_agg` does not respect `ORDER BY` on `49.0.0` #17011](https://github.com/apache/datafusion/issues/17011)
> 
> @nuno-faria and @findepi have prepared PRs to fix this, and it would be great if @ozankabak you or someone on your team could also help review it
> 
> * [[branch-49] fix: string_agg not respecting ORDER BY #17058](https://github.com/apache/datafusion/pull/17058)

I'll take a look at that today
