### PR TITLE
fix: CTEs defined in a subquery can escape their scope

### LINKED ISSUE #10914: CTE in a UNION query can escape its scope
### Describe the bug

In the following query:
```sql
(with cte as (select 1) select * from cte) 
union 
(select * from cte)
```
The visibility of the `cte` should be limited to the subquery on the left side of the UNION.

### To Reproduce

Run the following queries in CLI:
```sh
> create table t as values(100);
0 row(s) fetched.
Elapsed 0.025 seconds.

> (with t as (select 1) select * from t) union (select * from t);
+----------+
| Int64(1) |
+----------+
| 1        |
+----------+
1 row(s) fetched.
Elapsed 0.025 seconds.
```

### Expected behavior

The subquery on the right should not reference the CTE, and the result should be the same as in PostgreSQL.

```sh
postgres=# create table t as values(100);
SELECT 1

postgres=# (with t as (select 1) select * from t) union (select * from t);
 ?column?
----------
      100
        1
(2 rows)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jonahgao**
## Which issue does this PR close?

Closes #10914.

## Rationale for this change
Each query should have its own scope-visible CTEs and be able to inherit the CTEs from the outer query.
CTEs defined within a subquery should be visible only inside that subquery without affecting the outer query.
These goals can be achieved by cloning `PlannerContext` for each query.

## What changes are included in this PR?
- Clone the `PlannerContext` for each query/subquery to fix the CTE scope bug.
- Use `Arc` to make cloning the `PlannerContext` cheaper.
- Eliminate the cloning of the `PlannerContext` during planning joins and SetExprs, as this has already been done in each subquery.

## Are these changes tested?
Yes. By existing tests and new tests.

## Are there any user-facing changes?
No

### CODE REVIEW

File: datafusion/sql/src/query.rs [hunk 1]
```diff
@@ -29,23 +29,17 @@ use sqlparser::ast::{
...
-    }
+        // Each query has its own planner context, including CTEs that are visible within that query.
+        // It also inherits the CTEs from the outer query by cloning the outer planner context.
+        let mut query_plan_context = outer_planner_context.clone();
+        let planner_context = &mut query_plan_context;
 
-    /// Generate a logic plan from an SQL query.
-    /// It's implementation of `subquery_to_plan` and `query_to_plan`.
-    /// It shouldn't be invoked directly.
-    fn query_to_plan_with_schema(
```
Comment (jonahgao) [inline datafusion/sql/src/query.rs:44]: `subquery_to_plan` no longer exists, and `query_to_plan` was its only caller, so it has been merged into `query_to_plan`.

File: datafusion/sqllogictest/test_files/cte.slt [hunk 2]
```diff
@@ -834,4 +834,28 @@ SELECT * FROM non_recursive_cte, recursive_cte;
 query I
 WITH t AS (SELECT * FROM t where t.a < 2) SELECT * FROM t
 ----
-1
\ No newline at end of file
+1
+
+# Issue: https://github.com/apache/datafusion/issues/10914
+# The CTE defined within the subquery is only visible inside that subquery.
+query I rowsort
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/cte.slt:841]: I verified that this gets the wrong answer on main: 

```
DataFusion CLI v39.0.0
> (WITH t AS (SELECT 400) SELECT * FROM t) UNION (SELECT * FROM t);
+------------+
| Int64(400) |
+------------+
| 400        |
+------------+
```

File: datafusion/sql/src/query.rs [hunk 3]
```diff
@@ -29,23 +29,17 @@ use sqlparser::ast::{
...
+    /// Generate a logical plan from an SQL query/subquery
     pub(crate) fn query_to_plan(
         &self,
         query: Query,
-        planner_context: &mut PlannerContext,
+        outer_planner_context: &mut PlannerContext,
     ) -> Result<LogicalPlan> {
-        self.query_to_plan_with_schema(query, planner_context)
-    }
+        // Each query has its own planner context, including CTEs that are visible within that query.
```
Comment (alamb) [inline datafusion/sql/src/query.rs:38]: 👍

**Review by alamb — APPROVED** [review]
Very nice @jonahgao  👏  -- I think it is mark of a great engineer when they fix bugs by deleting code rather than adding it

File: datafusion/sqllogictest/test_files/cte.slt [hunk 4]
```diff
@@ -834,4 +834,28 @@ SELECT * FROM non_recursive_cte, recursive_cte;
...
+(WITH t AS (SELECT 400) SELECT * FROM t) UNION (SELECT * FROM t);
+----
+1
+2
+3
+400
+
+query error DataFusion error: Error during planning: table 'datafusion\.public\.cte' not found
+(WITH cte AS (SELECT 400) SELECT * FROM cte) UNION (SELECT * FROM cte);
```
Comment (jackwener) [inline datafusion/sqllogictest/test_files/cte.slt:850]: 👍

**Review by jackwener — APPROVED** [review]
Thanks @jonahgao

**Comment by jonahgao** [comment]
Thanks @alamb @jackwener for the review.
