### PR TITLE
Fix array types coercion: preserve child element nullability for list types

### LINKED ISSUE #17305: Array types coercion does not preserve child element nullability for list types
### Describe the bug

After upgrading from DataFusion 47 to a newer version I started seeing schema mismatch errors caused by updated array type coercion logic that does not preserve nullability information for nested types.

>SELECT offset[2]-offset[1] FROM rd;
Arrow error: Invalid argument error: column types must match schema types, expected List(Field { name: "item", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }) but found List(Field { name: "item", data_type: Int32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }) at column index 0

### To Reproduce

The following unit test can be used to verify this behavior.

>assertion `left == right` failed
  left: [[List(Field { name: "item", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), List(Field { name: "item", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} })]]
 right: [[List(Field { name: "item", data_type: Int64, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }), List(Field { name: "item", data_type: Int64, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} })]]
stack backtrace:

```rust
fn test_get_valid_types_fixed_size_arrays() -> Result<()> {
        let function = "fixed_size_arrays";
        let signature = Signature::arrays(2, None, Volatility::Immutable);

        let data_types = vec![
            DataType::new_fixed_size_list(DataType::Int64, 3, false),
            DataType::new_list(DataType::Int32, false),
        ];
        assert_eq!(
            get_valid_types(function, &signature.type_signature, &data_types)?,
            vec![vec![
                DataType::new_list(DataType::Int64, false),
                DataType::new_list(DataType::Int64, false),
            ]]
        );

        Ok(())
    }
```

This can also be observed by adding additional tracing into `coerce_arguments_for_signature_with_scalar_udf`. Observe `data_type: Int32, nullable: false` has changed to `data_type: Int32, nullable: true` in coerced type.

```rust
/// Returns `expressions` coerced to types compatible with
/// `signature`, if possible.
///
/// See the module level documentation for more detail on coercion.
fn coerce_arguments_for_signature_with_scalar_udf(
    expressions: Vec<Expr>,
    schema: &DFSchema,
    func: &ScalarUDF,
) -> Result<Vec<Expr>> {
    if expressions.is_empty() {
        return Ok(expressions);
    }

    let current_types = expressions
        .iter()
        .map(|e| e.get_type(schema))
        .collect::<Result<Vec<_>>>()?;

    let new_types = data_types_with_scalar_udf(&current_types, func)?;

    println!("schema: {:?}", schema);
    println!("current_types: {:?}", current_types);
    println!("Coerced types: {:?}", new_types);

    expressions
        .into_iter()
        .enumerate()
        .map(|(i, expr)| expr.cast_to(&new_types[i], schema))
        .collect()
}
```

```console
schema: DFSchema { inner: Schema { fields: [Field { name: "offset", data_type: FixedSizeList(Field { name: "item", data_type: Int32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, 2), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata: {"content_computed_columns": "content_embedding,content_offset"} }, field_qualifiers: [Some(Bare { table: "rd" })], functional_dependencies: FunctionalDependencies { deps: [] } }

current_types: [FixedSizeList(Field { name: "item", data_type: Int32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, 2), Int64]

Coerced types: [List(Field { name: "item", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), Int64]
```

### Expected behavior

_No response_

### Additional context

The original (correct) behavior was changed by the following improvement:
https://github.com/apache/datafusion/pull/15149#discussion_r2296274979

### PR DESCRIPTION
**Pull request by sgrebnov**
## Which issue does this PR close?

Fixes #17305

## What changes are included in this PR?

PR updates `array_valid_types`implementation to preserve nullability information for nested fields. It follows up on the change/improvement in the linked item to restore the previous behavior:

https://github.com/apache/datafusion/pull/15149#discussion_r2296274979

## Are these changes tested?

Yes, the existing unit test was expanded to cover nullability.

## Are there any user-facing changes?

No. This only prevents schema mismatch errors during execution, as described in the linked bug report.

### CODE REVIEW

File: datafusion/expr/src/type_coercion/functions.rs [hunk 1]
```diff
@@ -401,25 +401,35 @@ fn get_valid_types(
         let mut fixed_size = array_coercion != Some(&ListCoercion::FixedSizedListToList);
         let mut list_sizes = Vec::with_capacity(arguments.len());
         let mut element_types = Vec::with_capacity(arguments.len());
+        let mut nested_item_nullability = Vec::with_capacity(arguments.len());
         for (argument, current_type) in arguments.iter().zip(current_types.iter()) {
             match argument {
```
Comment (sgrebnov) [inline datafusion/expr/src/type_coercion/functions.rs:406]: Alternative approach that could be considered is the following, pls let me know if you prefer this one (does not require `nested_item_nullability` handling separately in each match)
```rust
for (argument, current_type) in arguments.iter().zip(current_types.iter()) {
  let mut field_nullability = None;
  match argument {
  ... 
    DataType::LargeList(field) => {
       ...
       field_nullability = Some(field.is_nullable());

    }
  ...
  }
  nested_item_nullability.push(field_nullability);
```

**Comment by sgrebnov** [comment]
@alamb, @jayzhan211 - Could you please take a look at this change and see if we can merge it? Without this change, we encounter the `column types must match schema types` error described in [#17305](https://github.com/apache/datafusion/issues/17305).

**Review by alamb — APPROVED** [review]
Thanks @sgrebnov  and @joroKr21  -- this makes esense to me

**Comment by sgrebnov** [comment]
Thank you @alamb and @joroKr21 for review!
