### PR TITLE
fix: disable dynamic filter pushdown for non min/max aggregates

### LINKED ISSUE #20267: [Bug] Dynamic filter leads to wrong results in some aggregation queries with >1 partitions
### Describe the bug

When `enable_dynamic_filter_pushdown` and `enable_aggregate_dynamic_filter_pushdown` are enabled (the defaults), queries on parquet files produce incorrect results with target_partitions > 1.

In this case The dynamic filter derived from MAX("ResolutionHeight") is incorrectly pushed down on ResolutionWidth instead of ResolutionHeight [ just from what i understand ], causing valid file ranges/row groups to be pruned.

### Setup

1. Use the ClickBench hits partitioned dataset

2. use datafusion-cli

3. CREATE EXTERNAL TABLE hits
STORED AS PARQUET
LOCATION '/path/to/partitioned/hits/';

4. Query with default settings -- returns wrong results
```
>  SELECT COUNT(*) as cnt, AVG("Age") as avg_age, SUM("IsRefresh") as refreshes, AVG("ResolutionWidth") as avg_width, MAX("ResolutionHeight") as max_height 
FROM hits 
WHERE "CounterID" < 1000;
+---------+-------------------+-----------+--------------------+------------+
| cnt     | avg_age           | refreshes | avg_width          | max_height |
+---------+-------------------+-----------+--------------------+------------+
| 1119068 | 26.87201403310612 | 258245    | 1539.4615429982807 | 9575       |
+---------+-------------------+-----------+--------------------+------------+
1 row(s) fetched. 
Elapsed 0.038 seconds.
```
5. Set the target partition to 1 --- same query returns right results
```
SELECT COUNT(*) as cnt, AVG("Age") as avg_age, SUM("IsRefresh") as refreshes, AVG("ResolutionWidth") as avg_width, MAX("ResolutionHeight") as max_height 
FROM hits 
WHERE "CounterID" < 1000;
0 row(s) fetched. 
Elapsed 0.000 seconds.

0 row(s) fetched. 
Elapsed 0.000 seconds.

+---------+-------------------+-----------+--------------------+------------+
| cnt     | avg_age           | refreshes | avg_width          | max_height |
+---------+-------------------+-----------+--------------------+------------+
| 1591782 | 26.14465108915668 | 266931    | 1330.2180763446252 | 9575       |
+---------+-------------------+-----------+--------------------+------------+
1 row(s) fetched. 
Elapsed 0.038 seconds.
```

6. Actual workaround with partitions

Disabling dynamic filter pushdown produces correct results even with parallel execution:
```
SET datafusion.optimizer.enable_dynamic_filter_pushdown = false;
SET datafusion.optimizer.enable_aggregate_dynamic_filter_pushdown = false;
```

### Expected behavior

The query should return right result with dynamic filter pushdown enabled / default settings with any number of partitions.

### Additional context

check `files_ranges_pruned_statistics` 
Wrong results - explain analyze output with dynamic filters enabled : 
```
|                   |           DataSourceExec: file_groups={10 groups: [[home/ec2-user/clickdata/partitioned/hits/hits_0.parquet:0..122446530, home/ec2-user/clickdata/partitioned/hits/hits_1.parquet:0..174965044, home/ec2-user/clickdata/partitioned/hits/hits_10.parquet:0..101513258, home/ec2-user/clickdata/partitioned/hits/hits_11.parquet:0..118419888, home/ec2-user/clickdata/partitioned/hits/hits_12.parquet:0..149514164, ...], [home/ec2-user/clickdata/partitioned/hits/hits_19.parquet:55500514..103692598, home/ec2-user/clickdata/partitioned/hits/hits_2.parquet:0..230595491, home/ec2-user/clickdata/partitioned/hits/hits_20.parquet:0..85766533, home/ec2-user/clickdata/partitioned/hits/hits_21.parquet:0..113455196, home/ec2-user/clickdata/partitioned/hits/hits_22.parquet:0..79775901, ...], [home/ec2-user/clickdata/partitioned/hits/hits_3.parquet:49140764..192507052, home/ec2-user/clickdata/partitioned/hits/hits_30.parquet:0..124187913, home/ec2-user/clickdata/partitioned/hits/hits_31.parquet:0..123065410, home/ec2-user/clickdata/partitioned/hits/hits_32.parquet:0..94506004, home/ec2-user/clickdata/partitioned/hits/hits_33.parquet:0..78243765, ...], [home/ec2-user/clickdata/partitioned/hits/hits_40.parquet:60145803..142508647, home/ec2-user/clickdata/partitioned/hits/hits_41.parquet:0..290614269, home/ec2-user/clickdata/partitioned/hits/hits_42.parquet:0..288524057, home/ec2-user/clickdata/partitioned/hits/hits_43.parquet:0..299692947, home/ec2-user/clickdata/partitioned/hits/hits_44.parquet:0..242404750, ...], [home/ec2-user/clickdata/partitioned/hits/hits_47.parquet:29698740..34336875, home/ec2-user/clickdata/partitioned/hits/hits_48.parquet:0..33680419, home/ec2-user/clickdata/partitioned/hits/hits_49.parquet:0..99795554, home/ec2-user/clickdata/partitioned/hits/hits_5.parquet:0..122286439, home/ec2-user/clickdata/partitioned/hits/hits_50.parquet:0..245339079, ...], ...]}, 

projection=[CounterID, IsRefresh, ResolutionWidth, ResolutionHeight, Age], file_type=parquet, 
predicate=CounterID@6 < 1000 AND DynamicFilter [ ResolutionWidth@20 > 9575 ], 
pruning_predicate=CounterID_null_count@1 != row_count@2 AND CounterID_min@0 < 1000 AND ResolutionWidth_null_count@4 != row_count@2 AND ResolutionWidth_max@3 > 9575, 


required_guarantees=[], metrics=[output_rows=1.40 M, elapsed_compute=10ns, output_bytes=16.0 MB, output_batches=171, files_ranges_pruned_statistics=109 total → 1 matched, 

row_groups_pruned_statistics=8 total → 6 matched, row_groups_pruned_bloom_filter=6 total → 6 matched, page_index_rows_pruned=0 total → 0 matched, batches_split=0, bytes_scanned=1.21 M, file_open_errors=0, file_scan_errors=0, num_predicate_creation_errors=0, predicate_cache_inner_records=0, predicate_cache_records=0, predicate_evaluation_errors=0, pushdown_rows_matched=0, pushdown_rows_pruned=0, bloom_filter_eval_time=59.03µs, metadata_load_time=926.80µs, page_index_eval_time=741ns, row_pushdown_eval_time=218ns, statistics_eval_time=46.58µs, time_elapsed_opening=2.49ms, time_elapsed_processing=49.95ms, time_elapsed_scanning_total=49.87ms, time_elapsed_scanning_until_data=10.93ms, scan_efficiency_ratio=1.2% (1.21 M/103.7 M)]
```

Correct results - explain analyze output - dynamic filters disabled :
```
|                   |           DataSourceExec: file_groups={10 groups: [[home/ec2-user/clickdata/partitioned/hits/hits_0.parquet:0..122446530, home/ec2-user/clickdata/partitioned/hits/hits_1.parquet:0..174965044, home/ec2-user/clickdata/partitioned/hits/hits_10.parquet:0..101513258, home/ec2-user/clickdata/partitioned/hits/hits_11.parquet:0..118419888, home/ec2-user/clickdata/partitioned/hits/hits_12.parquet:0..149514164, ...], [home/ec2-user/clickdata/partitioned/hits/hits_19.parquet:55500514..103692598, home/ec2-user/clickdata/partitioned/hits/hits_2.parquet:0..230595491, home/ec2-user/clickdata/partitioned/hits/hits_20.parquet:0..85766533, home/ec2-user/clickdata/partitioned/hits/hits_21.parquet:0..113455196, home/ec2-user/clickdata/partitioned/hits/hits_22.parquet:0..79775901, ...], [home/ec2-user/clickdata/partitioned/hits/hits_3.parquet:49140764..192507052, home/ec2-user/clickdata/partitioned/hits/hits_30.parquet:0..124187913, home/ec2-user/clickdata/partitioned/hits/hits_31.parquet:0..123065410, home/ec2-user/clickdata/partitioned/hits/hits_32.parquet:0..94506004, home/ec2-user/clickdata/partitioned/hits/hits_33.parquet:0..78243765, ...], [home/ec2-user/clickdata/partitioned/hits/hits_40.parquet:60145803..142508647, home/ec2-user/clickdata/partitioned/hits/hits_41.parquet:0..290614269, home/ec2-user/clickdata/partitioned/hits/hits_42.parquet:0..288524057, home/ec2-user/clickdata/partitioned/hits/hits_43.parquet:0..299692947, home/ec2-user/clickdata/partitioned/hits/hits_44.parquet:0..242404750, ...], [home/ec2-user/clickdata/partitioned/hits/hits_47.parquet:29698740..34336875, home/ec2-user/clickdata/partitioned/hits/hits_48.parquet:0..33680419, home/ec2-user/clickdata/partitioned/hits/hits_49.parquet:0..99795554, home/ec2-user/clickdata/partitioned/hits/hits_5.parquet:0..122286439, home/ec2-user/clickdata/partitioned/hits/hits_50.parquet:0..245339079, ...], ...]}, projection=[CounterID, IsRefresh, ResolutionWidth, ResolutionHeight, Age], file_type=parquet, 

predicate=CounterID@6 < 1000, pruning_predicate=CounterID_null_count@1 != row_count@2 AND CounterID_min@0 < 1000, required_guarantees=[],
 metrics=[output_rows=2.45 M, elapsed_compute=10ns, output_bytes=28.0 MB, output_batches=301, files_ranges_pruned_statistics=109 total → 20 matched, 

row_groups_pruned_statistics=51 total → 6 matched, row_groups_pruned_bloom_filter=6 total → 6 matched, page_index_rows_pruned=0 total → 0 matched, batches_split=0, bytes_scanned=1.97 M, file_open_errors=0, file_scan_errors=0, num_predicate_creation_errors=0, predicate_cache_inner_records=0, predicate_cache_records=0, predicate_evaluation_errors=0, pushdown_rows_matched=0, pushdown_rows_pruned=0, bloom_filter_eval_time=61.60µs, metadata_load_time=2.64ms, page_index_eval_time=2.00µs, row_pushdown_eval_time=218ns, statistics_eval_time=62.77µs, time_elapsed_opening=2.08ms, time_elapsed_processing=41.38ms, time_elapsed_scanning_total=44.99ms, time_elapsed_scanning_until_data=10.36ms, scan_efficiency_ratio=1.9% (1.97 M/103.7 M)] |
```

### PR DESCRIPTION
**Pull request by notashes**
## Which issue does this PR close?

- Partially closes #20267 

## Rationale for this change

Currently whenever we get a query with `min` or `max` we default to always pushing down the dynamic filter (when it's enabled). However if the query contains other aggregate functions such as `sum`, `avg` they require the full batch of rows. And because of the pruned rows we receive incorrect outputs for the query.

## What changes are included in this PR?

return the `init_dynamic_filter()` early if it contains non min/max aggregates.

## Are these changes tested?

Tested locally for the same query mentioned in the issue with `hits_partitioned` and got the correct output. Will add the tests!

### CODE REVIEW

File: datafusion/physical-plan/src/aggregates/mod.rs [hunk 1]
```diff
@@ -1129,6 +1129,16 @@ impl AggregateExec {
             return;
         }
 
+        // Don't push the dynamic filter if the query includes aggregates like
+        // COUNT, SUM, AVG as they usually require all of the rows matching the WHERE clause
+        let has_non_minmax = self.aggr_expr.iter().any(|aggr_expr| {
+            let fun_name = aggr_expr.fun().name();
+            !fun_name.eq_ignore_ascii_case("min") && !fun_name.eq_ignore_ascii_case("max")
```
Comment (adriangb) [inline datafusion/physical-plan/src/aggregates/mod.rs]: I think we can compare by expression struct instead of name

File: datafusion/physical-plan/src/aggregates/mod.rs [hunk 2]
```diff
@@ -1129,6 +1129,16 @@ impl AggregateExec {
             return;
         }
 
+        // Don't push the dynamic filter if the query includes aggregates like
+        // COUNT, SUM, AVG as they usually require all of the rows matching the WHERE clause
+        let has_non_minmax = self.aggr_expr.iter().any(|aggr_expr| {
```
Comment (adriangb) [inline datafusion/physical-plan/src/aggregates/mod.rs]: Do we need to look for nested expressions? I.e. call `agg_expr.apply` or something?

File: datafusion/physical-plan/src/aggregates/mod.rs (hunk 1 above)
Comment (notashes) [reply datafusion/physical-plan/src/aggregates/mod.rs]: Hey @adriangb 
that would require us to make `datafusion-functions-aggregate` a normal dependency from a dev-dep. Just wanted to confirm!! I also see #18643 open in case it's important! Let me know what you think!

File: datafusion/physical-plan/src/aggregates/mod.rs (hunk 2 above)
Comment (notashes) [reply datafusion/physical-plan/src/aggregates/mod.rs]: I don't think they would apply here (not any that I can think of). As physical UDAF args are `Vec<Arc<dyn PhysicalExpr>>`

```rust
/// Physical aggregate expression of a UDAF.
///
/// Instances are constructed via [`AggregateExprBuilder`].
#[derive(Debug, Clone)]
pub struct AggregateFunctionExpr {
    fun: AggregateUDF,
    args: Vec<Arc<dyn PhysicalExpr>>,
    /// Fields corresponding to args (same order & length)
    arg_fields: Vec<FieldRef>,
```

Comment (adriangb) [reply datafusion/physical-plan/src/aggregates/mod.rs]: My worry was about something like `min(avg(col))`. I can confirm that is not possible:

```sql
D create table tab(x int, y int);
D select min(avg(x)) from tab group by y;
Binder Error:
aggregate function calls cannot be nested

LINE 1: select min(avg(x)) from tab group by y;
```

File: datafusion/physical-plan/src/aggregates/mod.rs (hunk 1 above)
Comment (adriangb) [reply datafusion/physical-plan/src/aggregates/mod.rs]: Makes sense!

Comment (adriangb) [reply datafusion/physical-plan/src/aggregates/mod.rs]: Aren't we already doing this check on lines 1141 -> 1151?

```
// 1. Only `min` or `max` aggregate function
let fun_name = aggr_expr.fun().name();
// HACK: Should check the function type more precisely
// Issue: <https://github.com/apache/datafusion/issues/18643>
let aggr_type = if fun_name.eq_ignore_ascii_case("min") {
    DynamicFilterAggregateType::Min
} else if fun_name.eq_ignore_ascii_case("max") {
    DynamicFilterAggregateType::Max
} else {
    continue;
};
```

I'm guessing the only thing that is needed is to change `continue;` to `return;`

File: datafusion/physical-plan/src/aggregates/mod.rs
Comment (adriangb) [inline datafusion/physical-plan/src/aggregates/mod.rs]:
```suggestion
                return;
```

File: datafusion/physical-plan/src/aggregates/mod.rs [hunk 3]
```diff
@@ -1129,6 +1129,16 @@ impl AggregateExec {
...
+            let fun_name = aggr_expr.fun().name();
+            !fun_name.eq_ignore_ascii_case("min") && !fun_name.eq_ignore_ascii_case("max")
+        });
+        if has_non_minmax {
+            return;
+        }
+
```
Comment (adriangb) [inline datafusion/physical-plan/src/aggregates/mod.rs]:
```suggestion
```

File: datafusion/physical-plan/src/aggregates/mod.rs (hunk 1 above)
Comment (notashes) [reply datafusion/physical-plan/src/aggregates/mod.rs]: oh yes, that should do it! thanks for the review!

**Comment by adriangb** [comment]
@notashes can we add a test? Ideally an SLT test in `datafusion/sqllogictest/test_files/push_down_filter.slt`

File: datafusion/sqllogictest/test_files/dynamic_filter_pushdown_config.slt [hunk 4]
```diff
@@ -288,6 +288,42 @@ physical_plan
 04)------RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=1
 05)--------DataSourceExec: file_groups={1 group: [[WORKSPACE_ROOT/datafusion/sqllogictest/test_files/scratch/dynamic_filter_pushdown_config/agg_data.parquet]]}, projection=[score], file_type=parquet, predicate=category@0 = alpha AND DynamicFilter [ empty ], pruning_predicate=category_null_count@2 != row_count@3 AND category_min@0 <= alpha AND alpha <= category_max@1, required_guarantees=[category in (alpha)]
 
+# Test 4b: Mixed aggregates with non MIN/MAX should not have DynamicFilter
+
+# Pure MAX — DynamicFilter is expected here as we can safely prune that don't match the filter.
```
Comment (adriangb) [inline datafusion/sqllogictest/test_files/dynamic_filter_pushdown_config.slt]: I think there is already a test for this

Comment (notashes) [reply datafusion/sqllogictest/test_files/dynamic_filter_pushdown_config.slt]: removed that one! thanks!

**Comment by adriangb** [comment]
I plan to merge this once CI passes 😄
