### PR TITLE
fix: Return `probe_side.len()` for RightMark/Anti count(*) queries

### LINKED ISSUE #20669: Right joins with empty schema return invalid results
### Describe the bug

This is a regression found on `branch-53`.

When a physical right join (e.g., from a `RightAnti`) is executed with an empty schema (e.g., from `count(*)` queries), it returns invalid results. The issue comes from the `build_batch_from_indices` function:
https://github.com/apache/datafusion/blob/d1a305821f4d883a2a1e13d0bbc54af43d6d0441/datafusion/physical-plan/src/joins/utils.rs#L913-L925

If the schema is empty, an empty batch with `build_indices.len()` rows is returned. However, if the join type is, e.g., `RightAnti`, the correct number of rows should be retrieved from the probe side.

One way I see of fixing this would be to add the join type to `build_batch_from_indices`, since I don't think that info is available from the current arguments. However this might require a large number of changes.

### To Reproduce

```sql
create table t1 (k int, v int);
create table t2 (k int, v int);
insert into t1 select i as k, i as v from generate_series(1, 100) t(i);
insert into t2 values (1, 1);

-- select * is ok
with t as (
    select *
    from t1
    left anti join t2 on t1.k = t2.k
)
select *
from t;
+----+----+
| k  | v  |
+----+----+
| 2  | 2  |
| 3  | 3  |
| 4  | 4  |
| 5  | 5  |
...
+----+----+
99 row(s) fetched.

-- select count(*) is wrong
with t as (
    select *
    from t1
    left anti join t2 on t1.k = t2.k
)
select count(*)
from t;
+----------+
| count(*) |
+----------+
| 1        |
+----------+
1 row(s) fetched.
```

### Expected behavior

Return the correct number of rows.

### Additional context

This bug was exposed by the empty project optimization done by #20191, but the behavior of always returning the number of rows from the build side already existed.

### PR DESCRIPTION
**Pull request by jonathanc-n**
## Which issue does this PR close?

- Closes #20669 .

## Rationale for this change
Return probe_side.len() for count(*) queries

## Are these changes tested?
slt tests

### CODE REVIEW

**Comment by jonathanc-n** [comment]
cc @nuno-faria

File: datafusion/physical-plan/src/joins/utils.rs [hunk 1]
```diff
@@ -998,9 +1003,17 @@ pub(crate) fn build_batch_from_indices(
...
     build_side: JoinSide,
+    join_type: JoinType,
 ) -> Result<RecordBatch> {
     if schema.fields().is_empty() {
-        return new_empty_schema_batch(schema, build_indices.len());
+        // For RightAnti and RightSemi joins, after `adjust_indices_by_join_type`
+        // the build_indices were untouched so only probe_indices hold the actual
+        // row count.
+        let row_count = match join_type {
+            JoinType::RightAnti | JoinType::RightSemi => probe_indices.len(),
```
Comment (comphead) [inline datafusion/physical-plan/src/joins/utils.rs:1013]: should `RightMark` be in the list?

Comment (jonathanc-n) [reply datafusion/physical-plan/src/joins/utils.rs:1013]: No it becomes the same number of indices for both left + right indices. Refer to [here](https://github.com/apache/datafusion/blob/340ef606cf19f63a6b8e01160a43a394bbfd46f4/datafusion/physical-plan/src/joins/utils.rs#L1137)

File: datafusion/sqllogictest/test_files/joins.slt [hunk 2]
```diff
@@ -5318,3 +5318,46 @@ DROP TABLE issue_20437_small;
...
+99
+
+query I
+WITH t AS (
+    SELECT *
+    FROM t1
+    LEFT SEMI JOIN t2 ON t1.k = t2.k
+)
+SELECT count(*)
+FROM t;
```
Comment (comphead) [inline datafusion/sqllogictest/test_files/joins.slt:5355]: double checked tests with duckDB, everything is fine
