### PR TITLE
Fix inconsistent schema projection in ListingTable even when schema is specified

### LINKED ISSUE #16270: Inconsistent schema coercion in `ListingTableConfig`
### Describe the bug

When registering a `ListingTable` with a `file_schema` that includes optional fields (e.g., nested structs or additional columns), the resulting projected schema and output rows vary depending on the order of input files. Changing file order causes different columns to be included in the output.

### To Reproduce

Rust code to reproduce the issue:
```rust
use datafusion::prelude::*;
use datafusion::{
    arrow::{
        array::Array, array::Float64Array, array::StringArray, array::StructArray,
        array::TimestampMillisecondArray, datatypes::DataType, datatypes::Field,
        datatypes::Schema, datatypes::TimeUnit, record_batch::RecordBatch,
    },
    dataframe::DataFrameWriteOptions,
    datasource::{
        file_format::parquet::ParquetFormat,
        listing::ListingOptions,
        listing::ListingTable,
        listing::ListingTableConfig,
        listing::ListingTableUrl,
        // schema_adapter::SchemaAdapterFactory,
    },
};
use std::{error::Error, fs, sync::Arc};

/// Helper function to create a RecordBatch from a Schema and log the process
async fn create_and_write_parquet_file(
    ctx: &SessionContext,
    schema: &Arc<Schema>,
    schema_name: &str,
    file_path: &str,
) -> Result<(), Box<dyn Error>> {
    let batch = create_batch(schema, schema_name)?;

    let _ = fs::remove_file(file_path);

    let df = ctx.read_batch(batch)?;

    df.write_parquet(
        file_path,
        DataFrameWriteOptions::default()
            .with_single_file_output(true)
            .with_sort_by(vec![col("timestamp_utc").sort(true, true)]),
        None,
    )
    .await?;

    Ok(())
}

/// Helper function to create a ListingTableConfig for given paths and schema
async fn create_listing_table_config(
    ctx: &SessionContext,
    paths: impl Iterator<Item = String>,
    schema: &Arc<Schema>,
) -> Result<ListingTableConfig, Box<dyn Error>> {
    let config = ListingTableConfig::new_with_multi_paths(
        paths
            .map(|p| ListingTableUrl::parse(&p))
            .collect::<Result<Vec<_>, _>>()?,
    )
    .with_schema(schema.as_ref().clone().into());

    let config = config.infer(&ctx.state()).await?;

    let config = ListingTableConfig {
        options: Some(ListingOptions {
            file_sort_order: vec![vec![col("timestamp_utc").sort(true, true)]],
            ..config.options.unwrap_or_else(|| {
                ListingOptions::new(Arc::new(ParquetFormat::default()))
            })
        }),
        ..config
    };

    Ok(config)
}

/// Helper function to create a ListingTable from paths and schema
async fn create_listing_table(
    ctx: &SessionContext,
    paths: impl Iterator<Item = String>,
    schema: &Arc<Schema>,
) -> Result<Arc<ListingTable>, Box<dyn Error>> {
    // Create the config
    let config = create_listing_table_config(ctx, paths, schema).await?;

    // Create the listing table
    let listing_table = ListingTable::try_new(config)?;

    Ok(Arc::new(listing_table))
}

/// Helper function to register a table and execute a query
async fn execute_and_display_query(
    ctx: &SessionContext,
    table_name: &str,
    listing_table: Arc<ListingTable>,
) -> Result<(), Box<dyn Error>> {
    println!("==> {}", table_name);
    ctx.register_table(table_name, listing_table)?;

    // Derive query automatically based on table name
    let query = format!("SELECT * FROM {} ORDER BY body", table_name);
    let df = ctx.sql(&query).await?;

    let _results = df.clone().collect().await?;
    // Print the results
    df.show().await?;

    Ok(())
}

fn create_batch(
    schema: &Arc<Schema>,
    schema_name: &str,
) -> Result<RecordBatch, Box<dyn Error>> {
    // Create arrays for each field in the schema
    let columns = schema
        .fields()
        .iter()
        .map(|field| create_array_for_field(field, 1, schema_name))
        .collect::<Result<Vec<_>, _>>()?;

    // Create record batch with the generated arrays
    RecordBatch::try_new(schema.clone(), columns).map_err(|e| e.into())
}

/// Creates an appropriate array for a given field with the specified length
fn create_array_for_field(
    field: &Field,
    length: usize,
    schema_name: &str,
) -> Result<Arc<dyn Array>, Box<dyn Error>> {
    match field.data_type() {
        DataType::Utf8 => {
            // For the body field, use schema_name; for other fields use default
            if field.name() == "body" {
                Ok(Arc::new(StringArray::from(vec![Some(schema_name); length])))
            } else {
                let default_value = format!("{}_{}", field.name(), 1);
                Ok(Arc::new(StringArray::from(vec![
                    Some(default_value);
                    length
                ])))
            }
        }
        DataType::Float64 => {
            // Default float value
            Ok(Arc::new(Float64Array::from(vec![Some(1.0); length])))
        }
        DataType::Timestamp(TimeUnit::Millisecond, tz) => {
            // Default timestamp (2021-12-31T12:00:00Z)
            let array =
                TimestampMillisecondArray::from(vec![Some(1640995200000); length]);
            // Create the array with the same timezone as specified in the field
            Ok(Arc::new(array.with_data_type(DataType::Timestamp(
                TimeUnit::Millisecond,
                tz.clone(),
            ))))
        }
        DataType::Struct(fields) => {
            // Create arrays for each field in the struct
            let struct_arrays = fields
                .iter()
                .map(|f| {
                    let array = create_array_for_field(f, length, schema_name)?;
                    Ok((f.clone(), array))
                })
                .collect::<Result<Vec<_>, Box<dyn Error>>>()?;

            Ok(Arc::new(StructArray::from(struct_arrays)))
        }
        _ => Err(format!("Unsupported data type: {}", field.data_type()).into()),
    }
}

fn create_schema1() -> Arc<Schema> {
    let schema1 = Arc::new(Schema::new(vec![
        Field::new("body", DataType::Utf8, true),
        Field::new(
            "timestamp_utc",
            DataType::Timestamp(TimeUnit::Millisecond, Some("UTC".into())),
            true,
        ),
    ]));
    schema1
}

/// Creates a schema with basic HTTP request fields plus a query_params struct field
fn create_schema2() -> Arc<Schema> {
    // Get the base schema from create_schema1
    let schema1 = create_schema1();

    // Create a new vector of fields from schema1
    let mut fields = schema1
        .fields()
        .iter()
        .map(|f| f.as_ref().clone())
        .collect::<Vec<Field>>();

    // Add the query_params field
    fields.push(Field::new(
        "query_params",
        DataType::Struct(vec![Field::new("customer_id", DataType::Utf8, true)].into()),
        true,
    ));

    // Create a new schema with the extended fields
    Arc::new(Schema::new(fields))
}

/// Creates a schema with HTTP request fields, query_params struct field, and an error field
fn create_schema3() -> Arc<Schema> {
    // Get the base schema from create_schema2
    let schema2 = create_schema2();

    // Convert to a vector of fields
    let mut fields = schema2
        .fields()
        .iter()
        .map(|f| f.as_ref().clone())
        .collect::<Vec<Field>>();

    // Add the error field
    fields.push(Field::new("error", DataType::Utf8, true));

    // Create a new schema with the extended fields
    Arc::new(Schema::new(fields))
}

/// Creates a schema with HTTP request fields, expanded query_params struct with additional fields, and an error field
fn create_schema4() -> Arc<Schema> {
    // Get the base schema from create_schema1 (we can't use schema3 directly since we need to modify query_params)
    let schema1 = create_schema1();

    // Convert to a vector of fields
    let mut fields = schema1
        .fields()
        .iter()
        .map(|f| f.as_ref().clone())
        .collect::<Vec<Field>>();

    // Add the expanded query_params field with additional fields
    fields.push(Field::new(
        "query_params",
        DataType::Struct(
            vec![
                Field::new("customer_id", DataType::Utf8, true),
                Field::new("document_type", DataType::Utf8, true),
                Field::new("fetch_from_source", DataType::Utf8, true),
                Field::new("source_system", DataType::Utf8, true),
            ]
            .into(),
        ),
        true,
    ));

    // Add the error field
    fields.push(Field::new("error", DataType::Utf8, true));

    // Create a new schema with the extended fields
    Arc::new(Schema::new(fields))
}

async fn test_datafusion_schema_evolution() -> Result<(), Box<dyn Error>> {
    let ctx = SessionContext::new();

    // Create schemas
    let schema1 = create_schema1();
    let schema2 = create_schema2();
    let schema3 = create_schema3();
    let schema4 = create_schema4();

    // Define file paths in an array for easier management
    let test_files = ["jobs1.parquet", "jobs2.parquet", "jobs3.parquet"];
    let [path1, path2, path3] = test_files; // Destructure for individual access

    // Create and write parquet files for each schema
    create_and_write_parquet_file(&ctx, &schema1, "schema1", path1).await?;
    create_and_write_parquet_file(&ctx, &schema2, "schema2", path2).await?;
    create_and_write_parquet_file(&ctx, &schema3, "schema3", path3).await?;

    let paths = vec![path1.to_string(), path2.to_string(), path3.to_string()].into_iter();
    let paths2 = vec![path1.to_string(), path2.to_string(), path3.to_string()]
        .into_iter()
        .rev();

    // Use the helper function to create the listing tables with different paths
    let table_paths = create_listing_table(&ctx, paths, &schema4).await?;
    let table_paths2 = create_listing_table(&ctx, paths2, &schema4).await?;

    // Execute query on the first table with table name "paths"
    execute_and_display_query(
        &ctx,
        "paths", // First table with original path order
        table_paths,
    )
    .await?;

    // Execute query on the second table with table name "paths2"
    execute_and_display_query(
        &ctx,
        "paths_reversed", // Second table with reversed path order
        table_paths2,
    )
    .await?;

    Ok(())
}
fn main() -> Result<(), Box<dyn Error>> {
    // Create a Tokio runtime for running our async function
    let rt = tokio::runtime::Runtime::new()?;

    // Run the function in the runtime
    rt.block_on(async { test_datafusion_schema_evolution().await })?;

    println!("Example completed successfully!");
    Ok(())
}

```

Output from above:

```
==> paths
+---------+----------------------+
| body    | timestamp_utc        |
+---------+----------------------+
| schema1 | 2022-01-01T00:00:00Z |
| schema2 | 2022-01-01T00:00:00Z |
| schema3 | 2022-01-01T00:00:00Z |
+---------+----------------------+
==> paths_reversed
+---------+----------------------+------------------------------+---------+
| body    | timestamp_utc        | query_params                 | error   |
+---------+----------------------+------------------------------+---------+
| schema1 | 2022-01-01T00:00:00Z |                              |         |
| schema2 | 2022-01-01T00:00:00Z | {customer_id: customer_id_1} |         |
| schema3 | 2022-01-01T00:00:00Z | {customer_id: customer_id_1} | error_1 |
+---------+----------------------+------------------------------+---------+
```

### Expected behavior

The output schema and rows should be consistent regardless of file order, as file_schema is explicitly provided and coercion is expected to align all inputs accordingly.

### Additional context

Discovered this while working on #15295

### PR DESCRIPTION
**Pull request by kosiew**
## Which issue does this PR close?

- Closes #16270

## Rationale for this change

Understanding the origin of a schema (whether it was inferred or explicitly specified) is important for debugging, reproducibility, and behavioral consistency in systems like DataFusion that operate on dynamic data sources. Previously, this information was not available in the `ListingTable` or its configuration, making it hard to reason about schema behavior.

## What changes are included in this PR?

- **Schema-source metadata**  
  - Introduced a new `SchemaSource` enum to track the origin of a schema (`None`, `Inferred`, `Specified`).  
  - Extended `ListingTableConfig` and `ListingTable` to carry and expose this metadata.  
  - Ensured that schema inference logic respects an explicitly set schema and does not overwrite it.  
  - Added public accessors (`schema_source()`) to inspect schema origin in both config and table.

- **Imports cleanup**  
  - Reorganized imports in `table.rs` for clarity and consistency.

- **Test refactoring & additions**  
  - Refactored single-file scan/statistics tests:  
    - Kept and cleaned up `read_single_file`.  
    - Unified Parquet-stats coverage into a single `test_table_stats_behaviors`.  
  - Consolidated file-listing tests into a parameterized `test_list_files_configurations`.  
  - Parameterized insert-into append tests via `test_insert_into_parameterized`.  
  - Added comprehensive unit tests for all `SchemaSource` cases:  
    - `test_schema_source_tracking_comprehensive`  
    - `infer_preserves_provided_schema`  
  - Removed dozens of redundant individual tests in favor of DRY loops and shared helpers (`create_test_schema`, `generate_test_files…`).

### Deleted tests → New tests mapping

| Deleted test(s)                                                                                              | Replacement tests             |
|--------------------------------------------------------------------------------------------------------------|--------------------------------------|
| `read_single_file` (old)                                                                                     | `read_single_file` (refactored)      |
| `do_not_load_table_stats_by_default`<br>`load_table_stats_when_no_stats`                                     | `test_table_stats_behaviors`         |
| `test_assert_list_files_for_scan_grouping` <br> `test_assert_list_files_for_multi_path` <br>`test_assert_list_files_for_exact_paths`                                                                     | `test_list_files_configurations`     |
| `test_insert_into_append_new_json_files`<br>`test_insert_into_append_new_csv_files`<br>`test_insert_into_append_2_new_parquet_files_defaults`<br>`test_insert_into_append_1_new_parquet_files_defaults` | `test_insert_into_parameterized`     |

## Are these changes tested?

- **Yes.** This PR includes a full suite of unit tests covering:  
  - **Single-file + stats:** `read_single_file`, `test_table_stats_behaviors`  
  - **Schema-source tracking:** `test_schema_source_tracking_comprehensive`, `infer_preserves_provided_schema`  
  - **File-listing grouping:** `test_list_files_configurations`  
  - **Insert-into append behavior:** `test_insert_into_parameterized`  

Shared helpers and parameterized loops ensure that every previously tested scenario is still exercised, with improved maintainability and coverage.  

## Are there any user-facing changes?

Yes:
- `ListingTable` now exposes a `schema_source()` method, enabling downstream consumers to programmatically check the origin of the schema.
- This may help users understand or debug unexpected schema-related behavior when working with listing tables.

There are no breaking changes to the public API, but the enhancement provides improved introspection capabilities.

### CODE REVIEW

File: datafusion/core/src/datasource/listing/table.rs [hunk 1]
```diff
@@ -2452,4 +2178,381 @@ mod tests {
...
+
+        let exec_default = table_default.scan(&state, None, &[], None).await?;
+        assert_eq!(
+            exec_default.partition_statistics(None)?.num_rows,
+            Precision::Absent
+        );
+        assert_eq!(
+            exec_default.partition_statistics(None)?.total_byte_size,
+            Precision::Absent
+        );
```
Comment (kosiew) [inline datafusion/core/src/datasource/listing/table.rs:2469]: Replace this excerpt from previous `do_not_load_table_stats_by_default`
```rust
        let opt = ListingOptions::new(Arc::new(ParquetFormat::default()));
        let schema = opt.infer_schema(&state, &table_path).await?;
        let config = ListingTableConfig::new(table_path.clone())
            .with_listing_options(opt)
            .with_schema(schema);
        let table = ListingTable::try_new(config)?;

        let exec = table.scan(&state, None, &[], None).await?;
        assert_eq!(exec.partition_statistics(None)?.num_rows, Precision::Absent);
        // TODO correct byte size: https://github.com/apache/datafusion/issues/14936
        assert_eq!(
            exec.partition_statistics(None)?.total_byte_size,
            Precision::Absent
        );
   ```

File: datafusion/core/src/datasource/listing/table.rs [hunk 2]
```diff
@@ -2452,4 +2178,381 @@ mod tests {
...
+        let exec_disabled = table_disabled.scan(&state, None, &[], None).await?;
+        assert_eq!(
+            exec_disabled.partition_statistics(None)?.num_rows,
+            Precision::Absent
+        );
+        // TODO correct byte size: https://github.com/apache/datafusion/issues/14936
+        assert_eq!(
+            exec_disabled.partition_statistics(None)?.total_byte_size,
+            Precision::Absent
+        );
```
Comment (kosiew) [inline datafusion/core/src/datasource/listing/table.rs:2489]: replaces previous load_table_stats_when_no_stats
```rust
        let opt = ListingOptions::new(Arc::new(ParquetFormat::default()))
            .with_collect_stat(false);
        let schema = opt.infer_schema(&state, &table_path).await?;
        let config = ListingTableConfig::new(table_path)
            .with_listing_options(opt)
            .with_schema(schema);
        let table = ListingTable::try_new(config)?;

        let exec = table.scan(&state, None, &[], None).await?;
        assert_eq!(exec.partition_statistics(None)?.num_rows, Precision::Absent);
        assert_eq!(
            exec.partition_statistics(None)?.total_byte_size,
            Precision::Absent
        );
 ```

File: datafusion/core/src/datasource/listing/table.rs [hunk 3]
```diff
@@ -2452,4 +2178,381 @@ mod tests {
...
+        let exec_enabled = table_enabled.scan(&state, None, &[], None).await?;
+        assert_eq!(
+            exec_enabled.partition_statistics(None)?.num_rows,
+            Precision::Exact(8)
+        );
+        // TODO correct byte size: https://github.com/apache/datafusion/issues/14936
+        assert_eq!(
+            exec_enabled.partition_statistics(None)?.total_byte_size,
+            Precision::Exact(671)
+        );
```
Comment (kosiew) [inline datafusion/core/src/datasource/listing/table.rs:2507]: from previous do_not_load_table_stats_by_default
```rust
        let opt = ListingOptions::new(Arc::new(ParquetFormat::default()))
            .with_collect_stat(true);
        let schema = opt.infer_schema(&state, &table_path).await?;
        let config = ListingTableConfig::new(table_path)
            .with_listing_options(opt)
            .with_schema(schema);
        let table = ListingTable::try_new(config)?;

        let exec = table.scan(&state, None, &[], None).await?;
        assert_eq!(
            exec.partition_statistics(None)?.num_rows,
            Precision::Exact(8)
        );
        // TODO correct byte size: https://github.com/apache/datafusion/issues/14936
        assert_eq!(
            exec.partition_statistics(None)?.total_byte_size,
            Precision::Exact(671)
        );
```

File: datafusion/core/src/datasource/listing/table.rs [hunk 4]
```diff
@@ -2452,4 +2178,382 @@ mod tests {
...
+        assert_eq!(
+            exec_default.partition_statistics(None)?.num_rows,
+            Precision::Absent
+        );
+
+        // TODO correct byte size: https://github.com/apache/datafusion/issues/14936
+        assert_eq!(
+            exec_default.partition_statistics(None)?.total_byte_size,
+            Precision::Absent
+        );
```
Comment (kosiew) [inline datafusion/core/src/datasource/listing/table.rs:2468]: Replace this excerpt from previous do_not_load_table_stats_by_default

```rust
        let opt = ListingOptions::new(Arc::new(ParquetFormat::default()));
        let schema = opt.infer_schema(&state, &table_path).await?;
        let config = ListingTableConfig::new(table_path.clone())
            .with_listing_options(opt)
            .with_schema(schema);
        let table = ListingTable::try_new(config)?;

        let exec = table.scan(&state, None, &[], None).await?;
        assert_eq!(exec.partition_statistics(None)?.num_rows, Precision::Absent);
        // TODO correct byte size: https://github.com/apache/datafusion/issues/14936
        assert_eq!(
            exec.partition_statistics(None)?.total_byte_size,
            Precision::Absent
        );
```

File: datafusion/core/src/datasource/listing/table.rs [hunk 5]
```diff
@@ -17,44 +17,53 @@
...
-use async_trait::async_trait;
+use datafusion_physical_plan::{empty::EmptyExec, ExecutionPlan, Statistics};
 use futures::{future, stream, Stream, StreamExt, TryStreamExt};
 use itertools::Itertools;
 use object_store::ObjectStore;
+use std::{any::Any, collections::HashMap, str::FromStr, sync::Arc};
+/// Indicates the source of the schema for a [`ListingTable`]
+/// PartialEq required for assert_eq! in tests
+#[derive(Debug, Clone, PartialEq)]
+pub enum SchemaSource {
```
Comment (xudong963) [inline datafusion/core/src/datasource/listing/table.rs:59]: I really like this, the explicit representation definitely will reduce confusion

**Comment by kosiew** [comment]
Thanks @xudong963 for the review.

File: datafusion/core/src/datasource/listing/table.rs (hunk 5 above)
Comment (alamb) [reply datafusion/core/src/datasource/listing/table.rs:59]: 100% -- this is great

cc @adriangb

File: datafusion/core/src/datasource/listing/table.rs [hunk 6]
```diff
@@ -17,44 +17,53 @@
...
-use datafusion_physical_plan::{ExecutionPlan, Statistics};
-
-use async_trait::async_trait;
+use datafusion_physical_plan::{empty::EmptyExec, ExecutionPlan, Statistics};
 use futures::{future, stream, Stream, StreamExt, TryStreamExt};
 use itertools::Itertools;
 use object_store::ObjectStore;
+use std::{any::Any, collections::HashMap, str::FromStr, sync::Arc};
+/// Indicates the source of the schema for a [`ListingTable`]
+/// PartialEq required for assert_eq! in tests
```
Comment (alamb) [inline datafusion/core/src/datasource/listing/table.rs]: I personally think we don't have to explain the `PartialEq` in the user facing documentation. Maybe we could do this as a `//` normal comment

```suggestion
// PartialEq required for assert_eq! in tests
```

File: datafusion/core/src/datasource/listing/table.rs [hunk 7]
```diff
@@ -768,6 +808,9 @@ impl ListingTable {
     ///
     /// See documentation and example on [`ListingTable`] and [`ListingTableConfig`]
     pub fn try_new(config: ListingTableConfig) -> Result<Self> {
+        // Extract schema_source before moving other parts of the config
+        let schema_source = config.schema_source().clone();
```
Comment (alamb) [inline datafusion/core/src/datasource/listing/table.rs]: Minor nit: since SchemaSource is just a bare enum, it might also make sense to `#derive(Copy)` so we didn't have to clone it explicitly. 

This is totally unecessary I just wanted to mention it as a possibility

Comment (kosiew) [reply datafusion/core/src/datasource/listing/table.rs]: >  make sense to #derive(Copy) so we didn't have to clone it explicitly.

💯 and [implemented here](https://github.com/apache/datafusion/pull/16305/commits/21ad8fbc3a7728fa04c943c9bedd01acd9766b01).
