### PR TITLE
Compute gcd with u64 instead of i64 because of overflows

### LINKED ISSUE #11031: Bugs in LCM/GCD scalar functions (found by SQLancer)
### Describe the bug

1. It should return an error instead of crash
```shell
> SELECT LCM(9223372036854775807, -9223372036854775808);
thread 'main' panicked at /arrow-datafusion/datafusion/functions/src/math/gcd.rs:112:9:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

DataFusion CLI v39.0.0
> SELECT GCD(9223372036854775807, -9223372036854775808);
thread 'main' panicked at /arrow-datafusion/datafusion/functions/src/math/gcd.rs:112:9:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

2. This query get stuck for really long time, but same query in duckdb can return immediately
```shell
DataFusion CLI v39.0.0
> select GCD(-9223372036854775808, 1);
^C

DataFusion CLI v39.0.0
> select LCM(-9223372036854775808, 1);
^C
```

Found by very initial implementation of SQLancer https://github.com/apache/datafusion/issues/11030

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LorrensP-2158466**
## Which issue does this PR close?

Closes #11031.

## Rationale for this change
The issue mentioned 2 problems, I'll give an explanation here why this happened:

LCM depends on GCD, and the problems are indeed in GCD, so I expect that a fix to GCD will also fix LCM.

### Problem 1
This is because of using `i64` when computing the gcd, but the gcd is never negative. Rust doc also says that `i64::MIN.wrapping_abs() == i64::MIN`, so in the error case mentioned the gcd_compute goes like this:\
- Initial values
`a` = i64::MAX, `b` = i64::MIN
- After `wrapping_abs`:
`a` = still i64::MAX, `b` = still i64::MIN
- After the binary shifts:
`a` = still i64::MAX, b = -1 (here lies the problem)
- we swap `a` and `b` because a > b:
`a` = -1, `b` = i64::MAX
- Now we subtract a from b:
i64::MAX - (-1) = i64::MAX + 1 (here is our integer overflow)\

And because LCM depends on GCD, it also crashed similarly.

### Problem 2
The exact same reason as problem 1: when we do the `wrapping_abs`, we don't change the value of `i64::MIN`, causing the function to stall because it keeps switching `a` and `b`, which either have values -1 or 2.

These edge cases cause overflows or infinite loops, which are bugs, so we fix them.

### Solution
I propose we do the computations with `u64` and in the end, cast the result back to `i64`; this is safe since the input is never bigger than `i64::MAX` or smaller than `i64::MIN`.
This fixes both GCD and LCM

## What changes are included in this PR?
Compute GCD with `u64` and after computation, cast them back to `i64`

## Are these changes tested?
Tested this against the values used in the issue, also created an extra test case for this.
Other test also passed.

## Are there any user-facing changes?
No

### CODE REVIEW

File: datafusion/functions/src/math/gcd.rs [hunk 1]
```diff
@@ -88,14 +88,15 @@ fn gcd(args: &[ArrayRef]) -> Result<ArrayRef> {
...
 pub fn compute_gcd(x: i64, y: i64) -> i64 {
-    let mut a = x.wrapping_abs();
-    let mut b = y.wrapping_abs();
+    // because the input values are i64, casting these u64's back to i64 causes no overflow
+    let mut a = x.unsigned_abs();
+    let mut b = y.unsigned_abs();
 
     if a == 0 {
-        return b;
+        return b as i64;
```
Comment (jayzhan211) [inline datafusion/functions/src/math/gcd.rs:96]: If we move `unsigned_abs();` below, we don't need to cast

Comment (LorrensP-2158466) [reply datafusion/functions/src/math/gcd.rs:96]: Ah yes, nice catch! Thanks!

File: datafusion/functions/src/math/gcd.rs [hunk 2]
```diff
@@ -142,4 +143,22 @@ mod test {
         assert_eq!(ints.value(2), 5);
         assert_eq!(ints.value(3), 8);
     }
+
+    // from issue https://github.com/apache/datafusion/issues/11031 we know that the previous implementation could
+    // not handle cases were one or both of the inputs were an i64::MAX or i64::MIN coupled with other values (neg or pos)
+    #[test]
+    fn test_gcd_i64_maxes() {
```
Comment (jonahgao) [inline datafusion/functions/src/math/gcd.rs:150]: I think these tests can be implemented as [slt](https://github.com/apache/datafusion/blob/18042fd69138e19613844580408a71a200ea6caa/datafusion/sqllogictest/test_files/scalar.slt#L451).

**Comment by jonahgao** [comment]
The following query seems to return an incorrect result.
```sh
DataFusion CLI v39.0.0
> select gcd(-9223372036854775808, -9223372036854775808);
+--------------------------------------------------------------+
| gcd(Int64(-9223372036854775808),Int64(-9223372036854775808)) |
+--------------------------------------------------------------+
| -9223372036854775808                                         |
+--------------------------------------------------------------+
1 row(s) fetched.
Elapsed 0.007 seconds.
```
In PostgreSQL:
```sh
postgres=# select gcd(-9223372036854775808, -9223372036854775808);
ERROR:  bigint out of range
```

**Comment by LorrensP-2158466** [comment]
I think that is expected if we want to return `i64`,  if we enter the loop right before we return, we will have following values: `a` = 1, `b` = 0 and `shift` = 63, doing `1 << 63` wil result in `i64::MIN`, which is the final result. But the gcd can't be negative, so i think the only way to fix that issue is to return a `u64`, which will alter the API. Should we open up a separate issue and fix that after this one? 

I don't know why postgres' implementation results in a overflow, because when I change the output to u64 in datafusion, it works as expected.

**Comment by jonahgao** [comment]
> so i think the only way to fix that issue is to return a `u64`, which will alter the API.

@LorrensP-2158466  How about returning an overflow error when the final result cannot fit into `i64`? This way, it won't cause an API change. Something like this:
```rust
i64::try_from(a << shift).map_err(|_| exec_datafusion_err!("Overflow in gcd"))
```
I think we could have a separate fix for it.

**Comment by LorrensP-2158466** [comment]
> How about returning an overflow error when the final result cannot fit into i64? This way, it won't cause an API change. Something like this:

yes that is much nicer.
> I think we could have a separate fix for it.

I agree, do you want me to open it up or do you want to do it?

Also Thanks  @2010YOUY01! Your tool caught some weird edge cases.

**Comment by jonahgao** [comment]
> I agree, do you want me to open it up or do you want to do it?

Just go ahead; it will be very appreciated @LorrensP-2158466
