### PR TITLE
use ProjectionExprs:project_statistics in FileScanConfig

### LINKED ISSUE #14936: `Statistics::total_byte_size` does not account for projection in `FileScanConfig::with_projection`
### Describe the bug

As @blaginin  found in https://github.com/apache/datafusion/pull/14685, the statistics when a File is projected (aka only a subset of the columns are present) is incorrect

Specifically, the projected statistics have the same `total_byte_size`  as the input. However, given only a subset of columns are selected this will mean that the `total_byte_size` should actually be lower

### To Reproduce

See tests referenced in  https://github.com/apache/datafusion/pull/14685

### Expected behavior

`total_byte_size` should take into account the subset of columns

### Additional context

_No response_

### LINKED ISSUE #19075: Projection fails on TPCDS Q13
After latest merge with main I'm getting 
```
thread 'main' (115794474) panicked at datafusion/physical-expr/src/projection.rs:374:22:
Expected column reference in projection
```
on Q13, investigating

_Originally posted by @comphead in https://github.com/apache/datafusion/issues/18985#issuecomment-3608127304_

### PR DESCRIPTION
**Pull request by adriangb**
- Fixes #14936
- fixes #19075

### CODE REVIEW

File: datafusion/core/tests/physical_optimizer/partition_statistics.rs [hunk 1]
```diff
@@ -418,7 +417,7 @@ mod test {
 
         let expected_stats = Statistics {
             num_rows: Precision::Inexact(4),
-            total_byte_size: Precision::Inexact(220),
```
Comment (adriangb) [inline datafusion/core/tests/physical_optimizer/partition_statistics.rs:421]: I'm trying to understand why these numbers changed. I think the issue is that the way the row sizes are calculated when the statistics are initially computed doesn't match how the row sizes are calculated by `ProjectionExprs`. I'm guessing they're measuring different things (parquet row size vs arrow row size??). Unfortunately the `Statistics` struct doesn't have much in terms of documentation.

Comment (adriangb) [reply datafusion/core/tests/physical_optimizer/partition_statistics.rs:421]: Indeed this is the case:

https://github.com/apache/datafusion/blob/388db0e52f8e31256ba6185cfb9605c1e678c74c/datafusion/datasource-parquet/src/metadata.rs#L253

So the initial collection just adds up the size of the row groups (in Parquet). But presumably we want the size to be the size returned by the scan, not the size of the scan itself. So this is wrong, it should be doing the same calculation as `ProjectionExprs`.

**Comment by alamb** [comment]
functio docs CI check is failing due to
- https://github.com/apache/datafusion/pull/19088

Fix in 
- https://github.com/apache/datafusion/pull/19093

File: datafusion/datasource/src/file_scan_config.rs [hunk 2]
```diff
@@ -799,27 +799,16 @@ impl FileScanConfig {
...
-                }
-            })
-            .collect();
-
-        Statistics {
-            num_rows: statistics.num_rows,
-            // TODO correct byte size: https://github.com/apache/datafusion/issues/14936
-            total_byte_size: statistics.total_byte_size,
-            column_statistics: table_cols_stats,
+        let projection = self.file_source.projection();
```
Comment (alamb) [inline datafusion/datasource/src/file_scan_config.rs]: 👌

File: datafusion/core/tests/physical_optimizer/partition_statistics.rs (hunk 1 above)
Comment (adriangb) [reply datafusion/core/tests/physical_optimizer/partition_statistics.rs:421]: I'm going to include a fix in this PR so that the original collection matches 😄

Comment (alamb) [reply datafusion/core/tests/physical_optimizer/partition_statistics.rs:421]: I agree using "bytes of arrow data" sounds better compared to "bytes of parquet encoded data"

i would have thought the difference is due to your fixing this:

~(BTW I think you could mark this PR as fixing that issue as well)~

Edit: I see you did!

```
 // TODO correct byte size: https://github.com/apache/datafusion/issues/14936
            total_byte_size: statistics.total_byte_size,
```

**Comment by comphead** [comment]
Some stats tests are failing

**Comment by adriangb** [comment]
Yes will fix later tonight / tomorrow

**Comment by adriangb** [comment]
The only failing test is also failing on `main`: https://github.com/apache/datafusion/actions/runs/19962057560/job/57244600157#step:4:2618

**Comment by alamb** [comment]
> The only failing test is also failing on `main`: https://github.com/apache/datafusion/actions/runs/19962057560/job/57244600157#step:4:2618

- Filed https://github.com/apache/datafusion/issues/19114 to track
- PR to workaround: https://github.com/apache/datafusion/pull/19115

**Comment by adriangb** [comment]
Thanks all for the reviews!
