### PR TITLE
fix: Filter out nulls properly in approx_percentile_cont_with_weight

### LINKED ISSUE #4259: approx_percentile_cont panics because array is not ordered
**Describe the bug**
approx_quantile_cont panics, complaining that the input to TDigest is not ordered:
```panicked at 'unsorted input to TDigest'```

I have done some digging to understand what happens and it seams to have something to do with a corruption of indexes whithin the arrow Array.

I added a simple check to see if the array is ordered, and if not to print it in the [update_batch](https://github.com/apache/arrow-datafusion/blob/929a17525917727aa99b26667e9c3a8c55bd67c3/datafusion/physical-expr/src/aggregate/approx_percentile_cont.rs#L368-L374) function
```rust
    fn update_batch(&mut self, values: &[ArrayRef]) -> Result<()> {
        let values = &values[0];
        let v = downcast_value!(values, Int64Array);
        let sorted_values = &arrow::compute::sort(values, None)?;
        let a_down = downcast_value!(sorted_values, Int64Array);

        let mut is_sorted = true;
        for i in 0..sorted_values.len() -1 {
            if a_down.value(i) > a_down.value(i+1) {
                is_sorted = false;
                break;
            }
        }
        if !is_sorted {
           for i in 0..sorted_values.len() {
            println!("s: {}, b: {}", a_down.value(i), v.value(i));
        }
        }
        let sorted_values =
            ApproxPercentileAccumulator::convert_to_ordered_float(sorted_values)?;
        self.digest = self.digest.merge_sorted_f64(&sorted_values);
        Ok(())
    }
```

The output is surprising, we see that in seemingly every case, the first value of the sorted array *"s"* should be at the end of the array.
For intance on this array :
image

The weird thing is that if I recreate the array, the sort works properly and the panic goes away.
```rust
    fn update_batch(&mut self, values: &[ArrayRef]) -> Result<()> {
        let values = &values[0];
        # If I just recreate the array before the sorting, the problem goes away
        let v = downcast_value!(values, Int64Array);
        let values: Int64Array = v.iter().map(|d| d.clone()).collect();
        let values = Arc::new(values) as ArrayRef;
        let values = &values;
        let sorted_values =
            ApproxPercentileAccumulator::convert_to_ordered_float(sorted_values)?;
        self.digest = self.digest.merge_sorted_f64(&sorted_values);
        Ok(())
}
```
This makes me think that their may be some kind of index corruption within the array buffer.

I had this bug while performing an approx_percentile_cont on a GROUP BY, whithout the GROUP BY it works fine.

**To Reproduce**
Steps to reproduce:
1. Download the parquet file: [percentile_cont_bug.zip](https://github.com/apache/arrow-datafusion/files/10032416/percentile_cont_bug.zip)

2. Execute this function

```rust
fn percentile_cont_bug() ->Result<(), ()>{
    let ctx = SessionContext::new();
    let pq_path = "...path to the provided parquet file";
    ctx.register_parquet("example", pq_path, ParquetReadOptions::default())
        .await
        .map_err(|e|())?;
    
    let q = format!("
        SELECT 
            country,
            approx_median(age) as median_age,
        FROM example
        group by 
            country
    ");
    let df = ctx.sql(&q).await
    .map_err(|e| println!("err: {:?}", e))?;
    // execute and print results
    df.show().await;
    Ok(())
}
```

**Additional context**
datafusion version: 14.0.0
arrow version: 26.0
platform: WSL (ubuntu)

### PR DESCRIPTION
**Pull request by Jefffrey**
## Which issue does this PR close?

- Closes #4259

## Rationale for this change

#4259 was actually resolved by #11721, however I noticed this same fix wasn't applied on `approx_percentile_cont_with_weight`. Fixing it for this function too.

## What changes are included in this PR?

When updating batches in the `ApproxPercentileWithWeightAccumulator`, filter out null values in both arrays (taking care to filter out corresponding value in other array if partner value is null). Also add a debug assert in `ApproxPercentileAccumulator::convert_to_float` to ensure we don't accidentally pass in arrays with nulls again.

Also fix some visibility modifiers on `ApproxPercentileAccumulator` methods.

## Are these changes tested?

Added SLT tests.

## Are there any user-facing changes?

API change technically as changing some methods in `ApproxPercentileAccumulator` from `pub` to `pub(crate)`; I don't think these were meant to be `pub` in the first place based on the comments. I can revert this change if we decide to just leave them in the public API.

### CODE REVIEW

File: datafusion/functions-aggregate/src/approx_percentile_cont_with_weight.rs [hunk 1]
```diff
@@ -268,15 +269,37 @@ impl Accumulator for ApproxPercentileWithWeightAccumulator {
...
+                weights = filter(&weights, predicate)?;
+            }
+            (true, false) => {
+                let predicate = &is_not_null(&means)?;
+                means = filter(&means, predicate)?;
+                weights = filter(&weights, predicate)?;
+            }
+            // No nulls
+            (false, false) => {}
+        }
```
Comment (Jefffrey) [inline datafusion/functions-aggregate/src/approx_percentile_cont_with_weight.rs:295]: Handling in a similar way to `ApproxPercentileAccumulator`:

https://github.com/apache/datafusion/blob/c1d6f343161ad7a3a9a372469fafd529d0085ada/datafusion/functions-aggregate/src/approx_percentile_cont.rs#L493-L503

We could instead change `ApproxPercentileAccumulator::convert_to_float` to output `Vec<Option<f64>>` to properly handle nulls, but I assume it's more efficient to get rid of nulls upfront. Happy for any other suggestions.

File: datafusion/sqllogictest/test_files/aggregate.slt [hunk 2]
```diff
@@ -1540,6 +1540,19 @@ SELECT APPROX_PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY v) FROM (VALUES (CAST(
 ----
 NULL
 
+# percentile_cont_with_weight_with_nulls
+query I
+SELECT APPROX_PERCENTILE_CONT_WITH_WEIGHT(w, 0.5) WITHIN GROUP (ORDER BY v)
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/aggregate.slt:1545]: I verified these queries get different answers on main:

```sql

> SELECT APPROX_PERCENTILE_CONT_WITH_WEIGHT(w, 0.5) WITHIN GROUP (ORDER BY v)
FROM (VALUES (1, 1), (2, 1), (3, 1), (4, NULL), (NULL, 1), (NULL, NULL)) as t (v, w);
+----------------------------------------------------------------------------------------+
| approx_percentile_cont_with_weight(t.w,Float64(0.5)) WITHIN GROUP [t.v ASC NULLS LAST] |
+----------------------------------------------------------------------------------------+
| 0                                                                                      |
+----------------------------------------------------------------------------------------+
1 row(s) fetched.
Elapsed 0.031 seconds.

> SELECT APPROX_PERCENTILE_CONT_WITH_WEIGHT(1, 0.5) WITHIN GROUP (ORDER BY v) FROM (VALUES (CAST(NULL as INT))) as t (v);

+---------------------------------------------------------------------------------------------+
| approx_percentile_cont_with_weight(Int64(1),Float64(0.5)) WITHIN GROUP [t.v ASC NULLS LAST] |
+---------------------------------------------------------------------------------------------+
| 0                                                                                           |
+---------------------------------------------------------------------------------------------+
1 row(s) fetched.
Elapsed 0.004 seconds.
```

Thanks @Jefffrey

**Comment by alamb** [comment]
Thanks again @Jefffrey
