### PR TITLE
Avoid Aliased Window Expr Enter Unreachable Code

### LINKED ISSUE #14108: Aliased Window Expr enters unreachable code
### Describe the bug

There is an `unreachable!()` line in `PushDownFilter` rule, where `LogicalPlan::Window` is being handled.

https://github.com/apache/datafusion/blob/f9cc3325cdb5891b7566a6f3503c1f7ac6ad51e0/datafusion/optimizer/src/push_down_filter.rs#L1020

The following query enters there:

```rust
    pub(crate) const QUERY2: &str = "
    -- Define the subquery
    WITH SubQuery AS (
        SELECT
            a.column1,
            a.column2 AS ts_column,
            a.column3,
            SUM(a.column3) OVER (
                PARTITION BY a.column1
                ORDER BY a.column2 RANGE BETWEEN INTERVAL '10 minutes' PRECEDING AND CURRENT ROW
            ) AS moving_sum
        FROM source_table a
    )
    SELECT
        column1,
        ts_column,
        moving_sum
    FROM SubQuery
    WHERE moving_sum > 100
    ";
```

### To Reproduce

```rust
    #[tokio::test]
    async fn test_window_alias_in_subquery() -> Result<()> {
        let schema = Arc::new(Schema::new(vec![
            Field::new("column1", DataType::Utf8, false),
            Field::new(
                "column2",
                DataType::Timestamp(TimeUnit::Nanosecond, None),
                false,
            ),
            Field::new("column3", DataType::Float64, false),
        ]));

        let column1 = Arc::new(StringArray::from(vec!["item1", "item2", "item1"]));
        let column2 = Arc::new(TimestampNanosecondArray::from(vec![
            1_000_000_000,
            2_000_000_000,
            3_000_000_000,
        ]));
        let column3 = Arc::new(Float64Array::from(vec![50.0, 30.0, 25.0]));
        let source_table =
            RecordBatch::try_new(schema.clone(), vec![column1, column2, column3])?;

        let mut ctx = SessionContext::new();
        ctx.register_batch("source_table", source_table)?;

        let df = ctx.sql(QUERY2).await?;
        let results = df.collect().await?;

        for batch in results {
            println!("{:?}", batch);
        }

        Ok(())
    }
```

### Expected behavior

It should run without error.

### Additional context

This query works successfully:
```rust
        SELECT
            a.column1,
            a.column2 AS ts_column,
            a.column3,
            SUM(a.column3) OVER (
                PARTITION BY a.column1
                ORDER BY a.column2 RANGE BETWEEN INTERVAL '10 minutes' PRECEDING AND CURRENT ROW
            ) AS moving_sum
        FROM source_table a
```

However, if it becomes a subquery, then it starts to fail.

Handling the alias expr in the `if let` part solves the problem, but I am not sure it is the correct way.

### PR DESCRIPTION
**Pull request by berkaysynnada**
## Which issue does this PR close?

Closes #14108.

## Rationale for this change

Please see the issue.

## What changes are included in this PR?

Aliased window expr is handled as if it is a normal window expr

## Are these changes tested?

Yes, with an .slt test, which was failing before

### CODE REVIEW

**Review by ozankabak — APPROVED** [review]
LGTM

File: datafusion/optimizer/src/push_down_filter.rs [hunk 1]
```diff
@@ -1001,23 +1002,34 @@ impl OptimizerRule for PushDownFilter {
...
+                                extract_partition_keys(window_func)
+                            }
+                            Expr::Alias(alias) => {
+                                if let Expr::WindowFunction(window_func) =
+                                    alias.expr.as_ref()
+                                {
+                                    extract_partition_keys(window_func)
+                                } else {
+                                    // window functions expressions are only Expr::WindowFunction
+                                    unreachable!()
```
Comment (alamb) [inline datafusion/optimizer/src/push_down_filter.rs:1026]: maybe we can turn this into returning an internal error rather than a panic for safety

**Review by alamb — APPROVED** [review]
Thanks @berkaysynnada and @ozankabak
