### PR TITLE
Use SortMergeJoinExec name consistently in physical plan outputs

### LINKED ISSUE #19238: Inconsistent display of SortMergeJoinExec in indent vs tree plans
### Describe the bug

`SortMergeJoinExec` is currently displayed inconsistently across plan formats:

- In the indent plan, it appears as [SortMergeJoin](https://github.com/apache/datafusion/blob/20870c18a418ec081d44ecf8a90a30a95aa53138/datafusion/sqllogictest/test_files/joins.slt#L2727) (without Exec).

- In the tree plan, it appears as [SortMergeJoinExec](https://github.com/apache/datafusion/blob/20870c18a418ec081d44ecf8a90a30a95aa53138/datafusion/sqllogictest/test_files/explain_tree.slt#L1203)

To ensure consistency with other operators, both formats should use `SortMergeJoinExec`.

### To Reproduce

There are available tests. The links above are two of them

### Expected behavior

In both the indent and tree plans, all instances should be displayed as `SortMergeJoinExec`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xavlee**
## Which issue does this PR close?
- closes #19238

## Rationale for this change

`SortMergeJoinExec` is currently displayed inconsistently across physical plan formats, see [join.slt](https://github.com/apache/datafusion/blob/20870c18a418ec081d44ecf8a90a30a95aa53138/datafusion/sqllogictest/test_files/joins.slt#L2727) vs.  [explain_tree.slt](https://github.com/apache/datafusion/blob/20870c18a418ec081d44ecf8a90a30a95aa53138/datafusion/sqllogictest/test_files/explain_tree.slt#L1203).

These examples show that the tree-fmt plan uses SortMergeJoinExec, while the indent-fmt plan uses SortMergeJoin.

Standardizing the operator name improves clarity and aligns with the naming conventions of other execution operators.

## What changes are included in this PR?

Updates the `DisplayAs` implementation for `SortMergeJoinExec` to output `"SortMergeJoinExec: ..."`.

Updates SQL Logic Test expected outputs in `joins.slt` to reflect the unified naming.

No functional behavior changes; this is a display/consistency fix.

## Are these changes tested?

Yes. This change is encapsulated in existing SQL Logic Tests. I updated those expected outputs to match the new standardized naming.

All tests pass with the updated format.

## Are there any user-facing changes?

Yes—users inspecting physical plans will now consistently see `SortMergeJoinExec` instead of `SortMergeJoin`.

### CODE REVIEW

**Review by jayshrivastava — APPROVED** [review]

**Review by gene-bordegaray — APPROVED** [review]
LGTM

**Comment by NGA-TRAN** [comment]
cc @alamb @gabotechs : tiny but meaningful

**Review by 2010YOUY01 — APPROVED** [review]
Thank you for the fix!

**Comment by alamb** [comment]
Looks like there is a bunch more test updates that are needed here

File: datafusion/physical-plan/src/joins/sort_merge_join/exec.rs [hunk 1]
```diff
@@ -360,7 +360,7 @@ impl DisplayAs for SortMergeJoinExec {
                     };
                 write!(
                     f,
-                    "SortMergeJoin: join_type={:?}, on=[{}]{}{}",
+                    "SortMergeJoinExec: join_type={:?}, on=[{}]{}{}",
```
Comment (geoffreyclaude) [inline datafusion/physical-plan/src/joins/sort_merge_join/exec.rs]: This could even be `"{}: ...", Self::static_name()`

**Comment by alamb** [comment]
@xavlee will you be able to finish this PR (resolve the conflicts and update the tests?)

**Comment by xavlee** [comment]
I will complete this today, apologies for the delay.

File: datafusion/physical-plan/src/joins/sort_merge_join/exec.rs (hunk 1 above)
Comment (xavlee) [reply datafusion/physical-plan/src/joins/sort_merge_join/exec.rs]: Thx, added.

**Comment by xavlee** [comment]
@alamb I've rebased my changes and resolved conflicts 🙏 . You mentioned there were other tests that may also have to be updated–should I open a separate PR to address those?

**Comment by mbutrovich** [comment]
> @alamb I've rebased my changes and resolved conflicts 🙏 . You mentioned there were other tests that may also have to be updated–should I open a separate PR to address those?

I kicked CI so let's see if there are any tests that expect specific node names. Those would be tests that need updating. Thanks for your contribution so far!

**Comment by xavlee** [comment]
Got it, I'll update those tests as well

**Comment by comphead** [comment]
Thanks @xavlee and everyone involved, good job
