### PR TITLE
fix: Preserves field metadata when creating logical plan for VALUES expression

### LINKED ISSUE #17425: Extension metadata dropped from literals in SQL VALUES clause
### Describe the bug

Function calls that return scalars can be used in SQL VALUES; however if they contain extension metadata the metadata is dropped.

### To Reproduce

Output:

```
Regular select:
Field { name: "extension", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {"ARROW:extension:metadata": "foofy.foofy"} }


VALUES select:
Field { name: "extension", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }
```

```rust
use std::collections::HashMap;

use datafusion::{
    arrow::datatypes::DataType,
    logical_expr::{ScalarUDFImpl, Signature, Volatility},
    prelude::*,
};

#[tokio::main]
async fn main() {
    let ctx = SessionContext::new();
    ctx.register_udf(MakeExtension::default().into());

    let batches = ctx
        .sql("SELECT make_extension('foofy zero') as extension")
        .await
        .unwrap()
        .collect()
        .await
        .unwrap();
    println!("Regular select:");
    println!("{:?}", batches[0].schema().field(0));

    let batches = ctx
        .sql(
            "
SELECT extension FROM (VALUES
    ('one', make_extension('foofy one')),
    ('two', make_extension('foofy two')),
    ('three', make_extension('foofy three')))
AS t(string, extension)
        ",
        )
        .await
        .unwrap()
        .collect()
        .await
        .unwrap();

    println!("\nVALUES select:");
    println!("{:?}", batches[0].schema().field(0));
}

#[derive(Debug)]
struct MakeExtension {
    signature: Signature,
}

impl Default for MakeExtension {
    fn default() -> Self {
        Self {
            signature: Signature::user_defined(Volatility::Immutable),
        }
    }
}

impl ScalarUDFImpl for MakeExtension {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn name(&self) -> &str {
        "make_extension"
    }

    fn signature(&self) -> &Signature {
        &self.signature
    }

    fn coerce_types(&self, arg_types: &[DataType]) -> datafusion::error::Result<Vec<DataType>> {
        Ok(arg_types.to_vec())
    }

    fn return_type(&self, _arg_types: &[DataType]) -> datafusion::error::Result<DataType> {
        unreachable!("This shouldn't have been called")
    }

    fn return_field_from_args(
        &self,
        args: datafusion::logical_expr::ReturnFieldArgs,
    ) -> datafusion::error::Result<datafusion::arrow::datatypes::FieldRef> {
        Ok(args.arg_fields[0]
            .as_ref()
            .clone()
            .with_metadata(HashMap::from([(
                "ARROW:extension:metadata".to_string(),
                "foofy.foofy".to_string(),
            )]))
            .into())
    }

    fn invoke_with_args(
        &self,
        args: datafusion::logical_expr::ScalarFunctionArgs,
    ) -> datafusion::error::Result<datafusion::logical_expr::ColumnarValue> {
        Ok(args.args[0].clone())
    }
}
```

### Expected behavior

I would have expected the field metadata (if identical for all items) to be propagated to the schema of the values expression. This does bring the complexity of type equality, but byte-for-byte hash map equality should be safe. A "user defined extension type" (if there ever is one) could define a more lenient equality checker (e.g., JSON object metadata equality for extension types whose serialization is JSON).

### Additional context

cc @timsaucer  (😬 ...I can help with these, I'm just in the process of sorting through test failures and want to make sure anything we find is reported!)

### PR DESCRIPTION
**Pull request by Kontinuation**
## Which issue does this PR close?

- Closes #17425.

## Rationale for this change

The metadata of fields created by `VALUES` SQL expression were lost during the creation of `LogicalPlan::Values` logical plan node. This patch tries to preserve the field metadata.

## What changes are included in this PR?

This patch takes the metadata of fields in `VALUES` expression into consideration. The schema of `VALUES` expression will contain field with proper metadata.

## Are these changes tested?

1. Added a unit test
2. Added the repro in the issue to the `user_defined_scalar_functions` test

## Are there any user-facing changes?

No public API changes.

### CODE REVIEW

**Comment by Kontinuation** [comment]
CC @paleolimbot

File: datafusion/expr/src/logical_plan/builder.rs [hunk 1]
```diff
@@ -305,8 +305,14 @@ impl LogicalPlanBuilder {
...
         for j in 0..n_cols {
             let mut common_type: Option<DataType> = None;
+            let mut common_metadata: Option<FieldMetadata> = None;
             for (i, row) in values.iter().enumerate() {
                 let value = &row[j];
+                let metadata = value.metadata(&schema)?;
+                common_metadata = FieldMetadata::merge_options(
+                    common_metadata.as_ref(),
+                    Some(&metadata),
+                );
```
Comment (paleolimbot) [inline datafusion/expr/src/logical_plan/builder.rs]: I am not sure this is the exact merge operation we want here, since it will happily merge two completely unrelated extensions (I think) by overwriting the metadata of the first with whatever was encountered last.

It is not perfect, but a potentially safer solution might be to error for any mismatched metadata (i.e., if there's any metadata on these expressions, it has to be identical here or it will error).

**Review by paleolimbot — COMMENTED** [review]
Thank you for looking into this!

File: datafusion/expr/src/logical_plan/builder.rs (hunk 1 above)
Comment (Kontinuation) [reply datafusion/expr/src/logical_plan/builder.rs]: I agree that we should ensure that all the metadata in VALUES must be identical. This has the most unambiguous semantics and does not pose too many restrictions to typical use cases of VALUES. I'll submit commits to fix this later.

Comment (Kontinuation) [reply datafusion/expr/src/logical_plan/builder.rs]: I have updated `LogicalPlanBuilder::values` to require that all metadata should be identical. I'm not sure if a more permissive approach, such as computing the intersection of metadata, would work, but this more strict rule is a good start anyway.

**Comment by alamb** [comment]
I merged up to resolve a conflict

**Comment by alamb** [comment]
And there is now another one! I resolved it and merged up

**Comment by alamb** [comment]
🚀
