### PR TITLE
fix(substrait): Correctly parse field references in subqueries

### LINKED ISSUE #20438: Substrait consumer incorrectly parses references to outer query fields
### Describe the bug

In a substrait plan containing correlated subqueries, references to outer query fields are parsed incorrectly: we only look at the schema for the inner/subquery schema, which produced incorrect column names and types.

### To Reproduce

For example, consider TPC-H Q21, which is parsed as:

```
        Projection: SUPPLIER.S_NAME, count(Int64(1)) AS NUMWAIT
           Limit: skip=0, fetch=100
             Sort: count(Int64(1)) DESC NULLS FIRST, SUPPLIER.S_NAME ASC NULLS LAST
               Aggregate: groupBy=[[SUPPLIER.S_NAME]], aggr=[[count(Int64(1))]]
                 Projection: SUPPLIER.S_NAME
                   Filter: SUPPLIER.S_SUPPKEY = LINEITEM.L_SUPPKEY AND ORDERS.O_ORDERKEY = LINEITEM.L_ORDERKEY AND ORDERS.O_ORDERSTATUS = Utf8("F") AND LINEITEM.L_RECEIPTDATE > LINEITEM.L_COMMITDATE AND EXISTS (<subquery>) AND NOT EXISTS (<subquery>) AND SUPPLIER.S_NATIONKEY = NATION.N_NATIONKEY AND NATION.N_NAME = U\
 tf8("SAUDI ARABIA")
                     Subquery:
                       Filter: LINEITEM.L_ORDERKEY = LINEITEM.L_TAX AND LINEITEM.L_SUPPKEY != LINEITEM.L_LINESTATUS
                         TableScan: LINEITEM
                     Subquery:
                       Filter: LINEITEM.L_ORDERKEY = LINEITEM.L_TAX AND LINEITEM.L_SUPPKEY != LINEITEM.L_LINESTATUS AND LINEITEM.L_RECEIPTDATE > LINEITEM.L_COMMITDATE
                         TableScan: LINEITEM
                     Cross Join:
                       Cross Join:
                         Cross Join:
                           TableScan: SUPPLIER
                           TableScan: LINEITEM
                         TableScan: ORDERS
                       TableScan: NATION
```

Note that in the subquery, the filter has the clause `LINEITEM.L_SUPPKEY != LINEITEM.L_LINESTATUS`. This is not what Q21 contains; and in fact the types of those two columns (Int64 and Utf8) are not even compatible, although we don't currently reject this.

### Expected behavior

Parse references to outer query fields correctly.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by neilconway**
## Which issue does this PR close?

- Closes #20438.

## Rationale for this change

The substrait consumer parsed field references in correlated subqueries incorrectly. Field references were always resolved relative to the schema of the current (innermost) subquery, leading to incorrect results.

## What changes are included in this PR?

We now maintain a stack of outer query schemas, and pushes/pops elements from it as we traverse subqueries. When resolving field references, we now use `FieldReference.root_type` to detect outer query field references and resolve them against the appropriate schema.

This commit updates the expected results for parsing TPC-H queries, because several of them were parsed incorrectly (the misparsing was probably not detected because the incorrect parse didn't result in any illegal queries, by sheer luck). This also means we can enable Q17, which failed to parse before.

## Are these changes tested?

Yes. Test results updated to reflect new, correct behavior, and new unit tests added.

## Are there any user-facing changes?

The behavior of the substrait consumer has changed, although the previous behavior was wrong and it seems a bit unlikely anyone would have dependend on it. The `DefaultSubstraitConsumer` API is slightly changed (new private field).

### CODE REVIEW

**Comment by neilconway** [comment]
Hi @gabotechs @waynexia Would you have time to take a quick look at this when you get a chance? Thank you!

**Comment by gabotechs** [comment]
Requesting some backup for reviewing this one now. Thanks for taking the time!

File: datafusion/substrait/src/logical_plan/consumer/expr/field_reference.rs [hunk 1]
```diff
@@ -16,21 +16,24 @@
...
-    _consumer: &impl SubstraitConsumer,
+    consumer: &impl SubstraitConsumer,
     field_ref: &FieldReference,
     input_schema: &DFSchema,
 ) -> datafusion::common::Result<Expr> {
-    from_substrait_field_reference(field_ref, input_schema)
+    from_substrait_field_reference(consumer, field_ref, input_schema)
 }
 
 pub(crate) fn from_substrait_field_reference(
```
Comment (benbellick) [inline datafusion/substrait/src/logical_plan/consumer/expr/field_reference.rs:35]: I think that this is probably correct, but the inner code gets pretty deeply nested which can be a tad bit hard to read. What do you think about organizing the body like: 
```rust
pub(crate) fn from_substrait_field_reference(
    consumer: &impl SubstraitConsumer,
    field_ref: &FieldReference,
    input_schema: &DFSchema,
) -> datafusion::common::Result<Expr> {
    match &field_ref.reference_type {
        Some(DirectReference(direct)) => match &direct.reference_type {
            Some(StructField(struct_field)) => {
                if struct_field.child.is_some() {
                    return not_impl_err!(
                        "Direct reference StructField with child is not yet implemented"
                    );
                }
                let field_idx = struct_field.field as usize;
                match &field_ref.root_type {
                    Some(RootType::RootReference(_)) | None => Ok(Expr::Column(
                        Column::from(input_schema.qualified_field(field_idx)),
                    )),
                    Some(RootType::OuterReference(outer_ref)) => {
                        resolve_outer_reference(consumer, outer_ref, field_idx)
                    }
                    Some(RootType::Expression(_)) => not_impl_err!(
                        "Expression root type in field reference is not yet implemented"
                    ),
                }
            }
            _ => not_impl_err!(
                "Direct reference with types other than StructField is not yet implemented"
            ),
        },
        _ => not_impl_err!("unsupported field ref type"),
    }
}
```
and then moving your logic to the private `resolve_outer_reference` function? 

Just an idea, feel free to take it or leave it 🙂

File: datafusion/substrait/tests/cases/consumer_integration.rs
Comment (benbellick) [inline datafusion/substrait/tests/cases/consumer_integration.rs:1]: It might be worth it to add one more test for something that uses steps_out > 1 (AFAICT only steps_out = 1 is used in these plans). 


One possibility: 

```rust
    /// Tests nested correlated subqueries where the innermost subquery
    /// references the outermost query (steps_out=2).
    ///
    /// This tests the outer schema stack with depth > 1.
    /// The plan represents:
    /// ```sql
    /// SELECT * FROM A
    /// WHERE EXISTS (
    ///     SELECT * FROM B
    ///     WHERE B.b1 = A.a1              -- steps_out=1 (references immediate parent)
    ///       AND EXISTS (
    ///         SELECT * FROM C
    ///         WHERE C.c1 = A.a1          -- steps_out=2 (references grandparent)
    ///           AND C.c2 = B.b2          -- steps_out=1 (references immediate parent)
    ///     )
    /// )
    /// ```
    ///
    #[tokio::test]
    async fn test_nested_correlated_subquery() -> Result<()> {
        let path = "tests/testdata/test_plans/nested_correlated_subquery.substrait.json";
        let proto = serde_json::from_reader::<_, Plan>(BufReader::new(
            File::open(path).expect("file not found"),
        ))
        .expect("failed to parse json");

        let ctx = add_plan_schemas_to_ctx(SessionContext::new(), &proto)?;
        let plan = from_substrait_plan(&ctx.state(), &proto).await?;
        let plan_str = format!("{plan}");

        assert_snapshot!(
            plan_str,
            @r#"
        Filter: EXISTS (<subquery>)
          Subquery:
            Filter: B.b1 = outer_ref(A.a1) AND EXISTS (<subquery>)
              Subquery:
                Filter: C.c1 = outer_ref(A.a1) AND C.c2 = outer_ref(B.b2)
                  TableScan: C
              TableScan: B
          TableScan: A
        "#
        );
        Ok(())
    }
```

with plan

```json
{
  "extensionUris": [{
    "extensionUriAnchor": 1,
    "uri": "/functions_boolean.yaml"
  }, {
    "extensionUriAnchor": 2,
    "uri": "/functions_comparison.yaml"
  }],
  "extensions": [{
    "extensionFunction": {
      "extensionUriReference": 1,
      "name": "and:bool"
    }
  }, {
    "extensionFunction": {
      "extensionUriReference": 2,
      "functionAnchor": 1,
      "name": "equal:any_any"
    }
  }],
  "relations": [{
    "root": {
      "input": {
        "filter": {
          "common": {
            "direct": {}
          },
          "input": {
            "read": {
              "common": {
                "direct": {}
              },
              "baseSchema": {
                "names": ["a1", "a2"],
                "struct": {
                  "types": [{
                    "i64": {
                      "nullability": "NULLABILITY_REQUIRED"
                    }
                  }, {
                    "i64": {
                      "nullability": "NULLABILITY_REQUIRED"
                    }
                  }],
                  "nullability": "NULLABILITY_REQUIRED"
                }
              },
              "namedTable": {
                "names": ["A"]
              }
            }
          },
          "condition": {
            "subquery": {
              "setPredicate": {
                "predicateOp": "PREDICATE_OP_EXISTS",
                "tuples": {
                  "filter": {
                    "common": {
                      "direct": {}
                    },
                    "input": {
                      "read": {
                        "common": {
                          "direct": {}
                        },
                        "baseSchema": {
                          "names": ["b1", "b2"],
                          "struct": {
                            "types": [{
                              "i64": {
                                "nullability": "NULLABILITY_REQUIRED"
                              }
                            }, {
                              "i64": {
                                "nullability": "NULLABILITY_REQUIRED"
                              }
                            }],
                            "nullability": "NULLABILITY_REQUIRED"
                          }
                        },
                        "namedTable": {
                          "names": ["B"]
                        }
                      }
                    },
                    "condition": {
                      "scalarFunction": {
                        "outputType": {
                          "bool": {
                            "nullability": "NULLABILITY_REQUIRED"
                          }
                        },
                        "arguments": [{
                          "value": {
                            "scalarFunction": {
                              "functionReference": 1,
                              "outputType": {
                                "bool": {
                                  "nullability": "NULLABILITY_REQUIRED"
                                }
                              },
                              "arguments": [{
                                "value": {
                                  "selection": {
                                    "directReference": {
                                      "structField": {
                                        "field": 0
                                      }
                                    },
                                    "rootReference": {}
                                  }
                                }
                              }, {
                                "value": {
                                  "selection": {
                                    "directReference": {
                                      "structField": {
                                        "field": 0
                                      }
                                    },
                                    "outerReference": {
                                      "stepsOut": 1
                                    }
                                  }
                                }
                              }]
                            }
                          }
                        }, {
                          "value": {
                            "subquery": {
                              "setPredicate": {
                                "predicateOp": "PREDICATE_OP_EXISTS",
                                "tuples": {
                                  "filter": {
                                    "common": {
                                      "direct": {}
                                    },
                                    "input": {
                                      "read": {
                                        "common": {
                                          "direct": {}
                                        },
                                        "baseSchema": {
                                          "names": ["c1", "c2"],
                                          "struct": {
                                            "types": [{
                                              "i64": {
                                                "nullability": "NULLABILITY_REQUIRED"
                                              }
                                            }, {
                                              "i64": {
                                                "nullability": "NULLABILITY_REQUIRED"
                                              }
                                            }],
                                            "nullability": "NULLABILITY_REQUIRED"
                                          }
                                        },
                                        "namedTable": {
                                          "names": ["C"]
                                        }
                                      }
                                    },
                                    "condition": {
                                      "scalarFunction": {
                                        "outputType": {
                                          "bool": {
                                            "nullability": "NULLABILITY_REQUIRED"
                                          }
                                        },
                                        "arguments": [{
                                          "value": {
                                            "scalarFunction": {
                                              "functionReference": 1,
                                              "outputType": {
                                                "bool": {
                                                  "nullability": "NULLABILITY_REQUIRED"
                                                }
                                              },
                                              "arguments": [{
                                                "value": {
                                                  "selection": {
                                                    "directReference": {
                                                      "structField": {
                                                        "field": 0
                                                      }
                                                    },
                                                    "rootReference": {}
                                                  }
                                                }
                                              }, {
                                                "value": {
                                                  "selection": {
                                                    "directReference": {
                                                      "structField": {
                                                        "field": 0
                                                      }
                                                    },
                                                    "outerReference": {
                                                      "stepsOut": 2
                                                    }
                                                  }
                                                }
                                              }]
                                            }
                                          }
                                        }, {
                                          "value": {
                                            "scalarFunction": {
                                              "functionReference": 1,
                                              "outputType": {
                                                "bool": {
                                                  "nullability": "NULLABILITY_REQUIRED"
                                                }
                                              },
                                              "arguments": [{
                                                "value": {
                                                  "selection": {
                                                    "directReference": {
                                                      "structField": {
                                                        "field": 1
                                                      }
                                                    },
                                                    "rootReference": {}
                                                  }
                                                }
                                              }, {
                                                "value": {
                                                  "selection": {
                                                    "directReference": {
                                                      "structField": {
                                                        "field": 1
                                                      }
                                                    },
                                                    "outerReference": {
                                                      "stepsOut": 1
                                                    }
                                                  }
                                                }
                                              }]
                                            }
                                          }
                                        }]
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "names": ["a1", "a2"]
    }
  }]
}
```

I tested this one locally and your implementation does work 👍 but just if we wanted to lock in an extra boost of confidence.

File: datafusion/substrait/src/logical_plan/consumer/expr/field_reference.rs (hunk 1 above)
Comment (neilconway) [reply datafusion/substrait/src/logical_plan/consumer/expr/field_reference.rs:35]: Great idea! Done.

File: datafusion/substrait/tests/cases/consumer_integration.rs
Comment (neilconway) [reply datafusion/substrait/tests/cases/consumer_integration.rs:1]: Good call -- I added your test as-is. Thanks!

**Comment by neilconway** [comment]
Thanks @benbellick @gabotechs !
