### PR TITLE
fix: nested window function

### LINKED ISSUE #14910: Planning error for compound expressions involving window functions
### Describe the bug

The following query throws planning error for `DataFusion`, but it runs in `DuckDB` and `PostgreSQL`

Run in datafusion-cli (commit hash a28f2834c)
```sh
DataFusion CLI v45.0.0
> SELECT
  t1.v1,
  SUM(t1.v1) OVER w + 1
FROM
  generate_series(1, 10000) AS t1(v1)
WINDOW
  w AS (ORDER BY t1.v1 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW);

Error during planning: Projection references non-aggregate values: Expression t1.v1 could not be resolved from available columns: sum(t1.v1)
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chenkovsky**
## Which issue does this PR close?

- Closes #14910

## Rationale for this change

current implementation doesn't support nested window function in projection.

## What changes are included in this PR?

use expr visitor to find nested window function.

## Are these changes tested?

unit test

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by alamb** [comment]
> @alamb I think I have to add a BFS visitor in sqlparse crate, how do you feel about it?

i think that would mean it will take at least another month to fix this issue - as we would need a new sql parser release and then integrate that into DataFusion

If you can find another way that would likely be faster to get in

File: datafusion/core/tests/sql/sql_api.rs [hunk 1]
```diff
@@ -19,6 +19,23 @@ use datafusion::prelude::*;
...
+async fn test_window_function() {
+    let ctx = SessionContext::new();
+    let df = ctx
+        .sql(
+            r#"SELECT
+        t1.v1,
+        SUM(t1.v1) OVER w + 1
+        FROM
+        generate_series(1, 10000) AS t1(v1)
+        WINDOW
```
Comment (alamb) [inline datafusion/core/tests/sql/sql_api.rs:32]: I think we should at least have a .slt test that shows this query running and producing the same result as postgres, perhaps with a smaller number of series:

```sql
postgres=# SELECT
  t1.v1,
  SUM(t1.v1) OVER w
FROM
  generate_series(1, 5) AS t1(v1)
WINDOW
  w AS (ORDER BY t1.v1 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW);
 v1 | sum
----+-----
  1 |   1
  2 |   3
  3 |   6
  4 |  10
  5 |  15
(5 rows)
```

File: datafusion/sql/src/select.rs [hunk 2]
```diff
@@ -887,29 +888,42 @@ fn match_window_definitions(
...
-                if let Some(WindowType::NamedWindow(ident)) = &f.over {
-                    if ident.eq(window_ident) {
-                        f.over = Some(match window_expr {
-                            NamedWindowExpr::NamedWindow(ident) => {
-                                WindowType::NamedWindow(ident.clone())
-                            }
-                            NamedWindowExpr::WindowSpec(spec) => {
-                                WindowType::WindowSpec(spec.clone())
+            let mut err = None;
+            visit_expressions_mut(expr, |expr| {
```
Comment (alamb) [inline datafusion/sql/src/select.rs:895]: I am sorry @chenkovsky  and @2010YOUY01 

I don't know what 
```sql
SELECT
  t1.v1,
  SUM(t1.v1) OVER w + 1
FROM
  generate_series(1, 10) AS t1(v1)
WINDOW
  w AS (ORDER BY t1.v1);

```

Is supposed to be computing (what does adding one to a window definition like `w +1` represent?)

Comment (2010YOUY01) [reply datafusion/sql/src/select.rs:895]: DuckDB interprets it as `(SUM(t1.v1) OVER w) + 1`, and `... OVER (w + 1)` is not valid
```
D SELECT
    t1.v1,
    SUM(t1.v1) OVER (w + 1)
  FROM
    generate_series(1, 10) AS t1(v1)
  WINDOW
    w AS (ORDER BY t1.v1);
Parser Error: syntax error at or near "+"
LINE 3:   SUM(t1.v1) OVER (w + 1)
```

**Comment by alamb** [comment]
@jonahgao  would you possibly have time to help review this PR?

File: datafusion/sql/src/select.rs [hunk 3]
```diff
@@ -891,29 +892,42 @@ fn match_window_definitions(
...
+                if let SQLExpr::Function(f) = expr {
+                    if let Some(WindowType::NamedWindow(_)) = &f.over {
+                        for NamedWindowDefinition(window_ident, window_expr) in
+                            named_windows
+                        {
+                            if let Some(WindowType::NamedWindow(ident)) = &f.over {
+                                if ident.eq(window_ident) {
```
Comment (jonahgao) [inline datafusion/sql/src/select.rs:906]: Unrelated to the current fix, we should compare them using normalized names to support
```sql
SELECT
  t1.v1,
  SUM(t1.v1) OVER W + 1
FROM
  generate_series(1, 5) AS t1(v1)
WINDOW
  w AS (ORDER BY t1.v1);
```

**Review by jonahgao — APPROVED** [review]
LGTM, thank you @chenkovsky

File: datafusion/sql/src/select.rs (hunk 3 above)
Comment (alamb) [reply datafusion/sql/src/select.rs:906]: Thanks @jonahgao  -- filed as 
- https://github.com/apache/datafusion/issues/15605
