### PR TITLE
fix: Capture nullability in `Values` node planning

### LINKED ISSUE #14394: DataSink::write_all given invalid RecordBatchStream
### Describe the bug

We were trying to implement a `DataSink` and found that we were being given different schemas for the record batches than per the RecordBatchStream.

```
STREAM DTYPE Schema { fields: [Field { name: "c1", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "c2", data_type: Int32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata: {} }
RB SCHEMA: Schema { fields: [Field { name: "c1", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "c2", data_type: Int32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata: {} }

STREAM DTYPE Schema { fields: [Field { name: "c1", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "c2", data_type: Int32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata: {} }
RB SCHEMA: Schema { fields: [Field { name: "c1", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "c2", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata: {} }
```

The first (correct) invocation comes from assembling a logical plan with `LogicalPlanBuilder::insert_into`

The second (incorrect) invocation comes from `session.sql("INSERT INTO my_tbl VALUES ('hello', 42::INT);")`

I figured I'd add an assertion into the RecordBatchStreamAdapter, and it looks like ~12 tests fail on main right now with mismatched schemas. I wonder if it's worth adding that as a debug assertion?

https://github.com/gatesn/datafusion/pull/new/ngates/record-batch-stream-schema

cc @AdamGS 

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rkrishn7**
## Which issue does this PR close?

- Closes #14394

## What changes are included in this PR?

Includes field nullability from table schema when planning a `Values` node during `INSERT INTO ... VALUES`

## Are these changes tested?

Existing tests have been updated, but it would be great to figure out additional tests to add. 

## Are there any user-facing changes?

N/A

### CODE REVIEW

**Comment by alamb** [comment]
Thank you @rkrishn7  -- I marked this PR as a draft as it seems a CI test is failing. Thank you!

**Comment by alamb** [comment]
FYI @gatesn

**Comment by rkrishn7** [comment]
Thanks @alamb. Will fix it up when I'm back from work!

**Comment by rkrishn7** [comment]
`Rust / build with wasm-pack (pull_request)` is currently failing, but looks like this is due to the recent upstream release of `uuid`. Should be fixed in #14494

File: datafusion/expr/src/logical_plan/builder.rs [hunk 1]
```diff
@@ -296,12 +298,14 @@ impl LogicalPlanBuilder {
...
 
-        Self::infer_inner(values, &field_types, &schema)
+        let field_nullabilities = (0..n_cols).map(|_| true).collect::<Vec<_>>();
+        Self::infer_inner(values, &field_types, &field_nullabilities, &schema)
     }
 
     fn infer_inner(
         mut values: Vec<Vec<Expr>>,
         field_types: &[DataType],
+        field_nullabilities: &[bool],
```
Comment (alamb) [inline datafusion/expr/src/logical_plan/builder.rs:308]: Another way that you could do this is to pass in the fields

like

```rust
    fn infer_inner(
        mut values: Vec<Vec<Expr>>,
        field_types: &[&Field],
        schema: &DFSchema
    ) -> Result<Self> {
```

And then instead of making a new field 

```rust
            .map(|(j, (data_type, nullable))| {
                // naming is following convention https://www.postgresql.org/docs/current/queries-values.html
                let name = &format!("column{}", j + 1);
                Field::new(name, data_type.clone(), *nullable)
            })
```

Do something like
```rust
            .map(|(j, field)| {
                // naming is following convention https://www.postgresql.org/docs/current/queries-values.html
                field.clone().with_name(format!("column{}", j + 1))
            })
```

**Review by alamb — COMMENTED** [review]
Thank you @rkrishn7  -- this looks good to me ❤️ 
i will restart the failed CI check to get a clean run for this PR

**Review by alamb — APPROVED** [review]

File: datafusion/sqllogictest/test_files/insert.slt [hunk 2]
```diff
@@ -255,7 +255,7 @@ insert into table_without_values(id, id) values(3, 3);
 statement error Arrow error: Cast error: Cannot cast string 'zoo' to value of Int64 type
 insert into table_without_values(name, id) values(4, 'zoo');
 
-statement error Error during planning: Column count doesn't match insert query!
+statement error Error during planning: Inconsistent data length across values list: got 2 values in row 0 but expected 1
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/insert.slt:258]: These seem significantly better errors ❤️

**Comment by alamb** [comment]
I merged up from main to get a clean CI run

File: datafusion/expr/src/logical_plan/builder.rs (hunk 1 above)
Comment (rkrishn7) [reply datafusion/expr/src/logical_plan/builder.rs]: Yes, good call out!

We clone the data type to construct the field, so I just created a small container which encapsulates the naming logic as well. Think it cleans things up a bit!

**Review by alamb — APPROVED** [review]

**Review by jayzhan211 — APPROVED** [review]
👍🏻

**Comment by jayzhan211** [comment]
Thanks @rkrishn7 @alamb
