### PR TITLE
Fix: Make `CopyTo` logical plan output schema consistent with physical schema

### LINKED ISSUE #16704: Output schema of the CopyTo logical plan is not correct.
### Describe the bug

The output schema of the CopyTo logical plan currently directly outputs the underlying schema of it's child.
The physical plan however always returns a 1 row/column count which represents the number of affected rows.

This is inconsistent.

### To Reproduce

Following test fails : 

```
#[tokio::test]
async fn test_copy_schema() -> Result<()> {
    let tmp_dir = TempDir::new()?;

    let session_state = SessionStateBuilder::new_with_default_features().build();

    let session_ctx = SessionContext::new_with_state(session_state);

    let schema = Arc::new(Schema::new(vec![Field::new("a", DataType::Int64, true)]));

    // Create and register the source table with the provided schema and data
    let source_table = Arc::new(MemTable::try_new(schema.clone(), vec![vec![]])?);
    session_ctx.register_table("source_table", source_table.clone())?;

    let target_path = tmp_dir.path().join("target.csv");

    let query = format!(
        "COPY source_table TO '{:?}' STORED AS csv",
        target_path.to_str().unwrap()
    );

    let result = session_ctx.sql(&query).await?;
    assert_logical_expr_schema_eq_physical_expr_schema(result).await?;
    Ok(())
}
```

The schema of the physical output is not the same as the logical plan.

### Expected behavior

The CopyTo logical plan returns the same schema as the physical plan, being a 1 column named "count"

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bert-beyondloops**
## Which issue does this PR close?

- Closes #16704

## Rationale for this change

Schema of logical plan should be the same as the associated physical plan.

## What changes are included in this PR?

1. The logical plan schema() method for a CopyTo plan has been changed.
2. Construction of the CopyTo structure has been replaced with a "new" method and all callers have been updated.
3. A new test has been written to verify equality of the schemas of the CopyTo logical plan with the associated physical plan. See `test_copy_schema` on dataframe level. https://github.com/apache/datafusion/pull/16705/commits/e0e88a19ffe4669140b7edfb71fda129c02b91a4#diff-4a599584dfc900ec21169f4f820a1b1db46b004b77533dab83a6178d5d3a467eR6143

## Are these changes tested?

A new test has been written to verify that both the logical plan as the physical plan return the same schema.

## Are there any user-facing changes?

On SQL level, there is no change ; you cannot construct a sql statement where a CopyTo logical plan is child from another plan.

On dataframe level, retrieving the schema of a CopyTo logical plan will provide a correct schema now.

### CODE REVIEW

File: datafusion/expr/src/logical_plan/dml.rs [hunk 1]
```diff
@@ -89,6 +91,26 @@ impl Hash for CopyTo {
...
+        file_type: Arc<dyn FileType>,
+        options: HashMap<String, String>,
+    ) -> Self {
+        Self {
+            input,
+            output_url,
+            partition_by,
+            file_type,
+            options,
+            // The output schema is always a single column with the number of rows copied
```
Comment (alamb) [inline datafusion/expr/src/logical_plan/dml.rs]:
```suggestion
            // The output schema is always a single column "count" with the number of rows copied
```

File: datafusion/expr/src/logical_plan/dml.rs [hunk 2]
```diff
@@ -40,6 +40,7 @@ pub struct CopyTo {
     pub file_type: Arc<dyn FileType>,
     /// SQL Options that can affect the formats
     pub options: HashMap<String, String>,
+    pub output_schema: DFSchemaRef,
```
Comment (alamb) [inline datafusion/expr/src/logical_plan/dml.rs:44]:
```suggestion
    /// The schema of the output (a single column "count")
    pub output_schema: DFSchemaRef,
```

**Comment by bert-beyondloops** [comment]
unused import removed.

**Comment by alamb** [comment]
Thanks again @bert-beyondloops
