### PR TITLE
Remove physical sort parameters on aggregate window functions

### LINKED ISSUE #11981: order_by not respected for window functions using udaf
### Describe the bug

When using an aggregate function as a window function, the `order_by` is not respected. I've tried a few permutations of setting this value on the `WindowFunction` and setting it via the expression function builder.

### To Reproduce

Note: In the below snippet I tried with and without calling `.order_by()` and with and without setting `order_by` in the `WindowFunction` struct.

When trying to set it on the expression function builder you get an error
`Error: ArrowError(InvalidArgumentError("Sort requires at least one column"), None)`

```
use arrow::record_batch::RecordBatch;
use arrow::array::Int32Array;
use datafusion::arrow::datatypes::{DataType, Field, Schema};
use datafusion::datasource::MemTable;
use datafusion::error::Result;
use datafusion::functions_aggregate::first_last::last_value_udaf;
use datafusion::prelude::*;
use datafusion_expr::expr::WindowFunction;
use datafusion_expr::{
    WindowFrame, WindowFrameBound, WindowFrameUnits, WindowFunctionDefinition,
};
use datafusion_sql::sqlparser::ast::NullTreatment;
use std::sync::Arc;
use datafusion::common::ScalarValue;

#[tokio::main]
async fn main() -> Result<()> {
    let schema = Schema::new(vec![
        Field::new("a", DataType::Int32, true),
        Field::new("b", DataType::Int32, true),
    ]);

    let batch = RecordBatch::try_new(
        Arc::new(schema.clone()),
        vec![
            Arc::new(Int32Array::from(vec![1, 5, 3, 2, 4])),
            Arc::new(Int32Array::from(vec![
                Some(1),
                None,
                Some(3),
                None,
                Some(4),
            ])),
        ],
    )?;

    let ctx = SessionContext::new();

    let provider = MemTable::try_new(Arc::new(schema), vec![vec![batch]])?;
    ctx.register_table("t", Arc::new(provider))?;

    let df = ctx.table("t").await?;

    df.clone().show().await?;

    let w = WindowFunction::new(
        WindowFunctionDefinition::AggregateUDF(last_value_udaf()),
        vec![col("b")],
    );

    let func = Expr::WindowFunction(w)
        .null_treatment(NullTreatment::IgnoreNulls)
        .order_by(vec![col("a").sort(true, true)])
        .window_frame(WindowFrame::new_bounds(
            WindowFrameUnits::Rows,
            WindowFrameBound::Preceding(ScalarValue::UInt32(None)),
            WindowFrameBound::CurrentRow,
        ))
        .build()?
        .alias("last_val");

    df.select(vec![col("a"), col("b"), func])?.show().await?;

    Ok(())
}

    // Expectation
    // +---+---+----------+
    // | a | b | last_val |
    // +---+---+----------+
    // | 1 | 1 | 1        |
    // | 2 |   | 1        |
    // | 3 | 3 | 3        |
    // | 4 | 4 | 4        |
    // | 5 |   | 4        |
    // +---+---+----------+

    // Actual
    // +---+---+----------+
    // | a | b | last_val |
    // +---+---+----------+
    // | 1 | 1 | 1        |
    // | 5 |   | 1        |
    // | 3 | 3 | 3        |
    // | 2 |   | 3        |
    // | 4 | 4 | 4        |
    // +---+---+----------+
```

### Expected behavior

In the above example, we should be able to set a sort order to get the `last_value` as a window function.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by timsaucer**
## Which issue does this PR close?

Closes #11981 

## Rationale for this change

When performing a window function using a UDAF, which all of our aggregate functions are, causes an error in the physical plan. Specifically it generates a `SchemaError::FieldNotFound`. This *appears* to be because the `DFSchema` is empty in the minimal example showing in the bug report. However the ordering operation appears to already be handled by the window function call.

## What changes are included in this PR?

Removes the generation of the ordering and sorting, which are essentially duplicates of each other, and only leaves the ordering parameters on the window function definition.

## Are these changes tested?

All unit tests working.
The minimum demonstration of the error in the bug report now works.
Tested against my project where I initially discovered the problem.

## Are there any user-facing changes?

None.

## Additional Context

I must admit I don't fully understand the rationale behind setting the ordering/sort parameters on both the window function definition and also within the aggregate function. So this code change does resolve my immediate issue, but I am not 100% confident it will not have unintended side effects.

### CODE REVIEW

**Comment by timsaucer** [comment]
@jayzhan211 Would you mind taking a look at this one? You recently worked on the impacted code and I could use a second opinion on this.

**Comment by jayzhan211** [comment]
I think it makes sense to have either window or aggregate to bring along ordering information. Although I'm not sure who should take cares of at the end.

File: datafusion/physical-plan/src/windows/mod.rs [hunk 1]
```diff
@@ -112,25 +112,9 @@ pub fn create_window_expr(
...
-                        nulls_first: options.nulls_first,
-                    })
-                })
-                .collect::<Vec<_>>();
-
             let aggregate = AggregateExprBuilder::new(Arc::clone(fun), args.to_vec())
                 .schema(Arc::new(input_schema.clone()))
                 .alias(name)
-                .order_by(order_by.to_vec())
-                .sort_exprs(sort_exprs)
```
Comment (jayzhan211) [inline datafusion/physical-plan/src/windows/mod.rs:133]: `sort_exprs` is removed. I think we could take a look again with the latest main branch

Comment (timsaucer) [reply datafusion/physical-plan/src/windows/mod.rs]: Thank you. I rebased on `main` and ended up getting a different error, but I still think we need a correction. I think I'll write up a unit test as well.

Comment (jayzhan211) [reply datafusion/physical-plan/src/windows/mod.rs]: I guess after we introduce WindowExprBuilder, we could have a nice builder for createing window aggregate function with single `order_by`.

**Review by jayzhan211 — APPROVED** [review]
👍

**Comment by jayzhan211** [comment]
Thanks @timsaucer
