### PR TITLE
Fix COPY TO does not produce an output file for the empty set

### LINKED ISSUE #18073: COPY TO does not produce an output file for the empty set
### Describe the bug

Executing following sql does not effectively create an output file on disk :

`COPY (SELECT 1 AS id WHERE FALSE) TO 'table_no_rows.parquet';`

I would expect it creates a parquet file containing 0 rows including the schema metadata.

The fact you can still query the schema of such a table is still valuable information.

### To Reproduce

`COPY (SELECT 1 AS id WHERE FALSE) TO 'table_no_rows.parquet';`

does not create the file 'table_no_rows.parquet' on disk.

### Expected behavior

I would expect a valid parquet file written on disk containing only the schema metadata without any rows included.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bert-beyondloops**
## Which issue does this PR close?

COPY TO does not produce a single output file for an empty set

- Closes #18073

## Rationale for this change

Executing following sql does not effectively create a single output file on disk :

COPY (SELECT 1 AS id WHERE FALSE) TO 'table_no_rows.parquet';

I would expect it creates a parquet file containing 0 rows including the schema metadata.

The fact you can still query the schema of such a table is still valuable information.

## Are these changes tested?

Additional COPY TO test added in the copy.slt sqllogictests

## Are there any user-facing changes?

A file containing 0 rows will be created now

### CODE REVIEW

File: datafusion/datasource/src/write/demux.rs [hunk 1]
```diff
@@ -171,6 +171,22 @@ async fn row_count_demuxer(
         max_rows_per_file
     };
 
+    // Single-file output requires creating at least one file stream in advance.
+    // If no record batches are present in the input stream (zero-row scenario),
```
Comment (pepijnve) [inline datafusion/datasource/src/write/demux.rs]: I think there might a bit missing from this comment. Sentence doesn't seem complete.

Comment (bert-beyondloops) [reply datafusion/datasource/src/write/demux.rs]: rephrased it. Last sentence was indeed not complete.

**Comment by bert-beyondloops** [comment]
-

**Review by alamb — APPROVED** [review]
Thank you @bert-beyondloops  🙏 

The behavior of writing empty files has come up several times before and I worry we will go back and forth on the implementation if we don't have the expected results written down somewhere

Could you also please add some documentation to the top of this module / the demuxer tasks to make it clearer what behavior is expected?

**Comment by bert-beyondloops** [comment]
@alamb 

I've added documentation clarifying the minimum number of files written for each output scenario.

File: datafusion/datasource/src/write/demux.rs [hunk 2]
```diff
@@ -68,6 +68,11 @@ pub type DemuxedStreamReceiver = UnboundedReceiver<(Path, RecordBatchReceiver)>;
 /// be written with the extension from the path. Otherwise the default extension
 /// will be used and the output will be split into multiple files.
 ///
+/// Output file guarantees:
```
Comment (alamb) [inline datafusion/datasource/src/write/demux.rs:71]: 👍

**Review by alamb — APPROVED** [review]
Thank you @bert-beyondloops
