### PR TITLE
Fix Internal Error for an INNER JOIN query

### LINKED ISSUE #11412: Internal Error for an INNER JOIN query (SQLancer)
### Describe the bug

This query should be valid and can be executed on DuckDB, but produced an Internal Error when building initial physical plan.
Full reproducer:
```
/*DML*/CREATE TABLE t60(v0 BIGINT, v1 BIGINT, v2 BOOLEAN, v3 BOOLEAN);
/*DML*/CREATE TABLE t0(v0 DOUBLE, v1 BIGINT);
/*DML*/CREATE TABLE t1(v0 DOUBLE);
SELECT COUNT(*)
FROM t1
NATURAL JOIN t60
INNER JOIN t0
ON t60.v1 = t0.v0
AND t0.v1 > t60.v1;
```
Error messages
```
> SELECT COUNT(*)
FROM t1
NATURAL JOIN t60
INNER JOIN t0
ON t60.v1 = t0.v0
AND t0.v1 > t60.v1;

Internal error: Invalid join key. Expected column, found Cast(Cast { expr: Column(Column { relation: Some(Bare { table: "t60" }), name: "v0" }), data_type: Float64 }).
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker

> explain verbose SELECT COUNT(*)
FROM t1
NATURAL JOIN t60
INNER JOIN t0
ON t60.v1 = t0.v0
AND t0.v1 > t60.v1;

...

 initial_physical_plan                                      | Internal error: Invalid join key. Expected column, found Cast(Cast { expr: Column(Column { relation: Some(Bare { table: "t60" }), name: "v0" }), data_type: Float64 }). |
|                                                            | This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker                                              |
+------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

Found by SQLancer https://github.com/apache/datafusion/issues/11030

### PR DESCRIPTION
**Pull request by xinlifoobar**
## Which issue does this PR close?

Closes #11412 

## Rationale for this change

This issue has affected the `join using` query with type coercions, for the specific query in this issue.

```sql
/*DML*/CREATE TABLE t60(v0 BIGINT, v1 BIGINT, v2 BOOLEAN, v3 BOOLEAN);
/*DML*/CREATE TABLE t0(v0 DOUBLE, v1 BIGINT);
/*DML*/CREATE TABLE t1(v0 DOUBLE);
SELECT COUNT(*)
FROM t1
NATURAL JOIN t60
INNER JOIN t0
ON t60.v1 = t0.v0
AND t0.v1 > t60.v1;
```

1. The type_coercion transform `Column(c)` to `Cast(Column(c)`
https://github.com/apache/datafusion/blob/5da7ab300215c44ca5dc16771091890de22af99b/datafusion/optimizer/src/analyzer/type_coercion.rs#L180C1-L195C6

2. Then in the `using_columns` the issue pops up.
https://github.com/apache/datafusion/blob/5da7ab300215c44ca5dc16771091890de22af99b/datafusion/expr/src/logical_plan/plan.rs#L497C1-L512C25

This also indicates the `using_columns` should not be called after type_coercion

### CODE REVIEW

File: datafusion/expr/src/logical_plan/plan.rs [hunk 1]
```diff
@@ -518,6 +510,14 @@ impl LogicalPlan {
         Ok(using_columns)
     }
 
+    fn as_col(expr: Expr) -> Result<Column> {
```
Comment (alamb) [inline datafusion/expr/src/logical_plan/plan.rs:513]: I found this name is somewhat confusing given [Expr::try_as_col](https://docs.rs/datafusion/latest/datafusion/logical_expr/enum.Expr.html#method.try_as_col)

 I suggest:
1. Making this a free function (not in `LogicalPlan`)
2. Add a comment explaining what it does
3. Avoid the copy if possible

For example
```rust

/// Returns the underlying column if `expr` is `Expr::Column` or a cast of an `Expr::Column`
///
/// Returns an error if expr is not a column or a cast of a column
fn get_as_join_column(expr: &Expr) -> Result<&Column> {
...
}
```

**Review by alamb — APPROVED** [review]
Thank you @xinlifoobar  -- this looks good to me. I left a comment about how to improve the code, but I also think we could do that as a follow on

File: datafusion/expr/src/logical_plan/plan.rs (hunk 1 above)
Comment (xinlifoobar) [reply datafusion/expr/src/logical_plan/plan.rs]: Done

**Review by alamb — APPROVED** [review]
