### PR TITLE
fix: `array_remove`/`array_remove_n`/`array_remove_all` not using the same nullability as the input

### LINKED ISSUE #19260: `array_remove`/`array_remove_n`/`array_remove_all` change input list nullability
### Describe the bug

all those mentioned UDFs return in the data_type the input data type, while reutnin  

`array_remove`:
https://github.com/apache/datafusion/blob/2a08013af3ccf703bee202c959b40bb0d35bdea1/datafusion/functions-nested/src/remove.rs#L102-L104

`array_remove_n`:
https://github.com/apache/datafusion/blob/2a08013af3ccf703bee202c959b40bb0d35bdea1/datafusion/functions-nested/src/remove.rs#L190-L192

`array_remove_all`:
https://github.com/apache/datafusion/blob/2a08013af3ccf703bee202c959b40bb0d35bdea1/datafusion/functions-nested/src/remove.rs#L267-L269

while all using the same underlying function `general_remove` which always set the items to be nullable:
https://github.com/apache/datafusion/blob/2a08013af3ccf703bee202c959b40bb0d35bdea1/datafusion/functions-nested/src/remove.rs#L413

### To Reproduce

_No response_

### Expected behavior

it should not change input nullability and should return nullable if the input list is nullable

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rluvaton**
## Which issue does this PR close?

- Closes #19260

## Rationale for this change

removing items from list should not affect the nullability of the list

## What changes are included in this PR?

reused the same input field in the output field

## Are these changes tested?

yes, some of the tests fails on main and pass with this fix (as I added tests for nullable input for completness)

## Are there any user-facing changes?
nullability change

### CODE REVIEW

File: datafusion/functions-nested/src/remove.rs [hunk 1]
```diff
@@ -403,16 +433,442 @@ fn general_remove<OffsetSize: OffsetSizeTrait>(
...
+            ColumnarValue::Array(array) => {
+                let result_list = array.as_list::<i32>();
+                assert_eq!(result_list, &expected_list);
+            }
+            _ => panic!("Expected ColumnarValue::Array"),
+        }
+    }
+
+    #[test]
+    fn test_array_remove_all_non_nullable() {
```
Comment (rluvaton) [inline datafusion/functions-nested/src/remove.rs:773]: Fails on main

File: datafusion/functions-nested/src/remove.rs [hunk 2]
```diff
@@ -403,16 +433,442 @@ fn general_remove<OffsetSize: OffsetSizeTrait>(
...
+            ColumnarValue::Array(array) => {
+                let result_list = array.as_list::<i32>();
+                assert_eq!(result_list, &expected_list);
+            }
+            _ => panic!("Expected ColumnarValue::Array"),
+        }
+    }
+
+    #[test]
+    fn test_array_remove_n_non_nullable() {
```
Comment (rluvaton) [inline datafusion/functions-nested/src/remove.rs:665]: Fails on main

File: datafusion/functions-nested/src/remove.rs [hunk 3]
```diff
@@ -403,16 +433,442 @@ fn general_remove<OffsetSize: OffsetSizeTrait>(
...
+            assert_eq!(nulls, None);
+        }
+
+        let field = Arc::new(field.deref().clone().with_nullable(field_nullable));
+
+        GenericListArray::new(field, offsets, values, nulls)
+    }
+
+    #[test]
+    fn test_array_remove_non_nullable() {
```
Comment (rluvaton) [inline datafusion/functions-nested/src/remove.rs:562]: Fails on main

File: datafusion/functions-nested/src/remove.rs [hunk 4]
```diff
@@ -403,16 +433,442 @@ fn general_remove<OffsetSize: OffsetSizeTrait>(
...
+                    })
+                    .unwrap();
+
+                assert_eq!(result, input_field);
+            }
+        }
+    }
+
+    #[test]
+    fn test_array_remove_all_nullability() {
```
Comment (rluvaton) [inline datafusion/functions-nested/src/remove.rs:523]: Fails on main

File: datafusion/functions-nested/src/remove.rs [hunk 5]
```diff
@@ -403,16 +433,442 @@ fn general_remove<OffsetSize: OffsetSizeTrait>(
...
+                    })
+                    .unwrap();
+
+                assert_eq!(result, input_field);
+            }
+        }
+    }
+
+    #[test]
+    fn test_array_remove_n_nullability() {
```
Comment (rluvaton) [inline datafusion/functions-nested/src/remove.rs:491]: Fails on main

File: datafusion/functions-nested/src/remove.rs [hunk 6]
```diff
@@ -403,16 +433,442 @@ fn general_remove<OffsetSize: OffsetSizeTrait>(
...
+    };
+    use arrow::datatypes::{DataType, Field, Int32Type};
+    use datafusion_common::ScalarValue;
+    use datafusion_expr::{ReturnFieldArgs, ScalarFunctionArgs, ScalarUDFImpl};
+    use datafusion_expr_common::columnar_value::ColumnarValue;
+    use std::ops::Deref;
+    use std::sync::Arc;
+
+    #[test]
+    fn test_array_remove_nullability() {
```
Comment (rluvaton) [inline datafusion/functions-nested/src/remove.rs:464]: Fails on main
