### PR TITLE
Fix empty aggregation function count() in Substrait

### LINKED ISSUE #15344: Empty aggregation functions coming from substrait
### Describe the bug

Providing empty aggregation functions in a Substrait plan results in an invalid logical plan that fails in the physical transformation step with the following error:
```
Error: Internal("args should not be empty")
```

Coming from this line:

https://github.com/apache/datafusion/blob/11838be5efa8607f762504c198615c54575b0593/datafusion/physical-expr/src/aggregate.rs#L113

### To Reproduce

Feed this simple `SELECT count(*) FROM (SELECT 1))` substrait plan:

<details><summary>substrait plan</summary>
```json
{
  "extensionUris": [
    {
      "uri": "https://github.com/substrait-io/substrait/blob/main/extensions/functions_aggregate_generic.yaml"
    }
  ],
  "extensions": [
    {
      "extensionFunction": {
        "functionAnchor": 185,
        "name": "count:any"
      }
    }
  ],
  "relations": [
    {
      "root": {
        "input": {
          "aggregate": {
            "common": {
              "direct": {
              }
            },
            "input": {
              "read": {
                "common": {
                  "direct": {
                  }
                },
                "baseSchema": {
                  "names": [
                    "dummy"
                  ],
                  "struct": {
                    "types": [
                      {
                        "i64": {
                          "nullability": "NULLABILITY_REQUIRED"
                        }
                      }
                    ],
                    "nullability": "NULLABILITY_REQUIRED"
                  }
                },
                "virtualTable": {
                  "values": [
                    {
                      "fields": [
                        {
                          "i64": "0",
                          "nullable": false
                        }
                      ]
                    }
                  ]
                }
              }
            },
            "groupings": [
              {
                "groupingExpressions": [],
                "expressionReferences": []
              }
            ],
            "measures": [
              {
                "measure": {
                  "functionReference": 185,
                  "args": [],
                  "sorts": [],
                  "phase": "AGGREGATION_PHASE_INITIAL_TO_RESULT",
                  "outputType": {
                    "i64": {
                      "nullability": "NULLABILITY_REQUIRED"
                    }
                  },
                  "invocation": "AGGREGATION_INVOCATION_ALL",
                  "arguments": [],
                  "options": []
                }
              }
            ],
            "groupingExpressions": []
          }
        },
        "names": [
          "count(*)"
        ]
      }
    }
  ]
}
```
</details>

Or simply add the following line to the Substrait integration tests [here](https://github.com/apache/datafusion/blob/9278233e9fe34f7712370f2fa583ba94663a0678/datafusion/substrait/tests/cases/consumer_integration.rs#L44) and run them.

```rust
        let ctx = add_plan_schemas_to_ctx(SessionContext::new(), &proto)?;
        let plan = from_substrait_plan(&ctx.state(), &proto).await?;
+       ctx.state().create_physical_plan(&plan).await?;
        Ok(format!("{}", plan))
    }
```

### Expected behavior

The Substrait to DF conversion logic works as before injecting dummy arguments where necessary

### Additional context

I suspect that this regression was introduced in this change https://github.com/apache/datafusion/pull/14824/files#diff-474e53672159d74dae38992a914a74eba81b8350ebe161f11d755f06414ed7b4, but not sure if just adding that back will break something else

### PR DESCRIPTION
**Pull request by gabotechs**
## Which issue does this PR close?

- Closes #15344

## Rationale for this change

Fixing empty `count()` aggregation functions provided through Substrait

## What changes are included in this PR?

Adding back this check https://github.com/apache/datafusion/pull/14824/files#diff-474e53672159d74dae38992a914a74eba81b8350ebe161f11d755f06414ed7b4 and testing it

## Are these changes tested?

yes, by a new test and by extending previously existing tests

## Are there any user-facing changes?

yes, users will be able to feed empty `count()` functions through the Substrait interface

### CODE REVIEW

File: datafusion/substrait/src/logical_plan/consumer.rs [hunk 1]
```diff
@@ -1975,6 +1975,13 @@ pub async fn from_substrait_agg_func(
 
     let args = from_substrait_func_args(consumer, &f.arguments, input_schema).await?;
 
+    // deal with situation that count(*) got no arguments
```
Comment (geoffreyclaude) [inline datafusion/substrait/src/logical_plan/consumer.rs:1978]: Could you just explain in the comment *why* we need `count()` to have arguments?

**Review by geoffreyclaude — APPROVED** [review]

File: datafusion/substrait/src/logical_plan/consumer.rs (hunk 1 above)
Comment (gabotechs) [reply datafusion/substrait/src/logical_plan/consumer.rs:1978]: pretty much just rolled back whatever was removed in https://github.com/apache/datafusion/pull/14824, I would like some input first from @jayzhan211 about why was this removed and if it might be breaking something else that the tests are not catching

Comment (jayzhan211) [reply datafusion/substrait/src/logical_plan/consumer.rs:1978]: I remove it because I don't why we need to convert `count()` to `count(1)`, is there any reason we need `count(1)` in subtrait?

Comment (jayzhan211) [reply datafusion/substrait/src/logical_plan/consumer.rs:1978]: If there is reason, it would be nice to document the reason besides the conversion

Comment (gabotechs) [reply datafusion/substrait/src/logical_plan/consumer.rs:1978]: The main reason is that DataFusion does not support aggregate functions with no arguments:
https://github.com/apache/datafusion/blob/11838be5efa8607f762504c198615c54575b0593/datafusion/physical-expr/src/aggregate.rs#L100-L114
I imagine that this is the reason why it was there before.

If you do a similar operation and analyze DataFusion's logical plan ([link](https://datafusion-fiddle.vercel.app?q=eyJkZGwiOiItLSBQdXQgeW91ciBzY2hlbWEgZGVmaW5pdGlvbiBhbmQgZGF0YSBpbnNlcnRpb25zIGhlcmUuXG5cbkNSRUFURSBUQUJMRSBlbXBsb3llZXMgKFxuICBpZCBJTlQgUFJJTUFSWSBLRVksXG4gIGZpcnN0X25hbWUgVkFSQ0hBUig1MCksXG4gIGxhc3RfbmFtZSBWQVJDSEFSKDUwKSxcbiAgZW1haWwgVkFSQ0hBUigxMDApLFxuICBwaG9uZSBWQVJDSEFSKDIwKSxcbiAgaGlyZV9kYXRlIERBVEUsXG4gIGpvYl90aXRsZSBWQVJDSEFSKDUwKSxcbiAgZGVwYXJ0bWVudCBWQVJDSEFSKDUwKSxcbiAgc2FsYXJ5IERFQ0lNQUwoMTAsMilcbik7XG5cbklOU0VSVCBJTlRPIGVtcGxveWVlcyAoaWQsIGZpcnN0X25hbWUsIGxhc3RfbmFtZSwgZW1haWwsIHBob25lLCBoaXJlX2RhdGUsIGpvYl90aXRsZSwgZGVwYXJ0bWVudCwgc2FsYXJ5KVxuVkFMVUVTXG4gICgxLCAnSm9obicsICdEb2UnLCAnam9obi5kb2VAY29tcGFueS5jb20nLCAnMTIzLTQ1Ni03ODkwJywgJzIwMjAtMDEtMDEnLCAnTWFuYWdlcicsICdTYWxlcycsIDc1MDAwLjAwKSxcbiAgKDIsICdKYW5lJywgJ1NtaXRoJywgJ2phbmUuc21pdGhAY29tcGFueS5jb20nLCAnOTg3LTY1NC0zMjEwJywgJzIwMTktMDUtMTUnLCAnRW5naW5lZXInLCAnRW5naW5lZXJpbmcnLCA4NTAwMC4wMCksXG4gICgzLCAnTWljaGFlbCcsICdKb2huc29uJywgJ21pY2hhZWwuam9obnNvbkBjb21wYW55LmNvbScsICc0NTYtNzg5LTAxMjMnLCAnMjAyMS0wMy0xMCcsICdBbmFseXN0JywgJ0ZpbmFuY2UnLCA2NTAwMC4wMCksXG4gICg0LCAnRW1pbHknLCAnQnJvd24nLCAnZW1pbHkuYnJvd25AY29tcGFueS5jb20nLCAnMzIxLTY1NC05ODcwJywgJzIwMTgtMTEtMDEnLCAnRGVzaWduZXInLCAnTWFya2V0aW5nJywgNjAwMDAuMDApLFxuICAoNSwgJ0RhdmlkJywgJ1dpbHNvbicsICdkYXZpZC53aWxzb25AY29tcGFueS5jb20nLCAnNzg5LTEyMy00NTYwJywgJzIwMjAtMDgtMjAnLCAnRGV2ZWxvcGVyJywgJ0VuZ2luZWVyaW5nJywgODAwMDAuMDApLFxuICAoNiwgJ1NhcmFoJywgJ1RheWxvcicsICdzYXJhaC50YXlsb3JAY29tcGFueS5jb20nLCAnNjU0LTk4Ny0zMjEwJywgJzIwMTctMDYtMDEnLCAnTWFuYWdlcicsICdIdW1hbiBSZXNvdXJjZXMnLCA5MDAwMC4wMCksXG4gICg3LCAnUm9iZXJ0JywgJ0FuZGVyc29uJywgJ3JvYmVydC5hbmRlcnNvbkBjb21wYW55LmNvbScsICczMjEtNzg5LTY1NDAnLCAnMjAxOS0wOS0wNScsICdTYWxlc3BlcnNvbicsICdTYWxlcycsIDU1MDAwLjAwKSxcbiAgKDgsICdKZW5uaWZlcicsICdUaG9tYXMnLCAnamVubmlmZXIudGhvbWFzQGNvbXBhbnkuY29tJywgJzk4Ny0zMjEtNjU0MCcsICcyMDIwLTAyLTE1JywgJ0FjY291bnRhbnQnLCAnRmluYW5jZScsIDcwMDAwLjAwKSxcbiAgKDksICdXaWxsaWFtJywgJ0phY2tzb24nLCAnd2lsbGlhbS5qYWNrc29uQGNvbXBhbnkuY29tJywgJzY1NC0xMjMtOTg3MCcsICcyMDE4LTA3LTEwJywgJ0VuZ2luZWVyJywgJ0VuZ2luZWVyaW5nJywgOTUwMDAuMDApLFxuICAoMTAsICdFbGl6YWJldGgnLCAnV2hpdGUnLCAnZWxpemFiZXRoLndoaXRlQGNvbXBhbnkuY29tJywgJzEyMy03ODktNDU2MCcsICcyMDIxLTAxLTI1JywgJ0Nvb3JkaW5hdG9yJywgJ01hcmtldGluZycsIDUwMDAwLjAwKSxcbiAgKDExLCAnQ2hyaXN0b3BoZXInLCAnSGFycmlzJywgJ2NocmlzdG9waGVyLmhhcnJpc0Bjb21wYW55LmNvbScsICc3ODktNjU0LTEyMzAnLCAnMjAxOS0xMi0wMScsICdBbmFseXN0JywgJ0ZpbmFuY2UnLCA3MjAwMC4wMCksXG4gICgxMiwgJ0FzaGxleScsICdNYXJ0aW4nLCAnYXNobGV5Lm1hcnRpbkBjb21wYW55LmNvbScsICc0NTYtMzIxLTk4NzAnLCAnMjAyMC0wNi0xOCcsICdEZXNpZ25lcicsICdNYXJrZXRpbmcnLCA1ODAwMC4wMCksXG4gICgxMywgJ01hdHRoZXcnLCAnVGhvbXBzb24nLCAnbWF0dGhldy50aG9tcHNvbkBjb21wYW55LmNvbScsICczMjEtNDU2LTc4OTAnLCAnMjAxNy0wOS0yMCcsICdNYW5hZ2VyJywgJ09wZXJhdGlvbnMnLCA4MjAwMC4wMCksXG4gICgxNCwgJ0FtYW5kYScsICdHYXJjaWEnLCAnYW1hbmRhLmdhcmNpYUBjb21wYW55LmNvbScsICc5ODctMTIzLTY1NDAnLCAnMjAxOC0wNC0wNScsICdEZXZlbG9wZXInLCAnRW5naW5lZXJpbmcnLCA3NzAwMC4wMCksXG4gICgxNSwgJ0RhbmllbCcsICdNYXJ0aW5leicsICdkYW5pZWwubWFydGluZXpAY29tcGFueS5jb20nLCAnNjU0LTc4OS0zMjEwJywgJzIwMjAtMTEtMTAnLCAnU2FsZXNwZXJzb24nLCAnU2FsZXMnLCA2MDAwMC4wMCk7XG4iLCJzZWxlY3QiOiItLSBQdXQgeW91ciBzZWxlY3Qgc3RhdGVtZW50IGhlcmUgYW5kIGhpdCBDdHJsK0VudGVyIHRvIHN1Ym1pdC5cblxuRVhQTEFJTiBTRUxFQ1QgY291bnQoKSBGUk9NIGVtcGxveWVlcztcbiJ9)), a similar `Int64(1)` argument is injected.

Comment (gabotechs) [reply datafusion/substrait/src/logical_plan/consumer.rs:1978]: I'll add a comment explaining that

File: datafusion/substrait/src/logical_plan/consumer.rs [hunk 2]
```diff
@@ -1975,6 +1975,15 @@ pub async fn from_substrait_agg_func(
 
     let args = from_substrait_func_args(consumer, &f.arguments, input_schema).await?;
 
+    // Datafusion does not support aggregate functions with no arguments, so
```
Comment (alamb) [inline datafusion/substrait/src/logical_plan/consumer.rs:1978]: 👍

**Review by alamb — APPROVED** [review]
THank you @gabotechs and @geoffreyclaude

**Comment by jayzhan211** [comment]
Thanks all!
