### PR TITLE
fix: panic in ListingTableFactory when session is not SessionState

### LINKED ISSUE #20113: Potential panic due to unchecked downcast in ListingTableFactory::create
### Describe the bug

location : listing_table_factory.rs, inside ListingTableFactory::create

I might be mistaken, but I noticed that state is downcast to SessionState using downcast_ref::<SessionState>().unwrap(). Since create accepts a &dyn Session, this seems to assume that the concrete type is always SessionState.

If that assumption doesn’t hold (for example with alternative or wrapped Session implementations), this would cause a panic rather than returning an error. I’m not sure if this is an intentional invariant or just a temporary implementation detail (there’s a TODO nearby that suggests it may not be final).

If this is not intentional, I’m happy to open a PR to handle this more defensively and return a proper error instead.

### PR DESCRIPTION
**Pull request by evangelisilva**
## Which issue does this PR close?

- Closes #20113.

## Rationale for this change

This PR fixes a potential panic in `ListingTableFactory::create` when the provided [Session](cci:2://file:///Users/evangelisilva/.gemini/antigravity/scratch/datafusion/datafusion/session/src/session.rs:71:0-140:1) instance is not a `SessionState`.

Previously, the code used `.unwrap()` on `downcast_ref::<SessionState>()`. If a custom [Session](cci:2://file:///Users/evangelisilva/.gemini/antigravity/scratch/datafusion/datafusion/session/src/session.rs:71:0-140:1) implementation was used (which is allowed by the trait), this would cause a crash. This change replaces `.unwrap()` with `ok_or_else`, returning a proper `DataFusionError::Internal` instead.

## What changes are included in this PR?

- Replaced `.unwrap()` with `ok_or_else` in `ListingTableFactory::create` to safely handle session downcasting.
- Added a regression test [test_create_with_invalid_session](cci:1://file:///Users/evangelisilva/.gemini/antigravity/scratch/datafusion/datafusion/core/src/datasource/listing_table_factory.rs:554:4-638:5) in [datafusion/core/src/datasource/listing_table_factory.rs](cci:7://file:///Users/evangelisilva/.gemini/antigravity/scratch/datafusion/datafusion/core/src/datasource/listing_table_factory.rs:0:0-0:0) that uses a [MockSession](cci:2://file:///Users/evangelisilva/.gemini/antigravity/scratch/datafusion/datafusion/core/src/datasource/listing_table_factory.rs:570:8-570:27) to verify the error is returned instead of panicking.

## Are these changes tested?

Yes.
- Added new unit test [test_create_with_invalid_session](cci:1://file:///Users/evangelisilva/.gemini/antigravity/scratch/datafusion/datafusion/core/src/datasource/listing_table_factory.rs:554:4-638:5).
- Ran `cargo test -p datafusion --lib datasource::listing_table_factory::tests::test_create_with_invalid_session` and it passed.

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/core/src/datasource/listing_table_factory.rs [hunk 1]
```diff
@@ -546,4 +548,93 @@ mod tests {
             "Statistics cache should not be pre-warmed when collect_statistics is disabled"
         );
     }
+
+
+
+
+    #[tokio::test]
+    async fn test_create_with_invalid_session() {
```
Comment (alamb) [inline datafusion/core/src/datasource/listing_table_factory.rs:559]: this test is probably overkill, but it isn't a terrible thing to have coverage

**Comment by alamb** [comment]
I ran `cargo fmt` to resolve the CI run and merged up from main

**Comment by alamb** [comment]
The CI seems to have failed due to some earlier github issue. Rerunning

**Comment by alamb** [comment]
Thanks again @evangelisilva
