### PR TITLE
fix: Order by mentioning missing column multiple times

### LINKED ISSUE #13157: Duplicate expression errors due to column being used multiple times in order by
### Describe the bug

Currently we crash if a column not used in the select is mentioned more than once in the order by clause.

### To Reproduce

```
> select column1 foo from VALUES (1) order by column1 % 2, column1;
Error during planning: Projections require unique expression names but the expression "column1" at position 1 and "column1" at position 2 have the same name. Consider aliasing ("AS") one of them.
```

### Expected behavior

Query run without errors.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by eejbyfeldt**
## Which issue does this PR close?

Closes #13157

## Rationale for this change
Previously we crashed on queries where the order by mentioned a missing
columns multiple times.

## What changes are included in this PR?
Only add each missing column once.

## Are these changes tested?
Yes, new sqllogictest.

## Are there any user-facing changes?
Bugfix.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thank you @eejbyfeldt

File: datafusion/expr/src/logical_plan/builder.rs [hunk 1]
```diff
@@ -682,7 +682,7 @@ impl LogicalPlanBuilder {
             let columns = sort.expr.column_refs();
 
             columns.into_iter().for_each(|c| {
-                if !schema.has_column(c) {
+                if !schema.has_column(c) && !missing_cols.contains(c) {
```
Comment (findepi) [inline datafusion/expr/src/logical_plan/builder.rs:685]: can missing cols be a set?

**Review by findepi — APPROVED** [review]

File: datafusion/expr/src/logical_plan/builder.rs (hunk 1 above)
Comment (eejbyfeldt) [reply datafusion/expr/src/logical_plan/builder.rs]: I did not try it out, but most likely yes. The change becomes slightly bigger because we currently pass `missing_cols` as a slice to some helper methods.

I assume you are worried about this code now being quadratic? It was not clear if that was a real case in practice that you would order by a large number of columns and none of them are part of the output. But maybe it better to go for the set as it seems safer choice.

Comment (eejbyfeldt) [reply datafusion/expr/src/logical_plan/builder.rs]: Done in 557489879e2d4387e820b529a64d28cf5d8476c4

**Comment by alamb** [comment]
I restarted the failed CI check (was related to some sort of neetwork issue)

**Comment by alamb** [comment]
Thanks again @eejbyfeldt
