### PR TITLE
Disallow positional struct casting when field names don’t overlap

### LINKED ISSUE #19841: # Eliminate positional fallback in struct casting
## Problem

Currently, DataFusion's struct casting includes a **positional fallback** mechanism that allows casting between structs with completely different field names if the field counts match. This violates DuckDB's semantics and can silently corrupt data.

**Example of problematic behavior:**
```rust
// This currently succeeds but should fail
source: struct<left int, right varchar>
target: struct<alpha int, beta varchar>

// Positional fallback causes:
// left → alpha, right → beta
// Despite zero matching field names!
```

## Current Behavior

The implementation in [`validate_struct_compatibility()`](datafusion/common/src/nested_struct.rs) currently allows casting when:
- No field name overlap exists AND
- Field counts match

The casting correctly fails only when there's no overlap **and** counts differ with the error:
```
Cannot cast struct with X fields to Y fields without name overlap; positional mapping is ambiguous
```

## Proposed Solution

Align with **DuckDB's semantics** by requiring at least one matching field name for any struct cast to succeed:

1. **Require name-based matching** — at least one field name must match between source and target
2. **Remove positional fallback** — even when field counts are equal
3. **Clear error message** when no field names match

## Impact

- **Breaking change** — Any code relying on positional casting with no name overlap will fail
- **Safety improvement** — Prevents silent data corruption from accidental field misalignment
- **Consistency** — Aligns with DuckDB's well-designed struct casting semantics and the principle of "at least one field name must match"

#19674 [discussion](https://github.com/apache/datafusion/pull/19674#issuecomment-3757969719)

### PR DESCRIPTION
**Pull request by kosiew**
## Which issue does this PR close?

* Closes #19841.

## Rationale for this change

Struct-to-struct casting previously fell back to **positional mapping** when there was **no field-name overlap** and the number of fields matched. That behavior is ambiguous and can silently produce incorrect results when source/target schemas have different field naming conventions or ordering.

This PR makes struct casting **strictly name-based**: when there is no overlap in field names between the source and target structs, the cast is rejected with a clear planning error. This prevents accidental, hard-to-detect data corruption and forces callers to provide explicit field names (or align schemas) when casting.

## What changes are included in this PR?

* Removed the positional fallback logic for struct casting in `cast_struct_column`; child fields are now resolved **only by name**.
* Updated `validate_struct_compatibility` to **error out** when there is **no field name overlap**, instead of allowing positional compatibility checks.
* Updated unit tests to reflect the new behavior (no-overlap casts now fail with an appropriate error).
* Updated SQLLogicTest files to construct structs using **explicit field names** (e.g. `{id: 1}` / `{a: 1, b: 'x'}` or `struct(… AS field)`), avoiding reliance on positional behavior.
* Improved error messaging to explicitly mention the lack of field name overlap.

## Are these changes tested?

Yes.

* Updated existing Rust unit tests in `nested_struct.rs` to assert the new failure mode and error message.
* Updated SQLLogicTest coverage (`struct.slt`, `joins.slt`) to use named struct literals so tests continue to validate struct behavior without positional casting.

## Are there any user-facing changes?

Yes — behavioral change / potential breaking change.

* Casting between two `STRUCT`s with **no overlapping field names** now fails (previously it could succeed via positional mapping if field counts matched).
* Users must provide explicit field names (e.g. `{a: 1, b: 'x'}` or `struct(expr AS a, expr AS b)`) or ensure schemas share field names.
* Error messages are more explicit: casts are rejected when there is “no field name overlap”.

## LLM-generated code disclosure

This PR includes LLM-generated code and comments. All LLM-generated content has been manually reviewed and tested.

### CODE REVIEW

**Comment by adriangb** [comment]
I think we'll need an entry in `upgrading.md`

File: datafusion/common/src/nested_struct.rs [hunk 1]
```diff
@@ -323,7 +306,11 @@ fn validate_field_compatibility(
     Ok(())
 }
 
-fn has_one_of_more_common_fields(
+/// Check if two field lists have at least one common field by name.
+///
+/// This is useful for validating struct compatibility when casting between structs,
+/// ensuring that source and target fields have overlapping names.
+pub fn has_one_of_more_common_fields(
```
Comment (adriangb) [inline datafusion/common/src/nested_struct.rs:313]: Does this need to be `pub`?

File: docs/source/library-user-guide/upgrading.md [hunk 2]
```diff
@@ -118,6 +118,78 @@ let context = SimplifyContext::default()
...
+    DataType::Struct(vec![
+        FieldRef::new("new_a", DataType::Int32),
+        FieldRef::new("new_b", DataType::Utf8),
+    ]));
+
+// Don't rely on casting—construct directly
+// Use struct builders or row constructors that preserve your mapping logic
+```
+
+**Why this change:**
```
Comment (adriangb) [inline docs/source/library-user-guide/upgrading.md:241]: I think it's worth mentioning that this matches DuckDBs behavior

File: docs/source/library-user-guide/upgrading.md [hunk 3]
```diff
@@ -118,6 +118,78 @@ let context = SimplifyContext::default()
...
+```sql
+-- This would previously succeed by mapping positionally: x→a, y→b
+SELECT CAST(source_col AS STRUCT<a INT, b INT>) FROM table1;
+```
+
+**After (must align names):**
+
+```sql
+-- Explicitly rename to match source field names
+SELECT CAST(source_col AS STRUCT<x INT, y INT>) FROM table1;
```
Comment (adriangb) [inline docs/source/library-user-guide/upgrading.md]: Is this something other engines support? I would have guessed this fails under the "no name overlap" rule.

File: datafusion/common/src/nested_struct.rs (hunk 1 above)
Comment (kosiew) [reply datafusion/common/src/nested_struct.rs:313]: Yes, this function is re-used at 

datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs#L662

```
                    // Skip const-folding when there is no field name overlap
                    if !has_one_of_more_common_fields(&source_fields, target_fields) {
                        return false;
                    }

```

File: docs/source/library-user-guide/upgrading.md (hunk 3 above)
Comment (kosiew) [reply docs/source/library-user-guide/upgrading.md]: Amended in https://github.com/apache/datafusion/pull/19955/commits/659fc0fe093870057102928f6245243cc192cb35

**Comment by adriangb** [comment]
I plan to merge this tomorrow morning EST if there is no further feedback

**Comment by adriangb** [comment]
Thanks for merging up @alamb !

**Comment by alamb** [comment]
Thanks -- yeah I am just trying to keep the code flowing
