### PR TITLE
Fix decimal log precision for non-power values

### LINKED ISSUE #18524: Decimal128 implementation of log loses precision
### Describe the bug

See: https://github.com/apache/datafusion/pull/18519#discussion_r2499831489

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kumarUjjawal**
## Which issue does this PR close?

- Closes #18524

## Rationale for this change

The decimal log implementation used the integer ilog path whenever the base was an integer, which floors results for non‑power values. That produced incorrect outputs such as log(2, 10^35) returning 116 instead of 116.267...

## What changes are included in this PR?

  - Fix decimal log to use the integer fast path only for exact powers, preserving fractional results for non-power inputs.
  - Update unit tests and decimal sqllogictest expectations to match the corrected behav

## Are these changes tested?

Yes

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by kumarUjjawal** [comment]
@Jefffrey when you do get the time, can you take a look.

**Comment by kumarUjjawal** [comment]
@martin-g if I could borrow your time here.

File: datafusion/functions/src/math/log.rs
Comment (martin-g) [inline datafusion/functions/src/math/log.rs]:
```suggestion
```
remove some debug leftover

File: datafusion/functions/src/math/log.rs [hunk 1]
```diff
@@ -109,80 +109,59 @@ fn is_valid_integer_base(base: f64) -> bool {
...
+/// For integer bases >= 2 with zero scale, return an exact integer log when the
+/// value is a perfect power of the base. Otherwise falls back to f64 computation.
 fn log_decimal32(value: i32, scale: i8, base: f64) -> Result<f64, ArrowError> {
-    if is_valid_integer_base(base)
-        && scale >= 0
-        && let Some(unscaled) = unscale_to_u32(value, scale)
+    if scale == 0
+        && is_valid_integer_base(base)
+        && let Ok(unscaled) = u32::try_from(value)
+        && unscaled > 0
```
Comment (Jefffrey) [inline datafusion/functions/src/math/log.rs:118]: I feel we'll need to reconsider this integer log path now that it's reduced to needing all these requirements:

- 0 scale
- integer base
- can unscale

Just for a more accurate computation 🤔 

cc @theirix

Comment (theirix) [reply datafusion/functions/src/math/log.rs:118]: That's true. I would start with more test cases to express our expectations on int/float semantics, like stated in the PR description.

For unscaling, I believe it could be improved in general, there are some edge cases. One attempt is here https://github.com/apache/datafusion/pull/19874

**Comment by martin-g** [comment]
I am going to merge this PR tomorrow unless someone has objections!
Any improvements could be done in a follow-up!

**Comment by martin-g** [comment]
Thank you, @kumarUjjawal, @Jefffrey and @theirix !
