### PR TITLE
Fix overflow in factorial

### LINKED ISSUE #11074: Overflow bug in FACTORIAL scalar function (found by SQLancer)
### Describe the bug

The following statement should return an error instead of directly crash
```shell
> select FACTORIAL(350943270);
thread 'main' panicked at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/iter/traits/accum.rs:149:1:
attempt to multiply with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Found by very initial implementation of SQLancer https://github.com/apache/datafusion/issues/11030

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LorrensP-2158466**
## Which issue does this PR close?

Closes #11074 .

## What changes are included in this PR?
- do checked multiplication
- added SLT test for overflow

## Are these changes tested?
yes

## Are there any user-facing changes?
no

### CODE REVIEW

File: datafusion/functions/src/math/factorial.rs [hunk 1]
```diff
@@ -67,28 +70,27 @@ impl ScalarUDFImpl for FactorialFunc {
...
-            Int64Array,
-            { |value: i64| { (1..=value).product() } }
-        )) as ArrayRef),
+        DataType::Int64 => {
+            let arg = downcast_arg!((&args[0]), "value", Int64Array);
+            Ok(arg
+                .iter()
+                .map(|a| match a {
+                    Some(a) => (2..=a)
+                        .try_fold(1i64, i64::checked_mul)
```
Comment (alamb) [inline datafusion/functions/src/math/factorial.rs:82]: 👌  Very nice

**Review by alamb — APPROVED** [review]
Thanks @LorrensP-2158466
