### PR TITLE
fix: `ComposedPhysicalExtensionCodec` does not use the same codec as encoding when decoding

### LINKED ISSUE #16980: `ComposedPhysicalExtensionCodec` is unsound
### Describe the bug

Current implementation of  `ComposedPhysicalExtensionCodec` is unsound. Approach relying on `try_any` may produce a wrong type by accident if types are simple enough. 

This is not just theoretical issue, it happened in [ballista codec], where encoded parquet file was decoded as csv  instead of parquet. Type was encoded by the last encoded in the list but decoded by first encoder just by pure luck. ( I guess i don't have to mention how hard this was to debug)

In order to make current implementation sound we would need to capture which encoder in the list has been used and do a reverse lookup when we do decoding. We need to encode tuple (position, serialised_blob). 

[ballista codec]: https://github.com/milenkovicm/arrow-ballista/blob/d1295f7d1ab5c40a433ab17a344494f39b18f0af/ballista/core/src/serde/mod.rs#L214-L248

### To Reproduce

I dont have a reproducer at the moment, i believe it could be done very simple 

### Expected behavior

It is expected that types can't be decoded by accident 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Thearas**
## Which issue does this PR close?

Closes #16980 .

## Are these changes tested?

Tested via:

```sh
cargo run --package datafusion-examples --example composed_extension_codec
```

## Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by alamb** [comment]
FYI @milenkovicm perhaps you have a moment to review this PR?

**Comment by alamb** [comment]
Also FYI @lewiszlw  as I think you contributed the original example

File: datafusion-examples/examples/composed_extension_codec.rs [hunk 1]
```diff
@@ -233,6 +234,17 @@ impl PhysicalExtensionCodec for ChildPhysicalExtensionCodec {
...
+/// BlobFormatProto captures data encoded by blob format codecs
+#[derive(Clone, PartialEq, prost::Message)]
+struct BlobFormatProto {
+    /// encoder id used to encode blob
+    /// (to be used for decoding)
+    #[prost(uint32, tag = 1)]
+    pub encoder_position: u32,
+    #[prost(bytes, tag = 2)]
+    pub blob: Vec<u8>,
+}
```
Comment (milenkovicm) [inline datafusion-examples/examples/composed_extension_codec.rs]: can we find a bit better name for this structure. Would it make sense to change doc string to something like: Structure captures information about encoder used and actual encoded data

File: datafusion-examples/examples/composed_extension_codec.rs [hunk 2]
```diff
@@ -241,14 +253,50 @@ struct ComposedPhysicalExtensionCodec {
 }
 
 impl ComposedPhysicalExtensionCodec {
-    fn try_any<T>(
+    pub fn new(codecs: Vec<Arc<dyn PhysicalExtensionCodec>>) -> Self {
+        Self { codecs }
+    }
+
+    fn decode_protobuf(
```
Comment (milenkovicm) [inline datafusion-examples/examples/composed_extension_codec.rs]: this function does not really do decoding, it is just trying to find out which decoder should be used. so name is a bit off.
should se do decoding as well in this function? in the code down we repeat decoder lookup - decode multiple times.

File: datafusion-examples/examples/composed_extension_codec.rs [hunk 3]
```diff
@@ -266,26 +314,35 @@ impl PhysicalExtensionCodec for ComposedPhysicalExtensionCodec {
         inputs: &[Arc<dyn ExecutionPlan>],
         registry: &dyn FunctionRegistry,
     ) -> Result<Arc<dyn ExecutionPlan>> {
-        self.try_any(|codec| codec.try_decode(buf, inputs, registry))
+        let (codec, blob) = self.decode_protobuf(buf)?;
```
Comment (milenkovicm) [inline datafusion-examples/examples/composed_extension_codec.rs]: we have repeated code in multiple functions should we consider merging those two functions?

**Review by milenkovicm — COMMENTED** [review]
I think PR make sense, i would sugget to change naming in few places and remove duplicated code.

**Review by milenkovicm — COMMENTED** [review]
I see this pattern very ofthen when working with ballista, not sure if it makes sense to move `ComposedPhysicalExtensionCodec` to datafusion. wdyt @alamb?

File: datafusion-examples/examples/composed_extension_codec.rs (hunk 1 above)
Comment (Thearas) [reply datafusion-examples/examples/composed_extension_codec.rs]: OK, naming is hard. What name would you suggest?
Maybe `DataWithEncoderPositionProto`😂

File: datafusion-examples/examples/composed_extension_codec.rs (hunk 2 above)
Comment (Thearas) [reply datafusion-examples/examples/composed_extension_codec.rs]: make sense

File: datafusion-examples/examples/composed_extension_codec.rs (hunk 1 above)
Comment (milenkovicm) [reply datafusion-examples/examples/composed_extension_codec.rs]: DataEncoderTuple maybe or something like that

**Review by milenkovicm — APPROVED** [review]
Thanks @Thearas

File: datafusion/proto/src/physical_plan/mod.rs [hunk 4]
```diff
@@ -2941,12 +2941,126 @@ impl PhysicalExtensionCodec for DefaultPhysicalExtensionCodec {
...
+        decode(codec.as_ref(), &proto.blob)
+    }
+
+    fn encode_protobuf(
+        &self,
+        buf: &mut Vec<u8>,
+        mut encode: impl FnMut(&dyn PhysicalExtensionCodec, &mut Vec<u8>) -> Result<()>,
+    ) -> Result<()> {
+        let mut data = vec![];
+        let mut last_err = None;
```
Comment (lewiszlw) [inline datafusion/proto/src/physical_plan/mod.rs:2994]: I've changed this design in my project as this might lose real error message. I tend to collect all possible error messages, and tell user error might be one of them.

Comment (Thearas) [reply datafusion/proto/src/physical_plan/mod.rs:2994]: Good idea.
Maybe collect something in error like `encoder name -> error message`.

Comment (alamb) [reply datafusion/proto/src/physical_plan/mod.rs:2994]: Maybe we can add that as a follow on PR to the example

**Comment by alamb** [comment]
Thanks again everyone
