### PR TITLE
fix: partition pruning stats pruning when multiple values are present

### LINKED ISSUE #18922: Incorrectly result from PartitionPruningStatistics when multiple values are present
### Describe the bug

I have a hive partitioned TPC-DS dataset and I'm using a custom table provider where I'm doing some pre-scan partition pruning using `PartitionPruningStatistics`

A query with a single value in the filter expr works

```
select ss_list_price   
    from store_sales  
    where ss_sold_date_sk = 2451529 limit 10;
```

But when there are multiple values in the filter expr it fails

```
select ss_list_price 
    from store_sales  
    where ss_sold_date_sk in (2451529, 2452570, 2452596) limit 10;
```

This part of the code seems to be the problem

https://github.com/apache/datafusion/blob/d24eb4a23156b7814836e765d5890186ab40682f/datafusion/common/src/pruning.rs#L240-L250

I think `arrow::compute::kernels::boolean::or` should be used here instead of the `arrow::compute::kernels::boolean::and`

This query works from the `datafusion-cli` as I suspect that the file statistics prevents the accidental pruning

```
CREATE EXTERNAL TABLE store_sales
STORED AS PARQUET
LOCATION '/path/to/tpcds_1_delta/store_sales/';

select ss_list_price 
    from store_sales  
    where ss_sold_date_sk in (2451529, 2452570, 2452596) limit 10;
```

### To Reproduce

The following unit test will fail in `pruning.rs`

```
#[test]
fn test_partition_pruning_statistics_multiple_values() {
    let partition_values = vec![
        vec![ScalarValue::from(1i32), ScalarValue::from(2i32)],
        vec![ScalarValue::from(3i32), ScalarValue::from(4i32)],
    ];
    let partition_fields = vec![
        Arc::new(Field::new("a", DataType::Int32, false)),
        Arc::new(Field::new("b", DataType::Int32, false)),
    ];
    let partition_stats =
        PartitionPruningStatistics::try_new(partition_values, partition_fields)
            .unwrap();

    let column_a = Column::new_unqualified("a");
    let column_b = Column::new_unqualified("b");

    // Corresponds to
    // select * from table where a in (1, 3);

    let values = HashSet::from([ScalarValue::from(1i32), ScalarValue::from(3i32)]);
    let contained_a = partition_stats.contained(&column_a, &values).unwrap();
    let expected_contained_a = BooleanArray::from(vec![true, true]);
    assert_eq!(contained_a, expected_contained_a);
}
```

### Expected behavior

The unit test mentioned above should pass

### Additional context

I can raise a PR for this, let me know if my analysis was correct and if there is any background context behind why the condition is an `AND` in the `contained` function

### PR DESCRIPTION
**Pull request by Mark1626**
- Closes #18922

### CODE REVIEW

File: datafusion/common/src/pruning.rs [hunk 1]
```diff
@@ -560,6 +560,28 @@ mod tests {
...
+        ];
+        let partition_stats =
+            PartitionPruningStatistics::try_new(partition_values, partition_fields)
+                .unwrap();
+
+        let column_a = Column::new_unqualified("a");
+
+        let values = HashSet::from([ScalarValue::from(1i32), ScalarValue::from(3i32)]);
+        let contained_a = partition_stats.contained(&column_a, &values).unwrap();
+        let expected_contained_a = BooleanArray::from(vec![true, true]);
```
Comment (dqkqd) [inline datafusion/common/src/pruning.rs:581]: The stats:

| a | b |
| - | - |
| 1 | 2 |
| 3 | 4 |

Running `contained` on `a` with `values = [1, 3]` returns `[true, true]`.

I wonder if we need some cases that return `false`, or `None` as well.

**Review by dqkqd — APPROVED** [review]
Thank you @Mark1626. This change makes sense to me.

File: datafusion/common/src/pruning.rs (hunk 1 above)
Comment (Mark1626) [reply datafusion/common/src/pruning.rs:581]: The earlier case covers `false`. I've added a test cases for the `null` scenario, changed the `or` to a `or_kleene` so it works for `null`

File: datafusion/common/src/pruning.rs [hunk 2]
```diff
@@ -560,6 +560,79 @@ mod tests {
...
+            Arc::new(Field::new("a", DataType::Int32, false)),
+            Arc::new(Field::new("b", DataType::Int32, false)),
+        ];
+        let partition_stats =
+            PartitionPruningStatistics::try_new(partition_values, partition_fields)
+                .unwrap();
+
+        let column_a = Column::new_unqualified("a");
+
+        let values = HashSet::from([ScalarValue::from(1i32), ScalarValue::from(3i32)]);
```
Comment (alamb) [inline datafusion/common/src/pruning.rs:579]: This doesn't seem right to me 🤔 

According to 
https://docs.rs/datafusion/latest/datafusion/common/pruning/trait.PruningStatistics.html#tymethod.contained

> The returned array has one row for each container, with the following meanings:
> 
> * true if the values in column ONLY contain values from values
> * false if the values in column are NOT ANY of values
> * null if the neither of the above holds or is unknown.


This test I think has `a` with values `1` and `2`. So the result of `contains` for values `(1,3)` should be `NULL` as `3` is not in values...

Maybe I am missing something here

Comment (alamb) [reply datafusion/common/src/pruning.rs:579]: Given no other tests fail, we clearly have some sort of test coverage gap

Comment (alamb) [reply datafusion/common/src/pruning.rs:579]: I see now that @dqkqd had the same question here: https://github.com/apache/datafusion/issues/18922#issuecomment-3577546042

Comment (Mark1626) [reply datafusion/common/src/pruning.rs:579]: Given the partition columns are `(a, b)`, the value of `partition_values` in the test represent two partitions `(a=1, b=2)` and `(a=3, b=4)`. 

The `contained` is done on an array of column `a` values `[1, 3]`, and not a single tuple `(a=1, b=2)`. Which is why the result is `[true, true]` in this case

Comment (alamb) [reply datafusion/common/src/pruning.rs:579]: I see -- I thought the stats represented this (which is wrong).

| a | b |
| - | - |
| 1 | 3 |
| 2 | 4 |

I'll try and make a follow on PR with some more comments to try and make this clearer

**Comment by alamb** [comment]
Thanks @Mark1626  @adriangb @dqkqd and @xudong963

**Comment by alamb** [comment]
Here is one small PR
- https://github.com/apache/datafusion/pull/19020

**Comment by alamb** [comment]
I also made a PR with an additional test: 
- https://github.com/apache/datafusion/pull/19021
