### PR TITLE
fix: apply the left side schema on the right side in set expressions

### LINKED ISSUE #20818: Unexpected set expression query planning error
### Describe the bug

When a query involving set expressions (UNION, EXCEPT, INTERSECT):

1.  provides field names in the first SELECT
2. but some other SELECTs don't, and
3. these also contain more than one literal of the same value

then the projection validation logic (`validate_unique_names`) will error out.

### To Reproduce

```sql
> SELECT 1 c1, 0 c2, 0 c3 UNION ALL SELECT 2, 0, 0;
Error during planning: Projections require unique expression names but the expression "Int64(0)" at position 1 and "Int64(0)" at position 2 have the same name. Consider aliasing ("AS") one of them.
```

This is all the more frustrating since the field names for the all other SELECTs but the first are actually discarded in the final output, so they're effectively a throw-away input to abide by the projection validation logic
```sql
> SELECT 1 c1, 0 c2, 0 c3 UNION ALL SELECT 2 as a, 0 as b, 0 as c;
+----+----+----+
| c1 | c2 | c3 |
+----+----+----+
| 2  | 0  | 0  |
| 1  | 0  | 0  |
+----+----+----+
2 row(s) fetched.
```

### Expected behavior

```sql
>  SELECT 1 c1, 0 c2, 0 c3 UNION ALL SELECT 2, 0, 0;
+----+----+----+
| c1 | c2 | c3 |
+----+----+----+
| 2  | 0  | 0  |
| 1  | 0  | 0  |
+----+----+----+
2 row(s) fetched. 
```

### Additional context

This works as expected in Postgres
```sql
postgres@localhost:postgres> SELECT 1 c1, 0 c2, 0 c3 UNION ALL SELECT 2, 0, 0;
+----+----+----+
| c1 | c2 | c3 |
|----+----+----|
| 1  | 0  | 0  |
| 2  | 0  | 0  |
+----+----+----+
SELECT 2
```
and DuckDB
```sql
D SELECT 1 c1, 0 c2, 0 c3 UNION ALL SELECT 2, 0, 0;
┌───────┬───────┬───────┐
│  c1   │  c2   │  c3   │
│ int32 │ int32 │ int32 │
├───────┼───────┼───────┤
│     1 │     0 │     0 │
│     2 │     0 │     0 │
└───────┴───────┴───────┘
```

### PR DESCRIPTION
**Pull request by gruuya**
## Which issue does this PR close?

- Closes #20818.
- Alternative to #20819.

## Rationale for this change

DataFusion requires all projected expressions to have unique names during planning, so it doesn't support select 0, 0 for instance.

However this shouldn't be an issue when this is just a sub-SELECT in a larger query which does abide by this rule. For example a set expression (UNION, EXCEPT, INTERSECT) query should only require the first SELECT to provide a unique schema, and that should be sufficient.

Furthermore, this requirement is even more redundant, since all field name/aliases other than those in the first SELECT are discarded anyway.

## What changes are included in this PR?

- when we're processing a set expression (UNION, EXCEPT, INTERSECT), save the left side schema to planner context
- when we're inside `SqlToRel::select_to_plan` pop the schema and pass it down to
- a new `project_with_validation_and_schema` function in `LogicalPlanBuilder` to properly alias them

The benefit of this approach compared to #20819 is that wildcards are unwrapped and we can properly handle them as well.

The downside is that we need to thread the left schema via the planner context now. 

## Are these changes tested?

Yes, there are unit tests and SLTs.

## Are there any user-facing changes?

New method in `LogicalPlanBuilder` called `project_with_validation_and_schema` which will alias the projection with the provided schema.

### CODE REVIEW

File: datafusion/expr/src/logical_plan/builder.rs [hunk 1]
```diff
@@ -1984,6 +2001,17 @@ fn project_with_validation(
             }
         }
     }
+
+    // When inside a set expression, alias non-Column/non-Alias expressions
+    // to match the left side's field names, avoiding duplicate name errors.
+    if let Some(schema) = &schema {
+        for (expr, field) in projected_expr.iter_mut().zip(schema.fields()) {
+            if !matches!(expr, Expr::Column(_) | Expr::Alias(_)) {
+                *expr = expr.clone().alias(field.name());
```
Comment (jonahgao) [inline datafusion/expr/src/logical_plan/builder.rs]: Cloning an expression is typically expensive. How about 
```rust
projected_expr = projected_expr
            .into_iter()
            .zip(schema.fields().iter())
            .map(|(expr, field)| {
                if !matches!(expr, Expr::Column(_) | Expr::Alias(_)) {
                    expr.alias(field.name())
                } else {
                    expr
                }
            })
            .collect();
```

Comment (gruuya) [reply datafusion/expr/src/logical_plan/builder.rs]: Fair point, I replaced the clone with take, so we just replace the expr in-place
```diff
diff --git a/datafusion/expr/src/logical_plan/builder.rs b/datafusion/expr/src/logical_plan/builder.rs
index 1d257c775..188daa724 100644
--- a/datafusion/expr/src/logical_plan/builder.rs
+++ b/datafusion/expr/src/logical_plan/builder.rs
@@ -2017,7 +2017,7 @@ fn project_with_validation(
     if let Some(schema) = &schema {
         for (expr, field) in projected_expr.iter_mut().zip(schema.fields()) {
             if !matches!(expr, Expr::Column(_) | Expr::Alias(_)) {
-                *expr = expr.clone().alias(field.name());
+                *expr = std::mem::take(expr).alias(field.name());
             }
         }
     }
```
