### PR TITLE
fix: SanityCheckPlan error with window functions and NVL filter

### LINKED ISSUE #20194: SanityCheckPlan caused by Error during planning:
### Describe the bug

Hello, below is a simple query which is executing fine on 50.3.0 and started failing on 52.1.0. 

### To Reproduce

CREATE TABLE table_1 (
	value_1_1 decimal(25) NULL,
	value_1_2 int4 NULL,
	value_1_3 bigint NULL
);
CREATE TABLE table_2 (
	value_2_1 bigint NULL,
	value_2_2 varchar(140) NULL,
	value_2_3 varchar(140) NULL
);
INSERT INTO table_1 (value_1_1,value_1_2,value_1_3) VALUES	 (6774502793, 10040029, 1120);
INSERT INTO table_2 (value_2_1, value_2_2, value_2_3) VALUES(1120,'0','0');
 SELECT
      t1.value_1_1, t1.value_1_2
    , ROW_NUMBER()
    OVER
    (
        PARTITION BY t1.value_1_1, t1.value_1_2 ORDER BY 
	        case when t2.value_2_2='0' then 1 else 0 end ASC,
	        case when t2.value_2_3='0' then 1 else 0 end ASC
    ) ord
 FROM table_1 t1
 INNER JOIN table_2 t2
   ON  1=1
   AND t1.value_1_3=t2.value_2_1
   AND (nvl(t2.value_2_3,'0')='0');

### Expected behavior

Query finishing without error.

### Additional context

Error message is:
SanityCheckPlan
caused by
Error during planning: Plan: [BoundedWindowAggExec: wdw=[row_number() PARTITION BY [t1.value_1_1, t1.value_1_2] ORDER BY [CASE WHEN t2.value_2_2 = Utf8(\0\) THEN Int64(1) ELSE Int64(0) END ASC NULLS LAST, CASE WHEN t2.value_2_3 = Utf8(\0\) THEN Int64(1) ELSE Int64(0) END ASC NULLS LAST] RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW: Field { \row_number() PARTITION BY [t1.value_1_1, t1.value_1_2] ORDER BY [CASE WHEN t2.value_2_2 = Utf8(\\\0\\\) THEN Int64(1) ELSE Int64(0) END ASC NULLS LAST, CASE WHEN t2.value_2_3 = Utf8(\\\0\\\) THEN Int64(1) ELSE Int64(0) END ASC NULLS LAST] RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\: UInt64 }, frame: RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW], mode=[Sorted],
   SortExec: expr=[value_1_1@0 ASC NULLS LAST, value_1_2@1 ASC NULLS LAST, CASE WHEN value_2_2@2 = CASE WHEN value_2_3@3 IS NOT NULL THEN value_2_3@3 ELSE 0 END THEN 1 ELSE 0 END ASC NULLS LAST, CASE WHEN value_2_3@3 = CASE WHEN value_2_3@3 IS NOT NULL THEN value_2_3@3 ELSE 0 END THEN 1 ELSE 0 END ASC NULLS LAST], preserve_partitioning=[true],
     RepartitionExec: partitioning=Hash([value_1_1@0, value_1_2@1], 16), input_partitions=1,
       ProjectionExec: expr=[value_1_1@2 as value_1_1, value_1_2@3 as value_1_2, value_2_2@0 as value_2_2, value_2_3@1 as value_2_3],
         HashJoinExec: mode=CollectLeft, join_type=Inner, on=[(value_2_1@0, value_1_3@2)], projection=[value_2_2@1, value_2_3@2, value_1_1@3, value_1_2@4],
           FilterExec: CASE WHEN value_2_3@2 IS NOT NULL THEN value_2_3@2 ELSE 0 END = 0,
             DataSourceExec: partitions=1, partition_sizes=[1],
           DataSourceExec: partitions=1, partition_sizes=[1]] does not satisfy order requirements: [value_1_1@0 NA, value_1_2@1 NA, CASE WHEN value_2_2@2 = 0 THEN 1 ELSE 0 END ASC NULLS LAST, CASE WHEN value_2_3@3 = 0 THEN 1 ELSE 0 END ASC NULLS LAST]. Child-0 order: [[value_1_1@0 ASC NULLS LAST, value_1_2@1 ASC NULLS LAST, CASE WHEN value_2_2@2 = CASE WHEN value_2_3@3 IS NOT NULL THEN value_2_3@3 ELSE 0 END THEN 1 ELSE 0 END ASC NULLS LAST, CASE WHEN value_2_3@3 = CASE WHEN value_2_3@3 IS NOT NULL THEN value_2_3@3 ELSE 0 END THEN 1 ELSE 0 END ASC NULLS LAST]]

### PR DESCRIPTION
**Pull request by EeshanBembi**
## Which issue does this PR close?

Closes #20194

## Rationale for this change

A query with `ROW_NUMBER() OVER (... ORDER BY CASE WHEN col='0' THEN 1 ELSE 0 END)` combined with a filter `nvl(t2.value_2_3,'0')='0'` fails with a `SanityCheckPlan` error. This worked in 50.3.0 but broke in 52.1.0.

## What changes are included in this PR?

**Root cause**: `collect_columns_from_predicate_inner` was extracting equality pairs where neither side was a `Column` (e.g. `nvl(col, '0') = '0'`), creating equivalence classes between complex expressions and literals. `normalize_expr`'s deep traversal would then replace the literal `'0'` inside unrelated sort/window CASE WHEN expressions with the complex NVL expression, corrupting the sort ordering and causing a mismatch between `SortExec`'s reported output ordering and `BoundedWindowAggExec`'s expected ordering.

**Fix** (two changes in `filter.rs`):
1. **`collect_columns_from_predicate_inner`**: Only extract equality pairs where at least one side is a `Column` reference. This matches the function's documented intent ("Column-Pairs") and prevents complex-expression-to-literal equivalence classes from being created.
2. **`extend_constants`**: Recognize `Literal` expressions as inherently constant (previously only checked `is_expr_constant` on the input's equivalence properties, which doesn't know about literals). This ensures constant propagation still works for `complex_expr = literal` predicates — e.g. `nvl(col, '0')` is properly marked as constant after the filter.

## How was this tested?

- Unit test `test_collect_columns_skips_non_column_pairs` verifying the filtering logic
- Sqllogictest reproducing the exact query from the issue
- Full test suites: equivalence tests (51 passed), physical-plan tests (1255 passed), physical-optimizer tests (20 passed)
- Manual verification with datafusion-cli running the reproduction query

## Test plan
- [x] Unit test for `collect_columns_from_predicate_inner` column filtering
- [x] Sqllogictest regression test for #20194
- [x] Existing test suites pass
- [x] Manual reproduction query succeeds

### CODE REVIEW

**Comment by kosiew** [comment]
hi @EeshanBembi 
I would love to review this PR after you resolve the merge conflict.

File: datafusion/physical-plan/src/filter.rs [hunk 1]
```diff
@@ -359,18 +359,37 @@ impl FilterExec {
...
+                let left_const =
+                    input_eqs.is_expr_constant(binary.left()).or_else(|| {
+                        binary
+                            .left()
+                            .as_any()
+                            .downcast_ref::<Literal>()
+                            .map(|l| AcrossPartitions::Uniform(Some(l.value().clone())))
+                    });
+                let right_const =
+                    input_eqs.is_expr_constant(binary.right()).or_else(|| {
```
Comment (kosiew) [inline datafusion/physical-plan/src/filter.rs]: Current logic repeats nearly identical `is_expr_constant(...).or_else(literal...)` blocks for left/right operands.

Could we extract an `expr_constant_or_literal(expr, input_eqs)` helper here? It would remove duplication and centralize literal/const semantics used by filter equivalence inference.

File: datafusion/physical-plan/src/filter.rs [hunk 2]
```diff
@@ -979,6 +998,18 @@ fn collect_columns_from_predicate_inner(
...
     predicates.into_iter().for_each(|p| {
         if let Some(binary) = p.as_any().downcast_ref::<BinaryExpr>() {
+            // Only extract pairs where at least one side is a Column reference.
+            // Pairs like `complex_expr = literal` should not create equivalence
+            // classes — the literal could appear in many unrelated expressions
+            // (e.g. sort keys), and normalize_expr's deep traversal would
+            // replace those occurrences with the complex expression, corrupting
+            // sort orderings. Constant propagation for such pairs is handled
+            // separately by `extend_constants`.
+            let has_column = binary.left().as_any().downcast_ref::<Column>().is_some()
```
Comment (kosiew) [inline datafusion/physical-plan/src/filter.rs]: `has_column` currently means "one side is directly a `Column` expression," not "expression contains a column."

Would `has_direct_column_operand` (or similar) be clearer here? It matches the intentional exclusion of complex_expr=literal pairs and avoids misreading this as recursive column detection.

File: datafusion/physical-plan/src/filter.rs [hunk 3]
```diff
@@ -2066,4 +2097,46 @@ mod tests {
...
+
+    /// Regression test for https://github.com/apache/datafusion/issues/20194
+    ///
+    /// `collect_columns_from_predicate_inner` should only extract equality
+    /// pairs where at least one side is a Column. Pairs like
+    /// `complex_expr = literal` must not create equivalence classes because
+    /// `normalize_expr`'s deep traversal would replace the literal inside
+    /// unrelated expressions (e.g. sort keys) with the complex expression.
+    #[tokio::test]
+    async fn test_collect_columns_skips_non_column_pairs() -> Result<()> {
```
Comment (kosiew) [inline datafusion/physical-plan/src/filter.rs]: `test_collect_columns_skips_non_column_pairs` does not use async behavior.

Could this be a plain `#[test]`? Keeping it sync makes scope a bit clearer since no async execution is involved.

**Review by kosiew — APPROVED** [review]
lgtm

**Comment by alamb** [comment]
This is another one we should probably put on `branch-53` (backport to 53)

**Comment by alamb** [comment]
I took the liberty of merging up from main to resolve a conflict

**Comment by alamb** [comment]
> Thanks @EeshanBembi perhaps we can include a test
> 
> ```
> select row_number()
> ...
> where case when ...
> ```

Sorry @comphead  -- I missed this command and I didn't quite follow what you had in mind here
