### PR TITLE
Fix: StatisticsConverter `counts` for missing columns

### LINKED ISSUE #10926: `StatisticsConverter::row_group_null_counts` incorrect for missing column
### Describe the bug

 I noticed this while working on https://github.com/apache/datafusion/pull/10852 with @marvinlanhenke

Basially, when generating statistics for a non existent column, the StatisticsExtractor will return a null array of the type of the column not a UInt64Array

Specifically https://github.com/apache/datafusion/blob/2f4347647172f6997448b2e24d322b50c856f3a0/datafusion/core/src/datasource/physical_plan/parquet/statistics.rs#L871-L886

The same problem exists for  `data_page_null_counts` and `data_page_row_counts` (not for `row_group_row_counts`

### To Reproduce

Try to call row_group_null_counts for a column that isn't in the parquet file

### Expected behavior

1. row_group_null_counts should always return an `UInt64Array` (not an `ArrayRef`)
2. If there is not a column, the UInt64Array should be all nulls

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by marvinlanhenke**
## Which issue does this PR close?

Closes #10926.

## Rationale for this change

- row_group_null_counts, data_page_null_counts
- data_page_row_counts

return an ArrayRef instead of UInt64Array.

## What changes are included in this PR?

- fixed methods to return correct array type
- changed data_page_row_counts to fall back on row_page_row_counts if column is missing
- added a test case in `arrow_statistics`

## Are these changes tested?
Yes.

### CODE REVIEW

**Comment by marvinlanhenke** [comment]
@alamb PTAL.

I'm not sure about the assumptions I made in `data_page_row_counts` [here](https://github.com/apache/datafusion/pull/10946/files#diff-7110f4709c105a18ef74a212396444d62052179a735d148fb62470a8b157fb40R1053-R1057).

File: datafusion/core/src/datasource/physical_plan/parquet/statistics.rs [hunk 1]
```diff
@@ -1041,21 +1043,20 @@ impl<'a> StatisticsConverter<'a> {
...
     {
-        let data_type = self.arrow_field.data_type();
-
         let Some(parquet_index) = self.parquet_index else {
-            return Ok(self.make_null_array(data_type, row_group_indices));
+            // no matching column found in parquet_index;
+            // thus we cannot extract page_locations in order to determine
+            // the row count on a per DataPage basis.
+            // We use `row_group_row_counts` instead.
+            return Self::row_group_row_counts(row_group_metadatas);
```
Comment (alamb) [inline datafusion/core/src/datasource/physical_plan/parquet/statistics.rs:1057]: I see -- this is a tricky situation where there is no column and thus no information on data pages. 

Another potential behavior that might make sense here would be to return an error because unlike other functions in `StatisticsConverter` there is no way to "gracefully" ignore missing information

Or we could possible return an array with zero rows 🤔

File: datafusion/core/tests/parquet/arrow_statistics.rs [hunk 2]
```diff
@@ -1990,3 +2003,38 @@ async fn test_column_not_found() {
     }
     .run_col_not_found();
 }
+
+#[tokio::test]
+async fn test_column_non_existent() {
```
Comment (alamb) [inline datafusion/core/tests/parquet/arrow_statistics.rs:2008]: 💯  for the new tests - thank you @marvinlanhenke

**Review by alamb — APPROVED** [review]
Thank you very much @marvinlanhenke  -- I think this looks great to me

I see the complication related to data_page_row_counts.  I don't have a great answer for that at the moment other than potentially to return an error. 

I believe this PR could be merged in as is and we can update the behavior in a follow on PR (or leave it as is for a while). Let me know what you think

File: datafusion/core/src/datasource/physical_plan/parquet/statistics.rs (hunk 1 above)
Comment (marvinlanhenke) [reply datafusion/core/src/datasource/physical_plan/parquet/statistics.rs:1057]: ...perhaps looking at the behavior of `row_group_row_count` might help.

My main question here is: 
Why do we return row counts for a non existing column in `row_group_row_counts`?

A column that does not exists cannot have valid rows, or a row count in that regard? So returning a null_array would indicate those missing information? Suppose we had just a single column, and for whatever reason, it does not exist in the parquet file (or does not match). With the current implementation we would still return a 'valid' row count in this scenario, accessing a somewhat invalid / useless parquet file? 

I'm not sure one can follow my train of thought here, however I think we should return a null_array in both cases for `row_groups` and `data_pages` as well.

But, I might be missing something. Perhaps you can explain the reasoning why we don't return a null_array in the current `row_group_row_counts` impl @alamb? That would be nice and might help guide our decision here.

**Comment by marvinlanhenke** [comment]
> Thank you very much @marvinlanhenke -- I think this looks great to me
> 
> I see the complication related to data_page_row_counts. I don't have a great answer for that at the moment other than potentially to return an error.
> 
> I believe this PR could be merged in as is and we can update the behavior in a follow on PR (or leave it as is for a while). Let me know what you think

@alamb Thanks for the review. I left one question regarding the current impl of `row_group_row_counts` ... if this question does not help regarding data_pages_row_count, I'm a +1 for returning an error instead.

File: datafusion/core/src/datasource/physical_plan/parquet/statistics.rs (hunk 1 above)
Comment (alamb) [reply datafusion/core/src/datasource/physical_plan/parquet/statistics.rs:1057]: > Why do we return row counts for a non existing column in row_group_row_counts?

I think the (not great) reason is that it is the API needed for PruningStatistics here: https://github.com/apache/datafusion/blob/a923c659cf932f6369f2d5257e5b99128b67091a/datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs#L386-L390

Also, since the `ParquetMetadata` knows how many row groups there are even when there are no row group statistics, it is possible

For data pages, it is different as if the "page index" is not present then I don't think there is any way to know how many data pages there are other than reading the file 

The more we explore this, the more you have convinced me that we shouldn't return row counts for non existent columns in `row_group_row_counts` either

So I guess my new proposal would be to return `Option` like:

```rust
impl<'a> StatisticsConverter<'a> {
...
  /// return OK(None) if the column does not exist
  pub(crate) fn null_counts_page_statistics<'a, I>(iterator: I) -> Result<Option<UInt64Array>> {
  ...
  }

  /// return OK(None) if the column does not exist
    pub fn data_page_row_counts<I>(
        &self,
        column_offset_index: &ParquetOffsetIndex,
        row_group_metadatas: &[RowGroupMetaData],
        row_group_indices: I,
    ) -> Result<Option<UInt64Array>>
    where
        I: IntoIterator<Item = &'a usize>,
    {
    ...
    }

}
```

The rationale to return an Option rather than an error is that creating and ignoring `DataFusionError` via `ok()` still requires a string allocation, which is wasteful

I realize this is done many places already in the statistics extraction code, but I think for those cases it is meant to make the code resilent to incorrectly encoded parquet files rather than something that is "expected" to happen

Comment (marvinlanhenke) [reply datafusion/core/src/datasource/physical_plan/parquet/statistics.rs:1057]: > The more we explore this, the more you have convinced me that we shouldn't return row counts for non existent columns in `row_group_row_counts` either

But I'll guess this is a topic (or PR) for another day?

So for now, we only change `data_page_row_counts` and merge this? I'd be fine with that.

Comment (alamb) [reply datafusion/core/src/datasource/physical_plan/parquet/statistics.rs:1057]: > So for now, we only change data_page_row_counts and merge this? I'd be fine with that.

I think that is a good idea and I will file a ticket to fix `row_group_row_counts` in a follow on

Comment (marvinlanhenke) [reply datafusion/core/src/datasource/physical_plan/parquet/statistics.rs]: I changed it accordingly. Thanks again for your input here

**Review by alamb — APPROVED** [review]
Thanks again @marvinlanhenke 🚀

File: datafusion/core/src/datasource/physical_plan/parquet/statistics.rs (hunk 1 above)
Comment (alamb) [reply datafusion/core/src/datasource/physical_plan/parquet/statistics.rs]: Filed https://github.com/apache/datafusion/issues/10965 to track the changes to row_group_row_counts

**Review by alamb — APPROVED** [review]
Thanks @marvinlanhenke
