### PR TITLE
fix: calculate total seconds from interval fields for `extract(epoch)`

### LINKED ISSUE #19799: `select extract(epoch from ('15 minutes')::interval)` gives wrong result
### Describe the bug

Run `select extract(epoch from ('15 minutes')::interval);` gives `0.0` in `datafusion-cli`, `900.0` in  DuckDB and Postgres.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lemorage**
## Which issue does this PR close?

- Closes #19799.

## Rationale for this change

The epoch function incorrectly used `date_part(array, DatePart::Second)` for intervals which only extracts the seconds component of the interval structure (0 for "15 minutes"), not the total seconds from all components.

## What changes are included in this PR?

  - Modified epoch() function in date_part.rs to properly handle interval types by extracting struct fields and calculating total seconds
  - Added regression tests in date_part.slt

## Are these changes tested?

Yes. Added tests verifying correct conversion for all interval types and precision levels.

## Are there any user-facing changes?

Yes. `extract(epoch from interval)` now returns correct total seconds instead of 0.

### CODE REVIEW

File: datafusion/functions/src/datetime/date_part.rs [hunk 1]
```diff
@@ -349,6 +352,7 @@ fn seconds(array: &dyn Array, unit: TimeUnit) -> Result<ArrayRef> {
 
 fn epoch(array: &dyn Array) -> Result<ArrayRef> {
     const SECONDS_IN_A_DAY: f64 = 86400_f64;
+    const DAYS_PER_MONTH: f64 = 30_f64;
```
Comment (Jefffrey) [inline datafusion/functions/src/datetime/date_part.rs:359]: I suppose there's no easier way to define this for intervals 🤔

Comment (lemorage) [reply datafusion/functions/src/datetime/date_part.rs:359]: Yes! I just followed the PostgreSQL-way for simplicity here, what do u think?

> https://doxygen.postgresql.org/datatype_2timestamp_8h.html#ad35c6d425de4ccc4718c6ce7f4bfbba2

File: datafusion/functions/src/datetime/date_part.rs
Comment (martin-g) [inline datafusion/functions/src/datetime/date_part.rs]: Should this be updated to explain that for intervals it returns the total seconds in the interval ?

**Comment by Jefffrey** [comment]
Good to go 👍

**Comment by adriangb** [comment]
Thanks both!
