### PR TITLE
Fix `schema_adapter` integration tests not running

### LINKED ISSUE #16801: Schema adapter Integration tests are not being run
### Describe the bug

There's something wrong with [datafusion/core/tests/integration_tests/schema_adapter_integration_tests.rs](https://github.com/apache/datafusion/blob/main/datafusion/core/tests/integration_tests/schema_adapter_integration_tests.rs): I don't think it's being run.

Simple examination shows it would not compile:

https://github.com/apache/datafusion/blob/38b87bfa2418797e775ad3748dad5c4325654c9c/datafusion/core/tests/integration_tests/schema_adapter_integration_tests.rs#L57-L86

The methods implemented do not match the trait at all:

https://github.com/apache/datafusion/blob/38b87bfa2418797e775ad3748dad5c4325654c9c/datafusion/datasource/src/schema_adapter.rs#L80-L109

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kosiew**
## Which issue does this PR close?

* Closes #16801.

## Rationale for this change

This PR restructures and refactors the schema adapter integration tests to improve maintainability, clarity, and test isolation. It separates the test logic into a dedicated `schema_adapter` module under the `integration_tests` directory, aligning with other modular test patterns in the codebase.

## What changes are included in this PR?

- Removed `schema_adapter_integration_tests.rs` from the `integration_tests` directory.
- Created a new module `schema_adapter` and moved the tests there.
- Added `mod schema_adapter;` to `core_integration.rs` to include the new module.
- Enhanced the schema adapter test suite to:
  - Write and read test data using `InMemory` object store.
  - Validate consistent behavior of the `UppercaseAdapterFactory` across `ParquetSource`, `ArrowSource`, `CsvSource`, and `JsonSource`.
  - Confirm schema mapping behavior and adapter output schemas.
- Added missing `use` imports and corrected adapter error handling in existing test files.

## Are these changes tested?

✅ Yes, this PR includes comprehensive unit and integration tests for:
- Adapter correctness and schema transformation behavior.
- Reusability of `SchemaAdapterFactory` across file sources.
- Compatibility with object stores and batch collection.

## Are there any user-facing changes?

No, these changes are internal to the testing framework. There are no user-facing changes or breaking API changes introduced in this PR.

### CODE REVIEW

File: datafusion/datasource/src/schema_adapter.rs [hunk 1]
```diff
@@ -68,6 +68,8 @@ pub trait SchemaAdapterFactory: Debug + Send + Sync + 'static {
     ) -> Box<dyn SchemaAdapter> {
         self.create(Arc::clone(&projected_table_schema), projected_table_schema)
     }
+    /// Give us access to Any so callers can downcast.
+    fn as_any(&self) -> &dyn Any;
```
Comment (findepi) [inline datafusion/datasource/src/schema_adapter.rs]: If this is needed just to make the tests run, we should avoid adding this, and find some other way. Existence and structure of our tests should not drive the shape of public API.

Comment (kosiew) [reply datafusion/datasource/src/schema_adapter.rs]: @findepi

Amended.

File: datafusion/core/tests/parquet/schema_adapter.rs [hunk 2]
```diff
@@ -370,3 +378,321 @@ async fn test_custom_schema_adapter_and_custom_expression_adapter() {
...
+
+// ----------------------------------------------------------------------
+// Tests migrated from schema_adaptation/schema_adapter_integration_tests.rs
+// ----------------------------------------------------------------------
+
+/// A schema adapter factory that transforms column names to uppercase
+#[derive(Debug, PartialEq)]
+struct UppercaseAdapterFactory {}
+
+impl SchemaAdapterFactory for UppercaseAdapterFactory {
```
Comment (alamb) [inline datafusion/core/tests/parquet/schema_adapter.rs]: Moving the tests here sort of implies they are only related to parquet -- don't we apply schema adapter to other formats too?

~However, since all the tests use parquet this seems like a good place to put them~

Update: they don't all use parquet

**Review by alamb — DISMISSED** [review]
Thank you @kosiew

File: datafusion/core/tests/parquet/schema_adapter.rs [hunk 3]
```diff
@@ -370,3 +378,321 @@ async fn test_custom_schema_adapter_and_custom_expression_adapter() {
...
+    // Verify the schema has the original column names (schema adapter not applied in DataSourceExec)
+    let result_schema = batches[0].schema();
+    assert_eq!(result_schema.field(0).name(), "id");
+    assert_eq!(result_schema.field(1).name(), "name");
+
+    Ok(())
+}
+
+#[tokio::test]
+async fn test_multi_source_schema_adapter_reuse() -> Result<()> {
```
Comment (alamb) [inline datafusion/core/tests/parquet/schema_adapter.rs]: actually, I missed this one before -- given this is testing formats other than parquet, I think we should move it back into core_integration. 

Here is a suggestion how: https://github.com/apache/datafusion/issues/16801#issuecomment-3120115929

Comment (kosiew) [reply datafusion/core/tests/parquet/schema_adapter.rs]: Moved them to 
datafusion/core/tests/integration_tests/schema_adapter/schema_adapter_integration_tests.rs

File: datafusion/core/tests/schema_adapter_integration.rs [hunk 4]
```diff
@@ -0,0 +1,21 @@
+// Licensed to the Apache Software Foundation (ASF) under one
```
Comment (alamb) [inline datafusion/core/tests/schema_adapter_integration.rs]: I think this effectively means we will have a new integration test binary that gets run like

```shell
cargo test --test schema_adapter_integration
```

each test binary takes up significant space, and in the past we had problems with the runners disk space filling up

IN this case, the new binary takes 188MB on my machine, so it probably would add the same to most CI runs:

```shell
(venv) andrewlamb@Andrews-MacBook-Pro-3:~/Software/datafusion$ du -s -h target/debug/deps/schema_adapter_integration-2b9fa3c8791a7c77
188M	target/debug/deps/schema_adapter_integration-2b9fa3c8791a7c77
```

Here is a proposed PR to add it to the existing core_integration binary, so it would get run like this:

```shell
cargo test --test core_integration -- schema_adapter
```

- https://github.com/kosiew/datafusion/pull/27

And not add a new binary

**Review by alamb — APPROVED** [review]
Thank you @kosiew 

I think this PR does run the test now, so I think it could be merged as is

However, I think it is worth considering using an exisitng test binary rather than making a new one, namely this PR:
- https://github.com/kosiew/datafusion/pull/27

**Comment by kosiew** [comment]
Thanks @alamb , @findepi for your reviews.

**Comment by alamb** [comment]
Thank you for sticking with this @kosiew
