### PR TITLE
Fix config_namespace macro symbol usage

### LINKED ISSUE #14518: The `config_namespace!` macro requires `datafusion::common::Result` to be in scope
### Describe the bug

Just got caught by this. If you don't have `datafusion::common::Result` in scope as `Result` when using `config_namespace!`, rust-analyzer returns diagnostics for `enum takes 2 generic arguments but 1 generic argument was supplied`. I ended up having to `cargo expand` the module and paste it into an editor to figure out what it was complaining about.

I'm pretty sure I just need to fully specify the `Result` type here:

https://github.com/apache/datafusion/blob/304488d348ad2c952ce24f93064a81046155da79/datafusion/common/src/config.rs#L142

As in, just prefix it with `::datafusion::common::` on that line.

### To Reproduce

```rust
use datafusion::common::config::{ConfigField, Visit};
use datafusion::common::config_namespace;
use datafusion::common::error::_config_err;

// This has to be uncommented to fix the compiler error.
// use datafusion::common::Result;

config_namespace! {
    /// Options for controlling TileDB specific optimizations
    pub struct ExampleOptions {
        /// Control whether TileDB will attempt to do predicate pushdown.
        /// Setting this to false will disable all predicate push down analysis
        /// and rely on DataFusion to filter returned data. Generally speaking,
        /// this should only be disabled when testing predicate pushdown
        /// logic.
        pub some_setting: String, default = String::new()
    }
}
```

### Expected behavior

I would expect `config_namespace!` to work whether or not I have a specific identifier in scope.

### Additional context

I'm more than happy to post a PR for this as long as someone Ok's the proposed solution (or can point me at a better approach).

### PR DESCRIPTION
**Pull request by davisp**
The `config_namespace` macro was relying on a few symbols being properly imported before its used. This removes that need by referring to the symbols directly with the `$crate` prefix.

## Which issue does this PR close?

- Closes #14518.

## Rationale for this change

The `config_namespace!` macro relied on symbols being properly imported. This fixes that issue.

## What changes are included in this PR?

1. Fix `config_namespace!` to not require imported symbols being available.
2. Re-add the inadvertently removed `#[macro_export]` attribute.

## Are these changes tested?

Yes. There's an isolated test to show that the macro now works without any `use` statements.

## Are there any user-facing changes?

Some folks might get "unused import" diagnostics/warnings after this change, maybe?

### CODE REVIEW

File: datafusion/common/src/config.rs [hunk 1]
```diff
@@ -2093,3 +2094,22 @@ mod tests {
         assert_eq!(parsed_metadata.get("key_dupe"), Some(&Some("B".into())));
     }
 }
+
+#[cfg(test)]
+mod tests_isolated {
```
Comment (rkrishn7) [inline datafusion/common/src/config.rs:2099]:
```suggestion
mod tests {
```

I think it may be best to stick to [convention](https://doc.rust-lang.org/book/ch11-03-test-organization.html#unit-tests) here.

File: datafusion/common/src/config.rs [hunk 2]
```diff
@@ -2093,3 +2094,22 @@ mod tests {
...
+    // The point of this test is to check that the config_namespace! macro
+    // can compile without any surrounding `use` statements. Hence putting
+    // it into its own test module.
+    #[test]
+    fn check_config_namespace_macro() {
```
Comment (rkrishn7) [inline datafusion/common/src/config.rs:2104]: Do you think it may be better to add this test/module in `lib.rs` 🤔 ?

Since the subtle addition of a `use super::*` in the future would effectively hide any regression here.

Comment (alamb) [reply datafusion/common/src/config.rs:2104]: I believe this location / test is exactly for ensuring macro's don't import things unnecessarily: https://github.com/apache/datafusion/tree/main/datafusion/core/tests/macro_hygiene

How about we put this test there?

**Review by alamb — COMMENTED** [review]
Thanks @davisp and @rkrishn7

**Comment by davisp** [comment]
@alamb Thanks for the tip! I've moved the test to the macro_hygiene module.

**Review by alamb — APPROVED** [review]
Thanks @davisp and @rkrishn7
