### PR TITLE
fix: ignore `DataType::Null` in possible types during csv type inference

### LINKED ISSUE #17517: Can't read a directory of parquet files:  'Stop:Arrival time' because the from data_type = Timestamp(Second, None) does not equal Utf8
### Describe the bug

I was playing around with the Datafusion CSV parser by using the example from https://duckdb.org/2025/09/08/duckdb-on-the-framework-laptop-13 but DataFusion refused to load it into parquet 

### To Reproduce

Get the data
```shell
wget https://blobs.duckdb.org/nl-railway/railway-services-80-months.zip
unzip railway-services-80-months.zip
```

Then run 
```shell
mkdir services-parquet
datafusion-cli
```

Convert each file to parquet:

```sql
COPY 'services/services-2019.csv' TO 'services-parquet/services-2019.parquet';
COPY 'services/services-2020.csv' TO 'services-parquet/services-2020.parquet';
COPY 'services/services-2021.csv' TO 'services-parquet/services-2021.parquet';
COPY 'services/services-2022.csv' TO 'services-parquet/services-2022.parquet';
COPY 'services/services-2023.csv' TO 'services-parquet/services-2023.parquet';
COPY 'services/services-2024.csv' TO 'services-parquet/services-2024.parquet';
COPY 'services/services-2025-01.csv' TO 'services-parquet/services-2025-01.parquet';
COPY 'services/services-2025-02.csv' TO 'services-parquet/services-2025-02.parquet';
COPY 'services/services-2025-03.csv' TO 'services-parquet/services-2025-03.parquet';
COPY 'services/services-2025-04.csv' TO 'services-parquet/services-2025-04.parquet';
COPY 'services/services-2025-05.csv' TO 'services-parquet/services-2025-05.parquet';
COPY 'services/services-2025-06.csv' TO 'services-parquet/services-2025-07.parquet';
COPY 'services/services-2025-07.csv' TO 'services-parquet/services-2025-07.parquet';
COPY 'services/services-2025-08.csv' TO 'services-parquet/services-2025-08.parquet';
```

And then run 

```sql
DataFusion CLI v49.0.2
> select * from 'services-parquet' limit 10;
Arrow error: Schema error: Fail to merge schema field 'Stop:Arrival time' because the from data_type = Timestamp(Second, None) does not equal Utf8
```

### Expected behavior

I expect to be able to read the data corrrectly 

### Additional context

One error is that the the type of the `Stop: ArrivalTime` has been converted to something different in some of the different files. Sometimes it is a timestamp and sometimes a string:

```sql
> describe 'services-parquet/services-2020.parquet';
+------------------------------+-----------+-------------+
| column_name                  | data_type | is_nullable |
+------------------------------+-----------+-------------+
| Service:RDT-ID               | Int64     | YES         |
| Service:Date                 | Date32    | YES         |
| Service:Type                 | Utf8View  | YES         |
| Service:Company              | Utf8View  | YES         |
| Service:Train number         | Int64     | YES         |
| Service:Completely cancelled | Boolean   | YES         |
| Service:Partly cancelled     | Boolean   | YES         |
| Service:Maximum delay        | Int64     | YES         |
| Stop:RDT-ID                  | Int64     | YES         |
| Stop:Station code            | Utf8View  | YES         |
| Stop:Station name            | Utf8View  | YES         |
| Stop:Arrival time            | Utf8View  | YES         |
| Stop:Arrival delay           | Utf8View  | YES         |
| Stop:Arrival cancelled       | Utf8View  | YES         |
| Stop:Departure time          | Utf8View  | YES         |
| Stop:Departure delay         | Utf8View  | YES         |
| Stop:Departure cancelled     | Utf8View  | YES         |
+------------------------------+-----------+-------------+
17 row(s) fetched.
Elapsed 0.009 seconds.

> describe 'services-parquet/services-2021.parquet';
+------------------------------+-------------------------+-------------+
| column_name                  | data_type               | is_nullable |
+------------------------------+-------------------------+-------------+
| Service:RDT-ID               | Int64                   | YES         |
| Service:Date                 | Date32                  | YES         |
| Service:Type                 | Utf8View                | YES         |
| Service:Company              | Utf8View                | YES         |
| Service:Train number         | Int64                   | YES         |
| Service:Completely cancelled | Boolean                 | YES         |
| Service:Partly cancelled     | Boolean                 | YES         |
| Service:Maximum delay        | Int64                   | YES         |
| Stop:RDT-ID                  | Int64                   | YES         |
| Stop:Station code            | Utf8View                | YES         |
| Stop:Station name            | Utf8View                | YES         |
| Stop:Arrival time            | Timestamp(Second, None) | YES         |.  <--- Note this field type is different
| Stop:Arrival delay           | Int64                   | YES         |
| Stop:Arrival cancelled       | Boolean                 | YES         |
| Stop:Departure time          | Utf8View                | YES         |
| Stop:Departure delay         | Utf8View                | YES         |
| Stop:Departure cancelled     | Utf8View                | YES         |
+------------------------------+-------------------------+-------------+
17 row(s) fetched.
Elapsed 0.008 seconds.
```

### PR DESCRIPTION
**Pull request by dqkqd**
## Which issue does this PR close?

- Closes #17517.

## Rationale for this change

Datafusion cannot infer types correctly for CSV files where one of their chunks only contains NULLs.

Example: Consider the file below
```
a       // 1st chunk
1       // 1st chunk: Int64
2       // 1st chunk: Int64
<null>  // 2nd chunk: null
<null>  // 2nd chunk: null
```
Because all the records in the second chunk are nulls, Datafusion sees the possible data types for `a` as `[Int64, Null]`, and thus infers the data type as `Utf8`.

https://github.com/apache/datafusion/blob/691dd4727d43cf88e90ce5d38d1bcc6b2111ea47/datafusion/datasource-csv/src/file_format.rs#L610-L613

## What changes are included in this PR?

Ignore `DataType::Null` when inferring data type from possible data types.

## Are these changes tested?

Yes.

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/datasource-csv/src/file_format.rs [hunk 1]
```diff
@@ -593,15 +593,23 @@ fn build_schema_helper(names: Vec<String>, types: &[HashSet<DataType>]) -> Schem
         .zip(types)
         .map(|(field_name, data_type_possibilities)| {
             // ripped from arrow::csv::reader::infer_reader_schema_with_csv_options
-            // determine data type based on possible types
-            // if there are incompatible types, use DataType::Utf8
-            match data_type_possibilities.len() {
-                1 => Field::new(
+            // determine data type based on possible types, ignoring DataType::Null,
```
Comment (alamb) [inline datafusion/datasource-csv/src/file_format.rs]: Thank you @dqkqd -- this looks like it would work well. I played around with it and I think we might be able to make this simpler and more efficient by passing in the HashTable and removing the the null. Something like this seemed to work locally 


```rust
// changed signature to take Vec<HashSet<DataType>>.  ----v
fn build_schema_helper(names: Vec<String>, types: Vec<HashSet<DataType>>) -> Schema {
    let fields = names
        .into_iter()
        .zip(types)
        .map(|(field_name, mut data_type_possibilities)| {
            // ripped from arrow::csv::reader::infer_reader_schema_with_csv_options
            // determine data type based on possible types

            // Remove Null (missing column) from possibilities
            data_type_possibilities.remove(&DataType::Null);  <--- changed this

            // if there are incompatible types, use DataType::Utf8
            match data_type_possibilities.len() {
...
```

File: datafusion/core/src/datasource/file_format/csv.rs [hunk 2]
```diff
@@ -470,6 +471,47 @@ mod tests {
         Ok(())
     }
 
+    #[tokio::test]
+    async fn test_infer_schema_stream_separated_chunks_with_nulls() -> Result<()> {
```
Comment (alamb) [inline datafusion/core/src/datasource/file_format/csv.rs]: I don't understand how this test coves the new code. 

However, I did verify that without this code change, this PR fails like this:

```
thread 'datasource::file_format::csv::tests::test_infer_schema_stream_separated_chunks_with_nulls' panicked at datafusion/core/src/datasource/file_format/csv.rs:511:9:
assertion `left == right` failed
  left: ["c1: Int64", "c2: Float64"]
 right: ["c1: Utf8", "c2: Utf8"]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Review by alamb — APPROVED** [review]
Thank you so much @dqkqd  for debugging this issue. It is a great find. 

I left a few suggestions on how to improve the code, but given this solves the issue I think we can do them as a follow on (or never)

I verified that this PR does fix the original report in https://github.com/apache/datafusion/issues/17517:

```sql
> select count(*), "Service:Type" from 'services-parquet' GROUP BY 2 order by 1 desc;
+----------+----------------------+
| count(*) | Service:Type         |
+----------+----------------------+
| 64689377 | Sprinter             |
| 33813656 | Stoptrein            |
| 31252046 | Intercity            |
| 3714068  | Sneltrein            |
| 2284824  | Stopbus i.p.v. trein |
| 1642463  | Intercity direct     |
| 1532087  | stoptrein            |
| 1235170  | Stopbus ipv trein    |
| 772315   | Snelbus i.p.v. trein |
| 515543   | Snelbus ipv trein    |
...
| 83       | Train Charter        |
| 37       | Krokus Express       |
| 12       | Niet instappen       |
| 4        | InnovationXpress     |
| 2        | Tram i.p.v. trein    |
+----------+----------------------+
37 row(s) fetched.
Elapsed 0.170 seconds.
```

However, I couldn't figure out how it worked. 🤔  It seems like this PR has changed the CSV type inference so that it correctly resolves "Stop:Departure time" to a timestamp in 'services-parquet/services-2020.parquet'. 

Can you explain why that is?

```
>  describe 'services-parquet/services-2020.parquet';
+------------------------------+-------------------------+-------------+
| column_name                  | data_type               | is_nullable |
+------------------------------+-------------------------+-------------+
| Service:RDT-ID               | Int64                   | YES         |
| Service:Date                 | Date32                  | YES         |
| Service:Type                 | Utf8View                | YES         |
| Service:Company              | Utf8View                | YES         |
| Service:Train number         | Int64                   | YES         |
| Service:Completely cancelled | Boolean                 | YES         |
| Service:Partly cancelled     | Boolean                 | YES         |
| Service:Maximum delay        | Int64                   | YES         |
| Stop:RDT-ID                  | Int64                   | YES         |
| Stop:Station code            | Utf8View                | YES         |
| Stop:Station name            | Utf8View                | YES         |
| Stop:Arrival time            | Timestamp(Second, None) | YES         |
| Stop:Arrival delay           | Int64                   | YES         |
| Stop:Arrival cancelled       | Boolean                 | YES         |
| Stop:Departure time          | Timestamp(Second, None) | YES         | <-- this column is now correct 
| Stop:Departure delay         | Int64                   | YES         |
| Stop:Departure cancelled     | Boolean                 | YES         |
+------------------------------+-------------------------+-------------+
17 row(s) fetched.
Elapsed 0.008 seconds.
```

Though for some reason I still can't select * from the original directory of CSV files, which I will file a follow on ticket for

File: datafusion/datasource-csv/src/file_format.rs (hunk 1 above)
Comment (alamb) [reply datafusion/datasource-csv/src/file_format.rs]: Though when I did this I found some test failures

```
---- datasource::file_format::csv::tests::infer_schema stdout ----

thread 'datasource::file_format::csv::tests::infer_schema' panicked at datafusion/core/src/datasource/file_format/csv.rs:273:9:
assertion `left == right` failed
  left: ["c1: Utf8", "c2: Int64", "c3: Int64", "c4: Int64", "c5: Int64", "c6: Int64", "c7: Int64", "c8: Int64", "c9: Int64", "c10: Utf8", "c11: Float64", "c12: Float64", "c13: Utf8", "c14: Null", "c15: Utf8"]
 right: ["c1: Utf8", "c2: Int64", "c3: Int64", "c4: Int64", "c5: Int64", "c6: Int64", "c7: Int64", "c8: Int64", "c9: Int64", "c10: Utf8", "c11: Float64", "c12: Float64", "c13: Utf8", "c14: Utf8", "c15: Utf8"]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- datasource::file_format::csv::tests::infer_schema_with_null_regex stdout ----

thread 'datasource::file_format::csv::tests::infer_schema_with_null_regex' panicked at datafusion/core/src/datasource/file_format/csv.rs:324:9:
assertion `left == right` failed
  left: ["c1: Utf8", "c2: Int64", "c3: Int64", "c4: Int64", "c5: Int64", "c6: Int64", "c7: Int64", "c8: Int64", "c9: Int64", "c10: Utf8", "c11: Float64", "c12: Float64", "c13: Utf8", "c14: Null", "c15: Null"]
 right: ["c1: Utf8", "c2: Int64", "c3: Int64", "c4: Int64", "c5: Int64", "c6: Int64", "c7: Int64", "c8: Int64", "c9: Int64", "c10: Utf8", "c11: Float64", "c12: Float64", "c13: Utf8", "c14: Utf8", "c15: Utf8"]


failures:
    datasource::file_format::csv::tests::infer_schema
    datasource::file_format::csv::tests::infer_schema_with_null_regex
```

Comment (dqkqd) [reply datafusion/datasource-csv/src/file_format.rs]: Thanks for pointing out. I simplified the code as suggested.

These tests failed because there were columns with nulls only, after removing them, the match arm fell to `Utf8` case. But they asserted that nulls columns should have data type `DataType::Null`.

File: datafusion/core/src/datasource/file_format/csv.rs (hunk 2 above)
Comment (dqkqd) [reply datafusion/core/src/datasource/file_format/csv.rs]: Datafusion infers data type from each chunk separately, then combines all the possible types.

This test creates a [ChunkedStore](https://docs.rs/object_store/latest/object_store/chunked/struct.ChunkedStore.html), reading each line as a separated chunk (one of them contains only nulls),
then ensure type inference shouldn't be skewed by null chunks.

I should have commented and make the test clearer.

**Comment by dqkqd** [comment]
The test failed. It ensures an empty table should have its columns infer as `Uft8`.
DuckDB does the same so I think this is correct.
```bash
D CREATE TABLE empty AS
  SELECT * FROM read_csv_auto('empty.csv');
D select * from empty;
┌─────────┬─────────┬─────────┐
│   c1    │   c2    │   c3    │
│ varchar │ varchar │ varchar │
├─────────┴─────────┴─────────┤
│           0 rows            │
└─────────────────────────────┘
```

When I check how DuckDB handles table with null columns, it infer those columns as `VARCHAR`.
```bash
D CREATE TABLE has_nulls_column AS
  SELECT * FROM read_csv_auto('has_nulls_column.csv');
D select * from has_nulls_column;
┌───────┬───────┬─────────┐
│  c1   │  c2   │   c3    │
│ int64 │ int64 │ varchar │
├───────┼───────┼─────────┤
│     1 │     2 │ NULL    │
│     3 │     4 │ NULL    │
└───────┴───────┴─────────┘
```

However, datafusion infers those as `Null`. I think we should change them to `Utf8`.
```bash
> CREATE EXTERNAL TABLE has_nulls_column STORED AS CSV LOCATION 'has_nulls_column.csv' OPTIONS ('format.has_header' 'true');
0 row(s) fetched.
Elapsed 0.025 seconds

> select column_name, data_type, ordinal_position from information_schema.columns where table_name='has_nulls_column';
+-------------+-----------+------------------+
| column_name | data_type | ordinal_position |
+-------------+-----------+------------------+
| c1          | Int64     | 0                |
| c2          | Int64     | 1                |
| c3          | Null      | 2                |
+-------------+-----------+------------------+
3 row(s) fetched.
Elapsed 0.010 seconds.
```

I don't think this is hard to do, just fallback to `Utf8` when a column is all nulls.
Then add some testcases for mixed null columns, all null columns, and null regex. (maybe rewrite tests from #13228)

@alamb Would you like me to handle these cases in this PR?
Or I should just handle empty table by returning `Utf8` and cover the remaining cases in another PR?

**Comment by dqkqd** [comment]
I've just realized that returning `Utf8` for columns with only nulls (or empty files) causes schema mismatch when reading folders containing those files along with normal files. 
So maybe returning `DataType::Null` is a better choice. I'll revert the code and update testcase.

```
> cat test_data/a.csv
c1,c2,c3

> cat test_data/b.csv
c1,c2,c3
1,1,1
2,2,2
```

This fails in `main`.
```
DataFusion CLI v50.0.0
> select * from 'test_data';
Arrow error: Schema error: Fail to merge schema field 'c1' because the from data_type = Utf8 does not equal Int64
```

File: datafusion/core/src/datasource/file_format/csv.rs [hunk 3]
```diff
@@ -470,6 +471,59 @@ mod tests {
...
     }
 
+    #[tokio::test]
+    async fn test_infer_schema_stream_null_chunks() -> Result<()> {
+        let session_ctx = SessionContext::new();
+        let state = session_ctx.state();
+
+        // a stream where each line is read as a separate chunk,
+        // data type for each chunk is inferred separately.
+        // +----+-----+----+
```
Comment (alamb) [inline datafusion/core/src/datasource/file_format/csv.rs:481]: thank you for these comments

File: datafusion/datasource-csv/src/file_format.rs [hunk 4]
```diff
@@ -582,20 +582,25 @@ impl CsvFormat {
...
+        .map(|(field_name, mut data_type_possibilities)| {
             // ripped from arrow::csv::reader::infer_reader_schema_with_csv_options
             // determine data type based on possible types
             // if there are incompatible types, use DataType::Utf8
+
+            // ignore nulls, to avoid conflicting datatypes (e.g. [nulls, int]) being inferred as Utf8.
+            data_type_possibilities.remove(&DataType::Null);
+
             match data_type_possibilities.len() {
+                0 => Field::new(field_name, DataType::Null, true),
```
Comment (alamb) [inline datafusion/datasource-csv/src/file_format.rs:606]: I agree this makes sense. Some context might help too:

```suggestion
                // Return Null for columns with only nulls / empty files
                // This allows schema merging to work when reading folders 
                // such files along with normal files.
                0 => Field::new(field_name, DataType::Null, true),
```

File: datafusion/sqllogictest/test_files/ddl.slt [hunk 5]
```diff
@@ -707,9 +707,9 @@ CREATE EXTERNAL TABLE empty STORED AS CSV LOCATION '../core/tests/data/empty.csv
 query TTI
 select column_name, data_type, ordinal_position from information_schema.columns where table_name='empty';;
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/ddl.slt:708]: this makes sense to me

**Review by alamb — APPROVED** [review]
Thank you @dqkqd  -- this now looks really nice 🏅 🏆 ❤️

**Comment by alamb** [comment]
Sadly, I tried this branch with the reproducer in
- https://github.com/apache/datafusion/issues/17516

And it seems that CSV type inference is still not working correctly 😢  

To be clear, I don't think anything needs to change in this PR, I was just hoping it also fixed something else, which it did not

Update: @EeshanBembi actually already has a fix for it!
- https://github.com/apache/datafusion/pull/17553

**Comment by alamb** [comment]
🦾  🚀

**Comment by alamb** [comment]
Thanks again @dqkqd  -- this is a very nice first PR
