### PR TITLE
Fix: array list values are leaked on nested `unnest` operators

### LINKED ISSUE #10672: ArrayList data is leaked to outside unnest logical plan from the inner unnest logical plan that comes before a Limit
### Describe the bug

Given this query
```
select unnest(struct_c1c0), unnest(list_c2c0) from (
            select unnest(column1) as struct_c1c0, unnest(column2)['c0'] as list_c2c0 from temp limit 1
 );
```
where list_c2c0 is the result of an unnest logical plan followed by a limit
```
| logical_plan  | Unnest: lists[unnest(list_c2c0)] structs[unnest(struct_c1c0)]                                                                 |
|               |   Projection: unnest(temp.column1) AS unnest(struct_c1c0), get_field(unnest(column2), Utf8("c0")) AS unnest(list_c2c0)        |
|               |     Limit: skip=0, fetch=1                                                                                                    |
|               |       Unnest: lists[unnest(temp.column1), unnest(column2)] structs[]                                                          |
|               |         Projection: temp.column1 AS unnest(temp.column1), temp.column2 AS unnest(column2)                                     |
|               |           TableScan: temp projection=[column1, column2]   
```
then unnesting on this column "list_c2c0" again will cause the error
```
Arrow error: Invalid argument error: all columns in a record batch must have the same length
```

### To Reproduce

```
> create table temp as values ([struct('a')], [struct([1,2]),struct([2,3])]);
0 row(s) fetched. 
Elapsed 0.008 seconds.
> select unnest(column1) as struct_c1c0, unnest(column2)['c0'] as list_c2c0 from temp limit 1;
+-------------+-----------+
| struct_c1c0 | list_c2c0 |
+-------------+-----------+
| {c0: a}     | [1, 2]    |
+-------------+-----------+
1 row(s) fetched. 
Elapsed 0.010 seconds.
> select unnest(struct_c1c0), unnest(list_c2c0) from (
            select unnest(column1) as struct_c1c0, unnest(column2)['c0'] as list_c2c0 from temp limit 1
 );
Arrow error: Invalid argument error: all columns in a record batch must have the same length
```

### Expected behavior

Correct result returned
```
> select unnest(struct_c1c0), unnest(list_c2c0) from (
            select unnest(column1) as struct_c1c0, unnest(column2)['c0'] as list_c2c0 from temp limit 1
 );
+------------------------+-------------------+
| unnest(struct_c1c0).c0 | unnest(list_c2c0) |
+------------------------+-------------------+
| a                      | 1                 |
| a                      | 2                 |
+------------------------+-------------------+
```

### Additional context

The problem may be somewhere around this line
```
https://github.com/apache/datafusion/blob/34eda15b73a9e278af8844b30ed2f1c21c10359c/datafusion/physical-plan/src/unnest.rs#L431
```
The context of this function is it's trying to downcast the generic Array into underlying type and use the underlying values as the unnested column values.
However this downcast somehow leak all the values which were previously skipped at the Limit operator, thus leak the extra elements [2,3].
If we add these debug lines
```
        println!(
            "dyn array length: {} and data {:?}",
            list_arrays[0].len(),
            list_arrays[0]
        );
        println!(
            "down casted array length {} and data {:?}",
            typed_arrays[0].values().len(),
            typed_arrays[0].values()
        );
```
The result will be
```
dyn array length: 1 and data ListArray
[
  PrimitiveArray<Int64>
[
  1,
  2,
],
]
down casted array length 4 and data PrimitiveArray<Int64>
[
  1,
  2,
  2,
  3,
]
```

### PR DESCRIPTION
**Pull request by duongcongtoai**
## Which issue does this PR close?

Closes #10672 .

### CODE REVIEW

File: datafusion/physical-plan/src/unnest.rs [hunk 1]
```diff
@@ -515,16 +515,10 @@ fn unnest_list_arrays(
         })
         .collect::<Result<Vec<_>>>()?;
 
-    // If there is only one list column to unnest and it doesn't contain any NULL lists,
-    // we can return the values array directly without any copying.
-    if typed_arrays.len() == 1 && typed_arrays[0].null_count() == 0 {
-        Ok(vec![typed_arrays[0].values().clone()])
```
Comment (duongcongtoai) [inline datafusion/physical-plan/src/unnest.rs:521]: this will return the underlying low level array, which include the row indices filtered out by limit/offset

**Review by jonahgao — APPROVED** [review]
Nice catch ! Thanks @duongcongtoai 

Another simple way to reproduce it is 
```sql
select unnest(column1) from (select * from (values([1,2,3]), ([4,5,6])) limit 1);
```

I'm not sure if this is a bug in arrow-rs or by design. It only [slices](https://github.com/apache/arrow-rs/blob/95791f1c317558a57b4570660f204bd9764426aa/arrow-array/src/array/list_array.rs#L327) the offset data of the `ListArray`, without slicing the child data.

**Comment by duongcongtoai** [comment]
> Nice catch ! Thanks @duongcongtoai
> 
> Another simple way to reproduce it is
> 
> ```sql
> select unnest(column1) from (select * from (values([1,2,3]), ([4,5,6])) limit 1);
> ```
> 
> I'm not sure if this is a bug in arrow-rs or by design. It only [slices](https://github.com/apache/arrow-rs/blob/95791f1c317558a57b4570660f204bd9764426aa/arrow-array/src/array/list_array.rs#L327) the offset data of the `ListArray`, without slicing the child data.

I think current impl is correct, because the offset values after slicing is still offsetted based on original array. Else we have to do shifting for each offset elements like
```
Current buffers
            undearneath value: [1,?,3,?,5,6]
            nulls: [1,0,1,0,1,1]
            offset: [0,1,2,4,6]
            logical value: [1] [null] [3,null] [5,6]

Slice(2,2)
            logical values -> [3,null] [5,6]
            offset -> [2,4,6] << 2 = [0,2,4] 
            unearneath_value.slice(2:) = [3,?,5,6]
            nulls.slice(2:) = [1,0,1,1]
```

**Comment by jonahgao** [comment]
> I think current impl is correct, because the offset values after slicing is still offsetted based on original array. Else we have to do shifting for each offset elements like

I think the shifting operation should be done internally in arrow-rs if needed, as it depends on what the data in the [values](https://github.com/apache/arrow-rs/blob/95791f1c317558a57b4570660f204bd9764426aa/arrow-array/src/array/list_array.rs#L130) looks like. Moreover, we don't need to do shifting for [FixedSizeListArray](https://github.com/apache/arrow-rs/blob/95791f1c317558a57b4570660f204bd9764426aa/arrow-array/src/array/fixed_size_list_array.rs#L282). 

The current solution looks good to me.
