### PR TITLE
Handle canceled partitioned hash join dynamic filters lazily

### LINKED ISSUE #21625: bug: TPCH 18 query hangs
### Describe the bug

On my machine
```
OS: Fedora Linux 43 (KDE Plasma Desktop Edition) x86_64
Kernel: Linux 6.19.11-200.fc43.x86_64
CPU: AMD Ryzen AI 9 HX 370 (24) @ 5.16 GHz
GPU: AMD Radeon 890M Graphics [Integrated]
Memory: 11.96 GiB / 86.02 GiB (14%)
Swap: 0 B / 8.00 GiB (0%)
```
with updated rust:
```
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/bruce/.rustup

installed toolchains
--------------------
stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu
1.91.0-x86_64-unknown-linux-gnu
1.92.0-x86_64-unknown-linux-gnu
1.93.0-x86_64-unknown-linux-gnu
1.94.0-x86_64-unknown-linux-gnu (active)

active toolchain
----------------
name: 1.94.0-x86_64-unknown-linux-gnu
active because: overridden by '/home/bruce/dev/datafusion2/rust-toolchain.toml'
installed targets:
  x86_64-unknown-linux-gnu
```

Running against main:
`cd benchmarks;./bench.sh data tpch;./bench.sh run tpch 18` will hang
```
$ ./bench.sh run tpch 18
***************************
DataFusion Benchmark Script
COMMAND: run
BENCHMARK: tpch
QUERY: 18
DATAFUSION_DIR: /home/bruce/dev/datafusion2/benchmarks/..
BRANCH_NAME: HEAD
DATA_DIR: /home/bruce/dev/datafusion2/benchmarks/data
RESULTS_DIR: /home/bruce/dev/datafusion2/benchmarks/results/HEAD
CARGO_COMMAND: cargo run --release
PREFER_HASH_JOIN: true
SIMULATE_LATENCY: false
***************************
RESULTS_FILE: /home/bruce/dev/datafusion2/benchmarks/results/HEAD/tpch_sf1.json
Running tpch benchmark...
+ cargo run --release --bin dfbench -- tpch --iterations 5 --path /home/bruce/dev/datafusion2/benchmarks/data/tpch_sf1 --prefer_hash_join true --format parquet -o /home/bruce/dev/datafusion2/benchmarks/results/HEAD/tpch_sf1.json --query 18
    Finished `release` profile [optimized] target(s) in 0.11s
     Running `/home/bruce/dev/datafusion2/target/release/dfbench tpch --iterations 5 --path /home/bruce/dev/datafusion2/benchmarks/data/tpch_sf1 --prefer_hash_join true --format parquet -o /home/bruce/dev/datafusion2/benchmarks/results/HEAD/tpch_sf1.json --query 18`
Running benchmarks with the following options: RunOpt { query: Some(18), common: CommonOpt { iterations: 5, partitions: None, batch_size: None, mem_pool_type: "fair", memory_limit: None, sort_spill_reservation_bytes: None, debug: false, simulate_latency: false }, path: "/home/bruce/dev/datafusion2/benchmarks/data/tpch_sf1", file_format: "parquet", mem_table: false, output_path: Some("/home/bruce/dev/datafusion2/benchmarks/results/HEAD/tpch_sf1.json"), disable_statistics: false, prefer_hash_join: true, enable_piecewise_merge_join: false, sorted: false, hash_join_buffering_capacity: 0 }
```

git bisect points to [this commit](https://github.com/apache/datafusion/commit/6c5e241e6298e70077259b3a12840c3adab3c810) as the cause. Running the test at the commit just prior to that one succeeds. Running it at that commit fails.

If prefer_hash_join is disabled the query will run as expected:
```
PREFER_HASH_JOIN=false ./bench.sh run tpch 18
***************************
DataFusion Benchmark Script
COMMAND: run
BENCHMARK: tpch
QUERY: 18
DATAFUSION_DIR: /home/bruce/dev/datafusion2/benchmarks/..
BRANCH_NAME: HEAD
DATA_DIR: /home/bruce/dev/datafusion2/benchmarks/data
RESULTS_DIR: /home/bruce/dev/datafusion2/benchmarks/results/HEAD
CARGO_COMMAND: cargo run --release
PREFER_HASH_JOIN: false
SIMULATE_LATENCY: false
***************************
RESULTS_FILE: /home/bruce/dev/datafusion2/benchmarks/results/HEAD/tpch_sf1.json
Running tpch benchmark...
+ cargo run --release --bin dfbench -- tpch --iterations 5 --path /home/bruce/dev/datafusion2/benchmarks/data/tpch_sf1 --prefer_hash_join false --format parquet -o /home/bruce/dev/datafusion2/benchmarks/results/HEAD/tpch_sf1.json --query 18
    Finished `release` profile [optimized] target(s) in 0.15s
     Running `/home/bruce/dev/datafusion2/target/release/dfbench tpch --iterations 5 --path /home/bruce/dev/datafusion2/benchmarks/data/tpch_sf1 --prefer_hash_join false --format parquet -o /home/bruce/dev/datafusion2/benchmarks/results/HEAD/tpch_sf1.json --query 18`
Running benchmarks with the following options: RunOpt { query: Some(18), common: CommonOpt { iterations: 5, partitions: None, batch_size: None, mem_pool_type: "fair", memory_limit: None, sort_spill_reservation_bytes: None, debug: false, simulate_latency: false }, path: "/home/bruce/dev/datafusion2/benchmarks/data/tpch_sf1", file_format: "parquet", mem_table: false, output_path: Some("/home/bruce/dev/datafusion2/benchmarks/results/HEAD/tpch_sf1.json"), disable_statistics: false, prefer_hash_join: false, enable_piecewise_merge_join: false, sorted: false, hash_join_buffering_capacity: 0 }
Query 18 iteration 0 took 206.5 ms and returned 57 rows
Query 18 iteration 1 took 190.0 ms and returned 57 rows
Query 18 iteration 2 took 188.5 ms and returned 57 rows
Query 18 iteration 3 took 185.0 ms and returned 57 rows
Query 18 iteration 4 took 192.1 ms and returned 57 rows
Query 18 avg time: 192.42 ms
+ set +x
Done
```

### To Reproduce

This seems to be machine/OS specific. I've been unable to reproduce on other machines.

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adriangb**
## Which issue does this PR close?

- Closes https://github.com/apache/datafusion/issues/21625

## Rationale for this change

Partitioned hash join dynamic filters assumed every build-side partition would eventually report build data to the shared coordinator. That assumption breaks when an upstream partitioned operator legally short-circuits and drops a child hash-join partition before it is ever polled far enough to report.

In the original reproducer, a parent `RightSemi` join completes early for partitions whose own build side is empty. That causes child partitioned hash-join streams to be dropped while still waiting to build/report their dynamic-filter contribution. Sibling partitions then wait forever for reports that will never arrive.

## What changes are included in this PR?

- teach the shared partitioned dynamic-filter coordinator to distinguish terminal partition states:
  - reported build data
  - canceled before build data was known
- mark unreported partitioned hash-join streams as canceled on `Drop`
- treat canceled partitions as `true` in the synthesized partitioned filter so they do not block completion or incorrectly filter probe rows
- preserve existing empty-partition behavior so known-empty partitions still contribute `false`
- preserve the existing compact filter plan shapes when there are no canceled partitions, including the single-branch collapse used in hash-collision mode
- add a regression test for the cancellation pattern that previously hung

## Are these changes tested?

- `cargo fmt --all`
- `cargo test -p datafusion-physical-plan test_partitioned_dynamic_filter_reports_empty_canceled_partitions -- --nocapture`
- `cargo test -p datafusion --test core_integration physical_optimizer::filter_pushdown::test_hashjoin_dynamic_filter_pushdown_partitioned -- --nocapture`
- `cargo test -p datafusion --test core_integration physical_optimizer::filter_pushdown::test_hashjoin_dynamic_filter_pushdown_partitioned --features force_hash_collisions -- --nocapture`
- verified that `test_partitioned_dynamic_filter_reports_empty_canceled_partitions` times out on the pre-fix revision and passes on this branch

`cargo clippy --all-targets --all-features -- -D warnings` still fails on an unrelated existing workspace lint in `datafusion/expr/src/logical_plan/plan.rs:3773` (`clippy::mutable_key_type`).

## Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by adriangb** [comment]
run benchmarks

**Comment by adriangb** [comment]
run benchmark tpcds

**Comment by Omega359** [comment]
query 72 took a bit of a hit here.

<details>
  <summary>Query72</summary>
  
```sql
select  i_item_desc
      ,w_warehouse_name
      ,d1.d_week_seq
      ,sum(case when p_promo_sk is null then 1 else 0 end) no_promo
      ,sum(case when p_promo_sk is not null then 1 else 0 end) promo
      ,count(*) total_cnt
from catalog_sales
join inventory on (cs_item_sk = inv_item_sk)
join warehouse on (w_warehouse_sk=inv_warehouse_sk)
join item on (i_item_sk = cs_item_sk)
join customer_demographics on (cs_bill_cdemo_sk = cd_demo_sk)
join household_demographics on (cs_bill_hdemo_sk = hd_demo_sk)
join date_dim d1 on (cs_sold_date_sk = d1.d_date_sk)
join date_dim d2 on (inv_date_sk = d2.d_date_sk)
join date_dim d3 on (cs_ship_date_sk = d3.d_date_sk)
left outer join promotion on (cs_promo_sk=p_promo_sk)
left outer join catalog_returns on (cr_item_sk = cs_item_sk and cr_order_number = cs_order_number)
where d1.d_week_seq = d2.d_week_seq
  and inv_quantity_on_hand < cs_quantity
  and d3.d_date > (d1.d_date + INTERVAL '5 days')
  and hd_buy_potential = '1001-5000'
  and d1.d_year = 2001
  and cd_marital_status = 'M'
group by i_item_desc,w_warehouse_name,d1.d_week_seq
order by total_cnt desc, i_item_desc, w_warehouse_name, d_week_seq
limit 100;
```

</details>

**Comment by adriangb** [comment]
Yes. And I think this was another bandaid. But it's closer to the root cause than previous attempts. This has to do with cancellation when multiple joins are involved.

TLDR I think what is happening is when you have multiple joins you end up with a tree of operators. One of the joins up higher in the tree hits the new optimization and aborts work, dropping tasks that would have polled downstream joins. But not the downstream join is stuck waiting for all of it's partition tasks to finish even though they never will. I think we were all operating under the assumption that the issue was within a single join operator but really it's an issue any time an upstream operator cancels on a join.

I think the real solution is to track when a join build partition task gets dropped and report that to the dynamic filter building so that it doesn't wait for that partition to report.

**Comment by adriangb** [comment]
run benchmark tpcds

**Comment by adriangb** [comment]
run benchmarks

**Comment by adriangb** [comment]
Okay I think this addresses the root cause with no performance regression or behavior changes.

**Comment by adriangb** [comment]
@RatulDawar could you let me know what you think of this solution?

**Comment by RatulDawar** [comment]
@adriangb  went through the solution and the PR, makes much more sense to remove barrier and track states instead here, this also give a much predictable behaviour due to the mention of explicit states. 

Just one concern with code here, reaching to a correct state here depends on if the person calls report_build_data. Can we have a state transition method so that build data is automatically reported and we would just need to call the state changes method ike existing state_after_build_ready.

**Comment by adriangb** [comment]
@RatulDawar does 5ad96d908292d3c17e74964854f68dd0e3a3ad43 help?

**Comment by adriangb** [comment]
@Omega359, @gabotechs, @kosiew wondering if one of you as a committer would mind reviewing?

**Comment by Omega359** [comment]
I'm not actually a committer @adriangb ... legal at work never got back to approving me :( In any case I'm not knowledgeable enough about this area of the code to be much help I'm afraid.

**Comment by RatulDawar** [comment]
> @RatulDawar does [5ad96d9](https://github.com/apache/datafusion/commit/5ad96d908292d3c17e74964854f68dd0e3a3ad43) help?

Looks great now !

File: datafusion/physical-plan/src/joins/hash_join/exec.rs [hunk 1]
```diff
@@ -1316,6 +1316,33 @@ impl ExecutionPlan for HashJoinExec {
...
+            .on
+            .iter()
+            .map(|(_, right_expr)| Arc::clone(right_expr))
+            .collect::<Vec<_>>();
+        let build_accumulator = enable_dynamic_filter_pushdown
+            .then(|| {
+                self.dynamic_filter.as_ref().map(|df| {
+                    let filter = Arc::clone(&df.filter);
+                    Some(Arc::clone(df.build_accumulator.get_or_init(|| {
+                        Arc::new(SharedBuildAccumulator::new_from_partition_mode(
```
Comment (gabotechs) [inline datafusion/physical-plan/src/joins/hash_join/exec.rs:1332]: :thinking: I'm trying to deduce what does this change do, but I'm seeing that it's not related with the fix and it's just a refactor? is that right or did I missed something?

File: datafusion/physical-plan/src/joins/hash_join/stream.rs [hunk 2]
```diff
@@ -421,6 +424,49 @@ impl HashJoinStream {
...
+            PartitionMode::Auto => unreachable!(
+                "PartitionMode::Auto should not be present at execution time. This is a bug in DataFusion, please report it!"
+            ),
+        };
+
+        let acc = Arc::clone(build_accumulator);
+        self.build_waiter = Some(OnceFut::new(async move {
+            acc.report_build_data(build_data).await
+        }));
+        self.build_reported = true;
```
Comment (gabotechs) [inline datafusion/physical-plan/src/joins/hash_join/stream.rs]: I'm also trying to understand what exactly changed here, and it looks like the only logical change is that now there's a `self.build_reported = true` flag set, but everything else is pretty much a refactor. Does that sound right?

**Comment by adriangb** [comment]
Great all we need is review from a committer now 😄

File: datafusion/physical-plan/src/joins/hash_join/shared_bounds.rs [hunk 3]
```diff
@@ -358,229 +391,283 @@ impl SharedBuildAccumulator {
...
-                            Arc::new(CaseExpr::try_new(
-                                Some(modulo_expr),
-                                when_then_branches,
-                                Some(lit(false)), // ELSE false
-                            )?) as Arc<dyn PhysicalExpr>
-                        };
+            };
+            notified.await;
+        }
+    }
```
Comment (gabotechs) [inline datafusion/physical-plan/src/joins/hash_join/shared_bounds.rs:563]: I don't understand much the difference between the previous barrier and the current `loop` + `Notify` approach. At first sight, it looks like a convoluted way of re-implementing what the barrier, and the differential factor that seems key to solve the deadlock is calling `report_canceled_partition` on `HashJoinStream` drop.

Is it not possible to just gracefully handling the cancellation by doing something with the `Barrier` on drop?

File: datafusion/physical-plan/src/joins/hash_join/shared_bounds.rs [hunk 4]
```diff
@@ -358,229 +391,283 @@ impl SharedBuildAccumulator {
...
+
+    fn finish(&self, finalize_input: FinalizeInput) {
+        let result = self.build_filter(finalize_input).map_err(Arc::new);
+        self.dynamic_filter.mark_complete();
+
+        let mut guard = self.inner.lock();
+        guard.completion = CompletionState::Ready(result);
+        drop(guard);
+        self.completion_notify.notify_waiters();
+    }
```
Comment (gabotechs) [inline datafusion/physical-plan/src/joins/hash_join/shared_bounds.rs:545]: A `Mutex` with shared state + a `Notify` for broadcasting update signals sounds essentially a reimplementation of `tokio::sync::watch`.

I don't have the full context so the current solution might actually be the best one, just want to double-check that other synchronization primitives where considered before choosing this one.

File: datafusion/physical-plan/src/joins/hash_join/exec.rs [hunk 5]
```diff
@@ -5628,6 +5643,158 @@ mod tests {
         Ok(())
     }
 
+    #[tokio::test]
+    async fn test_partitioned_dynamic_filter_reports_empty_canceled_partitions()
```
Comment (gabotechs) [inline datafusion/physical-plan/src/joins/hash_join/exec.rs:5647]: Double checked with `main` and indeed this test reproduces the error 👍

**Review by gabotechs — COMMENTED** [review]
Looks good! left some comments mainly with questions for my understanding, as I'm not very familiar with this code.

File: datafusion/physical-plan/src/joins/hash_join/shared_bounds.rs (hunk 3 above)
Comment (adriangb) [reply datafusion/physical-plan/src/joins/hash_join/shared_bounds.rs:563]: Yes this is a refactor from https://github.com/apache/datafusion/pull/21666#issuecomment-4268080577

File: datafusion/physical-plan/src/joins/hash_join/stream.rs (hunk 2 above)
Comment (kosiew) [inline datafusion/physical-plan/src/joins/hash_join/stream.rs]: I think there is still a race here. `build_reported` gets flipped as soon as the `OnceFut` is created, but the future is lazy and only runs once `wait_for_partition_bounds_report()` actually polls it.

If a parent drops this stream after `transition_after_build_collected()` returns, but before the waiter is ever polled, `Drop` will skip `report_canceled_partition()` even though nothing was delivered to the coordinator. That feels like it recreates the original hang, just in a narrower timing window.

Would it make sense to only mark this as reported after the waiter completes successfully? Alternatively, maybe replace the bool with a small lifecycle state so `Drop` can still cancel something that was only scheduled but never observed.

File: datafusion/physical-plan/src/joins/hash_join/shared_bounds.rs [hunk 6]
```diff
@@ -358,229 +397,283 @@ impl SharedBuildAccumulator {
...
+                    let membership_expr = create_membership_predicate(
+                        &self.on_right,
+                        partition_data.pushdown.clone(),
+                        &HASH_JOIN_SEED,
+                        self.probe_schema.as_ref(),
+                    )?;
+                    let bounds_expr =
+                        create_bounds_predicate(&self.on_right, &partition_data.bounds);
+
+                    if let Some(filter_expr) = match (membership_expr, bounds_expr) {
```
Comment (kosiew) [inline datafusion/physical-plan/src/joins/hash_join/shared_bounds.rs]: I noticed the “membership + bounds gives final predicate” logic now exists in both the `CollectLeft` and `Partitioned` finalize paths, with slightly different control flow.

It might be worth pulling that into a small helper so both branches stay aligned as the dynamic filter logic evolves. That would make future changes a bit safer.

File: datafusion/physical-plan/src/joins/hash_join/stream.rs [hunk 7]
```diff
@@ -219,6 +219,8 @@ pub(super) struct HashJoinStream {
     /// Optional future to signal when build information has been reported by all partitions
     /// and the dynamic filter has been updated
     build_waiter: Option<OnceFut<()>>,
+    /// Tracks whether this partition has already reported build information to the coordinator.
```
Comment (kosiew) [inline datafusion/physical-plan/src/joins/hash_join/stream.rs]: Once the blocking issue above is sorted out, this field might benefit from a stronger type than just `bool`.

Something like `NotReported`, `ReportScheduled`, and `ReportDelivered` would make the drop semantics much clearer and help avoid another mix-up between "scheduled" and "actually seen by the coordinator".

**Review by kosiew — CHANGES_REQUESTED** [review]
@adriangb 

Thanks for the ping. 
I dug into the lifecycle around reporting and cancellation, and there is a subtle timing issue that could reintroduce a hang. I left details inline. I also added a couple of suggestions that could help keep things easier to reason about going forward.

File: datafusion/physical-plan/src/joins/hash_join/shared_bounds.rs
Comment (kosiew) [inline datafusion/physical-plan/src/joins/hash_join/shared_bounds.rs]: This should be updated since this PR replaced the Barrier-based coordination.

**Review by kosiew — APPROVED** [review]
looks good to me 
except a comment clean-up for Barrier.

**Comment by adriangb** [comment]
Thanks for the review @kosiew !

@gabotechs I did try to use an existing primitive, but I couldn't quite get anything to fit the shape we need. If you or anyone else can improve it a followup is welcome, but I didn't want to hold up unblocking benchmarks.
