### PR TITLE
fix: Eliminate consecutive repartitions

### LINKED ISSUE #18341: Avoid consecutive RepartitionExec
While playing with aggregation, I found that there are cases where two RepartitionExec next to each other that I think very sub-optimal and we should improve. 

I have this data set that I store in both csv na dparquet

### PR DESCRIPTION
**Pull request by gene-bordegaray**
## Which issue does this PR close?

- Closes #18341.
- Closes https://github.com/apache/datafusion/issues/9370

## Rationale for this change

Cases where two RepartitionExec operators appear consecutively in the plan. This is unneeded overhead that eliminating provides speed ups.

Full Report:  [The Physical Optimizer and Fixing Consecutive Repartitions In the Enforce Distribution Rule.pdf](https://github.com/user-attachments/files/23420831/The.Physical.Optimizer.and.Fixing.Consecutive.Repartitions.In.the.Enforce.Distribution.Rule.pdf)

Issue Report: [Fixing Consecutive Repartitions In the Enforce Distribution Rule.pdf](https://github.com/user-attachments/files/23420880/Fixing.Consecutive.Repartitions.In.the.Enforce.Distribution.Rule.pdf)

## What changes are included in this PR?

Change to repartition adding logic in `enforce_distribution.rs`
A ton of test and bench updates to mirror new behavior

## Are these changes tested?

Yes benchmarked and tested, check report for benchmarks

### CODE REVIEW

**Comment by alamb** [comment]
@NGA-TRAN and @gabotechs could you also please help review this PR?

File: datafusion/physical-optimizer/src/enforce_distribution.rs [hunk 1]
```diff
@@ -1273,7 +1273,7 @@ pub fn ensure_distribution(
                     child = add_merge_on_top(child);
                 }
                 Distribution::HashPartitioned(exprs) => {
-                    if add_roundrobin {
+                    if add_roundrobin && !hash_necessary {
```
Comment (NGA-TRAN) [inline datafusion/physical-optimizer/src/enforce_distribution.rs:1277]: **To reviewers:** This is the fix. The rest is test update

See [this](https://github.com/apache/datafusion/issues/18341#issuecomment-3505130845) for summary of the fix

See[ this](https://github.com/apache/datafusion/issues/18341#issuecomment-3503238325) for full analysis in 2 pdf  doc

**Review by NGA-TRAN — APPROVED** [review]
Wonderful work. Way to go @gene-bordegaray

File: datafusion/physical-optimizer/src/enforce_distribution.rs (hunk 1 above)
Comment (adriangb) [reply datafusion/physical-optimizer/src/enforce_distribution.rs:1277]: Could we permalink to these in the code?

**Comment by alamb** [comment]
🤖 `./gh_compare_branch.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/gh_compare_branch.sh) Running
Linux aal-dev 6.14.0-1018-gcp #19~24.04.1-Ubuntu SMP Wed Sep 24 23:23:09 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing gene.bordegaray/2025/10/avoid_consecutive_repartition_exec (746d6ba9c60a02b85818dc2cadc1ad938c7d2839) to a5eb9121ccf802dda547897155403b08a4fbf774 [diff](https://github.com/apache/datafusion/compare/a5eb9121ccf802dda547897155403b08a4fbf774..746d6ba9c60a02b85818dc2cadc1ad938c7d2839) using:  tpch_mem clickbench_partitioned clickbench_extended
Results will be posted here when complete

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
Comparing HEAD and gene.bordegaray_2025_10_avoid_consecutive_repartition_exec
--------------------
Benchmark clickbench_extended.json
--------------------
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ Query        ┃        HEAD ┃        gene ┃    Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ QQuery 0     │  2701.66 ms │  2687.43 ms │ no change │
│ QQuery 1     │  1256.52 ms │  1265.34 ms │ no change │
│ QQuery 2     │  2421.37 ms │  2430.82 ms │ no change │
│ QQuery 3     │  1175.67 ms │  1166.23 ms │ no change │
│ QQuery 4     │  2289.33 ms │  2290.09 ms │ no change │
│ QQuery 5     │ 28305.63 ms │ 28486.55 ms │ no change │
│ QQuery 6     │  4049.84 ms │  4039.75 ms │ no change │
│ QQuery 7     │  3747.33 ms │  3683.37 ms │ no change │
└──────────────┴─────────────┴─────────────┴───────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Benchmark Summary      ┃            ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ Total Time (HEAD)      │ 45947.35ms │
│ Total Time (gene)      │ 46049.59ms │
│ Average Time (HEAD)    │  5743.42ms │
│ Average Time (gene)    │  5756.20ms │
│ Queries Faster         │          0 │
│ Queries Slower         │          0 │
│ Queries with No Change │          8 │
│ Queries with Failure   │          0 │
└────────────────────────┴────────────┘
--------------------
Benchmark clickbench_partitioned.json
--------------------
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Query        ┃        HEAD ┃        gene ┃        Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ QQuery 0     │     2.56 ms │     2.24 ms │ +1.15x faster │
│ QQuery 1     │    49.67 ms │    49.68 ms │     no change │
│ QQuery 2     │   136.20 ms │   135.65 ms │     no change │
│ QQuery 3     │   166.98 ms │   159.12 ms │     no change │
│ QQuery 4     │  1109.85 ms │  1196.88 ms │  1.08x slower │
│ QQuery 5     │  1510.69 ms │  1584.73 ms │     no change │
│ QQuery 6     │     2.22 ms │     2.19 ms │     no change │
│ QQuery 7     │    55.25 ms │    56.19 ms │     no change │
│ QQuery 8     │  1478.38 ms │  1542.17 ms │     no change │
│ QQuery 9     │  1837.53 ms │  1850.17 ms │     no change │
│ QQuery 10    │   377.00 ms │   383.87 ms │     no change │
│ QQuery 11    │   436.38 ms │   432.86 ms │     no change │
│ QQuery 12    │  1372.09 ms │  1469.16 ms │  1.07x slower │
│ QQuery 13    │  2147.58 ms │  2217.65 ms │     no change │
│ QQuery 14    │  1296.23 ms │  1332.32 ms │     no change │
│ QQuery 15    │  1265.17 ms │  1299.31 ms │     no change │
│ QQuery 16    │  2711.44 ms │  2773.30 ms │     no change │
│ QQuery 17    │  2709.72 ms │  2744.08 ms │     no change │
│ QQuery 18    │  5621.26 ms │  5105.92 ms │ +1.10x faster │
│ QQuery 19    │   125.58 ms │   130.52 ms │     no change │
│ QQuery 20    │  2034.69 ms │  1999.22 ms │     no change │
│ QQuery 21    │  2307.78 ms │  2302.57 ms │     no change │
│ QQuery 22    │  6432.16 ms │  3979.01 ms │ +1.62x faster │
│ QQuery 23    │ 24802.80 ms │ 12873.93 ms │ +1.93x faster │
│ QQuery 24    │   223.29 ms │   212.35 ms │     no change │
│ QQuery 25    │   483.20 ms │   489.86 ms │     no change │
│ QQuery 26    │   219.08 ms │   210.53 ms │     no change │
│ QQuery 27    │  2788.56 ms │  2799.81 ms │     no change │
│ QQuery 28    │ 23375.34 ms │ 23911.66 ms │     no change │
│ QQuery 29    │   956.28 ms │   979.24 ms │     no change │
│ QQuery 30    │  1380.62 ms │  1363.76 ms │     no change │
│ QQuery 31    │  1409.79 ms │  1402.90 ms │     no change │
│ QQuery 32    │  4872.99 ms │  4523.94 ms │ +1.08x faster │
│ QQuery 33    │  5968.13 ms │  5757.30 ms │     no change │
│ QQuery 34    │  6295.36 ms │  6058.88 ms │     no change │
│ QQuery 35    │  2091.71 ms │  2070.84 ms │     no change │
│ QQuery 36    │   118.00 ms │   121.01 ms │     no change │
│ QQuery 37    │    51.82 ms │    52.62 ms │     no change │
│ QQuery 38    │   121.17 ms │   119.61 ms │     no change │
│ QQuery 39    │   199.56 ms │   196.22 ms │     no change │
│ QQuery 40    │    42.19 ms │    44.91 ms │  1.06x slower │
│ QQuery 41    │    39.41 ms │    40.77 ms │     no change │
│ QQuery 42    │    32.56 ms │    33.39 ms │     no change │
└──────────────┴─────────────┴─────────────┴───────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┓
┃ Benchmark Summary      ┃             ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━┩
│ Total Time (HEAD)      │ 110658.28ms │
│ Total Time (gene)      │  96012.32ms │
│ Average Time (HEAD)    │   2573.45ms │
│ Average Time (gene)    │   2232.84ms │
│ Queries Faster         │           5 │
│ Queries Slower         │           3 │
│ Queries with No Change │          35 │
│ Queries with Failure   │           0 │
└────────────────────────┴─────────────┘
--------------------
Benchmark tpch_mem_sf1.json
--------------------
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃ Query        ┃      HEAD ┃      gene ┃       Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━┩
│ QQuery 1     │ 127.88 ms │ 130.46 ms │    no change │
│ QQuery 2     │  26.94 ms │  28.66 ms │ 1.06x slower │
│ QQuery 3     │  39.13 ms │  39.31 ms │    no change │
│ QQuery 4     │  29.17 ms │  28.85 ms │    no change │
│ QQuery 5     │  87.75 ms │  88.28 ms │    no change │
│ QQuery 6     │  19.89 ms │  20.08 ms │    no change │
│ QQuery 7     │ 226.07 ms │ 234.72 ms │    no change │
│ QQuery 8     │  34.42 ms │  35.61 ms │    no change │
│ QQuery 9     │ 107.81 ms │ 104.83 ms │    no change │
│ QQuery 10    │  65.41 ms │  64.39 ms │    no change │
│ QQuery 11    │  18.45 ms │  18.69 ms │    no change │
│ QQuery 12    │  50.21 ms │  52.75 ms │ 1.05x slower │
│ QQuery 13    │  47.07 ms │  47.95 ms │    no change │
│ QQuery 14    │  13.84 ms │  14.03 ms │    no change │
│ QQuery 15    │  25.17 ms │  25.04 ms │    no change │
│ QQuery 16    │  25.59 ms │  25.01 ms │    no change │
│ QQuery 17    │ 151.65 ms │ 155.29 ms │    no change │
│ QQuery 18    │ 286.29 ms │ 285.04 ms │    no change │
│ QQuery 19    │  37.89 ms │  38.83 ms │    no change │
│ QQuery 20    │  49.58 ms │  49.98 ms │    no change │
│ QQuery 21    │ 334.18 ms │ 342.72 ms │    no change │
│ QQuery 22    │  21.03 ms │  21.40 ms │    no change │
└──────────────┴───────────┴───────────┴──────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ Benchmark Summary      ┃           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ Total Time (HEAD)      │ 1825.43ms │
│ Total Time (gene)      │ 1851.91ms │
│ Average Time (HEAD)    │   82.97ms │
│ Average Time (gene)    │   84.18ms │
│ Queries Faster         │         0 │
│ Queries Slower         │         2 │
│ Queries with No Change │        20 │
│ Queries with Failure   │         0 │
└────────────────────────┴───────────┘
```


</p>
</details>

File: datafusion/sqllogictest/test_files/joins.slt [hunk 2]
```diff
@@ -3269,22 +3262,17 @@ logical_plan
...
-11)------SortExec: expr=[a@1 ASC], preserve_partitioning=[true]
-12)--------CoalesceBatchesExec: target_batch_size=2
-13)----------RepartitionExec: partitioning=Hash([a@1], 2), input_partitions=2
-14)------------RepartitionExec: partitioning=RoundRobinBatch(2), input_partitions=1
-15)--------------ProjectionExec: expr=[a0@0 as a0, a@1 as a, b@2 as b, c@3 as c, d@4 as d, row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING@5 as rn1]
-16)----------------BoundedWindowAggExec: wdw=[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING: Field { "row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING": UInt64 }, frame: ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING], mode=[Sorted]
-17)------------------DataSourceExec: file_groups={1 group: [[WORKSPACE_ROOT/datafusion/core/tests/data/window_2.csv]]}, projection=[a0, a, b, c, d], output_ordering=[a@1 ASC, b@2 ASC NULLS LAST, c@3 ASC NULLS LAST], file_type=csv, has_header=true
+02)--SortMergeJoin: join_type=Inner, on=[(a@1, a@1)]
```
Comment (2010YOUY01) [inline datafusion/sqllogictest/test_files/joins.slt:3265]: Here it removed a `SortExec`, is it expected?

File: datafusion/physical-optimizer/src/enforce_distribution.rs (hunk 1 above)
Comment (NGA-TRAN) [reply datafusion/physical-optimizer/src/enforce_distribution.rs:1277]: @adriangb : Do you mean adding the comment with links right at the fix for future reference?

File: datafusion/sqllogictest/test_files/joins.slt [hunk 3]
```diff
@@ -3269,22 +3262,17 @@ logical_plan
...
+07)------------DataSourceExec: file_groups={1 group: [[WORKSPACE_ROOT/datafusion/core/tests/data/window_2.csv]]}, projection=[a0, a, b, c, d], output_ordering=[a@1 ASC, b@2 ASC NULLS LAST, c@3 ASC NULLS LAST], file_type=csv, has_header=true
+08)----CoalesceBatchesExec: target_batch_size=2
+09)------RepartitionExec: partitioning=Hash([a@1], 2), input_partitions=1
+10)--------ProjectionExec: expr=[a0@0 as a0, a@1 as a, b@2 as b, c@3 as c, d@4 as d, row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING@5 as rn1]
+11)----------BoundedWindowAggExec: wdw=[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING: Field { "row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING": UInt64 }, frame: ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING], mode=[Sorted]
+12)------------DataSourceExec: file_groups={1 group: [[WORKSPACE_ROOT/datafusion/core/tests/data/window_2.csv]]}, projection=[a0, a, b, c, d], output_ordering=[a@1 ASC, b@2 ASC NULLS LAST, c@3 ASC NULLS LAST], file_type=csv, has_header=true
```
Comment (NGA-TRAN) [inline datafusion/sqllogictest/test_files/joins.slt:3275]: Data is sorted on `a, b, c`

File: datafusion/sqllogictest/test_files/joins.slt [hunk 4]
```diff
@@ -3269,22 +3262,17 @@ logical_plan
...
+06)----------BoundedWindowAggExec: wdw=[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING: Field { "row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING": UInt64 }, frame: ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING], mode=[Sorted]
+07)------------DataSourceExec: file_groups={1 group: [[WORKSPACE_ROOT/datafusion/core/tests/data/window_2.csv]]}, projection=[a0, a, b, c, d], output_ordering=[a@1 ASC, b@2 ASC NULLS LAST, c@3 ASC NULLS LAST], file_type=csv, has_header=true
+08)----CoalesceBatchesExec: target_batch_size=2
+09)------RepartitionExec: partitioning=Hash([a@1], 2), input_partitions=1
+10)--------ProjectionExec: expr=[a0@0 as a0, a@1 as a, b@2 as b, c@3 as c, d@4 as d, row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING@5 as rn1]
+11)----------BoundedWindowAggExec: wdw=[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING: Field { "row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING": UInt64 }, frame: ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING], mode=[Sorted]
```
Comment (NGA-TRAN) [inline datafusion/sqllogictest/test_files/joins.slt:3274]: Data is sorted on `a, b, c, rn1`

File: datafusion/sqllogictest/test_files/joins.slt [hunk 5]
```diff
@@ -3269,22 +3262,17 @@ logical_plan
...
+02)--SortMergeJoin: join_type=Inner, on=[(a@1, a@1)]
+03)----CoalesceBatchesExec: target_batch_size=2
+04)------RepartitionExec: partitioning=Hash([a@1], 2), input_partitions=1
+05)--------ProjectionExec: expr=[a0@0 as a0, a@1 as a, b@2 as b, c@3 as c, d@4 as d, row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING@5 as rn1]
+06)----------BoundedWindowAggExec: wdw=[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING: Field { "row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING": UInt64 }, frame: ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING], mode=[Sorted]
+07)------------DataSourceExec: file_groups={1 group: [[WORKSPACE_ROOT/datafusion/core/tests/data/window_2.csv]]}, projection=[a0, a, b, c, d], output_ordering=[a@1 ASC, b@2 ASC NULLS LAST, c@3 ASC NULLS LAST], file_type=csv, has_header=true
+08)----CoalesceBatchesExec: target_batch_size=2
+09)------RepartitionExec: partitioning=Hash([a@1], 2), input_partitions=1
```
Comment (NGA-TRAN) [inline datafusion/sqllogictest/test_files/joins.slt:3272]: This is the key check: we need to confirm whether the data remains sorted after Hash Repartition. We're using it to split one partition/stream into two, and if we simply apply the hash function and stream each row forward, the data should stay sorted within each resulting partition/stream on `a, b, c, rn1`. I strongly suspect this holds, but we need to verify.

@gene-bordegaray:

Could you test this across different datasets to confirm both correctness and sort order?

Most importantly:
i. Check whether the execution plan marks the data as sorted per partition after Hash Repartition. If it does, please file a new ticket to ensure we display the sort order post-repartition in future work. 
ii. Investigate whether the data is actually sorted per partition, even when it's marked as such.

File: datafusion/sqllogictest/test_files/joins.slt (hunk 2 above)
Comment (NGA-TRAN) [reply datafusion/sqllogictest/test_files/joins.slt:3265]: See my three comments below. If the data in each corresponding partition/stream of the  join input is already sorted, we can skip the re-sorting step and simply perform a merge join on each matching partition/stream.

File: datafusion/sqllogictest/test_files/joins.slt [hunk 6]
```diff
@@ -3269,22 +3262,17 @@ logical_plan
 10)----------TableScan: annotated_data projection=[a0, a, b, c, d]
 physical_plan
 01)SortPreservingMergeExec: [a@1 ASC, b@2 ASC NULLS LAST, c@3 ASC NULLS LAST, rn1@11 ASC NULLS LAST]
```
Comment (NGA-TRAN) [inline datafusion/sqllogictest/test_files/joins.slt:3264]: And because there are 2 sorted partitions/streams after the join, we need this SortPreservingMergeExec to merge them

**Comment by gene-bordegaray** [comment]
> Thank you for the amazing work.
> 
> Removing unnecessary consecutive `RepartitionExec` makes sense to me, however I have went through half of the test and found 2 plan changes that is not `2 RepartitionExec -> 1 RepartitionExec`, I'm wondering is that expected? Do we have other plan changes that is not removing 1 of the consecutive `RepartitionExec`?
> 
> The first one see review comment.
> 
> The second one is tpch-q4, I saw a 20% speedup in benchmark result, so I checked the query plan, and the difference is it's removing a round robin repartition above parquet reader:

Can you calrify the data you used to create the tables, thank you

File: datafusion/sqllogictest/test_files/joins.slt (hunk 5 above)
Comment (NGA-TRAN) [reply datafusion/sqllogictest/test_files/joins.slt:3272]: And if this is the case, this would be another great optimization we have for free with this fix. I actually ran into this. See [Even More Suboptimal Plan here](https://github.com/NGA-TRAN/datafusion-optimal-plans/blob/main/docs/7_cli_read_plans_aggregation.md#even-more-sub-optimal-plan).

File: datafusion/physical-optimizer/src/enforce_distribution.rs (hunk 1 above)
Comment (gene-bordegaray) [reply datafusion/physical-optimizer/src/enforce_distribution.rs:1277]: if we link these I would like to finish the docs to be complete. If you notice I cut off at the end of the explanation of the enforce_distribution because this was thorough enough for this bug

File: datafusion/sqllogictest/test_files/joins.slt (hunk 5 above)
Comment (gene-bordegaray) [reply datafusion/sqllogictest/test_files/joins.slt:3272]: Ok great, yes I can investigate this.

File: datafusion/sqllogictest/test_files/joins.slt (hunk 6 above)
Comment (gene-bordegaray) [reply datafusion/sqllogictest/test_files/joins.slt:3264]: This the conclusion I cam to as well off of intutition but will confirm 😄

**Comment by NGA-TRAN** [comment]
>> @2010YOUY01 : The second one is tpch-q4, I saw a 20% speedup in benchmark result, so I checked the query plan, and the difference is it's removing a round robin repartition above parquet reader:

> @gene-bordegaray : Can you calrify the data you used to create the tables, thank you

@2010YOUY01 : The reason Gene asked you to verify your test data is [in this explanation](https://github.com/apache/datafusion/issues/18341#issuecomment-3505130845). It seems in the build side your lineitem table is too small to repartition. Thus the plan after the fix does not repartition it. That is the reason for the speedup

**Comment by gene-bordegaray** [comment]
> > > @2010YOUY01 : The second one is tpch-q4, I saw a 20% speedup in benchmark result, so I checked the query plan, and the difference is it's removing a round robin repartition above parquet reader:
> 
> > @gene-bordegaray : Can you calrify the data you used to create the tables, thank you
> 
> @2010YOUY01 : The reason Gene asked you to verify your test data is [in this explanation](https://github.com/apache/datafusion/issues/18341#issuecomment-3505130845). It seems in the build side your lineitem table is too small to repartition. Thus the plan after the fix does not repartition it. That is the reason for the speedup

Yes, I am suspecting that  i is due to the size of the tables because the logic for repartitioning at the file level lives above and independent of the repartitioning logic changes I have made

**Comment by NGA-TRAN** [comment]
>>>> @2010YOUY01 : The second one is tpch-q4, I saw a 20% speedup in benchmark result, so I checked the query plan, and the difference is it's removing a round robin repartition above parquet reader:

>>> @gene-bordegaray : Can you calrify the data you used to create the tables, thank you

>> @NGA-TRAN : @2010YOUY01 : The reason Gene asked you to verify your test data is https://github.com/apache/datafusion/issues/18341#issuecomment-3505130845. It seems in the build side your lineitem table is too small to repartition. Thus the plan after the fix does not repartition it. That is the reason for the speedup

> @gene-bordegaray: Yes, I am suspecting that i is due to the size of the tables because the logic for repartitioning at the file level lives above and independent of the repartitioning logic changes I have made

That’s likely the case—there’s a predicate on the lineitem table, and we’ve pushed down a kind-of bloom filter to prune data during the scan. As a result, the dataset could be quite small. I wouldn’t worry about this scenario; it’s a reasonable outcome and one of the motivations behind the fix. Plus, it clearly improves query performance.

File: datafusion/sqllogictest/test_files/joins.slt (hunk 5 above)
Comment (gene-bordegaray) [reply datafusion/sqllogictest/test_files/joins.slt:3272]: I have recreated the query from join.slt and checked the results, here is the command recreated:

```
-- These are settings that are set in join.slt that are set prior to the query
SET datafusion.optimizer.prefer_hash_join = false;
SET datafusion.explain.format = 'indent';

CREATE EXTERNAL TABLE annotated_data (
  a0 INTEGER,
  a INTEGER,
  b INTEGER,
  c INTEGER,
  d INTEGER
)
STORED AS CSV
WITH ORDER (a ASC NULLS FIRST, b ASC, c ASC)
LOCATION 'datafusion/core/tests/data/window_2.csv'
OPTIONS ('format.has_header' 'true');

EXPLAIN SELECT *
FROM (SELECT *, ROW_NUMBER() OVER() as rn1
      FROM annotated_data) as l_table
JOIN (SELECT *, ROW_NUMBER() OVER() as rn1
      FROM annotated_data) as r_table
ON l_table.a = r_table.a
ORDER BY l_table.a ASC NULLS FIRST, l_table.b, l_table.c, r_table.rn1;

SELECT *
FROM (SELECT *, ROW_NUMBER() OVER() as rn1
      FROM annotated_data) as l_table
JOIN (SELECT *, ROW_NUMBER() OVER() as rn1
      FROM annotated_data) as r_table
ON l_table.a = r_table.a
ORDER BY l_table.a ASC NULLS FIRST, l_table.b, l_table.c, r_table.rn1
LIMIT 30;

+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                                                                                                                                                      |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Sort: l_table.a ASC NULLS FIRST, l_table.b ASC NULLS LAST, l_table.c ASC NULLS LAST, r_table.rn1 ASC NULLS LAST                                                                                                                                                                           |
|               |   Inner Join: l_table.a = r_table.a                                                                                                                                                                                                                                                       |
|               |     SubqueryAlias: l_table                                                                                                                                                                                                                                                                |
|               |       Projection: annotated_data.a0, annotated_data.a, annotated_data.b, annotated_data.c, annotated_data.d, row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING AS rn1                                                                                                 |
|               |         WindowAggr: windowExpr=[[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING]]                                                                                                                                                                                  |
|               |           TableScan: annotated_data projection=[a0, a, b, c, d]                                                                                                                                                                                                                           |
|               |     SubqueryAlias: r_table                                                                                                                                                                                                                                                                |
|               |       Projection: annotated_data.a0, annotated_data.a, annotated_data.b, annotated_data.c, annotated_data.d, row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING AS rn1                                                                                                 |
|               |         WindowAggr: windowExpr=[[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING]]                                                                                                                                                                                  |
|               |           TableScan: annotated_data projection=[a0, a, b, c, d]                                                                                                                                                                                                                           |
| physical_plan | SortPreservingMergeExec: [a@1 ASC, b@2 ASC NULLS LAST, c@3 ASC NULLS LAST, rn1@11 ASC NULLS LAST]                                                                                                                                                                                         |
|               |   SortMergeJoin: join_type=Inner, on=[(a@1, a@1)]                                                                                                                                                                                                                                         |
|               |     CoalesceBatchesExec: target_batch_size=2                                                                                                                                                                                                                                              |
|               |       RepartitionExec: partitioning=Hash([a@1], 2), input_partitions=1                                                                                                                                                                                                                    |
|               |         ProjectionExec: expr=[a0@0 as a0, a@1 as a, b@2 as b, c@3 as c, d@4 as d, row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING@5 as rn1]                                                                                                                         |
|               |           BoundedWindowAggExec: wdw=[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING: Field { "row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING": UInt64 }, frame: ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING], mode=[Sorted]    |
|               |             DataSourceExec: file_groups={1 group: [[Users/gene.bordegaray/go/src/github.com/DataDog/datafusion/datafusion/core/tests/data/window_2.csv]]}, projection=[a0, a, b, c, d], output_ordering=[a@1 ASC, b@2 ASC NULLS LAST, c@3 ASC NULLS LAST], file_type=csv, has_header=true |
|               |     CoalesceBatchesExec: target_batch_size=2                                                                                                                                                                                                                                              |
|               |       RepartitionExec: partitioning=Hash([a@1], 2), input_partitions=1                                                                                                                                                                                                                    |
|               |         ProjectionExec: expr=[a0@0 as a0, a@1 as a, b@2 as b, c@3 as c, d@4 as d, row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING@5 as rn1]                                                                                                                         |
|               |           BoundedWindowAggExec: wdw=[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING: Field { "row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING": UInt64 }, frame: ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING], mode=[Sorted]    |
|               |             DataSourceExec: file_groups={1 group: [[Users/gene.bordegaray/go/src/github.com/DataDog/datafusion/datafusion/core/tests/data/window_2.csv]]}, projection=[a0, a, b, c, d], output_ordering=[a@1 ASC, b@2 ASC NULLS LAST, c@3 ASC NULLS LAST], file_type=csv, has_header=true |
|               |                                                                                                                                                                                                                                                                                           |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
2 row(s) fetched.
Elapsed 0.003 seconds.

+----+---+---+---+---+-----+----+---+---+----+---+-----+
| a0 | a | b | c | d | rn1 | a0 | a | b | c  | d | rn1 |
+----+---+---+---+---+-----+----+---+---+----+---+-----+
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 0  | 0 | 1   |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 1  | 2 | 2   |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 2  | 0 | 3   |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 3  | 0 | 4   |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 4  | 1 | 5   |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 5  | 1 | 6   |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 6  | 0 | 7   |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 7  | 2 | 8   |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 8  | 1 | 9   |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 9  | 4 | 10  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 10 | 4 | 11  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 11 | 2 | 12  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 12 | 2 | 13  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 13 | 1 | 14  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 14 | 2 | 15  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 15 | 3 | 16  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 16 | 3 | 17  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 17 | 2 | 18  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 18 | 1 | 19  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 19 | 4 | 20  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 20 | 0 | 21  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 21 | 3 | 22  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 22 | 0 | 23  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 23 | 0 | 24  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 0 | 24 | 4 | 25  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 1 | 25 | 0 | 26  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 1 | 26 | 2 | 27  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 1 | 27 | 0 | 28  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 1 | 28 | 1 | 29  |
| 1  | 0 | 0 | 0 | 0 | 1   | 1  | 0 | 1 | 29 | 1 | 30  |
+----+---+---+---+---+-----+----+---+---+----+---+-----+
30 row(s) fetched.
Elapsed 0.003 seconds.
```

1. The physical plan here has a Hash Repartition on the and no SortExec node above. Despite this as seen the results are still sorted meaning that sorting was preserved. 
2. The metadata for when order is preserved is not shown as seen in the above plan. The EXPLAIN output should display this but does not. This is tracked in the field `maintains_input_order`. I can create an issue for this and link it here
3. To recreate this I had to have: explicit ordering in the `WITH ORDER` and `ORDER BY` clause and set the prefer_hash_join flag to false to force SortMergeJoin. This means with the default config if a user is using pre-sorted files they might miss speed ups by keeping unneeded `SortExec` nodes. Might be worth further discussion if there is a better way to handle this or open an issue to look further into this.

Let me know what you think
@2010YOUY01

**Comment by 2010YOUY01** [comment]
> > Thank you for the amazing work.
> > Removing unnecessary consecutive `RepartitionExec` makes sense to me, however I have went through half of the test and found 2 plan changes that is not `2 RepartitionExec -> 1 RepartitionExec`, I'm wondering is that expected? Do we have other plan changes that is not removing 1 of the consecutive `RepartitionExec`?
> > The first one see review comment.
> > The second one is tpch-q4, I saw a 20% speedup in benchmark result, so I checked the query plan, and the difference is it's removing a round robin repartition above parquet reader:
> 
> Can you calrify the data you used to create the tables, thank you

I'm using tpch-sf0.1 dataset generated by https://github.com/clflushopt/tpchgen-rs/tree/main/tpchgen-cli
`tpchgen-cli -s 0.1 --format=parquet`
And register the dataset in `datafusion-cli` like
<details>

```
CREATE EXTERNAL TABLE customer
STORED AS PARQUET
LOCATION '/Users/yongting/Code/datafusion-sqlstorm/data/customer.parquet';

CREATE EXTERNAL TABLE nation
STORED AS PARQUET
LOCATION '/Users/yongting/Code/datafusion-sqlstorm/data/nation.parquet';

CREATE EXTERNAL TABLE part
STORED AS PARQUET
LOCATION '/Users/yongting/Code/datafusion-sqlstorm/data/part.parquet';

CREATE EXTERNAL TABLE region
STORED AS PARQUET
LOCATION '/Users/yongting/Code/datafusion-sqlstorm/data/region.parquet';

CREATE EXTERNAL TABLE lineitem
STORED AS PARQUET
LOCATION '/Users/yongting/Code/datafusion-sqlstorm/data/lineitem.parquet';

CREATE EXTERNAL TABLE orders
STORED AS PARQUET
LOCATION '/Users/yongting/Code/datafusion-sqlstorm/data/orders.parquet';

CREATE EXTERNAL TABLE partsupp
STORED AS PARQUET
LOCATION '/Users/yongting/Code/datafusion-sqlstorm/data/partsupp.parquet';

CREATE EXTERNAL TABLE supplier
STORED AS PARQUET
LOCATION '/Users/yongting/Code/datafusion-sqlstorm/data/supplier.parquet';
```

</details>

This PR collected the HJ build side into a single partition, while previously it doesn't. I checked with
```
SET datafusion.explain.show_statistics = true;
EXPLAIN ANALYZE...
```
And the statistics estimates the scan output row to be below `datafusion.optimizer.hash_join_single_partition_threshold_rows`, so the behavior is expected. Previously it's failing to follow the threshold for unknown reasons.

I think the result is good, nothing to worry about.

File: datafusion/sqllogictest/test_files/joins.slt (hunk 5 above)
Comment (2010YOUY01) [reply datafusion/sqllogictest/test_files/joins.slt:3272]: Yes, this seems a different issue that is triggered by the change, would be great to investigate in the future.

File: datafusion/sqllogictest/test_files/window.slt [hunk 7]
```diff
@@ -1925,16 +1924,15 @@ logical_plan
...
 physical_plan
 01)SortPreservingMergeExec: [c3@0 ASC NULLS LAST], fetch=5
-02)--ProjectionExec: expr=[c3@0 as c3, sum(aggregate_test_100.c9) ORDER BY [aggregate_test_100.c3 DESC NULLS FIRST, aggregate_test_100.c9 DESC NULLS FIRST, aggregate_test_100.c2 ASC NULLS LAST] RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW@2 as sum1, sum(aggregate_test_100.c9) PARTITION BY [aggregate_test_100.c3] ORDER BY [aggregate_test_100.c9 DESC NULLS FIRST] RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW@3 as sum2]
-03)----BoundedWindowAggExec: wdw=[sum(aggregate_test_100.c9) PARTITION BY [aggregate_test_100.c3] ORDER BY [aggregate_test_100.c9 DESC NULLS FIRST] RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW: Field { "sum(aggregate_test_100.c9) PARTITION BY [aggregate_test_100.c3] ORDER BY [aggregate_test_100.c9 DESC NULLS FIRST] RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW": nullable UInt64 }, frame: RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW], mode=[Sorted]
-04)------SortExec: expr=[c3@0 ASC NULLS LAST, c9@1 DESC], preserve_partitioning=[true]
+02)--SortExec: TopK(fetch=5), expr=[c3@0 ASC NULLS LAST], preserve_partitioning=[true]
```
Comment (2010YOUY01) [inline datafusion/sqllogictest/test_files/window.slt:1927]: Here it adds a `SortExec` similarly, might also worth investigating later.

**Review by 2010YOUY01 — APPROVED** [review]
LGTM, thank you.

I’ve reviewed all the test changes, everything looks good except several `SortExec` additions and removals — these appear to be redundant. It’s not a correctness issue, but it could affect performance, so it might be worth investigating further in the future.

**Comment by 2010YOUY01** [comment]
BTW, I think it's a great opportunity to add a section in the tuning guide https://datafusion.apache.org/user-guide/configs.html#tuning-guide explaining the default repartitioning behavior and how related configuration options (such as the minimum file size for repartitioning, minimum repartition size for hash joins, etc.) can affect it.

File: datafusion/sqllogictest/test_files/window.slt (hunk 7 above)
Comment (gene-bordegaray) [reply datafusion/sqllogictest/test_files/window.slt:1927]: I agree, I will amke not and submit an issue / discussion. later today or tmrw

File: datafusion/sqllogictest/test_files/joins.slt (hunk 5 above)
Comment (NGA-TRAN) [reply datafusion/sqllogictest/test_files/joins.slt:3272]: Thanks so much @gene-bordegaray and @2010YOUY01.

In summary, everything is working as expected. Gene’s fix—removing the unnecessary repartition—helped preserve the sort order, which in turn made the execution plan even more efficient.

CC @alamb

File: datafusion/sqllogictest/test_files/window.slt (hunk 7 above)
Comment (NGA-TRAN) [reply datafusion/sqllogictest/test_files/window.slt:1927]: Note: it does **not** add the `SortExec`. It moves the `SortExec`

**Comment by Dandandan** [comment]
Very nice results! This encourages me to have a look at hash-RepartitionExec once more :)

**Comment by gene-bordegaray** [comment]
> Very nice results! This encourages me to have a look at hash-RepartitionExec once more :)

I am glad :) , very fun to contribute

**Comment by alamb** [comment]
🤖 `./gh_compare_branch.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/gh_compare_branch.sh) Running
Linux aal-dev 6.14.0-1018-gcp #19~24.04.1-Ubuntu SMP Wed Sep 24 23:23:09 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing gene.bordegaray/2025/10/avoid_consecutive_repartition_exec (746d6ba9c60a02b85818dc2cadc1ad938c7d2839) to a5eb9121ccf802dda547897155403b08a4fbf774 [diff](https://github.com/apache/datafusion/compare/a5eb9121ccf802dda547897155403b08a4fbf774..746d6ba9c60a02b85818dc2cadc1ad938c7d2839) using:  tpch_mem clickbench_partitioned clickbench_extended
Results will be posted here when complete

File: datafusion/physical-optimizer/src/enforce_distribution.rs (hunk 1 above)
Comment (alamb) [reply datafusion/physical-optimizer/src/enforce_distribution.rs:1277]: Perhaps we can link to the comment: https://github.com/apache/datafusion/issues/18341#issuecomment-3503238325

That way you can edit / update the comment as needed

Something like this perhaps

```suggestion
                    // See https://github.com/apache/datafusion/issues/18341#issuecomment-3503238325 for background
                    if add_roundrobin && !hash_necessary {
```

Comment (gene-bordegaray) [reply datafusion/physical-optimizer/src/enforce_distribution.rs:1277]: I think this is good, this will let me link the docs after I finish including the last bit of logic.

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
Comparing HEAD and gene.bordegaray_2025_10_avoid_consecutive_repartition_exec
--------------------
Benchmark clickbench_extended.json
--------------------
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃ Query        ┃        HEAD ┃        gene ┃       Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━┩
│ QQuery 0     │  2698.74 ms │  2712.76 ms │    no change │
│ QQuery 1     │  1260.63 ms │  1265.42 ms │    no change │
│ QQuery 2     │  2387.18 ms │  2522.90 ms │ 1.06x slower │
│ QQuery 3     │  1166.96 ms │  1177.50 ms │    no change │
│ QQuery 4     │  2291.58 ms │  2308.66 ms │    no change │
│ QQuery 5     │ 28348.74 ms │ 28678.78 ms │    no change │
│ QQuery 6     │  4049.28 ms │  4055.22 ms │    no change │
│ QQuery 7     │  3749.07 ms │  3648.12 ms │    no change │
└──────────────┴─────────────┴─────────────┴──────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Benchmark Summary      ┃            ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ Total Time (HEAD)      │ 45952.19ms │
│ Total Time (gene)      │ 46369.36ms │
│ Average Time (HEAD)    │  5744.02ms │
│ Average Time (gene)    │  5796.17ms │
│ Queries Faster         │          0 │
│ Queries Slower         │          1 │
│ Queries with No Change │          7 │
│ Queries with Failure   │          0 │
└────────────────────────┴────────────┘
--------------------
Benchmark clickbench_partitioned.json
--------------------
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Query        ┃        HEAD ┃        gene ┃        Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ QQuery 0     │     2.27 ms │     2.26 ms │     no change │
│ QQuery 1     │    50.66 ms │    50.28 ms │     no change │
│ QQuery 2     │   136.60 ms │   138.77 ms │     no change │
│ QQuery 3     │   162.29 ms │   163.96 ms │     no change │
│ QQuery 4     │  1074.77 ms │  1117.81 ms │     no change │
│ QQuery 5     │  1535.68 ms │  1550.42 ms │     no change │
│ QQuery 6     │     2.14 ms │     2.18 ms │     no change │
│ QQuery 7     │    54.42 ms │    54.78 ms │     no change │
│ QQuery 8     │  1493.63 ms │  1467.26 ms │     no change │
│ QQuery 9     │  1855.67 ms │  1880.77 ms │     no change │
│ QQuery 10    │   374.00 ms │   384.13 ms │     no change │
│ QQuery 11    │   432.72 ms │   431.81 ms │     no change │
│ QQuery 12    │  1363.21 ms │  1388.07 ms │     no change │
│ QQuery 13    │  2111.50 ms │  2150.71 ms │     no change │
│ QQuery 14    │  1289.81 ms │  1281.76 ms │     no change │
│ QQuery 15    │  1233.63 ms │  1251.77 ms │     no change │
│ QQuery 16    │  2713.82 ms │  2730.59 ms │     no change │
│ QQuery 17    │  2717.88 ms │  2720.69 ms │     no change │
│ QQuery 18    │  5282.63 ms │  5007.89 ms │ +1.05x faster │
│ QQuery 19    │   129.33 ms │   127.42 ms │     no change │
│ QQuery 20    │  2001.56 ms │  1990.64 ms │     no change │
│ QQuery 21    │  2297.86 ms │  2309.18 ms │     no change │
│ QQuery 22    │  3949.17 ms │  3956.58 ms │     no change │
│ QQuery 23    │ 15078.32 ms │ 12734.83 ms │ +1.18x faster │
│ QQuery 24    │   216.32 ms │   222.87 ms │     no change │
│ QQuery 25    │   492.12 ms │   473.90 ms │     no change │
│ QQuery 26    │   208.94 ms │   217.13 ms │     no change │
│ QQuery 27    │  2814.30 ms │  2755.24 ms │     no change │
│ QQuery 28    │ 23481.27 ms │ 23681.89 ms │     no change │
│ QQuery 29    │   985.15 ms │   982.13 ms │     no change │
│ QQuery 30    │  1346.66 ms │  1340.37 ms │     no change │
│ QQuery 31    │  1408.24 ms │  1406.21 ms │     no change │
│ QQuery 32    │  4891.49 ms │  5051.32 ms │     no change │
│ QQuery 33    │  6043.34 ms │  5872.82 ms │     no change │
│ QQuery 34    │  6097.78 ms │  6101.02 ms │     no change │
│ QQuery 35    │  2136.04 ms │  2022.94 ms │ +1.06x faster │
│ QQuery 36    │   123.57 ms │   120.04 ms │     no change │
│ QQuery 37    │    52.55 ms │    53.48 ms │     no change │
│ QQuery 38    │   120.20 ms │   121.29 ms │     no change │
│ QQuery 39    │   195.47 ms │   199.61 ms │     no change │
│ QQuery 40    │    44.75 ms │    43.40 ms │     no change │
│ QQuery 41    │    39.89 ms │    38.96 ms │     no change │
│ QQuery 42    │    32.50 ms │    32.40 ms │     no change │
└──────────────┴─────────────┴─────────────┴───────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Benchmark Summary      ┃            ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ Total Time (HEAD)      │ 98074.17ms │
│ Total Time (gene)      │ 95631.61ms │
│ Average Time (HEAD)    │  2280.79ms │
│ Average Time (gene)    │  2223.99ms │
│ Queries Faster         │          3 │
│ Queries Slower         │          0 │
│ Queries with No Change │         40 │
│ Queries with Failure   │          0 │
└────────────────────────┴────────────┘
--------------------
Benchmark tpch_mem_sf1.json
--------------------
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Query        ┃      HEAD ┃      gene ┃        Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ QQuery 1     │ 129.16 ms │ 129.58 ms │     no change │
│ QQuery 2     │  26.77 ms │  28.13 ms │  1.05x slower │
│ QQuery 3     │  40.83 ms │  39.10 ms │     no change │
│ QQuery 4     │  29.29 ms │  29.04 ms │     no change │
│ QQuery 5     │  87.09 ms │  87.55 ms │     no change │
│ QQuery 6     │  19.96 ms │  20.08 ms │     no change │
│ QQuery 7     │ 225.99 ms │ 222.18 ms │     no change │
│ QQuery 8     │  34.57 ms │  35.47 ms │     no change │
│ QQuery 9     │ 103.75 ms │ 107.18 ms │     no change │
│ QQuery 10    │  62.66 ms │  64.20 ms │     no change │
│ QQuery 11    │  18.52 ms │  17.58 ms │ +1.05x faster │
│ QQuery 12    │  52.07 ms │  52.58 ms │     no change │
│ QQuery 13    │  48.16 ms │  48.78 ms │     no change │
│ QQuery 14    │  13.91 ms │  14.23 ms │     no change │
│ QQuery 15    │  24.84 ms │  24.68 ms │     no change │
│ QQuery 16    │  25.19 ms │  26.68 ms │  1.06x slower │
│ QQuery 17    │ 151.11 ms │ 153.78 ms │     no change │
│ QQuery 18    │ 280.89 ms │ 287.00 ms │     no change │
│ QQuery 19    │  38.22 ms │  37.51 ms │     no change │
│ QQuery 20    │  50.55 ms │  49.58 ms │     no change │
│ QQuery 21    │ 321.11 ms │ 347.32 ms │  1.08x slower │
│ QQuery 22    │  21.61 ms │  21.60 ms │     no change │
└──────────────┴───────────┴───────────┴───────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ Benchmark Summary      ┃           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ Total Time (HEAD)      │ 1806.23ms │
│ Total Time (gene)      │ 1843.84ms │
│ Average Time (HEAD)    │   82.10ms │
│ Average Time (gene)    │   83.81ms │
│ Queries Faster         │         1 │
│ Queries Slower         │         3 │
│ Queries with No Change │        18 │
│ Queries with Failure   │         0 │
└────────────────────────┴───────────┘
```


</p>
</details>

**Comment by 2010YOUY01** [comment]
Everything looks resolved, let's merge it. Thank you everyone!

**Comment by alamb** [comment]
This one is so epic
