### PR TITLE
Fix clippy error on wasmtest

### LINKED ISSUE #12842: CI: Clippy error on `datafusion-wasmtest`
### Describe the bug

CI failed due to the following error

```
error: function `datafusion_test` is never used
  --> datafusion/wasmtest/src/lib.rs:91:8
   |
91 |     fn datafusion_test() {
   |        ^^^^^^^^^^^^^^^
   |
   = note: `-D dead-code` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(dead_code)]`

error: function `basic_execute` is never used
  --> datafusion/wasmtest/src/lib.rs:97:14
   |
97 |     async fn basic_execute() {
   |              ^^^^^^^^^^^^^

error: could not compile `datafusion-wasmtest` (lib test) due to 2 previous errors
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jonahgao**
## Which issue does this PR close?

Closes #12842.

## Rationale for this change
The new release of wasm-bindgen-test causes clippy to throw errors.
 PR fixed these errors and also verified locally that these tests can still run on Chrome.
```sh
running 2 tests

test datafusion_wasmtest::test::basic_execute ... ok
test datafusion_wasmtest::test::datafusion_test ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 filtered out
```

## Are these changes tested?
Yes

## Are there any user-facing changes?
No

### CODE REVIEW

File: datafusion/wasmtest/src/lib.rs [hunk 1]
```diff
@@ -87,13 +87,14 @@ mod test {
...
-    #[wasm_bindgen_test]
+    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test)]
+    #[cfg_attr(not(target_arch = "wasm32"), allow(dead_code))]
     fn datafusion_test() {
         basic_exprs();
         basic_parse();
     }
 
-    #[wasm_bindgen_test]
+    #[wasm_bindgen_test(unsupported = tokio::test)]
```
Comment (jonahgao) [inline datafusion/wasmtest/src/lib.rs:97]: According to the new feature of wasm_bindgen_test, run this test with `tokio::test` under non-wasm targets.

File: datafusion/wasmtest/src/lib.rs [hunk 2]
```diff
@@ -87,13 +87,14 @@ mod test {
 
     wasm_bindgen_test::wasm_bindgen_test_configure!(run_in_browser);
 
-    #[wasm_bindgen_test]
+    #[cfg_attr(target_arch = "wasm32", wasm_bindgen_test)]
+    #[cfg_attr(not(target_arch = "wasm32"), allow(dead_code))]
```
Comment (jonahgao) [inline datafusion/wasmtest/src/lib.rs:91]: This test can't run on non-wasm targets, so add `allow(dead_code)`.
```sh
thread 'test::datafusion_test' panicked at datafusion/wasmtest/src/lib.rs:41:1:
cannot call wasm-bindgen imported functions on non-wasm targets
```

**Review by alamb — APPROVED** [review]
Thank you @jonahgao
