### PR TITLE
fix: grouping with alias

### LINKED ISSUE #21411: ResolveGroupingFunction does not unwrap Alias nodes
### Describe the bug

The ResolveGroupingFunction analyzer rule does not recognize grouping() calls when they are wrapped in an Alias node. This means that grouping(col).alias("name") fails at physical planning with:

```
This feature is not implemented: physical plan is not yet implemented for GROUPING aggregate function
```

The same query succeeds when the grouping() expression is not aliased.

### To Reproduce

Using SQL this works correctly because the SQL planner applies the alias at a different stage:

```sql
SELECT a, SUM(b) AS s, GROUPING(a) AS g
FROM t
GROUP BY ROLLUP(a)
```

But when constructing the equivalent logical plan programmatically (e.g., via the DataFrame API), wrapping the `grouping()` expression in `Expr::Alias(...)` before passing it to `LogicalPlanBuilder::aggregate()` causes the `ResolveGroupingFunction` rule to skip it. The rule appears to pattern-match on `Expr::AggregateFunction` but does not recurse into `Expr::Alias(Alias { expr: Expr::AggregateFunction(...), .. })`.

This test should pass:

```rust
    #[tokio::test]
    async fn test_grouping_function_alias() -> Result<()> {
        let ctx = SessionContext::default();
        let rb = record_batch!(("a", Int32, [1, 1, 2]), ("b", Int32, [10, 20, 30]))?;
        let df = ctx.read_batch(rb)?;

        fn check_results(results: &Vec<RecordBatch>) {
            // We have no guarantee on ordering of the batches
            for result in results {
                let s_array = result.column(1).as_any().downcast_ref::<Int64Array>().unwrap();
                let expected_val = match s_array.value(0) {
                    30 => { 0 },
                    60 => { 1 },
                    _ => {
                        panic!("unexpected value {}", s_array.value(0)) }
                };
                let expected = create_array!(Int32, [expected_val]) as ArrayRef;
                assert_eq!(&expected, result.column(2));
            }
        }

        let results = df.clone().aggregate(vec![
            Expr::GroupingSet(GroupingSet::Rollup(vec![col("a")])),
        ], vec![
            sum(col("b")).alias("s"),
            grouping(col("a"))
        ])?.collect().await?;
        check_results(&results);


        let results = df.clone().aggregate(vec![
            Expr::GroupingSet(GroupingSet::Rollup(vec![col("a")])),
        ], vec![
            sum(col("b")).alias("s"),
            grouping(col("a")).alias("g")
        ])?.collect().await?;
        check_results(&results);
        
        Ok(())
    }
```

### Expected behavior

`grouping(col).alias("name")` should work identically to an unaliased grouping(col) — the analyzer should unwrap Alias nodes when searching for grouping() calls to rewrite.

### Additional context

The relevant rule is ResolveGroupingFunction in `datafusion/optimizer/src/analyzer/resolve_grouping_function.rs`. The fix likely involves matching on Expr::Alias(Alias { expr, .. }) and recursing into the inner expression, then re-wrapping the rewritten result in the alias.

### PR DESCRIPTION
**Pull request by timsaucer**
## Which issue does this PR close?

- Closes https://github.com/apache/datafusion/issues/21411

## Rationale for this change

When you have an alias on `grouping` function via dataframe API, you get an error. This resolves that error.

## What changes are included in this PR?

Check for alias expressions in optimizer.
Add unit tests.

## Are these changes tested?

Unit test added, including a note on why a SQL logic test will not cover this case.

## Are there any user-facing changes?

None

### CODE REVIEW

File: datafusion/core/tests/dataframe/mod.rs [hunk 1]
```diff
@@ -6852,3 +6852,50 @@ async fn test_duplicate_state_fields_for_dfschema_construct() -> Result<()> {
...
+/// grouping() should work when wrapped in an alias via the DataFrame API.
+///
+/// This bug only manifests through the DataFrame API because `.alias()` wraps
+/// the `grouping()` call in an `Expr::Alias` node at the aggregate expression
+/// level. The SQL planner handles aliasing separately (via projection), so the
+/// `ResolveGroupingFunction` analyzer rule never sees an `Expr::Alias` wrapper
+/// around the aggregate function in SQL queries — making SQL-based tests
+/// insufficient to cover this case.
+#[tokio::test]
+async fn test_grouping_with_alias() -> Result<()> {
```
Comment (adriangb) [inline datafusion/core/tests/dataframe/mod.rs:6865]: I confirmed this test fails on main.

**Review by adriangb — APPROVED** [review]
