### PR TITLE
fix: add an "expr_planners" method to SessionState

### LINKED ISSUE #15114: Regression: count(*) does not work unless using default expression planners
Previously, the count wildcard is expanded by the CountWildCard analyzer rule which however was removed in the latest release 46.0.  And the functionality is now moved to the ExprPlanner for planning aggregate functions, see #14689.

This functionality assumes users could get expression planners from the ContextProvider. See:
https://github.com/apache/datafusion/blob/dfaede0ba5c970a131117cb1c089bb338dc64fb3/datafusion/sql/src/expr/function.rs#L374-L379

It's ok for the DataFusion native context provider `SessionContextProvider` since it's able to retrieve expression planners from the SessionState. See: 
https://github.com/apache/datafusion/blob/dfaede0ba5c970a131117cb1c089bb338dc64fb3/datafusion/core/src/execution/session_state.rs#L1619-L1627

Unfortunately, user defined ContextProvider is unable to get expression planners from the SessionState, since the `expr_planners` field is not exposed.

As a result, users who wish to utilize the default expression planners must import the `FunctionRegistry` trait, which provides an `expr_planners` method, and notably, SessionState implements this trait. 

To address this issue, I propose adding a method to SessionState that returns a reference of the registered expression planners. This would provide a more straightforward and consistent way for user-defined ContextProvider implementations to access these planners without requiring importing the additional `FunctionRegistry` trait.

### PR DESCRIPTION
**Pull request by niebayes**
## Which issue does this PR close?

- Closes #15114 .

## Rationale for this change

This method makes it convenient for users to retrieve expression planners from SessionState. The details are explained in the corresponding issue.

## What changes are included in this PR?

Added an `expr_planners` to SessionState.

## Are these changes tested?

Covered by existing test cases.

## Are there any user-facing changes?

Yes, users now can use the `expr_planners` method to get registered expression planners, including default expression planners, from SessionState.

### CODE REVIEW

**Comment by alamb** [comment]
CI appears to be failing so marking as draft

File: datafusion/core/src/execution/context/mod.rs [hunk 1]
```diff
@@ -1632,7 +1632,7 @@ impl FunctionRegistry for SessionContext {
     }
 
     fn expr_planners(&self) -> Vec<Arc<dyn ExprPlanner>> {
-        self.state.read().expr_planners()
+        self.state.read().expr_planners().to_vec()
```
Comment (niebayes) [inline datafusion/core/src/execution/context/mod.rs:1635]: Previously, it's the `FunctionRegistry::expr_planners` method gets called and a vector of expression planners is returned.
Now, the `SessionState::expr_planners` takes precedence and a slice of expression planners is returned.

Comment (niebayes) [reply datafusion/core/src/execution/context/mod.rs:1635]: @alamb Fixed CI. PTAL

**Comment by niebayes** [comment]
@alamb I wonder if we can remove the `register_expr_planners` and `expr_planners` from the `FunctionRegistry` trait. I have checked the codebase and they're only used by a test. And it's kind of weird as these methods don’t seem to align with the core responsibility of the trait.

**Comment by alamb** [comment]
> @alamb I wonder if we can remove the `register_expr_planners` and `expr_planners` from the `FunctionRegistry` trait. I have checked the codebase and they're only used by a test. And it's kind of weird as these methods don’t seem to align with the core responsibility of the trait.

It seem reasonable to me -- maybe we could make a PR to deprecate them first ?

**Review by alamb — COMMENTED** [review]
Thanks @niebayes  -- can you please add a test a test for this fix

File: datafusion/core/src/execution/context/mod.rs (hunk 1 above)
Comment (alamb) [reply datafusion/core/src/execution/context/mod.rs:1635]: I don't understand how the code in this PR is any different than what is in on main

**Comment by niebayes** [comment]
@alamb Sure, I maybe write an example to demonstrate how why the newly added `expr_planners` method is helpful

**Comment by alamb** [comment]
> 
@alamb Sure, I maybe write an example to demonstrate how why the newly added expr_planners method is helpful


What I am thinking is "how will we ensure that we don't accidentally break this feature during future refactors"

As it stands now, we could potentially break the feature without any tests failing

Ideally we would have some test that fails so we would know to fix it

**Comment by alamb** [comment]
I plan to make a 46.0.1 release tomorrow
- https://github.com/apache/datafusion/issues/15151

Is this something we should include?

**Comment by niebayes** [comment]
@alamb Sorry for late response, Some emergent personal matters have caused a delay.

File: datafusion/core/src/execution/context/mod.rs (hunk 1 above)
Comment (Omega359) [reply datafusion/core/src/execution/context/mod.rs:1635]: I think it's ContextProvider that uses a slice vs Vec. Bit annoying the types are not aligned. SessionState uses `expr_planners: Vec<Arc<dyn ExprPlanner>>,`

Comment (niebayes) [reply datafusion/core/src/execution/context/mod.rs:1635]: @Omega359 I agree, it's better to align the types. I have made both return a slice.

File: datafusion/core/src/execution/session_state.rs [hunk 2]
```diff
@@ -1950,6 +1955,16 @@ mod tests {
...
+    use crate::{
+        common::assert_contains,
+        config::ConfigOptions,
+        datasource::{empty::EmptyTable, provider_as_source},
+        logical_expr::{
+            planner::ExprPlanner, AggregateUDF, ScalarUDF, TableSource, WindowUDF,
+        },
+        physical_plan::ExecutionPlan,
+        sql::{planner::ContextProvider, ResolvedTableReference, TableReference},
+    };
```
[the remark this answers is not in the document]
Comment (niebayes) [reply datafusion/core/src/execution/session_state.rs:1967]: @Omega359 I have flatten all imports.

**Review by alamb — APPROVED** [review]
Thank you @niebayes  -- I am sorry this PR got lost. It seems like a reasonable change to me
