### PR TITLE
fix : correct nullability propagation for spark.bitwise_not

### LINKED ISSUE #19150: spark `bitwise_not` need to have custom nullability
### Describe the bug

the UDF uses the default `is_nullable` which is always true which is not the case

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shifluxxc**
## Which issue does this PR close?

- Closes #19150.

## Rationale for this change

The Spark `bitwise_not` UDF always appeared as **nullable** in logical plans, even when its input column was **non-nullable**.

This happened because the UDF implemented only `return_type()`, which returns a `DataType` but **does not propagate nullability**.  
DataFusion requires UDFs to implement `return_field_from_args()` when nullability depends on input fields.

As a result:

- `bitwise_not(non_nullable_col)` incorrectly produced a **nullable** output.
- Downstream query planning and schema inference became inconsistent.
- This differed from both **Spark semantics** and **Arrow kernel behavior**, where nullability is preserved.

This PR corrects the nullability inference.

## What changes are included in this PR?

- Implemented `return_field_from_args()` for the Spark `bitwise_not` UDF.
  - Output type = input type  
  - Output nullability = input nullability  
- Updated `return_type()` to return an error, per DataFusion API guidelines when overriding nullability.
- Added unit tests verifying:
  - Non-nullable input → non-nullable output  
  - Nullable input → nullable output  
  - Behavior across multiple integer types (`Int32`, `Int64`)
- Code comments and minor cleanup.

## Are these changes tested?

Yes.

This PR includes new unit tests that validate:

- correct nullability propagation
- correct output types  
- consistent behavior across supported integer types

## Are there any user-facing changes?

Yes, but they are **behavior-correcting**, not breaking:

- The `spark.bitwise_not` UDF now correctly reports nullability in schemas and logical plans.
- No API changes.
- No behavioral change for actual runtime values — Arrow kernels already preserved null bitmaps; only planner metadata was incorrect.

This is not considered a breaking change.

### CODE REVIEW

**Review by rluvaton — APPROVED** [review]
I verified that spark bitwise not nullability are depending on the children:

`BitwiseNot`:
https://github.com/apache/spark/blob/a189a450e9906362749e3ad3d022f593a2a562e4/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/bitwiseExpressions.scala#L172-L214

`UnaryExpression`:
https://github.com/apache/spark/blob/a189a450e9906362749e3ad3d022f593a2a562e4/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/Expression.scala#L590

File: datafusion/spark/src/function/bitwise/bitwise_not.rs [hunk 1]
```diff
@@ -64,8 +66,21 @@ impl ScalarUDFImpl for SparkBitwiseNot {
...
+        if args.arg_fields.len() != 1 {
+            return plan_err!("bitwise_not expects exactly 1 argument");
+        }
+
+        let input_field = &args.arg_fields[0];
+
+        let out_dt = input_field.data_type().clone();
+        let out_nullable = input_field.is_nullable();
+
+        Ok(Arc::new(Field::new("bitwise_not", out_dt, out_nullable)))
```
Comment (martin-g) [inline datafusion/spark/src/function/bitwise/bitwise_not.rs]:
```suggestion
        Ok(Arc::new(Field::new(self.name(), out_dt, out_nullable)))
```

File: datafusion/spark/src/function/bitwise/bitwise_not.rs [hunk 2]
```diff
@@ -64,8 +66,21 @@ impl ScalarUDFImpl for SparkBitwiseNot {
         &self.signature
     }
 
-    fn return_type(&self, arg_types: &[DataType]) -> Result<DataType> {
-        Ok(arg_types[0].clone())
+    fn return_type(&self, _arg_types: &[DataType]) -> Result<DataType> {
+        plan_err!("SparkBitwiseNot: return_type() is not used; return_field_from_args() is implemented")
```
Comment (martin-g) [inline datafusion/spark/src/function/bitwise/bitwise_not.rs]:
```suggestion
        internal_err!("SparkBitwiseNot: return_type() is not used; return_field_from_args() is implemented")
```
The other similar functions use `internal_err!()`

**Comment by shifluxxc** [comment]
@martin-g please review .

File: datafusion/spark/src/function/bitwise/bitwise_not.rs [hunk 3]
```diff
@@ -64,8 +66,21 @@ impl ScalarUDFImpl for SparkBitwiseNot {
...
+
+    fn return_field_from_args(&self, args: ReturnFieldArgs) -> Result<FieldRef> {
+        if args.arg_fields.len() != 1 {
+            return plan_err!("bitwise_not expects exactly 1 argument");
+        }
+
+        let input_field = &args.arg_fields[0];
+
+        let out_dt = input_field.data_type().clone();
+        let out_nullable = input_field.is_nullable();
```
Comment (martin-g) [inline datafusion/spark/src/function/bitwise/bitwise_not.rs]: You should also check for scalar None.
See https://github.com/apache/datafusion/pull/19242/changes#diff-cd6bd8d074f37d2c7815016e857791d6f9cb81f981110a218e59d9bd3b27f6d4R89-R94

And add a test case similar to https://github.com/apache/datafusion/pull/19242/changes#diff-cd6bd8d074f37d2c7815016e857791d6f9cb81f981110a218e59d9bd3b27f6d4R174-R181

Comment (shifluxxc) [reply datafusion/spark/src/function/bitwise/bitwise_not.rs]: I have added the test case and made the change as instructed , please review @martin-g .

**Review by martin-g — APPROVED** [review]

**Comment by alamb** [comment]
I am trying to clear out the merge queue so I took the liberty of merging up from main and resolving a clippy issue

**Comment by alamb** [comment]
Thanks @shifluxxc @rluvaton and @martin-g
