### PR TITLE
Fix Subtraction overflow in `max_distinct_count` when hash join has a pushed-down limit

### LINKED ISSUE #20779: Subtraction overflow in `max_distinct_count` when hash join has a pushed-down limit
### Describe the bug

`max_distinct_count` in `datafusion/physical-plan/src/joins/utils.rs` panics with "attempt to subtract with overflow" in the `Precision::Exact` branch (line 725):

```rust
Precision::Exact(count) => {
    let count = count - stats.null_count.get_value().unwrap_or(&0); // <-- panic
```

This happens when `num_rows` (Exact) is smaller than `null_count`, which became possible after #20228, which added `fetch` support to `HashJoinExec`. When a limit is pushed down, `HashJoinExec::partition_statistics()` calls `stats.with_fetch(self.fetch, 0, 1)`, which reduces `num_rows` to `Exact(fetch_value)` but does not reduce `null_count` in column statistics.

Example failing pipeline:
https://github.com/datafusion-contrib/datafusion-distributed/actions/runs/22798285744/job/66136064932?pr=366

### To Reproduce

```
git clone https://github.com/datafusion-contrib/datafusion-distributed
cd datafusion-distributed
git checkout branch-53
cargo test --test tpcds_plans_test tests::test_tpcds_19 --all-features
```

### Expected behavior

No substraction overflow

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by KARTIK64-rgb**
## Which issue does this PR close?

- Closes #20779.

## Rationale for this change

In `max_distinct_count` (inside `datafusion/physical-plan/src/joins/utils.rs`), the
`Precision::Exact` branch computes the number of non-null rows by doing:

```rust
let count = count - stats.null_count.get_value().unwrap_or(&0);
```

Before #20228 this subtraction was always safe because `num_rows` was never smaller
than `null_count`. But #20228 added `fetch` (limit push-down) support to
`HashJoinExec`, and when a limit is applied, `partition_statistics()` caps
`num_rows` to `Exact(fetch_value)` without also capping the per-column
`null_count`. This means `null_count` can legally exceed `num_rows`, causing a
panic with *"attempt to subtract with overflow"*.

## What changes are included in this PR?

- **Bug fix** in `max_distinct_count` (`utils.rs` ~line 725): replaced the bare
  subtraction with a saturating subtraction so that when `null_count` exceeds
  `num_rows` the result is clamped to `0` instead of panicking.

  ```rust
  // Before
  let count = count - stats.null_count.get_value().unwrap_or(&0);

  // After
  let count = count.saturating_sub(*stats.null_count.get_value().unwrap_or(&0));
  ```

- **Regression test** added at the bottom of the `mod tests` block in the same
  file. The test deliberately constructs a scenario where `null_count (5) >
  num_rows (2)` and asserts that `max_distinct_count` returns `Exact(0)` without
  panicking.

## Are these changes tested?

Yes. A new unit test
`test_max_distinct_count_no_overflow_when_null_count_exceeds_num_rows` is added
directly in `datafusion/physical-plan/src/joins/utils.rs`. It covers the exact
edge-case from the bug report (null_count > num_rows after a fetch/limit
push-down) and would have caught the panic before the fix.

## Are there any user-facing changes?

No user-facing or API changes. This is a purely internal arithmetic fix in the
statistics estimation logic. Queries that previously panicked when a limit was
pushed down into a `HashJoinExec` will now complete successfully.

### CODE REVIEW

**Comment by jonathanc-n** [comment]
cc @gabotechs

File: datafusion/physical-plan/src/joins/utils.rs [hunk 1]
```diff
@@ -2939,4 +2940,19 @@ mod tests {
 
         Ok(())
     }
-}
+    #[test]
```
Comment (jonathanc-n) [inline datafusion/physical-plan/src/joins/utils.rs:2944]: I created a test for this for `sqllogictest`s  @KARTIK64-rgb, can add:

```
statement ok
CREATE TABLE t1(a INT, b INT) AS VALUES 
  (NULL, 1), (NULL, 2), (NULL, 3), (NULL, 4), (NULL, 5);

statement ok
CREATE TABLE t2(c INT) AS VALUES (1), (2);

# This query panicked before the fix: the ORDER BY forces a SortExec,
# the LIMIT gets pushed into SortExec.fetch, and the HashJoinExec
# calls partition_statistics() on the SortExec child during execution.
query II
SELECT sub.a, sub.b FROM (
  SELECT * FROM t1 ORDER BY b LIMIT 1
) sub 
JOIN t2 ON sub.a = t2.c;
----

statement ok
DROP TABLE t1;

statement ok
DROP TABLE t2;
```

i verified it reproduces the bug

File: datafusion/physical-plan/src/joins/utils.rs [hunk 2]
```diff
@@ -721,12 +721,13 @@ fn max_distinct_count(
                         Some(non_null_count) => Precision::Inexact(non_null_count),
                     }
                 }
-                Precision::Exact(count) => {
-                    let count = count - stats.null_count.get_value().unwrap_or(&0);
+                    Precision::Exact(count) => {
+                    let null_count = *stats.null_count.get_value().unwrap_or(&0);
+                    let non_null_count = count.checked_sub(null_count).unwrap_or(0);
```
Comment (gabotechs) [inline datafusion/physical-plan/src/joins/utils.rs:726]: 👍 nice, even if this is a good safeguard, the fact that this can even happen makes me think that there is some further work to be done in the stats propagation mechanism.

Ideally, this would not even be possible by construction, but that's a topic for another PR.

Comment (KARTIK64-rgb) [reply datafusion/physical-plan/src/joins/utils.rs:726]: Welcome @gabotechs @jonathanc-n !

**Comment by alamb** [comment]
@KARTIK64-rgb can you help fix the CI tests on this PR?

**Comment by alamb** [comment]
I pushed a commit to try and resolve the build error

**Comment by gabotechs** [comment]
Should be good now, in it goes. Thanks @KARTIK64-rgb for the PR, @jonathanc-n for the review and @alamb for fixing the build error.

**Comment by alamb** [comment]
woohoo -- progress every day

**Comment by KARTIK64-rgb** [comment]
Thanks @alamb for solving the ci-issues.
thanks @jonathanc-n @gabotechs  for guiding me .

**Comment by alamb** [comment]
> Thanks @alamb for solving the ci-issues. thanks @jonathanc-n @gabotechs for guiding me .

Go team!
