### PR TITLE
Prevent overflow and panics when casting DATE to TIMESTAMP by validating bounds

### LINKED ISSUE #17534: Panic when cast from `DATE` to `TIMESTAMP` overflows
### Describe the bug

Casting a date to timestamp involves multiplication and may overflow.
DataFusion should report query error in such case, rather than panicking.

### To Reproduce

```shell
cargo run --bin datafusion-cli -- --command "SELECT CAST(DATE '9999-12-31' As timestamp);"
```

```
datafusion main$ cargo run --bin datafusion-cli -- --command "SELECT CAST(DATE '9999-12-31' As timestamp);"
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.18s
     Running `target/debug/datafusion-cli --command 'SELECT CAST(DATE '\''9999-12-31'\'' As timestamp);'`
DataFusion CLI v50.0.0

thread 'main' panicked at /Users/findepi/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arrow-cast-56.0.0/src/cast/mod.rs:1881:58:
attempt to multiply with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected behavior

- query error informing about overflow

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kosiew**
## Which issue does this PR close?

* Closes #17534.

## Rationale for this change

This change ensures that casting from `Date32` or `Date64` to timestamp types behaves safely and predictably. Previously, extreme date values (e.g., `9999-12-31`) could cause integer overflow during unit conversion, leading to panics in debug mode and silent incorrect results in release mode. This patch introduces explicit bounds checking so these cases return clear, user-facing errors instead of panicking.

### Before
```
❯ cargo run --bin datafusion-cli -- --command "SELECT CAST(DATE '9999-12-31' As timestamp);"
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.48s
     Running `target/debug/datafusion-cli --command 'SELECT CAST(DATE '\''9999-12-31'\'' As timestamp);'`
DataFusion CLI v51.0.0

thread 'main' panicked at /Users/kosiew/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/arrow-cast-57.0.0/src/cast/mod.rs:2079:58:
attempt to multiply with overflow

```
### After
```
❯ cargo run --bin datafusion-cli -- --command "SELECT CAST(DATE '9999-12-31' As timestamp);"
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.64s
     Running `target/debug/datafusion-cli --command 'SELECT CAST(DATE '\''9999-12-31'\'' As timestamp);'`
DataFusion CLI v51.0.0
Error: Optimizer rule 'simplify_expressions' failed
caused by
Execution error: Cannot cast Date32 value 2932896 to Timestamp(ns): timestamp values are limited to +/-2262 years
```

## What changes are included in this PR?

* Introduces `date_to_timestamp_multiplier` and `ensure_timestamp_in_bounds` to centralize safe conversion logic.
* Adds bounds validation for both scalar and array-based casts, preventing overflow when multiplying date values.
* Enhances error messages with consistent timestamp type formatting.
* Integrates bounds checks into `ScalarValue::cast_to` and `ColumnarValue::cast_to`.
* Adds comprehensive tests covering formatting, overflow detection, scalar casts, array casts, and SQL-level behavior.

## Are these changes tested?

Yes. The PR includes new unit tests validating:

* Formatting of timestamp types in error messages.
* Overflow detection for both `Date32` and `Date64` to nanoseconds.
* Array-based overflow handling.
* SQL-level behavior for casting large date literals.

## Are there any user-facing changes?

Yes. Users now receive clear and consistent error messages when attempting to cast dates that exceed the representable timestamp range (approximately ±2262 years). Instead of panics or silent overflow, a descriptive execution error is returned.

## LLM-generated code disclosure

This pull request includes LLM-generated content that has been manually reviewed and tested.

### CODE REVIEW

File: datafusion/expr-common/src/columnar_value.rs [hunk 1]
```diff
@@ -275,16 +282,69 @@ impl ColumnarValue {
...
+                        array.data_type()
+                    )
+                })?;
+            Box::new(arr.iter().flatten())
+        }
+        _ => return Ok(()), // Not a date type, nothing to do
+    };
+
+    for value in iter {
+        ensure_timestamp_in_bounds(value, multiplier, &source_type, cast_type)?;
```
Comment (martin-g) [inline datafusion/expr-common/src/columnar_value.rs]: Could this be done more effectively with the `compute::max()/min()` kernels instead of iterating over all items ?!

File: datafusion/common/src/scalar/mod.rs [hunk 2]
```diff
@@ -91,6 +91,99 @@ use chrono::{Duration, NaiveDate};
...
+            TimeUnit::Nanosecond => NANOS_PER_DAY,
+        }),
+
+        // Date64 stores milliseconds since epoch. Converting to
+        // seconds is a division (no multiplication), so return `None`.
+        // Converting to milliseconds is 1:1 (multiplier 1). Converting
+        // to micro/nano requires multiplying by 1_000 / 1_000_000.
+        DataType::Date64 => match target_unit {
+            TimeUnit::Second => None,
+            TimeUnit::Millisecond => Some(1),
```
Comment (martin-g) [inline datafusion/common/src/scalar/mod.rs]: Is it necessary to multiply/divide by 1 at all ? I.e. maybe this should return a None ?!

File: datafusion/common/src/scalar/mod.rs [hunk 3]
```diff
@@ -91,6 +91,99 @@ use chrono::{Duration, NaiveDate};
...
+    target_type: &DataType,
+) -> Result<()> {
+    if multiplier <= 1 {
+        return Ok(());
+    }
+
+    if value.checked_mul(multiplier).is_none() {
+        let target = format_timestamp_type_for_error(target_type);
+        _exec_err!(
+            "Cannot cast {} value {} to {}: timestamp values are limited to +/-2262 years",
```
Comment (martin-g) [inline datafusion/common/src/scalar/mod.rs]: +/-2262 is true if the target type is nanoseconds, no ? For seconds/milli/micro the limit years would be a bigger number.
Maybe:
```suggestion
            "Cannot cast {} value {} to {}: converted value exceeds the representable i64 range",
```

File: datafusion/common/src/scalar/mod.rs (hunk 2 above)
Comment (kosiew) [reply datafusion/common/src/scalar/mod.rs]: None -> no op
wil amend accordingly.

File: datafusion/expr-common/src/columnar_value.rs (hunk 1 above)
Comment (kosiew) [reply datafusion/expr-common/src/columnar_value.rs]: Good idea — we should only need to check extremes.
Will amend accordingly.

File: datafusion/common/src/scalar/mod.rs (hunk 3 above)
Comment (kosiew) [reply datafusion/common/src/scalar/mod.rs]: Good catch.
Will amend accordingly.

**Comment by kosiew** [comment]
@martin-g 
Thank you for your review and feedback

**Review by adriangb — APPROVED** [review]

**Review by adriangb — APPROVED** [review]

**Comment by adriangb** [comment]
Thanks @kosiew !

**Comment by kosiew** [comment]
@adriangb 
Thanks for your review!
