### PR TITLE
Use arrow IPC Stream format for spill files

### LINKED ISSUE #4658: ExternalSorter Fails to Spill Dictionaries
**Describe the bug**

ExternalSorter currently spills data using the Arrow IPC format, unfortunately the IPC file format does not support replacing a dictionary with the same ID. Consequently if `ExternalSorter` spills two batches with dictionary encoded columns, it will error with

```
Dictionary replacement detected when writing IPC file format. Arrow IPC files only support a single dictionary for a given field across all batches
```

**To Reproduce**

**Expected behavior**

Various options present themselves:

* Number the dictionary IDs consistently across DataFusion (a monumental task)
* Write batches to separate files
* Spill to the row format instead of Arrow IPC

Of these I think the last is the most compelling, I plan to work on this in the coming month

**Additional context**

It is possible Ballista also runs into this issue

### PR DESCRIPTION
**Pull request by davidhewitt**
## Which issue does this PR close?

- Closes #4658

## Rationale for this change

The IPC Stream format allows for dictionary replacement, unlike the IPC File format. As per https://github.com/apache/datafusion/issues/4658#issuecomment-2679417596 the File format does not offer advantages for the spill use case.

## What changes are included in this PR?

Replaced the functionality in spilled sorts to write the IPC Stream format, instead of the IPC File format.

## Are these changes tested?

Covered by existing tests of spill, I adapted these where necessary.

## Are there any user-facing changes?

The code change is internal only; if for some reason users were inspecting the contents of spilled files without using the datafusion APIs to read them, they will find the format has changed.

### CODE REVIEW

**Comment by comphead** [comment]
Wondering if this PR also addresses partially https://github.com/apache/datafusion/issues/14078

Another thing to mention we still lack some spilling test cases like https://github.com/apache/datafusion/issues/11541

File: datafusion/physical-plan/src/spill.rs [hunk 1]
```diff
@@ -59,13 +58,13 @@ pub(crate) fn read_spill_as_stream(
 ///
 /// Returns total number of the rows spilled to disk.
 pub(crate) fn spill_record_batches(
-    batches: Vec<RecordBatch>,
+    batches: &[RecordBatch],
```
Comment (2010YOUY01) [inline datafusion/physical-plan/src/spill.rs:61]: I understand that it's better, however, we might prefer public API stability and avoid this change, unless there is noticeable overhead.

**Review by 2010YOUY01 — COMMENTED** [review]
Thank you for the nice work. I think it's ready to go after the regression test is added.

File: datafusion/physical-plan/src/sorts/sort.rs [hunk 2]
```diff
@@ -439,36 +440,35 @@ impl ExternalSorter {
         // `self.in_mem_batches` is already taken away by the sort_stream, now it is empty.
         // We'll gradually collect the sorted stream into self.in_mem_batches, or directly
         // write sorted batches to disk when the memory is insufficient.
-        let mut spill_writer: Option<IPCWriter> = None;
+        let mut spill_writer: Option<IPCStreamWriter> = None;
```
[the remark this answers is not in the document]
Comment (davidhewitt) [reply datafusion/physical-plan/src/sorts/sort.rs:443]: 👍 I'll rebase on this now, thanks.

**Comment by davidhewitt** [comment]
Rebased on main & test pushed 👍

File: datafusion/physical-plan/src/spill.rs [hunk 3]
```diff
@@ -214,18 +260,85 @@ mod tests {
...
         assert_eq!(reader.schema(), schema);
 
+        let batches = reader.collect_vec();
+        assert!(batches.len() == 2);
+
+        Ok(())
+    }
+
+    #[test]
+    fn test_batch_spill_and_read_dictionary_arrays() -> Result<()> {
```
Comment (davidhewitt) [inline datafusion/physical-plan/src/spill.rs:281]: I confirmed that this test fails on main with the error in #4658

File: datafusion/physical-plan/src/spill.rs (hunk 1 above)
Comment (2010YOUY01) [reply datafusion/physical-plan/src/spill.rs:61]: Oops I didn't notice `(crate)`, you're right.

**Comment by comphead** [comment]
Thanks @davidhewitt I think this PR is good, please check the clippy

**Review by comphead — APPROVED** [review]
thanks @davidhewitt it is a really nice first contribution

**Comment by davidhewitt** [comment]
Thanks! `clippy` should be happy now... 🤞

**Comment by comphead** [comment]
Thanks @davidhewitt I let the PR some time for other approvers since this is a first contribution. I do not see any objections and planning to merge this PR, thanks again
