### PR TITLE
fix: shuffle seed

### LINKED ISSUE #18476: [datafusion-cli] `shuffle.slt` Intermittent CI failure for `SELECT shuffle([1, 2, 3, 4, 5, NULL]) != [1, 2, 3, 4, 5, NULL];`
### Describe the bug

A test in shuffle.slt fails  intermittently but passes on rerun

### To Reproduce

Here is an example:

https://github.com/apache/datafusion/actions/runs/19022758025/job/54320962649

```
     Running bin/sqllogictests.rs (target/ci/deps/sqllogictests-3c0c5297e9072553)
External error: 1 errors in file /__w/datafusion/datafusion/datafusion/sqllogictest/test_files/spark/array/shuffle.slt

1. query result mismatch:
[SQL] SELECT shuffle([1, 2, 3, 4, 5, NULL]) != [1, 2, 3, 4, 5, NULL];
[Diff] (-expected|+actual)
-   true
+   false
at /__w/datafusion/datafusion/datafusion/sqllogictest/test_files/spark/array/shuffle.slt:24
```

### Expected behavior

Test should always pass

### Additional context

I suspect the issue is that in very rare occasions the two calls to shuffle result in the exact same output

### PR DESCRIPTION
**Pull request by chenkovsky**
## Which issue does this PR close?

- Closes #18476.

## Rationale for this change

shuffle test sometimes fails

## What changes are included in this PR?

add seed to shuffle, make sure slt won't fail.

## Are these changes tested?

UT

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/spark/src/function/array/shuffle.rs [hunk 1]
```diff
@@ -47,7 +49,7 @@ impl Default for SparkShuffle {
 impl SparkShuffle {
     pub fn new() -> Self {
         Self {
-            signature: Signature::arrays(1, None, Volatility::Volatile),
+            signature: Signature::user_defined(Volatility::Volatile),
```
Comment (Jefffrey) [inline datafusion/spark/src/function/array/shuffle.rs]: We should avoid using user_defined and make use of `TypeSignature::ArraySignature`, for example:

https://github.com/apache/datafusion/blob/7591919be7e6582ed7f6a8d0b033f7a0a8ad60f7/datafusion/expr-common/src/signature.rs#L1247-L1262

- Index can be used as seed since it is Int64 type
- We can't use `Signature::array_and_index` directly since that would coerce FixedSizeLists to List arrays, which we don't want since we have a native implementation for FixedSizeLists
- Ensure there is support for both array only, and array + seed

File: datafusion/sqllogictest/test_files/spark/array/shuffle.slt [hunk 2]
```diff
@@ -22,7 +22,7 @@ SELECT array_sort(shuffle([1, 2, 3, 4, 5, NULL])) = [NULL,1, 2, 3, 4, 5];
 true
 
 query B
-SELECT shuffle([1, 2, 3, 4, 5, NULL]) != [1, 2, 3, 4, 5, NULL];
+SELECT shuffle([1, 2, 3, 4, 5, NULL], 1) != [1, 2, 3, 4, 5, NULL];
 ----
 true
```
Comment (Jefffrey) [inline datafusion/sqllogictest/test_files/spark/array/shuffle.slt]: We can just assert the output list instead of it being an inequality with its sorted version now, e.g.

```sql
query ?
SELECT shuffle([1, 2, 3, 4, 5, NULL], 1);
----
[2, 5, NULL, 3, 4, 1]
```

File: datafusion/spark/src/function/array/shuffle.rs [hunk 3]
```diff
@@ -66,32 +68,108 @@ impl ScalarUDFImpl for SparkShuffle {
     }
 
     fn return_type(&self, arg_types: &[DataType]) -> Result<DataType> {
+        if arg_types.is_empty() {
+            return plan_err!("shuffle expects at least 1 argument");
+        }
```
Comment (Jefffrey) [inline datafusion/spark/src/function/array/shuffle.rs]:
```suggestion
```

We don't need this check
