### PR TITLE
Ensure Substrait consumer can handle expressions in VirtualTable

### LINKED ISSUE #16363: Ensure Substrait consumer can handle expressions in VirtualTable
### Describe the bug

When we convert a Substrait plan (which includes a virtual table) to a DataFusion LogicalPlan using the `from_substrait_plan()` [function](https://github.com/apache/datafusion/blob/3a312a9976432e705f69ab6b6be2f49889eeb89b/datafusion/substrait/src/logical_plan/consumer/plan.rs#L28), the [function](https://github.com/apache/datafusion/blob/3a312a9976432e705f69ab6b6be2f49889eeb89b/datafusion/substrait/src/logical_plan/consumer/rel/read_rel.rs#L39) `from_read_rel()` is called for the virtual table read. In this function, if the `values` field in the provided `VirtualTable` struct is empty, the read returns an empty relation. However, the `values` field of `VirtualTable` is [deprecated](https://github.com/substrait-io/substrait/blob/d430e521f203aec6a4e06731d4bfd68cdf61f443/proto/substrait/algebra.proto#L150) and the `expressions` field of `VirtualTable` should be used to specify rows of a table; this function returns an empty table prematurely, when `expressions` is non-empty.

Returns `EmptyRelation` if `values` is empty:

Image
`expressions` should be supported in addition to the deprecated field `values`:

Image

### To Reproduce

1. Build a Substrait plan with expressions in embedded virtual table.
* Here's a snippet of a Substrait plan in YAML format with a virtual table that has `expressions` but no `values`.
Image
3. Convert the Substrait plan to a DataFusion `LogicalPlan` and execute the query.
4. Observe that the result has 0 rows.

### Expected behavior

`from_read_rel()` should not return an empty relation and there should be rows in the outputted table.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lorenarosati**
## Which issue does this PR close?

- Closes #16363.

## Rationale for this change

Virtual tables in Substrait can have either literal values or expressions, and currently, the Substrait consumer only handles the case when values are provided ([values is a deprecated field](https://github.com/substrait-io/substrait/blob/793c64ba26e337c22f5e91b658be58b1eea7efd3/proto/substrait/algebra.proto#L152)). If there are no values provided, an empty relation is returned, even if the virtual table has expressions specified.

If expressions are provided as elements in a virtual table (rather than literal values), from_read_rel() should return a LogicalPlan with the virtual table elements rather than an empty relation.

## What changes are included in this PR?

- Only returns an empty relation if there are no values _and_ no expressions specified.
- If expressions is non-empty, we iterate through the records and consume each expression; if expressions is empty, we fallback to iterate through the records and consume each literal.

## Are these changes tested?

Yes, a test was added that takes a Substrait plan which has expressions as elements in a virtual table, and checks that the resulting plan is correct (and does not have an empty relation).

## Are there any user-facing changes?

These changes will allow users to specify expressions in Substrait virtual tables, and get a result from their query.

### CODE REVIEW

File: datafusion/substrait/src/logical_plan/consumer/rel/read_rel.rs [hunk 1]
```diff
@@ -114,14 +114,37 @@ pub async fn from_read_rel(
...
+                    if name_idx != named_struct.names.len() {
+                        return substrait_err!(
+                                "Names list must match exactly to nested schema, but found {} uses for {} names",
+                                name_idx,
+                                named_struct.names.len()
+                            );
+                    }
+                    exprs.push(row_exprs);
+                }
+                exprs
```
Comment (vbarua) [inline datafusion/substrait/src/logical_plan/consumer/rel/read_rel.rs:145]: This does introduce a bit of duplication with the block below, but given that `consume_expression` is async and `from_substrait_literal` is not it would be a bit tricky to unify the processing. In the long-term Substrait drop support for the `values` field which is deprecated so we'll be able to remove the lower block entirely.

File: datafusion/substrait/src/logical_plan/consumer/rel/read_rel.rs [hunk 2]
```diff
@@ -114,14 +114,37 @@ pub async fn from_read_rel(
...
-            if vt.values.is_empty() {
+            if vt.values.is_empty() && vt.expressions.is_empty() {
                 return Ok(LogicalPlan::EmptyRelation(EmptyRelation {
                     produce_one_row: false,
                     schema: DFSchemaRef::new(substrait_schema),
                 }));
             }
 
-            let values = vt
+            let values = if vt.values.is_empty() {
```
Comment (vbarua) [inline datafusion/substrait/src/logical_plan/consumer/rel/read_rel.rs]: minor: I would suggest checking `!vt.expressions.is_empty()` to make it clearer that `expressions` are preferred over values. Effectively, it's the difference between "We are processing expressions because there are no values" as opposed to "We are processing expressions because they are present".

File: datafusion/substrait/tests/testdata/test_plans/select_count_from_select_1_virtual_table_expressions.substrait.json [hunk 3]
```diff
@@ -0,0 +1,94 @@
+{
```
Comment (vbarua) [inline datafusion/substrait/tests/testdata/test_plans/select_count_from_select_1_virtual_table_expressions.substrait.json]: minor: I would suggest we update the name to something like  `virtual_table_with_expressions.substrait.json` which more accurately reflects what this plan is intended to verify.

File: datafusion/substrait/tests/testdata/test_plans/select_count_from_select_1_virtual_table_expressions.substrait.json [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+      {
+        "root": {
+          "input": {
+            "aggregate": {
+              "common": {
+                "direct": {
+                }
+              },
+              "input": {
+                "read": {
```
Comment (vbarua) [inline datafusion/substrait/tests/testdata/test_plans/select_count_from_select_1_virtual_table_expressions.substrait.json]: minor: I would suggest of getting rid of everything other than the `read` in this plan, to make it clearer that this is a test of virtual table functionality. The aggregation in this plan is effectively noise.

File: datafusion/substrait/tests/testdata/test_plans/select_count_from_select_1_virtual_table_expressions.substrait.json [hunk 5]
```diff
@@ -0,0 +1,94 @@
...
+                      {
+                        "fields": [
+                            {
+                                "literal": {
+                                    "i64": "0",
+                                    "nullable": false
+                                }
+                            }
+                        ]
+                      }
```
Comment (vbarua) [inline datafusion/substrait/tests/testdata/test_plans/select_count_from_select_1_virtual_table_expressions.substrait.json]: To make this a slighly more robust test, I would suggest:
* Using a struct with more than 1 field to verify the name processing is applied correctly.
* Having more than 1 row to check that multiple rows can be processed.

**Review by vbarua — APPROVED** [review]
Left some minor comments, but overall this looks good to me. Thanks for fixing this ✨

File: datafusion/substrait/src/logical_plan/consumer/rel/read_rel.rs (hunk 2 above)
Comment (lorenarosati) [reply datafusion/substrait/src/logical_plan/consumer/rel/read_rel.rs]: Made this change!

File: datafusion/substrait/tests/testdata/test_plans/select_count_from_select_1_virtual_table_expressions.substrait.json (hunk 3 above)
Comment (lorenarosati) [reply datafusion/substrait/tests/testdata/test_plans/select_count_from_select_1_virtual_table_expressions.substrait.json]: Made this change!

File: datafusion/substrait/tests/testdata/test_plans/select_count_from_select_1_virtual_table_expressions.substrait.json (hunk 5 above)
Comment (lorenarosati) [reply datafusion/substrait/tests/testdata/test_plans/select_count_from_select_1_virtual_table_expressions.substrait.json]: Made this change!

**Comment by alamb** [comment]
I will plan to merge tomorrow so there is some additional time for other reviewers if they want

File: datafusion/substrait/src/logical_plan/consumer/rel/read_rel.rs [hunk 6]
```diff
@@ -114,14 +114,37 @@ pub async fn from_read_rel(
...
-            let values = vt
+            let values = if !vt.expressions.is_empty() {
+                let mut exprs = vec![];
+                for row in &vt.expressions {
+                    let mut name_idx = 0;
+                    let mut row_exprs = vec![];
+                    for expression in &row.fields {
+                        name_idx += 1;
+                        let expr = consumer
+                            .consume_expression(expression, &substrait_schema)
```
Comment (vbarua) [inline datafusion/substrait/src/logical_plan/consumer/rel/read_rel.rs]: Actually, we should be using an empty schema here. The `substrait_schema` we have access to here is the schema of the ReadRel. The expressions in the VirtualTable cannot reference that schema, or any schema at all.

**Comment by vbarua** [comment]
> I will plan to merge tomorrow so there is some additional time for other reviewers if they want

Sounds good. I actually just though of something to update in this PR as well 😅

File: datafusion/substrait/src/logical_plan/consumer/rel/read_rel.rs (hunk 6 above)
Comment (lorenarosati) [reply datafusion/substrait/src/logical_plan/consumer/rel/read_rel.rs]: Made this change!

**Review by vbarua — APPROVED** [review]
Thanks for updating this @lorenarosati. Now this should really be good to merge 😅

**Comment by alamb** [comment]
Thanks @lorenarosati and @vbarua
