### PR TITLE
fix: join swap for projected semi/anti joins

### LINKED ISSUE #10978: Inconsistent behavior in HashJoin Projections
### Describe the bug

We ran into problems with projections inside HashJoin. 

Each schema in the join (left / right) has:

* a single struct column 
* and the join column (reference to a get_field inside the first column)

The projection is `[0, 2]` - the struct column from left, and the struct column from right

The join column is not specified in the output. When trying to optimize the join and reverse the order, the projection is swapped as `[2, 0]`, however there is no column with index 2 in the output, as the output contains only the 2 structs

### To Reproduce

* Create two schemas with a single struct column `(key, value)`
* Join on the `key`
* request the two `value` fields

### Expected behavior

The hash join optimization works, even when swapping the join order (and wrapping in a ProjectionExec)

### Additional context

Reading the [comment for HashJoinExec::projection](https://github.com/apache/datafusion/blob/ac161bba336d098eab46f666af4664de7e8cd29f/datafusion/physical-plan/src/joins/hash_join.rs#L318) it says `The projection indices of the columns in the output schema of join`, however

* inside the `try_new` it seems to be [checked against the join schema](https://github.com/apache/datafusion/blob/ac161bba336d098eab46f666af4664de7e8cd29f/datafusion/physical-plan/src/joins/hash_join.rs#L363)
* and inside the `with_projection` it seems to be [checked against the output schema](https://github.com/apache/datafusion/blob/ac161bba336d098eab46f666af4664de7e8cd29f/datafusion/physical-plan/src/joins/hash_join.rs#L453)
* It also seems to be treated as relative to the join schema [inside the `swap_join_projection` function](https://github.com/apache/datafusion/blob/ac161bba336d098eab46f666af4664de7e8cd29f/datafusion/core/src/physical_optimizer/join_selection.rs#L140) - as it uses the left and right schemas

I tried taking a stab at it, but it's unclear what the meaning of what is passed in projections is. 
For now, I am fixing it surgically when swapping the order - I am rewriting the projections to be relative to the output schema when [wrapping the join with a `ProjectionExec`](https://github.com/apache/datafusion/blob/ac161bba336d098eab46f666af4664de7e8cd29f/datafusion/core/src/physical_optimizer/join_selection.rs#L196)

### PR DESCRIPTION
**Pull request by korowa**
## Which issue does this PR close?

Closes #10978.

## Rationale for this change

On join swap embedded projection for anti/semi joins is getting modified just like for any other join types. This leads to resulting embedded projection, containing column indices out of bounds of join output schema.

## What changes are included in this PR?

The fix is not to modify output projection for semi/anti joins -- they already have one-side schema as an output, and trying to add/subtract the number of fields from the other input side to column indices will break the projection. 

## Are these changes tested?

Existing test for swapping join with embedded projection is extended to test all join types.

## Are there any user-facing changes?

Swapping inputs for semi/anti joins with embedded projection should start working.

### CODE REVIEW

**Comment by korowa** [comment]
cc @berkaysynnada @my-vegetable-has-exploded 

Perhaps you could review this PR, due to still being in context after #12967?

**Review by Dandandan — APPROVED** [review]
This makes sense to me & looks good. It would be good to get another review

**Review by my-vegetable-has-exploded — APPROVED** [review]

File: datafusion/core/src/physical_optimizer/join_selection.rs [hunk 1]
```diff
@@ -1289,27 +1302,59 @@ mod tests_statistical {
         );
     }
 
+    #[rstest(
+        join_type, projection, small_on_right,
+        case::inner(JoinType::Inner, vec![1], true),
+        case::left(JoinType::Left, vec![1], true),
+        case::right(JoinType::Right, vec![1], true),
+        case::full(JoinType::Full, vec![1], true),
+        case::left_anti(JoinType::LeftAnti, vec![0], false),
```
Comment (my-vegetable-has-exploded) [inline datafusion/core/src/physical_optimizer/join_selection.rs:1311]: I think it will be better to add a swap test for LeftAnti & LeftSemi?

**Review by berkaysynnada — APPROVED** [review]
LGTM, thank you @korowa, nice catch

I see you've already did what https://github.com/apache/datafusion/pull/13022#discussion_r1808202057 mentions, but perhaps I couldn't understand the point, so not merging this yet

File: datafusion/core/src/physical_optimizer/join_selection.rs [hunk 2]
```diff
@@ -140,20 +140,32 @@ fn swap_join_projection(
...
-                // Otherwise, it is from the right schema, so we subtract the left schema length from it.
-                if *i < left_schema_len {
-                    *i + right_schema_len
-                } else {
-                    *i - left_schema_len
-                }
-            })
-            .collect()
-    })
+    match join_type {
```
Comment (comphead) [inline datafusion/core/src/physical_optimizer/join_selection.rs:145]: 👍

**Review by comphead — APPROVED** [review]
lgtm thanks @korowa

File: datafusion/core/src/physical_optimizer/join_selection.rs (hunk 1 above)
Comment (my-vegetable-has-exploded) [reply datafusion/core/src/physical_optimizer/join_selection.rs:1311]: Since small_on_right is false for  LeftAnti & LeftSemi,  the swap rule don't work for those tests. But it doesn't matters.
