### PR TITLE
Revert use file schema in parquet pruning

### LINKED ISSUE #15920: Parquet predicate filters fail with "Invalid comparison operation: Utf8View <= Utf8"
### Describe the bug

When running the tpch benchmark with debug logging, some errors are logged - they look like this:

> DEBUG datafusion_datasource_parquet::row_group_filter] Error evaluating row group predicate on bloom filter: Arrow error: Invalid argument error: Invalid comparison operation: Utf8View <= Utf8

> DEBUG datafusion_datasource_parquet::row_group_filter] Error evaluating row group predicate values Arrow error: Invalid argument error: Invalid comparison operation: Utf8View <= Utf8

> DEBUG datafusion_datasource_parquet::page_filter] Error evaluating page index predicate values Arrow error: Invalid argument error: Invalid comparison operation: Utf8View <= Utf8

This does not affect the query result, but I wonder if this there is a cast / conversion missing somewhere.

### To Reproduce

If not done yet, download the tpch dataset+convert it to parquet via
```
./bench.sh data tpch
```

Then run:
```
RUST_LOG=debug ./bench.sh run tpch |& grep error
```

### Expected behavior

No errors =)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adriangb**
- Fixes #15920

### CODE REVIEW

File: datafusion/core/src/datasource/physical_plan/parquet.rs [hunk 1]
```diff
@@ -848,6 +848,68 @@ mod tests {
...
+        // See <comment on PR>
+        // // Predicate should prune no row groups
+        // let filter = col("c1").eq(lit(ScalarValue::UInt64(Some(1))));
+        // let read = RoundTrip::new()
+        //     .with_predicate(filter)
+        //     .with_schema(schema)
+        //     .round_trip_to_batches(vec![batch])
+        //     .await
+        //     .unwrap();
+        // assert_eq!(read.len(), 1);
```
Comment (adriangb) [inline datafusion/core/src/datasource/physical_plan/parquet.rs:910]: This has been failing as far back as 76a7789ace33ced54c973fa0d5fc9d1866e1bf19 with this diff:

```diff
diff --git a/datafusion-testing b/datafusion-testing
index 3462eaa78..e9f9e22cc 160000
--- a/datafusion-testing
+++ b/datafusion-testing
@@ -1 +1 @@
-Subproject commit 3462eaa787459957e38df267a4a21f5bea605807
+Subproject commit e9f9e22ccf09145a7368f80fd6a871f11e2b4481
diff --git a/datafusion/core/src/datasource/file_format/parquet.rs b/datafusion/core/src/datasource/file_format/parquet.rs
index 3b71593b3..60b403aff 100644
--- a/datafusion/core/src/datasource/file_format/parquet.rs
+++ b/datafusion/core/src/datasource/file_format/parquet.rs
@@ -67,13 +67,14 @@ pub(crate) mod test_util {
             .into_iter()
             .zip(tmp_files.into_iter())
             .map(|(batch, mut output)| {
-                let builder = parquet::file::properties::WriterProperties::builder();
-                let props = if multi_page {
+                let mut builder = parquet::file::properties::WriterProperties::builder();
+                builder = if multi_page {
                     builder.set_data_page_row_count_limit(ROWS_PER_PAGE)
                 } else {
                     builder
-                }
-                .build();
+                };
+                builder = builder.set_bloom_filter_enabled(true);
+                let props = builder.build();
 
                 let mut writer = parquet::arrow::ArrowWriter::try_new(
                     &mut output,
diff --git a/datafusion/core/src/datasource/physical_plan/parquet.rs b/datafusion/core/src/datasource/physical_plan/parquet.rs
index 888f3ad9e..240d84783 100644
--- a/datafusion/core/src/datasource/physical_plan/parquet.rs
+++ b/datafusion/core/src/datasource/physical_plan/parquet.rs
@@ -489,6 +489,37 @@ mod tests {
         assert_eq!(read.len(), 0);
     }
 
+
+    #[tokio::test]
+    async fn evolved_schema_column_type_filter_ints() {
+        // The table and filter have a common data type, but the file schema differs
+        let c1: ArrayRef = Arc::new(Int8Array::from(vec![Some(1), Some(2)]));
+        let batch = create_batch(vec![("c1", c1.clone())]);
+
+        let schema =
+            Arc::new(Schema::new(vec![Field::new("c1", DataType::UInt64, false)]));
+
+        // // Predicate should prune all row groups
+        // let filter = col("c1").eq(lit(ScalarValue::UInt64(Some(5))));
+        // let read = RoundTrip::new()
+        //     .with_predicate(filter)
+        //     .with_schema(schema.clone())
+        //     .round_trip_to_batches(vec![batch.clone()])
+        //     .await
+        //     .unwrap();
+        // assert_eq!(read.len(), 0);
+
+        // Predicate should prune no row groups
+        let filter = col("c1").eq(lit(ScalarValue::UInt64(Some(1))));
+        let read = RoundTrip::new()
+            .with_predicate(filter)
+            .with_schema(schema)
+            .round_trip_to_batches(vec![batch])
+            .await
+            .unwrap();
+        assert_eq!(read.len(), 1);
+    }
+
     #[tokio::test]
     async fn evolved_schema_disjoint_schema_filter() {
         let c1: ArrayRef =
diff --git a/parquet-testing b/parquet-testing
index f4d7ed772..6e851ddd7 160000
--- a/parquet-testing
+++ b/parquet-testing
@@ -1 +1 @@
-Subproject commit f4d7ed772a62a95111db50fbcad2460833e8c882
+Subproject commit 6e851ddd768d6af741c7b15dc594874399fc3cff

```

File: datafusion/core/src/datasource/physical_plan/parquet.rs [hunk 2]
```diff
@@ -848,6 +848,68 @@ mod tests {
...
+        let read = RoundTrip::new()
+            .with_predicate(filter)
+            .with_schema(schema.clone())
+            .round_trip_to_batches(vec![batch.clone()])
+            .await
+            .unwrap();
+        assert_eq!(read.len(), 0);
+
+        // TODO: this is failing on main, and has been for a long time!
+        // See <comment on PR>
```
Comment (adriangb) [inline datafusion/core/src/datasource/physical_plan/parquet.rs:901]:
```suggestion
        // See https://github.com/apache/datafusion/pull/16086#discussion_r2094817127
```

File: datafusion/core/src/datasource/physical_plan/parquet.rs [hunk 3]
```diff
@@ -156,10 +162,20 @@ mod tests {
                 source = source
                     .with_pushdown_filters(true)
                     .with_reorder_filters(true);
+            } else {
+                source = source.with_pushdown_filters(false);
             }
```
Comment (adriangb) [inline datafusion/core/src/datasource/physical_plan/parquet.rs:167]: This is just to be explicit

**Comment by xudong963** [comment]
Thank you @adriangb , I'll review the PR tomorrow carefully and try to verify if this is related to the issue we encountered during upgrading DF47

File: datafusion/core/src/datasource/physical_plan/parquet.rs [hunk 4]
```diff
@@ -156,10 +162,20 @@ mod tests {
...
                 source = source.with_enable_page_index(true);
+            } else {
+                source = source.with_enable_page_index(false);
+            }
+
+            if self.bloom_filters {
+                source = source.with_bloom_filter_on_read(true);
+            } else {
+                source = source.with_bloom_filter_on_read(false);
             }
```
Comment (adriangb) [inline datafusion/core/src/datasource/physical_plan/parquet.rs:179]: Otherwise bloom filters will pick up the slack and do pruning even if the types mismatch and stats / page / row pruning fails (bloom filters use &str for both Utf8 and Utf8View so they don't care).

**Comment by adriangb** [comment]
> Thank you @adriangb , I'll review the PR tomorrow carefully and try to verify if this is related to the issue we encountered during upgrading DF47

Thank you 🙏🏻 and sorry for any inconvenience this has caused!

File: datafusion/datasource-parquet/src/opener.rs [hunk 5]
```diff
@@ -55,8 +55,9 @@ pub(super) struct ParquetOpener {
     pub limit: Option<usize>,
     /// Optional predicate to apply during the scan
     pub predicate: Option<Arc<dyn PhysicalExpr>>,
-    /// Schema of the output table
-    pub table_schema: SchemaRef,
+    /// Schema of the output table without partition columns.
```
Comment (alamb) [inline datafusion/datasource-parquet/src/opener.rs:58]: I verified that when the code changes are reverted this test fails:

```shell
cargo test --all-features -p datafusion -- parquet
...

---- datasource::physical_plan::parquet::tests::evolved_schema_column_type_filter_ints stdout ----

thread 'datasource::physical_plan::parquet::tests::evolved_schema_column_type_filter_ints' panicked at datafusion/core/src/datasource/physical_plan/parquet.rs:927:9:
assertion `left == right` failed
  left: 1
 right: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- datasource::physical_plan::parquet::tests::evolved_schema_column_type_filter_strings stdout ----

thread 'datasource::physical_plan::parquet::tests::evolved_schema_column_type_filter_strings' panicked at datafusion/core/src/datasource/physical_plan/parquet.rs:885:9:
assertion `left == right` failed
  left: 1
 right: 0


failures:
    datasource::physical_plan::parquet::tests::evolved_schema_column_type_filter_ints
    datasource::physical_plan::parquet::tests::evolved_schema_column_type_filter_strings
```

File: datafusion/datasource-parquet/src/opener.rs [hunk 6]
```diff
@@ -178,7 +182,7 @@ impl FileOpener for ParquetOpener {
             // Build predicates for this specific file
             let (pruning_predicate, page_pruning_predicate) = build_pruning_predicates(
                 predicate.as_ref(),
-                &physical_file_schema,
+                &logical_file_schema,
```
Comment (alamb) [inline datafusion/datasource-parquet/src/opener.rs:185]: This is the actual change (from physical to logical schema) -- I am calling this out because it took me a while to spot it (at first I thought this was only a name change)

**Review by alamb — APPROVED** [review]
Thank you @adriangb  and @xudong963

File: datafusion/datasource-parquet/src/opener.rs (hunk 6 above)
Comment (adriangb) [reply datafusion/datasource-parquet/src/opener.rs:185]: Yes sorry for also changing the names in this PR - it was just too confusing to even work on this PR without giving things a new name. Let me know if you have any suggestions for better names, happy to accept them, naming here seems to be 1/2 of the problem. You know what they say, there's 3 hard problems...

Comment (alamb) [reply datafusion/datasource-parquet/src/opener.rs:185]: no worries -- I think the new names are much clearer to me

File: datafusion/datasource-parquet/src/opener.rs (hunk 5 above)
Comment (xudong963) [reply datafusion/datasource-parquet/src/opener.rs:58]: I think they're related to the PR: https://github.com/apache/datafusion/pull/16133

File: datafusion/core/src/datasource/physical_plan/parquet.rs [hunk 7]
```diff
@@ -848,6 +864,88 @@ mod tests {
...
+    async fn evolved_schema_column_type_filter_strings() {
+        // The table and filter have a common data type, but the file schema differs
+        let c1: ArrayRef =
+            Arc::new(StringViewArray::from(vec![Some("foo"), Some("bar")]));
+        let batch = create_batch(vec![("c1", c1.clone())]);
+
+        let schema = Arc::new(Schema::new(vec![Field::new("c1", DataType::Utf8, false)]));
+
+        // Predicate should prune all row groups
+        let filter = col("c1").eq(lit(ScalarValue::Utf8(Some("aaa".to_string()))));
```
Comment (xudong963) [inline datafusion/core/src/datasource/physical_plan/parquet.rs:877]: I think the filter should be constructed by `Utf8View`, it's a logical expr.
```
let filter = col("c1").eq(lit(ScalarValue::Utf8View(Some("aaa".to_string()))));
```

Then, the test will fail because https://github.com/apache/datafusion/pull/16086/files#diff-c8eebe4fb9ee7662170c6ce507ad2be92c0229b3a91a2f4431a9bfc7185a0eb9L148 uses `file_schema` to transfer logical expr to physical expr. And https://github.com/apache/datafusion/pull/16133 will fix it

**Review by xudong963 — APPROVED** [review]
Thank you @adriangb 

Your test `evolved_schema_column_type_filter_strings` is close to my real case, my real case is that file_schema is view but table_schame is utf8.

I constructed a similar test that matches my cases:
```rust
let c1: ArrayRef =
    Arc::new(StringArray::from(vec![Some("foo"), Some("bar")]));
let batch = create_batch(vec![("c1", c1.clone())]);

let schema = Arc::new(Schema::new(vec![Field::new("c1", DataType::Utf8View, false)]));

// Predicate should prune all row groups
let filter = col("c1").eq(lit(ScalarValue::Utf8(Some("aaa".to_string()))));
```      
With the fix: https://github.com/apache/datafusion/pull/16133, I tested the test in branch-46, branch-47, main and your branch:
branch-46: ✅
branch-47: ❌
main: ❌
your branch: ✅

**Comment by alamb** [comment]
Thanks again @xudong963 and @adriangb

File: datafusion/datasource-parquet/src/opener.rs (hunk 6 above)
Comment (etseidl) [reply datafusion/datasource-parquet/src/opener.rs:185]: Sorry, coming to this too late, but I'm curious why the logical schema? To me pruning implies a physical layer kind of thing. I ask because now I'm having issues in #15821 trying to build pruning predicates for columns that don't exist in the physical schema.

This may just mean #15821 is operating at too low a level and needs to operate up here where we a) know it's parquet and b) have the physical schema.

@alamb @adriangb

Comment (alamb) [reply datafusion/datasource-parquet/src/opener.rs:185]: I think the key observation is that the predicates are expressed in terms of the table schema (not the file schema). 

Today there is a bunch of logic to translate table schema -> file schema  for data and statistics.

So in order to evaluate predicates on the physical schema we would need to translate the expression as well, which I think is what @adriangb  is saying above

Comment (adriangb) [reply datafusion/datasource-parquet/src/opener.rs:185]: Yep precisely. And that requires re evaluating cast rules, etc which is... not easy.

Comment (etseidl) [reply datafusion/datasource-parquet/src/opener.rs:185]: Ok, thanks for the explanation!

File: datafusion/core/src/datasource/physical_plan/parquet.rs (hunk 7 above)
Comment (alamb) [reply datafusion/core/src/datasource/physical_plan/parquet.rs:877]: Upon more reflection, I think the predicate needs to be created using the logical schema today

@adriangb @etseidl  and myself are discussing potentially changing that here:
- https://github.com/apache/datafusion/issues/15780

**Comment by xudong963** [comment]
Fyi, we've upgraded to DF47 with the fix successfully.

**Comment by adriangb** [comment]
Great to hear! Sorry for the inconvenience...

**Comment by xudong963** [comment]
> Great to hear! Sorry for the inconvenience...

No problem!

**Comment by alamb** [comment]
FWIW @phillipleblanc  also hit this as well in SpiceAI. See this for more details
- https://github.com/spiceai/spiceai/pull/6178
