### PR TITLE
fix: Handle Utf8View and LargeUtf8 separators in concat_ws

### LINKED ISSUE #20360: concat_ws() fails with Utf8View, LargeUtf8 separators
### Describe the bug

```
> create table t1 (sep text, v1 text, v2 text) as values (',', 'foo', 'bar');
0 row(s) fetched.
Elapsed 0.012 seconds.

> select concat_ws(arrow_cast(sep, 'Utf8View'), v1, v2) from t1;
Internal error: could not cast array of type Utf8View to arrow_array::array::byte_array::GenericByteArray<arrow_array::types::GenericStringType<i32>>.
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by neilconway**
## Which issue does this PR close?

- Closes #20360 

## Rationale for this change

concat_ws only handled Utf8 separators (despite its signature claiming otherwise). Attempting to pass a Utf8View or LargeUtf8 separator would result in a panic or internal error.

## What changes are included in this PR?

* Add SLT test case for array Utf8View separator
* Add unit test for scalar Utf8View separator
* Fix behavior: add support for LargeUtf8 and Utf8View separators, both array and scalar
* Other minor code cleanups and improvements

## Are these changes tested?

Yes. Added new test cases.

Note that we can't easily test the scalar separator case via SQL, because `simplify_concat_ws` casts constant/scalar separators to Utf8. That behavior is dubious and IMO should be changed, but I'll tackle that in a subsequent PR.

## Are there any user-facing changes?

No, aside from a previously failing query now succeeding.

### CODE REVIEW

File: datafusion/functions/src/string/concat_ws.rs [hunk 1]
```diff
@@ -546,4 +564,41 @@ mod tests {
 
         Ok(())
     }
+
+    #[test]
+    fn concat_ws_utf8view_scalar_separator() -> Result<()> {
```
Comment (xanderbailey) [inline datafusion/functions/src/string/concat_ws.rs:569]: Is it worth adding a large utf8 string test also?

File: datafusion/sqllogictest/test_files/expr.slt [hunk 2]
```diff
@@ -504,6 +504,19 @@ abc
 statement ok
 drop table foo
 
+# concat_ws with a Utf8View column as separator
+statement ok
+create table test_concat_ws_sep (sep varchar, val1 varchar, val2 varchar) as values (',', 'foo', 'bar'), ('|', 'a', 'b');
+
+query T
+SELECT concat_ws(arrow_cast(sep, 'Utf8View'), val1, val2) FROM test_concat_ws_sep ORDER BY val1
```
Comment (xanderbailey) [inline datafusion/sqllogictest/test_files/expr.slt:512]: Same here with a large string test?

File: datafusion/functions/src/string/concat_ws.rs (hunk 1 above)
Comment (neilconway) [reply datafusion/functions/src/string/concat_ws.rs:569]: Thank you! Added.

File: datafusion/sqllogictest/test_files/expr.slt (hunk 2 above)
Comment (neilconway) [reply datafusion/sqllogictest/test_files/expr.slt:512]: Thank you! Added.

File: datafusion/functions/src/string/concat_ws.rs [hunk 3]
```diff
@@ -162,23 +156,55 @@ impl ScalarUDFImpl for ConcatWsFunc {
...
-                    ColumnarValueRef::NonNullableArray(string_array)
+            ColumnarValue::Scalar(scalar) => match scalar.try_as_str() {
+                Some(Some(s)) => {
+                    data_size += s.len() * len * (args.len() - 2); // estimate
+                    ColumnarValueRef::Scalar(s.as_bytes())
                 }
-            }
-            _ => unreachable!("concat ws"),
+                Some(None) => {
+                    return Ok(ColumnarValue::Array(Arc::new(StringArray::new_null(
```
Comment (Jefffrey) [inline datafusion/functions/src/string/concat_ws.rs]: We can probably return scalar here

File: datafusion/functions/src/string/concat_ws.rs [hunk 4]
```diff
@@ -162,23 +156,55 @@ impl ScalarUDFImpl for ConcatWsFunc {
...
+                    let string_array = as_string_array(array)?;
+                    data_size += string_array.values().len() * (args.len() - 2);
+                    if array.is_nullable() {
+                        ColumnarValueRef::NullableArray(string_array)
+                    } else {
+                        ColumnarValueRef::NonNullableArray(string_array)
+                    }
+                }
+                DataType::LargeUtf8 => {
+                    let string_array = as_largestring_array(array);
```
Comment (Jefffrey) [inline datafusion/functions/src/string/concat_ws.rs]: nit: we seem to be mixing cast methods here; this comes from arrow but we're using datafusion sourced ones for utf8 & utf8view

**Review by Jefffrey — APPROVED** [review]

File: datafusion/functions/src/string/concat_ws.rs (hunk 4 above)
Comment (neilconway) [reply datafusion/functions/src/string/concat_ws.rs]: Good catch! Fixed.

File: datafusion/functions/src/string/concat_ws.rs (hunk 3 above)
Comment (neilconway) [reply datafusion/functions/src/string/concat_ws.rs]: Yep! Fixed.

**Comment by Jefffrey** [comment]
Thanks @neilconway & @xanderbailey
