### PR TITLE
Minor: fix signature `fn octect_length()`

### LINKED ISSUE #10676: Should the arg of `octet_length()` be a bare `Expr` instead of `Vec<Expr>`?
### Describe the bug

This is a minor issue about consistency. Currently, the signature of `octet_length()` is this, but I think this function takes only one argument just like `bit_length()`.

```rust
pub fn octet_length(args: Vec<Expr>) -> Expr
```
https://docs.rs/datafusion/38.0.0/datafusion/functions/string/expr_fn/fn.octet_length.html

### To Reproduce

n/a

### Expected behavior

n/a

### Additional context

n/a

### PR DESCRIPTION
**Pull request by marvinlanhenke**
## Which issue does this PR close?

Closes #10676.

## Rationale for this change

- fix a minor issue about consistency
- fn signature should be the same as `fn bit_length()`

## What changes are included in this PR?
- changed `octet_length` to accept `Expr` instead of `Vec<Expr>`

## Are these changes tested?
Yes. Existing tests.

## Are there any user-facing changes?
No.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Looks good to me 🙏 thank ou @marvinlanhenke 

Would it be possible to add a test here so we don't break it again: https://github.com/apache/datafusion/blob/904f0db73cf2c0049822c7045e09824a7453a02d/datafusion/core/tests/expr_api/mod.rs#L51-L63 ?     


(run via `cargo run --test core_integration`)

**Comment by marvinlanhenke** [comment]
thanks for the quick response @alamb - I added the test

File: datafusion/core/tests/expr_api/mod.rs [hunk 1]
```diff
@@ -28,6 +28,23 @@ use std::sync::{Arc, OnceLock};
 
 mod simplification;
 
+#[test]
+fn test_octet_length() {
```
Comment (comphead) [inline datafusion/core/tests/expr_api/mod.rs:32]: can we move it to slt?

File: datafusion/functions/src/string/mod.rs [hunk 2]
```diff
@@ -128,8 +128,8 @@ pub mod expr_fn {
     }
 
     #[doc = "returns the number of bytes of a string"]
-    pub fn octet_length(args: Vec<Expr>) -> Expr {
-        super::octet_length().call(args)
+    pub fn octet_length(args: Expr) -> Expr {
+        super::octet_length().call(vec![args])
```
Comment (comphead) [inline datafusion/functions/src/string/mod.rs:132]: 👍

File: datafusion/core/tests/expr_api/mod.rs (hunk 1 above)
Comment (alamb) [reply datafusion/core/tests/expr_api/mod.rs:32]: Since this fix is for the expr_fn API I don't think we can move this to .slt (the code path invoked needs to be invoked programatically, not via SQL)

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Thanks again @marvinlanhenke  and @comphead
