### PR TITLE
fix: regression of `dict_id` in physical plan proto

### LINKED ISSUE #20011: Physical plan proto roundtrip for null-valued scalar of a `Struct(Dict)` data type
### Describe the bug

We're currently upgrading from datafusion 45 to datafusion 46 🙈 and came across an issue related to dictionary ids during protobuf serde.
Here's a small reproducer, and this seems to still be a problem on current datafusion:

The following test works on df-45 but fails on df-46 and all later releases, added to the bottom of `datafusion/proto/tests/cases/roundtrip_physical_plan.rs`:
```rust
#[test]
fn roundtrip_call_null_scalar_struct_dict() {
    let data_type = DataType::Struct(Fields::from(vec![Field::new(
        "item",
        DataType::Dictionary(Box::new(DataType::UInt32), Box::new(DataType::Utf8)),
        true,
    )]));
    let schema = Arc::new(Schema::new(Fields::from([Arc::new(Field::new(
        "a",
        data_type.clone(),
        true,
    ))])));
    let scan = Arc::new(EmptyExec::new(schema.clone()));
    let scalar = lit(ScalarValue::try_from(data_type).unwrap());
    let filter = Arc::new(
        FilterExec::try_new(
            Arc::new(BinaryExpr::new(
                scalar,
                datafusion::logical_expr::Operator::Eq,
                col("a", &schema).unwrap(),
            )),
            scan,
        )
        .unwrap(),
    );
    roundtrip_test(filter).expect("roundtrip");
}
```

In df46, this fails during deserialization of protobuf back to the physical plan:
```
thread 'cases::roundtrip_physical_plan::roundtrip_call_null_scalar_struct_dict' panicked at datafusion/proto/tests/cases/roundtrip_physical_plan.rs:140:10:
from proto: Plan("DataFusion error: ArrowError(SchemaError(\"Invalid data for schema. Field { name: \\\"item\\\", data_type: Dictionary(UInt32, Utf8), nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } refers to node not found in schema\"), None)")
```

In df52, it already fails during serialization, as there's no pre-allocated dict id available from the dictionary tracker
```
thread 'cases::roundtrip_physical_plan::roundtrip_call_null_scalar_struct_dict' (145817) panicked at datafusion/proto/tests/cases/roundtrip_physical_plan.rs:148:14:
to proto: Plan("General error: Error encoding ScalarValue::List as IPC: Ipc error: no dict id for field item")
```

I am a bit puzzled on how that is supposed to work. From what I can tell, the `DictionaryTracker` seems to be initialized empty and then never modified - I don't see a possible code path where a dict_id is even created.

### To Reproduce

Run the test above within the context of `datafusion/proto/tests/cases/roundtrip_physical_plan.rs`

### Expected behavior

Test passes, protobuf roundtrip of physical plan succeeds.

### Additional context

I believe it started failing with work related to https://github.com/apache/datafusion/pull/14227/changes

### PR DESCRIPTION
**Pull request by kumarUjjawal**
## Which issue does this PR close?

- Closes #20011.

## Rationale for this change

- `dict_id` is intentionally not preserved  protobuf (it’s deprecated in Arrow schema metadata), but Arrow IPC still requires dict IDs for dictionary encoding/decoding.

## What changes are included in this PR?

- Fix protobuf serde for nested ScalarValue (list/struct/map) containing dictionary arrays by using Arrow IPC’s dictionary handling correctly.
- Seed DictionaryTracker by encoding the schema before encoding the nested scalar batch.
- On decode, reconstruct an IPC schema from the protobuf schema and use arrow_ipc::reader::read_dictionary to build dict_by_id before reading the record batch.

## Are these changes tested?

Yes added a test for this

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by kumarUjjawal** [comment]
> lgtm, thank you for fixing this!

Thanks for the review!

**Review by alamb — COMMENTED** [review]
Thank you @kumarUjjawal 

FYI @dispanser

**Comment by dispanser** [comment]
thanks @kumarUjjawal , appreciated!

File: datafusion/proto-common/src/from_proto/mod.rs [hunk 1]
```diff
@@ -406,6 +411,35 @@ impl TryFrom<&protobuf::ScalarValue> for ScalarValue {
...
+                    let encoded_schema = ipc_gen.schema_to_bytes_with_dictionary_tracker(
+                        &schema,
+                        &mut dict_tracker,
+                        &write_options,
+                    );
+                    let message =
+                        root_as_message(encoded_schema.ipc_message.as_slice()).map_err(
+                            |e| {
+                                Error::General(format!(
+                                    "Error IPC schema message while deserializing ScalarValue::List: {e}"
```
Comment (martin-g) [inline datafusion/proto-common/src/from_proto/mod.rs]: Why the error messages say `ScalarValue::List` ? (**List**)
Isn't this used for any nested type ? List, Map, Struct, ...

Comment (kumarUjjawal) [reply datafusion/proto-common/src/from_proto/mod.rs]: Good catch! I will update.

File: datafusion/proto-common/src/from_proto/mod.rs [hunk 2]
```diff
@@ -401,55 +406,83 @@ impl TryFrom<&protobuf::ScalarValue> for ScalarValue {
                     schema_ref.try_into()?
                 } else {
                     return Err(Error::General(
-                        "Invalid schema while deserializing ScalarValue::List"
+                        "Invalid schema while deserializing nested ScalarValue"
                             .to_string(),
                     ));
                 };
 
+                // IPC dictionary batch IDs are assigned when encoding the schema, but our protobuf
```
Comment (alamb) [inline datafusion/proto-common/src/from_proto/mod.rs:427]: I feel like somehow I missing something key -- this seems like a pretty massive  overhead to create / decode a single value here. 

That being said, it seems like the existing code is also doing the overhead, so maybe it is fine for now 🤔 

I wonder if we could pull this logic for creating the schema into its own function to try and reduce the size of the overall method / make it easier to understand

File: datafusion/proto/tests/cases/roundtrip_physical_plan.rs [hunk 3]
```diff
@@ -2564,3 +2564,22 @@ fn custom_proto_converter_intercepts() -> Result<()> {
 
     Ok(())
 }
+
+#[test]
```
Comment (alamb) [inline datafusion/proto/tests/cases/roundtrip_physical_plan.rs:2569]: With the code change reverted, this test fails like


---- cases::roundtrip_physical_plan::roundtrip_call_null_scalar_struct_dict stdout ----
Error: Plan("General error: Error encoding ScalarValue::List as IPC: Ipc error: no dict id for field item")

**Comment by alamb** [comment]
Screenshot 2026-02-03 at 4 30 18 PM

I merged up to resolve a conflict

**Comment by kumarUjjawal** [comment]
Thank you @alamb. I will look into your suggestions.

**Comment by alamb** [comment]
> Thank you @alamb. I will look into your suggestions.

Thanks -- let's do it as a follow on PR
