### PR TITLE
fix: Added nullable return from date_add(#19151)

### LINKED ISSUE #19151: spark `date_add` need to have custom nullability
### Describe the bug

the UDF uses the default `is_nullable` which is always true which is not the case

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by manishkr**
## Which issue does this PR close?

- Closes #19151.

## Rationale for this change

- This will make return type of data_add udf nullable.

## Are these changes tested?
- Yes

## Are there any user-facing changes?
- No

### CODE REVIEW

File: datafusion/spark/src/function/datetime/date_add.rs [hunk 1]
```diff
@@ -136,3 +145,48 @@ fn spark_date_add(args: &[ArrayRef]) -> Result<ArrayRef> {
...
+#[cfg(test)]
+mod tests {
+    use super::*;
+    use arrow::datatypes::Field;
+
+    #[test]
+    fn test_date_add_non_nullable_inputs() {
+        let func = SparkDateAdd::new();
+        let args = &[
+            Arc::new(Field::new("arg_int8", DataType::Int8, false)),
```
Comment (martin-g) [inline datafusion/spark/src/function/datetime/date_add.rs]: The possible signatures (https://github.com/apache/datafusion/pull/19229/files#diff-8b0a95c4b80c4d83fe7c0752f11a762647f4d36173ae7988a76d7bc7da5d5168R53-R55) say that the first argument should be `Date32`
```suggestion
            Arc::new(Field::new("arg_date32", DataType::Date32, false)),
```

File: datafusion/spark/src/function/datetime/date_add.rs [hunk 2]
```diff
@@ -136,3 +145,48 @@ fn spark_date_add(args: &[ArrayRef]) -> Result<ArrayRef> {
...
+
+        assert_eq!(ret_field.data_type(), &DataType::Date32);
+        assert!(!ret_field.is_nullable());
+    }
+
+    #[test]
+    fn test_date_add_nullable_inputs() {
+        let func = SparkDateAdd::new();
+        let args = &[
+            Arc::new(Field::new("arg_int8", DataType::Int8, false)),
```
Comment (martin-g) [inline datafusion/spark/src/function/datetime/date_add.rs]: The possible signatures (https://github.com/apache/datafusion/pull/19229/files#diff-8b0a95c4b80c4d83fe7c0752f11a762647f4d36173ae7988a76d7bc7da5d5168R53-R55) say that the first argument should be `Date32`
```suggestion
            Arc::new(Field::new("arg_date32", DataType::Date32, false)),
```

File: datafusion/spark/src/function/datetime/date_add.rs [hunk 3]
```diff
@@ -136,3 +145,48 @@ fn spark_date_add(args: &[ArrayRef]) -> Result<ArrayRef> {
...
+            Arc::new(Field::new("arg_int16", DataType::Int16, true)),
+            Arc::new(Field::new("arg_int32", DataType::Int32, false)),
```
Comment (martin-g) [inline datafusion/spark/src/function/datetime/date_add.rs]: The date_add() function accepts two arguments
```suggestion
```

File: datafusion/spark/src/function/datetime/date_add.rs [hunk 4]
```diff
@@ -136,3 +145,48 @@ fn spark_date_add(args: &[ArrayRef]) -> Result<ArrayRef> {
...
+            .return_field_from_args(ReturnFieldArgs {
+                arg_fields: args,
+                scalar_arguments: &[None, None, None],
+            })
+            .unwrap();
+
+        assert_eq!(ret_field.data_type(), &DataType::Date32);
+        assert!(ret_field.is_nullable());
+    }
+}
```
Comment (martin-g) [inline datafusion/spark/src/function/datetime/date_add.rs:218]: Please also add a test for NULL at datafusion/sqllogictest/test_files/spark/datetime/date_add.slt if there is no such already

**Comment by martin-g** [comment]
https://github.com/apache/datafusion/pull/19225 is very similar to this PR. Please check it for additional inspiration.

File: datafusion/spark/src/function/datetime/date_add.rs (hunk 1 above)
Comment (manishkr) [reply datafusion/spark/src/function/datetime/date_add.rs]: Done, Thanks.

File: datafusion/spark/src/function/datetime/date_add.rs (hunk 2 above)
Comment (manishkr) [reply datafusion/spark/src/function/datetime/date_add.rs]: Done, Thanks.

File: datafusion/spark/src/function/datetime/date_add.rs (hunk 3 above)
Comment (manishkr) [reply datafusion/spark/src/function/datetime/date_add.rs]: Done, Thanks.

File: datafusion/spark/src/function/datetime/date_add.rs (hunk 4 above)
Comment (manishkr) [reply datafusion/spark/src/function/datetime/date_add.rs:218]: I see NULL test cases already. If I am missing, something please let me know. Thanks

```
query D
SELECT date_add(NULL::date, 1::int);
----
NULL

query D
SELECT date_add('2016-07-30'::date, NULL::int);
----
NULL

query D
SELECT date_add(NULL::date, NULL::int);
```

**Comment by manishkr** [comment]
> #19225 is very similar to this PR. Please check it for additional inspiration.
Added scalar case. Thanks

**Comment by manishkr** [comment]
@martin-g If it doesn't need any further improvement, please approve. Thanks

**Comment by martin-g** [comment]
@manishkr  Please fix the PR title: s/data_add/date_add/

**Comment by manishkr** [comment]
> @manishkr Please fix the PR title: s/data_add/date_add/

Done, Thanks.

**Comment by manishkr** [comment]
@comphead Could you help in merging this. Thanks.

**Review by comphead — APPROVED** [review]
Thanks @manishkr and @martin-g for the review!
