### PR TITLE
fix: custom nullability for length (#19175)

### LINKED ISSUE #19175: spark `length` need to have custom nullability
### Describe the bug

the UDF uses the default `is_nullable` which is always true which is not the case

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by skushagra**
## Which issue does this PR close?

- Closes #19175

## What changes are included in this PR?

- includes custom nullability for length, determined dynamically using input arguments.

### CODE REVIEW

File: datafusion/spark/src/function/string/length.rs [hunk 1]
```diff
@@ -92,6 +93,11 @@ impl ScalarUDFImpl for SparkLengthFunc {
     fn aliases(&self) -> &[String] {
         &self.aliases
     }
+
+    fn return_field_from_args(&self, args: ReturnFieldArgs) -> Result<FieldRef> {
+        let nullable = args.arg_fields.iter().any(|f| f.is_nullable());
+        Ok(Arc::new(Field::new(self.name(), Boolean, nullable)))
```
Comment (rluvaton) [inline datafusion/spark/src/function/string/length.rs]: this function does not return a boolean but Int32, see the `return_type` function above.

can you please also add a test that it is nullable when the child is nullable

File: datafusion/spark/src/function/string/length.rs
Comment (rluvaton) [inline datafusion/spark/src/function/string/length.rs]: please move the comment to `return_field_from_args`, and return `internal_err!` that this should not be called, and `return_field_from_args` should be called instead

**Comment by rluvaton** [comment]
I've verified that this expression is null intolerant:
https://github.com/apache/spark/blob/98058da21e8a341eca10207f0ca458671220ca94/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/stringExpressions.scala#L2447

File: datafusion/spark/src/function/string/length.rs
Comment (skushagra) [reply datafusion/spark/src/function/string/length.rs]: what should the error message say exactly? Going with
`internal_err!("This should not be called, use return_field_from_args instead")` for now.

File: datafusion/spark/src/function/string/length.rs [hunk 2]
```diff
@@ -279,4 +286,38 @@ mod tests {
...
+    #[test]
+    fn test_spark_length_nullability() -> Result<()> {
+        let func = SparkLengthFunc::new();
+
+        let nullable_field: FieldRef =
+            Arc::new(Field::new("col", DataType::Utf8, true));
+
+        let out_nullable = func.return_field_from_args(ReturnFieldArgs {
+            arg_fields: &[nullable_field],
+            scalar_arguments: &[],
```
Comment (rluvaton) [inline datafusion/spark/src/function/string/length.rs]: there should be the same number of `scalar_arguments` and `arg_fields`, if something is not scalar than None is used.
```suggestion
            scalar_arguments: &[None], 
```

File: datafusion/spark/src/function/string/length.rs [hunk 3]
```diff
@@ -279,4 +286,38 @@ mod tests {
...
+            out_nullable.is_nullable(),
+            "length(col) should be nullable when child is nullable"
+        );
+
+        let non_nullable_field: FieldRef =
+            Arc::new(Field::new("col", DataType::Utf8, false));
+
+        let out_non_nullable = func.return_field_from_args(ReturnFieldArgs {
+            arg_fields: &[non_nullable_field],
+            scalar_arguments: &[],
```
Comment (rluvaton) [inline datafusion/spark/src/function/string/length.rs]:
```suggestion
            scalar_arguments: &[None], 
```
