### PR TITLE
fix: percentile_cont interpolation causes NaN for f16 input

### LINKED ISSUE #18945: percentile_cont interpolation causes `NaN` for f16 input
### Describe the bug

(Relies on #18944 being merged so it can accept f16 input)

This interpolation step here seems to cause f16 to go out of bounds (into inf) so we can't calculate percentiles for f16 as it'll always return NaN:

https://github.com/apache/datafusion/blob/769f36732a284cec3d549bfcda50cb67684fb5dc/datafusion/functions-aggregate/src/percentile_cont.rs#L753-L758

Need to fix this for f16.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kumarUjjawal**
## Which issue does this PR close?

- Closes #18945

## Rationale for this change

percentile_cont interpolation for Float16 could overflow f16 intermediates (e.g. when scaling the fractional component), producing inf/NaN and incorrect results. This PR makes interpolation numerically safe for f16.

## What changes are included in this PR?

 • Perform percentile interpolation in f64 and cast back to the input float type (f16/f32/f64) to avoid f16 overflow.
 • Add a regression unit test covering Float16 interpolation near the maximum finite value.

## Are these changes tested?

Yes

## Are there any user-facing changes?

Yes. percentile_cont on Float16 inputs no longer returns NaN due to interpolation overflow and will produce correct
finite results for valid finite f16 data

### CODE REVIEW

File: datafusion/functions-aggregate/src/percentile_cont.rs [hunk 1]
```diff
@@ -58,17 +58,50 @@ use datafusion_macros::user_doc;
...
-/// - Small enough to avoid overflow when multiplied with typical numeric values
-/// - Sufficient precision for most statistical applications
-///
-/// The interpolation formula: `lower + (upper - lower) * fraction`
-/// is computed as: `lower + ((upper - lower) * (fraction * PRECISION)) / PRECISION`
-/// to avoid floating-point operations on integer types while maintaining precision.
-const INTERPOLATION_PRECISION: usize = 1_000_000;
+/// Helper trait for safe interpolation on floating point native types
+/// (Float16 / Float32 / Float64).
+trait InterpolateNative: Copy {
```
Comment (Jefffrey) [inline datafusion/functions-aggregate/src/percentile_cont.rs]: I feel there should be existing traits we can leverage for this

e.g.

- https://docs.rs/half/latest/half/struct.f16.html#impl-AsPrimitive%3Cf64%3E-for-f16
- https://docs.rs/half/latest/half/struct.f16.html#impl-AsPrimitive%3Cf16%3E-for-f64

File: datafusion/sqllogictest/test_files/aggregate.slt [hunk 2]
```diff
@@ -3926,7 +3926,7 @@ SELECT percentile_cont(0.95) WITHIN GROUP (ORDER BY c3 DESC) FROM aggregate_test
 query R
 SELECT percentile_cont(0.05) WITHIN GROUP (ORDER BY c3 DESC) FROM aggregate_test_100
 ----
-118.099998
+118.1
```
Comment (Jefffrey) [inline datafusion/sqllogictest/test_files/aggregate.slt]: Not sure if this precision loss for other float types is desirable as part of these changes

File: datafusion/functions-aggregate/src/percentile_cont.rs [hunk 3]
```diff
@@ -58,16 +58,10 @@ use datafusion_macros::user_doc;
...
-/// - Small enough to avoid overflow when multiplied with typical numeric values
-/// - Sufficient precision for most statistical applications
-///
-/// The interpolation formula: `lower + (upper - lower) * fraction`
-/// is computed as: `lower + ((upper - lower) * (fraction * PRECISION)) / PRECISION`
-/// to avoid floating-point operations on integer types while maintaining precision.
+// Keep historical behavior for percentile interpolation by quantizing the
+// fractional component before interpolation. This minimizes output changes for
+// Float32/Float64 while still allowing us to perform the arithmetic in f64
+// (preventing Float16 overflow).
```
Comment (Jefffrey) [inline datafusion/functions-aggregate/src/percentile_cont.rs]: Can we keep the original comment here? I don't see why we should replace the proper explanation with simply "Keep historical behaviour"

File: datafusion/functions-aggregate/src/percentile_cont.rs [hunk 4]
```diff
@@ -772,22 +783,42 @@ fn calculate_percentile<T: ArrowNumericType>(
             let (_, upper_value, _) = values.select_nth_unstable_by(upper_index, cmp);
             let upper_value = *upper_value;
 
-            // Linear interpolation using wrapping arithmetic
-            // We use wrapping operations here (matching the approach in median.rs) because:
-            // 1. Both values come from the input data, so diff is bounded by the value range
-            // 2. fraction is between 0 and 1, and INTERPOLATION_PRECISION is small enough
```
Comment (Jefffrey) [inline datafusion/functions-aggregate/src/percentile_cont.rs:778]: Same here

File: datafusion/functions-aggregate/src/percentile_cont.rs [hunk 5]
```diff
@@ -772,22 +783,42 @@ fn calculate_percentile<T: ArrowNumericType>(
...
             let fraction = index - (lower_index as f64);
-            let diff = upper_value.sub_wrapping(lower_value);
-            let interpolated = lower_value.add_wrapping(
-                diff.mul_wrapping(T::Native::usize_as(
-                    (fraction * INTERPOLATION_PRECISION as f64) as usize,
-                ))
-                .div_wrapping(T::Native::usize_as(INTERPOLATION_PRECISION)),
-            );
-            Some(interpolated)
+            let scaled = (fraction * INTERPOLATION_PRECISION as f64) as usize;
```
Comment (Jefffrey) [inline datafusion/functions-aggregate/src/percentile_cont.rs]: Why are we removing the wrapping versions of the operators?

Comment (kumarUjjawal) [reply datafusion/functions-aggregate/src/percentile_cont.rs]: moved the interpolation math to f64 (then casts back), so there’s no native-type overflow to wrap anymore.

File: datafusion/functions-aggregate/src/percentile_cont.rs [hunk 6]
```diff
@@ -58,16 +58,14 @@ use datafusion_macros::user_doc;
...
-/// - Small enough to avoid overflow when multiplied with typical numeric values
-/// - Sufficient precision for most statistical applications
+/// We keep this quantization to minimize output changes for Float32/Float64
+/// compared to the previous implementation.
 ///
-/// The interpolation formula: `lower + (upper - lower) * fraction`
-/// is computed as: `lower + ((upper - lower) * (fraction * PRECISION)) / PRECISION`
-/// to avoid floating-point operations on integer types while maintaining precision.
+/// Interpolation is performed in f64 and then cast back to the native type to
+/// avoid overflowing Float16 intermediates.
```
Comment (Jefffrey) [inline datafusion/functions-aggregate/src/percentile_cont.rs]: I'd still prefer we keep the old documentation as it was and just add on any amendments; I don't like how it reads about a "previous implementation" considering there is no information about such implementation (without looking at the git history)

File: datafusion/functions-aggregate/src/percentile_cont.rs [hunk 7]
```diff
@@ -772,22 +787,49 @@ fn calculate_percentile<T: ArrowNumericType>(
...
             let fraction = index - (lower_index as f64);
-            let diff = upper_value.sub_wrapping(lower_value);
-            let interpolated = lower_value.add_wrapping(
-                diff.mul_wrapping(T::Native::usize_as(
-                    (fraction * INTERPOLATION_PRECISION as f64) as usize,
-                ))
-                .div_wrapping(T::Native::usize_as(INTERPOLATION_PRECISION)),
-            );
-            Some(interpolated)
+            let scaled = (fraction * INTERPOLATION_PRECISION as f64) as usize;
```
Comment (Jefffrey) [inline datafusion/functions-aggregate/src/percentile_cont.rs]: If we always cast `INTERPOLATION_PRECISION` to `f64` at all its usages we should just define it as `f64`

File: datafusion/functions-aggregate/src/percentile_cont.rs [hunk 8]
```diff
@@ -772,22 +787,49 @@ fn calculate_percentile<T: ArrowNumericType>(
...
-            // We use wrapping operations here (matching the approach in median.rs) because:
-            // 1. Both values come from the input data, so diff is bounded by the value range
-            // 2. fraction is between 0 and 1, and INTERPOLATION_PRECISION is small enough
-            //    to prevent overflow when combined with typical numeric ranges
-            // 3. The result is guaranteed to be between lower_value and upper_value
-            // 4. For floating-point types, wrapping ops behave the same as standard ops
+            // Linear interpolation.
+            //
+            // We quantize the fractional component (via `INTERPOLATION_PRECISION`) to
+            // minimize output changes for Float32/Float64 compared to the previous
```
Comment (Jefffrey) [inline datafusion/functions-aggregate/src/percentile_cont.rs]: What previous implementation are we referring to here?

**Comment by alamb** [comment]
Thanks @kumarUjjawal and @Jefffrey
