### PR TITLE
fix: enhance CTE resolution with identifier normalization

### LINKED ISSUE #18932: Implementing `CatalogProvider` breaks quoted CTE names
### Describe the bug

We use a custom `CatalogProvider`. We've discovered an edge case where a quoted CTE name breaks using a custom catalog provider, but not when using `MemoryCatalogProvider`. In other words, a query like:

```
with foobar as (select count(*) from orders) select * from "foobar"
```

Hits the catalog provider for `foobar`, even though it's a CTE table, and the catalog doesn't have any record of in it advance, obviously. Not quoting `"foobar"` or just using `ctx.register_table("orders", ...)` both cause the query to work.

### To Reproduce

Here is some code that reproduces:

```rust
#[derive(Debug)]
struct MyCatalog;

#[derive(Debug)]
struct MySchema(String);

impl CatalogProvider for MyCatalog {
    fn as_any(&self) -> &dyn Any {
        self
    }

    fn schema_names(&self) -> Vec<String> {
        Vec::new()
    }

    fn schema(&self, name: &str) -> Option<Arc<dyn SchemaProvider>> {
        Some(Arc::new(MySchema(name.to_owned())))
    }
}

#[async_trait::async_trait]
impl SchemaProvider for MySchema {
    fn as_any(&self) -> &dyn Any {
        self
    }

    fn table_names(&self) -> Vec<String> {
        todo!()
    }

    async fn table(
        &self,
        name: &str,
    ) -> Result<Option<Arc<dyn datafusion::catalog::TableProvider>>, DataFusionError> {
        if name == "orders" {
            let schema = Arc::new(Schema::new(vec![
                Field::new("id", DataType::Int32, false),
                Field::new("name", DataType::Utf8, false),
            ]));
            return Ok(Some(Arc::new(EmptyTable::new(schema))));
        } else {
            panic!("Table not found: {name}")
        }
    }

    fn table_exist(&self, name: &str) -> bool {
        name == "orders"
    }
}

#[tokio::test]
async fn quoted_cte() -> anyhow::Result<()> {
    let ctx = SessionContext::new();
    ctx.register_catalog("datafusion", Arc::new(MyCatalog));

    // If I comment out the line above and use this instead, both queries work.
    //
    // let schema = Arc::new(Schema::new(vec![
    //     Field::new("id", DataType::Int32, false),
    //     Field::new("name", DataType::Utf8, false),
    // ]));
    // let table = Arc::new(EmptyTable::new(schema));
    // ctx.register_table("orders", table)?;
    
    // NO QUOTING: This always works either way.
    let res = ctx
        .sql("with foobar as (select * from orders) select * from foobar")
        .await?
        .collect()
        .await?;

    println!("{}", pretty_format_batches(&res)?);

    // QUOTING: This doesn't work with `MyCatalog`.
    let res = ctx
        .sql("with barbaz as (select * from orders) select * from \"barbaz\"")
        .await?
        .collect()
        .await?;

    println!("{}", pretty_format_batches(&res)?);

    Ok(())
}
```

### Expected behavior

Both queries in the example should work with a custom catalog provider.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kysshsy**
## Which issue does this PR close?

- Closes #18932 

## Rationale for this change
- Quoted CTE references (e.g., `WITH barbaz AS (...) SELECT * FROM "barbaz"`) were being collected as table refs and could fall through to catalog lookup instead of resolving to the CTE, especially with custom providers.

## What changes are included in this PR?
- Normalize CTE and table references consistently during collection (preserve quote style; only lowercase unquoted idents when enabled).
- Avoid double-normalization when converting to `TableReference` in the resolve path.

## Are these changes tested?
Yes

## Are there any user-facing changes?
- Behavior fix for quoted CTE references; no API changes.

### CODE REVIEW

**Comment by kysshsy** [comment]
@alamb @comphead Could you take a look or suggest an alternative approach? Thanks!

File: datafusion/sql/src/resolve.rs [hunk 1]
```diff
@@ -49,13 +49,31 @@ struct RelationVisitor {
     relations: BTreeSet<ObjectName>,
     all_ctes: BTreeSet<ObjectName>,
     ctes_in_scope: Vec<ObjectName>,
+    normalizer: IdentNormalizer,
 }
 
 impl RelationVisitor {
+    fn normalize_object_name(&self, name: &ObjectName) -> ObjectName {
```
Comment (alamb) [inline datafusion/sql/src/resolve.rs]: Could you please add some comments that explain what this is doing and the rationale (the WHY)? I think you can adapt your PR description.

File: datafusion/sql/src/resolve.rs [hunk 2]
```diff
@@ -193,19 +213,20 @@ pub fn resolve_table_references(
...
+        normalizer: IdentNormalizer::new(enable_ident_normalization),
     };
 
     visit_statement(statement, &mut visitor);
 
     let table_refs = visitor
         .relations
         .into_iter()
-        .map(|x| object_name_to_table_reference(x, enable_ident_normalization))
+        .map(|x| object_name_to_table_reference(x, false))
```
Comment (alamb) [inline datafusion/sql/src/resolve.rs]: why is this always false now?

File: datafusion/sql/src/resolve.rs [hunk 3]
```diff
@@ -270,4 +291,57 @@ mod tests {
...
+        use crate::parser::DFParser;
+
+        let query = r#"with FOObar as (select 1) select * from "FOObar""#;
+        let statement = DFParser::parse_sql(query).unwrap().pop_back().unwrap();
+        let (table_refs, ctes) = resolve_table_references(&statement, false).unwrap();
+        // Without normalization, cases match exactly, so quoted reference resolves to the CTE
+        assert_eq!(ctes.len(), 1);
+        assert_eq!(ctes[0].to_string(), "FOObar");
+        assert_eq!(table_refs.len(), 0);
+    }
```
Comment (alamb) [inline datafusion/sql/src/resolve.rs:358]: Can you also please add some .slt tests so we can see this working when running end to end in queries?

Instructions are here: https://github.com/apache/datafusion/tree/main/datafusion/sqllogictest

**Review by alamb — COMMENTED** [review]
Thanks @kysshsy  -- this looks like a good start.

FYI @jonahgao  -- perhaps you would have some time to review this PR

File: datafusion/sql/src/resolve.rs (hunk 2 above)
Comment (jonahgao) [inline datafusion/sql/src/resolve.rs]: Can `RelationVisitor` directly collect normalized table references instead of object names so that there is no need for a second normalization here?

File: datafusion/sql/src/resolve.rs (hunk 3 above)
Comment (kysshsy) [reply datafusion/sql/src/resolve.rs:358]: Thanks for the suggestion — I’ve added an end-to-end .slt regression

File: datafusion/sql/src/resolve.rs (hunk 2 above)
Comment (kysshsy) [reply datafusion/sql/src/resolve.rs]: It’s `false` because references are already normalized when collected, so we only need to convert to `TableReference` here and avoid normalizing twice. 
Per the suggestion, the visitor now collects `TableReference` directly.

Comment (kysshsy) [reply datafusion/sql/src/resolve.rs]: I updated `RelationVisitor` to collect normalized `TableReferences` directly, so we don’t need a second normalization pass.
The only downside is error handling becomes a bit more involved, since converting to `TableReference` can fail and we now need to propagate that `Error` during visiting.

File: datafusion/sql/src/resolve.rs (hunk 1 above)
Comment (kysshsy) [reply datafusion/sql/src/resolve.rs]: updated

**Comment by kysshsy** [comment]
Thanks for the thorough review and the helpful suggestions. @alamb @jonahgao

File: datafusion/sqllogictest/test_files/cte_quoted_reference.slt [hunk 4]
```diff
@@ -0,0 +1,70 @@
+# Licensed to the Apache Software Foundation (ASF) under one
```
Comment (jonahgao) [inline datafusion/sqllogictest/test_files/cte_quoted_reference.slt:1]: Since this test is small, I think we can consolidate it into cte.slt. Maybe in next PR.

**Review by jonahgao — APPROVED** [review]
LGTM, thank you @kysshsy . I have fixed the ci failures in 168baba43cab261d036da8509b29ceb92bb756fa

File: datafusion/sqllogictest/test_files/cte_quoted_reference.slt (hunk 4 above)
Comment (alamb) [reply datafusion/sqllogictest/test_files/cte_quoted_reference.slt:1]: Good idea -- I filed this ticket to track the idea:
- https://github.com/apache/datafusion/issues/19786

**Comment by alamb** [comment]
Thanks again @kysshsy and @jonahgao
