### PR TITLE
Handle possible overflows in StringArrayBuilder / LargeStringArrayBuilder

### LINKED ISSUE #13759: StringArrayBuilder and LargeStringArrayBuilder don't check null buffer length
### Describe the bug

(This was found by a security audit performed by InfluxData)

> The public method finish in datafusion_functions::strings::StringArrayBuilder takes an argument, null_buffer, which is unconditionally assigned to an internal member; however, the contract for this data type requires that the three buffers (value_buffer, offsets_buffer, and nulls) are of the same length.
> 
> The argument to finish can be Option<NullBuffer> with a buffer of arbitrary length, but the length of it is not checked; therefore, the contract might be violated and subsequent usage of the resulting StringArray might lead to out-of-bounds reads or writes.

https://github.com/apache/datafusion/blob/e8314aba0bd2af4106a5dff49428bfb8fb003d57/datafusion/functions/src/strings.rs#L338-L348

I (@alamb ) analyzed the code and I do think there is a problem, but I do not think it is exploitable from SQL or other downstream applications. It would only affect someone using the `StringArrayBuilder` or `LargeStringArrayBuilder` APIs directly (though they are `pub`, [see doc links](https://docs.rs/datafusion/latest/datafusion/functions/strings/struct.StringArrayBuilder.html))

The reason I don't think it is exploitable is that it is only called in in two locations:

* https://github.com/apache/datafusion/blob/3ee9b3dfb6d9c4e95a93d694b6aaf5c21ab61354/datafusion/functions/src/string/concat.rs#L217-L218 (called with `None` aka no buffer)
* https://github.com/apache/datafusion/blob/3ee9b3dfb6d9c4e95a93d694b6aaf5c21ab61354/datafusion/functions/src/string/concat_ws.rs#L254 called with `Some(..)` buffer from the input array (that is the same size as the output array)

And the size of the null buffer is correct in both cases

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wiedld**
## Which issue does this PR close?

Closes https://github.com/apache/datafusion/issues/13796

## Rationale for this change

We identified a potential code vulnerability during a security audit at InfluxData.

## What changes are included in this PR?

Make overflow a panic.

## Are these changes tested?

yes

## Are there any user-facing changes?

no

### CODE REVIEW

File: datafusion/functions/src/strings.rs [hunk 1]
```diff
@@ -124,8 +125,18 @@ pub struct StringArrayBuilder {
 
 impl StringArrayBuilder {
     pub fn with_capacity(item_capacity: usize, data_capacity: usize) -> Self {
-        let mut offsets_buffer =
-            MutableBuffer::with_capacity((item_capacity + 1) * size_of::<i32>());
+        // MutableBuffer::with_capacity will round up to multiples of `ALIGNMENT`
+        let capacity = std::cmp::max(
```
Comment (alamb) [inline datafusion/functions/src/strings.rs:129]: The idea of the `with_capacity` is to allocate enough space for `item_capacity + 1` offsets, each of which is an `i32`

The code below then assumes that it has successfully allocated space for that many offsets and uses the `unsafe` API assuming that the allocation is sized for `item_capacity + 1` items

In the case where the `capacity` calculation overflows, that assumption is violated. 

Thus, I think the right fix is for the code in DataFusion to check that the value it passes to `mutable` is in fact sufficient to hold `item_capacity + 1` `i32` values

I think you can do this by using https://doc.rust-lang.org/std/primitive.i32.html#method.checked_mul instead of `*` and panic'ing if the calculation is bad

File: datafusion/functions/src/strings.rs [hunk 2]
```diff
@@ -124,8 +125,18 @@ pub struct StringArrayBuilder {
...
+            item_capacity.saturating_add(1).saturating_mul(ALIGNMENT),
+            data_capacity,
+        );
+        // rust core's Layout::from_size_align is capped at isize::Max
+        let capacity = std::cmp::min(
```
Comment (alamb) [inline datafusion/functions/src/strings.rs:134]: I am not sure what case you are trying to prevent by checking `ALIGNMENT`, but it looks like maybe you have found a problem passing large (but not overflowing) values to `MutableBuffer::with_capacity`

If this is the case, I have two suggestions:
1. Such a check belongs in arrow-rs (`MutableBuffer::with_capacity`)
2. File a ticket explaining what the issue is in arrow-rs along with a reproducer before adding additional checks.

**Review by alamb — COMMENTED** [review]
Thanks @wiedld  -- I left some comments -- not sure about the `ALIGNMENT` thing

File: datafusion/functions/src/strings.rs (hunk 1 above)
Comment (wiedld) [reply datafusion/functions/src/strings.rs]: I overthought things. Fixed.

**Review by alamb — COMMENTED** [review]
Thanks @wiedld  -- looks good to me

**Review by alamb — APPROVED** [review]
