### PR TITLE
fix: Fix scalar broadcast for to_timestamp()

### LINKED ISSUE #20223: to_timestamp() fails when passed mix of scalar and array args
### Describe the bug

When to_timestamp() was invoked with a scalar Float64 and an array of strings, the implementation neglects to broadcast the scalar to the array properly when producing the return value.

### To Reproduce

```
CREATE TABLE t61(v2 STRING);
INSERT INTO t61(v2) VALUES ('flX'), ('3');

SELECT TO_TIMESTAMP(123.5, tt0.v2) FROM t61 AS tt0;
```

Yields

```
Internal error: UDF to_timestamp returned a different number of rows than expected. Expected: 2, Got: 1
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by neilconway**
When to_timestamp() was invoked with a scalar Float64 and an array of strings, the previous coding neglected to broadcast the scalar to the array properly when producing the return value.  That is, a query like `SELECT to_timestamp(123.5, t.x) FROM t` would result in:

    Internal error: UDF to_timestamp returned a different number of rows
    than expected

## Which issue does this PR close?

- Closes #20223

## Are these changes tested?

Yes, added SLT.

### CODE REVIEW

File: datafusion/functions/src/datetime/to_timestamp.rs [hunk 1]
```diff
@@ -430,27 +430,56 @@ impl ScalarUDFImpl for ToTimestampFunc {
...
-            }
-            Float64 => {
-                let arr = args[0].to_array(1)?;
-                let f64_arr = downcast_arg!(&arr, Float64Array);
-                let result: TimestampNanosecondArray =
-                    f64_arr.unary(|x| (x * 1_000_000_000.0) as i64);
-                Ok(ColumnarValue::Array(Arc::new(result.with_timezone_opt(tz))))
-            }
+            Float16 => match &args[0] {
+                ColumnarValue::Scalar(ScalarValue::Float16(value)) => {
```
Comment (Jefffrey) [inline datafusion/functions/src/datetime/to_timestamp.rs:434]: what about scalar f16 nulls? same for other branches

File: datafusion/sqllogictest/test_files/datetime/timestamps.slt [hunk 2]
```diff
@@ -5328,3 +5328,33 @@ drop table ts_data_secs
...
+## Test to_timestamp with scalar float inputs
+##########
+
+statement ok
+create table test_to_timestamp_scalar(id int, name varchar) as values
+  (1, 'foo'),
+  (2, 'bar');
+
+query P
+SELECT to_timestamp(123.5, name) FROM test_to_timestamp_scalar ORDER BY id;
```
Comment (martin-g) [inline datafusion/sqllogictest/test_files/datetime/timestamps.slt:5342]: How `foo` and `bar` are interpreted as formats here ?!
According to https://github.com/apache/datafusion/pull/20224/changes#diff-853711994ef45ba29e048e6db0c6ad4e015f8f30299d1f39f6c7bca8b4f4fd36R282-R283:
```
If none of the formats successfully parse the expression an error will be returned
```

Comment (neilconway) [reply datafusion/sqllogictest/test_files/datetime/timestamps.slt:5342]: In the current implementation, the second and subsequent arguments are completely ignored, unless the first argument is a string. Passing format arguments when the first argument isn't a strict doesn't actually make much sense, and in fact Postgres only implements to variants:

```
to_timestamp(double) -> timestamptz
to_timestamp(text, text) -> timestamptz
```

On that basis, I can revise this PR to reject attempts to pass two or more arguments when the first argument is not a string. Does that sound reasonable?

File: datafusion/functions/src/datetime/to_timestamp.rs (hunk 1 above)
Comment (neilconway) [reply datafusion/functions/src/datetime/to_timestamp.rs:434]: I believe the current coding is correct -- `value.map()` will map `None` to `None`. Lmk if I'm mistaken though.

File: datafusion/sqllogictest/test_files/datetime/timestamps.slt (hunk 2 above)
Comment (martin-g) [reply datafusion/sqllogictest/test_files/datetime/timestamps.slt:5342]: Thanks for explaining!

> I can revise this PR to reject attempts to pass two or more arguments when the first argument is not a string

Maybe is a follow-up. No need to do mix two improvements in the same PR.

File: datafusion/functions/src/datetime/to_timestamp.rs (hunk 1 above)
Comment (Jefffrey) [reply datafusion/functions/src/datetime/to_timestamp.rs:434]: Yes you're right, my mistake

**Review by Jefffrey — APPROVED** [review]

**Comment by alamb** [comment]
Thanks @Jefffrey @neilconway and @martin-g
