### PR TITLE
FIX : Incorrect NULL handling in BETWEEN expression

### LINKED ISSUE #13976: Incorrect `NULL` handling in `BETWEEN` expression
### Describe the bug

Run in datafusion-cli compiled from main (commit 259443d66)
```
> select 1 where null between null and 2;
type_coercion
caused by
Error during planning: Cannot automatically convert Int64 to Null
```

### To Reproduce

_No response_

### Expected behavior

`null` should be interpreted as a missing integer, so the expression should be valid, and the query should return empty set
```
postgres=# select 1 where null between null and 2;
 ?column? 
----------
(0 rows)
```

### Additional context

This bug is found by the recently integrated SQLite test suite, after the fix, all related `skipif`s can be removed from test cases in https://github.com/apache/datafusion-testing
```
# Datafusion - Error during planning: Cannot automatically convert Int64 to Null
skipif Datafusion
```

### PR DESCRIPTION
**Pull request by getChan**
## Which issue does this PR close?

Closes #13976.

## What changes are included in this PR?

in `BETWEEN` expression, 
The type of the `high` value is determined by the type of the `high` value, not the type of the `low` value.

As a result, the coercion type in a BETWEEN expression is determined by comparing the `low`, `high`, and `compare` values.

https://github.com/apache/datafusion/blob/a2a353bc7a79465b0e56b5c821d6a5aa8a44e43f/datafusion/optimizer/src/analyzer/type_coercion.rs#L420-L441

## Are these changes tested?

unit tested, sqllogic tested.

## Are there any user-facing changes?

in `BETWEEN` expression, 
Type coercion will work as intended.

### CODE REVIEW

File: datafusion/optimizer/src/analyzer/type_coercion.rs [hunk 1]
```diff
@@ -426,7 +426,7 @@ impl TreeNodeRewriter for TypeCoercionRewriter<'_> {
                         ))
                     })?;
                 let high_type = high.get_type(self.schema)?;
-                let high_coerced_type = comparison_coercion(&expr_type, &low_type)
+                let high_coerced_type = comparison_coercion(&expr_type, &high_type)
```
Comment (alamb) [inline datafusion/optimizer/src/analyzer/type_coercion.rs:429]: 🤦  -- nice fix

File: datafusion/sqllogictest/test_files/between.slt [hunk 2]
```diff
@@ -0,0 +1,32 @@
+# Licensed to the Apache Software Foundation (ASF) under one
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/between.slt:1]: Would it be possible to move this file into this https://github.com/apache/datafusion/tree/main/datafusion/sqllogictest/test_files/expr directory? 

We can do it as a follow on PR too

**Review by alamb — APPROVED** [review]
Thanks @getChan  -- this is a nice fix ❤️ 

Thanks to @2010YOUY01 for filing the ticket.

File: datafusion/sqllogictest/test_files/between.slt (hunk 2 above)
Comment (getChan) [reply datafusion/sqllogictest/test_files/between.slt]: thanks. moved it.

**Comment by alamb** [comment]
Thanks again @getChan 🚀
