### PR TITLE
[Minor] add non topk benchmarks for utf8/utf8view string aggregates

### LINKED ISSUE #19713: Add non-TopK benchmark variants for Utf8/Utf8View string aggregates
## Summary
Add benchmark variants that run string-aggregate workloads with TopK disabled (representative case) in addition to the existing TopK-enabled worst-case benchmarks, so we can directly compare performance and verify correctness across `Utf8` and `Utf8View` group keys.

## Background
- The current `datafusion/core/benches/topk_aggregate.rs` benchmarks exercise the TopK-enabled code path for string aggregates.
- @haohuaijin  [suggested adding non-TopK benchmarks so we can compare the TopK and non-TopK behavior/performances](https://github.com/apache/datafusion/pull/19285#discussion_r2668719929) and validate the TopK fix in PR #19285.

## Why this matters
- Allows straightforward measurement of TopK's benefit (or regression) relative to the fallback path.
- Helps validate correctness (e.g., Utf8View grouping) under both code paths.
- Provides repeatable benchmarks to include in PRs and discussions.

### PR DESCRIPTION
**Pull request by buraksenn**
## Which issue does this PR close?
- Closes #19713.

## Rationale for this change
Details are in #19713 but main idea is to compare non-topk and topk test results so that we can compare performances

## What changes are included in this PR?
Added non topk benchmark tests. 

## Are these changes tested?
Only test changes

## Are there any user-facing changes?
No

### CODE REVIEW

File: datafusion/core/benches/topk_aggregate.rs [hunk 1]
```diff
@@ -290,152 +290,107 @@ fn criterion_benchmark(c: &mut Criterion) {
...
+            format!(
+                "top k={limit} string aggregate {total_rows} {scenario} rows [{type_label}]"
+            )
+        } else {
+            format!("string aggregate {total_rows} {scenario} rows [{type_label}]")
+        };
+        let ctx = rt
+            .block_on(create_context(partitions, samples, asc, use_topk, use_view))
+            .unwrap();
+        c.bench_function(&name, |b| {
```
Comment (kosiew) [inline datafusion/core/benches/topk_aggregate.rs:474]: These new TopK-disabled string cases expand the matrix, but they still only go through run_string()/aggregate_string(), which currently checks row-count and whether the physical plan contains lim=[...]. That means this PR does not actually verify correctness across Utf8 and Utf8View group keys, even though that is part of the motivation. Can we strengthen the string benchmark path with an expected-result assertion (or add a dedicated helper/test that compares Utf8 vs Utf8View output for both TopK modes) so the new variants catch ordering/value regressions instead of only plan-shape changes?

File: datafusion/core/benches/topk_aggregate.rs [hunk 2]
```diff
@@ -290,152 +290,107 @@ fn criterion_benchmark(c: &mut Criterion) {
...
-        |b| b.iter(|| run_distinct(&rt, ctx_topk.clone(), limit, true, true)),
-    );
+    // (use_topk, asc)
+    let distinct_cases: &[(bool, bool)] =
+        &[(false, false), (false, true), (true, false), (true, true)];
+    for &(use_topk, asc) in distinct_cases {
+        let dir = if asc { "asc" } else { "desc" };
+        let topk_label = if use_topk { "TopK" } else { "no TopK" };
+        let name = format!("distinct {total_rows} rows {dir} [{topk_label}]");
+        let ctx = rt.block_on(async {
```
Comment (kosiew) [inline datafusion/core/benches/topk_aggregate.rs:481]: This refactor now rebuilds the DISTINCT input/context once per (use_topk, asc) pair, even though asc only affects the query text and the old version shared one context per TopK mode. It is outside the timed loop, so not a benchmark-result bug, but it does add a lot of setup work for 10M rows. Could we hoist context creation by use_topk again, or extract a small helper that caches the two contexts?

File: datafusion/core/benches/topk_aggregate.rs [hunk 3]
```diff
@@ -290,152 +290,107 @@ fn criterion_benchmark(c: &mut Criterion) {
...
+        ),
+        (
+            true,
+            true,
+            true,
+            true,
+            "top k={limit} aggregate {rows} worst-case rows [Utf8View]",
+        ),
+    ];
+    for &(asc, use_topk, use_view, run_asc, name_tpl) in numeric_cases {
```
Comment (kosiew) [inline datafusion/core/benches/topk_aggregate.rs]: Could this tuple be simplified a bit? run_asc currently mirrors asc in every entry, so carrying both booleans makes the benchmark matrix harder to audit and easier to desynchronize later. Passing asc straight through (or switching to a small case struct with named fields) would make the intent clearer.

**Review by kosiew — CHANGES_REQUESTED** [review]
👋 @buraksenn 

Thanks for working on this.

File: datafusion/core/benches/topk_aggregate.rs (hunk 1 above)
Comment (buraksenn) [reply datafusion/core/benches/topk_aggregate.rs:474]: I wrongly assumed we wanted to only check performance but I understand. I've added a `assert` to check results of each

File: datafusion/core/benches/topk_aggregate.rs (hunk 3 above)
Comment (buraksenn) [reply datafusion/core/benches/topk_aggregate.rs]: Makes sense, I've got rid of `run_asc` and  reordered cases. I can also introduce a struct if requested

File: datafusion/core/benches/topk_aggregate.rs (hunk 2 above)
Comment (buraksenn) [reply datafusion/core/benches/topk_aggregate.rs:481]: I understand I think I've resolved this by using and cloning the session (shallow copy afais) but can you check if possible

**Comment by buraksenn** [comment]
Thanks @kosiew for the detailed review

File: datafusion/core/benches/topk_aggregate.rs [hunk 4]
```diff
@@ -204,7 +204,7 @@ async fn aggregate_string(
     let batch = batches.first().unwrap();
     assert_eq!(batch.num_rows(), LIMIT);
 
-    Ok(())
+    Ok(format!("{}", pretty_format_batches(&batches)?))
```
Comment (kosiew) [inline datafusion/core/benches/topk_aggregate.rs]: It looks like `aggregate_string` now pretty prints the collected batches and returns a `String`, and that is what `b.iter(...)` is measuring for each string benchmark.

This means the non TopK string benchmarks now include batch formatting and heap allocation overhead, which the numeric benchmarks do not include. So the comparison is no longer isolating query execution.

Would it make sense to keep a `Result<()>` fast path for the timed benchmark, and move the `pretty_format_batches` work into a one time validation helper that runs before benchmark registration?

File: datafusion/core/benches/topk_aggregate.rs [hunk 5]
```diff
@@ -290,152 +290,113 @@ fn criterion_benchmark(c: &mut Criterion) {
...
-        .unwrap();
-    c.bench_function(
-        format!(
-            "top k={limit} string aggregate {} time-series rows [Utf8View]",
-            partitions * samples
-        )
-        .as_str(),
-        |b| b.iter(|| run_string(&rt, ctx.clone(), limit, true)),
-    );
+    for asc in [false, true] {
```
Comment (kosiew) [inline datafusion/core/benches/topk_aggregate.rs]: Small readability thought here. Could the Utf8 vs Utf8View parity check live in a helper?

Right now `criterion_benchmark` is doing both benchmark registration and cross layout validation. Pulling the verification loop into something like `assert_string_results_match(...)` would make the benchmark matrix easier to scan.

File: datafusion/core/benches/topk_aggregate.rs [hunk 6]
```diff
@@ -290,152 +290,113 @@ fn criterion_benchmark(c: &mut Criterion) {
...
-        format!(
-            "top k={limit} string aggregate {} worst-case rows [Utf8View]",
-            partitions * samples
-        )
-        .as_str(),
-        |b| b.iter(|| run_string(&rt, ctx.clone(), limit, true)),
-    );
+    // String aggregate benchmarks
+    // (asc, use_topk, use_view)
+    let string_cases: &[(bool, bool, bool)] = &[
```
Comment (kosiew) [inline datafusion/core/benches/topk_aggregate.rs]: The `&[(bool, bool, bool)]` tuple list is a bit hard to read and reason about when scanning or extending cases.

Maybe a small case struct or a helper similar to `numeric_cases` would help make the intent clearer. Something that names `asc`, `use_topk`, and `use_view` explicitly would also reduce the chance of mixing up tuple positions later.

**Review by kosiew — CHANGES_REQUESTED** [review]
@buraksenn 

Thanks for the updates here, this is heading in a good direction. I did notice one issue that affects the benchmark results, plus a couple of smaller readability suggestions.

File: datafusion/core/benches/topk_aggregate.rs (hunk 5 above)
Comment (buraksenn) [reply datafusion/core/benches/topk_aggregate.rs]: I've extracted two helpers instead of this

File: datafusion/core/benches/topk_aggregate.rs (hunk 6 above)
Comment (buraksenn) [reply datafusion/core/benches/topk_aggregate.rs]: I've made this and numeric one both structs

File: datafusion/core/benches/topk_aggregate.rs (hunk 4 above)
Comment (buraksenn) [reply datafusion/core/benches/topk_aggregate.rs]: I've changed it such that it is done in the caller path and function returns vector

**Comment by buraksenn** [comment]
Thanks for the detailed review twice @kosiew, really appreciate it :)

**Review by kosiew — APPROVED** [review]
lgtm
