### PR TITLE
Make scalar and array handling for array_has consistent

### LINKED ISSUE #13682: `array_has` has inconsistent null handling for scalars and arrays
### Describe the bug

`array_has` handles nulls differently for scalars and arrays. Scalars return null if all the left hand side values are null, while arrays don't care what values in the left hand side are null. Additionally, other systems like Spark and Postgres have different null behavior, such that if at least one element of the left hand side is null, return null instead of false. I can't find any definitive SQL standard for this, but it might be good to behave consistent with those other systems.

### To Reproduce

```
> create table arrays as values (make_array(1, 2, 3), 4), (make_array(1, 2, NULL), 4), (make_array(NULL, NULL, NULL), 4);
0 row(s) fetched. 
Elapsed 0.017 seconds.

> select array_has(column1, column2) from arrays;
+------------------------------------------+
| array_has(arrays.column1,arrays.column2) |
+------------------------------------------+
| false                                    |
| false                                    |
| false                                    |
+------------------------------------------+
3 row(s) fetched. 
Elapsed 0.007 seconds.

> select array_has([1, 2, 3], 4),
array_has([1, 2, NULL], 4),
array_has([NULL, NULL, NULL], 4);
+------------------------------------------------------------+--------------------------------------------------------+------------------------------------------------+
| array_has(make_array(Int64(1),Int64(2),Int64(3)),Int64(4)) | array_has(make_array(Int64(1),Int64(2),NULL),Int64(4)) | array_has(make_array(NULL,NULL,NULL),Int64(4)) |
+------------------------------------------------------------+--------------------------------------------------------+------------------------------------------------+
| false                                                      | false                                                  |                                                |
+------------------------------------------------------------+--------------------------------------------------------+------------------------------------------------+
1 row(s) fetched. 
Elapsed 0.007 seconds.
```

### Expected behavior

These queries return the same results.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Kimahriman**
## Which issue does this PR close?

Closes #13682 

## Rationale for this change

Makes null handling for `array_has` consistent across scalars and arrays, following the DuckDB behavior of returning false instead of null if a list contains null values.

## What changes are included in this PR?

Updates both scalar and array handling for `array_has` to return false regardless of if the left hand side has any null values in it. This matches DuckDB, but differs from systems like Postgres, Spark, and Trino.

## Are these changes tested?

Tests are added and updated to accommodate the changes.

## Are there any user-facing changes?

Fix handling of array_has for scalars to match the array behavior.

### CODE REVIEW

File: datafusion/functions-nested/src/array_has.rs [hunk 1]
```diff
@@ -215,7 +215,11 @@ fn array_has_dispatch_for_array<O: OffsetSizeTrait>(
         let needle_row = Scalar::new(needle.slice(i, 1));
         let eq_array = compare_with_eq(&arr, &needle_row, is_nested)?;
         let is_contained = eq_array.true_count() > 0;
-        boolean_builder.append_value(is_contained)
+        if is_contained || eq_array.null_count() == 0 {
```
Comment (alamb) [inline datafusion/functions-nested/src/array_has.rs:218]: I am surprised this isn't 

```suggestion
        if is_contained && eq_array.null_count() == 0 {
```

I thought if the eq_array is null that means there was at least one comparison that is not known 🤔

**Review by alamb — APPROVED** [review]
Thank you for this PR @Kimahriman 

I have a question

> This is the behavior defined by Postgres, and used by Spark as well, not sure what other database systems use:

I think that is the right set of target systems.

File: datafusion/functions-nested/src/array_has.rs (hunk 1 above)
Comment (Kimahriman) [reply datafusion/functions-nested/src/array_has.rs:218]: The semantics are basically:
- if the element is contained, return true
- otherwise if there is a null value in the array, return null
- otherwise return false

So nulls don't matter if there's match, it only matters if there's no match

File: datafusion/sqllogictest/test_files/array.slt [hunk 2]
```diff
@@ -5260,6 +5270,13 @@ select array_has([], null),
 ----
 NULL NULL NULL
 
+# If lhs is has any Nulls, we return Null instead of false
+query BB
+select array_has([1, null, 2], 3),
```
Comment (comphead) [inline datafusion/sqllogictest/test_files/array.slt:5275]: I'm not sure this is a correct behavior.

Checking DuckDB

```
D select array_has([1, null, 2], 3);
┌───────────────────────────────────────────┐
│ array_has(main.list_value(1, NULL, 2), 3) │
│                  boolean                  │
├───────────────────────────────────────────┤
│ false                                     │
└───────────────────────────────────────────┘
```

**Review by comphead — CHANGES_REQUESTED** [review]
I'm not sure the test gives a correct answer

File: datafusion/sqllogictest/test_files/array.slt (hunk 2 above)
Comment (Kimahriman) [reply datafusion/sqllogictest/test_files/array.slt:5275]: Hmm DuckDB is different then Spark and Postgres then

```
spark-sql (default)> SELECT array_contains(array(1, NULL, 3), 4);
NULL
```

```
postgres=# SELECT 4 =ANY('{1, NULL, 3}');
 ?column? 
----------
 
(1 row)
```

Was hoping to use this to implement `ArrayContains` for Comet, and this is the one behavior difference.

**Comment by jayzhan211** [comment]
We follow DuckDB for array function, I think the better approach is having a easy way to customize the function

**Comment by Weijun-H** [comment]
> We follow DuckDB for array function mostly, the best I can think of is implementing spark function in [datafusion-contrib/datafusion-functions-extra](https://github.com/datafusion-contrib/datafusion-functions-extra)

I agree with @jayzhan211 that we should follow the DuckDB pattern for the array family function, as we consider the DuckDB results.

**Comment by Kimahriman** [comment]
Interesting thing is that DuckDB says they based it on the PrestoDB behavior: https://github.com/duckdb/duckdb/pull/3065

But a quick look at the PrestoDB implementation suggests they use the behavior I'm suggesting, if one null is found the result is null: https://github.com/prestodb/presto/blob/b68af58583b8d58992b6ab0804d8d3618f7f402b/presto-main/src/main/java/com/facebook/presto/operator/scalar/ArrayContains.java#L52

So I wonder if DuckDBs null handling was actually intentionally or just an oversight by whoever initially implemented it

**Comment by jayzhan211** [comment]
> Interesting thing is that DuckDB says they based it on the PrestoDB behavior: [duckdb/duckdb#3065](https://github.com/duckdb/duckdb/pull/3065)
> 
> But a quick look at the PrestoDB implementation suggests they use the behavior I'm suggesting, if one null is found the result is null: https://github.com/prestodb/presto/blob/b68af58583b8d58992b6ab0804d8d3618f7f402b/presto-main/src/main/java/com/facebook/presto/operator/scalar/ArrayContains.java#L52
> 
> So I wonder if DuckDBs null handling was actually intentionally or just an oversight by whoever initially implemented it

Interesting, in this case I think changing the result is not a bad idea.

**Comment by comphead** [comment]
just checked the Trino, it returns null in such case. DuckDB returns false.
Not sure what should we do, @alamb WDYT to break the tie?

**Comment by alamb** [comment]
> just checked the Trino, it returns null in such case. DuckDB returns false. Not sure what should we do, @alamb WDYT to break the tie?

I recommend following @jayzhan211 and @Weijun-H 's suggestion that we follow DuckDB semantics for array/list functions

I think it is past time to document what we think we are doing with respect to dialects, and I will attempt to do so shortly
- https://github.com/apache/datafusion/issues/13704

File: datafusion/sqllogictest/test_files/array.slt (hunk 2 above)
Comment (Kimahriman) [reply datafusion/sqllogictest/test_files/array.slt:5275]: Turns out the existing "correct" behavior for scalars doesn't match DuckDB either, which never returns null unless the whole array is null

DuckDB
```
D select array_has([null, null], 4);
┌───────────────────────────────────────────┐
│ array_has(main.list_value(NULL, NULL), 4) │
│                  boolean                  │
├───────────────────────────────────────────┤
│ false                                     │
└───────────────────────────────────────────┘
```

DF
```
DataFusion CLI v43.0.0
> select array_has([null, null], 4);
+-------------------------------------------+
| array_has(make_array(NULL,NULL),Int64(4)) |
+-------------------------------------------+
|                                           |
+-------------------------------------------+
1 row(s) fetched. 
Elapsed 0.001 seconds.
```

**Comment by jayzhan211** [comment]
Can we add config setting in `SessionConfig` to tune the result of function after #13519 is done?

Something like `returns_null_if_contains_null`, `ignore_nulls`, `convert_null_to_value` and so on.

If `returns_null_if_contains_null` is true, we can have the Spark result of `array_has`, otherwise we have Postgres/DuckDB result.

**Comment by comphead** [comment]
> Can we add config setting in `SessionConfig` to tune the result of function after #13519 is done?
> 
> Something like `returns_null_if_contains_null`, `ignore_nulls`, `convert_null_to_value` and so on. (These should be dialect-agnostic)
> 
> If `returns_null_if_contains_null` is true, we can have the Spark result of `array_has`, otherwise we have Postgres/DuckDB result.

That sounds reasonable but those discrepancies tends to grow so maintain those params could be unbearable. My feeling we should follow some standard whatever it is, but one and the idea of extensibility is awesome so users can implements their own behavior

**Comment by Kimahriman** [comment]
Yeah that does seem like a messy slippery slope. And I feel like part of the critique in https://github.com/apache/datafusion/issues/13525 was that too many things required the `SessionContext` to customize.

**Comment by alamb** [comment]
> Yeah that does seem like a messy slippery slope. And I feel like part of the critique in #13525 was that too many things required the `SessionContext` to customize.

Maybe we you could just implement a version of array_has  that has the null semantics that you need in your system 🤔

**Comment by Kimahriman** [comment]
> Maybe we you could just implement a version of array_has that has the null semantics that you need in your system 🤔

Yeah that seems like the only viable option. I'll just update this to match duckdb

File: datafusion/sqllogictest/test_files/array.slt (hunk 2 above)
Comment (Kimahriman) [reply datafusion/sqllogictest/test_files/array.slt:5275]: Updated to match DuckDB behavior and updated description

**Comment by alamb** [comment]
What is the status of this PR? It seems from the most recent comments we don't plan to proceed with this PR?

I'll mark it draft to signify it isn't waiting on review, but please feel free to correct me if I am wrong

**Comment by Kimahriman** [comment]
This is ready. It still fixes a minor discrepancy between scalars and arrays handling of null values, so that both now match ducksb's behavior

File: datafusion/functions-nested/src/array_has.rs [hunk 3]
```diff
@@ -214,8 +214,7 @@ fn array_has_dispatch_for_array<O: OffsetSizeTrait>(
         let is_nested = arr.data_type().is_nested();
         let needle_row = Scalar::new(needle.slice(i, 1));
         let eq_array = compare_with_eq(&arr, &needle_row, is_nested)?;
-        let is_contained = eq_array.true_count() > 0;
-        boolean_builder.append_value(is_contained)
+        boolean_builder.append_value(eq_array.true_count() > 0);
```
Comment (alamb) [inline datafusion/functions-nested/src/array_has.rs:217]: this is not a behavior change I don't think - just a refactor

**Review by alamb — APPROVED** [review]
This seems like an improvement to me -- that now DataFusion is at least consistent

Also since most of the array functions follow DuckDB I think picking to follow that is also a good idea. 

Thank you for your patience @Kimahriman

File: datafusion/functions-nested/src/array_has.rs (hunk 3 above)
Comment (Kimahriman) [reply datafusion/functions-nested/src/array_has.rs:217]: Yeah this was just matching the style of the other

**Comment by alamb** [comment]
🚀  thanks again!
