### PR TITLE
fix: import JoinTestType without triggering unused_qualifications lint

### LINKED ISSUE #13162: Address unused_qualifications lint overrides on JoinTestType enums in join_fuzz tests.
### Describe the bug

When the `unused_qualifications` lint was added in [Issue #13086](https://github.com/apache/datafusion/pull/13086) a lint allow was needed due to `JoinTestType` enums triggering the linter for [datafusion/core/tests/fuzz_cases/join_fuzz.rs](https://github.com/apache/datafusion/pull/13086/files#diff-f8330244c576c142337679ecbeeb99e9016c2c7c54d7bae492144374e138a0b7)

It would be preferable to import `JoinTestType` in a way that does not need a linter override.

### To Reproduce

Remove #[allow(unused_qualifications)] from datafusion/core/tests/fuzz_cases/join_fuzz.rs

### Expected behavior

Linter should succeed without the override.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by smarticen**
## Which issue does this PR close?

Closes #13162

## Rationale for this change

Same as in #13162

## What changes are included in this PR?

Remove #[allow(unused_qualifications)] and the unused qualifiers used in importing JoinTestType from datafusion/core/tests/fuzz_cases/join_fuzz.rs

## Are these changes tested?

tested via `cargo clippy`

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by alamb** [comment]
Thanks @smarticen  -- I triggered the CI to start

File: datafusion/core/tests/fuzz_cases/join_fuzz.rs [hunk 1]
```diff
@@ -191,51 +183,47 @@ async fn test_full_join_1k_filtered() {
...
-#[allow(unused_qualifications)]
 async fn test_semi_join_1k() {
     JoinFuzzTestCase::new(
         make_staggered_batches(1000),
         make_staggered_batches(1000),
         JoinType::LeftSemi,
         None,
     )
-    .run_test(&[JoinTestType::HjSmj, JoinTestType::NljHj], false)
+    .run_test(&[JoinTestType::HjSmj, NljHj], false)
```
Comment (findepi) [inline datafusion/core/tests/fuzz_cases/join_fuzz.rs:198]: Why would we want to import the left but not the right?

Maybe rather than removing the now-redundant `JoinTestType::` qualifications, we could remove `use` statements ?

Comment (alamb) [reply datafusion/core/tests/fuzz_cases/join_fuzz.rs:198]: I agree that it is strange for one variant to be qualified and one variant to be unqualified (aka `use`)

Perhaps we could either remove this `use` statement:

```rust
use crate::fuzz_cases::join_fuzz::JoinTestType::NljHj;
```

Or change it to

```rust
use crate::fuzz_cases::join_fuzz::JoinTestType::{HjSmj, NljHj};
```

**Review by alamb — APPROVED** [review]
Thank you @smarticen and thank you @findepi  for the review

I think this PR is an improvement over what is on `main` and thus could be merged. However, I think it would be even better if we implemented @findepi 's suggestion https://github.com/apache/datafusion/pull/13170/files#r1821470775 (which we can do as a follow on PR too)

File: datafusion/core/tests/fuzz_cases/join_fuzz.rs (hunk 1 above)
Comment (smarticen) [reply datafusion/core/tests/fuzz_cases/join_fuzz.rs]: @findepi @alamb Thanks for your review, I agree with you.
I will remove this `use` statement.

**Review by alamb — APPROVED** [review]
this is awesome. Thank you @smarticen -- and thank you for the suggestion @findepi

**Comment by alamb** [comment]
🚀

**Comment by findepi** [comment]
thanks!
