### PR TITLE
Correct implementations of `NullableInterval::and` and `NullableInterval::or`.

### LINKED ISSUE #18626: `NullableInterval::apply_operator` returns incorrect values for `Operator::And` and `Operator::Or`
### Describe the bug

The current implementation of `apply_operator` does not implement all possible cases of 'and' and 'or' correctly

### To Reproduce

There are quite a few cases that are not correct. One example is

```
let t = NullableInterval::NotNull { values: Interval::CERTAINLY_TRUE };
let u = NullableInterval::Null { datatype: DataType::Boolean };
t.apply_operator(&Operator::Or, &u).unwrap();
```

In SQL `true OR NULL` evaluates to `true`, so this should return the same value as `t`. In practice the same value as `u` is returned.

### Expected behavior

The interval arithmetic for boolean `NullableInterval` matches SQLs boolean arithmetic.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pepijnve**
## Which issue does this PR close?

- Closes #18626.

## Rationale for this change

The boolean interval arithmetic implemented by `NullableInterval` should match that of SQL.

## What changes are included in this PR?

- Add unit tests covering all possible permutations of `and`, `or` and `not` on `NullableInterval`
- Add `NullableInterval` constants for boolean intervals
- Add `NullableInterval::and` and `NullableInterval::or` implementations that match SQL
- Delegate to `and` and `or` in `NullableInterval::apply_operator`

## Are these changes tested?

Yes, tests have been added that cover all possible combinations

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/expr-common/src/interval_arithmetic.rs [hunk 1]
```diff
@@ -1756,27 +1794,31 @@ impl NullableInterval {
 
     /// Return true if the value is definitely true (and not null).
     pub fn is_certainly_true(&self) -> bool {
-        match self {
-            Self::Null { .. } | Self::MaybeNull { .. } => false,
-            Self::NotNull { values } => values == &Interval::CERTAINLY_TRUE,
-        }
+        self == &Self::TRUE
```
Comment (alamb) [inline datafusion/expr-common/src/interval_arithmetic.rs:1797]: while your new implementations are simpler, I think they are equivalent to the old ones

Or am I missing something here?

File: datafusion/expr-common/src/interval_arithmetic.rs [hunk 2]
```diff
@@ -4226,4 +4327,555 @@ mod tests {
...
+            ),
+            (
+                NullableInterval::UNKNOWN,
+                NullableInterval::TRUE,
+                NullableInterval::UNKNOWN,
+            ),
+            (
+                NullableInterval::UNKNOWN,
+                NullableInterval::FALSE,
+                NullableInterval::FALSE,
```
Comment (alamb) [inline datafusion/expr-common/src/interval_arithmetic.rs:4412]: 👍

File: datafusion/expr-common/src/interval_arithmetic.rs [hunk 3]
```diff
@@ -1738,6 +1738,44 @@ impl From<ScalarValue> for NullableInterval {
...
+        values: Interval::CERTAINLY_FALSE,
+    };
+
+    /// An interval that only contains 'true'.
+    pub const TRUE: Self = NullableInterval::NotNull {
+        values: Interval::CERTAINLY_TRUE,
+    };
+
+    /// An interval that only contains 'unknown' (boolean null).
+    pub const UNKNOWN: Self = NullableInterval::Null {
```
Comment (alamb) [inline datafusion/expr-common/src/interval_arithmetic.rs:1752]: I found this wording confusing (as I do much of this tri-state logic) because we "know" something about this interval -- that it is null. So it is a known unknown 🤔 

Maybe we could call this `NULL` or `ONLY_NULL`  or something to make it less confusing

File: datafusion/expr-common/src/interval_arithmetic.rs [hunk 4]
```diff
@@ -1738,6 +1738,44 @@ impl From<ScalarValue> for NullableInterval {
...
+
+    /// An interval that only contains 'false' and 'unknown'.
+    pub const FALSE_OR_UNKNOWN: Self = NullableInterval::MaybeNull {
+        values: Interval::CERTAINLY_FALSE,
+    };
+
+    /// An interval that contains all possible boolean values: 'true', 'false' and 'unknown'.
+    ///
+    /// Note that this is different from [Interval::UNCERTAIN] which only contains 'true' and 'false'.
+    pub const UNCERTAIN: Self = NullableInterval::MaybeNull {
```
Comment (alamb) [inline datafusion/expr-common/src/interval_arithmetic.rs:1775]: I personally found it hard to keep track of how UNCERTAIN differed from UNKNOWN and the other enums

Maybe we could name it something like `TRUE_OR_FALSE_OR_NULL` (even though that is a mouthful it is the most explicit)

**Comment by pepijnve** [comment]
If you comment out the `and` and `or` special cases in `apply_operator` you'll see the incorrect results.

File: datafusion/expr-common/src/interval_arithmetic.rs (hunk 3 above)
Comment (pepijnve) [reply datafusion/expr-common/src/interval_arithmetic.rs:1752]: For better or worse 'unknown' is the common term in three-value logic and is what `IS UNKNOWN` refers to. See https://en.wikipedia.org/wiki/Three-valued_logic. I did find usage of 'uncertain' in Oracle documentation as well though https://docs.oracle.com/html/E79061_01/Content/Reference/Truth_tables.htm.

`NULL` is a bit more generic in the sense that `UNKNOWN` is specifically a boolean, while `NULL` can be any typed.

I'll admit it's hard to name these things properly and it's rather unfortunate that `Interval::UNCERTAIN` already exists.

File: datafusion/expr-common/src/interval_arithmetic.rs (hunk 1 above)
Comment (pepijnve) [reply datafusion/expr-common/src/interval_arithmetic.rs:1797]: Nope, just simpler and more self explanatory.

File: datafusion/expr-common/src/interval_arithmetic.rs (hunk 4 above)
Comment (pepijnve) [reply datafusion/expr-common/src/interval_arithmetic.rs:1775]: Happy to change this to whatever you prefer.

My rationale FWIW was:
- `TRUE`, `FALSE`, and `UNKNOWN` are individual values in the SQL 3VL
- Besides those there are sets with more than one value: `TRUE | FALSE`, `TRUE | UNKNOWN`, `FALSE | UNKNOWN`, `TRUE | FALSE | UNKNOWN`.
- I went for `UNCERTAIN` to make a parallel with `Interval` where `UNCERTAIN` covers all possible values, but as I was writing the doc comments I did wonder if this was a good idea or not. `TRUE_OR_FALSE_OR_NULL`/`UNCERTAIN` could also by `ANY_TRUTH_VALUE`, but maybe that's too mathematically minded.

File: datafusion/expr-common/src/interval_arithmetic.rs (hunk 3 above)
Comment (pepijnve) [reply datafusion/expr-common/src/interval_arithmetic.rs:1752]: Finally got me a copy of the SQL spec. The spec says the following:

> The Boolean data type comprises the distinct truth values True and False. Unless prohibited by a NOT
NULL constraint, the Boolean data type also supports the truth value Unknown as the null value. This
specification does not make a distinction between the null value of the Boolean data type and the truth
value Unknown that is the result of an SQL `<predicate>`, `<search condition>`, or `<boolean value expression>`; they may be used interchangeably to mean exactly the same thing.

So the three truth values are name 'True', 'False' and 'Unknown'. And 'Unknown' is specifically equivalent to boolean null.

I wouldn't call 'boolean unknown' just plain 'null' since that's much broader.

File: datafusion/expr-common/src/interval_arithmetic.rs (hunk 4 above)
Comment (alamb) [reply datafusion/expr-common/src/interval_arithmetic.rs:1775]: I suppose consistency makes sense to me

File: datafusion/expr-common/src/interval_arithmetic.rs (hunk 3 above)
Comment (pepijnve) [reply datafusion/expr-common/src/interval_arithmetic.rs:1752]: This little bit from the BNF might also help

```
<boolean test> ::= <boolean primary> [ IS [ NOT ] <truth value> ]
<truth value> ::= TRUE | FALSE | UNKNOWN
```

**Comment by alamb** [comment]
> If you comment out the `and` and `or` special cases in `apply_operator` you'll see the incorrect results.

In case anyone else is curious:
```

thread 'interval_arithmetic::tests::nullable_and_test' (25123332) panicked at datafusion/expr-common/src/interval_arithmetic.rs:4580:13:
assertion `left == right` failed: Failed for NullableInterval: [false, false] AND NullableInterval: {NULL}
  left: Null { datatype: Boolean }
 right: NotNull { values: Interval { lower: Boolean(false), upper: Boolean(false) } }

...

thread 'interval_arithmetic::tests::nullable_or_test' (25123334) panicked at datafusion/expr-common/src/interval_arithmetic.rs:4842:13:
assertion `left == right` failed: Failed for NullableInterval: [true, true] OR NullableInterval: {NULL}
  left: Null { datatype: Boolean }
 right: NotNull { values: Interval { lower: Boolean(true), upper: Boolean(true) } }
```

File: datafusion/expr-common/src/interval_arithmetic.rs (hunk 3 above)
Comment (alamb) [reply datafusion/expr-common/src/interval_arithmetic.rs:1752]: There are a lot of things I don't like about the SQL spec, and this is one of them, FWIW

The concept of `NULL` is already quite confusing to everyone, so also calling it a different name, `UNKNOWN` I don't think made it any easier to understand 😆

**Comment by pepijnve** [comment]
> In case anyone else is curious:

There's quite a few more since the test stops at the first failure. I had logged just one example as repro in the issue for brevity's sake. In general `unknown and|or true|false` handling was not correct.

**Comment by pepijnve** [comment]
I didn't mean to be snarky about this and give you homework btw. Here's the full list:

**AND**
```
NullableInterval: [false, false] AND NullableInterval: {NULL} should be NullableInterval: [false, false]; was NullableInterval: {NULL}
NullableInterval: [false, false] AND NullableInterval: [true, true] U {NULL} should be NullableInterval: [false, false]; was NullableInterval: [false, false] U {NULL}
NullableInterval: [false, false] AND NullableInterval: [false, false] U {NULL} should be NullableInterval: [false, false]; was NullableInterval: [false, false] U {NULL}
NullableInterval: [false, false] AND NullableInterval: [false, true] U {NULL} should be NullableInterval: [false, false]; was NullableInterval: [false, false] U {NULL}
NullableInterval: {NULL} AND NullableInterval: [false, false] should be NullableInterval: [false, false]; was NullableInterval: {NULL}
NullableInterval: {NULL} AND NullableInterval: [false, true] should be NullableInterval: [false, false] U {NULL}; was NullableInterval: {NULL}
NullableInterval: {NULL} AND NullableInterval: [false, false] U {NULL} should be NullableInterval: [false, false] U {NULL}; was NullableInterval: {NULL}
NullableInterval: {NULL} AND NullableInterval: [false, true] U {NULL} should be NullableInterval: [false, false] U {NULL}; was NullableInterval: {NULL}
NullableInterval: [false, true] U {NULL} AND NullableInterval: [false, false] should be NullableInterval: [false, false]; was NullableInterval: [false, false] U {NULL}
NullableInterval: [false, true] U {NULL} AND NullableInterval: {NULL} should be NullableInterval: [false, false] U {NULL}; was NullableInterval: {NULL}
NullableInterval: [false, true] AND NullableInterval: {NULL} should be NullableInterval: [false, false] U {NULL}; was NullableInterval: {NULL}
NullableInterval: [true, true] U {NULL} AND NullableInterval: [false, false] should be NullableInterval: [false, false]; was NullableInterval: [false, false] U {NULL}
NullableInterval: [false, false] U {NULL} AND NullableInterval: [false, false] should be NullableInterval: [false, false]; was NullableInterval: [false, false] U {NULL}
NullableInterval: [false, false] U {NULL} AND NullableInterval: {NULL} should be NullableInterval: [false, false] U {NULL}; was NullableInterval: {NULL}
```

**OR**
```
NullableInterval: [true, true] OR NullableInterval: {NULL} should be NullableInterval: [true, true]; was NullableInterval: {NULL}
NullableInterval: [true, true] OR NullableInterval: [true, true] U {NULL} should be NullableInterval: [true, true]; was NullableInterval: [true, true] U {NULL}
NullableInterval: [true, true] OR NullableInterval: [false, false] U {NULL} should be NullableInterval: [true, true]; was NullableInterval: [true, true] U {NULL}
NullableInterval: [true, true] OR NullableInterval: [false, true] U {NULL} should be NullableInterval: [true, true]; was NullableInterval: [true, true] U {NULL}
NullableInterval: {NULL} OR NullableInterval: [true, true] should be NullableInterval: [true, true]; was NullableInterval: {NULL}
NullableInterval: {NULL} OR NullableInterval: [false, true] should be NullableInterval: [true, true] U {NULL}; was NullableInterval: {NULL}
NullableInterval: {NULL} OR NullableInterval: [true, true] U {NULL} should be NullableInterval: [true, true] U {NULL}; was NullableInterval: {NULL}
NullableInterval: {NULL} OR NullableInterval: [false, true] U {NULL} should be NullableInterval: [true, true] U {NULL}; was NullableInterval: {NULL}
NullableInterval: [false, true] U {NULL} OR NullableInterval: [true, true] should be NullableInterval: [true, true]; was NullableInterval: [true, true] U {NULL}
NullableInterval: [false, true] U {NULL} OR NullableInterval: {NULL} should be NullableInterval: [true, true] U {NULL}; was NullableInterval: {NULL}
NullableInterval: [false, true] OR NullableInterval: {NULL} should be NullableInterval: [true, true] U {NULL}; was NullableInterval: {NULL}
NullableInterval: [true, true] U {NULL} OR NullableInterval: [true, true] should be NullableInterval: [true, true]; was NullableInterval: [true, true] U {NULL}
NullableInterval: [true, true] U {NULL} OR NullableInterval: {NULL} should be NullableInterval: [true, true] U {NULL}; was NullableInterval: {NULL}
NullableInterval: [false, false] U {NULL} OR NullableInterval: [true, true] should be NullableInterval: [true, true]; was NullableInterval: [true, true] U {NULL}
```

File: datafusion/expr-common/src/interval_arithmetic.rs (hunk 3 above)
Comment (pepijnve) [reply datafusion/expr-common/src/interval_arithmetic.rs:1752]: It makes sense to the logician in me 😄 Admittedly, last time I studied logic theory is something like 25 years ago, but something seems to have stuck.

Comment (pepijnve) [reply datafusion/expr-common/src/interval_arithmetic.rs:1752]: @alamb I was doing some research on 3VL and came across https://www.logic.at/multlog/kleene.pdf. If you're not a fan of `unknown`, I'm sure you'll love the name/symbol that's used in this paper: `*` 😄

https://logic.dougowings.net/doc/logics/k3.html speaks of 'neither true nor false'
https://builds.openlogicproject.org/content/many-valued-logic/three-valued-logics/kleene.pdf uses both 'undefined' and 'unknown'

All the way to the original source at https://www.jstor.org/stable/2267778 where Kleene uses 'u' for 'undefined'.

Comment (alamb) [reply datafusion/expr-common/src/interval_arithmetic.rs:1752]: Impressive research (though a sad result 😆 )

Comment (alamb) [reply datafusion/expr-common/src/interval_arithmetic.rs:1752]: To be clear what I think is a disservice is to use the terms `UNKNOWN` and the term `NULL` and the  term  uncertain  🤯  -- using the same term consistently I think would make the topic easier to understand

(this is not something you or I are going to change, I realize, I am just keyboard venting)

File: datafusion/expr-common/src/interval_arithmetic.rs (hunk 4 above)
Comment (pepijnve) [reply datafusion/expr-common/src/interval_arithmetic.rs:1775]: @alamb I was wondering if we might want to consider renaming the `Interval` constants. I think this mapping would be nicer since they match exactly with their `NullableInterval` equivalents then in both name and semantics and we're also at least using the SQL terminology consistently.

- `Interval::CERTAINLY_TRUE` -> `Interval::TRUE`
- `Interval::CERTAINLY_FALSE` -> `Interval::FALSE`
- `Interval::UNCERTAIN` -> `Interval::TRUE_OR_FALSE`

For `NullableInterval::UNCERTAIN` I'm inclined to go for `ANY_TRUTH_VALUE` rather than `TRUE_OR_FALSE_OR_UNKNOWN` just to keep it somewhat short.

For backwards compatibility it might be useful to retain the old constants and mark them deprecated. Not sure what the DataFusion policy on stuff like that is.

**Comment by alamb** [comment]
Thanks again @pepijnve

File: datafusion/expr-common/src/interval_arithmetic.rs (hunk 3 above)
Comment (pepijnve) [reply datafusion/expr-common/src/interval_arithmetic.rs:1752]: I see you've already gone ahead and merged, so I just missed it, but for consistency see https://github.com/apache/datafusion/pull/18625#discussion_r2518641184

I can make a followup for that if you like.

**Comment by alamb** [comment]
> I didn't mean to be snarky about this and give you homework btw. Here's the full list:


No worries! I did not take it that way

File: datafusion/expr-common/src/interval_arithmetic.rs (hunk 4 above)
Comment (alamb) [reply datafusion/expr-common/src/interval_arithmetic.rs:1775]: > For NullableInterval::UNCERTAIN I'm inclined to go for ANY_TRUTH_VALUE rather than TRUE_OR_FALSE_OR_UNKNOWN just to keep it somewhat short.

I defer to you -- I can also live with `UNCERTAIN` (my personal distaste for  SQL NULL shoudn't cause you to do more work 😆 )


> @alamb I was wondering if we might want to consider renaming the Interval constants. I think this mapping would be nicer since they match exactly with their NullableInterval equivalents then in both name and semantics and we're also at least using the SQL terminology consistently.

I agree it would be a nice change

> For backwards compatibility it might be useful to retain the old constants and mark them deprecated. Not sure what the DataFusion policy on stuff like that is.

Yes I agree that would be best and is consistent with the API health policy is here: https://datafusion.apache.org/contributor-guide/api-health.html

Comment (pepijnve) [reply datafusion/expr-common/src/interval_arithmetic.rs:1775]: I'll go for it then. I wasn't a fan of 'uncertain' either because it's vague and hints at 'unknown'.
