### PR TITLE
fix: graceful NULL and type error handling in array functions

### LINKED ISSUE #14451: Proper NULL handling in array functions
### Describe the bug

The following array functions do not properly handle NULL input, they either return an error or panic (non-exhaustive):

- `array_sort`
- `array_replace`
- `array_replace_all`
- `array_replace_n`
- `array_resize`

Discovered in https://github.com/apache/datafusion/pull/14289

## Scalar input

```
> SELECT array_sort([1,2,3], NULL);
Internal error: could not cast value to arrow_array::array::byte_array::GenericByteArray<arrow_array::types::GenericStringType<i32>>.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker

> SELECT array_resize([1,2,3], NULL, 0);
Internal error: could not cast value to arrow_array::array::primitive_array::PrimitiveArray<arrow_array::types::Int64Type>.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker

> SELECT array_replace([1,2,3], NULL, NULL);
thread 'main' panicked at /home/joe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-data-54.0.0/src/transform/mod.rs:418:13:
assertion `left == right` failed: Arrays with inconsistent types passed to MutableArrayData
  left: Int64
 right: Null
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/core/src/panicking.rs:76:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /home/joe/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:373:5
   4: arrow_data::transform::MutableArrayData::with_capacities
             at /home/joe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-data-54.0.0/src/transform/mod.rs:418:13
   5: datafusion_functions_nested::replace::general_replace
             at /home/joe/Projects/datafusion/datafusion/functions-nested/src/replace.rs:303:23
   6: datafusion_functions_nested::replace::array_replace_inner
             at /home/joe/Projects/datafusion/datafusion/functions-nested/src/replace.rs:394:13
   7: core::ops::function::Fn::call
             at /home/joe/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79:5
   8: datafusion_functions_nested::utils::make_scalar_function::{{closure}}
             at /home/joe/Projects/datafusion/datafusion/functions-nested/src/utils.rs:72:22
   9: <datafusion_functions_nested::replace::ArrayReplace as datafusion_expr::udf::ScalarUDFImpl>::invoke_batch
             at /home/joe/Projects/datafusion/datafusion/functions-nested/src/replace.rs:123:9
  10: datafusion_expr::udf::ScalarUDFImpl::invoke_with_args
             at /home/joe/Projects/datafusion/datafusion/expr/src/udf.rs:643:9
  11: datafusion_expr::udf::ScalarUDF::invoke_with_args
             at /home/joe/Projects/datafusion/datafusion/expr/src/udf.rs:237:9
  12: <datafusion_physical_expr::scalar_function::ScalarFunctionExpr as datafusion_physical_expr_common::physical_expr::PhysicalExpr>::evaluate
             at /home/joe/Projects/datafusion/datafusion/physical-expr/src/scalar_function.rs:195:22
  13: datafusion_optimizer::simplify_expressions::expr_simplifier::ConstEvaluator::evaluate_to_scalar
             at /home/joe/Projects/datafusion/datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:639:29
  14: <datafusion_optimizer::simplify_expressions::expr_simplifier::ConstEvaluator as datafusion_common::tree_node::TreeNodeRewriter>::f_up
             at /home/joe/Projects/datafusion/datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:529:30
  15: datafusion_common::tree_node::TreeNode::rewrite::{{closure}}::{{closure}}
             at /home/joe/Projects/datafusion/datafusion/common/src/tree_node.rs:183:13
  16: datafusion_common::tree_node::Transformed<T>::transform_parent
             at /home/joe/Projects/datafusion/datafusion/common/src/tree_node.rs:763:44
  17: datafusion_common::tree_node::TreeNode::rewrite::{{closure}}
             at /home/joe/Projects/datafusion/datafusion/common/src/tree_node.rs:28:9
  18: stacker::maybe_grow
             at /home/joe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.17/src/lib.rs:55:9
  19: datafusion_common::tree_node::TreeNode::rewrite
             at /home/joe/Projects/datafusion/datafusion/common/src/tree_node.rs:177:50
  20: datafusion_optimizer::simplify_expressions::expr_simplifier::ExprSimplifier<S>::simplify_with_cycle_count
             at /home/joe/Projects/datafusion/datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:211:17
  ...
  71: tokio::runtime::runtime::Runtime::block_on
             at /home/joe/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.43.0/src/runtime/runtime.rs:340:13
  72: datafusion_cli::main
             at ./src/main.rs:131:5
  73: core::ops::function::FnOnce::call_once
             at /home/joe/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
killed

Process finished with exit code 9
```

## Array Input
```
> CREATE TABLE t (a int[], b int, c int);
0 row(s) fetched. 
Elapsed 0.004 seconds.

> INSERT INTO t VALUES ([1,2,3], 1, 2), (NULL, 1, 2), ([1,2,3], NULL, 2), ([1,2,3], 1, NULL);
+-------+
| count |
+-------+
| 4     |
+-------+
1 row(s) fetched. 
Elapsed 0.006 seconds.

> SELECT array_sort(a, b, c) FROM t;
Internal error: could not cast value to arrow_array::array::byte_array::GenericByteArray<arrow_array::types::GenericStringType<i32>>.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
> SELECT array_resize(a, b, c) FROM t;
Internal error: could not cast value to arrow_array::array::primitive_array::PrimitiveArray<arrow_array::types::Int64Type>.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

### Expected behavior

The functions should either return NULL or correctly handle the NULL input without panicking.

### Additional context

I briefly investigated the functions and found the following:

## `array_sort`

To fix this function we can add `NullHandling::Propagate` to the`impl ScalarUDFImpl for ArraySort`. Then we also have to update `array_sort_inner` to return NULL on NULL inputs.

## `array_resize`

I haven't looked into this one yet, but I think the solution is probably similar to `array_sort`.

## `array_replace`

Note this applies to `array_replace_all` and `array_replace_n`.

This function actually does not want to propagate NULLs, it should be able to find NULL elements and replace with NULL elements. When the inputs are `ArrayRef`s then actually everything works correctly, it's only when the inputs are `Scalar` that things break. The issue is that the functions accepts `DataType::Null` instead of a null value for the list element type. Then we get type errors when trying to use the `DataType::Null` with a typed list.

I believe if we updated the signature from `Signature::any(3, Volatility::Immutable)` to something that includes type information then we would fix the panic. However, we face a familiar problem that there is no way to represent `(list, element-type, element-type, i64)` with the current `Signature` struct.

### PR DESCRIPTION
**Pull request by alan910127**
## Which issue does this PR close?

- Closes #14451.

## Rationale for this change

This change ensures that array functions handle `NULL` and incorrect argument types gracefully, preventing unexpected failures or internal errors showing up to the user.

## What changes are included in this PR?

Added `ArrayFunctionArgument::DataType(data_type)` variant for array functions to define an argument of a specific type.

### `array_sort`

- Returns NULL when either `desc` or `nulls_first` is NULL.
- There's no incorrect input type since every type can be coerced into `Utf8`

**NULL inputs:**
```
> select array_sort([1,2,3]);
+----------------------------------------------------+
| array_sort(make_array(Int64(1),Int64(2),Int64(3))) |
+----------------------------------------------------+
| [1, 2, 3]                                          |
+----------------------------------------------------+
1 row(s) fetched.
Elapsed 0.008 seconds.

> select array_sort([1,2,3], NULL);
+---------------------------------------------------------+
| array_sort(make_array(Int64(1),Int64(2),Int64(3)),NULL) |
+---------------------------------------------------------+
| NULL                                                    |
+---------------------------------------------------------+
1 row(s) fetched.
Elapsed 0.007 seconds.

> select array_sort([1,2,3], NULL, 'NULLS FIRST');
+-----------------------------------------------------------------------------+
| array_sort(make_array(Int64(1),Int64(2),Int64(3)),NULL,Utf8("NULLS FIRST")) |
+-----------------------------------------------------------------------------+
| NULL                                                                        |
+-----------------------------------------------------------------------------+
1 row(s) fetched.
Elapsed 0.005 seconds.

> select array_sort([1,2,3], 'DESC', NULL);
+----------------------------------------------------------------------+
| array_sort(make_array(Int64(1),Int64(2),Int64(3)),Utf8("DESC"),NULL) |
+----------------------------------------------------------------------+
| NULL                                                                 |
+----------------------------------------------------------------------+
1 row(s) fetched.
Elapsed 0.007 seconds.

> select array_sort([1,2,3], NULL, NULL);
+--------------------------------------------------------------+
| array_sort(make_array(Int64(1),Int64(2),Int64(3)),NULL,NULL) |
+--------------------------------------------------------------+
| NULL                                                         |
+--------------------------------------------------------------+
1 row(s) fetched.
Elapsed 0.008 seconds.
```

**Incorrect type of inputs:**
N/A

### `array_replace`, `array_replace_n`, `array_replace_all`

- Treat NULLs as elements.
- Internal coercion errors are not handled yet. Don't know if it should be handled in this PR

**NULL inputs:**
```
> select array_replace([1,2,3,NULL],NULL,4);
+--------------------------------------------------------------------------+
| array_replace(make_array(Int64(1),Int64(2),Int64(3),NULL),NULL,Int64(4)) |
+--------------------------------------------------------------------------+
| [1, 2, 3, 4]                                                             |
+--------------------------------------------------------------------------+
1 row(s) fetched.
Elapsed 0.008 seconds.

> select array_replace([1,2,3,NULL],2,NULL);
+--------------------------------------------------------------------------+
| array_replace(make_array(Int64(1),Int64(2),Int64(3),NULL),Int64(2),NULL) |
+--------------------------------------------------------------------------+
| [1, NULL, 3, NULL]                                                       |
+--------------------------------------------------------------------------+
1 row(s) fetched.
Elapsed 0.008 seconds.
```

**incorrect type of inputs:**
```
> select array_replace([1,2,3], 1, true);
Error during planning: Internal error: Function 'array_replace' does not support coercion from Int64 to Boolean.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker No function matches the given name and argument types 'array_replace(List(Field { name: "item", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), Int64, Boolean)'. You might need to add explicit type casts.
        Candidate functions:
        array_replace(array, element, element)
```

### `array_resize`

- If `size` is NULL, returns an empty array. If `value` is NULL, fill the new slots to be NULL.
- Incorrect types of arguments returns plan errors instead of internal errors.

**NULL inputs:**
```
> select array_resize([1,2,3], NULL);
+-----------------------------------------------------------+
| array_resize(make_array(Int64(1),Int64(2),Int64(3)),NULL) |
+-----------------------------------------------------------+
| []                                                        |
+-----------------------------------------------------------+
1 row(s) fetched.
Elapsed 0.005 seconds.

> select array_resize([1,2,3], NULL, NULL);
+----------------------------------------------------------------+
| array_resize(make_array(Int64(1),Int64(2),Int64(3)),NULL,NULL) |
+----------------------------------------------------------------+
| []                                                             |
+----------------------------------------------------------------+
1 row(s) fetched.
Elapsed 0.003 seconds.

> select array_resize([1,2,3], 5, NULL);
+--------------------------------------------------------------------+
| array_resize(make_array(Int64(1),Int64(2),Int64(3)),Int64(5),NULL) |
+--------------------------------------------------------------------+
| [1, 2, 3, NULL, NULL]                                              |
+--------------------------------------------------------------------+
1 row(s) fetched.
Elapsed 0.006 seconds.
```

**incorrect type of inputs:**
```
> select array_resize([1,2,3], 'invalid', NULL);
Error during planning: Failed to coerce arguments to satisfy a call to 'array_resize' function: coercion from [List(Field { name: "item", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), Utf8, Null] to the signature OneOf([ArraySignature(Array { arguments: [Array, Index], array_coercion: Some(FixedSizedListToList) }), ArraySignature(Array { arguments: [Array, Index, Element], array_coercion: Some(FixedSizedListToList) })]) failed No function matches the given name and argument types 'array_resize(List(Field { name: "item", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), Utf8, Null)'. You might need to add explicit type casts.
        Candidate functions:
        array_resize(array, index)
        array_resize(array, index, element)
> select array_resize([1,2,3], 5, true);
Error during planning: Failed to coerce arguments to satisfy a call to 'array_resize' function: coercion from [List(Field { name: "item", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), Int64, Boolean] to the signature OneOf([ArraySignature(Array { arguments: [Array, Index], array_coercion: Some(FixedSizedListToList) }), ArraySignature(Array { arguments: [Array, Index, Element], array_coercion: Some(FixedSizedListToList) })]) failed No function matches the given name and argument types 'array_resize(List(Field { name: "item", data_type: Int64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }), Int64, Boolean)'. You might need to add explicit type casts.
        Candidate functions:
        array_resize(array, index)
        array_resize(array, index, element)
```

## Are these changes tested?

Tests for `array_sort` with NULL and incorrect inputs are added in `array.slt`. Other functions are already tested via `arrays_values` in `sqllogictest`. If additional tests are needed, please let me know.

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/expr-common/src/signature.rs [hunk 1]
```diff
@@ -358,6 +358,8 @@ pub enum ArrayFunctionArgument {
     /// An argument of type List/LargeList/FixedSizeList. All Array arguments must be coercible
     /// to the same type.
     Array,
+    // An arbitrary data type.
+    DataType(DataType),
```
Comment (jayzhan211) [inline datafusion/expr-common/src/signature.rs:362]: How about `String`

Comment (alan910127) [reply datafusion/expr-common/src/signature.rs:362]: that's fair, we probably don't need any other types

File: datafusion/functions-nested/src/sort.rs [hunk 2]
```diff
@@ -143,6 +169,13 @@ pub fn array_sort_inner(args: &[ArrayRef]) -> Result<ArrayRef> {
         return exec_err!("array_sort expects one to three arguments");
     }
 
+    if args[1..].iter().any(|array| array.logical_null_count() > 0) {
+        return Ok(Arc::new(make_array(ArrayData::new_null(
```
Comment (jayzhan211) [inline datafusion/functions-nested/src/sort.rs:173]: You can use `new_null_array` here

File: datafusion/sqllogictest/test_files/array.slt [hunk 3]
```diff
@@ -2265,6 +2265,35 @@ select array_sort([]);
...
 
+# test with null arguments
+# expected error:
+# DataFusion error: Error during planning: Failed to coerce arguments to satisfy a call to 'array_sort' function: coercion from [Null] to the signature OneOf([ArraySignature(Array { arguments: [Array], array_coercion: None }), ArraySignature(Array { arguments: [Array, DataType(Utf8)], array_coercion: None }), ArraySignature(Array { arguments: [Array, DataType(Utf8), DataType(Utf8)], array_coercion: None })]) failed No function matches the given name and argument types 'array_sort(Null)'. You might need to add explicit type casts.
+#	Candidate functions:
+#	array_sort(array)
+#	array_sort(array, Utf8)
+#	array_sort(array, Utf8, Utf8)
+query error
+select array_sort(NULL);
```
Comment (jayzhan211) [inline datafusion/sqllogictest/test_files/array.slt:2276]: I think `Null` should be returned in this case?

Comment (jayzhan211) [reply datafusion/sqllogictest/test_files/array.slt:2276]:
```
D select array_sort(null);
┌──────────────────┐
│ array_sort(NULL) │
│      int32       │
├──────────────────┤
│                  │
└──────────────────┘
```

Comment (alan910127) [reply datafusion/sqllogictest/test_files/array.slt:2276]: I'm not pretty sure about this, but this seems like a better behavior.

Comment (alan910127) [reply datafusion/sqllogictest/test_files/array.slt:2276]: Since the the error is defined by `ArrayFunctionArgument::Array`, changing the behavior would change all of the array functions, is this acceptable? I will push this for now and we can revert it if this is not desired.

Comment (jayzhan211) [reply datafusion/sqllogictest/test_files/array.slt:2260]:
```
D select array_append(null, 1);
┌───────────────────────┐
│ array_append(NULL, 1) │
│        int32[]        │
├───────────────────────┤
│ [1]                   │
└───────────────────────┘
```

Need to be careful not to break other array functions behaviour

Comment (alan910127) [reply datafusion/sqllogictest/test_files/array.slt:2260]: it seems like they're already broken in current main branch :thinking:

```
❯ gsw upstream/main -d
HEAD is now at 6bfeb0272 fix: we are missing the unlimited case for bounded streaming when usi… (#14815)
❯ cargo run
DataFusion CLI v45.0.0
> select array_append(NULL, 1);
Error during planning: Failed to coerce arguments to satisfy a call to 'array_append' function: coercion from [Null, Int64] to the signature ArraySignature(Array { arguments: [Array, Element], array_coercion: Some(FixedSizedListToList) }) failed No function matches the given name and argument types 'array_append(Null, Int64)'. You might need to add explicit type casts.
        Candidate functions:
        array_append(array, element)
> select array_append(NULL, NULL);
Error during planning: Failed to coerce arguments to satisfy a call to 'array_append' function: coercion from [Null, Null] to the signature ArraySignature(Array { arguments: [Array, Element], array_coercion: Some(FixedSizedListToList) }) failed No function matches the given name and argument types 'array_append(Null, Null)'. You might need to add explicit type casts.
        Candidate functions:
        array_append(array, element)
> select array_concat(NULL, NULL);
Error during planning: The array_concat function can only accept list as the args.
```

Comment (alan910127) [reply datafusion/sqllogictest/test_files/array.slt:2260]: Should I fix it in this PR or open another issue for this?

Comment (jayzhan211) [reply datafusion/sqllogictest/test_files/array.slt:2260]: You can fix them in follow-on PR

File: datafusion/sqllogictest/test_files/array.slt [hunk 4]
```diff
@@ -2235,36 +2235,43 @@ select array_sort(make_array(1, 3, null, 5, NULL, -5)), array_sort(make_array(1,
 ----
 [NULL, NULL, -5, 1, 3, 5] [NULL, 1, 2, 3] [NULL, 3, 2, 1]
 
-query ?
+query error
```
Comment (jayzhan211) [inline datafusion/sqllogictest/test_files/array.slt:2238]: if there is null in the row, we return null.

File: datafusion/functions-nested/src/sort.rs [hunk 5]
```diff
@@ -143,6 +168,10 @@ pub fn array_sort_inner(args: &[ArrayRef]) -> Result<ArrayRef> {
         return exec_err!("array_sort expects one to three arguments");
     }
 
+    if args.iter().any(|array| array.logical_null_count() > 0) {
```
Comment (jayzhan211) [inline datafusion/functions-nested/src/sort.rs:171]: so actually we should remove this line

Comment (jayzhan211) [reply datafusion/functions-nested/src/sort.rs:171]: After removing this, array_sort(null) fail.

What you need to do is return DataType::List(Int32) in `array_valid_types`, i32 as the default type. Then you can get something like `ListArray[null]` as ArrayRef in `array_sort_inner`, this is null with datatype list. After that we can handle null case in `array_sort_inner` with returning it directly

Comment (alan910127) [reply datafusion/functions-nested/src/sort.rs:171]: I think we still need to check for `args[1..]` for null `desc` or `nulls_first`? but to be align with the sort options, I think checking `is_null(0)` should be enough.

Comment (alan910127) [reply datafusion/functions-nested/src/sort.rs:171]: I believe so does the third?

```
D select array_sort([1,2,3], 'desc', null);
┌────────────────────────────────────────────────────┐
│ array_sort(main.list_value(1, 2, 3), 'desc', NULL) │
│                       int32                        │
├────────────────────────────────────────────────────┤
│                        NULL                        │
└────────────────────────────────────────────────────┘
```

File: datafusion/sqllogictest/test_files/array.slt [hunk 6]
```diff
@@ -2546,8 +2568,10 @@ select array_append(column1, arrow_cast(make_array(1, 11, 111), 'FixedSizeList(3
 # DuckDB: [4]
 # ClickHouse: Null
 # Since they dont have the same result, we just follow Postgres, return error
-query error
+query ?
 select array_prepend(4, NULL);
+----
+[4]
```
Comment (alan910127) [inline datafusion/sqllogictest/test_files/array.slt:2595]: did I break this? 😢

File: datafusion/sqllogictest/test_files/array.slt [hunk 7]
```diff
@@ -5271,9 +5294,11 @@ NULL [3] [5]
 # array_ndims scalar function #1
 
 #follow PostgreSQL
-query error
+query I
 select
   array_ndims(null);
+----
+NULL
```
Comment (alan910127) [inline datafusion/sqllogictest/test_files/array.slt:5322]: and this?

File: datafusion/sqllogictest/test_files/array.slt (hunk 6 above)
Comment (jayzhan211) [reply datafusion/sqllogictest/test_files/array.slt:2595]: that is fine

File: datafusion/expr/src/type_coercion/functions.rs [hunk 8]
```diff
@@ -435,6 +436,10 @@ fn get_valid_types(
         match array_type {
             DataType::List(_) | DataType::LargeList(_) => Some(array_type.clone()),
             DataType::FixedSizeList(field, _) => Some(DataType::List(Arc::clone(field))),
+            DataType::Null => Some(DataType::List(Arc::new(Field::new_list_field(
+                DataType::Null,
```
Comment (jayzhan211) [inline datafusion/expr/src/type_coercion/functions.rs:440]: probably i64 or i32 is better

File: datafusion/functions-nested/src/resize.rs [hunk 9]
```diff
@@ -106,6 +127,7 @@ impl ScalarUDFImpl for ArrayResize {
         match &arg_types[0] {
             List(field) | FixedSizeList(field, _) => Ok(List(Arc::clone(field))),
             LargeList(field) => Ok(LargeList(Arc::clone(field))),
+            DataType::Null => Ok(DataType::Null),
```
Comment (jayzhan211) [inline datafusion/functions-nested/src/resize.rs:130]: convert to List(Int64) then we don't need to handle null

File: datafusion/expr/src/type_coercion/functions.rs (hunk 8 above)
Comment (alan910127) [reply datafusion/expr/src/type_coercion/functions.rs:440]: I was trying something like `array_append(null, [1])`, since only NULL is possible to be coerced to those types, I use List(Null) here

**Comment by alamb** [comment]
Marking as draft as I think this PR is no longer waiting on feedback. Please mark it as ready for review when it is ready for another look

File: datafusion/functions-nested/src/resize.rs (hunk 9 above)
Comment (alan910127) [reply datafusion/functions-nested/src/resize.rs]: It seems like this way is easier! I've updated.

File: datafusion/expr/src/type_coercion/functions.rs (hunk 8 above)
Comment (alan910127) [reply datafusion/expr/src/type_coercion/functions.rs]: Updated to i64 for now

File: datafusion/sqllogictest/test_files/array.slt [hunk 10]
```diff
@@ -2243,9 +2245,9 @@ select array_sort(column1, 'DESC', 'NULLS LAST') from arrays_values;
 [30, 29, 28, 27, 26, 25, 23, 22, 21, NULL]
 [40, 39, 38, 37, 35, 34, 33, 32, 31, NULL]
 NULL
-[50, 49, 48, 47, 46, 45, 44, 43, 42, 41]
-[60, 59, 58, 57, 56, 55, 54, 52, 51, NULL]
-[70, 69, 68, 67, 66, 65, 64, 63, 62, 61]
+[NULL, 50, 49, 48, 47, 46, 45, 44, 43, 42]
```
Comment (jayzhan211) [inline datafusion/sqllogictest/test_files/array.slt:2248]: This seems incorrect 🤔

File: datafusion/functions-nested/src/sort.rs [hunk 11]
```diff
@@ -175,6 +204,7 @@ pub fn array_sort_inner(args: &[ArrayRef]) -> Result<ArrayRef> {
     for i in 0..row_count {
         if list_array.is_null(i) {
             array_lengths.push(0);
+            arrays.push(new_null_array(list_array.value(i).data_type(), 1));
```
Comment (jayzhan211) [inline datafusion/functions-nested/src/sort.rs:207]: Remove this line fix the issue below.

for null case, you just need to make sure the offset append a single 0 and the null buffer append a null, that is why we `array_lengths.push(0) and append null`

Comment (alan910127) [reply datafusion/functions-nested/src/sort.rs]: oh, thank you so much! I think I did it wrong when dealing with `array_sort(NULL)`. I've pushed a new version, please take a look to check if that's the correct implementation.

**Review by jayzhan211 — APPROVED** [review]
👍🏻

**Comment by jayzhan211** [comment]
Thanks @alan910127
