### PR TITLE
Overflow in negate operator

### LINKED ISSUE #11076: Overflow bug in negate arithmetic operator (found by SQLancer)
### Describe the bug

The following statement should return an error instead of directly crash

```
DataFusion CLI v39.0.0
> select (- -9223372036854775808);
thread 'main' panicked at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/arith.rs:699:1:
attempt to negate with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Found by SQLancer https://github.com/apache/datafusion/issues/11030

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LorrensP-2158466**
## Which issue does this PR close?

Closes #11076. Tracking: #11078

## What changes are included in this PR?
Doing checked negations on scalarValue

## Are these changes tested?
With unit tests yes

## Are there any user-facing changes?
no

### CODE REVIEW

File: datafusion/common/src/scalar/mod.rs [hunk 1]
```diff
@@ -1177,40 +1185,103 @@ impl ScalarValue {
...
+                    format!("In negation of IntervalYearMonth({v})"),
+                )?)))
             }
             ScalarValue::IntervalDayTime(Some(v)) => {
                 let (days, ms) = IntervalDayTimeType::to_parts(*v);
-                let val = IntervalDayTimeType::make_value(-days, -ms);
+                let val = IntervalDayTimeType::make_value(
+                    neg_checked_with_ctx(
+                        days,
+                        format!("In negation of days {days} in IntervalDayTime"),
```
Comment (alamb) [inline datafusion/common/src/scalar/mod.rs:1203]: I think that calling these functions like this will  result in actually creating these error strings for each row, even if there is no error -- I think it is important to avoid that overhead.

I suspect it would be faster to use `map_err` like

```rust
let days = v.neg_checked()
  .map_err(|e| {
    DataFusionError::from(e)
      .context(format!("In negation of milliseconds {ms} in IntervalDayTime")))
  })?
```

The reason being that in that formulation the `format!` is part of a closure that is only called when there is an actual error

File: datafusion/common/src/scalar/mod.rs [hunk 2]
```diff
@@ -5494,6 +5566,69 @@ mod tests {
...
+                ScalarValue::Float16(Some(f16::MAX)),
+                ScalarValue::Float16(Some(f16::MIN)),
+            ),
+            (f32::MIN.into(), f32::MAX.into()),
+            (f32::MAX.into(), f32::MIN.into()),
+            (f64::MIN.into(), f64::MAX.into()),
+            (f64::MAX.into(), f64::MIN.into()),
+        ];
+        // skip float 16 because they aren't supported
+        for (test, expected) in float_cases.into_iter().skip(2) {
```
Comment (alamb) [inline datafusion/common/src/scalar/mod.rs:5626]: maybe we just shouldn't list float 16 at all 🤔 I think it might be more confusing to see them listed then skipped than simply not listed (or listed in a separate test that simply fails)

**Review by alamb — COMMENTED** [review]
Thank you @LorrensP-2158466  -- this looks good to me except for creating error messags on each row.

File: datafusion/common/src/scalar/mod.rs (hunk 1 above)
Comment (LorrensP-2158466) [reply datafusion/common/src/scalar/mod.rs:1203]: Yeah, I first tried that, but I didn't like repeating the same thing for every case. But this went over my head, I'll fix this back to `map_err`. Thanks for the tip!

File: datafusion/common/src/scalar/mod.rs (hunk 2 above)
Comment (LorrensP-2158466) [reply datafusion/common/src/scalar/mod.rs:5626]: Yeah I did this when filing #11083. Maybe it's cleaner to add a test that should fail on Float16 and when Float16 is supported, that test fails and the person making those changes knows to change the test.

**Review by alamb — APPROVED** [review]
👨‍🍳 👌  @LorrensP-2158466  -- very nice. Thank you for this improvement
