### PR TITLE
Fix clippy for Rust 1.84

### LINKED ISSUE #14061: Fix build issues on latest stable Rust toolchain (1.84)
### Describe the bug

1.84 was released today and /dev/rust_lint.sh does not currently pass under this release.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jonahgao**
## Which issue does this PR close?

Closes #14061.

## Are these changes tested?
Yes

## Are there any user-facing changes?
No

### CODE REVIEW

**Review by berkaysynnada — APPROVED** [review]
LGTM, thank you @jonahgao

**Comment by berkaysynnada** [comment]
@jonahgao does linter pass in your local after this change?

**Comment by jonahgao** [comment]
> @jonahgao does linter pass in your local after this change?

Yes, it passed. Do you encounter any issues?

**Comment by berkaysynnada** [comment]
> > @jonahgao does linter pass in your local after this change?
> 
> Yes, it passed. Do you encounter any issues?

 ```
 cargo clippy --all-targets --workspace --features avro,pyarrow -- -D warnings
    Checking ffi_module_interface v0.1.0 (/Users/berkaysahin/Desktop/datafusion/datafusion-examples/examples/ffi/ffi_module_interface)
    Checking datafusion-wasmtest v44.0.0 (/Users/berkaysahin/Desktop/datafusion/datafusion/wasmtest)
    Checking datafusion-ffi v44.0.0 (/Users/berkaysahin/Desktop/datafusion/datafusion/ffi)
    Checking datafusion-benchmarks v44.0.0 (/Users/berkaysahin/Desktop/datafusion/benchmarks)
error: unexpected `cfg` condition name: `wasm_bindgen_unstable_test_coverage`
  --> datafusion/wasmtest/src/lib.rs:47:1
   |
47 | #[wasm_bindgen]
   | ^^^^^^^^^^^^^^^
   |
   = help: expected names are: `clippy`, `debug_assertions`, `doc`, `docsrs`, `doctest`, `feature`, `fmt_debug`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `sanitize`, `sanitizer_cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, `target_has_atomic_equal_alignment`, `target_has_atomic_load_store`, `target_os`, `target_pointer_width`, `target_thread_local`, `target_vendor`, `tarpaulin`, `test`, `ub_checks`, `unix`, and `windows`
   = help: consider using a Cargo feature instead
   = help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
            [lints.rust]
            unexpected_cfgs = { level = "warn", check-cfg = ['cfg(wasm_bindgen_unstable_test_coverage)'] }
   = help: or consider adding `println!("cargo::rustc-check-cfg=cfg(wasm_bindgen_unstable_test_coverage)");` to the top of the `build.rs`
   = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
   = note: `-D unexpected-cfgs` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(unexpected_cfgs)]`
   = note: this error originates in the attribute macro `wasm_bindgen` (in Nightly builds, run with -Z macro-backtrace for more info)

error: unexpected `cfg` condition name: `wasm_bindgen_unstable_test_coverage`
  --> datafusion/wasmtest/src/lib.rs:67:1
   |
67 | #[wasm_bindgen]
   | ^^^^^^^^^^^^^^^
   |
   = help: consider using a Cargo feature instead
   = help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
            [lints.rust]
            unexpected_cfgs = { level = "warn", check-cfg = ['cfg(wasm_bindgen_unstable_test_coverage)'] }
   = help: or consider adding `println!("cargo::rustc-check-cfg=cfg(wasm_bindgen_unstable_test_coverage)");` to the top of the `build.rs`
   = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
   = note: this error originates in the attribute macro `wasm_bindgen` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `datafusion-wasmtest` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `datafusion-wasmtest` (lib test) due to 2 previous errors
```

These unexpected cfg conditions are changing at each try. I couldn't quickly understand the reason of these errors.

**Comment by mbrobbel** [comment]
> > > @jonahgao does linter pass in your local after this change?
> > 
> > 
> > Yes, it passed. Do you encounter any issues?
> 
> ```
> cargo clippy --all-targets --workspace --features avro,pyarrow -- -D warnings
>    Checking ffi_module_interface v0.1.0 (/Users/berkaysahin/Desktop/datafusion/datafusion-examples/examples/ffi/ffi_module_interface)
>    Checking datafusion-wasmtest v44.0.0 (/Users/berkaysahin/Desktop/datafusion/datafusion/wasmtest)
>    Checking datafusion-ffi v44.0.0 (/Users/berkaysahin/Desktop/datafusion/datafusion/ffi)
>    Checking datafusion-benchmarks v44.0.0 (/Users/berkaysahin/Desktop/datafusion/benchmarks)
> error: unexpected `cfg` condition name: `wasm_bindgen_unstable_test_coverage`
>  --> datafusion/wasmtest/src/lib.rs:47:1
>   |
> 47 | #[wasm_bindgen]
>   | ^^^^^^^^^^^^^^^
>   |
>   = help: expected names are: `clippy`, `debug_assertions`, `doc`, `docsrs`, `doctest`, `feature`, `fmt_debug`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `sanitize`, `sanitizer_cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, `target_has_atomic_equal_alignment`, `target_has_atomic_load_store`, `target_os`, `target_pointer_width`, `target_thread_local`, `target_vendor`, `tarpaulin`, `test`, `ub_checks`, `unix`, and `windows`
>   = help: consider using a Cargo feature instead
>   = help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
>            [lints.rust]
>            unexpected_cfgs = { level = "warn", check-cfg = ['cfg(wasm_bindgen_unstable_test_coverage)'] }
>   = help: or consider adding `println!("cargo::rustc-check-cfg=cfg(wasm_bindgen_unstable_test_coverage)");` to the top of the `build.rs`
>   = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
>   = note: `-D unexpected-cfgs` implied by `-D warnings`
>   = help: to override `-D warnings` add `#[allow(unexpected_cfgs)]`
>   = note: this error originates in the attribute macro `wasm_bindgen` (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> error: unexpected `cfg` condition name: `wasm_bindgen_unstable_test_coverage`
>  --> datafusion/wasmtest/src/lib.rs:67:1
>   |
> 67 | #[wasm_bindgen]
>   | ^^^^^^^^^^^^^^^
>   |
>   = help: consider using a Cargo feature instead
>   = help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
>            [lints.rust]
>            unexpected_cfgs = { level = "warn", check-cfg = ['cfg(wasm_bindgen_unstable_test_coverage)'] }
>   = help: or consider adding `println!("cargo::rustc-check-cfg=cfg(wasm_bindgen_unstable_test_coverage)");` to the top of the `build.rs`
>   = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
>   = note: this error originates in the attribute macro `wasm_bindgen` (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> error: could not compile `datafusion-wasmtest` (lib) due to 2 previous errors
> warning: build failed, waiting for other jobs to finish...
> error: could not compile `datafusion-wasmtest` (lib test) due to 2 previous errors
> ```
> 
> These unexpected cfg conditions are changing at each try. I couldn't quickly understand the reason of these errors.

Can you try again after `cargo update wasm-bindgen`? This was fixed in https://github.com/rustwasm/wasm-bindgen/pull/4284.

**Comment by mbrobbel** [comment]
> > Can you try again after `cargo update wasm-bindgen`? This was fixed in [rustwasm/wasm-bindgen#4284](https://github.com/rustwasm/wasm-bindgen/pull/4284).
> 
> That works, thank you.
> 
> ```
> Checking datafusion-expr v44.0.0 (/Users/berkaysahin/Desktop/datafusion/datafusion/expr)
> error: unexpected `cfg` condition value: `used_linker`
>    --> datafusion/expr/src/lib.rs:101:1
>     |
> 101 | #[ctor::ctor]
>     | ^^^^^^^^^^^^^
>     |
>     = note: expected values for `feature` are: `recursive_protection`
>     = help: consider adding `used_linker` as a feature in `Cargo.toml`
>     = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
>     = note: `-D unexpected-cfgs` implied by `-D warnings`
>     = help: to override `-D warnings` add `#[allow(unexpected_cfgs)]`
>     = note: this error originates in the attribute macro `ctor::ctor` (in Nightly builds, run with -Z macro-backtrace for more info);
> ```
> 
> Do you have a remedy for this one as well 😄 ?

https://github.com/mmastrac/rust-ctor/issues/309#issuecomment-2489037492

**Review by alamb — COMMENTED** [review]
Thank you very much @jonahgao 🙏

File: datafusion/common/src/pyarrow.rs [hunk 1]
```diff
@@ -138,6 +138,9 @@ mod tests {
     fn test_py_scalar() {
         init_python();
 
+        // TODO: remove this attribute when bumping pyo3 to v0.23.0
+        // See: <https://github.com/PyO3/pyo3/blob/v0.23.0/guide/src/migration.md#gil-refs-feature-removed>
+        #[allow(unexpected_cfgs)]
```
Comment (alamb) [inline datafusion/common/src/pyarrow.rs:143]: pyo3 will be updated in 
- https://github.com/apache/datafusion/pull/13663

I need to find some time to polish that PR a bit
