### PR TITLE
Fix: Sort Merge Join LeftSemi issues when JoinFilter is set

### LINKED ISSUE #10100: fix Sort Merge Join to pass TPCH tests
I was trying to mark the Sort Merge Join as stable and run TPCH tests with SMJ enforced. Got the issue below, we need to fix before returning to discuss SMJ stable status

To run benches 
`RESULTS_NAME=smj ./benchmarks/bench.sh run tpch_smj`

Depends on #10092

```
thread 'tokio-runtime-worker' panicked at datafusion/physical-plan/src/joins/sort_merge_join.rs:1357:22:
index out of bounds: the len is 0 but the index is 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at datafusion/physical-plan/src/joins/sort_merge_join.rs:1357:22:
index out of bounds: the len is 0 but the index is 1
thread 'tokio-runtime-worker' panicked at datafusion/physical-plan/src/joins/sort_merge_join.rs:1357:22:
index out of bounds: the len is 0 but the index is 1
thread 'tokio-runtime-worker' panicked at datafusion/physical-plan/src/joins/sort_merge_join.rs:1357:22:
index out of bounds: the len is 0 but the index is 1
Error: Context("Join Error", External(JoinError::Panic(Id(88693), ...)))
```
 
_Originally posted by @comphead in https://github.com/apache/arrow-datafusion/issues/9846#issuecomment-2057999488_

### LINKED ISSUE #10379: Sort Merge Join. LeftSemi issues
### Describe the bug

The ticket is umbrella for Sort Merge Join LeftSemi bugs.
Currently Sort Merge Join LeftSemi crashes or gives the wrong result.

### To Reproduce

To reproduce it is enough to run Q21 TPCH bench in `bench.sh`

```
 RUST_BACKTRACE=1 RESULTS_NAME=smj ./benchmarks/bench.sh run tpch_smj
```

Or just Q21 

```
    $CARGO_COMMAND --bin tpch -- benchmark datafusion --iterations 5 --query 21 --path "${TPCH_DIR}" --prefer_hash_join false --format parquet -o ${RESULTS_FILE}
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by comphead**
## Which issue does this PR close?

Closes #10379  .

## Rationale for this change
Fixing some existing SMJ LeftSemi bugs when join filter is set. Currently the join either crashes or giving wrong results

### CODE REVIEW

**Comment by comphead** [comment]
I was able to fix initial query but now stuck on 
```
Error: ArrowError(InvalidArgumentError("all columns in a record batch must have the same length"), None)
```
Likely related to nulls

**Comment by comphead** [comment]
Q21 contains both LeftSemi and LeftAnti joins. Hopefully LeftSemi works now, solving LeftAnti

**Comment by comphead** [comment]
fuzztests failing...

File: datafusion/core/tests/fuzz_cases/join_fuzz.rs [hunk 1]
```diff
@@ -79,20 +79,20 @@ async fn test_full_join_1k() {
 }
 
 #[tokio::test]
-async fn test_semi_join_10k() {
+async fn test_semi_join_1k() {
```
Comment (comphead) [inline datafusion/core/tests/fuzz_cases/join_fuzz.rs:82]: Made it 1k to be consistent with other join fuzz tests

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 2]
```diff
@@ -824,6 +824,7 @@ impl SMJStream {
                             self.join_metrics.input_rows.add(batch.num_rows());
                             self.streamed_batch =
                                 StreamedBatch::new(batch, &self.on_streamed);
+
```
Comment (viirya) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:827]: Unnecessary change.

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 3]
```diff
@@ -991,6 +992,9 @@ impl SMJStream {
             Ordering::Equal => {
                 if matches!(self.join_type, JoinType::LeftSemi) {
                     join_streamed = !self.streamed_joined;
+                    // if the join filter specified there can be references to buffered columns
+                    // so its needed to join them
+                    join_buffered = self.filter.is_some();
```
Comment (viirya) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:997]: LeftSemi doesn't join buffered side, why we want to do this?

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 4]
```diff
@@ -1134,7 +1138,6 @@ impl SMJStream {
                 .collect::<Result<Vec<_>, ArrowError>>()?;
 
             let buffered_indices: UInt64Array = chunk.buffered_indices.finish();
-
```
Comment (viirya) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1137]: Unnecessary change too.

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 3 above)
Comment (viirya) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:997]: Oh, I see. As the filter uses buffered columns, we need to access to it.

Comment (viirya) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:997]: But the comment doesn't look correct as we don't actually join buffered columns.

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 5]
```diff
@@ -1161,6 +1164,15 @@ impl SMJStream {
...
                 if matches!(self.join_type, JoinType::Right) {
                     get_filter_column(&self.filter, &buffered_columns, &streamed_columns)
+                } else if matches!(self.join_type, JoinType::LeftSemi) {
+                    let buffered_columns = self.buffered_data.batches
+                        [chunk.buffered_batch_idx.unwrap()]
+                    .batch
+                    .columns()
+                    .iter()
+                    .map(|column| take(column, &buffered_indices, None))
+                    .collect::<Result<Vec<_>, ArrowError>>()?;
```
Comment (viirya) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1174]: This is a bit duplicate to above one block where preparing `buffered_columns`, we can create a small function for it.

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 6]
```diff
@@ -1195,11 +1207,45 @@ impl SMJStream {
...
+                    };
+
+                    if let Some(ref left_semi_mask) = maybe_left_semi_mask {
+                        mask = left_semi_mask;
+                    }
 
                     // Push the filtered batch to the output
                     let filtered_batch =
                         compute::filter_record_batch(&output_batch, mask)?;
+
```
Comment (viirya) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1248]: Unnecessary change.

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 3 above)
Comment (viirya) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:997]: Hmm, but if there are more rows at buffered side are matched on keys, won't it add additional joined pairs with nulls and buffered rows?

Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:997]: I hope the concern right and wrapped it into SQL query
```
query II
select * from (
with
t1 as (
    select 11 a, 12 b union all
    select 11 a, 13 b),
t2 as (
    select 11 a, 12 b union all
    select 11 a, 12 b union all
    select 11 a, 14 b
    )
select t1.* from t1 where exists (select 1 from t2 where t2.a = t1.a and t2.b != t1.b)
) order by 1, 2;
----
11 12
11 13
```
it passes, I can add it to slt file as well

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 7]
```diff
@@ -1195,7 +1205,40 @@ impl SMJStream {
                         .into_array(filter_batch.num_rows())?;
 
                     // The selection mask of the filter
-                    let mask = datafusion_common::cast::as_boolean_array(&filter_result)?;
+                    let mut mask =
+                        datafusion_common::cast::as_boolean_array(&filter_result)?;
+                    // for LeftSemi Join the filter mask should be calculated in its own way:
+                    // if we find at least one matching row for specific streaming key/filter we dont need to check others for the same key/filter
+                    let mut maybe_left_semi_mask: Option<BooleanArray> = None;
```
Comment (comphead) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1212]: I will add a unit test for left_semi_mask calculation

**Comment by comphead** [comment]
@viirya @alamb can I get a review on this PR please?

**Comment by alamb** [comment]
I will review this today

**Comment by viirya** [comment]
I'll take another look today.

File: datafusion/sqllogictest/test_files/sort_merge_join.slt [hunk 8]
```diff
@@ -263,5 +263,139 @@ DROP TABLE t1;
 statement ok
 DROP TABLE t2;
 
+
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/sort_merge_join.slt:266]: To verify that these tests cover the code changes, I ran them locally without the code changes in this PR and they failed as expected 👍 


```
Running "sort_merge_join.slt"
thread 'tokio-runtime-worker' panicked at datafusion/physical-plan/src/joins/sort_merge_join.rs:1356:22:
index out of bounds: the len is 0 but the index is 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
External error: task 17 panicked
Error: Execution("1 failures")
error: test failed, to rerun pass `-p datafusion-sqllogictest --test sqllogictests`

Caused by:
  process didn't exit successfully: `/Users/andrewlamb/Software/datafusion/target/debug/deps/sqllogictests-ce3a36cfeab74789 sort_merge` (exit status: 1)
```

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 9]
```diff
@@ -1161,6 +1162,15 @@ impl SMJStream {
             let filter_columns = if chunk.buffered_batch_idx.is_some() {
                 if matches!(self.join_type, JoinType::Right) {
                     get_filter_column(&self.filter, &buffered_columns, &streamed_columns)
+                } else if matches!(self.join_type, JoinType::LeftSemi) {
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1165]: I wonder if this should also check for `JoinType::Left` (and the clause above also check for `JoinType::RightSemi` 🤔

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 10]
```diff
@@ -1363,6 +1380,57 @@ fn get_filter_column(
     filter_columns
 }
 
+// Get buffered data sliece by specific batch index and for specified column indices only
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1383]: I think `buffered_indices` are row indices (not column indices), which confused me for a moment

Maybe this would be clearer:

```suggestion
/// Get `buffered_indices` rows for `buffered_data[buffered_batch_idx]`
```

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 11]
```diff
@@ -1363,6 +1380,57 @@ fn get_filter_column(
...
+) -> Result<Vec<ArrayRef>, ArrowError> {
+    buffered_data.batches[buffered_batch_idx]
+        .batch
+        .columns()
+        .iter()
+        .map(|column| take(column, &buffered_indices, None))
+        .collect::<Result<Vec<_>, ArrowError>>()
+}
+
+// Calculate join filter bit mask considering join type specifics
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1398]: I think it would help to also document what the input parameters `streamed_indicies` and `mask` represents here (I think it is the rows in streamed_indices that match the join predicate?)

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 12]
```diff
@@ -1363,6 +1380,57 @@ fn get_filter_column(
...
+    // for LeftSemi Join the filter mask should be calculated in its own way:
+    // if we find at least one matching row for specific streaming index
+    // we dont need to check any others for the same index
+    if matches!(join_type, JoinType::LeftSemi) {
+        // have we seen a filter match for a streaming index before
+        let mut seen_as_true: bool = false;
+        let streamed_indices_length = streamed_indices.len();
+        let mut corrected_mask: Vec<bool> = vec![false; streamed_indices_length];
+
+        #[allow(clippy::needless_range_loop)]
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1413]: I wonder why ignore clippy here?

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 13]
```diff
@@ -1363,6 +1380,57 @@ fn get_filter_column(
...
+// Calculate join filter bit mask considering join type specifics
+fn get_filtered_join_mask(
+    join_type: JoinType,
+    streamed_indices: UInt64Array,
+    mask: &BooleanArray,
+) -> Option<BooleanArray> {
+    // for LeftSemi Join the filter mask should be calculated in its own way:
+    // if we find at least one matching row for specific streaming index
+    // we dont need to check any others for the same index
+    if matches!(join_type, JoinType::LeftSemi) {
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1407]: I find it strange this doesn't' also handle RightSemi (as in I would expect the code to be symmetrical)

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 14]
```diff
@@ -1363,6 +1380,57 @@ fn get_filter_column(
...
+        // have we seen a filter match for a streaming index before
+        let mut seen_as_true: bool = false;
+        let streamed_indices_length = streamed_indices.len();
+        let mut corrected_mask: Vec<bool> = vec![false; streamed_indices_length];
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1411]: FWIW it might be faster / easier to followto create the `BooleanArray` directly using [`BooleanBuilder`](https://docs.rs/arrow/latest/arrow/array/struct.BooleanBuilder.html) rather than Vec<bool>

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 15]
```diff
@@ -2639,6 +2710,70 @@ mod tests {
 
         Ok(())
     }
+
+    #[tokio::test]
+    async fn left_semi_join_filtered_mask() -> Result<()> {
+        assert_eq!(
+            get_filtered_join_mask(
+                LeftSemi,
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:2718]: maybe we should test a type other than LeftSemi as negative test coverage 🤔

**Review by alamb — APPROVED** [review]
Thank you @comphead  -- while I am not an expert in this code it looks like an improvement to me (less panic'ing and better test coverage all around) 👍 

cc @richox  who I think contributed the first version of this code in https://github.com/apache/datafusion/pull/2242 and @yjshen  who reviewed, in case you would also like to review the change

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 12 above)
Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:1413]: Clippy doesn't like for loops anymore ....

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 11 above)
Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:1398]: Will do as a few documentation also added me quite a pain

**Comment by comphead** [comment]
Thanks @alamb I'll add more docs and also added a task to check RightSemi join to https://github.com/apache/datafusion/issues/9846

I'll let it be opened a little longer to give @viirya more time to have a second eye on the PR

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 3 above)
Comment (viirya) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:996]: I think above test doesn't hit the case I mean.

If last join loop already joined streamed row and buffered rows and the output size reaches batch size, the loop will exit and go to output joined paired.

After that, next join loop gets started again. 

Now the `current_ordering` is `Equal` and `self.streamed_joined` is true, the loop will join nulls and buffered rows. As the left side are nulls, the join filter doesn't work.

This is not caught by the test you posted, because all joined pairs will be output in one batch, I think.

Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:996]: Thanks @viirya I'll try to add tests separating the data across multiple batches

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 13 above)
Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:1407]: I will add more tests for RightSemi as followup

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 14 above)
Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:1411]: done, btw, I'm thinking why BooleanArray, doesnt support capacity with default values to achieve the same as 
```
vec![false; streamed_indices_length];
```

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 3 above)
Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:996]: I'm not able to run such test just because of other SMJ issue not related to this PR:
If the join filter is set and for the same streaming index there are matching rows more or equal to a batch size then the query just stuck. Likely the problem is in polling state and it can be easily reproduced on main branch.

```
  #[tokio::test]
    async fn test_11() -> Result<()> {
        let ctx: SessionContext = SessionContext::new();

        let sql = "set datafusion.optimizer.prefer_hash_join = false;";
        let _ = ctx.sql(sql).await?.collect().await?;

        let sql = "set datafusion.execution.batch_size = 1";
        let _ = ctx.sql(sql).await?.collect().await?;

        let sql = "
        select * from (
        with
        t1 as (
            select 12 a, 12 b
            ),
        t2 as (
            select 12 a, 12 b
            )
            select t1.* from t1 join t2 on t1.a = t2.b where t1.a > t2.b
        ) order by 1, 2;
        ";

        let actual = ctx.sql(sql).await?.collect().await?;


        Ok(())
    }
```

I'll file a separate issue for this one, but perhaps we can go with this PR because potential problem you talking about cannot ever be hit because of the  issue above

Comment (viirya) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:996]: Thanks for creating the ticket.

I think that current fix to the LeftSemi isn't correct due to the additional joined pairs of nulls and buffered rows. I don't think we should move forward with it because of that.

Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:996]: I'm putting the PR to draft until we can check if PR requires modifications to avoid addition join pairs of nulls and buffered rows. It depends on #10491

Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:996]: I have checked the case, it doesn't fail, however it produces more rows than expected, looking into this

Comment (viirya) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:996]: Yea, what I meant is actually it will produce some rows that are not correct results.

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 16]
```diff
@@ -54,7 +45,17 @@ use datafusion_execution::TaskContext;
 use datafusion_physical_expr::equivalence::join_equivalence_properties;
 use datafusion_physical_expr::{PhysicalExprRef, PhysicalSortRequirement};
 
-use futures::{Stream, StreamExt};
+use crate::expressions::PhysicalSortExpr;
```
Comment (comphead) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:48]: this change is by formatter

**Comment by comphead** [comment]
@viirya I'm planning to merge this PR soon as it fixes the crash, and addresses your concern (please see the slt test covering this specific case). All other improvements can be in follow up PR.

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 17]
```diff
@@ -989,8 +996,21 @@ impl SMJStream {
                 }
             }
             Ordering::Equal => {
-                if matches!(self.join_type, JoinType::LeftSemi) {
+                if matches!(self.join_type, JoinType::LeftSemi) && self.filter.is_some() {
+                    join_streamed = !self
+                        .streamed_batch
+                        .join_filter_matched_idxs
+                        .contains(&(self.streamed_batch.idx as u64))
+                        && !self.streamed_joined;
```
Comment (viirya) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1004]: If `self.streamed_joined` is false, `join_filter_matched_idxs` always doesn't contain `self.streamed_batch.idx`, so the two conditions are duplicated as they are both true.

If `self.streamed_joined` is true, this `and` check is failed, the another condition doesn't matter.

I'm not sure what this is added to check.

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 18]
```diff
@@ -989,8 +996,21 @@ impl SMJStream {
...
+                    // if the join filter specified there can be references to buffered columns
+                    // so buffered columns are needed to access them
+                    join_buffered = join_streamed;
+                }
+                if matches!(self.join_type, JoinType::LeftSemi) && self.filter.is_none() {
                     join_streamed = !self.streamed_joined;
+                    // if the join filter specified there can be references to buffered columns
```
Comment (viirya) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1011]: This block knows `self.filter.is_none()`, why you still do `join_buffered = self.filter.is_some();`?

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 19]
```diff
@@ -1365,6 +1402,69 @@ fn get_filter_column(
...
+        let mut filter_matched_indices: Vec<u64> = vec![];
+
+        #[allow(clippy::needless_range_loop)]
+        for i in 0..streamed_indices_length {
+            // LeftSemi respects only first true values for specific streaming index,
+            // others true values for the same index must be false
+            if mask.value(i) && !seen_as_true {
+                seen_as_true = true;
+                corrected_mask.append_value(true);
+                filter_matched_indices.push(streamed_indices.value(i));
```
Comment (viirya) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1450]: I'm not sure what this supposes to do. `streamed_indices` may contain different streamed indices, so that means they are different rows. Why you only output first seen row?

**Review by viirya — COMMENTED** [review]
I've seen some issues in this patch. It doesn't look like a correct fix.

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 19 above)
Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:1450]: the output contains first seen row for the same streaming index, not just first row. Its done to avoid duplicates if the streamed row has multiple matches within a single batch

**Comment by comphead** [comment]
> I've seen some issues in this patch. It doesn't look like a correct fix.

The tests currently in sync with what hash join returns, is there a test showing the opposite?

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 19 above)
Comment (viirya) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:1450]: Could you explain why it is "same streaming index"? `streamed_indices` contains all indices of current streamed batch. Why you think they are pointing to same index?

Comment (viirya) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:1450]: Oh, I saw the below there is a check of changed streamed index.

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 20]
```diff
@@ -989,8 +996,21 @@ impl SMJStream {
...
+                        && !self.streamed_joined;
+                    // if the join filter specified there can be references to buffered columns
+                    // so buffered columns are needed to access them
+                    join_buffered = join_streamed;
+                }
+                if matches!(self.join_type, JoinType::LeftSemi) && self.filter.is_none() {
                     join_streamed = !self.streamed_joined;
+                    // if the join filter specified there can be references to buffered columns
+                    // so buffered columns are needed to access them
+                    join_buffered = self.filter.is_some();
```
Comment (viirya) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1013]:
```suggestion
```

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 21]
```diff
@@ -989,8 +996,21 @@ impl SMJStream {
                 }
             }
             Ordering::Equal => {
-                if matches!(self.join_type, JoinType::LeftSemi) {
+                if matches!(self.join_type, JoinType::LeftSemi) && self.filter.is_some() {
```
Comment (viirya) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:999]: You can combine this and below which both are for `JoinType::LeftSemi` under single `if` block.

**Review by viirya — APPROVED** [review]

**Comment by alamb** [comment]
🚀
