### PR TITLE
fix(sql): handle GROUP BY ALL with aliased aggregates

### LINKED ISSUE #20909: Incorrectly parsed SQL query containing GROUP BY ALL and an alias in the projection
### Describe the bug

When a query contains `GROUP BY ALL`, an alias on a projected column results in an error about an unsupported implementation:
```
Exception: DataFusion error: This feature is not implemented: Physical plan does not support logical expression AggregateFunction(AggregateFunction { func: AggregateUDF { inner: Count { name: "count", signature: Signature { type_signature: OneOf([VariadicAny, Nullary]), volatility: Immutable, parameter_names: None } } }, params: AggregateFunctionParams { args: [Literal(Int64(1), None)], distinct: false, filter: None, order_by: [], null_treatment: None } })
```

It can be seen in the logical plan that it was incorrectly parsed. This error does not happen when the alias is removed.

### To Reproduce

```python
# /// script
# dependencies = [
#   "datafusion",
# ]
# ///

from datafusion import SessionContext

df_ctx = SessionContext()
df_ctx.sql("CREATE TABLE t(first INT, second VARCHAR) AS VALUES (1, 'a'), (2, 'b'), (3, 'a')")

good_df = df_ctx.sql('SELECT COUNT(*) FROM t GROUP BY ALL')
print(good_df.logical_plan())
print(good_df.collect())

print('\n\n')

bad_df = df_ctx.sql('SELECT COUNT(*) AS c FROM t GROUP BY ALL')
print(bad_df.logical_plan())
print(bad_df.collect())
```

### Expected behavior

I expect `SELECT COUNT(*) FROM t GROUP BY ALL` and `SELECT COUNT(*) AS c FROM t GROUP BY ALL` to have the same behavior, and for both of them to succeed.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kumarUjjawal**
## Which issue does this PR close?

- Closes #20909

## Rationale for this change

Issue #20909 reported that:

  - SELECT COUNT(*) FROM t GROUP BY ALL works
  - SELECT COUNT(*) AS c FROM t GROUP BY ALL fails at execution

  The failure came from an incorrect plan that grouped by an aggregate alias expression.

## What changes are included in this PR?

This PR fixes GROUP BY ALL when the select list has an aliased aggregate like COUNT(*) AS c.

  Changes:

  - Update GROUP BY ALL expansion logic to skip any select expression that contains an aggregate, even if it is wrapped in aliases.
  - Add SQL planner tests for:
      - SELECT COUNT(*) FROM ... GROUP BY ALL
      - SELECT COUNT(*) AS c FROM ... GROUP BY ALL
  - Add core execution test for:
      - SELECT COUNT(*) AS c FROM ... GROUP BY ALL

## Are these changes tested?

Yes

### CODE REVIEW

File: datafusion/core/tests/sql/aggregates/basic.rs [hunk 1]
```diff
@@ -103,6 +103,21 @@ async fn count_aggregated() -> Result<()> {
     Ok(())
 }
 
+#[tokio::test]
+async fn count_aggregated_group_by_all_alias() -> Result<()> {
```
Comment (neilconway) [inline datafusion/core/tests/sql/aggregates/basic.rs]: Seems like this would be better as an SLT test?

File: datafusion/sql/tests/sql_integration.rs [hunk 2]
```diff
@@ -1748,6 +1748,32 @@ fn select_simple_aggregate_with_groupby_can_use_alias() {
     );
 }
 
+#[test]
+fn select_count_with_group_by_all() {
```
Comment (neilconway) [inline datafusion/sql/tests/sql_integration.rs]: The two tests in this file pass without the fix. Probably best to remove them?

File: datafusion/sql/src/select.rs [hunk 3]
```diff
@@ -192,16 +192,13 @@ impl<S: ContextProvider> SqlToRel<'_, S> {
                 })
                 .collect::<Result<Vec<Expr>>>()?
         } else {
-            // 'group by all' groups wrt. all select expressions except 'AggregateFunction's.
-            // Filter and collect non-aggregate select expressions
+            // 'group by all' groups wrt. all select expressions except aggregate expressions.
+            // Note: aggregate expressions can be nested under one or more aliases
+            // (e.g. count(1) AS count(*) AS c), so detect aggregates recursively.
```
Comment (neilconway) [inline datafusion/sql/src/select.rs]: This comment is a bit misleading, because that SQL statement doesn't parse. The problem seems to actually occur in practice because of a (nested) alias inserted by the analyzer, which AFAICS you can't do from SQL. I'd probably just remove the change to the comment.

**Comment by kumarUjjawal** [comment]
Thanks @neilconway for the feedback

**Comment by neilconway** [comment]
@alamb This PR looks ready to me.
