### PR TITLE
keep fetch when merge FilterExec in FilterPushdown

### LINKED ISSUE #21069: FilterPushdown discard the fetch when merge FilterExec
### Describe the bug

when i test the branch-53, i find this that when i use the `FilterPushdown` to merge two `FilterExec` if the outer FilterExec have the fetch, after `FilterPushdown` the fetch wil be discard.
```
before pushdown plan:
FilterExec: event@0 = Ingestion, projection=[size@1], fetch=10
  FilterExec: time@0 < 350, projection=[event@1, size@2]
    DataSourceExec: partitions=1, partition_sizes=[1]

after pushdown plan:
ProjectionExec: expr=[size@1 as size]
  FilterExec: event@1 = Ingestion AND time@0 < 350, projection=[event@1, size@2]
    DataSourceExec: partitions=1, partition_sizes=[1]
```

### To Reproduce

```rust
use std::sync::Arc;

use arrow::array::{Int64Array, RecordBatch, StringArray};
use arrow::datatypes::{DataType, Field, Schema};
use datafusion::common::config::ConfigOptions;
use datafusion::physical_expr::expressions::{BinaryExpr, Literal, col};
use datafusion::physical_optimizer::PhysicalOptimizerRule;
use datafusion::physical_optimizer::filter_pushdown::FilterPushdown;
use datafusion::physical_plan::ExecutionPlan;
use datafusion::physical_plan::displayable;
use datafusion::physical_plan::filter::FilterExecBuilder;
use datafusion_common::ScalarValue;
use datafusion_expr::Operator;

#[tokio::main]
async fn main() {
    // Create schema: [time, event, size]
    let schema = Arc::new(Schema::new(vec![
        Field::new("time", DataType::Int64, false),
        Field::new("event", DataType::Utf8, false),
        Field::new("size", DataType::Int64, false),
    ]));

    // Create sample data
    let timestamps = vec![100i64, 200, 300, 400, 500];
    let events = vec!["Ingestion", "Ingestion", "Query", "Ingestion", "Query"];
    let sizes = vec![10i64, 20, 30, 40, 50];

    let batch = RecordBatch::try_new(
        schema.clone(),
        vec![
            Arc::new(Int64Array::from(timestamps)),
            Arc::new(StringArray::from(events)),
            Arc::new(Int64Array::from(sizes)),
        ],
    )
    .unwrap();

    // Create data source
    let memory_exec = datafusion::catalog::memory::MemorySourceConfig::try_new_exec(
        &[vec![batch]],
        schema.clone(),
        None,
    )
    .unwrap();

    // First FilterExec: time < 350 with projection=[event@1, size@2]
    let time_col = col("time", &memory_exec.schema()).unwrap();
    let time_filter = Arc::new(BinaryExpr::new(
        time_col,
        Operator::Lt,
        Arc::new(Literal::new(ScalarValue::Int64(Some(350)))),
    ));
    let filter1 = Arc::new(
        FilterExecBuilder::new(time_filter, memory_exec)
            .apply_projection(Some(vec![1, 2]))
            .unwrap()
            .build()
            .unwrap(),
    );

    // Second FilterExec: event = 'Ingestion' with projection=[size@1]
    let event_col = col("event", &filter1.schema()).unwrap();
    let event_filter = Arc::new(BinaryExpr::new(
        event_col,
        Operator::Eq,
        Arc::new(Literal::new(ScalarValue::Utf8(Some(
            "Ingestion".to_string(),
        )))),
    ));
    let filter2 = Arc::new(
        FilterExecBuilder::new(event_filter, filter1)
            .apply_projection(Some(vec![1]))
            .unwrap()
            .with_fetch(Some(10))
            .build()
            .unwrap(),
    );

    let display = displayable(filter2.as_ref());
    println!("before pushdown plan:\n{}", display.indent(true));

    // Apply filter pushdown optimization
    let config = ConfigOptions::default();
    let optimized_plan = FilterPushdown::new()
        .optimize(Arc::clone(&filter2) as Arc<dyn ExecutionPlan>, &config)
        .unwrap();

    // print the plan as an indented tree
    let display = displayable(optimized_plan.as_ref());
    println!("after pushdown plan:\n{}", display.indent(true));
    // println!("Tree render:\n{}", display.tree_render());
}
```

### Expected behavior

the fetch should be keep

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by haohuaijin**
## Which issue does this PR close?

- Closes #21069

## Rationale for this change

- see #21069

## What changes are included in this PR?

When `FilterPushdown` merges/eliminates a `FilterExec`, it now correctly propagates the `fetch` limit that was on the FilterExec.

Previously, if a `FilterExec` had a fetch (e.g., LIMIT 10) and all its predicates were fully pushed down to a under `FilterExec`, the FilterExec node was dropped — and the fetch was silently lost, potentially returning more rows than requested.
The fix:
- If the FilterExec being eliminated has a fetch, propagate it to the child node via `with_fetch()`, if the clid node do not support `with_fetch` add a local limit node.
- If both the outer and inner nodes have a fetch, use min(outer, inner) to preserve the tighter constraint

## Are these changes tested?

yes, add some test cases, trying to reproduce use sql, current not able

### CODE REVIEW

File: datafusion/physical-plan/src/filter.rs [hunk 1]
```diff
@@ -695,7 +695,21 @@ impl ExecutionPlan for FilterExec {
...
+            // When the child also has a fetch, use the minimum of both to preserve
+            // the tighter constraint.
+            let filter_input = if let Some(outer_fetch) = self.fetch {
+                let effective_fetch = match filter_input.fetch() {
+                    Some(inner_fetch) => outer_fetch.min(inner_fetch),
+                    None => outer_fetch,
+                };
+                filter_input
+                    .with_fetch(Some(effective_fetch))
+                    .unwrap_or(filter_input)
```
Comment (haohuaijin) [inline datafusion/physical-plan/src/filter.rs]: this still have the change that lost the fetch, if the child node do not support the `with_fetch` method. 

One idea is that when a child node does not support fetch, we can leave a FilterExec with both fetch and filter set to true, if the filter have projection, keep projection as well. However, I'm uncertain if this is the best approach and think it requires further discussion.

Comment (adriangb) [reply datafusion/physical-plan/src/filter.rs]: Just an idea: could we replace with a limit node?

Comment (haohuaijin) [reply datafusion/physical-plan/src/filter.rs]: ~we can, but the FilterExec also have the projection, so we have two way~
~1. filter node (true filter, limit, project)~
~2. limit node + projection node~

Comment (haohuaijin) [reply datafusion/physical-plan/src/filter.rs]: thank you, i think add a limit node is a good idea, i impl it in [0ac834a](https://github.com/apache/datafusion/pull/21070/commits/0ac834abc6b7897bd850b210bcb5778050d18750). For user, after `FilterPushdown`, user can use `ProjectionPushdown` and `LimitPushdown` to futermore optimizer the physical plan

**Review by adriangb — APPROVED** [review]
Looks good to me!

**Comment by haohuaijin** [comment]
Thanks for you reviews @adriangb
