### PR TITLE
physical-plan: push filters down to UnionExec children

### LINKED ISSUE #18053: UnionExec does not push down filters to children
### Describe the bug

This is because gather_filters_for_pushdown is not implemented. This causes performance issues if scans are below unions.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by asubiotto**
Filters are safe to be pushed down, so we can override the default behavior here.

## Which issue does this PR close?

- Closes #18053

### CODE REVIEW

File: datafusion/core/tests/physical_optimizer/filter_pushdown/mod.rs [hunk 1]
```diff
@@ -1833,6 +1834,34 @@ STORED AS PARQUET;
...
+    OptimizationTest:
+      input:
+        - FilterExec: a@0 = foo
+        -   UnionExec
+        -     DataSourceExec: file_groups={1 group: [[test.parquet]]}, projection=[a, b, c], file_type=test, pushdown_supported=true
+        -     DataSourceExec: file_groups={1 group: [[test.parquet]]}, projection=[a, b, c], file_type=test, pushdown_supported=true
+      output:
+        Ok:
+          - UnionExec
+          -   DataSourceExec: file_groups={1 group: [[test.parquet]]}, projection=[a, b, c], file_type=test, pushdown_supported=true, predicate=a@0 = foo
```
Comment (alamb) [inline datafusion/core/tests/physical_optimizer/filter_pushdown/mod.rs:1859]: nice!
