### PR TITLE
fix: Change `OuterReferenceColumn` to contain the entire outer field to prevent metadata loss

### LINKED ISSUE #17422: Extension metadata dropped in some queries (possibly involving subquries)
### Describe the bug

I haven't yet figured out exactly what part of this query causes the issue, but in the query:

```sql
SELECT L.id l_id FROM L
WHERE EXISTS (SELECT 1 FROM R WHERE extension_predicate(L.geometry, R.geometry))
ORDER BY l_id
```

...causes `extension_predicate()` to be called with `(<extension type dropped>, <extension type>)`. I think, but don't know, that the subquery is the issue.

We're using that query to check a left semi join...explicit joins that don't involve a subquery are OK.

### To Reproduce

Output:

```
INNER JOIN ---
+------+
| l_id |
+------+
| 1    |
| 1    |
| 2    |
| 2    |
+------+
With subquery ---

thread 'main' panicked at src/main.rs:118:13:
Metadata for 1 or more args was dropped (return_field_from_args) [(0, Field { name: "outer_ref(l.geometry)", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} })]
```

Reproducer:

```rust
use std::collections::HashMap;

use datafusion::{
    arrow::{
        array::{RecordBatch, create_array},
        datatypes::{DataType, Field, Schema},
    },
    logical_expr::{ColumnarValue, ScalarUDFImpl, Signature, Volatility},
    prelude::*,
    scalar::ScalarValue,
};

#[tokio::main]
async fn main() {
    let schema = Schema::new(vec![
        Field::new("id", DataType::Int64, true),
        Field::new("geometry", DataType::Utf8, true).with_metadata(HashMap::from([(
            "ARROW:extension:name".to_string(),
            "foofy.foofy".to_string(),
        )])),
    ]);

    let batch_lhs = RecordBatch::try_new(
        schema.clone().into(),
        vec![
            create_array!(Int64, [1, 2]),
            create_array!(Utf8, [Some("item1"), Some("item2")]),
        ],
    )
    .unwrap();

    let batch_rhs = RecordBatch::try_new(
        schema.clone().into(),
        vec![
            create_array!(Int64, [2, 3]),
            create_array!(Utf8, [Some("item2"), Some("item3")]),
        ],
    )
    .unwrap();

    let ctx = SessionContext::new();
    ctx.register_batch("l", batch_lhs).unwrap();
    ctx.register_batch("r", batch_rhs).unwrap();
    ctx.register_udf(ExtensionScalarPredicate::default().into());

    println!("INNER JOIN ---");
    let df = ctx
        .sql(
            "
        SELECT L.id l_id FROM L
        INNER JOIN R ON extension_predicate(L.geometry, R.geometry)
        ORDER BY l_id
        ",
        )
        .await
        .unwrap();
    df.show().await.unwrap();

    println!("With subquery ---");
    let df = ctx
        .sql(
            "
        SELECT L.id l_id FROM L
        WHERE EXISTS (SELECT 1 FROM R WHERE extension_predicate(L.geometry, R.geometry))
        ORDER BY l_id
        ",
        )
        .await
        .unwrap();
    df.show().await.unwrap();
}

#[derive(Debug)]
struct ExtensionScalarPredicate {
    signature: Signature,
}

impl Default for ExtensionScalarPredicate {
    fn default() -> Self {
        Self {
            signature: Signature::user_defined(Volatility::Immutable),
        }
    }
}

impl ScalarUDFImpl for ExtensionScalarPredicate {
    fn as_any(&self) -> &dyn std::any::Any {
        self
    }

    fn name(&self) -> &str {
        "extension_predicate"
    }

    fn signature(&self) -> &Signature {
        &self.signature
    }

    fn coerce_types(&self, arg_types: &[DataType]) -> datafusion::error::Result<Vec<DataType>> {
        Ok(arg_types.to_vec())
    }

    fn return_type(&self, _arg_types: &[DataType]) -> datafusion::error::Result<DataType> {
        unreachable!("This shouldn't have been called")
    }

    fn return_field_from_args(
        &self,
        args: datafusion::logical_expr::ReturnFieldArgs,
    ) -> datafusion::error::Result<datafusion::arrow::datatypes::FieldRef> {
        let dropped = args
            .arg_fields
            .iter()
            .enumerate()
            .filter(|(_, input_field)| !input_field.metadata().contains_key("ARROW:extension:name"))
            .collect::<Vec<_>>();
        if !dropped.is_empty() {
            panic!(
                "Metadata for {} or more args was dropped (return_field_from_args) {dropped:?}",
                dropped.len()
            );
        }

        Ok(Field::new("", DataType::Boolean, true).into())
    }

    fn invoke_with_args(
        &self,
        args: datafusion::logical_expr::ScalarFunctionArgs,
    ) -> datafusion::error::Result<datafusion::logical_expr::ColumnarValue> {
        let dropped = args
            .arg_fields
            .iter()
            .enumerate()
            .filter(|(_, input_field)| !input_field.metadata().contains_key("ARROW:extension:name"))
            .collect::<Vec<_>>();
        if !dropped.is_empty() {
            panic!(
                "Metadata for {} or more args was dropped (invoke_with_args) {dropped:?}",
                dropped.len()
            );
        }

        let array = ScalarValue::Boolean(Some(true)).to_array_of_size(args.number_rows)?;
        Ok(ColumnarValue::Array(array))
    }
}
```

### Expected behavior

I would have expected the function to be called with field metadata from its inputs (rather than the storage type).

### Additional context

cc @timsaucer and @Kontinuation

### PR DESCRIPTION
**Pull request by Kontinuation**
## Which issue does this PR close?

- Closes #17422.

## Rationale for this change

As reported by #17422, extension metadata was dropped in some queries involving subqueries. This happens when a column references another column in a correlated subquery, which creates an `OuterReferenceColumn` in DataFusion's logical plan.

`OuterReferenceColumn` is defined to contain a data type and a referenced column. As we know, outer reference column refers to a field in another table, so there's no way to retrieve the field metadata of referenced column given the schema of the current table. To overcome this problem, we define `OuterReferenceColumn` to contain the entire referenced field as a `FieldRef`. We also updated the implementation of `to_field` to return the referenced field, which contains the original metadata of referenced field.

## What changes are included in this PR?

Changed `OuterReferenceColumn` to contain the referenced outer field as a `FieldRef`.

## Are these changes tested?

* Added a unit test
* Added the repro in the issue to `user_defined_scalar_functions` test

## Are there any user-facing changes?

Yes. This changes part of the public API.

### CODE REVIEW

**Comment by Kontinuation** [comment]
CC @paleolimbot

File: datafusion/expr/src/expr.rs [hunk 1]
```diff
@@ -3951,7 +3951,7 @@ mod test {
         // If this test fails when you change `Expr`, please try
         // `Box`ing the fields to make `Expr` smaller
         // See https://github.com/apache/datafusion/issues/16199 for details
-        assert_eq!(size_of::<Expr>(), 128);
+        assert!(size_of::<Expr>() <= 128);
```
Comment (paleolimbot) [inline datafusion/expr/src/expr.rs]: Should this be shrunk to the actual new size_of?

File: datafusion/expr/src/expr_fn.rs [hunk 2]
```diff
@@ -71,7 +71,15 @@ pub fn col(ident: impl Into<Column>) -> Expr {
 /// Create an out reference column which hold a reference that has been resolved to a field
 /// outside of the current plan.
 pub fn out_ref_col(dt: DataType, ident: impl Into<Column>) -> Expr {
-    Expr::OuterReferenceColumn(dt, ident.into())
+    // Construct a synthetic field (no metadata). Prefer using `out_ref_field` when possible
+    let column = ident.into();
```
Comment (paleolimbot) [inline datafusion/expr/src/expr_fn.rs]: Should this function be removed? Keeping it feels like it may result in a future bug from somebody who uses it accidentally and looses metadata (I have no idea how widely used this is or whether that will cause mayhem 🙂 )

**Review by paleolimbot — COMMENTED** [review]
Thank you for looking into this!

File: datafusion/expr/src/expr_fn.rs (hunk 2 above)
Comment (Kontinuation) [reply datafusion/expr/src/expr_fn.rs]: I prefer to be conservative when it comes to introducing breaking changes to the API. I'd like to wait for more eyes on this before removing this API.

File: datafusion/expr/src/expr.rs (hunk 1 above)
Comment (Kontinuation) [reply datafusion/expr/src/expr.rs]: The actual size is 112. I have changed this assertion to assert_eq! on the actual size.

Comment (alamb) [reply datafusion/expr/src/expr.rs]: I think it would be nicer to include the new, smaller size, in order to  prevent regressions (from the smaller 112 bytes)

File: datafusion/expr/src/expr_fn.rs (hunk 2 above)
Comment (alamb) [reply datafusion/expr/src/expr_fn.rs]: Rather than removing it, how about we mark it "deprecated" per https://datafusion.apache.org/contributor-guide/api-health.html#deprecation-guidelines?

**Comment by Kontinuation** [comment]
I have marked `out_ref_col` as deprecated. I also found that the new API `out_ref_field` is quite cumbersome, so I replaced it with `out_ref_col_with_metadata`. This will also make transitioning from the deprecated API to the new API more easier (only need to pass in one empty HashMap).

UPDATE: I found that `out_ref_col_with_metadata(dt, HashMap::new(), col)` is probably too verbose compared to `out_ref_col(dt, col)` for cases where we are referencing plain outer fields without metadata, so I'm not certain if we really want to deprecate `out_ref_col` given this situation.

**Comment by alamb** [comment]
let's try it this way, and if we find other bugs related to using the wrong `out_ref_col` we can reasses
