### PR TITLE
fix: maintain inner list nullability for `array_sort`

### LINKED ISSUE #19947: Regression: `array_sort` fails on list with inner non-nullable field
### Describe the bug

When you have a ListArray and the inner field is non-nullable, `array_sort` generates an error in 51.0.0. See below for steps to reproduce.

### To Reproduce

The following generates an error:

```sql
select array_sort(arrow_cast(make_array(1, 3, 5, -5), 'List(non-null Int32)'));
```

> DataFusion error: Internal("Assertion failed: result_data_type == *expected_type: Function 'array_sort' returned value of type 'List(Field { data_type: Int32 })' while the following type was promised at planning time and expected: 'List(Field { data_type: Int32, nullable: true })'")

### Expected behavior

You cannot do the above sql with 50.0.0 (In 50.0.0 it doesn't support the "non-null" in parser) but I did test by manually creating and registering a record batch that has a list array with inner non-nullable field. It passes in 50.0.0 and fails in 51.0.0.

### Additional context

I believe this was introduced in https://github.com/apache/datafusion/pull/17657

### PR DESCRIPTION
**Pull request by Jefffrey**
## Which issue does this PR close?

- Closes #19947

## Rationale for this change

#17657 introduced a regression since it cloned the inner field in the execution path but in the `return_type` function it still set nullability to true. Fix to ensure we maintain the field of the inner field as is.

## What changes are included in this PR?

Change `return_type` to just pass through the input datatype as is.

Also refactor away usage of a null buffer builder in favour of copying the input array null buffer.

## Are these changes tested?

Added tests.

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/functions-nested/src/sort.rs [hunk 1]
```diff
@@ -134,18 +132,7 @@ impl ScalarUDFImpl for ArraySort {
...
-            DataType::Null => Ok(DataType::Null),
-            DataType::List(field) => {
-                Ok(DataType::new_list(field.data_type().clone(), true))
-            }
-            DataType::LargeList(field) => {
-                Ok(DataType::new_large_list(field.data_type().clone(), true))
-            }
-            arg_type => {
-                plan_err!("{} does not support type {arg_type}", self.name())
-            }
```
Comment (timsaucer) [inline datafusion/functions-nested/src/sort.rs:147]: By removing this, don't we delay the error generated when someone passes an invalid type until execution? It seems like we want this check to still happen during planning.

Maybe something like match on `DataType::Null | DataType::List(_) | ataType::LargeList(_) => Ok(arg_types[0].clone())`

Comment (Jefffrey) [reply datafusion/functions-nested/src/sort.rs:147]: The signature should already guard us from that path; it was only there for completeness before. Worst case if something does go wrong at least we'll just error normally at execution time instead of panicking via `unreachable!()` for example
