### PR TITLE
fix: clickbench type err

### LINKED ISSUE #15753: `Cargo bench --bench sql_planner` is failing
### Describe the bug

I get an error when trying to run the sql planning benchmarkl:

here is the error:

thread 'main' panicked at datafusion/core/benches/sql_planner.rs:60:14:
called `Result::unwrap()` on an `Err` value: Context("type_coercion", Plan("Internal error: Expect TypeSignatureClass::Native(LogicalType(Native(String), String)) but received NativeType::Binary, DataType: BinaryView.\nThis was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker No function matches the given name and argument types 'levenshtein(BinaryView, BinaryView)'. You might need to add explicit type casts.\n\tCandidate functions:\n\tlevenshtein(Coercion(TypeSignatureClass::Native(LogicalType(Native(String), String))), Coercion(TypeSignatureClass::Native(LogicalType(Native(String), String))))"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### To Reproduce

```shell
cargo bench --profile=dev --bench sql_planner -- physical_plan_clickbench_all
```

### Expected behavior

I expect the plan to complete without error 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chenkovsky**
## Which issue does this PR close?

- Closes #15753.

## Rationale for this change

column types of UTMSource and UTMCampaign in clickbench_partitioned are binary, but in datafusion/core/tests/data/clickbench_hits_10.parquet they are string.

## What changes are included in this PR?

add a cast in sql

## Are these changes tested?

Manually run clickbench

## Are there any user-facing changes?

No

### CODE REVIEW

File: benchmarks/queries/clickbench/extended.sql [hunk 1]
```diff
@@ -4,4 +4,4 @@ SELECT "BrowserCountry",  COUNT(DISTINCT "SocialNetwork"), COUNT(DISTINCT "HitCo
...
-SELECT COUNT(*) AS ShareCount FROM hits WHERE "IsMobile" = 1 AND "MobilePhoneModel" LIKE 'iPhone%' AND "SocialAction" = 'share' AND "SocialSourceNetworkID" IN (5, 12) AND "ClientTimeZone" BETWEEN -5 AND 5 AND regexp_match("Referer", '\/campaign\/(spring|summer)_promo') IS NOT NULL AND CASE WHEN split_part(split_part("URL", 'resolution=', 2), '&', 1) ~ '^\d+$' THEN split_part(split_part("URL", 'resolution=', 2), '&', 1)::INT ELSE 0 END > 1920 AND levenshtein("UTMSource", "UTMCampaign") < 3;
\ No newline at end of file
+SELECT COUNT(*) AS ShareCount FROM hits WHERE "IsMobile" = 1 AND "MobilePhoneModel" LIKE 'iPhone%' AND "SocialAction" = 'share' AND "SocialSourceNetworkID" IN (5, 12) AND "ClientTimeZone" BETWEEN -5 AND 5 AND regexp_match("Referer", '\/campaign\/(spring|summer)_promo') IS NOT NULL AND CASE WHEN split_part(split_part("URL", 'resolution=', 2), '&', 1) ~ '^\d+$' THEN split_part(split_part("URL", 'resolution=', 2), '&', 1)::INT ELSE 0 END > 1920 AND levenshtein(CAST("UTMSource" AS STRING), CAST("UTMCampaign" AS STRING)) < 3;
```
Comment (Weijun-H) [inline benchmarks/queries/clickbench/extended.sql:7]:
```suggestion
SELECT COUNT(*) AS ShareCount FROM hits WHERE "IsMobile" = 1 AND "MobilePhoneModel" LIKE 'iPhone%' AND "SocialAction" = 'share' AND "SocialSourceNetworkID" IN (5, 12) AND "ClientTimeZone" BETWEEN -5 AND 5 AND regexp_match("Referer", '\/campaign\/(spring|summer)_promo') IS NOT NULL AND CASE WHEN split_part(split_part("URL", 'resolution=', 2), '&', 1) ~ '^\d+$' THEN split_part(split_part("URL", 'resolution=', 2), '&', 1)::INT ELSE 0 END > 1920 AND levenshtein('UTMSource', 'UTMCampaign') < 3;
```

File: benchmarks/queries/clickbench/README.md [hunk 2]
```diff
@@ -155,7 +155,7 @@ WHERE
         THEN split_part(split_part("URL", 'resolution=', 2), '&', 1)::INT 
         ELSE 0 
     END > 1920 -- Extract and validate resolution parameter
-    AND levenshtein("UTMSource", "UTMCampaign") < 3 -- Verify UTM parameter similarity
+    AND levenshtein(CAST("UTMSource" AS STRING), CAST("UTMCampaign" AS STRING)) < 3 -- Verify UTM parameter similarity
```
Comment (Weijun-H) [inline benchmarks/queries/clickbench/README.md:158]:
```suggestion
    AND levenshtein('UTMSource', 'UTMCampaign') < 3 -- Verify UTM parameter similarity
```

**Review by Weijun-H — APPROVED** [review]
Thanks @chenkovsky 👍 I tested `cargo bench --profile=dev --bench sql_planner -- physical_plan_clickbench_all`, and it worked perfectly.

File: benchmarks/queries/clickbench/README.md (hunk 2 above)
Comment (Weijun-H) [reply benchmarks/queries/clickbench/README.md:158]: Apologies, I misspoke earlier. In this case, we can’t use ‘UTMSource’ here because it’s a column name.

**Review by xudong963 — APPROVED** [review]

**Comment by xudong963** [comment]
Thank you

**Comment by alamb** [comment]
Thank you so much @chenkovsky and @xudong963
