### PR TITLE
fix: Use codepoints in `lpad`, `rpad`, `translate`

### LINKED ISSUE #21060: lpad, rpad, translate should use codepoints, not graphemes
### Describe the bug

For consistency with most other SQL implementations (including Postgres), as well as the rest of DataFusion, `lpad`, `rpad`, and `translate` should use codepoints when manipulating Unicode strings, not graphemes. #3054 switched to using codepoints instead of graphemes in most places, but AFAICS the same should be done for these remaining UDFs.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by neilconway**
## Which issue does this PR close?

- Closes #21060.

## Rationale for this change

`lpad`, `rpad`, and `translate` use grapheme segmentation. This is inconsistent with how these functions behave in Postgres and DuckDB, as well as the SQL standard -- segmentation based on Unicode codepoints is used instead. It also happens that grapheme-based segmentation is significantly more expensive than codepoint-based segmentation.

In the case of `lpad` and `rpad`, graphemes and codepoints were used inconsistently: the input string was measured in code points but the fill string was measured in graphemes.

#3054 switched to using codepoints for most string-related functions in DataFusion but these three functions still need to be changed.

Benchmarks (M4 Max):

lpad size=1024:
  - lpad utf8 [str_len=5, target=20]: 12.4 µs → 12.8 µs, +3.0%
  - lpad stringview [str_len=5, target=20]: 11.5 µs → 11.7 µs, +1.4%
  - lpad utf8 [str_len=20, target=50]: 11.3 µs → 11.3 µs, +0.1%
  - lpad stringview [str_len=20, target=50]: 11.8 µs → 12.0 µs, +1.6%
  - lpad utf8 unicode [target=20]: 98.4 µs → 24.4 µs, -75.1%
  - lpad stringview unicode [target=20]: 99.8 µs → 26.0 µs, -74.0%
  - lpad utf8 scalar [str_len=5, target=20, fill='x']: 8.7 µs → 8.8 µs, +1.0%
  - lpad stringview scalar [str_len=5, target=20, fill='x']: 10.2 µs → 10.1 µs, -0.1%
  - lpad utf8 scalar unicode [str_len=5, target=20, fill='é']: 44.7 µs → 10.9 µs, -75.7%
  - lpad utf8 scalar truncate [str_len=20, target=5, fill='é']: 152.5 µs → 11.7 µs, -92.3%

  lpad size=4096:
  - lpad utf8 [str_len=5, target=20]: 55.9 µs → 55.1 µs, -1.4%
  - lpad stringview [str_len=5, target=20]: 49.2 µs → 50.1 µs, +1.8%
  - lpad utf8 [str_len=20, target=50]: 46.6 µs → 46.4 µs, -0.5%
  - lpad stringview [str_len=20, target=50]: 47.5 µs → 48.5 µs, +2.1%
  - lpad utf8 unicode [target=20]: 401.3 µs → 100.1 µs, -75.0%
  - lpad stringview unicode [target=20]: 397.7 µs → 104.9 µs, -73.6%
  - lpad utf8 scalar [str_len=5, target=20, fill='x']: 34.2 µs → 35.0 µs, +2.4%
  - lpad stringview scalar [str_len=5, target=20, fill='x']: 40.1 µs → 40.4 µs, +0.6%
  - lpad utf8 scalar unicode [str_len=5, target=20, fill='é']: 178.3 µs → 42.9 µs, -76.0%
  - lpad utf8 scalar truncate [str_len=20, target=5, fill='é']: 601.3 µs → 46.2 µs, -92.3%

  rpad size=1024:
  - rpad utf8 [str_len=5, target=20]: 15.5 µs → 14.4 µs, -7.1%
  - rpad stringview [str_len=5, target=20]: 13.8 µs → 14.0 µs, +1.7%
  - rpad utf8 [str_len=20, target=50]: 12.6 µs → 12.7 µs, +1.3%
  - rpad stringview [str_len=20, target=50]: 13.0 µs → 13.1 µs, +0.7%
  - rpad utf8 unicode [target=20]: 103.5 µs → 26.0 µs, -74.8%
  - rpad stringview unicode [target=20]: 101.2 µs → 27.6 µs, -72.7%
  - rpad utf8 scalar [str_len=5, target=20, fill='x']: 11.4 µs → 10.9 µs, -3.9%
  - rpad stringview scalar [str_len=5, target=20, fill='x']: 12.2 µs → 12.6 µs, +2.8%
  - rpad utf8 scalar unicode [str_len=5, target=20, fill='é']: 46.3 µs → 12.4 µs, -73.1%
  - rpad utf8 scalar truncate [str_len=20, target=5, fill='é']: 155.6 µs → 11.6 µs, -92.4%

  rpad size=4096:
  - rpad utf8 [str_len=5, target=20]: 70.1 µs → 61.6 µs, -12.2%
  - rpad stringview [str_len=5, target=20]: 60.4 µs → 56.8 µs, -6.0%
  - rpad utf8 [str_len=20, target=50]: 50.6 µs → 51.2 µs, +1.2%
  - rpad stringview [str_len=20, target=50]: 53.7 µs → 53.3 µs, -0.8%
  - rpad utf8 unicode [target=20]: 407.1 µs → 104.0 µs, -74.5%
  - rpad stringview unicode [target=20]: 404.8 µs → 114.5 µs, -71.7%
  - rpad utf8 scalar [str_len=5, target=20, fill='x']: 47.5 µs → 45.6 µs, -4.0%
  - rpad stringview scalar [str_len=5, target=20, fill='x']: 56.4 µs → 58.5 µs, +3.6%
  - rpad utf8 scalar unicode [str_len=5, target=20, fill='é']: 184.1 µs → 48.1 µs, -73.9%
  - rpad utf8 scalar truncate [str_len=20, target=5, fill='é']: 606.4 µs → 45.6 µs, -92.5%

  translate size=1024:
  - array_from_to [str_len=8]: 140.0 µs → 37.6 µs, -73.2%
  - scalar_from_to [str_len=8]: 9.0 µs → 8.8 µs, -2.7%
  - array_from_to [str_len=32]: 371.3 µs → 65.6 µs, -82.3%
  - scalar_from_to [str_len=32]: 19.9 µs → 19.2 µs, -3.6%
  - array_from_to [str_len=128]: 1249.6 µs → 188.7 µs, -84.9%
  - scalar_from_to [str_len=128]: 70.2 µs → 64.7 µs, -7.9%
  - array_from_to [str_len=1024]: 9349.4 µs → 1378.1 µs, -85.3%
  - scalar_from_to [str_len=1024]: 506.5 µs → 445.8 µs, -12.0%

  translate size=4096:
  - array_from_to [str_len=8]: 548.0 µs → 147.1 µs, -73.2%
  - scalar_from_to [str_len=8]: 33.9 µs → 32.8 µs, -3.1%
  - array_from_to [str_len=32]: 1457.2 µs → 266.0 µs, -81.7%
  - scalar_from_to [str_len=32]: 78.0 µs → 75.5 µs, -3.2%
  - array_from_to [str_len=128]: 4935.0 µs → 791.1 µs, -84.0%
  - scalar_from_to [str_len=128]: 278.2 µs → 260.7 µs, -6.3%
  - array_from_to [str_len=1024]: 37496 µs → 5591 µs, -85.1%
  - scalar_from_to [str_len=1024]: 2058.0 µs → 1770 µs, -14.0%

## What changes are included in this PR?

* Switch from grapheme segmentation to codepoint segmentation for `lpad`, `rpad`, and `translate`
* Add SLT tests
* Refactor a few helper functions
* Remove dependency on `unicode_segmentation` crate as it is no longer used

## Are these changes tested?

Yes. The new SLT tests were also run against DuckDB and Postgres to confirm the behavior is consistent.

## Are there any user-facing changes?

Yes. This PR changes the behavior of `lpad`, `rpad`, and `translate`, although the new behavior is more consistent with the SQL standard and with other SQL implementations.

### CODE REVIEW

**Comment by neilconway** [comment]
FYI @martin-g -- this came up as part of reviewing #20657

**Review by Dandandan — APPROVED** [review]
LGTM

File: datafusion/functions/src/unicode/lpad.rs [hunk 1]
```diff
@@ -270,22 +269,19 @@ fn lpad_scalar_unicode<'a, V: StringArrayType<'a> + Copy, T: OffsetSizeTrait>(
...
-                graphemes_buf.extend(string.graphemes(true));
+                let char_count = string.chars().count();
 
-                if target_len < graphemes_buf.len() {
-                    let end: usize =
-                        graphemes_buf[..target_len].iter().map(|g| g.len()).sum();
-                    builder.append_value(&string[..end]);
+                if target_len < char_count {
+                    builder
+                        .append_value(&string[..byte_offset_of_char(string, target_len)]);
```
Comment (martin-g) [inline datafusion/functions/src/unicode/lpad.rs]: Both `byte_offset_of_char(string, ...)` and `let char_count = string.chars().count();` iterate over the chars in `string`.
It could be optimized to iterate just once with something like:
```rust
let mut char_count = 0;
let mut truncate_offset = None;
for (i, (byte_idx, _)) in string.char_indices().enumerate() {
    if i == target_len {
        truncate_offset = Some(byte_idx);
    }
    char_count += 1;
}
if let Some(offset) = truncate_offset {
    builder.append_value(&string[..offset]);
    ... 
```

File: datafusion/functions/src/unicode/rpad.rs [hunk 2]
```diff
@@ -271,22 +270,19 @@ fn rpad_scalar_unicode<'a, V: StringArrayType<'a> + Copy, T: OffsetSizeTrait>(
...
-                graphemes_buf.extend(string.graphemes(true));
+                let char_count = string.chars().count();
 
-                if target_len < graphemes_buf.len() {
-                    let end: usize =
-                        graphemes_buf[..target_len].iter().map(|g| g.len()).sum();
-                    builder.append_value(&string[..end]);
+                if target_len < char_count {
+                    builder
+                        .append_value(&string[..byte_offset_of_char(string, target_len)]);
```
Comment (martin-g) [inline datafusion/functions/src/unicode/rpad.rs]: Similar to lpad - two passes over the string when truncation is needed.

File: datafusion/sqllogictest/test_files/string/string_literal.slt [hunk 3]
```diff
@@ -1829,3 +1886,27 @@ query T
...
+true
+
+# Replacing the base character but not the combining accent.
+query B
+SELECT translate('e' || chr(769) || 'y', 'e', 'a') = 'a' || chr(769) || 'y'
+----
+true
+
+# Deleting a combining accent (from longer than to).
+# 'e' || chr(769) || 'x' with chr(769) in from but no corresponding to entry → deleted.
```
Comment (martin-g) [inline datafusion/sqllogictest/test_files/string/string_literal.slt]:
```suggestion
# 'e' || chr(769) || 'x' with chr(769) in `from` but no corresponding `to` entry → deleted.
```

**Review by martin-g — APPROVED** [review]

File: datafusion/functions/src/unicode/rpad.rs [hunk 4]
```diff
@@ -492,16 +484,15 @@ where
...
-                            graphemes_buf[..target_len].iter().map(|g| g.len()).sum();
-                        builder.append_value(&string[..end]);
+                    if target_len < char_count {
+                        builder.append_value(
+                            &string[..byte_offset_of_char(string, target_len)],
+                        );
                     } else {
                         builder.write_str(string)?;
-                        for _ in 0..(target_len - graphemes_buf.len()) {
+                        for _ in 0..(target_len - char_count) {
```
Comment (Dandandan) [inline datafusion/functions/src/unicode/rpad.rs]: couldn't this use some `repeat` `extend` or something?

File: datafusion/functions/src/unicode/rpad.rs [hunk 5]
```diff
@@ -492,16 +484,15 @@ where
...
                 } else {
-                    graphemes_buf.clear();
-                    graphemes_buf.extend(string.graphemes(true));
+                    let char_count = string.chars().count();
 
-                    if target_len < graphemes_buf.len() {
-                        let end: usize =
-                            graphemes_buf[..target_len].iter().map(|g| g.len()).sum();
-                        builder.append_value(&string[..end]);
+                    if target_len < char_count {
```
Comment (Dandandan) [inline datafusion/functions/src/unicode/rpad.rs]: Would <= not be correct here?

**Comment by martin-g** [comment]
Maybe a note should be added to the migration guide because there is a small behavior change in these functions.

File: datafusion/functions/src/unicode/lpad.rs (hunk 1 above)
Comment (neilconway) [reply datafusion/functions/src/unicode/lpad.rs]: Good idea! I added a helper here to do this in one place and DRY up the code a bit.

File: datafusion/functions/src/unicode/rpad.rs (hunk 5 above)
Comment (neilconway) [reply datafusion/functions/src/unicode/rpad.rs]: I refactored the code here as part of some improvements @martin-g suggested, so I think this is moot now.

File: datafusion/functions/src/unicode/rpad.rs (hunk 4 above)
Comment (neilconway) [reply datafusion/functions/src/unicode/rpad.rs]: You could, although this is just what the pre-existing code did. I think `repeat` would allocate and `write_str` in a loop will not; not sure offhand which is better but I'd think it's a wash? We could look at this in a followup PR if you'd like?

**Comment by neilconway** [comment]
> Maybe a note should be added to the migration guide because there is a small behavior change in these functions.

Thanks! Done.

File: datafusion/functions/src/unicode/lpad.rs (hunk 1 above)
Comment (neilconway) [reply datafusion/functions/src/unicode/lpad.rs]: I posted updated benchmark results, this is a nice win.

Comment (martin-g) [reply datafusion/functions/src/unicode/lpad.rs]: Awesome!

**Review by martin-g — APPROVED** [review]

**Comment by neilconway** [comment]
@martin-g @Dandandan Is this ready to be merged?

**Comment by alamb** [comment]
🚀

**Comment by alamb** [comment]
I can click the merge button with the best of them!
