### PR TITLE
fix: Avoid unnecessary type casts in `concat_ws`

### LINKED ISSUE #20434: concat_ws does unnecessary type casts
### Describe the bug

1. `concat_ws` returns `Utf8`, regardless of the input types it is called with. So if it is called with `LargeUtf8`, we might overflow. In general, functions like these should operate on all three string representations unless there is a compelling reason not to.
2. `simplify_concat_ws` coerces literals to `Utf8`. Again, we should generally preserve the original string type.

### To Reproduce

Note the 

```
DataFusion CLI v52.1.0
>       CREATE TABLE test_views AS
      SELECT arrow_cast('hello', 'Utf8View') AS a, arrow_cast('world', 'Utf8View') AS b;
0 row(s) fetched.
Elapsed 0.027 seconds.

> EXPLAIN SELECT * FROM test_views WHERE concat(a, b) = a;
+---------------+-------------------------------+
| plan_type     | plan                          |
+---------------+-------------------------------+
| physical_plan | ┌───────────────────────────┐ |
|               | │         FilterExec        │ |
|               | │    --------------------   │ |
|               | │         predicate:        │ |
|               | │      concat(a, b) = a     │ |
|               | └─────────────┬─────────────┘ |
|               | ┌─────────────┴─────────────┐ |
|               | │       DataSourceExec      │ |
|               | │    --------------------   │ |
|               | │         bytes: 272        │ |
|               | │       format: memory      │ |
|               | │          rows: 1          │ |
|               | └───────────────────────────┘ |
|               |                               |
+---------------+-------------------------------+
1 row(s) fetched.
Elapsed 0.010 seconds.

> EXPLAIN SELECT * FROM test_views WHERE concat_ws(',', a, b) = a;
+---------------+-------------------------------+
| plan_type     | plan                          |
+---------------+-------------------------------+
| physical_plan | ┌───────────────────────────┐ |
|               | │         FilterExec        │ |
|               | │    --------------------   │ |
|               | │         predicate:        │ |
|               | │ CAST(concat_ws(,, a, b) AS│ |
|               | │        Utf8View) = a      │ |
|               | └─────────────┬─────────────┘ |
|               | ┌─────────────┴─────────────┐ |
|               | │       DataSourceExec      │ |
|               | │    --------------------   │ |
|               | │         bytes: 272        │ |
|               | │       format: memory      │ |
|               | │          rows: 1          │ |
|               | └───────────────────────────┘ |
|               |                               |
+---------------+-------------------------------+
1 row(s) fetched.
Elapsed 0.007 seconds.

> explain SELECT concat(a, concat(a, b)) FROM test_views;
+---------------+-------------------------------+
| plan_type     | plan                          |
+---------------+-------------------------------+
| physical_plan | ┌───────────────────────────┐ |
|               | │       ProjectionExec      │ |
|               | │    --------------------   │ |
|               | │ concat(test_views.a,concat│ |
|               | │  (test_views.a,test_views │ |
|               | │           .b)):           │ |
|               | │  concat(a, concat(a, b))  │ |
|               | └─────────────┬─────────────┘ |
|               | ┌─────────────┴─────────────┐ |
|               | │       DataSourceExec      │ |
|               | │    --------------------   │ |
|               | │         bytes: 272        │ |
|               | │       format: memory      │ |
|               | │          rows: 1          │ |
|               | └───────────────────────────┘ |
|               |                               |
+---------------+-------------------------------+
1 row(s) fetched.
Elapsed 0.005 seconds.

> explain SELECT concat(a, concat_ws(',', a, b)) FROM test_views;
+---------------+-------------------------------+
| plan_type     | plan                          |
+---------------+-------------------------------+
| physical_plan | ┌───────────────────────────┐ |
|               | │       ProjectionExec      │ |
|               | │    --------------------   │ |
|               | │    concat(test_views.a    │ |
|               | │     ,concat_ws(Utf8(",    │ |
|               | │      "),test_views.a      │ |
|               | │      ,test_views.b)):     │ |
|               | │ concat(a, CAST(concat_ws(,│ |
|               | │   , a, b) AS Utf8View))   │ |
|               | └─────────────┬─────────────┘ |
|               | ┌─────────────┴─────────────┐ |
|               | │       DataSourceExec      │ |
|               | │    --------------------   │ |
|               | │         bytes: 272        │ |
|               | │       format: memory      │ |
|               | │          rows: 1          │ |
|               | └───────────────────────────┘ |
|               |                               |
+---------------+-------------------------------+
1 row(s) fetched.
Elapsed 0.006 seconds.
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by neilconway**
## Which issue does this PR close?

- Closes #20434.

## Rationale for this change

1. `concat_ws` returned `Utf8`, regardless of the input types it was called with. If it was called with `LargeUtf8`, returning `Utf8` might overflow. In general, functions like these should operate on all three string representations unless there is a compelling reason not to (e.g., this is how `concat` works).
4. `simplify_concat_ws` always constructed new literals with type `Utf8`. This lead to unnecessary casts when its inputs were of a different string type.

## What changes are included in this PR?

* Support `concat_ws` return type matching its input types, following how `concat` does it.
* In `simplify_concat_ws`, construct literals with the right type, not always `Utf8`
* Refactor `return_type` for `concat` to be more readable
* Make `StringViewArrayBuilder` API more similar to the other string array builders, WRT null handling
* Add new unit and SLT tests
* Update test output for changed types

## Are these changes tested?

Yes.

## Are there any user-facing changes?

Yes: some queries involving `concat_ws` will now omit unnecessary cast operations, and the return type of `concat_ws` might be any of the three string types. Generally these changes should match user expectations better than the previous behavior.

### CODE REVIEW

**Comment by Omega359** [comment]
I did a quick look at the changes and nothing obvious jumped out at me. I'll try and find time to do a more extensive review if no one else beats me to it.

**Comment by neilconway** [comment]
@Omega359 Thank you!

**Comment by Omega359** [comment]
🤖 `/home/bruce/gh_compare_branch_bench.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/gh_compare_branch_bench.sh) Running
Linux fedora 6.18.12-200.fc43.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Feb 16 18:58:26 UTC 2026 x86_64 GNU/Linux
Comparing neilc/concat-ws-type-fixes (9c0b4f4bedc3a9af1e1140518dcfa4281db9001e) to c3f080774cd5dd588b5250317ac3b0fc393c0647 [diff](https://github.com/apache/datafusion/compare/c3f080774cd5dd588b5250317ac3b0fc393c0647..9c0b4f4bedc3a9af1e1140518dcfa4281db9001e)
BENCH_NAME=concat_ws
BENCH_COMMAND=cargo bench --bench concat_ws
BENCH_FILTER=
BENCH_BRANCH_NAME=neilc_concat-ws-type-fixes
Results will be posted here when complete

**Comment by Omega359** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                                  main                                   neilc_concat-ws-type-fixes
-----                                  ----                                   --------------------------
concat_ws function/concat_ws/1024      1.00     11.1±0.08µs        ? ?/sec    1.16     12.9±2.43µs        ? ?/sec
concat_ws function/concat_ws/4096      1.00     44.1±0.88µs        ? ?/sec    1.02     44.8±1.95µs        ? ?/sec
concat_ws function/concat_ws/8192      1.00     88.5±3.98µs        ? ?/sec    1.02     90.4±3.22µs        ? ?/sec
concat_ws function/concat_ws/scalar    1.00     28.3±0.15µs        ? ?/sec    1.02     28.8±0.41µs        ? ?/sec
```


</p>
</details>

File: datafusion/functions/src/string/concat_ws.rs [hunk 1]
```diff
@@ -268,28 +314,71 @@ impl ScalarUDFImpl for ConcatWsFunc {
             }
         }
 
-        let mut builder = StringArrayBuilder::with_capacity(len, data_size);
-        for i in 0..len {
-            if !sep.is_valid(i) {
-                builder.append_offset();
-                continue;
+        match return_datatype {
+            DataType::Utf8View => {
```
Comment (Omega359) [inline datafusion/functions/src/string/concat_ws.rs:318]: I wonder if all this duplicated code could be eliminated with an approach similar to https://github.com/apache/datafusion/blob/2a08013af3ccf703bee202c959b40bb0d35bdea1/datafusion/functions-nested/src/string.rs#L792 ?

Comment (neilconway) [reply datafusion/functions/src/string/concat_ws.rs:318]: Yeah, I think that would make sense to do. I'm inclined to do it as a follow-up PR -- let me know if you'd prefer it as part of this PR.

Comment (Omega359) [reply datafusion/functions/src/string/concat_ws.rs:318]: I think that is fine.

**Comment by Omega359** [comment]
LGTM. @Jefffrey, @alamb I believe this is ready for final review and approval.

File: datafusion/functions/src/string/concat.rs [hunk 2]
```diff
@@ -88,37 +88,33 @@ impl ScalarUDFImpl for ConcatFunc {
...
-            }
-            if data_type == &LargeUtf8 && dt != &Utf8View {
-                dt = data_type;
-            }
-        });
-
-        Ok(dt.to_owned())
+        if arg_types.contains(&Utf8View) {
+            Ok(Utf8View)
+        } else if arg_types.contains(&LargeUtf8) {
```
Comment (Omega359) [inline datafusion/functions/src/string/concat.rs:98]: I had a thought about this. I think LargeUtf8 should take precedence over Utf8View because you cannot necessarily fit data from a LargeUtf8 column into Utf8View (i64 vs i32) https://docs.rs/arrow/latest/arrow/datatypes/enum.DataType.html#variant.LargeUtf8

Comment (neilconway) [reply datafusion/functions/src/string/concat.rs:98]: Interesting point. I believe the typical precedence today is Utf8View > LargeUtf8 > Utf8, partly on the grounds that "StringArray to StringViewArray is cheap but not vice versa". I can see arguments for both sides; if we want to reconsider this, seems like a distinct issue?

https://github.com/apache/datafusion/blob/e894a03bea638e35677eaf27876966013dd64bf4/datafusion/expr-common/src/type_coercion/binary.rs#L1663-L1667

Comment (Omega359) [reply datafusion/functions/src/string/concat.rs:98]: Likely it should be another issue as it likely occurs in a few places. I am fairly certain I am correct on the proper type ordering here but in the wild I doubt it would be encountered much - just how many columns would have > 2 billion bytes?

Comment (Omega359) [reply datafusion/functions/src/string/concat.rs:98]: Also, this is really only pertinent in areas that pick a return type based on multiple columns. For the typical case where the udf is operating on a single column the existing logic should be fine - such as in [btrim](https://github.com/apache/datafusion/blob/a026e7da2fe88f1923770ec3249c5f0e7b2ea6b0/datafusion/functions/src/string/btrim.rs#L113)

Comment (alamb) [reply datafusion/functions/src/string/concat.rs:98]: >  I think LargeUtf8 should take precedence over Utf8View because you cannot necessarily fit data from a LargeUtf8 column into Utf8View (i64 vs i32)

I think the only type of data that can't be stored in a Utf8View that a LargeUtf8 an handle is individual strings that are longer than 2GB

Otherwise, data from a LargeUtf8 will work just fine in Utf8View (the view will have multiple buffers rather than one large one)

Comment (Omega359) [reply datafusion/functions/src/string/concat.rs:98]: > > I think LargeUtf8 should take precedence over Utf8View because you cannot necessarily fit data from a LargeUtf8 column into Utf8View (i64 vs i32)
> 
> I think the only type of data that can't be stored in a Utf8View that a LargeUtf8 an handle is individual strings that are longer than 2GB
> 
> Otherwise, data from a LargeUtf8 will work just fine in Utf8View (the view will have multiple buffers rather than one large one)

Indeed, that was the point I was trying to get across. It's a rare ... but possible. Though honestly I expect DF would fail somewhere else pretty quickly if a column with data that big was ever encountered.

**Comment by neilconway** [comment]
@alamb This is ready to be reviewed and/or merged, I think.
