### PR TITLE
Fix: ensure that compression type is also taken into consideration during ListingTableConfig infer_options

### LINKED ISSUE #14016: Inference of ListingTableConfig does not work (anymore) for compressed json file
### Describe the bug

Inference of ListingTableConfig does not work (anymore) for compressed json file

With datafusion 35 and 36 the expected schema is inferred.
With datafusion 37, 38 and 39 we see an error: ArrowError(JsonError("Failed to read JSON record: stream did not contain valid UTF-8"), None)
With datafusion 40+ we error goes away, but no schema is inferred

### To Reproduce

```rust

    let ctx = SessionContext::new();

    // the file can be found here: https://github.com/timvw/arrow-testing/blob/master/data/json/ndjson-sample.json.gz
    let data_path = "/somewhere/testing/data/json/ndjson-sample.json.gz";

    let table_path = ListingTableUrl::parse(&data_path)?;
    let config = ListingTableConfig::new(table_path);
    let mut config_with_opts = config.infer_options(&ctx.state()).await?;
    let config_with_schema = config_with_opts.infer_schema(&ctx.state()).await?;

```

### Expected behavior

The schema is inferred as in earlier versions

### Additional context

Initial investigation shows that in ListingTableConfig infer_options method there is information loss:
- file_extension is inferred to be "json" (instead of json.gz in the past) -> no files will be found in infer_schema
- file_format is created without capturing the (potential) compression type -> trying to read the file (without codec) results in the error mentionned

### PR DESCRIPTION
**Pull request by timvw**
## Which issue does this PR close?

- Closes #14016 .
- closes https://github.com/timvw/datafusion/pull/1

## What changes are included in this PR?

Relatively simple changes to ensure that eventual compression information is considered

## Are these changes tested?

Yes. Added test to verify behavior is as expected.

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/core/src/datasource/listing/table.rs [hunk 1]
```diff
@@ -114,19 +114,22 @@ impl ListingTableConfig {
         }
     }
 
-    fn infer_file_extension(path: &str) -> Result<String> {
+    fn infer_file_extension_and_compression_type(
```
Comment (alamb) [inline datafusion/core/src/datasource/listing/table.rs:117]: Can you please document what the return values are? Something like

```suggestion
    /// Returns a tuple of (file_extension, optional compression_extension)
    ///
    /// For example `("csv", Some("gz"))`
    fn infer_file_extension_and_compression_type(
```

File: datafusion/core/src/datasource/listing/table.rs [hunk 2]
```diff
@@ -147,18 +150,31 @@ impl ListingTableConfig {
...
+        let (file_extension, maybe_compression_type) =
+            ListingTableConfig::infer_file_extension_and_compression_type(
+                file.location.as_ref(),
+            )?;
+
+        let mut format_options = HashMap::new();
+
+        let listing_file_extension =
+            if let Some(compression_type) = maybe_compression_type {
+                format_options
```
Comment (alamb) [inline datafusion/core/src/datasource/listing/table.rs:162]: Very minor: I think if you reoranized this code you could avoid `clone`ing the compression_type and file_extension.

File: datafusion/core/src/datasource/listing/table.rs [hunk 3]
```diff
@@ -2194,4 +2210,23 @@ mod tests {
...
+
+        let ctx = SessionContext::new();
+
+        let config = ListingTableConfig::new(table_path);
+        let config_with_opts = config.infer_options(&ctx.state()).await?;
+        let config_with_schema = config_with_opts.infer_schema(&ctx.state()).await?;
+
+        let schema = config_with_schema.file_schema.unwrap();
+
+        assert_eq!(schema.fields.len(), 13);
```
Comment (alamb) [inline datafusion/core/src/datasource/listing/table.rs:2228]: I verified that without the code in this PR this test fails like this:

```

assertion `left == right` failed
  left: 0
 right: 13

Left:  0
Right: 13
<Click to see difference>

thread 'datasource::listing::table::tests::test_infer_options_compressed_csv' panicked at datafusion/core/src/datasource/listing/table.rs:2212:9:
assertion `left == right` failed
  left: 0
 right: 13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /Users/andrewlamb/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:367:5
   4: datafusion::datasource::listing::table::tests::test_infer_options_compressed_csv::{{closure}}
             at ./src/datasource/listing/table.rs:2212:9
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /Users/andrewlamb/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:123:9
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /Users/andrewlamb/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/future/future.rs:123:9
   7: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/current_thread/mod.rs:729:57
   8: tokio::runtime::coop::with_budget
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/coop.rs:107:5
   9: tokio::runtime::coop::budget
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/coop.rs:73:5
  10: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/current_thread/mod.rs:729:25
  11: tokio::runtime::scheduler::current_thread::Context::enter
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/current_thread/mod.rs:428:19
  12: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/current_thread/mod.rs:728:36
  13: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/current_thread/mod.rs:807:68
  14: tokio::runtime::context::scoped::Scoped<T>::set
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/context/scoped.rs:40:9
  15: tokio::runtime::context::set_scheduler::{{closure}}
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/context.rs:180:26
  16: std::thread::local::LocalKey<T>::try_with
             at /Users/andrewlamb/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:283:12
  17: std::thread::local::LocalKey<T>::with
             at /Users/andrewlamb/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/std/src/thread/local.rs:260:9
  18: tokio::runtime::context::set_scheduler
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/context.rs:180:9
  19: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/current_thread/mod.rs:807:27
  20: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/current_thread/mod.rs:716:19
  21: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/current_thread/mod.rs:196:28
  22: tokio::runtime::context::runtime::enter_runtime
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/context/runtime.rs:65:16
  23: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/scheduler/current_thread/mod.rs:184:9
  24: tokio::runtime::runtime::Runtime::block_on_inner
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/runtime.rs:368:47
  25: tokio::runtime::runtime::Runtime::block_on
             at /Users/andrewlamb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.42.0/src/runtime/runtime.rs:342:13
  26: datafusion::datasource::listing::table::tests::test_infer_options_compressed_csv
             at ./src/datasource/listing/table.rs:2214:9
  27: datafusion::datasource::listing::table::tests::test_infer_options_compressed_csv::{{closure}}
             at ./src/datasource/listing/table.rs:2199:53
  28: core::ops::function::FnOnce::call_once
             at /Users/andrewlamb/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  29: core::ops::function::FnOnce::call_once
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Review by alamb — APPROVED** [review]
Thank you @timvw  -- this PR looks good to me and fixes the issue 🙏 

I left some suggestions for improvements but I also think they are not required and/or can be done as follow on PRs

File: datafusion/core/src/datasource/listing/table.rs (hunk 1 above)
Comment (timvw) [reply datafusion/core/src/datasource/listing/table.rs:121]: Added the documentation as suggested

File: datafusion/core/src/datasource/listing/table.rs (hunk 2 above)
Comment (timvw) [reply datafusion/core/src/datasource/listing/table.rs]: You're correct. Restructuring has been comitted.

**Review by alamb — APPROVED** [review]
❤️

**Comment by alamb** [comment]
🤔 something seems to be broken now

**Comment by alamb** [comment]
> 🤔 something seems to be broken now

I feel bad that this broke after my suggestion -- here is a proposal targeting this branch to fix it:
- https://github.com/timvw/datafusion/pull/1

**Comment by alamb** [comment]
Thanks again @timvw
