### PR TITLE
fix: array_concat widens container variant for mixed List/LargeList inputs

### LINKED ISSUE #21702: array_concat fails with internal error on mixed List + LargeList inputs
### Describe the bug

Calling `array_concat` with a mix of `List` and `LargeList` arguments hits an internal cast error:

```sql
> select array_concat(make_array(1, 2), arrow_cast([3, 4], 'LargeList(Int64)'));
DataFusion error: Internal error: could not cast array of type List(Int64) to arrow_array::array::list_array::GenericListArray<i64>.
```

The issue is in `ArrayConcat::coerce_types` (`datafusion/functions-nested/src/concat.rs`). It uses the return type's base element type to coerce items but leaves the container variant alone, so a `List` input isn't coerced to `LargeList` when the return type is `LargeList`. Then `array_concat_inner` tries to downcast the `List` array to `GenericListArray<i64>` and fails.

Same symptom for `FixedSizeList + LargeList`.

### To Reproduce

```sql
select array_concat(make_array(1, 2), arrow_cast([3, 4], 'LargeList(Int64)'));
select array_concat(arrow_cast([1, 2], 'FixedSizeList(2, Int64)'), arrow_cast([3, 4], 'LargeList(Int64)'));
```

### Expected behavior

`[1, 2, 3, 4]` returned as `LargeList(Int64)` in both cases (the widest container variant).

### Additional context

Surfaced while reviewing [#21689](https://github.com/apache/datafusion/pull/21689), which rewrites `concat(array, ...)` to `array_concat(array, ...)` and inherits this limitation for `concat(List, LargeList)`.

### PR DESCRIPTION
**Pull request by hcrosse**
## Which issue does this PR close?

- Closes #21702.

## Rationale for this change

`array_concat` hit an internal cast error when given a mix of `List` and `LargeList` (or `FixedSizeList` and `LargeList`) arguments:

```sql
> select array_concat(make_array(1, 2), arrow_cast([3, 4], 'LargeList(Int64)'));
DataFusion error: Internal error: could not cast array of type List(Int64) to arrow_array::array::list_array::GenericListArray<i64>.
```

`ArrayConcat::coerce_types` was coercing only the base element type, leaving the outer container alone. When the resolved return type is `LargeList`, `array_concat_inner` later tries to downcast each arg to `GenericListArray<i64>`, which fails for any `List` argument that slipped through.

## What changes are included in this PR?

In `ArrayConcat::coerce_types`, after coercing the base type, also promote each input's outermost `List` to `LargeList` when the return type is a `LargeList`. `FixedSizeList` inputs already go through `FixedSizedListToList` first and then get promoted too. Per-arg dimensionality is preserved, so nested cases keep working with `align_array_dimensions`.

## Are these changes tested?

Yes, added sqllogictests in `array_concat.slt` covering:
- `List` + `LargeList`
- `LargeList` + `List`
- `FixedSizeList` + `LargeList`
- Three-way mix `List`, `LargeList`, `List`

Each one also asserts `arrow_typeof(...) = LargeList(Int64)`.

## Are there any user-facing changes?

Queries that previously returned an internal cast error now return the concatenated `LargeList` as expected. No API changes.

### CODE REVIEW

File: datafusion/functions-nested/src/concat.rs [hunk 1]
```diff
@@ -317,10 +317,23 @@ impl ScalarUDFImpl for ArrayConcat {
     }
 
     fn coerce_types(&self, arg_types: &[DataType]) -> Result<Vec<DataType>> {
-        let base_type = base_type(&self.return_type(arg_types)?);
```
Comment (Jefffrey) [inline datafusion/functions-nested/src/concat.rs:320]: I just realized something funny the existing implementation does; it calls `return_type` within `coerce_types` even though the docstring for `return_type` states that the input types are already coerced (i.e. `coerce_types` would have already been called) 😅

**Review by Jefffrey — APPROVED** [review]
Nice catch

**Comment by Jefffrey** [comment]
Thanks @hcrosse
