### PR TITLE
Fix overflow in pow

### LINKED ISSUE #11075: Overflow bug in POW scalar function (found by SQLancer)
### Describe the bug

The following statement should return an error instead of directly crash
```shell
DataFusion CLI v39.0.0
> select pow(2107754225, 1221660777);
thread 'main' panicked at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/num/mod.rs:358:5:
attempt to multiply with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Found by SQLancer https://github.com/apache/datafusion/issues/11030

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LorrensP-2158466**
## Which issue does this PR close?

Closes #11075.

## What changes are included in this PR?
- check overflow for integer parameters
- check that exponent is non negative for integer parameters (this was allowed but resulted in nothing)

## Are these changes tested?
Added SLT test 

## Are there any user-facing changes?
no

### CODE REVIEW

File: datafusion/functions/src/math/power.rs [hunk 1]
```diff
@@ -94,14 +96,25 @@ impl ScalarUDFImpl for PowerFunc {
...
+                let bases = downcast_arg!(&args[0], "base", Int64Array);
+                let exponents = downcast_arg!(&args[1], "exponent", Int64Array);
+                bases
+                    .iter()
+                    .zip(exponents.iter())
+                    .map(|(base, exp)| match (base, exp) {
+                        (Some(base), Some(exp)) => Ok(Some(base.pow_checked(
+                            exp.try_into().map_err(|_| {
+                                exec_datafusion_err!(
+                                    "Can't use negative exponents: {exp} in integer computation, please use Float."
```
Comment (alamb) [inline datafusion/functions/src/math/power.rs:109]: 💯  for the error message

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @LorrensP-2158466

**Review by jonahgao — APPROVED** [review]
LGTM, thanks @LorrensP-2158466
