### PR TITLE
Fix the null handling for to_char function

### LINKED ISSUE #14884: Fix the null handling for `to_char` function
### Describe the bug

Currenlty, if we input a null value to `to_char`, we will get an empty string instead of a null value.
```
> select to_char(NULL, '%Y-%m-%d %H:%M:%S') is null;
+-------------------------------------------------+
| to_char(NULL,Utf8("%Y-%m-%d %H:%M:%S")) IS NULL |
+-------------------------------------------------+
| false                                           |
+-------------------------------------------------+
1 row(s) fetched. 
Elapsed 0.001 seconds.

> select to_char(NULL, '%Y-%m-%d %H:%M:%S');
+-----------------------------------------+
| to_char(NULL,Utf8("%Y-%m-%d %H:%M:%S")) |
+-----------------------------------------+
|                                         |
+-----------------------------------------+
1 row(s) fetched. 
Elapsed 0.001 seconds.
```

However, the postgres behavior is returing a null value if got a null input.
```
psql=# select to_char(null::timestamp, '%Y-%m-%d %H:%M:%S') is null;
 ?column? 
----------
 t
(1 row)

psql=# select to_char(null::timestamp, '%Y-%m-%d %H:%M:%S');
 to_char 
---------
 
(1 row)
```

I think we should follow the behavior of postgres.

### To Reproduce

Execute the SQL mentioned above.

### Expected behavior

`to_char` should return a null if got a null input.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kosiew**
## Which issue does this PR close?

- Closes #14884.

## Rationale for this change

Currently, when passing a NULL value to to_char, it returns an empty string instead of NULL. [This behavior differs from PostgreSQL, Spark, DuckDb](https://github.com/apache/datafusion/issues/14884#issuecomment-2686313231), which returns NULL when given a NULL input. Aligning with common practise ensures consistency and expected behavior for users relying on SQL standards.

## What changes are included in this PR?

Modify to_char function implementation to return NULL when the input is NULL.

Update relevant test cases to validate the correct behavior.

Ensure consistent behavior across different data types.
## Are these changes tested?

Yes, test cases have been added to check the NULL behavior of to_char.

Existing test cases have been updated where necessary.

Verified that the changes do not introduce regressions.

## Are there any user-facing changes?

Users who previously received an empty string when calling to_char(NULL, format) will now receive NULL, aligning with PostgreSQL behavior.

No breaking changes to public APIs, but behavior will be corrected to match expected SQL standards.

### CODE REVIEW

**Comment by Omega359** [comment]
LGTM

File: datafusion/functions/src/datetime/to_char.rs [hunk 1]
```diff
@@ -663,4 +678,51 @@ mod tests {
             "Execution error: Format for `to_char` must be non-null Utf8, received Timestamp(Nanosecond, None)"
         );
     }
+
+    #[test]
+    fn test_to_char_input_none_scalar() {
```
Comment (jayzhan211) [inline datafusion/functions/src/datetime/to_char.rs:683]: we don't need rust test for this function, we can add it to slt

Comment (kosiew) [reply datafusion/functions/src/datetime/to_char.rs:683]: Thanks for spotting this.
Removed.

**Comment by alamb** [comment]
Thanks @kosiew and @jayzhan211
