### PR TITLE
Fix FilterExec converting Absent column stats to Exact(NULL)

### LINKED ISSUE #20388: `FilterExec::collect_new_statistics` converts Absent column stats to Exact(NULL), corrupting join cardinality estimation
### Describe the bug

Hi, this is my first issue here! 👋 
Thank you for this awesome project - I have so much fun building on top of what you've built here.

I ran into this while building [quiver](https://github.com/fwojciec/quiver), in the context of joining a combination of Postgres tables and views (custom `TableProvider`) to a large Parquet table. A query that should have taken ~7s was taking ~52s - the physical plan showed `Partitioned` join mode and a CASE-form dynamic filter that `PruningPredicate` couldn't evaluate, resulting in no row groups pruned. After fixing the statistics issue described below, the joins selected `CollectLeft`, the dynamic filter became a simple IN-list with range bounds, and 354/362 row groups were pruned.

**Disclosure**

I used Claude (Opus 4.6) to help trace through the statistics propagation chain and identify the root cause; the finding was independently confirmed by Codex 5.3. I understand the issue end-to-end and have a provisional fix in quiver that restored correct CollectLeft join selection and row group pruning (52s -> 7.7s performance improvement on my test query).

**The problem**

When a `FilterExec` sits above a table with no column-level statistics (all `Precision::Absent` - common for database views or unanalyzed tables), `collect_new_statistics` converts the absent min/max into `Precision::Exact(ScalarValue::Int32(None))`.

This happens because the interval analysis represents absent bounds as NULL `ScalarValue` endpoints, and `collect_new_statistics` doesn't distinguish "NULL meaning unbounded" from "a known equal value" - since `NULL == NULL`, the `lower.eq(&upper)` branch fires and wraps both in `Precision::Exact`.

Downstream, `estimate_disjoint_inputs` treats these `Exact(NULL)` values as real bounds, concludes the join inputs are disjoint, and returns zero cardinality. This forces `Partitioned` join mode, which produces CASE-form dynamic filters that `PruningPredicate` can't evaluate, disabling row group pruning entirely on the probe side.

### To Reproduce

the easiest way to reproduce is using a unit test against DataFusion codebase:

```rust
diff --git a/datafusion/physical-plan/src/filter.rs b/datafusion/physical-plan/src/filter.rs
index 2af0731fb..75501b783 100644
--- a/datafusion/physical-plan/src/filter.rs
+++ b/datafusion/physical-plan/src/filter.rs
@@ -2053,4 +2053,43 @@ mod tests {
 
         Ok(())
     }
+
+    /// Regression test: columns with Absent min/max statistics must remain
+    /// Absent after FilterExec, not be converted to Exact(NULL). The latter
+    /// causes `estimate_disjoint_inputs` to incorrectly conclude join inputs
+    /// are disjoint (ScalarValue's PartialOrd sorts NULLs last), producing
+    /// zero cardinality and forcing Partitioned join mode.
+    #[tokio::test]
+    async fn test_filter_statistics_absent_columns_stay_absent() -> Result<()> {
+        let schema = Schema::new(vec![
+            Field::new("a", DataType::Int32, false),
+            Field::new("b", DataType::Int32, false),
+        ]);
+        let input = Arc::new(StatisticsExec::new(
+            Statistics {
+                num_rows: Precision::Inexact(1000),
+                total_byte_size: Precision::Absent,
+                column_statistics: vec![
+                    ColumnStatistics::default(),
+                    ColumnStatistics::default(),
+                ],
+            },
+            schema.clone(),
+        ));
+
+        let predicate = Arc::new(BinaryExpr::new(
+            Arc::new(Column::new("a", 0)),
+            Operator::Eq,
+            Arc::new(Literal::new(ScalarValue::Int32(Some(42)))),
+        ));
+        let filter: Arc<dyn ExecutionPlan> =
+            Arc::new(FilterExec::try_new(predicate, input)?);
+
+        let statistics = filter.partition_statistics(None)?;
+        let col_b_stats = &statistics.column_statistics[1];
+        assert_eq!(col_b_stats.min_value, Precision::Absent);
+        assert_eq!(col_b_stats.max_value, Precision::Absent);
+
+        Ok(())
+    }
 }
```

this test currently fails with:

```
assertion `left == right` failed
  left: Exact(Int32(NULL))
  right: Absent
```

### Expected behavior

`collect_new_statistics` should map NULL interval bounds back to `Precision::Absent`, not wrap them in `Precision::Exact`.

### Additional context

I have a working fix for this (and the regression test above) - happy to submit as a PR if the approach looks right. Wanted to file the issue first to check.

### PR DESCRIPTION
**Pull request by fwojciec**
## Which issue does this PR close?

- Closes #20388.

## Rationale for this change

`collect_new_statistics` in `FilterExec` wraps NULL interval bounds in `Precision::Exact`, converting what should be `Precision::Absent` column statistics into `Precision::Exact(ScalarValue::Int32(None))`. Downstream, `estimate_disjoint_inputs` treats these as real bounds and incorrectly concludes join inputs are disjoint, forcing Partitioned join mode and disabling dynamic filter pushdown for Parquet row group pruning.

## What changes are included in this PR?

Single change to `collect_new_statistics` in `filter.rs`: check `is_null()` on interval bounds before wrapping in `Precision`, mapping NULL bounds back to `Absent`.

## Are these changes tested?

Yes — includes a regression test (`test_filter_statistics_absent_columns_stay_absent`) that fails on current main and passes with the fix.

## Are there any user-facing changes?

No API changes. Corrects statistics propagation for tables/views with absent column statistics.

### CODE REVIEW

File: datafusion/physical-plan/src/filter.rs [hunk 1]
```diff
@@ -2053,4 +2064,43 @@ mod tests {
 
         Ok(())
     }
+
+    /// Regression test: columns with Absent min/max statistics must remain
+    /// Absent after FilterExec, not be converted to Exact(NULL). The latter
+    /// causes `estimate_disjoint_inputs` to incorrectly conclude join inputs
+    /// are disjoint (ScalarValue's PartialOrd sorts NULLs last), producing
+    /// zero cardinality and forcing Partitioned join mode.
```
Comment (neilconway) [inline datafusion/physical-plan/src/filter.rs]: Some parts of this comment overfit to the exact scenario you ran into and other implementation details. What about something simpler like:


```suggestion
    /// Columns with Absent min/max statistics should remain Absent after
    /// FilterExec.
```

File: datafusion/physical-plan/src/filter.rs [hunk 2]
```diff
@@ -771,10 +771,21 @@ fn collect_new_statistics(
...
                 } else {
-                    (Precision::Inexact(lower), Precision::Inexact(upper))
+                    Precision::Inexact(lower)
+                };
+                let max_value = if upper.is_null() {
+                    Precision::Absent
+                } else if bounds_equal {
+                    Precision::Exact(upper)
+                } else {
+                    Precision::Inexact(upper)
```
Comment (neilconway) [inline datafusion/physical-plan/src/filter.rs]: I found the revised logic a little hard to read. What about something like:

```suggestion
                 let is_exact =
                     !lower.is_null() && !upper.is_null() && lower == upper;
                 let min_value = interval_bound_to_precision(lower, is_exact);
                 let max_value = interval_bound_to_precision(upper, is_exact);
```

Where we define a helper func:

```rust
/// Converts an interval bound to a [`Precision`] value. NULL bounds (which
 /// represent "unbounded" in the [`Interval`] type) map to [`Precision::Absent`].
 fn interval_bound_to_precision(
     bound: ScalarValue,
     is_exact: bool,
 ) -> Precision<ScalarValue> {
     if bound.is_null() {
         Precision::Absent
     } else if is_exact {
         Precision::Exact(bound)
     } else {
         Precision::Inexact(bound)
     }
 }
```

**Review by neilconway — APPROVED** [review]
Welcome @fwojciec! Thank you for the detailed bug report and proposed fix. Both the analysis and the proposed fix seem reasonable to me.

I wonder whether we should try to proactively prevent `Precision::Exact(ScalarValue::Null)` (same for Inexact) from being used for min/max/sum values in ColumnStatistics -- it doesn't seem to make much sense.

File: datafusion/physical-plan/src/filter.rs (hunk 1 above)
Comment (fwojciec) [reply datafusion/physical-plan/src/filter.rs]: Done (apologies, should have just "Committed suggestion") - the result is the same though.

File: datafusion/physical-plan/src/filter.rs (hunk 2 above)
Comment (fwojciec) [reply datafusion/physical-plan/src/filter.rs]: Done.

**Comment by fwojciec** [comment]
> Welcome @fwojciec! Thank you for the detailed bug report and proposed fix. Both the analysis and the proposed fix seem reasonable to me.

Appreciate the super-fast review @neilconway!

> I wonder whether we should try to proactively prevent `Precision::Exact(ScalarValue::Null)` (same for Inexact) from being used for min/max/sum values in ColumnStatistics -- it doesn't seem to make much sense.

Makes sense to me, would prevent this entire class of bugs. A separate PR (looks like that would be a slightly bigger change, though mostly mechanical)?

**Comment by neilconway** [comment]
> Makes sense to me, would prevent this entire class of bugs. A separate PR (looks like that would be a slightly bigger change, though mostly mechanical)?

Yep, deferring it to a separate PR would be better I'd say. I'm not a committer though, so maybe wait for someone else to weigh in before you spend time on it :)

**Comment by jonathanc-n** [comment]
> > Makes sense to me, would prevent this entire class of bugs. A separate PR (looks like that would be a slightly bigger change, though mostly mechanical)?
> 
> Yep, deferring it to a separate PR would be better I'd say. I'm not a committer though, so maybe wait for someone else to weigh in before you spend time on it :)

I think this makes sense

**Comment by fwojciec** [comment]
Hi @alamb, I pushed a small fix to address a CI failure (broken rustdoc link to `Interval` in filter.rs). Could you approve the workflow run when you get a chance? Thanks!

**Comment by alamb** [comment]
Thansk @fwojciec and @gabotechs
