### PR TITLE
fix: Return Int for Date - Date instead of duration

### LINKED ISSUE #19528: Date - Date returns a type inconsistent with other databases
### Describe the bug

As uncovered in https://github.com/apache/datafusion/pull/19460, `SELECT '2001-09-28'::date - '2001-08-12'::date` returns a Duration type whereas other systems return an int:

    https://www.postgresql.org/docs/current/functions-datetime.html
    https://duckdb.org/docs/stable/sql/data_types/interval#arithmetic-with-timestamps-dates-and-intervals
    https://dev.mysql.com/doc/refman/8.4/en/expressions.html#temporal-intervals

Datafusion should adhere to common conventions for operation types unless there is a really good reason to deviate.

IOW, this should work:

```
query T
SELECT arrow_typeof('2001-09-28'::date - '2001-08-12'::date)
----
Int64
```

### To Reproduce

See sql above

### Expected behavior

date - date should return an int of the days difference between the two dates, not a duration.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kumarUjjawal**
## Which issue does this PR close?

- Closes #19528.

## Rationale for this change

The Date - Date currently returns duration which is not consistent with other databases. 

## What changes are included in this PR?

- Made changes to so it return Int instead of the days duration
- Added slt test

## Are these changes tested?

Yes

### CODE REVIEW

**Comment by Omega359** [comment]
It seems to me that mapping the binary op's duration result to an int64 taking into account the timeunit and mod to get the day would be cleaner?

**Comment by kumarUjjawal** [comment]
> It seems to me that mapping the binary op's duration result to an int64 taking into account the timeunit and mod to get the day would be cleaner?

Thanks of the feedback.

File: datafusion/expr-common/src/type_coercion/binary.rs [hunk 1]
```diff
@@ -261,6 +261,17 @@ impl<'a> BinaryTypeCoercer<'a> {
             })
         }
         Plus | Minus | Multiply | Divide | Modulo  =>  {
```
Comment (Jefffrey) [inline datafusion/expr-common/src/type_coercion/binary.rs:270]:
```suggestion
        Minus if is_date_minus_date(lhs, rhs) => {
            return Ok(Signature {
                lhs: lhs.clone(),
                rhs: rhs.clone(),
                ret: Int64,
            });
        }
        Plus | Minus | Multiply | Divide | Modulo  =>  {
```

Can move it into a match arm

File: datafusion/sqllogictest/test_files/datetime/dates.slt [hunk 2]
```diff
@@ -94,12 +94,20 @@ caused by
...
 SELECT DATE '2023-04-09' - DATE '2023-04-02';
 ----
-7 days 0 hours 0 mins 0 secs
+7
+
+# Verify Date - Date returns Int64 type
+query T
+SELECT arrow_typeof(DATE '2023-04-09' - DATE '2023-04-02');
+----
+Int64
```
Comment (Jefffrey) [inline datafusion/sqllogictest/test_files/datetime/dates.slt]: These tests seem duplicated with what we already have in `arith_date_date.slt`?

File: datafusion/physical-expr/src/expressions/binary.rs [hunk 3]
```diff
@@ -251,6 +340,11 @@ impl PhysicalExpr for BinaryExpr {
         match self.op {
             Operator::Plus if self.fail_on_overflow => return apply(&lhs, &rhs, add),
             Operator::Plus => return apply(&lhs, &rhs, add_wrapping),
+            // Special case: Date - Date returns Int64 (days difference)
+            // This aligns with PostgreSQL, DuckDB, and MySQL behavior
+            Operator::Minus if is_date_minus_date(&left_data_type, &right_data_type) => {
```
Comment (Jefffrey) [inline datafusion/physical-expr/src/expressions/binary.rs:345]: Do we need to take into account overflow config like below?

File: datafusion/sqllogictest/test_files/datetime/dates.slt (hunk 2 above)
Comment (Omega359) [reply datafusion/sqllogictest/test_files/datetime/dates.slt]: they are, though the arith_* files came in after these tests existed and I didn't noticed until after that PR had merged.

File: datafusion/physical-expr/src/expressions/binary.rs (hunk 3 above)
Comment (kumarUjjawal) [reply datafusion/physical-expr/src/expressions/binary.rs:345]: Date subtraction  will always fit in Int64 without overflow risk so comment might be suffiecient.  I can add a check for that if your prefer.

File: datafusion/sqllogictest/test_files/datetime/dates.slt (hunk 2 above)
Comment (kumarUjjawal) [reply datafusion/sqllogictest/test_files/datetime/dates.slt]: I will remove the duplicate test.

File: datafusion/expr-common/src/type_coercion/binary.rs [hunk 4]
```diff
@@ -260,7 +260,25 @@ impl<'a> BinaryTypeCoercer<'a> {
...
+                lhs: lhs.clone(),
+                rhs: rhs.clone(),
+                ret: Int64,
+            });
+        }
         Plus | Minus | Multiply | Divide | Modulo  =>  {
+            // Special case: Date - Date should return Int64 (days difference)
+            // This aligns with PostgreSQL, DuckDB, and MySQL behavior
+            // See: https://www.postgresql.org/docs/current/functions-datetime.html
+            if matches!(self.op, Minus) && is_date_minus_date(lhs, rhs) {
```
Comment (Jefffrey) [inline datafusion/expr-common/src/type_coercion/binary.rs]: This needs to be removed if the above suggestion was applied

Comment (kumarUjjawal) [reply datafusion/expr-common/src/type_coercion/binary.rs]: Yes, I forgot

**Comment by alamb** [comment]
Thanks @Jefffrey and @kumarUjjawal
