### PR TITLE
fix: disallow specify both order_by and within_group

### LINKED ISSUE #16596: It should be disallowed to specify both order_by and within_group.
It should be disallowed to specify both order_by and within_group. 

_Originally posted by @findepi in https://github.com/apache/datafusion/pull/16538#discussion_r2169196626_

### PR DESCRIPTION
**Pull request by watchingthewheelsgo**
## Which issue does this PR close?

- Closes #16596.

## What changes are included in this PR?

raise exception when order_by and within_group are specified

## Are these changes tested?

UT

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by alamb** [comment]
Thank you @watchingthewheelsgo  🙏  -- I kicked off the tests!

File: datafusion/sql/src/expr/function.rs [hunk 1]
```diff
@@ -227,6 +227,10 @@ impl<S: ContextProvider> SqlToRel<'_, S> {
                 OVER is for window functions, whereas WITHIN GROUP is for ordered set aggregate functions");
         }
 
+        if !order_by.is_empty() && !within_group.is_empty() {
+            return plan_err!("ORDER BY and WITHIN GROUP clauses cannot be used together in the same aggregate function. ");
```
Comment (findepi) [inline datafusion/sql/src/expr/function.rs:231]:
```suggestion
            return plan_err!("ORDER BY and WITHIN GROUP clauses cannot be used together in the same aggregate function");
```

**Comment by alamb** [comment]
Thank you @watchingthewheelsgo and @findepi

File: datafusion/sql/src/expr/function.rs (hunk 1 above)
Comment (alamb) [reply datafusion/sql/src/expr/function.rs:231]: Sorry -- I missed this suggestion before merging. @watchingthewheelsgo any chance you are willing to make a small follow on PR?

Comment (watchingthewheelsgo) [reply datafusion/sql/src/expr/function.rs:231]: > Sorry -- I missed this suggestion before merging. @watchingthewheelsgo any chance you are willing to make a small follow on PR?

@alamb sure, here is the one https://github.com/apache/datafusion/pull/16613. sorry I didn't follow the suggested changes in time.

Comment (alamb) [reply datafusion/sql/src/expr/function.rs:231]: > > Sorry -- I missed this suggestion before merging. @watchingthewheelsgo any chance you are willing to make a small follow on PR?
> 
> @alamb sure, here is the one #16613. sorry I didn't follow the suggested changes in time.

No worries at all -- it was my mistake to merge the PR without giving you time to respond. Thank you for your patience
