### PR TITLE
fix: Fix documentation for `null_string` to `array_to_string` + `string_to_array`

### LINKED ISSUE #13384: docs: array_to_string missing 3rd 'null_string' argument in documentation
### Describe the bug

The array_to_string function has an optional third argument `null_string` that if provided will replace null. This is tested in the slt tests:
```
# array_to_string scalar function with nulls #2
query TTT
select array_to_string(make_array('h', NULL, NULL, NULL, 'o'), ',', '-'), array_to_string(make_array(NULL, 2, NULL, 4, 5), '-', 'nil'), array_to_string(make_array(1.0, NULL, 3.0), '|', '0');
----
h,-,-,-,o nil-2-nil-4-5 1|0|3
```

### To Reproduce

_No response_

### Expected behavior

Docs should reflect the actual functionality.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jonathanc-n**
## Which issue does this PR close?

Closes #13384.

## What changes are included in this PR?
Added and fixed docs for array_to_string and string_to_array

### CODE REVIEW

File: datafusion/functions-nested/src/string.rs [hunk 1]
```diff
@@ -274,8 +278,10 @@ impl ScalarUDFImpl for StringToArray {
     }
 }
 
+static DOCUMENTATION_STRING_TO_ARRAY: OnceLock<Documentation> = OnceLock::new();
+
 fn get_string_to_array_doc() -> &'static Documentation {
-    DOCUMENTATION.get_or_init(|| {
+    DOCUMENTATION_STRING_TO_ARRAY.get_or_init(|| {
```
Comment (alamb) [inline datafusion/functions-nested/src/string.rs:284]: nice find 👍

**Review by alamb — APPROVED** [review]
Thank you @jonathanc-n

**Review by jayzhan211 — APPROVED** [review]

**Comment by jayzhan211** [comment]
Nice, thanks @jonathanc-n @alamb
