### PR TITLE
fix: no longer support the `substring` function

### LINKED ISSUE #10240: Regression: no longer support the `substring` function
### Describe the bug

Found while working on #10013.

An error was reported stating, `This feature is not implemented: Unsupported ast node in sqltorel: Substring.`
It worked prior to #10137, but it stopped working after upgrading sqlparser to 0.45.0.

Related to https://github.com/sqlparser-rs/sqlparser-rs/pull/1173

### To Reproduce

```sh
DataFusion CLI v37.1.0
> select substring('xxxx', 1, 2);
This feature is not implemented: Unsupported ast node in sqltorel: Substring { expr: Value(SingleQuotedString("xxxx")), substring_from: Some(Value(Number("1", false))), substring_for: Some(Value(Number("2", false))), special: true }
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jonahgao**
## Which issue does this PR close?

Closes #10240.

## Rationale for this change
Before version 0.45.0 of sqlparser, the `special` flag for both `substring('xxxx', 1, 2)` and `substring('xxxx' from 1 for 2)` was false. 

After https://github.com/sqlparser-rs/sqlparser-rs/pull/1173, the `special` flag for `substring('xxxx', 1, 2)` becomes true.

We need to support both formats  as before, so there's no need to check the `special` flag.

The 'from' and 'for' parameters don't support string types because they should be treated as regular expressions. Currently, substring is just an alias of`substr`. This PR adds tests to verify this.

Reference document: https://www.postgresql.org/docs/current/functions-string.html

## What changes are included in this PR?
Re-enable `substring('xxxx', 1, 2)`.

## Are these changes tested?
Yes
## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/sql/src/expr/mod.rs [hunk 1]
```diff
@@ -467,7 +467,7 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
                 expr,
                 substring_from,
                 substring_for,
-                special: false,
+                ..
```
Comment (Jefffrey) [inline datafusion/sql/src/expr/mod.rs:470]:
```suggestion
                special: _
```

Maybe this so we can be informed of any new fields in Substring in the future?

File: datafusion/sql/src/expr/mod.rs [hunk 2]
```diff
@@ -476,13 +476,6 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
                 planner_context,
             ),
 
-            #[cfg(not(feature = "unicode_expressions"))]
-            SQLExpr::Substring { .. } => {
-                internal_err!(
-                    "statement substring requires compilation with feature flag: unicode_expressions."
-                )
-            }
```
Comment (Jefffrey) [inline datafusion/sql/src/expr/mod.rs:484]: I think this might still be needed?

File: datafusion/sqllogictest/test_files/expr.slt [hunk 3]
```diff
@@ -1871,6 +1871,17 @@ SELECT digest('','blake3');
...
+
+query T
+SELECT substring('alphabet', 1)
+----
+alphabet
+
+query T
+SELECT substring('alphabet', 3, 2)
+----
+ph
```
Comment (Jefffrey) [inline datafusion/sqllogictest/test_files/expr.slt:1883]: :+1:

File: datafusion/sql/src/expr/mod.rs (hunk 2 above)
Comment (jonahgao) [reply datafusion/sql/src/expr/mod.rs]: Indeed, I considered it as matching special to false, without carefully checking.
Fixed. Thank you @Jefffrey !

File: datafusion/sql/src/expr/mod.rs (hunk 1 above)
Comment (jonahgao) [reply datafusion/sql/src/expr/mod.rs]: I think this is a very good practice, thank you @Jefffrey . Applied in [commit](https://github.com/apache/datafusion/pull/10242/commits/0d0fbe891cae0eac54407c1aa6930902b68a6575).

**Review by Jefffrey — APPROVED** [review]
Looks good, nice catch :+1:

**Comment by alamb** [comment]
Looks good to me @jonahgao  -- thank you for the review @Jefffrey
