### PR TITLE
fix: support scalar function nested in get_field in Unparser

### LINKED ISSUE #16607: SQL Unparser Can Not Process Struct Of Struct Access When Generating Sql
### Describe the bug

When attempting to invoke `plan_to_sql` on a plan which includes accessing a field inside of a nested structure, the invocation fails with the following error:

```
Error: Custom { kind: Other, error: Internal("get_field expects first argument to be column, but received: ScalarFunction(ScalarFunction { func: ScalarUDF { inner: GetFieldFunc { signature: Signature { type_signature: Any(2), volatility: Immutable } } }, args: [Column(Column { relation: Some(Bare { table: \"query\" }), name: \"metadata\" }), Literal(Utf8(\"product\"), None)] })") }
```

### To Reproduce

Given `query.json` as:

```json
{"metadata": {"product": {"name": "Product Name"}}}
```

The following test case reproduces the error:

```rust
use std::io::Error;
use datafusion::prelude::{NdJsonReadOptions, SessionContext};
use datafusion::sql::unparser::plan_to_sql;

#[tokio::test]
async fn test_plan_to_sql() -> Result<(), Error> {
    let ctx = SessionContext::new();
    ctx.register_json("query", "tests/fixtures/query.json", NdJsonReadOptions::default()).await?;

    let df = ctx.sql(r#"SELECT query."message" FROM query WHERE metadata['product']['name']  = 'Product Name'"#).await?;
    let sql_ast = plan_to_sql(df.logical_plan())?;

    assert_eq!(r#"SELECT "query".message FROM "query" WHERE ("query"."metadata".product.name = 'Product Name')"#, sql_ast.to_string());

    Ok(())
}
```

### Expected behavior

The expectation would be that the `plan_to_sql` call succeeds and generates a SQL expression similar to:

```sql
SELECT "query".message FROM "query" WHERE ("query"."metadata".product.name = 'Product Name')
```

### Additional context

While I'm not too familiar with the code base, my best guess is that the problem seems to be in [`get_field_to_sql`](https://github.com/apache/datafusion/blob/0143b20de3f9e25ab8d87ef4b96b78c28e462bee/datafusion/sql/src/unparser/expr.rs#L619). If I'm understanding the logic correctly, the implementation assumes a column / field pair.

### PR DESCRIPTION
**Pull request by chenkovsky**
## Which issue does this PR close?

- Closes #16607.

## Rationale for this change

unparser for get_field will check the first parameter. currently it only allows column.

## What changes are included in this PR?

support scalar function in get_field

## Are these changes tested?

UT

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/sql/src/unparser/expr.rs [hunk 1]
```diff
@@ -639,9 +630,27 @@ impl Unparser<'_> {
             )
             }
         };
-        id.push(field);
 
-        Ok(ast::Expr::CompoundIdentifier(id))
+        match &args[0] {
+            Expr::Column(col) => {
```
Comment (alamb) [inline datafusion/sql/src/unparser/expr.rs:635]: I wonder if we could just convert this like any other normal expression 🤔

File: datafusion/sql/tests/cases/plan_to_sql.rs [hunk 2]
```diff
@@ -2596,3 +2600,27 @@ fn test_not_ilike_filter_with_escape() {
         @"SELECT person.first_name FROM person WHERE person.first_name NOT ILIKE 'A!_%' ESCAPE '!'"
     );
 }
+
+#[test]
+fn test_struct_expr() {
```
Comment (alamb) [inline datafusion/sql/tests/cases/plan_to_sql.rs:2605]: Is it possible to test using the non struct syntax too?

Like `SELECT ["ProductName"]["product"]`?

**Review by alamb — COMMENTED** [review]
Thanks @chenkovsky  -- this looks good to me but I am not super familar with this code

@goldmedal  or @phillipleblanc  I wonder if either of you have some time (or can suggest someone else) to review this code?

**Comment by goldmedal** [comment]
> Thanks @chenkovsky -- this looks good to me but I am not super familar with this code
> 
> @goldmedal or @phillipleblanc I wonder if either of you have some time (or can suggest someone else) to review this code?

I'll review this PR tonight.

File: datafusion/sql/tests/cases/plan_to_sql.rs [hunk 3]
```diff
@@ -2596,3 +2600,36 @@ fn test_not_ilike_filter_with_escape() {
...
+    let statement = generate_round_trip_statement(
+        GenericDialect {},
+        r#"WITH test AS (SELECT STRUCT(STRUCT(STRUCT('Product Name' as name)) as product) AS metadata) SELECT metadata.product FROM test WHERE metadata.product.name  = 'Product Name'"#,
```
Comment (goldmedal) [inline datafusion/sql/tests/cases/plan_to_sql.rs]: I think this test case is wrong. If I try to select `metadata.product.name` like:
```sql
WITH
    test AS (
        SELECT
            STRUCT (
                STRUCT (STRUCT ('Product Name' as name)) as product
            ) AS metadata
    )
SELECT
    metadata.product.name
FROM
    test
```
We will get the following error message:
```
called `Result::unwrap()` on an `Err` value: Plan("Field name not found in struct")
```
Because you create an unnamed struct as `product`:
```
STRUCT (STRUCT ('Product Name' as name)) as product
```
It creates the structure like `product.c0.name` here, actually.
I guess what you really want is:
```suggestion
        r#"WITH test AS (SELECT STRUCT(STRUCT('Product Name' as name) as product) AS metadata) SELECT metadata.product FROM test WHERE metadata.product.name = 'Product Name'"#,
```
It will create a column called `metadata` which is a 2-dim struct `product.name`.

**Review by goldmedal — COMMENTED** [review]
Thanks @chenkovsky for working on this. I have some comments for this PR.

I think we should also consider that the length of the access chain is greater than 3. 
For example: 
```
WITH
    test AS (
        SELECT
            STRUCT (
                STRUCT (
                    STRUCT ('Product Name' as name) as product
                ) AS metadata
            ) AS c1
    )
SELECT
    c1.metadata.product.name
FROM
    test
```
I found the result for this case is wrong.
```
SELECT test.c1."metadata" FROM (SELECT {"metadata": {product: {"name": 'Product Name'}}} AS c1) AS test
```
It should be
```
SELECT test.c1."metadata".product.name FROM (SELECT {"metadata": {product: {"name": 'Product Name'}}} AS c1) AS test
```

File: datafusion/sql/tests/cases/plan_to_sql.rs (hunk 3 above)
Comment (chenkovsky) [reply datafusion/sql/tests/cases/plan_to_sql.rs]: @goldmedal could you please review it again

File: datafusion/sql/src/unparser/expr.rs [hunk 4]
```diff
@@ -617,31 +617,55 @@ impl Unparser<'_> {
     }
 
     fn get_field_to_sql(&self, args: &[Expr]) -> Result<ast::Expr> {
-        if args.len() != 2 {
-            return internal_err!("get_field must have exactly 2 arguments");
-        }
```
Comment (goldmedal) [inline datafusion/sql/src/unparser/expr.rs]: I think we don't need to remove the condition. We still need to ensure the length of arguments for `get_field` is 2.

File: datafusion/sql/src/unparser/expr.rs [hunk 5]
```diff
@@ -617,31 +617,55 @@ impl Unparser<'_> {
...
+                                &arg
+                            )
+                        }
+                    };
+                    access_chain.push(ast::AccessExpr::Dot(ast::Expr::Identifier(field)));
+                }
+                Ok(ast::Expr::CompoundFieldAccess {
+                    root: Box::new(root),
+                    access_chain,
+                })
```
Comment (goldmedal) [inline datafusion/sql/src/unparser/expr.rs]:
```suggestion
                let field = match &args[1] {
                    Expr::Literal(lit, _) => self.new_ident_quoted_if_needs(lit.to_string()),
                    _ => {
                        return internal_err!(
                            "get_field expects arguments except the first one to be a string, but received: {:?}",
                            &args[1]
                        )
                    }
                };
                Ok(ast::Expr::CompoundFieldAccess {
                    root: Box::new(root),
                    access_chain:  vec![ast::AccessExpr::Dot(ast::Expr::Identifier(field))],
                })
```
We don't need this for-loop, actually. The arguments of `get_field` are always `column_name` and `field_name`.

File: datafusion/sql/src/unparser/expr.rs [hunk 6]
```diff
@@ -617,31 +617,55 @@ impl Unparser<'_> {
...
+                        Expr::Literal(lit, _) => self.new_ident_quoted_if_needs(lit.to_string()),
+                        _ => {
+                            return internal_err!(
+                                "get_field expects arguments except the first one to be a string, but received: {:?}",
+                                &arg
+                            )
+                        }
+                    };
+                    id.push(field);
+                }
```
Comment (goldmedal) [inline datafusion/sql/src/unparser/expr.rs]: This for-loop isn't necessary, either. We can simplify it as above.

**Review by goldmedal — COMMENTED** [review]
I have confirmed the tests make sense and are correct. I only have some suggestions to simplify the code.

File: datafusion/sql/src/unparser/expr.rs (hunk 6 above)
Comment (chenkovsky) [reply datafusion/sql/src/unparser/expr.rs]: updated

**Review by goldmedal — APPROVED** [review]
Thanks @chenkovsky 👍

**Comment by alamb** [comment]
Thanks @chenkovsky  and @goldmedal
