### PR TITLE
Check window functions by str for with_column

### LINKED ISSUE #12425: Calling `with_column` twice generates an error when the second call uses a `window` function
### Describe the bug

Calling `with_column` twice generates an error when the second column is a window expression.

```
df
.with_column("foo", <normal_expr>)
.with_column("bar, <window_expr>)
```

Because `"foo"` does not have a qualifier, the second call to `with_column` ends up aliasing it as well.

https://github.com/apache/datafusion/blob/3ece7a736193a87941a00eb35f3001df282fd075/datafusion/core/src/dataframe/mod.rs#L1466-L1479

```console
Error: Plan("Projections require unique expression names but the expression \"s AS r\" at position 3 and \"row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING AS r\" at position 4 have the same name. Consider aliasing (\"AS\") one of them.")
```

### To Reproduce

Update `test_window_function_with_column` to first call `with_column` with any expression.

For example:

```rust

    // Test issue: https://github.com/apache/datafusion/issues/11982
    // Window function was creating unwanted projection when using with_column() method.
    #[tokio::test]
    async fn test_window_function_with_column() -> Result<()> {
        let df = test_table().await?.select_columns(&["c1", "c2", "c3"])?;
        let ctx = SessionContext::new();
        let df_impl = DataFrame::new(ctx.state(), df.plan.clone());
        let func = row_number().alias("row_num");

        // This first `with_column` results in a column without a `qualifier` 
        let df_impl = df_impl.with_column("s", col("c2") + col("c3"))?;

        // This second `with_column` then assigns `"r"` alias to the above column and the window function
        // Should create an additional column with alias 'r' that has window func results
        let df = df_impl.with_column("r", func)?.limit(0, Some(2))?;
        assert_eq!(4, df.schema().fields().len());

        let df_results = df.clone().collect().await?;
        assert_batches_sorted_eq!(
            [
                "+----+----+-----+---+",
                "| c1 | c2 | c3  | r |",
                "+----+----+-----+---+",
                "| c  | 2  | 1   | 1 |",
                "| d  | 5  | -40 | 2 |",
                "+----+----+-----+---+",
            ],
            &df_results
        );

        Ok(())
    }
```

### Expected behavior

I would expect the second call to succeed and the final dataframe to have columns `c1, c2, c3, s, r`

### Additional context

#12000 introduced that conditional.

### PR DESCRIPTION
**Pull request by timsaucer**
## Which issue does this PR close?

Closes #12425 

## Rationale for this change

The current implementation regresses when you have multiple columns without a qualifier and the new with_column is a window function. This is because the loop is checking for any field to not have a qualifier.

## What changes are included in this PR?

Check the display name of the expr in the schema matches that of the window function that was added.

## Are these changes tested?

Updated unit test

## Are there any user-facing changes?

None

### CODE REVIEW

**Review by alamb — APPROVED** [review]
The code ane test makes sense to me. Thank you @timsaucer

File: datafusion/core/src/dataframe/mod.rs [hunk 1]
```diff
@@ -2984,19 +2990,25 @@ mod tests {
         let df_impl = DataFrame::new(ctx.state(), df.plan.clone());
         let func = row_number().alias("row_num");
 
+        // This first `with_column` results in a column without a `qualifier`
+        let df_impl = df_impl.with_column("s", col("c2") + col("c3"))?;
+
+        // This second `with_column` then assigns `"r"` alias to the above column and the window function
```
Comment (Michael-J-Ward) [inline datafusion/core/src/dataframe/mod.rs:2996]:
```suggestion
        // This second `with_column` should only alias `func` as `"r"`
```

Update the comment from explaining the bug to explaining the correct the behavior.

The comment for this test case already links to GH issue, so maybe add a link to this bug as well.

**Review by Michael-J-Ward — APPROVED** [review]

File: datafusion/core/src/dataframe/mod.rs [hunk 2]
```diff
@@ -1452,28 +1452,34 @@ impl DataFrame {
...
                     col_exists = true;
-                    new_column.clone()
-                } else if window_func && qualifier.is_none() {
-                    col(Column::from((qualifier, field))).alias(name)
+                    Some(new_column.clone())
                 } else {
-                    col(Column::from((qualifier, field)))
+                    let e = col(Column::from((qualifier, field)));
+                    let match_window_fn = window_fn_str
+                        .as_ref()
```
[the remark this answers is not in the document]
Comment (timsaucer) [reply datafusion/core/src/dataframe/mod.rs]: That's a nice suggestion. Thank you. Pushed with the included change.

File: datafusion/core/src/dataframe/mod.rs (hunk 1 above)
Comment (timsaucer) [reply datafusion/core/src/dataframe/mod.rs]: Added

**Review by comphead — APPROVED** [review]
lgtm thanks @timsaucer
