### PR TITLE
Fix `null` input  in `map_keys/values`

### LINKED ISSUE #14400: Return `null` for `null` maps in `map_keys` and `map_values`
### Describe the bug

`map_keys` and `map_values` should return `null` instead of empty array for `null` inputs

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cht42**
## Which issue does this PR close?

Closes #14400.

### CODE REVIEW

File: datafusion/functions-nested/src/map_keys.rs [hunk 1]
```diff
@@ -126,9 +126,36 @@ fn map_keys_inner(args: &[ArrayRef]) -> Result<ArrayRef> {
...
+        Arc::new(Field::new_list_field(map_array.key_type().clone(), true)),
         map_array.offsets().clone(),
         Arc::clone(map_array.keys()),
-        None,
+        map_array.nulls().cloned(),
     )))
 }
+
+#[cfg(test)]
+mod test {
```
Comment (cht42) [inline datafusion/functions-nested/src/map_keys.rs:137]: cannot use slt tests as we can't cast Map to nulls 
see https://github.com/apache/arrow-rs/blob/a6648fe53bc386eb8f491e68dca3d2bdee6c549c/arrow-schema/src/datatype_parse.rs#L683

Comment (alamb) [reply datafusion/functions-nested/src/map_keys.rs:137]: I think you can test it using slt with this trick (create a column with non null value and then insert a `NULL` into it)

```sql
DataFusion CLI v44.0.0
> create table foo as values (MAP {'foo': 'bar'});
0 row(s) fetched.
Elapsed 0.037 seconds.

> insert into foo values (NULL);
+-------+
| count |
+-------+
| 1     |
+-------+
1 row(s) fetched.
Elapsed 0.016 seconds.

> select * from foo;
+------------+
| column1    |
+------------+
| {foo: bar} |
| NULL       |
+------------+
2 row(s) fetched.
Elapsed 0.004 seconds.

> select column1, arrow_typeof(column1) from foo;
+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| column1    | arrow_typeof(foo.column1)                                                                                                                                                                                                                                                                                                                            |
+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| {foo: bar} | Map(Field { name: "entries", data_type: Struct([Field { name: "key", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "value", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, false) |
| NULL       | Map(Field { name: "entries", data_type: Struct([Field { name: "key", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "value", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, false) |
+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
2 row(s) fetched.
Elapsed 0.006 seconds.
```

**Review by alamb — COMMENTED** [review]
Thank you very much @cht42  -- this makes sense to me 🙏 

I think it would be really nice to update the tests to use `slt` (I left a suggestion on how to do so ) but not strictly required.

**Review by alamb — APPROVED** [review]

File: datafusion/functions-nested/src/map_keys.rs (hunk 1 above)
Comment (cht42) [reply datafusion/functions-nested/src/map_keys.rs:137]: sweet, will update

**Review by xudong963 — APPROVED** [review]
Thanks @cht42
