### PR TITLE
fix(SubqueryAlias): use maybe_project_redundant_column

### LINKED ISSUE #17405: `change_redundant_column` lossy approach breaks logical optimizer and physical planner
### Describe the bug

Related to #15439 (fixed in #15438) and #16063 (fixed in #16064).

While executing some queries with a similar pattern to the ones described the related issue, I encountered several situations where the physical planner would get confused when grouping by columns originating from multiple joins (`Input field name {} does not match with the projection expression {}`). All pathologic columns didn't pass the check because of a `:1` (or similar) to their column name. 

The suffix is appended from: 

https://github.com/apache/datafusion/blob/d83a290d1d534f7db9849b11c39d2b0a289a62e4/datafusion/expr/src/logical_plan/builder.rs#L1528 

which gets called when creating a new [`SubqueryAlias`](https://github.com/apache/datafusion/blob/d83a290d1d534f7db9849b11c39d2b0a289a62e4/datafusion/expr/src/logical_plan/plan.rs#L2226), which is used in these queries to qualify the `left` and `right` part of the join so the query can reference the columns indepentely. The qualification happens by stripping the inner DFSchema of its current qualification and applying the new one (e.g. `TableReference::bar("left")`). During this re-qualification, columns with duplicate names are handled in a very hacky way by appending a `:{N}` where N is a unique number for that column. While this is not a problem for the first alias it can quickly become a problem when nesting join operation as the previous re-qualification gets discarded and all columns (from left and right) get mixed into the same pot, causing collisions. 

The issue lies in the fact that nesting multiple `SubqueryAlias`es together could lead to information loss, which after an optimization step could lead to fatal errors in the logical and physical planner.

The fix for #16064 applies only for projections but if instead of projecting we use the column references in any other way the issue repeats. We would either have to use the `maybe_fix_physical_column_name` function everywhere, which is inconvenient or fix this at a systemic level by keeping the qualification path when creating a `SubqueryAlias` so that no information is lost and dropping the `:{N}` suffix so that columns can continue to be identified by name.

### To Reproduce

I have a substrait minimal repro, which confuses the logical optimizer and errors like this:

```
Error: Context("Optimizer rule 'optimize_projections' failed", SchemaError(FieldNotFound { field: Column { relation: Some(Bare { table: "left" }), name: "count(Int64(1)):1" }, valid_fields: [Column { relation: Some(Bare { table: "left" }), name: "id" }, Column { relation: Some(Bare { table: "left" }), name: "count(Int64(1))" }, Column { relation: Some(Bare { table: "right" }), name: "id" }] }, Some("")))
```

The unoptimized logical plan looks like this:

```
Aggregate: groupBy=[[left.count(Int64(1)):1 AS count_second]], aggr=[[]]
  Left Join: left.id = right.id
    SubqueryAlias: left
      Left Join: left.id = right.id
        SubqueryAlias: left
          Left Join: left.id = right.id
            SubqueryAlias: left
              Aggregate: groupBy=[[id]], aggr=[[count(Int64(1))]]
                Values: (Int64(1)), (Int64(2))
            SubqueryAlias: right
              Aggregate: groupBy=[[id, category]], aggr=[[]]
                Values: (Int64(1), Utf8("info")), (Int64(2), Utf8("low"))
        SubqueryAlias: right
          Aggregate: groupBy=[[id]], aggr=[[count(Int64(1))]]
            Values: (Int64(1)), (Int64(2))
    SubqueryAlias: right
      Aggregate: groupBy=[[id]], aggr=[[count(Int64(1))]]
        Values: (Int64(1)), (Int64(2))
```

The  raw substrait plan:

<details>
<summary>Hidden by default because it's huge.</summary>
<pre><code>
{
  "extensionUris": [{
    "extensionUriAnchor": 1,
    "uri": "/functions_aggregate_generic.yaml"
  }, {
    "extensionUriAnchor": 2,
    "uri": "/functions_comparison.yaml"
  }],
  "extensions": [{
    "extensionFunction": {
      "extensionUriReference": 1,
      "functionAnchor": 0,
      "name": "count:"
    }
  }, {
    "extensionFunction": {
      "extensionUriReference": 2,
      "functionAnchor": 1,
      "name": "equal:any_any"
    }
  }],
  "relations": [{
    "root": {
      "input": {
        "aggregate": {
          "common": {
          },
          "input": {
            "join": {
              "common": {
                "direct": {
                }
              },
              "left": {
                "join": {
                  "common": {
                    "direct": {
                    }
                  },
                  "left": {
                    "join": {
                      "common": {
                        "direct": {
                        }
                      },
                      "left": {
                        "aggregate": {
                          "common": {
                            "direct": {
                            }
                          },
                          "input": {
                            "read": {
                              "common": {
                                "direct": {
                                }
                              },
                              "baseSchema": {
                                "names": ["id"],
                                "struct": {
                                  "types": [{
                                    "i64": {
                                      "typeVariationReference": 0,
                                      "nullability": "NULLABILITY_NULLABLE"
                                    }
                                  }],
                                  "typeVariationReference": 0,
                                  "nullability": "NULLABILITY_REQUIRED"
                                }
                              },
                              "virtualTable": {
                                "values": [{
                                  "fields": [{
                                    "i64": "1",
                                    "nullable": true,
                                    "typeVariationReference": 0
                                  }]
                                }, {
                                  "fields": [{
                                    "i64": "2",
                                    "nullable": true,
                                    "typeVariationReference": 0
                                  }]
                                }]
                              }
                            }
                          },
                          "groupings": [{
                            "groupingExpressions": [{
                              "selection": {
                                "directReference": {
                                  "structField": {
                                    "field": 0
                                  }
                                },
                                "rootReference": {
                                }
                              }
                            }],
                            "expressionReferences": []
                          }],
                          "measures": [{
                            "measure": {
                              "functionReference": 0,
                              "args": [],
                              "sorts": [],
                              "phase": "AGGREGATION_PHASE_INITIAL_TO_RESULT",
                              "outputType": {
                                "i64": {
                                  "typeVariationReference": 0,
                                  "nullability": "NULLABILITY_REQUIRED"
                                }
                              },
                              "invocation": "AGGREGATION_INVOCATION_ALL",
                              "arguments": [],
                              "options": []
                            }
                          }],
                          "groupingExpressions": []
                        }
                      },
                      "right": {
                        "aggregate": {
                          "common": {
                            "direct": {
                            }
                          },
                          "input": {
                            "read": {
                              "common": {
                                "direct": {
                                }
                              },
                              "baseSchema": {
                                "names": ["id", "category"],
                                "struct": {
                                  "types": [{
                                    "i64": {
                                      "typeVariationReference": 0,
                                      "nullability": "NULLABILITY_NULLABLE"
                                    }
                                  }, {
                                    "string": {
                                      "typeVariationReference": 0,
                                      "nullability": "NULLABILITY_NULLABLE"
                                    }
                                  }],
                                  "typeVariationReference": 0,
                                  "nullability": "NULLABILITY_REQUIRED"
                                }
                              },
                              "virtualTable": {
                                "values": [{
                                  "fields": [{
                                    "i64": "1",
                                    "nullable": true,
                                    "typeVariationReference": 0
                                  }, {
                                    "string": "info",
                                    "nullable": true,
                                    "typeVariationReference": 0
                                  }]
                                }, {
                                  "fields": [{
                                    "i64": "2",
                                    "nullable": true,
                                    "typeVariationReference": 0
                                  }, {
                                    "string": "low",
                                    "nullable": true,
                                    "typeVariationReference": 0
                                  }]
                                }]
                              }
                            }
                          },
                          "groupings": [{
                            "groupingExpressions": [{
                              "selection": {
                                "directReference": {
                                  "structField": {
                                    "field": 0
                                  }
                                },
                                "rootReference": {
                                }
                              }
                            }, {
                              "selection": {
                                "directReference": {
                                  "structField": {
                                    "field": 1
                                  }
                                },
                                "rootReference": {
                                }
                              }
                            }],
                            "expressionReferences": []
                          }],
                          "measures": [],
                          "groupingExpressions": []
                        }
                      },
                      "expression": {
                        "scalarFunction": {
                          "functionReference": 1,
                          "args": [],
                          "outputType": {
                            "bool": {
                              "typeVariationReference": 0,
                              "nullability": "NULLABILITY_NULLABLE"
                            }
                          },
                          "arguments": [{
                            "value": {
                              "selection": {
                                "directReference": {
                                  "structField": {
                                    "field": 0
                                  }
                                },
                                "rootReference": {
                                }
                              }
                            }
                          }, {
                            "value": {
                              "selection": {
                                "directReference": {
                                  "structField": {
                                    "field": 2
                                  }
                                },
                                "rootReference": {
                                }
                              }
                            }
                          }],
                          "options": []
                        }
                      },
                      "type": "JOIN_TYPE_LEFT"
                    }
                  },
                  "right": {
                    "aggregate": {
                      "common": {
                        "direct": {
                        }
                      },
                      "input": {
                        "read": {
                          "common": {
                            "direct": {
                            }
                          },
                          "baseSchema": {
                            "names": ["id"],
                            "struct": {
                              "types": [{
                                "i64": {
                                  "typeVariationReference": 0,
                                  "nullability": "NULLABILITY_NULLABLE"
                                }
                              }],
                              "typeVariationReference": 0,
                              "nullability": "NULLABILITY_REQUIRED"
                            }
                          },
                          "virtualTable": {
                            "values": [{
                              "fields": [{
                                "i64": "1",
                                "nullable": true,
                                "typeVariationReference": 0
                              }]
                            }, {
                              "fields": [{
                                "i64": "2",
                                "nullable": true,
                                "typeVariationReference": 0
                              }]
                            }]
                          }
                        }
                      },
                      "groupings": [{
                        "groupingExpressions": [{
                          "selection": {
                            "directReference": {
                              "structField": {
                                "field": 0
                              }
                            },
                            "rootReference": {
                            }
                          }
                        }],
                        "expressionReferences": []
                      }],
                      "measures": [{
                        "measure": {
                          "functionReference": 0,
                          "args": [],
                          "sorts": [],
                          "phase": "AGGREGATION_PHASE_INITIAL_TO_RESULT",
                          "outputType": {
                            "i64": {
                              "typeVariationReference": 0,
                              "nullability": "NULLABILITY_REQUIRED"
                            }
                          },
                          "invocation": "AGGREGATION_INVOCATION_ALL",
                          "arguments": [],
                          "options": []
                        }
                      }],
                      "groupingExpressions": []
                    }
                  },
                  "expression": {
                    "scalarFunction": {
                      "functionReference": 1,
                      "args": [],
                      "outputType": {
                        "bool": {
                          "typeVariationReference": 0,
                          "nullability": "NULLABILITY_NULLABLE"
                        }
                      },
                      "arguments": [{
                        "value": {
                          "selection": {
                            "directReference": {
                              "structField": {
                                "field": 0
                              }
                            },
                            "rootReference": {
                            }
                          }
                        }
                      }, {
                        "value": {
                          "selection": {
                            "directReference": {
                              "structField": {
                                "field": 4
                              }
                            },
                            "rootReference": {
                            }
                          }
                        }
                      }],
                      "options": []
                    }
                  },
                  "type": "JOIN_TYPE_LEFT"
                }
              },
              "right": {
                "aggregate": {
                  "common": {
                    "direct": {
                    }
                  },
                  "input": {
                    "read": {
                      "common": {
                        "direct": {
                        }
                      },
                      "baseSchema": {
                        "names": ["id"],
                        "struct": {
                          "types": [{
                            "i64": {
                              "typeVariationReference": 0,
                              "nullability": "NULLABILITY_NULLABLE"
                            }
                          }],
                          "typeVariationReference": 0,
                          "nullability": "NULLABILITY_REQUIRED"
                        }
                      },
                      "virtualTable": {
                        "values": [{
                          "fields": [{
                            "i64": "1",
                            "nullable": true,
                            "typeVariationReference": 0
                          }]
                        }, {
                          "fields": [{
                            "i64": "2",
                            "nullable": true,
                            "typeVariationReference": 0
                          }]
                        }]
                      }
                    }
                  },
                  "groupings": [{
                    "groupingExpressions": [{
                      "selection": {
                        "directReference": {
                          "structField": {
                            "field": 0
                          }
                        },
                        "rootReference": {
                        }
                      }
                    }],
                    "expressionReferences": []
                  }],
                  "measures": [{
                    "measure": {
                      "functionReference": 0,
                      "args": [],
                      "sorts": [],
                      "phase": "AGGREGATION_PHASE_INITIAL_TO_RESULT",
                      "outputType": {
                        "i64": {
                          "typeVariationReference": 0,
                          "nullability": "NULLABILITY_REQUIRED"
                        }
                      },
                      "invocation": "AGGREGATION_INVOCATION_ALL",
                      "arguments": [],
                      "options": []
                    }
                  }],
                  "groupingExpressions": []
                }
              },
              "expression": {
                "scalarFunction": {
                  "functionReference": 1,
                  "args": [],
                  "outputType": {
                    "bool": {
                      "typeVariationReference": 0,
                      "nullability": "NULLABILITY_NULLABLE"
                    }
                  },
                  "arguments": [{
                    "value": {
                      "selection": {
                        "directReference": {
                          "structField": {
                            "field": 0
                          }
                        },
                        "rootReference": {
                        }
                      }
                    }
                  }, {
                    "value": {
                      "selection": {
                        "directReference": {
                          "structField": {
                            "field": 6
                          }
                        },
                        "rootReference": {
                        }
                      }
                    }
                  }],
                  "options": []
                }
              },
              "type": "JOIN_TYPE_LEFT"
            }
          },
          "groupings": [{
            "groupingExpressions": [{
              "selection": {
                "directReference": {
                  "structField": {
                    "field": 5
                  }
                },
                "rootReference": {
                }
              }
            }],
            "expressionReferences": []
          }],
          "measures": []
        }
      },
      "names": ["count_second"]
    }
  }],
  "expectedTypeUrls": [],
  "version": {
    "majorNumber": 0,
    "minorNumber": 52,
    "patchNumber": 0,
    "gitHash": ""
  }
}
</code></pre>
</details>

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by notfilippo**
## Which issue does this PR close?

- Closes #17405.

## Rationale for this change

When creating nested `SubqueryAlias` operations in complex joins, DataFusion was incorrectly handling column name conflicts by appending suffixes like `:1` to duplicate column names. This caused the physical planner to fail with "Input field name {} does not match with the projection expression {}" errors, as the optimizer couldn't properly match columns with these modified names.

The root cause was that the `SubqueryAlias` creation process was stripping qualification information and mixing columns from left and right sides of joins, leading to name collisions that were resolved by adding numeric suffixes. This approach lost important context needed for proper column resolution.

## What changes are included in this PR?

- Replaced the hacky column renaming approach in `SubqueryAlias` with a projection-based solution
- Added `maybe_project_redundant_column` function that creates explicit projections with aliases when needed, instead of modifying column names directly
- Removed the `maybe_fix_physical_column_name` function from the physical planner that was attempting to fix these naming issues downstream
- Updated `SubqueryAlias::try_new` to use the new projection approach, preserving qualification information properly
- Added test case demonstrating the fix for nested subquery alias scenarios

## Are these changes tested?

The changes include a new test case `subquery_alias_confusing_the_optimizer` that reproduces the original issue and verifies the fix works correctly. **Note: The newly added function `maybe_project_redundant_column` is missing comprehensive tests.**

## Are there any user-facing changes?

No user-facing changes. This is an internal fix that resolves query planning errors for complex nested join scenarios without changing the public API or query behavior.

### CODE REVIEW

**Comment by notfilippo** [comment]
Seems like [the CI flaked](https://github.com/apache/datafusion/actions/runs/17577986600/job/49927621476). Retrying...

**Comment by notfilippo** [comment]
cc @LiaCastaneda @berkaysynnada for the review. Thanks!

File: datafusion/expr/src/logical_plan/builder.rs [hunk 1]
```diff
@@ -2675,34 +2703,6 @@ mod tests {
         Ok(())
     }
 
-    #[test]
-    fn test_change_redundant_column() -> Result<()> {
```
Comment (LiaCastaneda) [inline datafusion/expr/src/logical_plan/builder.rs:2679]: maybe we should add a test for maybe_project_redundant_column?

File: datafusion/expr/src/logical_plan/plan.rs [hunk 2]
```diff
@@ -2223,13 +2223,15 @@ impl SubqueryAlias {
...
-            DFSchema::from_unqualified_fields(fields.into(), meta_data)?.into();
-        // Since schema is the same, other than qualifier, we can use existing
-        // functional dependencies:
+        let plan = maybe_project_redundant_column(plan)?;
+
+        let fields = plan.schema().fields().clone();
+        let meta_data = plan.schema().metadata().clone();
         let func_dependencies = plan.schema().functional_dependencies().clone();
+
+        let schema = DFSchema::from_unqualified_fields(fields, meta_data)?;
```
Comment (LiaCastaneda) [inline datafusion/expr/src/logical_plan/plan.rs:2278]: Here the join.schema() will have the` :<N>` still no? since we are returning the schema from the top level projection ( if it was inserted ). I know this solves the issue + makes the optimizer pass work but I don't understand how the optimizer works with this fix if we are still keeping the` :<N>` in the top level schema..

File: datafusion/substrait/tests/cases/consumer_integration.rs [hunk 3]
```diff
@@ -605,26 +605,30 @@ mod tests {
...
-            \n          Aggregate: groupBy=[[id]], aggr=[[count(Int64(1))]]\
-            \n            Values: (Int64(1)), (Int64(2))\
-            \n    SubqueryAlias: right\
-            \n      Aggregate: groupBy=[[id]], aggr=[[count(Int64(1))]]\
-            \n        Values: (Int64(1)), (Int64(2))"
+            @r#"
+        Projection: left.count(Int64(1)) AS count_first, left.category, left.count(Int64(1)):1 AS count_second, right.count(Int64(1)) AS count_third
+          Left Join: left.id = right.id
+            SubqueryAlias: left
+              Projection: left.id, left.count(Int64(1)), left.id:1, left.category, right.id AS id:2, right.count(Int64(1)) AS count(Int64(1)):1
```
Comment (LiaCastaneda) [inline datafusion/substrait/tests/cases/consumer_integration.rs:614]: I think this solves my doubt above, this is not requalifying the column name but its adding the `:<N> `as an alias, so I guess the optimizer sees the column names for resultion not the alias?

File: datafusion/expr/src/logical_plan/builder.rs [hunk 4]
```diff
@@ -1517,39 +1518,66 @@ impl ValuesFields {
...
+            match name {
+                Cow::Borrowed(_) => None,
+                Cow::Owned(alias) => Some(alias),
+            }
         })
-        .collect()
+        .collect::<Vec<_>>();
+
+    // Check if there is at least an alias
+    let is_projection_needed = aliases.iter().any(Option::is_some);
```
Comment (LiaCastaneda) [inline datafusion/expr/src/logical_plan/builder.rs]: very nit: maybe we can keep a flag inside the iteration above? so we avoid this one

File: datafusion/substrait/tests/cases/consumer_integration.rs (hunk 3 above)
Comment (LiaCastaneda) [inline datafusion/substrait/tests/cases/consumer_integration.rs:614]: Also, I was looking into the logical optimizer and there is [this](https://docs.rs/datafusion/latest/datafusion/optimizer/optimize_projections/index.html) rule to remove unnecessary projections, I don't think it will remove this one but maybe worth checking?

Comment (notfilippo) [reply datafusion/substrait/tests/cases/consumer_integration.rs:614]: I don't think this is an unnecessary projection as the aliases are needed for the correct semantic representation of `left.count(Int64(1)):1` in the final projection which actually refers to `right.count(Int64(1))` which gets aliased to `left`.

**Comment by alamb** [comment]
@NGA-TRAN  could you help review this PR?

**Comment by notfilippo** [comment]
Rebased to latest `main`

**Comment by NGA-TRAN** [comment]
I am actively reviewing this

File: datafusion/expr/src/logical_plan/builder.rs [hunk 5]
```diff
@@ -2787,4 +2765,33 @@ mod tests {
...
+        assert_eq!(
+            remove_redundant,
+            vec![
+                None,
+                Some("a:1".to_string()),
+                None,
+                Some("b:1".to_string()),
+                Some("a:2".to_string()),
+                Some("a:1:1".to_string()),
+            ]
```
Comment (NGA-TRAN) [inline datafusion/expr/src/logical_plan/builder.rs:2807]: `a, a, b, b, a, a:1` becomes `_, a:1, _, b:1, a:2, a:1:1`?  Does it mean  we keep the last of the same contiguous values and add 1, 2, 3, ... into the same but non contiguous?
Can you add this comment on top of the test?

File: datafusion/expr/src/logical_plan/builder.rs [hunk 6]
```diff
@@ -1517,37 +1518,42 @@ impl ValuesFields {
...
-// would rename them to -> col:1, col, col:1 causing a posteriror error when building the DFSchema.
-// that's why we need the `seen` set, so the fields are always unique.
-//
-pub fn change_redundant_column(fields: &Fields) -> Vec<Field> {
-    let mut name_map = HashMap::new();
-    let mut seen: HashSet<String> = HashSet::new();
+// Return a list of aliases so that if applied to `fields` it would result in a unique name for each
+// column, regardless of qualification. The returned vector length is equal to the number of fields
+// as input and will optionally contain the alias that needs to be assigned to the column in the
+// same position in order to maintain the uniqueness property.
```
Comment (NGA-TRAN) [inline datafusion/expr/src/logical_plan/builder.rs]: Can you add example in this comment? Something like you use in the test below:
`a, a, b, b, a, a:1` becomes `_, a:1, _, b:1, a:2, a:1:1`

It is also good to explain why you do this. Maybe another more general example for it?

File: datafusion/core/src/physical_planner.rs [hunk 7]
```diff
@@ -3562,4 +3448,44 @@ digraph {
 
         Ok(())
     }
+
+    #[tokio::test]
```
Comment (NGA-TRAN) [inline datafusion/core/src/physical_planner.rs:3469]: For other reviewers, this is a reproducer of the bug. I have run this test before the fix and it fails. Great job to reproduce this with logical and physical plan @notfilippo.

I suggest you add the below comment so we know what the bug is

File: datafusion/core/src/physical_planner.rs [hunk 8]
```diff
@@ -3562,4 +3448,44 @@ digraph {
...
+    async fn subquery_alias_confusing_the_optimizer() -> Result<()> {
```
Comment (NGA-TRAN) [inline datafusion/core/src/physical_planner.rs:3470]:
```suggestion
    // Reproducer for DataFusion issue #17405:
    // 
    // The following SQL is semantically invalid. Notably, the `SELECT left_table.a, right_table.a` clause is missing from the explicit logical plan:
   //  
   // SELECT a FROM (
   //       -- SELECT left_table.a, right_table.a
   //       FROM left_table
   //       FULL JOIN right_table ON left_table.a = right_table.a
    // ) AS alias
    // GROUP BY a;
    // 
    // As a result, the variables within `alias` subquery are not properly distinguished, which leads to a bug when converting the logical plan into a physical plan.
   // 
   // The proposed fix is to implicitly insert a ProjectionExec node to represent the missing SELECT clause.
   
    async fn subquery_alias_confusing_the_optimizer() -> Result<()> {
```

File: datafusion/substrait/tests/cases/consumer_integration.rs [hunk 9]
```diff
@@ -605,26 +605,30 @@ mod tests {
...
+                        SubqueryAlias: right
+                          Aggregate: groupBy=[[id, category]], aggr=[[]]
+                            Values: (Int64(1), Utf8("info")), (Int64(2), Utf8("low"))
+                  SubqueryAlias: right
+                    Aggregate: groupBy=[[id]], aggr=[[count(Int64(1))]]
+                      Values: (Int64(1)), (Int64(2))
+            SubqueryAlias: right
+              Aggregate: groupBy=[[id]], aggr=[[count(Int64(1))]]
+                Values: (Int64(1)), (Int64(2))
+        "#
```
Comment (NGA-TRAN) [inline datafusion/substrait/tests/cases/consumer_integration.rs:631]: This existing test also help verify the fix

**Comment by notfilippo** [comment]
Thanks for the insight @NGA-TRAN, I've added the comments and the code looks much better when contextualised.

File: datafusion/substrait/tests/cases/consumer_integration.rs (hunk 3 above)
Comment (alamb) [reply datafusion/substrait/tests/cases/consumer_integration.rs:614]: FWIW you can test stuff like this by writing .slt tests that have EXPLAIN in them and viewing the final output plan

**Review by alamb — APPROVED** [review]
Thanks for the code @notfilippo and for the reviews @LiaCastaneda and @NGA-TRAN  🙏

**Comment by hareshkh** [comment]
FYI - cherry-picking this onto branch-50 for 50.3.0 here - https://github.com/apache/datafusion/pull/18130 @notfilippo
