### PR TITLE
Clamp early aggregation emit to the sort boundary when using partial group ordering

### LINKED ISSUE #20445: [Bug] [v52 regression] Panic in `GroupOrderingPartial::remove_groups` when Partial aggregate with PartiallySorted hits memory pressure
### Describe the bug

Partial aggregation with `PartiallySorted` ordering panics when memory pressure triggers the `EmitEarly` OOM path:

```
assertion failed: *current_sort >= n
at aggregates/order/partial.rs:174
```

#19287 changed `Partial` aggregation to always use `OutOfMemoryMode::EmitEarly`:

```rust
(AggregateMode::Partial, _) => OutOfMemoryMode::EmitEarly,
```

The `EmitEarly` handler calls `emit(EmitTo::First(n))` with `n` based on batch size, ignoring the sort boundary tracked by `GroupOrderingPartial`. Previously, `emit_early_if_necessary()` had a guard:

```rust
&& matches!(self.group_ordering, GroupOrdering::None)
```

This guard was lost in the refactor.

## Trigger conditions

1. `Partial` aggregate with `PartiallySorted` ordering (e.g. `GROUP BY a, b` where input is sorted on `a`)
2. Memory pressure triggers `EmitEarly` before a sort key boundary is reached
3. Many groups accumulate with the same sort key value (so `current_sort` stays at 0 while `n` grows)

### To Reproduce

A unit test is included in the linked PR https://github.com/apache/datafusion/pull/20446

### Expected behavior

OOM, but not a assertion panic

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jackkleeman**
## Which issue does this PR close?

- Closes #20445.

## What changes are included in this PR?

Fix a panic on early emit with partial sort aggregations, by clamping our emit point to the sort boundary

## Are these changes tested?

Yes

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/physical-plan/src/aggregates/row_hash.rs [hunk 1]
```diff
@@ -1036,7 +1036,19 @@ impl GroupedHashAggregateStream {
                     self.group_values.len()
                 };
 
-                if let Some(batch) = self.emit(EmitTo::First(n), false)? {
+                // Clamp to the sort boundary when using partial group ordering,
+                // otherwise remove_groups panics (#20445).
+                let n = match &self.group_ordering {
```
Comment (alamb) [inline datafusion/physical-plan/src/aggregates/row_hash.rs:1041]: I found this logic quite confusing and the use of `0` as a sentiel also zero. Could we maybe encapsulate it into a method? That way we could at least explain what it is doing better. 

I tried a bunch of different forumations, and the best I could come up with was

```rust
impl GroupedHashAggregateStream {
...
     // Clamp to the sort boundary when using partial group ordering,
                // otherwise remove_groups panics (#20445).
                if let Some(emit_to) = self.emit_target_for_oom() {
                    if let Some(batch) = self.emit(EmitTo::First(n), false)?
                    {
                        return Ok(Some(ExecutionState::ProducingOutput(batch)))
                    }
                }
...

    /// Returns how many groups to try and emit in order to avoid an out-of-memory
    /// condition.
    ///
    /// Returns `None` if emitting is not possible.
    ///
    /// Returns Some(EmitTo) with the number of groups to emit if it is possible
    /// to emit some groups to free memory
    fn emit_target_for_oom(&self) -> Option<EmitTo> {
        let n = if self.group_values.len() >= self.batch_size {
            // Try to emit an integer multiple of batch size if possible
            self.group_values.len() / self.batch_size * self.batch_size
        } else {
            // Otherwise emit whatever we can
            self.group_values.len()
        };

        // Special case for GroupOrdering::None since emit_to() returns None for
        // that case, but we can still emit some groups to try to resolve the OOM
         if matches!(&self.group_ordering, GroupOrdering::None) {
             return Some(EmitTo::First(n));
         };

        self.group_ordering.emit_to()
            .map(|emit_to| match emit_to {
                // If the ordering allows emitting some groups,
                // emit as many as we can to try to resolve the OOM,
                EmitTo::First(max)=> EmitTo::First(n.min(max)),
                // if the ordering allows emitting all groups, we can emit n
                // groups to try to resolve the OOM
                EmitTo::All => EmitTo::First(n),
            })
    }

...
}
```


Here is the entire proposed diff

```diff
index 35f32ac7a..5bd33aab5 100644
--- a/datafusion/physical-plan/src/aggregates/row_hash.rs
+++ b/datafusion/physical-plan/src/aggregates/row_hash.rs
@@ -1038,26 +1038,50 @@ impl GroupedHashAggregateStream {

                 // Clamp to the sort boundary when using partial group ordering,
                 // otherwise remove_groups panics (#20445).
-                let n = match &self.group_ordering {
-                    GroupOrdering::None => n,
-                    _ => match self.group_ordering.emit_to() {
-                        Some(EmitTo::First(max)) => n.min(max),
-                        _ => 0,
-                    },
-                };
-
-                if n > 0
-                    && let Some(batch) = self.emit(EmitTo::First(n), false)?
-                {
-                    Ok(Some(ExecutionState::ProducingOutput(batch)))
-                } else {
-                    Err(oom)
+                if let Some(emit_to) = self.emit_target_for_oom() {
+                    if let Some(batch) = self.emit(EmitTo::First(n), false)? {
+                        return Ok(Some(ExecutionState::ProducingOutput(batch)));
+                    }
                 }
+
+                Err(oom)
             }
             _ => Err(oom),
         }
     }

+    /// Returns how many groups to try and emit in order to avoid an out-of-memory
+    /// condition.
+    ///
+    /// Returns `None` if emitting is not possible.
+    ///
+    /// Returns Some(EmitTo) with the number of groups to emit if it is possible
+    /// to emit some groups to free memory
+    fn emit_target_for_oom(&self) -> Option<EmitTo> {
+        let n = if self.group_values.len() >= self.batch_size {
+            // Try to emit an integer multiple of batch size if possible
+            self.group_values.len() / self.batch_size * self.batch_size
+        } else {
+            // Otherwise emit whatever we can
+            self.group_values.len()
+        };
+
+        // Special case for GroupOrdering::None since emit_to() returns None for
+        // that case, but we can still emit some groups to try to resolve the OOM
+        if matches!(&self.group_ordering, GroupOrdering::None) {
+            return Some(EmitTo::First(n));
+        };
+
+        self.group_ordering.emit_to().map(|emit_to| match emit_to {
+            // If the ordering allows emitting some groups,
+            // emit as many as we can to try to resolve the OOM,
+            EmitTo::First(max) => EmitTo::First(n.min(max)),
+            // if the ordering allows emitting all groups, we can emit n
+            // groups to try to resolve the OOM
+            EmitTo::All => EmitTo::First(n),
+        })
+    }
+
```

File: datafusion/physical-plan/src/aggregates/row_hash.rs [hunk 2]
```diff
@@ -1036,7 +1036,19 @@ impl GroupedHashAggregateStream {
...
+                    GroupOrdering::None => n,
+                    _ => match self.group_ordering.emit_to() {
+                        Some(EmitTo::First(max)) => n.min(max),
+                        _ => 0,
```
Comment (alamb) [inline datafusion/physical-plan/src/aggregates/row_hash.rs:1045]: Why not change this to emit n groups on `Some(EmitTo::All)`?

```rust
             _ => match self.group_ordering.emit_to() {
                        Some(EmitTo::First(max)) => n.min(max),
                        Some(EmitTo::All) => n,
                        _ => 0,
```

As I understand what it is doing, we are trying to ensure at most n groups are emitted
(this is incorporated above as well)

**Comment by alamb** [comment]
FYI @2010YOUY01 as I think you have also worked on this part of the code as well

**Comment by alamb** [comment]
@jackkleeman are you ok with merging this PR as is (and I will backport it and propose the cleanup as a follow on PR)?

**Comment by alamb** [comment]
Ok, in order to get 52.2.0 out, I am going to merge this PR and then make a proposed cleanup as a follow on

I'll then backport this PR as is to 52.2.0

**Comment by alamb** [comment]
Follow on PR:
- https://github.com/apache/datafusion/pull/20559

Backport:
- https://github.com/apache/datafusion/pull/20558

**Comment by jackkleeman** [comment]
so sorry @alamb i started a new job and its been a crazy few weeks. thanks for taking it on.

**Comment by alamb** [comment]
> so sorry @alamb i started a new job and its been a crazy few weeks. thanks for taking it on.

no problem -- I totally understand. Thank you for all your help
