### PR TITLE
bugfix: select_columns should validate column names

### LINKED ISSUE #18622: select_columns fails silently when invalid column names are passed
### Describe the bug

This appears to be a regression from https://github.com/apache/datafusion/pull/18236

### To Reproduce

I changed the unit test in `datafusion/core/tests/dataframe/mod.rs` as follows

```rust
#[tokio::test]
async fn select_columns() -> Result<()> {
    // build plan using Table API

    let t = test_table().await?;
    let t2 = t.clone().select_columns(&["c1", "c2", "c11"])?;
    let plan = t2.logical_plan().clone();

    // build query using SQL
    let sql_plan = create_plan("SELECT c1, c2, c11 FROM aggregate_test_100").await?;

    // the two plans should be identical
    assert_same_plan(&plan, &sql_plan);

    assert!(t.select_columns(&["non_existent_column"]).is_err());

    Ok(())
}
```

### Expected behavior

I would expect this to return an error as it did before when columns are selected that do not exist. Instead they are simply not present in the output dataframe.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by timsaucer**
## Which issue does this PR close?

- Closes #18622

## Rationale for this change

If you call `select_columns` or `drop_columns` and you pass an invalid column name, you should get an error. In 50.3 the unit tests I have updated will pass but in the current branch for 51 release candidate they fail.

## What changes are included in this PR?

Adds validation of column names.
Updates unit tests.

## Are these changes tested?

Yes, included. Also tested with datafusion-python.

### CODE REVIEW

**Comment by timsaucer** [comment]
@dqkqd would you mind reviewing?

File: datafusion/core/tests/dataframe/mod.rs [hunk 1]
```diff
@@ -305,6 +305,17 @@ async fn select_columns() -> Result<()> {
     Ok(())
 }
 
+#[tokio::test]
+async fn select_columns_with_nonexistent_columns() -> Result<()> {
+    let t = test_table().await?;
+    let t2 = t.select_columns(&["canada", "c2", "rocks"]);
+    let Err(DataFusionError::SchemaError(_, _)) = t2 else {
+        return internal_err!("select_columns with nonexistent columns should error");
+    };
```
Comment (dqkqd) [inline datafusion/core/tests/dataframe/mod.rs]: We could verify the actual error message here (or using `assert_snapshot!`):

```suggestion
    assert_contains!(
        t2.unwrap_err().strip_backtrace(),
        "Schema error: No field named canada"
    );
```

Comment (martin-g) [reply datafusion/core/tests/dataframe/mod.rs]: My personal preference for asserting on errors would be:
```rust
let t2 = t.select_columns(&["canada", "c2", "rocks"]);
match t2 {
    Err(DataFusionError::SchemaError(SchemaError::FieldNotFound { field, .. }, _)) => {
        // Verify it's the first invalid column
        assert_eq!(field.name(), "canada");
    }
    _ => panic!("Expected SchemaError::FieldNotFound for 'canada'"),
}
```

**Comment by alamb** [comment]
Thanks @timsaucer @martin-g and @dqkqd
