### PR TITLE
Fix duplicate group keys after hash aggregation spill (#20724)

### LINKED ISSUE #20724: Data regression in aggregations that spill
### Describe the bug

We (CC @rgehan) encountered a rare data regression in production during spillable aggregations, where `GROUP BY some_key` would return duplicate entries for `some_key` .

We reproduced in both Datafusion 50 and 52, and we believe we’ve found the root-cause and the fix.

Our understanding of the bug is the following:

when the `Final` aggregation spills and is done iterating over the `Partial` aggregation, it switches to a sorted streaming aggregation. This is implemented by resetting its input to point to the sorted spill stream, and by mutating some its internal state, notably 
`self.group_ordering = GroupOrdering::Full(GroupOrderingFull::new());`

https://github.com/apache/datafusion/blob/0aab6a3d2f67deb8eafe475b20942c6f2b40e886/datafusion/physical-plan/src/aggregates/row_hash.rs#L1220-L1222

This ordering then unlocks streaming the output here:

https://github.com/apache/datafusion/blob/0aab6a3d2f67deb8eafe475b20942c6f2b40e886/datafusion/physical-plan/src/aggregates/row_hash.rs#L754-L762

What’s problematic is that at this point, the `GroupedHashAggregateStream#group_values` state didn't get rebuilt: in our case it’s still a `GroupValuesColumn<Streaming = false>` , which uses `vectorized_intern` under the hood and can lead to correctness bugs in the case of streaming aggregations, as documented here:

https://github.com/apache/datafusion/blob/65a6bc423142678528cdde03e4e2823952758328/datafusion/physical-plan/src/aggregates/group_values/multi_group_by/mod.rs#L321

This bug analysis correlates quite well with the data correctness symptoms we experienced in production, aka, duplicated grouping keys output by the aggregation.

We fixed the correctness problem by resetting  `group_values` to the streaming implementation when  `group_ordering` get mutated, cf [this example commit](https://github.com/rgehan/datafusion/commit/45bddb5d93c97942d0f1ec8f24d8baa5c6fee0ce) :

```
self.group_ordering = GroupOrdering::Full(GroupOrderingFull::new());
self.group_values = new_group_values(group_schema, &self.group_ordering)?;
```

### To Reproduce

We have a reproduction based on production data which isn’t really comfortable to share as is / takes a while to run / is a bit complex.

We’ve tried to simplify the reproduction without much success so far, we’d be happy to get assistance of maintainers to build a synthetic repro, which probably involves hash collisions here.

### Expected behavior

No duplicate groups after an aggregation.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gboucher90**
## Which issue does this PR close?

- Closes #20724

## Rationale for this change

When `update_merged_stream()` switches to streaming merge after spill, it sets `group_ordering = GroupOrdering::Full` but does not recreate `group_values`. The existing `GroupValuesColumn<false>` uses `vectorized_intern`, which can produce non-monotonic group indices under hash collisions, violating `GroupOrderingFull`'s assumption and causing duplicate groups in the output.

### Example with concrete values

Consider a batch of 6 rows arriving at `vectorized_intern` after spill merge, with keys that hash to only 2 buckets (due to partial collisions):

```
Row  Key        Hash (truncated)  Bucket
───  ─────────  ────────────────  ──────
0    (1, 100)   0x03              3
1    (1, 200)   0x03              3      ← collides with row 0
2    (1, 300)   0x07              7
3    (1, 400)   0x07              7      ← collides with row 2
4    (1, 500)   0x03              3      ← collides with rows 0,1
5    (1, 600)   0x07              7      ← collides with rows 2,3
```

`vectorized_intern` processes rows in two passes:

1. **Fast path** (empty bucket → new group): rows 0, 2 get group indices 0, 1
2. **Collision path** (bucket occupied → `equal_to` → not equal → new group): rows 1, 3, 4, 5 get indices 2, 3, 4, 5

The resulting group index assignment is:

```
Row  Key        Group Index
───  ─────────  ───────────
0    (1, 100)   0           ← fast path
1    (1, 200)   2           ← collision path (processed after all fast-path rows)
2    (1, 300)   1           ← fast path
3    (1, 400)   3           ← collision path
4    (1, 500)   4           ← collision path
5    (1, 600)   5           ← collision path
```

The group indices are **non-monotonic**: `[0, 2, 1, 3, 4, 5]`. The input was sorted `(1,100) < (1,200) < (1,300)`, but group 2 (key `(1,200)`) comes after group 1 (key `(1,300)`).

`GroupOrderingFull` tracks progress via `current = total_num_groups - 1`. When group index 1 is seen, it thinks group 0 is complete and emits it. But later, group index 2 arrives for key `(1,200)` — a key that sorts *between* already-emitted groups. If this group happens to span a batch boundary, it gets emitted twice: once partially in the current batch and once in the next batch, producing **duplicate group keys** in the final output.

## What changes are included in this PR?

**Fix** (`row_hash.rs`): Recreate `group_values` after updating `group_ordering` in `update_merged_stream()`, so the streaming-mode `GroupValuesColumn<true>` (with `scalarized_intern`) is used instead. `scalarized_intern` processes rows one at a time, always producing monotonic group indices.

**Regression test** (`memory_limit/mod.rs`): Deterministic test that reproduces the bug using a new `force_hash_partial_collisions` feature flag.

**New feature flag** (`force_hash_partial_collisions`): Truncates real hashes to 5 bits (32 distinct values) instead of zeroing them all. Full collisions (`force_hash_collisions`) paradoxically do not trigger the bug because all rows land in the same bucket, so every row takes the collision path in order — producing monotonic indices. Partial collisions create the necessary mix of fast-path and collision-path rows.

**CI** (`extended.yml`, `rust.yml`): Added the regression test to extended tests and a compile check for the new feature.

## Are these changes tested?

Yes — the new `test_no_duplicate_groups_after_spill` test deterministically reproduces the bug (fails without the fix, passes with it) when compiled with `--features force_hash_partial_collisions`.

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/physical-plan/src/aggregates/row_hash.rs [hunk 1]
```diff
@@ -1267,6 +1267,18 @@ impl GroupedHashAggregateStream {
...
+            // Recreate group_values to use streaming mode (GroupValuesColumn<true>
+            // with scalarized_intern) which preserves input row order, as required
+            // by GroupOrderingFull. This is only needed for multi-column group by,
+            // since single-column uses GroupValuesPrimitive which is always safe.
+            let group_schema = self
+                .spill_state
+                .merging_group_by
+                .group_schema(&self.spill_state.spill_schema)?;
+            if group_schema.fields().len() > 1 {
+                self.group_values = new_group_values(group_schema, &self.group_ordering)?;
```
Comment (gboucher90) [inline datafusion/physical-plan/src/aggregates/row_hash.rs:1279]: Note: 
> only recreates group_values for multi-column GROUP BY (fields().len() > 1), since single-column uses GroupValuesPrimitive which doesn't have the vectorized_intern bug. This avoids the memory overhead that was causing aggregate_source_not_yielding_with_spill to fail with its tight 2600-byte budget.

File: .github/workflows/extended.yml [hunk 2]
```diff
@@ -154,11 +154,16 @@ jobs:
         uses: ./.github/actions/setup-builder
         with:
           rust-version: stable
-      - name: Run tests
+      - name: Run tests (force_hash_collisions)
         run: |
           cd datafusion
           cargo test  --profile ci --exclude datafusion-examples --exclude datafusion-benchmarks --exclude datafusion-sqllogictest --exclude datafusion-cli --workspace --lib --tests --features=force_hash_collisions,avro
           cargo clean
+      - name: Run tests (force_hash_partial_collisions, #20724)
```
Comment (alamb) [inline .github/workflows/extended.yml]: Given how long our CI already runs for we probably want to avoid a new target (this will recompile a bunch of DataFusion even though it only runs one test)

Another technique we might use to add coverage / find a reproducer here is fuzzing

File: datafusion/physical-plan/src/aggregates/row_hash.rs [hunk 3]
```diff
@@ -1267,6 +1267,18 @@ impl GroupedHashAggregateStream {
             // on the grouping columns.
             self.group_ordering = GroupOrdering::Full(GroupOrderingFull::new());
 
+            // Recreate group_values to use streaming mode (GroupValuesColumn<true>
+            // with scalarized_intern) which preserves input row order, as required
+            // by GroupOrderingFull. This is only needed for multi-column group by,
+            // since single-column uses GroupValuesPrimitive which is always safe.
```
Comment (alamb) [inline datafusion/physical-plan/src/aggregates/row_hash.rs]:
```suggestion
            // Recreate `group_values` for streaming merge so group ids are assigned
            // in first-seen order, as required by `GroupOrderingFull`.
            // The pre-spill multi-column collector may use `vectorized_intern`, which
            // can assign new group ids out of input order under hash collisions.
```

**Review by alamb — COMMENTED** [review]
Thank you very much @gboucher90 and @16pierre

I reviewed the code quite carefully and it looks good. However, I am concerned about the additional testing complexity added for this one corner case

so, as much as it pains me, I recommend:
1. Remove the extra feature flag / CI run
2. Just put in the code fix

File: .github/workflows/extended.yml (hunk 2 above)
Comment (alamb) [reply .github/workflows/extended.yml]: I made a PR here to propose removing the test
- https://github.com/gboucher90/datafusion/pull/1

Comment (gboucher90) [reply .github/workflows/extended.yml]: Ah thank you 🙇 , I was about to do it after my lunch break

**Comment by gboucher90** [comment]
> I reviewed the code quite carefully and it looks good. However, I am concerned about the additional testing complexity added for this one corner case

Yes that makes sense, I get it, I was also not very satisified with it to be honest but couldn't find a better way unfortunately

File: .github/workflows/extended.yml (hunk 2 above)
Comment (gboucher90) [reply .github/workflows/extended.yml]: I merged it on this branch, thanks a lot

**Comment by alamb** [comment]
Thanks again @gboucher90

**Comment by gboucher90** [comment]
> Thanks again @gboucher90

No problem, thank you for maintaining this project and being so reactive on all those issues/PRs

**Comment by gboucher90** [comment]
(Note: I cannot merge myself the PR but I assume this is expected and you will be merging it when appropriate)

**Comment by alamb** [comment]
> (Note: I cannot merge myself the PR but I assume this is expected and you will be merging it when appropriate)

Yes, I plan to merge this later today or tomorrow

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Thanks agian @gboucher90

**Comment by gboucher90** [comment]
> Thanks agian @gboucher90

No problem, I merely wrote the test. The investigation and fix, which are the bulk of the work, were done by @rgehan and @16pierre so please make sure to credit them for their work in the changelog if possible 🙇
