### PR TITLE
fix: DataFusion panics with "No candidates provided"

### LINKED ISSUE #12464: DataFusion panics with "No candidates provided"
### Describe the bug

I am working on a small prototype that uses DataFusion and I have a query failing with:

```
thread 'test_tpch_q1' panicked at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/datafusion-sql-41.0.0/src/expr/function.rs:79:10:
No candidates provided.
```

This happens in `suggest_valid_function` when no suggestions are found. It is likely because I have an error with my context setup but it look like it should be trival to use an `Err` instead of a panic here, which would be better DX for others building new things on DataFusion.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Weijun-H**
## Which issue does this PR close?

Closes #12464

### CODE REVIEW

File: datafusion/sql/src/expr/function.rs [hunk 1]
```diff
@@ -77,7 +77,7 @@ fn find_closest_match(candidates: Vec<String>, target: &str) -> String {
                 &target,
             )
         })
-        .expect("No candidates provided.") // Panic if `candidates` argument is empty
+        .ok_or_else(|| internal_datafusion_err!("No candidates provided."))
```
Comment (alamb) [inline datafusion/sql/src/expr/function.rs:80]:
```suggestion
        .ok_or_else(|| internal_datafusion_err!("No functions registered with this context."))
```

**Review by alamb — APPROVED** [review]
Thank you @Weijun-H  -- what do you think about adding a small test for this too? It should be pretty simple: don't register any functions and then run a sql test with a unknown function 🤔

File: datafusion/sql/src/expr/function.rs [hunk 2]
```diff
@@ -66,8 +66,8 @@ pub fn suggest_valid_function(
 }
 
 /// Find the closest matching string to the target string in the candidates list, using edit distance(case insensitive)
-/// Input `candidates` must not be empty otherwise it will panic
-fn find_closest_match(candidates: Vec<String>, target: &str) -> String {
+/// Input `candidates` must not be empty otherwise an error is returned.
+fn find_closest_match(candidates: Vec<String>, target: &str) -> Result<String> {
```
Comment (comphead) [inline datafusion/sql/src/expr/function.rs:70]: Wondering may be it can be an `Option<String>`?
Usually `find` methods, on collections as well returns the Option

Comment (alamb) [reply datafusion/sql/src/expr/function.rs:70]: I tried this -- I'll put up a PR as a follow on.

**Review by alamb — APPROVED** [review]
Thanks again @Weijun-H and @comphead for the review

I think this PR is definitely better as it doesn't panic.

**Comment by alamb** [comment]
Technically speaking this PR has an API change as I think the signature of a public function has changed

**Comment by alamb** [comment]
Thanks again @Weijun-H and @comphead
