### PR TITLE
fix: predicate cache stats calculation

### LINKED ISSUE #19334: Possible incorrect calculation of predicate_cache statistics received from arrow-rs
### Describe the bug

Hey everyone! 👋🏻

I was reading through how metrics are exported to `datafusion` from `arrow-rs`, it seems to be happening with the help of [ArrowReaderMetrics](https://github.com/apache/arrow-rs/blob/e49c2edbde46c09cf19d2be344a841a041d416f0/parquet/src/arrow/arrow_reader/metrics.rs#L31-L38). We [init](https://github.com/apache/datafusion/blob/899a762230d0abc705482d8898d3793763b6afb4/datafusion/datasource-parquet/src/opener.rs#L498) this struct in `ParquetOpener` and then update metric using [map](https://github.com/apache/datafusion/blob/899a762230d0abc705482d8898d3793763b6afb4/datafusion/datasource-parquet/src/opener.rs#L526) over stream by fetching value from the `ArrowReaderMetrics` struct and [incrementing](https://github.com/apache/datafusion/blob/899a762230d0abc705482d8898d3793763b6afb4/datafusion/datasource-parquet/src/opener.rs#L580) value of datafusion metric.

Problem I see with this flow is, `map` is called whenever stream returns anything, so lets say stream is polled 3 times. We get value of an ever increasing metric 3 times and add it over.

### To Reproduce

I noticed this when trying to implement a different metric, its on an internal fork, but I can try to make a reproducer if this is getting hard to understand.

### Expected behavior

For e.g. if it looked like this:

start: there are 3 record batches worth of data in this file, and df_predicate_cache_inner_records = 0

- 1st poll: return 1st record batch, predicate_cache_inner_records: 5, adding to df_predicate_cache_inner_records: 5
- 2nd poll: return 2nd record batch, predicate_cache_inner_records: 10, adding to df_predicate_cache_inner_records: 15
- 3rd poll: return 3rd record batch, predicate_cache_inner_records: 15, adding to df_predicate_cache_inner_records: 30

So instead of metric in datafusion having a value of 15, it gets 30. In short, we would have wanted to store metric at the end of the stream, but as we implemented this using map we are getting a compounded value of the metric over time.

### Additional context

Do correct me if I am understanding this correctly, if this indeed sounds like a bug, I would love to make a fix for the same :)

### PR DESCRIPTION
**Pull request by feniljain**
## Which issue does this PR close?

- Closes #19334

## Rationale for this change

Explained in issue

## What changes are included in this PR?

Changed counter to gauge to set value provided by arrow-rs correctly

## Are these changes tested?

Yes, have added a new test which fails with old code as it reports compounded metric

## Are there any user-facing changes?

There are user-facing changes, but it's more of a fix to a metric reported to the user. No change to API itself.

### CODE REVIEW

**Comment by feniljain** [comment]
Resolved the conflict, thank you for reviewing @xudong963! 🙇🏻

File: datafusion/datasource-parquet/src/metrics.rs [hunk 1]
```diff
@@ -77,11 +77,11 @@ pub struct ParquetFileMetrics {
     /// Parquet.
     ///
     /// This is the expensive path (IO + Decompression + Decoding).
-    pub predicate_cache_inner_records: Count,
+    pub predicate_cache_inner_records: Gauge,
```
Comment (alamb) [inline datafusion/datasource-parquet/src/metrics.rs:85]: It may be somewhat subtle why this is a gauge. Maybe we can add a comment explaining the context

Something like

```suggestion
    ///
    /// Use a Gauge to avoid double counting inner counter values from parquet reader
    pub predicate_cache_inner_records: Gauge,
```

(also below)

Comment (feniljain) [reply datafusion/datasource-parquet/src/metrics.rs:85]: That's a good catch, should have thought about that 🙈

I have tried to add a slightly more detailed comment, lemme know if that does not work 😅

**Comment by alamb** [comment]
Thanks again @feniljain
