### PR TITLE
fix: stack overflow for substrait functions with large argument lists that translate to DataFusion binary operators  

### LINKED ISSUE #16030: Stack overflow for substrait functions with large argument lists that translate to DataFusion binary operators
### Describe the bug

When [translating a substrait scalar function call](https://github.com/fmonjalet/datafusion/blob/b7060c143c3eede8f49f8b51d92e184043e3a081/datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs#L25) to DataFusion logical plan, when the function name [translates to a binary operator](https://github.com/fmonjalet/datafusion/blob/b7060c143c3eede8f49f8b51d92e184043e3a081/datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs#L78) and has a large number of arguments (say 2000), further processing of this logical plan result in stack overflow.

### To Reproduce

[This commit](https://github.com/apache/datafusion/commit/fd13db09dd76ea888f7dc43340a4b3b7a316f038) contains a reproducer plan and test. The plan is pretty large (because a lot of arguments are required to see the stack overflow), but pretty simple: it's an `OR(col == a, col ==b, col == c, ..., col == x)`. We could argue that this precise example should actually be a substrait `SingularOrList`, but the issue can be triggered all the same with other operators and expressions.

### Expected behavior

No stack overflow or crash. At best, the plan is accepted and executed, at worst DataFusion returns a clean error.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fmonjalet**
## Which issue does this PR close?

- Closes #16030

## Rationale for this change

Some substrait plans can cause DataFusion to trigger stack overflow, crashing the hosting process and preventing to run them. This stack overflow is caused by very large recursion levels. See issue for more details.

This kind of issue may also occur in the SQL --> Logical plan path, but I did not investigate it yet. The "ideal" fix would be not to rely on recursion for most operations on plans, but this sounds like an unreasonably large and complex code change for now.

~~**This is a fairly small change**, the high diff count is because of the added sample substrait plan, that has to be large to reproduce the issue.~~
==> The PR has been updated to avoid the large test file.

## What changes are included in this PR?

When transforming a substrait function call to DataFusion logical plan,
if the substrait function maps to a DataFusion binary operator, but has
more than 2 arguments, it is mapped to a tree of BinaryExpr. This
BinaryExpr tree is not balanced, and its depth is the number of
arguments:

```
       Op
      /  \
    arg1  Op
         /  \
       arg2  ...
             /  \
           argN  Op
```

Since many functions manipulating the logical plan are recursive, it
means that N arguments result in an `O(N)` recursion, leading to stack
overflows for large N (1000 for example).

Transforming these function calls into a balanced tree mitigates the
issue:

```
             .__ Op __.
            /          \
          Op            Op
         /  \          /  \
       ...  ...      ...  ...
      /  \  /  \    /  \  /  \
    arg1        ...          argN
```

The recursion depth is now `O(log2(N))`, meaning that 1000 arguments
results in a depth of ~10, and it would take 2^1000 arguments to reach a
depth of 1000, which is a vastly unreasonable amount of data.

Therefore, it's not possible to use this flaw anymore to trigger stack
overflows in processes running DataFusion.

The new balanced tree preserves the order of execution (`arg1` evaluated
before `arg2`) and has the same order of magnitude of operator nodes.
The main change is that there is now at least `O(log2(N))` operators evaluated,
whereas before the minimum was 1, if the first operator exited after evaluating
only its left side.

## Are these changes tested?

Yes

## Are there any user-facing changes?

No, the change to the logical plan is semantically equivalent and should not be exposed to users.

### CODE REVIEW

File: datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs [hunk 1]
```diff
@@ -124,6 +109,31 @@ pub fn name_to_op(name: &str) -> Option<Operator> {
...
+    // Cut argument list in 2 balanced parts
+    let mid_idx = args.len() / 2;
+    let left = arg_list_to_binary_op_tree(op, &args[0..mid_idx]);
+    let right = arg_list_to_binary_op_tree(op, &args[mid_idx..]);
+    Expr::BinaryExpr(BinaryExpr {
+        left: Box::new(left),
+        op,
+        right: Box::new(right),
+    })
+}
```
Comment (gabotechs) [inline datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs:135]: Nice! do you think we can do it without cloning the expressions? something like:
```rust
fn arg_list_to_binary_op_tree(op: Operator, mut args: Vec<Expr>) -> Expr {
    if args.is_empty() {
        panic!("must not be called with empty args");
    }
    if args.len() == 1 {
        return args.into_iter().next().unwrap();
    }
    // Cut argument list in 2 balanced parts
    let mid_idx = args.len() / 2;
    let right = arg_list_to_binary_op_tree(op, args.split_off(mid_idx));
    let left = arg_list_to_binary_op_tree(op, args);
    Expr::BinaryExpr(BinaryExpr {
        left: Box::new(left),
        op,
        right: Box::new(right),
    })
}
```

Comment (LiaCastaneda) [reply datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs:135]: quick question: is it safe to balance any operator?

Comment (LiaCastaneda) [reply datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs:135]: ah ok nvm, I just read order of execution is preserved ^

**Comment by fmonjalet** [comment]
> Is it possible to add the test that generate equivalent json?
@jayzhan211 sure, I can even try to build the substrait plan programatically. This will be more verbose, but more explicit.

**Comment by fmonjalet** [comment]
@jayzhan211 After looking into it, generating the plan programatically may become very unwieldy (very verbose). Is your concern about the size of the file checked into git, or the fact that it's hard to read because it's so large?
If it's the former, I can put in two files and put together some string formatting. If it's the former, this won't help much as it will still be pretty hard to read and understand and we'll have to find another better way!

**Comment by jayzhan211** [comment]
> @jayzhan211 After looking into it, generating the plan programatically may become very unwieldy (very verbose). Is your concern about the size of the file checked into git, or the fact that it's hard to read because it's so large? If it's the former, I can put in two files and put together some string formatting. If it's the former, this won't help as much, but will still be more readable for humans.

My idea is that we can generate such parameters for the code we want to test, we don't need end to end test from json.

I take a quick look, if we enter this function, I think it is possible to generate a deep nested `Expression` that easily cause stack overflow.
```rust
    async fn consume_expression(
        &self,
        expr: &Expression,
        input_schema: &DFSchema,
    ) -> datafusion::common::Result<Expr> {
        from_substrait_rex(self, expr, input_schema).await
    }
```

If that doesn't work, I think we don't even need to keep such test since the change to me is quite trivial.

**Comment by fmonjalet** [comment]
Oh right it makes sense, I'll try to produce a test based on `consume_expression` then. Thanks!

File: datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs (hunk 1 above)
Comment (fmonjalet) [reply datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs]: @gabotechs unfortunately [`.split_off()` calls clone](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.split_off), but I got a simple enough version working with an explicit `Drain`. Thanks for making me look again!

**Comment by fmonjalet** [comment]
@jayzhan211 and @gabotechs thank you for your guidance, I updated the PR:

- Expressions are not cloned anymore.
- The test has been scoped to a much more unit test style, where we build a substrait `ScalarFunction` call and translate it to a DataFusion expression. I manually checked that reverting the fix made the test fail. It requires a larger argument list to trigger the issue because the expressions are simpler than in the original complex plan I submitted.

Ready for a next round of feedback if any!

File: datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs [hunk 2]
```diff
@@ -54,23 +55,8 @@ pub async fn from_scalar_function(
...
-                        right: Box::new(arg),
-                    }),
-                    None => arg,
-                })
-            })
-            .unwrap();
-
-        Ok(combined_expr)
+        // In those cases we build a balanced tree of BinaryExprs
+        Ok(arg_list_to_binary_op_tree(op, args))
```
Comment (gabotechs) [inline datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs:59]: If `args` is the thing that must not be empty, maybe it's better to do `args.len() < 2` instead of `f.arguments.len() < 2` in line 52?

File: datafusion/substrait/src/logical_plan/consumer/utils.rs [hunk 3]
```diff
@@ -560,4 +564,41 @@ pub(crate) mod tests {
...
+        };
+        // Trivial input schema
+        let schema = Schema::new(vec![Field::new("a", DataType::Boolean, false)]);
+        let df_schema = DFSchema::try_from(schema).unwrap();
+
+        // Consume the expression and ensure we don't crash
+        let _ = consumer
+            .consume_scalar_function(&func, &df_schema)
+            .await
+            .expect("This should succeed");
```
Comment (gabotechs) [inline datafusion/substrait/src/logical_plan/consumer/utils.rs:601]: nit: propagate the errors to the test runner

```suggestion
        let df_schema = DFSchema::try_from(schema)?;

        // Consume the expression and ensure we don't crash
        let _ = consumer.consume_scalar_function(&func, &df_schema).await?;
```

File: datafusion/substrait/src/logical_plan/consumer/utils.rs [hunk 4]
```diff
@@ -560,4 +564,41 @@ pub(crate) mod tests {
         );
         Ok(())
     }
+
+    /// Test that large argument lists for binary operations do not crash the consumer
+    #[tokio::test]
+    async fn test_binary_op_large_argument_list() -> Result<()> {
```
Comment (gabotechs) [inline datafusion/substrait/src/logical_plan/consumer/utils.rs:570]: As this test is not testing any `utils` function, do you think we can place it somewhere else? maybe in `scalar_function.rs` as it's testing the `consume_scalar_function()` method in the consumer?

**Review by gabotechs — APPROVED** [review]
💯 very smart usage of `std::vec::Drain` +1

I don't think it's strictly necessary, but leaving here some further testing ideas that I explored on my own:
<details><summary>not strictly necessary unit tests</summary>

```rust
#[cfg(test)]
mod tests {
    use super::*;
    use insta::assert_snapshot;

    fn n(n: i64) -> Expr {
        Expr::Literal(ScalarValue::Int64(Some(n)))
    }

    #[test]
    fn arg_list_to_binary_op_tree_1_arg() {
        let expr = arg_list_to_binary_op_tree(Operator::Or, vec![n(1)]);
        assert_snapshot!(expr.to_string(), @"Int64(1)");
    }

    #[test]
    fn arg_list_to_binary_op_tree_2_args() {
        let expr = arg_list_to_binary_op_tree(Operator::Or, vec![n(1), n(2)]);
        assert_snapshot!(expr.to_string(), @"Int64(1) OR Int64(2)");
    }

    #[test]
    fn arg_list_to_binary_op_tree_3_args() {
        let expr = arg_list_to_binary_op_tree(Operator::Or, vec![n(1), n(2), n(3)]);
        assert_snapshot!(expr.to_string(), @"Int64(1) OR Int64(2) OR Int64(3)");
    }

    #[test]
    fn arg_list_to_binary_op_tree_4_args() {
        let expr = arg_list_to_binary_op_tree(Operator::Or, vec![n(1), n(2), n(3), n(4)]);
        assert_snapshot!(expr.to_string(), @"Int64(1) OR Int64(2) OR Int64(3) OR Int64(4)");
    }
}
```
</details>

File: datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs [hunk 5]
```diff
@@ -124,6 +110,43 @@ pub fn name_to_op(name: &str) -> Option<Operator> {
...
+    let n_args = args.len();
+    let mut drained_args = args.drain(..);
+    _arg_list_to_binary_op_tree(op, &mut drained_args, n_args)
+}
+
+/// Helper function for [`arg_list_to_binary_op_tree`] implementation
+///
+/// `take_len` represents the number of elements to take from `args` before returning.
+/// We use `take_len` to avoid recursively building a `Take<Take<Take<...>>>` type.
+fn _arg_list_to_binary_op_tree(
```
Comment (comphead) [inline datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs:128]: Please use `Result<Expr>` as the return type

File: datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs [hunk 6]
```diff
@@ -124,6 +110,43 @@ pub fn name_to_op(name: &str) -> Option<Operator> {
     }
 }
 
+/// Build a balanced tree of binary operations from a binary operator and a list of arguments.
+///
+/// For example, `OR` `(a, b, c, d, e)` will be converted to: `OR(OR(a, OR(b, c)), OR(d, e))`.
+///
+/// `args` must not be empty.
+fn arg_list_to_binary_op_tree(op: Operator, mut args: Vec<Expr>) -> Expr {
```
Comment (comphead) [inline datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs:118]: Please return a `Result<Expr>`

File: datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs (hunk 5 above)
Comment (comphead) [inline datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs:128]:
```suggestion
fn arg_list_to_binary_op_tree_inner(
```

File: datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs [hunk 7]
```diff
@@ -124,6 +110,43 @@ pub fn name_to_op(name: &str) -> Option<Operator> {
...
+/// We use `take_len` to avoid recursively building a `Take<Take<Take<...>>>` type.
+fn _arg_list_to_binary_op_tree(
+    op: Operator,
+    args: &mut Drain<Expr>,
+    take_len: usize,
+) -> Expr {
+    if take_len == 1 {
+        return args.next().unwrap();
+    } else if take_len == 0 {
+        panic!("must not be called with empty args");
```
Comment (comphead) [inline datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs:136]: please use a DataFusionError::SubstraitError
```
    /// Errors from either mapping LogicalPlans to/from Substrait plans
    /// or serializing/deserializing protobytes to Substrait plans
    Substrait(String)
```

Comment (fmonjalet) [reply datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs:136]: Makes sense, thanks!

File: datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs (hunk 2 above)
Comment (fmonjalet) [reply datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs:59]: Makes sense, fixed it in upcoming commit 👍

File: datafusion/substrait/src/logical_plan/consumer/utils.rs (hunk 4 above)
Comment (fmonjalet) [reply datafusion/substrait/src/logical_plan/consumer/utils.rs:570]: Makes sense, I added the test in the only place `DefaultSubstraitConsumer` was used, but moving it to the `scalar_function` module is better. Thanks!

**Comment by fmonjalet** [comment]
Thanks for the second round of feedback! This is now ready for a re-review.
All the comments should have been taken into account. I force pushed to remove the first commit that added the large file, so that PR passes the CI (otherwise the large file is still in the history and the CI check fails), but all new changes have been added as additional commits for easier review, [starting with this one](https://github.com/apache/datafusion/pull/16031/commits/ce9ad7057dc3993a184d926c4936bb2272f722fe).

**Review by gabotechs — APPROVED** [review]

**Review by comphead — APPROVED** [review]
Thanks @fmonjalet I think it is LGTM to be now, love the testing

File: datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs [hunk 8]
```diff
@@ -254,3 +284,86 @@ impl BuiltinExprBuilder {
...
+        Ok(())
+    }
+
+    fn n(n: i64) -> Expr {
+        Expr::Literal(ScalarValue::Int64(Some(n)))
+    }
+
+    #[test]
+    fn arg_list_to_binary_op_tree_1_arg() -> Result<()> {
+        let expr = arg_list_to_binary_op_tree(Operator::Or, vec![n(1)])?;
```
Comment (jayzhan211) [inline datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs:343]: you can use `lit(1)` directly instead of n(1)

**Review by jayzhan211 — APPROVED** [review]

File: datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs (hunk 8 above)
Comment (fmonjalet) [reply datafusion/substrait/src/logical_plan/consumer/expr/scalar_function.rs]: Makes sense, I switched to a more explicit function name (`int64_literals`) taking a slice of integers to keep a compact code.

**Comment by alamb** [comment]
I plan to merge this PR to main once the CI has passed

**Comment by alamb** [comment]
Thanks again everyone

**Comment by fmonjalet** [comment]
Thanks everyone for the review and the merge!
