### PR TITLE
Fix: Remove Unrelated Fields When Expanding Wildcards in Functional Dependency Projections

### LINKED ISSUE #12054: Bug in Functional Dependency Calculation for Projection
### Describe the bug

Following query gives the error: 

```
SELECT s.*, s.amount * LAST_VALUE(e.rate) AS amount_usd
FROM sales_global AS s
JOIN exchange_rates AS e
ON s.currency = e.currency_from AND
   e.currency_to = 'USD' AND
   s.ts >= e.ts
GROUP BY s.sn
ORDER BY s.sn
```

`External error: query failed: DataFusion error: Error during planning: Invalid functional dependency: FunctionalDependencies { deps: [FunctionalDependence { source_indices: [1], target_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], nullable: false, mode: Single }] }`

It might be related with #11681, since I reverted the changes in `datafusion/expr/src/logical_plan/plan.rs`, and the test passed.

### To Reproduce

```
statement ok
CREATE TABLE sales_global (
    ts TIMESTAMP,
    sn INTEGER,
    amount INTEGER,
    currency VARCHAR NOT NULL,
    primary key(sn)
);

statement ok
CREATE TABLE exchange_rates (
  ts TIMESTAMP,
  sn INTEGER,
  currency_from VARCHAR NOT NULL,
  currency_to VARCHAR NOT NULL,
  rate FLOAT,
  primary key(sn)
);

query TT
EXPLAIN SELECT s.*, s.amount * LAST_VALUE(e.rate) AS amount_usd
FROM sales_global AS s
JOIN exchange_rates AS e
ON s.currency = e.currency_from AND
   e.currency_to = 'USD' AND
   s.ts >= e.ts
GROUP BY s.sn
ORDER BY s.sn
----
```

### Expected behavior

The test should pass

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by berkaysynnada**
## Which issue does this PR close?

Closes #12054.

## Rationale for this change

Our downstream tests started failing after #11681. In` calc_func_dependencies_for_project()`, the projection length is no longer taken from the expression length. Instead, wildcard expressions are now counted based on the number of fields in the wildcard schema. The problem occurs when the wildcard expression has a table reference, but the wildcard schema is built on multiple tables.

## What changes are included in this PR?

This PR filters the wildcard schema according to the table reference of the wildcard expression.

## Are these changes tested?

Yes, a minimal example of our failing test has been added to `joins.slt`.

### CODE REVIEW

File: datafusion/expr/src/utils.rs [hunk 1]
```diff
@@ -838,16 +838,41 @@ pub fn exprlist_len(
...
+                        let qualified_fields = schema
+                            .fields()
+                            .iter()
+                            .enumerate()
+                            .filter_map(|(idx, field)| {
+                                let (maybe_table_ref, _field) =
+                                    schema.qualified_field(idx);
+                                if maybe_table_ref == Some(qualifier)
+                                    || maybe_table_ref.is_none()
+                                {
```
Comment (ozankabak) [inline datafusion/expr/src/utils.rs:854]:
```suggestion
                                let (maybe_table_ref, _) =
                                    schema.qualified_field(idx);
                                if maybe_table_ref.map_or(true, |q| q == qualifier) {
```

**Review by ozankabak — APPROVED** [review]
Minor style suggestion, otherwise LGTM

File: datafusion/sqllogictest/test_files/joins.slt [hunk 2]
```diff
@@ -4040,3 +4040,59 @@ physical_plan
...
+CREATE TABLE sales_global (
+    ts TIMESTAMP,
+    sn INTEGER,
+    amount INTEGER,
+    currency VARCHAR NOT NULL,
+    primary key(sn)
+);
+
+statement ok
+CREATE TABLE exchange_rates (
```
Comment (goldmedal) [inline datafusion/sqllogictest/test_files/joins.slt:4056]: How about dorp `sales_global` and `exchange_rates` after the test?

**Review by goldmedal — APPROVED** [review]
Thank @berkaysynnada for fixing this. LGTM. Just one minor comment.
I'm sorry for missing this case 😭

**Comment by ozankabak** [comment]
Thank you @goldmedal for reviewing
