### PR TITLE
Enhance: simplify `x=x` --> `x IS NOT NULL OR NULL`

### LINKED ISSUE #15387: Trivial WHERE filter not eliminated when combined with CTE
### Describe the bug

I am testing against Datafusion main (d68fca91fd4c73f2cd92d61d036bc0411a2ed826).

With the query below I expect there to be no `FilterExec` because the condition is trivial `x = x`. But it is not eliminated.

### To Reproduce

```
> explain with test AS (SELECT unnest(generate_series(1, 10)) as x)
select count(*) from test WHERE x = x;
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                              |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: count(Int64(1)) AS count(*)                                                                                                                           |
|               |   Aggregate: groupBy=[[]], aggr=[[count(Int64(1))]]                                                                                                               |
|               |     SubqueryAlias: test                                                                                                                                           |
|               |       Projection:                                                                                                                                                 |
|               |         Filter: __unnest_placeholder(generate_series(Int64(1),Int64(10)),depth=1) = __unnest_placeholder(generate_series(Int64(1),Int64(10)),depth=1)             |
|               |           Unnest: lists[__unnest_placeholder(generate_series(Int64(1),Int64(10)))|depth=1] structs[]                                                              |
|               |             Projection: List([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) AS __unnest_placeholder(generate_series(Int64(1),Int64(10)))                                        |
|               |               EmptyRelation                                                                                                                                       |
| physical_plan | ProjectionExec: expr=[count(Int64(1))@0 as count(*)]                                                                                                              |
|               |   AggregateExec: mode=Final, gby=[], aggr=[count(Int64(1))]                                                                                                       |
|               |     CoalescePartitionsExec                                                                                                                                        |
|               |       AggregateExec: mode=Partial, gby=[], aggr=[count(Int64(1))]                                                                                                 |
|               |         ProjectionExec: expr=[]                                                                                                                                   |
|               |           CoalesceBatchesExec: target_batch_size=8192                                                                                                             |
|               |             FilterExec: __unnest_placeholder(generate_series(Int64(1),Int64(10)),depth=1)@0 = __unnest_placeholder(generate_series(Int64(1),Int64(10)),depth=1)@0 |
|               |               RepartitionExec: partitioning=RoundRobinBatch(8), input_partitions=1                                                                                |
|               |                 UnnestExec                                                                                                                                        |
|               |                   ProjectionExec: expr=[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] as __unnest_placeholder(generate_series(Int64(1),Int64(10)))]                             |
|               |                     PlaceholderRowExec                                                                                                                            |
|               |                                                                                                                                                                   |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ding-young**
## Which issue does this PR close?

- Closes #15387

## What changes are included in this PR?

This pr adds a rule in ExprSimplifier to simplify x=x as follows.
- if x is not nullable, x=x -> true
- else, x=x -> x is NOT NULL

## Are these changes tested?
Yes, via unit test and slt

### CODE REVIEW

**Comment by 2010YOUY01** [comment]
This optimizer transformation doesn't look right for projected columns like
```
create table t1(v1 int);
insert into t1 values (null);

select v1=v1 from t1;
-- Should return `NULL`, but get `False`
```

However it makes sense if it is only applied on filter expressions.

**Comment by ding-young** [comment]
> This optimizer transformation doesn't look right for projected columns like
> 
> ```
> create table t1(v1 int);
> insert into t1 values (null);
> 
> select v1=v1 from t1;
> -- Should return `NULL`, but get `False`
> ```
> 
> However it makes sense if it is only applied on filter expressions.

Thank you for review. I'll make the change

**Comment by ding-young** [comment]
@2010YOUY01 Instead of applying transformation on filter expression, I adjusted the rule to transform x=x into `x IS NOT NULL OR NULL`. This preserves the behavior where NULL = NULL evaluates to NULL, which is treated as FALSE in filter expressions.

About the performance, I'm not 100% sure whether this rule worth the change, but I made this change because `IS NOT NULL OR NULL` was a bit better than actual comparision. 
image

**Comment by berkaysynnada** [comment]
> About the performance, I'm not 100% sure whether this rule worth the change, but I made this change because `IS NOT NULL OR NULL` was a bit better than actual comparision. 

I recommend writing a simple benchmark by criterion or other tools to get more reliable results instead of measuring the CLI execution

**Comment by alamb** [comment]
We could also use a CASE 
```sql
CASE x IS NOT NULL THEN true ELSE null END
```

**Comment by alamb** [comment]
I expect this to make a large performance difference when x is a string type (as string comparisons are fairly expensive)

Thank you for this PR @ding-young and the great reviews @2010YOUY01 and @berkaysynnada

**Comment by ding-young** [comment]
I wrote a simple criterion bench (https://github.com/ding-young/datafusion/blob/simplify-trivial-eq-bench/datafusion/core/benches/simplify_trivial_eq.rs) and the result is as follows. 
It showed performance improvement, especially for comparing long strings. 
```
select_f32_eq_f32       time:   [366.19 µs 366.42 µs 366.69 µs]
                        change: [-79.571% -79.180% -78.787%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
  2 (2.00%) high mild
  6 (6.00%) high severe

select_str_eq_str       time:   [372.53 µs 373.02 µs 373.61 µs]
                        change: [-85.333% -85.117% -84.884%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 10 outliers among 100 measurements (10.00%)
  4 (4.00%) high mild
  6 (6.00%) high severe

select_str_eq_str_long  time:   [372.49 µs 372.85 µs 373.25 µs]
                        change: [-98.351% -98.316% -98.280%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
  3 (3.00%) high mild
  6 (6.00%) high severe
```

Plus, since `x IS NOT NULL OR NULL` is slightly better than `CASE`, I'll leave the pr as is :)  
```
select_CASE_str_eq_str_long
                        time:   [396.36 µs 396.73 µs 397.15 µs]
Found 10 outliers among 100 measurements (10.00%)
  2 (2.00%) high mild
  8 (8.00%) high severe
```
Thanks for the review! Trying out the bench was also a great experience for me.

**Comment by berkaysynnada** [comment]
> I wrote a simple criterion bench (https://github.com/ding-young/datafusion/blob/simplify-trivial-eq-bench/datafusion/core/benches/simplify_trivial_eq.rs) and the result is as follows. It showed performance improvement, especially for comparing long strings.

Thank you for sharing the results. It doesn't effect much here but next time you can exclude the create_context() part out of bench_function :)

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs [hunk 1]
```diff
@@ -2152,6 +2169,17 @@ mod tests {
         }
     }
 
+    #[test]
+    fn test_simplify_eq_not_self() {
+        let expr_a = col("c2").eq(col("c2"));
+        let expr_b = col("c2_non_null").eq(col("c2_non_null"));
+        let expected_a = col("c2").is_not_null().or(lit_bool_null());
+        let expected_b = lit(true);
```
Comment (kosiew) [inline datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:2177]:
```suggestion
    // `expr_a`: column `c2` is nullable, so `c2 = c2` simplifies to `c2 IS NOT NULL OR NULL`
    // This ensures the expression is only true when `c2` is not NULL, accounting for SQL's NULL semantics.
    let expected_a = col("c2").is_not_null().or(lit_bool_null());

    // `expr_b`: column `c2_non_null` is explicitly non-nullable, so `c2_non_null = c2_non_null` is always true
    let expected_b = lit(true);
```

**Review by kosiew — COMMENTED** [review]
👍 👍 @ding-young 

Left a few suggestions.

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs (hunk 1 above)
Comment (ding-young) [reply datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs]: I updated the comments. Thank you :)

File: datafusion/sqllogictest/test_files/array.slt [hunk 2]
```diff
@@ -6140,21 +6140,19 @@ logical_plan
 02)--Aggregate: groupBy=[[]], aggr=[[count(Int64(1))]]
 03)----SubqueryAlias: test
 04)------SubqueryAlias: t
-05)--------Projection:
-06)----------Filter: __common_expr_3 = __common_expr_3
-07)------------Projection: substr(CAST(md5(CAST(tmp_table.value AS Utf8)) AS Utf8), Int64(1), Int64(32)) AS __common_expr_3
-08)--------------TableScan: tmp_table projection=[value]
+05)--------Projection:
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/array.slt:6143]: There is a comment a few lines above that says:

> # TODO: this should probably be possible to completely remove the filter as always true?

We can probably update that too -- but we could do it in a follow on PR as well

**Review by alamb — APPROVED** [review]
Thank you @ding-young  @kosiew @2010YOUY01 and @berkaysynnada  -- go team 🦾 !

File: datafusion/sqllogictest/test_files/array.slt [hunk 3]
```diff
@@ -6130,7 +6130,8 @@ select count(*) from test WHERE array_has([needle], needle);
 ----
 100000
 
-# TODO: this should probably be possible to completely remove the filter as always true?
+# The optimizer does not currently eliminate the filter; 
+# Instead, it's rewritten as `IS NULL OR NOT NULL` due to SQL null semantics
```
Comment (ding-young) [inline datafusion/sqllogictest/test_files/array.slt:6134]: I updated the comment in slt as well :)

**Comment by alamb** [comment]
Thanks again @ding-young 🙏
