### PR TITLE
fix: Fix various complaints from the latest nightly clippy

### LINKED ISSUE #11957: Latest nightly clippy complains about more things
### Describe the bug

Running `cargo clippy` with the latest nightly toolchain reports a few more warnings, due to (I assume) internal improvements in clippy that got merged recently.

### To Reproduce

1. `rustup update nightly`
2. `cargo +nightly clippy`

### Expected behavior

No warnings

### Additional context

All warnings can be fixed except for one, which complains about an issue stemming from the stabilization of `min_exhaustive_patterns`. This can't be fixed until 1.82 releases in a few months. We could add a lint to allow an unreachable pattern, plus a lint to ignore that lint if it's unrecognized (so people can keep using stable), but I don't feel like that's really necessary right now.

I'll file a PR to fix this.

### PR DESCRIPTION
**Pull request by itsjunetime**
## Which issue does this PR close?

Closes #11957 

## Rationale for this change

It's nice to keep ahead of future rust changes and make sure people can comfortably use this library on any toolchain.

## What changes are included in this PR?

- Fixed all issues reported by clippy (but 1, mentioned in the attached issue)
- Refactored the `make_error` macro that's used to make all the errors + variants to prevent code duplication and get rid of unnecessary `with_dollar_sign` macro

## Are these changes tested?
Yes, it passes all tests that main currently passes on my machine.

## Are there any user-facing changes?
This adds items to the public API, under `#[doc(hidden)]`. This is not a breaking change afaik, but would cause a breaking change if they were removed.

### CODE REVIEW

File: datafusion/functions/src/datetime/common.rs [hunk 1]
```diff
@@ -227,46 +229,34 @@ where
         // if the first argument is a scalar utf8 all arguments are expected to be scalar utf8
         ColumnarValue::Scalar(scalar) => match scalar {
             ScalarValue::Utf8(a) | ScalarValue::LargeUtf8(a) => {
-                let mut val: Option<Result<ColumnarValue>> = None;
-                let mut err: Option<DataFusionError> = None;
+                let a = a.as_ref();
+                // ASK: Why do we trust `a` to be non-null at this point?
```
Comment (alamb) [inline datafusion/functions/src/datetime/common.rs:233]: I don't think we do trust a to be non-null -- the current code on main has an explicitly `match` that handles `None` doesn't it? Maybe I am misreading the diff

```rust
                    None => (),
```

🤔 

However, clearly we don't have test coverage for this

File: datafusion/functions/src/datetime/common.rs [hunk 2]
```diff
@@ -227,46 +229,34 @@ where
...
+                            Err(e) => ret = Some(Err(e)),
                         }
                     }
-                    None => (),
                 }
 
-                if let Some(v) = val {
-                    v
-                } else {
-                    Err(err.unwrap())
```
Comment (alamb) [inline datafusion/functions/src/datetime/common.rs:268]: that is pretty strange -- I like your formulation `unwrap_or_internal_err` much better

File: datafusion/sql/src/parser.rs [hunk 3]
```diff
@@ -523,9 +523,7 @@ impl<'a> DFParser<'a> {
                 Ok(n) => Ok(Value::Number(n, l)),
                 // The tokenizer should have ensured `n` is an integer
                 // so this should not be possible
-                Err(e) => parser_err!(format!(
-                    "Unexpected error: could not parse '{n}' as number: {e}"
-                )),
+                Err(e) => match e {},
```
Comment (alamb) [inline datafusion/sql/src/parser.rs:526]: I don't understand this change -- doesn't `match e{}` just ignore `e`  where as before this would have returned an error?

File: datafusion/sql/src/unparser/plan.rs [hunk 4]
```diff
@@ -359,18 +359,14 @@ impl Unparser<'_> {
...
-                            Some(sort_expr) => {
-                                if let Some(query_ref) = query {
-                                    query_ref
-                                        .order_by(self.sort_to_sql(sort_expr.clone())?);
-                                } else {
-                                    return internal_err!(
-                                "Sort operator only valid in a statement context."
-                            );
-                                }
+                        if let Some(sort_expr) = &on.sort_expr {
```
Comment (alamb) [inline datafusion/sql/src/unparser/plan.rs:362]: Another way I have seen this written is

```suggestion
                        if let Some(sort_expr) = on.sort_expr.as_ref() {
```

File: datafusion/common/src/lib.rs [hunk 5]
```diff
@@ -73,6 +73,18 @@ pub use table_reference::{ResolvedTableReference, TableReference};
 pub use unnest::UnnestOptions;
 pub use utils::project_schema;
 
+// These are hidden from docs purely to avoid polluting the public view of what this crate exports.
```
[the remark this answers is not in the document]
Comment (alamb) [reply datafusion/common/src/lib.rs:76]: I double checked the docs locally:

Screenshot 2024-08-12 at 6 05 07 PM

**Review by alamb — COMMENTED** [review]
Thank you @itsjunetime  🙏 

This will also avoid the mad scramble we often do when a new rust release comes out and we have to make this sort of change to get CI running 

I had a few questions on changes in error handling that i think should be addressed, but otherwise this is looking almost ready to ship to me

Note for other reviewers: I found using whitespace blind diff for this change made it easier to see what changed: https://github.com/apache/datafusion/pull/11958/files?w=1

File: datafusion/common/src/error.rs [hunk 6]
```diff
@@ -501,37 +494,37 @@ macro_rules! with_dollar_sign {
...
+            /// Macro wraps Err(`$ERR`) to add backtrace feature
+            #[macro_export]
+            macro_rules! $NAME_ERR {
+                ($d($d args:expr),*) => {
+                    Err($crate::[<_ $NAME_DF_ERR>]!($d($d args),*))
                 }
             }
+
+            #[doc(hidden)]
+            #[allow(unused)]
```
[the remark this answers is not in the document]
Comment (itsjunetime) [reply datafusion/common/src/error.rs:523]: rust-analyzer still analyzes macro output and will complain if they generate unused typealiases. Previously we got around that by explicitly adding something like `pub use err as _err` only where needed, but this makes those identifiers for all errors, (to make it easier to use in the future), but some of them aren't currently used in the codebase. So those typealiases are technically unused, but that's fine because they're just there for if we need them inside the crate.

File: datafusion/functions/src/datetime/common.rs (hunk 1 above)
Comment (itsjunetime) [reply datafusion/functions/src/datetime/common.rs:233]: Previously, in this code path, if `a` was None, then the `err` that we unwrap later down in that same block would also be None, causing a more confusing error. So since we're comfortable unwrapping the err later on, we must be confident `a` is `Some(_)`.

File: datafusion/functions/src/datetime/common.rs (hunk 2 above)
Comment (itsjunetime) [reply datafusion/functions/src/datetime/common.rs:268]: Yeah, I feel like this is explicitly the thing that enums allow us to avoid

File: datafusion/sql/src/parser.rs (hunk 3 above)
Comment (itsjunetime) [reply datafusion/sql/src/parser.rs:526]: `e` is `Infallible`, so it can't be constructed. Since it can't be constructed, this code path is unreachable, and that's what this proves. a match with no arms has a return type of `!` since it can't ever be executed, so it can be implicitly converted to any type, and can prove that a `Result` cannot be its `Err` variant.

File: datafusion/sql/src/unparser/plan.rs (hunk 4 above)
Comment (itsjunetime) [reply datafusion/sql/src/unparser/plan.rs:362]: Ah, yeah - this change was made by `cargo clippy --fix` so I just went with it. I don't really have any preference for which it should be.

Comment (alamb) [reply datafusion/sql/src/unparser/plan.rs:362]: this is fine too.

File: datafusion/sql/src/parser.rs (hunk 3 above)
Comment (alamb) [reply datafusion/sql/src/parser.rs:526]: I think we can avoid this error handling entirely by not trying to parse a String in the first place. I'll make a follow on PR

**Review by alamb — APPROVED** [review]
Thank you @itsjunetime  -- I think this is better than main 🙏 

I have some ideas on how to simplify the code further, and I'll make another PR with some proposals

File: datafusion/common/src/error.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (alamb) [reply datafusion/common/src/error.rs:523]: This makes sense -- I will add your reasoning as a comment in a follow on PR

**Comment by alamb** [comment]
Follow on PR in https://github.com/apache/datafusion/pull/11965
