### PR TITLE
fix: unparse join without projection

### LINKED ISSUE #15688: Unparse of Joins is ignoring projections
### Describe the bug

The unparse of Join operators is ignoring the projected columns, ending up projecting everything.

Two conditions cause this to happen:
- the final projected columns match the columns in the `TableScans`, meaning the `Projection` is optimized away with the `optimize_projections` rule;
- the `try_transform_to_simple_table_scan_with_filters` function in the `unparser` module -- used when processing joins -- causes the `TableScan` projection to be discarded.

I could try to fix this by modifying the join unparser, but I would like to be sure that this is the best approach here.

### To Reproduce

```rust
use datafusion::error::Result;
use datafusion::prelude::SessionContext;
use datafusion::sql::unparser::Unparser;
use datafusion::sql::unparser::dialect::PostgreSqlDialect;

#[tokio::main]
async fn main() -> Result<()> {
    let ctx = SessionContext::new();

    ctx.sql("create table test (k int, v int)")
        .await?
        .collect()
        .await?;

    let df = ctx.sql("select t1.v, t2.v from test t1, test t2").await?;

    println!("{}\n", df.logical_plan());

    let plan = df.into_optimized_plan()?;
    println!("{}\n", plan);

    println!(
        "{}",
        Unparser::new(&PostgreSqlDialect {})
            .plan_to_sql(&plan)
            .unwrap()
    );

    Ok(())
}
```

```
Projection: t1.v, t2.v
  Cross Join: 
    SubqueryAlias: t1
      TableScan: test
    SubqueryAlias: t2
      TableScan: test

Cross Join:
  SubqueryAlias: t1
    TableScan: test projection=[v]
  SubqueryAlias: t2
    TableScan: test projection=[v]

SELECT * FROM "test" AS "t1" CROSS JOIN "test" AS "t2"
```

### Expected behavior

Output the query with the projected fields:
```
SELECT "t1".v, "t2".v FROM "test" AS "t1" CROSS JOIN "test" AS "t2"
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chenkovsky**
## Which issue does this PR close?

- Closes #15688.

## Rationale for this change

There are two issues.

1. projection in scan table is dropped in try_transform_to_simple_table_scan_with_filters
2. projection in selectbuilder can only be setted once. it's ok if there's a projection plan outside, but for dataframe api or optimized logical plan. it's not always true. for join, we need to add selected expressions from left plan, and  selected expressions from right plan.

## What changes are included in this PR?

1. add projection in try_transform_to_simple_table_scan_with_filters
2. enable setting projection in selectbuilder twice for join logical plan.

## Are these changes tested?

UT

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/sql/src/unparser/plan.rs [hunk 1]
```diff
@@ -719,6 +737,14 @@ impl Unparser<'_> {
                         let mut from = select.pop_from().unwrap();
                         from.push_join(ast_join);
                         select.push_from(from);
+                        if !already_projected {
+                            let projection = left_projection
+                                .unwrap()
```
Comment (goldmedal) [inline datafusion/sql/src/unparser/plan.rs:742]:
```suggestion
                            let Some(left_projection) = left_projection else {
                                return internal_err!("Left projection is missing");
                            };
                            let projection = left_projection
```

File: datafusion/sql/src/unparser/plan.rs [hunk 2]
```diff
@@ -582,6 +582,7 @@ impl Unparser<'_> {
                     }
                     _ => (&join.left, &join.right),
                 };
+                let already_projected = select.already_projected();
```
Comment (goldmedal) [inline datafusion/sql/src/unparser/plan.rs:585]: Could you add a comment explaining why we get `already_projected` before the rewriting for left_plan?

**Review by goldmedal — APPROVED** [review]
Thanks @chenkovsky. The change and the testing look good to me. I only have some minor comments.

**Comment by goldmedal** [comment]
Thanks @chenkovsky
