### PR TITLE
Validate ScalarUDF output rows and fix nulls for `array_has` and `get_field` for `Map`

### LINKED ISSUE #5735: Check the udf output size which should be equal to the input size
Hmmm...or we should check the result size of udf? I'm not sure wether it's proper that the sizes of input and result could be different. cc @alamb @mingmwang @tustvold

_Originally posted by @doki23 in https://github.com/apache/arrow-datafusion/issues/5635#issuecomment-1475092781_

### PR DESCRIPTION
**Pull request by duongcongtoai**
## Which issue does this PR close?

Closes #5735.

Add a small constraint for each UDF to have the same input and output size, with "arrow_typeof" as an exception

2 implementation failed the constraint (also fixed inside this PR)
- array_has
- get_field

### CODE REVIEW

File: datafusion/physical-expr/src/scalar_function.rs [hunk 1]
```diff
@@ -177,7 +177,18 @@ impl PhysicalExpr for ScalarFunctionExpr {
                 let fun = create_physical_fun(fun)?;
                 (fun)(&inputs)
             }
-            ScalarFunctionDefinition::UDF(ref fun) => fun.invoke(&inputs),
+            ScalarFunctionDefinition::UDF(ref fun) => {
+                let output = fun.invoke(&inputs)?;
+                let output_count = match &output {
```
Comment (jayzhan211) [inline datafusion/physical-expr/src/scalar_function.rs:182]: https://github.com/apache/datafusion/blob/19356b26f515149f96f9b6296975a77ac7260149/datafusion/functions/src/utils.rs#L108

I think we should check it inside the function wrapper

**Comment by duongcongtoai** [comment]
udf arrow_typeof is violating this check, perhaps we have to make it into a udaf

File: datafusion/physical-expr/src/scalar_function.rs (hunk 1 above)
Comment (duongcongtoai) [reply datafusion/physical-expr/src/scalar_function.rs:182]: then anyone who implement ScalarUDFImpl trait and not using this util can miss this validation right?

Comment (duongcongtoai) [reply datafusion/physical-expr/src/scalar_function.rs:182]: for example this function: https://github.com/apache/datafusion/blob/b2cbc7809ee0656099169307a73aadff23ab1030/datafusion-examples/examples/advanced_udf.rs#L96

Comment (jayzhan211) [reply datafusion/physical-expr/src/scalar_function.rs:182]: > then anyone who implement ScalarUDFImpl trait and not using this util can miss this validation right?

True, but in another way, all the function is forced to check the length, even if it does not expect to. 🤔

Comment (duongcongtoai) [reply datafusion/physical-expr/src/scalar_function.rs:182]: i think the initial purpose of this validation is to announce users who define their own udf to follow this constraint (maybe they provide a wrong implementation, and our code just panic with ambiguous error, for example the error in the reported issue https://github.com/apache/datafusion/issues/5635

after adding this validation, i found one udf violating this rule which is arrow_typeof.
Can we consider this function a udaf, i need your opinion here @alamb

Comment (jayzhan211) [reply datafusion/physical-expr/src/scalar_function.rs:182]: @duongcongtoai 
The reason why `arrow_typeof` is failing is that it does not consider the input is array or scalar but always return `ColumnarValue::Scalar`.

Comment (jayzhan211) [reply datafusion/physical-expr/src/scalar_function.rs:182]: The reason `arrow_typeof` failed is because it returns `ColumnValue::Scalar(ScalarValue::UTF8("type name"))`, so if the input is list with number of rows 7, we get 1 (because of ColumnValue::Scalar) but expected 7 in this case.

Change `arrow_typeof` to UDAF is definitely not a good idea.
In this case, I think we can add `validate_length` method to `ScalarUDFImpl`, disable `arrow_typeof` to skip the check for this special case

Comment (jayzhan211) [reply datafusion/physical-expr/src/scalar_function.rs:182]: It also address my previous concern that all functions are not forced to check the length. By default it does, if any function does not expect to like `arrow_typeof`, it is allowed to skip the check

Comment (duongcongtoai) [reply datafusion/physical-expr/src/scalar_function.rs:182]: i wonder if i misunderstood the usage of the enum ColumnarValue::Scalar here. For example a input having 10 rows, and UDF return ColumnarValue::Scalar(somevalue), then this will be transformed into an output array with 10rows having the same value right?
Then i think this validation can only be applied if the output returned is of type ColumnarValue::Array wdyt?

Comment (duongcongtoai) [reply datafusion/physical-expr/src/scalar_function.rs:182]: ahah confirmed: https://github.com/apache/datafusion/blob/e642cc2a94f38518d765d25c8113523aedc29198/datafusion/expr/src/columnar_value.rs#L57

Comment (jayzhan211) [reply datafusion/physical-expr/src/scalar_function.rs]: > then this will be transformed into an output array with 10rows having the same value right

But `into_array` is not called, so the result of `arrow_typeof` remains to be ColumnarValue::Scalar not Array.

Comment (duongcongtoai) [reply datafusion/physical-expr/src/scalar_function.rs]:
```
 but into_array is not called after invoke(), so the result of arrow_typeof remains to be a single row value ColumnarValue::Scalar
```
which is fine to skip the validation right? because such transformation (scalar -> expected output) will be done some where else, depends on the plan, for example during [projection](https://github.com/apache/datafusion/blob/e642cc2a94f38518d765d25c8113523aedc29198/datafusion/physical-plan/src/projection.rs#L315)

Comment (duongcongtoai) [reply datafusion/physical-expr/src/scalar_function.rs]: > ColumnarValue::Scalar is used for single row

hmm, maybe this is the point i got confused, because the way i look at how this ColumnarValue work, this is not correct. e.g in projection stream above). How i understand is: ColumnarValue::Scalar looks like a single value represent (arbitrarily) a single shared value of n rows

Comment (jayzhan211) [reply datafusion/physical-expr/src/scalar_function.rs]: Skip the validation for `arrow_typeof ` is fine to me, but skip it for `ScalarValue` in general is not. I think most of the function expects scalar in scalar out, so we still need to check if the result is single row.

Comment (duongcongtoai) [reply datafusion/physical-expr/src/scalar_function.rs]: thank you for the review :D understood

**Comment by duongcongtoai** [comment]
```
External error: query failed: DataFusion error: Internal error: UDF returned a different number of rows than expected. Expected: 7, Got: 6.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
[SQL] select array_has(column1, make_array(5, 6)),
       array_has(column1, make_array(7, NULL)),
       array_has(column2, 5.5),
       array_has(column3, 'o')
from arrays;
at test_files/array.slt:5161
```

File: datafusion/sqllogictest/test_files/array.slt [hunk 2]
```diff
@@ -5169,8 +5169,9 @@ false false false true
 true false true false
 true false false true
 false true false false
-false false false false
-false false false false
```
Comment (duongcongtoai) [inline datafusion/sqllogictest/test_files/array.slt:5173]: The test result does not look correct, because it ignore some null rows in between

File: datafusion/functions-array/src/array_has.rs [hunk 3]
```diff
@@ -288,36 +288,40 @@ fn general_array_has_dispatch<O: OffsetSizeTrait>(
...
+                };
+
+                if comparison_type == ComparisonType::Any {
+                    res |= res;
+                }
+                boolean_builder.append_value(res);
+            }
+            // respect null input
+            (_, _) => {
+                boolean_builder.append_null();
```
Comment (jayzhan211) [inline datafusion/functions-array/src/array_has.rs:323]: 👍

File: datafusion/sqllogictest/test_files/map.slt [hunk 4]
```diff
@@ -44,6 +44,7 @@ DELETE 24
 query T
 SELECT strings['not_found'] FROM data LIMIT 1;
 ----
+NULL
```
Comment (jayzhan211) [inline datafusion/sqllogictest/test_files/map.slt:47]: I'm not familiar with Map. Why should we returns null here?

Comment (duongcongtoai) [reply datafusion/sqllogictest/test_files/map.slt:47]: It will throws the invalidation error i added in this PR. I think the correct behavior is to return null for every input rows. I took a look at duckdb and spark's behavior

```
import org.apache.spark.sql.functions._
import org.apache.spark.sql.SparkSession

val spark = SparkSession.builder().appName("Spark SQL Map Example").getOrCreate()
import spark.implicits._

val data = Seq(
  ("Alice", Map("age" -> "25", "email" -> "alice@example.com")),
  ("Bob", Map("age" -> "30", "email" -> "bob@example.com")),
  ("Carol", Map("age" -> "35", "email" -> "carol@example.com"))
)
val df = data.toDF("name", "attributes")
val result = df.select($"name", $"attributes.email".as("email"),$"attributes.notfound".as("should_be_null"))
// Show the DataFrame
result.show(false)

+-----+-----------------+--------------+
|name |email            |should_be_null|
+-----+-----------------+--------------+
|Alice|alice@example.com|NULL          |
|Bob  |bob@example.com  |NULL          |
|Carol|carol@example.com|NULL          |
+-----+-----------------+--------------+
```

And also, a similar implementation in Datafusion is array_element also return null if the index goes out of range

File: datafusion/functions/src/core/getfield.rs [hunk 5]
```diff
@@ -107,29 +109,55 @@ impl ScalarUDFImpl for GetFieldFunc {
                 );
             }
         };
+
         match (array.data_type(), name) {
-                (DataType::Map(_, _), ScalarValue::Utf8(Some(k))) => {
-                    let map_array = as_map_array(array.as_ref())?;
-                    let key_scalar = Scalar::new(StringArray::from(vec![k.clone()]));
-                    let keys = arrow::compute::kernels::cmp::eq(&key_scalar, map_array.keys())?;
-                    let entries = arrow::compute::filter(map_array.entries(), &keys)?;
```
Comment (duongcongtoai) [inline datafusion/functions/src/core/getfield.rs:115]: using filter will reduce the number of input rows to the number of rows that have keys matching the input key. But we want to respect the number of input rows, and give null for any rows not having the matching key

File: datafusion/physical-expr/src/scalar_function.rs (hunk 1 above)
Comment (duongcongtoai) [reply datafusion/physical-expr/src/scalar_function.rs]: Btw I also tested with Spark and Duckdb for their version of "typeof"
Duckdb
```
toai@ToaiPC:~/proj/rust/arrow-datafusion/datafusion/core/tests/data$ duckdb 
v0.10.2 1601d94f94
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select typeof(ints) from parquet_map.parquet
  ;
┌──────────────────────┐
│     typeof(ints)     │
│       varchar        │
├──────────────────────┤
│ MAP(VARCHAR, BIGINT) │
│ MAP(VARCHAR, BIGINT) │
│ MAP(VARCHAR, BIGINT) │
│ MAP(VARCHAR, BIGINT) │
│ MAP(VARCHAR, BIGINT) │
│ MAP(VARCHAR, BIGINT) │
```
and Spark
```
val data = Seq(
  ("Alice", Map("age" -> "25", "email" -> "alice@example.com")),
  ("Bob", Map("age" -> "30", "email" -> "bob@example.com")),
  ("Carol", Map("age" -> "35", "email" -> "carol@example.com"))
)
val df = data.toDF("name", "attributes")
val types = df.select($"name", typeof($"name").as("name_type"), $"attributes", typeof($"attributes").as("attributes_type"))
types.show(false)
+-----+---------+---------------------------------------+------------------+
|name |name_type|attributes                             |attributes_type   |
+-----+---------+---------------------------------------+------------------+
|Alice|string   |{age -> 25, email -> alice@example.com}|map<string,string>|
|Bob  |string   |{age -> 30, email -> bob@example.com}  |map<string,string>|
|Carol|string   |{age -> 35, email -> carol@example.com}|map<string,string>|
+-----+---------+---------------------------------------+------------------+
```
Look like they also respect number of input row

Comment (duongcongtoai) [reply datafusion/physical-expr/src/scalar_function.rs]: oh actually current arrow_typeof also respect this behavior (added extra test case in arrow_typeof.slt)
```
query T
select arrow_typeof(col) from (select 1 as col union select 2 as col) as table_a;
----
Int64
Int64
```
=> So in this case ArrowTypeOfFunc always return a Scalar
```
        Ok(ColumnarValue::Scalar(ScalarValue::from(format!(
            "{input_data_type}"
        ))))
```
but the rendered record batch shows n rows anyway, does it mean wrong implementation with correct result?

File: datafusion/physical-expr/src/scalar_function.rs [hunk 6]
```diff
@@ -160,7 +160,22 @@ impl PhysicalExpr for ScalarFunctionExpr {
 
         // evaluate the function
         match self.fun {
-            ScalarFunctionDefinition::UDF(ref fun) => fun.invoke(&inputs),
+            ScalarFunctionDefinition::UDF(ref fun) => {
+                let output = fun.invoke(&inputs)?;
+                // Only arrow_typeof can bypass this rule
+                if fun.name() != "arrow_typeof" {
```
[the remark this answers is not in the document]
Comment (duongcongtoai) [reply datafusion/physical-expr/src/scalar_function.rs]: i added to the trait and the wrapper

**Review by jayzhan211 — APPROVED** [review]
👍

File: datafusion/physical-expr/src/scalar_function.rs [hunk 7]
```diff
@@ -146,11 +146,22 @@ impl PhysicalExpr for ScalarFunctionExpr {
...
-                    fun.invoke(&inputs)
+                let output = match self.args.is_empty() {
+                    true => fun.invoke_no_args(batch.num_rows()),
+                    false => fun.invoke(&inputs),
+                }?;
+
+                if fun.validate_number_of_rows() {
+                    let output_size = match &output {
+                        ColumnarValue::Array(array) => array.len(),
+                        ColumnarValue::Scalar(_) => 1,
```
Comment (alamb) [inline datafusion/physical-expr/src/scalar_function.rs:157]: I don't think this logic is correct -- specifically `ColumnarValue::Scalar` represents (logically) a single value for all the rows.

Thus I think if the function returns `ColumnarValue::Scalar` that implicitly can be any number of rows. 

Therefore I think the check could be something like 
```rust
if let ColumnarValue::Array(array) = &output {
  if output_size != array.len() {
    return internal_err...
  }
}
```

I'll try and make a PR to improve the documentation on ColumnarValue to make this clearer: https://docs.rs/datafusion/latest/datafusion/logical_expr/enum.ColumnarValue.html

File: datafusion/functions/src/core/arrowtypeof.rs [hunk 8]
```diff
@@ -69,4 +69,8 @@ impl ScalarUDFImpl for ArrowTypeOfFunc {
             "{input_data_type}"
         ))))
     }
+
+    fn validate_number_of_rows(&self) -> bool {
```
Comment (alamb) [inline datafusion/functions/src/core/arrowtypeof.rs:73]: I don't think this is correct -- arrow_typeof always returns the same number of rows as its input...

File: datafusion/functions/src/core/getfield.rs (hunk 5 above)
Comment (alamb) [reply datafusion/functions/src/core/getfield.rs:115]: I don't understand this

If the input is like this (two rows, each three elements)
```
{ a: 1, b: 2, c: 100}
{ a: 3, b: 4, c: 200}
```

An expression like `col['c']` will still return 2 rows (but each row will have only a single element)

```
{ c: 100 }
{ c: 200 }
```

**Review by alamb — CHANGES_REQUESTED** [review]
Thank you for the work here @duongcongtoai  and @jayzhan211  . I don't think this PR handles scalar values correctly -- I left some comments explaining why. Let me know what you think

File: datafusion/physical-expr/src/scalar_function.rs (hunk 7 above)
Comment (duongcongtoai) [reply datafusion/physical-expr/src/scalar_function.rs:157]: ah yes, so we don't need to check the length if the output is a scalar value, we actually had a discussion here: https://github.com/apache/datafusion/pull/10148#discussion_r1573629188

File: datafusion/functions/src/core/arrowtypeof.rs (hunk 8 above)
Comment (duongcongtoai) [reply datafusion/functions/src/core/arrowtypeof.rs:73]: then i think this new method is no longer needed

File: datafusion/functions/src/core/getfield.rs (hunk 5 above)
Comment (duongcongtoai) [reply datafusion/functions/src/core/getfield.rs:115]: **Previous implememtation**

map_array.entries() has type of
```
pub struct StructArray {
    len: usize,
    data_type: DataType,
    nulls: Option<NullBuffer>,
    fields: Vec<ArrayRef>,
}
```
With the example above, the layout of "field" will be a vector of 2 array, where first array is a list of key, and second array is a list of value
```
[0]: ["a","b","c","a","b",c"]
[1]: [1,2,100,3,4,200]
```
```
                    let keys = arrow::compute::kernels::cmp::eq(&key_scalar, map_array.keys())?;
```
with this computation, the result is a boolean aray where "key" = "c"
```
[false,false,true,false,false,true]
```
 and thus this operation will reduce the number of rows into
```
                    let entries = arrow::compute::filter(map_array.entries(), &keys)?;
```
```
[0]: ["c,"c"]
[1]: [100,200]
```

**Problem**

However, let's add a row where the map does not have key "c" in between
```
{ a: 1, b: 2, c: 100}
{ a: 1, b: 2}
{ a: 3, b: 4, c: 200}
```
map_array.entries() underneath is represented as
```
[0]: ["a,"b","c","a","b","a","b","c"]
[1]: [1,2,100,1,2,3,4,200]

                    let entries = arrow::compute::filter(map_array.entries(), &keys)?;
Now rows after filtered will be
[0]: ["c","c"]
[1]: [100,200]
```
and the return result will be 
```
{ c: 100 }
{ c: 200 }
```
instead of
```
{ c: 100 }
null
{ c: 200 }
```

File: datafusion/physical-expr/src/scalar_function.rs (hunk 7 above)
Comment (alamb) [reply datafusion/physical-expr/src/scalar_function.rs:157]: Here is a PR to improve the docs https://github.com/apache/datafusion/pull/10265

Comment (duongcongtoai) [reply datafusion/physical-expr/src/scalar_function.rs:157]: oh then perhaps the current implementation of arrow_typeof can be wrong, if we have a map like this:
```
{id:1,name:"bob"}
{id:"string_id",name:"alice"}
```

File: datafusion/functions/src/core/getfield.rs (hunk 5 above)
Comment (alamb) [reply datafusion/functions/src/core/getfield.rs:115]: I would expect the result of evaluating `col[b]` on

```
{ a: 1, b: 2, c: 100}
{ a: 1, b: 2}
{ a: 3, b: 4, c: 200}
```

to be:
```
{ c: 100 }
null
{ c: 200 }
```

For example, in duckdb:

```sql
D create table foo as values (MAP {'a':1, 'b':2, 'c':100}), (MAP{ 'a':1, 'b':2}), (MAP {'a':1, 'b':2, 'c':200});
D select * from foo;
┌───────────────────────┐
│         col0          │
│ map(varchar, integer) │
├───────────────────────┤
│ {a=1, b=2, c=100}     │
│ {a=1, b=2}            │
│ {a=1, b=2, c=200}     │
└───────────────────────┘
D select col0['c'] from foo;
┌───────────┐
│ col0['c'] │
│  int32[]  │
├───────────┤
│ [100]     │
│ []        │
│ [200]     │
└───────────┘
```

Basically a scalar function has the invarant that each input row produces exactly 1 output row

Comment (duongcongtoai) [reply datafusion/functions/src/core/getfield.rs:115]: yes, the previous implementation will not return null (according to slt https://github.com/apache/datafusion/pull/10148/files#diff-4db02ec06ada20062cbb518eeb713c2643f5a51e89774bdadd9966410baa7d1dR47)

Comment (duongcongtoai) [reply datafusion/functions/src/core/getfield.rs:115]: i also explained in this discussion: https://github.com/apache/datafusion/pull/10148#discussion_r1580329368

File: datafusion/physical-expr/src/scalar_function.rs (hunk 7 above)
Comment (jayzhan211) [reply datafusion/physical-expr/src/scalar_function.rs]: I see. I agree that we can check with Array only.

Comment (jayzhan211) [reply datafusion/physical-expr/src/scalar_function.rs]: why is map key allowed to have different types

Comment (duongcongtoai) [reply datafusion/physical-expr/src/scalar_function.rs]: Aha i 'v read duckdb's map definition again
```
A dictionary of multiple named values, each key having the same type and each value having the same type. Keys and values can be any type and can be different types from one another
```
I am new to this kind of project, but i think we don't have and should not have that use case 🤔. Else it will affect alot of execution logic

Comment (jayzhan211) [reply datafusion/physical-expr/src/scalar_function.rs]: In Duckdb, map keys can be **different value** for each row, but the types should not be different.
In OLAP which has the columnar format (we use arrow), it does not make sense to have different types on different rows.

Comment (jayzhan211) [reply datafusion/physical-expr/src/scalar_function.rs]: > MAPs must have a single type for all keys, and a single type for all values

**Comment by duongcongtoai** [comment]
Requested change made, please help me check again @alamb

File: datafusion/physical-expr/src/scalar_function.rs (hunk 7 above)
Comment (duongcongtoai) [reply datafusion/physical-expr/src/scalar_function.rs]: :+1:

File: datafusion/sqllogictest/test_files/map.slt [hunk 9]
```diff
@@ -44,6 +44,7 @@ DELETE 24
 query T
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/map.slt:44]: I had to remind myself what this data looked like. Here it is for anyone else who may be interested

```sql
DataFusion CLI v37.1.0
> select * from 'datafusion/core/tests/data/parquet_map.parquet';
+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+
| ints           | strings                                                                                                                                                                                               | timestamp            |
+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+
| {bytes: 38906} | {host: 198.194.132.41, method: GET, protocol: HTTP/1.0, referer: https://some.com/this/endpoint/prints/money, request: /observability/metrics/production, status: 400, user-identifier: shaneIxD}     | 06/Oct/2023:17:53:45 |
| {bytes: 44606} | {host: 140.115.224.194, method: PATCH, protocol: HTTP/1.0, referer: https://we.org/user/booperbot124, request: /booper/bopper/mooper/mopper, status: 304, user-identifier: jesseddy}                  | 06/Oct/2023:17:53:45 |
| {bytes: 23517} | {host: 63.69.43.67, method: GET, protocol: HTTP/2.0, referer: https://random.net/booper/bopper/mooper/mopper, request: /booper/bopper/mooper/mopper, status: 550, user-identifier: jesseddy}          | 06/Oct/2023:17:53:45 |
| {bytes: 44876} | {host: 69.4.253.156, method: PATCH, protocol: HTTP/1.1, referer: https://some.net/booper/bopper/mooper/mopper, request: /user/booperbot124, status: 403, user-identifier: Karimmove}                  | 06/Oct/2023:17:53:45 |
| {bytes: 34122} | {host: 239.152.196.123, method: DELETE, protocol: HTTP/2.0, referer: https://for.com/observability/metrics/production, request: /apps/deploy, status: 403, user-identifier: meln1ks}                  | 06/Oct/2023:17:53:45 |
| {bytes: 37438} | {host: 95.243.186.123, method: DELETE, protocol: HTTP/1.1, referer: https://make.de/wp-admin, request: /wp-admin, status: 550, user-identifier: Karimmove}                                            | 06/Oct/2023:17:53:45 |
| {bytes: 45784} | {host: 66.142.251.66, method: PUT, protocol: HTTP/2.0, referer: https://some.org/apps/deploy, request: /secret-info/open-sesame, status: 403, user-identifier: benefritz}                             | 06/Oct/2023:17:53:45 |
| {bytes: 27788} | {host: 157.85.140.215, method: GET, protocol: HTTP/1.1, referer: https://random.de/booper/bopper/mooper/mopper, request: /booper/bopper/mooper/mopper, status: 401, user-identifier: devankoshal}     | 06/Oct/2023:17:53:45 |
| {bytes: 5344}  | {host: 62.191.179.3, method: POST, protocol: HTTP/1.0, referer: https://random.org/booper/bopper/mooper/mopper, request: /observability/metrics/production, status: 400, user-identifier: jesseddy}   | 06/Oct/2023:17:53:45 |
| {bytes: 9136}  | {host: 237.213.221.20, method: PUT, protocol: HTTP/2.0, referer: https://some.us/this/endpoint/prints/money, request: /observability/metrics/production, status: 304, user-identifier: ahmadajmi}     | 06/Oct/2023:17:53:46 |
| {bytes: 5640}  | {host: 38.148.115.2, method: GET, protocol: HTTP/1.0, referer: https://for.net/apps/deploy, request: /do-not-access/needs-work, status: 301, user-identifier: benefritz}                              | 06/Oct/2023:17:53:46 |
...
```

File: datafusion/sqllogictest/test_files/map.slt (hunk 4 above)
Comment (alamb) [reply datafusion/sqllogictest/test_files/map.slt:47]: Here is how it works on main:

```sql
> select strings['not_found'] from 'datafusion/core/tests/data/parquet_map.parquet';
0 row(s) fetched.
Elapsed 0.006 seconds.

```

Here is how it works on this PR (aka has a single row for each input row) 
```sql
DataFusion CLI v37.1.0
> select strings['not_found'] from '../datafusion/core/tests/data/parquet_map.parquet';
+----------------------------------------------------------------------+
| ../datafusion/core/tests/data/parquet_map.parquet.strings[not_found] |
+----------------------------------------------------------------------+
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
|                                                                      |
| .                                                                    |
| .                                                                    |
| .                                                                    |
+----------------------------------------------------------------------+
209 row(s) fetched. (First 40 displayed. Use --maxrows to adjust)
Elapsed 0.033 seconds.
```
