### PR TITLE
bug: Eliminate dead round-robin insertion in enforce distribution

### LINKED ISSUE #19131: Delete Unneecessary Round-Robin Condition in Repartitioning
### Describe the bug

When a parent operator requires a hash partitioning in `EnforceDistribution` rule, there exists a conition that theoretically should add round-robin partitioning. The conditions for this are:

If the parent operator requires hash partitioning
- If hash repartitioning is not necessary (we are not already correctly hashed) and we want to add a round-robin => add a round-robin repartition on top
- If hash is necessary (we do not meet the hash requirements) => add a hash repartition on top

[link to code](https://github.com/apache/datafusion/blob/6746007826ebd3fcb5614bf87183674435bbb134/datafusion/physical-optimizer/src/enforce_distribution.rs#L1279)

This logic is incorrect as if the parent requires hash repartitioning and we are already hash partitioned, we should never round-robin repartition as this would break our hash partitioning.

This logic is proved to be incorrect as Datafusion actually never evaluates the first condition as true.

### To Reproduce

Run all sqllogictests and benchmarks with this condition. 

Delete it, and run them all again. No plans will change (it's dead code)

### Expected behavior

The correct logic should be

If the parent operator requires hash partitioning
- If we are already hashed correctly, don't do anything. If we insert a round-robin we will break out partitioning
- If we a hash is required, just insert a hash repartition

### Additional context

I actually created this dead code in issue #18341 to avoid consecutive repartitions, but glanced over the fact that this round-robin should never be happening (and the change makes it so that it doesn't) in the first place

### PR DESCRIPTION
**Pull request by gene-bordegaray**
## Which issue does this PR close?

- Closes #19131.

## Rationale for this change

Eliminates dead code that was not used in the enforce distribution rule.

In the branch where a parent requires hash repartitioning, there was a condition that would "add" a round robin if hash was not necessary (already hashed correctly) and the add round-robin flag was marked as true. This condition would never evaluate to true because anytime a parent requires hash repartitioning, we cannot round-robin because it would break the hash partitioning. 

## What changes are included in this PR?

A condition is deleted. No tests or plans were changed since this was dead code.

## Are these changes tested?

Yes, all tests (unit and sqllogictests) still pass.

There is no new tests to add.

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/physical-optimizer/src/enforce_distribution.rs [hunk 1]
```diff
@@ -1276,11 +1276,6 @@ pub fn ensure_distribution(
                 }
                 Distribution::HashPartitioned(exprs) => {
                     // See https://github.com/apache/datafusion/issues/18341#issuecomment-3503238325 for background
```
Comment (alamb) [inline datafusion/physical-optimizer/src/enforce_distribution.rs:1276]: Should we remove this comment too?

**Review by alamb — APPROVED** [review]
Looks good to me -- thanks @gene-bordegaray

File: datafusion/physical-optimizer/src/enforce_distribution.rs (hunk 1 above)
Comment (gene-bordegaray) [reply datafusion/physical-optimizer/src/enforce_distribution.rs:1276]: I think I will update this documentation to be accurate. I think it is still useful for people who want to dive into this part of the codebase
