### PR TITLE
Fix type coercion for unsigned and signed integers (`Int64` vs `UInt64`, etc)

### LINKED ISSUE #15340: type coercion for arthmetic/binary ops fails for some unsigned/signed mappings
### Describe the bug

The type coercion in the [mathematics_numerical_coercion](https://github.com/apache/datafusion/blob/main/datafusion/expr-common/src/type_coercion/binary.rs#L1014) function are too simple and do not properly handle mappings. However, the [binary_numeric_coercion](https://github.com/apache/datafusion/blob/main/datafusion/expr-common/src/type_coercion/binary.rs#L826) function does have the correct coercion rules for numeric values.

### To Reproduce

You can see this with the tests:

```Rust
test_coercion_binary_rule!(
            DataType::Int32,
            DataType::UInt32,
            Operator::Plus,
            DataType::Int32
        );
```
That is incorrect. Proper expansion of i32 and u32 is i64, not i32. 

### Expected behavior

Proper numeric type conversion happens when unsigned numeric types are involved.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Omega359**
## Which issue does this PR close?

- Closes #15340

## Rationale for this change
Better handle type coercion when unsigned numerics are involved

## What changes are included in this PR?

code, extensive tests, existing test updates.

## Are these changes tested?

Yes

## Are there any user-facing changes?

Possibly. Some previous results from dataframe/sql queries may have had the incorrect type if one of the types that were coerced was an unsigned type.

### CODE REVIEW

File: datafusion/expr-common/src/type_coercion/binary.rs [hunk 1]
```diff
@@ -855,21 +855,14 @@ pub fn binary_numeric_coercion(
         (UInt64, _) | (_, UInt64) => Some(UInt64),
         (Int64, _)
         | (_, Int64)
-        | (UInt32, Int8)
-        | (Int8, UInt32)
-        | (UInt32, Int16)
-        | (Int16, UInt32)
-        | (UInt32, Int32)
-        | (Int32, UInt32) => Some(Int64),
```
Comment (berkaysynnada) [inline datafusion/expr-common/src/type_coercion/binary.rs:863]: (Int32, UInt32) goes to Int64

 Are you sure your example in the issue is valid?
 https://github.com/apache/datafusion/issues/15340#issue-2936593900

Comment (Omega359) [reply datafusion/expr-common/src/type_coercion/binary.rs:863]: Yes. It cannot go to Int32 because uInt32 has larger values than Int32. It cannot go to UInt32 because Int can go negative. The most appropriate option here is Int64 since that encloses all possible values for UInt32 and Int32.

Comment (berkaysynnada) [reply datafusion/expr-common/src/type_coercion/binary.rs:863]: I wanted to emphasize this removed line, as it seemed to me that it is already the same of your intention:
image

but I looked more and see:
1) binary_numeric_coercion(): as I can see, you only did a refactor. There is a logical change there?
2) mathematics_numerical_coercion(): which was the inaccurate part, and you are updating the code such that it has the same behavior with binary_numeric_coercion(). 

IIUC, instead of duplicating these huge match arm, can we unify them into 1 function?

File: datafusion/optimizer/tests/optimizer_integration.rs [hunk 2]
```diff
@@ -267,8 +267,8 @@ fn push_down_filter_groupby_expr_contains_alias() {
     let sql = "SELECT * FROM (SELECT (col_int32 + col_uint32) AS c, count(*) FROM test GROUP BY 1) where c > 3";
     let plan = test_sql(sql).unwrap();
     let expected = "Projection: test.col_int32 + test.col_uint32 AS c, count(Int64(1)) AS count(*)\
-    \n  Aggregate: groupBy=[[test.col_int32 + CAST(test.col_uint32 AS Int32)]], aggr=[[count(Int64(1))]]\
-    \n    Filter: test.col_int32 + CAST(test.col_uint32 AS Int32) > Int32(3)\
+    \n  Aggregate: groupBy=[[CAST(test.col_int32 AS Int64) + CAST(test.col_uint32 AS Int64)]], aggr=[[count(Int64(1))]]\
```
Comment (alamb) [inline datafusion/optimizer/tests/optimizer_integration.rs:270]: this might be slower-- as now the larger column type is used (so it needs to do a 64 bit comparison rather than 32 bit) 🤔

Comment (alamb) [reply datafusion/optimizer/tests/optimizer_integration.rs:270]: but it probably also doesn't lose precision

**Review by alamb — COMMENTED** [review]
Thanks @Omega359 

I think this PR nicely reduces code replication and does what is explained on https://github.com/apache/datafusion/issues/15340

However, I am struggling to understand the implications of this change to a user. Like for example, if we were going to add a note about this in the upgrade / release notes, what would it say? 

Or put another way, what problem is this PR solving (the ticket just describes what the code does as wrong but it doesn't say why) 🤔

**Comment by Omega359** [comment]
> However, I am struggling to understand the implications of this change to a user. Like for example, if we were going to add a note about this in the upgrade / release notes, what would it say?

An issue was fixed where type coercion between expressions using certain mathematical operations having unsigned / signed types could produce values with an incorrect type that is not large enough to encompass all the possible values for both types. For example, comparing an unsigned int32 with a signed int32 could result in values having int32 type (where it should be int64) and could result in "Can't cast .." error for any unsigned values larger than the maximum int32 value.

This change may result in expressions unexpectedly having a 'larger' output type than they would have had in previous releases.

> Or put another way, what problem is this PR solving (the ticket just describes what the code does as wrong but it doesn't say why) 🤔

```Rust
let df = df
            .select_columns(&[P_ID, IDENTITY_KEY_VALUE])?
            .with_column(
                IDENTITY_KEY_VALUE,
                cast(hex_to_u64.call(vec![col(IDENTITY_KEY_VALUE)]), DataType::UInt64),
            )?
            .with_column(PARTITION_COLUMN, col(IDENTITY_KEY_VALUE).rem(lit(64)))?;
```

That currently throws `
Cast error: Can't cast value 16858640775341098663 to type Int32`

Is it easy to work around? Yes. Should it happen? No.

File: datafusion/optimizer/tests/optimizer_integration.rs (hunk 2 above)
Comment (Omega359) [reply datafusion/optimizer/tests/optimizer_integration.rs:270]: Correctness > performance.

**Review by alamb — APPROVED** [review]
Thank you @Omega359 

This makes sense to me

I added a link to add a note in the release notes
- https://github.com/apache/datafusion/pull/15341/files

**Review by xudong963 — APPROVED** [review]
LGTM

**Comment by alamb** [comment]
Thanks @Omega359 @berkaysynnada and @xudong963
