### PR TITLE
fix: NaN semantics in GROUP BY

### LINKED ISSUE #16254: Inconsistency with count distinct on NaN values
### Describe the bug

I have this csv file:

```
a,b
x,NaN
x,NaN
x,NaN
```

With a simple select query, DF says there is only 1 distinct value for column b (which, I think is correct).

```
> select count(distinct b) from 'nan.csv';
+---------------------------+
| count(DISTINCT nan.csv.b) |
+---------------------------+
| 1                         |
+---------------------------+
```

However, in an aggregate query, DF says there are 3 distinct values:

```
> select a, count(distinct b) from 'nan.csv' group by 1 order by 1;
+---+---------------------------+
| a | count(DISTINCT nan.csv.b) |
+---+---------------------------+
| x | 3                         |
+---+---------------------------+
```

This behavior seems inconsistent. I would expect the aggregate query to also report that there is one distinct value (in Spark, the behavior is consistent between the two queries).

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chenkovsky**
## Which issue does this PR close?

- Closes #16254.

## Rationale for this change

NaN != NaN

## What changes are included in this PR?

Use arrow is_eq to test equality

## Are these changes tested?

UT

## Are there any user-facing changes?

No

### CODE REVIEW

**Review by andygrove — APPROVED** [review]
Thanks @chenkovsky!

File: datafusion/physical-plan/src/aggregates/group_values/multi_group_by/primitive.rs [hunk 1]
```diff
@@ -121,7 +122,7 @@ impl<T: ArrowPrimitiveType, const NULLABLE: bool> GroupColumn
                 // Otherwise, we need to check their values
             }
 
-            *equal_to_result = self.group_values[lhs_row] == array.value(rhs_row);
+            *equal_to_result = self.group_values[lhs_row].is_eq(array.value(rhs_row));
```
Comment (andygrove) [inline datafusion/physical-plan/src/aggregates/group_values/multi_group_by/primitive.rs:125]: The implementation of `is_eq` for floating point is `self.to_bits() == rhs.to_bits()`
