### PR TITLE
Fix: to_char Function Now Correctly Handles DATE Values in DataFusion

### LINKED ISSUE #14969: Bug: to_char Function Returns NULL for Valid DATE Values in DataFusion
### Describe the bug

The to_char function in DataFusion returns NULL when formatting valid DATE values

### To Reproduce

cargo run -p datafusion-cli -- -c "SELECT to_char(date_column, '%Y-%m-%d') FROM (VALUES (NULL), (DATE '2020-09-01')) AS t(date_column)"

```
+-----------------------------------------+
| to_char(t.date_column,Utf8("%Y-%m-%d")) |
+-----------------------------------------+
| NULL                                    |
| NULL                                    |
+-----------------------------------------+
```

### Expected behavior

```
+-----------------------------------------+
| to_char(t.date_column,Utf8("%Y-%m-%d")) |
+-----------------------------------------+
| NULL                                    |
| 2020-09-01                              |
+-----------------------------------------+
```

### Additional context

I discovered this bug while trying to add this slt test

```sql
SELECT to_char(date_column, '%Y-%m-%d')
FROM (VALUES 
    (DATE '2020-09-01'),
    (NULL)
) AS t(date_column);
```

### PR DESCRIPTION
**Pull request by kosiew**
## Which issue does this PR close?

- Closes #14969.

## Rationale for this change

After #14908, the `to_char` function was incorrectly returning `NULL` for valid `DATE` values due to improper handling of the `DATE` type. This fix ensures that `to_char` correctly formats non-null `DATE` values while preserving `NULL` values as expected.

This is a re-implementation of #14908

## What changes are included in this PR?

- Fixed the `to_char` function to properly process `DATE` values.
- Added slt test cases to verify correct behavior when formatting `DATE` values.

## Are these changes tested?

Yes, new test cases have been added to confirm that:
1. `to_char` correctly formats valid `DATE` values.
2. `NULL` values remain unaffected.

## Are there any user-facing changes?

No breaking changes. Users will now see correctly formatted `DATE` values when using `to_char`, instead of unexpected `NULL` results.

### CODE REVIEW

File: datafusion/functions/src/datetime/to_char.rs [hunk 1]
```diff
@@ -678,31 +669,4 @@ mod tests {
...
-        if let ColumnarValue::Array(result) = result {
-            let result = result.as_any().downcast_ref::<StringArray>().unwrap();
-            assert_eq!(result.len(), 2);
-            // The first element is valid, second is null.
-            assert!(!result.is_null(0));
-            assert!(result.is_null(1));
-        } else {
-            panic!("Expected an array value");
-        }
-    }
```
Comment (kosiew) [inline datafusion/functions/src/datetime/to_char.rs:707]: Removing this test which was added in #14908

File: datafusion/functions/src/datetime/to_char.rs [hunk 2]
```diff
@@ -212,14 +212,6 @@ fn _to_char_scalar(
...
     let array = expression.into_array(1)?;
 
-    // fix https://github.com/apache/datafusion/issues/14884
-    // If the input date/time is null, return a null Utf8 result.
-    if array.is_null(0) {
-        return Ok(match is_scalar_expression {
-            true => ColumnarValue::Scalar(ScalarValue::Utf8(None)),
-            false => ColumnarValue::Array(new_null_array(&Utf8, array.len())),
-        });
-    }
```
Comment (kosiew) [inline datafusion/functions/src/datetime/to_char.rs:222]: Undo #14908

File: datafusion/functions/src/datetime/to_char.rs [hunk 3]
```diff
@@ -260,13 +258,6 @@ fn _to_char_array(args: &[ColumnarValue]) -> Result<ColumnarValue> {
     let data_type = arrays[0].data_type();
 
     for idx in 0..arrays[0].len() {
-        // fix https://github.com/apache/datafusion/issues/14884
-        // If the date/time value is null, push None.
-        if arrays[0].is_null(idx) {
-            results.push(None);
-            continue;
-        }
-
```
Comment (kosiew) [inline datafusion/functions/src/datetime/to_char.rs:269]: undo #14908

File: datafusion/functions/src/datetime/to_char.rs [hunk 4]
```diff
@@ -234,15 +226,21 @@ fn _to_char_scalar(
     };
 
     let formatter = ArrayFormatter::try_new(array.as_ref(), &format_options)?;
-    let formatted: Result<Vec<_>, ArrowError> = (0..array.len())
-        .map(|i| formatter.value(i).try_to_string())
+    let formatted: Result<Vec<Option<String>>, ArrowError> = (0..array.len())
```
Comment (alamb) [inline datafusion/functions/src/datetime/to_char.rs:229]: 👍

**Comment by alamb** [comment]
Thanks again @kosiew

**Comment by kosiew** [comment]
Thank you @alamb for the review.
