### PR TITLE
fix query results for predicates referencing partition columns and data columns

### LINKED ISSUE #15912: Wrong query results for filters that involve partition columns and data file columns and `pushdown_filters` is enabled
### Describe the bug

Filters such as `partition_col = col_from_file` are never applied if `datafusion.execution.parquet.pushdown_filters = true`

### To Reproduce

With `datafusion-cli`:

```sql
COPY  (
  SELECT arrow_cast('a', 'Utf8') AS val
)  TO 'test_files/scratch/test/part=a/123.parquet'
STORED AS PARQUET;
COPY  (
  SELECT arrow_cast('b', 'Utf8') AS val
)  TO 'test_files/scratch/test/part=b/123.parquet'
STORED AS PARQUET;
COPY  (
  SELECT arrow_cast('xyz', 'Utf8') AS val
)  TO 'test_files/scratch/test/part=c/123.parquet'
STORED AS PARQUET;

set datafusion.execution.parquet.pushdown_filters = true;

CREATE EXTERNAL TABLE test(part text, val text)
STORED AS PARQUET
PARTITIONED BY (part)
LOCATION 'test_files/scratch/test/';

SELECT * FROM test;

explain analyze
select * from test
where part != val;
```

```
> select * from test
where part != val;
+-----+------+
| val | part |
+-----+------+
| a   | a    |
| xyz | c    |
| b   | b    |
+-----+------+
3 row(s) fetched. 
```

Which is clearly wrong.

### Expected behavior

```
> select * from test
where part != val;
+-----+------+
| val | part |
+-----+------+
| xyz | c    |
+-----+------+
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adriangb**
Fixes #15912

### CODE REVIEW

File: datafusion/datasource-parquet/src/row_filter.rs [hunk 1]
```diff
@@ -662,14 +660,11 @@ mod test {
...
             &file_schema,
-            &table_schema
         ));
     }
 
     #[test]
-    fn projected_columns_prevent_pushdown() {
-        let table_schema = get_basic_table_schema();
-
+    fn projected_or_partition_columns_prevent_pushdown() {
```
Comment (adriangb) [inline datafusion/datasource-parquet/src/row_filter.rs:667]: This test actually tests for this... except that since both schemas were being passed in it hit the bug as well.

**Comment by adriangb** [comment]
cc @alamb

File: datafusion/datasource-parquet/src/file_format.rs [hunk 2]
```diff
@@ -464,16 +464,16 @@ impl FileFormat for ParquetFormat {
     fn supports_filters_pushdown(
         &self,
         file_schema: &Schema,
-        table_schema: &Schema,
```
Comment (berkaysynnada) [inline datafusion/datasource-parquet/src/file_format.rs:467]: I'm a bit confused, as we talked like 
"_keep supports_filters_pushdown so that TableProviders can do Exact pruning of filters, e.g. using partition columns._",
 and that is making sense to me now. So, instead, should we pass only table_schema's to these `supports_filters_pushdown()` API's at ListingTable level? Theory and practice conflict in my mind now

**Review by berkaysynnada — APPROVED** [review]
Thanks for the fix @adriangb. It's LGTM, but I have one question

File: datafusion/datasource-parquet/src/file_format.rs (hunk 2 above)
Comment (adriangb) [reply datafusion/datasource-parquet/src/file_format.rs:467]: > instead, should we pass only table_schema's to these supports_filters_pushdown() API's at ListingTable level

We could! But we'd do that in https://github.com/apache/datafusion/pull/15769 right?

Comment (berkaysynnada) [reply datafusion/datasource-parquet/src/file_format.rs:467]: It doesn't change any API?
I mean can we remove `file_schema: &Schema` or `table_schema: &Schema`from these `supports_filters_pushdown()` API's? If we can, which one should we remove? In this PR, the fix shows that we utilize `file_schema: &Schema`, however, what I understand from that conversation is we should depend on `table_schema: &Schema`, not `file_schema: &Schema`. That's what confuses me

Comment (adriangb) [reply datafusion/datasource-parquet/src/file_format.rs:467]: Well keep only the table_schema. This fix (this PR) becomes irrelevant once we merge the other one. But since that may take longer I thought it was best to make this PR as a simpler fix.
