### PR TITLE
fix: Fix eq properties regression from #10434

### LINKED ISSUE #11362: Regression in eliminating monotonic sorts
### Describe the bug

After PR #10434, there is a slight regression in eliminating certain sorts during physical planning. In particular, consider the following case:
```
SortExec: [c ASC]
  FilterExec: b = 'A'
    CustomTableProviderExec: output_ordering=[a ASC, b ASC, c ASC], equal_conditions=[a=f(c)]
```

`f` is known to be monotonic in `c`. Hence we know that `[a ASC, c ASC]` is equivalent to `c ASC`. (See discussion in #9812.) 

We are unable to eliminate sorting in this case. This is because after PR #10434, adding constants to the eq properties does not leave them in a normalized state. This was not caught in tests, as the tests add constants _before_ adding equal conditions. 
In practice, however, physical plans like the one above add constants _after_ adding equal conditions. 

### To Reproduce

The simplest way to reproduce this behavior, short of implementing a custom table provider, is to modify [this existing test](https://github.com/apache/datafusion/blob/e65c3e919855c9977cf4d80c0630ee26b7fd03ee/datafusion/physical-expr/src/equivalence/properties.rs#L2382) to add constants _after_ adding the equal conditions. On the current version of `main` branch this will cause the test to fail. 

### Expected behavior

Equivalence properties should be the same regardless of what order the equal conditions, constants, etc. are added. (In particular the test should pass either way.)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by suremarc**
## Which issue does this PR close?

Closes #11362.

## Rationale for this change

This PR fixes a regression in #10434. The previous PR implements "discovery" of new orderings when equal conditions are added. However, this discovery process is not carried out when constants are added. 
As a result, adding equality conditions tends to leave the properties in a normalized state, but adding constants does _not_ leave the properties in a normalized state. Thus the order in which one constructs the properties matters. 

Since the existing test for this feature applied equal conditions _after_ adding constants, this path dependence was not caught. 

## What changes are included in this PR?

We extract out the "discovery" logic into a helper method, and we ensure it is called not only when adding equal conditions, but also when adding constants. 

## Are these changes tested?

Yes; we modify the test to construct the equivalence properties in different orders. 

## Are there any user-facing changes?

No, aside from improved physical plans in some cases

### CODE REVIEW

**Review by mustafasrepo — APPROVED** [review]
LGTM!. Thanks @suremarc for this PR. This is really nice.

File: datafusion/physical-expr/src/equivalence/properties.rs [hunk 1]
```diff
@@ -223,56 +223,11 @@ impl EquivalenceProperties {
...
-        }
-        if !new_orderings.is_empty() {
-            self.oeq_class.add_new_orderings(new_orderings);
-        }
-
         // Add equal expressions to the state
         self.eq_group.add_equal_conditions(left, right);
+
+        // Discover any new orderings
+        self.discover_new_orderings(left)?;
```
Comment (alamb) [inline datafusion/physical-expr/src/equivalence/properties.rs:230]: ❤️

File: datafusion/physical-expr/src/equivalence/properties.rs [hunk 2]
```diff
@@ -2454,30 +2478,49 @@ mod tests {
...
-            }
-
-            let sort = case
-                .sort_columns
-                .iter()
-                .map(|&name| {
-                    col(name, &schema).map(|col| PhysicalSortExpr {
-                        expr: col,
-                        options: SortOptions::default(),
+            // Construct the equivalence properties in different orders
```
Comment (alamb) [inline datafusion/physical-expr/src/equivalence/properties.rs:2481]: I also verified test coverage by running these tests without the code changes and verified they do in fact fail ✅ 

```

thread 'equivalence::properties::tests::test_eliminate_redundant_monotonic_sorts' panicked at datafusion/physical-expr/src/equivalence/properties.rs:2493:17:
assertion `left == right` failed: failed test '(a, b, c) -> (c)'
  left: false
 right: true
stack backtrace:
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:364:5
   4: datafusion_physical_expr::equivalence::properties::tests::test_eliminate_redundant_monotonic_sorts
             at ./src/equivalence/properties.rs:2493:17
   5: datafusion_physical_expr::equivalence::properties::tests::test_eliminate_redundant_monotonic_sorts::{{closure}}
             at ./src/equivalence/properties.rs:2382:54
   6: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: test failed, to rerun pass `--lib`
error: 1 target failed:
    `--lib`
```

**Review by alamb — COMMENTED** [review]
Thanks @suremarc  and @mustafasrepo
