### PR TITLE
Remove any aliases in `Filter::try_new` rather than erroring

### LINKED ISSUE #11306: "Filter predicates should not be aliased." seems too strict
### Describe the bug

Aliases are not allowed as filter predicates.

As per https://github.com/datafusion-contrib/datafusion-functions-json/pull/26#discussion_r1664566127 @alamb suggested we work around change of alias when substituting functions to replace operators by using `Expr::Alias`.

However when substituting `foo ? 'bar'` with a function wrapped in an alias, we get an error

```
Plan("Attempted to create Filter predicate with expression `json_contains(test.json_data, Utf8(\"foo\"))` aliased as 'json_data ? Utf8(\"foo\")'. Filter predicates should not be aliased.")
```

This is caused by

https://github.com/apache/datafusion/blob/08c5345e932f1c5c948751e0d06b1fd99e174efa/datafusion/expr/src/logical_plan/plan.rs#L2133-L2140

Ref #3796 & #3795

This seems unnecessarily strict.

The problem is that I when replacing the operator, you don't know what part of the query the operator is used in, so you can't decide whether or not to apply the alias AFAIK.

### To Reproduce

Add the following test to https://github.com/datafusion-contrib/datafusion-functions-json/pull/26

```

#[tokio::test]
async fn test_question_filter() {
    let batches = run_query("select name from test where json_data ? 'foo'")
        .await
        .unwrap();

    let expected = [
        "+------------+",
        "| name       |",
        "+------------+",
        "| object_foo |",
        "+------------+",
    ];
    assert_batches_eq!(expected, &batches);
}
```

### Expected behavior

I think aliases as predicates should be allowed.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by samuelcolvin**
## Which issue does this PR close?

fix #11306.

## Rationale for this change

See https://github.com/datafusion-contrib/datafusion-functions-json/pull/26 and #11306

## What changes are included in this PR?

Remove the block on aliases as prediates, add test.

## Are these changes tested?

Yes, the only way I could get a failure without this change.

## Are there any user-facing changes?

AFAIK, we just allow something that should be allowed.

**NOTE:** Aliases were already allowed in binary expressions, just not as full predicates, so this restriction seemed unusually strict. Also the SQL parser wouldn't allow me to build such an expression directly in SQL, e.g. `from x where (y = z) as the_alias` was invalid SQL.

### CODE REVIEW

File: datafusion/core/tests/user_defined/user_defined_sql_planner.rs [hunk 1]
```diff
@@ -86,3 +97,27 @@ async fn test_custom_operators_long_arrow() {
     ];
     assert_batches_eq!(&expected, &actual);
 }
+
+#[tokio::test]
+async fn test_question_sekect() {
```
Comment (alamb) [inline datafusion/core/tests/user_defined/user_defined_sql_planner.rs:102]: Is it a typo?
```suggestion
async fn test_question_select() {
```

Comment (alamb) [reply datafusion/core/tests/user_defined/user_defined_sql_planner.rs:102]: I verified this test fails like this without this PR's changes:

```
---- user_defined::user_defined_sql_planner::test_question_filter stdout ----
thread 'user_defined::user_defined_sql_planner::test_question_filter' panicked at datafusion/core/tests/user_defined/user_defined_sql_planner.rs:120:10:
called `Result::unwrap()` on an `Err` value: Plan("Attempted to create Filter predicate with expression `Boolean(true)` aliased as 'a ? Int64(2)'. Filter predicates should not be aliased.")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Review by alamb — COMMENTED** [review]
Thank you @samuelcolvin  

I think the original rationale as I remember for this check was to avoid optimizer passes creating ill formed plans.

I think @andygrove  added this check in #3796 and while we can remove it I think there are other options. 

You can't trigger this bug in the current sql implementation because it is not syntactically valid to do something like `SELECT ... FROM foo WHERE my_user_function(x) as nice_name`

However, the user defined planning doesn't have enough context to know if the expr is in the context of a select item (where aliases are allowed) or a filter clause (where aliases are not allowed)

Some other potential options:
1. Strip aliases in the sql planner where they don't make sense (as in if an extension planner returns an Alias in WHERE, just remove the alias before creating the filter)
2. Add another parameter to `plan_binary_op` that says if aliases are allowed or not (or maybe if it was in a SELECT list)

@andygrove , @jonahgao or @jackwener  I wonder if you have any thoughts / opinions?

**Comment by jonahgao** [comment]
I think aliases in a predicate will not affect functionality. They are just useless because they do not contribute to the output names of the filter plan, nor will any other expressions reference them.

If this is true, we can move the [unalias](https://github.com/apache/datafusion/blob/main/datafusion/expr/src/logical_plan/plan.rs#L662) logic to `Filter::try_new` and convert this check to a test.

**Comment by samuelcolvin** [comment]
I've updated this to un-alias the predicate.

I'm not sure if this was your suggestion, but I don't think it's necessarily to un-alias recursively within `Filter::try_new` — nested aliases were already accepted and are presumably elided by the optimiser already.

File: datafusion/expr/src/logical_plan/plan.rs [hunk 2]
```diff
@@ -2130,16 +2130,10 @@ impl Filter {
...
-            return plan_err!(
-                "Attempted to create Filter predicate with \
-                expression `{expr}` aliased as '{name}'. Filter predicates should not be \
-                aliased."
-            );
-        }
-
-        Ok(Self { predicate, input })
+        Ok(Self {
+            predicate: predicate.unalias(),
```
Comment (jonahgao) [inline datafusion/expr/src/logical_plan/plan.rs:2134]: After unalias, it might still be another alias, which doesn't seem very thorough.
Therefore, what do you think about executing `unalias_nested` during planning, like [this](https://github.com/jonahgao/datafusion/commit/7c924284553920004059717c1bac68d913cd6daf)?
This should be able to solve the current problem.

 As for whether we need to strictly strip aliases, perhaps we can discuss that separately.

Comment (samuelcolvin) [reply datafusion/expr/src/logical_plan/plan.rs:2134]: done.

File: datafusion/expr/src/logical_plan/plan.rs [hunk 3]
```diff
@@ -2130,16 +2130,10 @@ impl Filter {
...
-            return plan_err!(
-                "Attempted to create Filter predicate with \
-                expression `{expr}` aliased as '{name}'. Filter predicates should not be \
-                aliased."
-            );
-        }
-
-        Ok(Self { predicate, input })
+        Ok(Self {
+            predicate: predicate.unalias_nested().data,
```
Comment (jonahgao) [inline datafusion/expr/src/logical_plan/plan.rs:2134]: My thought is to execute `unalias_nested` when creating the initial logical plan. 

But the current implementation is also acceptable to me. Thank you @samuelcolvin .  If we follow the current implementation, we also need to remove the redundant `unalias_nested` calls outside of try_new.

cc @alamb

Comment (andygrove) [inline datafusion/expr/src/logical_plan/plan.rs:2134]: Unaliasing rather than throwing an exception here makes sense to me.

Comment (alamb) [reply datafusion/expr/src/logical_plan/plan.rs:2134]: Filed https://github.com/apache/datafusion/issues/11339 to track

**Review by alamb — APPROVED** [review]
Let's merge this PR and then address @jonahgao 's concerns / https://github.com/apache/datafusion/issues/11339 in a follow up

**Comment by alamb** [comment]
Thanks everyone

File: datafusion/expr/src/logical_plan/plan.rs [hunk 4]
```diff
@@ -2130,16 +2130,10 @@ impl Filter {
             }
         }
 
-        // filter predicates should not be aliased
-        if let Expr::Alias(Alias { expr, name, .. }) = predicate {
```
[the remark this answers is not in the document]
Comment (alamb) [reply datafusion/expr/src/logical_plan/plan.rs:2134]: I think it is a very old check and substantially predates `unalias_nested` so it may have become unaligned over time

File: datafusion/expr/src/logical_plan/plan.rs (hunk 3 above)
Comment (alamb) [reply datafusion/expr/src/logical_plan/plan.rs:2134]: PR to fix: https://github.com/apache/datafusion/pull/11340
