### PR TITLE
Fix bug in `nth_value` when `ignoreNulls` is true and no nulls in values

### LINKED ISSUE #14041: `ignoreNulls` in `nth_value` doesn't work when no nulls are in input
### Describe the bug

When the input values doesn't have any null setting `ignoreNulls` to true on `nth_value` window functions returns always `NULL`.

### To Reproduce

_No response_

### Expected behavior

When no nulls in tables, `nth_value` should return the same values wether `ignore_nulls` is true or false
```
statement ok
CREATE TABLE t AS VALUES  (3, 3), (4, 4), (5, 5), (6, 6);

query I
SELECT column1 FROM t ORDER BY column2;
----
3
4
5
6

query I
SELECT nth_VALUE(column1, 1) OVER(ORDER BY column2) FROM t;
----
3
3
3
3

query I
SELECT nth_VALUE(column1, 1) IGNORE NULLS OVER(ORDER BY column2) FROM t;
----
3
3
3
3

statement ok
DROP TABLE t;
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cht42**
## Which issue does this PR close?

Closes #14041.

### CODE REVIEW

**Review by jayzhan-synnada — APPROVED** [review]
👍

**Review by jayzhan211 — APPROVED** [review]
👍🏻

File: datafusion/functions-window/src/nth_value.rs [hunk 1]
```diff
@@ -360,9 +360,10 @@ impl PartitionEvaluator for NthValueEvaluator {
                     })
                     .unwrap_or_default();
                 if valid_indices.is_empty() {
-                    return ScalarValue::try_from(arr.data_type());
+                    None
```
Comment (Blizzara) [inline datafusion/functions-window/src/nth_value.rs:363]: took me a while to figure out what's happening here; maybe instead check slice.nulls() explicitly and return None if it doesn't exist (i.e. there's no nulls)?

also the pre-existing short-circuiting might be useful in cases where the nulls() index exists but valid_indices() truly is empty (i.e. the array is completely nulls)?

Comment (alamb) [reply datafusion/functions-window/src/nth_value.rs:363]: I filed https://github.com/apache/datafusion/issues/14063 to track the idea.  Thank you 🙏
