### PR TITLE
fix error result in execute&pre_selection

### LINKED ISSUE #16928: Incorrect results from pre_selection_scatter when RHS is scalar
### Describe the bug

When evaluating an AND expression, if fewer than 20% of the LHS values are true, the evaluator will use a "pre selection" strategy wherein we evaluate the right hand only for those rows where the left hand is true.

However, there is a bug in how scalars are handled for the right hand: 

https://github.com/apache/datafusion/blame/9deec2ad725813e266dc8c51ec75302fed7412f8/datafusion/physical-expr/src/expressions/binary.rs#L979-L982

For any scalar RHS we just return the scalar, which is not generally correct.

For example, in the expession (`x = 5 AND true`) evaluated against [3, 5, 10, 12, 1] this will return [true, true, true, true], whereas the correct result is `[false, true, false, false, false]`.

### To Reproduce

This is somewhat hard to reproduce as expressions that trigger the issue will generally be optimized away, however it can be triggered by unoptimized expressions or expressions that are manually constructed.

This test exhibits the behavior

```rust
    #[test]
    fn test_and_true_preselection_returns_lhs() {
        let schema =
            Arc::new(Schema::new(vec![Field::new("c", DataType::Boolean, false)]));
        let c_array = Arc::new(BooleanArray::from(vec![false, true, false, false, false]))
            as ArrayRef;
        let batch = RecordBatch::try_new(Arc::clone(&schema), vec![Arc::clone(&c_array)])
            .unwrap();

        let expr = logical2physical(&logical_col("c").and(expr_lit(true)), &schema);

        let lhs_value = logical2physical(&logical_col("c"), &schema)
            .evaluate(&batch)
            .unwrap();
        assert!(matches!(
            check_short_circuit(&lhs_value, &Operator::And),
            ShortCircuitStrategy::PreSelection(_)
        ));

        let result = expr.evaluate(&batch).unwrap();
        let ColumnarValue::Array(result_arr) = result else {
            panic!("Expected ColumnarValue::Array");
        };

        let expected: Vec<_> = c_array.as_boolean().iter().collect();
        let actual: Vec<_> = result_arr.as_boolean().iter().collect();
        assert_eq!(
            expected, actual,
            "AND with TRUE must equal LHS even with PreSelection"
        );
    }
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by acking-you**
## Which issue does this PR close?

- Closes #16928.

## Are there any user-facing changes?

No

## Some thoughts

In current computing frameworks, all computation results are in the form of immutable shared ownership, which leads to many situations where new buffers have to be created instead of reusing existing ones.

For example, in the case of early exit optimization, it should be possible to reuse and modify `lhs` to return the result.

However, doing so under the current framework would lead to memory safety issues. For instance, the `evaluate` implementation of the Column expression reuses the original `Arc` to obtain the result instead of creating a new one, while in other cases a new structure is created (which can be safely modified).

If there were a way to internally indicate whether the current result is newly created or reuses an `Arc`, and if we could design a mutable API for this scenario, it might be possible to reduce unnecessary copies in many computation processes across DataFusion.

### CODE REVIEW

File: datafusion/physical-expr/src/expressions/binary.rs [hunk 1]
```diff
@@ -375,7 +375,19 @@ impl PhysicalExpr for BinaryExpr {
                 // as it takes into account cases where the selection contains null values.
                 let batch = filter_record_batch(batch, selection)?;
                 let right_ret = self.right.evaluate(&batch)?;
-                return pre_selection_scatter(selection, right_ret);
+                match &right_ret {
+                    ColumnarValue::Array(array) => {
+                        return pre_selection_scatter(selection, array.as_boolean());
+                    }
+                    ColumnarValue::Scalar(scalar) => {
+                        if let ScalarValue::Boolean(v) = scalar {
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/binary.rs:398]: You can probably do better here than expanding out the entire array -- 

specifically if the right value is `ScalarValue::Boolean(false)` we know nothing matches so can't we return a single ColumnValue(ScalarValue::Boolean(false))`

Likewise if we know it is `ScalarValue::Boolean(true)` we can avoid selection gathering at all (and just pass back the selection)

File: datafusion/physical-expr/src/expressions/binary.rs [hunk 2]
```diff
@@ -375,7 +375,19 @@ impl PhysicalExpr for BinaryExpr {
...
+                            let array = BooleanArray::from(vec![*v; batch.num_rows()]);
+                            return pre_selection_scatter(selection, &array);
+                        } else {
+                            return Ok(right_ret);
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/binary.rs]: What other kind of scalar value could there be here? Would it be better to return an internal error if we get some non boolean value

**Review by alamb — COMMENTED** [review]
Thank you @acking-you and @mwylde 

I had a few questions but the PR looks nice to me

File: datafusion/physical-expr/src/expressions/binary.rs (hunk 2 above)
Comment (acking-you) [reply datafusion/physical-expr/src/expressions/binary.rs]: Yes, there should not be other types of scalar values.

File: datafusion/physical-expr/src/expressions/binary.rs (hunk 1 above)
Comment (acking-you) [reply datafusion/physical-expr/src/expressions/binary.rs:398]: done

File: datafusion/physical-expr/src/expressions/binary.rs [hunk 3]
```diff
@@ -375,7 +375,46 @@ impl PhysicalExpr for BinaryExpr {
...
+                        if let ScalarValue::Boolean(v) = scalar {
+                            // When the scalar is true or false, skip the scatter process
+                            if let Some(v) = v {
+                                if *v {
+                                    return Ok(lhs);
+                                } else {
+                                    return Ok(right_ret);
+                                }
+                            } else {
+                                let array =
```
Comment (alamb) [inline datafusion/physical-expr/src/expressions/binary.rs]: I suspect anywhere we do a `BooleanArray::from(vec![..])` could be improved eventually if we care. It is likely not worth pursuing in this PR, but I figured I would bring it u

File: datafusion/physical-expr-common/src/physical_expr.rs [hunk 4]
```diff
@@ -106,6 +106,9 @@ pub trait PhysicalExpr: Send + Sync + Display + Debug + DynEq + DynHash {
             Ok(tmp_result)
         } else if let ColumnarValue::Array(a) = tmp_result {
             scatter(selection, a.as_ref()).map(ColumnarValue::Array)
+        } else if let ColumnarValue::Scalar(ScalarValue::Boolean(v)) = &tmp_result {
+            let a = BooleanArray::from(vec![*v; tmp_batch.num_rows()]);
```
Comment (alamb) [inline datafusion/physical-expr-common/src/physical_expr.rs]: we can probably make things faster if we avoid expanding out to a constant array here (avoid the `vec![]`).

**Review by alamb — APPROVED** [review]
Thanks @acking-you and @mwylde 

I think there are some ways to make this PR even faster (avoid `vec!` specifically). However, given this PR is now correct where previously it was not, I think we can merge it and handle other things as a follow on

File: datafusion/physical-expr-common/src/physical_expr.rs (hunk 4 above)
Comment (acking-you) [reply datafusion/physical-expr-common/src/physical_expr.rs]: done

**Comment by alamb** [comment]
Thanks again @acking-you and @mwylde

**Comment by alamb** [comment]
Gah, somehow this PR caused a CI failure: https://github.com/apache/datafusion/actions/runs/16732639756/job/47364317932


Perhaps it undid the fix by @adamreeve  here: 
- https://github.com/apache/datafusion/pull/17026 🤔
