### PR TITLE
Fix hash join with sort push down

### LINKED ISSUE #13559: An error occurred when the sort push down rule pushed sort below join
### Describe the bug

datafusion reported error: does not satisfy order requirements: [c@2 ASC NULLS LAST]. Child-0 order: [[b@1 ASC NULLS LAST]] when execution subquery.



### To Reproduce

```
DataFusion CLI v43.0.0
> create table t(a int, b int, c int) as values (1,2,3), (4,5,6);

select * from t where a in (select a from t where b > 1) order by c;
0 row(s) fetched. 
Elapsed 0.033 seconds.

SanityCheckPlan
caused by
Error during planning: Plan: ["SortPreservingMergeExec: [c@2 ASC NULLS LAST]", "  CoalesceBatchesExec: target_batch_size=8192", "    HashJoinExec: mode=Partitioned, join_type=RightSemi, on=[(a@0, a@0)]", "      CoalesceBatchesExec: target_batch_size=8192", "        RepartitionExec: partitioning=Hash([a@0], 12), input_partitions=12", "          RepartitionExec: partitioning=RoundRobinBatch(12), input_partitions=1", "            CoalesceBatchesExec: target_batch_size=8192", "              FilterExec: b@1 > 1, projection=[a@0]", "                MemoryExec: partitions=1, partition_sizes=[1]", "      SortExec: expr=[b@1 ASC NULLS LAST], preserve_partitioning=[true]", "        CoalesceBatchesExec: target_batch_size=8192", "          RepartitionExec: partitioning=Hash([a@0], 12), input_partitions=1", "            MemoryExec: partitions=1, partition_sizes=[1]"] does not satisfy order requirements: [c@2 ASC NULLS LAST]. Child-0 order: [[b@1 ASC NULLS LAST]]
> 
```

the error due to sort push down, after sort push down the sort column change from `c` to `b`.
```
| physical_plan after EnforceDistribution                    | OutputRequirementExec                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                                                            |   SortExec: expr=[c@2 ASC NULLS LAST], preserve_partitioning=[false]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|                                                            |     CoalescePartitionsExec                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|                                                            |       HashJoinExec: mode=Partitioned, join_type=RightSemi, on=[(a@0, a@0)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|                                                            |         RepartitionExec: partitioning=Hash([a@0], 12), input_partitions=12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
|                                                            |           RepartitionExec: partitioning=RoundRobinBatch(12), input_partitions=1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                            |             ProjectionExec: expr=[a@0 as a]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                                                            |               FilterExec: b@1 > 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|                                                            |                 MemoryExec: partitions=1, partition_sizes=[1]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|                                                            |         RepartitionExec: partitioning=Hash([a@0], 12), input_partitions=1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|                                                            |           MemoryExec: partitions=1, partition_sizes=[1]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| physical_plan after CombinePartialFinalAggregate           | SAME TEXT AS ABOVE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| physical_plan after EnforceSorting                         | OutputRequirementExec                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|                                                            |   SortPreservingMergeExec: [c@2 ASC NULLS LAST]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                            |     HashJoinExec: mode=Partitioned, join_type=RightSemi, on=[(a@0, a@0)]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|                                                            |       RepartitionExec: partitioning=Hash([a@0], 12), input_partitions=12                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|                                                            |         RepartitionExec: partitioning=RoundRobinBatch(12), input_partitions=1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|                                                            |           ProjectionExec: expr=[a@0 as a]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|                                                            |             FilterExec: b@1 > 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|                                                            |               MemoryExec: partitions=1, partition_sizes=[1]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                                                            |       SortExec: expr=[b@1 ASC NULLS LAST], preserve_partitioning=[true]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |
|                                                            |         RepartitionExec: partitioning=Hash([a@0], 12), input_partitions=1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|                                                            |           MemoryExec: partitions=1, partition_sizes=[1]  
```

### Expected behavior

work in datafusion v42, but reported error in datafusion v43 also error in main branch

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by haohuaijin**
## Which issue does this PR close?

Closes #13559

## Are these changes tested?

test by existed test and add a sqllogicaltest test

### CODE REVIEW

**Comment by alamb** [comment]
This appears to be code that was introduced in https://github.com/apache/datafusion/pull/12559 from @berkaysynnada 

@berkaysynnada  is there any way you can help review this PR?

**Comment by berkaysynnada** [comment]
Hi @haohuaijin, and sorry for the delayed response. I have been very busy over the past few days. I have reviewed your fix and have some comments about the problem and the solution.

The issue originates from `handle_custom_pushdown()`, which overfits to operators that simply concatenate the input children's schemas side by side. In your example, the join is a right-semi join, which exposed this bug.

Your fix refers to column names when propagating the order. However, if there are multiple columns in the child schema, this fix may still be insufficient. To address this, I suggest two potential solutions:

1. You can write a specific handler for hash joins. This approach would not rely on a general mapping of input_fields to output_fields but would instead use a join type parameter to propagate the ordering. This solution should work for any type of join in our project and is my recommended approach. You could copy the current logic from this function and adapt it for different join types.
2. You could generalize the logic further to include a mapping of input children fields to output children fields and propagate the ordering accordingly. However, implementing this solution would be non-trivial and would require extensive testing.
If you go with the first solution, I suggest adding a note to the function’s header to clarify its purpose:
"The function can be used for operators that simply concatenate the input children's schemas side by side."

By the way, @alamb, isn’t it risky to have an `index_of(`) API in the `Schema` implementation? Doesn’t this create the potential for mismatches when columns are matched based solely on their names?

**Comment by alamb** [comment]
> By the way, @alamb, isn’t it risky to have an index_of() API in the Schema implementation? Doesn’t this create the potential for mismatches when columns are matched based solely on their names?

Yes, I agree there is this danger

I think the core challenge is that arrow Schema can have duplicated field names, but there are various places in DataFusion that assume the field name is unique (to resolve column referenes)

Even more confusing is that the unique column name assumption is only in the `LogicalPlan` level, rather than the `ExecutonPlan` level (which uses offsets). 🤯 

@findepi

**Comment by alamb** [comment]
So how shall we fix this bug? Is this PR ok to go (even if not perfect)? Or should we do something else?

**Comment by berkaysynnada** [comment]
I can open a PR implementing my first suggestion as it does not require much effort. However, it will handle only hash join properly, and other operators will still go on the custom handler function, and it remains same, not being such custom actually. I'd like to hear from @haohuaijin before deciding.

**Comment by haohuaijin** [comment]
Sorry for the delay @berkaysynnada and @alamb, and thanks for the suggestion for @berkaysynnada 
I go for the first solution, I think for the generalize solution, we need to have the information the how to map the input schema to the output schema (for different join type, the map is different and for hash join, it have projection).

File: datafusion/core/src/physical_optimizer/sort_pushdown.rs [hunk 1]
```diff
@@ -606,6 +610,118 @@ fn handle_custom_pushdown(
...
+    // Collect all unique column indices used in the parent-required sorting expression
+    let all_indices: HashSet<usize> = parent_required
+        .iter()
+        .flat_map(|order| {
+            collect_columns(&order.expr)
+                .iter()
+                .map(|col| col.index())
+                .collect::<HashSet<_>>()
+        })
+        .collect();
```
Comment (berkaysynnada) [inline datafusion/core/src/physical_optimizer/sort_pushdown.rs:640]:
```suggestion
    let all_indices = parent_required
        .iter()
        .flat_map(|order| {
            collect_columns(&order.expr)
                .into_iter()
                .map(|col| col.index())
        })
        .collect::<HashSet<_>>();
```

File: datafusion/core/src/physical_optimizer/sort_pushdown.rs [hunk 2]
```diff
@@ -606,6 +610,118 @@ fn handle_custom_pushdown(
...
+                side: JoinSide::Right,
+            })
+    };
+
+    match plan.join_type() {
+        JoinType::Inner | JoinType::Right => {
+            left_fields().chain(right_fields()).collect()
+        }
+        JoinType::RightSemi | JoinType::RightAnti => right_fields().collect(),
+        _ => unreachable!("unexpected join type: {}", plan.join_type()),
```
Comment (berkaysynnada) [inline datafusion/core/src/physical_optimizer/sort_pushdown.rs:721]:
```suggestion
       let map_fields = |schema: SchemaRef, side: JoinSide| {
        schema
            .fields()
            .iter()
            .enumerate()
            .map(|(index, _)| ColumnIndex { index, side })
            .collect::<Vec<_>>()
    };

    match plan.join_type() {
        JoinType::Inner | JoinType::Right => {
            map_fields(plan.left().schema(), JoinSide::Left)
                .into_iter()
                .chain(map_fields(plan.right().schema(), JoinSide::Right))
                .collect::<Vec<_>>()
        }
        JoinType::RightSemi | JoinType::RightAnti => {
            map_fields(plan.right().schema(), JoinSide::Right)
        }
        _ => unreachable!("unexpected join type: {}", plan.join_type()),
    }
```

**Review by berkaysynnada — APPROVED** [review]
Thanks you @haohuaijin, LGTM. I have just a few minor suggestions.

The plans in the tests look improved (BTW did the previous way of the fix change the plans like that? 🤔 )

**Comment by haohuaijin** [comment]
> BTW did the previous way of the fix change the plans like that? 

the previous way didn't change the plan. Maybe because the current solutions take into account the join type(for right join, the left side don't output) and projection, so make the plan change

File: datafusion/core/src/physical_optimizer/sort_pushdown.rs [hunk 3]
```diff
@@ -606,6 +611,102 @@ fn handle_custom_pushdown(
     }
 }
 
+// For hash join we only maintain the input order for the right child
+// for join type: Inner, Right, RightSemi, RightAnti
+fn handle_hash_join(
```
Comment (alamb) [inline datafusion/core/src/physical_optimizer/sort_pushdown.rs:616]: I think it would be great eventually to get this kind of operator specific logic into the operators (e.g. some method in HashJoinExec). Definitely not in this PR, but having assumptions about the operator separate from its implementation gives us a larger chance of introducing inconsistencies I think

File: datafusion/sqllogictest/test_files/joins.slt [hunk 4]
```diff
@@ -3160,10 +3160,10 @@ explain SELECT t1_id, t1_name, t1_int FROM right_semi_anti_join_table_t2 t2 RIGH
 ----
 physical_plan
 01)SortPreservingMergeExec: [t1_id@0 ASC NULLS LAST]
-02)--SortExec: expr=[t1_id@0 ASC NULLS LAST], preserve_partitioning=[true]
-03)----CoalesceBatchesExec: target_batch_size=2
-04)------HashJoinExec: mode=CollectLeft, join_type=RightSemi, on=[(t2_id@0, t1_id@0)], filter=t2_name@0 != t1_name@1
-05)--------MemoryExec: partitions=1, partition_sizes=[1]
+02)--CoalesceBatchesExec: target_batch_size=2
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/joins.slt:3163]: These plans imply that the sort has been pushed into the second (probe) input which makes sense I think : https://docs.rs/datafusion/latest/datafusion/physical_plan/joins/struct.HashJoinExec.html

**Review by alamb — COMMENTED** [review]
Thankyou @haohuaijin and @berkaysynnada  -- my primary concern with this PR is that it encodes an assumption (that the hash join preserved probe side output order) that is only covered with explain plans tests, and not more end to end style tests with data

For example, if the probe side has `nulls` introduced, I think the current algorithm will introduce nulls at the end of the input, but I don't see any check that the sort order is `NULLS LAST` 🤔  

So I am not sure there is a potential bug but I am also worried 

I worry we could hit subtle bugs in this case if either our assumption about probe side being sorted

Maybe we can add more test coverage with data (including probe sides that have nulls and that don't have nulls) but where nulls are introduced

**Comment by haohuaijin** [comment]
Thanks for your reviews @alamb, I will later find time to add more e2e tests.

File: datafusion/sqllogictest/test_files/joins.slt [hunk 5]
```diff
@@ -4313,3 +4313,86 @@ physical_plan
...
 05)--------MemoryExec: partitions=1, partition_sizes=[1]
 06)--------MemoryExec: partitions=1, partition_sizes=[1]
+
+# Test hash join sort push down
+# Issue: https://github.com/apache/datafusion/issues/13559
+statement ok
+CREATE TABLE test(a INT, b INT, c INT)
+
+statement ok
+insert into test values (1,2,3), (4,5,6), (null, 7, 8), (8, null, 9), (9, 10, null)
```
Comment (haohuaijin) [inline datafusion/sqllogictest/test_files/joins.slt:4323]: cc @alamb, are these tests appropriate?

**Review by alamb — APPROVED** [review]
Thanks @haohuaijin  and @berkaysynnada
