### PR TITLE
fix: use spill writer's schema instead of the first batch schema for spill files

### LINKED ISSUE #21292: Streaming panic when spilling batches with mixed nullability
### Describe the bug

We've been seeing a panic during streaming for a large query (on sizable tables with high cardinality)
```
 Column 'val' is declared as non-nullable but contains null values
```
This is unexpected as the plan seems fine, i.e. the column is nullable from the leaf nodes up to the root node, so this doesn't appear to be a planning error.

The query itself has a union operator where one child has a nullable schema (column projection), while the other child has non-nullable schema (literal projection), wrapped by some aggregation operations (among other things).

The problem seems to occur when there's spilling and the input batches with mixed nullability arive in a specific order
https://github.com/apache/datafusion/blob/bc2b36cf56846e0c697b0f8b98619f346a72a9bf/datafusion/physical-plan/src/spill/in_progress_spill_file.rs#L52-L65

Note that the schema is inherited from the first batch, instead of the spill_writer.

### To Reproduce

It's quite hard to reproduce this at a higher level (i.e. with plain SQL or DataFrame API), but the best I could Claude up is this
```rust
const NUM_BATCHES: usize = 200;
const ROWS_PER_BATCH: usize = 10;

fn non_nullable_schema() -> Arc<Schema> {
    Arc::new(Schema::new(vec![
        Field::new("key", DataType::Int64, false),
        Field::new("val", DataType::Int64, false),
    ]))
}

fn nullable_schema() -> Arc<Schema> {
    Arc::new(Schema::new(vec![
        Field::new("key", DataType::Int64, false),
        Field::new("val", DataType::Int64, true),
    ]))
}

fn non_nullable_batches() -> Vec<RecordBatch> {
    (0..NUM_BATCHES)
        .map(|i| {
            let start = (i * ROWS_PER_BATCH) as i64;
            let keys: Vec<i64> = (start..start + ROWS_PER_BATCH as i64).collect();
            RecordBatch::try_new(
                non_nullable_schema(),
                vec![
                    Arc::new(Int64Array::from(keys)),
                    Arc::new(Int64Array::from(vec![0i64; ROWS_PER_BATCH])),
                ],
            )
            .unwrap()
        })
        .collect()
}

fn nullable_batches() -> Vec<RecordBatch> {
    (0..NUM_BATCHES)
        .map(|i| {
            let start = (i * ROWS_PER_BATCH) as i64;
            let keys: Vec<i64> = (start..start + ROWS_PER_BATCH as i64).collect();
            let vals: Vec<Option<i64>> = (0..ROWS_PER_BATCH)
                .map(|j| if j % 3 == 1 { None } else { Some(j as i64) })
                .collect();
            RecordBatch::try_new(
                nullable_schema(),
                vec![
                    Arc::new(Int64Array::from(keys)),
                    Arc::new(Int64Array::from(vals)),
                ],
            )
            .unwrap()
        })
        .collect()
}

fn build_task_ctx(pool_size: usize) -> Arc<datafusion_execution::TaskContext> {
    let session_config = SessionConfig::new().with_batch_size(2);
    let runtime = RuntimeEnvBuilder::new()
        .with_memory_pool(Arc::new(FairSpillPool::new(pool_size)))
        .build_arc()
        .unwrap();
    Arc::new(
        datafusion_execution::TaskContext::default()
            .with_session_config(session_config)
            .with_runtime(runtime),
    )
}

/// Exercises spilling through UnionExec -> RepartitionExec where union children
/// have mismatched nullability (one child's `val` is non-nullable, the other's
/// is nullable with NULLs). A tiny FairSpillPool forces all batches to spill.
///
/// UnionExec returns child streams without schema coercion, so batches from
/// different children carry different per-field nullability into the shared
/// SpillPool. The IPC writer must use the SpillManager's canonical (nullable)
/// schema — not the first batch's schema — so readback batches are valid.
///
/// Otherwise, sort_batch will panic with
/// `Column 'val' is declared as non-nullable but contains null values`
#[tokio::test]
async fn test_sort_union_repartition_spill_mixed_nullability() {
    let non_nullable_exec = MemorySourceConfig::try_new_exec(
        &[non_nullable_batches()],
        non_nullable_schema(),
        None,
    )
        .unwrap();

    let nullable_exec =
        MemorySourceConfig::try_new_exec(&[nullable_batches()], nullable_schema(), None)
            .unwrap();

    let union_exec =
        UnionExec::try_new(vec![non_nullable_exec, nullable_exec]).unwrap();
    assert!(union_exec.schema().field(1).is_nullable());

    let repartition = Arc::new(
        RepartitionExec::try_new(union_exec, Partitioning::RoundRobinBatch(1)).unwrap(),
    );

    let task_ctx = build_task_ctx(200);
    let mut stream = repartition.execute(0, task_ctx).unwrap();

    let sort_expr = LexOrdering::new(vec![PhysicalSortExpr {
        expr: col("key", &nullable_schema()).unwrap(),
        options: SortOptions::default(),
    }])
        .unwrap();

    let mut total_rows = 0usize;
    let mut total_nulls = 0usize;
    while let Some(result) = stream.next().await {
        let batch = result.unwrap();

        let batch = sort_batch(&batch, &sort_expr, None).unwrap();

        total_rows += batch.num_rows();
        total_nulls += batch.column(1).null_count();
    }

    assert_eq!(
        total_rows,
        NUM_BATCHES * ROWS_PER_BATCH * 2,
        "All rows from both UNION branches should be present"
    );
    assert!(
        total_nulls > 0,
        "Expected some null values in output (i.e. nullable batches were processed)"
    );
}
```

This test fails with `Column 'val' is declared as non-nullable but contains null values`.

On the other hand the test does pass with the following change
```diff
diff --git a/datafusion/physical-plan/src/spill/in_progress_spill_file.rs b/datafusion/physical-plan/src/spill/in_progress_spill_file.rs
index 2666ab882..362768ee5 100644
--- a/datafusion/physical-plan/src/spill/in_progress_spill_file.rs
+++ b/datafusion/physical-plan/src/spill/in_progress_spill_file.rs
@@ -62,7 +62,11 @@ impl InProgressSpillFile {
             ));
         }
         if self.writer.is_none() {
-            let schema = batch.schema();
+            // Use the SpillManager's declared schema rather than the batch's schema.
+            // Individual batches may have different schemas (e.g., different nullability)
+            // when they come from different branches of a UnionExec. The SpillManager's
+            // schema represents the canonical schema that all batches should conform to.
+            let schema = self.spill_writer.schema();
             if let Some(in_progress_file) = &mut self.in_progress_file {
                 self.writer = Some(IPCStreamWriter::new(
                     in_progress_file.path(),
```

### Expected behavior

There should be no streaming errors.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gruuya**
## Which issue does this PR close?

- Closes #21292.

## Rationale for this change

`InProgressSpillFile` will use the first batch schema when it has no writer, which could have different nullability from the subsequent batches (e.g. due to union-ing a literal projection and a table column projection). This can then lead to a panic in `sort_batch`.

`InProgressSpillFile` already has access to the canonical schema that the spill file should have (`self.spill_writer.schema()`).

## What changes are included in this PR?

Single line fix: instead of using the first batch schema for the spill file schema, use the spill_writer's schema instead.

The rest of the changes are two new tests.

## Are these changes tested?

Yes, two new tests are added.

### CODE REVIEW

File: datafusion/physical-plan/src/spill/in_progress_spill_file.rs [hunk 1]
```diff
@@ -138,3 +142,81 @@ impl InProgressSpillFile {
         Ok(self.in_progress_file.take())
     }
 }
+
+#[cfg(test)]
```
Comment (alamb) [inline datafusion/physical-plan/src/spill/in_progress_spill_file.rs:146]: I wonder if the unit tests are needed give the end to end tests?

Comment (gruuya) [reply datafusion/physical-plan/src/spill/in_progress_spill_file.rs:146]: I was actually of the opposite opinion—the e2e test is slightly unwieldy to me, and convoluted in a way, since it tries to reproduce the bug using non-standard primitives and hit the right spill conditions in an unnatural way (because otherwise it's hard to repro). For instance union/repartition exec used directly instead of sql/dataframe API, special task ctx, sort_batch called directly on batches instead of wrapping with SortExec.

Also `InProgressSpillFile` spill file unit tests were missing anyway.

Either way, I'm fine with dropping either one (or none) of those, let me know what you think.

Comment (alamb) [reply datafusion/physical-plan/src/spill/in_progress_spill_file.rs:146]: I think this it is fine to keep both

File: datafusion/core/tests/memory_limit/union_nullable_spill.rs [hunk 2]
```diff
@@ -0,0 +1,162 @@
+// Licensed to the Apache Software Foundation (ASF) under one
```
Comment (alamb) [inline datafusion/core/tests/memory_limit/union_nullable_spill.rs:1]: Could we please not add a new test binary? Instead add it to the existing core_integration test?

Each new test binary takes like 100MB of disk space on the runner

Comment (gruuya) [reply datafusion/core/tests/memory_limit/union_nullable_spill.rs:1]: Oh for sure, give me a minute.

Comment (gruuya) [reply datafusion/core/tests/memory_limit/union_nullable_spill.rs:1]: Done, moved to `memory_limit` dir as there's another spill-themed test there already.

**Comment by alamb** [comment]
Thanks again @gruuya

**Comment by alamb** [comment]
FYI I backported this to 52 and we will do it for 53 as well
- https://github.com/apache/datafusion/pull/21403
