### PR TITLE
Fix bug where binary types were incorrectly being casted for coercible signatures

### LINKED ISSUE #18746: Optimizer: type coercion difference in schemas for LargeUtf8 input on UDF accepting coercible binary
### Describe the bug

Full reproduction:

```rust
use std::any::Any;

use arrow::datatypes::DataType;
use datafusion::common::types::{logical_binary, logical_string, NativeType};
use datafusion::common::ScalarValue;
use datafusion::error::Result;
use datafusion::logical_expr::{Coercion, TypeSignatureClass, Volatility};
use datafusion::logical_expr::{
    ColumnarValue, ScalarFunctionArgs, ScalarUDF, ScalarUDFImpl, Signature,
};
use datafusion::prelude::*;

#[derive(Debug, PartialEq, Eq, Hash)]
struct ExampleUdf {
    signature: Signature,
}

impl ExampleUdf {
    fn new() -> Self {
        Self {
            signature: Signature::coercible(
                vec![Coercion::new_implicit(
                    TypeSignatureClass::Native(logical_binary()),
                    vec![TypeSignatureClass::Native(logical_string())],
                    NativeType::Binary,
                )],
                Volatility::Immutable,
            ),
        }
    }
}

impl ScalarUDFImpl for ExampleUdf {
    fn as_any(&self) -> &dyn Any {
        self
    }

    fn name(&self) -> &str {
        "example_udf"
    }

    fn signature(&self) -> &Signature {
        &self.signature
    }

    fn return_type(&self, arg_types: &[DataType]) -> Result<DataType> {
        match &arg_types[0] {
            DataType::Binary | DataType::BinaryView => Ok(DataType::Utf8),
            DataType::LargeBinary => Ok(DataType::LargeUtf8),
            _ => unreachable!(),
        }
    }

    fn invoke_with_args(&self, args: ScalarFunctionArgs) -> Result<ColumnarValue> {
        match &args.args[0].data_type() {
            DataType::Binary | DataType::BinaryView => Ok(ColumnarValue::Scalar(
                ScalarValue::Utf8(Some("a".to_string())),
            )),
            DataType::LargeBinary => Ok(ColumnarValue::Scalar(ScalarValue::LargeUtf8(
                Some("a".to_string()),
            ))),
            _ => unreachable!(),
        }
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    let ctx = SessionContext::new();
    ctx.register_udf(ScalarUDF::from(ExampleUdf::new()));
    let sqls = [
        // all of these are fine
        "select example_udf(arrow_cast('a', 'Binary'))",
        "select example_udf(arrow_cast('a', 'BinaryView'))",
        "select example_udf(arrow_cast('a', 'LargeBinary'))",
        "select example_udf(arrow_cast('a', 'Utf8'))",
        "select example_udf(arrow_cast('a', 'Utf8View'))",
        // this one has error
        "select example_udf(arrow_cast('a', 'LargeUtf8'))",
    ];
    for sql in sqls {
        ctx.sql(sql).await?.show().await?;
    }
    Ok(())
}
```

Here we have a UDF which accepts string & binary inputs, where strings are coerced to binary. Can see in the example SQLs we test each type that should be accepted. The first five SQL are fine, however the last one fails with error:

```
Error: Context("Optimizer rule 'optimize_projections' failed", Context("Check optimizer-specific invariants after optimizer rule: optimize_projections", Internal("Failed due to a difference in schemas: original schema: DFSchema { inner: Schema { fields: [Field { name: \"example_udf(arrow_cast(Utf8(\\\"a\\\"),Utf8(\\\"LargeUtf8\\\")))\", data_type: Utf8, nullable: true }], metadata: {} }, field_qualifiers: [None], functional_dependencies: FunctionalDependencies { deps: [] } }, new schema: DFSchema { inner: Schema { fields: [Field { name: \"example_udf(arrow_cast(Utf8(\\\"a\\\"),Utf8(\\\"LargeUtf8\\\")))\", data_type: LargeUtf8 }], metadata: {} }, field_qualifiers: [None], functional_dependencies: FunctionalDependencies { deps: [] } }")))
```

Formatted for readability:

```
Failed due to a difference in schemas:
original schema: DFSchema { inner: Schema { fields: [Field { name: "example_udf(arrow_cast(Utf8("a"),Utf8("LargeUtf8")))", data_type: Utf8, nullable: true }] } },
     new schema: DFSchema { inner: Schema { fields: [Field { name: "example_udf(arrow_cast(Utf8("a"),Utf8("LargeUtf8")))", data_type: LargeUtf8 }] } }"
```

- Remove unrelated info and extracted the difference in schema
- Note the error is from `optimize_projections` but I believe this is only because this is where it checks the schema; error stems from type_coercion rule
- See how the data type is difference as well as nullability

There seems to be something going on in the type coercion analyzer rule that incorrectly changes the project schema from `LargeUtf8` to `Utf8`?

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Jefffrey**
## Which issue does this PR close?

- Closes #18746

## Rationale for this change

When presented with a coercible signature that expects binary types, there was a bug where a binary type could be incorrectly casted to another binary type even though it should've stayed as its original self. We were missing an arm to allowed binary origin types to pass through as is where the native type was also binary.

## What changes are included in this PR?

Add arm in native default cast to ensure binary types don't get needlessly casted if the native type is binary.

## Are these changes tested?

Added test.

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/common/src/types/native.rs [hunk 1]
```diff
@@ -253,6 +251,8 @@ impl LogicalType for NativeType {
             (Self::Interval(iu), _) => Interval(*iu),
             (Self::Binary, LargeUtf8) => LargeBinary,
             (Self::Binary, Utf8View) => BinaryView,
+            // We don't cast to another kind of binary type if the origin one is already a binary type
+            (Self::Binary, Binary | LargeBinary | BinaryView) => origin.to_owned(),
```
Comment (Jefffrey) [inline datafusion/common/src/types/native.rs:255]: Same thing as we do for strings:

https://github.com/apache/datafusion/blob/fad5f8a628acc7db29ffed2c3faf7f1f35da5837/datafusion/common/src/types/native.rs#L266-L267

Looks like we just missed it for binary types.

File: datafusion/expr/src/type_coercion/functions.rs [hunk 2]
```diff
@@ -1336,6 +1337,30 @@ mod tests {
         Ok(())
     }
 
+    #[test]
+    fn test_get_valid_types_coercible_binary() -> Result<()> {
```
Comment (Jefffrey) [inline datafusion/expr/src/type_coercion/functions.rs:1341]: On main this test would fail as an input of `LargeBinary` would generate an output of `BinaryView`, since `LargeBinary` can be casted to `BinaryView` as per this arm:

https://github.com/apache/datafusion/blob/fad5f8a628acc7db29ffed2c3faf7f1f35da5837/datafusion/common/src/types/native.rs#L256-L258

Now it should be maintained as `LargeBinary`.

File: datafusion/common/src/types/native.rs (hunk 1 above)
Comment (martin-g) [inline datafusion/common/src/types/native.rs]: What about `FixedSizeBinary` ?

**Review by alamb — APPROVED** [review]
makes sense to me
