### PR TITLE
#16994 Ensure CooperativeExec#maintains_input_order returns a Vec of the correct size

### LINKED ISSUE #16994: `CooperativeExec` incorrectly implements `maintains_input_order`
### Describe the bug

`CooperativeExec` implements `maintains_input_order` by delegating to its input. As a consequence it may return a `Vec` with a length that is smaller or larger than the number of children of `CooperativeExec` which is always exactly `1`.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pepijnve**
## Which issue does this PR close?

- Closes #16994.

## Rationale for this change

The initial implementation of `CooperativeExec#maintains_input_order` is not correct and is likely to return a `Vec` with the wrong size.

## What changes are included in this PR?

Update the implementation of `maintains_input_order` to `vec![true; self.children().len()]` since `CooperativeExec` does not modify input order in any way.

## Are these changes tested?

Still working on unit test(s) that demonstrate the problem.

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by pepijnve** [comment]
@alamb this one might require a 49.0.1 😬

**Review by alamb — COMMENTED** [review]
Thanks @pepijnve 

I have a suggestion on testing: https://github.com/apache/datafusion/issues/16994#issuecomment-3141279920,

**Comment by alamb** [comment]
> @alamb this one might require a 49.0.1 😬

I added it to a "Maybe even 49.0.1" list on 
- https://github.com/apache/datafusion/issues/16799

**Comment by pepijnve** [comment]
I added a number of invariant checks as suggested in https://github.com/apache/datafusion/issues/16994#issuecomment-3141279920
I had to introduce a separate 'default checks' function since it seems there's no way to call the default implementation of a trait function from an implementation that overrides it.

File: datafusion/physical-plan/src/execution_plan.rs [hunk 1]
```diff
@@ -1045,6 +1046,37 @@ impl PlanProperties {
...
+                actual_len,
+                $expected_len
+            );
+        }
+    };
+}
+
+/// Checks a set of invariants that apply to all ExecutionPlan implementations.
+/// Returns an error if the given node does not conform.
+pub fn check_default_invariants<P: ExecutionPlan + ?Sized>(
```
Comment (alamb) [inline datafusion/physical-plan/src/execution_plan.rs:1066]: 👍  this is a good one

**Review by alamb — APPROVED** [review]
Thank you @pepijnve

**Review by xudong963 — APPROVED** [review]

**Comment by alamb** [comment]
Thanks again @pepijnve and @xudong963
