### PR TITLE
fix: Track metrics in hash joins with empty build sides

### LINKED ISSUE #20809: Hash join with empty build side displays wrong number of output rows
### Describe the bug

When a hash join has an empty build side, the existing fast-path optimization does not report the correct number of rows. The problem is that the way metrics are tracked has changed but that part has not been updated.

### To Reproduce

```sql
-- this returns two rows but 0 are reported
EXPLAIN ANALYZE
WITH t1 (k) AS (
    VALUES (1), (2)
), t2 (k) AS (
    VALUES (1)
)
SELECT *
FROM t1
LEFT ANTI JOIN (
    SELECT *
    FROM t2
    WHERE k <> 1
) t2 ON t1.k = t2.k;

HashJoinExec: mode=CollectLeft, join_type=RightAnti, on=[(k@0, k@0)], metrics=[output_rows=0, ...
```

### Expected behavior

Show the correct number of rows.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nuno-faria**
## Which issue does this PR close?

- Closes #20809.

## Rationale for this change

Show the correct metrics when executing hash joins.

## What changes are included in this PR?

- The fast path in `process_probe_batch` now stores the output batch in `output_buffer` instead of returning it, since the metrics are only updated with batches stored there.
- Added unit test.

## Are these changes tested?

Yes.

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/physical-plan/src/joins/hash_join/stream.rs [hunk 1]
```diff
@@ -655,10 +655,10 @@ impl HashJoinStream {
                 self.join_type,
             )?;
             timer.done();
-
+            self.output_buffer.push_batch(result)?;
             self.state = HashJoinStreamState::FetchProbeBatch;
 
-            return Ok(StatefulStreamResult::Ready(Some(result)));
+            return Ok(StatefulStreamResult::Continue);
```
Comment (jonathanc-n) [inline datafusion/physical-plan/src/joins/hash_join/stream.rs:661]: I think we can slowly transition everything to slowly not need to variants of `StatefulStreamResult`, maybe an issue can be raised for this. It goes hand in hand with using the limited batch coalescer

**Comment by jonathanc-n** [comment]
cc @Dandandan for review

File: datafusion/physical-plan/src/joins/hash_join/stream.rs (hunk 1 above)
Comment (jonathanc-n) [reply datafusion/physical-plan/src/joins/hash_join/stream.rs:661]: @Dandandan We can replicate the pattern you added with `LimitedBatchCoalescer` and updating metrics in `poll_next_impl` throughout the codebase

File: datafusion/sqllogictest/test_files/joins.slt [hunk 2]
```diff
@@ -5056,6 +5056,48 @@ LEFT ANTI JOIN t2 ON k1 = k2
 WHERE k1 < 0
 ----
 
+# Also check that the reported number of output rows/batches are correct in the "empty build side"
+# optimization.
```
Comment (2010YOUY01) [inline datafusion/sqllogictest/test_files/joins.slt:5060]:
```suggestion
# optimization.
# Issue: https://github.com/apache/datafusion/issues/20809
```
For future reference if the join order changed. Unfortunately we don't have a configuration to turn off the join reordering, so this test case might need some maintenance in the future.

File: datafusion/physical-plan/src/joins/hash_join/stream.rs [hunk 3]
```diff
@@ -655,10 +655,10 @@ impl HashJoinStream {
                 self.join_type,
             )?;
             timer.done();
```
Comment (2010YOUY01) [inline datafusion/physical-plan/src/joins/hash_join/stream.rs:657]: Not related to this PR, but I noticed we don’t need to explicitly end the timer here since it’s an RAII variable. I’ll open a separate PR after this is merged.

File: datafusion/sqllogictest/test_files/joins.slt (hunk 2 above)
Comment (nuno-faria) [reply datafusion/sqllogictest/test_files/joins.slt:5060]: Applied.
