### PR TITLE
Handle columns in with_new_exprs with a Join

### LINKED ISSUE #14999: Bug: calling "with_new_exprs" on join after optimization unexpectedly fails
### Describe the bug

Before optimization, specifically the `ExtractEquijoinPredicate` rule, calling `with_new_exprs` succeeds.
However, after optimized by `ExtractEquijoinPredicate`, calling `with_new_exprs` unexpectedly fails with the following error:
```
            "The front part expressions should be an binary equality expression, actual:t1.a"
```

### To Reproduce

``` rust
 #[tokio::test]
    async fn test_join_with_new_exprs() -> Result<()> {
        // Creates a default session context.
        let session_context = SessionContext::new();

        // Registers two tables.
        session_context.register_table(
            "t1",
            Arc::new(EmptyTable::new(
                Schema::new(vec![Field::new("a", DataType::Int32, true)]).into(),
            )),
        )?;
        session_context.register_table(
            "t2",
            Arc::new(EmptyTable::new(
                Schema::new(vec![Field::new("a", DataType::Int32, true)]).into(),
            )),
        )?;

        // Creates a plan consisting of a join operator and extracts the join operator.
        let join = session_context
            .sql("select * from t1 join t2 on t1.a = t2.a")
            .await?
            .logical_plan()
            .inputs()
            .remove(0)
            .clone();
        assert!(matches!(join, LogicalPlan::Join(_)));

        let LogicalPlan::Join(before) = &join else {
            unreachable!()
        };
        // Should be: "[]".
        println!("on before opt: {:?}", before.on);
        // Should be: "Some(BinaryExpr(BinaryExpr { left: Column(Column { relation: Some(Bare { table: "t1" }), name: "a" }), op: Eq,
        //                                          right: Column(Column { relation: Some(Bare { table: "t2" }), name: "a" }) }))".
        println!("filter before opt: {:?}", before.filter);
        // Invokes `with_new_exprs` before optimization should succeed.
        let res = join.with_new_exprs(
            join.expressions(),
            join.inputs().into_iter().map(|x| x.clone()).collect(),
        );
        assert!(res.is_ok());

        print!("\n\n");

        // Optimizes join.
        let join = session_context.state().optimize(&join)?;
        let LogicalPlan::Join(after) = &join else {
            unreachable!()
        };
        // Should be: "[(Column(Column { relation: Some(Bare { table: "t1" }), name: "a" }), Column(Column { relation: Some(Bare { table: "t2" }), name: "a" }))]".
        println!("on after opt: {:?}", after.on);
        // Should be: "None".
        println!("filter after opt: {:?}", after.filter);
        // Invokes `with_new_exprs` after optimization unexpectedly fails.
        let res = join.with_new_exprs(
            join.expressions(),
            join.inputs().into_iter().map(|x| x.clone()).collect(),
        );
        assert!(res.is_err());
        assert_contains!(
            res.unwrap_err().to_string(),
            "The front part expressions should be an binary equality expression, actual:t1.a"
        );

        Ok(())
    }
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by delamarch3**
## Which issue does this PR close?

- Closes #14999

## What changes are included in this PR?

Account for columns in any comparisons to the `equi_join_count`. Eg a pair of columns can be compared to one equi_join. Then check for column pairs while creating the new `on` expression.

## Are these changes tested?
Yes, I've added some unit tests.

## Are there any user-facing changes?
`with_new_exprs` with a column will no longer return an error if the other conditions are correct.

### CODE REVIEW

File: datafusion/expr/src/logical_plan/plan.rs [hunk 1]
```diff
@@ -906,28 +906,43 @@ impl LogicalPlan {
                 let equi_expr_count = on.len();
                 assert!(expr.len() >= equi_expr_count);
 
+                let col_pair_count =
+                    expr.iter().filter(|e| matches!(e, Expr::Column(_))).count() / 2;
```
Comment (jonahgao) [inline datafusion/expr/src/logical_plan/plan.rs:910]: The filter can also be a column expression if it's a boolean column. And the on expression may not be a column expr, e.g. ` select * from t1 join t2 on t1.a+2 = t2.a+1 where t2.b`.

I think we don't need to match expr types; we just extract them according to the format returned by `apply_expressions()`, where the first `on.len() * 2` elements are the on-expression pairs, and the last one is the filter expression.

File: datafusion/expr/src/logical_plan/plan.rs [hunk 2]
```diff
@@ -906,28 +906,43 @@ impl LogicalPlan {
...
+                        }) => new_on.push((*left, *right)),
+                        left @ Expr::Column(_) => {
+                            let Some(right) = iter.next() else {
+                                internal_err!("Expected a pair of columns to construct the join on expression")?
+                            };
+
+                            new_on.push((left, right));
+                        }
+                        _ => internal_err!(
+                            "The front part expressions should be a binary equality expression or a column expression, actual:{equi_expr}"
```
Comment (niebayes) [inline datafusion/expr/src/logical_plan/plan.rs:942]:
```suggestion
                            "The front part expressions should be a binary equality expression or a column expression, actual: {equi_expr}"
```

File: datafusion/expr/src/logical_plan/plan.rs [hunk 3]
```diff
@@ -4630,4 +4645,125 @@ digraph {
         let parameter_type = params.clone().get(placeholder_value).unwrap().clone();
         assert_eq!(parameter_type, None);
     }
+
+    #[test]
+    fn test_join_with_new_exprs() {
```
Comment (niebayes) [inline datafusion/expr/src/logical_plan/plan.rs:4650]:
```suggestion
    fn test_join_with_new_exprs() -> Result<()> {
```
Make the function fallible so that many `unwrap`'s can be replaced with `?`

**Comment by delamarch3** [comment]
Thanks for the reviews, I've pushed up your suggestions @jonahgao @niebayes

File: datafusion/expr/src/logical_plan/plan.rs [hunk 4]
```diff
@@ -917,17 +917,16 @@ impl LogicalPlan {
                 // The first part of expr is equi-exprs,
                 // and the struct of each equi-expr is like `left-expr = right-expr`.
                 assert_eq!(expr.len(), equi_expr_count);
-                let new_on = expr.into_iter().map(|equi_expr| {
+                let mut new_on = Vec::new();
```
Comment (jonahgao) [inline datafusion/expr/src/logical_plan/plan.rs:920]: nit: use `with_capacity` would be preferable.
```rust
 let mut new_on = Vec::with_capacity(on.len());
```

**Review by jonahgao — APPROVED** [review]
LGTM👍, thank you @delamarch3

**Comment by jonahgao** [comment]
Thanks @delamarch3 @niebayes
