### PR TITLE
Use `equals_datatype` to compare type when type coercion

### LINKED ISSUE #15351: Merge operation involving map field fails
### Describe the bug

Using the `delta-rs` Python binding, a `DeltaError` was raised when attempting a `DeltaTable.merge` operation. Library-assigned map field names appear to be mutually incompatible, which is beyond the user's control.

The error looks like this:
`DeltaError: Generic DeltaTable error: type_coercion
caused by
Error during planning: Failed to coerce then ([Map(Field { name: "entries", data_type: Struct([Field { name: "key", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "value", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, false), Map(Field { name: "entries", data_type: Struct([Field { name: "key", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "value", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, false), Map(Field { name: "key_value", data_type: Struct([Field { name: "key", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "value", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, false), Map(Field { name: "key_value", data_type: Struct([Field { name: "key", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "value", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, false), Map(Field { name: "key_value", data_type: Struct([Field { name: "key", data_type: Utf8, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, Field { name: "value", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }]), nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, false)]) and else (None) to common types in CASE WHEN expression`

See linked `delta-rs` bug report below for full traceback.

### To Reproduce

Environment
- Python 3.11 on Ubuntu
- Datafusion version: [45](https://github.com/delta-io/delta-rs/blob/python-v0.25.4/Cargo.toml)
- Delta-rs version: 0.25.4
- Pandas version: 2.2.3
- Pyarrow version: 18.1.0

Python code
```python
import pyarrow as pa
import pandas as pd
import deltalake

path = "~/tmp/test"

schema = pa.schema(
    [
        pa.field(
            "foo",
            pa.int64(),
            nullable=False,
        ),
        pa.field(
            "bar",
            pa.map_(pa.string(), pa.float64()),
            nullable=True,
        ),
    ]
)

df = pd.DataFrame(data={"foo": 1, "bar": [{"baz": 123.4}]})

deltalake.write_deltalake(
    path,
    pa.Table.from_pandas(df, schema),
    mode="append"
)

(
    deltalake.DeltaTable(path)
    .merge(
        pa.Table.from_pandas(df, schema),
        predicate="s.foo = t.foo",
        target_alias="t",
        source_alias="s",
    )
    .when_matched_update_all()
    .when_not_matched_insert_all()
    .execute()
)
```

### Expected behavior

I expected the `merge` operation to succeed.

### Additional context

`delta-rs` maintainers indicated this issue is upstream of their library, which is why I'm raising this here.

The issue I raised there: [link](https://github.com/delta-io/delta-rs/issues/3340)

### PR DESCRIPTION
**Pull request by goldmedal**
## Which issue does this PR close?

- Closes #15351.

## Rationale for this change

In the `delta-rs` case, they use a custom field name, `key_value`, for the map type.
https://github.com/delta-io/delta-rs/blob/30dd5edf9717f6545ffbc73e65b676b8adaa0a01/crates/core/src/kernel/arrow/mod.rs#L13

Then, we use `lhs_type = rhs_type` to compare the data type for type coercion checking. However, in the document of `MpaType`:
```rust
    /// In a field with Map type, the field has a child Struct field, which then
    /// has two children: key type and the second the value type. The names of the
    /// child fields may be respectively "entries", "key", and "value", but this is
    /// not enforced.
    Map(FieldRef, bool),
```
The field name doesn't matter actually. We should use `equals_datatype` to compare them instead.
```rust
    /// Compares the datatype with another, ignoring nested field names
    /// and metadata.
    pub fn equals_datatype(&self, other: &DataType) -> bool {
```

## Are these changes tested?
- Add the unit test.
- A reproduce code: https://github.com/apache/datafusion/issues/15351#issuecomment-2746211723

### CODE REVIEW

**Comment by alamb** [comment]
Thanks @goldmedal  -- I'll check this one our more carefully tomorrow

File: datafusion/expr-common/src/type_coercion/binary.rs [hunk 1]
```diff
@@ -708,7 +708,7 @@ pub fn try_type_union_resolution_with_struct(
 /// strings.  For example when comparing `'2' > 1`,  the arguments will be
 /// coerced to `Utf8` for comparison
 pub fn comparison_coercion(lhs_type: &DataType, rhs_type: &DataType) -> Option<DataType> {
-    if lhs_type == rhs_type {
+    if lhs_type.equals_datatype(rhs_type) {
```
Comment (xudong963) [inline datafusion/expr-common/src/type_coercion/binary.rs:711]: 👍 

I also want to ping @jayzhan211 , He corrected me about a similar thing before.

Comment (jayzhan211) [reply datafusion/expr-common/src/type_coercion/binary.rs:711]: Since we only care about data type in this coercion, so I think this makes sense

**Review by jayzhan211 — APPROVED** [review]

**Comment by alamb** [comment]
Thanks @goldmedal  @xudong963 and @jayzhan211
