### PR TITLE
Fix DELETE/UPDATE filter extraction when predicates are pushed down into TableScan

### LINKED ISSUE #19840: `TableProvider::delete_from` problem with pushed down filters
### Describe the bug

I'm attempting to implement the new `delete_from` method in my custom TableProvider implementation.  Despite a `DELETE` query with a where clause that matches a single record, I'm getting no filter expressions passed to `delete_from` leading to all data being deleted instead of a single record.

What I currently believe is happening:
1) My table provider supports push down filters.
2) The datafusion pushes down the filters, so that instead of the ExecutionPlan being a Filter at the top level and having `TableScan` as its input value, the ExecutionPlan becomes `TableScan` which now contains the filters instead.
3) In `extract_dml_filters` , the call to `TreeNode::apply` never reaches the filters inside the `TableScan` because `LogicalPlan::apply_children`  calls ``LogicalPlan::inputs` which returns no children in the case where the top level of the LogicalPlan is a TableScan.

If this explanation does not help, I will try to make a minimal reproduction case to show the problem.

### To Reproduce

1) Try to delete a single record from a table via a TableProvider that supports Exact pushdown filters.
2) Observe all records being deleted.

### Expected behavior

Filters should be correctly passed to `delete_from`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kosiew**
## Which issue does this PR close?

* Closes #19840.

## Rationale for this change

Custom `TableProvider` implementations (notably those that support filter pushdown) expect the DML engine to pass `WHERE` predicates into `TableProvider::delete_from` / `TableProvider::update` so they can apply targeted changes.

However, when the optimizer pushes predicates down into `TableScan.filters`, the logical plan may no longer contain a top-level `Filter` node. The existing DML planning code only collected predicates from `Filter` nodes, so `delete_from` / `update` could receive an empty filter list and unintentionally apply the operation to all rows.

This PR fixes filter extraction to also consider pushdown predicates stored in `TableScan.filters`, while avoiding incorrect behavior in multi-table contexts.

## What changes are included in this PR?

* Extend DML predicate extraction to collect filters from both:

  * `LogicalPlan::Filter` nodes (splitting `AND` conjunctions), and
  * `LogicalPlan::TableScan.filters` for the **target** table.
* Add target scoping for filter extraction:

  * Determine the set of allowed table references for the target table (including simple aliases via `SubqueryAlias`).
  * For `Filter` nodes, retain only predicates whose column references belong to the target table (or are unqualified).
  * For `TableScan.filters`, only read filters from the target table scan to prevent accidentally pulling predicates from source tables.
* Strip column qualifiers before passing expressions to the provider so filters evaluate against the provider schema.
* Deduplicate extracted predicates (needed when partial/inexact pushdown causes the same predicate to appear in both a `Filter` node and `TableScan.filters`).
* Add comprehensive tests for DELETE/UPDATE covering:

  * exact pushdown (filters live in `TableScan.filters`),
  * compound predicates,
  * mixed locations due to `Inexact` pushdown and per-filter decisions,
  * qualifier stripping behavior.
* Temporarily reject `UPDATE ... FROM` during planning with a clear `not_impl` error and align sqllogictest expectations.

  * This avoids incorrect semantics caused by qualifier stripping / predicate selection in multi-table update scenarios.

## Are these changes tested?

Yes.

* Added new unit tests in `datafusion/core/tests/custom_sources_cases/dml_planning.rs` that validate:

  * pushed-down filters are extracted from `TableScan` and passed through to providers,
  * compound predicates are preserved (not over-deduped),
  * mixed pushdown/residual cases still deliver the full predicate set,
  * qualifiers are stripped from passed filters.
* Updated sqllogictest coverage for `UPDATE ... FROM` to assert the feature is currently not implemented.

## Are there any user-facing changes?

* **Bug fix:** `DELETE ... WHERE ...` and `UPDATE ... WHERE ...` against custom `TableProvider`s that use filter pushdown will now correctly pass predicates to the provider, preventing accidental full-table operations.
* **Behavior change (planning error message / support level):** `UPDATE ... FROM` now consistently returns `This feature is not implemented: UPDATE ... FROM is not supported` (until the underlying issue is fixed).

## LLM-generated code disclosure

This PR includes LLM-generated code and comments. All LLM-generated content has been manually reviewed and tested.

### CODE REVIEW

File: datafusion/core/src/physical_planner.rs [hunk 1]
```diff
@@ -1912,24 +1907,48 @@ fn get_physical_expr_pair(
...
+            }
+            LogicalPlan::TableScan(TableScan {
+                filters: scan_filters,
+                ..
+            }) => {
+                for filter in scan_filters {
+                    filters.extend(split_conjunction(filter).into_iter().cloned());
+                }
+            }
+            _ => {}
```
Comment (mjgarton) [inline datafusion/core/src/physical_planner.rs]: I worry slightly that as `LogicalPlan` and perhaps the optimiser behavior change in future, this default case may lead to similar issues.   If the outcome was "nothing gets deleted" rather than "everything gets deleted" I'd worry less.

On the other hand, I can't think of how to improve it, and this change overall fixes the current issue.

Comment (kosiew) [reply datafusion/core/src/physical_planner.rs]: Good point!

The DML input we build for DELETE/UPDATE currently only carries predicates in `Filter` nodes or in `TableScan.filters` after pushdown, so the match over those two variants is exhaustive for today's plan shapes.

We also have regression tests for pushdown paths--`test_delete_filter_pushdown_extracts_table_scan_filters` and `test_delete_compound_filters_with_pushdown which should catch any future optimizer change that relocates predicates away from these nodes. 

If we ever add a new logical node that can hold filters, we'll extend `extract_dml_filters` instead of relying on the default case.

Comment (mjgarton) [reply datafusion/core/src/physical_planner.rs]: Would it make sense to handle each unhandled variant explicity instead of via a default case?  This is how several of the methods in `LogicalPlan` work currently, presumably to deliberately cause compilation failure when new variants are added?

Comment (mjgarton) [reply datafusion/core/src/physical_planner.rs]: For example: https://github.com/apache/datafusion/blob/d90d0746d64bf6e91a81b3ec6954369bd0851bb2/datafusion/expr/src/logical_plan/plan.rs#L480-L484

**Comment by adriangb** [comment]
Would it help to have a `filters` field on `TableScan` similar to projection?

That's something I've wanted to various reasons. My view is that if we define what a scan is as a table + a set of filter expressions + a set of projection expressions universally across the codebase a lot of use cases will be unlocked and things will be simplified. It gives us a framework under which to define cost based optimizers, etc. That becomes a digression from the issue at hand though.

File: datafusion/core/src/physical_planner.rs [hunk 2]
```diff
@@ -1907,24 +1907,48 @@ fn get_physical_expr_pair(
...
     input.apply(|node| {
-        if let LogicalPlan::Filter(filter) = node {
-            // Split AND predicates into individual expressions
-            filters.extend(split_conjunction(&filter.predicate).into_iter().cloned());
+        match node {
+            LogicalPlan::Filter(filter) => {
+                // Split AND predicates into individual expressions
+                filters.extend(split_conjunction(&filter.predicate).into_iter().cloned());
+            }
+            LogicalPlan::TableScan(TableScan {
```
Comment (ethan-tyler) [inline datafusion/core/src/physical_planner.rs:1988]: This collects TableScan.filters from any scan in the subtree. Works for single-table DELETE/UPDATE, but unsafe for UPDATE … FROM (extra scans). Should we restrict extraction to the DML target scan (match table_name or provider identity) and fail-closed if multiple candidate scans exist?

File: datafusion/core/tests/custom_sources_cases/dml_planning.rs [hunk 3]
```diff
@@ -246,6 +269,75 @@ async fn test_delete_complex_expr() -> Result<()> {
     Ok(())
 }
 
+#[tokio::test]
+async fn test_delete_filter_pushdown_extracts_table_scan_filters() -> Result<()> {
+    let provider = Arc::new(CaptureDeleteProvider::new_with_filter_pushdown(
```
Comment (ethan-tyler) [inline datafusion/core/tests/custom_sources_cases/dml_planning.rs:386]: 1) Nice DELETE+Exact pushdown regression. I would add the same coverage for UPDATE … WHERE … + TableProviderFilterPushDown::Exact (since extract_dml_filters is used by both).

2) I would think about adding a "mixed location" case (some conjuncts in residual Filter, others in TableScan.filters) to lock in union+dedup behavior.

File: datafusion/core/src/physical_planner.rs [hunk 4]
```diff
@@ -1907,24 +1907,48 @@ fn get_physical_expr_pair(
...
     })?;
 
-    // Strip table qualifiers from column references
-    filters.into_iter().map(strip_column_qualifiers).collect()
+    // Strip table qualifiers from column references and deduplicate.
+    // Deduplication is necessary because filters may appear in both Filter nodes
+    // and TableScan.filters when the optimizer pushes some predicates down.
+    // We deduplicate by (unqualified) expression to avoid passing the same filter twice.
+    let mut seen_filters = HashSet::new();
+    let deduped = filters
```
Comment (ethan-tyler) [inline datafusion/core/src/physical_planner.rs]: Dedup is done after stripping qualifiers; that can collapse distinct qualified predicates in multi-scan plans. I would either enforce single-target-scan eligibility or adjust dedup so it can't drop distinct predicates.

File: datafusion/core/src/physical_planner.rs [hunk 5]
```diff
@@ -1907,24 +1907,48 @@ fn get_physical_expr_pair(
...
+        .into_iter()
+        .map(strip_column_qualifiers)
```
Comment (ethan-tyler) [inline datafusion/core/src/physical_planner.rs]: Qualifier stripping is dangerous if any predicate references non-target relations (t.id = u.id → id = id). I think we should validate all Column refs belong to the DML target before stripping, and error out (fail closed) otherwise.

File: datafusion/core/tests/custom_sources_cases/dml_planning.rs [hunk 6]
```diff
@@ -91,6 +107,13 @@ impl TableProvider for CaptureDeleteProvider {
             Field::new("count", DataType::UInt64, false),
         ])))))
     }
+
+    fn supports_filters_pushdown(
```
Comment (ethan-tyler) [inline datafusion/core/tests/custom_sources_cases/dml_planning.rs:127]: Right now pushdown mode is uniform for all filters. To test mixed-location behavior (Inexact vs Unsupported per conjunct), I would consider making this provider return per-filter decisions so we can force residual and pushed-down predicates in one query.

File: datafusion/core/tests/custom_sources_cases/dml_planning.rs (hunk 3 above)
Comment (kosiew) [reply datafusion/core/tests/custom_sources_cases/dml_planning.rs:386]: Added in https://github.com/apache/datafusion/pull/19884/commits/98be1b5e03530aba6ffc3d9658be3e33667b4993
https://github.com/apache/datafusion/pull/19884/commits/5fcb927f6bea3f7a60cb796c8aceda757d9f2124

File: datafusion/core/src/physical_planner.rs (hunk 1 above)
Comment (kosiew) [reply datafusion/core/src/physical_planner.rs]: Good idea - https://github.com/apache/datafusion/pull/19884/commits/b3240bfc6cf50f476c430f7864153f8d6e38d518

File: datafusion/core/src/physical_planner.rs (hunk 2 above)
Comment (kosiew) [reply datafusion/core/src/physical_planner.rs:1988]: Done - https://github.com/apache/datafusion/pull/19884/commits/b66edf4774834e332bcdff85eb58f848b65a8a70

File: datafusion/core/src/physical_planner.rs (hunk 4 above)
Comment (kosiew) [reply datafusion/core/src/physical_planner.rs]: Addresssed via 
Target Scan Scoping - https://github.com/apache/datafusion/pull/19884/commits/b66edf4774834e332bcdff85eb58f848b65a8a70
Predicate-Level Validation - https://github.com/apache/datafusion/pull/19884/commits/cfc945d586e3daa9932b6f7710954f1675c639b3

File: datafusion/core/src/physical_planner.rs (hunk 5 above)
Comment (kosiew) [reply datafusion/core/src/physical_planner.rs]: addressed via  qualifier-validation in https://github.com/apache/datafusion/pull/19884/commits/cfc945d586e3daa9932b6f7710954f1675c639b3

File: datafusion/core/tests/custom_sources_cases/dml_planning.rs (hunk 6 above)
Comment (kosiew) [reply datafusion/core/tests/custom_sources_cases/dml_planning.rs:127]: added per-filter pushdown - https://github.com/apache/datafusion/pull/19884/commits/bc5bb4c95b13e264b45e2b14c079d07675c5ccf4

**Comment by ethan-tyler** [comment]
Thanks @kosiew - I'll do another pass and look at the new TableScan.filters as well. It's coming together nicely 👌

File: datafusion/core/src/physical_planner.rs (hunk 5 above)
Comment (ethan-tyler) [reply datafusion/core/src/physical_planner.rs]: Looks good - thanks for adding target-scan scoping and the mixed residual/pushdown coverage.

One remaining concern: `extract_dml_filters` currently drops non-target conjuncts (`predicate_is_on_target` check in `datafusion/core/src/physical_planner.rs:1941`), and `test_update_from_drops_non_target_predicates` (`datafusion/core/tests/custom_sources_cases/dml_planning.rs:658`) codifies this as expected behavior. That can silently broaden row selection and worst case, if the join predicate is the only constraint, this becomes "update all rows".

Would it make sense to fail closed instead (planning error if any WHERE conjunct references a non-target relation), and update that test to assert the error?

File: datafusion/core/src/physical_planner.rs [hunk 7]
```diff
@@ -1907,24 +1907,125 @@ fn get_physical_expr_pair(
...
+/// - `target`: The target table reference to scope filter extraction (prevents multi-table filter leakage)
+///
+/// # Returns
+/// A vector of unqualified filter expressions that can be passed to the TableProvider for execution.
+/// Returns an empty vector if no applicable filters are found.
+///
+fn extract_dml_filters(
+    input: &Arc<LogicalPlan>,
+    target: &TableReference,
+) -> Result<Vec<Expr>> {
```
Comment (ethan-tyler) [inline datafusion/core/src/physical_planner.rs]: `target: &TableReference` may not be sufficient when the target has an alias. Consider deriving allowed target identities from the plan (base ref + alias) rather than only `DmlStatement.table_name`.

File: datafusion/core/src/physical_planner.rs [hunk 8]
```diff
@@ -1907,24 +1907,125 @@ fn get_physical_expr_pair(
...
+            })?;
+            if seen_filters.insert(unqualified.clone()) {
+                deduped.push(unqualified);
+            }
+            Ok(deduped)
+        })
+}
+
+/// Determine whether a predicate references only columns from the target table.
+fn predicate_is_on_target(expr: &Expr, target: &TableReference) -> Result<bool> {
```
Comment (ethan-tyler) [inline datafusion/core/src/physical_planner.rs]: Two concerns here: 
- alias-qualified columns (`x.id` from `UPDATE t AS x`) may not match `target` if it's the base ref -- see `update.slt:91` for the plan shape
- Dropping join predicates silently can broaden scope. Consider failing closed if any conjunct is rejected.

File: datafusion/core/tests/custom_sources_cases/dml_planning.rs [hunk 9]
```diff
@@ -295,3 +619,127 @@ async fn test_unsupported_table_update() -> Result<()> {
...
+    );
+    assert!(
+        filters[0].to_string().contains("5"),
+        "Filter should contain the value 5"
+    );
+    Ok(())
+}
+
+#[tokio::test]
+async fn test_update_from_drops_non_target_predicates() -> Result<()> {
```
Comment (ethan-tyler) [inline datafusion/core/tests/custom_sources_cases/dml_planning.rs:727]: `t2` shares column names with `t1`, the "no t2 references" check can false-negative after qualifier stripping. I would use a t2-only column name to detect leakage reliably.

File: datafusion/core/src/physical_planner.rs (hunk 8 above)
Comment (kosiew) [reply datafusion/core/src/physical_planner.rs]: > Dropping join predicates silently can broaden scope. Consider failing closed if any conjunct is rejected.

Failing close causes these slt tests to fail:

https://github.com/apache/datafusion/blob/d90d0746d64bf6e91a81b3ec6954369bd0851bb2/datafusion/sqllogictest/test_files/update.slt#L70-L105

File: datafusion/core/tests/custom_sources_cases/dml_planning.rs (hunk 9 above)
Comment (kosiew) [reply datafusion/core/tests/custom_sources_cases/dml_planning.rs:727]: Done.

File: datafusion/core/src/physical_planner.rs (hunk 8 above)
Comment (kosiew) [reply datafusion/core/src/physical_planner.rs]: > alias-qualified columns (x.id from UPDATE t AS x) may not match target if it's the base ref -- see update.slt:91 for the plan shape

addressed.

**Comment by kosiew** [comment]
@ethan-tyler 
I added some UPDATE FROM tests and found issues.
Marking it draft for further work.

File: datafusion/sqllogictest/test_files/update.slt [hunk 10]
```diff
@@ -81,8 +81,22 @@ physical_plan
...
+# test update from other table with actual data
 statement ok
-create table t3(a int, b varchar, c double, d int);
+insert into t1 values (1, 'zoo', 2.0, 10), (2, 'qux', 3.0, 20), (3, 'bar', 4.0, 30);
+
+statement ok
+insert into t2 values (1, 'updated_b', 5.0, 40), (2, 'updated_b2', 2.5, 50), (4, 'updated_b3', 1.5, 60);
+
+statement ok
+update t1 set b = t2.b, c = t2.a, d = 1 from t2 where t1.a = t2.a and t1.b > 'foo' and t2.c > 1.0;
```
Comment (ethan-tyler) [inline datafusion/sqllogictest/test_files/update.slt:86]: This expects `SET b = t2.b` to copy values from `t2` into `t1`. With current `TableProvider::update()` and qualifier stripping, cross-table assignments can't be evaluated against the target provider schema.

Belongs in a separate PR implementing UPDATE…FROM execution or explicitly rejecting cross-table assignments. Otherwise this will fail under the DF engine.

File: datafusion/sqllogictest/test_files/update.slt [hunk 11]
```diff
@@ -96,10 +110,33 @@ logical_plan
...
+delete from t2;
+
+statement ok
+insert into t1 values (1, 'zebra', 1.5, 5), (2, 'wolf', 2.0, 10), (3, 'apple', 3.5, 15);
+
+statement ok
+insert into t2 values (1, 'new_val', 2.0, 100), (2, 'new_val2', 1.5, 200);
+
+statement ok
+update t1 as T set b = t2.b, c = t.a, d = 1 from t2 where t.a = t2.a and t.b > 'foo' and t2.c > 1.0;
```
Comment (ethan-tyler) [inline datafusion/sqllogictest/test_files/update.slt:114]: Same concern- cross-table assignment (`SET b = t2.b`) can't be evaluated with current execution model. Should be EXPLAIN only or deferred to a follow up PR.

File: datafusion/sqllogictest/test_files/update.slt [hunk 12]
```diff
@@ -81,8 +81,22 @@ physical_plan
 01)CooperativeExec
 02)--DmlResultExec: rows_affected=0
 
+# test update from other table with actual data
```
Comment (ethan-tyler) [inline datafusion/sqllogictest/test_files/update.slt:75]: Removing `CREATE TABLE t3` here breaks the multi-table negative test at :103 (`FROM t2, t3`). 

Now fails with "table not found" instead of "Multiple tables… not supported". Re-add `t3` setup to keep that test valid.

**Comment by kosiew** [comment]
hi @ethan-tyler 

I am thinking of addressing UPDATE..FROM separately and amending the current UPDATE .. FROM like in the tests to fail.
They are giving wrong results here and in `main`.
Created #19950 to track.

File: datafusion/sql/src/statement.rs [hunk 13]
```diff
@@ -1070,6 +1070,13 @@ impl<S: ContextProvider> SqlToRel<'_, S> {
                     plan_err!("Multiple tables in UPDATE SET FROM not yet supported")?;
                 }
                 let update_from = from_clauses.and_then(|mut f| f.pop());
+
+                // UPDATE ... FROM is currently not working
+                // TODO fix https://github.com/apache/datafusion/issues/19950
+                if update_from.is_some() {
+                    return not_impl_err!("UPDATE ... FROM is not supported");
```
Comment (ethan-tyler) [inline datafusion/sql/src/statement.rs:1079]: Minor inconsistency: multi-table `FROM` (L1070) returns `plan_err!("Multiple tables...")` while single-table `FROM` (L1077) returns `not_impl_err!`. 

Consider unifying- any `UPDATE ... FROM` → `not_impl_err!` making error handling is consistent.

Comment (kosiew) [reply datafusion/sql/src/statement.rs:1079]: 👍 
Unified in https://github.com/apache/datafusion/pull/19884/commits/e9bf8f3fe0b2fe46d499103a7be8fb35cda1083d

**Comment by adriangb** [comment]
Hi folks just looping back here. I haven't followed the details but don't want a good change to go to waste. Is this fix ready to go?

**Comment by ethan-tyler** [comment]
> Hi folks just looping back here. I haven't followed the details but don't want a good change to go to waste. Is this fix ready to go?

Thanks @adriangb - from my last review I think we are in good shape with planned follow up work to build on this. I can do another look since it's been a hot min. Just lmk

**Comment by adriangb** [comment]
Sounds good, @kosiew could you give the final approval since you're a committer?

**Comment by kosiew** [comment]
@adriangb 

> @kosiew could you give the final approval since you're a committer?

I can't because I am the originator of this PR

File: datafusion/core/src/physical_planner.rs [hunk 14]
```diff
@@ -1936,24 +1936,149 @@ fn get_physical_expr_pair(
 }
 
 /// Extract filter predicates from a DML input plan (DELETE/UPDATE).
-/// Walks the logical plan tree and collects Filter predicates,
-/// splitting AND conjunctions into individual expressions.
-/// Column qualifiers are stripped so expressions can be evaluated against
-/// the TableProvider's schema.
 ///
-fn extract_dml_filters(input: &Arc<LogicalPlan>) -> Result<Vec<Expr>> {
+/// Walks the logical plan tree and collects Filter predicates and any filters
```
Comment (adriangb) [inline datafusion/core/src/physical_planner.rs:1940]: Thank you for the detailed docstring!

**Comment by adriangb** [comment]
> @adriangb
> 
> > @kosiew could you give the final approval since you're a committer?
> 
> I can't because I am the originator of this PR

Duh! I reviewed now :)

**Comment by kosiew** [comment]
@adriangb, @ethan-tyler 
Thanks for your review and feedback
