### PR TITLE
Fix FileStream scanning_total to include sync next-file open time

### LINKED ISSUE #20571: FileStream start_next_file() is not measured in compute time.
### Describe the bug

start_next_file returns a FileOpenFuture, however nothing guarantees that the open() function, which returns that future, doesn't take processing time.
This time should be represented in time scanning total

```
fn start_next_file(&mut self) -> Option<Result<(FileOpenFuture, Vec<ScalarValue>)>> {
        let part_file = self.file_iter.pop_front()?;

        let partition_values = part_file.partition_values.clone();
        let _timer = self.file_stream_metrics.time_scanning_total.metrics.timer(); // <- this line is missing
        Some(
            self.file_opener
                .open(part_file)
                .map(|future| (future, partition_values)),
        )
    }
```

An alternative solution would be to remove Result from this function's signature, and return a futures::future::lazy which will perform the opening, and call .try_flatten() on that nested future.
That way this will only happen when polled first

### To Reproduce

Add a FileOpener which sleeps a couple seconds before returning the file open future

### Expected behavior

This should be clearly represented by the scan time total, in practice, given enough CPU work, the opening file time can actually appear larger than total scan time

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by RatulDawar**
## Summary
- include synchronous `start_next_file()` / `FileOpener::open()` setup time in `time_elapsed_scanning_total`
- keep existing `time_opening` and scanning timers lifecycle intact
- avoid timer overlap by scoping the temporary timer before calling `time_scanning_total.start()`

## Details
In `FileStreamState::Open`, `start_next_file()` is invoked before `time_scanning_total.start()`. If `open()` performs synchronous work before returning the future, that time was previously unaccounted for in `time_elapsed_scanning_total`.

This change wraps the `start_next_file()` call in a scoped timer on the same `time_scanning_total` metric so the missing segment is recorded.

- Fixes #20571

## Validation
I tested by reading CSV files via AWS S3.

### CODE REVIEW

**Comment by RatulDawar** [comment]
Can a commiter please help me run the CI checks here ? 
@alamb  @ozankabak  @andygrove

**Comment by RatulDawar** [comment]
Hey @alamb who will be the correct person to review this ?

File: datafusion/datasource/src/file_stream.rs [hunk 1]
```diff
@@ -126,7 +126,15 @@ impl FileStream {
                     Ok(reader) => {
                         // include time needed to start opening in `start_next_file`
                         self.file_stream_metrics.time_opening.stop();
-                        let next = self.start_next_file().transpose();
+                        let next = {
```
Comment (alamb) [inline datafusion/datasource/src/file_stream.rs:130]: I wonder if there is any way to make this more concise (to avoid complicating the FileStream more).

Perhaps a method on `file_stream_metrics so this could look like

```rust
 let scanning_total_metric = self.file_stream_metrics.time_scanning_total.timer()` 🤔

**Comment by alamb** [comment]
Thanks @RatulDawar and @xudong963
