### PR TITLE
fix: window unparsing

### LINKED ISSUE #17360: Unparsing of Window functions is generating incorrect queries
### Describe the bug

The unparsing of Window functions on optimized plans is generating incorrect queries. The reason for this is that the projection on Window columns is optimized away, meaning the final query will use the entire function as the column name.

### To Reproduce

Example:
```sql
-- original (the window function is used both in the filter and in the projection)
select k, v, r
from (
    select *, rank() over(partition by k order by v) as r
    from t
) t
where r = 1

-- unoptimized plan (the window function is projected as "r", which is used by the filter and the projection)
Projection: t.k, t.v, t.r
  Filter: t.r = Int64(1)
    SubqueryAlias: t
      Projection: t.k, t.v, rank() PARTITION BY [t.k] ORDER BY [t.v ASC NULLS LAST] RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW AS r
        WindowAggr: windowExpr=[[rank() PARTITION BY [t.k] ORDER BY [t.v ASC NULLS LAST] RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW]]
          TableScan: t

-- optimized plan (the projection is optimized out, the filter and projection refer to the window function directly by the original code)
SubqueryAlias: t
  Projection: t.k, t.v, rank() PARTITION BY [t.k] ORDER BY [t.v ASC NULLS LAST] RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW AS r
    Filter: rank() PARTITION BY [t.k] ORDER BY [t.v ASC NULLS LAST] RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW = UInt64(1)
      WindowAggr: windowExpr=[[rank() PARTITION BY [t.k] ORDER BY [t.v ASC NULLS LAST] RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW]]
        TableScan: t projection=[k, v]

-- invalid filter
SELECT * FROM (
  SELECT t.k, t.v, rank() OVER (PARTITION BY t.k ORDER BY t.v ASC NULLS LAST RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS r 
  FROM t 
  WHERE ("rank() PARTITION BY [t.k] ORDER BY [t.v ASC NULLS LAST] RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW" = 1)
) AS t
```

### Expected behavior

Return valid SQL.

### Additional context

Also failing with the `QUALIFY` statement:
```sql
-- original
select *, rank() over(partition by k order by v) as r
from t
qualify r = 1;

-- optimized plan
Projection: t.k, t.v, rank() PARTITION BY [t.k] ORDER BY [t.v ASC NULLS LAST] RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW AS r
  Filter: rank() PARTITION BY [t.k] ORDER BY [t.v ASC NULLS LAST] RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW = UInt64(1)
    WindowAggr: windowExpr=[[rank() PARTITION BY [t.k] ORDER BY [t.v ASC NULLS LAST] RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW]]
      TableScan: t projection=[k, v]

-- output
SELECT t.k, t.v, rank() OVER (PARTITION BY t.k ORDER BY t.v ASC NULLS LAST RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS r 
FROM t
WHERE ("rank() PARTITION BY [t.k] ORDER BY [t.v ASC NULLS LAST] RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW" = 1)
```

### PR DESCRIPTION
**Pull request by chenkovsky**
## Which issue does this PR close?

- Closes #17360.

## Rationale for this change

in LogicalPlan::Filter unparsing, 
if there's a window expr, it should be converted to quailify.

postgres must has an alias for derived table. otherwise it will complain:
```
ERROR: subquery in FROM must have an alias.
```
fixed this issue at the same time.

## What changes are included in this PR?

If window expr is found, convert filter to quailify.

## Are these changes tested?

UT

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/sql/tests/cases/plan_to_sql.rs [hunk 1]
```diff
@@ -2519,6 +2521,46 @@ fn test_unparse_left_semi_join_with_table_scan_projection() -> Result<()> {
...
+    let name = plan.schema().fields().last().unwrap().name().clone();
+    let plan = LogicalPlanBuilder::from(plan)
+        .filter(col(name.clone()).eq(lit(1i64)))?
+        .project(vec![col("k"), col("v"), col(name)])?
+        .build()?;
+    let unparser = Unparser::new(&UnparserPostgreSqlDialect {});
+    let sql = unparser.plan_to_sql(&plan)?;
+    assert_snapshot!(
+        sql,
+        @r#"SELECT "test"."k", "test"."v", rank() OVER (PARTITION BY "test"."k" ORDER BY "test"."v" ASC NULLS FIRST ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) FROM "test" QUALIFY (rank() OVER (PARTITION BY "test"."k" ORDER BY "test"."v" ASC NULLS FIRST ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) = 1)"#
```
Comment (nuno-faria) [inline datafusion/sql/tests/cases/plan_to_sql.rs]: Thanks @chenkovsky, this now generates valid Datafusion SQL.
Unfortunately, the `QUALIFY` keyword is not available in PostgreSQL, as well as other systems (https://modern-sql.com/caniuse/qualify), meaning the output does not work there.

File: datafusion/sql/src/unparser/dialect.rs [hunk 2]
```diff
@@ -267,6 +274,14 @@ impl Dialect for DefaultDialect {
 pub struct PostgreSqlDialect {}
 
 impl Dialect for PostgreSqlDialect {
+    fn supports_qualify(&self) -> bool {
+        false
+    }
```
Comment (nuno-faria) [inline datafusion/sql/src/unparser/dialect.rs:286]: Like PostgreSQL, MySQL and SQLite also do not support the `Qualify` keyword, so they should also have `supports_qualify` returning `false`.

**Review by nuno-faria — APPROVED** [review]
Thanks @chenkovsky, LGTM. I leave below just a minor note.

File: datafusion/sql/src/unparser/dialect.rs [hunk 3]
```diff
@@ -267,6 +274,14 @@ impl Dialect for DefaultDialect {
...
+
+    fn requires_derived_table_alias(&self) -> bool {
+        true
+    }
```
Comment (Jefffrey) [inline datafusion/sql/src/unparser/dialect.rs:290]: What's the relation of this fix?

File: datafusion/sql/src/unparser/rewrite.rs [hunk 4]
```diff
@@ -100,6 +100,79 @@ fn rewrite_sort_expr_for_union(exprs: Vec<SortExpr>) -> Result<Vec<SortExpr>> {
...
+/// becomes:
+///
+/// Filter: condition
+///   SubqueryAlias: __qualify_subquery
+///     Projection: table.column1, table.column2
+///       Window: window_function
+///         TableScan: table
+///
+pub(super) fn rewrite_qualify(plan: &LogicalPlan) -> Result<LogicalPlan> {
+    let plan = plan.clone();
```
Comment (Jefffrey) [inline datafusion/sql/src/unparser/rewrite.rs]:
```suggestion
pub(super) fn rewrite_qualify(plan: LogicalPlan) -> Result<LogicalPlan> {
```

If we clone a reference it's better to make it known in the signature that we need ownership anyway (and do clone at callsite if required)

File: datafusion/sql/src/unparser/rewrite.rs [hunk 5]
```diff
@@ -100,6 +100,79 @@ fn rewrite_sort_expr_for_union(exprs: Vec<SortExpr>) -> Result<Vec<SortExpr>> {
...
+                    .iter()
+                    .filter(|(q, _)| q.is_some())
+                    .flat_map(|(q, _)| q)
+                    .collect::<Vec<_>>();
+
+                let qualifier = if qualifiers.is_empty() {
+                    "__qualify_subquery".to_string()
+                } else {
+                    qualifiers[0].to_string()
+                };
```
Comment (Jefffrey) [inline datafusion/sql/src/unparser/rewrite.rs]: What's the significance of this hardcoded `"__qualify_subquery"`? Can it be demonstrated in a test?

Btw can avoid collect to Vec by doing something like this:

```rust
let qualifier = filter
    .input
    .schema()
    .iter()
    .find_map(|(q, _)| q)
    .map(|q| q.to_string())
    .unwrap_or_else(|| "__qualify_subquery".to_string());
```

File: datafusion/sql/tests/cases/plan_to_sql.rs [hunk 6]
```diff
@@ -2521,6 +2523,69 @@ fn test_unparse_left_semi_join_with_table_scan_projection() -> Result<()> {
...
+    let plan = LogicalPlanBuilder::from(plan)
+        .filter(col(name.clone()).eq(lit(1i64)))?
+        .project(vec![col("k"), col("v"), col(name)])?
+        .build()?;
+
+    let unparser = Unparser::new(&UnparserPostgreSqlDialect {});
+    let sql = unparser.plan_to_sql(&plan)?;
+    assert_snapshot!(
+        sql,
+        @r#"SELECT "test"."k", "test"."v", "rank() PARTITION BY [test.k] ORDER BY [test.v ASC NULLS FIRST] ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING" FROM (SELECT "test"."k" AS "k", "test"."v" AS "v", rank() OVER (PARTITION BY "test"."k" ORDER BY "test"."v" ASC NULLS FIRST ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "rank() PARTITION BY [test.k] ORDER BY [test.v ASC NULLS FIRST] ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING" FROM "test") AS "test" WHERE ("rank() PARTITION BY [test.k] ORDER BY [test.v ASC NULLS FIRST] ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING" = 1)"#
```
Comment (Jefffrey) [inline datafusion/sql/tests/cases/plan_to_sql.rs:2563]: These column names seem really chunky 🤔 

Is it possible to also use the cases provided in the original issue, e.g.

```sql
select k, v, r
from (
    select *, rank() over(partition by k order by v) as r
    from t
) t
where r = 1
```

and

```sql
select *, rank() over(partition by k order by v) as r
from t
qualify r = 1;
```

And see if the `where r = 1` gets preserved?

File: datafusion/sql/src/unparser/rewrite.rs [hunk 7]
```diff
@@ -100,6 +100,79 @@ fn rewrite_sort_expr_for_union(exprs: Vec<SortExpr>) -> Result<Vec<SortExpr>> {
...
+///       Window: window_function
+///         TableScan: table
+///
+pub(super) fn rewrite_qualify(plan: &LogicalPlan) -> Result<LogicalPlan> {
+    let plan = plan.clone();
+
+    let transformed_plan = plan.transform_up(|plan| match plan {
+        LogicalPlan::Filter(mut filter) => {
+            // Check if the filter's input is a Window plan
+            if matches!(&*filter.input, LogicalPlan::Window(_)) {
```
Comment (Jefffrey) [inline datafusion/sql/src/unparser/rewrite.rs:127]:
```suggestion
        // Check if the filter's input is a Window plan
        LogicalPlan::Filter(mut filter)
            if matches!(&*filter.input, LogicalPlan::Window(_)) =>
        {
```

fyi can collapse the if into a match guard

File: datafusion/sql/src/unparser/dialect.rs (hunk 3 above)
Comment (chenkovsky) [reply datafusion/sql/src/unparser/dialect.rs:290]: it's another bug. postgres must has an alias for derived table.  
ERROR:  subquery in FROM must have an alias.
I come across this error when I try to fix this issue.

Comment (Jefffrey) [reply datafusion/sql/src/unparser/dialect.rs:290]: Thanks, please make sure to explicitly mention this in the PR body so reviewers have context on the change

File: datafusion/sql/tests/cases/plan_to_sql.rs (hunk 6 above)
Comment (chenkovsky) [reply datafusion/sql/tests/cases/plan_to_sql.rs:2563]: column name is chunky. but the test is essential. because postgres and datafusion have different default column names for window function. I added a default alias to make sure unparsed sql can be queried in postgres.

**Review by Jefffrey — APPROVED** [review]

**Comment by nuno-faria** [comment]
Thanks @chenkovsky and @Jefffrey.
