### PR TITLE
Minor: return NULL for range and generate_series

### LINKED ISSUE #10269: Handle nulls for `range` and `generate_series`
### Describe the bug

Follow the logic like DuckDB, if any of the argument is Null, return Null instead of throwing error

### To Reproduce

```
query error
select range(DATE '1992-09-01', NULL, INTERVAL '1' YEAR);

query error
select range(DATE '1992-09-01', DATE '1993-03-01', NULL);

query error
select range(NULL, DATE '1993-03-01', INTERVAL '1' YEAR);
```

### Expected behavior

```
select range(DATE '1992-09-01', NULL, INTERVAL '1' YEAR);
----
Null

select range(DATE '1992-09-01', DATE '1993-03-01', NULL);
----
Null

query error
select range(NULL, DATE '1993-03-01', INTERVAL '1' YEAR);
----
Null
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Lordworms**
## Which issue does this PR close?

Closes #10269

### CODE REVIEW

File: datafusion/functions-array/src/range.rs [hunk 1]
```diff
@@ -57,6 +56,7 @@ impl Range {
                     TypeSignature::Exact(vec![Int64, Int64]),
                     TypeSignature::Exact(vec![Int64, Int64, Int64]),
                     TypeSignature::Exact(vec![Date32, Date32, Interval(MonthDayNano)]),
+                    TypeSignature::Any(3),
```
Comment (jayzhan211) [inline datafusion/functions-array/src/range.rs:59]: Does this mean we need to find a new kind of signature that accepts either one exact type or  null 🤔

Comment (Lordworms) [reply datafusion/functions-array/src/range.rs:59]: I think it would be better to have a new Signature. Maybe I can add more signatures in the following PR along with dealing #10200

Comment (jayzhan211) [reply datafusion/functions-array/src/range.rs:59]: I'm thinking of something like
```
        TypeSignature::ExactOrNull(valid_types) => {
            current_types.iter().map(|t| {
                if t != &DataType::Null {
                    valid_types.clone()
                } else {
                    vec![DataType::Null]
                }
            })
        }
```

Comment (Lordworms) [reply datafusion/functions-array/src/range.rs:59]: Yeah, that would be fine. I'll add a ticket to record it

**Review by jayzhan211 — APPROVED** [review]

File: datafusion/sqllogictest/test_files/array.slt [hunk 2]
```diff
@@ -5666,15 +5677,25 @@ select generate_series(5),
 [0, 1, 2, 3, 4, 5] [2, 3, 4, 5] [2, 5, 8] [1, 2, 3, 4, 5] [5, 4, 3, 2, 1] [10, 7, 4] [1992-09-01, 1992-10-01, 1992-11-01, 1992-12-01, 1993-01-01, 1993-02-01, 1993-03-01] [1993-02-01, 1993-01-31, 1993-01-30, 1993-01-29, 1993-01-28, 1993-01-27, 1993-01-26, 1993-01-25, 1993-01-24, 1993-01-23, 1993-01-22, 1993-01-21, 1993-01-20, 1993-01-19, 1993-01-18, 1993-01-17, 1993-01-16, 1993-01-15, 1993-01-14, 1993-01-13, 1993-01-12, 1993-01-11, 1993-01-10, 1993-01-09, 1993-01-08, 1993-01-07, 1993-01-06, 1993-01-05, 1993-01-04, 1993-01-03, 1993-01-02, 1993-01-01] [1989-04-01, 1990-04-01, 1991-04-01, 1992-04-01]
 
 ## should throw error
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/array.slt:5679]:
```suggestion
## should return NULL
```

File: datafusion/sqllogictest/test_files/array.slt [hunk 3]
```diff
@@ -5632,14 +5632,25 @@ select range(NULL)
 NULL
 
 ## should throw error
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/array.slt:5634]:
```suggestion
## should return NULL
```

File: datafusion/functions-array/src/udf.rs [hunk 4]
```diff
@@ -166,146 +166,6 @@ impl ScalarUDFImpl for StringToArray {
     }
 }
 
-make_udf_function!(
```
Comment (alamb) [inline datafusion/functions-array/src/udf.rs:169]: is this just an accidental left over copy?

File: datafusion/functions-array/src/udf.rs [hunk 5]
```diff
@@ -166,146 +166,6 @@ impl ScalarUDFImpl for StringToArray {
...
-            }
-        }
-    }
-
-    fn aliases(&self) -> &[String] {
-        &self.aliases
-    }
-}
-
-make_udf_function!(
```
Comment (alamb) [inline datafusion/functions-array/src/udf.rs:239]: Likewise this looks like an accidental copy too -- here is the other copy:

https://github.com/apache/datafusion/blob/0ea9bc659cbcdd1d70cf8ea8c284634d65171c33/datafusion/functions-array/src/range.rs#L102-L163

**Review by alamb — APPROVED** [review]
Thank you @Lordworms  and @jayzhan211 -- looks good to me

FWIW I also verified that returning NULL is consistent with DuckDB:

```sql
D select generate_series(DATE '1992-09-01', NULL, INTERVAL '1' YEAR);
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ generate_series(CAST('1992-09-01' AS DATE), NULL, to_years(CAST(trunc(CAST('1' AS DOUBLE)) AS INTEGER))) │
│                                                  int32                                                   │
├──────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│                                                                                                          │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

File: datafusion/functions-array/src/udf.rs (hunk 4 above)
Comment (Lordworms) [reply datafusion/functions-array/src/udf.rs:169]: Yes, there might be some other left things

**Comment by jayzhan211** [comment]
thanks @Lordworms and @alamb
