### PR TITLE
fix: handle empty delimiter in split_part (closes #20503)

### LINKED ISSUE #20503: split_part function returning wrong results
### Describe the bug

`split_part('a,b', '', 2)` is returning `'a'`, but it should return `""` (PostgreSQL - https://www.db-fiddle.com/f/bndEpNtUKEnLoe3oQE1gtY/0). It seems to be related to how the split(...) function works in Rust.

Rust playground [repro](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=64a5b1bb9ffd42c8fddd2fa016f72f47)

Another instance of this bug is the following query:

`SELECT split_part('a,b', '', 1)
`

returning `"" `instead of `a,b`

### To Reproduce

[DF fiddle link](https://datafusion-fiddle.vercel.app/?q=eyJkZGwiOiItLSBTdGVwIDE6IENyZWF0ZSBhIHRlc3QgdGFibGVcbkNSRUFURSBUQUJMRSB0ZXN0X2xvZ3MgKFxuICAgIGlkIElOVCwgXG4gICAgc2VydmljZSBURVhUIE5VTEwgICAgIC0tIE51bGxhYmxlIGNvbHVtblxuKTtcblxuLS0gU3RlcCAyOiBJbnNlcnQgc2FtcGxlIGRhdGFcbklOU0VSVCBJTlRPIHRlc3RfbG9ncyAoaWQsIHNlcnZpY2UpIFZBTFVFU1xuICAgICgxLCAnbXlzZXJ2aWNlJyksXG4gICAgKDIsIE5VTEwpLFxuICAgICgzLCAnb3RoZXJzZXJ2aWNlJyksXG4gICAgKDQsICdteXNlcnZpY2UnKTtcblxuXG4iLCJzZWxlY3QiOiItLSBTdGVwIDM6IFJ1biB0aGUgcXVlcnkgdGhhdCB0cmlnZ2VycyB0aGUgZXJyb3JcblNFVCBkYXRhZnVzaW9uLnNxbF9wYXJzZXIuZGlhbGVjdCB0byBIaXZlO1xuU0VMRUNUIFxuICAgIENPVU5UKCopIEZJTFRFUiAoV0hFUkUgc2VydmljZSA9ICdteXNlcnZpY2UnIElTIFRSVUUpIEFTIHNlcnZpY2VfbG9nc1xuRlJPTSB0ZXN0X2xvZ3M7XG4ifQ==)

### Expected behavior

return `""`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gferrate**
## Which issue does this PR close?

- Closes #20503 

## Rationale for this change

`split_part` did not handle empty delimiters in a PostgreSQL-compatible way (`split("")` in Rust creates leading/trailing empty fields).
This could return unexpected results for positions like `1` / `-1` and out-of-range values.
This PR aligns behavior with Postgres semantics for empty delimiters.

## What changes are included in this PR?

Small change in how we treat the 1, -1

## Are these changes tested?

Indeed!

## Are there any user-facing changes?

Yes, behavior is now more consistent with PostgreSQL for `split_part(str, '', n)`.
No API changes.

### CODE REVIEW

File: datafusion/functions/src/string/split_part.rs [hunk 1]
```diff
@@ -341,6 +356,117 @@ mod tests {
             Utf8,
             StringArray
         );
+        // Edge cases with delimiters
```
Comment (LiaCastaneda) [inline datafusion/functions/src/string/split_part.rs:359]: wdyt about adding a couple of test cases for these edge cases in the [sqllogic tests](https://github.com/apache/datafusion/blob/e937cadbcceff6a42bee2c5fc8d03068fa0eb30c/datafusion/sqllogictest/test_files/string/string_literal.slt#L854) too?

Comment (gferrate) [reply datafusion/functions/src/string/split_part.rs:359]: Added!

**Comment by alamb** [comment]
Thank you @gferrate and @gabotechs
