### PR TITLE
Fix wildcard dataframe case

### LINKED ISSUE #15218: Dataframe: select wildcard not working
### Describe the bug

```rust
#[tokio::test]
async fn select_all() -> Result<()> {
    // build plan using `select_expr``
    let t = test_table().await?;

    let df = t
    .select(vec![wildcard()])?;

    let plan = df
        .logical_plan().clone();
    
    let r = df.collect().await?;
    println!("r: {:?}", r);


    println!("paln: {}", plan.display_indent());

    Ok(())
}
```

This query is no longer working after https://github.com/apache/datafusion/pull/15170/files. I didn't notice Dataframe case but only sql case.

But given `Expr::Wildcard` is deprecated, we need to find alternative way to support wildcard. 

One way is to add WildcardOptions

```rust
impl Projection {
    pub fn try_new_with_schema(
        expr: Vec<Expr>,
        wildcard: Option<WildcardOptions>,
        input: Arc<LogicalPlan>,
        schema: DFSchemaRef,
    ) -> Result<Self>
``` 

or maybe a new Enum

```rust
enum ProjectionExprs {
    /// The expressions are provided as a list of expressions
    Exprs(Vec<Expr>),
    /// The expressions are provided as a wildcard
    Wildcard(WildcardOptions),
}
```

However, both require API change

Also, I would like to add new API like `select_all` or `project_all` for wildcard cases

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jayzhan211**
## Which issue does this PR close?

- Closes #15218 .

### CODE REVIEW

File: datafusion/sql/src/select.rs [hunk 1]
```diff
@@ -741,8 +722,17 @@ impl<S: ContextProvider> SqlToRel<'_, S> {
...
+    fn project(&self, input: LogicalPlan, expr: Vec<SelectExpr>) -> Result<LogicalPlan> {
+        // convert to Expr for validate_schema_satisfies_exprs
+        let exprs = expr
+            .iter()
+            .filter_map(|e| match e {
+                SelectExpr::Expression(expr) => Some(expr.to_owned()),
+                _ => None,
+            })
+            .collect::<Vec<_>>();
+        self.validate_schema_satisfies_exprs(input.schema(), &exprs)?;
```
Comment (jayzhan211) [inline datafusion/sql/src/select.rs:734]: maybe we can change the params to SelectExpr?

File: datafusion/core/src/dataframe/mod.rs [hunk 2]
```diff
@@ -342,13 +343,28 @@ impl DataFrame {
...
+
+        let expressions = expr_list
+            .iter()
+            .filter_map(|e| match e {
+                SelectExpr::Expression(expr) => Some(expr.clone()),
+                _ => None,
+            })
+            .collect::<Vec<_>>();
+
+        let window_func_exprs = find_window_exprs(&expressions);
```
Comment (jayzhan211) [inline datafusion/core/src/dataframe/mod.rs:361]: it matches Expr::Window

File: datafusion/sql/src/select.rs (hunk 1 above)
Comment (jayzhan211) [reply datafusion/sql/src/select.rs:734]: it doesn't check wildcard case so we don't need to change params to SelectExpr

**Review by goldmedal — APPROVED** [review]
Thanks @jayzhan211. It looks great 👍

**Comment by jayzhan211** [comment]
Thanks @goldmedal
