### PR TITLE
fix: `array_slice` panics

### LINKED ISSUE #10425: `array_slice` panics with `stride=1`
### Describe the bug

See reproduction for specific example that triggers the panic.

Some combination of a column with varying size arrays, a negative start index, a positive end index, and stride explicitly set to one triggers the panic.

### To Reproduce

```sql
CREATE TEMPORARY VIEW data3 AS VALUES ([1.0, 2.0, 3.0, 3.0]), ([4.0, 5.0, 3.0]), ([6.0]);
❯ select * from data3;
+----------------------+
| column1              |
+----------------------+
| [1.0, 2.0, 3.0, 3.0] |
| [4.0, 5.0, 3.0]      |
| [6.0]                |
+----------------------+
❯ select array_slice(column1, -1, 2, 1) from data3;
```
```console
thread 'main' panicked at /Users/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arrow-data-51.0.0/src/transform/primitive.rs:31:43:
range end index 9 out of range for slice of length 8
```

### Expected behavior

Doesn't panic. Works just like the `stride=1` default.

```
+-----------------------------------------------+
| array_slice(data3.column1,Int64(-1),Int64(2)) |
+-----------------------------------------------+
| []                                            |
| []                                            |
| [6.0]                                         |
```

### Additional context

This was found upgrading `datafusion-python`: https://github.com/apache/datafusion-python/pull/669

### PR DESCRIPTION
**Pull request by jonahgao**
## Which issue does this PR close?

Closes #10425.

## Rationale for this change

Note:  Negative `from` or `to` implies counting from the end of the list and both are standardized to the corresponding positive index.

When `from` is greater than `to` and `stride` is a positive, the following loop becomes infinite, until the `index` becomes excessively large and panics.

https://github.com/apache/datafusion/blob/842f3933e3496a022984c2a37254475a3bcde1bf/datafusion/functions-array/src/extract.rs#L468-L478

The fix is to return an empty list directly in this situation.

## What changes are included in this PR?
Fix panic.

## Are these changes tested?
Yes

## Are there any user-facing changes?
No

### CODE REVIEW

File: datafusion/functions-array/src/extract.rs [hunk 1]
```diff
@@ -418,19 +418,16 @@ where
...
-            }
+            // Default stride is 1 if not provided
             let stride = stride.unwrap_or(1);
             if stride.is_zero() {
                 return exec_err!(
                     "array_slice got invalid stride: {:?}, it cannot be 0",
                     stride
                 );
-            } else if from <= to && stride.is_negative() {
+            } else if (from <= to && stride.is_negative())
```
Comment (jonahgao) [inline datafusion/functions-array/src/extract.rs:428]: When `from` is equal to `to`, it should not return an empty list.
The fix for it is not included in this PR, it has been added to issue #10548.

**Review by alamb — APPROVED** [review]
Thank you @jonahgao

**Comment by jonahgao** [comment]
Thank you for reviewing @alamb
