### PR TITLE
fix: correct date_trunc for times before the epoch

### LINKED ISSUE #18334: Non-constant `DATE_TRUNC` expression regression
### Describe the bug

On DF 50, `DATE_TRUNC` function sometimes returns off-by-1 result.

### To Reproduce

```
DataFusion CLI v50.3.0
> select d as datetime,
DATE_TRUNC('hour', d) as hour_from_column,
DATE_TRUNC('hour', (timestamp '1900-06-15 07:09:00')) as hour_from_const
from (values (timestamp '1900-06-15 07:09:00')) as T(d);
+---------------------+---------------------+---------------------+
| datetime            | hour_from_column    | hour_from_const     |
+---------------------+---------------------+---------------------+
| 1900-06-15T07:09:00 | 1900-06-15T08:00:00 | 1900-06-15T07:00:00 |
+---------------------+---------------------+---------------------+
1 row(s) fetched. 
Elapsed 0.006 seconds.
```

### Expected behavior

`hour_from_column` should have the same value as `hour_from_const`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mhilton**
## Which issue does this PR close?

- Closes #18334.

## What changes are included in this PR?

The array-based implementation of date_trunc can produce incorrect results for negative timestamps (i.e. dates before 1970-01-01). Check for any such incorrect values and compensate accordingly.

Running the date_trunc benchmark suggests this fix introduces an ~9% performance cost.

```
date_trunc_minute_1000  time:   [1.7424 µs 1.7495 µs 1.7583 µs]
                        change: [+7.9289% +8.5950% +9.1955%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) low mild
  1 (1.00%) high mild
  2 (2.00%) high severe
```

## Are these changes tested?

Yes, an SLT is added based on the issue.

### CODE REVIEW

**Comment by alamb** [comment]
@mhilton  notes this is very similar to the fix in 
- https://github.com/apache/datafusion/pull/13204

**Comment by alamb** [comment]
> Running the date_trunc benchmark suggests this fix introduces an ~9% performance cost.

I think we need to have correctness before performance. I'll run the benchmarks on this PR to be sure

**Comment by alamb** [comment]
cc @waynexia @sadboy

**Comment by alamb** [comment]
I have also created a PR to try and get the performance back
- https://github.com/apache/datafusion/pull/18360

File: datafusion/functions/src/datetime/date_trunc.rs [hunk 1]
```diff
@@ -482,9 +482,20 @@ fn general_date_trunc_array_fine_granularity<T: ArrowTimestampType>(
...
+        // it is possible that the truncated value is actually later
+        // than the original value. Correct any such cases by
+        // subtracting `unit`.
+        let too_late = arrow::compute::kernels::cmp::gt(&array, &input)?;
+        let array = if too_late.true_count() > 0 {
+            let earlier = arrow::compute::kernels::numeric::sub(&array, &unit)?;
+            arrow::compute::kernels::zip::zip(&too_late, &earlier, &array)?
+        } else {
+            array
+        };
```
Comment (findepi) [inline datafusion/functions/src/datetime/date_trunc.rs]: in scalar terms, what we're computing it

```
value - (value floor mod unit)
```

can we maybe express this logic directly?

Comment (findepi) [reply datafusion/functions/src/datetime/date_trunc.rs]: in rust terms "floor mod" is probably `rem_euclid`

https://doc.rust-lang.org/std/primitive.i64.html#method.rem_euclid

Comment (alamb) [reply datafusion/functions/src/datetime/date_trunc.rs]: > can we maybe express this logic directly

That is an excellent point -- I think we could use the code in https://github.com/apache/datafusion/pull/18360 to do so directly

Comment (findepi) [reply datafusion/functions/src/datetime/date_trunc.rs]: https://github.com/apache/datafusion/pull/18360 looks more complicated to me.
We can fix semantics fix without that, or with that. Either way works.

Comment (findepi) [reply datafusion/functions/src/datetime/date_trunc.rs]: #18360 turns `unit` into a primitive, which really helps write the logic `value - (value floor mod unit)`. it can become a one-step vectorized operation. that's the part of that PR we should copy over here.

#18360 goes further with `try_unary_mut_or_clone`. that's the part orthogonal to semantic fix and can be a follow-up

File: datafusion/sqllogictest/test_files/timestamps.slt [hunk 2]
```diff
@@ -1687,6 +1687,13 @@ SELECT DATE_TRUNC('second', '2022-08-03 14:38:50Z');
 ----
 2022-08-03T14:38:50
 
+# DATE_TRUNC handling of times before the unix epoch (issue 18334)
+query PPP
+SELECT d, DATE_TRUNC('hour', d), DATE_TRUNC('hour', TIMESTAMP '1900-06-15 07:09:00')
+FROM (VALUES (TIMESTAMP '1900-06-15 07:09:00')) AS t(d);
```
Comment (sadboy) [inline datafusion/sqllogictest/test_files/timestamps.slt]: Let's test the whole lot:
```suggestion
select d as datetime,
       DATE_TRUNC('year', d) as year,
       DATE_TRUNC('quarter', d) as quarter,
       DATE_TRUNC('month', d) as month,
       DATE_TRUNC('week', d) as week,
       DATE_TRUNC('day', d) as day,
       DATE_TRUNC('hour', d) as hour,
       DATE_TRUNC('minute', d) as minute,
       DATE_TRUNC('second', d) as second
       DATE_TRUNC('microsecond', d) as microsecond
       DATE_TRUNC('millisecond', d) as millisecond
from (values (timestamp '1900-06-15 07:31:23'),
             (timestamp '1970-01-01 00:00:00'),
             (timestamp '2024-12-31 23:39:01')) as T(d)
```

**Comment by alamb** [comment]
🤖 `./gh_compare_branch_bench.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/gh_compare_branch_bench.sh) Running
Linux aal-dev 6.14.0-1017-gcp #18~24.04.1-Ubuntu SMP Tue Sep 23 17:51:44 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing issue-18334 (f70abf14f80414687087f3753290328d9b667c59) to 6cc73fa24d0d4d4006375e3bc20d6c267fc55c44 [diff](https://github.com/apache/datafusion/compare/6cc73fa24d0d4d4006375e3bc20d6c267fc55c44..f70abf14f80414687087f3753290328d9b667c59)
BENCH_NAME=date_trunc
BENCH_COMMAND=cargo bench --bench date_trunc
BENCH_FILTER=
BENCH_BRANCH_NAME=issue-18334
Results will be posted here when complete

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                     issue-18334                            main
-----                     -----------                            ----
date_trunc_minute_1000    1.20      5.8±0.02µs        ? ?/sec    1.00      4.8±0.01µs        ? ?/sec
```


</p>
</details>

**Comment by mhilton** [comment]
Running a totally unscientific benchmark on my laptop suggests that the newer version based on review suggestions is significantly faster than main.

```
date_trunc_minute_1000  time:   [643.37 ns 644.49 ns 645.64 ns]
                        change: [-59.158% -59.017% -58.870%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) high mild
  2 (2.00%) high severe
```

**Comment by alamb** [comment]
> Running a totally unscientific benchmark on my laptop suggests that the newer version based on review suggestions is significantly faster than main.

Sweet! I have queued up a benchmark to reproduce

File: datafusion/functions/src/datetime/date_trunc.rs [hunk 3]
```diff
@@ -456,37 +457,40 @@ fn general_date_trunc_array_fine_granularity<T: ArrowTimestampType>(
...
-        let array = arrow::compute::kernels::numeric::div(&array, &unit)?;
-        let array = arrow::compute::kernels::numeric::mul(&array, &unit)?;
-        let array = arrow::compute::cast(&array, original_type)?;
-        Ok(array)
+        let unit = unit.get();
+        let array = PrimitiveArray::<T>::from_iter_values_with_nulls(
+            array
+                .values()
+                .iter()
+                .map(|v| *v - i64::rem_euclid(*v, unit)),
```
Comment (alamb) [inline datafusion/functions/src/datetime/date_trunc.rs:490]: this is pretty fancy

File: datafusion/functions/src/datetime/date_trunc.rs (hunk 1 above)
Comment (alamb) [reply datafusion/functions/src/datetime/date_trunc.rs]: > https://github.com/apache/datafusion/pull/18360 goes further with try_unary_mut_or_clone. that's the part orthogonal to semantic fix and can be a follow-up 

Agreed -- I will work on that as a follow up

File: datafusion/functions/src/datetime/date_trunc.rs (hunk 3 above)
Comment (waynexia) [reply datafusion/functions/src/datetime/date_trunc.rs:490]: Interesting. Another example for LLVM understand SIMD better than developers 🙂‍↕️

**Comment by alamb** [comment]
🤖 `./gh_compare_branch_bench.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/gh_compare_branch_bench.sh) Running
Linux aal-dev 6.14.0-1017-gcp #18~24.04.1-Ubuntu SMP Tue Sep 23 17:51:44 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing issue-18334 (587856d282c6e5fadc1cbffc16577c5ec2c357a4) to 6cc73fa24d0d4d4006375e3bc20d6c267fc55c44 [diff](https://github.com/apache/datafusion/compare/6cc73fa24d0d4d4006375e3bc20d6c267fc55c44..587856d282c6e5fadc1cbffc16577c5ec2c357a4)
BENCH_NAME=date_trunc
BENCH_COMMAND=cargo bench --bench date_trunc
BENCH_FILTER=
BENCH_BRANCH_NAME=issue-18334
Results will be posted here when complete

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                     issue-18334                            main
-----                     -----------                            ----
date_trunc_minute_1000    1.00      2.9±0.01µs        ? ?/sec    1.66      4.8±0.01µs        ? ?/sec
```


</p>
</details>

**Comment by alamb** [comment]
Fixing bug and making it 60% faster. Great team effort. Thank you @mhilton @findepi @waynexia
