### PR TITLE
fix duplicated schema name error from count wildcard

### LINKED ISSUE #14855: Regression since 45.0.0: `select count(), count(*)` does not work
### Describe the bug

@jonahgao noticed this in https://github.com/apache/datafusion/pull/14824

This query works in DataFusion 44 and 45:
```sql
select count(), count(*);
```

However, it does not work on main (what would become DataFusion 46)

```
DataFusion CLI v45.0.0
> select count(), count(*);
Error during planning: Projections require unique expression names but the expression "count(*)" at position 0 and "count(*)" at position 1 have the same name. Consider aliasing ("AS") one of them.
>
```

### To Reproduce

_No response_

### Expected behavior

The query should produce the same results as in datafusion 44 and 45

```shell
andrewlamb@Andrews-MacBook-Pro-2:~/Software/datafusion$ ~/Downloads/datafusion-cli-44
DataFusion CLI v44.0.0
> select count(), count(*);
+---------+----------+
| count() | count(*) |
+---------+----------+
| 1       | 1        |
+---------+----------+
1 row(s) fetched.
Elapsed 0.013 seconds.

>
\q
andrewlamb@Andrews-MacBook-Pro-2:~/Software/datafusion$ ~/Downloads/datafusion-cli-45
DataFusion CLI v45.0.0
> select count(), count(*);
+---------+----------+
| count() | count(*) |
+---------+----------+
| 1       | 1        |
+---------+----------+
1 row(s) fetched.
Elapsed 0.013 seconds.

```

### Additional context

It is likely this was introduced by
- https://github.com/apache/datafusion/pull/14689

There is more discussion on
- https://github.com/apache/datafusion/pull/14824

### PR DESCRIPTION
**Pull request by jayzhan211**
## Which issue does this PR close?

We convert count(constant) i.e. count(2) to count(*) in previous PR
so `select count(1) * count(2)` produces duplicated schema name error given both are `count(*)` in schema name.

- Closes https://github.com/apache/datafusion/issues/14853
- Closes #14855

## Rationale for this change

Instead of converting `count()` and `count(*)` to `count(1)`. We makes `count()` possible as a replacement of count wildcard. In this case, `count(1)` can be treated as the normal case (although it is equivalent to wildcard), without this we need to handle many different complex case for `count(1)` such as `count(cast(1 as i32))`. The schema name is much more consistent with DuckDB too.

## What changes are included in this PR?

Implement count with zero arg in aggregate function level.

`count()` -> count()
`count(*)` -> count()
`count(1)` -> count(1)
`count(2)` -> count(2)

### CODE REVIEW

File: datafusion/physical-plan/src/aggregates/mod.rs [hunk 1]
```diff
@@ -1231,6 +1233,13 @@ fn evaluate(
     expr: &[Arc<dyn PhysicalExpr>],
     batch: &RecordBatch,
 ) -> Result<Vec<ArrayRef>> {
+    // handle count() case
+    if expr.is_empty() {
+        return Ok(vec![
+            Arc::new(Int64Array::from(vec![1; batch.num_rows()])) as ArrayRef
```
Comment (jayzhan211) [inline datafusion/physical-plan/src/aggregates/mod.rs:1239]: This is equivalent to `count(1)` case

File: datafusion/physical-plan/src/aggregates/no_grouping.rs [hunk 2]
```diff
@@ -219,23 +220,26 @@ fn aggregate_batch(
...
-            let values = &expr
-                .iter()
-                .map(|e| {
-                    e.evaluate(&batch)
-                        .and_then(|v| v.into_array(batch.num_rows()))
-                })
-                .collect::<Result<Vec<_>>>()?;
+            // Handle count(*) case
+            let values = if expr.is_empty() {
+                vec![Arc::new(Int64Array::from(vec![1; n_rows])) as ArrayRef]
```
Comment (jayzhan211) [inline datafusion/physical-plan/src/aggregates/no_grouping.rs:228]: This is equivalent to count(1) case

**Comment by jayzhan211** [comment]
fix the extended test in main branch

File: datafusion/functions-aggregate/src/count.rs [hunk 3]
```diff
@@ -148,6 +155,15 @@ impl AggregateUDFImpl for Count {
         "count"
     }
 
+    // In AggregateFunctionPlanner, wildcard is converted to count(1)
+    //
+    // count() -> count(1)
```
Comment (jonahgao) [inline datafusion/functions-aggregate/src/count.rs:160]: We still can't run `select count(), count(*)`.
```sh
> select count(), count(*);
Error during planning: Projections require unique expression names but the expression "count(*)" at position 0 and "count(*)" at position 1 have the same name. Consider aliasing ("AS") one of them
```
I suspect that using aliases to restore the original names is a simpler fix. I tried doing this on https://github.com/jonahgao/datafusion/commit/08206fd5179da6efbc12ec2f863d4b3bf5baa6ef.

Comment (jayzhan211) [reply datafusion/functions-aggregate/src/count.rs:160]: I think this is quite different than the test covered in extended test.

`select count() * count(*);` is executable now.

But I agree, this query should be executable too

**Comment by alamb** [comment]
I ran the sqllogictests locally and verified this patch fixes them:

```shell
INCLUDE_SQLITE=true cargo test --profile release-nonlto --test sqllogictests
...
...
    Finished `release-nonlto` profile [optimized] target(s) in 1m 48s
     Running bin/sqllogictests.rs (target/release-nonlto/deps/sqllogictests-f643b09b33355b16)
Completed 705 test files in 6 minutes
andrewlamb@Andrews-MacBook-Pro-2:~/Software/datafusion$
```

File: datafusion/functions-aggregate/src/count.rs (hunk 3 above)
Comment (alamb) [reply datafusion/functions-aggregate/src/count.rs:160]: BTW I verified that both of those queries run in `datafusion` 44 and 45 but does not run on main. Thus this is a regression.

I agree with @jayzhan211  that the issue is different than what is causing the sqlite tests to fail in main

I have filed a ticket to track this:
- https://github.com/apache/datafusion/issues/14855

File: datafusion/functions-aggregate/src/count.rs [hunk 4]
```diff
@@ -550,8 +571,6 @@ impl AggregateUDFImpl for Count {
 fn is_count_wildcard(args: &[Expr]) -> bool {
```
Comment (alamb) [inline datafusion/functions-aggregate/src/count.rs:571]: this function now feels a bit redundant as it is just checking for `.empty()`

File: datafusion/physical-plan/src/aggregates/mod.rs (hunk 1 above)
Comment (jonahgao) [reply datafusion/physical-plan/src/aggregates/mod.rs:1239]: It seems that this function is not only used by `count`. I'm not quite sure about the impact of this change.
Ideally, this function should not involve the logic of any specific aggregation function.

File: datafusion/sqllogictest/test_files/aggregate.slt [hunk 5]
```diff
@@ -6296,6 +6299,54 @@ physical_plan
...
+statement count 0
+create table t (a int) as values (1), (2);
+
+query I
+select count() from t;
+----
+2
+
+query I
+select count(1) * count(2) from t;
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/aggregate.slt:6316]: Could you also please add a test that shows just the values of `count(2)`

For example
```sql
select count(1), count(2), count(1) * count(2) from t;
```

File: datafusion/sqllogictest/test_files/aggregate.slt [hunk 6]
```diff
@@ -6296,6 +6299,54 @@ physical_plan
...
+select count(1) * count(*) from t;
+----
+4
+
+query I
+select count(*) * count(*) from t;
+----
+4
+
+query I
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/aggregate.slt:6330]: Likewise here it would be nice to have `count(1)` and `count(2)` individually tested

File: datafusion/functions-aggregate/src/count.rs (hunk 3 above)
Comment (jonahgao) [reply datafusion/functions-aggregate/src/count.rs:160]: I think they have the same root cause, which is the rewriting by `AggregateFunctionPlanner` introducing duplicate names, and they could all be fixed by using aliases. The old `CountWildcardRule` used `NamePreserver` to achieve a similar effect.

File: datafusion/sql/tests/sql_integration.rs [hunk 7]
```diff
@@ -1460,13 +1460,13 @@ fn select_simple_aggregate_with_groupby_and_column_is_in_aggregate_and_groupby()
 #[test]
 fn select_simple_aggregate_with_groupby_can_use_positions() {
     quick_test(
-        "SELECT state, age AS b, count(1) FROM person GROUP BY 1, 2",
+        "SELECT state, age AS b, count() FROM person GROUP BY 1, 2",
```
Comment (alamb) [inline datafusion/sql/tests/sql_integration.rs:1463]: Why is this test changed?

**Review by alamb — APPROVED** [review]
Thanks @jayzhan211  -- I think this PR is an improvement (it fixes the extended tests)

However, I agree with @jonahgao that it might be better to not change the physical implementation of `count()` and instead rewrite `count(*)` to `count(1) as "count(*)"` 

That would likely also fix https://github.com/apache/datafusion/issues/14855

**Comment by findepi** [comment]
> We convert count(constant) i.e. count(2) to count(*) in previous PR
> so `select count(1) * count(2)` produces duplicated schema name error given both are `count(*)` in schema name.

Can we just give names to generated projections to avoid duplicated schema name error?

or is the problem solvable only at the physical planning level?

**Comment by alamb** [comment]
> > We convert count(constant) i.e. count(2) to count(*) in previous PR
> > so `select count(1) * count(2)` produces duplicated schema name error given both are `count(*)` in schema name.
> 
> Can we just give names to generated projections to avoid duplicated schema name error?
> 
> or is the problem solvable only at the physical planning level?

I think we can fix this with the generated projections (and I think it is what @jonahgao  is implemented)

File: datafusion/core/tests/dataframe/mod.rs [hunk 8]
```diff
@@ -2455,7 +2455,7 @@ async fn test_count_wildcard_on_sort() -> Result<()> {
     let ctx = create_join_context()?;
 
     let sql_results = ctx
-        .sql("select b,count(*) from t1 group by b order by count(*)")
+        .sql("select b,count(1) from t1 group by b order by count(1)")
```
Comment (jayzhan211) [inline datafusion/core/tests/dataframe/mod.rs:2458]: count_all() is count(1) now, so we need to change to count(1) to have a consistent name (count(*) is count(a) AS count(*) now).

File: datafusion/core/tests/dataframe/dataframe_functions.rs [hunk 9]
```diff
@@ -1145,9 +1145,9 @@ async fn test_count_wildcard() -> Result<()> {
         .build()
         .unwrap();
 
-    let expected = "Sort: count(*) ASC NULLS LAST [count(*):Int64]\
-    \n  Projection: count(*) [count(*):Int64]\
-    \n    Aggregate: groupBy=[[test.b]], aggr=[[count(*)]] [b:UInt32, count(*):Int64]\
+    let expected = "Sort: count(Int64(1)) ASC NULLS LAST [count(Int64(1)):Int64]\
```
Comment (jayzhan211) [inline datafusion/core/tests/dataframe/dataframe_functions.rs:1148]: count_all() is count(1)

**Comment by findepi** [comment]
> I think we can fix this with the generated projections (and I think it is what @jonahgao is implemented)

@alamb  I am not sure what is the "generated projections"?
then, would we still need changes from this?

**Comment by jayzhan211** [comment]
anyone familiar with sqlite test?

I update test with `--complete`, ends up the format like what we have in datafusion `0 Null`.

But execute it again comes out error
```
External error: query result mismatch:
[SQL] SELECT ALL - + COUNT ( * ) * + + 51 AS col2, - CAST ( NULL AS INTEGER ) FROM tab0 AS cor0 WHERE NULL <> - col0
[Diff] (-expected|+actual)
    0 NULL
at ../../datafusion-testing/data/sqlite/index/random/1000/slt_good_0.slt:6333

External error: query result mismatch:
[SQL] SELECT DISTINCT - COUNT ( * ), CAST ( NULL AS INTEGER ) FROM tab0 AS cor0 WHERE NOT NULL IS NULL
[Diff] (-expected|+actual)
    0 NULL
at ../../datafusion-testing/data/sqlite/index/random/1000/slt_good_7.slt:7248

External error: query result mismatch:
[SQL] SELECT DISTINCT 99, + 16 * + + 75 AS col3 FROM tab0 WHERE + 15 IS NOT NULL
[Diff] (-expected|+actual)
    99 1200
at ../../datafusion-testing/data/sqlite/index/random/1000/slt_good_8.slt:21878
```

Screenshot 2025-02-25 at 6 02 34 PM

@Omega359 Have you experienced similar issue before?

**Comment by jonahgao** [comment]
> But execute it again comes out error

SQLite tests use a value-wise format. Their file headers have a control directive: `control resultmode valuewise`

**Comment by alamb** [comment]
> > But execute it again comes out error
> 
> SQLite tests use a value-wise format. Their file headers have a control directive: `control resultmode valuewise`

I think you need to use this script to update the expected output:
- https://github.com/apache/datafusion/blob/main/datafusion/sqllogictest/regenerate_sqlite_files.sh

We should probably document that somewhere in the sqllite readme file

**Comment by Omega359** [comment]
> We should probably document that somewhere in the sqllite readme file

https://github.com/apache/datafusion/blob/1fedb4e000293e3997b477d87d575f3a5453171e/datafusion/sqllogictest/README.md?plain=1#L253

**Comment by Omega359** [comment]
> anyone familiar with sqlite test?
> 
> I update test with `--complete`, ends up the format like what we have in datafusion `0 Null` and not
> 
> ```
> 0
> Null
> ```
> 
> But execute it again comes out error
> 
> ```
> External error: query result mismatch:
> [SQL] SELECT ALL - + COUNT ( * ) * + + 51 AS col2, - CAST ( NULL AS INTEGER ) FROM tab0 AS cor0 WHERE NULL <> - col0
> [Diff] (-expected|+actual)
>     0 NULL
> at ../../datafusion-testing/data/sqlite/index/random/1000/slt_good_0.slt:6333
> 
> External error: query result mismatch:
> [SQL] SELECT DISTINCT - COUNT ( * ), CAST ( NULL AS INTEGER ) FROM tab0 AS cor0 WHERE NOT NULL IS NULL
> [Diff] (-expected|+actual)
>     0 NULL
> at ../../datafusion-testing/data/sqlite/index/random/1000/slt_good_7.slt:7248
> 
> External error: query result mismatch:
> [SQL] SELECT DISTINCT 99, + 16 * + + 75 AS col3 FROM tab0 WHERE + 15 IS NOT NULL
> [Diff] (-expected|+actual)
>     99 1200
> at ../../datafusion-testing/data/sqlite/index/random/1000/slt_good_8.slt:21878
> ```
> 
> Screenshot 2025-02-25 at 6 02 34 PM
> 
> @Omega359 Have you experienced similar issue before?

Is this to just get the tests passing for now by having those failures be ignored? Otherwise I am unsure why you would want to regenerate the results ... were they not correct before?

**Comment by jayzhan211** [comment]
Is it possible to run with `INCLUDE_SQLITE=true cargo test --profile release-nonlto --test sqllogictests -- --complete` like what we have in sqllogictest. Why do we have `control resultmode valuewise`?

**Comment by jayzhan211** [comment]
We convert count wildcard in planner which is before plan built unlike previously we convert after plan is created. There are many changes required

**Comment by Omega359** [comment]
> Run with `PG_URI="postgresql://postgres:postgres@$POSTGRES_HOST:$POSTGRES_PORT/db_test" bash datafusion/sqllogictest/regenerate_sqlite_files.sh`

> error[E0407]: method `shutdown` is not a member of trait `sqllogictest::AsyncDB`
>    --> datafusion/sqllogictest/src/engines/postgres_engine/mod.rs:309:5
>     |
> 309 | /     async fn shutdown(&mut self) {
> 310 | |         if let Some(client) = self.client.take() {
> 311 | |             drop(client);
> ...   |
> 316 | |     }
>     | |_____^ not a member of trait `sqllogictest::AsyncDB`

First I've ever see that. I'll try to look into it tonight

**Comment by alamb** [comment]
> error[E0407]: method `shutdown` is not a member of trait `sqllogictest::AsyncDB`


This is likely related to a change made in the most recent version of sqllogictests . Here was the relevant change in DataFusion:
- https://github.com/apache/datafusion/pull/14598

**Comment by alamb** [comment]
I think the issue is that the runner in  https://github.com/Omega359/sqllogictest-rs is based on an older version of the sqllogictests than we use in datafusion. 

I have an idea for a workaround, but longer term we probably need to make the update eaiser to maintaine

**Comment by Omega359** [comment]
> I think the issue is that the runner in https://github.com/Omega359/sqllogictest-rs is based on an older version of the sqllogictests than we use in datafusion.
> 
> I have an idea for a workaround, but longer term we probably need to make the update eaiser to maintaine

That is exactly what I was thinking and hopefully will fix tonight. I think a decent short-term fix is to 'lock' the sqllogictest-rs dependency version and add a comment that any update to it will require a full run of the regenerate script before committing.

Long term ideally would be to improve my changes to my fork of sqllogictest-rs such that they would be suitable to submit a PR to that project. That is not an insignificant amount of work to be honest and I'm a bit thin on time for the next month or two.

**Comment by alamb** [comment]
> > I think the issue is that the runner in https://github.com/Omega359/sqllogictest-rs is based on an older version of the sqllogictests than we use in datafusion.
> > I have an idea for a workaround, but longer term we probably need to make the update eaiser to maintaine
> 
> That is exactly what I was thinking and hopefully will fix tonight. I think a decent short-term fix is to 'lock' the sqllogictest-rs dependency version and add a comment that any update to it will require a full run of the regenerate script before committing.
> 
> Long term ideally would be to improve my changes to my fork of sqllogictest-rs such that they would be suitable to submit a PR to that project. That is not an insignificant amount of work to be honest and I'm a bit thin on time for the next month or two.

Makes sesne -- thank you

BTW I have another interim workaround here:
- https://github.com/apache/datafusion/pull/14881

I think we can use that to regenerate the output for this PR

**Comment by jayzhan211** [comment]
After merging https://github.com/apache/datafusion-testing/pull/7 and update commit, I guess is good to go

**Comment by alamb** [comment]
I just merged https://github.com/apache/datafusion-testing/pull/7

File: datafusion/core/tests/dataframe/mod.rs (hunk 8 above)
Comment (alamb) [reply datafusion/core/tests/dataframe/mod.rs:2458]: I had to double check -- the reason this needs to change is that the test is comparing again a dataframe built with `count_all()` which now uses `count(1)` 

Though maybe we could change `count_all()` to return `count(1) as "count(*)"` so it would be consistent with older versions?

File: datafusion/expr/src/expr_rewriter/mod.rs [hunk 10]
```diff
@@ -286,6 +286,7 @@ pub struct NamePreserver {
 
 /// If the qualified name of an expression is remembered, it will be preserved
 /// when rewriting the expression
+#[derive(Debug)]
```
Comment (alamb) [inline datafusion/expr/src/expr_rewriter/mod.rs:289]: 💯

**Review by alamb — COMMENTED** [review]
Thank you @jayzhan211

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
I think we need to update the datafusion-testing pin -- closing/reopening this PR to rerun the tests to make sure

File: datafusion/core/tests/dataframe/mod.rs (hunk 8 above)
Comment (jayzhan211) [reply datafusion/core/tests/dataframe/mod.rs:2458]:
```
  left: "+---------------+------------------------------------------------------------------------------------------------------------+\n| plan_type     | plan                                                                                                       |\n+---------------+------------------------------------------------------------------------------------------------------------+\n| logical_plan  | Projection: t1.b, count(*)                                                                                 |\n|               |   Sort: count(Int64(1)) AS count(*) AS count(*) ASC NULLS LAST                                             |\n|               |     Projection: t1.b, count(Int64(1)) AS count(*), count(Int64(1))                                         |\n|               |       Aggregate: groupBy=[[t1.b]], aggr=[[count(Int64(1))]]                                                |\n|               |         TableScan: t1 projection=[b]                                                                       |\n| physical_plan | ProjectionExec: expr=[b@0 as b, count(*)@1 as count(*)]                                                    |\n|               |   SortPreservingMergeExec: [count(Int64(1))@2 ASC NULLS LAST]                                              |\n|               |     SortExec: expr=[count(Int64(1))@2 ASC NULLS LAST], preserve_partitioning=[true]                        |\n|               |       ProjectionExec: expr=[b@0 as b, count(Int64(1))@1 as count(*), count(Int64(1))@1 as count(Int64(1))] |\n|               |         AggregateExec: mode=FinalPartitioned, gby=[b@0 as b], aggr=[count(Int64(1))]                       |\n|               |           CoalesceBatchesExec: target_batch_size=8192                                                      |\n|               |             RepartitionExec: partitioning=Hash([b@0], 12), input_partitions=12                             |\n|               |               RepartitionExec: partitioning=RoundRobinBatch(12), input_partitions=1                        |\n|               |                 AggregateExec: mode=Partial, gby=[b@0 as b], aggr=[count(Int64(1))]                        |\n|               |                   DataSourceExec: partitions=1, partition_sizes=[1]                                        |\n|               |                                                                                                            |\n+---------------+------------------------------------------------------------------------------------------------------------+"
 right: "+---------------+-----------------------------------------------------------------------------------+\n| plan_type     | plan                                                                              |\n+---------------+-----------------------------------------------------------------------------------+\n| logical_plan  | Sort: count(Int64(1)) ASC NULLS LAST                                              |\n|               |   Aggregate: groupBy=[[t1.b]], aggr=[[count(Int64(1))]]                           |\n|               |     TableScan: t1 projection=[b]                                                  |\n| physical_plan | SortPreservingMergeExec: [count(Int64(1))@1 ASC NULLS LAST]                       |\n|               |   SortExec: expr=[count(Int64(1))@1 ASC NULLS LAST], preserve_partitioning=[true] |\n|               |     AggregateExec: mode=FinalPartitioned, gby=[b@0 as b], aggr=[count(Int64(1))]  |\n|               |       CoalesceBatchesExec: target_batch_size=8192                                 |\n|               |         RepartitionExec: partitioning=Hash([b@0], 12), input_partitions=12        |\n|               |           RepartitionExec: partitioning=RoundRobinBatch(12), input_partitions=1   |\n|               |             AggregateExec: mode=Partial, gby=[b@0 as b], aggr=[count(Int64(1))]   |\n|               |               DataSourceExec: partitions=1, partition_sizes=[1]                   |\n|               |                                                                                   |\n+---------------+-----------------------------------------------------------------------------------+"
```

This is the err after changing it back to count(*)

Comment (jayzhan211) [reply datafusion/core/tests/dataframe/mod.rs:2458]: 😕 
```
query I
SELECT count(*) order by count(*);
----
1

query TT
explain SELECT count(*) order by count(*);
----
logical_plan
01)Projection: count(*)
02)--Sort: count(Int64(1)) AS count(*) AS count(*) ASC NULLS LAST
03)----Projection: count(Int64(1)) AS count(*), count(Int64(1))
04)------Aggregate: groupBy=[[]], aggr=[[count(Int64(1))]]
05)--------EmptyRelation
physical_plan
01)ProjectionExec: expr=[1 as count(*)]
02)--PlaceholderRowExec

```

**Comment by alamb** [comment]
NM I think things are clean now

**Review by alamb — APPROVED** [review]
Thanks @jayzhan211  -- since this PR fixes a bunch of tests and gets the main branch back to green, I am going to merge it. We can then address the `count_all()` function name as a follow on PR

File: datafusion/core/tests/dataframe/mod.rs (hunk 8 above)
Comment (alamb) [reply datafusion/core/tests/dataframe/mod.rs:2458]: - Filed  https://github.com/apache/datafusion/issues/14894 to track

**Comment by jayzhan211** [comment]
Thanks @alamb. I will file related issue as follow-up

**Comment by alamb** [comment]
The tests are green again on main!
https://github.com/apache/datafusion/actions/runs/13545248421/job/37855153112
