### PR TITLE
consider volatile function in simply_expression

### LINKED ISSUE #13060: SimplifyExpressions should not consider volatile expressions equal for rewrites
### Describe the bug

Currently we do not consider the volatility of expressions in SimplifyExpressions. This leads us to doing rewrites that might change the results and lead to unexpected behavior.

### To Reproduce

Consider the following query:
```
> explain select * from VALUES (1), (2) where random() = 0 OR (column1 = 2 AND random() = 0);
+---------------+---------------------------------------------+
| plan_type     | plan                                        |
+---------------+---------------------------------------------+
| logical_plan  | Filter: random() = Float64(0)               |
|               |   Values: (Int64(1)), (Int64(2))            |
| physical_plan | CoalesceBatchesExec: target_batch_size=8192 |
|               |   FilterExec: random() = 0                  |
|               |     ValuesExec                              |
|               |                                             |
+---------------+---------------------------------------------+
2 row(s) fetched. 
Elapsed 0.013 seconds.
```
The predicate get simplified into `random() = 0`

### Expected behavior

The predicate should not be simplified so we deduplicat the volatile expressions. 
```
> explain select * from VALUES (1), (2) where random() = 0 OR (column1 = 2 AND random() = 0);
+---------------+----------------------------------------------------------------------------------+
| plan_type     | plan                                                                             |
+---------------+----------------------------------------------------------------------------------+
| logical_plan  | Filter: random() = Float64(0)  OR column1 = Int64(2) AND  random() = Float64(0)  |
|               |   Values: (Int64(1)), (Int64(2))                                                 |
| physical_plan | CoalesceBatchesExec: target_batch_size=8192                                      |
|               |   FilterExec: random() = 0                                                       |
|               |     ValuesExec                                                                   |
|               |                                                                                  |
+---------------+----------------------------------------------------------------------------------+
2 row(s) fetched. 
Elapsed 0.013 seconds.
```

### Additional context

We can not exclude volatile expressions outright from simplification as we would still like the simplify for example following predicate
```
> explain select * from VALUES (1), (2) where column1 = 2 OR (column1 = 2 AND random() = 0);
+---------------+---------------------------------------------+
| plan_type     | plan                                        |
+---------------+---------------------------------------------+
| logical_plan  | Filter: column1 = Int64(2)                  |
|               |   Values: (Int64(1)), (Int64(2))            |
| physical_plan | CoalesceBatchesExec: target_batch_size=8192 |
|               |   FilterExec: column1@0 = 2                 |
|               |     ValuesExec                              |
|               |                                             |
+---------------+---------------------------------------------+
2 row(s) fetched. 
Elapsed 0.015 seconds.
```
As it does not change the result.

### PR DESCRIPTION
**Pull request by Lordworms**
## Which issue does this PR close?

Closes #13060

### CODE REVIEW

**Review by jonathanc-n — APPROVED** [review]
this lgtm!

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs [hunk 1]
```diff
@@ -835,40 +835,38 @@ impl<'a, S: SimplifyInfo> TreeNodeRewriter for Simplifier<'a, S> {
...
-            }) if is_op_with(And, &left, &right) => Transformed::yes(*right),
+            }) if is_op_with(And, &left, &right)? => Transformed::yes(*right),
             // Eliminate common factors in conjunctions e.g
             // (A AND B) OR (A AND C) -> A AND (B OR C)
             Expr::BinaryExpr(BinaryExpr {
                 left,
                 op: Or,
                 right,
-            }) if has_common_conjunction(&left, &right) => {
+            }) if has_common_conjunction(&left, &right)? => {
```
Comment (peter-toth) [inline datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:863]: This doesn't seem correct. It is ok to just check the presence of common non-volatile expressions in `has_common_conjunction()` to trigger simplification, but you need to deal with volatile expressions during simplification too and don't extract them as common.

E.g. can you please add a test like `column1 = 2 AND random() = 0 OR column1 = 2 AND random() = 0`?

File: datafusion/optimizer/src/simplify_expressions/utils.rs [hunk 2]
```diff
@@ -341,3 +355,49 @@ pub fn distribute_negation(expr: Expr) -> Expr {
         _ => Expr::Negative(Box::new(expr)),
     }
 }
+
```
Comment (peter-toth) [inline datafusion/optimizer/src/simplify_expressions/utils.rs:358]: Do we need this? We already have an `Expr::is_volatile()` API.

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs (hunk 1 above)
Comment (Lordworms) [reply datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:863]: I checked postgresql and duckdb, they seems to merge the volatile expressions
image
image

File: datafusion/optimizer/src/simplify_expressions/utils.rs (hunk 2 above)
Comment (Lordworms) [reply datafusion/optimizer/src/simplify_expressions/utils.rs:358]: I'll refactor that

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs [hunk 3]
```diff
@@ -1681,9 +1679,15 @@ impl<'a, S: SimplifyInfo> TreeNodeRewriter for Simplifier<'a, S> {
     }
 }
 
-fn has_common_conjunction(lhs: &Expr, rhs: &Expr) -> bool {
+fn has_common_conjunction(lhs: &Expr, rhs: &Expr) -> Result<bool, DataFusionError> {
     let lhs: HashSet<&Expr> = iter_conjunction(lhs).collect();
-    iter_conjunction(rhs).any(|e| lhs.contains(&e))
+    iter_conjunction(rhs).try_fold(false, |acc, e| {
```
Comment (peter-toth) [inline datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:1684]: This still looks a bit ugly. I mean, we just look for the first non-volatile expression and don't want to iterate over all expressions.

Actually, I think I made a mistake when I added `is_volatile()` with return type `Result<bool>`:
https://github.com/apache/datafusion/blob/e22d23113f549a90483bbf161add84eba08510fd/datafusion/expr/src/expr.rs#L1581-L1583
As the closure we provide to `exists()` can't return an error it would be safe to unwrap the result and return only `bool`.

@alamb, do you think we can fix `Expr::is_volatile()`, it would be an API breaking change though, to make it simpler and so we can keep using `any()` here?

Comment (Lordworms) [reply datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs]: I have refactored it, Thanks for your review

Comment (peter-toth) [reply datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs]: Looks good to me, thanks for the fix.

Maybe we can consider changing the return type of `Expr::is_volatile()` in a follow-up.

**Review by peter-toth — APPROVED** [review]

File: datafusion/sqllogictest/test_files/explain.slt [hunk 4]
```diff
@@ -411,3 +411,40 @@ logical_plan
 physical_plan
 01)ProjectionExec: expr=[{c0:1,c1:2.3,c2:abc} as struct(Int64(1),Float64(2.3),Utf8("abc"))]
 02)--PlaceholderRowExec
+
+
+
+
+query TT
```
Comment (eejbyfeldt) [inline datafusion/sqllogictest/test_files/explain.slt:418]: Any reason for not adding these as unit tests in the `expr_simplifier` module instead? 

They feel quite output place in file called `explain.slt`.

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs (hunk 3 above)
Comment (eejbyfeldt) [reply datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs]: > Maybe we can consider changing the return type of `Expr::is_volatile()` in a follow-up PR.

I think this PR would be much cleaner if we fixed the signature of that first. But I guess the important thing is that we do fix it before it spreads keeps spreading.

File: datafusion/sqllogictest/test_files/explain.slt (hunk 4 above)
Comment (Lordworms) [reply datafusion/sqllogictest/test_files/explain.slt:418]: Sure

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs [hunk 5]
```diff
@@ -1681,9 +1690,14 @@ impl<'a, S: SimplifyInfo> TreeNodeRewriter for Simplifier<'a, S> {
     }
 }
 
-fn has_common_conjunction(lhs: &Expr, rhs: &Expr) -> bool {
-    let lhs: HashSet<&Expr> = iter_conjunction(lhs).collect();
-    iter_conjunction(rhs).any(|e| lhs.contains(&e))
+fn has_common_conjunction(lhs: &Expr, rhs: &Expr) -> Result<bool, DataFusionError> {
+    let lhs_set: HashSet<&Expr> = iter_conjunction(lhs).collect();
+    for e in iter_conjunction(rhs) {
+        if lhs_set.contains(&e) && !e.is_volatile()? {
```
Comment (alamb) [inline datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:1696]: I looked a little more at `Expr::is_volatile` and I actually think it can't return any errors. If we changed the signature I think this PR would be significantly simpler

**Review by alamb — APPROVED** [review]
Thanks @Lordworms @findepi and @peter-toth 

I agree with @eejbyfeldt  in https://github.com/apache/datafusion/pull/13128/files#r1822606751 that we should add some unit tests in datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs in addition to the explain .slt test

I also have a proposal that I think would simplify this PR: https://github.com/apache/datafusion/pull/13206

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs [hunk 6]
```diff
@@ -3980,4 +3994,69 @@ mod tests {
...
+
+            assert_eq!(simplify(expr.clone()), expr);
+        }
+
+        {
+            let expr = col("column1")
+                .eq(lit(2))
+                .or(col("column1").eq(lit(2)).and(rand.clone().eq(lit(0))));
+
+            assert_eq!(simplify(expr), col("column1").eq(lit(2)));
```
Comment (alamb) [inline datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:4044]: It would seem to me this should still be the same thing -- namely that we shouldn't remove the `rand() = 0` condition 🤔

**Review by alamb — COMMENTED** [review]
Thanks @Lordworms

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs (hunk 6 above)
Comment (alamb) [reply datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:4044]: However, this PR still seems like it is an improvement over what is on main so we could potentially fix this in a follow on PR

Comment (Lordworms) [reply datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:4044]: Could be something wrong here, let me double check

Comment (Lordworms) [reply datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:4044]: I think here should remove the rand() = 0 since we must fulfill the column1 = 2 first? according to the description in the issue?  Don't know if I got it wrong....
image

Comment (Lordworms) [reply datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:4044]: Also Happy Halloween!

**Comment by alamb** [comment]
I double checked that this PR compiles after we merge up from main, so let's get it in

**Comment by alamb** [comment]
I merged up from main to resolve a logical conflict with this PR

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs (hunk 3 above)
Comment (alamb) [reply datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs]: I changed the signature in https://github.com/apache/datafusion/pull/13206 which caused a logical conflict in this PR (failed to compile) and then I updated this PR to use the new signature

As @eejbyfeldt  predicated, the PR became much cleaner

File: datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs (hunk 6 above)
Comment (alamb) [reply datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs:4028]: > Also Happy Halloween!

image

**Comment by alamb** [comment]
Thanks again @Lordworms  and @eejbyfeldt
