### PR TITLE
Enforce explicit opt-in for `WITHIN GROUP` syntax in aggregate UDAFs

### LINKED ISSUE #18109: `WITHIN GROUP` needs to be more strict
### Describe the bug

This should not work:

```sql
> select sum(num) within group (order by num) from '/Users/jeffrey/Downloads/test.csv';
+------------------------------------------------------------------------------------------------------------+
| sum(/Users/jeffrey/Downloads/test.csv.num) ORDER BY [/Users/jeffrey/Downloads/test.csv.num ASC NULLS LAST] |
+------------------------------------------------------------------------------------------------------------+
| 750                                                                                                        |
+------------------------------------------------------------------------------------------------------------+
1 row(s) fetched.
Elapsed 0.011 seconds.
```

`WITHIN GROUP` should be allowed only for ordered set aggregate functions (see #12824)

Postgres for reference:

```sql
postgres=# select sum(salary) within group (order by salary) from employees;
ERROR:  function sum(numeric, numeric) does not exist
LINE 1: select sum(salary) within group (order by salary) from emplo...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
postgres=# select sum() within group (order by salary) from employees;
ERROR:  sum is not an ordered-set aggregate, so it cannot have WITHIN GROUP
LINE 1: select sum() within group (order by salary) from employees;
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

See these comments:

- https://github.com/apache/datafusion/pull/17805#issuecomment-3413963574
- https://github.com/apache/datafusion/pull/17805#issuecomment-3413977907

### PR DESCRIPTION
**Pull request by kosiew**
## Which issue does this PR close?

Closes #18109.

## Rationale for this change

Previously, the SQL planner accepted `WITHIN GROUP` clauses for all aggregate UDAFs, even those that did not explicitly support ordered-set semantics. This behavior was too permissive and inconsistent with PostgreSQL. For example, queries such as `SUM(x) WITHIN GROUP (ORDER BY x)` were allowed, even though `SUM` is not an ordered-set aggregate.

This PR enforces stricter validation so that only UDAFs that explicitly return `true` from `supports_within_group_clause()` may use `WITHIN GROUP`. All other aggregates now produce a clear planner error when this syntax is used.

## What changes are included in this PR?

* Added type alias `WithinGroupExtraction` to simplify complex tuple return types used by helper functions.
* Introduced a new helper method `extract_and_prepend_within_group_args` to centralize logic for handling `WITHIN GROUP` argument rewriting.
* Updated the planner to:

  * Validate that only UDAFs with `supports_within_group_clause()` can accept `WITHIN GROUP`.
  * Prepend `WITHIN GROUP` ordering expressions to function arguments only for supported ordered-set aggregates.
  * Produce clear error messages when `WITHIN GROUP` is used incorrectly.
* Added comprehensive unit tests verifying correct behavior and failure cases:

  * `WITHIN GROUP` rejected for non-ordered-set aggregates (`MIN`, `SUM`, etc.).
  * `WITHIN GROUP` accepted for ordered-set aggregates such as `percentile_cont`.
  * Validation for named arguments, multiple ordering expressions, and semantic conflicts with `OVER` clauses.
* Updated SQL logic tests (`aggregate.slt`) to reflect new rejection behavior.
* Updated documentation:

  * `aggregate_functions.md` and developer docs to clarify when and how `WITHIN GROUP` can be used.
  * `upgrading.md` to inform users of this stricter enforcement and migration guidance.

## Are these changes tested?

✅ Yes.

* New tests in `sql_integration.rs` validate acceptance, rejection, and argument behavior of `WITHIN GROUP` for both valid and invalid cases.
* SQL logic tests (`aggregate.slt`) include negative test cases confirming planner rejections.

## Are there any user-facing changes?

✅ Yes.

* Users attempting to use `WITHIN GROUP` with regular aggregates (e.g. `SUM`, `AVG`, `MIN`, `MAX`) will now see a planner error:

  > `WITHIN GROUP is only supported for ordered-set aggregate functions`

* Documentation has been updated to clearly describe `WITHIN GROUP` semantics and provide examples of valid and invalid usage.

No API-breaking changes were introduced; only stricter planner validation and improved error messaging.

### CODE REVIEW

File: datafusion/sql/src/expr/function.rs [hunk 1]
```diff
@@ -212,6 +213,11 @@ impl FunctionArgs {
     }
 }
 
+// Type alias to simplify very complex tuple return types used by helper
+// functions in this module. Using a named alias reduces the type complexity
+// shown in compiler errors and improves readability.
```
Comment (Jefffrey) [inline datafusion/sql/src/expr/function.rs]: These comments feel overly verbose

Also having this type alias so far away from its only usage feels odd to me

File: datafusion/sql/src/expr/function.rs [hunk 2]
```diff
@@ -490,31 +496,35 @@ impl<S: ContextProvider> SqlToRel<'_, S> {
...
+                    return plan_err!(
+                        "WITHIN GROUP is only supported for ordered-set aggregate functions"
+                    );
+                }
+
+                // If the UDAF opted into WITHIN GROUP handling, convert the
+                // WITHIN GROUP ordering into sort expressions and prepend the
+                // ordering expressions to the function argument list (as unnamed
+                // args). This helper centralizes the argument-prepending protocol
+                // so it's easier to maintain and reason about.
```
Comment (Jefffrey) [inline datafusion/sql/src/expr/function.rs]: Ditto for these comments

File: datafusion/sql/src/expr/function.rs [hunk 3]
```diff
@@ -807,6 +817,41 @@ impl<S: ContextProvider> SqlToRel<'_, S> {
...
+    fn extract_and_prepend_within_group_args(
+        &self,
+        within_group: Vec<OrderByExpr>,
+        args: Vec<Expr>,
+        arg_names: Vec<Option<String>>,
+        schema: &DFSchema,
+        planner_context: &mut PlannerContext,
+    ) -> Result<WithinGroupExtraction> {
+        let mut args = args;
+        let mut arg_names = arg_names;
```
Comment (Jefffrey) [inline datafusion/sql/src/expr/function.rs]:
```suggestion
        mut args: Vec<Expr>,
        mut arg_names: Vec<Option<String>>,
        schema: &DFSchema,
        planner_context: &mut PlannerContext,
    ) -> Result<WithinGroupExtraction> {
```

File: datafusion/sql/tests/sql_integration.rs
Comment (Jefffrey) [inline datafusion/sql/tests/sql_integration.rs:1]: I'm not sure adding these tests here are necessary; SLTs should be sufficient and I believe some of the tests added here are already in SLTs, e.g.

https://github.com/apache/datafusion/blob/d57e215f95fb2a015a825ceec1849edb32d189da/datafusion/sqllogictest/test_files/aggregate.slt#L174-L179

File: docs/source/user-guide/sql/aggregate_functions.md [hunk 4]
```diff
@@ -48,6 +48,28 @@ FROM employees;
...
+```sql
+percentile_cont(0.5) WITHIN GROUP (ORDER BY value)
+```
+
+Example (invalid usage — planner will error):
+
+```sql
+-- This will fail: SUM is not an ordered-set aggregate
+SELECT SUM(x) WITHIN GROUP (ORDER BY x) FROM t;
+```
```
Comment (Jefffrey) [inline docs/source/user-guide/sql/aggregate_functions.md:79]: If we decide to add this to our documentation we should be explicit about which functions are ordered set aggregates. As it is, the user cannot tell by this alone.

File: datafusion/sql/src/expr/function.rs (hunk 1 above)
Comment (kosiew) [reply datafusion/sql/src/expr/function.rs]: Removed the comment.
Moving the alias closer to fn `extract_and_prepend_within_group_args` generated this compiler error
`error[E0658]: inherent associated types are unstable`

File: datafusion/sql/src/expr/function.rs (hunk 2 above)
Comment (kosiew) [reply datafusion/sql/src/expr/function.rs]: Amended to be more succinct.

File: datafusion/sql/src/expr/function.rs (hunk 1 above)
Comment (kosiew) [reply datafusion/sql/src/expr/function.rs]: On a stable Rust release, this errors is resolved by moving the type alias outside of the impl block and making it a top-level type alias

File: datafusion/sql/tests/sql_integration.rs
Comment (kosiew) [reply datafusion/sql/tests/sql_integration.rs:1]: Removed the tests that are already covered in slt.

File: docs/source/user-guide/sql/aggregate_functions.md (hunk 4 above)
Comment (kosiew) [reply docs/source/user-guide/sql/aggregate_functions.md:79]: >ordered-set aggregate functions (for example, percentile and rank-like aggregations) to specify the ordering
of inputs that the aggregate relies on. In DataFusion, only aggregate functions that explicitly opt into
ordered-set semantics via their implementation will accept `WITHIN GROUP`; attempting to use `WITHIN GROUP`

I thought this part gave a good indication of ordered set aggregate functions.

**Comment by kosiew** [comment]
> Can I ask how much of this PR was LLM generated? I see a lot of hallmarks of LLM generated code.

Thank you for your patient review and feedback.

image

I use VS Code with Copilot Pro, but I always review, adapt, and test everything before opening a PR.
The final code reflects my design and review decisions.

File: docs/source/user-guide/sql/aggregate_functions.md (hunk 4 above)
Comment (Jefffrey) [reply docs/source/user-guide/sql/aggregate_functions.md:79]: The problem here is it is not an explicit list, and refers to rank as an ordered-set aggregation when it isn't in DataFusion. My concern here is that it'll inform the users that ordered-set aggregate functions _exist_, but isn't exactly clear which ones we have.

File: docs/source/library-user-guide/upgrading.md [hunk 5]
```diff
@@ -360,6 +360,27 @@ The accompanying `AggregateUDF::is_ordered_set_aggregate` has also been renamed
 No functionality has been changed with regards to this method; it still refers only to permitting use of `WITHIN GROUP`
 SQL syntax for the aggregate function.
 
+### Planner now requires explicit opt-in for WITHIN GROUP syntax
```
Comment (Jefffrey) [inline docs/source/library-user-guide/upgrading.md]: Need to move this to v52 section now

Comment (kosiew) [reply docs/source/library-user-guide/upgrading.md]: Moved the above into the new section
