### PR TITLE
fix: fix elapsed_compute metric in ParquetSink to report encoding time only 

### LINKED ISSUE #21797: ParquetSink's elapsed_compute accounts for IO, not just CPU
### Describe the bug

`ParquetSink` registers an `elapsed_compute` metric, but its value is a single wall-clock timer spanning the entire write phase — from before writer tasks are spawned to after they all join (`file_format.rs`, `spawn_writer_tasks_and_join`):

```rust
let write_start = Instant::now();
// spawn tasks — each calls writer.write(&batch) then writer.close()
// join all tasks
elapsed_compute.add_elapsed(write_start);
```

This means `elapsed_compute` conflates three fundamentally different contributors:

1. **Upstream backpressure** — time blocked on `rx.recv().await` waiting for the upstream plan to produce the next `RecordBatch`
2. **CPU encoding** — Arrow → Parquet serialisation and column compression
3. **Object-store I/O** — `BufWriter` flushes at row-group boundaries and the final `close()`

`DataSinkExec::metrics()` is a transparent passthrough to `ParquetSink::metrics()`, so this value propagates unchanged up the plan tree. Any metrics walker that sums `ElapsedCompute` across operators will misattribute I/O latency and upstream wait time as compute time.

### To Reproduce

_No response_

### Expected behavior

`elapsed_compute` for `ParquetSink` should reflect only CPU time (Arrow → Parquet encoding and compression), consistent with how `elapsed_compute` is used in other operators. I/O time and upstream wait should either be tracked separately or excluded.

### Additional context

`ParquetSink` has two write paths: a **sequential path** (one `AsyncArrowWriter` per file, active when `allow_single_file_parallelism = false`) and a **parallel path** (`output_single_parquet_file_parallelized`, active when `allow_single_file_parallelism = true`,
which is the default).

**Sequential path.** `AsyncArrowWriter` encodes batches one at a time. Encoding is synchronous (`sync_writer.write(batch)?`) and I/O is async, occurring only at row-group flush boundaries and on `close()`. The two phases are clearly separated inside the crate, but `sync_writer` is a private field — DataFusion cannot time them independently without changes to `arrow-rs` or an interception point at the `AsyncFileWriter` layer.

**Parallel path.** Each column in each row group is encoded in its own tokio task. A separate task assembles completed row groups and flushes them to the object store via a raw `Box<dyn AsyncWrite>`. CPU encoding is distributed across concurrent tasks and the I/O and CPU work are interleaved within the same concatenation loop — there is no clean trait boundary to intercept.

### PR DESCRIPTION
**Pull request by fred1268**
## Which issue does this PR close?

- Closes #21797.

## Rationale for this change

`ParquetSink` registered an `elapsed_compute` metric using a single wall-clock timer that spanned the entire write operation — upstream batch wait, CPU Arrow→Parquet encoding, and object-store I/O all rolled into one number. This
made the metric misleading: it inflated `elapsed_compute` with I/O latency, which is inconsistent with how every other operator in DataFusion reports this metric (CPU time only).

## What changes are included in this PR?

Two write paths are fixed independently:

**Sequential path** (`allow_single_file_parallelism = false` or CDC enabled):
- A new `TimingWriter<W>` wrapper implements `AsyncFileWriter` and records wall-clock time spent in I/O calls (`write` / `complete`).
- The total time inside `writer.write()` and `writer.close()` is accumulated in `total_write_time`. After all tasks join, `elapsed_compute` is set to `total_write_time − io_time`, isolating pure Arrow→Parquet encoding time.

**Parallel path** (`allow_single_file_parallelism = true`, default):
- `encoding_time: Time` (a clone of the registered `elapsed_compute` metric) is threaded through the five-function call chain down to the two leaf sites: `writer.write()` in `column_serializer_task` and `writer.close()` in `spawn_rg_join_and_finalize_task`. Since `Time` is `Arc<AtomicUsize>`, all concurrent column tasks accumulate directly into the registered metric.
- Note: on the parallel path, `append_to_row_group()` in `concatenate_parallel_row_groups` is interleaved with I/O and cannot be cleanly isolated. It is excluded from `elapsed_compute`. This is acceptable since it operates on already-encoded data and represents a small fraction of total encoding CPU time.

## Are these changes tested?

Yes. Two tests are added/extended in `datafusion/core/src/dataframe/parquet.rs`:
- `test_parquet_sink_metrics_sequential` (new): verifies `elapsed_compute > 0` with `allow_single_file_parallelism = false`.
- `test_parquet_sink_metrics_parallel`: extended with an `elapsed_compute > 0` assertion (was previously missing for the parallel path).

The existing `test_parquet_sink_metrics` test (parallel path, default config) already asserted `elapsed_compute > 0` and continues to pass.

## Are there any user-facing changes?

No API changes. The `elapsed_compute` metric was already surfaced — this PR makes its value accurate rather than introducing a new metric.

### CODE REVIEW

File: datafusion/datasource-parquet/src/file_format.rs [hunk 1]
```diff
@@ -1339,8 +1375,10 @@ impl FileSink for ParquetSink {
             .with_category(MetricCategory::Bytes)
             .global_counter("bytes_written");
         let elapsed_compute = MetricBuilder::new(&self.metrics).elapsed_compute(0);
-
-        let write_start = datafusion_common::instant::Instant::now();
+        // Sequential path only: not registered in MetricsSet — used internally to
+        // compute elapsed_compute = total_write_time - io_time.
+        let total_write_time = Time::new();
+        let io_time = Time::new();
```
Comment (gabotechs) [inline datafusion/datasource-parquet/src/file_format.rs]: One of the things I see here is that the `elapsed_compute` metrics is completely wrong.

Measuring IO and compensating with `total_write_time` sounds like it can work, but it sounds like a patch for compensating the fact that `elapsed_compute` is not being measured correctly. It would be interesting to see if we can measure `elapsed_compute` correctly on the first place.

File: datafusion/datasource-parquet/src/file_format.rs [hunk 2]
```diff
@@ -1584,6 +1634,7 @@ fn spawn_rg_join_and_finalize_task(
                 .map_err(|e| DataFusionError::ExecutionJoin(Box::new(e)))??;
             let encoded_size = writer.get_estimated_total_bytes();
             rg_reservation.grow(encoded_size);
+            let _timer = encoding_time.timer();
             finalized_rg.push(writer.close()?);
```
Comment (gabotechs) [inline datafusion/datasource-parquet/src/file_format.rs:1609]: Isn't this just measuring the `writer.close()` method here? is there nothing to be measured in the tasks above?

EDIT: I see now that the `encoding_time` is also passed while instantiating the tasks. It's a bit messy, but I think it should work.

File: datafusion/datasource-parquet/src/file_format.rs (hunk 1 above)
Comment (gabotechs) [reply datafusion/datasource-parquet/src/file_format.rs]: In https://github.com/datafusion-contrib/datafusion-distributed we have this:

https://github.com/datafusion-contrib/datafusion-distributed/blob/2b6c918e0636e0645fafcc109252262f94d6c452/src/worker/worker_connection_pool.rs#L455-L486

Which allows to wrap any arbitrary future, something like this:

```rust
async move {
    // do some async work
}.with_elapsed_compute(elapsed_compute)
```

I could imagine how something similar could just be used here for properly measuring `elapsed_compute`, although the change would be bigger.

Comment (gabotechs) [reply datafusion/datasource-parquet/src/file_format.rs]: If you think this can help avoid the mess, it might be worth trying, otherwise, what you have here is an improvement.

File: datafusion/datasource-parquet/src/file_format.rs [hunk 3]
```diff
@@ -1599,6 +1650,7 @@ fn spawn_rg_join_and_finalize_task(
 /// on the next row group in parallel. So, parquet serialization is parallelized
 /// across both columns and row_groups, with a theoretical max number of parallel tasks
 /// given by n_columns * num_row_groups.
+#[expect(clippy::too_many_arguments)]
 fn spawn_parquet_parallel_serialization_task(
```
Comment (gabotechs) [inline datafusion/datasource-parquet/src/file_format.rs]: oh no... clippy kicked in.

I see this file was a bit messy before.

Comment (gabotechs) [reply datafusion/datasource-parquet/src/file_format.rs]: Here is one idea about how to make it better:

I see a pattern where `file_write_tasks` is set only once on the `FileSink::spawn_writer_tasks_and_join` implementation, and then task are spawned for it.

I see that several of the arguments passed to these longs functions are not per-path, and are instead global to the whole `FileSink::spawn_writer_tasks_and_join` call, for example: `schema`, `props`, `skip_arrow_metadata`, `parallel_options`, `pool`.

One idea that comes to mind is to gather all these "contextual" variables in a struct that is responsible for task spawning, for example:

```rust
struct FileWriteTasks {
    file_write_tasks: JoinSet<
        std::result::Result<(Path, ParquetMetaData), DataFusionError>,
    >,
    schema: SchemaRef,
    properties: WriterProperties,
    parquet_options: ParallelParquetWriterOptions,
    pool: Arc<dyn MemoryPool>
}

impl FileWriteTasks {
    fn spawn_task_foo(&mut self) {
        self.file_write_tasks.spawn(async move {
            ...
        })
    }

    fn spawn_task_bar(&mut self) {
        self.file_write_tasks.spawn(async move {
            ...
        })
    }
}
```

That would allow the contextual variables to not need to be threaded around all the way down the callstack.

Actually, your new `encoding_time`, etc... variables fall in this category of "contextual variables" that are in scope for the whole duration of `FileSink::spawn_writer_tasks_and_join`, so they could be just fields of `FileWriteTasks`

File: datafusion/datasource-parquet/src/file_format.rs (hunk 1 above)
Comment (fred1268) [reply datafusion/datasource-parquet/src/file_format.rs]: This is indeed a good idea. I implemented your `datafusion-distributed` proposal as consistently as possible. Let me know if this is not what you had in mind.

File: datafusion/datasource-parquet/src/file_format.rs (hunk 2 above)
Comment (fred1268) [reply datafusion/datasource-parquet/src/file_format.rs:1609]: No action on my side as I understand it.

File: datafusion/datasource-parquet/src/file_format.rs (hunk 3 above)
Comment (fred1268) [reply datafusion/datasource-parquet/src/file_format.rs]: I didn't like this, but wanted to have some community thinking about this. I implemented a slightly different version of your proposal, but I did not include `encoding_time` inside of it since what's inside are more _input parameters_ and `encoding_time` is more of an output parameter. So I left it outside the struct. Let me know if this is what you had in mind.

File: datafusion/datasource-parquet/src/file_format.rs [hunk 4]
```diff
@@ -1175,6 +1181,70 @@ impl DisplayAs for ParquetSink {
...
+///
+/// Used by the sequential write path so that `elapsed_compute` reflects
+/// pure Arrow→Parquet encoding time, automatically excluding object-store
+/// I/O latency without requiring a separate subtraction step.
+///
+/// Note: uses `pin-project` rather than `pin-project-lite` in order to
+/// support `PinnedDrop`, which ensures accumulated time is flushed even
+/// if the future is cancelled (dropped before completion).
+#[pin_project(PinnedDrop)]
+struct ElapsedComputeFuture<T> {
```
Comment (gabotechs) [inline datafusion/datasource-parquet/src/file_format.rs]: Nice! as this is pretty general, I think a good place to put this is `datafusion/datafusion/physical-expr-common/src/metrics/elapsed_compute.rs`, and we can import it here.

I see other places in the codebase that are actually doing something similar:
- https://github.com/apache/datafusion/blob/main/datafusion/physical-plan/src/memory.rs#L404-L404

I'd do a couple of things to the doc comment:
1) State that this will measure all the time the future spends polling, so everything happening under the `Future::poll` scope is measured.
2) As this will be exposed as part of the public API, Some doc comments to `ElapsedComputeFutureExt::with_elapsed_compute` could be useful.

File: datafusion/datasource-parquet/src/file_format.rs [hunk 5]
```diff
@@ -1175,6 +1181,70 @@ impl DisplayAs for ParquetSink {
...
+
+impl<O, F: Future<Output = O>> Future for ElapsedComputeFuture<F> {
+    type Output = O;
+
+    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
+        let self_projected = self.project();
+        let start = Instant::now();
+        let result = self_projected.inner.poll(cx);
+        *self_projected.curr += start.elapsed();
+        if result.is_ready() {
```
Comment (gabotechs) [inline datafusion/datasource-parquet/src/file_format.rs]: Tracking the consumed time is done separately from the `elapsed_compute: Time` metric, and it's only on a ready future or on Drop that the two `elapsed_compute: Time` and `curr: Duration` are synced.

This is for avoiding doing atomic operations under a `Future::poll` implementation that can afford to perform mutations.
- The good thing about this, is better performance as no synchronization primitives sit in between future polls
- The bad thing is, the reported `elapsed_compute` is only available at the end, once the future has fully finished.

I'd document this decision so that if someone thinks there's a better approach they have all the cards on the table.

**Review by gabotechs — APPROVED** [review]
Looks pretty good! +1 from me, I just left a comment about placement of the `ElapsedComputeFuture` struct and public API exposure. I think this is something valuable that anyone that wants to track their elapsed compute in their nodes can use.

File: datafusion/datasource-parquet/src/file_format.rs (hunk 4 above)
Comment (fred1268) [reply datafusion/datasource-parquet/src/file_format.rs]: I did move the file and add the relevant comments as you suggested.

File: datafusion/datasource-parquet/src/file_format.rs (hunk 5 above)
Comment (fred1268) [reply datafusion/datasource-parquet/src/file_format.rs]: I tracked this rationale as a comment within the code.

**Comment by gabotechs** [comment]
Thanks @fred1268! merging this now
