### PR TITLE
fix: compound_field_access doesn't identifier qualifier.

### LINKED ISSUE #15118: Change in behavior for deep structure columns with the latest sql parser upgrade
### Describe the bug

with SQLParser 0.53, this works: 
```
SELECT * 
FROM
    (meta_asset_featurization AS asset_meta
    INNER JOIN meta_asset_summary_metrics AS asset_metrics ON (
        asset_meta.struct_field['substruct']['substruct'] = asset_metrics.struct_field['substruct']['substruct']
    ))

```

with SQLParser 0.54, this no longer works, the newly added `sql_compound_field_access_to_expr` interprets the `root` (in this case for example `asset_meta`) as a column name instead of a table. 
The solution (workaround) for SQLParser 0.54 is to do 
```
SELECT * 
FROM
    (meta_asset_featurization AS asset_meta
    INNER JOIN meta_asset_summary_metrics AS asset_metrics ON (
        asset_meta.struct_field.substruct.substruct = asset_metrics.struct_field.substruct.substruct
    ))
```

Is this intended ? I have tried to see the history, but unsure which behavior is correct. Since we do interpret the `[]` index access in the case of NOT having to specify the table correctly (so, if I have a single table and I specify directly the column `col['substruct']['substruct']` it works), why wouldn't this case work ? 

### To Reproduce

_No response_

### Expected behavior

Structure field access with either dot acess `.subfield` or subscript access`['subfield']` should work in the same way and yield the same result in all conditions

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chenkovsky**
## Which issue does this PR close?

- Closes #15118.

## Rationale for this change

In sql_compound_field_access_to_expr, datafusion doesn't check whether prefix can be merged into qualifier,
but in sql_compound_identifier_to_expr, it does. 

## What changes are included in this PR?

update sql_compound_field_access_to_expr to identify if a compound expression (like `a.b.c`) should be treated as a column reference with a qualifier (like `table.column`)

## Are these changes tested?

Unit test 

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/core/tests/sql/select.rs [hunk 1]
```diff
@@ -350,3 +350,45 @@ async fn test_version_function() {
 
     assert_eq!(version.value(0), expected_version);
 }
+
+#[tokio::test]
+async fn test_subscript() -> Result<()> {
```
Comment (jonahgao) [inline datafusion/core/tests/sql/select.rs:355]: This is more suitable as a sqllogictest test. Maybe we can move it to [struct.slt](https://github.com/apache/datafusion/blob/main/datafusion/sqllogictest/test_files/struct.slt) or [identifiers.slt](https://github.com/apache/datafusion/blob/main/datafusion/sqllogictest/test_files/identifiers.slt)

File: datafusion/sql/src/expr/mod.rs [hunk 2]
```diff
@@ -983,14 +983,102 @@ impl<S: ContextProvider> SqlToRel<'_, S> {
...
+    /// A tuple containing:
+    /// * The resolved root expression
+    /// * The remaining access chain that should be processed as field accesses
+    fn extract_root_and_access_chain(
+        &self,
+        root: SQLExpr,
+        access_chain: Vec<AccessExpr>,
+        schema: &DFSchema,
+        planner_context: &mut PlannerContext,
+    ) -> Result<(Expr, Vec<AccessExpr>)> {
```
Comment (jonahgao) [inline datafusion/sql/src/expr/mod.rs:1009]: I think it would be simpler to reuse `sql_compound_identifier_to_expr()`, like [this](https://github.com/jonahgao/datafusion/commit/8f5129997c40f3054b66a1fd4e877ccdf84ec996).

File: datafusion/core/tests/sql/select.rs (hunk 1 above)
Comment (jonahgao) [inline datafusion/core/tests/sql/select.rs:355]: This is more suitable as a sqllogictest test. Maybe we can move it to [struct.slt](https://github.com/apache/datafusion/blob/main/datafusion/sqllogictest/test_files/struct.slt) or [identifiers.slt](https://github.com/apache/datafusion/blob/main/datafusion/sqllogictest/test_files/identifiers.slt)
