### PR TITLE
fix: hash join tests with forced collisions

### LINKED ISSUE #11658: `join_inner_two`, `join_inner_one_two_parts_left` and `join_inner_one_two_parts_right` fail with `force_hash_collisions`
### Describe the bug

The `force_hash_collisions` feature flag is intended to ensure DataFusion works correctly even in the very unlikely event that hash values collide.

The new version of clippy in Rust 1.80 found we had not been running some tests with this flag  https://github.com/apache/datafusion/issues/11651

And it turns out when we started running the tests with the hash collision they failed

we commented them out in https://github.com/apache/datafusion/pull/11654 but we should really figure out why they failed

Maybe the test needs to be updated or maybe there is a real bug

### To Reproduce

Remove these lines from the tests mentioned above

```rust
    #[cfg(not(feature = "force_hash_collisions"))]
```

Then run 

```shell
cargo test -p datafusion-physical-plan --features=force_hash_collisions
```

### Expected behavior

Tests should pass 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by korowa**
## Which issue does this PR close?

Closes #11658.

## Rationale for this change

Some tests in `hash_join.rs` check the number of output batches, and since output batch for `HashJoinExec` is created while matching join keys against hash table built on build-side data (which includes only matching by hashes, comparing actual values is a next step in join execution), these tests are failing with forced collisions (due to equal hashes, all records are considered as matching).

This PR recovers hash join tests by adjusting the numbers of expected batches in case test is running with `force_hash_collisions` feature.

## What changes are included in this PR?

Different numbers of expected output batches for `force_hash_collisions` feature in hash join tests.

## Are these changes tested?

Yes

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/physical-plan/src/joins/hash_join.rs [hunk 1]
```diff
@@ -1964,12 +1960,21 @@ mod tests {
...
+            // in case batch_size is 1 - additional empty batch for remaining 3-2 row
+            let mut expected_batch_count = div_ceil(3, batch_size);
+            if batch_size == 1 {
+                expected_batch_count += 1;
+            }
+            expected_batch_count
+        } else {
+            // With hash collisions enabled, all records will match each other
+            // and filtered later.
+            // Expected number of matches = 9
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/hash_join.rs:1974]: nit I think the comment is redundant with the assert right below it
```suggestion
```

File: datafusion/physical-plan/src/joins/hash_join.rs [hunk 2]
```diff
@@ -2029,12 +2031,21 @@ mod tests {
...
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/hash_join.rs:2045]: Likewise this seems somewhat redundant (and same below)

```suggestion
```

**Review by alamb — APPROVED** [review]
Thank you @korowa

**Comment by alamb** [comment]
Thanks again @korowa  and @comphead
