### PR TITLE
fix: Add AWS environment variable checks for S3 tests

### LINKED ISSUE #17458: `datafusion-cli` tests fails locally
### Describe the bug

`datafusion-cli` tests are failing on the latest main (see the below commit hash)

```sh
yongting@Yongtings-MacBook-Pro-2 ~/C/datafusion (main=) [SIGINT]> git rev-parse --short HEAD
6a21b675a
yongting@Yongtings-MacBook-Pro-2 ~/C/datafusion (main=)> cargo test --package datafusion-cli
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.14s
     Running unittests src/lib.rs (target/debug/deps/datafusion_cli-98327d75a8e65845)

running 42 tests

... PASSED TESTS...

test catalog::tests::query_http_location_test ... ok
test exec::tests::create_object_store_table_s3 ... ok
test catalog::tests::query_gs_location_test ... ok
test object_storage::tests::s3_object_store_builder_default ... FAILED
test object_storage::tests::s3_object_store_builder_resolves_region_when_none_provided ... FAILED
test object_storage::tests::s3_object_store_builder_overrides_region_when_resolve_region_enabled ... FAILED
test exec::tests::copy_to_external_object_store_test ... FAILED
test catalog::tests::query_s3_location_test ... FAILED

failures:

---- object_storage::tests::s3_object_store_builder_default stdout ----
Error: ObjectStore(Generic { store: "S3", source: "Error getting credentials from provider: an error occurred while loading credentials: failed to load IMDS session token" })

---- object_storage::tests::s3_object_store_builder_resolves_region_when_none_provided stdout ----
Error: ObjectStore(Generic { store: "S3", source: "Error getting credentials from provider: an error occurred while loading credentials: failed to load IMDS session token" })

---- object_storage::tests::s3_object_store_builder_overrides_region_when_resolve_region_enabled stdout ----
Error: ObjectStore(Generic { store: "S3", source: "Error getting credentials from provider: an error occurred while loading credentials: failed to load IMDS session token" })

---- exec::tests::copy_to_external_object_store_test stdout ----
Error: ObjectStore(Generic { store: "S3", source: "Error getting credentials from provider: an error occurred while loading credentials: failed to load IMDS session token" })

---- catalog::tests::query_s3_location_test stdout ----
Error: ObjectStore(Generic { store: "S3", source: "Error getting credentials from provider: an error occurred while loading credentials: failed to load IMDS session token" })


failures:
    catalog::tests::query_s3_location_test
    exec::tests::copy_to_external_object_store_test
    object_storage::tests::s3_object_store_builder_default
    object_storage::tests::s3_object_store_builder_overrides_region_when_resolve_region_enabled
    object_storage::tests::s3_object_store_builder_resolves_region_when_none_provided

test result: FAILED. 37 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out; finished in 32.21s

error: test failed, to rerun pass `-p datafusion-cli --lib`
```

### To Reproduce

_No response_

### Expected behavior

It's better to let them pass without extra settings.

I checked they require certain env vars to be set in order to pass: https://github.com/apache/datafusion/blob/6a21b675ad75b84f2dcd61d4d8c0855282398f7b/.github/workflows/rust.yml#L319-L324

Perhaps we should skip those test if the env var is not set?

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Weijun-H**
## Which issue does this PR close?

- Closes #17458

## Rationale for this change
Skip related tests if the AWS envs is not set.

## Are these changes tested?
Yes

## Are there any user-facing changes?
No

### CODE REVIEW

File: datafusion-cli/src/object_storage.rs [hunk 1]
```diff
@@ -579,6 +579,8 @@ mod tests {
 
     #[tokio::test]
     async fn s3_object_store_builder_default() -> Result<()> {
+        check_aws_envs().await?;
```
Comment (2010YOUY01) [inline datafusion-cli/src/object_storage.rs]: This will make it continue execution even the env vars are not set, so these 3 tests in datafusion-cli are not skipped:

```sh

failures:

---- object_storage::tests::s3_object_store_builder_overrides_region_when_resolve_region_enabled stdout ----
aws envs not set, skipping s3 testError: ObjectStore(Generic { store: "S3", source: "Error getting credentials from provider: an error occurred while loading credentials: failed to load IMDS session token" })

---- object_storage::tests::s3_object_store_builder_default stdout ----
aws envs not set, skipping s3 testError: ObjectStore(Generic { store: "S3", source: "Error getting credentials from provider: an error occurred while loading credentials: failed to load IMDS session token" })

---- object_storage::tests::s3_object_store_builder_resolves_region_when_none_provided stdout ----
aws envs not set, skipping s3 testError: ObjectStore(Generic { store: "S3", source: "Error getting credentials from provider: an error occurred while loading credentials: failed to load IMDS session token" })


failures:
    object_storage::tests::s3_object_store_builder_default
    object_storage::tests::s3_object_store_builder_overrides_region_when_resolve_region_enabled
    object_storage::tests::s3_object_store_builder_resolves_region_when_none_provided

test result: FAILED. 39 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 16.43s

```

Comment (Weijun-H) [reply datafusion-cli/src/object_storage.rs]: fixed!

**Review by 2010YOUY01 — APPROVED** [review]
Thank you! I've tested it locally.

**Comment by Weijun-H** [comment]
Thanks @2010YOUY01 for reviewing
