### PR TITLE
Substrait join consumer should not merge nullability of join keys

### LINKED ISSUE #21124: Substrait join consumer produces incorrect logical plan
### Describe the bug

The substrait join consumer produces incorrect logical plan for queries like 
```sql
SELECT t1.id AS t1_id, t2.id AS t2_id, t1.val, t2.val
FROM t1
JOIN t2 ON t1.id = t2.id AND t1.val IS NOT DISTINCT FROM t2.val
```

where it assumes the null semantics of one of the join conditions to be the null semantics of the entire join

### To Reproduce

Convert this substrait plan - datafusion/substrait/tests/testdata/test_plans/mixed_join_equal_and_indistinct.json from https://github.com/apache/datafusion/pull/21121/changes

### Expected behavior

If a join with join_keys having mixed null handling i.e. a few join keys with `NullEqNull` and a few with `NullEqNothing` then the resulting outer join should preserve these semantics

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hareshkh**
## Which issue does this PR close?

- Closes #21124 

## Rationale for this change

When a Substrait join expression contains both equal and is_not_distinct_from predicates (e.g. Spark pushes a null-safe filter into a join that already has a regular equality key), the `split_eq_and_noneq_join_predicate_with_nulls_equality` function uses a single `nulls_equal_nulls` boolean that gets overwritten per-predicate. Whichever operator is processed last determines the `NullEquality` for all keys, silently dropping NULL-matching rows.

Since NullEquality is a join-level setting (not per-key) across all physical join implementations (HashJoinExec, SortMergeJoinExec, SymmetricHashJoinExec), the correct fix is to match DataFusion's own SQL planner behavior: demote IS NOT DISTINCT FROM keys to the join filter when mixed with Eq keys. This is already correctly handled for SQL as shown in [join_is_not_distinct_from.slt:L188](https://sourcegraph.com/r/github.com/apache/datafusion@2b7d4f9a5b005905b23128274ad37c3306ffcd15/-/blob/datafusion/sqllogictest/test_files/join_is_not_distinct_from.slt?L188)
```
# Test mixed equal and IS NOT DISTINCT FROM conditions
# The `IS NOT DISTINCT FROM` expr should NOT in HashJoin's `on` predicate
query TT
EXPLAIN SELECT t1.id AS t1_id, t2.id AS t2_id, t1.val, t2.val
FROM t1
JOIN t2 ON t1.id = t2.id AND t1.val IS NOT DISTINCT FROM t2.val
----
logical_plan
01)Projection: t1.id AS t1_id, t2.id AS t2_id, t1.val, t2.val
02)--Inner Join: t1.id = t2.id Filter: t1.val IS NOT DISTINCT FROM t2.val
03)----TableScan: t1 projection=[id, val]
04)----TableScan: t2 projection=[id, val]
```

## What changes are included in this PR?

`datafusion/substrait/src/logical_plan/consumer/rel/join_rel.rs`:
  - Collect eq_keys and indistinct_keys separately instead of using a single vec with an overwritable boolean
  - When both are present (mixed case), use eq_keys as equijoin keys with NullEqualsNothing and reconstruct the IsNotDistinctFrom expressions into the join filter
  - Return NullEquality directly instead of converting from bool

## Are these changes tested?

Yes, three levels of coverage:

1. Unit tests (join_rel.rs) — directly assert the output of split_eq_and_noneq_join_predicate_with_nulls_equality for eq-only, indistinct-only, mixed, and non-column-operand cases
2. Integration test (consumer_integration.rs) — loads a JSON-encoded Substrait plan with a JoinRel containing both operators through from_substrait_plan, executes it, and asserts 6 rows (including NULL=NULL matches)
3. Existing SLT (join_is_not_distinct_from.slt:179-205) — confirms the SQL planner already exhibits the same demotion behavior that this PR adds to the Substrait consumer

## Are there any user-facing changes?

No API changes. Substrait plans with mixed equal/is_not_distinct_from join predicates now correctly preserve null-safe semantics instead of silently dropping NULL-matching rows.

### CODE REVIEW

**Comment by hareshkh** [comment]
Hey @gabotechs, @alamb, @LiaCastaneda! would you like to take a look at this one please?

File: datafusion/substrait/src/logical_plan/consumer/rel/join_rel.rs [hunk 1]
```diff
@@ -89,49 +84,61 @@ pub async fn from_join_rel(
...
-                _ => accum_filters.push(expr.clone()),
             },
-            _ => accum_filters.push(expr.clone()),
+            _ => accum_filters.push(expr),
         }
     }
 
+    let (join_keys, null_equality) =
+        match (eq_keys.is_empty(), indistinct_keys.is_empty()) {
+            // Mixed: use eq_keys as equijoin keys, demote indistinct keys to filter
```
Comment (Satyr09) [inline datafusion/substrait/src/logical_plan/consumer/rel/join_rel.rs:121]: We unconditionally favour Eq keys here, but if we have a case where there exists multiple (say 4) `IS NOT DISTINCT FROM` column pairs and 1 `Eq` column pair, this demotes all 4 to filter and keeps just the 1 eq key, right? 

But, in this case, would the inverse (demote the single eq to filter) not allow more columns to participate in the hash partitioning/pruning and therefore be a bit more performant? 
More selective hash key = frwer candidate pairs survive and need fewer row-by-row filter evaluation, if I understand correctly?

File: datafusion/substrait/src/logical_plan/consumer/rel/join_rel.rs [hunk 2]
```diff
@@ -153,3 +160,104 @@ fn from_substrait_jointype(join_type: i32) -> datafusion::common::Result<JoinTyp
...
+            right: Box::new(col("b")),
+        });
+
+        let (keys, _, filter) =
+            split_eq_and_noneq_join_predicate_with_nulls_equality(expr);
+
+        assert!(keys.is_empty());
+        assert!(filter.is_some());
+    }
+}
```
Comment (Satyr09) [inline datafusion/substrait/src/logical_plan/consumer/rel/join_rel.rs:261]: Can we also add some tests for multiple `IS NOT DISTINCT FROM` keys being demoted simultaneously?

Also, in the integration tests - can we check for other types of joins (outer etc.)?

File: datafusion/substrait/tests/cases/consumer_integration.rs [hunk 3]
```diff
@@ -762,4 +762,40 @@ mod tests {
...
+        let proto = serde_json::from_reader::<_, Plan>(BufReader::new(
+            File::open(path).expect("file not found"),
+        ))
+        .expect("failed to parse json");
+        let ctx = SessionContext::new();
+        let plan = from_substrait_plan(&ctx.state(), &proto).await?;
+        let df = ctx.execute_logical_plan(plan).await?;
+        let results = df.collect().await?;
+        let total_rows: usize = results.iter().map(|b| b.num_rows()).sum();
+        assert_eq!(total_rows, 6);
```
Comment (Satyr09) [inline datafusion/substrait/tests/cases/consumer_integration.rs]: Just to make this regression test a bit stronger - can we check that the rows we expect to exist do?

File: datafusion/substrait/src/logical_plan/consumer/rel/join_rel.rs (hunk 1 above)
Comment (hareshkh) [reply datafusion/substrait/src/logical_plan/consumer/rel/join_rel.rs:121]: The optimiser currently already has this behaviour of favouring `Eq` predicates over `Indistinct` predicates. Added a SLT to confirm that behaviour - https://github.com/apache/datafusion/pull/21121/changes#diff-63fc43cf735eb03abd4d114cfbbf24982939425938a74b354fb7db6da7d499d7R305, and replicating that behaviour in this change.

I also think that selectivity is a function of data i.e. having a hash join on 3 `indistinct` keys could produce more data than 1 `eq` key.

**Comment by hareshkh** [comment]
Thanks for the review @Satyr09 - I have addressed all your comments.

File: datafusion/substrait/tests/cases/consumer_integration.rs [hunk 4]
```diff
@@ -33,6 +35,32 @@ mod tests {
...
+        let all_lines: Vec<&str> = pretty.trim().lines().collect();
+        let header = &all_lines[..3];
+        let mut data: Vec<&str> = all_lines[3..all_lines.len() - 1].to_vec();
+        data.sort();
+        header
+            .iter()
+            .copied()
+            .chain(data)
+            .collect::<Vec<_>>()
+            .join("\n")
```
Comment (gabotechs) [inline datafusion/substrait/tests/cases/consumer_integration.rs:63]: This seems to be truncating the footer (just the last line of the table that gives closure to it), making the assertion look like it's incomplete. How about re-adding the footer here, just so that it's clearer to readers that the `insta` assertions are actually complete and where not truncated?

Comment (hareshkh) [reply datafusion/substrait/tests/cases/consumer_integration.rs:63]: Thanks, added the footer now

**Comment by hareshkh** [comment]
Thanks for the review @gabotechs - I have addressed the comment as well.

**Comment by gabotechs** [comment]
Nice, I'll leave this open until tomorrow in case someone wants to chime in, otherwise good work!

**Comment by alamb** [comment]
Thank you @hareshkh and @gabotechs
