### PR TITLE
feat: Implement LeftMark join to fix subquery correctness issue

### LINKED ISSUE #13135: Decorrelated predicate subqueries with disjuncition has duplicated rows
### Describe the bug

In https://github.com/apache/datafusion/pull/12945 the emulation of an mark join has a bug when there is duplicate values in the subquery. This would be fixable by adding a distinct before the join. This can also be resolved by using a LeftMark join.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by eejbyfeldt**
## Which issue does this PR close?

Closes #13135

## Rationale for this change
In https://github.com/apache/datafusion/pull/12945 the emulation of an mark join has a bug when there is duplicate values in the subquery. This would be fixable by adding a distinct before the join. This can also be resolved by using a LeftMark join. The LeftMark join exists in several other query engines. This will help us produce correct answers for TPC-DS (https://github.com/apache/datafusion/issues/4763)

Note: This patch does not implement the full null semantics for the mark join
described in http://btw2017.informatik.uni-stuttgart.de/slidesandpapers/F1-10-37/paper_web.pdf which which will be needed if we and `ANY` subqueries. The version is this patch the mark column will only be true for had a match and false when no match was found, never `null`.

## What changes are included in this PR?
This patch instead implements a LeftMark join with the desired semantics and uses that. The LeftMark join will return a row for each in the left input with an additional column "mark" that is true if there was a match in the right input and false otherwise.

This join is then used in decorrelate predicate subqueries to simplify the
implementation and fix a correctness issue.

## Are these changes tested?
Yes, new unit and fuzz tests.

## Are there any user-facing changes?
Fix of correctness issue with decorrelated subqueries.

### CODE REVIEW

File: datafusion/common/src/join_type.rs [hunk 1]
```diff
@@ -113,6 +118,9 @@ pub enum JoinSide {
     Left,
     /// Right side of the join
     Right,
+    /// Neither side of the join, used for Mark joins where the mark column does not belong to
```
Comment (Dandandan) [inline datafusion/common/src/join_type.rs:121]: Is there such a thing as right mark join? If so, can we add a issue/TODO for it?

File: datafusion/physical-plan/src/joins/utils.rs [hunk 2]
```diff
@@ -1171,6 +1173,15 @@ pub(crate) fn get_final_indices_from_bit_map(
     join_type: JoinType,
 ) -> (UInt64Array, UInt32Array) {
     let left_size = left_bit_map.len();
+    if join_type == JoinType::LeftMark {
+        let left_indices = (0..left_size)
```
Comment (Dandandan) [inline datafusion/physical-plan/src/joins/utils.rs:1177]:
```suggestion
        let left_indices = (0..left_size as u64)
```

File: datafusion/substrait/tests/cases/roundtrip_logical_plan.rs [hunk 3]
```diff
@@ -473,15 +473,15 @@ async fn roundtrip_inlist_5() -> Result<()> {
...
-    "SELECT a, f FROM data WHERE (f IN ('a', 'b', 'c') OR a in (SELECT data2.a FROM data2 WHERE f IN ('b', 'c', 'd')))",
-    "Projection: data.a, data.f\
-     \n  Filter: data.f = Utf8(\"a\") OR data.f = Utf8(\"b\") OR data.f = Utf8(\"c\") OR Boolean(true) IS NOT NULL\
-     \n    Projection: data.a, data.f, Boolean(true)\
-     \n      Left Join: data.a = data2.a\
-     \n        TableScan: data projection=[a, f]\
-     \n        Projection: data2.a, Boolean(true)\
-     \n          Filter: data2.f = Utf8(\"b\") OR data2.f = Utf8(\"c\") OR data2.f = Utf8(\"d\")\
-     \n            TableScan: data2 projection=[a, f], partial_filters=[data2.f = Utf8(\"b\") OR data2.f = Utf8(\"c\") OR data2.f = Utf8(\"d\")]",
+        "SELECT a, f FROM data WHERE (f IN ('a', 'b', 'c') OR a in (SELECT data2.a FROM data2 WHERE f IN ('b', 'c', 'd')))",
```
Comment (Dandandan) [inline datafusion/substrait/tests/cases/roundtrip_logical_plan.rs:476]: I think ut makes sense to show a physical plan for mark join as well

File: datafusion/common/src/join_type.rs (hunk 1 above)
Comment (eejbyfeldt) [reply datafusion/common/src/join_type.rs:121]: There is. I started adding both in a single PR but realised that is was more changes then I expected, so I did LeftMark first to keep the PR smaller. But created an issue for RightMark here: https://github.com/apache/datafusion/issues/13138

File: datafusion/substrait/tests/cases/roundtrip_logical_plan.rs (hunk 3 above)
Comment (eejbyfeldt) [reply datafusion/substrait/tests/cases/roundtrip_logical_plan.rs:476]: Added in https://github.com/apache/datafusion/pull/13134/commits/3c72e374e92e31fbea6b91aa82dfd6aa585da67d

File: datafusion/optimizer/src/decorrelate_predicate_subquery.rs [hunk 4]
```diff
@@ -296,37 +287,26 @@ fn build_join_top(
 ///
 /// ```text
 /// Projection: t1.id
-///   Filter: t1.id < 0 OR __correlated_sq_1.__exists IS NOT NULL
+///   Filter: t1.id < 0 OR __correlated_sq_1.mark
```
Comment (Dandandan) [inline datafusion/optimizer/src/decorrelate_predicate_subquery.rs:290]: Shouldn't this have `mark join` here in the doc?

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 5]
```diff
@@ -784,6 +790,29 @@ fn get_corrected_filter_mask(
...
+                }
+
+                if last_index {
+                    seen_true = false;
+                }
+            }
+
+            // Generate null joined rows for records which have no matching join key
+            let null_matched = expected_size - corrected_mask.len();
+            corrected_mask.extend(vec![Some(false); null_matched]);
```
Comment (Dandandan) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:813]: There should be `append_n` which is faster and avoids extra allocation.

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 6]
```diff
@@ -784,6 +790,29 @@ fn get_corrected_filter_mask(
             corrected_mask.extend(vec![Some(false); null_matched]);
             Some(corrected_mask.finish())
         }
+        JoinType::LeftMark => {
+            for i in 0..row_indices_length {
+                let last_index =
+                    last_index_for_row(i, row_indices, batch_ids, row_indices_length);
+                if filter_mask.value(i) && !seen_true {
```
Comment (Dandandan) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:797]: This seems like it could be simplified a bit but I see it follows the same structure in existing code

File: datafusion/physical-plan/src/joins/symmetric_hash_join.rs [hunk 7]
```diff
@@ -708,6 +713,20 @@ where
...
+        (JoinSide::Left, JoinType::LeftMark) => {
+            let build_indices = (0..prune_length)
+                .map(L::Native::from_usize)
+                .collect::<PrimitiveArray<L>>();
+            let probe_indices = (0..prune_length)
+                .map(|idx| {
+                    // For mark join we output a dummy index 0 to indicate the row had a match
+                    visited_rows
+                        .contains(&(idx + deleted_offset))
+                        .then_some(R::Native::from_usize(0).unwrap())
```
Comment (Dandandan) [inline datafusion/physical-plan/src/joins/symmetric_hash_join.rs:725]: How does this work, it will have probe indices with fewer number of indices?

Comment (Dandandan) [reply datafusion/physical-plan/src/joins/symmetric_hash_join.rs:725]: Ah I get it, it will be null in that case...

File: datafusion/physical-plan/src/joins/utils.rs [hunk 8]
```diff
@@ -1254,7 +1264,10 @@ pub(crate) fn build_batch_from_indices(
     let mut columns: Vec<Arc<dyn Array>> = Vec::with_capacity(schema.fields().len());
 
     for column_index in column_indices {
-        let array = if column_index.side == build_side {
+        let array = if column_index.side == JoinSide::None {
+            // LeftMark join, the mark column is a boolean if the indices is not null
```
Comment (Dandandan) [inline datafusion/physical-plan/src/joins/utils.rs:1267]:
```suggestion
            // LeftMark join, the mark column is a true if the indices is not null, otherwise it will be false
```

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 5 above)
Comment (Dandandan) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:813]: Ok

File: datafusion/expr/src/logical_plan/builder.rs [hunk 9]
```diff
@@ -1324,6 +1325,25 @@ pub fn change_redundant_column(fields: &Fields) -> Vec<Field> {
...
 }
+
+fn mark_field(schema: &DFSchema) -> (Option<TableReference>, Arc<Field>) {
+    let mut table_references = schema
+        .iter()
+        .filter_map(|(qualifier, _)| qualifier)
+        .collect::<Vec<_>>();
+    table_references.dedup();
+    let table_reference = if table_references.len() == 1 {
+        table_references.first().cloned().cloned()
```
Comment (jayzhan211) [inline datafusion/expr/src/logical_plan/builder.rs:1336]: Is this doing double clone?

Is `table_references[0].clone()` better?

Comment (eejbyfeldt) [reply datafusion/expr/src/logical_plan/builder.rs:1336]: I because the type is `Option<&&TableReference>` will change it to `pop()` instead of `first()` to avoid one of the `cloned`.

File: datafusion/physical-plan/src/joins/utils.rs (hunk 8 above)
Comment (eejbyfeldt) [reply datafusion/physical-plan/src/joins/utils.rs]: Made this change.

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 6 above)
Comment (eejbyfeldt) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:797]: Yeah, I just followed the existing code. So it probably better to simplify it as a later step and maybe do the same to the others.

**Review by Dandandan — COMMENTED** [review]
Nice, this seems a improvement from correctness standpoint and looks like it's probably more efficient as well (especially with right mark join support).

File: datafusion/expr/src/logical_plan/builder.rs [hunk 10]
```diff
@@ -1324,6 +1325,25 @@ pub fn change_redundant_column(fields: &Fields) -> Vec<Field> {
...
+    table_references.dedup();
+    let table_reference = if table_references.len() == 1 {
+        table_references.pop().cloned()
+    } else {
+        None
+    };
+
+    (
+        table_reference,
+        Arc::new(Field::new("mark", DataType::Boolean, false)),
```
Comment (jonahgao) [inline datafusion/expr/src/logical_plan/builder.rs:1343]: Could this field name potentially conflict with user-defined column names? If so, it might be necessary to add a special prefix, similar to [CSE_PREFIX](https://github.com/apache/datafusion/blob/132b232b8861888348f05cc99d11bf1d2d4f1c63/datafusion/optimizer/src/common_subexpr_eliminate.rs#L40).

File: datafusion/optimizer/src/decorrelate_predicate_subquery.rs [hunk 11]
```diff
@@ -296,37 +287,26 @@ fn build_join_top(
...
-    let subquery = LogicalPlanBuilder::from(subquery).project(cols)?.build()?;
     let alias = alias_generator.next("__correlated_sq");
 
-    let exists_col = Expr::Column(Column::new(Some(alias.clone()), "__exists"));
-    let exists_expr = if negated {
-        exists_col.is_null()
-    } else {
-        exists_col.is_not_null()
-    };
+    let exists_col = Expr::Column(Column::new(Some(alias.clone()), "mark"));
```
Comment (jayzhan211) [inline datafusion/optimizer/src/decorrelate_predicate_subquery.rs:305]: Also here.
It seems the column has prefix `__` for `__exists` too. I think what @jonahgao said makes sense.

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 6 above)
Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:797]: There is ongoing work with SortMergeJoin. 
For LeftMark is it the same filtering rules as for LeftOuter join? 

We need to cover it in fuzz tests

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 5 above)
Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:813]: I'll create a ticket to replace filtered masks to use new method if its faster

Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:813]: https://github.com/apache/datafusion/issues/13144

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 12]
```diff
@@ -784,6 +790,29 @@ fn get_corrected_filter_mask(
             corrected_mask.extend(vec![Some(false); null_matched]);
             Some(corrected_mask.finish())
         }
+        JoinType::LeftMark => {
```
Comment (comphead) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:793]: this block is for filtered joins, does LeftMark need it?

Comment (eejbyfeldt) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:793]: I think it needed for `LeftMark` as well. Currently it might only be tested by fuzz test, but I think this is reachable from SQL as well (using subquries).

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 6 above)
Comment (eejbyfeldt) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:797]: > For LeftMark is it the same filtering rules as for LeftOuter join?

It not the same as LeftMark will only output a single row per row in left even if there are multiple passing the filter.

> We need to cover it in fuzz tests

This PR contains fuzz test covering this code.

File: datafusion/optimizer/src/decorrelate_predicate_subquery.rs (hunk 4 above)
Comment (eejbyfeldt) [reply datafusion/optimizer/src/decorrelate_predicate_subquery.rs:290]: Fixed in https://github.com/apache/datafusion/pull/13134/commits/e1809392649611f24ea112e214e54c2c353d2aa8

File: datafusion/expr/src/logical_plan/builder.rs (hunk 10 above)
Comment (eejbyfeldt) [reply datafusion/expr/src/logical_plan/builder.rs:1343]: The way the join is used from decorrelate subqueries it will never conflict as that uses a subquery alias (that is prefixed __) and the new code will then use that for the mark column as well.

But if some uses LeftMark in a query without an alias it would be able to conflict. But I don't think just adding `__` would be a perfect fix. As it can still conflict with it self if you have multiple joins. But also if you are using a `LeftMark` join you will probably like to refer to the mark column and naming it `__mark` make it look like an internal name.

One option could be to make the output column name be part of of the `JoinType` e.g `LeftMark(Column)` and then use that for the output. Then each  user would need to make sure that name is sufficiently unique.

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 6 above)
Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:797]: My bad, I was talking on LeftSemi. How LeftMark differs from LeftSemi?

Comment (eejbyfeldt) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:797]: It will also produced output for unmatched rows, with the mark column being false.

Comment (alamb) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:797]: yes, 100% documenting the semantics of Left Mark Join will be very important

File: datafusion/common/src/join_type.rs [hunk 13]
```diff
@@ -44,6 +44,8 @@ pub enum JoinType {
     LeftAnti,
     /// Right Anti Join
     RightAnti,
+    /// Left Mark join, used for correlated subqueries EXIST/IN
```
Comment (alamb) [inline datafusion/common/src/join_type.rs:47]: I am not familar with what a LeftMarkJoin is -- can we add some additional context here (e.g. maybe based on the PR's description with a link to the ) to help future readers

File: datafusion/physical-plan/src/joins/sort_merge_join.rs (hunk 6 above)
Comment (Dandandan) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:797]: The paper
http://btw2017.informatik.uni-stuttgart.de/slidesandpapers/F1-10-37/paper_web.pdf
is quite helpful to understand it.

The issue explains as well a for queries like `exists` a join + distinct will be needed, this will surely be less efficient than the mark join.

Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:797]: Please correct me if I'm wrong supposedly there are 2 options how to achieve LeftMark

EXISTS
```
SELECT 
    a.id,
    a.name,
    CASE 
        WHEN EXISTS (SELECT 1 FROM table_B AS b WHERE a.id = b.table_a_id) THEN 1
        ELSE 0
    END AS has_match
FROM 
    table_A AS a;
```

LeftOuter
```
SELECT 
    a.id,
    a.name,
    CASE 
        WHEN b.table_a_id IS NOT NULL THEN 1
        ELSE 0
    END AS has_match
FROM 
    table_A AS a
LEFT JOIN 
    table_B AS b
ON 
    a.id = b.table_a_id;
```

The EXISTS approach looks overheated but LeftOuter interpretation  looks for me as a pretty standard  without extra performance issues? 

I'm just wondering on introducing new join type what the value we can bring up? 🤔

Comment (Dandandan) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:797]: image

Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:797]: `it would be tempting to translate into a semi join` - they are 100% right, that exactly what I did 😄  That is interesting type of join, we def need to document its features

Comment (eejbyfeldt) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:797]: We can not use just a `LeftOuter` because it will produce multiple rows per left row if there multiple matches in  the right input. (Note that this is what we do in master and this PR adds a test case that produce incorrect results on master) But we could do a distinct + LeftOuter to handle the duplicates but should be much slower than just doing a mark join.

Comment (comphead) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:797]: Thanks @eejbyfeldt, so it sounds to me like `LeftOuter + mark field + distinct`. I think we should describe the LeftMark join algorithm in test/example. 
For the usage is it planned to pick this algorithm automatically by the planner if some conditions met or the user currently calling it manually via API?

Comment (eejbyfeldt) [reply datafusion/physical-plan/src/joins/sort_merge_join.rs:797]: It used/needed for decorrelating exists/in subqueries that are used in more complex boolean expressions like `OR`. This PR updates the optimizer rule decorrelate predicate subqueries to use mark join when it needed.

File: datafusion/common/src/join_type.rs (hunk 13 above)
Comment (eejbyfeldt) [reply datafusion/common/src/join_type.rs]: Added more docs in https://github.com/apache/datafusion/pull/13134/commits/00bf6192990ae7a32cc1bcc2b2bd0346e7966296 

Let me know if there is something missing.

**Comment by alamb** [comment]
I merged up from main to get a clean CI run

**Comment by Dandandan** [comment]
FYI, I created an epic for the other join types which are I think worth investigating.
https://github.com/apache/datafusion/issues/13181

**Comment by alamb** [comment]
🚀  -- thanks again @Dandandan and @eejbyfeldt
