### PR TITLE
fix: preserve byte-size statistics in AggregateExec

### LINKED ISSUE #18850: AggregateExec drops byte-size statistics causing incorrect join build-side selection and broken dynamic filtering
### Describe the bug

In DataFusion 51.1.0, joins involving a `GROUP BY` may choose the wrong build/probe side.
This happens because `AggregateExec` discards `total_byte_size` statistics, leaving only row-count stats.
The join-selection rule then falls back to comparing `num_rows`, which producing incorrect decisions for tables with uneven byte-size distributions

As a result, dynamic filters may be:
- Built on the large table, or
- Not generated at all.

### To Reproduce

This occurs when joining tables with extreme size asymmetry:

- large_bytes: ~50 rows, ~1 GB total
- many_rows: ~1,000,000 rows, ~50 KB total

Run:
```
SELECT *
FROM large_bytes
JOIN (
  SELECT id, join_key
  FROM many_rows
  GROUP BY ALL
) AS many_rows
ON large_bytes.id = many_rows.join_key;

```

Inspect the optimized plan (`EXPLAIN` or `df.explain(false, true)`).
The optimizer may select `large_bytes` as the build side because the aggregated `many_rows` loses its byte-size stats.

Minimal Rust test reproducing the issue: [repro_aggregate_bytes.rs](https://gist.github.com/Tamar-Posen/758bca567c9a591e0b9e5d0a1fa53633)

### Expected behavior

- AggregateExec should preserve or approximate total_byte_size.
- Join selection should use byte-size when available.
- Dynamic filters should consistently build on the smaller table.

### Additional context

Relevant areas:

- physical-plan/aggregates/mod.rs – statistics propagation
- physical-optimizer/join_selection.rs
- physical-optimizer/filter_pushdown.rs
- physical-plan/joins/hash_join/exec.rs

This behavior appears to be a limitation (design choice) rather than an incidental bug. Preserving or estimating byte-size stats after aggregation would improve join selection for skewed row-size distributions

I’m happy to submit a PR after discussing the desired approach for propagating or estimating byte-size stats through AggregateExec.

### PR DESCRIPTION
**Pull request by Tamar-Posen**
Previously, AggregateExec dropped total_byte_size statistics (Precision::Absent) through aggregation operations, preventing the optimizer from making informed decisions about memory allocation and execution strategies(join side selection -> dynamic filters).

This commit implements proportional byte-size scaling based on row count ratios:
- Added calculate_scaled_byte_size helper with inline optimization
- Scales byte size for Final/FinalPartitioned without GROUP BY
- Scales byte size proportionally for all other aggregation modes
- Always returns Precision::Inexact for estimates (semantically correct)
- Returns Precision::Absent when insufficient input statistics

Added test coverage for edge cases (absent statistics, zero rows).

## Which issue does this PR close?
https://github.com/apache/datafusion/issues/18850

- Closes #18850

## Rationale for this change
Without byte-size statistics, the optimizer cannot estimate memory requirements for join-side selection, dynamic filter generation, and memory allocation decisions. This preserves statistics using proportional scaling (bytes_per_row × output_rows).

## What changes are included in this PR?
1. Modified `statistics_inner` to calculate proportional byte size instead of returning `Precision::Absent`
2. Added `calculate_scaled_byte_size` helper (inline optimized, guards against division by zero)
3. Updated test assertions and added edge case coverage

## Are these changes tested?
Yes:
- New `test_aggregate_statistics_edge_cases` covers edge cases scenarios
- Existing tests confirm stats propagate correctly through the aggregation pipeline

## Are there any user-facing changes?
No breaking changes. 
Internal optimization that may improve query planning and provide more accurate memory estimates in EXPLAIN output.

### CODE REVIEW

**Comment by Dandandan** [comment]
Thanks for opening the PR! I fired the tests

**Comment by Tamar-Posen** [comment]
Hey @Dandandan, could you retrigger the tests?
Pushed an additional fix
THNX

File: datafusion/core/tests/dataframe/mod.rs [hunk 1]
```diff
@@ -3302,30 +3302,33 @@ async fn test_count_wildcard_on_where_scalar_subquery() -> Result<()> {
     assert_snapshot!(
         pretty_format_batches(&sql_results).unwrap(),
         @r"
-    +---------------+-------------------------------------------------------------------------------------------------------------------------+
```
Comment (Tamar-Posen) [inline datafusion/core/tests/dataframe/mod.rs:3305]: The physical plan changed bc join selection now uses available byte stats.
Which leads to a more optimal join order - ensuring the smaller side is chosen as the build side.

**Comment by Dandandan** [comment]
> Hey @Dandandan, could you retrigger the tests? Pushed an additional fix THNX

Done

**Comment by Tamar-Posen** [comment]
Same here @Dandandan, @alamb  - could one of you please retrigger the CI? (Unless there’s a way for me to do it myself?)
Also, I’d appreciate a review when you have a moment.
Thanks!

**Comment by Tamar-Posen** [comment]
@Dandandan Thanks for the review! 
Whenever convenient, could someone merge it, pls?

**Comment by Dandandan** [comment]
@Tamar-Posen thank you for the PR!
