### PR TITLE
fix[physical-expr-adapter]: support casting structs nested inside complex types

### LINKED ISSUE #20906: DefaultPhysicalExprAdapterRewriter doesn't handle structs inside complex types
### Describe the bug

If a column has e.g. a `List<Struct>`, the adapter falls through to the default case:
https://github.com/apache/datafusion/blob/8b412deaca33ec79f4982019379f3c8e538ab650/datafusion/physical-expr-adapter/src/schema_rewriter.rs#L504

Which does not allow struct field evolution. This behavior is unexpected.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by asubiotto**
Previously, DefaultPhysicalExprAdapterRewriter.create_cast_column_expr would only allow struct evolution for top-level structs. However, it is valid to have structs that are nested inside other complex types (e.g. Dictionary<_, Struct>, List<Struct>). These cases would previously return an error although they were valid.

This commit handles Structs that are arbitrarily nested within certain complex types (Lists, ListViews, and Dicts). Other complex types can be supported in the future, but I think this is good enough for now.

## Which issue does this PR close?
- Closes #20906 

## Rationale for this change

Struct evolution is supported, this PR fixes an edge case where struct evolution is not supported when structs are nested inside other complex types.

## Are these changes tested?

Yes, I initially wrote parametrized tests, but I think that's probably overkill.

## Are there any user-facing changes?

Queries that would previously error, now complete successfully.

### CODE REVIEW

**Comment by asubiotto** [comment]
cc @kosiew since you touched the code most recently. cc @alamb in case this needs to be routed to somebody else.

File: datafusion/common/src/nested_struct.rs [hunk 1]
```diff
@@ -151,7 +156,7 @@ fn cast_struct_column(
 ///
 /// # Arguments
 /// * `source_col` - The source array to cast
-/// * `target_field` - The target field definition (including type and metadata)
+/// * `target_type` - The target data type to cast to
```
Comment (asubiotto) [inline datafusion/common/src/nested_struct.rs:159]: This refactor made sense. `target_field` was not used at all, only its inner `DataType`. There were several callsites that constructed "mock" fields just to be able to call this function with a datatype.

File: datafusion/common/src/scalar/mod.rs [hunk 2]
```diff
@@ -3905,15 +3905,11 @@ impl ScalarValue {
...
-            DataType::Struct(_) => {
-                // Field name is unused; only the struct's inner field names matter
-                let target_field = Field::new("_", target_type.clone(), true);
-                crate::nested_struct::cast_column(
-                    &scalar_array,
-                    &target_field,
-                    cast_options,
-                )?
-            }
+            DataType::Struct(_) => crate::nested_struct::cast_column(
```
Comment (kosiew) [inline datafusion/common/src/scalar/mod.rs]: This match DataType::Struct  cast entry point and at 
datafusion/expr-common/src/columnar_value.rs:317
mean casts such as `List<Struct{...}> -> List<Struct{..., extra}>` and `Dictionary<_, Struct{...}> -> Dictionary<_, Struct{..., extra}>` still fall back to Arrow's generic `cast_with_options`.

I think we should add a shared predicate like "does this target type require name-based nested struct casting?" and reuse it in all three places.

File: datafusion/common/src/nested_struct.rs [hunk 3]
```diff
@@ -165,18 +170,139 @@ fn cast_struct_column(
...
 pub fn cast_column(
     source_col: &ArrayRef,
-    target_field: &Field,
+    target_type: &DataType,
     cast_options: &CastOptions,
 ) -> Result<ArrayRef> {
-    match target_field.data_type() {
-        Struct(target_fields) => {
+    match (source_col.data_type(), target_type) {
+        (_, Struct(target_fields)) => {
```
Comment (kosiew) [inline datafusion/common/src/nested_struct.rs:177]: After this patch, runtime support exists for some nested wrappers around structs, but planning is still using the old top-level check 
`    } else if matches!((&expr_type, &cast_type), (Struct(_), Struct(_))) {`
at datafusion/physical-expr/src/expressions/cast.rs:326

File: datafusion/common/src/nested_struct.rs [hunk 4]
```diff
@@ -1010,4 +1173,18 @@ mod tests {
         assert!(b_col.is_null(0));
         assert!(b_col.is_null(1));
     }
+
```
Comment (kosiew) [inline datafusion/common/src/nested_struct.rs:1205]: The new functionality adds fairly intricate `ListView` and dictionary rebuild logic, but the new tests exercise only the `List<Struct>` execution path and dictionary compatibility validation. 

Do you think It would be worth adding tests for `Dictionary<_, Struct>` and for `ListView<Struct>`?

Comment (asubiotto) [reply datafusion/common/src/nested_struct.rs:1205]: I initially had parameterized test cases for all types but it was a fair amount of code. I'm not sure, but I'm happy to add them back and we can decide.

**Comment by asubiotto** [comment]
Thanks for the review! I will address the comments and have a new version by the middle of next week.

File: datafusion/common/src/scalar/mod.rs (hunk 2 above)
Comment (asubiotto) [reply datafusion/common/src/scalar/mod.rs]: Done.

File: datafusion/common/src/nested_struct.rs (hunk 3 above)
Comment (asubiotto) [reply datafusion/common/src/nested_struct.rs:177]: Done, thanks for the pointer!

File: datafusion/common/src/nested_struct.rs (hunk 4 above)
Comment (asubiotto) [reply datafusion/common/src/nested_struct.rs:1205]: Added concrete tests instead. Let me know what you think

**Comment by asubiotto** [comment]
Addressed the comments. I'm realizing now that this struct casting is not supported if you're also doing an outer cast (list->listview). That seems like a more involved change though, so will open an issue for a future PR.

**Comment by alamb** [comment]
Is this ready to merge?
