### PR TITLE
fix: `median` retract logic for sliding window frames

### LINKED ISSUE #21299: `median` window function can skip retracted values in sliding frames
### Describe the bug

`median` can return incorrect results in sliding window queries when the frame retracts multiple values in the accumulator.

### To Reproduce

```sql
SELECT
    x,
    median(x) OVER (
        ORDER BY x
        RANGE BETWEEN 1 PRECEDING AND CURRENT ROW
    ) AS median_val
FROM (VALUES (1.0), (1.0), (2.0), (5.0)) AS t(x)
ORDER BY x;
```

Current result:
```
1 1
1 1
2 1
5 3.5
```

Expected result:
```
1 1
1 1
2 1
5 5
```

### Expected behavior

`median` should return the correct result for sliding window frames by retracting every value that leaves the frame

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lyne7-sc**
## Which issue does this PR close?

- Closes https://github.com/apache/datafusion/issues/21299.

## Rationale for this change

`median` could produce incorrect results for sliding window frames because `MedianAccumulator::retract_batch` could skip values after `swap_remove(i)`.

When an element was removed, the last element was moved into index `i`, but the loop still incremented `i`. That meant the swapped-in value was never checked, so not all requested values were retracted.

## What changes are included in this PR?

- fix `retract_batch` so the index is only advanced when no value is removed
- add a slt case for `median` over a sliding `range` window

## Are these changes tested?

Yes.

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/functions-aggregate/src/median.rs [hunk 1]
```diff
@@ -313,8 +313,9 @@ impl<T: ArrowNumericType> Accumulator for MedianAccumulator<T> {
                         break;
                     }
                 }
+            } else {
```
Comment (lyne7-sc) [inline datafusion/functions-aggregate/src/median.rs:317]: this should be simple, just re-check index i after swap_remove(i).

**Review by Jefffrey — APPROVED** [review]
Makes sense. Double checked with DuckDB and looks like this PR aligns to them:

```sql
DuckDB v1.5.1 (Variegata)
Enter ".help" for usage hints.
memory D SELECT
             x,
             median(x) OVER (
                 ORDER BY x
                 RANGE BETWEEN 1 PRECEDING AND CURRENT ROW
             ) AS median_val
         FROM (VALUES (1.0), (1.0), (2.0), (5.0)) AS t(x)
         ORDER BY x;
┌──────────────┬──────────────┐
│      x       │  median_val  │
│ decimal(2,1) │ decimal(2,1) │
├──────────────┼──────────────┤
│          1.0 │          1.0 │
│          1.0 │          1.0 │
│          2.0 │          1.0 │
│          5.0 │          5.0 │
└──────────────┴──────────────┘
```

Also looks like percentile_cont was already handling this correctly:

https://github.com/apache/datafusion/blob/8dedd12c836c978aea0463319f80fd335d5a8e74/datafusion/functions-aggregate/src/percentile_cont.rs#L453-L471

**Comment by Jefffrey** [comment]
Thanks @lyne7-sc

**Comment by lyne7-sc** [comment]
thank you @Jefffrey
