### PR TITLE
fix: preserve subquery structure when unparsing SubqueryAlias over Ag…

### LINKED ISSUE #21098: SQL Unparser loses subquery structure when SubqueryAlias directly wraps an Aggregate (PR to follow)
### Describe the bug

When the SQL unparser encounters a SubqueryAlias node whose direct child is an Aggregate (without an intermediate Projection), it flattens the subquery into a simple table alias, losing the aggregate entirely.

# Root cause

The SubqueryAlias handler in select_to_sql_recursively (datafusion/sql/src/unparser/plan.rs) calls
subquery_alias_inner_query_and_columns (which only unwraps Projection children) and unparse_table_scan_pushdown (which only
handles TableScan/SubqueryAlias/Projection). When both return nothing useful for an Aggregate child, the code recurses directly
into the Aggregate, merging its GROUP BY into the outer SELECT instead of emitting a derived subquery.

# Additional context

This also affects other plan types that build their own SELECT clauses (Window, Sort, Limit, Union) when directly wrapped by
SubqueryAlias.

### To Reproduce

Manually construct a logical plan with a join where the right side is SubqueryAlias > Aggregate:

```sql
SELECT j1.j1_string FROM j1 JOIN (SELECT max(j2_id) AS max_id FROM j2) AS b ON j1.j1_id = b.max_id
```

This bug doesn't manifest when the SQL is parsed from a string, as the parser inserts a Projection between the SubqueryAlias and Aggregate, so the roundtrip works. The bug only manifests with manually constructed plans where SubqueryAlias directly wraps Aggregate.

```rust
let right_scan = table_scan(Some("j2"), &j2_schema, None)?.build()?;
let right_agg = LogicalPlanBuilder::from(right_scan)
    .aggregate(vec![] as Vec<Expr>, vec![max(col("j2.j2_id")).alias("max_id")])?
    .build()?;
let right_subquery = subquery_alias(right_agg, "b")?;

let left_scan = table_scan(Some("j1"), &j1_schema, None)?.build()?;
let plan = LogicalPlanBuilder::from(left_scan)
    .join(right_subquery, JoinType::Inner,
        (vec![Column::from_qualified_name("j1.j1_id")],
         vec![Column::from_qualified_name("b.max_id")]),
        None)?
    .project(vec![col("j1.j1_string")])?
    .build()?;

let sql = Unparser::default().plan_to_sql(&plan)?.to_string();
```
## Current behavior

```sql
SELECT j1.j1_string FROM j1 INNER JOIN j2 AS b ON j1.j1_id = b.max_id
``` 
The aggregate subquery is completely dropped — (SELECT max(j2_id) AS max_id FROM j2) AS b becomes just j2 AS b.

### Expected behavior

```sql
SELECT j1.j1_string FROM j1 INNER JOIN (SELECT max(j2.j2_id) AS max_id FROM j2) AS b ON j1.j1_id = b.max_id
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yonatan-sevenai**
When the SQL unparser encountered a SubqueryAlias node whose direct child was an Aggregate (or other clause-building plan like Window, Sort, Limit, Union), it would flatten the subquery into a simple table alias, losing the aggregate entirely.

For example, a plan representing:
  SELECT j1.col FROM j1 JOIN (SELECT max(id) AS m FROM j2) AS b ON j1.id = b.m

would unparse to:
  SELECT j1.col FROM j1 INNER JOIN j2 AS b ON j1.id = b.m

dropping the MAX aggregate and the subquery.

Root cause: the SubqueryAlias handler in select_to_sql_recursively would call subquery_alias_inner_query_and_columns (which only unwraps Projection children) and unparse_table_scan_pushdown (which only handles TableScan/SubqueryAlias/Projection). When both returned nothing useful for an Aggregate child, the code recursed directly into the Aggregate, merging its GROUP BY into the outer SELECT instead of wrapping it in a derived subquery.

The fix adds an early check: if the SubqueryAlias's direct child is a plan type that builds its own SELECT clauses (Aggregate, Window, Sort, Limit, Union), emit it as a derived subquery via self.derive() with the alias always attached, rather than falling through to the recursive path that would flatten it.

## Which issue does this PR close?
- Closes #21098 

## Rationale for this change

The SQL unparser silently drops subquery structure when a SubqueryAlias node directly wraps an Aggregate (or Window, Sort, Limit, Union). For example, a plan representing 
```sql 
SELECT ... FROM j1 JOIN (SELECT max(id) FROM j2) AS b ...
``` 
unparses to 
```sql
SELECT ... FROM j1 JOIN j2 AS b ...
```
losing the aggregate entirely. This produces semantically incorrect SQL.

## What changes are included in this PR?

In the SubqueryAlias handler within select_to_sql_recursively (`datafusion/sql/src/unparser/plan.rs`):
  - Added an early check: if the SubqueryAlias's direct child is a plan type that builds its own SELECT clauses (Aggregate, Window, Sort, Limit, Union) and cannot be reduced to a table scan, emit it as a derived subquery (SELECT ...) AS alias via self.derive() instead of recursing into the child and flattening it.
  - Added a helper requires_derived_subquery() that identifies plan types requiring this treatment.

## Are these changes tested?

Yes. A new test test_unparse_manual_join_with_subquery_aggregate is added that constructs a SubqueryAlias > Aggregate plan (without an intermediate Projection) and asserts the unparsed SQL preserves the MAX() aggregate function call. This test fails without the fix. All current unparser tests succeed without modification

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/sql/src/unparser/plan.rs [hunk 1]
```diff
@@ -828,6 +828,27 @@ impl Unparser<'_> {
...
                 )?;
+
+                // If the SubqueryAlias directly wraps a plan that builds its
+                // own SELECT clauses (e.g. Aggregate adds GROUP BY, Window adds
+                // OVER, etc.) and unparse_table_scan_pushdown couldn't reduce it,
+                // we must emit a derived subquery: (SELECT ...) AS alias.
+                // Without this, the recursive handler would merge those clauses
+                // into the outer SELECT, losing the subquery structure entirely.
+                if unparsed_table_scan.is_none()
+                    && Self::requires_derived_subquery(plan_alias.input.as_ref())
```
Comment (kosiew) [inline datafusion/sql/src/unparser/plan.rs]: I think there is still a subtle issue here. `subquery_alias_inner_query_and_columns()` can already unwrap `plan_alias.input` into a different inner `plan`, for example turning a `Projection -> Aggregate` into just the aggregate when column aliases are involved.

This guard is still checking `plan_alias.input`, though. Because of that, cases like projected aggregates, windows, sorts, limits, or unions can skip the derived subquery path and end up being flattened into the outer SELECT.

That brings back the original correctness issue for parser generated queries like `FROM (SELECT max(j1_id) FROM j1) AS c(id)`.

Can we key this check, and the `derive(...)` call, off the rewritten `plan` instead? That should make the behavior consistent with the alias rewrite logic.

File: datafusion/sql/tests/cases/plan_to_sql.rs [hunk 2]
```diff
@@ -2893,3 +2893,58 @@ fn test_json_access_3() {
...
+
+/// Test that unparsing a manually constructed join with a subquery aggregate
+/// preserves the MAX aggregate function.
+///
+/// Builds the equivalent of:
+///   SELECT j1.j1_string FROM j1
+///     JOIN (SELECT max(j2_id) AS max_id FROM j2) AS b
+///     ON j1.j1_id = b.max_id
+#[test]
+fn test_unparse_manual_join_with_subquery_aggregate() -> Result<()> {
```
Comment (kosiew) [inline datafusion/sql/tests/cases/plan_to_sql.rs:2930]: This test is great and definitely helps 👍

One small suggestion. Right now it only covers a `SubqueryAlias` wrapping an `Aggregate` directly. Since the alias rewrite helper can also turn `Projection -> Aggregate` shapes into an inner aggregate, it might be worth adding a roundtrip test for a more realistic SQL case with column aliases.

Something like `SELECT id FROM (SELECT max(j1_id) FROM j1) AS c(id)` would help lock down that edge case as well.

File: datafusion/sql/src/unparser/plan.rs (hunk 1 above)
Comment (yonatan-sevenai) [reply datafusion/sql/src/unparser/plan.rs]: Good catch - updated the check and the derive call to use the rewritten plan instead of plan_alias.input. This also needed a small addition: when the derive path is taken with column
  aliases on a dialect that doesn't support them in table aliases (e.g. SQLite), we now inject them into the inner projection first, same as the non-derive path already does.

File: datafusion/sql/tests/cases/plan_to_sql.rs (hunk 2 above)
Comment (yonatan-sevenai) [reply datafusion/sql/tests/cases/plan_to_sql.rs:2930]: Added roundtrip_subquery_aggregate_with_column_alias using the existing macro

**Comment by yonatan-sevenai** [comment]
> lgtm

Thanks @kosiew . What's the next step to get it merged?

**Comment by alamb** [comment]
I kicked off the CI tests

**Comment by yonatan-sevenai** [comment]
> I kicked off the CI tests

Merged in Master to make merge easier, but you might need to rerun CI.

**Comment by kosiew** [comment]
@yonatan-sevenai 
thanks again for contributing
