### PR TITLE
Fix bug in LimitPushPastWindows

### LINKED ISSUE #18028: LimitPushPastWindows returns incorrect results for queries with `lead()`
### Describe the bug

Some analytical functions effect the effective window bounds by adding a lookahead (acausal) amount of rows. The current implementation of `LimitPushPastWindows` does not take this into account, does not grow the limit by the appropriate amount, and does not give them the input data necessary to compute the correct totals.

### To Reproduce

Run a query like:

```
SELECT LEAD(empno) OVER (ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM employees LIMIT 3
```

with `datafusion.optimizer.enable_window_limits` enabled/disabled to observe different results.

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by avantgardnerio**
## Which issue does this PR close?

- Closes #18028.

## Rationale for this change

It's pretty important optimizer rules don't change results.

## What changes are included in this PR?

1. A new `LimitEffect` similar to `CardinalityEffect` with which plan nodes and window functions can declare their effects on limit_pushdown
2. Most functions are None or Unknown, but the options is given to `Lead()` to calculate and return its effect
3. Updates to the optimizer rule to take these into account, as well as partitioning
4. Tests for all of the above

## Are these changes tested?

In a new `window_limits.slt` to break things up.

## Are there any user-facing changes?

Yes, we should patch-fix and notify users. Credit to @Dandandan for finding this bug.

### CODE REVIEW

File: datafusion/physical-optimizer/src/limit_pushdown_past_window.rs [hunk 1]
```diff
@@ -51,83 +79,62 @@ impl PhysicalOptimizerRule for LimitPushPastWindows {
         if !config.optimizer.enable_window_limits {
             return Ok(original);
         }
-        let mut latest_limit: Option<usize> = None;
-        let mut latest_max = 0;
+        let mut ctx = TraverseState::default();
```
Comment (Dandandan) [inline datafusion/physical-optimizer/src/limit_pushdown_past_window.rs:82]: I wonder if we can / should move the code to LimitPushdown instead?
Might be possible to do it in a single pass and simplify the code.

Comment (avantgardnerio) [reply datafusion/physical-optimizer/src/limit_pushdown_past_window.rs:82]: I was also of two minds on this. I think it's easier to reason about, debug, and disable as a separate rule, but then interplay between lots of optimizer rules can be really difficult to debug as well.

**Comment by avantgardnerio** [comment]
@alamb what's the process for turning this into a patch-fix?

**Comment by alamb** [comment]
> @alamb what's the process for turning this into a patch-fix?

If you mean releasing as part of the DataFusion 50.x line, it is to follow this process: https://github.com/apache/datafusion/pull/17299#issuecomment-3403398530

Seems like @hareshkh  may also be interested in helping so perhaps you can coordinate together

**Comment by hareshkh** [comment]
@alamb @avantgardnerio: Creating a Datafusion release issue now, will cherry-pick changes after that.

**Comment by alamb** [comment]
@hareshkh  has created a ticket to track the 50.3.0 release:
- https://github.com/apache/datafusion/issues/18072

@avantgardnerio can you please create a backport PR to branch-50?
