### PR TITLE
Fix async_udf batch size behaviour

### LINKED ISSUE #18822: AsyncScalarUDFs break when batch_size doesn't divide number of rows
### Describe the bug

When `ideal_batch_size` is set to a value that doesn't evenly divide the total number of rows in some data for an `AsyncScalarUDFImpl`, we get this error:

`Error: Internal("Arguments has mixed length. Expected length: 2, found length: 1")`

for example, the numbers vary depending on both parameters. This happens for example if I have 3 rows and my batch size is set to 2, then I would get two batches, one with size 2 and one with size 1. Due to a bug in the physical expression this throws an error.

### To Reproduce

I wrote a test in the fix PR which fails today: https://github.com/apache/datafusion/pull/18819/files

### Expected behavior

Batch size shouldn't necessarily need to divide the number of rows evenly.

### Additional context

I have a fix [PR](https://github.com/apache/datafusion/pull/18819), the issue was in the `AsyncFuncExpr` physical expression. We were calling `ColumnarValue::values_to_arrays` on all the batches returned asynchronously, but this method enforces that all batches need to be the same length, which isn't necessary here.

### PR DESCRIPTION
**Pull request by shivbhatia10**
## Which issue does this PR close?

- Closes #18822.

## Rationale for this change

This PR fixes the bug outlined in the issue, we shouldn't use `ColumnarValue::values_to_arrays` on the batches collected in `async_scalar_function.rs`.

## What changes are included in this PR?

Added a test to cover this behaviour and fixed the issue in the async scalar function physical expression.

## Are these changes tested?

Yes, I added a new `user_defined_async_scalar_functions.rs` test file similar to `user_defined_scalar_functions.rs` which contains a test that covers this behaviour.

## Are there any user-facing changes?

Yes

### CODE REVIEW

File: datafusion/physical-expr/src/async_scalar_function.rs [hunk 1]
```diff
@@ -192,10 +192,18 @@ impl AsyncFuncExpr {
             );
         }
 
-        let datas = ColumnarValue::values_to_arrays(&result_batches)?
```
Comment (shivbhatia10) [inline datafusion/physical-expr/src/async_scalar_function.rs:195]: `ColumnarValue::values_to_arrays` requires that each batch has the same length, but this is not necessarily the case for our batches here. If the ideal batch size doesn't evenly divide the total number of rows we'll get one batch at the end with a different length.

File: datafusion/core/tests/user_defined/user_defined_async_scalar_functions.rs [hunk 2]
```diff
@@ -0,0 +1,141 @@
...
+    ) -> Result<ColumnarValue> {
+        let arg1 = &args.args[0];
+        let results = call_external_service(arg1.clone()).await?;
+        Ok(results)
+    }
+}
+
+/// Simulates calling an async external service
+async fn call_external_service(arg1: ColumnarValue) -> Result<ColumnarValue> {
+    tokio::time::sleep(Duration::from_millis(10)).await;
```
Comment (Jefffrey) [inline datafusion/core/tests/user_defined/user_defined_async_scalar_functions.rs]: We should remove this sleep, not necessary for testing

**Comment by shivbhatia10** [comment]
Thanks @Jefffrey , I've removed the unnecessary `sleep` and reverted the accidental submodule changes.

File: datafusion/core/tests/user_defined/user_defined_async_scalar_functions.rs [hunk 3]
```diff
@@ -0,0 +1,139 @@
...
+
+    let ctx = SessionContext::new();
+    ctx.register_batch("test_table", batch)?;
+
+    ctx.register_udf(
+        AsyncScalarUDF::new(Arc::new(TestAsyncUDFImpl::new(batch_size)))
+            .into_scalar_udf(),
+    );
+
+    let df = ctx
```
Comment (alamb) [inline datafusion/core/tests/user_defined/user_defined_async_scalar_functions.rs:62]: I verified this test fails without the code fix in this PR

```
---- user_defined::user_defined_async_scalar_functions::test_async_udf_with_non_modular_batch_size stdout ----
Error: Internal("Arguments has mixed length. Expected length: 2, found length: 1")

```

File: datafusion/physical-expr/src/async_scalar_function.rs (hunk 1 above)
Comment (alamb) [reply datafusion/physical-expr/src/async_scalar_function.rs:195]: Yeah, I agree with this assesment

Your solution works and looks good to me. I played around with it locally and I think using the [concat](https://docs.rs/arrow/latest/arrow/compute/kernels/concat/index.html) kernel might be a little faster, for your consideration:

Here is what works well for me locally


```diff
diff --git a/datafusion/physical-expr/src/async_scalar_function.rs b/datafusion/physical-expr/src/async_scalar_function.rs
index 1a794f411b..afb01f7b5e 100644
--- a/datafusion/physical-expr/src/async_scalar_function.rs
+++ b/datafusion/physical-expr/src/async_scalar_function.rs
@@ -16,7 +16,8 @@
 // under the License.

 use crate::ScalarFunctionExpr;
-use arrow::array::{make_array, MutableArrayData, RecordBatch};
+use arrow::array::RecordBatch;
+use arrow::compute::concat;
 use arrow::datatypes::{DataType, Field, FieldRef, Schema};
 use datafusion_common::config::ConfigOptions;
 use datafusion_common::Result;
@@ -192,23 +193,22 @@ impl AsyncFuncExpr {
             );
         }

+        // Create the  all the arrays into a single array
         let datas = result_batches
-            .iter()
+            .into_iter()
             .map(|cv| match cv {
-                ColumnarValue::Array(arr) => Ok(arr.to_data()),
-                ColumnarValue::Scalar(scalar) => {
-                    Ok(scalar.to_array_of_size(1)?.to_data())
-                }
+                ColumnarValue::Array(arr) => Ok(arr),
+                ColumnarValue::Scalar(scalar) => Ok(scalar.to_array_of_size(1)?),
             })
             .collect::<Result<Vec<_>>>()?;

-        let total_len = datas.iter().map(|d| d.len()).sum();
-        let mut mutable = MutableArrayData::new(datas.iter().collect(), false, total_len);
-        datas.iter().enumerate().for_each(|(i, data)| {
-            mutable.extend(i, 0, data.len());
-        });
-        let array_ref = make_array(mutable.freeze());
-        Ok(ColumnarValue::Array(array_ref))
+        // Get references to the arrays as dyn Array to call concat
+        let dyn_arrays = datas
+            .iter()
+            .map(|arr| arr as &dyn arrow::array::Array)
+            .collect::<Vec<_>>();
+        let result_array = concat(&dyn_arrays)?;
+        Ok(ColumnarValue::Array(result_array))
     }
 }
```

**Review by alamb — APPROVED** [review]
Thank you @shivbhatia10  -- this is a nice find and solution

**Comment by alamb** [comment]
FYI @goldmedal in case you would like to review as well

**Review by Jefffrey — APPROVED** [review]

**Comment by shivbhatia10** [comment]
Thank you @alamb and @Jefffrey , I've changed the code to use the `concat` kernel

**Comment by alamb** [comment]
Looks great ot me -- thank you @shivbhatia10  🙏
