### PR TITLE
fix: derive nullability for spark `bit_get`

### LINKED ISSUE #19148: spark `bit_get` need to have custom nullability
### Describe the bug

the UDF uses the default `is_nullable` which is always true which is not the case

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kumarUjjawal**
## Which issue does this PR close?

- Closes #19148.
- Part of #19144

## Rationale for this change

As stated in the original issue the UDF uses the default is_nullable which is always true which is not the case.

## What changes are included in this PR?

- `bit_get` now reports schema using `return_field_from_args`
- Added unit tests

## Are these changes tested?

- All original tests pass
- Added new unit tests for the changes

### CODE REVIEW

File: datafusion/spark/src/function/bitwise/bit_get.rs [hunk 1]
```diff
@@ -83,7 +83,13 @@ impl ScalarUDFImpl for SparkBitGet {
     }
 
     fn return_type(&self, _arg_types: &[DataType]) -> Result<DataType> {
-        Ok(DataType::Int8)
+        internal_err!("return_field_from_args should be used instead")
+    }
+
+    fn return_field_from_args(&self, args: ReturnFieldArgs) -> Result<FieldRef> {
+        // Spark marks bit_get as null-intolerant: result is nullable only if an input can be null
```
Comment (rluvaton) [inline datafusion/spark/src/function/bitwise/bit_get.rs]: It is not that it is because of null-intolerant but because nullable is derived from the children

**Comment by rluvaton** [comment]
I verified that `BitwiseGet` nullability is based on the children:
https://github.com/apache/spark/blob/a189a450e9906362749e3ad3d022f593a2a562e4/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/bitwiseExpressions.scala#L263-L314

`BinaryExpression`:
https://github.com/apache/spark/blob/a189a450e9906362749e3ad3d022f593a2a562e4/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/Expression.scala#L711

File: datafusion/spark/src/function/bitwise/bit_get.rs (hunk 1 above)
Comment (kumarUjjawal) [reply datafusion/spark/src/function/bitwise/bit_get.rs]: Would `Spark derives nullability for BinaryExpression from its children` be more appropriate comment?

**Comment by comphead** [comment]
@rluvaton are you waiting for any feedback here now?

**Comment by alamb** [comment]
Thanks everyone!
