### PR TITLE
fix: try to lower plain reserved functions to columns as well

### LINKED ISSUE #14141: Error when use `user` field in where clause
### Describe the bug

```
DataFusion CLI v44.0.0
> create table t(a int, b int, user text) as values (1,2,'test'), (2,3,null);
0 row(s) fetched.
Elapsed 0.051 seconds.

> select * from t;
+---+---+------+
| a | b | user |
+---+---+------+
| 1 | 2 | test |
| 2 | 3 |      |
+---+---+------+
2 row(s) fetched.
Elapsed 0.006 seconds.

> select * from t where user = 'test';
Error during planning: Invalid function 'user'.
Did you mean 'upper'?
```

### To Reproduce

like above

### Expected behavior

this query can run success

### Additional context

test in datafusion v44.0.0, v43.0.0 and current main, both reported error
not sure if it is a bug or `user` is a keyword, but i also check in duckdb, it work
```
D create table t(a int, b int, user text); insert into t values (1,2,'test'), (2,3,null);
D select * from t where user = 'test';
┌───────┬───────┬─────────┐
│   a   │   b   │  user   │
│ int32 │ int32 │ varchar │
├───────┼───────┼─────────┤
│     1 │     2 │ test    │
└───────┴───────┴─────────┘
D
```

### PR DESCRIPTION
**Pull request by crepererum**
## Which issue does this PR close?
Fixes #14141.

## Rationale for this change
When a reserved function like `user` is called without parenthesis, it may as well be a column. This works in PostgreSQL for example:

```text
psql (17.5 (Debian 17.5-1.pgdg120+1))
Type "help" for help.

postgres=# create table t(a int, "user" text);
CREATE TABLE
postgres=# insert into t values (1, 'foo');
INSERT 0 1
postgres=# select t.user from t;
 user
------
 foo
(1 row)
postgres=# select user from t;
   user
----------
 postgres
(1 row)
```

However sqlparser tries to detect these functions, see https://github.com/apache/datafusion-sqlparser-rs/issues/1909

## What changes are included in this PR?
We now first try to use the respective function and then also consider columns.

## Are these changes tested?
More sqllogictests

## Are there any user-facing changes?
More queries work as expected (IMHO).

### CODE REVIEW

File: datafusion/sql/src/expr/function.rs [hunk 1]
```diff
@@ -93,6 +93,8 @@ struct FunctionArgs {
     distinct: bool,
     /// WITHIN GROUP clause, if any
     within_group: Vec<OrderByExpr>,
+    /// Was the function called without parenthesis, i.e. could this also be a column reference?
+    function_without_paranthesis: bool,
```
Comment (alamb) [inline datafusion/sql/src/expr/function.rs:97]: I think there is a typo here:

```suggestion
    function_without_parenthesis: bool,
```

**Review by alamb — APPROVED** [review]
Thank you @crepererum  -- looks good to me

cc @jonahgao  in case you also have time to review

**Review by jonahgao — APPROVED** [review]
Looks good to me!

**Comment by alamb** [comment]
Thank you for the review @jonahgao ❤️
