### PR TITLE
disallow pushdown of volatile functions

### LINKED ISSUE #16545: Physical plan pushdown for volatile predicates
### Describe the bug

This is a follow-up to a discussion in https://github.com/apache/datafusion/pull/16325#issuecomment-2985522134, which is not directly related to table sampling but could affect it.

I'd like to double-check if a volatile filter pushdown to a Parquet executor is expected. I had implemented the disabling of volatile pushdown filters for a logical plan in #13268. But it seems like the physical optimiser still pushes this predicate to an executor.  Should we implement a similar mechanism to make volatile predicates as unsupported filters? In a current physical plan implementation, there is a concept of "unsupported" filters, which can be easily reused for it.

Current behaviour:

Before:
```
[2025-06-18T18:20:07Z TRACE datafusion::physical_planner] Optimized physical plan by LimitedDistinctAggregation:
    OutputRequirementExec
      ProjectionExec: expr=[count(Int64(1))@0 as count(*)]
        AggregateExec: mode=Final, gby=[], aggr=[count(Int64(1))]
          AggregateExec: mode=Partial, gby=[], aggr=[count(Int64(1))]
            FilterExec: random() < 0.1
              DataSourceExec: file_groups={1 group: [[sample.parquet]]}, file_type=parquet
```

After:
```
[2025-06-18T18:20:07Z TRACE datafusion::physical_planner] Optimized physical plan by FilterPushdown:
    OutputRequirementExec
      ProjectionExec: expr=[count(Int64(1))@0 as count(*)]
        AggregateExec: mode=Final, gby=[], aggr=[count(Int64(1))]
          AggregateExec: mode=Partial, gby=[], aggr=[count(Int64(1))]
            DataSourceExec: file_groups={1 group: [[sample.parquet]]}, file_type=parquet, predicate=random() < 0.1
```

### To Reproduce

```sql
set datafusion.execution.parquet.pushdown_filters=true;
create external table data stored as parquet location 'sample.parquet';
SELECT count(*) FROM data WHERE random() < 0.1;
```

### Expected behavior

I expect the physical plan optimiser doesn't perform pushdown of volatile predicates.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adriangb**
Closes #16545

### CODE REVIEW

**Comment by adriangb** [comment]
@theirix could you take a look? Are there any other expressions we should dissallow?

@alamb are there any existing APIs to get "volatility" from a `PhysicalExpr`? If not should we add some?

**Comment by theirix** [comment]
Thank you! I'll check my cases.

**Comment by theirix** [comment]
Thank you, @adriangb ! I can confirm that it works great with the table sampling, since I use `random` function (matched by name):
```
query TT
EXPLAIN SELECT COUNT(*) from t TABLESAMPLE 42 WHERE a < 10;
----
logical_plan
01)Projection: count(Int64(1)) AS count(*)
02)--Aggregate: groupBy=[[]], aggr=[[count(Int64(1))]]
03)----Projection:
04)------Filter: t.a < Int32(10) AND random() < Float64(0.42)
05)--------TableScan: t projection=[a]
physical_plan
01)ProjectionExec: expr=[count(Int64(1))@0 as count(*)]
02)--AggregateExec: mode=Final, gby=[], aggr=[count(Int64(1))]
03)----CoalescePartitionsExec
04)------AggregateExec: mode=Partial, gby=[], aggr=[count(Int64(1))]
05)--------RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=1
06)----------ProjectionExec: expr=[]
07)------------CoalesceBatchesExec: target_batch_size=8192
08)--------------FilterExec: a@0 < 10 AND random() < 0.42
09)----------------DataSourceExec: partitions=1, partition_sizes=[1]
```

The volatile filter is not pushed to the datasource. Without this patch, it looked like `predicate=random() < 0.1`.

I agree it'd be more scalable to have an abstract way to specify UDF volatility.

File: datafusion/physical-optimizer/src/filter_pushdown.rs [hunk 1]
```diff
@@ -597,3 +631,34 @@ fn push_down_filters(
...
+}
+
+fn allow_pushdown_for_expr_inner(expr: &Arc<dyn PhysicalExpr>) -> bool {
+    // TODO: do downcast matching on specific expressions, or add a method to the PhysicalExpr trait
+    // to check if the expression is volatile or otherwise unsuitable for pushdown.
+    if let Some(scalar_function) =
+        expr.as_any()
+            .downcast_ref::<datafusion_physical_expr::ScalarFunctionExpr>()
+    {
+        let name = scalar_function.fun().name();
```
Comment (alamb) [inline datafusion/physical-optimizer/src/filter_pushdown.rs]: I think you can find volatility using

https://docs.rs/datafusion/latest/datafusion/logical_expr/trait.ScalarUDFImpl.html#tymethod.signature

Which then has a volatility field: https://docs.rs/datafusion/latest/datafusion/logical_expr/struct.Signature.html#structfield.volatility

File: datafusion/physical-optimizer/src/filter_pushdown.rs [hunk 2]
```diff
@@ -485,21 +497,32 @@ fn push_down_filters(
         // currently. `self_filters` are the predicates which are provided by the current node,
         // and tried to be pushed down over the child similarly.
 
-        let num_self_filters = self_filters.len();
-        let mut all_predicates = self_filters.clone();
+        // Filter out self_filters that contain volatile expressions and track indices
```
Comment (alamb) [inline datafusion/physical-optimizer/src/filter_pushdown.rs:497]: All the book keeping for volatile functions got complicated (though I can't really see a better way to do it).

Maybe we could encapsulate the book keeping into some structure that would make it easier to track or something 🤔

**Review by alamb — COMMENTED** [review]
Thank you @adriangb and @theirix  -- this looks good to me. I think we need to change the volatility check but otherwise this is good to go

It is probably reasonable to add a `pub fn volatility()` method to PhysicalExpr as well so that user defined expressions that are volatile / shouldn't be pushed down can be excluded as well

File: datafusion/physical-optimizer/src/filter_pushdown.rs (hunk 2 above)
Comment (adriangb) [reply datafusion/physical-optimizer/src/filter_pushdown.rs:497]: Yes agreed. I'll see what I can come up with...

Comment (adriangb) [reply datafusion/physical-optimizer/src/filter_pushdown.rs:497]: Claude and I came up with https://github.com/pydantic/datafusion/pull/34. It's not exactly simple or pretty, but it does put the indexing logic in one place and make it testable in isolation. Curious what you folks think.

Comment (alamb) [reply datafusion/physical-optimizer/src/filter_pushdown.rs:497]: I think it is better than the current inlined implementation FWIW - even if it is somewhat mindblowing at least the mind blowingness is documented

**Review by alamb — APPROVED** [review]
Thank you @adriangb and @theirix 

The only thing I think we should try and have is some way to test this "end to end" slt test. Here is a proposal for your consideration:
- https://github.com/pydantic/datafusion/pull/35

**Comment by alamb** [comment]
🚀
