### PR TITLE
bug: Fix memory reservation and allocation problems for SortExec

### LINKED ISSUE #10073: Memory account not adding up in SortExec
### Describe the bug

This is related / tangential to #9359

My primary problem is that I am trying to sort 100 million strings and always getting errors like:

```
Resources exhausted: Failed to allocate additional 39698712 bytes for ExternalSorterMerge[0] with 4053021824 bytes already allocated - maximum available is 26915520
```

After reading through the sort impl a bit I have noticed a few concerns (recorded in additional context)

### To Reproduce

I don't have a df reproduction but this reproduces it for me in lance:

```
import pyarrow as pa
import lance

# Once the dataset has been generated you can comment out this generation code and reproduce the issue very quickly
print("Generating data")
my_strings = [f"string-{i}" * 3 for i in range(100 * 1024 * 1024)]                                                                                                                                               
my_table = pa.table({"my_strings": my_strings})                                                                                                                                                                  

print("Writing dataset")
ds = lance.write_dataset(                                                                                                                                                                                        
    my_table, "/tmp/big_strings.lance", mode="overwrite", schema=my_table.schema                                                                                                                                 
)                                                                                                                                                                                                                
del my_table                                                                                                                                                                                                     
# End of generation code

ds = lance.dataset("/tmp/big_strings.lance")
print("Training scalar index")
# To create a scalar index we must sort the column, this is where the error occurs
ds.create_scalar_index("my_strings", "BTREE")
```

### Expected behavior

I can sort any number of strings, as long as I don't overflow the disk

### Additional context

Here is how I understand memory accounting in the sort today:

- As batches arrive, they are placed in an accumulation queue, and the size of the spillable reservation grows
- Once the pool is out of space we begin the spill process
  - The first part of the spill process is to sort the accumulation queue (which, at this point, has many batches in it)
  - Each batch becomes an input stream for a SortPreservingMergeStream (this is a LOT of inputs).
  - When the batch input stream is polled the batch is sorted, the unsorted batch is dropped (and removed from the spillable reservation) and the sorted batch is returned.  The SortPreservingMergeStream then puts this batch in the batch builder (which adds it to the non-spillable reservation).  *This is a problem, as described below*
  - As the sort preserving merge stream is polled it polls the various inputs, fills up the batch builder, and then starts to emit output batches
- Back in the sort exec the sort preserving merge stream is fully drained (try_collect).  *This is a problem, as described below*

The first problem (and the one causing my error) is that a sorted batch of strings (the output of `sort_batch`) is occupying 25% more memory than the unsorted batch of strings.  I'm not sure if this buffer alignment, padding, or some kind of 2x allocation strategy used by the sort, but it seems reasonable something like this could happen.  Unfortunately, this is a problem.  We are spilling because we have used up the entire memory pool.  We now take X bytes from the memory pool, convert it into 1.25 * X bytes, and try to put it back in the memory pool.  This fails with the error listed above.

The second problem is that we are not accounting for the output of the sort perserving merge stream.  Each output batch from the sort preserving merge stream is made up of rows from the various input batches.  In the degenerate case, where the input data is fully random, this means we will probably require 2 * X bytes.  This is because each output batch is made up of 1 batch from each input stream.  We can't release any of the input batches until we emit the final output batch.

The solution to this second problem is that we should be streaming into the spill file.  We should not collect from the sort preserving merge stream and then write the collected batches into the spill file.  This problem is a bit less concerning for me at the moment because it is "datafusion uses more memory than it should" and not "datafusion is failing the plan with an error".  We don't do a lot of sorting in lance and so we can work around it reasonably well by halving the size of the spill pool.

### PR DESCRIPTION
**Pull request by Kontinuation**
## Which issue does this PR close?

- Hopefully it closes #10073, but it is still an incomplete solution.

## Rationale for this change

I had a hard time making DataFusion Comet work on cloud instances with 4GB memory per CPU core, partially because DataFusion is very likely to allocates more memory than reserved and run into OOM, or run into various kinds of memory reservation failures. In cases when the partition to process is larger than available memory, we expect spilling to happen to run the query to completion, but got tons of failures instead. We found operators involving SortExec such as sort-merge join triggers the aforementioned problems frequently.

#10073 reports that SortExec may allocate 2X memory than it reserves (see "the second problem" in the issue), and we found that it contributed to most of the OOM cases we encountered when using Comet. We have also found several other problems related to SortExec that are critical for our memory-limited use cases, and this PR tries to accommodate some of them. 

## What changes are included in this PR?

This PR contains several fixes:

1. Don't `try_collect` the result of merging all at once. We consume the merged batches one after another and reserve memory for each batch. Once the reservation fails we switch to "spill mode" and write all future batches into the spill file. This resolves the 2X memory allocation problem ("the second problem") reported by #10073, as well as this comment: https://github.com/apache/datafusion/issues/12136#issuecomment-2642135559
2. `shrink_to_fit` every sorted batches reduce the memory footprint of sorted batches, otherwise sorted string arrays may take 2X the original space in the worst case, due to exponential growth of `MutableBuffer` for storing variable length binary values. `shrink_to_fit` is a no-op for primitive-type columns returned by `take_arrays` since they already have the right capacity, and benchmarking showed no significant performance regression for non-primitive types such as string arrays, so I think it is a good change. This resolves "the first problem" reported by #10073.
3. Reserves more memory for ingested batches to leave some room for merging. This PR reserves 2X memory for each batch, this works for most of the queries in sort-tpch benchmark (all except Q5 and Q8). User still have to configure `sort_spill_reservation_bytes` when memory reserved is not big enough for merging. I don't think it is a good change but this is the only solution I can think of to compensate for the extra memory usage for the row representation of sorted columns.

The problems with SortExec are not easy to solve without introducing significant changes to the overall design, 3) of this PR is mostly a bandaid solutions. I believe that the implementation needs to be revamped to make all the memory reservation/spilling behave correctly.

## Are these changes tested?

Yes. It passes all the tests.

## Are there any user-facing changes?

Uses may find that sort operator is more likely to spill when running with memory constraints. The old configurations they had to make sort operator work may not be optimal after applying this PR. For instance, user may configure a super large `sort_spill_reservation_bytes` to make merging work, but this PR reduces the optimal value of `sort_spill_reservation_bytes` for the same workload.

### CODE REVIEW

File: datafusion/physical-plan/src/sorts/stream.rs [hunk 1]
```diff
@@ -171,20 +173,32 @@ impl<T: CursorArray> std::fmt::Debug for FieldCursorStream<T> {
...
+        let size_in_mem = array.get_buffer_memory_size();
         let array = array.as_any().downcast_ref::<T>().expect("field values");
-        Ok(ArrayValues::new(self.sort.options, array))
+        let mut array_reservation = self.reservation.new_empty();
+        array_reservation.try_grow(size_in_mem)?;
+        Ok(ArrayValues::new(
+            self.sort.options,
+            array,
+            array_reservation,
+        ))
```
Comment (Kontinuation) [inline datafusion/physical-plan/src/sorts/stream.rs:201]: I think this reservation is needed.

When the sort expression is a simple column reference, the `array` simply reuses the buffer in `batch`, this is the case where reservation is not needed. However, the sort expression can be a complex expression such as `l_linenumber + 1`, the result of evaluation takes additional space in this case. Always reserving `array` is a more conservative approach that prevents allocations from overshooting the limit.

File: datafusion/physical-plan/src/sorts/sort.rs [hunk 2]
```diff
@@ -369,7 +356,7 @@ impl ExternalSorter {
                 .with_metrics(self.metrics.baseline.clone())
                 .with_batch_size(self.batch_size)
                 .with_fetch(self.fetch)
-                .with_reservation(self.reservation.new_empty())
+                .with_reservation(self.merge_reservation.new_empty())
```
Comment (Kontinuation) [inline datafusion/physical-plan/src/sorts/sort.rs:359]: I believe we should use `merge_reservation` here, because the allocations in the stream built here are for merging.

**Review by comphead — COMMENTED** [review]
Thanks @Kontinuation this looks incredibly helpful 
cc @tustvold @Dandandan @crepererum

**Comment by comphead** [comment]
@andygrove cc as this ticket directly related on Comet working on cloud instances

File: datafusion/physical-plan/src/sorts/sort.rs [hunk 3]
```diff
@@ -408,50 +395,114 @@ impl ExternalSorter {
...
+
+        let mut sorted_stream =
+            self.in_mem_sort_stream(self.metrics.baseline.intermediate())?;
+
+        // `self.in_mem_batches` is already taken away by the sort_stream, now it is empty.
+        // We'll gradually collect the sorted stream into self.in_mem_batches, or directly
+        // write sorted batches to disk when the memory is insufficient.
+        let mut spill_writer: Option<IPCWriter> = None;
+        // Leave at least 1/3 of spill reservation for sort/merge the next batch. Here the
+        // 1/3 is simply an arbitrary chosen number.
```
Comment (comphead) [inline datafusion/physical-plan/src/sorts/sort.rs:439]: I'm thinking should we have this number configurable as datafusion parameter? feeling depending on data this number can fluctuate? It might be different for short and plain data vs deeply nested wide rows?

Comment (Kontinuation) [reply datafusion/physical-plan/src/sorts/sort.rs]: I found that `SortPreservingMergeStream` will never reserve memory after producing the first merged batch when merging in-memory batches, so there's no need to reserve additional space for merging in this place. I have removed the additional memory reservation in a new commit.

**Comment by 2010YOUY01** [comment]
> I had a hard time making DataFusion Comet work on cloud instances with 4GB memory per CPU core, partially because DataFusion is very likely to allocates more memory than reserved and run into OOM, or run into various kinds of memory reservation failures. 

Yes, this feature is quite bug-prone, perhaps we should mark it as experimental to prevent someone to use it in production. Thank you so much for the efforts.

Here are my thoughts on the changes

> 1. Don't `try_collect` the result of merging all at once. We consume the merged batches one after another and reserve memory for each batch. Once the reservation fails we switch to "spill mode" and write all future batches into the spill file. This resolves the 2X memory allocation problem ("the second problem") reported by [Memory account not adding up in SortExec #10073](https://github.com/apache/datafusion/issues/10073), as well as this comment: [External sorting not working for (maybe only for string columns??) #12136 (comment)](https://github.com/apache/datafusion/issues/12136#issuecomment-2642135559)

> 3. Reserves more memory for ingested batches to leave some room for merging. This PR reserves 2X memory for each batch, this works for most of the queries in sort-tpch benchmark (all except Q5 and Q8). User still have to configure `sort_spill_reservation_bytes` when memory reserved is not big enough for merging. I don't think it is a good change but this is the only solution I can think of to compensate for the extra memory usage for the row representation of sorted columns.

The 2X memory problem is: specifying a query to run under 100M memory, the measured physical memory is 200M. (though the reality is even worse than 2X 🤦🏼 , see https://github.com/apache/datafusion/pull/14142)
This is caused by, when the first time OOM happens:
- there are already 1X batches in memory
- Then it will be sorted and merged at once, meaning original batches should hold until all sorted runs are generated (now memory footprint is already 2X)
- In the merging phase, additional col->row conversion consumes some extra memory (2X+)

I can get the high-level idea of the more conservative memory accounting in point 3, it is used to also account for merged batches, but I get lost in the memory estimation details in the implementation (especially is this 2X estimation amplification only for merged batches, or also intermediate `Row`s), could you explain with a concrete example how everything is calculated? (for example, there is a `ExternalSorter` with 100M memory budget, and it will consume 10 batches, each with 20M size, how memory estimation is calculated in each step)

> 2. `shrink_to_fit` every sorted batches reduce the memory footprint of sorted batches, otherwise sorted string arrays may take 2X the original space in the worst case, due to exponential growth of `MutableBuffer` for storing variable length binary values. `shrink_to_fit` is a no-op for primitive-type columns returned by `take_arrays` since they already have the right capacity, and benchmarking showed no significant performance regression for non-primitive types such as string arrays, so I think it is a good change. This resolves "the first problem" reported by [Memory account not adding up in SortExec #10073](https://github.com/apache/datafusion/issues/10073).

I think the buffer resizing mechanism is not doubling each time, the default policy will allocate new constant size buffers https://docs.rs/arrow-array/54.1.0/src/arrow_array/builder/generic_bytes_view_builder.rs.html#120-122, so this change might not help

File: datafusion/physical-plan/src/sorts/sort.rs [hunk 4]
```diff
@@ -408,50 +395,114 @@ impl ExternalSorter {
...
+            writer.finish()?;
+            self.metrics.spill_count.add(1);
+            self.metrics.spilled_rows.add(writer.num_rows);
+            self.metrics.spilled_bytes.add(writer.num_bytes);
+        }
+
+        // Sorting may free up some memory especially when fetch is `Some`. If we have
+        // not freed more than 50% of the memory, then we have to spill to free up more
+        // memory for inserting more batches.
+        if spill_writer.is_none() && self.reservation.size() > before / 2 {
```
[the remark this answers is not in the document]
Comment (Kontinuation) [reply datafusion/physical-plan/src/sorts/sort.rs:483]: The comment says that when `fetch` is not `Some(N)`, the sorted batches will be truncated to only top `N` values. This will make the sorted batches smaller than the original. There's a test case `test_sort_fetch_memory_calculation` for this.

**Comment by Kontinuation** [comment]
> > 2. `shrink_to_fit` every sorted batches reduce the memory footprint of sorted batches, otherwise sorted string arrays may take 2X the original space in the worst case, due to exponential growth of `MutableBuffer` for storing variable length binary values. `shrink_to_fit` is a no-op for primitive-type columns returned by `take_arrays` since they already have the right capacity, and benchmarking showed no significant performance regression for non-primitive types such as string arrays, so I think it is a good change. This resolves "the first problem" reported by [Memory account not adding up in SortExec #10073](https://github.com/apache/datafusion/issues/10073).
> 
> I think the buffer resizing mechanism is not doubling each time, the default policy will allocate new constant size buffers https://docs.rs/arrow-array/54.1.0/src/arrow_array/builder/generic_bytes_view_builder.rs.html#120-122, so this change might not help

Actually it helps. I have added a new test case `test_sort_spill_utf8_strings`. It will fail after removing the `shrink_to_fit` calls.

Here is where the 2X buffer growth come from:

1. [sort_batch calls `take_arrays`](https://github.com/apache/datafusion/blob/45.0.0/datafusion/physical-plan/src/sorts/sort.rs#L646), which calls `take_bytes` for string columns
2. `take_bytes` [allocates a `MutableBuffer`](https://github.com/apache/arrow-rs/blob/54.1.0/arrow-select/src/take.rs#L473) for storing strings taken from the input array
3. `take_bytes` [calls the `extend_from_slice` method](https://github.com/apache/arrow-rs/blob/54.1.0/arrow-select/src/take.rs#L479) of the values mutable buffer to append strings to the buffer, which in turn [calls `reserve`](https://github.com/apache/arrow-rs/blob/54.1.0/arrow-buffer/src/buffer/mutable.rs#L375) to grow its space
4. `reserve` [grows the size exponentially](https://github.com/apache/arrow-rs/blob/54.1.0/arrow-buffer/src/buffer/mutable.rs#L195) by a factor of 2

**Comment by Kontinuation** [comment]
> I can get the high-level idea of the more conservative memory accounting in point 3, it is used to also account for merged batches, but I get lost in the memory estimation details in the implementation (especially is this 2X estimation amplification only for merged batches, or also intermediate `Row`s), could you explain with a concrete example how everything is calculated? (for example, there is a `ExternalSorter` with 100M memory budget, and it will consume 10 batches, each with 20M size, how memory estimation is calculated in each step)

The 2X amplification is mainly for intermediate `Row`s, not for merged batches.

Let's assume that each batch is 10 MB, and we have 100 MB memory budget. The following diagram shows how the memory consumption become 100MB when performing merging.

datafusion-sort-merge drawio

Here is the detailed explanation:

1. We reserve 2X memory for each batch on insertion, so when `in_mem_batches` holds 5 batches and consumes 50 MB memory, we have already reserved 100 MB memory. The next insertion will trigger a merge, and possibly a spill.
2. When merge happens, each batch in `in_mem_batches` was sorted individually using `sort_batch` and fed into `StreamingMergeBuilder` to build a `SortPreservingMergeStream`. The batches were taken away from `in_mem_batches`, and the original batches will be dropped immediately after retrieving a sorted batch. We assume that the sorted batches has the same size as the original batches.
3. `SortPreservingMergeStream` polls one batch from each sorted stream, create a [row representation](https://github.com/apache/datafusion/blob/45.0.0/datafusion/physical-plan/src/sorts/stream.rs#L118-L132) or [sorted array representation](https://github.com/apache/datafusion/blob/45.0.0/datafusion/physical-plan/src/sorts/stream.rs#L183-L188) for each batch. The sorted batches were saved into `in_progress` and the row/sorted array representation were saved into `cursors`. We assume that the row representation or sorted array has the same size as the sorted batch. Now we have consumed 100MB.
4. `SortPreservingMergeStream` produces merged batches. We can assume that the overall memory consumption remains unchanged during this process, and certainly we need to reserve memory for merged batches. Each time we poll a merged batche from `SortPreservingMergeStream`, we try reserving memory for it. If the reservation fails, all future merged batches polled from the merged stream will be directly written to the spill file.

**Comment by Kontinuation** [comment]
BTW, the 2X amplification for intermediate `Rows` seems to be conservative, but it is still not enough for some of the queries. The following query creates `Rows` larger than the original batches, and the query will fail when reserving memory for `Rows`:

```
-- sort-tpch Q5: 3 sort keys {(INTEGER, 7), (BIGINT, 10k), (BIGINT, 1.5M)} + no payload column

SELECT l_linenumber, l_suppkey, l_orderkey
FROM lineitem
ORDER BY l_linenumber, l_suppkey, l_orderkey
```

This can be worked around by configuring a larger `sort_spill_reservation_bytes`.

**Comment by Kontinuation** [comment]
I had another interesting observation: spilling sort can be faster than memory unbounded sort in datafusion.

I tried running sort-tpch Q3 using this PR with https://github.com/apache/datafusion/pull/14642 cherry-picked onto it, and configured `parquet.schema_force_view_types = false` to mitigate https://github.com/apache/datafusion/issues/12136#issuecomment-2656400964. Here are the test results obtained on a cloud instance with `Intel(R) Xeon(R) Platinum 8269CY CPU @ 2.50GHz` CPU:

```
$./target/release/dfbench sort-tpch --iterations 1 --path benchmarks/data/tpch_sf10 --memory-limit 1000M -q 3 -n1
Q3 iteration 0 took 93339.0 ms and returned 59986052 rows
Q3 avg time: 93339.00 ms
$./target/release/dfbench sort-tpch --iterations 1 --path benchmarks/data/tpch_sf10 --memory-limit 500M -q 3 -n1
Q3 iteration 0 took 81831.2 ms and returned 59986052 rows
Q3 avg time: 81831.18 ms
$./target/release/dfbench sort-tpch --iterations 1 --path benchmarks/data/tpch_sf10 --memory-limit 200M -q 3 -n1
Q3 iteration 0 took 77046.4 ms and returned 59986052 rows
Q3 avg time: 77046.36 ms
$./target/release/dfbench sort-tpch --iterations 1 --path benchmarks/data/tpch_sf10 -q 3 -n1
Q3 iteration 0 took 170416.1 ms and returned 59986052 rows
Q3 avg time: 170416.10 ms
```

When running without memory limit, we are merging tons of small sorted streams, this seems to be bad for performance. Memory limit enforces us to do merging before ingesting all the batches, so we are doing several smaller merges first and do a final merge at last to produce the result set. Coalescing batches into larger streams before merging seems to be a good idea.

**Comment by kazuyukitanimura** [comment]
Not directly related to the point of this PR but regarding
`
I had a hard time making DataFusion Comet work on cloud instances with 4GB memory per CPU core, partially because DataFusion is very likely to allocates more memory than reserved and run into OOM, or run into various kinds of memory reservation failures
`

I hope this https://github.com/apache/datafusion-comet/pull/1369 helps. This may cause more spilling but I expect the chance of OOM is reduced. Still accurate tracking of memory is important, otherwise mis-tracking still causes OOM

**Comment by zhuqi-lucas** [comment]
```rust
use arrow::array::{RecordBatch, StringBuilder};
use arrow_schema::{DataType, Field, Schema};
use datafusion::execution::disk_manager::DiskManagerConfig;
use datafusion::execution::memory_pool::FairSpillPool;
use datafusion::execution::runtime_env::RuntimeEnvBuilder;
use datafusion::parquet::arrow::ArrowWriter;
use datafusion::prelude::{ParquetReadOptions, SessionConfig, SessionContext};
use futures::TryStreamExt;
use std::sync::Arc;

#[tokio::main(flavor = "multi_thread", worker_threads = 1)]
pub async fn main() {
    build_parquet();

    let env = RuntimeEnvBuilder::new()
        .with_disk_manager(DiskManagerConfig::default())
        .with_memory_pool(Arc::new(FairSpillPool::new(100 * 1024 * 1024)))
        .build_arc()
        .unwrap();

    let mut config = SessionConfig::new().with_sort_spill_reservation_bytes(32 * 1024 * 1024);
    config.options_mut().execution.parquet.schema_force_view_types = false;

    let ctx = SessionContext::new_with_config_rt(config, env);

    ctx.register_parquet(
        "big_strings",
        "/tmp/big_strings.parquet",
        ParquetReadOptions::default(),
    )
        .await
        .unwrap();

    let sql = "SELECT * FROM big_strings ORDER BY strings";
    println!("Sorting strings");
    ctx.sql(sql)
        .await
        .unwrap()
        .execute_stream()
        .await
        .unwrap()
        .try_for_each(|_| std::future::ready(Ok(())))
        .await
        .unwrap();
}

fn build_parquet() {
    if std::fs::File::open("/tmp/big_strings.parquet").is_ok() {
        println!("Using existing file at /tmp/big_strings.parquet");
        return;
    }
    println!("Generating test file at /tmp/big_strings.parquet");
    let file = std::fs::File::create("/tmp/big_strings.parquet").unwrap();
    let schema = Arc::new(Schema::new(vec![Field::new(
        "strings",
        DataType::Utf8,
        false,
    )]));
    let mut writer = ArrowWriter::try_new(file, schema.clone(), None).unwrap();

    for batch_idx in 0..100 {
        println!("Generating batch {} of 100", batch_idx);
        let mut string_array_builder =
            StringBuilder::with_capacity(1024 * 1024, 1024 * 1024 * 3 * 14);
        for i in 0..(1024 * 1024) {
            string_array_builder
                .append_value(format!("string-{}string-{}string-{}", i, i, i));
        }
        let array = Arc::new(string_array_builder.finish());
        let batch = RecordBatch::try_new(schema.clone(), vec![array]).unwrap();
        writer.write(&batch).unwrap();
    }
    writer.close().unwrap();
}
```

Thank you @kazuyukitanimura for the PR, i applied the PR try to fix the testing, but the above testing is still failed for me, i am not sure if i am missing something.

**Comment by Kontinuation** [comment]
> Thank you @kazuyukitanimura for the PR, i applied the PR try to fix the testing, but the above testing is still failed for me, i am not sure if i am missing something.

There are 2 problems:

1. The `DataSourceExec` may have many partitions, and each SortExec on that partition will only get a fair share of the 100MB pool, so each partition won't get enough memory to operate. This is still the case even with `worker_threads = 1`. If you still want to sort 4.2GB parquet file using 100MBs of memory, you can set `.with_target_partitions(1)` in your session config.
2. 100MB is not enough for the final merging with spill-reads. There will be roughly 200 spill files generated after ingesting all the batches, the size of a typical batch for this workload is 352380 bytes. The memory needed for merging will be 200 * (352380 bytes) * 2 > 100MB. Merging phase is unspillable so it requires a minimum amount of memory to operate. Raising the memory limit to 200MB will work for this particular workload.

One possible fix for problem 2 is to use a smaller batch size when writing batches to spill files, so that the unspillable memory required for the final spill-read merging will be smaller. Or we simply leave this problem as is and requires the user to raise the memory limit.

**Comment by zhuqi-lucas** [comment]
> > Thank you @kazuyukitanimura for the PR, i applied the PR try to fix the testing, but the above testing is still failed for me, i am not sure if i am missing something.
> 
> There are 2 problems:
> 
> 1. The `DataSourceExec` may have many partitions, and each SortExec on that partition will only get a fair share of the 100MB pool, so each partition won't get enough memory to operate. This is still the case even with `worker_threads = 1`. If you still want to sort 4.2GB parquet file using 100MBs of memory, you can set `.with_target_partitions(1)` in your session config.
> 2. 100MB is not enough for the final merging with spill-reads. There will be roughly 200 spill files generated after ingesting all the batches, the size of a typical batch for this workload is 352380 bytes. The memory needed for merging will be 200 * (352380 bytes) * 2 > 100MB. Merging phase is unspillable so it requires a minimum amount of memory to operate. Raising the memory limit to 200MB will work for this particular workload.
> 
> One possible fix for problem 2 is to use a smaller batch size when writing batches to spill files, so that the unspillable memory required for the final spill-read merging will be smaller. Or we simply leave this problem as is and requires the user to raise the memory limit.

Thank you @Kontinuation for good explain, it makes sense to me, i will try it.

And for the problem 2, is it possible we introduce a spillable merging phase, will it be more safe?

File: datafusion/physical-plan/src/sorts/sort.rs [hunk 5]
```diff
@@ -302,31 +299,16 @@ impl ExternalSorter {
...
-            if self.reservation.size() > before / 2
-                || self.reservation.try_grow(size).is_err()
-            {
-                self.spill().await?;
-                self.reservation.try_grow(size)?
-            }
+            self.sort_or_spill_in_mem_batches().await?;
+            // We've already freed more than half of reserved memory,
+            // so we can grow the reservation again. There's nothing we can do
+            // if this try_grow fails.
```
Comment (zhuqi-lucas) [inline datafusion/physical-plan/src/sorts/sort.rs:307]: Is it possible to make the merging phase also spillable?

**Comment by zhuqi-lucas** [comment]
> > Thank you @kazuyukitanimura for the PR, i applied the PR try to fix the testing, but the above testing is still failed for me, i am not sure if i am missing something.
> 
> There are 2 problems:
> 
> 1. The `DataSourceExec` may have many partitions, and each SortExec on that partition will only get a fair share of the 100MB pool, so each partition won't get enough memory to operate. This is still the case even with `worker_threads = 1`. If you still want to sort 4.2GB parquet file using 100MBs of memory, you can set `.with_target_partitions(1)` in your session config.
> 2. 100MB is not enough for the final merging with spill-reads. There will be roughly 200 spill files generated after ingesting all the batches, the size of a typical batch for this workload is 352380 bytes. The memory needed for merging will be 200 * (352380 bytes) * 2 > 100MB. Merging phase is unspillable so it requires a minimum amount of memory to operate. Raising the memory limit to 200MB will work for this particular workload.
> 
> One possible fix for problem 2 is to use a smaller batch size when writing batches to spill files, so that the unspillable memory required for the final spill-read merging will be smaller. Or we simply leave this problem as is and requires the user to raise the memory limit.


**Updated, it works after change to 1 partition and increase the memory limit.**

File: datafusion/physical-plan/src/sorts/sort.rs [hunk 6]
```diff
@@ -641,7 +702,15 @@ pub fn sort_batch(
...
     };
 
-    let columns = take_arrays(batch.columns(), &indices, None)?;
+    let mut columns = take_arrays(batch.columns(), &indices, None)?;
+
+    // The columns may be larger than the unsorted columns in `batch` especially for variable length
+    // data types due to exponential growth when building the sort columns. We shrink the columns
+    // to prevent memory reservation failures, as well as excessive memory allocation when running
+    // merges in `SortPreservingMergeStream`.
+    columns.iter_mut().for_each(|c| {
```
Comment (zhuqi-lucas) [inline datafusion/physical-plan/src/sorts/sort.rs:711]: Will it be expensive for all columns to do this, or can we filter those accurate columns which need to shrink?

File: datafusion/physical-plan/src/sorts/sort.rs (hunk 5 above)
Comment (Kontinuation) [reply datafusion/physical-plan/src/sorts/sort.rs:307]: We can implement a more complicated multi-stage merging phase which merges a small portion of streams each time, and perform multiple rounds of merges to produce the final merged stream. However this approach is quite complex and out of the scope of this PR. I believe that there should be dedicated discussions around this problem.

File: datafusion/physical-plan/src/sorts/sort.rs [hunk 7]
```diff
@@ -408,50 +395,100 @@ impl ExternalSorter {
...
+        let before = self.reservation.size();
+
+        let mut sorted_stream =
+            self.in_mem_sort_stream(self.metrics.baseline.intermediate())?;
+
+        // `self.in_mem_batches` is already taken away by the sort_stream, now it is empty.
+        // We'll gradually collect the sorted stream into self.in_mem_batches, or directly
+        // write sorted batches to disk when the memory is insufficient.
+        let mut spill_writer: Option<IPCWriter> = None;
+        while let Some(batch) = sorted_stream.next().await {
```
Comment (zhuqi-lucas) [inline datafusion/physical-plan/src/sorts/sort.rs:438]: This is a good point to avoid OOM for try_collect().

File: datafusion/physical-plan/src/sorts/sort.rs (hunk 6 above)
Comment (zhuqi-lucas) [reply datafusion/physical-plan/src/sorts/sort.rs:711]: It seems you already benchmarked it, we may can the benchmark code also.

Comment (Kontinuation) [reply datafusion/physical-plan/src/sorts/sort.rs:711]: This `shrink_to_fit` is basically a no-op for primitive type columns produced by `take_arrays` because their internal buffer already has the right capacity, and it will only perform reallocations for columns with variable length data. so I don't there's a need for cherry-picking which columns to shrink.

I've also benchmarked sorting using utf8 columns and have not observed significant performance overhead:

```
merge sorted utf8 low cardinality
                        time:   [3.8824 ms 3.8903 ms 3.8987 ms]
                        change: [-2.8027% -2.1227% -1.5573%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  3 (3.00%) high mild
  1 (1.00%) high severe

sort merge utf8 low cardinality
                        time:   [4.2295 ms 4.2360 ms 4.2430 ms]
                        change: [+0.5975% +0.8722% +1.1242%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 15 outliers among 100 measurements (15.00%)
  2 (2.00%) low mild
  5 (5.00%) high mild
  8 (8.00%) high severe

sort utf8 low cardinality
                        time:   [6.4265 ms 6.4369 ms 6.4483 ms]
                        change: [-0.3276% -0.0658% +0.1908%] (p = 0.62 > 0.05)
                        No change in performance detected.
Found 7 outliers among 100 measurements (7.00%)
  5 (5.00%) high mild
  2 (2.00%) high severe

sort partitioned utf8 low cardinality
                        time:   [343.87 µs 347.16 µs 351.07 µs]
                        change: [-1.1291% +0.3066% +1.8160%] (p = 0.68 > 0.05)
                        No change in performance detected.
Found 15 outliers among 100 measurements (15.00%)
  5 (5.00%) high mild
  10 (10.00%) high severe

merge sorted utf8 high cardinality
                        time:   [5.9968 ms 6.0083 ms 6.0207 ms]
                        change: [-1.9398% -1.6215% -1.2928%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
  7 (7.00%) high mild
  1 (1.00%) high severe

sort merge utf8 high cardinality
                        time:   [6.4266 ms 6.4399 ms 6.4558 ms]
                        change: [-0.5594% -0.2292% +0.1020%] (p = 0.19 > 0.05)
                        No change in performance detected.
Found 6 outliers among 100 measurements (6.00%)
  2 (2.00%) high mild
  4 (4.00%) high severe

sort utf8 high cardinality
                        time:   [7.7403 ms 7.7541 ms 7.7693 ms]
                        change: [-2.7779% -2.1541% -1.6176%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 6 outliers among 100 measurements (6.00%)
  2 (2.00%) high mild
  4 (4.00%) high severe

sort partitioned utf8 high cardinality
                        time:   [364.21 µs 370.21 µs 376.41 µs]
                        change: [+2.2461% +4.2833% +6.3333%] (p = 0.00 < 0.05)
                        Performance has regressed.
```

sort_tpch and tpch10 benchmarks also showed no difference in performance.

**Comment by 2010YOUY01** [comment]
> Here is the detailed explanation:
> 
> 1. We reserve 2X memory for each batch on insertion, so when `in_mem_batches` holds 5 batches and consumes 50 MB memory, we have already reserved 100 MB memory. The next insertion will trigger a merge, and possibly a spill.
> 2. When merge happens, each batch in `in_mem_batches` was sorted individually using `sort_batch` and fed into `StreamingMergeBuilder` to build a `SortPreservingMergeStream`. The batches were taken away from `in_mem_batches`, and the original batches will be dropped immediately after retrieving a sorted batch. We assume that the sorted batches has the same size as the original batches.
> 3. `SortPreservingMergeStream` polls one batch from each sorted stream, create a [row representation](https://github.com/apache/datafusion/blob/45.0.0/datafusion/physical-plan/src/sorts/stream.rs#L118-L132) or [sorted array representation](https://github.com/apache/datafusion/blob/45.0.0/datafusion/physical-plan/src/sorts/stream.rs#L183-L188) for each batch. The sorted batches were saved into `in_progress` and the row/sorted array representation were saved into `cursors`. We assume that the row representation or sorted array has the same size as the sorted batch. Now we have consumed 100MB.
> 4. `SortPreservingMergeStream` produces merged batches. We can assume that the overall memory consumption remains unchanged during this process, and certainly we need to reserve memory for merged batches. Each time we poll a merged batche from `SortPreservingMergeStream`, we try reserving memory for it. If the reservation fails, all future merged batches polled from the merged stream will be directly written to the spill file.

Thanks for the nice diagram, this explanation is super clear

Regarding point 3, I thought of a edge case can cause `Row`s way larger than 1X:
During merging, now only order key will be converted to row format. 
- If `select c1,c2 from t order by c1, c2`, all columns will be convereted to `Row`, the estimation is close to 1X
- If `select c1, ... c10 from t order by c1`, only 1 column will be converted, the extra `Row` overhead is 0.1X. (I think this is okay to estimate more to be conservative)

Edge case: let's say input is a deduplicated `StringViewArray` (like a 10k rows batch with only 100 distinct values, but payload content are stored without duplication, the array elements are just referencing to the payload range), after converting to `Row` format, every row will be materialized, then the `Row` format will have 100X expansion
I think we need some mechanism to deal with this kind of edge case, perhaps this also applies to dictionary representation

For point 4, are the memory budget to hold merged batches come from `sort_spill_reservation_bytes`? Small sorted runs, and converted rows should have taken up all memory spaces at this stage.

File: datafusion/physical-plan/src/sorts/sort.rs (hunk 5 above)
Comment (zhuqi-lucas) [reply datafusion/physical-plan/src/sorts/sort.rs:307]: I agree, we can add more dedicated discussions around this problem.

File: datafusion/physical-plan/src/sorts/sort.rs (hunk 6 above)
Comment (zhuqi-lucas) [reply datafusion/physical-plan/src/sorts/sort.rs:711]: It makes sense.

**Comment by Kontinuation** [comment]
> Edge case: let's say input is a deduplicated `StringViewArray` (like a 10k rows batch with only 100 distinct values, but payload content are stored without duplication, the array elements are just referencing to the payload range), after converting to `Row` format, every row will be materialized, then the `Row` format will have 100X expansion I think we need some mechanism to deal with this kind of edge case, perhaps this also applies to dictionary representation

I agree that the current implementation uses a very rough estimation, and it could be way off from the actual memory consumption.

A better approach is to sort and generate the row representation of the batch right after we ingesting it, then we would know the exact size of sorted batches and their row representations held in memory. The merge phase for handling spilling could simply take away these data and perform merging without reserving more memory. However, this conflicts with some optimizations we did in the past:

* https://github.com/apache/datafusion/pull/6308: sort are performed concurrently right before merging.

> For point 4, are the memory budget to hold merged batches come from `sort_spill_reservation_bytes`? Small sorted runs, and converted rows should have taken up all memory spaces at this stage.

Yes. It may come from `sort_spill_reservation_bytes`, or the reduced memory usage because of the fetch option.

File: datafusion/core/tests/fuzz_cases/sort_fuzz.rs [hunk 8]
```diff
@@ -54,7 +54,9 @@ async fn test_sort_10k_mem() {
 #[tokio::test]
 #[cfg_attr(tarpaulin, ignore)]
 async fn test_sort_100k_mem() {
```
Comment (alamb) [inline datafusion/core/tests/fuzz_cases/sort_fuzz.rs:56]: Can you please also add some fuzz tests for the cases you are coverting in this PR? Specifically:
1. `RecordBatch`es with String arrays
2. `RecordBatch`es that have multiple columns (and thus use the Row format)

**Review by alamb — COMMENTED** [review]
First of all, thank you so much @Kontinuation and @zhuqi-lucas  - I think this PR is very nicely coded, and commented and is quite clear to read.

I think the only other thing left in my mind is to add a few more fuzz tests, but otherwise this is nice

@2010YOUY01 made a nice set of tests too to verify that the memory accounting was accurate, but they are currently disabled. Maybe we can also run them here too 🤔 
- https://github.com/apache/datafusion/issues/14680


cc @kazuyukitanimura 
cc @westonpace  as you filed https://github.com/apache/datafusion/issues/10073

File: datafusion/physical-plan/src/sorts/sort.rs (hunk 5 above)
Comment (zhuqi-lucas) [reply datafusion/physical-plan/src/sorts/sort.rs:307]: Thank you @alamb for double check, i created a follow-up issue now:
https://github.com/apache/datafusion/issues/14692

We can mark and further discuss about the potential complete solution about spill data in sort.

**Review by 2010YOUY01 — COMMENTED** [review]
I think it's a good high-level design to solve the 2X memory issue in spilling sort queries. I also checked the implementation, overall it looks good to me, I left some nit-picking suggestions.
Now I think the TODOs before merging are adding physical memory consumption validation, and file issues for known tasks.

## Validate physical consumption
In theory, I think this PR can solve the 2X memory problem for memory-limited sort queries, but still can't solve 2X memory issue if running without memory limit and spilling enabled.
Examples:
- **This PR can't solve**
`select * from t` consumes 2GB memory to fully materialize the output, in the best case `select * from t order by c1` consumes around 2GB memory, given sorting is an O(1) space operation. The current situation is it consumes 4GB+ (more than 2 times).
- **This PR can solve**
If you specify the memory limit to 1GB, the actual physical memory consumption would be more than 2GB. The ideal actual consumption is around 1GB.
### Problem
~~I tried one query and this PR is not working as expected, I specified one query to run under 5GB memory (`select *` without order requires 7GB) but it's still consuming around 10GB, could you double check? I suspect we missed some details.~~
I made a mistake, there is no problem: the result to check is `measured RSS < memory limit + result size`
### Reproducer
Under `datafusion-cli`, run
```
/usr/bin/time -l cargo run --release -- --mem-pool-type fair -m 5G -f '/Users/yongting/Code/scripts/external_sort.sql'
```
SQL script (have to modify tpch_sf10 path), I did not include string columns because I think there are some known issues.
```sql
CREATE EXTERNAL TABLE IF NOT EXISTS lineitem (
        l_orderkey BIGINT,
        l_partkey BIGINT,
        l_suppkey BIGINT,
        l_linenumber INTEGER,
        l_quantity DECIMAL(15, 2),
        l_extendedprice DECIMAL(15, 2),
        l_discount DECIMAL(15, 2),
        l_tax DECIMAL(15, 2),
        l_returnflag VARCHAR,
        l_linestatus VARCHAR,
        l_shipdate DATE,
        l_commitdate DATE,
        l_receiptdate DATE,
        l_shipinstruct VARCHAR,
        l_shipmode VARCHAR,
        l_comment VARCHAR
) STORED AS parquet
LOCATION '/Users/yongting/Code/datafusion/benchmarks/data/tpch_sf10/lineitem';

-- selected all non-varchar columns
SELECT l_orderkey, l_partkey, l_suppkey, l_linenumber, l_quantity, l_extendedprice, l_discount, l_tax, l_shipdate, l_commitdate, l_receiptdate FROM lineitem ORDER BY l_orderkey;
```
Result is around 10GB:
```
 10703093760  maximum resident set size
```

Once fixed, I think the following memory bounds can be set smaller (e.g. `*3` -> `*1.5`), for regression test. https://github.com/apache/datafusion/blob/223868014eb871c567c4f9a6c784431554db1c4f/datafusion/core/tests/memory_limit/memory_limit_validation/sort_mem_validation.rs#L175

## Known issues
I think this PR already made improvements on the current status, so those issues only need to be tracked (I can help)
- After merging, memory consumption of `StringViewArray` will increase, see reproducer in https://github.com/apache/datafusion/issues/12136#issuecomment-2656449956. This PR uses a workaround to eagerly flush merged batches, instead of directly fixing it.
- This PR uses 2x to estimate memory consumption for sorted batches and `Rows` generated in intermediate steps to accelerate comparisions, it works for common cases but still can fail. See https://github.com/apache/datafusion/pull/14644#issuecomment-2659063578 and https://github.com/apache/datafusion/pull/14644#issuecomment-2660783992. The solution can be when reading a new batch, first do `col->row` conversion and measure the memory consumption, though this require some significant change to the current code structure.

**Comment by Kontinuation** [comment]
> * **This PR can't solve**
>   `select * from t` consumes 2GB memory to fully materialize the output, in the best case `select * from t order by c1` consumes around 2GB memory, given sorting is an O(1) space operation. The current situation is it consumes 4GB+ (more than 2 times).

I think this is by design. The physical operators should not reserve memory for the batches it produces. It is the parent operator's duty to reserve memory for the batches fetched from children operators if it needs to hold the batches in memory for a long time.

> 
> ### Problem
> I tried one query and this PR is not working as expected, I specified one query to run under 5GB memory (`select *` without order requires 7GB) but it's still consuming around 10GB, could you double check? I suspect we missed some details.
> 

It is a problem of datafusion-cli. If datafusion-cli decides to hold all the result batches in memory, it should create a memory consumer for itself and reserve memory for the result batches.

`datafusion-cli` [calls `collect`](https://github.com/apache/datafusion/blob/45.0.0/datafusion-cli/src/exec.rs#L249-L254) to hold the entire result set in memory before displaying it, this is unnecessary when `maxrows` is not unlimited. I've tried the following code to replace the `collect` call, and the `maximum resident set size` has reduced to 4.8 GB:

```rust
// Bounded stream; collected results are printed after all input consumed.
let schema = physical_plan.schema();
let mut stream = execute_stream(physical_plan, task_ctx.clone())?;
let mut results = vec![];
while let Some(batch) = stream.next().await {
    let batch = batch?;
    results.push(batch);
    if let MaxRows::Limited(max_rows) = print_options.maxrows {
        if results.len() >= max_rows {
            break;
        }
    }
}
adjusted.into_inner().print_batches(schema, &results, now)?;
```

**Comment by 2010YOUY01** [comment]
Sorry, I mistakenly edited your original reply @Kontinuation, I'm trying to revert it back.

**Comment by 2010YOUY01** [comment]
>  It is a problem of datafusion-cli. If datafusion-cli decides to hold all the result batches in memory, it should create a memory consumer for itself and reserve memory for the result batches.

Yes, you are right and the result is good. I made a mistake about the expected behavior: it should be `measured RSS < memory limit + result size`. I've tested several smaller memory limit and the result is correct.

**Comment by zhuqi-lucas** [comment]
> > This PR can't solve
> > select * from t consumes 2GB memory to fully materialize the output, in the best case select * from t order by c1 consumes around 2GB memory, given sorting is an O(1) space operation. The current situation is it consumes 4GB+ (more than 2 times).
> 
> I think this is by design. The physical operators should not reserve memory for the batches it produces. It is the parent operator's duty to reserve memory for the batches fetched from children operators if it needs to hold the batches in memory for a long time.
> 
> > Problem
> > I tried one query and this PR is not working as expected, I specified one query to run under 5GB memory (select * without order requires 7GB) but it's still consuming around 10GB, could you double check? I suspect we missed some details.
> 
> It is a problem of datafusion-cli. If datafusion-cli decides to hold all the result batches in memory, it should create a memory consumer for itself and reserve memory for the result batches.
> 
> datafusion-cli [calls collect](https://github.com/apache/datafusion/blob/45.0.0/datafusion-cli/src/exec.rs#L249-L254) to hold the entire result set in memory before displaying it, this is unnecessary when maxrows is not unlimited. I've tried the following code to replace the collect call, and the maximum resident set size has reduced to 4.8 GB:
> 
> ```rust
> // Bounded stream; collected results are printed after all input consumed.
> let schema = physical_plan.schema();
> let mut stream = execute_stream(physical_plan, task_ctx.clone())?;
> let mut results = vec![];
> while let Some(batch) = stream.next().await {
>     let batch = batch?;
>     results.push(batch);
>     if let MaxRows::Limited(max_rows) = print_options.maxrows {
>         if results.len() >= max_rows {
>             break;
>         }
>     }
> }
> adjusted.into_inner().print_batches(schema, &results, now)?;
> ```

Good finding, may be we can file a issue to improve the datafusion-cli memory usage and reservation.

**Comment by zhuqi-lucas** [comment]
Hi @westonpace , i think the problem is we need to setting the partition count and also to increase the memory limit also for your case:


```
1. setting the partition count to 1:
 .with_target_partitions(1)

2. increasing the memory limit for example to 300MB
```


Details here:

https://github.com/apache/datafusion/pull/14644#issuecomment-2660748423


1. The DataSourceExec may have many partitions, and each SortExec on that partition will only get a fair share of the 100MB pool, so each partition won't get enough memory to operate. This is still the case even with worker_threads = 1. If you still want to sort 4.2GB parquet file using 100MBs of memory, you can set .with_target_partitions(1) in your session config.


2. 100MB is not enough for the final merging with spill-reads. There will be roughly 200 spill files generated after ingesting all the batches, the size of a typical batch for this workload is 352380 bytes. The memory needed for merging will be 200 * (352380 bytes) * 2 > 100MB. Merging phase is unspillable so it requires a minimum amount of memory to operate. Raising the memory limit to 200MB will work for this particular workload.


And for future work we can have a complete spill solution tracking here:

https://github.com/apache/datafusion/issues/14692

**Review by 2010YOUY01 — APPROVED** [review]
Thanks again for the nice work.

**Comment by alamb** [comment]
> > This PR can't solve
> > select * from t consumes 2GB memory to fully materialize the output, in the best case select * from t order by c1 consumes around 2GB memory, given sorting is an O(1) space operation. The current situation is it consumes 4GB+ (more than 2 times).
> 
> I think this is by design. The physical operators should not reserve memory for the batches it produces. It is the parent operator's duty to reserve memory for the batches fetched from children operators if it needs to hold the batches in memory for a long time.

This is a great observation and I think holds true in practice

However I don't think it is reflected in the documention here
https://docs.rs/datafusion/latest/datafusion/execution/memory_pool/trait.MemoryPool.html


Would someone be willing to update those docs?

**Comment by alamb** [comment]
> > Problem
> > I tried one query and this PR is not working as expected, I specified one query to run under 5GB memory (select * without order requires 7GB) but it's still consuming around 10GB, could you double check? I suspect we missed some details.
> 
> It is a problem of datafusion-cli. If datafusion-cli decides to hold all the result batches in memory, it should create a memory consumer for itself and reserve memory for the result batches.
> 
> datafusion-cli [calls collect](https://github.com/apache/datafusion/blob/45.0.0/datafusion-cli/src/exec.rs#L249-L254) to hold the entire result set in memory before displaying it, this is unnecessary when maxrows is not unlimited. I've tried the following code to replace the collect call, and the maximum resident set size has reduced to 4.8 GB:

This is also another great observation that it would be great to get captured in a ticket

**Comment by alamb** [comment]
Thanks everyone -- this is a great example of collaboration and what the collective efforts of many contributors can do. I love it.

**Review by alamb — APPROVED** [review]
❤️ 🦾

**Comment by westonpace** [comment]
> 100MB is not enough for the final merging with spill-reads. There will be roughly 200 spill files generated after ingesting all the batches, the size of a typical batch for this workload is 352380 bytes. The memory needed for merging will be 200 * (352380 bytes) * 2 > 100MB. Merging phase is unspillable so it requires a minimum amount of memory to operate. Raising the memory limit to 200MB will work for this particular workload.

Thank you for this.  You are correct, with this addition then my test passes.  #14692 sounds awesome but I think we can also go far with these current fixes in the meantime :rocket:

**Comment by zhuqi-lucas** [comment]
> > > Problem
> > > I tried one query and this PR is not working as expected, I specified one query to run under 5GB memory (select * without order requires 7GB) but it's still consuming around 10GB, could you double check? I suspect we missed some details.
> > 
> > 
> > It is a problem of datafusion-cli. If datafusion-cli decides to hold all the result batches in memory, it should create a memory consumer for itself and reserve memory for the result batches.
> > datafusion-cli [calls collect](https://github.com/apache/datafusion/blob/45.0.0/datafusion-cli/src/exec.rs#L249-L254) to hold the entire result set in memory before displaying it, this is unnecessary when maxrows is not unlimited. I've tried the following code to replace the collect call, and the maximum resident set size has reduced to 4.8 GB:
> 
> This is also another great observation that it would be great to get captured in a ticket

Created a follow-up for this improvement:
https://github.com/apache/datafusion/issues/14751

**Review by comphead — APPROVED** [review]
thanks @Kontinuation @zhuqi-lucas @2010YOUY01 @alamb and everyone, awesome team effort like Andrew mentioned. I think this ticket tests and experience would be beneficial for #14510
