### PR TITLE
fix: custom nullability for format_string (#19173)

### LINKED ISSUE #19173: spark `format_string` need to have custom nullability
### Describe the bug

the UDF uses the default `is_nullable` which is always true which is not the case

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by skushagra**
## Which issue does this PR close?

- Closes #19173

## What changes are included in this PR?

- includes custom nullability for `format_string`.

### CODE REVIEW

**Comment by skushagra** [comment]
@rluvaton can you please review?

File: datafusion/spark/src/function/string/format_string.rs [hunk 1]
```diff
@@ -78,15 +78,17 @@ impl ScalarUDFImpl for FormatStringFunc {
...
+            "return_type should not be called, use return_field_from_args instead"
+        )
+    }
+
+    fn return_field_from_args(&self, args: ReturnFieldArgs) -> Result<FieldRef> {
+        match args.arg_fields[0].data_type() {
+            DataType::Null => Ok(Arc::new(Field::new("format_string", DataType::Utf8, true))),
+            DataType::Utf8 | DataType::LargeUtf8 | DataType::Utf8View => Ok(Arc::clone(&args.arg_fields[0])),
+            _ => exec_err!("format_string expects the first argument to be Utf8, LargeUtf8 or Utf8View, got {} instead", args.arg_fields[0].data_type())
         }
```
Comment (Jefffrey) [inline datafusion/spark/src/function/string/format_string.rs:99]:
```rust
Ok(Arc::clone(&args.arg_fields[0]))
```

Is it possible to have a `DataType::Null` where the field isn't nullable? If not we can simplify like so

Comment (skushagra) [reply datafusion/spark/src/function/string/format_string.rs:99]: Hi, thanks for the review! 

I'm not certain whether `DataType::Null` can have `nullable = false` in practice. If it's always nullable, then yes, we can simplify by using `Arc::clone(&args.arg_fields[0])` for the Null case as well.

If you could confirm on this, I'll push the updated changes. I guess it makes sense to update it this way!

EDIT:
I have updated the code, I believe this should be in accordance with the above suggestion.

Comment (Jefffrey) [reply datafusion/spark/src/function/string/format_string.rs:99]: Ah I didn't see the `DataType::Utf8`; I think we need to keep that for Null arm

Comment (skushagra) [reply datafusion/spark/src/function/string/format_string.rs:99]: updated

**Comment by Jefffrey** [comment]
Thanks @skushagra
