### PR TITLE
fix: IS NULL panic with invalid function without input arguments

### LINKED ISSUE #20201: IS NULL doesn't type-check its input
### Describe the bug

The input expression to `IS NULL` isn't type-checked, unless for other constructs (`IS TRUE`, binary operators, etc.)

### To Reproduce

```
CREATE TABLE tt();
SELECT * FROM tt WHERE ((STARTS_WITH()) IS NULL);
```

Yields:

```
thread 'main' (41425691) panicked at datafusion/functions/src/string/starts_with.rs:168:54:
index out of bounds: the len is 0 but the index is 1
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/std/src/panicking.rs:698:5
   1: core::panicking::panic_fmt
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/core/src/panicking.rs:80:14
   2: core::panicking::panic_bounds_check
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/core/src/panicking.rs:276:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /Users/neilconway/.rustup/toolchains/1.92.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:267:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /Users/neilconway/.rustup/toolchains/1.92.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/slice/index.rs:18:15
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /Users/neilconway/.rustup/toolchains/1.92.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:3628:9
   6: <datafusion_functions::string::starts_with::StartsWithFunc as datafusion_expr::udf::ScalarUDFImpl>::simplify
             at ./datafusion/functions/src/string/starts_with.rs:168:54
```

### Expected behavior

The expected behavior is that `STARTS_WITH()` should be rejected at planning time because of a type mismatch -- which is what happens for other variants like `STARTS_WITH() IS TRUE`.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Acfboy**
## Which issue does this PR close?

- Closes #20201 .

## Rationale for this change

Unlike `Projection`, expressions within a `Filter` node do not always have their types resolved during the initial LogicalPlan generation. Validation is often deferred until the type_coercion phase. When invoking f_up on the expression tree to perform type coercion, the check is bypassed for function nodes with empty arguments, leading to a panic during subsequent execution.

For example, all statements below cause a panic:
```
SELECT * FROM (SELECT 1) WHERE (STARTS_WITH() IS NULL);
SELECT * FROM (SELECT 1) WHERE (STARTS_WITH() IS NOT NULL);
SELECT * FROM (SELECT 'a') WHERE (STARTS_WITH() SIMILAR TO 'abc%');
SELECT * FROM (SELECT 1) WHERE CAST(STARTS_WITH() AS STRING) = 'x';
SELECT * FROM (SELECT 1) WHERE TRY_CAST(STARTS_WITH() AS INT) IS NULL;
```

This pr aims to stop panic. It would be better if reject these invalid cases at planning.

## What changes are included in this PR?

```diff
 fn coerce_arguments_for_signature<F: UDFCoercionExt>(
      schema: &DFSchema,
      func: &F,
  ) -> Result<Vec<Expr>> {
-    if expressions.is_empty() {
-        return Ok(expressions);
-    }
```

Deleted the early return. Thanks to @neilconway .

## Are these changes tested?
All original tests passed. Added some unit tests and sqllogictests.

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/optimizer/src/analyzer/type_coercion.rs [hunk 1]
```diff
@@ -744,18 +744,47 @@ impl TreeNodeRewriter for TypeCoercionRewriter<'_> {
                 });
                 Ok(Transformed::yes(new_expr))
             }
+            // IS NULL / IS NOT NULL / SIMILAR TO / CAST / TRY_CAST validate
```
Comment (neilconway) [inline datafusion/optimizer/src/analyzer/type_coercion.rs]: I don't think comments should reference "previously" (previously to what?); they should just talk about the current state of the code.

I'd rephrase this comment to something like:

```
// IS NULL, IS NOT NULL, SIMILAR TO, CAST, and TRY CAST don't require
// type coercion, but we need to handle them here to ensure that their
// arguments have type coercion and type checking applied (see #20201
// for context).
```

File: datafusion/optimizer/src/analyzer/type_coercion.rs [hunk 2]
```diff
@@ -2742,4 +2771,69 @@ mod test {
...
     }
+
+    fn zero_arg_scalar_func() -> Expr {
+        let fun = ScalarUDF::new_from_impl(TestScalarUDF {
+            signature: Signature::uniform(1, vec![DataType::Float32], Volatility::Stable),
+        });
+        Expr::ScalarFunction(ScalarFunction::new_udf(Arc::new(fun), vec![]))
+    }
+
+    #[test]
```
Comment (neilconway) [inline datafusion/optimizer/src/analyzer/type_coercion.rs]: These tests feel redundant to the SLT tests, no? In my opinion we should be fine with just adding the SLT tests only (which arguably is closer to testing the user-visible behavior anyway).

File: datafusion/sqllogictest/test_files/type_coercion.slt [hunk 3]
```diff
@@ -281,3 +281,30 @@ SELECT true FROM t0 WHERE (REGEXP_MATCH(t0.v1, t0.v1)) NOT ILIKE [];
 
 statement ok
 DROP TABLE t0;
+
+###############################################################################
+## Test that IS NULL / IS NOT NULL / SIMILAR TO / CAST / TRY_CAST validate  ##
+## their inner expressions during type coercion (previously they were in     ##
```
Comment (neilconway) [inline datafusion/sqllogictest/test_files/type_coercion.slt]: I'm omit discussion of the previous incorrect behavior, I'd just talk about the current/correct behavior under test.

File: datafusion/optimizer/src/analyzer/type_coercion.rs [hunk 4]
```diff
@@ -744,18 +744,47 @@ impl TreeNodeRewriter for TypeCoercionRewriter<'_> {
...
+            // the catch-all branch and skipped validation, which caused panics at
+            // runtime for invalid inner expressions like zero-argument function calls).
+            // Detail: <https://github.com/apache/datafusion/issues/20201>
+            //
+            // TODO: reject the invalid cases at planning.
+            Expr::IsNotNull(ref inner_expr) | Expr::IsNull(ref inner_expr) => {
+                let _check_type = inner_expr.get_type(self.schema)?;
+                Ok(Transformed::no(expr))
+            }
+            Expr::SimilarTo(Like {
```
Comment (neilconway) [inline datafusion/optimizer/src/analyzer/type_coercion.rs]: I wonder whether the handling of `SIMILAR TO` should be more similar to how we handle `LIKE`?

File: datafusion/optimizer/src/analyzer/type_coercion.rs (hunk 1 above)
Comment (Acfboy) [reply datafusion/optimizer/src/analyzer/type_coercion.rs]: Thanks, modified.

File: datafusion/optimizer/src/analyzer/type_coercion.rs (hunk 2 above)
Comment (Acfboy) [reply datafusion/optimizer/src/analyzer/type_coercion.rs]: I don't see it as overlapping. slt ensures the whole path works, and unit tests are there to help us isolate the root cause when something goes wrong.

File: datafusion/optimizer/src/analyzer/type_coercion.rs (hunk 4 above)
Comment (Acfboy) [reply datafusion/optimizer/src/analyzer/type_coercion.rs]: I suspect this is because the current implementation has focused more on optimizing LIKE. Many of these optimizations could likely be applied to SIMILAR TO as well, but they are probably just yet to be implemented.

For this issue, let's maintain consistency with the existing implementation. Maybe we should create separate issues to refine how SIMILAR TO is handled.

Comment (neilconway) [reply datafusion/optimizer/src/analyzer/type_coercion.rs]: I wasn't thinking about optimizations; my concern was more whether the type coercion that is done for `LIKE` should also be done for `IS SIMILAR TO` for correctness reasons. Some digging suggests this might be the case:

```
-- works
  SELECT CAST('hello' AS BYTEA) LIKE 'hello%';

-- fails ("Cannot infer common argument type for regex operation Binary ~ Utf8")
  SELECT CAST('hello' AS BYTEA) SIMILAR TO 'hello%';

-- works
  SELECT arrow_cast('hello', 'Dictionary(Int32, Utf8)') LIKE 'hello%';

-- fails ("Data type Dictionary(Int32, Utf8) not supported for regex_match_dyn")
  SELECT arrow_cast('hello', 'Dictionary(Int32, Utf8)') SIMILAR TO 'hello%';
  ```

**Comment by neilconway** [comment]
Digging into this a bit further, this fix seems cleaner to me:

```
diff --git a/datafusion/optimizer/src/analyzer/type_coercion.rs b/datafusion/optimizer/src/analyzer/type_coercion.rs
index c2121f45c..1a8218a1e 100644
--- a/datafusion/optimizer/src/analyzer/type_coercion.rs
+++ b/datafusion/optimizer/src/analyzer/type_coercion.rs
@@ -954,10 +954,6 @@ fn coerce_arguments_for_signature<F: UDFCoercionExt>(
     schema: &DFSchema,
     func: &F,
 ) -> Result<Vec<Expr>> {
-    if expressions.is_empty() {
-        return Ok(expressions);
-    }
-
     let current_fields = expressions
         .iter()
         .map(|e| e.to_field(schema).map(|(_, f)| f))
```

i.e., `coerce_arguments_for_signature()` -> `fields_with_udf()` is *already* checking for functions that require arguments but that are invoked with no arguments, but this is effectively dead code because we exit early before we get there. If we just remove the early-exit then the behavior seems right to me. What do you think?

File: datafusion/optimizer/src/analyzer/type_coercion.rs (hunk 4 above)
Comment (neilconway) [reply datafusion/optimizer/src/analyzer/type_coercion.rs]: I filed #20342, I'll take a look at fixing shortly.

File: datafusion/optimizer/src/analyzer/type_coercion.rs (hunk 2 above)
Comment (alamb) [reply datafusion/optimizer/src/analyzer/type_coercion.rs]: I agree with @neilconway  here -- I do think the tests are redundant and I think we can just use the slt tests

File: datafusion/sqllogictest/test_files/type_coercion.slt [hunk 5]
```diff
@@ -281,3 +281,30 @@ SELECT true FROM t0 WHERE (REGEXP_MATCH(t0.v1, t0.v1)) NOT ILIKE [];
...
 DROP TABLE t0;
+
+###############################################################################
+## Test that IS NULL / IS NOT NULL / SIMILAR TO / CAST / TRY_CAST validate   ##
+## their inner expressions.                                                  ##
+###############################################################################
+
+# https://github.com/apache/datafusion/issues/20201
+
+# IS NULL should reject invalid inner expression
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/type_coercion.slt]: I ran these tests without the code changes to verify they cover the issue and they fail like

```
Completed 403 test files in 8 seconds                                                                                                                                         failure in type_coercion.slt for sql SELECT * FROM (SELECT 1) WHERE (STARTS_WITH() IS NULL);
caused by
External error: task 22188 panicked with message "index out of bounds: the len is 0 but the index is 1"
Error: Execution("1 failures")
error: test failed, to rerun pass `-p datafusion-sqllogictest --test sqllogictests`
```

**Comment by neilconway** [comment]
> Thanks @Acfboy and @neilconway
> 
> I think this looks good to me

Thanks @alamb ! I'm curious what you think of the alternative approach I suggested https://github.com/apache/datafusion/pull/20306#issuecomment-3898530434

**Comment by alamb** [comment]
>  If we just remove the early-exit then the behavior seems right to me. What do you think?

I think that sounds like a great change to me

**Comment by Acfboy** [comment]
> i.e., `coerce_arguments_for_signature()` -> `fields_with_udf()` is _already_ checking for functions that require arguments but that are invoked with no arguments, but this is effectively dead code because we exit early before we get there. If we just remove the early-exit then the behavior seems right to me. What do you think?

It seems this only works for cases where UDFs are called without arguments. However, there are other cases failing due to a lack of type-checking in IS NULL. For example, `SELECT * FROM (SELECT 1) WHERE ((1.0 << 2.0) IS NULL);` is expected to report that we can't run float << float, but it actually runs without error after constant folding by the optimizer.

File: datafusion/sqllogictest/test_files/type_coercion.slt (hunk 5 above)
Comment (Acfboy) [reply datafusion/sqllogictest/test_files/type_coercion.slt]: Thanks for the review, @alamb and @neilconway. I have removed the redundant unit tests in type_coercion.rs and will rely on the .slt tests for coverage as suggested.

**Comment by neilconway** [comment]
> It seems this only works for cases where UDFs are called without arguments. However, there are other cases failing due to a lack of type-checking in IS NULL. For example, `SELECT * FROM (SELECT 1) WHERE ((1.0 << 2.0) IS NULL);` is expected to report that we can't run float << float, but it actually runs without error after constant folding by the optimizer.

Good point!

Can you add one or more example queries like this to the SLT tests?

**Comment by Acfboy** [comment]
@neilconway Thanks! While trying to add some tests, another bug occurs: #20355 . So I can't add something like `SELECT * FROM (SELECT 1) WHERE ((-'abc') IS NULL);` to slt tests now.

Also, my apologies for the oversight. Binary operators are indeed type-checked. The bitwise operation issue was a bug that's already been fixed in a merged PR. I've checked the other branches, and it appears that only unary negation and function calls still have this problem.

**Comment by neilconway** [comment]
Proposal:

1. Remove the early return from `coerce_arguments_for_signature()`, because that seems wrong in any case. (I'm happy to send a PR for this or you can, @Acfboy -- lmk what you prefer)
2. Fix #20355 and #20342 separately

My understanding is that if we do the above, we don't need the changes to `TypeCoercionRewriter` proposed in this PR -- is that correct?

**Comment by Acfboy** [comment]
Thanks @neilconway ! You are right. I have changed the pr and re-request reivews.
