### PR TITLE
Fix `SortPreservingMergeExec` tree formatting with limit

### LINKED ISSUE #18008: `SortPreservingMergeExec` tree formatting with limit is missing a new line
### Describe the bug

When formatting a `SortPreservingMergeExec` node with a limit, there's no space or line break between the expression and the limit.
For example:

Image

### To Reproduce

1. Create table with `WITH ORDER` clause, backed by multiple files.
2. Run a query with both a limit and `ORDER BY` clause that matches the table's order, prefixed with `EXPLAIN FORMAT TREE`.

### Expected behavior

Like other fields and nodes, have a separate line for the limit.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AdamGS**
## Which issue does this PR close?

- Closes #18008.

The PR is split into two commits, the first one includes a passing test that shows the bug, and the second PR fixes the formatting and the test. 

## Rationale for this change

Fixes tree formatting for `SortPreservingMergeExec`

## What changes are included in this PR?

Fix tree formatting for `SortPreservingMergeExec` and add a test for the behavior.

## Are these changes tested?

A new slt test

## Are there any user-facing changes?

Only if a user asserts the tree-display in this case.

### CODE REVIEW

File: datafusion/physical-plan/src/sorts/sort_preserving_merge.rs [hunk 1]
```diff
@@ -204,7 +204,9 @@ impl DisplayAs for SortPreservingMergeExec {
                         write!(f, ", ")?;
                     }
                 }
+
                 if let Some(fetch) = self.fetch {
+                    writeln!(f)?;
                     writeln!(f, "limit={fetch}")?;
```
Comment (alamb) [inline datafusion/physical-plan/src/sorts/sort_preserving_merge.rs]: I wonder if the last one should be just `write!` rather than `writeln!` 🤔

Comment (Weijun-H) [reply datafusion/physical-plan/src/sorts/sort_preserving_merge.rs]: Alternatively, we could move the previous logic before the `PhysicalSortExec` iteration, which would be more intuitive.

Comment (AdamGS) [reply datafusion/physical-plan/src/sorts/sort_preserving_merge.rs]: @Weijun-H took your suggestion, definitely cleaner

**Comment by alamb** [comment]
Thanks @AdamGS and @Weijun-H !
