### PR TITLE
fix: projection for `CooperativeExec` and `CoalesceBatchesExec`

### LINKED ISSUE #19398: `CoalesceBatchesExec` and `CooperativeExec` prevent projection pushdown
### Describe the bug

current in datafusion we have projection pushdown optimizer rule before the the optimizer rule that add `CoalesceBatchesExec` and `CooperativeExec`, it work fine.
https://github.com/apache/datafusion/blob/d493f3d441aa30e7e83d4ff918e07681f985a966/datafusion/physical-optimizer/src/optimizer.rs#L122-L151

but in another case, if you want to do projection down again for the phsycial plan that already go thoung one round physical optimzier rule, the projection pushdown will not able to go through for `CoalesceBatchesExec` and `CooperativeExec`

### To Reproduce

```rust
use std::sync::Arc;

use arrow::{
    array::{ArrayRef, Int32Array, RecordBatch},
    datatypes::{DataType, Field, Schema},
};
use datafusion::{
    common::config::ConfigOptions,
    datasource::MemTable,
    physical_expr::PhysicalExpr,
    physical_optimizer::{
        PhysicalOptimizerRule, projection_pushdown::ProjectionPushdown,
    },
    physical_plan::{
        ExecutionPlan, coalesce_batches::CoalesceBatchesExec, displayable,
        expressions::Column, projection::ProjectionExec,
    },
    prelude::{SessionContext, col, lit},
};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let schema = Arc::new(Schema::new(vec![
        Field::new("a", DataType::Int32, false),
        Field::new("b", DataType::Int32, false),
        Field::new("c", DataType::Int32, false),
        Field::new("d", DataType::Int32, false),
    ]));
    let mut partitions = vec![];
    for _ in 0..4 {
        let batch = RecordBatch::try_new(
            schema.clone(),
            vec![
                Arc::new(Int32Array::from(vec![1, 2, 3])) as ArrayRef,
                Arc::new(Int32Array::from(vec![4, 5, 6])) as ArrayRef,
                Arc::new(Int32Array::from(vec![7, 8, 9])) as ArrayRef,
                Arc::new(Int32Array::from(vec![10, 11, 12])) as ArrayRef,
            ],
        )?;
        partitions.push(vec![batch]);
    }
    let table = MemTable::try_new(schema.clone(), partitions)?;
    let ctx = SessionContext::new();
    ctx.register_table("test", Arc::new(table))?;

    // physical plan after optimizer rules are applied
    let physical_plan = ctx
        .table("test")
        .await?
        .select_columns(&["a", "b", "c"])?
        .filter(col("c").gt(lit(0)))?
        .create_physical_plan()
        .await?;
    println!(
        "{}",
        displayable(physical_plan.as_ref())
            .set_show_schema(true)
            .indent(true)
    );

    // add projection and coalesce batches exec, then apply projection pushdown
    let physical_plan = Arc::new(ProjectionExec::try_new(
        vec![
            (
                Arc::new(Column::new("a", 0)) as Arc<dyn PhysicalExpr>,
                "a".to_string(),
            ),
            (
                Arc::new(Column::new("b", 1)) as Arc<dyn PhysicalExpr>,
                "b".to_string(),
            ),
        ],
        Arc::new(CoalesceBatchesExec::new(physical_plan.clone(), 8192))
            as Arc<dyn ExecutionPlan>,
    )?);
    let config = ConfigOptions::new();
    let projection_pushdown = ProjectionPushdown::new();
    let optimized = projection_pushdown.optimize(physical_plan.clone(), &config)?;
    // projection pushdown is not applied
    println!(
        "{}",
        displayable(optimized.as_ref())
            .set_show_schema(true)
            .indent(true)
    );

    Ok(())
}
```
result
```
FilterExec: c@2 > 0, schema=[a:Int32, b:Int32, c:Int32]
  DataSourceExec: partitions=4, partition_sizes=[1, 1, 1, 1], schema=[a:Int32, b:Int32, c:Int32]

ProjectionExec: expr=[a@0 as a, b@1 as b], schema=[a:Int32, b:Int32]
  CoalesceBatchesExec: target_batch_size=8192, schema=[a:Int32, b:Int32, c:Int32]
    FilterExec: c@2 > 0, schema=[a:Int32, b:Int32, c:Int32]
      DataSourceExec: partitions=4, partition_sizes=[1, 1, 1, 1], schema=[a:Int32, b:Int32, c:Int32]
```

### Expected behavior

projection pushdown can go though `CoalesceBatchesExec` and `CooperativeExec` 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by haohuaijin**
## Which issue does this PR close?

close #19398 

## Rationale for this change

see issue #19398

## What changes are included in this PR?

impl `try_swapping_with_projection` for `CooperativeExec` and `CoalesceBatchesExec`

## Are these changes tested?

add test case

### CODE REVIEW

File: datafusion/physical-plan/src/coalesce_batches.rs [hunk 1]
```diff
@@ -226,6 +227,19 @@ impl ExecutionPlan for CoalesceBatchesExec {
...
     }
 
+    fn try_swapping_with_projection(
+        &self,
+        projection: &ProjectionExec,
+    ) -> Result<Option<Arc<dyn ExecutionPlan>>> {
+        match self.input.try_swapping_with_projection(projection)? {
+            Some(new_input) => Ok(Some(Arc::new(
+                CoalesceBatchesExec::new(new_input, self.target_batch_size)
+                    .with_fetch(self.fetch),
```
Comment (xudong963) [inline datafusion/physical-plan/src/coalesce_batches.rs]: There is a `with_new_children` API

**Comment by haohuaijin** [comment]
in this pr, the result for #19398 is below
```
FilterExec: c@2 > 0, schema=[a:Int32, b:Int32, c:Int32]
  DataSourceExec: partitions=4, partition_sizes=[1, 1, 1, 1], schema=[a:Int32, b:Int32, c:Int32]

CoalesceBatchesExec: target_batch_size=8192, schema=[a:Int32, b:Int32]
  FilterExec: c@2 > 0, projection=[a@0, b@1], schema=[a:Int32, b:Int32]
    DataSourceExec: partitions=4, partition_sizes=[1, 1, 1, 1], schema=[a:Int32, b:Int32, c:Int32]
```
main branch is
```
FilterExec: c@2 > 0, schema=[a:Int32, b:Int32, c:Int32]
  DataSourceExec: partitions=4, partition_sizes=[1, 1, 1, 1], schema=[a:Int32, b:Int32, c:Int32]

ProjectionExec: expr=[a@0 as a, b@1 as b], schema=[a:Int32, b:Int32]
  CoalesceBatchesExec: target_batch_size=8192, schema=[a:Int32, b:Int32, c:Int32]
    FilterExec: c@2 > 0, schema=[a:Int32, b:Int32, c:Int32]
      DataSourceExec: partitions=4, partition_sizes=[1, 1, 1, 1], schema=[a:Int32, b:Int32, c:Int32]
```

File: datafusion/physical-plan/src/coalesce_batches.rs (hunk 1 above)
Comment (haohuaijin) [reply datafusion/physical-plan/src/coalesce_batches.rs]: i check the `with_new_children` accept a `Arc<Self>`, but in `try_swapping_with_projection` accept `&self`, so if use `with_new_children` we need copy the self like
```rust
Arc::new(self.clone()).with_new_children(vec![new_input])?;
```

File: datafusion/physical-plan/src/coop.rs [hunk 2]
```diff
@@ -298,6 +299,16 @@ impl ExecutionPlan for CooperativeExec {
...
 
+    fn try_swapping_with_projection(
+        &self,
+        projection: &ProjectionExec,
+    ) -> Result<Option<Arc<dyn ExecutionPlan>>> {
+        match self.input.try_swapping_with_projection(projection)? {
+            Some(new_input) => Ok(Some(Arc::new(CooperativeExec::new(new_input)))),
+            None => Ok(None),
+        }
+    }
```
[the remark this answers is not in the document]
Comment (haohuaijin) [reply datafusion/physical-plan/src/coop.rs:312]: CooperativeExec is transparent for projection

File: datafusion/physical-plan/src/coalesce_batches.rs (hunk 1 above)
Comment (Dandandan) [reply datafusion/physical-plan/src/coalesce_batches.rs]: I think in this case it's not very different as `CoalesceBatchesExec::new` does also create a new instance.

Comment (haohuaijin) [reply datafusion/physical-plan/src/coalesce_batches.rs]: updated

**Comment by haohuaijin** [comment]
Thanks @xudong963 and @Dandandan for reviews, already apply suggestion.
