### PR TITLE
fix: unparsing left/ right semi/mark join

### LINKED ISSUE #15127: Unparse of logical plans with `LEFT ANTI` and `LEFT SEMI` joins generate invalid SQL
### Describe the bug

When unparsing a logical plan containing a `LeftAnti Join` or a `LeftSemi Join` operator with the `unparser::dialect::PostgreSqlDialect`, the resulting unparsed SQL contains `LEFT ANTI JOIN` or `LEFT SEMI JOIN`, respectively, which are not supported by Postgres. The same thing is true for other dialects such as `unparser::dialect::MySqlDialect` and `unparser::dialect::SqliteDialect`.

This causes issues when attempting to run federated queries in Datafusion over systems such as Postgres (namely, in the [datafusion-table-providers](https://github.com/datafusion-contrib/datafusion-table-providers) repo).

I'm not sure if this is a bug or if the responsibility to generate valid SQL in a specific dialect should be delegated downstream. However, since there appears to be a previous PR with a similar issue (https://github.com/apache/datafusion/pull/10625), I leave this one here just in case.

### To Reproduce

```rust
use datafusion::{
    error::Result,
    prelude::SessionContext,
    sql::unparser::{self, Unparser},
};

#[tokio::main]
async fn main() -> Result<()> {
    let ctx = SessionContext::new();
    ctx.sql("create table t1 (c int)").await?.collect().await?;
    ctx.sql("create table t2 (c int)").await?.collect().await?;

    let df = ctx
        .sql("select * from t1 where c not in (select c from t2)")
        .await?;

    let plan = df.into_optimized_plan()?; // optimizing the plan will introduce the LeftAnti Join
    println!("{}", plan);

    let sql = Unparser::new(&unparser::dialect::PostgreSqlDialect {}).plan_to_sql(&plan)?;
    println!("{}", sql);

    Ok(())
}
```

Which returns the (invalid in Postgres) query: 
```sql
SELECT * FROM "t1" LEFT ANTI JOIN "t2" AS "__correlated_sq_1" ON "t1"."c" = "__correlated_sq_1"."c"
```

### Expected behavior

Generate an equivalent valid query, such as:

```sql
SELECT * FROM t1 WHERE c NOT IN (SELECT c FROM t2)
```

### Additional context

```toml
datafusion = "45.0.0"
```

### PR DESCRIPTION
**Pull request by chenkovsky**
## Which issue does this PR close?

- Closes #15127.

## Rationale for this change

Most SQL dialects don't support specialized join types like LEFT SEMI, LEFT ANTI, LEFT MARK, RIGHT SEMI, or RIGHT ANTI joins. 

## What changes are included in this PR?

For these cases, this PR rewrites these joins into equivalent EXISTS subqueries. 

However, an alternative approach would be to generate dialect-specific SQL for different database engines.

## Are these changes tested?

unit test

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/sql/src/unparser/ast.rs [hunk 1]
```diff
@@ -176,6 +177,41 @@ impl SelectBuilder {
...
+    /// with the actual join condition in the selection clause.
+    ///
+    /// # Arguments
+    ///
+    /// * `existing_expr` - The expression to replace
+    /// * `value` - The new expression to set as the selection
+    ///
+    /// # Returns
+    ///
+    /// A mutable reference to self for method chaining
```
Comment (goldmedal) [inline datafusion/sql/src/unparser/ast.rs:198]:
```suggestion
```
It's redundant.

File: datafusion/sql/tests/cases/plan_to_sql.rs [hunk 2]
```diff
@@ -1746,3 +1749,153 @@ fn test_unparse_subquery_alias_with_table_pushdown() -> Result<()> {
...
 }
+
+#[test]
+fn test_unparse_left_anti_join() -> Result<()> {
+    let schema = Schema::new(vec![
+        Field::new("c", DataType::Int32, false),
+        Field::new("d", DataType::Int32, false),
+    ]);
+
+    // LeftAnti Join: t1.c = __correlated_sq_1.c
```
Comment (goldmedal) [inline datafusion/sql/tests/cases/plan_to_sql.rs:1760]: Could you add the original SQL in the comment? It would be nice for other people to know where the plan comes from.

File: datafusion/sql/tests/cases/plan_to_sql.rs [hunk 3]
```diff
@@ -1746,3 +1749,153 @@ fn test_unparse_subquery_alias_with_table_pushdown() -> Result<()> {
...
+                vec![Column::from_qualified_name("t1.c")],
+                vec![Column::from_qualified_name("t2.c")],
+            ),
+            None,
+        )?
+        .filter(col("t1.c").lt_eq(lit(1i64)))?
+        .build()?;
+    let unparser = Unparser::new(&UnparserPostgreSqlDialect {});
+    let sql = unparser.plan_to_sql(&plan)?;
+    assert_eq!("SELECT \"t2\".\"c\", \"t2\".\"d\" FROM \"t1\" WHERE (\"t1\".\"c\" <= 1) AND NOT EXISTS (SELECT 1 FROM \"t1\" WHERE (\"t1\".\"c\" = \"t2\".\"c\"))", sql.to_string());
```
Comment (goldmedal) [inline datafusion/sql/tests/cases/plan_to_sql.rs:1899]: This result isn't valid for DataFusion and Postgres. 
```
psql=# create table t1 (c int, d int);
CREATE TABLE
psql=# create table t2 (c int, d int);
CREATE TABLE
psql=# SELECT "t2"."c", "t2"."d" FROM "t1" WHERE ("t1"."c" <= 1) AND NOT EXISTS (SELECT 1 FROM "t1" WHERE ("t1"."c" = "t2"."c"));
ERROR:  missing FROM-clause entry for table "t2"
LINE 1: SELECT "t2"."c", "t2"."d" FROM "t1" WHERE ("t1"."c" <= 1) AN...
```
I guess the clause `FROM t1` is wrong.

File: datafusion/sql/tests/cases/plan_to_sql.rs [hunk 4]
```diff
@@ -1746,3 +1749,153 @@ fn test_unparse_subquery_alias_with_table_pushdown() -> Result<()> {
...
+                vec![Column::from_qualified_name("t1.c")],
+                vec![Column::from_qualified_name("t2.c")],
+            ),
+            None,
+        )?
+        .filter(col("t1.c").lt_eq(lit(1i64)))?
+        .build()?;
+    let unparser = Unparser::new(&UnparserPostgreSqlDialect {});
+    let sql = unparser.plan_to_sql(&plan)?;
+    assert_eq!("SELECT \"t2\".\"c\", \"t2\".\"d\" FROM \"t1\" WHERE (\"t1\".\"c\" <= 1) AND EXISTS (SELECT 1 FROM \"t1\" WHERE (\"t1\".\"c\" = \"t2\".\"c\"))", sql.to_string());
```
Comment (goldmedal) [inline datafusion/sql/tests/cases/plan_to_sql.rs:1870]: It's a similar problem. The SQL isn't valid.

File: datafusion/sql/tests/cases/plan_to_sql.rs [hunk 5]
```diff
@@ -1746,3 +1749,153 @@ fn test_unparse_subquery_alias_with_table_pushdown() -> Result<()> {
...
+    Ok(())
+}
+
+#[test]
+fn test_unparse_left_mark_join() -> Result<()> {
+    // select t1.id from t1 where t1.id < 0 OR exists(SELECT t2.id FROM t2 WHERE t1.id = t2.id)
+    let schema = Schema::new(vec![
+        Field::new("c", DataType::Int32, false),
+        Field::new("d", DataType::Int32, false),
+    ]);
```
Comment (goldmedal) [inline datafusion/sql/tests/cases/plan_to_sql.rs:1819]: I don't think the SQL matches this schema 🤔. Where is `t1.id`?

File: datafusion/sql/tests/cases/plan_to_sql.rs [hunk 6]
```diff
@@ -1746,3 +1749,153 @@ fn test_unparse_subquery_alias_with_table_pushdown() -> Result<()> {
...
+            datafusion_expr::JoinType::LeftMark,
+            vec![col("t1.id").eq(col("__correlated_sq_1.id"))],
+        )?
+        .project(vec![col("t1.d")])?
+        .filter(col("mark").or(col("t1.d").lt(lit(0))))?
+        .build()?;
+
+    let unparser = Unparser::new(&UnparserPostgreSqlDialect {});
+    let sql = unparser.plan_to_sql(&plan)?;
+    assert_eq!("SELECT \"t1\".\"d\" FROM \"t1\" WHERE (EXISTS (SELECT 1 FROM \"t2\" AS \"__correlated_sq_1\" WHERE (\"t1\".\"id\" = \"__correlated_sq_1\".\"id\")) OR (\"t1\".\"d\" < 0))", sql.to_string());
```
Comment (goldmedal) [inline datafusion/sql/tests/cases/plan_to_sql.rs:1841]: If the schema of t1 is `t1(c int, b int)`, the SQL is invalid.

**Review by goldmedal — COMMENTED** [review]
Thanks @chenkovsky. I think the results of `left mark join`, `right semi join` and `right anit join` aren't correct (they aren't executable). I left some comments for them. Could you double-check them?

**Comment by goldmedal** [comment]
> for stackoverflow problem. do you have any idea?

No, I don't have any idea currently 🤔. I'm not sure, but I guess `recursive_protection` is the right direction.

File: .github/workflows/rust.yml [hunk 7]
```diff
@@ -246,6 +246,7 @@ jobs:
             mc cp -r /source/* localminio/data"
       - name: Run tests (excluding doctests)
         env:
+          RUST_MIN_STACK: 4194304
```
Comment (goldmedal) [inline .github/workflows/rust.yml:249]: This test has been modified in the `main` branch. It seems that it never happens stack overflow anymore.

File: datafusion/sql/src/unparser/expr.rs [hunk 8]
```diff
@@ -94,6 +94,7 @@ impl Unparser<'_> {
         Ok(root_expr)
     }
 
+    #[cfg_attr(feature = "recursive_protection", recursive::recursive)]
```
Comment (goldmedal) [inline datafusion/sql/src/unparser/expr.rs:97]: This annotation should be enabled by using the  `recursive_protection` feature. I found the CI doesn't enable it. I experimented with it https://github.com/apache/datafusion/pull/15272 (It seems to work well)
You can see how I modified the workflow.

File: .github/workflows/extended.yml [hunk 9]
```diff
@@ -81,6 +81,7 @@ jobs:
       - name: Run tests (excluding doctests)
         env:
           RUST_BACKTRACE: 1
+          RUST_MIN_STACK: 4194304
```
Comment (goldmedal) [inline .github/workflows/extended.yml:84]: After enabling `recursive_protection`, it can be removed.

**Review by goldmedal — COMMENTED** [review]
It seems that the `main` branch optimized the CI flow. It's better to rebase or merge `main` firstly.

**Review by goldmedal — APPROVED** [review]
Thanks @chenkovsky. Overall look great 👍
