### PR TITLE
Fix sqllogictests test running compatibility (ignore `--test-threads`)

### LINKED ISSUE #16693: Running tests with `--test-threads` option fails.
### Describe the bug

Running `cargo test -- --test-threads 1` in the project root fails, complaining about unrecognised option.

### To Reproduce

Run `cargo test -- --test-threads 1`

### Expected behavior

Tests should run and pass

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mjgarton**
sqllogictests.rs already has various parts of it's Options struct that provide compatibility with the standard test running options.

Extend this to include the standard `--test-threads` option, so that running for example `cargo test -- --test-threads 1` in the project root will succeed.  Previously it complained about the unknown option.

This can be useful on a machine with a large number of cores which causes many tests to build & run in parallel, which in my case caused a crash due to exhausing the system RAM.

Fixes #16693

### CODE REVIEW

File: datafusion/sqllogictest/bin/sqllogictests.rs [hunk 1]
```diff
@@ -689,6 +689,12 @@ struct Options {
         help = "IGNORED (for compatibility with built-in rust test runner)"
     )]
     nocapture: bool,
+
+    #[clap(
```
Comment (alamb) [inline datafusion/sqllogictest/bin/sqllogictests.rs:693]: Another thing we could do (as a follow on PR) is to actually thread this through to the runner:

https://github.com/apache/datafusion/blob/eeee6b00a0a0cf1bb449631b57535c06bbf99583/datafusion/sqllogictest/bin/sqllogictests.rs#L197-L196

**Review by alamb — APPROVED** [review]
Thank you @mjgarton  -- this makes sense to me

**Comment by alamb** [comment]
Thanks again @mjgarton

File: datafusion/sqllogictest/bin/sqllogictests.rs (hunk 1 above)
Comment (mjgarton) [reply datafusion/sqllogictest/bin/sqllogictests.rs:693]: I will follow up on this.

Comment (alamb) [reply datafusion/sqllogictest/bin/sqllogictests.rs:693]: Thank you -- I filed a ticket to track
- https://github.com/apache/datafusion/issues/16723
