### PR TITLE
test: get file size by func metadata

### LINKED ISSUE #11574: always failed test on datasource::file_format::csv::tests::test_csv_parallel_one_col::case_6 on windows machine
### Describe the bug

test datasource::file_format::csv::tests::test_csv_parallel_one_col::case_1 ... ok
test datasource::file_format::csv::tests::test_csv_parallel_one_col::case_2 ... ok
test datasource::file_format::csv::tests::test_csv_parallel_one_col::case_3 ... ok
test datasource::file_format::csv::tests::test_csv_parallel_one_col::case_4 ... ok
test datasource::file_format::csv::tests::test_csv_parallel_one_col::case_5 ... ok
thread 'datasource::file_format::csv::tests::test_csv_parallel_one_col::case_6' panicked at datafusion\core\src\datasource\file_format\csv.rs:1267:9:
assertion `left == right` failed
  left: 30
 right: 20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test datasource::file_format::csv::tests::test_csv_parallel_one_col::case_6 ... FAILED

failures:

failures:
failures:
failures:
    datasource::file_format::csv::tests::test_csv_parallel_one_col::case_6
failures:
    datasource::file_format::csv::tests::test_csv_parallel_one_col::case_6

test result: FAILED. 5 passed; 1 failed; 0 ignored; 0 measured; 708 filtered out; finished in 0.11s

error: test failed, to rerun pass `--lib`

D:\workspace\rust\datafusion\datafusion\core>

failures:
    datasource::file_format::csv::tests::test_csv_parallel_one_col::case_6

test result: FAILED. 5 passed; 1 failed; 0 ignored; 0 measured; 708 filtered out; finished in 0.11s

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

I notice that, below code, which gets file_size of `one_col.csv` by target_os. I don't think this is right.
https://github.com/apache/datafusion/blob/5da7ab300215c44ca5dc16771091890de22af99b/datafusion/core/src/datasource/file_format/csv.rs#L1254-L1258
Because `tests/data/one_col.csv` is save as `lf` instead of `crlf`, won't apprear `\r\n`. I got file info in windows machine. according file info, this file is 20bytes.
```cmd
 Directory of D:\workspace\rust\datafusion\datafusion\core\tests\data

2024/06/19  21:40                20 one_col.csv
               1 File(s)             20 bytes
               0 Dir(s)   4,626,849,792 bytes free
```

### PR DESCRIPTION
**Pull request by zhuliquan**
## Which issue does this PR close?

Closes #11574.

## Rationale for this change

fix failure running of case test_csv_parallel_one_col on windows machine
## What changes are included in this PR?
getting `file_size` according to func `metadata` instead of `target_os`

## Are these changes tested?

yes
## Are there any user-facing changes?

no

### CODE REVIEW

File: datafusion/core/src/datasource/file_format/csv.rs [hunk 1]
```diff
@@ -1251,11 +1251,8 @@ mod tests {
             "+-----------------------+",
             "| 50                    |",
             "+-----------------------+"];
-        let file_size = if cfg!(target_os = "windows") {
-            30 // new line on Win is '\r\n'
-        } else {
-            20
-        };
+
+        let file_size = std::fs::metadata("tests/data/one_col.csv")?.len() as usize;
```
Comment (alamb) [inline datafusion/core/src/datasource/file_format/csv.rs:1255]: I wonder how this test is passing on CI? In theory we run these tests on CI: 

https://github.com/apache/datafusion/actions/runs/10044145872/job/27758535504

but somehow this test does not appear to run 🤔

**Review by alamb — APPROVED** [review]
Thanks @zhuliquan  -- this makes sense to me.

I don't understand how this issue isn't caught on the CI runner though

**Comment by alamb** [comment]
> I'am not sure that ci run unittests on real windows machine according to workflow yaml.

Or maybe it runs in [WSL](https://learn.microsoft.com/en-us/windows/wsl/faq) or something

**Comment by alamb** [comment]
Anyhow, thanks again @zhuliquan
