### PR TITLE
Using display_name for Expr::Aggregation

### LINKED ISSUE #10878: Aggregate with `FILTER` clause and alias errors
### Describe the bug

See the following code:

```python
import datafusion

print(f"datafusion: {datafusion.__version__}")

ctx = datafusion.SessionContext(
    datafusion.SessionConfig(
        {"datafusion.sql_parser.dialect": "PostgreSQL"}
    ).with_information_schema(True)
)

ctx.from_pydict({"a": [1, 3, 5]}, name="test")

# A query with no alias works
good = "SELECT MIN(a) FILTER (WHERE a > 1) FROM test"
print(ctx.sql(good))

# A query with an IN filter works
bad = "SELECT MIN(a) FILTER (WHERE a IN (1, 2)) AS x FROM test"
print(ctx.sql(bad))

# But one with an inequality and an alias fails
bad = "SELECT MIN(a) FILTER (WHERE a > 1) AS x FROM test"
print(ctx.sql(bad))
```

And results:

```
datafusion: 38.0.1
DataFrame()
+-------------+
| MIN(test.a) |
+-------------+
| 3           |
+-------------+
DataFrame()
+---+
| x |
+---+
| 1 |
+---+
Traceback (most recent call last):
  File "/home/jcristharif/Code/ibis/bug.py", line 23, in <module>
    print(ctx.sql(bad))
Exception: Internal error: Input field name MIN(test.a) does not match with the projection expression MIN(test.a) FILTER (WHERE test.a > Int64(1)).
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

All 3 queries do seem to work in versions `< 38.0.1`, so the bug appears to have been introduced in that version.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Lordworms**
## Which issue does this PR close?

Closes #10878

### CODE REVIEW

**Comment by Lordworms** [comment]
Also happened to solve #10364

**Comment by Lordworms** [comment]
The reason for the error is that the field name generation rules of AggregationFunction are different in logicalplan and physicalplan. The former uses display_name() and the latter uses create_physical_name.

File: datafusion/core/src/physical_planner.rs [hunk 1]
```diff
@@ -1916,6 +1916,7 @@ pub fn create_aggregate_expr_and_maybe_filter(
     // unpack (nested) aliased logical expressions, e.g. "sum(col) as total"
     let (name, e) = match e {
         Expr::Alias(Alias { expr, name, .. }) => (name.clone(), expr.as_ref()),
+        Expr::AggregateFunction(_) => (e.display_name().unwrap_or(physical_name(e)?), e),
```
Comment (jayzhan211) [inline datafusion/core/src/physical_planner.rs:1919]: How about we call `display_name` in `physical_name` like what ScalarFunction does. 
And even more, I think there are no such difference between logical name and physical name, maybe we can have one name for these two 🤔

Comment (jayzhan211) [reply datafusion/core/src/physical_planner.rs:1919]: It seems CastExpr is different in `write_name` and `Expr's Display` 🤔

Comment (Lordworms) [reply datafusion/core/src/physical_planner.rs:1919]: > It seems CastExpr is different in `write_name` and `Expr's Display` 🤔
> 
> And, there is an issue that expect CastExpr be shown in `write name`
> 
> #10274
> 
> CastExpr is removed in #3222, but I didn't find the rationale of doing this
> 
> If the issue is due to the schema change, then it will be quite tricky #10276
> 
> We can reuse `display_name` in `physical_name` to fix the regression first

Yes, I think calling display_name like physical name is a good idea, I tried it before, but there are some tests failed, there might be some reason that the display_name is different from physical name, I think for this issue, only change AggregateFunction is enough, I can take other related issue and fix them in the following PR, Thanks for review !

File: datafusion/core/tests/dataframe/mod.rs [hunk 2]
```diff
@@ -2194,3 +2194,44 @@ async fn write_parquet_results() -> Result<()> {
...
+    let config =
+        SessionConfig::from_string_hash_map(std::collections::HashMap::from([(
+            "datafusion.sql_parser.dialect".to_owned(),
+            "postgresql".to_owned(),
+        )]))?;
+    let ctx = SessionContext::new_with_config(config);
+
+    ctx.register_table("test", Arc::new(table))?;
+
+    let sql = "SELECT MIN(a) FILTER (WHERE a > 1) AS x FROM test";
```
Comment (jayzhan211) [inline datafusion/core/tests/dataframe/mod.rs:2218]: I'm not sure what is this test for 🤔 

Is it possible to move to slt?

```
statement ok
set datafusion.sql_parser.dialect = 'Postgres';

statement ok
create table t (a float) as values (1), (2), (3);

query TT
explain select min(a) filter (where a > 1) as x from t;
----
logical_plan
01)Projection: MIN(t.a) FILTER (WHERE t.a > Int64(1)) AS x
02)--Aggregate: groupBy=[[]], aggr=[[MIN(t.a) FILTER (WHERE t.a > Float32(1)) AS MIN(t.a) FILTER (WHERE t.a > Int64(1))]]
03)----TableScan: t projection=[a]
physical_plan
01)ProjectionExec: expr=[MIN(t.a) FILTER (WHERE t.a > Int64(1))@0 as x]
02)--AggregateExec: mode=Single, gby=[], aggr=[MIN(t.a) FILTER (WHERE t.a > Int64(1))]
03)----MemoryExec: partitions=1, partition_sizes=[1]

statement ok
drop table t;
```

Comment (Lordworms) [reply datafusion/core/tests/dataframe/mod.rs:2218]: Sure, I can do that.

Comment (Lordworms) [reply datafusion/core/tests/dataframe/mod.rs:2218]: > I'm not sure what is this test for 🤔
> 
> Is it possible to move to slt?
> 
> ```
> statement ok
> set datafusion.sql_parser.dialect = 'Postgres';
> 
> statement ok
> create table t (a float) as values (1), (2), (3);
> 
> query TT
> explain select min(a) filter (where a > 1) as x from t;
> ----
> logical_plan
> 01)Projection: MIN(t.a) FILTER (WHERE t.a > Int64(1)) AS x
> 02)--Aggregate: groupBy=[[]], aggr=[[MIN(t.a) FILTER (WHERE t.a > Float32(1)) AS MIN(t.a) FILTER (WHERE t.a > Int64(1))]]
> 03)----TableScan: t projection=[a]
> physical_plan
> 01)ProjectionExec: expr=[MIN(t.a) FILTER (WHERE t.a > Int64(1))@0 as x]
> 02)--AggregateExec: mode=Single, gby=[], aggr=[MIN(t.a) FILTER (WHERE t.a > Int64(1))]
> 03)----MemoryExec: partitions=1, partition_sizes=[1]
> 
> statement ok
> drop table t;
> ```

This test is for the original issue https://github.com/apache/datafusion/issues/10878

Comment (jayzhan211) [reply datafusion/core/tests/dataframe/mod.rs:2218]: > > I'm not sure what is this test for 🤔
> > Is it possible to move to slt?
> > ```
> > statement ok
> > set datafusion.sql_parser.dialect = 'Postgres';
> > 
> > statement ok
> > create table t (a float) as values (1), (2), (3);
> > 
> > query TT
> > explain select min(a) filter (where a > 1) as x from t;
> > ----
> > logical_plan
> > 01)Projection: MIN(t.a) FILTER (WHERE t.a > Int64(1)) AS x
> > 02)--Aggregate: groupBy=[[]], aggr=[[MIN(t.a) FILTER (WHERE t.a > Float32(1)) AS MIN(t.a) FILTER (WHERE t.a > Int64(1))]]
> > 03)----TableScan: t projection=[a]
> > physical_plan
> > 01)ProjectionExec: expr=[MIN(t.a) FILTER (WHERE t.a > Int64(1))@0 as x]
> > 02)--AggregateExec: mode=Single, gby=[], aggr=[MIN(t.a) FILTER (WHERE t.a > Int64(1))]
> > 03)----MemoryExec: partitions=1, partition_sizes=[1]
> > 
> > statement ok
> > drop table t;
> > ```
> 
> This test is for the original issue #10878

I guess the test you write only test if the value is correct or not, didn't test if the name is expected

**Comment by Lordworms** [comment]
An unrelated issue with CI/CD

**Review by jayzhan211 — APPROVED** [review]

**Comment by jayzhan211** [comment]
Thanks @Lordworms
