### PR TITLE
fix(11397): surface proper errors in ParquetSink

### LINKED ISSUE #11397: Improve error messages for parallel parquet writer "Unable to send array to writer!"
@devinjdangelo noted on https://github.com/apache/datafusion/pull/11345 that if an error happens deep in the parallel parquet writer it often is not returned to the user and instead we get a generic message `"Unable to send array to writer!"`

              I think we need to update several map_err statements to propagate inner error messages rather than ignore them. E.g. 

https://github.com/apache/datafusion/blob/b96186fdef1ff410663ec8fce41186c018f8e09a/datafusion/core/src/datasource/file_format/parquet.rs#L880-L884

change to something like

```rust
            col_array_channels[next_channel]
                .send(c)
                .await
                .map_err(|e| internal_datafusion_err!("Unable to send array to writer due to error {e}"))
```

_Originally posted by @devinjdangelo in https://github.com/apache/datafusion/pull/11345#discussion_r1672594976_

### PR DESCRIPTION
**Pull request by wiedld**
## Which issue does this PR close?

Closes #11397 

## Rationale for this change

During the parallel writes in ParquetSink, we spawn a series of parallel tasks and then message pass the outcome from one task to the next. In abstraction:
read_batches => channel => `Vec<col_write_tasks>` => channel => `Vec<serialize_rowgroup_tasks>`

When we encounter an error in one of the `Vec<x_tasks>` we are first surfacing an error on the channel.send() rather than on the task join.

## What changes are included in this PR?

Don't surface the errors on the channel send.
This results in the proper error returned, as can be seen on the updated test.

## Are these changes tested?

Yes.

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/core/src/datasource/file_format/parquet.rs [hunk 1]
```diff
@@ -893,12 +893,9 @@ async fn send_arrays_to_col_writers(
...
         for c in compute_leaves(field, array)? {
-            col_array_channels[next_channel]
-                .send(c)
-                .await
-                .map_err(|_| {
-                    DataFusionError::Internal("Unable to send array to writer!".into())
-                })?;
+            // Do not surface error from closed channel.
+            let _ = col_array_channels[next_channel].send(c).await;
+
```
Comment (wiedld) [inline datafusion/core/src/datasource/file_format/parquet.rs:898]: The tradeoff is that we don't error early and extra messages may attempt to be passed.

Comment (alamb) [reply datafusion/core/src/datasource/file_format/parquet.rs:898]: I agree if we just ignore the error here I think this code will continue to furiously encode data only to throw it away. If it hits an error I think it should return early 

In general, I don't there is any useful error message to be made if the channel errors on write. It happens when the other end of the channel has "hung up" (aka there is no receiver that will ever receive the message)

SO in other words, I think this function needs to stop and return control if encounters an error sending.  

Something like 

```rust
            // Do not surface error from closed channel (means something 
            // else hit an error, and the plan is shutting down).
            if let Err(_) = col_array_channels[next_channel].send(c).await {
                return Ok(());
            }
```

**Review by alamb — COMMENTED** [review]
Nice! I think we need to return early here rather than ignoring the error

BTW I tried returning early locally and the test still passes

**Comment by comphead** [comment]
I agree with @alamb early return is way better than ignoring error.
Ignoring error leads to unpredictable behavior

**Review by alamb — APPROVED** [review]
Looks good to me -- thanks @wiedld
