### PR TITLE
propagate error instead of panicking on out of bounds in physical-expr/src/analysis.rs 

### LINKED ISSUE #10536: `analysis.rs` bounds check panic
### Describe the bug

Me again..

I'm getting a panic from

https://github.com/apache/datafusion/blob/cafbc9ddceb5af8c6408d0c8bbfed7568f655ddb/datafusion/physical-expr/src/analysis.rs#L95

I'm not exactly sure yet what's causing it, I'll give more details when I get them.

I must say, I'm bit surprised there's code that's so likely to panic in a situation where:
* returning an error is easy
* there's not guarantee from nearby code that `index` should be in bounds in all common scenarios.

backtrace is:

```
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: datafusion_physical_expr::analysis::ExprBoundaries::try_from_column
   4: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   5: datafusion_physical_expr::analysis::AnalysisContext::try_from_statistics
   6: datafusion_physical_plan::filter::FilterExec::statistics_helper
   7: datafusion_physical_plan::filter::FilterExec::try_new
   8: datafusion::physical_planner::DefaultPhysicalPlanner::map_logical_node_to_physical::{{closure}}
   9: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
  10: <S as futures_core::stream::TryStream>::try_poll_next
  11: <futures_util::stream::try_stream::try_collect::TryCollect<St,C> as core::future::future::Future>::poll
  12: datafusion::physical_planner::DefaultPhysicalPlanner::create_initial_plan::{{closure}}
  13: <datafusion::physical_planner::DefaultPhysicalPlanner as datafusion::physical_planner::PhysicalPlanner>::create_physical_plan::{{closure}}
  14: <datafusion::execution::context::DefaultQueryPlanner as datafusion::execution::context::QueryPlanner>::create_physical_plan::{{closure}}
  15: datafusion::dataframe::DataFrame::create_physical_plan::{{closure}}
  16: datafusion::dataframe::DataFrame::collect::{{closure}}
```

### To Reproduce

no public code right now, but this is somewhat related to my work on #10400, although is specialised enough that my code wouldn't be solution to that.

### Expected behavior

Either my stats are invalid in which case there should be an error, or my stats are okay and it should pass

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LorrensP-2158466**
## Which issue does this PR close?

Closes #10536. 

## Rationale for this change
In https://github.com/apache/datafusion/blob/cafbc9ddceb5af8c6408d0c8bbfed7568f655ddb/datafusion/physical-expr/src/analysis.rs#L95
The function panics when `col_index` is out of bounds when returning an internal error with extra context is much more convenient.

## What changes are included in this PR?

Propagate the error as en `DataFusionError::Internal.`

## Are there any user-facing changes?
Users may need to handle that error case

### CODE REVIEW

File: datafusion/physical-expr/src/analysis.rs [hunk 1]
```diff
@@ -92,7 +94,12 @@ impl ExprBoundaries {
         col_stats: &ColumnStatistics,
         col_index: usize,
     ) -> Result<Self> {
-        let field = &schema.fields()[col_index];
+        let field = schema.fields()
+            .get(col_index)
+            .ok_or_else(|| DataFusionError::Internal(
+                format!("Could not create `ExprBoundaries`: in `try_from_column` `col_index` has gone out of bounds with a value of {col_index}, the schema has {} columns while.", schema.fields.len())
```
Comment (jonahgao) [inline datafusion/physical-expr/src/analysis.rs:100]: Using `internal_datafusion_err` could simplify it.
```rust
 let field = schema.fields().get(col_index).ok_or_else(|| {
            internal_datafusion_err!(
                "Could not create `ExprBoundaries`: in `try_from_column` `col_index` 
                has gone out of bounds with a value of {col_index}, the schema has {} columns while.",
                schema.fields.len()
            )
        })?;
```

**Review by jonahgao — APPROVED** [review]
Looks good to me! Thanks @LorrensP-2158466
