### PR TITLE
Fix shuffle function to report nullability correctly

### LINKED ISSUE #19145: `shuffle` should report nullability correctly
### Describe the bug

the UDF uses the default `is_nullable` which is always true which is not the case

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by harshitsaini17**
# fix: shuffle should report nullability correctly

- Replace return_type with return_field_from_args to preserve input nullability
- Add test to verify nullability is correctly reported
- Addresses issue #19145

## Which issue does this PR close?

Closes #19145

## Rationale for this change

The `shuffle` UDF was using the default `is_nullable` implementation which always returns `true`, regardless of the input array's nullability. This causes:
1. Incorrect schema inference - non-nullable inputs are incorrectly marked as nullable
2. Missed optimization opportunities - the query optimizer cannot apply certain optimizations when nullability information is incorrect
3. Potential runtime errors - incorrect metadata can lead to unexpected behavior in downstream operations

The shuffle function simply reorders elements within an array without changing the array's structure or nullability, so the output should have the same nullability as the input.

## What changes are included in this PR?

1. **Implemented `return_field_from_args`**: Returns the input field directly, preserving both data type and nullability
2. **Updated `return_type`**: Now returns an error directing users to use `return_field_from_args` instead (following DataFusion best practices)
3. **Added comprehensive tests**: Verifies that both nullable and non-nullable inputs are handled correctly

## Are these changes tested?

Yes, this PR includes a new test `test_shuffle_nullability` that verifies:
- Non-nullable array input produces non-nullable output
- Nullable array input produces nullable output
- Data types are preserved correctly in both cases

Test results:

### CODE REVIEW

File: datafusion/spark/src/function/array/shuffle.rs [hunk 1]
```diff
@@ -263,3 +268,53 @@ fn fixed_size_array_shuffle(
...
+        let non_nullable_field = Arc::new(Field::new(
+            "arr",
+            List(Arc::new(Field::new("item", DataType::Int32, true))),
+            false, // not nullable
+        ));
+
+        let result = shuffle
+            .return_field_from_args(ReturnFieldArgs {
+                arg_fields: &[non_nullable_field.clone()],
+                scalar_arguments: &[],
```
Comment (rluvaton) [inline datafusion/spark/src/function/array/shuffle.rs]: there should be the same number of `scalar_arguments` and `arg_fields`, if something is not scalar than None is used.

```suggestion
                arg_fields: &[non_nullable_field.clone()],
                scalar_arguments: &[None],
```

File: datafusion/spark/src/function/array/shuffle.rs [hunk 2]
```diff
@@ -263,3 +268,53 @@ fn fixed_size_array_shuffle(
...
+        let nullable_field = Arc::new(Field::new(
+            "arr",
+            List(Arc::new(Field::new("item", DataType::Int32, true))),
+            true, // nullable
+        ));
+
+        let result = shuffle
+            .return_field_from_args(ReturnFieldArgs {
+                arg_fields: &[nullable_field.clone()],
+                scalar_arguments: &[],
```
Comment (rluvaton) [inline datafusion/spark/src/function/array/shuffle.rs]:
```suggestion
                scalar_arguments: &[None],
```

File: datafusion/spark/src/function/array/shuffle.rs [hunk 3]
```diff
@@ -263,3 +268,53 @@ fn fixed_size_array_shuffle(
...
+            })
+            .unwrap();
+
+        // The result should be nullable (same as input)
+        assert!(result.is_nullable());
+        assert_eq!(result.data_type(), nullable_field.data_type());
+    }
+}
+
+
```
[the remark this answers is not in the document]
Comment (harshitsaini17) [reply datafusion/spark/src/function/array/shuffle.rs]: addressed

File: datafusion/spark/src/function/array/shuffle.rs (hunk 1 above)
Comment (harshitsaini17) [reply datafusion/spark/src/function/array/shuffle.rs]: Implimented

File: datafusion/spark/src/function/array/shuffle.rs (hunk 2 above)
Comment (harshitsaini17) [reply datafusion/spark/src/function/array/shuffle.rs]: Implimented
