### PR TITLE
fix: respect DataFrameWriteOptions::with_single_file_output for paths without extensions

### LINKED ISSUE #13323: Regression: `DataFrameWriteOptions::with_single_file_output` produces a directory
### Describe the bug

Consider a snippet like this:
```rust
df.write_parquet(
  "dir/data",
  DataFrameWriteOptions::new().with_single_file_output(true),
  None
).await
```
Before v43 this would write a single file called `data`, but in v43 this is creating `data` as a directory with a randomly named file(s) in it.

This seems to be related to #13079 (cc @dhegberg) that added an extension-based heuristic.

I see this as a regression, as single file output is requested explicitly, and I don't want a heuristics to be applied.

We are using Parquet files with a content-addressable file system and our files don't have extensions.

### To Reproduce

See above

### Expected behavior

Considering the introduction of the extension-based heuristic I would suggest the following behavior:
- `with_single_file_output` is not called (`single_file_output == None`) - apply the heuristic
- `with_single_file_output(true)` - produce a single file at the exact path specified
- `with_single_file_output(false)` - create directory under specified path if doesn't exist and write one or many files

### Additional context

-

### PR DESCRIPTION
**Pull request by kumarUjjawal**
## Which issue does this PR close?

- Closes #13323.

## Rationale for this change

When using `DataFrameWriteOptions::with_single_file_output(true)`, the setting was being ignored if the output path didn't have a file extension. For example:

```rust
df.write_parquet("/path/to/output", 
    DataFrameWriteOptions::new().with_single_file_output(true), 
    None).await?;
```
Would create a directory /path/to/output/ with files inside instead of a single file at /path/to/output.

This happened because the demuxer used a heuristic based solely on file extension, ignoring the explicit user setting.

## What changes are included in this PR?

- New FileOutputMode enum:  Uses explicit modes (Automatic, SingleFile, Directory) in FileSinkConfig for clearer output path handling.
- The demuxer now uses the user's explicit setting instead of always relying on extension-based heuristics.

## Are these changes tested?

- New unit test test_single_file_output_without_extension tests the fixed behavior
- All sqllogictest pass

## Are there any user-facing changes?

Breaking for direct FileSinkConfig construction: The struct now requires file_output_mode: FileOutputMode field. Use FileOutputMode::Automatic to preserve existing behavior.

### CODE REVIEW

File: datafusion/proto/src/physical_plan/from_proto.rs [hunk 1]
```diff
@@ -737,6 +737,8 @@ impl TryFrom<&protobuf::FileSinkConfig> for FileSinkConfig {
             insert_op,
             keep_partition_by_columns: conf.keep_partition_by_columns,
             file_extension: conf.file_extension.clone(),
+            // For deserialized plans, use extension heuristic (backward compatible)
```
Comment (martin-g) [inline datafusion/proto/src/physical_plan/from_proto.rs]: For how long this backward compatible approach will be used ? At some point it should start using the new config property.

IMO the proper way would be to add a new optional field to [the Protobuf format](https://github.com/kumarUjjawal/datafusion/blob/ab870580248d8d6ab885f9aa56296b4ec6682f50/datafusion/proto/proto/datafusion.proto#L773), then try to read it and use `None` only if it is missing, but if it is not missing then use its value.

Comment (kumarUjjawal) [reply datafusion/proto/src/physical_plan/from_proto.rs]: Thanks for the feedback. You were right, I made some changes based on the input. Let me know if this looks better.

Comment (martin-g) [reply datafusion/proto/src/physical_plan/from_proto.rs]: Lovely!

File: datafusion-examples/examples/data_io/parquet_encrypted.rs [hunk 2]
```diff
@@ -55,7 +55,7 @@ pub async fn parquet_encrypted() -> datafusion::common::Result<()> {
 
     // Create a temporary file location for the encrypted parquet file
     let tmp_source = TempDir::new()?;
-    let tempfile = tmp_source.path().join("cars_encrypted");
+    let tempfile = tmp_source.path().join("cars_encrypted.parquet");
```
Comment (alamb) [inline datafusion-examples/examples/data_io/parquet_encrypted.rs:58]: does it need to be called .parquet even though the dataframe explicitly says `write_parquet`? Or is this just to clean up the code?

File: datafusion/core/src/dataframe/mod.rs [hunk 3]
```diff
@@ -2048,11 +2048,17 @@ impl DataFrame {
                 .build()?
         };
 
+        // Build copy options, including single_file_output if explicitly set
+        let mut copy_options: HashMap<String, String> = HashMap::new();
```
Comment (alamb) [inline datafusion/core/src/dataframe/mod.rs]: since this seems to be a common piece of functionality, what do you think about creating a common function that takes a `DataFrameWriteOptions` and returns a `CopyOptions`?

**Comment by alamb** [comment]
Thank you @martin-g , as always, for the review

File: datafusion-examples/examples/data_io/parquet_encrypted.rs (hunk 2 above)
Comment (martin-g) [reply datafusion-examples/examples/data_io/parquet_encrypted.rs:58]: If there is no file extension and there is no configuration (`Some(true)`) then the heuristics decide that this is a folder and creates a Parquet partition file.
If there is no config and the path has file extension then it writes all the content in this file (no partitions)

**Comment by alamb** [comment]
I took the liberty of adding a small note to the upgrade guide too

File: datafusion/datasource/src/file_sink_config.rs [hunk 4]
```diff
@@ -112,6 +112,11 @@ pub struct FileSinkConfig {
     pub keep_partition_by_columns: bool,
     /// File extension without a dot(.)
     pub file_extension: String,
+    /// Override for single file output behavior.
+    /// - `None`: use extension heuristic (path with extension = single file)
+    /// - `Some(true)`: force single file output at exact path
+    /// - `Some(false)`: force directory output with generated filenames
+    pub single_file_output: Option<bool>,
```
Comment (Jefffrey) [inline datafusion/datasource/src/file_sink_config.rs]: I think it would be better to make this an enum, something like

```rust
enum FileOutputMode {
    Automatic,
    SingleFile,
    Directory,
}
```

It makes it clearer at a glance vs needing to check the comments to know what `None`, `Some(true)` and `Some(false)` mean

File: datafusion/core/src/dataframe/mod.rs (hunk 3 above)
Comment (kumarUjjawal) [reply datafusion/core/src/dataframe/mod.rs]: Thank you. I will take a lool at that and see how it shapes.

File: datafusion/datasource/src/file_sink_config.rs (hunk 4 above)
Comment (kumarUjjawal) [reply datafusion/datasource/src/file_sink_config.rs]: Great! Thanks @Jefffrey

File: datafusion-examples/examples/data_io/parquet_encrypted.rs (hunk 2 above)
Comment (Jefffrey) [reply datafusion-examples/examples/data_io/parquet_encrypted.rs:58]: Actually why is this change needed for the example? Is it fixing some behaviour made by this change or just clarifying the example?

File: datafusion/core/src/dataframe/mod.rs [hunk 5]
```diff
@@ -125,6 +125,14 @@ impl DataFrameWriteOptions {
         self.sort_by = sort_by;
         self
     }
+
+    fn copy_to_options(&self) -> HashMap<String, String> {
```
Comment (Jefffrey) [inline datafusion/core/src/dataframe/mod.rs]: This is a bit confusingly named for what it does

File: datafusion/core/src/dataframe/parquet.rs [hunk 6]
```diff
@@ -324,4 +326,52 @@ mod tests {
 
         Ok(())
     }
+
+    /// Test that single_file_output works for paths WITHOUT file extensions.
+    /// This verifies the fix for the regression where extension heuristics
+    /// ignored the explicit with_single_file_output(true) setting.
+    #[tokio::test]
+    async fn test_single_file_output_without_extension() -> Result<()> {
```
Comment (Jefffrey) [inline datafusion/core/src/dataframe/parquet.rs]: Do we have tests for all the modes? automatic, single, directory

File: datafusion/core/src/physical_planner.rs [hunk 7]
```diff
@@ -549,8 +549,30 @@ impl DefaultPhysicalPlanner {
                     }
                 };
 
+                // Parse single_file_output option if explicitly set
+                let file_output_mode = match source_option_tuples
```
Comment (Jefffrey) [inline datafusion/core/src/physical_planner.rs:553]: I wonder if it would be better to push this enum into `single_file_output` itself as well instead of having this parse from an `Option<bool>` logic 🤔

File: datafusion/core/src/physical_planner.rs [hunk 8]
```diff
@@ -549,8 +549,30 @@ impl DefaultPhysicalPlanner {
...
+                    Some("false") => FileOutputMode::Directory,
+                    Some(value) => {
+                        return Err(DataFusionError::Configuration(format!(
+                            "provided value for 'single_file_output' was not recognized: \"{value}\""
+                        )));
+                    }
+                };
+
+                // Filter out sink-related options that are not format options
+                let format_options: HashMap<String, String> = source_option_tuples
```
Comment (Jefffrey) [inline datafusion/core/src/physical_planner.rs:568]: What's the need for filtering the option here?

File: datafusion/proto/proto/datafusion.proto [hunk 9]
```diff
@@ -771,6 +771,11 @@ message FileSinkConfig {
   bool keep_partition_by_columns = 9;
   InsertOp insert_op = 10;
   string file_extension = 11;
+  // Optional override for single file output behavior.
+  // When not set, uses extension heuristic (path with extension = single file).
+  // When set to true, forces single file output at exact path.
+  // When set to false, forces directory output with generated filenames.
+  optional bool single_file_output = 12;
```
Comment (Jefffrey) [inline datafusion/proto/proto/datafusion.proto]: Might be better to represent this as an actual enum to more align with the source 🤔

File: datafusion/proto/tests/cases/roundtrip_physical_plan.rs [hunk 10]
```diff
@@ -1475,6 +1475,7 @@ fn roundtrip_json_sink() -> Result<()> {
         insert_op: InsertOp::Overwrite,
         keep_partition_by_columns: true,
         file_extension: "json".into(),
+        file_output_mode: FileOutputMode::Automatic,
```
Comment (Jefffrey) [inline datafusion/proto/tests/cases/roundtrip_physical_plan.rs]: Can we use different modes for each of the tests for coverage

File: docs/source/library-user-guide/upgrading.md [hunk 11]
```diff
@@ -21,7 +21,37 @@
...
+**Note:** DataFusion `53.0.0` has not been released yet. The information provided
+*in this section pertains to features and changes that have already been merged
+*to the main branch and are awaiting release in this version. See [#19692] for
+\*more details.
+
+[#19692]: https://github.com/apache/datafusion/issues/19692
+
+### `FileSinkConfig` adds `single_file_output`
+
+`FileSinkConfig` now includes a `single_file_output: Option<bool>` field to override the
```
Comment (Jefffrey) [inline docs/source/library-user-guide/upgrading.md]: Reminder to update this

File: datafusion-examples/examples/data_io/parquet_encrypted.rs (hunk 2 above)
Comment (kumarUjjawal) [reply datafusion-examples/examples/data_io/parquet_encrypted.rs:58]: Before this PR, `with_single_file_output(true)` was silently ignored for paths without extensions it would create a directory `cars_encrypted/` with parquet files inside. The `read_parquet()` call then found these files in the directory. After this PR, `with_single_file_output(true)` is correctly respected, creating a single file at the exact path `cars_encrypted` . However, `read_parquet()` with default options expects a `.parquet` extension and fails validation. Adding .parquet to the filename fixes this and makes the example explicit about the expected file format.

File: datafusion/core/src/physical_planner.rs (hunk 8 above)
Comment (kumarUjjawal) [reply datafusion/core/src/physical_planner.rs:568]: The `single_file_output` option is a sink-level configuration that controls file output behavior, not a format-specific option . The `file_type_to_format().create(session_state, &format_options)` call validates options against the format's config schema and would fail with "unrecognized option" if we pass `single_file_output`. So we extract it first for `FileSinkConfig`, then filter it out before passing the remaining options to the format factory.

File: datafusion/core/src/physical_planner.rs (hunk 7 above)
Comment (kumarUjjawal) [reply datafusion/core/src/physical_planner.rs:553]: I kept `with_single_file_output(bool)` in DataFrameWriteOptions for backward compatibility, it's the existing public API. Internally, I changed the field to Option<bool> so we can distinguish "not set" from "explicitly set to false". The conversion to FileOutputMode happens in the physical planner. Adding `with_file_output_mode(FileOutputMode)` would expand the API surface; are you okay with that?

File: docs/source/library-user-guide/upgrading.md [hunk 12]
```diff
@@ -21,7 +21,45 @@
 
 ## DataFusion `53.0.0`
 
-**Note:** DataFusion `53.0.0` has not been released yet. The information provided in this section pertains to features and changes that have already been merged to the main branch and are awaiting release in this version.
+**Note:** DataFusion `53.0.0` has not been released yet. The information provided
+*in this section pertains to features and changes that have already been merged
+*to the main branch and are awaiting release in this version. See [#19692] for
+\*more details.
+
+[#19692]: https://github.com/apache/datafusion/issues/19692
```
Comment (alamb) [inline docs/source/library-user-guide/upgrading.md:29]: 👍

**Comment by alamb** [comment]
Thanks again @kumarUjjawal and @Jefffrey and @martin-g
