### PR TITLE
fix: `optimize_projections` failure after mark joins created by `EXISTS OR EXISTS`

### LINKED ISSUE #20083: optimize_projections fails after mark-join involved
### Describe the bug

optimize failed if a plan with filter: ` Filter: EXISTS (<subquery>) OR EXISTS (<subquery>)`

### To Reproduce

```
use datafusion::logical_expr::expr::Exists;
use datafusion::logical_expr::utils::disjunction;
use datafusion::logical_expr::{LogicalPlan, LogicalPlanBuilder, TableSource};
use datafusion::optimizer::{Optimizer, OptimizerContext, OptimizerRule};
use datafusion::prelude::{Expr, lit};
use datafusion::{
    arrow::datatypes::{DataType, Field, Schema},
    datasource::{DefaultTableSource, MemTable},
};
use datafusion_common::{Column, JoinType};
use std::sync::Arc;

async fn get_table() -> datafusion_common::Result<Arc<dyn TableSource>> {
    let schema = Arc::new(Schema::new(vec![
        Field::new("uid", DataType::Int32, false),
        Field::new("val", DataType::Int32, false),
    ]));
    let provider = MemTable::try_new(schema.clone(), vec![vec![]])?;
    let table = Arc::new(DefaultTableSource::new(Arc::new(provider)));

    Ok(table)
}

async fn build_exists_expr(table_name: &str) -> datafusion_common::Result<Expr> {
    let table = get_table().await?;

    let scan = LogicalPlanBuilder::scan(table_name, table.clone(), None)?
        .project(vec![lit(1)])?
        .build()?;

    let subquery = datafusion::logical_expr::Subquery {
        subquery: Arc::new(scan),
        outer_ref_columns: vec![],
        spans: Default::default(),
    };

    Ok(Expr::Exists(Exists::new(subquery, false)))
}

async fn build_plan() -> datafusion_common::Result<LogicalPlan> {
    let exists_a = build_exists_expr("a").await?;
    let exists_b = build_exists_expr("b").await?;

    let filter = disjunction(vec![exists_a, exists_b]);

    let mut scan_a =
        LogicalPlanBuilder::scan("a", get_table().await?, None)?.filter(filter.unwrap())?;
    
    // this test case will pass if un-comment this line
    // scan_a = scan_a.project(vec![Expr::Column(Column::from_name("uid"))])?;
    
    let scan_b = LogicalPlanBuilder::scan("b", get_table().await?, None)?.build()?;

    let plan = scan_a
        .join(
            scan_b,
            JoinType::Left,
            (vec!["uid".to_string()], vec!["uid".to_string()]),
            None,
        )?
        .build()?;

    let optimizer = Optimizer::new();
    let config = OptimizerContext::new().with_max_passes(16);
    let ret = optimizer.optimize(plan, &config, observer);
    if ret.is_err() {
        println!("ret = {:#?}", ret);
    }

    fn observer(plan: &LogicalPlan, rule: &dyn OptimizerRule) {
        println!(
            "\nAfter applying rule '{}':\n{}",
            rule.name(),
            plan.display_indent()
        )
    }

    ret
}


#[tokio::test]
async fn test_build_plan() {
    let ret = build_plan().await;
    assert!(ret.is_ok());
}
```

### Expected behavior

this test case should pass

### Actual Behavior
```
ret = Err(
    Context(
        "Optimizer rule 'optimize_projections' failed",
        Context(
            "Check optimizer-specific invariants after optimizer rule: optimize_projections",
            Internal(
                "Failed due to a difference in schemas: original schema: DFSchema { inner: Schema { fields: [Field { name: \"uid\", data_type: Int32 }, Field { name: \"val\", data_type: Int32 }, Field { name: \"uid\", data_type: Int32, nullable: true }, Field { name: \"val\", data_type: Int32, nullable: true }], metadata: {} }, field_qualifiers: [Some(Bare { table: \"a\" }), Some(Bare { table: \"a\" }), Some(Bare { table: \"b\" }), Some(Bare { table: \"b\" })], functional_dependencies: FunctionalDependencies { deps: [] } }, new schema: DFSchema { inner: Schema { fields: [Field { name: \"uid\", data_type: Int32 }, Field { name: \"val\", data_type: Int32 }, Field { name: \"mark\", data_type: Boolean }, Field { name: \"mark\", data_type: Boolean }, Field { name: \"uid\", data_type: Int32, nullable: true }], metadata: {} }, field_qualifiers: [Some(Bare { table: \"a\" }), Some(Bare { table: \"a\" }), Some(Bare { table: \"__correlated_sq_1\" }), Some(Bare { table: \"__correlated_sq_2\" }), Some(Bare { table: \"b\" })], functional_dependencies: FunctionalDependencies { deps: [] } }",
            ),
        ),
    ),
)

thread 'test_build_plan' (2129566) panicked at src/main.rs:86:5:
assertion failed: ret.is_ok()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_build_plan

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s


```

### Additional context

This case will not fail if add the projection to `scan_a`

_No response_

### PR DESCRIPTION
**Pull request by buraksenn**
## Which issue does this PR close?

- Closes #20083.

## Rationale for this change

Issue has details but main problem is mark columns from LeftMark joins leak into parent join schemas, causing `optimize_projections` optimizer to fail.

## What changes are included in this PR?
Add a projection after embedded subquery decorrelation to strip mark columns, following the same pattern as `scalar_subquery_to_join`. I've seen this projection is merged in the final plan.

## Are these changes tested?
Added test case for reported failure

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/optimizer/src/optimize_projections/mod.rs
Comment (neilconway) [inline datafusion/optimizer/src/optimize_projections/mod.rs:749]: Update this for new `right_len` parameter.

File: datafusion/optimizer/src/optimize_projections/mod.rs [hunk 1]
```diff
@@ -2311,6 +2320,56 @@ mod tests {
...
+            .filter(disjunction(vec![exists_a, exists_b]).unwrap())?
+            .join(table_b, JoinType::Left, (vec!["a"], vec!["a"]), None)?
+            .build()?;
+
+        let optimizer = Optimizer::new();
+        let config = OptimizerContext::new();
+        let result = optimizer.optimize(plan, &config, observe);
+        assert!(
+            result.is_ok(),
+            "Full optimizer should not fail with schema mismatch: {:?}",
```
Comment (neilconway) [inline datafusion/optimizer/src/optimize_projections/mod.rs]: Seems a bit fragile to assume the assert fails with a schema mismatch, if it fails.

File: datafusion/optimizer/src/optimize_projections/mod.rs [hunk 2]
```diff
@@ -2311,6 +2320,56 @@ mod tests {
...
+            result.err()
+        );
+        let optimized = result.unwrap();
+        let plan_str = format!("{optimized}");
+        // Verify no double projection — the projection we add to strip mark
+        // columns should be merged by optimize_projections, not left stacked.
+        assert!(
+            !plan_str.contains("Projection: a.a, a.b, a.c\n            Projection:"),
```
Comment (neilconway) [inline datafusion/optimizer/src/optimize_projections/mod.rs]: Testing for an expected plan via string containment seems a bit unfortunate. Can't we check for the plan shape we expect, e.g., via `assert_optimized_plan_equal!`?

File: datafusion/optimizer/src/optimize_projections/mod.rs [hunk 3]
```diff
@@ -757,21 +758,29 @@ fn outer_columns_helper_multi<'a, 'b>(
...
-        | JoinType::Full
-        | JoinType::LeftMark
-        | JoinType::RightMark => {
+        JoinType::Inner | JoinType::Left | JoinType::Right | JoinType::Full => {
             // Decrease right side indices by `left_len` so that they point to valid
             // positions within the right child:
             indices.split_off(left_len)
         }
+        JoinType::LeftMark => {
+            // LeftMark output: [left_cols(0..left_len), mark(left_len)]
```
Comment (neilconway) [inline datafusion/optimizer/src/optimize_projections/mod.rs]: Nit: I think writing

```
// LeftMark output: [left_cols(0..left_len), mark]
```

Would be a bit clearer.

**Review by neilconway — APPROVED** [review]
Overall lgtm!

File: datafusion/optimizer/src/optimize_projections/mod.rs
Comment (buraksenn) [reply datafusion/optimizer/src/optimize_projections/mod.rs:749]: Thanks I've missed this

File: datafusion/optimizer/src/optimize_projections/mod.rs (hunk 1 above)
Comment (buraksenn) [reply datafusion/optimizer/src/optimize_projections/mod.rs]: I've added a test for just make sure full optimizer runs successfully as a regression test instead of this. Moreover, I've modified the other test to use `assert_optimized_plan_equal` and check final plan.

File: datafusion/optimizer/src/optimize_projections/mod.rs (hunk 2 above)
Comment (buraksenn) [reply datafusion/optimizer/src/optimize_projections/mod.rs]: > I've added a test for just make sure full optimizer runs successfully as a regression test instead of this. Moreover, I've modified the other test to use `assert_optimized_plan_equal` and check final plan.

replied above. Thanks it makes sense

**Comment by neilconway** [comment]
@alamb This PR looks reasonable to me.

**Review by alamb — APPROVED** [review]
Looks good to me too - thanks @buraksenn and @neilconway

**Review by berkaysynnada — APPROVED** [review]
I've finally had a chance to take a look at this. LGTM, it's a clear fix
