### PR TITLE
fix: increase ROUND decimal precision to prevent overflow truncation

### LINKED ISSUE #19921: `round` decimal incorrect result
### Describe the bug

`SELECT ROUND('999.9'::DECIMAL(4,1))` produces `100.0` which is incorrect.

### To Reproduce

Launch a `datafusion-cli`, execute:

```shell
./datafusion-cli                                                                          
DataFusion CLI v52.0.0
> SELECT ROUND('999.9'::DECIMAL(4,1));
+----------------------+
| round(Utf8("999.9")) |
+----------------------+
| 100.0                |
+----------------------+
1 row(s) fetched. 
Elapsed 0.020 seconds.
```

### Expected behavior

Expect `1000`, like in the postgresql:

```shell
postgres=# SELECT ROUND('999.9'::DECIMAL(4,1));
 round
-------
  1000
(1 row)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kumarUjjawal**
## Which issue does this PR close?

- Closes #19921.

## Rationale for this change

`SELECT ROUND('999.9'::DECIMAL(4,1))` incorrectly returned `100.0` instead of `1000`.

When rounding a decimal value causes a carry-over that increases the number of digits (e.g., 999.9 → 1000.0), the result overflows the original precision constraint. The overflow was silently truncated during display, producing incorrect results.

## What changes are included in this PR?

  - Fixes ROUND on DECIMAL so carry-over doesn’t silently truncate/produce wrong results.
  - When decimal_places is a constant (including omitted/NULL), ROUND now reduces the output scale to min(input_scale, max(decimal_places, 0)) (Spark/DuckDB-style), reclaiming
    precision for the integer part.
  - When decimal_places is not a constant (e.g. a column/array), ROUND keeps the original scale and may increase precision by 1 (capped); if precision is already max and the rounded
    value can’t fit, it returns an overflow error instead of a wrong value.
  - Adds/updates sqllogictests for these behaviors and edge cases.

## Are these changes tested?

- Added new sqllogictest case for the specific bug scenario
- Updated 2 existing tests with new expected precision values
- All existing tests pass

## Are there any user-facing changes?

| Aspect | Before | After |
  | --- | --- | --- |
  | ROUND('999.9'::DECIMAL(4,1)) | 100.0 (wrong) | 1000 (correct) |
  | Return type (default/literal dp) | Decimal128(4, 1) | Decimal128(4, 0) |

  - Return type for DECIMAL inputs can change: with literal dp it generally reduces scale; with non-literal dp it keeps scale and may increase precision by 1.
  - New error case: when precision is already max and dp is non-literal, ROUND may now error on overflow rather than return a truncated/wrong decimal.

### CODE REVIEW

**Comment by kumarUjjawal** [comment]
Other options considered:

1. Increase output precision by 1 (PostgreSQL behavior): The `return_type` should increase precision by 1 to accommodate potential carry-over from rounding. For `DECIMAL(p, s)` with `decimal_places=0`, return `DECIMAL(p+1, s)`.

2. Return error on overflow: Keep same precision but return an error when the rounded value exceeds the precision (current code uses mul_checked but the overflow happens silently in display).

3. Dynamic precision based on scale reduction: When reducing scale (e.g., from 1 to 0), calculate the minimum precision needed.

I chose option 1 as the most user friendly, I would like to hear if there are other suggestion for this fix.

**Comment by Jefffrey** [comment]
> Other options considered:
> 
>     1. Increase output precision by 1 (PostgreSQL behavior): The `return_type` should increase precision by 1 to accommodate potential carry-over from rounding. For `DECIMAL(p, s)` with `decimal_places=0`, return `DECIMAL(p+1, s)`.
> 
>     2. Return error on overflow: Keep same precision but return an error when the rounded value exceeds the precision (current code uses mul_checked but the overflow happens silently in display).
> 
>     3. Dynamic precision based on scale reduction: When reducing scale (e.g., from 1 to 0), calculate the minimum precision needed.
> 
> 
> I chose option 1 as the most user friendly, I would like to hear if there are other suggestion for this fix.

Option 1 sounds good. Option 2 would be too strict, not sure I fully understand what option 3 means here.

One thing to keep in mind is we still need to consider edge case where precision is already maxed out. Would this bug occur again?

**Comment by kumarUjjawal** [comment]
> > Other options considered:
> > ```
> > 1. Increase output precision by 1 (PostgreSQL behavior): The `return_type` should increase precision by 1 to accommodate potential carry-over from rounding. For `DECIMAL(p, s)` with `decimal_places=0`, return `DECIMAL(p+1, s)`.
> > 
> > 2. Return error on overflow: Keep same precision but return an error when the rounded value exceeds the precision (current code uses mul_checked but the overflow happens silently in display).
> > 
> > 3. Dynamic precision based on scale reduction: When reducing scale (e.g., from 1 to 0), calculate the minimum precision needed.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I chose option 1 as the most user friendly, I would like to hear if there are other suggestion for this fix.
> 
> Option 1 sounds good. Option 2 would be too strict, not sure I fully understand what option 3 means here.
> 
> One thing to keep in mind is we still need to consider edge case where precision is already maxed out. Would this bug occur again?

You were right to point that, i did some more test and found out it was overflowing after 38 digits, I handled that as an error.

File: datafusion/functions/src/math/round.rs [hunk 1]
```diff
@@ -377,9 +404,28 @@ fn round_decimal<V: ArrowNativeTypeOp>(
...
-    quotient
-        .mul_checked(factor)
-        .map_err(|_| ArrowError::ComputeError("Overflow while rounding decimal".into()))
+    let result = quotient.mul_checked(factor).map_err(|_| {
+        ArrowError::ComputeError("Overflow while rounding decimal".into())
+    })?;
+
+    // Validate the result fits within the precision
+    // The max value for a given precision is 10^precision - 1
+    let max_value = ten.pow_checked(precision as u32).map_err(|_| {
```
Comment (Jefffrey) [inline datafusion/functions/src/math/round.rs]: Can use these constants instead

- https://docs.rs/arrow/latest/arrow/datatypes/constant.MAX_DECIMAL128_FOR_EACH_PRECISION.html
- https://docs.rs/arrow/latest/arrow/datatypes/constant.MIN_DECIMAL128_FOR_EACH_PRECISION.html

(Same constants exist for each decimal type)

File: datafusion/sqllogictest/test_files/scalar.slt [hunk 2]
```diff
@@ -951,15 +951,29 @@ query TR
...
-Decimal128(10, 2) 12350
+Decimal128(11, 2) 12350
 
 # round decimal256 keeps decimals
 query TR
 select arrow_typeof(round('1234.5678'::decimal(50,4), 2)),
        round('1234.5678'::decimal(50,4), 2);
 ----
-Decimal256(50, 4) 1234.57
+Decimal256(51, 4) 1234.57
```
Comment (martin-g) [inline datafusion/sqllogictest/test_files/scalar.slt]: I was going to ask whether the increase of the precision could be done only when really needed.
And I went checking what the other DBs do:

1) Postgres v18
```
postgres=# SELECT pg_typeof(round(999.9::DECIMAL(4,1))), round(999.9::DECIMAL(4,1));
 pg_typeof | round
-----------+-------
 numeric   |  1000
(1 row)
```
(Not helpful)

2) Apache Spark (v4.0.1)
```
spark-sql (default)> SELECT typeof(round(999.9::DECIMAL(4,1))), round(999.9::DECIMAL(4,1));
decimal(4,0)    1000
Time taken: 0.032 seconds, Fetched 1 row(s)
```
Reduced the scale!

3) DuckDB
```
SELECT typeof(round(999.9::DECIMAL(4,1))), round(999.9::DECIMAL(4,1));
┌────────────────────────────────────────────┬────────────────────────────────────┐
│ typeof(round(CAST(999.9 AS DECIMAL(4,1)))) │ round(CAST(999.9 AS DECIMAL(4,1))) │
│                  varchar                   │            decimal(4,0)            │
├────────────────────────────────────────────┼────────────────────────────────────┤
│ DECIMAL(4,0)                               │                1000                │
└────────────────────────────────────────────┴────────────────────────────────────┘
```
Reduced the scale!

Comment (kumarUjjawal) [reply datafusion/sqllogictest/test_files/scalar.slt]: This is really nice, Thank you.

Comment (kumarUjjawal) [reply datafusion/sqllogictest/test_files/scalar.slt]: Case | Input | Result | Type
-- | -- | -- | --
dp column | 123.4567, dp=1 | 123.5000 | DECIMAL(10,4) 
carry-over | 999.9999, dp=0 | 1000.0000 | DECIMAL(10,4) 
constant dp | 999.9 | 1000 | DECIMAL(4,0) 
scale reduction | 1234.5678, dp=2 | 1234.57 | DECIMAL(50,2) 
negative dp | 12345.67, dp=-2 | 12300 | DECIMAL(7,0) 
dp > scale | 123.4, dp=5 | 123.4 | DECIMAL(4,1) 
negative values | -999.9, dp=0 | -1000 | DECIMAL(4,0)

File: datafusion/functions/src/math/round.rs [hunk 3]
```diff
@@ -117,15 +119,74 @@ impl ScalarUDFImpl for RoundFunc {
...
-    fn return_type(&self, arg_types: &[DataType]) -> Result<DataType> {
-        Ok(match arg_types[0].clone() {
+    fn return_field_from_args(&self, args: ReturnFieldArgs) -> Result<FieldRef> {
+        let input_field = &args.arg_fields[0];
+        let input_type = input_field.data_type();
+
+        // Get decimal_places from scalar_arguments
+        // If dp is not a constant scalar, we must keep the original scale because
+        // we can't determine a single output scale for varying per-row dp values.
+        let (decimal_places, dp_is_scalar): (i32, bool) =
```
Comment (martin-g) [inline datafusion/functions/src/math/round.rs]: Here `decimal_places` is initialized as `i32` but below it is casted to `i8` with `as i8` and this may lead to problems. A validation is needed that it is not bigger than i8::MAX

File: datafusion/functions/src/math/round.rs [hunk 4]
```diff
@@ -117,15 +119,74 @@ impl ScalarUDFImpl for RoundFunc {
...
+                }
+            }
             _ => Float64,
-        })
+        };
+
+        Ok(Arc::new(Field::new(
+            self.name(),
+            return_type,
+            input_field.is_nullable(),
```
Comment (martin-g) [inline datafusion/functions/src/math/round.rs]: This should also take into account the `decimal_places` arg.

Postgres:
```
postgres=# SELECT pg_typeof(round(999.9::DECIMAL(4,1))), round(999.9::DECIMAL(4,1), NULL);
 pg_typeof | round
-----------+-------
 numeric   |
(1 row)
```

Apache Spark:
```
spark-sql (default)> SELECT typeof(round(999.9::DECIMAL(4,1))), round(999.9::DECIMAL(4,1), NULL);
decimal(4,0)    NULL
Time taken: 0.055 seconds, Fetched 1 row(s)
```

DuckDB:
```
D SELECT typeof(round(999.9::DECIMAL(4,1))), round(999.9::DECIMAL(4,1), NULL);
┌────────────────────────────────────────────┬──────────────────────────────────────────┐
│ typeof(round(CAST(999.9 AS DECIMAL(4,1)))) │ round(CAST(999.9 AS DECIMAL(4,1)), NULL) │
│                  varchar                   │                  int32                   │
├────────────────────────────────────────────┼──────────────────────────────────────────┤
│ DECIMAL(4,0)                               │                   NULL                   │
└────────────────────────────────────────────┴──────────────────────────────────────────┘
```

File: datafusion/functions/src/math/round.rs [hunk 5]
```diff
@@ -117,15 +119,74 @@ impl ScalarUDFImpl for RoundFunc {
...
+        let input_type = input_field.data_type();
+
+        // Get decimal_places from scalar_arguments
+        // If dp is not a constant scalar, we must keep the original scale because
+        // we can't determine a single output scale for varying per-row dp values.
+        let (decimal_places, dp_is_scalar): (i32, bool) =
+            if args.scalar_arguments.len() > 1 {
+                match args.scalar_arguments[1] {
+                    Some(ScalarValue::Int32(Some(v))) => (*v, true),
+                    Some(ScalarValue::Int64(Some(v))) => (*v as i32, true),
```
Comment (martin-g) [inline datafusion/functions/src/math/round.rs]: Better use a safe cast and return an Err if the number is bigger than i32::MAX (or even i8::MAX)

File: datafusion/functions/src/math/round.rs [hunk 6]
```diff
@@ -397,12 +501,14 @@ mod test {
         decimal_places: Option<ArrayRef>,
     ) -> Result<ArrayRef, DataFusionError> {
         let number_rows = value.len();
+        let return_type = value.data_type().clone();
```
Comment (martin-g) [inline datafusion/functions/src/math/round.rs:750]: This could be wrong for decimals which scale is reduced.
No need to fix/improve it. Just a comment acknowledging that is enough.

File: datafusion/functions/src/math/round.rs [hunk 7]
```diff
@@ -117,15 +209,135 @@ impl ScalarUDFImpl for RoundFunc {
...
+        let input_type = input_field.data_type();
+
+        // Get decimal_places from scalar_arguments
+        // If dp is not a constant scalar, we must keep the original scale because
+        // we can't determine a single output scale for varying per-row dp values.
+        let (decimal_places, dp_is_scalar) = match args.scalar_arguments.get(1) {
+            None => (0, true),        // No dp argument means default to 0
+            Some(None) => (0, false), // dp is a column
+            Some(Some(ScalarValue::Int32(Some(v)))) => (*v, true),
+            Some(Some(ScalarValue::Int64(Some(v)))) => {
```
Comment (Jefffrey) [inline datafusion/functions/src/math/round.rs]: I don't think we should have i64 handling code since the signature expects only i32 for the 2nd argument

**Comment by kumarUjjawal** [comment]
> I plan to take a look at this again soon; in the meantime could we update the PR body since it seems outdated compared to the recent changes?

I will update it. Thanks!

File: datafusion/functions/src/math/round.rs (hunk 7 above)
Comment (kumarUjjawal) [reply datafusion/functions/src/math/round.rs]: The Int64 handling isn’t “accepting Int64 dp” at runtime; it’s handling how literals are represented during planning.

Comment (Jefffrey) [reply datafusion/functions/src/math/round.rs]: I'm not sure I follow; does that mean `scalar_arguments` types don't have type coercion applied to them?

Comment (kumarUjjawal) [reply datafusion/functions/src/math/round.rs]: Yes, `ReturnFieldArgs.scalar_arguments` are taken directly from the original `Expr::Literal` values, so they can be `ScalarValue::Int64` even though the function signature/coercion will ensure the argument is evaluated as Int32 at runtime.
Type coercion is applied when building the physical expression / evaluating the arguments, but scalar_arguments is just “what literal was written in the query”, not the coerced value. That’s why we handle Int64 there: to (a) treat it as a constant dp for return-type computation and (b) produce a clear out-of-range error for literals that can’t fit in i32.

Comment (Jefffrey) [reply datafusion/functions/src/math/round.rs]: This is certainly interesting, I'll look into it 🤔 

But I think we can still remove the i64 code in `invoke_with_args` at the very least?

Edit: raised

- https://github.com/apache/datafusion/issues/19982

File: datafusion/functions/src/math/round.rs [hunk 8]
```diff
@@ -24,20 +24,112 @@ use arrow::datatypes::DataType::{
...
+fn output_scale_for_decimal(input_scale: i8, decimal_places: i32) -> Result<i8> {
+    let new_scale = i32::from(input_scale).min(decimal_places.max(0));
+    i8::try_from(new_scale).map_err(|_| {
+        datafusion_common::DataFusionError::Internal(format!(
+            "Computed decimal scale {new_scale} is out of range for i8"
+        ))
+    })
+}
+
+fn validate_decimal32_precision(value: i32, precision: u8) -> Result<i32, ArrowError> {
```
Comment (Jefffrey) [inline datafusion/functions/src/math/round.rs]: Use https://docs.rs/arrow/latest/arrow/datatypes/trait.DecimalType.html#tymethod.validate_decimal_precision

File: datafusion/functions/src/math/round.rs [hunk 9]
```diff
@@ -117,15 +209,135 @@ impl ScalarUDFImpl for RoundFunc {
...
-    fn return_type(&self, arg_types: &[DataType]) -> Result<DataType> {
-        Ok(match arg_types[0].clone() {
+    fn return_field_from_args(&self, args: ReturnFieldArgs) -> Result<FieldRef> {
+        let input_field = &args.arg_fields[0];
+        let input_type = input_field.data_type();
+
+        // Get decimal_places from scalar_arguments
+        // If dp is not a constant scalar, we must keep the original scale because
+        // we can't determine a single output scale for varying per-row dp values.
+        let (decimal_places, dp_is_scalar) = match args.scalar_arguments.get(1) {
```
Comment (Jefffrey) [inline datafusion/functions/src/math/round.rs]: Maybe these should be folded into an `Option` if `decimal_places` is only used if `dp_is_scalar` is true

File: datafusion/functions/src/math/round.rs [hunk 10]
```diff
@@ -117,15 +209,135 @@ impl ScalarUDFImpl for RoundFunc {
...
+        // This matches Spark/DuckDB behavior where ROUND adjusts the scale
+        // BUT only if dp is a constant - otherwise keep original scale and add
+        // extra precision to accommodate potential carry-over.
+        let return_type = match input_type {
             Float32 => Float32,
-            dt @ Decimal128(_, _)
-            | dt @ Decimal256(_, _)
-            | dt @ Decimal32(_, _)
-            | dt @ Decimal64(_, _) => dt,
+            Decimal32(precision, scale) => {
```
Comment (Jefffrey) [inline datafusion/functions/src/math/round.rs]: Can deduplicate like so

```rust
fn calculate_new_precision_scale<T: DecimalType>(
    precision: u8,
    scale: i8,
    dp_is_scalar: bool,
    decimal_places: i32,
) -> Result<DataType> {
    if dp_is_scalar {
        let new_scale = output_scale_for_decimal(scale, decimal_places)?;
        let new_precision = if scale == 0
            && decimal_places < 0
            && decimal_places
                .checked_neg()
                .map(|abs| abs <= i32::from(precision))
                .unwrap_or(false)
        {
            precision.saturating_add(1).min(T::MAX_PRECISION)
        } else {
            precision
        };
        Ok(T::TYPE_CONSTRUCTOR(new_precision, new_scale))
    } else {
        let new_precision = precision.saturating_add(1).min(T::MAX_PRECISION);
        Ok(T::TYPE_CONSTRUCTOR(new_precision, scale))
    }
}
```

And use

```rust
            Decimal32(precision, scale) => {
                calculate_new_precision_scale::<Decimal32Type>(
                    *precision,
                    *scale,
                    dp_is_scalar,
                    decimal_places,
                )?
            }
```

File: datafusion/functions/src/math/round.rs [hunk 11]
```diff
@@ -168,28 +386,96 @@ impl ScalarUDFImpl for RoundFunc {
...
                     let scalar =
-                        ScalarValue::Decimal64(Some(rounded), *precision, *scale);
+                        ScalarValue::Decimal64(Some(rounded), out_precision, out_scale);
                     Ok(ColumnarValue::Scalar(scalar))
                 }
-                ScalarValue::Decimal32(Some(v), precision, scale) => {
-                    let rounded = round_decimal(*v, *scale, dp)?;
+                ScalarValue::Decimal32(Some(v), _precision, scale) => {
+                    let (out_precision, out_scale) =
+                        if let Decimal32(p, s) = args.return_type() {
```
Comment (Jefffrey) [inline datafusion/functions/src/math/round.rs]: Might be better to pull this destructuring of return type into the match, which can enable further deduplication across the decimal arms

File: datafusion/functions/src/math/round.rs [hunk 12]
```diff
@@ -25,19 +25,96 @@ use arrow::datatypes::DataType::{
...
 use datafusion_macros::user_doc;
+use std::sync::Arc;
+
+fn output_scale_for_decimal(input_scale: i8, decimal_places: i32) -> Result<i8> {
+    let new_scale = i32::from(input_scale).min(decimal_places.max(0));
+    i8::try_from(new_scale).map_err(|_| {
+        datafusion_common::DataFusionError::Internal(format!(
+            "Computed decimal scale {new_scale} is out of range for i8"
+        ))
+    })
```
Comment (Jefffrey) [inline datafusion/functions/src/math/round.rs]: I feel we could clamp `decimal_places` to the max precision, which is well within an `i8`; that way we can avoid all these error paths, especially because such a large `decimal_places` would return 0 (or some value) instead of erroring

File: datafusion/functions/src/math/round.rs [hunk 13]
```diff
@@ -25,19 +25,96 @@ use arrow::datatypes::DataType::{
...
+    decimal_places: Option<i32>,
+) -> Result<DataType> {
+    if let Some(decimal_places) = decimal_places {
+        let new_scale = output_scale_for_decimal(scale, decimal_places)?;
+        let new_precision = if scale == 0
+            && decimal_places < 0
+            && decimal_places
+                .checked_neg()
+                .map(|abs| abs <= i32::from(precision))
+                .unwrap_or(false)
```
Comment (Jefffrey) [inline datafusion/functions/src/math/round.rs]: This checked negative of `decimal_places` is also something we can avoid if we clamp it earlier on

Also could we add some explanation here for these checks? To me it's not clearly obvious why we check for `scale == 0` and `abs(decimal_places) <= precision`

File: datafusion/functions/src/math/round.rs [hunk 14]
```diff
@@ -159,48 +279,122 @@ impl ScalarUDFImpl for RoundFunc {
...
-                ScalarValue::Decimal128(Some(v), precision, scale) => {
-                    let rounded = round_decimal(*v, *scale, dp)?;
+                (
+                    ScalarValue::Decimal32(Some(v), _precision, scale),
+                    Decimal32(out_precision, out_scale),
+                ) => {
+                    let rounded = round_decimal(*v, *scale, *out_scale, dp)?;
+                    let rounded = if *out_precision == Decimal32Type::MAX_PRECISION
+                        && *scale == 0
+                        && dp < 0
```
Comment (Jefffrey) [inline datafusion/functions/src/math/round.rs:333]: Same here regarding explanation of these checks

File: datafusion/functions/src/math/round.rs [hunk 15]
```diff
@@ -228,29 +422,32 @@ fn round_columnar(
     value: &ColumnarValue,
     decimal_places: &ColumnarValue,
     number_rows: usize,
+    return_type: &DataType,
 ) -> Result<ColumnarValue> {
     let value_array = value.to_array(number_rows)?;
     let both_scalars = matches!(value, ColumnarValue::Scalar(_))
```
Comment (Jefffrey) [inline datafusion/functions/src/math/round.rs:472]: I realized this `both_scalars` check is redundant since we have a fast path above; can be refactored away in a followup PR

File: datafusion/functions/src/math/round.rs [hunk 16]
```diff
@@ -259,13 +456,24 @@ fn round_columnar(
...
+                    let rounded = round_decimal(v, *scale, *new_scale, dp)?;
+                    if *precision == Decimal32Type::MAX_PRECISION
+                        && (decimal_places_is_array || (*scale == 0 && dp < 0))
+                    {
+                        validate_decimal_precision::<Decimal32Type>(
+                            rounded, *precision, *new_scale,
+                        )
+                    } else {
+                        Ok(rounded)
+                    }
```
Comment (Jefffrey) [inline datafusion/functions/src/math/round.rs]: I feel these arms can be deduplicated using `DecimalType` generic, potentially with the scalar fast path above too?

File: datafusion/functions/src/math/round.rs [hunk 17]
```diff
@@ -377,9 +619,45 @@ fn round_decimal<V: ArrowNativeTypeOp>(
...
+
+    if output_scale == computed_scale {
+        // scale reduction, return quotient directly (or shifted for negative dp)
+        if decimal_places >= 0 {
+            Ok(quotient)
+        } else {
+            // For negative decimal_places, multiply by 10^(-decimal_places) to shift left
+            let neg_dp: u32 = (-decimal_places).try_into().map_err(|_| {
+                ArrowError::ComputeError(format!(
+                    "Invalid negative decimal places: {decimal_places}"
```
Comment (Jefffrey) [inline datafusion/functions/src/math/round.rs]: I don't think we can have a invalid `decimal_places`? At least, we shouldn't throw an error; what are some examples of invalid values?

File: datafusion/sqllogictest/test_files/scalar.slt [hunk 18]
```diff
@@ -951,15 +952,51 @@ query TR
...
 
 # round decimal256 keeps decimals
 query TR
 select arrow_typeof(round('1234.5678'::decimal(50,4), 2)),
        round('1234.5678'::decimal(50,4), 2);
 ----
-Decimal256(50, 4) 1234.57
+Decimal256(50, 2) 1234.57
+
+# round decimal with carry-over (reduce scale)
```
Comment (Jefffrey) [inline datafusion/sqllogictest/test_files/scalar.slt:971]: Do we have tests for decimals with negative scales?

**Comment by MichaelScofield** [comment]
Great work, thx @kumarUjjawal @Jefffrey ! Is this PR able to merge?

**Comment by kumarUjjawal** [comment]
@MichaelScofield I'm just waiting for one last look from @Jefffrey and @martin-g

File: datafusion/functions/src/math/round.rs [hunk 19]
```diff
@@ -117,15 +228,59 @@ impl ScalarUDFImpl for RoundFunc {
...
+
+        // If decimal_places is a scalar literal, we can incorporate it into the output type
+        // (scale reduction). Otherwise, keep the input scale as we can't pick a per-row scale.
+        //
+        // Note: `scalar_arguments` contains the original literal values (pre-coercion), so
+        // integer literals may appear as Int64 even though the signature coerces them to Int32.
+        let decimal_places: Option<i32> = match args.scalar_arguments.get(1) {
+            None => Some(0),    // No dp argument means default to 0
+            Some(None) => None, // dp is not a literal (e.g. column)
+            Some(Some(scalar)) if scalar.is_null() => Some(0), // null dp => output is null
```
Comment (martin-g) [inline datafusion/functions/src/math/round.rs]:
```suggestion
            Some(Some(scalar)) if scalar.is_null() => Some(0), // null dp => default to 0
```

File: datafusion/functions/src/math/round.rs [hunk 20]
```diff
@@ -25,19 +25,130 @@ use arrow::datatypes::DataType::{
...
+}
+
+fn validate_decimal_precision<T: DecimalType>(
+    value: T::Native,
+    precision: u8,
+    scale: i8,
+) -> Result<T::Native, ArrowError> {
+    T::validate_decimal_precision(value, precision, scale).map_err(|_| {
+        ArrowError::ComputeError(format!(
+            "Decimal overflow: rounded value exceeds precision {precision}"
```
Comment (martin-g) [inline datafusion/functions/src/math/round.rs]: nit: Preserve the cause:
```suggestion
    T::validate_decimal_precision(value, precision, scale).map_err(|e| {
        ArrowError::ComputeError(format!(
            "Decimal overflow: rounded value exceeds precision {precision}: {e}"
```

**Review by martin-g — APPROVED** [review]

**Comment by martin-g** [comment]
Thank you for the contribution, @kumarUjjawal !

Thank you for the review, @Jefffrey !
