### PR TITLE
Substrait: Handle inner map fields in schema renaming

### LINKED ISSUE #15868: Substrait: Handle inner map fields in schema renaming
### Describe the bug

When doing substrait plan to DF plan, currently inner map fields are not handled correctly when renaming the schema.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cht42**
## Which issue does this PR close?

- Closes #15868.

### CODE REVIEW

**Review by gabotechs — COMMENTED** [review]
Thanks for this fix! would it be possible to add a test that replicates the issue on `main` and shows that this PR solves it?

File: datafusion/substrait/tests/cases/substrait_validations.rs [hunk 1]
```diff
@@ -61,16 +61,41 @@ mod tests {
...
 
             let ctx = generate_context_with_table("DATA", df_schema)?;
             let plan = from_substrait_plan(&ctx.state(), &proto_plan).await?;
 
             assert_snapshot!(
             plan,
             @r#"
-                Projection: DATA.a, DATA.b
+                Projection: DATA.a, DATA.b, DATA.c
                   TableScan: DATA
```
Comment (gabotechs) [inline datafusion/substrait/tests/cases/substrait_validations.rs:99]: Thanks for the tests! I think it might be worth to expand a bit on them, as they are only testing the new functionality partially. For example, I could replace the code committed in [datafusion/substrait/src/logical_plan/consumer.rs](https://github.com/apache/datafusion/pull/15869/files#diff-474e53672159d74dae38992a914a74eba81b8350ebe161f11d755f06414ed7b4R1012-R1044) with just the following:
```rust
        ...
        DataType::Map(inner, _) => match inner.data_type() {
            DataType::Struct(key_and_value) if key_and_value.len() == 2 => {
                *name_idx += 1;
                Ok(field.clone())
            }
            _ => substrait_err!("Map fields must contain a Struct with exactly 2 fields"),
        },
        ...
```
And make the test green, even though the code is wrong.

Maybe @Blizzara or @westonpace can give a bit more insights about how to better test this.

Comment (cht42) [reply datafusion/substrait/tests/cases/substrait_validations.rs]: updated with unit tests

File: datafusion/substrait/src/logical_plan/consumer/utils.rs [hunk 2]
```diff
@@ -396,4 +435,120 @@ pub(crate) mod tests {
...
+                    )),
+                    false,
+                )),
+            ),
+            (
+                Some(table_ref.clone()),
+                Arc::new(Field::new_map(
+                    "7",
+                    "entries",
+                    Arc::new(Field::new("keys", DataType::Int32, false)),
```
Comment (Blizzara) [inline datafusion/substrait/src/logical_plan/consumer/utils.rs:479]: make `keys` also a struct?

Comment (cht42) [reply datafusion/substrait/src/logical_plan/consumer/utils.rs:479]: done

**Review by Blizzara — APPROVED** [review]
Thanks! (I work with @cht42 )

**Review by alamb — APPROVED** [review]
Looks good to me -- thank you @cht42 and @Blizzara 

@gabotechs  is this PR good to merge from your perspective?

**Review by gabotechs — APPROVED** [review]

**Comment by alamb** [comment]
I'll plan to merge tomorrow unless we get any more feedback
