### PR TITLE
fix: handle out of range errors in DATE_BIN instead of panicking

### LINKED ISSUE #20219: date_bin() panics on large inputs
### Describe the bug

Found via fuzzing.

### To Reproduce

```
select DATE_BIN('1637426858', TO_TIMESTAMP_MILLIS(1040292460), TIMESTAMP '1984-01-07 00:00:00');
```

Yields
```
thread 'main' (43082114) panicked at /Users/neilconway/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/chrono-0.4.43/src/datetime/mod.rs:1750:38:
`DateTime - Months` out of range
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/std/src/panicking.rs:698:5
   1: core::panicking::panic_fmt
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/core/src/panicking.rs:80:14
   2: core::panicking::panic_display
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/core/src/panicking.rs:264:5
   3: core::option::expect_failed
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/core/src/option.rs:2183:5
   4: core::option::Option<T>::expect
             at /Users/neilconway/.rustup/toolchains/1.92.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:970:21
   5: <chrono::datetime::DateTime<Tz> as core::ops::arith::Sub<chrono::month::Months>>::sub
             at /Users/neilconway/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/chrono-0.4.43/src/datetime/mod.rs:1750:38
   6: datafusion_functions::datetime::date_bin::date_bin_months_interval
             at ./datafusion/functions/src/datetime/date_bin.rs:358:9
   7: datafusion_functions::datetime::date_bin::date_bin_impl::stride_map_fn::{{closure}}
             at ./datafusion/functions/src/datetime/date_bin.rs:557:23
[...]
```

```
select DATE_BIN('1637426858', TO_TIMESTAMP_MILLIS(-1040292460), TIMESTAMP '1984-01-07 00:00:00');
```

Yields

```
thread 'main' (43083083) panicked at datafusion/functions/src/datetime/date_bin.rs:380:42:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/std/src/panicking.rs:698:5
   1: core::panicking::panic_fmt
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/core/src/panicking.rs:80:14
   2: core::panicking::panic
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/core/src/panicking.rs:150:5
   3: core::option::unwrap_failed
             at /rustc/ded5c06cf21d2b93bffd5d884aa6e96934ee4234/library/core/src/option.rs:2174:5
   4: core::option::Option<T>::unwrap
             at /Users/neilconway/.rustup/toolchains/1.92.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:1015:21
   5: datafusion_functions::datetime::date_bin::to_utc_date_time
             at ./datafusion/functions/src/datetime/date_bin.rs:380:42
   6: datafusion_functions::datetime::date_bin::date_bin_months_interval
             at ./datafusion/functions/src/datetime/date_bin.rs:346:23
   7: datafusion_functions::datetime::date_bin::date_bin_impl::stride_map_fn::{{closure}}
             at ./datafusion/functions/src/datetime/date_bin.rs:557:23
[...]
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mishop-15**
## Which issue does this PR close?

Closes #20219

## Rationale for this change

The DATE_BIN function was panicking when datetime operations went out of range instead of returning proper errors. The two specific cases were:
1. Month subtraction going out of range causing `DateTime - Months` panic
2. `timestamp_nanos_opt()` returning None and then unwrapping

## What changes are included in this PR?

- Changed `date_bin_months_interval` and `to_utc_date_time` to return `Result` instead of panicking
- Replaced `origin_date - Months` and `origin_date + Months` with `checked_sub_months` and `checked_add_months`
- Replaced `.unwrap()` calls with proper `match` statements and error handling
- Updated all callers throughout the file to handle `Result` types

## Are these changes tested?

Tested manually with the exact queries from the issue that were panicking:
```sql
select DATE_BIN('1637426858', TO_TIMESTAMP_MILLIS(1040292460), TIMESTAMP '1984-01-07 00:00:00');
select DATE_BIN('1637426858', TO_TIMESTAMP_MILLIS(-1040292460), TIMESTAMP '1984-01-07 00:00:00');
```

Both queries now return NULL instead of panicking. All existing unit tests pass.

## Are there any user-facing changes?

Yes - queries with DATE_BIN that would previously panic now return NULL when datetime operations go out of range.

### CODE REVIEW

**Comment by mishop-15** [comment]
> Thanks for looking at this! Can we add some test cases?

Added test cases for both out-of-range scenarios in the latest commit.

File: datafusion/functions/src/datetime/date_bin.rs [hunk 1]
```diff
@@ -546,110 +567,138 @@ fn date_bin_impl(
     fn stride_map_fn<T: ArrowTimestampType>(
         origin: i64,
         stride: i64,
-        stride_fn: fn(i64, i64, i64) -> i64,
-    ) -> impl Fn(i64) -> i64 {
+        stride_fn: fn(i64, i64, i64) -> Result<i64>,
```
Comment (neilconway) [inline datafusion/functions/src/datetime/date_bin.rs]: nit: Use `BinFunction` here?

**Review by neilconway — APPROVED** [review]

File: datafusion/functions/src/datetime/date_bin.rs (hunk 1 above)
Comment (mishop-15) [reply datafusion/functions/src/datetime/date_bin.rs]: Updated to use `BinFunction` alias. Thanks for the review.

**Comment by mishop-15** [comment]
@alamb @avantgardnerio When you get a chance, could you take a look at this PR? All feedback has been addressed, checks are passing, and it's ready for merge. Thanks!

File: datafusion/functions/src/datetime/date_bin.rs [hunk 2]
```diff
@@ -715,14 +774,20 @@ fn date_bin_impl(
...
                     let array = array.as_primitive::<Time64MicrosecondType>();
-                    let apply_stride_fn = move |x: i64| {
-                        let binned_nanos = stride_fn(stride, x * NANOS_PER_MICRO, origin);
-                        let nanos = binned_nanos % (NANOSECONDS_IN_DAY);
-                        nanos / NANOS_PER_MICRO
-                    };
-                    let array: PrimitiveArray<Time64MicrosecondType> =
-                        array.unary(apply_stride_fn);
-                    ColumnarValue::Array(Arc::new(array))
+                    let result: PrimitiveArray<Time64MicrosecondType> = array
```
Comment (alamb) [inline datafusion/functions/src/datetime/date_bin.rs]: How about using `try_unary`? https://docs.rs/arrow/latest/arrow/array/struct.PrimitiveArray.html#method.try_unary

I think that will result in a smaller diff and be faster as well

The same comment applies to the other methods in this function

File: datafusion/functions/src/datetime/date_bin.rs [hunk 3]
```diff
@@ -295,7 +295,7 @@ impl ScalarUDFImpl for DateBinFunc {
 const NANOS_PER_MICRO: i64 = 1_000;
 const NANOS_PER_MILLI: i64 = 1_000_000;
 const NANOS_PER_SEC: i64 = NANOSECONDS;
-
+type BinFunction = fn(i64, i64, i64) -> Result<i64>;
```
Comment (alamb) [inline datafusion/functions/src/datetime/date_bin.rs:306]: Can you please add comments here aout what `BinFunction` is and what it represents (e.g. what are the aguments and what does it return)?

Comment (mishop-15) [reply datafusion/functions/src/datetime/date_bin.rs:306]: Added comments explaining the arguments and return value.

File: datafusion/functions/src/datetime/date_bin.rs (hunk 2 above)
Comment (mishop-15) [reply datafusion/functions/src/datetime/date_bin.rs]: Switched to try_unary, thanks for pointing that out!

**Comment by alamb** [comment]
Thank you @mishop-15 and @mhilton and @neilconway
