### PR TITLE
Extract `Date32` parquet statistics as `Date32Array`  rather than `Int32Array`

### LINKED ISSUE #10587: DataFusion reads Date32 and Date64 parquet statistics in as Int32Array
### Describe the bug

When reading a Date32 or Date64 column from a parquet file, DataFusion currently returns an Int32 array

### To Reproduce

You can see the issue in https://github.com/apache/datafusion/pull/10537 
* `test_dates_32_diff_rg_sizes`
* `test_dates_64_diff_rg_sizes`

### Expected behavior

I expect a
1.  Date32 column to be read as `Date32Array`
2. Date64 column to be read as `Date64Array`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by xinlifoobar**
## Which issue does this PR close?

Closes #10587 

## Rationale for this change

This is to fix a bug when reading a Date32 or Date64 column from a parquet file, DataFusion currently returns an Int32 array

## What changes are included in this PR?

Adds conversions in the `get_statistic` marco from Int32 to Date32 and Date64 respectively.

## Are these changes tested?

Yes

### CODE REVIEW

File: datafusion/core/tests/parquet/arrow_statistics.rs [hunk 1]
```diff
@@ -605,9 +611,6 @@ async fn test_dates_32_diff_rg_sizes() {
     .run("date32");
 }
 
-// BUG: same as above. Expect to return Date64Array but returns Int32Array
-// test date with different row group sizes
-// https://github.com/apache/datafusion/issues/10587
 #[ignore]
```
Comment (crepererum) [inline datafusion/core/tests/parquet/arrow_statistics.rs:614]: should the `ignore` marker be removed?

**Review by edmondop — APPROVED** [review]
Not a PMC or a full-time committer, my review is not very valuable, but looks good to me.
 Added a comment to the PR outside the review to track whether we are ok with a catch-all pattern matching statement or we want to track somewhere to make the patterns explicit

**Comment by alamb** [comment]
> Not a PMC or a full-time committer, my review is not very valuable, but looks good to me.

Your review is valuable in my opinion -- thank you @edmondop

File: datafusion/core/src/datasource/physical_plan/parquet/statistics.rs [hunk 2]
```diff
@@ -75,6 +75,12 @@ macro_rules! get_statistic {
                             *scale,
                         ))
                     }
+                    Some(DataType::Date32) => {
+                        Some(ScalarValue::Date32(Some(*s.$func())))
+                    }
+                    Some(DataType::Date64) => {
```
Comment (alamb) [inline datafusion/core/src/datasource/physical_plan/parquet/statistics.rs:81]: I don't think a Date64 be stored as an `Int32` in parquet. Is this branch required to get the tests to pass? I would be surprised if it were covered

File: datafusion/core/src/datasource/physical_plan/parquet/statistics.rs [hunk 3]
```diff
@@ -75,6 +75,12 @@ macro_rules! get_statistic {
...
+                        Some(ScalarValue::Date64(Some(i64::from(*s.$func()) * 24 * 60 * 60 * 1000)))
+                    }
                     _ => Some(ScalarValue::Int32(Some(*s.$func()))),
```
[the remark this answers is not in the document]
Comment (alamb) [reply datafusion/core/src/datasource/physical_plan/parquet/statistics.rs:84]: I agree it is likely what is masking all the bugs

I am not sure if it is worth explicitly listing all the types out here to be honest 🤔  I am hoping in some future PR to revamp how these statistics are done entirely (basically match on the arrow target type in the outer loop rather than the inner loop)

File: datafusion/core/tests/parquet/arrow_statistics.rs [hunk 4]
```diff
@@ -593,10 +593,16 @@ async fn test_dates_32_diff_rg_sizes() {
 
     Test {
         reader,
-        // mins are [18262, 18565,]
-        expected_min: Arc::new(Int32Array::from(vec![18262, 18565])),
-        // maxes are [18564, 21865,]
-        expected_max: Arc::new(Int32Array::from(vec![18564, 21865])),
+        // mins are [2020-01-01, 2020-10-30]
+        expected_min: Arc::new(Date32Array::from(vec![
```
Comment (alamb) [inline datafusion/core/tests/parquet/arrow_statistics.rs:597]: ❤️  that is much easier to read

**Review by alamb — COMMENTED** [review]
Thank you @xinlifoobar  -- this looks really nice 👌 I had only one question related to Date64 but otherwise this PR looks good to me

File: datafusion/core/src/datasource/physical_plan/parquet/statistics.rs (hunk 2 above)
Comment (alamb) [reply datafusion/core/src/datasource/physical_plan/parquet/statistics.rs:81]: Actually, it turns out both Date32 and Date64 seem to be stored in Int32 in parquet.

**Comment by alamb** [comment]
This file had some merge conflicts so I took the liberty of merging up from main and addressing the comment https://github.com/apache/datafusion/pull/10593#discussion_r1608835566 in 43cf43524

Thank you again so much @xinlifoobar  -- very much appreciated

**Review by alamb — APPROVED** [review]
