### PR TITLE
fix: aggregation corner case

### LINKED ISSUE #15386: `panic` when evaluating trivial WHERE with a CTE
### Describe the bug

I am testing against Datafusion main (d68fca91fd4c73f2cd92d61d036bc0411a2ed826).

With the query below I get a crash.

### To Reproduce

```
DataFusion CLI v46.0.1
> with test AS (SELECT i as needle FROM generate_series(1, 10) t(i))
select count(*) from test WHERE 1 = 1;
Internal error: Physical input schema should be the same as the one converted from logical input schema. Differences: 
        - Different number of fields: (physical) 1 vs (logical) 0.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chenkovsky**
## Which issue does this PR close?

- Closes #15386 .

## Rationale for this change

for sql

```
with test AS (SELECT i as needle FROM generate_series(1, 10) t(i))
select count(*) from test WHERE 1 = 1;
```

The root cause is that after `optimize_projections`.
columns are dropped from logical plan, but in physical plan, there is still a value column.

## What changes are included in this PR?

add project in generated series

## Are these changes tested?

UT

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by jayzhan211** [comment]
Looks correct
```
query TT
explain
with test AS (SELECT i as needle FROM generate_series(1, 10) t(i))
select count(*) from test WHERE 1 = 1;
----
logical_plan
01)Projection: count(Int64(1)) AS count(*)
02)--Aggregate: groupBy=[[]], aggr=[[count(Int64(1))]]
03)----SubqueryAlias: test
04)------SubqueryAlias: t
05)--------TableScan: tmp_table projection=[]
physical_plan
01)ProjectionExec: expr=[count(Int64(1))@0 as count(*)]
02)--AggregateExec: mode=Final, gby=[], aggr=[count(Int64(1))]
03)----CoalescePartitionsExec
04)------AggregateExec: mode=Partial, gby=[], aggr=[count(Int64(1))]
05)--------RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=1
06)----------LazyMemoryExec: partitions=1, batch_generators=[generate_series: start=1, end=10, batch_size=8192]
```

**Comment by jayzhan211** [comment]
but why don't we have "value" column in logical plan schema

**Comment by jayzhan211** [comment]
> count（*） actually doesnt depend on any column on input logically

count(*) need to know the row number of the column

**Comment by jayzhan211** [comment]
> > > count（*） actually doesnt depend on any column on input logically
> > 
> > 
> > count(*) need to know the row number of the column, and it doesn't make sense to count all on "empty" column, so I guess keeping the column in logical plan makes more sense
> 
> but, for
> 
> ```sql
> with test AS (SELECT i as needle FROM generate_series(1, 10) t(i))
> select count(*), i from test WHERE 1 = 1 group by i;
> ```
> 
> there's no row number in both physical and logical plan. do you think we should also add row number for this sql?

In this case, the row number is 1. there are 10 group, each group contains single number.

File: datafusion/functions-table/src/generate_series.rs [hunk 1]
```diff
@@ -138,12 +138,15 @@ impl TableProvider for GenerateSeriesTable {
...
         &self,
         state: &dyn Session,
-        _projection: Option<&Vec<usize>>,
+        projection: Option<&Vec<usize>>,
         _filters: &[Expr],
         _limit: Option<usize>,
     ) -> Result<Arc<dyn ExecutionPlan>> {
         let batch_size = state.config_options().execution.batch_size;
-
+        let schema = match projection {
```
Comment (jayzhan211) [inline datafusion/functions-table/src/generate_series.rs:146]: Great that you find the root cause instead of having a workaround config!

**Review by jayzhan211 — APPROVED** [review]
Thanks @chenkovsky
