### PR TITLE
Segfault in ByteGroupValueBuilder

### LINKED ISSUE #15967: Memory safety issue in ByteGroupValueBuilder
### Describe the bug

The implementation of `ByteGroupValueBuilder` is unsound as cast back and forth between signed and unsigned integer types can lead to a out-of-bounds memory access since `ByteGroupValueBuilder::value` uses `core::slice::get_unchecked`

### To Reproduce

This test will segfault if run in release mode
```
    #[test]
    fn test_byte_group_value_builder_overflow() {
        let mut builder = ByteGroupValueBuilder::<i32>::new(OutputType::Utf8);
        
        let large_string = std::iter::repeat('a').take(1024 * 1024).collect::<String>();
        
        let array = Arc::new(StringArray::from(vec![Some(large_string.as_str())])) as ArrayRef;
        
        // Append items until our buffer length is 1 + i32::MAX as usize 
        for _ in 0..2048 {
            builder.append_val(&array, 0);
        }

        assert_eq!(builder.value(2047), large_string.as_bytes());
    }
```

### Expected behavior

Either `ByteGroupValueBuilder::do_append_val_inner` needs to validate that `self.buffer.len() <= i32::MAX as usize` or `ByteGroupValueBuilder::value` needs to use safe slice access. The former seems like a better option since it would panic with a more useful message

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by thinkharderdev**
## Which issue does this PR close?

- Closes #15967.

## Rationale for this change

See issue description

## What changes are included in this PR?

When appending values in `ByteGroupValueBuilder` we check for overflows of the underlying `OffsetSizeTrait` type

## Are these changes tested?

There is a test which reproduces the segfault without this fix

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/physical-plan/src/aggregates/group_values/multi_group_by/bytes.rs [hunk 1]
```diff
@@ -187,6 +194,13 @@ where
     {
         let value: &[u8] = array.value(row).as_ref();
         self.buffer.append_slice(value);
+
+        assert!(
```
Comment (alamb) [inline datafusion/physical-plan/src/aggregates/group_values/multi_group_by/bytes.rs:198]: would it be better to return an error here to the user instead of a panic? I realize that would require some additional plumbing.

However, a panic is certainly better than SEGFAULT 👍

File: datafusion/physical-plan/src/aggregates/group_values/multi_group_by/bytes.rs [hunk 2]
```diff
@@ -62,6 +64,11 @@ where
             buffer: BufferBuilder::new(INITIAL_BUFFER_CAPACITY),
             offsets: vec![O::default()],
             nulls: MaybeNullBufferBuilder::new(),
+            max_buffer_size: if O::IS_LARGE {
```
Comment (alamb) [inline datafusion/physical-plan/src/aggregates/group_values/multi_group_by/bytes.rs:67]: I couldn't find any other way to get the max value of the offset size, which is weird. Maybe it would be a nice addition to arrow-rs

**Comment by alamb** [comment]
🤖 `./gh_compare_branch.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/gh_compare_branch.sh) Running
Linux aal-dev 6.11.0-1013-gcp #13~24.04.1-Ubuntu SMP Wed Apr  2 16:34:16 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing offset-overflow (e3fcaf2efe14fbe947ceae4c0b7898b48472cf86) to 09a7a2a729c1c3a7e3ed1311462e6dcb389821cb [diff](https://github.com/apache/datafusion/compare/09a7a2a729c1c3a7e3ed1311462e6dcb389821cb..e3fcaf2efe14fbe947ceae4c0b7898b48472cf86)
Benchmarks: tpch_mem clickbench_partitioned clickbench_extended
Results will be posted here when complete

**Review by alamb — APPROVED** [review]
Thank you @thinkharderdev 

I started the performance tests just to check, but realistically we need to fix this issue

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
Comparing HEAD and offset-overflow
--------------------
Benchmark clickbench_extended.json
--------------------
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Query        ┃       HEAD ┃ offset-overflow ┃        Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ QQuery 0     │  1986.43ms │       1868.86ms │ +1.06x faster │
│ QQuery 1     │   704.83ms │        720.83ms │     no change │
│ QQuery 2     │  1476.92ms │       1460.99ms │     no change │
│ QQuery 3     │   709.70ms │        707.18ms │     no change │
│ QQuery 4     │  1453.93ms │       1462.20ms │     no change │
│ QQuery 5     │ 15346.57ms │      15058.53ms │     no change │
│ QQuery 6     │  2085.02ms │       2094.70ms │     no change │
│ QQuery 7     │  2061.65ms │       2032.67ms │     no change │
└──────────────┴────────────┴─────────────────┴───────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Benchmark Summary              ┃            ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ Total Time (HEAD)              │ 25825.05ms │
│ Total Time (offset-overflow)   │ 25405.95ms │
│ Average Time (HEAD)            │  3228.13ms │
│ Average Time (offset-overflow) │  3175.74ms │
│ Queries Faster                 │          1 │
│ Queries Slower                 │          0 │
│ Queries with No Change         │          7 │
└────────────────────────────────┴────────────┘
--------------------
Benchmark clickbench_partitioned.json
--------------------
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃ Query        ┃       HEAD ┃ offset-overflow ┃       Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━┩
│ QQuery 0     │     2.22ms │          2.18ms │    no change │
│ QQuery 1     │    39.68ms │         38.19ms │    no change │
│ QQuery 2     │    94.14ms │         91.56ms │    no change │
│ QQuery 3     │    95.85ms │         99.12ms │    no change │
│ QQuery 4     │   620.41ms │        629.68ms │    no change │
│ QQuery 5     │   864.93ms │        889.61ms │    no change │
│ QQuery 6     │     2.16ms │          2.41ms │ 1.12x slower │
│ QQuery 7     │    44.57ms │         45.35ms │    no change │
│ QQuery 8     │   889.87ms │        916.62ms │    no change │
│ QQuery 9     │  1228.70ms │       1214.68ms │    no change │
│ QQuery 10    │   265.13ms │        268.80ms │    no change │
│ QQuery 11    │   307.84ms │        312.65ms │    no change │
│ QQuery 12    │   927.03ms │        928.29ms │    no change │
│ QQuery 13    │  1390.15ms │       1374.36ms │    no change │
│ QQuery 14    │   850.50ms │        869.04ms │    no change │
│ QQuery 15    │   822.92ms │        827.88ms │    no change │
│ QQuery 16    │  1735.93ms │       1755.19ms │    no change │
│ QQuery 17    │  1602.91ms │       1630.27ms │    no change │
│ QQuery 18    │  3032.28ms │       3107.68ms │    no change │
│ QQuery 19    │    85.76ms │         85.26ms │    no change │
│ QQuery 20    │  1163.47ms │       1159.24ms │    no change │
│ QQuery 21    │  1353.11ms │       1348.19ms │    no change │
│ QQuery 22    │  2222.53ms │       2219.31ms │    no change │
│ QQuery 23    │  8392.20ms │       8530.03ms │    no change │
│ QQuery 24    │   472.88ms │        476.06ms │    no change │
│ QQuery 25    │   400.35ms │        409.19ms │    no change │
│ QQuery 26    │   546.73ms │        536.40ms │    no change │
│ QQuery 27    │  1603.72ms │       1612.58ms │    no change │
│ QQuery 28    │ 12823.03ms │      12680.22ms │    no change │
│ QQuery 29    │   547.10ms │        540.02ms │    no change │
│ QQuery 30    │   830.46ms │        837.03ms │    no change │
│ QQuery 31    │   869.77ms │        868.16ms │    no change │
│ QQuery 32    │  2610.03ms │       2658.05ms │    no change │
│ QQuery 33    │  3370.83ms │       3400.91ms │    no change │
│ QQuery 34    │  3375.37ms │       3379.85ms │    no change │
│ QQuery 35    │  1273.19ms │       1281.03ms │    no change │
│ QQuery 36    │   127.43ms │        130.76ms │    no change │
│ QQuery 37    │    57.69ms │         58.30ms │    no change │
│ QQuery 38    │   127.51ms │        128.13ms │    no change │
│ QQuery 39    │   208.11ms │        199.74ms │    no change │
│ QQuery 40    │    48.72ms │         52.45ms │ 1.08x slower │
│ QQuery 41    │    48.51ms │         49.08ms │    no change │
│ QQuery 42    │    40.57ms │         39.30ms │    no change │
└──────────────┴────────────┴─────────────────┴──────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Benchmark Summary              ┃            ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ Total Time (HEAD)              │ 57416.25ms │
│ Total Time (offset-overflow)   │ 57682.88ms │
│ Average Time (HEAD)            │  1335.26ms │
│ Average Time (offset-overflow) │  1341.46ms │
│ Queries Faster                 │          0 │
│ Queries Slower                 │          2 │
│ Queries with No Change         │         41 │
└────────────────────────────────┴────────────┘
--------------------
Benchmark tpch_mem_sf1.json
--------------------
┏━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
┃ Query        ┃     HEAD ┃ offset-overflow ┃       Change ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━┩
│ QQuery 1     │ 124.93ms │        120.60ms │    no change │
│ QQuery 2     │  23.44ms │         24.16ms │    no change │
│ QQuery 3     │  34.53ms │         35.05ms │    no change │
│ QQuery 4     │  19.97ms │         21.06ms │ 1.05x slower │
│ QQuery 5     │  55.80ms │         55.33ms │    no change │
│ QQuery 6     │  12.15ms │         11.93ms │    no change │
│ QQuery 7     │ 102.40ms │        104.75ms │    no change │
│ QQuery 8     │  25.48ms │         26.70ms │    no change │
│ QQuery 9     │  61.36ms │         65.87ms │ 1.07x slower │
│ QQuery 10    │  57.25ms │         58.77ms │    no change │
│ QQuery 11    │  12.70ms │         13.03ms │    no change │
│ QQuery 12    │  44.67ms │         45.08ms │    no change │
│ QQuery 13    │  29.08ms │         30.26ms │    no change │
│ QQuery 14    │   9.97ms │         10.20ms │    no change │
│ QQuery 15    │  24.46ms │         25.04ms │    no change │
│ QQuery 16    │  22.54ms │         23.57ms │    no change │
│ QQuery 17    │  99.37ms │        101.65ms │    no change │
│ QQuery 18    │ 242.76ms │        241.30ms │    no change │
│ QQuery 19    │  26.53ms │         27.01ms │    no change │
│ QQuery 20    │  38.79ms │         41.15ms │ 1.06x slower │
│ QQuery 21    │ 167.04ms │        170.63ms │    no change │
│ QQuery 22    │  16.74ms │         17.56ms │    no change │
└──────────────┴──────────┴─────────────────┴──────────────┘
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃ Benchmark Summary              ┃           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│ Total Time (HEAD)              │ 1251.98ms │
│ Total Time (offset-overflow)   │ 1270.69ms │
│ Average Time (HEAD)            │   56.91ms │
│ Average Time (offset-overflow) │   57.76ms │
│ Queries Faster                 │         0 │
│ Queries Slower                 │         3 │
│ Queries with No Change         │        19 │
└────────────────────────────────┴───────────┘
```


</p>
</details>

File: datafusion/physical-plan/src/aggregates/group_values/multi_group_by/bytes.rs (hunk 1 above)
Comment (thinkharderdev) [reply datafusion/physical-plan/src/aggregates/group_values/multi_group_by/bytes.rs:198]: Yeah I think in general it would be better. Panicking due to offset overflow is common in other places though so it's not that jarring :)

File: datafusion/physical-plan/src/aggregates/group_values/multi_group_by/bytes.rs (hunk 2 above)
Comment (thinkharderdev) [reply datafusion/physical-plan/src/aggregates/group_values/multi_group_by/bytes.rs:67]: Agreed: https://github.com/apache/arrow-rs/issues/7474

**Review by jayzhan211 — APPROVED** [review]

File: datafusion/physical-plan/src/aggregates/group_values/multi_group_by/bytes.rs (hunk 1 above)
Comment (Dandandan) [reply datafusion/physical-plan/src/aggregates/group_values/multi_group_by/bytes.rs:198]: https://github.com/apache/datafusion/issues/15969

File: datafusion/physical-plan/src/aggregates/group_values/multi_group_by/bytes.rs (hunk 2 above)
Comment (Dandandan) [reply datafusion/physical-plan/src/aggregates/group_values/multi_group_by/bytes.rs:67]: 👍

**Review by Dandandan — APPROVED** [review]

**Comment by Dandandan** [comment]
Thanks all!
