### PR TITLE
fix: Don't treat quoted column names as placeholder variables in SQL

### LINKED ISSUE #19249: Quoted field names beginning with @ treated as variables by SQL parser
### Describe the bug

My understanding, which could be wrong, is that quoted field names should not be treated as placeholder variables when parsing SQL statements.

For example:
```
SELECT `@my_field` FROM my_table
```

The SqlToRel parser currently treats these fields as variables, because it [only checks](https://github.com/apache/datafusion/blob/6751f441f435efc401376c1d3d35397b1b39ab1f/datafusion/sql/src/expr/identifier.rs#L39) for the name starting with `@` and does not check if the name was quoted. I think the fix is as simple as updating the condition from `id.value.starts_with('@')` to `id.value.starts_with('@') && id.quote_style.is_none()`, but would like to hear some thoughts on this.

### To Reproduce

Execute the following test:
```
    #[test]
    fn test_quoted_field_names_with_at_sign() {
        use std::sync::Arc;
        use datafusion::arrow::datatypes::{DataType, Field, Schema};
        use datafusion::config::ConfigOptions;
        use datafusion::logical_expr::LogicalTableSource;
        use datafusion_sql::planner::{ContextProvider, SqlToRel};
        use datafusion_sql::sqlparser::dialect::GenericDialect;
        use datafusion_sql::sqlparser::parser::Parser;

        struct MyContextProvider {
            config_options: ConfigOptions
        }

        impl ContextProvider for MyContextProvider {
            fn get_table_source(&self, _name: datafusion_sql::TableReference) -> datafusion_common::Result<Arc<dyn datafusion::logical_expr::TableSource>> {
                let mut fields = Vec::new();
                fields.push(Field::new("@my_field", DataType::Utf8, true));
                let schema = Arc::new(Schema::new(fields));
                let table = Arc::new(LogicalTableSource::new(schema));
                Ok(table)
            }
            fn get_function_meta(&self, _name: &str) -> Option<Arc<datafusion::logical_expr::ScalarUDF>> { None }
            fn get_aggregate_meta(&self, _name: &str) -> Option<Arc<datafusion::logical_expr::AggregateUDF>> { None }
            fn get_window_meta(&self, _name: &str) -> Option<Arc<datafusion::logical_expr::WindowUDF>> { None }
            fn get_variable_type(&self, _variable_names: &[String]) -> Option<datafusion::arrow::datatypes::DataType> { None }
            fn options(&self) -> &datafusion::config::ConfigOptions { &self.config_options }
            fn udf_names(&self) -> Vec<String> { Vec::new() }
            fn udaf_names(&self) -> Vec<String> { Vec::new() }
            fn udwf_names(&self) -> Vec<String> { Vec::new() }
        }

        let sql = r#"SELECT `@my_field` FROM my_table"#;
        let dialect = GenericDialect {};
        let abstract_syntax_tree = Parser::parse_sql(&dialect, sql).unwrap();
        let statement = &abstract_syntax_tree[0];
        let context_provider = MyContextProvider { config_options: ConfigOptions::default() };
        let sql_to_rel = SqlToRel::new(&context_provider);
        let plan = sql_to_rel.sql_statement_to_plan(statement.clone());

        println!("{}", plan.unwrap());
    }
```

Running this test will result in the following error:
```
called `Result::unwrap()` on an `Err` value: Plan("variable [\"@my_field\"] has no type information")
```

### Expected behavior

This should produce a logical plan with `@my_field` as an identifier:
```
Projection: my_table.@my_field
  TableScan: my_table
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by pmallex**
## Which issue does this PR close?

Closes #19249

## Rationale for this change

SQL allows for column names to begin with `@`, so long as the identifier is quoted. For example, `SELECT "@column" FROM table`. Both PostgreSQL and MySQL allow for this at least. The existing SQL parser treats these column names as placeholder variables, because it does not check if the identifier is quoted. This change corrects that behavior.

## What changes are included in this PR?

sql/src/expr/identifier.rs - fix to check if identifiers are quoted
sql/tests/common/mod.rs - new test table
sql/tests/sql_integration.rs - unit test

## Are these changes tested?

Yes, `test_parse_quoted_column_name_with_at_sign` unit test was added to verify quoted column names beginning with `@` are treated as column names instead of placeholder variables.

## Are there any user-facing changes?

It's possible users are relying on the existing behavior.

### CODE REVIEW

**Comment by pmallex** [comment]
Per https://datafusion.apache.org/contributor-guide/index.html#pull-request-overview, @timsaucer could you trigger the CI for this PR?

**Comment by pmallex** [comment]
Fixing the formatting issue.

File: datafusion/sql/src/expr/identifier.rs
Comment (martin-g) [inline datafusion/sql/src/expr/identifier.rs]: Is the same fix needed here too ?

File: datafusion/sql/tests/sql_integration.rs [hunk 1]
```diff
@@ -4617,6 +4617,29 @@ fn test_parse_escaped_string_literal_value() {
...
+    let plan = logical_plan(sql).unwrap();
+    assert_snapshot!(
+        plan,
+        @r#"
+    Projection: quoted_column_name_table.@column
+      TableScan: quoted_column_name_table
+    "#
+    );
+}
+
```
Comment (martin-g) [inline datafusion/sql/tests/sql_integration.rs:4561]: I don't see any similar tests here for unquoted `@variable`. Maybe add some too ?

Comment (pmallex) [reply datafusion/sql/tests/sql_integration.rs:4561]: Yeah that makes sense. Let me get another revision out.

File: datafusion/sql/src/expr/identifier.rs
Comment (pmallex) [reply datafusion/sql/src/expr/identifier.rs]: It seems like it should. I tried some tests to force this path to be exercised, but couldn't find one. I'll look some more.

**Comment by pmallex** [comment]
@martin-g apologies for the inactivity here. Addressed your comments and pushed a new revision.

File: datafusion/sql/tests/sql_integration.rs [hunk 2]
```diff
@@ -4522,6 +4522,42 @@ fn test_parse_escaped_string_literal_value() {
...
+#[test]
+fn test_variable_identifier() {
+    let sql = r"SELECT @variable = t_date32 FROM test";
+    let plan = logical_plan(sql).unwrap();
+    assert_snapshot!(
+        plan,
+        @r#"
+    Projection: @variable = test.t_date32
```
Comment (Jefffrey) [inline datafusion/sql/tests/sql_integration.rs]: The output doesn't seem to have a way to indicate if this was parsed as a variable or identifier? I wonder if there is a way to make this difference more obvious 🤔

**Review by Jefffrey — APPROVED** [review]
Just a minor comment on tests

File: datafusion/sql/tests/sql_integration.rs (hunk 2 above)
Comment (pmallex) [reply datafusion/sql/tests/sql_integration.rs]: Makes sense. I pushed a new revision that makes this clearer. If it was an identifier then it would be qualified with the table name in the filter.

**Comment by Jefffrey** [comment]
Thanks @pmallex & @martin-g
