### PR TITLE
Fix `regex` cache on pattern, less alloc, hash less often

### LINKED ISSUE #13413: regexpcount caches regex on a wrong key
### Describe the bug

regexpcount caches regex on a raw regex string rather than on the regex pattern (including flags) as other regexp functions

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Dimchikkk**
## Which issue does this PR close?

Closes #13413

## Rationale for this change

Fixes bug, also code refactoring to have less allocations and calculate hash less often.

## Are these changes tested?

Yes, the new unit test has been added to cover a bug fix. Also, bench results.. so regexp_count has similar perf as other regexp functions now:

```rs
regexp_count_1000 string
                        time:   [2.4421 ms 2.4491 ms 2.4562 ms]
                        change: [-2.4790% -2.1304% -1.7839%] (p = 0.00 < 0.05)
                        Performance has improved.

regexp_count_1000 utf8view
                        time:   [2.4608 ms 2.4686 ms 2.4766 ms]
                        change: [-2.4392% -1.9838% -1.5766%] (p = 0.00 < 0.05)
                        Performance has improved.

regexp_like_1000        time:   [2.4550 ms 2.4806 ms 2.5182 ms]
                        change: [-2.9338% -1.1353% +0.4878%] (p = 0.23 > 0.05)
                        No change in performance detected.
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high severe

regexp_match_1000       time:   [2.8470 ms 2.8799 ms 2.9283 ms]
                        change: [-2.7508% -0.8240% +1.3563%] (p = 0.46 > 0.05)
                        No change in performance detected.
Found 7 outliers among 100 measurements (7.00%)
  4 (4.00%) high mild
  3 (3.00%) high severe

regexp_replace_1000     time:   [2.2726 ms 2.2786 ms 2.2851 ms]
                        change: [-3.7486% -2.7447% -1.9508%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild
```

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/functions/src/regex/regexpcount.rs [hunk 1]
```diff
@@ -548,19 +549,25 @@ where
...
-    regex_cache: &'a mut HashMap<String, Regex>,
-) -> Result<&'a Regex, ArrowError> {
-    if !regex_cache.contains_key(regex) {
+fn compile_and_cache_regex<'strings, 'cache>(
+    regex: &'strings str,
+    flags: Option<&'strings str>,
+    regex_cache: &'cache mut HashMap<(&'strings str, Option<&'strings str>), Regex>,
+) -> Result<&'cache Regex, ArrowError>
+where
+    'strings: 'cache,
```
Comment (Omega359) [inline datafusion/functions/src/regex/regexpcount.rs:558]: I've never seen this before. Does this effectively mean 'strings is equivalent to 'cache ?

File: datafusion/functions/src/regex/regexpcount.rs [hunk 2]
```diff
@@ -977,4 +985,25 @@ mod tests {
         .unwrap();
         assert_eq!(re.as_ref(), &expected);
     }
+
+    fn test_case_regexp_count_cache_check<A>()
```
Comment (Omega359) [inline datafusion/functions/src/regex/regexpcount.rs:989]: I ran this test locally and verified it failed with the "i" flags item.

**Review by Omega359 — APPROVED** [review]

**Review by jonathanc-n — APPROVED** [review]
This lgtm! This explains why this function was going a lot faster than the other regex expressions. Thanks @Dimchikkk

File: datafusion/functions/src/regex/regexpcount.rs (hunk 1 above)
Comment (jonathanc-n) [reply datafusion/functions/src/regex/regexpcount.rs:558]: Yeah, that was I was looking into, I think its saying that strings comes before the cache and lives after as well. I don't know if that is the correct behaviour

Comment (Dimchikkk) [reply datafusion/functions/src/regex/regexpcount.rs:558]: "strings outlives hashmap" or "strings lasts longer than hashmap", so hashmap can borrow data from strings (because while hashmap holds data from strings, strings won't die), but if hashmap dies before strings dies, it's fine.

File: datafusion/functions/src/regex/regexpcount.rs [hunk 3]
```diff
@@ -634,6 +640,8 @@ mod tests {
         test_case_sensitive_regexp_count_array_complex::<GenericStringArray<i32>>();
         test_case_sensitive_regexp_count_array_complex::<GenericStringArray<i64>>();
         test_case_sensitive_regexp_count_array_complex::<StringViewArray>();
+
```
[the remark this answers is not in the document]
Comment (Dimchikkk) [reply datafusion/functions/src/regex/regexpcount.rs:643]: Tests are grouped & group separated by space?

[the remark this answers is not in the document]
Comment (Omega359) [reply datafusion/functions/src/regex/regexpcount.rs:646]: Personal preference @Dimchikkk, you are free to choose.

[the remark this answers is not in the document]
Comment (jonathanc-n) [reply datafusion/functions/src/regex/regexpcount.rs:646]: Oh good poit didn't se ethat

File: datafusion/functions/src/regex/regexpcount.rs [hunk 4]
```diff
@@ -548,16 +549,22 @@ where
     }
 }
 
-fn compile_and_cache_regex<'a>(
-    regex: &'a str,
-    flags: Option<&'a str>,
-    regex_cache: &'a mut HashMap<String, Regex>,
-) -> Result<&'a Regex, ArrowError> {
-    if !regex_cache.contains_key(regex) {
```
Comment (alamb) [inline datafusion/functions/src/regex/regexpcount.rs:556]: the bug is that this check doesn't include the flags, is that correct?

**Review by alamb — APPROVED** [review]
Thank @Dimchikkk @Omega359 and @jonathanc-n

**Comment by alamb** [comment]
Thanks again @Dimchikkk
