### PR TITLE
Handle nulls in approx_percentile_cont

### LINKED ISSUE #11720: `APPROX_PERCENTILE_CONT` doesn't handle nulls and gives incorrect answer
### Describe the bug

```sql
select APPROX_PERCENTILE_CONT(v, 0.5) FROM (VALUES (1), (2), (3), (NULL), (NULL), (NULL)) as t (v);
+------------------------------------------+
| APPROX_PERCENTILE_CONT(t.v,Float64(0.5)) |
+------------------------------------------+
| 0                                        |
+------------------------------------------+
1 row in set. Query took 0.002 seconds.
```

### To Reproduce

_No response_

### Expected behavior

Should return 2 (answer without nulls). `0` is not input, so obviously incorrect, ignoring the nulls it should have given `NULL`

Following PostgreSQL query also gives 2:

```
SELECT percentile_cont(0.5) WITHIN GROUP(order by v) FROM (VALUES (1), (2), (3), (NULL), (NULL), (NULL)) as t (v);
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Dandandan**
## Which issue does this PR close?

Closes #11720

## Rationale for this change

Fix a bug in `approx_percentile_cont` when having nulls in input

## What changes are included in this PR?
Filters input arrays on nulls if present

## Are these changes tested?
Yes, additional sql test

## Are there any user-facing changes?
Just the fix

### CODE REVIEW

File: datafusion/functions-aggregate/src/approx_percentile_cont.rs [hunk 1]
```diff
@@ -104,6 +105,12 @@ impl ApproxPercentileCont {
             None
         };
 
+        if args.ignore_nulls {
+            return not_impl_err!(
+                "IGNORE NULLS clause not yet supported for APPROX_PERCENTILE_CONT"
```
Comment (Dandandan) [inline datafusion/functions-aggregate/src/approx_percentile_cont.rs:110]: Effectively this fix actually does ignore nulls, but we don't have a way to disable setting RESPECT NULLS.
I believe we should also move DataFusion to `SELECT percentile_cont(0.5) WITHIN GROUP(order by v)` (used by PostgreSQL, others) syntax...

File: datafusion/functions-aggregate/src/approx_percentile_cont.rs [hunk 2]
```diff
@@ -104,6 +105,12 @@ impl ApproxPercentileCont {
             None
         };
 
+        if args.ignore_nulls {
```
Comment (alamb) [inline datafusion/functions-aggregate/src/approx_percentile_cont.rs:108]: Maybe it is worth a negative test for this (aka run a query that generates this Error)

**Review by alamb — APPROVED** [review]
Thanks @Dandandan

File: datafusion/functions-aggregate/src/approx_percentile_cont.rs (hunk 1 above)
Comment (alamb) [reply datafusion/functions-aggregate/src/approx_percentile_cont.rs:110]: Maybe we can trigger it if used as a window function `PERCENTILE_CONT(...) OVER (PARTITION BY ... IGNORE NULLS)` 🤔

Comment (Dandandan) [reply datafusion/functions-aggregate/src/approx_percentile_cont.rs]: Hm... for now I think it makes sense to ignore the `ignore_nulls` argument (like we did before) and remove any nulls which makes the most sense. Null handling is broken anyway (resulting in 0 instead of NULL), so no one will rely on percentile_cont on columns with nulls.
I'll file a ticket to discuss standardizing `PERCENTILE_CONT` and having it behave like PostgreSQL / Spark  / Snowflake, etc....

File: datafusion/functions-aggregate/src/approx_percentile_cont.rs (hunk 2 above)
Comment (Dandandan) [reply datafusion/functions-aggregate/src/approx_percentile_cont.rs]: Removed the check / error for now

File: datafusion/sqllogictest/test_files/aggregate.slt [hunk 3]
```diff
@@ -1237,6 +1237,12 @@ SELECT (ABS(1 - CAST(approx_percentile_cont(c11, 0.9) AS DOUBLE) / 0.834) < 0.05
 ----
 true
 
+# percentile_cont_with_nulls
+query I
+SELECT APPROX_PERCENTILE_CONT(v, 0.5) FROM (VALUES (1), (2), (3), (NULL), (NULL), (NULL)) as t (v);
+----
+2
```
Comment (Dandandan) [inline datafusion/sqllogictest/test_files/aggregate.slt:1244]: This was `0` before (not even NULL)

File: datafusion/functions-aggregate/src/approx_percentile_cont.rs (hunk 1 above)
Comment (Dandandan) [reply datafusion/functions-aggregate/src/approx_percentile_cont.rs]: https://github.com/apache/datafusion/issues/11732
