### PR TITLE
Coerce types for all union children plans when eliminating nesting

### LINKED ISSUE #11385: Regression in TPC-DS Q75
### Describe the bug

While logical and physical planning work fine for TPC-DS Q75, as of v39.0.0 the execution throws the following error 
```
Error: External(External(ArrowError(InvalidArgumentError("RowConverter column schema mismatch, expected Int32 got Int64"), None)))
```

### To Reproduce

Generate TPC-DS dataset, or use the one attached (for SF=0.01): [tpcds_sf0_01.zip](https://github.com/user-attachments/files/16157369/tpcds_sf0_01.zip)

Register parquet files as tables
```rust
...
ctx.register_parquet(
        "catalog_sales",
        "/Users/gruuya/Splitgraph/tpcds_sf0_01/catalog_sales.parquet",
        ParquetReadOptions::default(),
    )
        .await?;
...
```

And run the [query](https://github.com/apache/datafusion/blob/main/datafusion/core/tests/tpc-ds/75.sql) 
```rust
let df = ctx.sql("...").await?;
df.show().await?;
```

It will error out with the above error.

### Expected behavior

The query shouldn't error out, and should return something like
```sql
+-----------+------+------------+------------+---------------+---------------+-------------+-------------+----------------+----------------+
| prev_year | year | i_brand_id | i_class_id | i_category_id | i_manufact_id | prev_yr_cnt | curr_yr_cnt | sales_cnt_diff | sales_amt_diff |
+-----------+------+------------+------------+---------------+---------------+-------------+-------------+----------------+----------------+
| 2001      | 2002 | 8015002    | 15         | 8             | 167           | 5346        | 3418        | -1928          | -94072.53      |
| 2001      | 2002 | 10016012   | 13         | 8             | 46            | 5125        | 3338        | -1787          | -81828.03      |
+-----------+------+------------+------------+---------------+---------------+-------------+-------------+----------------+----------------+
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gruuya**
## Which issue does this PR close?

Closes #11385.

## Rationale for this change

Investigating the above issue led me to identify a couple of aspects that need to align in order for the bug to manifest:
- there's a (grouping) aggregation
- of a >2 way union
- with some type coercion

In particular here's a minimal repro of the above issue
```sql
> select c1, sum(c2) as sum_c2
from (select 1 as c1, 1::int as c2
    union
    select 2 as c1, 2::int as c2
    union
    select 3 as c1, coalesce(3::int, 0) as c2)
group by c1;
External error: External error: External error: Arrow error: Invalid argument error: RowConverter column schema mismatch, expected Int32 got Int64
```

What happens is that the nested union elimination unwraps the first two child plans and coerces their schema, however the remaining plan isn't being coerced. Upon physical planning Union inherits the schema of the first child plan.

Consequently during execution, the RowConverter gets instantiated with `Int32` type, whereas the last child will produce `Int64` elements, since `coalesce` enforces type coercion to align the left element with the right one (represented as `Int64(0)`)

## What changes are included in this PR?

Coerce all child plans of the outer union as per it's schema, not only plans in the inner union.

## Are these changes tested?

There's a new SLT.

## Are there any user-facing changes?

No error in TPC-DS Q75

### CODE REVIEW

File: datafusion/optimizer/src/eliminate_nested_union.rs [hunk 1]
```diff
@@ -60,7 +60,8 @@ impl OptimizerRule for EliminateNestedUnion {
                 let inputs = inputs
                     .into_iter()
                     .flat_map(extract_plans_from_union)
-                    .collect::<Vec<_>>();
+                    .map(|plan| coerce_plan_expr_for_schema(&plan, &schema))
```
Comment (alamb) [inline datafusion/optimizer/src/eliminate_nested_union.rs:63]: This makes sense -- that the children were not all coerced with respect to the outermost union schema but rather with respect to the inner one.

File: datafusion/sqllogictest/test_files/union.slt [hunk 2]
```diff
@@ -135,6 +135,21 @@ SELECT SUM(d) FROM (
 ----
 5
 
+# three way union with aggregate and type coercion
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/union.slt:138]: I verified that this test covers the fix by running this test without the code changes and it fails as expected

```
Running "pg_compat/pg_compat_union.slt"
Running "union.slt"
External error: query failed: DataFusion error: External error: External error: External error: Arrow error: Invalid argument error: RowConverter column schema mismatch, expected Int32 got Int64
[SQL] SELECT c1, SUM(c2) FROM (
    SELECT 1 as c1, 1::int as c2
    UNION
    SELECT 2 as c1, 2::int as c2
    UNION
    SELECT 3 as c1, COALESCE(3::int, 0) as c2
) as a
GROUP BY c1
at test_files/union.slt:139

Error: Execution("1 failures")
error: test failed, to rerun pass `-p datafusion-sqllogictest --test sqllogictests`
```

**Review by alamb — COMMENTED** [review]
Thanks @gruuya 

This fix makes sense to me. Thank you



cc @erratic-pattern as I think you observed something similar at some point

**Comment by erratic-pattern** [comment]
> cc @erratic-pattern as I think you observed something similar at some point

https://github.com/apache/datafusion/issues/11258 is (possibly) a similar type coercion bug when `CASE` is used inside an aggregate, but I think it will involve a different fix.

**Comment by alamb** [comment]
Thanks again!
