### PR TITLE
fix: add `order_requirement` & `dist_requirement` to `OutputRequirementExec` display

### LINKED ISSUE #16725: [Discussion]: show more info for `OutputRequirementExec` display
Currently, the display of  `OutputRequirementExec` only contains the name 
```
01)DataSinkExec: sink=ParquetSink(file_groups=[])
02)--CoalescePartitionsExec
03)----ProjectionExec: expr=[CAST(c1@0 AS Int64) as field1, a@1 as field2]
04)------RepartitionExec: partitioning=RoundRobinBatch(8), input_partitions=1
05)--------OutputRequirementExec
```

It'll be helpful to include `order_requirement` and `dist_requirement`

### PR DESCRIPTION
**Pull request by Loaki07**
## Which issue does this PR close?

- Closes #16725.

## What changes are included in this PR?
- Adds the info of the `order_by` cols and distribution requirements as `dist_requirements`
```sh
OutputRequirementExec: order_by=[(b@1, asc), (c@2 + a@0, asc)], dist_by=HashPartitioned[[a@0, b@1]])
```

## Are these changes tested?

Yes

### CODE REVIEW

**Review by xudong963 — COMMENTED** [review]
I believe there are more tests that need to be updated

**Comment by Loaki07** [comment]
I ran both `cargo test -p datafusion-sqllogictest --test sqllogictests` and `cargo test`, fixed them both. Please review.

**Comment by Loaki07** [comment]
Looks like the ci is unable to install `sudo apt-get install -y protobuf-compiler` 

```
E: Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/universe/p/protobuf/protobuf-compiler_3.21.12-8.2ubuntu0.1_amd64.deb  404  Not Found [IP: 52.252.163.49 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```

File: datafusion/core/tests/physical_optimizer/enforce_sorting.rs [hunk 1]
```diff
@@ -983,7 +983,7 @@ async fn test_soft_hard_requirements_with_multiple_soft_requirements_and_output_
     ));
 
     let expected_input = [
-        "OutputRequirementExec",
+        "OutputRequirementExec: order_by=[([non_nullable_col@1], asc)], dist_by=SinglePartition",
```
Comment (xudong963) [inline datafusion/core/tests/physical_optimizer/enforce_sorting.rs]: It seems that we can remove the extra `[]` around order by expr to make the display concise.

`order_by=[(non_nullable_col@1, asc)]`

Comment (Loaki07) [reply datafusion/core/tests/physical_optimizer/enforce_sorting.rs]: yeah, agreed.

File: datafusion/physical-optimizer/src/output_requirements.rs [hunk 2]
```diff
@@ -138,10 +138,36 @@ impl DisplayAs for OutputRequirementExec {
...
+                    }
+                } else {
+                    "[]".to_string()
+                };
+
+                write!(
+                    f,
+                    "OutputRequirementExec: order_by={}, dist_by={}",
+                    order_cols, self.dist_requirement
+                )
```
Comment (xudong963) [inline datafusion/physical-optimizer/src/output_requirements.rs]:
```suggestion
                let order_cols = self.order_requirement.as_ref()
                    .and_then(|reqs| reqs.into_alternatives().0.first())
                    .map(|lex| {
                        let pairs: Vec<String> = lex.iter()
                            .map(|req| {
                                let direction = req.options
                                    .as_ref()
                                    .map(|opt| if opt.descending { "desc" } else { "asc" })
                                    .unwrap_or("unspecified");
                                format!("({}, {direction})", req.expr)
                            })
                            .collect();
                        format!("[{}]", pairs.join(", "))
                    })
                    .unwrap_or_else(|| "[]".to_string());
            
                write!(
                    f,
                    "OutputRequirementExec: order_by={}, dist_by={}",
                    order_cols, self.dist_requirement
                )
```

**Review by xudong963 — APPROVED** [review]
thanks
