### PR TITLE
fix: coalesce schema issues

### LINKED ISSUE #12307: Coalesce fails for query: `SELECT COALESCE(null, 5)
### Describe the bug

This [issue](https://github.com/apache/datafusion-python/issues/534) was first reported in datafusion-python; upon further inspection, this appears to be a bug in datafusion itself.

### To Reproduce

This fails:

```rust
  async fn test_coalesce_schema() -> Result<()> {
      let ctx = SessionContext::new();

      let query = r#"SELECT COALESCE(null, 5)"#;

      let result = ctx.sql(query).await?;
      assert_logical_expr_schema_eq_physical_expr_schema(result).await?;
      Ok(())
  }
```

### Expected behavior

The code should not fail.

### Additional context

The problem seems to be in the `ScalarUDFImpl` for `CoalesceFunc`:

```rust
    fn return_type(&self, arg_types: &[DataType]) -> Result<DataType> {
        Ok(arg_types[0].clone())
    }

    // If all the element in coalesce is non-null, the result is non-null
    fn is_nullable(&self, args: &[Expr], schema: &dyn ExprSchema) -> bool {
        args.iter().any(|e| e.nullable(schema).ok().unwrap_or(true))
    }
```

The `return_type` is the first one when it should be the first non-null, and `is_nullable` returns true if any of the `args` is null

### PR DESCRIPTION
**Pull request by mesejo**
## Which issue does this PR close?
Closes #12307.

## Are these changes tested?
Yes

## Are there any user-facing changes?
No

### CODE REVIEW

File: datafusion/core/src/dataframe/mod.rs [hunk 1]
```diff
@@ -1803,6 +1803,17 @@ mod tests {
         Ok(())
     }
 
+    #[tokio::test]
+    async fn test_coalesce_schema() -> Result<()> {
+        let ctx = SessionContext::new();
+
+        let query = r#"SELECT COALESCE(null, 5)"#;
```
Comment (andygrove) [inline datafusion/core/src/dataframe/mod.rs:1810]: I tried a variation of this test and found another issue:

```
let query = r#"SELECT COALESCE(column1, column2) FROM VALUES (null, 1.2)"#;
```

failed with:

```
Left:  Schema { fields: [Field { name: "coalesce(column1,column2)", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata: {} }
Right: Schema { fields: [Field { name: "coalesce(column1,column2)", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} }], metadata: {} }
```

File: datafusion/functions/src/core/coalesce.rs [hunk 2]
```diff
@@ -60,12 +60,16 @@ impl ScalarUDFImpl for CoalesceFunc {
     }
 
     fn return_type(&self, arg_types: &[DataType]) -> Result<DataType> {
-        Ok(arg_types[0].clone())
+        Ok(arg_types
+            .iter()
+            .find_or_first(|d| !d.is_null())
+            .unwrap()
```
Comment (andygrove) [inline datafusion/functions/src/core/coalesce.rs:66]: I wonder if it is ever possible for this unwrap to panic? I could trigger it by explicitly calling `return_type(&[])` but perhaps this would never happen via SQL

File: datafusion/functions/src/core/coalesce.rs [hunk 3]
```diff
@@ -60,12 +60,16 @@ impl ScalarUDFImpl for CoalesceFunc {
...
+            .clone())
     }
 
-    // If all the element in coalesce is non-null, the result is non-null
+    // If all the elements in coalesce are non-null, the result is non-null
     fn is_nullable(&self, args: &[Expr], schema: &dyn ExprSchema) -> bool {
-        args.iter().any(|e| e.nullable(schema).ok().unwrap_or(true))
+        args.iter().all(|e| e.nullable(schema).ok().unwrap_or(true))
```
Comment (jayzhan211) [inline datafusion/functions/src/core/coalesce.rs:72]: I think the logic here is incorrect.

`e.nullable(schema)` is true if `nullable`, false if `non-null`.

Therefore, whenever we found at least one is `nullable`, we should returns `true`.

File: datafusion/functions/src/core/coalesce.rs (hunk 2 above)
Comment (jayzhan211) [reply datafusion/functions/src/core/coalesce.rs:66]: Only if the `arg_types` is empty, the unwrap panics. But the length check is handled in `coerce_types`, so it is safe to unwrap here.

File: datafusion/functions/src/core/coalesce.rs (hunk 3 above)
Comment (mesejo) [reply datafusion/functions/src/core/coalesce.rs:72]: But wouldn't a coalesce be `non-null` (`is_nullable` -> false) if at least one of the args is `non-null`?

Comment (jayzhan211) [reply datafusion/functions/src/core/coalesce.rs:72]: You are right, the comment should also be updated.

Comment (jayzhan211) [reply datafusion/functions/src/core/coalesce.rs:72]: Also, we should fix here too.

We should provide the coerced types to `return_type`

https://github.com/apache/datafusion/blob/f72622d6fcd27adac0bce5e87cccc83bad215448/datafusion/expr/src/expr_schema.rs#L153-L167

Comment (mesejo) [reply datafusion/functions/src/core/coalesce.rs:72]: Great! Where can I find an example of coercion of types?

File: datafusion/core/src/dataframe/mod.rs (hunk 1 above)
Comment (mesejo) [reply datafusion/core/src/dataframe/mod.rs:1810]: Thanks! I trace the source of this error to:
https://github.com/apache/datafusion/blob/6bbad7eda15cd1adcfb85182f6a20df6b5035842/datafusion/expr/src/logical_plan/builder.rs#L217
The choice of the DataType::Utf8 as a default value seems off, even more so when the only case for the `Option` to be `None` is if all the values were null.

I added this case as a test, as well as some others.

File: datafusion/functions/src/core/coalesce.rs (hunk 3 above)
Comment (jayzhan211) [reply datafusion/functions/src/core/coalesce.rs:72]: `coalesce(null, 5)` will coerced to i64. Therefore we have i64(None) and i64(5). Is this what you are asking for?

Comment (mesejo) [reply datafusion/functions/src/core/coalesce.rs:72]: Sorry, I was asking more about which function to use to coerce the types.
I see that in the `coerce_types` function, there is the following code:
```rust
if arg_types.is_empty() {
            return exec_err!("coalesce must have at least one argument");
        }
        let new_type = type_union_resolution(arg_types)
            .unwrap_or(arg_types.first().unwrap().clone());
``` 

Should I follow the same pattern?

Comment (mesejo) [reply datafusion/functions/src/core/coalesce.rs:72]: Sorry, but I'm not following. Are you suggesting that we change coerce `arg_data_types` and pass that result to:

```rust
 // perform additional function arguments validation (due to limited 
 // expressiveness of `TypeSignature`), then infer return type 
 Ok(func.return_type_from_exprs(args, schema, &arg_data_types)?) 
```

Comment (mesejo) [reply datafusion/functions/src/core/coalesce.rs:72]: Great! Thanks for the quick feedback!

Comment (mesejo) [reply datafusion/functions/src/core/coalesce.rs:72]: I pushed that change to the PR, but it caused some test failures, for example the statement:
```sql
SELECT encode(12, 'hex')
```

Doesn't produce the error:

> query error DataFusion error: Error during planning: The encode function can only accept utf8 or binary\.

The source seems to be this line in the function `coerced_from`:
https://github.com/apache/datafusion/blob/91b1d2bfe8f603df94e846b91d8475a0af2e5240/datafusion/expr/src/type_coercion/functions.rs#L681-L682

It specifies that any `DataType` can be coerced into a `Utf8`.

So, what is the best approach to move forward, @jayzhan211?

Comment (jayzhan211) [reply datafusion/functions/src/core/coalesce.rs:72]: We need to fix each function's signature

Comment (jayzhan211) [reply datafusion/functions/src/core/coalesce.rs:72]: https://github.com/mesejo/arrow-datafusion/pull/1/files

I try to fix the signature of encode to make sure the suggestion makes sense.
I think we might need to fix other functions as well

Comment (mesejo) [reply datafusion/functions/src/core/coalesce.rs:72]: I am having some sqllogictests fail in the CI ([link](https://github.com/mesejo/arrow-datafusion/actions/runs/10728724019/job/29753866598)), but executing:
```bash
cargo test --test sqllogictests
```  
Passes on my local machine. Have you experienced something similar? 

**Note:** The error message says that it only received a prefix of the actual message

Comment (jayzhan211) [reply datafusion/functions/src/core/coalesce.rs:72]: @mesejo  Try `cargo test --test sqllogictests` (slt files), `cargo test --lib --tests --bins --features avro,json` (rust test) and `./dev/rust_lint.sh` (clippy + fmt)

Comment (mesejo) [reply datafusion/functions/src/core/coalesce.rs:72]: @jayzhan211 Thanks for the tips! I updated the functions; this is ready for review.

File: datafusion/functions/src/datetime/to_local_time.rs [hunk 4]
```diff
@@ -348,6 +327,25 @@ impl ScalarUDFImpl for ToLocalTimeFunc {
...
+                arg_types.len()
+            )));
+        }
+
+        match &arg_types[0] {
+            Timestamp(Nanosecond, timezone) => Ok(vec![Timestamp(Nanosecond, timezone.clone())]),
+            Timestamp(Microsecond, timezone) => Ok(vec![Timestamp(Microsecond, timezone.clone())]),
+            Timestamp(Millisecond, timezone) => Ok(vec![Timestamp(Millisecond, timezone.clone())]),
+            Timestamp(Second, timezone) => Ok(vec![Timestamp(Second, timezone.clone())]),
+            _ => Err(DataFusionError::Execution(format!(
```
Comment (jayzhan211) [inline datafusion/functions/src/datetime/to_local_time.rs:344]: You could use `macro` like `exec_err`, `plan_err`

File: datafusion/sqllogictest/test_files/select.slt [hunk 5]
```diff
@@ -483,6 +483,17 @@ CREATE TABLE foo2(c1 double, c2 double) AS VALUES
 (2, 5),
 (3, 6);
 
+statement ok
+SELECT COALESCE(column1, column2) FROM VALUES (null, 1.2);
```
Comment (jayzhan211) [inline datafusion/sqllogictest/test_files/select.slt:487]: Maybe add `SELECT arrow_typeof(COALESCE(column1, column2)) FROM VALUES (null, 1.2);` to show that the final coerced type?

File: datafusion/sqllogictest/test_files/select.slt [hunk 6]
```diff
@@ -483,6 +483,17 @@ CREATE TABLE foo2(c1 double, c2 double) AS VALUES
...
+
+# multiple rows and columns with null need type coercion
+statement ok
+SELECT column1, column2, column3 FROM VALUES
```
Comment (jayzhan211) [inline datafusion/sqllogictest/test_files/select.slt:491]: We can try subquery to show the type

`select * from (select * from values (...))`

File: datafusion/functions/src/datetime/to_local_time.rs (hunk 4 above)
Comment (mesejo) [reply datafusion/functions/src/datetime/to_local_time.rs]: I tried to use the macros, but that caused the sqllogictest to fail. As, you can see in [here](https://github.com/mesejo/arrow-datafusion/actions/runs/10788101958/job/29918150107):

```
 External error: statement is expected to fail with error:
	(regex) DataFusion error: Error during planning: Execution error: User\-defined coercion failed with Plan\("The to_local_time function can only accept timestamp as the arg, got Utf8"\)
but got error:
	DataFusion error: Error during planning: Execution error: User-defined coercion failed with Plan("The to_local_time function can only accept timestamp as the arg, got Utf8
```
The messages match, but the error type, even though it has the same name, is different.

I could not figure out what was causing the macros to fail.

Comment (jayzhan211) [reply datafusion/functions/src/datetime/to_local_time.rs]: You could try to rewrite the error with `The to_local_time function can only accept timestamp as the arg. got Utf8`.

Comment (mesejo) [reply datafusion/functions/src/datetime/to_local_time.rs]: Thanks! Done using plan_err!

File: datafusion/sqllogictest/test_files/timestamps.slt [hunk 7]
```diff
@@ -2858,7 +2858,7 @@ statement error
 select to_local_time('2024-04-01T00:00:20Z'::timestamp, 'some string');
 
 # invalid argument data type
-statement error DataFusion error: Execution error: The to_local_time function can only accept timestamp as the arg, got Utf8
+statement error DataFusion error: Error during planning: Execution error: User\-defined coercion failed with Plan
```
Comment (jayzhan211) [inline datafusion/sqllogictest/test_files/timestamps.slt:2861]: I think it is better to have the reason of error `The to_local_time function can only accept timestamp as the arg, got Utf8`

**Review by jayzhan211 — APPROVED** [review]
Thanks @mesejo, I think overall looks good to me

File: datafusion/sqllogictest/test_files/timestamps.slt (hunk 7 above)
Comment (mesejo) [reply datafusion/sqllogictest/test_files/timestamps.slt]: Done!

File: datafusion/functions/src/encoding/inner.rs [hunk 8]
```diff
@@ -49,17 +48,8 @@ impl Default for EncodeFunc {
 
 impl EncodeFunc {
     pub fn new() -> Self {
-        use DataType::*;
         Self {
-            signature: Signature::one_of(
```
Comment (alamb) [inline datafusion/functions/src/encoding/inner.rs:54]: It seems to me that moving the signature from a data driven description (aka describe "what" is needed and letting some other code compute if the given arguments match that signature), this PR is moving many of the functions towards more functional (each function has to implement its own custom coercion, likely resulting in significant duplication).

What do you think (perhaps as a follow on PR) of adding `DataType::Null` support to the Signature calculations somehow rather than inlining / duplicating the coercion logic?

Maybe something like 
```
Signature::allow_null(..)
```
that would support automatically coercing arguments from null?

Or maybe we should always support coercing Null to any type

**Review by alamb — COMMENTED** [review]
Thanks @mesejo and @jayzhan211 

cc @findepi  who I believe is also working in this area / thinking about functions

File: datafusion/functions/src/encoding/inner.rs (hunk 8 above)
Comment (jayzhan211) [reply datafusion/functions/src/encoding/inner.rs:54]: Alternative signature like Signature::String, similar to Signature::numeric that includes converting null to string too?

Comment (alamb) [reply datafusion/functions/src/encoding/inner.rs:54]: I am not sure -- I was just reacting that this "handle null" pattern seems common and it seems like this approach will require custom coerce logic for all functions 🤔

Comment (findepi) [reply datafusion/functions/src/encoding/inner.rs:54]: Null to T coercion needs to be handled elsewhere anyway (eg when computing type of a UNION, etc.).
We can free functions from having to bother about coercions at all and let the engine calculate coercions when building the logical plan.

This is actually super fundamental for DataFusion vision as a composable query engine. Coercion rules are very implementation-specific. If we had functions spiced up with coercions inside them, that would make those functions non-reusable.

cc @wizardxz @sadboy

Comment (alamb) [reply datafusion/functions/src/encoding/inner.rs:54]: 100%

It seems to me like `Signature` is supposed to communicate what types the function implementation has a native implementation for and the coercion of whatever the user provided doesn't match one of the supported types

Comment (jayzhan211) [reply datafusion/functions/src/encoding/inner.rs:54]: @findepi Are you suggesting something like general coercion that is non-function specific? But what if we want different coercion rule for different function, we might need to do coercion function wise

Comment (findepi) [reply datafusion/functions/src/encoding/inner.rs:54]: Why would we want different coercion rules for different functions?

Comment (jayzhan211) [reply datafusion/functions/src/encoding/inner.rs:54]: My idea is that it is more flexible to the user, although, without the real use case, it might be a premature optimization 🤔.

Comment (mesejo) [reply datafusion/functions/src/encoding/inner.rs:54]: Sorry to chip in late; this PR addresses other issues, such as #12307. I wonder if I could split it and leave the changes regarding the coercion of functions in this one (to keep the discussion in one place) and the others in a new PR. Would that be ok?

File: datafusion/expr/src/expr_schema.rs [hunk 9]
```diff
@@ -150,21 +150,22 @@ impl ExprSchemable for Expr {
...
                 // verify that function is invoked with correct number and type of arguments as defined in `TypeSignature`
-                data_types_with_scalar_udf(&arg_data_types, func).map_err(|err| {
-                    plan_datafusion_err!(
-                        "{} {}",
-                        err,
-                        utils::generate_signature_error_msg(
-                            func.name(),
-                            func.signature().clone(),
-                            &arg_data_types,
+                let new_data_types = data_types_with_scalar_udf(&arg_data_types, func)
```
Comment (jayzhan211) [inline datafusion/expr/src/expr_schema.rs:153]: I think this is the root cause of the issue and to solve this other changes are necessary. Therefore, I think we should go with this change and maybe further optimize the coercion in another PR.

Comment (mesejo) [reply datafusion/expr/src/expr_schema.rs:153]: Ok, so should I leave it as it is? Or change it back to how it was:

```rust
data_types_with_scalar_udf(&arg_data_types, func)
```

Comment (jayzhan211) [reply datafusion/expr/src/expr_schema.rs:153]: I'm ok with the current change, maybe wait for @findepi @alamb for how to move on with this PR

Comment (alamb) [reply datafusion/expr/src/expr_schema.rs:153]: I defer to @jayzhan211  -- if he is good to merge this PR, let's get the conflicts resolved and merge it in.

If there is additional work we know is needed / could be cleaned up, let's try and file them as tickets

Comment (mesejo) [reply datafusion/expr/src/expr_schema.rs:154]: Conflicts solved! :smile:

**Comment by jayzhan211** [comment]
Thanks @mesejo and @alamb @findepi @andygrove for the review

File: datafusion/sqllogictest/test_files/scalar.slt [hunk 10]
```diff
@@ -1907,7 +1907,7 @@ select position('' in '')
 1
 
 
-query error DataFusion error: Execution error: The STRPOS/INSTR/POSITION function can only accept strings, but got Int64.
```
Comment (findepi) [inline datafusion/sqllogictest/test_files/scalar.slt:1910]: i agree in principle, but actually why didn't this work?

Looking at the code here, every function that accepts a string, should be invocable with a number or pretty much anything
https://github.com/apache/datafusion/blob/8db30e25d6fe65a9779d237cf48aea9aee297502/datafusion/expr/src/type_coercion/functions.rs#L681-L682

i am not convinced this is how it should be, but that's not the point here. My question is -- why this didn't work.

cc @alamb @jayzhan211

Comment (jayzhan211) [reply datafusion/sqllogictest/test_files/scalar.slt:1910]: `coerce_types` doesn't go to `coerce_from`. That is the reason

Comment (findepi) [reply datafusion/sqllogictest/test_files/scalar.slt:1910]: thanks, but not sure i understand.  It this explaining why the query fails before or after this PR?

Comment (mesejo) [reply datafusion/sqllogictest/test_files/scalar.slt:1910]: The query was already failing before this PR. The reason is in the function that computes the return type: 
```rust 
fn return_type(&self, arg_types: &[DataType]) -> Result<DataType> {
        utf8_to_int_type(&arg_types[0], "strpos/instr/position")
    }
``` 
The source of the error is in these lines:
https://github.com/apache/datafusion/blob/5740774acc9febb51fafb17235066c4c5ef2b32a/datafusion/functions/src/utils.rs#L57-L67

**Comment by alamb** [comment]
This PR appears to have introduced another regression found by @progval 
- https://github.com/apache/datafusion/issues/14055
