### PR TITLE
FIX : some benchmarks are failing

### LINKED ISSUE #15213: distinct_query_sql benchmark is failing
### Describe the bug

```
Benchmarking custom-measurement-time/distinct_group_by_u64_narrow_limit_10: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 40.0s. You may wish to increase target time to 43.4s, enable flat sampling, or reduce sample count to 60.
custom-measurement-time/distinct_group_by_u64_narrow_limit_10
                        time:   [8.4231 ms 8.4443 ms 8.4657 ms]
                        change: [-20.783% -17.184% -13.756%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) low mild
  3 (3.00%) high mild
custom-measurement-time/distinct_group_by_u64_narrow_limit_100
                        time:   [39.834 ms 40.002 ms 40.178 ms]
                        change: [-40.712% -35.158% -29.146%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) high mild
custom-measurement-time/distinct_group_by_u64_narrow_limit_1000
                        time:   [40.009 ms 40.269 ms 40.549 ms]
                        change: [-32.039% -28.795% -25.608%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
  8 (8.00%) high mild
  1 (1.00%) high severe
custom-measurement-time/distinct_group_by_u64_narrow_limit_10000
                        time:   [39.870 ms 40.048 ms 40.237 ms]
                        change: [-17.900% -13.292% -8.8751%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) high mild
custom-measurement-time/group_by_multiple_columns_limit_10
                        time:   [37.690 ms 37.762 ms 37.837 ms]
                        change: [-1.5462% -1.1394% -0.7797%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 5 outliers among 100 measurements (5.00%)
  5 (5.00%) high mild

Benchmarking distinct query with 100 partitions and 100000 samples per partition with limit 10: Warming up for 3.0000 s
thread 'tokio-runtime-worker' panicked at datafusion/physical-plan/src/repartition/mod.rs:618:22:
partition not used yet
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### To Reproduce

checkout main, run ` cargo bench -p datafusion --bench distinct_query_sql`

### Expected behavior

benchmark runs to completion

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by getChan**
## Which issue does this PR close?

- Closes #15213 .

## Rationale for this change

It is not certain, but it seems that plan creation and `collect()` should share the same runtime.. It is presumed that the issue occurred because RepartitionExec lazily polls within the runtime.
- https://github.com/apache/datafusion/blob/main/datafusion/physical-plan/src/repartition/mod.rs#L165-L177
- https://github.com/apache/datafusion/pull/10009

I will add more details if I find anything additional.

## What changes are included in this PR?
- Move the `Runtime::new()` into`bench_function`
- Ensure that plan creation (`ctx.sql()`) and `collect()` share the same runtime.

## Are these changes tested?
yes. below test are succeded
- `cargo bench -p datafusion --bench topk_aggregate`
- `cargo bench -p datafusion --bench distinct_query_sql`

## Are there any user-facing changes?
No.

### CODE REVIEW

File: datafusion/core/benches/distinct_query_sql.rs [hunk 1]
```diff
@@ -144,59 +141,50 @@ pub async fn create_context_sampled_data(
...
-            .await
-            .unwrap()
-    });
-
     c.bench_function(
         format!("distinct query with {} partitions and {} samples per partition with limit {}", partitions, samples, limit).as_str(),
-        |b| b.iter(|| run(distinct_trace_id_100_partitions_100_000_samples_limit_100.0.clone(),
-                                   distinct_trace_id_100_partitions_100_000_samples_limit_100.1.clone())),
+        |b| b.iter(|| {
+            let rt = Runtime::new().unwrap();
```
Comment (alamb) [inline datafusion/core/benches/distinct_query_sql.rs:152]: I think this means that the benchmark will include the time to create each tokio runtime (with a bunch of threads, etc)

To avoid this I think you can create the runtime once, and then use it for each tieration:

```rist
            let rt = Runtime::new().unwrap();
    c.bench_function(
        format!("distinct query with {} partitions and {} samples per partition with limit {}", partitions, samples, limit).as_str(),
        |b| b.iter(|| {
```

**Review by alamb — COMMENTED** [review]
Thanks for this @getChan

File: datafusion/core/benches/distinct_query_sql.rs (hunk 1 above)
Comment (getChan) [reply datafusion/core/benches/distinct_query_sql.rs]: Got it. Changed the runtime to be shared between loops.

However, it seems that other benchmark codes still have runtime creation within the iteration.

**Comment by 2010YOUY01** [comment]
Thank you for the fix! I noticed there are two other tests panicked on the same line of source code, is this fix still applicable?
1. Running sqllogictest with sqlite check: https://github.com/apache/datafusion/actions/runs/14152508679/job/39647603410
2. `custom_datasource` example: https://github.com/apache/datafusion/actions/runs/14152369014/job/39647355093

**Comment by getChan** [comment]
> Thank you for the fix! I noticed there are two other tests panicked on the same line of source code, is this fix still applicable?
> 
> 1. Running sqllogictest with sqlite check: https://github.com/apache/datafusion/actions/runs/14152508679/job/39647603410
> 2. `custom_datasource` example: https://github.com/apache/datafusion/actions/runs/14152369014/job/39647355093

@2010YOUY01 
This PR is to fix the bench test code. The `partition not used yet` error can occur depending on the execution environment of each test (it is not likely an error in repartitionExec). Therefore, this PR does not solve the issue you mentioned.

File: datafusion/core/benches/distinct_query_sql.rs (hunk 1 above)
Comment (Omega359) [reply datafusion/core/benches/distinct_query_sql.rs]: Filed as https://github.com/apache/datafusion/issues/15507

**Review by alamb — APPROVED** [review]
Thank you @getChan and @Omega359

**Comment by alamb** [comment]
Let's get this in and keep iterating on the benchmarks
