### PR TITLE
fix: avoid compressed json files repartitioning

### LINKED ISSUE #10435: "Unknown frame descriptor" for ZSTD data.
### Describe the bug

When reading a partition of big NDJSON files compressed with ZSTD there is an error appears. 
`Error: Custom { kind: Other, error: External(ArrowError(ExternalError(IoError(Custom { kind: Other, error: "Unknown frame descriptor" })), None)) }`
Meanwhile all files could be easily decompressed with ZSTD terminal utility.

### To Reproduce

Try to access big ZSTD files with multiple frames.

### Expected behavior

Would be good if it could read it. 

### Additional context

Same was fixed in [Hadoop](https://issues.apache.org/jira/browse/HDFS-14099)

### PR DESCRIPTION
**Pull request by korowa**
## Which issue does this PR close?

Closes #10435.

## Rationale for this change

Turning off repartitioning for compressed JSON files allows not to fail on reading such files.

## What changes are included in this PR?

Same as above

## Are these changes tested?

Test for reading gzipped JSON with forced repartitioning (controlled by settings), extended with other compression types.

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/core/src/datasource/physical_plan/json.rs [hunk 1]
```diff
@@ -154,7 +154,7 @@ impl ExecutionPlan for NdJsonExec {
         target_partitions: usize,
         config: &datafusion_common::config::ConfigOptions,
     ) -> Result<Option<Arc<dyn ExecutionPlan>>> {
-        if self.file_compression_type == FileCompressionType::GZIP {
+        if self.file_compression_type.is_compressed() {
```
Comment (alamb) [inline datafusion/core/src/datasource/physical_plan/json.rs:157]: This is the actual fix 🎉

**Review by alamb — APPROVED** [review]
Thank you @korowa  -- this looks great 🙏

**Comment by alamb** [comment]
Thanks again @korowa
