### PR TITLE
fix: correct statistics for `NestedLoopJoinExec`

### LINKED ISSUE #17679: Mismatch between Statistics and Schema in `NestedLoopJoinExec` if projection push down is enabled
### Describe the bug

Error is thrown inside `FilterExec`, if the direct child is a `NestedLoopJoinExec`, which has a mismatch between its statistics and schema
```
1. query failed: DataFusion error: ProjectionPushdown
caused by
Internal error: Could not create `ExprBoundaries`: in `try_from_column` `col_index`
                has gone out of bounds with a value of 2, the schema has 2 columns.
[SQL] select t1.t1_int from t1 left join (
    select * from t1 left join (
        select count(*) cnt ,t1_int from t1 left join t2 
            on t2.t2_int is not distinct from t1_int group by t1_int 
    ) temp on t1.t1_int is not distinct from temp.t1_int
) a on t1.t1_int=a.t1_int where a.cnt=0
---

```

### To Reproduce

```
statement ok
CREATE TABLE t1(t1_id INT, t1_name TEXT, t1_int INT) AS VALUES
(11, 'a', 1),
(22, 'b', 2),
(33, 'c', 3),
(44, 'd', 4);

statement ok
CREATE TABLE t2(t2_id INT, t2_name TEXT, t2_int INT) AS VALUES
(11, 'z', 3),
(22, 'y', 1),
(44, 'x', 3),
(55, 'w', 3);





query TT
explain with temp as (
 select count(*) cnt ,t1_int from t1 left join t2 
        on t2.t2_int is not distinct from t1_int group by t1_int 
)
select t1.t1_int from t1 left join (
    select * from t1 left join 
    temp on t1.t1_int is not distinct from temp.t1_int
) a on t1.t1_int=a.t1_int where a.cnt=0
---
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by duongcongtoai**
## Which issue does this PR close?

- Closes #17679.
- Fix a lot of test cases in https://github.com/apache/datafusion/pull/17110

### CODE REVIEW

File: datafusion/physical-plan/src/joins/nested_loop_join.rs [hunk 1]
```diff
@@ -564,7 +564,7 @@ impl ExecutionPlan for NestedLoopJoinExec {
             self.right.partition_statistics(None)?,
             vec![],
             &self.join_type,
-            &self.join_schema,
```
Comment (2010YOUY01) [inline datafusion/physical-plan/src/joins/nested_loop_join.rs:567]: It would be great to update the comment in `self.join_schema` to clarify that it's the concatenated schema of left and right child, without applying the projection

**Review by 2010YOUY01 — APPROVED** [review]
Thank you for the fix!

File: datafusion/physical-plan/src/joins/nested_loop_join.rs (hunk 1 above)
Comment (duongcongtoai) [reply datafusion/physical-plan/src/joins/nested_loop_join.rs:567]: updated
