### PR TITLE
Make `CREATE EXTERNAL TABLE` format options consistent, remove special syntax for `HEADER ROW`, `DELIMITER` and `COMPRESSION` 

### LINKED ISSUE #9945: Overwritten Format Configs by CreateExternalTable Options
### Describe the bug

https://github.com/apache/datafusion/blob/4bd7c137e0e205140e273a7c25824c94b457c660/datafusion/core/src/datasource/listing_table_factory.rs#L67-L73

These lines of `ListingTableFactory.create()` overwrites the config options by cmd (CreateExternalTable options). Configs coming from `OPTIONS('format...` are discarded silently.

### To Reproduce

```
statement ok
CREATE EXTERNAL TABLE aggregate_simple (
  c1 FLOAT NOT NULL,
  c2 DOUBLE NOT NULL,
  c3 BOOLEAN NOT NULL
)
STORED AS CSV
LOCATION '../core/tests/data/aggregate_simple.csv'
WITH HEADER ROW

query RRB
SELECT * FROM aggregate_simple LIMIT 3;
----
```
works as expected, but

```
statement ok
CREATE EXTERNAL TABLE aggregate_simple (
  c1 FLOAT NOT NULL,
  c2 DOUBLE NOT NULL,
  c3 BOOLEAN NOT NULL
)
STORED AS CSV
LOCATION '../core/tests/data/aggregate_simple.csv'
OPTIONS('format.has_header' 'true')

query RRB
SELECT * FROM aggregate_simple LIMIT 3;
----
```

does not, since `CREATE EXTERNAL TABLE` does not have `WITH HEADER ROW`, which overwrites `csv.has_header` to `false`.

### Expected behavior

The actual problem is that we can set the same settings by 2 different commands now, and one of them is silently chosen. Their default values are also different (CreateExternalTable's false, CsvOptions' true). We can set both of them as false initially. Then if one of them is true, then we expect a header. If `WITH HEADER ROW` exists and `'format.has_header' 'false'`, we can give an error.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by berkaysynnada**
## Which issue does this PR close?

Closes #9945.
Closes https://github.com/apache/datafusion/issues/10414

## Rationale for this change

https://github.com/apache/datafusion/blob/4bd7c137e0e205140e273a7c25824c94b457c660/datafusion/core/src/datasource/listing_table_factory.rs#L67-L73

These lines of `ListingTableFactory.create()` overwrites the config options by `cmd` (CreateExternalTable options). Configs coming from `OPTIONS('format...` are discarded silently.

```
statement ok
CREATE EXTERNAL TABLE aggregate_simple (
  c1 FLOAT NOT NULL,
  c2 DOUBLE NOT NULL,
  c3 BOOLEAN NOT NULL
)
STORED AS CSV
LOCATION '../core/tests/data/aggregate_simple.csv'
WITH HEADER ROW

query RRB
SELECT * FROM aggregate_simple LIMIT 3;
----
```
works as expected, but

```
statement ok
CREATE EXTERNAL TABLE aggregate_simple (
  c1 FLOAT NOT NULL,
  c2 DOUBLE NOT NULL,
  c3 BOOLEAN NOT NULL
)
STORED AS CSV
LOCATION '../core/tests/data/aggregate_simple.csv'
OPTIONS('format.has_header' 'true')

query RRB
SELECT * FROM aggregate_simple LIMIT 3;
----
```

does not, since `CREATE EXTERNAL TABLE` does not have `WITH HEADER ROW`, which overwrites `csv.has_header` to `false`.

**To summarize:**
`CreateExternalTable` has 3 format specific fields:
1) `has_header`
2) `delimiter`
3) `file_compression_type`
After https://github.com/apache/datafusion/pull/9382, `CreateExternalTable.options` does store these format specific configurations. 

## What changes are included in this PR?

`CreateExternalTable.delimiter` and `CreateExternalTable.file_compression_type` are removed, and they are needed to be given from options, such as 
```
OPTIONS(
    'format.delimiter' ',',
    'format.compression' 'gzip')
```

~For the `has_header` config, as @alamb https://github.com/apache/datafusion/issues/9945#issuecomment-2056552026 suggests, we can sustain its usage as `WITH HEADER ROW` from CreateExternalTable's scope. I refactor the code such that~

_(WITH HEADER ROW) + (format.has_header = true) => OK with header
(WITH HEADER ROW) + (format.has_header = false) => Error
(WITH HEADER ROW) + (format.has_header = not specified) => OK with header
() + (format.has_header = true) => OK with header
() + (format.has_header = false) => Ok without header
() + (format.has_header = not_specified) => Ok without header_

~However in the long term, I think removing also `WITH HEADER ROW` option will be a better design and help having more clear UX.~

WITH HEADER ROW is also removed to OPTIONS tab.

## Are these changes tested?

Yes.

## Are there any user-facing changes?

Users access format specific configurations (delimiter and compression type) via `OPTIONS()` command.

### CODE REVIEW

**Review by ozankabak — APPROVED** [review]
Thank you for this clean-up PR @berkaysynnada. This almost closes the loop on getting us to a consistent API w.r.t. I/O option handling (e.g. format options). With this PR, the only "weird" thing remaining in the API will be the `WITH HEADER ROW` top-level specifier (which it shouldn't be, as it is a format-specific option (CSV)).

We organized this PR to keep `WITH HEADER ROW` for now and gave it consistent semantics w.r.t. its interaction with `format` options. Maybe can add a deprecation warning in a follow-on PR and remove it entirely in the future.

@alamb, it'd be great if you can take a look as we discussed this before. Thanks

File: datafusion/common/src/config.rs [hunk 1]
```diff
@@ -1564,7 +1564,7 @@ config_namespace_with_hashmap! {
 config_namespace! {
     /// Options controlling CSV format
     pub struct CsvOptions {
-        pub has_header: bool, default = true
+        pub has_header: Option<bool>, default = None
```
Comment (alamb) [inline datafusion/common/src/config.rs:1567]: 👍

Comment (alamb) [reply datafusion/common/src/config.rs:1567]: I think it would help to explain why this is an `Option` which is different than the other options. Something like

```suggestion
        /// If the first line of the CSV is column names. 
        /// If not specified, uses default from `CREATE TABLE` command, if any. 
        pub has_header: Option<bool>, default = None
```

File: datafusion/common/src/config.rs [hunk 2]
```diff
@@ -1600,13 +1600,13 @@ impl CsvOptions {
     /// Set true to indicate that the first line is a header.
     /// - default to true
     pub fn with_has_header(mut self, has_header: bool) -> Self {
-        self.has_header = has_header;
+        self.has_header = Some(has_header);
         self
     }
 
     /// True if the first line is a header.
     pub fn has_header(&self) -> bool {
```
Comment (alamb) [inline datafusion/common/src/config.rs:1608]: I wonder if it would be clearer to change this to to return `Option<bool>` to mirror the underlying struct 🤔

File: datafusion/core/src/datasource/file_format/csv.rs [hunk 3]
```diff
@@ -136,13 +136,13 @@ impl CsvFormat {
     /// Set true to indicate that the first line is a header.
     /// - default to true
     pub fn with_has_header(mut self, has_header: bool) -> Self {
-        self.options.has_header = has_header;
+        self.options.has_header = Some(has_header);
         self
     }
 
     /// True if the first line is a header.
     pub fn has_header(&self) -> bool {
```
Comment (alamb) [inline datafusion/core/src/datasource/file_format/csv.rs:144]: Likewise here, I wonder if returning `Option<bool>` would be less confusing

File: datafusion/core/src/datasource/file_format/csv.rs [hunk 4]
```diff
@@ -236,13 +236,15 @@ impl FileFormat for CsvFormat {
...
+        state: &SessionState,
         conf: FileScanConfig,
         _filters: Option<&Arc<dyn PhysicalExpr>>,
     ) -> Result<Arc<dyn ExecutionPlan>> {
         let exec = CsvExec::new(
             conf,
-            self.options.has_header,
+            self.options
+                .has_header
+                .unwrap_or(state.config().options().catalog.has_header),
```
Comment (alamb) [inline datafusion/core/src/datasource/file_format/csv.rs:247]: It took me a while to understand why this is reading from `catalog.has_header` (which is different than `format.has_header`). I think it is because catalog.has_header is the default value that is used when has_header has not been explicitly specified for the table.

If so this make sense - but maybe it is worth a comment on `catalog.has_header` explaining this (I can make a follow on PR too)

File: datafusion/core/src/datasource/file_format/csv.rs [hunk 5]
```diff
@@ -298,7 +301,12 @@ impl CsvFormat {
 
         while let Some(chunk) = stream.next().await.transpose()? {
             let format = arrow::csv::reader::Format::default()
-                .with_header(self.options.has_header && first_chunk)
+                .with_header(
+                    self.options
+                        .has_header
+                        .unwrap_or(state.config_options().catalog.has_header)
+                        && first_chunk,
```
Comment (alamb) [inline datafusion/core/src/datasource/file_format/csv.rs:308]: It might be possible to avoid some redundant code (and also document the behavior) by pulling this into a function like

```rust
impl CsvFormat { 
..
  /// returns true if the first line should be treated like a header
  /// if not explicitly specified by the `CREATE TABLE` statement or format options
  /// defaults to the default `catalog.has_header` value
  fn has_header(&self) -> bool {
    self.options
      .has_header
      .unwrap_or(state.config_options().catalog.has_header)
  }
..
}
```

File: datafusion/core/src/datasource/file_format/csv.rs [hunk 6]
```diff
@@ -803,9 +819,11 @@ mod tests {
         file_name: &str,
         projection: Option<Vec<usize>>,
         limit: Option<usize>,
+        hash_header: bool,
```
Comment (alamb) [inline datafusion/core/src/datasource/file_format/csv.rs:822]: possibly a typo

```suggestion
        has_header: bool,
```

File: datafusion/core/src/datasource/listing_table_factory.rs [hunk 7]
```diff
@@ -67,9 +67,13 @@ impl TableProviderFactory for ListingTableFactory {
         let file_format: Arc<dyn FileFormat> = match file_type {
             FileType::CSV => {
                 let mut csv_options = table_options.csv;
-                csv_options.has_header = cmd.has_header;
-                csv_options.delimiter = cmd.delimiter as u8;
-                csv_options.compression = cmd.file_compression_type;
+                if let Some(has_header) = csv_options.has_header {
+                    if cmd.has_header && !has_header {
+                        return plan_err!("Conflicting header options for CSV file");
```
Comment (alamb) [inline datafusion/core/src/datasource/listing_table_factory.rs:72]: Nice!

Can you please add a test for this error? Perhaps using the example from https://github.com/apache/datafusion/issues/9945 ?

File: datafusion/sql/src/parser.rs [hunk 8]
```diff
@@ -1009,34 +996,33 @@ mod tests {
...
-            file_compression_type: UNCOMPRESSED,
             unbounded: false,
             options: HashMap::new(),
             constraints: vec![],
         });
         expect_parse_ok(sql, expected)?;
 
         // positive case with delimiter
-        let sql = "CREATE EXTERNAL TABLE t(c1 int) STORED AS CSV DELIMITER '|' LOCATION 'foo.csv'";
+        let sql = "CREATE EXTERNAL TABLE t(c1 int) STORED AS CSV LOCATION 'foo.csv' OPTIONS ('format.delimiter' '|')";
```
Comment (alamb) [inline datafusion/sql/src/parser.rs:1010]: Is it required to removing the existing syntax support for `DELIMTER` and `COMPRESSION` -- I think other users will see that as a regression. 

It seems like it would be possible to apply the same type of logic for `has_header` to these other options to prevent conflicts and silent igores

**Review by alamb — COMMENTED** [review]
Thank you @berkaysynnada and @ozankabak 

This PR looks great to me other than removing support for `DELIMTER` and `COMRESSION` in the `CREATE EXTERNAL TABLE`  syntax (and I almost missed that change when skimming this PR initially)


What I suggest is:
1. Update this PR to just fix the has_header bug in https://github.com/apache/datafusion/issues/9945
2. Start a new discussion / ticket about removing  / deprecating the `WITH HEADER ROW` / `COMPRESSION`, `DELIMITER` syntax support. 

> However in the long term, I think removing also WITH HEADER ROW option will be a better design and help having more clear UX.

I don't really have a strong preference myself, but given how long the other syntax has been around I think other people might have

**Comment by ozankabak** [comment]
Thanks for taking a look. Do you suggest having a similar mechanism for `DELIMITER` and `COMPRESSION` like we did for `WITH HEADER ROW`? We can do that, but it will increase code complexity and we will need maintain that code until we finally remove them to arrive at the consistent syntax we aim.

I fear the longer we support the current syntax, the harder it will be to fix it. We may end up being stuck with CSV-related options living at the top level.

> Start a new discussion / ticket about removing / deprecating the WITH HEADER ROW / COMPRESSION, DELIMITER syntax support.

Makes sense, let's do this

**Comment by alamb** [comment]
> Thanks for taking a look. Do you suggest having a similar mechanism for DELIMITER and COMPRESSION like we did for WITH HEADER ROW? 

Yes, that is my suggestion

> We can do that, but it will increase code complexity and we will need maintain that code until we finally remove them to arrive at the consistent syntax we aim.

I agree it will make the code more complex

> I fear the longer we support the current syntax, the harder it will be to fix it. We may end up being stuck with CSV-related options living at the top level.

I agree -- I will file a follow on ticket discuss removing the options

**Comment by alamb** [comment]
> I agree -- I will file a follow on ticket discuss removing the options

Filed https://github.com/apache/datafusion/issues/10414 to discus removing these options

File: datafusion/sqllogictest/test_files/parquet.slt [hunk 9]
```diff
@@ -66,7 +66,6 @@ CREATE EXTERNAL TABLE test_table (
   date_col DATE
 )
 STORED AS PARQUET
-WITH HEADER ROW
```
Comment (berkaysynnada) [inline datafusion/sqllogictest/test_files/parquet.slt:69]: No need to specify header rows for parquet

**Comment by berkaysynnada** [comment]
This PR is now ready for review. By employing that [method](https://github.com/apache/datafusion/issues/10414#issuecomment-2099555237), users can choose to maintain the existing behavior if desired.

File: datafusion/sqllogictest/test_files/create_external_table.slt [hunk 10]
```diff
@@ -68,18 +60,6 @@ CREATE EXTERNAL TABLE t STORED AS CSV STORED AS PARQUET LOCATION 'foo.parquet'
 statement error DataFusion error: SQL error: ParserError\("LOCATION specified more than once"\)
 CREATE EXTERNAL TABLE t STORED AS CSV LOCATION 'foo.csv' LOCATION 'bar.csv'
 
-# Duplicate `WITH HEADER ROW` clause
```
Comment (berkaysynnada) [inline datafusion/sqllogictest/test_files/create_external_table.slt:71]: Not applicable anymore

File: datafusion/sqllogictest/test_files/create_external_table.slt [hunk 11]
```diff
@@ -52,14 +52,6 @@ CREATE EXTERNAL TABLE t STORED AS CSV WITH HEADER LOCATION 'abc'
 statement error DataFusion error: SQL error: ParserError\("Expected BY, found: LOCATION"\)
 CREATE EXTERNAL TABLE t STORED AS CSV PARTITIONED LOCATION 'abc'
 
-# Missing `TYPE` in COMPRESSION clause
```
Comment (berkaysynnada) [inline datafusion/sqllogictest/test_files/create_external_table.slt:55]: Not applicable anymore

File: datafusion/sql/src/parser.rs [hunk 12]
```diff
@@ -1048,66 +959,41 @@ mod tests {
...
             if_not_exists: false,
-            file_compression_type: UNCOMPRESSED,
             unbounded: false,
-            options: HashMap::new(),
+            options: vec![],
             constraints: vec![],
         });
         expect_parse_ok(sql, expected)?;
 
-        // positive case: it is ok for case insensitive sql stmt with `WITH HEADER ROW` tokens
```
Comment (berkaysynnada) [inline datafusion/sql/src/parser.rs:1064]: Not applicable

**Review by ozankabak — APPROVED** [review]
I did one more round of review and it looks good to me. Seems like @berkaysynnada threw in a minor improvement of being able to use non-quoted strings in the `OPTIONS` clause as well, which is great. Creating warnings when `WITH HEADER ROW` is used and directing users to the `OPTIONS` clause is also great. Great work @berkaysynnada 🚀 

@alamb, feel free to merge once you take a look and all looks good.

**Comment by alamb** [comment]
I plan to review this again later today. Thanks @berkaysynnada and @ozankabak

File: docs/source/user-guide/sql/ddl.md [hunk 13]
```diff
@@ -60,9 +60,6 @@ CREATE [UNBOUNDED] EXTERNAL TABLE
 [ IF NOT EXISTS ]
 <TABLE_NAME>[ (<column_definition>) ]
 STORED AS <file_type>
-[ WITH HEADER ROW ]
```
Comment (alamb) [inline docs/source/user-guide/sql/ddl.md:63]: 👍

File: datafusion/core/src/datasource/file_format/csv.rs [hunk 14]
```diff
@@ -716,6 +733,10 @@ mod tests {
     async fn query_compress_data(
         file_compression_type: FileCompressionType,
     ) -> Result<()> {
+        let runtime = Arc::new(RuntimeEnv::new(RuntimeConfig::new()).unwrap());
+        let cfg = SessionConfig::new().set_str("datafusion.catalog.has_header", "true");
+        let session_state = SessionState::new_with_config_rt(cfg, runtime);
```
Comment (alamb) [inline datafusion/core/src/datasource/file_format/csv.rs:738]: I think you can write this like this for extra compile time checking (maybe for some other PR)

```rust
        let mut cfg = SessionConfig::new();
        cfg.options_mut().catalog.has_header = true;
        let session_state = SessionState::new_with_config_rt(cfg, runtime);
```

File: datafusion/core/src/datasource/stream.rs [hunk 15]
```diff
@@ -58,12 +58,22 @@ impl TableProviderFactory for StreamTableFactory {
...
         let encoding = cmd.file_type.parse()?;
+        let header = if let Ok(opt) = cmd
+            .options
+            .get("format.has_header")
+            .map(|has_header| bool::from_str(has_header))
+            .transpose()
+        {
+            opt.unwrap_or(false)
+        } else {
+            return config_err!("format.has_header can either be true or false");
```
Comment (alamb) [inline datafusion/core/src/datasource/stream.rs:69]: I am not quite sure what this error message means. Does it mean  that there are inconsistent settings somehow? Perhaps we could improve the text to give some hint about how the user can fix whatever the problem is 🤔

File: datafusion/sql/src/statement.rs [hunk 16]
```diff
@@ -985,8 +981,52 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
         let inline_constraints = calc_inline_constraints_from_columns(&columns);
         all_constraints.extend(inline_constraints);
 
+        let mut options_map = HashMap::<String, String>::new();
+        for (key, value) in options {
+            if options_map.contains_key(&key) {
+                return plan_err!("Option {key} is specified multiple times");
```
Comment (alamb) [inline datafusion/sql/src/statement.rs:987]: Can we please add a negative test in .slt for this case (it is a good one)

File: datafusion/sql/src/parser.rs [hunk 17]
```diff
@@ -734,22 +712,15 @@ impl<'a> DFParser<'a> {
                         } else {
                             self.parser.expect_keyword(Keyword::HEADER)?;
                             self.parser.expect_keyword(Keyword::ROW)?;
-                            ensure_not_set(&builder.has_header, "WITH HEADER ROW")?;
-                            builder.has_header = Some(true);
+                            return parser_err!("WITH HEADER ROW clause is no longer in use. Please use the OPTIONS clause with 'format.has_header' set appropriately, e.g., OPTIONS ('format.has_header' 'true')");
```
Comment (alamb) [inline datafusion/sql/src/parser.rs:715]: ❤️

File: datafusion/sql/src/statement.rs [hunk 18]
```diff
@@ -985,8 +981,52 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
...
+                | Value::Placeholder(_) => {
+                    return plan_err!(
+                        "Unsupported Value in CREATE EXTERNAL TABLE statement {}",
+                        value
+                    );
+                }
+            };
+
+            if !(&key.contains('.')) {
+                // If a config does not belong to any namespace, we assume it is
```
Comment (alamb) [inline datafusion/sql/src/statement.rs:1012]: I am not sure this commet applies to CREATE EXTERNAL TABLE which didn't have format options previously

Can you also please make sure there is test for this alternate syntax (aka `OPTIONS ('has_header' 'true')");` instead of `OPTIONS ('format.has_header' 'true')");` (I may have missed it)

File: docs/source/user-guide/cli/datasources.md [hunk 19]
```diff
@@ -166,8 +166,8 @@ Register a single file csv datasource with a header row.
 ```sql
 CREATE EXTERNAL TABLE test
 STORED AS CSV
-WITH HEADER ROW
-LOCATION '/path/to/aggregate_test_100.csv';
+LOCATION '/path/to/aggregate_test_100.csv'
+OPTIONS ('format.has_header' 'true');
```
Comment (alamb) [inline docs/source/user-guide/cli/datasources.md:170]: I wonder if we can show the slightly nicer syntax here (and elsewhere in the intro docs) 

```suggestion
LOCATION '/path/to/aggregate_test_100.csv'
OPTIONS ('has_header' 'true');
```

**Review by alamb — APPROVED** [review]
Thank you @berkaysynnada  and @ozankabak -- i looked over this PR and I think the code looks really nice 👏 

From my perspective this PR also now implements the consensus from https://github.com/apache/datafusion/issues/10414 and everyone seems happy with the overall increase in consistency (and there is a [workaround](https://github.com/apache/datafusion/issues/10414#issuecomment-2099555237) for anyone who needs the old special syntax -- kudos to @phillipleblanc  🙏 ). 

Something else I noticed while reviewing this PR is that the available options (e.g. `format.has_header`, `format.delimiter`, etc do not appear to be documented anywhere -- I filed https://github.com/apache/datafusion/issues/10451 to track that

**Comment by alamb** [comment]
I also updated this PR's title to reflect the user visible changes and added the `api-change` label

**Comment by ozankabak** [comment]
Thank you. We will address your review feedback and then merge afterwards. 🚀

File: datafusion/core/src/datasource/stream.rs (hunk 15 above)
Comment (berkaysynnada) [reply datafusion/core/src/datasource/stream.rs:69]: An error occurs here if the user would set such an option: ('format.has_header' 'x') where x is anything other than 'true' or 'false'. I'd like to emphasize that. But as you said, the message may direct the user as if a conflicting options are set. Thanks for the feedback, I am updating it now.

**Comment by alamb** [comment]
Thanks again for this work  @berkaysynnada  and the guidance @ozankabak

**Comment by Blizzara** [comment]
Hey, this changed the behavior of writing and reading CSVs to be slightly inconsistent: now writing defaults to **not** writing a header, while reading defaults to **having** a header. Previously both defaulted to **having** a header, ie. the write side has flipped.

I noticed as our test started failing - a simplified version below, the following worked previously, after this commit it fails:
```
#[tokio::test]
async fn write_then_read_csv() -> Result<()> {
    let test_path = test_file_path("csv/");

    let ctx = SessionContext::new();

    let df = ctx.sql("SELECT 1 AS col").await?;
    assert_eq!(df.to_owned().count().await?, 1);
    df.write_csv(&test_path, DataFrameWriteOptions::default(), None).await?;

    let df = ctx.read_csv(&test_path, CsvReadOptions::default()).await?;
    assert_eq!(df.count().await?, 1);

    Ok(())
}
```

but can be fixed by adding `Some(CsvOptions::default().with_has_header(true))` to the write_csv (restoring old behavior), or alternatively changing read_csv to have `CsvReadOptions::default().has_header(false)` to make it match the write.

Doesn't really matter to me how it works, though I find the mismatch somewhat surprising - but mainly I just wanted to flag this in case this was not expected/intentional change.

**Comment by berkaysynnada** [comment]
> Doesn't really matter to me how it works, though I find the mismatch somewhat surprising - but mainly I just wanted to flag this in case this was not expected/intentional change.

Thanks for reporting that. It's surprising that this issue hasn't emerged before. `CatalogOptions`'s has_header value was false as default from the beginning, which is the write options in that case. However, reader's is true:
https://github.com/apache/datafusion/blob/09dde27be39ad054f85dfb5c37b7468a3f68d652/datafusion/core/src/datasource/file_format/options.rs#L90

I believe we should also set it as false while creating it.
