### PR TITLE
fix: Substrait serializer clippy error: not calling truncate

### LINKED ISSUE #9727: Substrait serializer clippy error: not calling `truncate`
As part of https://github.com/apache/arrow-datafusion/pull/9725 we had to disable a newly added clippy lint to get CI to pass

However it looks like the clippy lint is flagging a potential real issue

              @waynexia please check this

I suppressed the warning but clippy requires `.truncate` to be called before file creation

```
  --> datafusion/substrait/src/serializer.rs:32:39
   |
32 |     let mut file = OpenOptions::new().create(true).write(true).open(path)?;
   |                                       ^^^^^^^^^^^^- help: add: `.truncate(true)`
   |
   = help: if you intend to overwrite an existing file entirely, call `.truncate(true)`
   = help: if you instead know that you may want to keep some parts of the old file, call `.truncate(false)`
   = help: alternatively, use `.append(true)` to append to the file instead of overwriting it
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#suspicious_open_options
   = note: `-D clippy::suspicious-open-options` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::suspicious_open_options)]`
```

_Originally posted by @comphead in https://github.com/apache/arrow-datafusion/pull/9725#discussion_r1534174055_

### PR DESCRIPTION
**Pull request by niebayes**
## Which issue does this PR close?

- Closes #9727 

## Rationale for this change

It's reasonable to always truncate an existing file before serializing a plan. 
On the other hand, the following `deserialize` method always read the file to end which does not consider the case that the file is not truncated before serialization.

## What changes are included in this PR?

Applied a clippy suggestion by adding a `truncate(true)`.

## Are these changes tested?

Tested by clippy

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/substrait/src/serializer.rs [hunk 1]
```diff
@@ -27,10 +27,13 @@ use substrait::proto::Plan;
...
 use std::io::{Read, Write};
 
-#[allow(clippy::suspicious_open_options)]
 pub async fn serialize(sql: &str, ctx: &SessionContext, path: &str) -> Result<()> {
     let protobuf_out = serialize_bytes(sql, ctx).await;
-    let mut file = OpenOptions::new().create(true).write(true).open(path)?;
+    let mut file = OpenOptions::new()
+        .create(true)
+        .write(true)
+        .truncate(true)
```
Comment (alamb) [inline datafusion/substrait/src/serializer.rs:35]: An alternate, potentially less confusing behavior, would be to return an error if the file existed, so the user could decide if they meant to overwrite the contents or not

In any event, I think it would be very helpful if you could also add comments to the function explaining what it does (and including the fact it truncates the file).

**Review by alamb — APPROVED** [review]
Thank you @niebayes  -- I think this is an improvment, but it would be better if:
1. Return an error of the file already exists
2. Added doccomments comments to `serialize`

File: datafusion/substrait/src/serializer.rs (hunk 1 above)
Comment (mbrobbel) [reply datafusion/substrait/src/serializer.rs:35]: If this is going to change the signature (to return a `Result`), maybe we can also change the `path` arg to `impl AsRef<Path>`?

Comment (niebayes) [reply datafusion/substrait/src/serializer.rs:35]: @mbrobbel sounds good.

Comment (niebayes) [reply datafusion/substrait/src/serializer.rs:35]: @alamb I would suggest return an error if the file exists and is not empty.

File: datafusion/substrait/src/serializer.rs [hunk 2]
```diff
@@ -50,6 +72,7 @@ pub async fn serialize_bytes(sql: &str, ctx: &SessionContext) -> Result<Vec<u8>>
     Ok(protobuf_out)
 }
 
+/// Reads the file at `path` and deserializes a plan from the bytes.
 pub async fn deserialize(path: &str) -> Result<Box<Plan>> {
```
Comment (mbrobbel) [inline datafusion/substrait/src/serializer.rs:76]:
```suggestion
/// Reads the file at `path` and deserializes a plan from the bytes.
pub async fn deserialize(path: impl AsRef<Path>) -> Result<Box<Plan>> {
```

File: datafusion/substrait/src/serializer.rs [hunk 3]
```diff
@@ -26,9 +26,30 @@ use substrait::proto::Plan;
...
+    sql: &str,
+    ctx: &SessionContext,
+    path: impl AsRef<Path>,
+) -> Result<()> {
     let protobuf_out = serialize_bytes(sql, ctx).await;
+
+    match std::fs::metadata(path.as_ref()) {
+        Ok(meta) if meta.len() > 0 => {
+            return Err(DataFusionError::Substrait(format!(
+                "Failed to encode substrait plan: the file {} already exists and is not empty",
```
Comment (mbrobbel) [inline datafusion/substrait/src/serializer.rs:45]: You could remove `substrait` here because it's already part of the error prefix https://github.com/apache/datafusion/blob/19fe44cf2f30cbdd63d4a4f52c74055163c6cc38/datafusion/common/src/error.rs#L517
```suggestion
                "Failed to encode plan: the file {} already exists and is not empty", 
```

File: datafusion/substrait/src/serializer.rs [hunk 4]
```diff
@@ -26,9 +26,30 @@ use substrait::proto::Plan;
...
+    match std::fs::metadata(path.as_ref()) {
+        Ok(meta) if meta.len() > 0 => {
+            return Err(DataFusionError::Substrait(format!(
+                "Failed to encode substrait plan: the file {} already exists and is not empty", 
+                path.as_ref().display())
+            ));
+        }
+        // Ignores other cases.
+        _ => {}
+    }
```
Comment (mbrobbel) [inline datafusion/substrait/src/serializer.rs:51]:
```suggestion
    if std::fs::metadata(path.as_ref()).is_ok_and(|meta| meta.len() > 0) {
        return Err(DataFusionError::Substrait(format!(
            "Failed to encode substrait plan: the file {} already exists and is not empty", 
            path.as_ref().display())
        ));
    }
```

**Review by alamb — APPROVED** [review]
Thank you @niebayes and @mbrobbel  -- looks great to me

I think @mbrobbel 's recent comments and suggestions are worth considering too as they would improve the code substantially, but we can also do it as a follow on PR too

File: datafusion/substrait/src/serializer.rs (hunk 3 above)
Comment (niebayes) [reply datafusion/substrait/src/serializer.rs]: Adding a `substrait` is because there already had an error message "Failed to encode substrait plan" in the fuction `serialize_bytes`. I was following that error message to make error messages consistent.

Comment (niebayes) [reply datafusion/substrait/src/serializer.rs]: Removed the word "substrait" from all error messages.

**Comment by niebayes** [comment]
@alamb Applied suggestions from @mbrobbel. Please check it.

File: datafusion/substrait/src/serializer.rs [hunk 5]
```diff
@@ -26,28 +26,50 @@ use substrait::proto::Plan;
...
+            "Failed to encode plan: the file {} already exists and is not empty",
+            path.as_ref().display()
+        )));
+    }
+
+    let mut file = OpenOptions::new()
+        .create(true)
+        .write(true)
+        .truncate(true)
+        .open(path)?;
```
Comment (mbrobbel) [inline datafusion/substrait/src/serializer.rs:53]: Looking at this again; we can further simply this with [OpenOptions::create_new](https://doc.rust-lang.org/stable/std/fs/struct.OpenOptions.html#method.create_new).

```suggestion
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)?;
```

This means we also get an error if the file is empty, however this check is atomic, and the existing code is not (the empty check and the open).

Comment (niebayes) [reply datafusion/substrait/src/serializer.rs:53]: @mbrobbel  Didn't consider the atomicity, good catch!

**Review by mbrobbel — APPROVED** [review]

File: datafusion/substrait/tests/cases/serialize.rs [hunk 6]
```diff
@@ -31,6 +32,25 @@ mod tests {
...
+    async fn serialize_to_file() -> Result<()> {
+        let ctx = create_context().await?;
+        let path = "tests/serialize_to_file.bin";
+        let sql = "SELECT a, b FROM data";
+
+        // Test case 1: serializing to a non-existing file should succeed.
+        serializer::serialize(sql, &ctx, path).await?;
+        serializer::deserialize(path).await?;
+
+        // Test case 3: serializing to an existing file should fail.
```
Comment (mbrobbel) [inline datafusion/substrait/tests/cases/serialize.rs:45]:
```suggestion
        // Test case 2: serializing to an existing file should fail.
```

File: datafusion/substrait/src/serializer.rs [hunk 7]
```diff
@@ -56,8 +67,9 @@ pub async fn deserialize(path: &str) -> Result<Box<Plan>> {
     deserialize_bytes(protobuf_in).await
 }
 
+/// Deserializes a plan from the bytes.
```
Comment (mbrobbel) [inline datafusion/substrait/src/serializer.rs:70]: Follow-up suggestion (breaking change): this function is marked `async` but it doesn't have to be.

File: datafusion/substrait/src/serializer.rs [hunk 8]
```diff
@@ -26,28 +26,39 @@ use substrait::proto::Plan;
...
-    })?;
+    proto
+        .encode(&mut protobuf_out)
+        .map_err(|e| DataFusionError::Substrait(format!("Failed to encode plan: {e}")))?;
     Ok(protobuf_out)
 }
 
-pub async fn deserialize(path: &str) -> Result<Box<Plan>> {
+/// Reads the file at `path` and deserializes a plan from the bytes.
+pub async fn deserialize(path: impl AsRef<Path>) -> Result<Box<Plan>> {
```
Comment (mbrobbel) [inline datafusion/substrait/src/serializer.rs:61]: Follow-up suggestion (breaking change): this function is marked `async` but it doesn't have to be (see comment on `deserialize_bytes`).
```suggestion
/// Reads the file at `path` and deserializes a plan from the bytes.
pub fn deserialize(path: impl AsRef<Path>) -> Result<Box<Plan>> {
```

File: datafusion/substrait/src/serializer.rs [hunk 9]
```diff
@@ -26,28 +26,39 @@ use substrait::proto::Plan;
...
+pub async fn serialize(
+    sql: &str,
+    ctx: &SessionContext,
+    path: impl AsRef<Path>,
+) -> Result<()> {
     let protobuf_out = serialize_bytes(sql, ctx).await;
-    let mut file = OpenOptions::new().create(true).write(true).open(path)?;
+
+    let mut file = OpenOptions::new().write(true).create_new(true).open(path)?;
     file.write_all(&protobuf_out?)?;
```
Comment (mbrobbel) [inline datafusion/substrait/src/serializer.rs:43]: Follow-up suggestion: use `tokio::io::AsyncWriteExt::write_all` instead of the blocking `std::io::Write::write_all` in this async function.

File: datafusion/substrait/src/serializer.rs [hunk 10]
```diff
@@ -26,28 +26,39 @@ use substrait::proto::Plan;
...
     Ok(())
 }
 
+/// Plans a sql and serializes the generated logical plan to bytes.
 pub async fn serialize_bytes(sql: &str, ctx: &SessionContext) -> Result<Vec<u8>> {
```
Comment (mbrobbel) [inline datafusion/substrait/src/serializer.rs:48]: If we replace the `sql` arg with a `DataFrame` arg, this function (and `serialize`) can be non-async.

**Review by mbrobbel — COMMENTED** [review]
Thanks! I added some follow-up suggestions.

File: datafusion/substrait/src/serializer.rs (hunk 9 above)
Comment (niebayes) [reply datafusion/substrait/src/serializer.rs]: I have replaced the sync `OpenOptions` with the async counterpart backed by tokio.

File: datafusion/substrait/src/serializer.rs (hunk 8 above)
Comment (niebayes) [reply datafusion/substrait/src/serializer.rs:66]: I plan to contribute more to the datafusion-substrait crate. Personally, I would like to reserve the breaking change in one of the following PR

File: datafusion/substrait/src/serializer.rs (hunk 10 above)
Comment (niebayes) [reply datafusion/substrait/src/serializer.rs:53]: Not sure which one is preferable for users. 
@alamb cc

**Review by alamb — APPROVED** [review]
Thanks again @niebayes and @mbrobbel
