### PR TITLE
fix: grouping separator for float and decimal

### LINKED ISSUE #20266: format_string: grouping separator flag (,) ignored for float and decimal conversions (%f)
### Describe the bug

  The FormatStringFunc (datafusion/spark/src/function/string/format_string.rs) correctly parses the grouping separator flag (,) in format specifiers like %,.2f, setting 
`ConversionSpecifier::grouping_separator =true` 
However, the flag is only applied during integer formatting in format_unsigned() (for %d). It is silently ignored in two methods:

  1. format_float() (line ~1684) -- handles Float16, Float32, Float64 with %f, %e, %g conversions. The method never checks self.grouping_separator.
  2. format_decimal() (line ~2022) -- handles Decimal128, Decimal256 with %f, %e, %g conversions. Same issue.

  This is inconsistent with `java.util.Formatter` behavior, where %,.2f applies thousands separators to the integer portion of floating-point output.

### To Reproduce

```rs
use datafusion::execution::SessionStateBuilder;
use datafusion::prelude::SessionContext;
use datafusion_spark::SessionStateBuilderSpark;

#[tokio::main]
async fn main() -> datafusion::common::Result<()> {
    let state = SessionStateBuilder::new()
        .with_default_features()
        .with_spark_features()
        .build();
    let ctx = SessionContext::new_with_state(state);

    let df = ctx
        .sql("SELECT format_string('%,.2f', 1234567.89)")
        .await?;
    df.show().await?;

    Ok(())
}
```

Output
```
+--------------------------------------------------+
| format_string(Utf8("%,.2f"),Float64(1234567.89)) |
+--------------------------------------------------+
| 1234567.89                                       |
+--------------------------------------------------+
+--------------------------------------------------+
| format_string(Utf8("%,.2f"),Float64(1234567.89)) |
+--------------------------------------------------+
| 1234567.89                                       |
+--------------------------------------------------+
```

### Expected behavior

Got expected behaviour from Java
```java
public class FormatTest {
    public static void main(String[] args) {
        // Float grouping separator
        System.out.println("Float %,.2f:  " + String.format("%,.2f", 1234567.89));
        System.out.println("Float %.2f:   " + String.format("%.2f", 1234567.89));
        System.out.println("Float %,.0f:  " + String.format("%,.0f", 1000.0));

        // Decimal (BigDecimal) grouping separator
        java.math.BigDecimal bd = new java.math.BigDecimal("1234567.89");
        System.out.println("BigDec %,.2f: " + String.format("%,.2f", bd));
        System.out.println("BigDec %.2f:  " + String.format("%.2f", bd));
    }
}
```
```
Float %,.2f:  1,234,567.89
Float %.2f:   1234567.89
Float %,.0f:  1,000
BigDec %,.2f: 1,234,567.89
BigDec %.2f:  1234567.89
```

### Additional context

Apply the same thousands-separator loop already used in format_unsigned() to the integer part, then rejoin. This
  needs to be added in two places:

  - format_float(): after line ~1768 where number = format!("{abs:.prec$}", ...)
  - format_decimal(): after the number is produced from the match self.conversion_type block (~line 2095), before padding is applied

  Reference: the grouping logic already exists in format_unsigned() (line ~1897) and can be reused.

### PR DESCRIPTION
**Pull request by Druva-D**
## Which issue does this PR close?

- Closes https://github.com/apache/datafusion/issues/20266

## What changes are included in this PR?
Created a new function to insert the separator (,) into the numbers if the flag is enabled

## Are these changes tested?

Tests passed locally 
Added unit tests to verify functionality

## Are there any user-facing changes?
No

No changes to public api

## Additional Info
Claude was used to assist in identifying the source of the issue.

### CODE REVIEW

File: datafusion/spark/src/function/string/format_string.rs [hunk 1]
```diff
@@ -2082,6 +2085,10 @@ impl ConversionSpecifier {
             }
         };
 
+        if self.grouping_separator {
+            number = insert_thousands_separator(&number);
+        }
```
Comment (kosiew) [inline datafusion/spark/src/function/string/format_string.rs]: Would this be applied unconditionally for decimal formatting, including scientific / compact-scientific output?

File: datafusion/spark/src/function/string/format_string.rs [hunk 2]
```diff
@@ -2391,4 +2419,51 @@ mod tests {
...
+        assert_eq!(
+            insert_thousands_separator("1234567890.1234"),
+            "1,234,567,890.1234"
+        );
+        assert_eq!(insert_thousands_separator("1000"), "1,000");
+        assert_eq!(insert_thousands_separator("100"), "100");
+    }
+
+    #[test]
+    fn test_grouping_separator_float() -> Result<()> {
```
Comment (kosiew) [inline datafusion/spark/src/function/string/format_string.rs:2461]: I think add tests for scientific/compact + grouping (especially precision `0`) where exponent formatting is sensitive, would be helpful

**Review by kosiew — CHANGES_REQUESTED** [review]
Thanks for working on this.

File: datafusion/spark/src/function/string/format_string.rs (hunk 1 above)
Comment (Druva-D) [reply datafusion/spark/src/function/string/format_string.rs]: Yeah it does, will move it to only apply on non scientific output

File: datafusion/spark/src/function/string/format_string.rs [hunk 3]
```diff
@@ -1690,6 +1690,23 @@ impl ConversionSpecifier {
     }
 
     fn format_float(&self, writer: &mut String, value: f64) -> Result<()> {
+        // Java/Spark reject the grouping separator flag with scientific notation
```
Comment (kosiew) [inline datafusion/spark/src/function/string/format_string.rs]: This new ',' + scientific notation validation looks good, but I noticed the same logic now exists in both `format_float` and `format_decimal`. Would it make sense to pull this into a small helper on `ConversionSpecifier`? That way the Spark or Java compatibility rule lives in one place and it reduces the risk of the float and decimal paths drifting over time.

File: datafusion/spark/src/function/string/format_string.rs [hunk 4]
```diff
@@ -2332,6 +2381,24 @@ impl FloatBits for f64 {
     }
 }
 
+/// Inserts thousands separators (`,`) into the integer part of a numeric string.
+/// For example, `"1234567.89"` becomes `"1,234,567.89"`.
+fn insert_thousands_separator(number: &str) -> String {
```
Comment (kosiew) [inline datafusion/spark/src/function/string/format_string.rs:2373]: `insert_thousands_separator` is a really nice addition. It feels like something we could reuse more broadly. I noticed `format_unsigned` still has its own inline grouping logic for decimal integers. Maybe that call site could switch over to this helper as well? It would reduce duplication and keep grouping behavior consistent across numeric formatters.

File: datafusion/spark/src/function/string/format_string.rs [hunk 5]
```diff
@@ -2385,4 +2454,225 @@ mod tests {
...
+        assert_eq!(
+            insert_thousands_separator("1234567890.1234"),
+            "1,234,567,890.1234"
+        );
+        assert_eq!(insert_thousands_separator("1000"), "1,000");
+        assert_eq!(insert_thousands_separator("100"), "100");
+    }
+
+    #[test]
+    fn test_grouping_separator_float() -> Result<()> {
```
Comment (kosiew) [inline datafusion/spark/src/function/string/format_string.rs:2461]: Would it be worth adding a couple more coverage cases around width and sign interactions with the new flag? Something like `%0,10.2f` and `%(,10.2f`, plus the decimal equivalents. The main grouping and scientific cases are well covered, but padding and sign ordering are often where formatter behavior can get a bit tricky.

**Review by kosiew — APPROVED** [review]
@Druva-D 
Thanks for the iteration. 
The changes look solid and the new behavior is well thought through. I left a few small suggestions that could help reduce duplication and tighten consistency, especially if this area evolves further.

File: datafusion/spark/src/function/string/format_string.rs (hunk 4 above)
Comment (Druva-D) [reply datafusion/spark/src/function/string/format_string.rs:2373]: Will deduplicate and move it to ConversionSpecifier

File: datafusion/spark/src/function/string/format_string.rs [hunk 6]
```diff
@@ -2385,4 +2437,295 @@ mod tests {
...
+                ColumnarValue::Scalar(ScalarValue::Utf8(Some("%+,15.2f".to_string()))),
+                ColumnarValue::Scalar(ScalarValue::Decimal128(Some(123456789), 10, 2)),
+            ],
+            Ok(Some("  +1,234,567.89")),
+            &str,
+            Utf8,
+            StringArray
+        );
+        Ok(())
+    }
```
Comment (kosiew) [inline datafusion/spark/src/function/string/format_string.rs:2734]: I think one test case that was explicitly called out earlier is still missing.

The combination %(,10.2f (parentheses for negatives + grouping + width) was mentioned alongside %0,10.2f. The %0 case is covered now, but I could not find a test for the %( case.

From a quick read, format_float seems to already handle negative_in_parentheses correctly, including placing commas in the integer part. So this is probably working fine, but it would be great to have a test to confirm the behavior.

Something like:

// %(,12.2f with -1234.5
// Expect something like "(1,234.50)" with padding depending on width
// Worth verifying against Java: String.format("%(,12.2f", -1234.5)

Also worth noting that format_decimal currently ignores negative_in_parentheses and always uses a minus sign. That looks like pre-existing behavior, but adding the decimal version of this test would help document that gap more clearly.

**Review by kosiew — COMMENTED** [review]
@Druva-D 
Nice work overall. Most of the original feedback has been addressed and the implementation looks solid. I only noticed one small gap around test coverage that was explicitly mentioned in the earlier review.

File: datafusion/spark/src/function/string/format_string.rs (hunk 6 above)
Comment (Druva-D) [reply datafusion/spark/src/function/string/format_string.rs:2734]: Yep, looks like its not being handled in `format_decimal`, added a test and a TODO to document, will implement it if I get time.
