### PR TITLE
fix: incorrect NATURAL/USING JOIN schema

### LINKED ISSUE #14058: Regression: `DataFrame::schema` returns incorrect schema for NATURAL JOIN
### Describe the bug

Affected Version: 42.x, 43.x, 44.x (regression since 41.x)

The `DataFrame::schema` (=> `LogicalPlan::schema`) method returns a schema that includes all columns from the joined sources (using `NATURAL JOIN`), including columns not present in the final output. This behavior is incorrect and inconsistent with the documented behavior:

> Returns the DFSchema describing the output of this DataFrame.

### To Reproduce

Simple MRE here:

```rust
// Works for datafusion: 41.x and earlier
// Failed for datafusion: 42.x and later (including 44.x)

use datafusion::arrow::util::pretty;
use datafusion::prelude::*;

#[tokio::main]
async fn main() -> datafusion::error::Result<()> {
    let ctx = SessionContext::new();

    // Create table1
    ctx.sql(
        r#"
        CREATE TABLE table1 AS
        SELECT * FROM (
            VALUES
            (1, 'a'),
            (2, 'b'),
            (3, 'c')
        ) AS t(id, value1)
        "#,
    )
    .await?;

    // Create table2
    ctx.sql(
        r#"
        CREATE TABLE table2 AS
        SELECT * FROM (
            VALUES
            (1, 'x'),
            (3, 'y'),
            (4, 'z')
        ) AS t(id, value2)
        "#,
    )
    .await?;

    // Execute NATURAL JOIN query
    let df = ctx.sql("SELECT * FROM table1 NATURAL JOIN table2").await?;

    // Incorrect schema includes all columns from both tables
    let schema = df.schema().as_arrow().clone();
    println!("Schema: {:?}", schema);

    // Output does not include all columns
    let result = df.collect().await?;
    pretty::print_batches(&result)?;

    let result_schema = result.first().unwrap().schema();
    assert_eq!(&schema, &*result_schema, "Schema mismatch");

    Ok(())
}

```

Deps:
```toml
datafusion = "44.0.0"
tokio = { version = "1", features = ["full"] }
```

### Expected behavior

The schema returned by `DataFrame::schema` should match the structure of the output produced by `collect`/`collect_partitioned` and etc. Specifically:

- Excluded columns from the result of a NATURAL JOIN should not appear in the schema.

___
Or, if it was intended - the documentation should be aligned and be clear how to access the schema.
However, I find previous behavior correct and useful (e.g - get schema before methods like `write_parquet`/`csv`/`json`)

### Additional context

This is a regression, as the method previously **worked correctly in version 41.x.x and earlier.** 

Also, it probably points to the missing test coverage for particular code-paths. In a sense it's not enough to compare SQL execution results

### PR DESCRIPTION
**Pull request by jonahgao**
## Which issue does this PR close?

Closes #14058.

## Rationale for this change
When expanding unqualified wildcard over a natural/using join, it should deduplicate the columns specified in the join conditions. For example, `select * from t t1 join t t2 using(a)` should output the column `a` only once.

We have already done this in `ExpandWildcardRule`, and this PR re-implements it when computing plan schemas.

## Are these changes tested?
Yes

## Are there any user-facing changes?
No

### CODE REVIEW

File: datafusion/expr/src/utils.rs [hunk 1]
```diff
@@ -379,14 +379,12 @@ fn get_exprs_except_skipped(
...
-/// Resolves an `Expr::Wildcard` to a collection of `Expr::Column`'s.
-pub fn expand_wildcard(
-    schema: &DFSchema,
-    plan: &LogicalPlan,
-    wildcard_options: Option<&WildcardOptions>,
-) -> Result<Vec<Expr>> {
+/// For each column specified in the USING JOIN condition, the JOIN plan outputs it twice
+/// (once for each join side), but an unqualified wildcard should include it only once.
+/// This function returns the columns that should be excluded.
+fn exclude_using_columns(plan: &LogicalPlan) -> Result<HashSet<Column>> {
```
Comment (jonahgao) [inline datafusion/expr/src/utils.rs:385]: This function is extracted from `expand_wildcard`, so that we can reuse it in `exprlist_to_fields`.

Comment (jonahgao) [reply datafusion/expr/src/utils.rs:385]: Although we have moved wildcard expansions to the analyzer #11681, it still does wildcard expansions when computing plan schemas(in [exprlist_to_fields](https://github.com/apache/datafusion/blob/f9cc3325cdb5891b7566a6f3503c1f7ac6ad51e0/datafusion/expr/src/utils.rs#L696) and [exprlist_len](https://github.com/apache/datafusion/blob/f9cc3325cdb5891b7566a6f3503c1f7ac6ad51e0/datafusion/expr/src/utils.rs#L797C8-L797C20)).  I wonder if performing wildcard expansions before computing schemas would be simplier, at least it would avoid redundant work.

File: datafusion/expr/src/utils.rs [hunk 2]
```diff
@@ -705,27 +711,20 @@ pub fn exprlist_to_fields<'a>(
         .map(|e| match e {
             Expr::Wildcard { qualifier, options } => match qualifier {
```
Comment (jonahgao) [inline datafusion/expr/src/utils.rs:712]: Although we have moved wildcard expansions to the analyzer https://github.com/apache/datafusion/pull/11681, it still does wildcard expansions when computing plan schemas(in [exprlist_to_fields](https://github.com/apache/datafusion/blob/f9cc3325cdb5891b7566a6f3503c1f7ac6ad51e0/datafusion/expr/src/utils.rs#L696) and [exprlist_len](https://github.com/apache/datafusion/blob/f9cc3325cdb5891b7566a6f3503c1f7ac6ad51e0/datafusion/expr/src/utils.rs#L797C8-L797C20)). I wonder if performing wildcard expansions before computing schemas would be simplier, at least it would avoid redundant work.

File: datafusion/expr/src/utils.rs [hunk 3]
```diff
@@ -379,14 +379,12 @@ fn get_exprs_except_skipped(
...
-pub fn expand_wildcard(
-    schema: &DFSchema,
-    plan: &LogicalPlan,
-    wildcard_options: Option<&WildcardOptions>,
-) -> Result<Vec<Expr>> {
+/// For each column specified in the USING JOIN condition, the JOIN plan outputs it twice
+/// (once for each join side), but an unqualified wildcard should include it only once.
+/// This function returns the columns that should be excluded.
+fn exclude_using_columns(plan: &LogicalPlan) -> Result<HashSet<Column>> {
     let using_columns = plan.using_columns()?;
```
Comment (jonahgao) [inline datafusion/expr/src/utils.rs:386]: [using_columns()](https://github.com/apache/datafusion/blob/f9cc3325cdb5891b7566a6f3503c1f7ac6ad51e0/datafusion/expr/src/logical_plan/plan.rs#L485) finds join condition columns by traversing the plan tree. This manner might be unsafe as it could incorrectly find columns that are not relevant to the current SQL context. For example, the result of the query below is different from other databases.
```sql
create table t(a int);
insert into t values(1),(2),(3);
select * from (select t.a+2 as a from t join t t2 using(a)) as t2;
```

File: datafusion/expr/src/utils.rs (hunk 2 above)
Comment (jonahgao) [reply datafusion/expr/src/utils.rs:712]: Another issue is that in [exprlist_to_fields](https://github.com/apache/datafusion/blob/f9cc3325cdb5891b7566a6f3503c1f7ac6ad51e0/datafusion/expr/src/utils.rs#L696), we don't handle replace items, but `ExpandWildcardRule` does.
`select * replace ('foo' as a) from t` will give the wrong datatype in schema before executing analyzer.

**Review by DDtKey — COMMENTED** [review]
Thank you for quickly addressing the issue and preparing the PR! 🙏 ❤️ 

I haven’t had a chance to dive deeply into the code yet, but I do have one request: improving test coverage, as I believe it’s really important.

File: datafusion/expr/src/utils.rs (hunk 3 above)
Comment (alamb) [reply datafusion/expr/src/utils.rs:386]: is this something we should file a ticket to track?

**Review by alamb — APPROVED** [review]
This makes sense to me -- thank you @jonahgao and @DDtKey 

I verified that the test fails without this code change, so from that perspective this PR is strictly better than main so in my opinion this PR could be merged in as is

However, I very much think @DDtKey 's comment about more testing is important https://github.com/apache/datafusion/pull/14102/files#r1913426831

Though I do think we can do it as a follow on PR as well


Here is how the test fails

```
assertion `left == right` failed
  left: 2
 right: 1

Left:  2
Right: 1
<Click to see difference>

thread 'test_using_join_wildcard_schema' panicked at datafusion/sql/tests/sql_integration.rs:4568:5:
assertion `left == right` failed
  left: 2
 right: 1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/core/src/panicking.rs:76:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /Users/andrewlamb/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/panicking.rs:373:5
   4: sql_integration::test_using_join_wildcard_schema
             at ./tests/sql_integration.rs:4568:5
   5: sql_integration::test_using_join_wildcard_schema::{{closure}}
             at ./tests/sql_integration.rs:4559:37
   6: core::ops::function::FnOnce::call_once
             at /Users/andrewlamb/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/9fc6b43126469e3858e2fe86cafb4f0fd5068869/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


```

File: datafusion/sql/tests/sql_integration.rs [hunk 4]
```diff
@@ -4552,3 +4552,31 @@ fn test_error_message_invalid_window_aggregate_function_signature() {
...
+    let expected_fields = vec![
+        "o1.order_id".to_string(),
+        "o1.customer_id".to_string(),
+        "o1.o_item_id".to_string(),
+        "o1.qty".to_string(),
+        "o1.price".to_string(),
+        "o1.delivered".to_string(),
+    ];
+    assert_eq!(plan.schema().field_names(), expected_fields);
+}
```
[the remark this answers is not in the document]
Comment (jonahgao) [reply datafusion/sql/tests/sql_integration.rs]: Added in https://github.com/apache/datafusion/pull/14102/commits/789e9f9fc8b0b3c90e1a449252b796d8685dcf37

File: datafusion/expr/src/utils.rs (hunk 3 above)
Comment (jonahgao) [reply datafusion/expr/src/utils.rs:386]: > is this something we should file a ticket to track?

@alamb Filed https://github.com/apache/datafusion/issues/14118

**Review by DDtKey — APPROVED** [review]

**Comment by alamb** [comment]
Thanks @jonahgao  and @DDtKey

**Comment by jonahgao** [comment]
Thanks @DDtKey @alamb for the review.
