### PR TITLE
Extract out super slow planning benchmark to it's own benchmark

### LINKED ISSUE #18366: Running the sql_planner benchmark takes too long (many hours)
### Describe the bug

Running the sql_planner benchmark takes multiple hours, which makes it very hard to run / find useful

For example, `logical_plan_optimize` reports it will take 14782s = 246min = 4.1 HOURs

```
Benchmarking logical_plan_optimize: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 14782.0s, or reduce sample count to 10.
Benchmarking logical_plan_optimize: Collecting 100 samples in estimated  14782 s (100 iterations)^X
```

### To Reproduce

```
cargo bench --bench sql_planner -- logical_plan_optimize
```

### Expected behavior

I expect the benchmarks to each take around 5s which is the standard amount of time needed 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Omega359**
## Which issue does this PR close?

- Closes #18366

## Rationale for this change

Speed up the running of sql planner benchmarks

## What changes are included in this PR?

Extracted out the 'logical_plan_optimize' benchmark to its own file.

## Are these changes tested?

Yes.

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/core/benches/sql_planner_extended.rs [hunk 1]
```diff
@@ -0,0 +1,225 @@
...
+use datafusion_expr::Expr::Literal;
+use datafusion_expr::{cast, col, lit, not, try_cast, when};
+use datafusion_functions::expr_fn::{
+    btrim, length, regexp_like, regexp_replace, to_timestamp, upper,
+};
+use std::ops::Rem;
+use std::sync::Arc;
+use tokio::runtime::Runtime;
+
+/// Registers a table like this:
```
Comment (alamb) [inline datafusion/core/benches/sql_planner_extended.rs:43]: Maybe we could add some context to this benchmark that explains the reproducer is very slow and designed to cover certain planning cases, referencing

https://github.com/apache/datafusion/issues/17261

**Review by alamb — APPROVED** [review]
Thanks @Omega359  -- this is clearly an improvement over main


THere are some others like

```
Benchmarking physical_sorted_union_order_by_200: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 557.0s, or reduce sample count to 10.
Benchmarking physical_sorted_union_order_by_200: Collecting 100 samples in estimated 556.98 s (100 iterations)
```
That still take time but that is only 10 minutes (not hours!)
