### PR TITLE
FIX: Out of bounds error when inserting into MemTable with zero partitions

### LINKED ISSUE #14010: Out of bounds error when inserting into MemTable with zero partitions
### Describe the bug

Trying to insert into a MemTable with zero partitions causes and index out of bounds error when executing.

Backtrace:
```
index out of bounds: the len is 0 but the index is 0
thread 'datasource::memory::tests::test_insert_into_zero_partition' panicked at datafusion/core/src/datasource/memory.rs:373:24:
index out of bounds: the len is 0 but the index is 0
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::panicking::panic_bounds_check
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:276:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index_mut
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/slice/index.rs:307:14
   4: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/slice/index.rs:28:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/vec/mod.rs:2924:9
   6: <datafusion::datasource::memory::MemSink as datafusion_physical_plan::insert::DataSink>::write_all::{{closure}}
...
```

### To Reproduce

The following test case asserts a descriptive message for said error:

```
    // Test inserting a batch into a MemTable without any partitions
    #[tokio::test]
    async fn test_insert_into_zero_partition() -> Result<()> {
        // Create a new schema with one field called "a" of type Int32
        let schema = Arc::new(Schema::new(vec![Field::new("a", DataType::Int32, false)]));

        // Create a new batch of data to insert into the table
        let batch = RecordBatch::try_new(
            schema.clone(),
            vec![Arc::new(Int32Array::from(vec![1, 2, 3]))],
        )?;
        // Run the experiment and expect an error
        let experiment_result = experiment(schema, vec![], vec![vec![batch.clone()]])
            .await
            .unwrap_err();
        // Ensure that there is a descriptive error message
        assert_eq!(
            "Error during planning: Cannot insert into MemTable with zero partitions.",
            experiment_result.strip_backtrace()
        );
        Ok(())
    }
```

### Expected behavior

I think there are multiple ways to address this.

1. An error during planning with a descriptive message.
2. An error during execution with a descriptive message.
3. Automatically create a single partition during insertion
4. Do not allow creating MemTables without any partitions

From my point of view, 1. is the preferred solution because this allows creating "Empty MemTables that cannot become non-empty".
However, I am not really familiar with the code base so opinions may vary.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tobixdev**
## Which issue does this PR close?

Closes #14010

## Rationale for this change

Implements Option 1. from said issue.
If anybody thinks other options are more reasonable I can also change the implementation.

## What changes are included in this PR?

Test during planning whether the `MemTable` has zero partitions and raise a planning error if this is the case.

## Are these changes tested?

The error message is asserted in `test_insert_into_zero_partition`

## Are there any user-facing changes?

Inserting into a `MemTable` with zero partitions fails during planning instead of during execution.
Should this be mentioned in the doc to `insert_into`?

### CODE REVIEW

**Comment by tobixdev** [comment]
@alamb 
I hope its OK to mention you for triggering the CI as you've been recently active and this is my first PR.
Hope this is the expected process :)

File: datafusion/core/src/datasource/memory.rs [hunk 1]
```diff
@@ -265,6 +265,10 @@ impl TableProvider for MemTable {
         input: Arc<dyn ExecutionPlan>,
         insert_op: InsertOp,
     ) -> Result<Arc<dyn ExecutionPlan>> {
+        if self.batches.is_empty() {
```
Comment (jonahgao) [inline datafusion/core/src/datasource/memory.rs:268]: Since we [allow](https://github.com/apache/datafusion/blob/78ee13a7cfdb741d91be805e4117281a2054d2d3/datafusion/physical-plan/src/execution_plan.rs#L817) scanning a MemTable with zero partitions, it seems appropriate to perform this check here.

File: datafusion/core/src/datasource/memory.rs [hunk 2]
```diff
@@ -333,7 +337,11 @@ impl DisplayAs for MemSink {
 }
 
 impl MemSink {
+    /// Creates a new [`MemSink`].
+    ///
+    /// The caller is responsible for ensuring that there is at least one partition to insert into.
```
Comment (alamb) [inline datafusion/core/src/datasource/memory.rs:342]: I think you could avoid the assert / panic here by changing the `new` method to `try_new` and return a `Result` so it could be an error if the batches is empty (and move the check to try_new)

However, I agree this PR is an improvement over what is currently on main so this PR is good to merge as is.

ALso I double checked and `MemSink` is not part of the Public API so this seems reasonable to me

**Review by alamb — APPROVED** [review]
Thank you @tobixdev and @jonahgao

File: datafusion/core/src/datasource/memory.rs (hunk 2 above)
Comment (tobixdev) [reply datafusion/core/src/datasource/memory.rs:342]: In hindsight this would be the better API, even though its just internal.
As I don't have access to a computer for now, I'd merge it like that and if the API ever becomes public we expose the error to the caller.

Comment (jonahgao) [reply datafusion/core/src/datasource/memory.rs:342]: Merged. Thanks @tobixdev . I will create a new PR to follow @alamb 's suggestion.
