### PR TITLE
Strip table qualifiers from schema in `UNION ALL` for unparser

### LINKED ISSUE #10706: UNION ALL should strip table identifiers in its resulting schema
edit:
This bug cannot be fixed as-is due to a requirement that we keep the table identifiers to prevent a duplicate column issue. See #5410 for more context on that issue

The PR that will close this issue only fixes it for the unparser scenario: https://github.com/apache/datafusion/pull/11082

### Describe the bug

The schema that is the result of a UNION ALL should not have any table qualifiers, as the table information has effectively been erased and is no longer a valid reference.

Consider the following SQL:

```sql
SELECT table1.foo FROM table1
UNION ALL
SELECT table2.foo FROM table2
```

The logical schema from this UNION ALL should be just `foo`, but it is currently taking the first input's schema directly, resulting in a schema of `table1.foo`.

This came up as an issue when trying to validate the unparser works correctly for UNION ALL statements, which I added in https://github.com/apache/datafusion/pull/10603

Slightly modifying the above example, if I add an ORDER BY clause to the input SQL:

```sql
SELECT table1.foo FROM table1
UNION ALL
SELECT table2.foo FROM table2
ORDER BY foo
```

Then the resulting unparsed SQL will be:

```sql
SELECT table1.foo FROM table1
UNION ALL
SELECT table2.foo FROM table2
ORDER BY table1.foo
```

Because the unparser takes the schema directly from the Union node when writing out the column expressions.

### To Reproduce

Running this test fails, when it should succeed:

```
#[test]
fn roundtrip_statement_with_dialect() -> Result<()> {
    struct TestStatementWithDialect {
        sql: &'static str,
        expected: &'static str,
        parser_dialect: Box<dyn Dialect>,
        unparser_dialect: Box<dyn UnparserDialect>,
    }
    let tests: Vec<TestStatementWithDialect> = vec![
        TestStatementWithDialect {
            sql: "SELECT j1_id FROM j1
                  UNION ALL
                  SELECT tb.j2_id as j1_id FROM j2 tb
                  ORDER BY j1_id
                  LIMIT 10;",
            expected: r#"SELECT j1.j1_id FROM j1 UNION ALL SELECT tb.j2_id AS j1_id FROM j2 AS tb ORDER BY j1_id ASC NULLS LAST LIMIT 10"#,
            parser_dialect: Box::new(GenericDialect {}),
            unparser_dialect: Box::new(UnparserDefaultDialect {}),
        },
    ];

    for query in tests {
        let statement = Parser::new(&*query.parser_dialect)
            .try_with_sql(query.sql)?
            .parse_statement()?;

        let context = MockContextProvider::default();
        let sql_to_rel = SqlToRel::new(&context);
        let plan = sql_to_rel
            .sql_statement_to_plan(statement)
            .unwrap_or_else(|e| panic!("Failed to parse sql: {}\n{e}", query.sql));

        let unparser = Unparser::new(&*query.unparser_dialect);
        let roundtrip_statement = unparser.plan_to_sql(&plan)?;

        let actual = format!("{}", &roundtrip_statement);
        println!("roundtrip sql: {actual}");
        println!("plan {}", plan.display_indent());

        assert_eq!(query.expected, actual);
    }

    Ok(())
}
```

### Expected behavior

The table qualifiers are stripped from the schema of a UNION ALL LogicalPlan node.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by phillipleblanc**
## Which issue does this PR close?

Closes #10706

## Rationale for this change

The schema that is the result of a UNION ALL should not have any table qualifiers, as the table information has effectively been erased and is no longer a valid reference.

Consider the following SQL:

```sql
SELECT table1.foo FROM table1
UNION ALL
SELECT table2.foo FROM table2
```

The logical schema from this UNION ALL should be just `foo`, but it is currently taking the first input's schema directly, resulting in a schema of `table1.foo`.

This came up as an issue when trying to validate the unparser works correctly for UNION ALL statements, which I added in https://github.com/apache/datafusion/pull/10603

Slightly modifying the above example, if I add an ORDER BY clause to the input SQL:

```sql
SELECT table1.foo FROM table1
UNION ALL
SELECT table2.foo FROM table2
ORDER BY foo
```

Then the resulting unparsed SQL will be:

```sql
SELECT table1.foo FROM table1
UNION ALL
SELECT table2.foo FROM table2
ORDER BY table1.foo
```

Because the unparser takes the schema directly from the Union node when writing out the column expressions.

This is my second attempt to fix #10706, my [first attempt](https://github.com/apache/datafusion/pull/10707) was to remove the table qualifiers when building the Union plan directly, but that caused issues documented here: https://github.com/apache/datafusion/pull/10707#discussion_r1618338309

This attempt scopes the problem to just removing the table qualifiers during the unparsing.

## What changes are included in this PR?

Rewrite the LogicalPlan before unparsing to remove table identifiers from the Union All plan and any sort expressions that take a Union All plan as input.

## Are these changes tested?

Yes, I added a test in the Unparser `sql_integration` test.

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/sql/src/unparser/rewrite.rs [hunk 1]
```diff
@@ -0,0 +1,96 @@
...
+                let schema = match Arc::try_unwrap(union.schema) {
+                    Ok(inner) => inner,
+                    Err(schema) => (*schema).clone(),
+                };
+                let schema = schema.strip_qualifiers();
+
+                union.schema = Arc::new(schema);
+                Ok(Transformed::yes(LogicalPlan::Union(union)))
+            }
+            LogicalPlan::Sort(sort) => {
```
Comment (alamb) [inline datafusion/sql/src/unparser/rewrite.rs:52]: It might be worth documenting here why this very special pattern is verified -- specifically for the unparser

File: datafusion/sql/src/unparser/rewrite.rs [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+/// Normalize the schema of a union plan to remove qualifiers from the schema fields.
+pub(super) struct NormalizeUnionSchema {}
+
+impl NormalizeUnionSchema {
+    pub fn new() -> Self {
+        Self {}
+    }
+}
+
+impl TreeNodeRewriter for NormalizeUnionSchema {
```
Comment (alamb) [inline datafusion/sql/src/unparser/rewrite.rs:35]: FYI because these two rewriters don't have state, you could also implement them using transform_up -- like

```rust
let plan = plan.transform_up(|plan| {
    match plan {
            LogicalPlan::Union(mut union) => {
                let schema = match Arc::try_unwrap(union.schema) {
                    Ok(inner) => inner,
                    Err(schema) => (*schema).clone(),
                };
...
})?.data
```

File: datafusion/sql/src/unparser/rewrite.rs [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+                if !matches!(&*sort.input, LogicalPlan::Union(_)) {
+                    return Ok(Transformed::no(LogicalPlan::Sort(sort)));
+                }
+
+                let mut sort_expr_rewriter = NormalizeSortExprForUnion::new();
+                let sort_exprs: Vec<Expr> = sort
+                    .expr
+                    .into_iter()
+                    .map(|expr| expr.rewrite(&mut sort_expr_rewriter).data())
+                    .collect::<Result<Vec<_>>>()?;
```
Comment (alamb) [inline datafusion/sql/src/unparser/rewrite.rs:62]: If you want, you could avoid the rewriter here too via 

```rust
 let sort_exprs: Vec<Expr> = sort
                    .expr
                    .into_iter()
                    .map_until_stop_and_collect(|expr| {
                        expr.transform_up(|expr| {
                            if let Expr::Column(mut col) = expr {
                                col.relation = None;
                                Ok(Transformed::yes(Expr::Column(col)))
                            } else {
                                Ok(Transformed::no(expr))
                            }
                        })
                    })?.data;
```


However, I will admit the rewriter keeps the logic nicely separated which is nice

Comment (alamb) [reply datafusion/sql/src/unparser/rewrite.rs:62]: You actually might be able to use `LogicalPlan::map_exprs` here instead of having to manually rewrite the sort_exprs too 🤔 

https://github.com/apache/datafusion/blob/c7ac8b8221229b307bba434390ce1d19b7fb9358/datafusion/expr/src/logical_plan/tree_node.rs#L538C12-L538C27

**Review by alamb — APPROVED** [review]
Thank you @phillipleblanc  -- I left some style comments / suggestions, but I think this PR does what it says it does and could be merged as is

Thank you very much for the contribution

File: datafusion/sql/src/unparser/rewrite.rs (hunk 2 above)
Comment (phillipleblanc) [reply datafusion/sql/src/unparser/rewrite.rs:35]: TIL! Will rewrite

File: datafusion/sql/src/unparser/rewrite.rs (hunk 1 above)
Comment (phillipleblanc) [reply datafusion/sql/src/unparser/rewrite.rs]: Added some documentation to the rewrite function

File: datafusion/sql/src/unparser/rewrite.rs (hunk 2 above)
Comment (phillipleblanc) [reply datafusion/sql/src/unparser/rewrite.rs]: I rewrote this to use `transform_up`

File: datafusion/sql/src/unparser/rewrite.rs (hunk 3 above)
Comment (phillipleblanc) [reply datafusion/sql/src/unparser/rewrite.rs]: I used the `transform_up` logic to not require a separate struct, but I moved it to a separate function to keep the logic separated - which I think gets the best of both worlds.

I took a look at `map_expressions`, but I don't think its the right approach for this situation since it doesn't recurse into the expressions.

**Review by alamb — APPROVED** [review]
🚀

**Comment by alamb** [comment]
Thanks again @phillipleblanc  and nice work!@
