### PR TITLE
Fix TopK aggregation for UTF-8/Utf8View group keys and add safe fallback for unsupported string aggregates

### LINKED ISSUE #19219: Execution error: Can't group type: Utf8View
### Describe the bug

Execution error: Can't group type: Utf8View

### To Reproduce

```
DataFusion CLI v51.0.0
> create table t(a text, b text) as values ('123', '4'), ('1', '3');
0 row(s) fetched.
Elapsed 0.019 seconds.

> select a, max(b) as y_axis from t group by a order by y_axis desc;
+-----+--------+
| a   | y_axis |
+-----+--------+
| 123 | 4      |
| 1   | 3      |
+-----+--------+
2 row(s) fetched.
Elapsed 0.013 seconds.

> select a, max(b) as y_axis from t group by a order by y_axis desc limit 1;
Execution error: Can't group type: Utf8View
>
```

### Expected behavior

sql run success

### Additional context

after disable `datafusion.optimizer.enable_topk_aggregation`, the query can run success

check datafusion 51, 50, 49, all not work

### PR DESCRIPTION
**Pull request by kosiew**
## Which issue does this PR close?

* Closes #19219.

## Rationale for this change

A `GROUP BY ... ORDER BY <aggregate> ... LIMIT` query can trigger DataFusion’s TopK aggregation optimization. In affected releases, queries grouping by text columns—especially `Utf8View` produced via SQL `varchar` mappings / `arrow_cast`—could fail at execution time with an error such as `Can't group type: Utf8View`.

This happens because the optimizer may select the TopK aggregation path even when the underlying TopK data structures (heap/hash table) do not fully support the specific key/value Arrow types involved. Disabling `datafusion.optimizer.enable_topk_aggregation` is a workaround, but it forces users to trade correctness for performance.

This PR makes TopK type support explicit and consistent across the optimizer and execution, adds support for UTF-8 string value heaps, and ensures unsupported key/value combinations fall back to the standard aggregation implementation rather than panicking.

## What changes are included in this PR?

* **Centralized TopK type validation**

  * Introduced `topk_types_supported(key_type, value_type)` (in `physical-plan/src/aggregates/mod.rs`) to validate both grouping key and min/max value types.
  * Optimizer now uses this shared check rather than duplicating partial type logic.

* **Safer AggregateExec cloning for limit pushdown**

  * Added `AggregateExec::with_new_limit` to clone an aggregate exec while overriding only the TopK `limit` hint, avoiding manual reconstruction and ensuring plan properties/fields remain consistent.

* **TopK hash table improvements + helper functions**

  * Added `is_supported_hash_key_type` helper for grouping key compatibility checks.
  * Refactored string key extraction to a single helper function.
  * Added `find_or_insert` entry API to avoid double lookups and unify insertion behavior.

* **TopK heap support for string aggregate values**

  * Added `StringHeap` implementation supporting `Utf8`, `LargeUtf8`, and `Utf8View` aggregate values using lexicographic ordering.
  * Added `is_supported_heap_type` helper for aggregate value compatibility.
  * Updated `new_heap` to create `StringHeap` for supported string types and return a clearer error message for unsupported types.

* **Debug contract in TopK stream**

  * Added a debug assertion in `GroupedTopKAggregateStream` documenting that type validation should have already happened (optimizer + can_use_topk), without affecting release builds.

## Are these changes tested?

Yes.

* Added a new physical optimizer test covering UTF-8 grouping with:

  1. **Supported** numeric `max/min` value (TopK should be used and results correct)
  2. **Unsupported** string `max/min` value (must fall back to standard aggregation and not use `GroupedTopKAggregateStream`)

* Added unit tests in `PriorityMap` to validate lexicographic `min/max` tracking for:

  * `Utf8`
  * `LargeUtf8`
  * `Utf8View`

* Added SQLLogicTest coverage (`aggregates_topk.slt`) for:

  * `varchar` tables
  * `Utf8View` via `arrow_cast`
  * `EXPLAIN` verification that TopK limit propagation is applied and plans remain stable
  * Regression case for `max(trace_id)` with `ORDER BY ... LIMIT`

## Are there any user-facing changes?

Yes (bug fix).

* Queries that group by text columns (including `Utf8View`) and use `ORDER BY <aggregate> ... LIMIT` should no longer error.
* TopK aggregation now supports UTF-8 string aggregate values for min/max (lexicographic ordering) where applicable.
* For unsupported type combinations, DataFusion will fall back gracefully to the standard aggregation path instead of panicking.

No breaking public API changes are intended. The only new public helper APIs are internal to the physical plan modules.

## LLM-generated code disclosure

This PR includes LLM-generated code and comments. All LLM-generated content has been manually reviewed and tested.

### CODE REVIEW

File: datafusion/physical-plan/src/aggregates/topk/heap.rs [hunk 1]
```diff
@@ -15,10 +15,22 @@
...
+//!
+//! This module uses the **Strategy pattern** with runtime polymorphism: the `new_heap`
+//! factory function selects an appropriate heap implementation (`PrimitiveHeap` or `StringHeap`)
+//! based on the Arrow data type. All implementations conform to the `ArrowHeap` trait,
+//! enabling dynamic dispatch while keeping the interface uniform.
+//!
+//! Supported value types include Arrow primitives (integers, floats, decimals, intervals)
+//! and UTF-8 strings (`Utf8`, `LargeUtf8`, `Utf8View`) using lexicographic ordering.
+//!
+//! Note: String values are owned/cloned on insertion. For very high cardinality or large
```
Comment (alamb) [inline datafusion/physical-plan/src/aggregates/topk/heap.rs]: I am not sure that this is a useful comment (strings always have overhead compared to primitive types 🤔 )

File: datafusion/physical-plan/src/aggregates/mod.rs [hunk 2]
```diff
@@ -73,6 +75,39 @@ mod row_hash;
...
 mod topk_stream;
 
+/// Returns true if TopK aggregation data structures support the provided key and value types.
+///
+/// This function checks whether both the key type (used for grouping) and value type
+/// (used in min/max aggregation) can be handled by the TopK aggregation heap and hash table.
+/// Supported types include Arrow primitives (integers, floats, decimals, intervals) and
+/// UTF-8 strings (`Utf8`, `LargeUtf8`, `Utf8View`).
+///
+/// # Example
```
Comment (alamb) [inline datafusion/physical-plan/src/aggregates/mod.rs]: I don't think this example adds much (it is pretty clear how to use this function).

File: datafusion/physical-plan/src/aggregates/topk/heap.rs [hunk 3]
```diff
@@ -15,10 +15,22 @@
 // specific language governing permissions and limitations
 // under the License.
 
-//! A custom binary heap implementation for performant top K aggregation
+//! A custom binary heap implementation for performant top K aggregation.
+//!
+//! This module uses the **Strategy pattern** with runtime polymorphism: the `new_heap`
```
Comment (alamb) [inline datafusion/physical-plan/src/aggregates/topk/heap.rs]: I am not familiar with the strategy pattern -- perhaps you can add a reference to a definiton if that is important to understand thus function.

I think you could probably simplify this paragraph to a single sentence:
```rust
//! the `new_heap` factory function selects an appropriate heap implementation
//! based on the Arrow data type.
```

File: datafusion/physical-plan/src/aggregates/topk/heap.rs [hunk 4]
```diff
@@ -161,6 +180,108 @@ where
...
+}
+
+/// Helper to extract a string value from an ArrayRef at a given index.
+///
+/// Supports `Utf8`, `LargeUtf8`, and `Utf8View` data types. This helper reduces
+/// duplication between `StringHeap::value()` and `StringHeap::drain()`.
+///
+/// # Panics
+/// Panics if the index is out of bounds or if the data type is unsupported.
+fn extract_string_value(batch: &ArrayRef, data_type: &DataType, idx: usize) -> String {
```
Comment (alamb) [inline datafusion/physical-plan/src/aggregates/topk/heap.rs]: This will allocate a string for *every* row -- which I suspect will perform quite poorly

I think you could use this trait or something similar to return `&str` at least, and only clone the String when you need to put it into the heap https://docs.rs/arrow/latest/arrow/array/trait.StringArrayType.html

**Review by alamb — COMMENTED** [review]
Thanks @kosiew  -- I started looking at this and I think it is a good start. 

cc @haohuaijin perhaps you can help review here too

**Comment by alamb** [comment]
@avantgardnerio  perhaps you can help here too as you are familiar with this code

File: datafusion/physical-plan/src/aggregates/topk/heap.rs (hunk 4 above)
Comment (avantgardnerio) [reply datafusion/physical-plan/src/aggregates/topk/heap.rs]: I think a bench would be important for a change like this.

Comment (avantgardnerio) [reply datafusion/physical-plan/src/aggregates/topk/heap.rs]: I think we need a `trait IntoHeapValue<T>` or something so we can check the heap for `&str` but then take ownership if it actually replaces a value.

File: datafusion/physical-plan/src/aggregates/topk/heap.rs [hunk 5]
```diff
@@ -451,23 +572,46 @@ compare_integer!(u8, u16, u32, u64);
...
+        return Ok(Box::new(StringHeap::new(limit, desc, vt)));
+    }
+
     macro_rules! downcast_helper {
         ($vt:ty, $d:ident) => {
             return Ok(Box::new(PrimitiveHeap::<$vt>::new(limit, desc, vt)))
         };
     }
 
+    let vt_clone = vt.clone();
```
Comment (haohuaijin) [inline datafusion/physical-plan/src/aggregates/topk/heap.rs]: look like this clone do not need

File: datafusion/physical-plan/src/aggregates/mod.rs (hunk 2 above)
Comment (kosiew) [reply datafusion/physical-plan/src/aggregates/mod.rs]: I'll remove the example.

File: datafusion/physical-plan/src/aggregates/topk/heap.rs (hunk 3 above)
Comment (kosiew) [reply datafusion/physical-plan/src/aggregates/topk/heap.rs]: I'll simplify the comment as suggested.

File: datafusion/physical-plan/src/aggregates/topk/heap.rs (hunk 1 above)
Comment (kosiew) [reply datafusion/physical-plan/src/aggregates/topk/heap.rs]: I'll remove it.

File: datafusion/physical-plan/src/aggregates/topk/heap.rs (hunk 4 above)
Comment (kosiew) [reply datafusion/physical-plan/src/aggregates/topk/heap.rs]: Thanks for the suggestion!
I'll implement it.

File: datafusion/physical-plan/src/aggregates/topk/heap.rs (hunk 5 above)
Comment (kosiew) [reply datafusion/physical-plan/src/aggregates/topk/heap.rs]: fixed

File: datafusion/physical-plan/src/aggregates/topk/heap.rs [hunk 6]
```diff
@@ -161,6 +225,166 @@ where
...
+    ///
+    /// This is particularly effective for workloads with repeated string values like trace IDs.
+    fn intern_string(&mut self, s: &str) -> Arc<str> {
+        // Compute hash of the string
+        let mut hasher = std::collections::hash_map::DefaultHasher::new();
+        s.hash(&mut hasher);
+        let hash = hasher.finish();
+
+        // Check cache and return if found
+        if let Some(cached) = self.string_cache.get(&hash) {
```
Comment (haohuaijin) [inline datafusion/physical-plan/src/aggregates/topk/heap.rs]: maybe we can use `entry` to avoid two time lookup for `hash`

File: datafusion/physical-plan/src/aggregates/topk/heap.rs [hunk 7]
```diff
@@ -161,6 +225,166 @@ where
...
+/// The `string_cache` maps string hashes to `Arc<str>` values, amortizing allocation costs
+/// when the same string appears multiple times (common in trace IDs, user IDs, etc.).
+pub struct StringHeap {
+    batch: ArrayRef,
+    heap: TopKHeap<Arc<str>>,
+    desc: bool,
+    data_type: DataType,
+    /// Cache of interned strings for the current batch, mapping hash to `Arc<str>`.
+    /// Cleared on each `set_batch` call to prevent memory leaks from old batches.
+    string_cache: HashMap<u64, Arc<str>>,
```
Comment (haohuaijin) [inline datafusion/physical-plan/src/aggregates/topk/heap.rs]: i'm not sure if we really need this, the heap mantains the values of aggregate result, if the column in stringHeap is the column like trace ids or user ids, for each batch almost impossible to have duplicate values.

**Review by haohuaijin — COMMENTED** [review]
Sorry for delay reviews @kosiew , i left two comment, otherwise look good to me. maybe you add a benchmark to https://github.com/apache/datafusion/blob/main/datafusion/core/benches/topk_aggregate.rs

File: datafusion/physical-plan/src/aggregates/topk/heap.rs (hunk 6 above)
Comment (kosiew) [reply datafusion/physical-plan/src/aggregates/topk/heap.rs]: good idea!
I'll implement it.

File: datafusion/physical-plan/src/aggregates/topk/heap.rs (hunk 7 above)
Comment (kosiew) [reply datafusion/physical-plan/src/aggregates/topk/heap.rs]: Fair point—for high-cardinality string columns like trace or user IDs, duplicate values within a single batch are rare. 

However, the cache provides a cheap safety net for lower-cardinality workloads (e.g., country codes, status strings) where duplicates are common. The overhead is minimal (one hash lookup per new value).

Comment (kosiew) [reply datafusion/physical-plan/src/aggregates/topk/heap.rs]: After getting bad benchmark results, I refactored this from 
per-batch string interning cache (mapping hashes to `Arc<str>`)
to
compare-first design that stores `Option<String>` in the heap

and string_cache.

**Comment by kosiew** [comment]
Run benchmarks

**Review by haohuaijin — APPROVED** [review]
Thanks @kosiew, Look good to me. for benchmark, because we can't support topk_aggregate for string aggregate func type before, so maybe you need add a new benchmark to https://github.com/apache/datafusion/blob/main/datafusion/core/benches/topk_aggregate.rs

**Comment by kosiew** [comment]
@haohuaijin 
> we can't support topk_aggregate for string aggregate func type before, so maybe you need add a new benchmark 

Thanks for your review and nudge.
I added a new benchmark.

File: datafusion/core/benches/topk_aggregate.rs [hunk 8]
```diff
@@ -170,6 +204,55 @@ fn criterion_benchmark(c: &mut Criterion) {
         .as_str(),
         |b| b.iter(|| run(&rt, ctx.clone(), limit, true, true)),
     );
+
+    // String aggregate benchmarks - grouping by timestamp, aggregating string column
+    let ctx = rt
```
Comment (haohuaijin) [inline datafusion/core/benches/topk_aggregate.rs:209]: one suggestion, added benchmark always use topk, we should add some benchmark do not use topk, then we can compare, like below
```rust
    let ctx = rt
        .block_on(create_context(partitions, samples, false, false, false))
        .unwrap();
    c.bench_function(
        format!(
            "string aggregate {} time-series rows [Utf8]",
            partitions * samples
        )
        .as_str(),
        |b| b.iter(|| run_string(&rt, ctx.clone(), limit, false)),
    );

    let ctx = rt
        .block_on(create_context(partitions, samples, true, false, false))
        .unwrap();
    c.bench_function(
        format!(
            "string aggregate {} worst-case rows [Utf8]",
            partitions * samples
        )
        .as_str(),
        |b| b.iter(|| run_string(&rt, ctx.clone(), limit, false)),
    );
```

**Review by haohuaijin — APPROVED** [review]

**Comment by avantgardnerio** [comment]
> @haohuaijin
> 
> > we can't support topk_aggregate for string aggregate func type before, so maybe you need add a new benchmark
> 
> Thanks for your review and nudge. I added a new benchmark.

How does the new benchmark compare in performance between:
1. running with this topk optimization enabled
2. running without
?

The original justification for merging the primitive version of this rule was that it was equally as fast with it enabled or disabled, but when enabled memory was constant.

If that remains true for strings, I think we can merge. If it is constant memory but slower for strings, I think we need to look at heuristics for when to enable vs not.

**Comment by haohuaijin** [comment]
@avantgardnerio 
enable topk_aggregate is faster, you can check this https://github.com/apache/datafusion/pull/19523#issue-3765628404

File: datafusion/core/benches/topk_aggregate.rs (hunk 8 above)
Comment (kosiew) [reply datafusion/core/benches/topk_aggregate.rs:209]: Created #19713 to track this.

**Comment by kosiew** [comment]
@haohuaijin , @avantgardnerio ,
Thanks for your review and feedback.
