### PR TITLE
fix: The inconsistency between scalar and array on the cast decimal to timestamp

### LINKED ISSUE #16531: Different result of decimal to timestamp cast when source value is constant
### Describe the bug

decimal value V cast to timestamp type produces different values T1 or T2, depending on whether V is a constant

### To Reproduce

```
> SELECT CAST(CAST(1 AS decimal(17,2)) AS timestamp(3));
+---------------------+
| Int64(1)            |
+---------------------+
| 1970-01-01T00:00:01 |
+---------------------+
1 row(s) fetched.
Elapsed 0.003 seconds.

> SELECT CAST(CAST(x AS decimal(17,2)) AS timestamp(3)) from (values (1)) t(x);
+-------------------------+
| t.x                     |
+-------------------------+
| 1970-01-01T00:00:00.001 |
+-------------------------+
```

### Expected behavior

The queries should produce same result

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chenkovsky**
## Which issue does this PR close?

- Closes #16531.

## Rationale for this change

In arrow(array), it will treat decimal as millisecond. but in datafusion(scalar), decimal will be treated as second.

for int64, datafusion's behavior is same as arrow. only decimal is incorrect.

## What changes are included in this PR?

treat decimal as millisecond.

## Are these changes tested?

UT

## Are there any user-facing changes?

Yes

### CODE REVIEW

File: datafusion/common/src/scalar/mod.rs [hunk 1]
```diff
@@ -3069,7 +3069,7 @@ impl ScalarValue {
                 ScalarValue::Decimal128(Some(decimal_value), _, scale),
                 DataType::Timestamp(time_unit, None),
             ) => {
-                let scale_factor = 10_i128.pow(*scale as u32);
+                let scale_factor = 10_i128.pow(*scale as u32 + 3);
```
Comment (findepi) [inline datafusion/common/src/scalar/mod.rs]: Does this depend on the timestamp precision (time unit)? Can you please add tests for other units?

Do we need this special casing at all for casting decimal to timestamp?
or can we end up calling `cast_with_options`, just like we do for virtually all other type pairs?

File: datafusion/sqllogictest/test_files/timestamps.slt [hunk 2]
```diff
@@ -3420,3 +3420,8 @@ select to_timestamp('-1');
 
 query error DataFusion error: Arrow error: Parser error: Error parsing timestamp from '\-1': timestamp must contain at least 10 characters
 select to_timestamp(arrow_cast('-1', 'Utf8'));
+
+query B
+SELECT CAST(CAST(x AS decimal(17,2)) AS timestamp(3)) = CAST(CAST(1 AS decimal(17,2)) AS timestamp(3)) from (values (1)) t(x);
+----
```
Comment (findepi) [inline datafusion/sqllogictest/test_files/timestamps.slt]: Formatting like this will help see why these should be equal. Also it's enough to project the values. (They should be equal, but also they should be particular values).

```
SELECT CAST(CAST(1   AS decimal(17,2)) AS timestamp(3)) AS a UNION ALL
SELECT CAST(CAST(one AS decimal(17,2)) AS timestamp(3)) AS a FROM (VALUES (1)) t(one);
```

File: datafusion/common/src/scalar/mod.rs (hunk 1 above)
Comment (alamb) [reply datafusion/common/src/scalar/mod.rs]: I think the underlying arrow kernel may not support casting decimal --> timestamp (I bet this is something spark related) 🤔

Comment (chenkovsky) [reply datafusion/common/src/scalar/mod.rs]: > I think the underlying arrow kernel may not support casting decimal --> timestamp (I bet this is something spark related) 🤔
@alamb here implements casting decimal --> timestamp
https://github.com/apache/arrow-rs/blob/b6240b32e235d4ca330372e3be31f784ba133252/arrow-cast/src/cast/mod.rs#L4032

**Comment by chenkovsky** [comment]
should I also change https://github.com/apache/datafusion/blob/334d449ff778af590a7d8421544ac60222e5f69b/datafusion/functions/src/datetime/to_timestamp.rs#L339 ?

File: datafusion/common/src/scalar/mod.rs (hunk 1 above)
Comment (chenkovsky) [reply datafusion/common/src/scalar/mod.rs]: > Does this depend on the timestamp precision (time unit)? Can you please add tests for other units?
> 
> Do we need this special casing at all for casting decimal to timestamp? or can we end up calling `cast_with_options`, just like we do for virtually all other type pairs?

@findepi you are right, it's time unit related. I updated code.

Comment (findepi) [reply datafusion/common/src/scalar/mod.rs]: > I think the underlying arrow kernel may not support casting decimal --> timestamp

Can be!

So how does this work when the value is not constant-folded?
What code ends up executing in the 'normal query' case?

Can the same code be executed also in constant-folding case?

File: datafusion/sqllogictest/test_files/timestamps.slt [hunk 3]
```diff
@@ -3420,3 +3420,38 @@ select to_timestamp('-1');
 
 query error DataFusion error: Arrow error: Parser error: Error parsing timestamp from '\-1': timestamp must contain at least 10 characters
 select to_timestamp(arrow_cast('-1', 'Utf8'));
+
+query P
+SELECT CAST(CAST(1   AS decimal(17,2)) AS timestamp(3)) AS a UNION ALL
+SELECT CAST(CAST(one AS decimal(17,2)) AS timestamp(3)) AS a FROM (VALUES (1)) t(one);
+----
+1970-01-01T00:00:00.001
+1970-01-01T00:00:00.001
```
Comment (findepi) [inline datafusion/sqllogictest/test_files/timestamps.slt:3538]: Is this the desired semantics when casting from decimal(p,s) to timestamp(q)? 

For example, when casting from `decimal(38,3)` to `timestamp(3)` it could feel natural to interpret decimal's whole integer part as seconds-of-epoch, and decimal's fraction as millis-of-second.

With the current implementation, the decimal's fraction seems to be discarded.
(Should we have tests with some non-whole integer decimal values as well)?

Comment (alamb) [reply datafusion/sqllogictest/test_files/timestamps.slt:3538]: I don't know what the semantics should be when casting from decimal --> timestamp.  I recommend that we add the tests @findepi  suggests and file a follow on ticket to clarify this point

**Comment by findepi** [comment]
> It is not 100% clear to me if this is the "right" behavior, but in my opinion consistent is better than inconsistent

agreed

my second thought before merging is that:
We now have two behaviors. clearly a bug, and fixing it can be viewed as a breaking change (depending on point of view). We have to make this breaking change so it's not contentious.

if we fix the bug now into one direction (whichever), and then reconsider desired semantics concluding we want opposite, it will be another breaking change and may be a point of contention. Given breaking changes should be done very judiciously (for good reasons), i would somewhat prefer to force us to decide on the desired semantics.

**Comment by alamb** [comment]
> Given breaking changes should be done very judiciously (for good reasons), i would somewhat prefer to force us to decide on the desired semantics.

Looks like the original was added as part of  this PR from @jatin510 
- https://github.com/apache/datafusion/pull/15486

maybe they remember

**Comment by findepi** [comment]
That PR added ScalarValue cast, but not the runtime cast.
I can't find the code for runtie cast. Do we delegate that to arrow?

**Comment by alamb** [comment]
> That PR added ScalarValue cast, but not the runtime cast. I can't find the code for runtie cast. Do we delegate that to arrow?

I am not sure -- we would need to trace the code down

**Comment by findepi** [comment]
I think i understand.

Before https://github.com/apache/datafusion/pull/15486 we were using Arrow's cast semantics for Decimal to Timestamp conversion.  This semantics has unfortunate effect of discarding the fractional part of decimal. 

In https://github.com/apache/datafusion/pull/15486, a to_timestamp(decimal) was implemented, but only for scalar values / constant-foldable values (https://github.com/apache/datafusion/pull/15486#issuecomment-3014122915). To match the cast behavior in scalar tests, the `ScalarValue::cast_to_with_options` was changed (probably following pre-existing pattern of Float64->timestamp special treatment). This introduced https://github.com/apache/datafusion/issues/16531, because the non-scalar code path was not changed.

The https://github.com/apache/datafusion/pull/15486 was merged fairly recently and didn't change the non-scalar code path. I think we should restore the decimal cast behavior to as it was before https://github.com/apache/datafusion/pull/15486. For those who -- like me -- don't want decimal fraction to get ignored, the to_timestamp seems like the alternative to use. Further, we should remove any other type-special handling in `ScalarValue::cast_to_with_options`, because it's likely other discrepancies.

Last but not least, i start to appreciate engines which deliberately don't implement a cast from number to timestamp.
```
postgres=# SELECT 1::timestamp(3);
ERROR:  cannot cast type integer to timestamp without time zone
LINE 1: SELECT 1::timestamp(3);
```

```
trino> SELECT CAST(1 AS timestamp(3));
Query 20250627_192003_00001_zzaqu failed: line 1:8: Cannot cast integer to timestamp(3)
```

there is no single good way to cast, so supporting this with named functions is better.

**Comment by findepi** [comment]
> The #15486 was merged fairly recently and didn't change the non-scalar code path. I think we should restore the decimal cast behavior to as it was before #15486.


@alamb do we have an agreement on the direction proposed above?

**Comment by alamb** [comment]
> > The #15486 was merged fairly recently and didn't change the non-scalar code path. I think we should restore the decimal cast behavior to as it was before #15486.
> 
> @alamb do we have an agreement on the direction proposed above?


> The https://github.com/apache/datafusion/pull/15486 was merged fairly recently and didn't change the non-scalar code path. I think we should restore the decimal cast behavior to as it was before https://github.com/apache/datafusion/pull/15486. For those who -- like me -- don't want decimal fraction to get ignored, the to_timestamp seems like the alternative to use. Further, we should remove any other type-special handling in ScalarValue::cast_to_with_options, because it's likely other discrepancies.

I think this makes sense to me -- ideally we can document this somewhere so we don't churn / rework the semantics again in the future

**Comment by jatin510** [comment]
hey !

When i was working with https://github.com/apache/datafusion/issues/14612 I found out that, after changing the default `parse_float_as_decimal` to `true`. The test cases for the timestamp started failing.

My initial impression was, not to change the behaviour of the existing test cases with this parse option.
So, I worked on https://github.com/apache/datafusion/pull/15486, and passed the tests successfully.

**Comment by findepi** [comment]
@jatin510 as mentioned [above](https://github.com/apache/datafusion/pull/16539#issuecomment-3014136564), the Float64 to timestamp cast is broken too. I filed separate issue for this: https://github.com/apache/datafusion/issues/16636

File: datafusion/common/src/scalar/mod.rs [hunk 4]
```diff
@@ -3069,7 +3069,14 @@ impl ScalarValue {
                 ScalarValue::Decimal128(Some(decimal_value), _, scale),
                 DataType::Timestamp(time_unit, None),
```
Comment (findepi) [inline datafusion/common/src/scalar/mod.rs]: In https://github.com/apache/datafusion/pull/16639 i tried to clear the path for more changes here.
If and once that one merged, we should be able to remove this whole code block.

**Comment by alamb** [comment]
What is the status of this PR? Shall we merge it? Or are there outstanding issues to resolve?

File: datafusion/common/src/scalar/mod.rs (hunk 4 above)
Comment (findepi) [reply datafusion/common/src/scalar/mod.rs]: https://github.com/apache/datafusion/pull/16639 is now merged.
please remove the whole `let scalar_array = match (self, target_type) { ... }` block, replacing it with just `self.to_array()?`.

**Comment by findepi** [comment]
> What is the status of this PR? Shall we merge it? Or are there outstanding issues to resolve?

requires an update -- https://github.com/apache/datafusion/pull/16539#discussion_r2180903190

**Review by findepi — APPROVED** [review]

**Comment by findepi** [comment]
@alamb PTAL

File: datafusion/common/src/scalar/mod.rs [hunk 5]
```diff
@@ -3075,38 +3075,7 @@ impl ScalarValue {
...
-                        ScalarValue::Int64(Some(nanos as i64))
-                    }
-                };
-
-                timestamp_value.to_array()?
-            }
-            _ => self.to_array()?,
-        };
-
+        let scalar_array = self.to_array()?;
```
Comment (alamb) [inline datafusion/common/src/scalar/mod.rs:3078]: that is pretty nice fixing bugs by deleting code 🏆
