### PR TITLE
fix: deserialization error for `FilterExec` (predicates with inlist)

### LINKED ISSUE #17225: regression: inlist deserialization error
### Describe the bug

encounter deserialization  error when query have inlist and other filter like below
```
Error: Internal("PhysicalExpr Column references column 'p_size' at index 1 (zero-based) but input schema only has 1 columns: [\"p_size\"]")
```
the query is
```sql
SELECT p_size FROM part WHERE p_size IN (14, 6, 5, 31) and p_partkey > 1000
```

### To Reproduce

add a reproduce in pr https://github.com/apache/datafusion/pull/17224/files

this is another reproduce https://github.com/haohuaijin/inlist-reproduce
The code is as follows
```rust
use std::sync::Arc;

use arrow::datatypes::{DataType, Field, Schema, SchemaRef};
use datafusion::{
    datasource::{
        file_format::parquet::ParquetFormat,
        listing::{ListingOptions, ListingTableUrl},
    },
    prelude::SessionContext,
};
use datafusion_proto::{
    physical_plan::{AsExecutionPlan, DefaultPhysicalExtensionCodec},
    protobuf::PhysicalPlanNode,
};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let ctx = SessionContext::new();
    let listing_options = ListingOptions::new(Arc::new(ParquetFormat::default()));
    let table_path = ListingTableUrl::parse("data.parquet")?;

    ctx.register_listing_table(
        "default",
        &table_path,
        listing_options.clone(),
        Some(get_schema()),
        None,
    )
    .await?;

    let plan = ctx
        .sql("select message from default where message in ('a', 'b', 'c', 'd') and timestamp >= 1")
        .await
        .unwrap()
        .create_physical_plan()
        .await
        .unwrap();

    let node: PhysicalPlanNode =
        PhysicalPlanNode::try_from_physical_plan(plan, &DefaultPhysicalExtensionCodec {}).unwrap();

    let plan = node
        .try_into_physical_plan(&ctx, &ctx.runtime_env(), &DefaultPhysicalExtensionCodec {})
        .unwrap();

    println!("{:?}", plan);

    Ok(())
}

fn get_schema() -> SchemaRef {
    SchemaRef::new(Schema::new(vec![
        Field::new("timestamp", DataType::Int64, false),
        Field::new("message", DataType::Utf8, true),
    ]))
}
```

### Expected behavior

deserialization success

### Additional context

it work fine in datafusion v47 and v48
look like related https://github.com/apache/datafusion/issues/16665 and https://github.com/apache/datafusion/pull/16744

### PR DESCRIPTION
**Pull request by haohuaijin**
## Which issue does this PR close?

- closes #17225

## Rationale for this change

fix #17225

### CODE REVIEW

**Comment by haohuaijin** [comment]
I check the code, the FliterExec predicate's column index is based on FilterExec's input schema, so when we deserialization the FilterExec, the predicate should also based on input schema.
https://github.com/apache/datafusion/blob/b84ddfde0689e8ecb9b71521fd95c7245d68d4ca/datafusion/physical-plan/src/filter.rs#L90-L116

and i also check the disscussion in #16744 and #16665, not sure why previous issue happen. maybe some code have problem before, but someone fix it recently

cc @alamb @XiangpengHao

File: datafusion/proto/src/physical_plan/mod.rs [hunk 1]
```diff
@@ -567,43 +567,33 @@ impl protobuf::PhysicalPlanNode {
...
-        } else {
-            input.schema()
-        };
 
         let predicate = filter
             .expr
             .as_ref()
             .map(|expr| {
-                parse_physical_expr(expr, ctx, predicate_schema.as_ref(), extension_codec)
+                parse_physical_expr(expr, ctx, input.schema().as_ref(), extension_codec)
```
Comment (alamb) [inline datafusion/proto/src/physical_plan/mod.rs:590]: Using the input schema always matches my understanding of how the FilterExec work 👍

File: datafusion/proto/tests/cases/roundtrip_physical_plan.rs [hunk 2]
```diff
@@ -1909,3 +1909,37 @@ async fn test_round_trip_date_part_display() -> Result<()> {
 
     Ok(())
 }
+
+#[tokio::test]
+async fn test_tpch_part_in_list_query_with_real_parquet_data() -> Result<()> {
```
Comment (alamb) [inline datafusion/proto/tests/cases/roundtrip_physical_plan.rs:2061]: I verified this test covers the code as it fails without the fix

```


---- cases::roundtrip_physical_plan::test_tpch_part_in_list_query_with_real_parquet_data stdout ----
Error: Internal("PhysicalExpr Column references column 'p_size' at index 1 (zero-based) but input schema only has 1 columns: [\"p_size\"]")
```

**Comment by alamb** [comment]
My understanding of this fix is that it could affect any predicate, not just `IN` lists, so I updated the PR description to match

**Comment by haohuaijin** [comment]
Thank you @alamb

**Comment by alamb** [comment]
Screenshot 2025-08-19 at 12 49 49 PM
I merged up from main to resolve a conflict

**Comment by alamb** [comment]
Thanks again @haohuaijin
