### PR TITLE
Fix: check ambiguous column reference

### LINKED ISSUE #12337: A join SQL query with ambiguous table reference executes without error (SQLancer-NoREC)
### Describe the bug

The `t1.v1` inside query's `on` clause is ambiguous, it's not clear which `t1` it's referring to, such query should be rejected by the planner

See reproducer in `datafusion-cli` (Compilred from latest main with `cargo run`, commit hash d6f3f738e)
```
DataFusion CLI v41.0.0
> create table t1(v1 int);

0 row(s) fetched.
Elapsed 0.070 seconds.

> select count(*)
from t1
right outer join t1
on t1.v1 > 0;
+----------+
| count(*) |
+----------+
| 0        |
+----------+
1 row(s) fetched.
Elapsed 0.075 seconds.

```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

Found by SQLancer https://github.com/apache/datafusion/issues/11030

### PR DESCRIPTION
**Pull request by HuSen8891**
## Which issue does this PR close?

Closes #12337 

## Rationale for this change
check ambiguous column reference in query

### CODE REVIEW

File: datafusion/common/src/dfschema.rs [hunk 1]
```diff
@@ -467,6 +464,36 @@ impl DFSchema {
...
+                    // the original field may now be aliased with a name that matches the
+                    // original qualified name
+                    let column = Column::from_qualified_name(f.name());
+                    match column {
+                        Column {
+                            relation: Some(r),
+                            name: column_name,
+                        } => &r == qq && column_name == name,
+                        _ => false,
+                    }
```
Comment (alamb) [inline datafusion/common/src/dfschema.rs:490]: Another way to express this logic I would find clearer would be

```suggestion
                    if let Some(r) = column.relation.as_ref() {
                        r == qq && column.name == name
                    } else {
                        false
                    }
```

(though this is fine too)

File: datafusion/sql/src/expr/identifier.rs [hunk 2]
```diff
@@ -186,7 +186,22 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
                             let s = &ids[0..ids.len()];
                             // safe unwrap as s can never be empty or exceed the bounds
                             let (relation, column_name) = form_identifier(s).unwrap();
-                            Ok(Expr::Column(Column::new(relation, column_name)))
+                            // sanity check on column
+                            match schema
```
Comment (alamb) [inline datafusion/sql/src/expr/identifier.rs:190]: I think we are trying to avoid matching on `Err` and converting to `Ok` because each `Err` results in at least one `String` allocation (for the error message)

Since this code is potentially invoked many times during planning the allocations can add up and slow down planning

Is there any way to use a method that doesn't return `Err` here?

**Review by alamb — COMMENTED** [review]
Thank you very much @HuSen8891  -- this is a great contribution

I have one concern about handling `Err` but otherwise looks good to me. 

I think it would be good if someone else (perhaps @jonahgao ) also took a look at this PR to see if we are missing anything else

File: datafusion/sql/src/expr/identifier.rs (hunk 2 above)
Comment (HuSen8891) [reply datafusion/sql/src/expr/identifier.rs:190]: The result returned is not Err in most cases, we can ignore the additional cost here?

File: datafusion/common/src/dfschema.rs (hunk 1 above)
Comment (HuSen8891) [reply datafusion/common/src/dfschema.rs:490]: Thanks！Refine this part by the clearer way.

**Comment by jonahgao** [comment]
Thanks @HuSen8891. I plan to review it later today.

File: datafusion/sql/src/expr/identifier.rs [hunk 3]
```diff
@@ -186,7 +186,22 @@ impl<'a, S: ContextProvider> SqlToRel<'a, S> {
                             let s = &ids[0..ids.len()];
                             // safe unwrap as s can never be empty or exceed the bounds
                             let (relation, column_name) = form_identifier(s).unwrap();
-                            Ok(Expr::Column(Column::new(relation, column_name)))
+                            // sanity check on column
```
Comment (jonahgao) [inline datafusion/sql/src/expr/identifier.rs:189]: As the comment says, how about adding a `check_ambiguous_qualified_name` method to `DFSchema`? 
I think this would be more intuitive and simpler. The code here can be changed to the following.
```rust
// sanity check on column
schema.check_ambiguous_qualified_name(relation.as_ref(), column_name)?;
Ok(Expr::Column(Column::new(relation, column_name)))
```
`check_ambiguous_qualified_name` is used to check whether the specified qualified name appears multiple times in the schema.

I suspect that we should not allow two identical qualified fields within a schema, but this would violate PR 6091. Therefore, introducing a method like `check_ambiguous_qualified_name` to be called when needed might be a workaround.

Comment (HuSen8891) [reply datafusion/sql/src/expr/identifier.rs:189]: That‘s good idea.
Add method 'check_ambiguous_name' to check ambiguous column reference.

File: datafusion/common/src/dfschema.rs [hunk 4]
```diff
@@ -412,17 +412,32 @@ impl DFSchema {
         }
     }
 
+    /// Check whether the column reference is ambiguous
+    pub fn check_ambiguous_name(
```
Comment (jonahgao) [inline datafusion/common/src/dfschema.rs:416]: I think the newly introduced functions `qualified_field_with_qualified_name` and `qualified_fields_with_qualified_name` do more than what we need. They might be unnecessary.
If I understand correctly, this function can be implemented as follows:
```rust
pub fn check_ambiguous_name(
        &self,
        qualifier: Option<&TableReference>,
        name: &str,
    ) -> Result<()> {
        let count = self
            .iter()
            .filter(|(field_q, f)| match (field_q, qualifier) {
                (Some(q1), Some(q2)) => q1.resolved_eq(q2) && f.name() == name,
                (None, None) => f.name() == name,
                _ => false,
            })
            .take(2)
            .count();
        if count > 1 {
            _schema_err!(SchemaError::AmbiguousReference {
                field: Column {
                    relation: None,
                    name: name.to_string(),
                },
            })
        } else {
            Ok(())
        }
    }
```

Comment (HuSen8891) [reply datafusion/common/src/dfschema.rs:416]: Fixed. Thanks!

Comment (jonahgao) [reply datafusion/common/src/dfschema.rs:416]: It looks like we no longer need to add these two functions🤔, `qualified_field_with_qualified_name` and `qualified_fields_with_qualified_name`, along with the modifications to `qualified_field_with_name`

Comment (HuSen8891) [reply datafusion/common/src/dfschema.rs:416]: These two functions will check the ambiguous column reference, it's necessary, or we could not identify the case below:

create table t1(v1 int);

select count(*)
from t1
right outer join t1
on t1.v1 > 0;

Comment (jonahgao) [reply datafusion/common/src/dfschema.rs:416]: We also need add `check_ambiguous_name` at [L132](https://github.com/apache/datafusion/blob/21e35eeb4e106835cc059205315d94ad0201a921/datafusion/sql/src/expr/identifier.rs#L146).

The changes to `qualified_field_with_name` will cause the following query to produce an incorrect result.
```sh
DataFusion CLI v41.0.0
> create table t1(v1 int) as values(100);
0 row(s) fetched.

> select t1.v1 from t1 join t1 using(v1) cross join (select struct('foo' as v1) as t1);
+--------+
| t1[v1] |
+--------+
| foo    |
+--------+
```
On the main branch, it gives
```sh
> select t1.v1 from t1 join t1 using(v1) cross join (select struct('foo' as v1) as t1);
+-----+
| v1  |
+-----+
| 100 |
+-----+
```
This is because it breaks [search_dfschema](https://github.com/apache/datafusion/blob/21e35eeb4e106835cc059205315d94ad0201a921/datafusion/sql/src/expr/identifier.rs#L274), making it unable to find `t1.v1`, but instead found the nested column `t1`.

Comment (HuSen8891) [reply datafusion/common/src/dfschema.rs:416]: Is column reference 't1.v1' ambiguous in below query ?

`select t1.v1 from t1 join t1 using(v1) cross join (select struct('foo' as v1) as t1);`

**Review by jonahgao — APPROVED** [review]
Looks good to me👍 Thanks @HuSen8891 ❤️

File: datafusion/sqllogictest/test_files/join.slt [hunk 5]
```diff
@@ -1209,3 +1209,20 @@ drop table t1;
 
 statement ok
 drop table t2;
+
+# Test SQLancer issue: https://github.com/apache/datafusion/issues/12337
+statement ok
+create table t1(v1 int) as values(100);
+
+## Query with Ambiguous column reference
+query error DataFusion error: Schema error: Ambiguous reference to unqualified field v1
```
Comment (jonahgao) [inline datafusion/sqllogictest/test_files/join.slt:1218]: I think it should be an "Ambiguous reference to qualified field", but currently the SchemaError cannot describe it, so the current situation is acceptable to me.

**Comment by jonahgao** [comment]
We may check ambiguous names during `search_dfschema` to achieve one pass search. However, before doing this, it would be better to remove the following logic; otherwise, the code in `dfschema.rs` will become too redundant.

https://github.com/apache/datafusion/blob/eaf8d162ca3dcfa4a0abe9d77b660cdf1433373c/datafusion/common/src/dfschema.rs#L358-L369

On the other hand, having a separate `check_ambiguous_name` in the current implementation would be clearer.

Let's merge it first, and then explore other optimization possibilities later.

File: datafusion/sqllogictest/test_files/join.slt [hunk 6]
```diff
@@ -1209,3 +1209,20 @@ drop table t1;
...
+select count(*)
+from t1
+right outer join t1
+on t1.v1 > 0;
+
+query error DataFusion error: Schema error: Ambiguous reference to unqualified field v1
+select t1.v1 from t1 join t1 using(v1) cross join (select struct('foo' as v1) as t1);
```
Comment (jonahgao) [inline datafusion/sqllogictest/test_files/join.slt:1225]: 👍

File: datafusion/sqllogictest/test_files/join.slt (hunk 5 above)
Comment (eejbyfeldt) [reply datafusion/sqllogictest/test_files/join.slt:1218]: How is this error different from `DuplicatedQualifiedField`?
https://github.com/apache/datafusion/blob/main/datafusion/common/src/error.rs#L149-L152

Comment (jonahgao) [reply datafusion/sqllogictest/test_files/join.slt:1218]: `DuplicatedQualifiedField` was used to check the schema during its creation. After PR 6091, we allow duplicate qualified fields in the schema, so this error is no longer used.
