### PR TITLE
fix: make `columnize_expr` resistant to display_name collisions

### LINKED ISSUE #10413: Incorrect results with expression resolution
### Describe the bug

DataFusion will sometimes resolve expressions incorrectly when the alias shadows an expression

### To Reproduce

```sql
DataFusion CLI v37.1.0
> select a + b from (select 1 as a, 2 as b, 1 as "a + b");
+-------+
| a + b |
+-------+
| 1     | <- Should be 3
+-------+
1 row(s) fetched.
Elapsed 0.009 seconds.
```

### Expected behavior

Result should be 3

### Additional context

This was found by @peter-toth  in https://github.com/apache/datafusion/pull/10396

### PR DESCRIPTION
**Pull request by jonahgao**
## Which issue does this PR close?

Closes #10413.

### Background
[`columnize_expr`](https://github.com/apache/datafusion/blob/8cc92a921f3b0296caf035edb66a4b3c422f084d/datafusion/expr/src/logical_plan/builder.rs#L1413) is used during planning projections.  Usually, a projected expr can only reference the output data of the input plan through a column reference, but this does not work for aggregation and window functions. For example
```rust
let aggr_expr = sum(col("c2"));
let df = test_table()
      .await?
      .aggregate(vec![], vec![aggr_expr.clone()])?
      .select(vec![aggr_expr])?;
```
The aggregate expression `sum(col("c2"))` is calculated in the aggregate logical plan, and the projection plan references its result through the aggregate expression directly. To make it work appropriately, we need to convert the aggregate expression in the projection into a column reference of the aggregate plan, which is done by `columnize_expr`.

### Problem And Fix
Previously, `columnize_expr` [searched](https://github.com/apache/datafusion/blob/721974456742bf44bdae291b3114bc23fe478bcd/datafusion/expr/src/utils.rs#L772) for the corresponding column from the input schema through the display name of projected expr. However, different expressions may have the same display name. It is easy to reproduce by creating the same alias for another differenct expression. Collisions of display name will cause `columnize_expr` to find the wrong column, producing incorrect results as in issue #10413.

The fix is to search from input plan's output expressions directly based on the expression itself, instead of searching by display name.

## What changes are included in this PR?
Refactor columnize_expr so that it can correctly find the column corresponding to the expression.

## Are these changes tested?
Yes. 

## Are there any user-facing changes?
Yes. columnize_expr is a public method, although it may only be used internally in DataFusion.

### CODE REVIEW

File: datafusion/optimizer/src/single_distinct_to_groupby.rs [hunk 1]
```diff
@@ -280,11 +261,7 @@ impl OptimizerRule for SingleDistinctToGroupBy {
                         outer_group_exprs,
                         outer_aggr_exprs,
                     )?);
-
-                    Ok(Some(LogicalPlan::Projection(Projection::try_new(
-                        alias_expr,
-                        Arc::new(outer_aggr),
-                    )?)))
+                    Ok(Some(project(outer_aggr, alias_expr)?))
```
Comment (jonahgao) [inline datafusion/optimizer/src/single_distinct_to_groupby.rs:264]: The function `project()` will internally call `columnize_expr`, which can simplify the code here.

File: datafusion/optimizer/src/common_subexpr_eliminate.rs [hunk 2]
```diff
@@ -1154,12 +1154,12 @@ mod test {
         let table_scan = test_table_scan()?;
 
         let plan = LogicalPlanBuilder::from(table_scan)
-            .project(vec![lit(1) + col("a")])?
+            .project(vec![lit(1) + col("a"), col("a")])?
```
Comment (jonahgao) [inline datafusion/optimizer/src/common_subexpr_eliminate.rs:1157]: It corresponds to `select a+1 from (select a+1 from t)`, which is not a valid query.
```sh
> select a+1 from (select a+1 from t);
Schema error: No field named a. Valid fields are "t.a + Int64(1)"
```

File: datafusion/core/tests/dataframe/mod.rs [hunk 3]
```diff
@@ -210,7 +210,6 @@ async fn test_count_wildcard_on_aggregate() -> Result<()> {
     let sql_results = ctx
         .sql("select count(*) from t1")
         .await?
-        .select(vec![count(wildcard())])?
```
Comment (jonahgao) [inline datafusion/core/tests/dataframe/mod.rs:213]: Select an aggregation expression on top of a Projection plan should be invalid.

Comment (alamb) [reply datafusion/core/tests/dataframe/mod.rs:213]: I agree that this tests is not a valid.

Perhaps it meant to show how to select the count(*) again -- if so maybe we could update the tests to do  something like this (rather than removing it entirely):

```
        .select(vec![col("COUNT(*)")])?
```

File: datafusion/sqllogictest/test_files/select.slt [hunk 4]
```diff
@@ -1619,7 +1619,16 @@ select count(1) from v;
 query I
 select a + b from (select 1 as a, 2 as b, 1 as "a + b");
 ----
-1
+3
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/select.slt:1622]: 🎉

File: datafusion/optimizer/src/single_distinct_to_groupby.rs [hunk 5]
```diff
@@ -228,37 +228,18 @@ impl OptimizerRule for SingleDistinctToGroupBy {
                         .collect::<Result<Vec<_>>>()?;
 
                     // construct the inner AggrPlan
```
Comment (alamb) [inline datafusion/optimizer/src/single_distinct_to_groupby.rs:230]: FYI @appletreeisyellow  - this PR contains some changes which may conflict with https://github.com/apache/datafusion/issues/10295

File: datafusion/expr/src/logical_plan/plan.rs [hunk 6]
```diff
@@ -2528,6 +2568,14 @@ impl Aggregate {
         })
     }
 
+    /// Get the output expressions.
+    fn output_expressions(&self) -> Result<Vec<Expr>> {
```
Comment (alamb) [inline datafusion/expr/src/logical_plan/plan.rs:2572]: We have been trying to remove copies from the optimizer (see https://github.com/apache/datafusion/issues/9637) and this API forces a copy.

I wonder if we could avoid copies by returning references here instead 🤔  I looked at the above code and it wasn't immediately clear we could do so

```suggestion
    fn output_expressions(&self) -> Result<Vec<&Expr>> {
```

I think then you could have like this perhaps

```rust
    pub(crate) fn columnized_output_exprs(&self) -> Result<Vec<(&Expr, Column)>> {
```

**Review by alamb — APPROVED** [review]
Thank you @jonahgao  -- I went through this PR quite carefully and it looks really nice to me ❤️ 

I made a note of some place we maybe could avoid some clones, but I don't think it is required

cc @peter-toth and @erratic-pattern

File: datafusion/core/tests/dataframe/mod.rs (hunk 3 above)
Comment (jonahgao) [reply datafusion/core/tests/dataframe/mod.rs:213]: Fixed. Thank you @alamb

File: datafusion/expr/src/logical_plan/plan.rs (hunk 6 above)
Comment (jonahgao) [reply datafusion/expr/src/logical_plan/plan.rs:2572]: We can't do this now because [grouping_set_to_exprlist](https://github.com/jonahgao/datafusion/blob/131d1a96e64e84a01b954d7f5658976cbb64e83a/datafusion/expr/src/logical_plan/plan.rs#L2573) returns a temporary `Vec<Expr>`.

We need to first remove the copies in `grouping_set_to_exprlist`, and also need to modify [`exprlist_to_fields`](https://github.com/jonahgao/datafusion/blob/131d1a96e64e84a01b954d7f5658976cbb64e83a/datafusion/expr/src/logical_plan/plan.rs#L2515). `exprlist_to_fields` is referenced in many places. Maybe we can try to do this in subsequent PRs.

**Review by alamb — APPROVED** [review]
This looks awesome -- thank you @jonahgao  

Really really nice

**Comment by jonahgao** [comment]
Thanks for reviewing @alamb .
