### PR TITLE
repro and disable dyn filter for preserve file partitions

### LINKED ISSUE #20176: incorrect dynamic filter on partitioned join when file partitioned
### Describe the bug

When preserving file partitioning we claim "hash" partitioned on the columns values. Then when applying a dynamic filter for partitioned joins it creates a filter based on a true hash function, not key/value based like file partitioning. This causes partitions to be filtered incorrectly:

```text
Declare file partitioned: Hash([partition_col], N)
Filter with hash-based routing:
  CASE hash(key) % N
    WHEN 0 THEN <partition 0 bounds>
    WHEN 1 THEN <partition 1 bounds>
    ...

Since file partitioned is using value based partitioning and dynamic filtering is using true hash based end of in this scenario:
  ┌─────┬──────────────────────┬───────────────┐
  │ Key │ Hive Partition Index │ hash(key) % 3 │
  ├─────┼──────────────────────┼───────────────┤
  │ "A" │ 0                    │ 2             │
  ├─────┼──────────────────────┼───────────────┤
  │ "B" │ 1                    │ 2             │
  ├─────┼──────────────────────┼───────────────┤
  │ "C" │ 2                    │ 2             │
  └─────┴──────────────────────┴───────────────┘

thus, when the filter evaluates row f_dkey=A, the filter computes it to map to partition 2 bounds even though it is actually in partition 0. So it doesn't match and is incorrectly filtered out.
```

### To Reproduce

see PR: #20175 

### Expected behavior

For now dynamic filtering will be disabled for partitioned hash joins when preserve file partitions is on.

A long term fix is to introduce a new type of partitioning for the file partitioning to safely distinguish the two. Something like `KeyPartitoned` or `ValuePartitioned` is suiting.

Oracle calls this [`ListPartitioning`](https://docs.oracle.com/en/database/oracle/oracle-database/26/cncpt/partitions-views-and-other-schema-objects.html)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by gene-bordegaray**
## Which issue does this PR close?

  

  - Closes #20176
  - Discussed this with @adriangb 

  ## Rationale for this change

  

Dynamic filter pushdown can produce incorrect results when `preserve_file_partitions` is enabled and a partitioned hash join is used. The file groups are Hive‑partitioned (value‑based) but reported as hash‑partitioned, so hash‑routed dynamic filters can drop valid rows.

  ## What changes are included in this PR?

  

  - Disable join dynamic filter pushdown for `PartitionMode::Partitioned` when `preserve_file_partitions > 0`.
  - Add two sqllogictests that reproduce the issue and validate the fix.

  ## Are these changes tested?

  

  - `cargo test --test sqllogictests -- preserve_file_partitioning` -> will pass
  - `git checkout main ‎datafusion/physical-plan/src/joins/hash_join/exec.rs`
  - `cargo test --test sqllogictests -- preserve_file_partitioning` -> will fail

  ## Are there any user-facing changes?

  

Join dynamic filter pushdown is disabled when `preserve_file_partitions` is enabled and the join is partitioned.

  

cc: @NGA-TRAN @gabotechs

### CODE REVIEW

File: datafusion/physical-plan/src/joins/hash_join/exec.rs [hunk 1]
```diff
@@ -609,6 +609,24 @@ impl HashJoinExec {
...
+            return false;
+        }
+
+        // `preserve_file_partitions` can report Hash partitioning for Hive-style
+        // file groups, but those partitions are not actually hash-distributed.
+        // Partitioned dynamic filters rely on hash routing, so disable them in
+        // this mode to avoid incorrect results.
+        if config.optimizer.preserve_file_partitions > 0
+            && self.mode == PartitionMode::Partitioned
+        {
```
Comment (gabotechs) [inline datafusion/physical-plan/src/joins/hash_join/exec.rs:625]: I imagine we'd want this at some point. Is there any issue we can link here?

**Review by gabotechs — APPROVED** [review]

File: datafusion/physical-plan/src/joins/hash_join/exec.rs (hunk 1 above)
Comment (gene-bordegaray) [reply datafusion/physical-plan/src/joins/hash_join/exec.rs:625]: I can make an issue today and will link

**Review by NGA-TRAN — APPROVED** [review]
This is a good PR to prevent incorrect results.
In the near future, we want to support dynamic filtering for this use case, too

**Review by adriangb — APPROVED** [review]
LGTM pending https://github.com/apache/datafusion/pull/20175/changes#r2773583210

File: datafusion/physical-plan/src/joins/hash_join/exec.rs (hunk 1 above)
Comment (gene-bordegaray) [reply datafusion/physical-plan/src/joins/hash_join/exec.rs:625]: Should I link in PR or comment itself?

Here is issue: https://github.com/apache/datafusion/issues/20195

cc: @adriangb @gabotechs

**Comment by gene-bordegaray** [comment]
> but if users can specify this, should partitioning be a trait? 🤔

this is a really great idea and something that @fmonjalet brought up. I think that partitioning being a trait would be very valuable. I have mentioned follow up work in #20195 to explore this

File: datafusion/physical-plan/src/joins/hash_join/exec.rs (hunk 1 above)
Comment (gene-bordegaray) [reply datafusion/physical-plan/src/joins/hash_join/exec.rs:625]: I will assume the comment, can't hurt

**Comment by gene-bordegaray** [comment]
quick bump on this guy @gabotechs

**Comment by gabotechs** [comment]
Merged!
