### PR TITLE
fix: create file for empty stream

### LINKED ISSUE #16240: How to write csv file to disk from a empty dataframe?
I want write a csv file only include headers;

```
use datafusion::config::CsvOptions;
use datafusion::dataframe::DataFrameWriteOptions;
use datafusion::error::Result;
use datafusion::prelude::*;
use std::path::Path;

#[tokio::main]
async fn main() -> Result<()> {
    let ctx = SessionContext::new();

    let df = ctx.sql("SELECT 1 limit 0").await?;

    let mut cfg1 = DataFrameWriteOptions::new();
    cfg1 = cfg1.with_single_file_output(true);

    let mut cfg2 = CsvOptions::default();
    cfg2.has_header = Some(true);

    df.write_csv("/tmp/t.csv", cfg1, Some(cfg2)).await?;
    assert_eq!(Path::new("/tmp/t.csv").exists(), true);  // panic!
    Ok(())
}
```

### PR DESCRIPTION
**Pull request by chenkovsky**
## Which issue does this PR close?

- Closes #16240.

## Rationale for this change

file won't be created for empty dataframe

## What changes are included in this PR?

create file if row number is zero

## Are these changes tested?

UT

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by mmooyyii** [comment]
Maybe add same test for write_parquet and write_json?  I think they should have same behavior.

File: datafusion/core/src/datasource/file_format/csv.rs [hunk 1]
```diff
@@ -795,6 +796,25 @@ mod tests {
         Ok(())
     }
 
+    #[tokio::test]
+    async fn test_csv_write_empty_file() -> Result<()> {
```
Comment (alamb) [inline datafusion/core/src/datasource/file_format/csv.rs:800]: Can you please also add a test of what happens if we are writing into a directory (aka a partitioned file)? 

Like a test that targets a path of `/foo`

In this case, I think I would expect that no files are created when the data stream is empty

File: datafusion/datasource/src/file_sink_config.rs [hunk 2]
```diff
@@ -77,13 +79,32 @@ pub trait FileSink: DataSink {
...
-        .await
+        let mut num_rows = self
+            .spawn_writer_tasks_and_join(
+                context,
+                demux_task,
+                file_stream_rx,
+                Arc::clone(&object_store),
+            )
+            .await?;
+        if num_rows == 0 {
```
Comment (alamb) [inline datafusion/datasource/src/file_sink_config.rs:90]: I think it would help here to add some comments with context about what it is doing. For example, something like

```suggestion
        // If no rows were written, then no files are output either. In this case 
        // send an empty record batch through to ensure the output file is generated
        if num_rows == 0 {
```

**Review by alamb — APPROVED** [review]
Thank you @chenkovsky

File: datafusion/datasource/src/file_sink_config.rs [hunk 3]
```diff
@@ -77,13 +79,34 @@ pub trait FileSink: DataSink {
...
+            // If no rows were written, then no files are output either.
```
Comment (brunal) [inline datafusion/datasource/src/file_sink_config.rs:91]: You say now row => no file was created.

But then you say write an empty recordbatch => ensure a file gets created.

Except an empty recordbatch has no rows (at least when written to a parquet file).

Your 2 sentences don't make sense together.

In practice, this PR caused a regression: we cannot write empty recordbatch to parquet anymore,  as the code here tries to write it a second time, and we get an error.

**Review by brunal — CHANGES_REQUESTED** [review]

**Comment by brunal** [comment]
User facing breakage: one cannot explicitly write an empty recordbatch that has a schema anymore.

The tests in the PR don't have a schema so they don't reveal the issue.

**Comment by brunal** [comment]
How can i send a rollback of this PR?

File: datafusion/datasource/src/file_sink_config.rs (hunk 3 above)
Comment (chenkovsky) [reply datafusion/datasource/src/file_sink_config.rs:91]: Hi, I didn't reproduce you problem. could you please share your test. I will check it ASAP

Comment (chenkovsky) [reply datafusion/datasource/src/file_sink_config.rs:91]: @alamb I think we need to define 'empty' in datafusion clearly. currently it's vec![] https://github.com/apache/datafusion/blob/a7151730a6c65a62793d293557ca15e975fcb701/datafusion/physical-plan/src/empty.rs#L70 , I guess brunal uses `vec![empty_record_batch]`.

Comment (brunal) [reply datafusion/datasource/src/file_sink_config.rs:91]: Indeed, I write one empty RecordBatch. Here is a short repro of the issue: https://github.com/brunal/datafusion/commit/aed5316583ecae7901d9596039ca4bfe7cd48811.

I don't think num_rows should be used to determine whether a file was created.

**Comment by alamb** [comment]
- Reverted in https://github.com/apache/datafusion/pull/16682
