### PR TITLE
fix: `DataFrame::select_columns` and `DataFrame::drop_columns` for qualified duplicated field names

### LINKED ISSUE #18212: Unable to drop the mark column added by `JoinType::LeftMark` if there are multiple joins
### Describe the bug

When I join a table using `JoinType::LeftMark`, a `mark` column will be added to the results. I am able to drop this column by calling `.drop_columns(&["mark"])`. However, when join two tables using this join type, I am not able to drop this column.

### To Reproduce

```rs
use std::sync::Arc;

use arrow::array::{RecordBatch, StringArray, UInt8Array};
use arrow::datatypes::{DataType, Field, Schema};
use arrow::util::pretty::print_batches;
use datafusion::catalog::MemTable;
use datafusion::common::JoinType;
use datafusion::prelude::{col, lit, when, SessionContext};


#[tokio::main]
async fn main() {
    let schema1 = Arc::new(Schema::new(vec![
        Field::new("id", DataType::UInt8, false),
        Field::new("name", DataType::Utf8, false)
    ]));

    let rb1 = RecordBatch::try_new(schema1.clone(), vec![
        Arc::new(UInt8Array::from_iter_values(vec![0, 1, 2, 3])),
        Arc::new(StringArray::from_iter_values(vec!["a", "b", "c", "d"]))
    ]).unwrap();


    let schema2 = Arc::new(Schema::new(vec![
        Field::new("parent_id", DataType::UInt8, false),
        Field::new("key", DataType::Utf8, false),
        Field::new("val", DataType::Utf8, false)
    ]));

    let rb2 = RecordBatch::try_new(schema2.clone(), vec![
        Arc::new(UInt8Array::from_iter_values(vec![0, 1])),
        Arc::new(StringArray::from_iter_values(vec!["k1", "k2"])),
        Arc::new(StringArray::from_iter_values(vec!["v1", "v2"])),
    ]).unwrap();

    let rb3 = RecordBatch::try_new(schema2.clone(), vec![
        Arc::new(UInt8Array::from_iter_values(vec![1, 2])),
        Arc::new(StringArray::from_iter_values(vec!["k1", "k2"])),
        Arc::new(StringArray::from_iter_values(vec!["v1", "v2"])),
    ]).unwrap();
    
    let ctx = SessionContext::new();

    ctx.register_table("table1", Arc::new(MemTable::try_new(schema1.clone(), vec![vec![rb1]]).unwrap())).unwrap();
    ctx.register_table("table2", Arc::new(MemTable::try_new(schema2.clone(), vec![vec![rb2]]).unwrap())).unwrap();
    ctx.register_table("table3", Arc::new(MemTable::try_new(schema2.clone(), vec![vec![rb3]]).unwrap())).unwrap();

    // Here is an example where dropping the `mark` column works as expected.
    // By way of a motivating example, imagine I am trying to do the following:
    // Add `ok = true` column where there's an associated record in table2
    let results = ctx.table("table1").await.unwrap()
        .join(
            ctx.table("table2").await.unwrap(),
            JoinType::LeftMark,
            &["id"],
            &["parent_id"],
            None
        )
        .unwrap()
        .with_column("ok", when(col("mark").eq(lit(true)), lit(true)).end().unwrap())
        .unwrap()
        // this works as expected, drops the mark column
        .drop_columns(&["mark"])
        .unwrap()
        .collect()
        .await
        .unwrap();

    println!("result 1");
    print_batches(&results).unwrap();
    // prints:
    // result 1
    // +----+------+------+
    // | id | name | ok   |
    // +----+------+------+
    // | 0  | a    | true |
    // | 1  | b    | true |
    // | 2  | c    |      |
    // | 3  | d    |      |
    // +----+------+------+

    // Here is an example where I'm not able to drop the `mark` column. Say for example
    // that I'm trying to do the following:
    // Add `ok = true` column where there's an associated record in table2 and table3
    let results = ctx.table("table1").await.unwrap()
        .join(
            ctx.table("table2").await.unwrap(),
            JoinType::LeftMark,
            &["id"],
            &["parent_id"],
            None
        )
        .unwrap()
        .join(
            ctx.table("table3").await.unwrap(),
            JoinType::LeftMark,
            &["id"],
            &["parent_id"],
            None
        )
        .unwrap()
        .with_column(
            "ok",
            when(
                col("table2.mark").eq(lit(true)).and(col("table3.mark").eq(lit(true))),
                lit(true)
            ).end().unwrap())
        .unwrap()
        // this doesn't work:
        // .drop_columns(&["mark"])
        // neither does this
        .drop_columns(&["table2.mark", "table3.mark"])
        .unwrap()
        .collect()
        .await
        .unwrap();

    println!("result 2");
    print_batches(&results).unwrap()
    // prints:
    // result 2
    // +----+------+-------+-------+------+
    // | id | name | mark  | mark  | ok   |
    // +----+------+-------+-------+------+
    // | 0  | a    | true  | false |      |
    // | 1  | b    | true  | true  | true |
    // | 2  | c    | false | true  |      |
    // | 3  | d    | false | false |      |
    // +----+------+-------+-------+------+
}
```

### Expected behavior

I would expect that in my second result above, that I am able to drop the `mark` columns by doing either `.drop_columns(&["mark"])` or `.drop_columns(&["table2.mark", "table3.mark"])`

### Additional context

Using DataFusion version 50.2

### PR DESCRIPTION
**Pull request by dqkqd**
## Which issue does this PR close?

- Closes #18212.

## Rationale for this change

`DataFrame::drop_columns` only considers one field for each `name`,
it fails to drop columns from dataframe containing duplicated names
from different relations. Such as `mark` columns created by multiples 
`Join::LeftMark`.

`DataFrame::select_columns` has the same issue, it fails to select columns
with the same name from different relations.

## What changes are included in this PR?

Allow `DataFrame::drop_columns` and `DataFrame::select_columns`
work with duplicated names from different relations.

## Are these changes tested?

Yes.

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/core/tests/dataframe/mod.rs [hunk 1]
```diff
@@ -405,6 +405,55 @@ async fn select_with_periods() -> Result<()> {
...
+    +----+----+----+
+    | b  | b  |    |
+    | b  | b  |    |
+    | c  |    |    |
+    | d  |    | d  |
+    +----+----+----+
+    "
+    );
+
+    let select_res = join_res.select_columns(&["c1"])?;
```
Comment (dqkqd) [inline datafusion/core/tests/dataframe/mod.rs:439]: This line returned `SchemaError` without the code changes.

```
    Error: SchemaError(AmbiguousReference { field: Column { relation: None, name: "c1" } }, Some(""))
```

File: datafusion/core/tests/dataframe/mod.rs [hunk 2]
```diff
@@ -543,6 +592,54 @@ async fn drop_with_periods() -> Result<()> {
...
+    +----+
+    | b  |
+    | c  |
+    | d  |
+    +----+
+    "
+    );
+
+    Ok(())
+}
```
Comment (dqkqd) [inline datafusion/core/tests/dataframe/mod.rs:640]: This failed without the code changes

```
    running 1 test
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    Snapshot: drop_columns_duplicated_names_from_different_qualifiers-2
    Source: datafusion/core/tests/dataframe/mod.rs:627
    ────────────────────────────────────────────────────────────────────────────────
    Expression: batches_to_sort_string(&drop_res.clone().collect().await.unwrap())
    ────────────────────────────────────────────────────────────────────────────────
    -old snapshot
    +new results
    ────────────┬───────────────────────────────────────────────────────────────────
        1       │-+----+
        2       │-| c1 |
        3       │-+----+
        4       │-| b  |
        5       │-| c  |
        6       │-| d  |
        7       │-+----+
              1 │++----+-------+-------+
              2 │+| c1 | mark  | mark  |
              3 │++----+-------+-------+
              4 │+| b  | true  | false |
              5 │+| c  | false | false |
              6 │+| d  | false | true  |
              7 │++----+-------+-------+
    ────────────┴───────────────────────────────────────────────────────────────────
    To update snapshots run `cargo insta review`
    Stopped on the first failure. Run `cargo insta test` to run all snapshots.
    test dataframe::drop_columns_duplicated_names_from_different_qualifiers ... FAILED

    failures:

    failures:
        dataframe::drop_columns_duplicated_names_from_different_qualifiers

    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 769 filtered out; finished in 0.17s
```

**Review by alamb — APPROVED** [review]
Thank  you @dqkqd and @albertlockett  🙏
