### PR TITLE
ci: fix clippy failures on main

### LINKED ISSUE #10902: ci: clippy failed on main
### Describe the bug

The release of a new version of Rust likely caused it.
https://blog.rust-lang.org/2024/06/13/Rust-1.79.0.html

### To Reproduce

Failed job: https://github.com/apache/datafusion/actions/runs/9501682032/job/26188186709

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jonahgao**
## Which issue does this PR close?

Closes #10902.

## Are these changes tested?
Yes

## Are there any user-facing changes?
No

### CODE REVIEW

File: datafusion/physical-expr/src/window/window_expr.rs [hunk 1]
```diff
@@ -559,7 +559,6 @@ pub enum NthValueKind {
 
 #[derive(Debug, Clone)]
 pub struct NthValueState {
-    pub range: Range<usize>,
```
Comment (jonahgao) [inline datafusion/physical-expr/src/window/window_expr.rs:562]: field `range` is never read. Not sure if it will still be used in the future. cc @mustafasrepo

**Review by alamb — APPROVED** [review]
Looks good to me - thank you very much @jonahgao
