### PR TITLE
fix(sql): fix a bug when planning semi- or antijoins

### LINKED ISSUE #20989: `exclude_using_columns ` might wrongly retain columns from a projected join input
### Describe the bug

Currently, the `exclude_using_columns` called from `expand_wildcard` doesn't consider the filtering semantics of semi- and antijoins when expanding wildcards on top of joins defined via `USING(<columns>)` syntax.

From each set of columns equated by a `USING(<column>)` expression, the code currently (1) sorts the set entries, and (2) retains only the first entry from each set.

Because of that, the columns surviving the `exclude_using_columns` call might be wrongly chosen from the filtering side if the table qualifier from that side is sorted before the filtered side qualifier.

### To Reproduce

For example, given this schema of two identical tables:

```sql
create table s(x1 int, x2 int, x3 int);
create table t(x1 int, x2 int, x3 int);
```

One would expect that the schema of queries where the `s` and `t` names are swapped will be identical. However, currently this is not  the case:

```sql
-- Q1 schema: x1 int, x2 int, x3 int (because s < t)
select * from s left semi join t using (x1);

-- Q2 schema: x2 int, x3 int (x1 is wrongly excluded because t < s)
select * from t left semi join s using (x1);
```

### Expected behavior

I expect the schemas of Q1 and Q2 to be identical.

### Additional context

I have a fix for that, for which I will open a PR shortly.

### PR DESCRIPTION
**Pull request by aalexandrov**
- Closes #20989.

## Rationale for this change

The planner should be consistent with the expected SQL behavior—swapping the names of tables that have identical structure in a SQL query should not affect the schema for that query.

## What changes are included in this PR?

- A fix in the `exclude_using_columns` helper method in `datafusion/expr/src/utils.rs` that ensures that we don't retain columns from the projected side when deciding which USING columns to exclude and which to retain on top of semi- or antijoins.
- Regression tests for the change in `test_using_join_wildcard_schema_semi_anti`.

## Are these changes tested?

- Added a regression test.

## Are there any user-facing changes?

Yes, the change is user facing, but I doubt that this behavior is expected and is documented anywhere.
If existing docs need to be updated, please point me to the concrete places and I can take a look.

### CODE REVIEW

File: datafusion/sql/tests/sql_integration.rs [hunk 1]
```diff
@@ -4847,6 +4847,40 @@ fn test_using_join_wildcard_schema() {
...
 
+#[test]
+fn test_using_join_wildcard_schema_semi_anti() {
+    let left_expected = vec!["s.x1".to_string(), "s.x2".to_string(), "s.x3".to_string()];
+    let right_expected = vec!["t.x1".to_string(), "t.x2".to_string(), "t.x3".to_string()];
+
+    let sql = "WITH 
+        s AS (SELECT 1 AS x1, 2 AS x2, 3 AS x3),
+        t AS (SELECT 1 AS x1, 4 AS x2, 5 AS x3)
+        SELECT * FROM s LEFT SEMI JOIN t USING (x1)";
```
Comment (neilconway) [inline datafusion/sql/tests/sql_integration.rs:5015]: This test (and the other `LEFT ANTI JOIN` test) should succeed without this PR, right? Because the correct side of the join happens to be picked. Can we change this (or add a new test variant) that checks that the behavior has changed for `LEFT` joins?

File: datafusion/sql/tests/sql_integration.rs [hunk 2]
```diff
@@ -4847,6 +4847,40 @@ fn test_using_join_wildcard_schema() {
     );
 }
 
+#[test]
+fn test_using_join_wildcard_schema_semi_anti() {
+    let left_expected = vec!["s.x1".to_string(), "s.x2".to_string(), "s.x3".to_string()];
+    let right_expected = vec!["t.x1".to_string(), "t.x2".to_string(), "t.x3".to_string()];
```
Comment (neilconway) [inline datafusion/sql/tests/sql_integration.rs]:
```suggestion
    let left_expected = &["s.x1", "s.x2", "s.x3"];
    let right_expected = &["t.x1", "t.x2", "t.x3"];
```

File: datafusion/expr/src/utils.rs
Comment (neilconway) [inline datafusion/expr/src/utils.rs]: It took me a while to wrap my head around the logic here; what do you think of this instead?

```suggestion
  /// When a JOIN has a USING clause, the join columns appear in the output
  /// schema once per side (for inner/outer joins) or once total (for semi/anti
  /// joins). An unqualified wildcard should include each USING column only once.
  /// This function returns the duplicate columns that should be excluded.
  fn exclude_using_columns(plan: &LogicalPlan) -> Result<HashSet<Column>> {
      let output_columns: HashSet<_> = plan.schema().columns().iter().cloned().collect();
      let mut excluded = HashSet::new();

      for cols in plan.using_columns()? {
          // `using_columns()` returns join columns from both sides regardless
          // of join type. For semi/anti joins, only one side's columns appear
          // in the output schema. Filter to output columns so that columns
          // from the non-output side don't participate in deduplication and
          // displace real output columns.
          let mut cols: Vec<_> = cols
              .into_iter()
              .filter(|c| output_columns.contains(c))
              .collect();
              
          // Sort so we keep the same qualified column, regardless of HashSet
          // iteration order.
          cols.sort();

          let mut seen = HashSet::new();
          for col in cols {
              if !seen.insert(col.name.clone()) {
                  excluded.insert(col);
              }
          }
      }

      Ok(excluded)
  }
```

File: datafusion/sql/tests/sql_integration.rs (hunk 1 above)
Comment (aalexandrov) [reply datafusion/sql/tests/sql_integration.rs:5015]: Done.

File: datafusion/expr/src/utils.rs
Comment (aalexandrov) [reply datafusion/expr/src/utils.rs]: I don't have a strong preference here—in the initial PR I was trying to do the minimal amount of changes to the existing method definition to fix the error.

I did some cosmetic changes to your suggestion and added it to the PR. In addition, went with this variation of the `for`-loop body

```rust
if seen_names.contains(col.name.as_str()) {
    excluded.insert(col); // exclude columns with already seen name
} else {
    seen_names.insert(col.name.clone()); // mark column name as seen
}
```
because `seen_names.contains(col.name.clone())` will create unnecessary `String` clones for ~50% of the `cols` entries.

**Review by alamb — APPROVED** [review]
Thanks -- this mkes sense to me @aalexandrov 

Thanks for the review @neilconway
