### PR TITLE
Fix SortMergeJoin with join filter filtering all rows out

### LINKED ISSUE #10491: SortMergeJoin: The query stuck when join filter is set and more matched rows than batch size
I'm not able to run such test just because of other SMJ issue not related to this PR:
If the join filter is set and for the same streaming index there are matching rows more or equal to a batch size then the query just stuck. Likely the problem is in polling state and it can be easily reproduced on main branch.

```
  #[tokio::test]
    async fn test_11() -> Result<()> {
        let ctx: SessionContext = SessionContext::new();

        let sql = "set datafusion.optimizer.prefer_hash_join = false;";
        let _ = ctx.sql(sql).await?.collect().await?;

        let sql = "set datafusion.execution.batch_size = 1";
        let _ = ctx.sql(sql).await?.collect().await?;

        let sql = "
        select * from (
        with
        t1 as (
            select 12 a, 12 b
            ),
        t2 as (
            select 12 a, 12 b
            )
            select t1.* from t1 join t2 on t1.a = t2.b where t1.a > t2.b
        ) order by 1, 2;
        ";

        let actual = ctx.sql(sql).await?.collect().await?;


        Ok(())
    }
```

I'll file a separate issue for this one, but perhaps we can go with this PR because potential problem you talking about cannot ever be hit because of the  issue above

_Originally posted by @comphead in https://github.com/apache/datafusion/pull/10304#discussion_r1599255387_

### PR DESCRIPTION
**Pull request by viirya**
## Which issue does this PR close?

Closes #10491.

### CODE REVIEW

File: datafusion/core/tests/sql/joins.rs [hunk 1]
```diff
@@ -231,3 +231,32 @@ async fn join_change_in_planner_without_sort_not_allowed() -> Result<()> {
...
+async fn test_smj_with_join_filter_fitering_all() -> Result<()> {
+    let ctx: SessionContext = SessionContext::new();
+
+    let sql = "set datafusion.optimizer.prefer_hash_join = false;";
+    let _ = ctx.sql(sql).await?.collect().await?;
+
+    let sql = "set datafusion.execution.batch_size = 1";
+    let _ = ctx.sql(sql).await?.collect().await?;
+
+    let sql = "
```
Comment (alamb) [inline datafusion/core/tests/sql/joins.rs:245]: is there any reason this isn't a slt test (in https://github.com/apache/datafusion/blob/main/datafusion/sqllogictest/test_files/sort_merge_join.slt)? Looks like it would work just fine

**Review by alamb — APPROVED** [review]
Thanks @viirya  -- looks good to me

File: datafusion/core/tests/sql/joins.rs (hunk 1 above)
Comment (viirya) [reply datafusion/core/tests/sql/joins.rs:245]: No, I simply copy the reproducer from the issue. Let me move it to sort_merge_join.slt.

File: datafusion/physical-plan/src/joins/sort_merge_join.rs [hunk 2]
```diff
@@ -1323,7 +1323,9 @@ impl SMJStream {
         // If join filter exists, `self.output_size` is not accurate as we don't know the exact
         // number of rows in the output record batch. If streamed row joined with buffered rows,
         // once join filter is applied, the number of output rows may be more than 1.
-        if record_batch.num_rows() > self.output_size {
+        // If `record_batch` is empty, we should reset `self.output_size` to 0. It could be happened
```
Comment (comphead) [inline datafusion/physical-plan/src/joins/sort_merge_join.rs:1326]: 👍

**Review by comphead — APPROVED** [review]
lgtm, thanks @viirya for quick turnaround,I agree lets please move the test to slt file

File: datafusion/sqllogictest/test_files/sort_merge_join.slt [hunk 3]
```diff
@@ -263,5 +263,22 @@ DROP TABLE t1;
 statement ok
 DROP TABLE t2;
 
+# Set batch size to 1 for sort merge join
```
Comment (comphead) [inline datafusion/sqllogictest/test_files/sort_merge_join.slt:266]:
```suggestion
# Set batch size to 1 for sort merge join to test scenario when data spread across multiple batches
```

**Comment by viirya** [comment]
Thanks @alamb @comphead
