### PR TITLE
Prevent exponential planning time for Window functions - v2

### LINKED ISSUE #17401: Exponential planning time when window function is partitioned by multiple columns
### Describe the bug

Planning time, or to be precise: optimization time, is very long for queries that have a window function partitioned by multiple columns.

### To Reproduce

```sql
WITH source AS (
    SELECT
        1 AS n,
        '' AS a1, '' AS a2, '' AS a3, '' AS a4, '' AS a5, '' AS a6, '' AS a7, '' AS a8,
        '' AS a9, '' AS a10, '' AS a11, '' AS a12
)
SELECT
    sum(n) OVER (PARTITION BY
        a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12
    )
FROM source;
```

In 48.0.1 this takes ~543 seconds. 

On current `main` this takes ~292 seconds
It looks `O(4ⁿ)`[^1] where `n` is number of columns used in `PARTITION BY`

### Expected behavior

In DataFusion 45.0.0 this query runs in <100ms.

### Additional context

_No response_

[^1]: based on timings when adding or removing a column. Definitely exponential, not sure the base.

### PR DESCRIPTION
**Pull request by berkaysynnada**
## Which issue does this PR close?

- Closes #17401.

## Rationale for this change

There is a complexity issue with window ordering calculations. Rather than computing all possibilities and eliminating the failing ones, we incrementally refine the ordering, keeping only elements that satisfy requirements.

related content: https://github.com/apache/datafusion/pull/14813, https://github.com/apache/datafusion/issues/17401, https://github.com/apache/datafusion/pull/17563

## What changes are included in this PR?

This PR implements the algorithm mentioned in the issue. There is also one minor change: the `sort_options_resolving_constant` function now generates candidates according to the intended usage. This enables a minor optimization possibility.

### CODE REVIEW

**Comment by berkaysynnada** [comment]
@findepi can you please review this? I've implemented something similar to what I'd in my mind, and I hope it will solve your problems without sacrificing anything, I don't know how to measure the improvement on my computer though

**Comment by berkaysynnada** [comment]
cc @alamb also, if you are interested in this and want to review

**Comment by alamb** [comment]
🤖 `./gh_compare_branch_bench.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/gh_compare_branch_bench.sh) Running
Linux aal-dev 6.14.0-1014-gcp #15~24.04.1-Ubuntu SMP Fri Jul 25 23:26:08 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing fix/exponential-window-ordering-calc (43f75920d849e57f4bf7530dd7d6fff8706032dc) to 03b67897ec2b2b71bf083e78a35125dc391b0e68 [diff](https://github.com/apache/datafusion/compare/03b67897ec2b2b71bf083e78a35125dc391b0e68..43f75920d849e57f4bf7530dd7d6fff8706032dc)
BENCH_NAME=sql_planner
BENCH_COMMAND=cargo bench --bench sql_planner
BENCH_FILTER=physical_window_function_partition
BENCH_BRANCH_NAME=fix_exponential-window-ordering-calc
Results will be posted here when complete

**Comment by berkaysynnada** [comment]
@findepi do you want me to take bench and slt changes from #17563 ?

**Review by comphead — APPROVED** [review]
Thanks @berkaysynnada nice to see benches though

**Comment by findepi** [comment]
> @findepi do you want me to take bench and slt changes from #17563 ?

yes, please

File: datafusion/physical-plan/src/windows/mod.rs [hunk 1]
```diff
@@ -371,18 +371,46 @@ pub(crate) fn window_equivalence_properties(
     for (i, expr) in window_exprs.iter().enumerate() {
         let partitioning_exprs = expr.partition_by();
         let no_partitioning = partitioning_exprs.is_empty();
-        // Collect columns defining partitioning, and construct all `SortOptions`
-        // variations for them. Then, we will check each one whether it satisfies
-        // the existing ordering provided by the input plan.
+
+        // Use incremental approach to avoid O(4^n) exponential complexity:
+        // Instead of generating all combinations upfront via multi_cartesian_product,
+        // we build orderings incrementally and prune invalid paths early.
```
Comment (findepi) [inline datafusion/physical-plan/src/windows/mod.rs]: ❤️

File: datafusion/physical-plan/src/windows/mod.rs [hunk 2]
```diff
@@ -371,18 +371,46 @@ pub(crate) fn window_equivalence_properties(
...
         let mut all_satisfied_lexs = vec![];
-        for lex in partitioning_exprs
-            .iter()
-            .map(|pb_order| sort_options_resolving_constant(Arc::clone(pb_order)))
-            .multi_cartesian_product()
-            .filter_map(LexOrdering::new)
-        {
-            if window_eq_properties.ordering_satisfy(lex.clone())? {
-                all_satisfied_lexs.push(lex);
+        if !no_partitioning {
```
Comment (findepi) [inline datafusion/physical-plan/src/windows/mod.rs]: This condition looks redundant.

File: datafusion/physical-plan/src/windows/mod.rs [hunk 3]
```diff
@@ -471,7 +501,7 @@ pub(crate) fn window_equivalence_properties(
                         .get_aggregate_expr()
                         .expressions()
                         .into_iter()
-                        .map(sort_options_resolving_constant)
+                        .map(|expr| sort_options_resolving_constant(expr, false))
                         .multi_cartesian_product();
```
Comment (findepi) [inline datafusion/physical-plan/src/windows/mod.rs]: this looks exponential still. when is this code path taken?

File: datafusion/physical-plan/src/windows/mod.rs [hunk 4]
```diff
@@ -371,18 +371,46 @@ pub(crate) fn window_equivalence_properties(
...
+                let mut next_orderings = vec![];
+
+                let sort_options =
+                    sort_options_resolving_constant(Arc::clone(partition_expr), true);
+
+                // For each current partial ordering, try extending with each sort option
+                for current in current_orderings.iter() {
+                    for sort_expr in sort_options.iter() {
+                        let mut extended = current.clone();
+                        extended.push(sort_expr.clone());
```
Comment (findepi) [inline datafusion/physical-plan/src/windows/mod.rs]: Does this look potentially expensive?

Comment (findepi) [reply datafusion/physical-plan/src/windows/mod.rs]: In https://github.com/apache/datafusion/pull/17563 we have this example query
```
# regression test for https://github.com/apache/datafusion/issues/17401
query I
WITH source AS (
    SELECT
        1 AS n,
        '' AS a1, '' AS a2, '' AS a3, '' AS a4, '' AS a5, '' AS a6, '' AS a7, '' AS a8,
        '' AS a9, '' AS a10, '' AS a11, '' AS a12, '' AS a13, '' AS a14, '' AS a15, '' AS a16,
        '' AS a17, '' AS a18, '' AS a19, '' AS a20, '' AS a21, '' AS a22, '' AS a23, '' AS a24,
        '' AS a25, '' AS a26, '' AS a27, '' AS a28, '' AS a29, '' AS a30, '' AS a31, '' AS a32,
        '' AS a33, '' AS a34, '' AS a35, '' AS a36, '' AS a37, '' AS a38, '' AS a39, '' AS a40
)
SELECT
    sum(n) OVER (PARTITION BY
        a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20,
        a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40
    )
FROM source;
```

with current PR code it never completes, but let's ignore this for a moment.

if i read the code correctly, it "prunes early" when next partitioning expression doesn't provide more benefits. So i thought that it won't prune in some cases. Perhaps when input is pre-partitioned? 

Let's add a test query
```
WITH source AS (
    SELECT
        1 AS n,
        '' AS a1, '' AS a2, '' AS a3, '' AS a4, '' AS a5, '' AS a6, '' AS a7, '' AS a8,
        '' AS a9, '' AS a10, '' AS a11, '' AS a12, '' AS a13, '' AS a14, '' AS a15, '' AS a16,
        '' AS a17, '' AS a18, '' AS a19, '' AS a20, '' AS a21, '' AS a22, '' AS a23, '' AS a24,
        '' AS a25, '' AS a26, '' AS a27, '' AS a28, '' AS a29, '' AS a30, '' AS a31, '' AS a32,
        '' AS a33, '' AS a34, '' AS a35, '' AS a36, '' AS a37, '' AS a38, '' AS a39, '' AS a40
)
SELECT
    sum(n) OVER (PARTITION BY
        a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20,
        a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40
    )
FROM (SELECT * FROM source ORDER BY a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20,;
        a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40);
```

Comment (findepi) [reply datafusion/physical-plan/src/windows/mod.rs]: However, I am not sure if i understand correctly the pruning condition and what's the condition for _not pruning_. Please elaborate.

**Comment by alamb** [comment]
This seems to actually have made planning time worse -- the benchmark run from yesterday is still running

```
Benchmarking physical_window_function_partition_by_7_on_values: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 30504.9s, or reduce sample count to 10.
physical_window_function_partition_by_7_on_values
                        time:   [303.87 s 304.07 s 304.28 s]
Found 5 outliers among 100 measurements (5.00%)
  5 (5.00%) high mild

Benchmarking physical_window_function_partition_by_8_on_values: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 696351.6s, or reduce sample count to 10.
Benchmarking physical_window_function_partition_by_8_on_values: Collecting 100 samples in estimated 696352 s (100 iterations)
...
```

(note I think 696351.6s means **8 days!**)

**Comment by berkaysynnada** [comment]
```
DataFusion CLI v50.0.0
> WITH source AS (
    SELECT
        1 AS n,
        '' AS a1, '' AS a2, '' AS a3, '' AS a4, '' AS a5, '' AS a6, '' AS a7, '' AS a8,
        '' AS a9, '' AS a10, '' AS a11, '' AS a12, '' AS a13, '' AS a14, '' AS a15, '' AS a16,
        '' AS a17, '' AS a18, '' AS a19, '' AS a20, '' AS a21, '' AS a22, '' AS a23, '' AS a24,
        '' AS a25, '' AS a26, '' AS a27, '' AS a28, '' AS a29, '' AS a30, '' AS a31, '' AS a32,
        '' AS a33, '' AS a34, '' AS a35, '' AS a36, '' AS a37, '' AS a38, '' AS a39, '' AS a40
)
SELECT
    sum(n) OVER (PARTITION BY
        a1, a2, a3, a4
    )
FROM source;
+----------------------------------------------------------------------------------------------------------------------------------+
| sum(source.n) PARTITION BY [source.a1, source.a2, source.a3, source.a4] ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING |
+----------------------------------------------------------------------------------------------------------------------------------+
| 1                                                                                                                                |
+----------------------------------------------------------------------------------------------------------------------------------+
1 row(s) fetched. 
Elapsed 0.039 seconds.

> WITH source AS (
    SELECT
        1 AS n,
        '' AS a1, '' AS a2, '' AS a3, '' AS a4, '' AS a5, '' AS a6, '' AS a7, '' AS a8,
        '' AS a9, '' AS a10, '' AS a11, '' AS a12, '' AS a13, '' AS a14, '' AS a15, '' AS a16,
        '' AS a17, '' AS a18, '' AS a19, '' AS a20, '' AS a21, '' AS a22, '' AS a23, '' AS a24,
        '' AS a25, '' AS a26, '' AS a27, '' AS a28, '' AS a29, '' AS a30, '' AS a31, '' AS a32,
        '' AS a33, '' AS a34, '' AS a35, '' AS a36, '' AS a37, '' AS a38, '' AS a39, '' AS a40
)
SELECT
    sum(n) OVER (PARTITION BY
        a1, a2, a3, a4, a5
    )
FROM source;
+---------------------------------------------------------------------------------------------------------------------------------------------+
| sum(source.n) PARTITION BY [source.a1, source.a2, source.a3, source.a4, source.a5] ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING |
+---------------------------------------------------------------------------------------------------------------------------------------------+
| 1                                                                                                                                           |
+---------------------------------------------------------------------------------------------------------------------------------------------+
1 row(s) fetched. 
Elapsed 0.018 seconds.
```

I missed the case where there are no ordering constraints. In that scenario, ordering_satisfy() returns true for nearly all combinations, so we were still keeping O(4^n) orderings despite pruning. I've now updated the approach as greedy.
1) For each partition column, try 4 sort options and pick the first that works
2) Move to the next column only with the chosen option
3) Stop immediately if any column has no valid option

Can you check this updated version @findepi ?

File: datafusion/physical-plan/src/windows/mod.rs (hunk 3 above)
Comment (berkaysynnada) [reply datafusion/physical-plan/src/windows/mod.rs]: Yes, this part is for calculating orderings of function results, and similar approach can also be applied here. If you think the partitioning expr update reasonable now, I'll apply the same here as well, in addition to the valid parts of your PR

**Comment by alamb** [comment]
🤖 `./gh_compare_branch_bench.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/gh_compare_branch_bench.sh) Running
Linux aal-dev 6.14.0-1014-gcp #15~24.04.1-Ubuntu SMP Fri Jul 25 23:26:08 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing fix/exponential-window-ordering-calc (43a323fa3124fbddc2412925bfc32aa250eedf6a) to 03b67897ec2b2b71bf083e78a35125dc391b0e68 [diff](https://github.com/apache/datafusion/compare/03b67897ec2b2b71bf083e78a35125dc391b0e68..43a323fa3124fbddc2412925bfc32aa250eedf6a)
BENCH_NAME=sql_planner
BENCH_COMMAND=cargo bench --bench sql_planner
BENCH_FILTER=physical_window_function_partition
BENCH_BRANCH_NAME=fix_exponential-window-ordering-calc
Results will be posted here when complete

**Comment by findepi** [comment]
> @findepi do you want me to take bench and slt changes from #17563 ?

The PR is currently light on tests. Can you please consider pulling https://github.com/synnada-ai/datafusion-upstream/pull/74 ?

File: datafusion/physical-plan/src/windows/mod.rs (hunk 2 above)
Comment (findepi) [reply datafusion/physical-plan/src/windows/mod.rs]: This condition still looks redundant. IIUC, when `partitioning_exprs.is_empty()` the code inside the THEN arm will not do anything

File: datafusion/physical-plan/src/windows/mod.rs [hunk 5]
```diff
@@ -371,18 +371,41 @@ pub(crate) fn window_equivalence_properties(
...
+            let mut ordering = vec![];
+            for partition_expr in partitioning_exprs.iter() {
+                let sort_options =
+                    sort_options_resolving_constant(Arc::clone(partition_expr), true);
+
+                // Try each sort option and pick the first one that works
+                let mut found = false;
+                for sort_expr in sort_options.iter() {
+                    let mut candidate_ordering = ordering.clone();
+                    candidate_ordering.push(sort_expr.clone());
```
Comment (findepi) [inline datafusion/physical-plan/src/windows/mod.rs]: nit:

`ordering.clone()` is avoidable. 
logically, it's an expression being pushed-tried-else-popped:

```rust
// Find a single valid ordering using a greedy approach
let mut candidate_ordering = vec![];
for partition_expr in partitioning_exprs.iter() {
    let sort_options =
        sort_options_resolving_constant(Arc::clone(partition_expr), true);

    // Try each sort option and pick the first one that works
    let mut found = false;
    for sort_expr in sort_options.iter() {
        candidate_ordering.push(sort_expr.clone());

        if let Some(lex) = LexOrdering::new(candidate_ordering.clone()) {
            if window_eq_properties.ordering_satisfy(lex)? {
                found = true;
                break;
            }
        } else {
            candidate_ordering.pop();
        }
    }
    // If no sort option works for this column, we can't build a valid ordering
    if !found {
        candidate_ordering.clear();
        break;
    }
}
// If we successfully built an ordering for all columns, use it
if candidate_ordering.len() == partitioning_exprs.len() {
    if let Some(lex) = LexOrdering::new(ordering) {
        all_satisfied_lexs.push(lex);
    }
}
```

File: datafusion/physical-plan/src/windows/mod.rs [hunk 6]
```diff
@@ -371,18 +371,41 @@ pub(crate) fn window_equivalence_properties(
...
+
+                    if let Some(lex) = LexOrdering::new(candidate_ordering.clone()) {
+                        if window_eq_properties.ordering_satisfy(lex)? {
```
Comment (findepi) [inline datafusion/physical-plan/src/windows/mod.rs]: With every new window sort expression iterated over, we seem to be processing all previous sort expressions. This feels quadratic.

File: datafusion/physical-plan/src/windows/mod.rs (hunk 3 above)
Comment (findepi) [reply datafusion/physical-plan/src/windows/mod.rs]: let's maybe file issue / follow-up PR, so that we don't need to re-review code unnecessarily

**Review by findepi — APPROVED** [review]
the changed piece of code no longer looks like exhibiting exponential complexity

thank you!


please include tests (https://github.com/apache/datafusion/pull/17684#issuecomment-3319430577)

**Comment by alamb** [comment]
🤖 `./gh_compare_branch_bench.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/gh_compare_branch_bench.sh) Running
Linux aal-dev 6.14.0-1014-gcp #15~24.04.1-Ubuntu SMP Fri Jul 25 23:26:08 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing fix/exponential-window-ordering-calc (43a323fa3124fbddc2412925bfc32aa250eedf6a) to 03b67897ec2b2b71bf083e78a35125dc391b0e68 [diff](https://github.com/apache/datafusion/compare/03b67897ec2b2b71bf083e78a35125dc391b0e68..43a323fa3124fbddc2412925bfc32aa250eedf6a)
BENCH_NAME=sql_planner
BENCH_COMMAND=cargo bench --bench sql_planner
BENCH_FILTER=physical_window_function_partition
BENCH_BRANCH_NAME=fix_exponential-window-ordering-calc
Results will be posted here when complete

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                                                fix_exponential-window-ordering-calc    main
-----                                                ------------------------------------    ----
physical_window_function_partition_by_4_on_values    1.00    606.4±5.29µs        ? ?/sec     2.19   1327.3±5.88µs        ? ?/sec
physical_window_function_partition_by_7_on_values    1.00    736.8±4.67µs        ? ?/sec     48.32    35.6±0.16ms        ? ?/sec
physical_window_function_partition_by_8_on_values    1.00    797.4±6.45µs        ? ?/sec     173.51   138.4±0.54ms        ? ?/sec
```


</p>
</details>

**Comment by alamb** [comment]
🤖 `./gh_compare_branch_bench.sh` [Benchmark Script](https://github.com/alamb/datafusion-benchmarking/blob/main/gh_compare_branch_bench.sh) Running
Linux aal-dev 6.14.0-1014-gcp #15~24.04.1-Ubuntu SMP Fri Jul 25 23:26:08 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
Comparing fix/exponential-window-ordering-calc (43a323fa3124fbddc2412925bfc32aa250eedf6a) to 03b67897ec2b2b71bf083e78a35125dc391b0e68 [diff](https://github.com/apache/datafusion/compare/03b67897ec2b2b71bf083e78a35125dc391b0e68..43a323fa3124fbddc2412925bfc32aa250eedf6a)
BENCH_NAME=sql_planner
BENCH_COMMAND=cargo bench --bench sql_planner
BENCH_FILTER=physical_window_function_partition
BENCH_BRANCH_NAME=fix_exponential-window-ordering-calc
Results will be posted here when complete

**Comment by alamb** [comment]
```
physical_window_function_partition_by_4_on_values    1.00    606.4±5.29µs        ? ?/sec     2.19   1327.3±5.88µs        ? ?/sec
physical_window_function_partition_by_7_on_values    1.00    736.8±4.67µs        ? ?/sec     48.32    35.6±0.16ms        ? ?/sec
physical_window_function_partition_by_8_on_values    1.00    797.4±6.45µs        ? ?/sec     173.51   138.4±0.54ms        ? ?/sec
```

🚀  -- it is not often we see a 173x speedup 🐈 🥳

**Comment by berkaysynnada** [comment]
> the changed piece of code no longer looks like exhibiting exponential complexity
> 
> thank you!
> 
> please include tests ([#17684 (comment)](https://github.com/apache/datafusion/pull/17684#issuecomment-3319430577))

I'll drive this to the finish line, probably tomorrow morning (all the stuff we've talked about). Thank you :)

**Comment by alamb** [comment]
🤖: Benchmark completed

<details><summary>Details</summary>
<p>


```
group                                                fix_exponential-window-ordering-calc    main
-----                                                ------------------------------------    ----
physical_window_function_partition_by_4_on_values    1.00    598.6±4.75µs        ? ?/sec     2.21  1323.9±14.77µs        ? ?/sec
physical_window_function_partition_by_7_on_values    1.00    751.3±5.72µs        ? ?/sec     47.12    35.4±0.15ms        ? ?/sec
physical_window_function_partition_by_8_on_values    1.00    798.7±3.28µs        ? ?/sec     173.17   138.3±0.48ms        ? ?/sec
```


</p>
</details>

**Comment by findepi** [comment]
> 🤖: Benchmark completed

thanks @alamb . these lgtm

File: datafusion/physical-plan/src/windows/mod.rs (hunk 6 above)
Comment (berkaysynnada) [reply datafusion/physical-plan/src/windows/mod.rs]: Yes, it's quadratic as we validate orderings of length 1, 2, 3, n. But that's unavoidable since we need to check that each partial ordering stays valid as we extend it.

Still way better than before. Old version is O(4^n), the new one is O(n^2 * 4)

The quadratic cost is the price of correctness

**Comment by berkaysynnada** [comment]
I think it's ready. @findepi feel free to commit directly if you'd like to make any changes

```
DataFusion CLI v50.0.0
> WITH source AS (
    SELECT
        1 AS n,
        '' AS a1, '' AS a2, '' AS a3, '' AS a4, '' AS a5, '' AS a6, '' AS a7, '' AS a8,
        '' AS a9, '' AS a10, '' AS a11, '' AS a12, '' AS a13, '' AS a14, '' AS a15, '' AS a16,
        '' AS a17, '' AS a18, '' AS a19, '' AS a20, '' AS a21, '' AS a22, '' AS a23, '' AS a24,
        '' AS a25, '' AS a26, '' AS a27, '' AS a28, '' AS a29, '' AS a30, '' AS a31, '' AS a32,
        '' AS a33, '' AS a34, '' AS a35, '' AS a36, '' AS a37, '' AS a38, '' AS a39, '' AS a40
)
SELECT
    sum(n) OVER (PARTITION BY
        a1, a2, a3, a4, a5
    )
FROM source;
+---------------------------------------------------------------------------------------------------------------------------------------------+
| sum(source.n) PARTITION BY [source.a1, source.a2, source.a3, source.a4, source.a5] ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING |
+---------------------------------------------------------------------------------------------------------------------------------------------+
| 1                                                                                                                                           |
+---------------------------------------------------------------------------------------------------------------------------------------------+
1 row(s) fetched. 
Elapsed 0.039 seconds.
```

File: datafusion/physical-plan/src/windows/mod.rs [hunk 7]
```diff
@@ -371,17 +371,41 @@ pub(crate) fn window_equivalence_properties(
     for (i, expr) in window_exprs.iter().enumerate() {
         let partitioning_exprs = expr.partition_by();
         let no_partitioning = partitioning_exprs.is_empty();
-        // Collect columns defining partitioning, and construct all `SortOptions`
-        // variations for them. Then, we will check each one whether it satisfies
-        // the existing ordering provided by the input plan.
+
+        // Find "one" valid ordering for partition columns to avoid exponential complexity.
```
Comment (alamb) [inline datafusion/physical-plan/src/windows/mod.rs:375]: Context might help too
```suggestion
        // Find "one" valid ordering for partition columns to avoid exponential complexity.
        // see https://github.com/apache/datafusion/issues/17401
```

File: datafusion/physical-plan/src/windows/mod.rs [hunk 8]
```diff
@@ -371,17 +371,41 @@ pub(crate) fn window_equivalence_properties(
...
+
+        for partition_expr in partitioning_exprs.iter() {
+            let sort_options =
+                sort_options_resolving_constant(Arc::clone(partition_expr), true);
+
+            // Try each sort option and pick the first one that works
+            let mut found = false;
+            for sort_expr in sort_options.iter() {
+                candidate_ordering.push(sort_expr.clone());
+                if let Some(lex) = LexOrdering::new(candidate_ordering.clone()) {
```
Comment (alamb) [inline datafusion/physical-plan/src/windows/mod.rs]: Minor: you can avoid some clones I think like
```suggestion
            for sort_expr in sort_options.into_iter() {
                candidate_ordering.push(sort_expr);
                if let Some(lex) = LexOrdering::new(candidate_ordering.clone()) {
```

File: datafusion/physical-plan/src/windows/mod.rs [hunk 9]
```diff
@@ -467,23 +493,44 @@ pub(crate) fn window_equivalence_properties(
...
+                    let mut candidate_order = vec![];
+                    let mut asc = false;
+
+                    for (idx, expr) in aggregate_exprs.iter().enumerate() {
+                        let mut found = false;
+                        let sort_options =
+                            sort_options_resolving_constant(Arc::clone(expr), false);
+
+                        // Try each option and pick the first that works
+                        for sort_expr in sort_options.iter() {
```
Comment (alamb) [inline datafusion/physical-plan/src/windows/mod.rs]: Similarly here you could potentially use `sort_options.into_iter()` and save the clone below. Here is what I used

```diff
@@ -505,13 +505,14 @@ pub(crate) fn window_equivalence_properties(
                             sort_options_resolving_constant(Arc::clone(expr), false);

                         // Try each option and pick the first that works
-                        for sort_expr in sort_options.iter() {
-                            candidate_order.push(sort_expr.clone());
+                        for sort_expr in sort_options.into_iter() {
+                            let is_asc = !sort_expr.options.descending;
+                            candidate_order.push(sort_expr);

                             if let Some(lex) = LexOrdering::new(candidate_order.clone()) {
                                 if window_eq_properties.ordering_satisfy(lex)? {
                                     if idx == 0 {
-                                        asc = !sort_expr.options.descending;
+                                        asc = is_asc;
                                     }
                                     found = true;
                                     break;
```

File: datafusion/physical-plan/src/windows/mod.rs [hunk 10]
```diff
@@ -467,23 +493,44 @@ pub(crate) fn window_equivalence_properties(
...
-                        .map(sort_options_resolving_constant)
-                        .multi_cartesian_product();
-
-                    let (mut asc, mut satisfied) = (false, false);
-                    for order in args_all_lexs {
-                        if let Some(f) = order.first() {
-                            asc = !f.options.descending;
+                    // Find one valid ordering for aggregate arguments instead of
+                    // checking all combinations
+                    let aggregate_exprs = sliding_expr.get_aggregate_expr().expressions();
```
Comment (alamb) [inline datafusion/physical-plan/src/windows/mod.rs:497]: FWIW this seems very similar to the loop above, I wonder if there is some way (as a follow on PR) to factor it out to reduce the replication

File: datafusion/sqllogictest/test_files/window.slt [hunk 11]
```diff
@@ -6034,3 +6034,92 @@ LIMIT 5
 0 2 NULL NULL 0 NULL NULL
 0 3 NULL NULL 0 NULL NULL
 0 4 NULL NULL 0 NULL NULL
+
+# regression test for https://github.com/apache/datafusion/issues/17401
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/window.slt:6038]: I ran this locally, and found

both main and This branch -- took 2 seconds 


Main
```shell
(venv) andrewlamb@Andrews-MacBook-Pro-3:~/Software/datafusion$ cargo test --profile=ci --test sqllogictests  --  window.slt
    Finished `ci` profile [unoptimized + debuginfo] target(s) in 0.20s
     Running bin/sqllogictests.rs (target/ci/deps/sqllogictests-4dcb99f83e94c047)
Completed 2 test files in 2 seconds
```
This branch
```
(venv) andrewlamb@Andrews-MacBook-Pro-3:~/Software/datafusion$ cargo test --profile=ci --test sqllogictests  --  window.slt
    Finished `ci` profile [unoptimized + debuginfo] target(s) in 0.19s
     Running bin/sqllogictests.rs (target/ci/deps/sqllogictests-fbba93e4275b7826)
Completed 2 test files in 2 seconds
```

File: datafusion/physical-plan/src/windows/mod.rs (hunk 6 above)
Comment (findepi) [reply datafusion/physical-plan/src/windows/mod.rs]: No doubt quadratic is so much better than exponential.

What could make turn valid partial ordering into an invalid, when extended with a new expression?
Is it only about duplicates?
IIRC, `LexOrdering::new` checks for dups, so something we could easily do O(n) overall. But I don't know yet what `window_eq_properties.ordering_satisfy` does.

File: datafusion/sqllogictest/test_files/window.slt (hunk 11 above)
Comment (findepi) [reply datafusion/sqllogictest/test_files/window.slt:6038]: > I ran this locally, and found
> 
> both main and This branch -- took 2 seconds
> 
> Main

Do you mean you run window.slt unmodified as currently in `main`, or did you apply changes from this PR first?

I tried to reproduce the latter and for me execution "hangs" at

```
[00:00:01] #######################################-     442/454     "window.slt"
```

File: datafusion/physical-plan/src/windows/mod.rs [hunk 12]
```diff
@@ -371,17 +371,41 @@ pub(crate) fn window_equivalence_properties(
...
+            if !found {
+                candidate_ordering.clear();
+                break;
+            }
+        }
+
+        // If we successfully built an ordering for all columns, use it
+        // When there are no partition expressions, candidate_ordering will be empty and won't be added
+        if candidate_ordering.len() == partitioning_exprs.len()
+            && !candidate_ordering.is_empty()
```
Comment (findepi) [inline datafusion/physical-plan/src/windows/mod.rs]: `&& !candidate_ordering.is_empty()` is redundant.
in the empty case, the `LexOrdering::new` returns `None`

```suggestion
```

File: datafusion/physical-plan/src/windows/mod.rs [hunk 13]
```diff
@@ -467,23 +493,44 @@ pub(crate) fn window_equivalence_properties(
...
+                            sort_options_resolving_constant(Arc::clone(expr), false);
+
+                        // Try each option and pick the first that works
+                        for sort_expr in sort_options.iter() {
+                            candidate_order.push(sort_expr.clone());
+
+                            if let Some(lex) = LexOrdering::new(candidate_order.clone()) {
+                                if window_eq_properties.ordering_satisfy(lex)? {
+                                    if idx == 0 {
+                                        asc = !sort_expr.options.descending;
```
Comment (findepi) [inline datafusion/physical-plan/src/windows/mod.rs]: why first is special? worth a code comment 

(i know the logic is pre-existing and did not have a comment, but you seem to know what this is about and I do not)

File: datafusion/physical-plan/src/windows/mod.rs [hunk 14]
```diff
@@ -467,23 +493,44 @@ pub(crate) fn window_equivalence_properties(
                 // utilize set-monotonicity since the set shrinks as the frame
                 // boundary starts "touching" the end of the table.
                 else if frame.is_causal() {
-                    let args_all_lexs = sliding_expr
-                        .get_aggregate_expr()
-                        .expressions()
-                        .into_iter()
-                        .map(sort_options_resolving_constant)
-                        .multi_cartesian_product();
```
Comment (findepi) [inline datafusion/physical-plan/src/windows/mod.rs:475]: Thanks for solving this exponential case too!

I am not sure the regression tests cover this case.
Do we need some more test queries?

File: datafusion/physical-plan/src/windows/mod.rs [hunk 15]
```diff
@@ -634,11 +681,45 @@ pub fn get_window_mode(
...
+///
+/// # When to use `all_options = true`:
+/// Use for PARTITION BY columns where we want to explore all possible orderings to find
+/// one that matches the existing data ordering.
+///
+/// # When to use `all_options = false`:
+/// Use for aggregate/window function arguments where set monotonicity needs to be preserved.
+/// Only generates ASC NULLS LAST and DESC NULLS FIRST because:
+/// - Set monotonicity is broken if data has increasing order but nulls come first
+/// - Set monotonicity is broken if data has decreasing order but nulls come last
```
Comment (findepi) [inline datafusion/physical-plan/src/windows/mod.rs]: Maybe `only_monotonic` could be a more descriptive param name?

File: datafusion/physical-plan/src/windows/mod.rs (hunk 14 above)
Comment (berkaysynnada) [reply datafusion/physical-plan/src/windows/mod.rs:475]: https://github.com/apache/datafusion/blob/6ec14e9e488c2b5bd57114d1b3bf3a798fc579ad/datafusion/core/tests/physical_optimizer/enforce_sorting.rs#L2470 highly covers the correctness issue, but for the performance concerns, a similar regression test should be added, like this:

``` 
    SUM(c1 + c2 + c3 + c4 + c5 + c6 + c7 + c8 + c9 + c10 + ... + cN) 
        OVER (ORDER BY c1, c2, ... cN and a causal window)
```

File: datafusion/physical-plan/src/windows/mod.rs (hunk 15 above)
Comment (berkaysynnada) [reply datafusion/physical-plan/src/windows/mod.rs]: I think it's not very obvious for someone who hasn't grasped the relationship between nulls and set monotonicity

Comment (findepi) [reply datafusion/physical-plan/src/windows/mod.rs]: Sure it's not.
But "all options" is even less obvious. It well hints what gets returned when all_options=true, but reader has no clue what gets returned when all_options=false.  The all_options=false variant is meaningless on its own.

Comment (berkaysynnada) [reply datafusion/physical-plan/src/windows/mod.rs]: ok, I'm warming up to that name. I guess there is not any remaining issue now

Comment (alamb) [reply datafusion/physical-plan/src/windows/mod.rs]: Is the name change a blocker? Or perhaps we can update it in a follow on PR if needed?

**Comment by alamb** [comment]
Are there any remaining issues preventing merging this PR?

File: datafusion/physical-plan/src/windows/mod.rs (hunk 15 above)
Comment (berkaysynnada) [reply datafusion/physical-plan/src/windows/mod.rs]: I've done that change already 👍🏻

**Comment by alamb** [comment]
Ok, this looks good to me, so I'll merge it in now. Thank you @berkaysynnada and @findepi

**Comment by alamb** [comment]
Backport PR
- https://github.com/apache/datafusion/pull/17778
