### PR TITLE
Minor: fix: Include FetchRel when producing LogicalPlan from Sort

### LINKED ISSUE #13860: Substrait roundtrip fails for Sort with a fetch
### Describe the bug

Substrait round trip fails for a query that produces a logical plan where the Sort node includes a fetch.

As an example,
```
Sort: data.b ASC NULLS LAST, fetch=2
  Filter: data.a > Int64(1)
    TableScan: data projection=[a, b, c, d, e, f], partial_filters=[data.a > Int64(1)]
```
Upon returning from the round trip produces
```
Sort: data.b ASC NULLS LAST
  Filter: data.a > Int64(1)
    TableScan: data projection=[a, b, c, d, e, f], partial_filters=[data.a > Int64(1)]
```   
the fetch is lost.

I'm happy to take and fix this issue, but I wasn't sure where the fix should be made.   Should this fix the Sort Rel in substrait that cannot hold a `fetch` member?  Or should this be a fix in the substrait producer to produce a plan with a Limit and a Sort?

### To Reproduce

Add a test to `datafusion/substrait/tests/cases/round_trip_logical_plan.rs` such as

```rust
#[tokio::test]
async fn select_with_filter_sort_limit() -> Result<()> {
    roundtrip("SELECT * FROM data WHERE a > 1 ORDER BY b ASC LIMIT 2").await
}
```

in this repo, run 
```shell
cd datafusion/substrait
 cargo test -- --nocapture select_with_filter_sort_limit
```

### Expected behavior

A round trip for this plan should work.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by robtandy**
## Which issue does this PR close?
Closes #13860

## Rationale for this change

Explained in #13860 

## Are these changes tested?

Included a test that fails before this change

## Are there any user-facing changes?

`to_substrait_plan` will include a `FetchRel` when serializing a `Sort` that contains a `fetch`.   It had previously missed this.

### CODE REVIEW

**Comment by robtandy** [comment]
Per contribution guide 
```For new contributors a committer must first trigger the CI tasks. Please mention the members from committers list in the PR to help trigger the CI```

Mentioning @alamb :)

File: datafusion/substrait/src/logical_plan/producer.rs [hunk 1]
```diff
@@ -368,14 +368,45 @@ pub fn to_substrait_rel(
...
                 rel_type: Some(RelType::Sort(Box::new(SortRel {
                     common: None,
                     input: Some(input),
                     sorts: sort_fields,
                     advanced_extension: None,
                 }))),
-            }))
+            });
+
+            match sort.fetch {
```
Comment (alamb) [inline datafusion/substrait/src/logical_plan/producer.rs:381]: 👍 

Another pattern I have seen to avoid missing fields like this is 

```rust
let Sort { input, offset } = sort ;
...
```
That way the compiler will tell you when you have not handled some field and you have to explicitly list it out

File: datafusion/substrait/tests/cases/roundtrip_logical_plan.rs [hunk 2]
```diff
@@ -200,6 +200,11 @@ async fn select_with_filter() -> Result<()> {
     roundtrip("SELECT * FROM data WHERE a > 1").await
 }
 
+#[tokio::test]
+async fn select_with_filter_sort_limit() -> Result<()> {
+    roundtrip("SELECT * FROM data WHERE a > 1 ORDER BY b ASC LIMIT 2").await
```
Comment (alamb) [inline datafusion/substrait/tests/cases/roundtrip_logical_plan.rs:205]: It might also be worth a test for `OFFSET`

Like

```sql
    roundtrip("SELECT * FROM data WHERE a > 1 ORDER BY b ASC LIMIT 2").await
```

```
> select * from values (1), (2), (3) ORDER BY column1 LIMIT 1 offset 2;
+---------+
| column1 |
+---------+
| 3       |
+---------+
1 row(s) fetched.
Elapsed 0.012 seconds.
```

**Review by alamb — APPROVED** [review]
Looks like an improvement to me. Thank you @robtandy

cc @Blizzara and @vbarua

File: datafusion/substrait/tests/cases/roundtrip_logical_plan.rs (hunk 2 above)
Comment (robtandy) [reply datafusion/substrait/tests/cases/roundtrip_logical_plan.rs:205]: Good idea.  I'll add.

File: datafusion/substrait/src/logical_plan/producer.rs (hunk 1 above)
Comment (robtandy) [reply datafusion/substrait/src/logical_plan/producer.rs:381]: Making sure I follow:

You mean on line 364 destructuring the plan like 
```rust
LogicalPlan::Sort(Sort {expr, input, fetch}) => {...
```
I didn't see that pattern followed in that file for the other LogicalPlan inners.   I think its a good idea though

File: datafusion/substrait/src/logical_plan/producer.rs [hunk 3]
```diff
@@ -368,14 +368,45 @@ pub fn to_substrait_rel(
...
+                Some(_) => {
+                    let empty_schema = Arc::new(DFSchema::empty());
+                    let count_mode = sort
+                        .fetch
+                        .map(|amount| {
```
Comment (Blizzara) [inline datafusion/substrait/src/logical_plan/producer.rs:386]: given you have the `match sort.fetch { Some(_) =>` above, you could store that "some" and then use it here
```
match sort.fetch {
   Some(amount) => { 
      ...
      let count_mode = to_substrait_rex(.., (amount as i64), ...)
```

Comment (Blizzara) [reply datafusion/substrait/src/logical_plan/producer.rs:386]: also I think rather than using to_substrait_rex, you could create the substrait expr directly, that might be nicer here

File: datafusion/substrait/tests/cases/roundtrip_logical_plan.rs (hunk 2 above)
Comment (robtandy) [reply datafusion/substrait/tests/cases/roundtrip_logical_plan.rs:205]: added

File: datafusion/substrait/src/logical_plan/producer.rs (hunk 3 above)
Comment (robtandy) [reply datafusion/substrait/src/logical_plan/producer.rs:386]: ty for the suggestions!  Heading to dinner now and I can address these tomorrow morning eastern time.

File: datafusion/substrait/src/logical_plan/producer.rs (hunk 1 above)
Comment (robtandy) [reply datafusion/substrait/src/logical_plan/producer.rs]: Done

File: datafusion/substrait/src/logical_plan/producer.rs (hunk 3 above)
Comment (robtandy) [reply datafusion/substrait/src/logical_plan/producer.rs]: Incorporated both suggestions.  Thank you @Blizzara

**Review by alamb — APPROVED** [review]
Love it -- thank you so much @robtandy  and @Blizzara 

🚀
