### PR TITLE
Bug fix :  fix the bug in docs in 'cum_dist()' Example

### LINKED ISSUE #15611: Bug in 'cum_dist()' example in the docs
### Describe the bug

i was reviewing the changes made in  the docs for the examples in window functions  and notice that the example was not in a organised manner .

Image

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Adez017**
## Which issue does this PR close?

- Closes #15611 

## Rationale for this change

 I was going though the window functions docs and it seems that something is broken with the 'cum_dist()' example in the docs.
Screenshot 2025-04-07 114024

### CODE REVIEW

**Comment by Adez017** [comment]
i ahd done the needed updates in the `cum_dist.rs` file  . you can review it @alamb  .
thank you for your time and patience

File: datafusion/functions-window/src/cume_dist.rs [hunk 1]
```diff
@@ -45,18 +45,21 @@ define_udwf_and_expr!(
...
-    sql_example = r#"-- Example usage of the cume_dist window function:
-SELECT salary,
+    sql_example = r#"```sql
+    --Example usage of the cume_dist window function:
+    SELECT salary,
        cume_dist() OVER (ORDER BY salary) AS cume_dist
-FROM employees;
+    FROM employees;
+```
+```text
```
Comment (alamb) [inline datafusion/functions-window/src/cume_dist.rs:54]:
```suggestion
```sql
```

**Review by alamb — COMMENTED** [review]
Thanks @Adez017 

Remember you will very likely have to regenerate the user documentation using

```shell
./datafusion/dev/update_function_docs.sh
```

And checking in the results

**Review by alamb — APPROVED** [review]
Looks great -- thank you @Adez017
