### PR TITLE
parquet: Make page_index/pushdown metrics consistent with row_group metrics

### LINKED ISSUE #12543: parquet: page_index/pushdown metrics names are inconsistent with row_group metrics
### Describe the bug

Row group metric names are:

* row_groups_pruned_bloom_filter
* row_groups_matched_statistics
* row_groups_matched_bloom_filter
* row_groups_pruned_statistics

while page_index/pushdown metrics names are:

* pushdown_filtered
* page_index_filtered

We should rename "filtered" to "pruned" for consistency, and "matched" added.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### LINKED ISSUE #12544: parquet: Pushdown-related metrics are not documented
### Describe the bug

The following metrics in `EXPLAIN ANALYZE` are not described in a documentation targeted to users: page_index_rows_filtered, row_groups_pruned_bloom_filter, predicate_evaluation_errors, row_groups_matched_statistics, row_groups_pruned_statistics, pushdown_rows_filtered, num_predicate_creation_errors, row_groups_matched_bloom_filter, pushdown_eval_time, page_index_eval_time

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by progval**
## Which issue does this PR close?

Closes #12543.
Closes #12544.

## What changes are included in this PR?

1. Rename `{pushdown,page_index}_filtered` to `{pushdown,page_index}_pruned`
2. Add `{pushdown,page_index}_matched`
3. Added documentation for existing pushdown-related metrics

## Rationale for this change

The latter makes it clearer in EXPLAIN ANALYZE when the Page Index is not checked because their row groups were already eliminated (with a Bloom Filter or row group statistics).

## Are these changes tested?

yes

## Are there any user-facing changes?

New metrics in `EXPLAIN ANALYZE`, documented in docs/source/user-guide/explain-usage.md

### CODE REVIEW

File: datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs [hunk 1]
```diff
@@ -178,6 +178,8 @@ impl PagePruningAccessPlanFilter {
 
         // track the total number of rows that should be skipped
         let mut total_skip = 0;
+        // track the total number of rows that should not be skipped
+        let mut total_pass = 0;
```
Comment (alamb) [inline datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs:182]: minor nit is that `total_select` might be more consistent terminology here

File: datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs [hunk 2]
```diff
@@ -276,6 +281,14 @@ fn rows_skipped(selection: &RowSelection) -> usize {
         .fold(0, |acc, x| if x.skip { acc + x.row_count } else { acc })
 }
 
+/// returns the number of rows not skipped in the selection
+/// TODO should this be upstreamed to RowSelection?
```
Comment (alamb) [inline datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs:285]: This looks the same as https://docs.rs/parquet/latest/parquet/arrow/arrow_reader/struct.RowSelection.html#method.row_count

It would be great to upstream this and rows_skipped to `parquet` -- any chance you are willing to file a ticket to do so?

File: docs/source/user-guide/explain-usage.md [hunk 3]
```diff
@@ -223,6 +223,21 @@ Again, reading from bottom up:
 - `SortPreservingMergeExec`
   - `output_rows=5`, `elapsed_compute=2.375µs`: Produced the final 5 rows in 2.375µs (microseconds)
 
+When predicate pushdown is enabled, `ParquetExec` gains the following metrics:
```
Comment (alamb) [inline docs/source/user-guide/explain-usage.md:226]: ❤️

File: docs/source/user-guide/explain-usage.md [hunk 4]
```diff
@@ -223,6 +223,21 @@ Again, reading from bottom up:
...
+- `row_groups_matched_bloom_filter`: number of rows in row groups that were tested by a Bloom Filter, and passed
+- `row_groups_pruned_bloom_filter`: number of rows in row groups that were tested by a Bloom Filter, and did not pass
+- `row_groups_matched_statistics`: number of rows in row groups that were tested by row group statistics (min and max value), and passed
+- `row_groups_pruned_statistics`: number of rows in row groups that were tested by row group statistics (min and max value), and did not pass
+- `pushdown_rows_matched`: rows that were tested by any of the above filtered, and passed all of them (this should be minimum of `page_index_rows_matched`, `row_groups_pruned_bloom_filter`, and `row_groups_pruned_statistics`)
+- `pushdown_rows_pruned`: rows that were tested by any of the above filtered, and did not pass one of them (this should be sum of `page_index_rows_matched`, `row_groups_pruned_bloom_filter`, and `row_groups_pruned_statistics`)
+- `predicate_evaluation_errors`
+- `num_predicate_creation_errors`
+- `pushdown_eval_time`: time spent evaluating these filters
+- `page_index_eval_time`
```
Comment (alamb) [inline docs/source/user-guide/explain-usage.md:239]:
```suggestion
- `predicate_evaluation_errors`: number of times evaluating the filter expression failed (expected to be zero in normal operation)
- `num_predicate_creation_errors`: number of errors creating predicates (expected to be zero in normal operation)
- `pushdown_eval_time`: time spent evaluating these filters
- `page_index_eval_time`: time required to evaluate the page index filters
```

**Review by alamb — APPROVED** [review]
Thank you @progval  -- this looks like a very nice improvement to me. I left some small suggestions but I don't think they are required to merge this PR

File: datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs (hunk 2 above)
Comment (progval) [reply datafusion/core/src/datasource/physical_plan/parquet/page_filter.rs:285]: sent to https://github.com/apache/arrow-rs/pull/6429

**Comment by alamb** [comment]
Thanks agian @progval
