### PR TITLE
fix: normalize window ident

### LINKED ISSUE #15605: Support window definitions with aliases
Originally posted by @jonahgao in https://github.com/apache/datafusion/pull/15033#discussion_r2029886625:

>  Unrelated to the current fix, we should compare them using normalized names to support the following SQL

```sql
SELECT
  t1.v1,
  SUM(t1.v1) OVER W + 1
FROM
  generate_series(1, 5) AS t1(v1)
WINDOW
  w AS (ORDER BY t1.v1);
```

### PR DESCRIPTION
**Pull request by chenkovsky**
## Which issue does this PR close?

- Closes #15605.

## Rationale for this change

ident normalizer is not called.

## What changes are included in this PR?

normalize ident before comparing window name.

## Are these changes tested?

UT

## Are there any user-facing changes?

NO

### CODE REVIEW

File: datafusion/sql/src/select.rs [hunk 1]
```diff
@@ -914,20 +906,35 @@ fn match_window_definitions(
...
-                        }
-                        // All named windows must be defined with a WindowSpec.
-                        if let Some(WindowType::NamedWindow(ident)) = &f.over {
-                            err = Some(DataFusionError::Plan(format!(
-                                "The window {ident} is not defined!"
-                            )));
-                            return ControlFlow::Break(());
+                            // All named windows must be defined with a WindowSpec.
+                            if let Some(WindowType::NamedWindow(ident)) = &f.over {
+                                err = Some(DataFusionError::Plan(format!(
```
Comment (comphead) [inline datafusion/sql/src/select.rs:911]: @chenkovsky can you make a favor and change this to `plan_err!`?

**Review by comphead — APPROVED** [review]
Thanks @chenkovsky this lgtm

**Comment by alamb** [comment]
Thanks @chenkovsky and @comphead
