### PR TITLE
[sqllogictest] Run tests on Windows

### LINKED ISSUE #4494: Fix the sqllogictest runner on Windows
**Describe the bug**
The runner currently fails on Windows - see line 2098 to 2961 of this [CI failure](https://github.com/apache/arrow-datafusion/actions/runs/3579678163/jobs/6021107151). It looks like its failing to split on a new line at the end of `SELECT avg(c12) FROM aggregate_test_100` and is reading the entire[ aggregate.slt](https://github.com/apache/arrow-datafusion/blob/master/datafusion/core/tests/sqllogictests/test_files/aggregate.slt) file as a string.

### PR DESCRIPTION
**Pull request by melgenek**
# Which issue does this PR close?

Closes #4494.

# Rationale for this change

Run sqllogictest tests in Windows in Github actions. These tests are currently disabled.

# What changes are included in this PR?

Enable sqllogictest tests in Windows in Github actions. Additionally, there are some tricks to make tests work.

# Are these changes tested?

The change is a test only and runs in ci.

# Are there any user-facing changes?

N/A

### CODE REVIEW

File: datafusion/core/tests/sqllogictests/src/main.rs [hunk 1]
```diff
@@ -33,16 +35,31 @@ mod utils;
...
 const PG_COMPAT_FILE_PREFIX: &str = "pg_compat_";
 
-#[tokio::main]
 #[cfg(target_family = "windows")]
-pub async fn main() -> Result<(), Box<dyn Error>> {
-    println!("Skipping test on windows");
-    Ok(())
+pub fn main() {
+    // Tests from `tpch.slt` fail with stackoverflow with the default stack size.
+    thread::Builder::new()
```
Comment (melgenek) [inline datafusion/core/tests/sqllogictests/src/main.rs:41]: `tpch.slt` test fails with stack overflow errors. The stack size on Windows seems to be 1Mb by default vs 2MB on Linux. I tried debugging what causes the error, but it seems that the stack is just deep enough due to the recursive design of the physical planner.

In case somebody with more understanding takes a closer look, I added a stack trace for the overflow as well as a test to reproduce the issue with unit tests on any platform here https://gist.github.com/melgenek/b6acf4467ee10c1941f3b103a17e1b1e.

Comment (alamb) [reply datafusion/core/tests/sqllogictests/src/main.rs:41]: We have hit this before (e.g. https://github.com/apache/arrow-datafusion/issues/4065)  -- I think cranking up the default size is fine.

Specifically, release builds seem to use much less stack so this is primarily a test issue rather than a production issue

**Review by alamb — APPROVED** [review]
LGTM -- thank you @melgenek 

I also verified that the windows CI run indeed is running sqllogictests now: https://github.com/apache/arrow-datafusion/actions/runs/4611787296/jobs/8151915512?pr=5870#step:5:2877
