### PR TITLE
fix: Ensure columns are casted to the correct names with Unions

### LINKED ISSUE #20123: Duplicate unqualified name error on unions
### Describe the bug

When going through Substrait in a query with unions, where two different union-ed columns have the same name, the following error happens:
```
Error: type_coercion
Schema contains duplicate unqualified field name "foo(bar(tags,Utf8(""baz"")))"
```
This seems to be a regression that started happening in v52 and was introduced in:
- https://github.com/apache/datafusion/pull/19019

As reverting that PR fixes the problem.

### To Reproduce

Run the new test introduced in https://github.com/apache/datafusion/pull/20106

### Expected behavior

The test succeeds

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nuno-faria**
## Which issue does this PR close?

- Closes #20123.

## Rationale for this change

When aliasing a cast, use the original name to prevent duplicate column names errors.

## What changes are included in this PR?

- Updated `coerce_exprs_for_schema` to use the correct name.
- Updated tests.

## Are these changes tested?

Yes.

## Are there any user-facing changes?

No.

### CODE REVIEW

File: datafusion/optimizer/tests/optimizer_integration.rs [hunk 1]
```diff
@@ -543,7 +543,7 @@ fn recursive_cte_projection_pushdown() -> Result<()> {
       RecursiveQuery: is_distinct=false
         Projection: test.col_int32 AS id
           TableScan: test projection=[col_int32]
-        Projection: CAST(CAST(nodes.id AS Int64) + Int64(1) AS Int32) AS id
+        Projection: CAST(CAST(nodes.id AS Int64) + Int64(1) AS Int32)
```
Comment (nuno-faria) [inline datafusion/optimizer/tests/optimizer_integration.rs:546]: These changes are ok, the alias had been introduced by #19019 but it was not needed.

File: datafusion/expr/src/expr_rewriter/mod.rs [hunk 2]
```diff
@@ -261,9 +261,14 @@ fn coerce_exprs_for_schema(
                     #[expect(deprecated)]
                     Expr::Wildcard { .. } => Ok(expr),
                     _ => {
-                        // maintain the original name when casting
-                        let name = dst_schema.field(idx).name();
-                        Ok(expr.cast_to(new_type, src_schema)?.alias(name))
+                        match expr {
+                            // maintain the original name when casting a column
+                            Expr::Column(ref column) => {
```
Comment (alamb) [inline datafusion/expr/src/expr_rewriter/mod.rs:268]: can we add some context about why we maintain the original name only for columns?

File: datafusion/optimizer/tests/optimizer_integration.rs (hunk 1 above)
Comment (alamb) [reply datafusion/optimizer/tests/optimizer_integration.rs:546]: it isn't needed because the outer query doesn't use `id`?

File: datafusion/expr/src/expr_rewriter/mod.rs (hunk 2 above)
Comment (nuno-faria) [reply datafusion/expr/src/expr_rewriter/mod.rs:268]: Added.

**Comment by nuno-faria** [comment]
> it isn't needed because the outer query doesn't use id?

The outer query uses `id` but the cast on the recursive branch was not needed since I think the name is set by the non-recursive term (or by the CTE definition).

**Comment by alamb** [comment]
Thanks again @nuno-faria
