### PR TITLE
Split output batches of joins that do not respect batch size

### LINKED ISSUE #12633: NestedLoopJoinExec can create excessively large record batches
### Describe the bug

`NestedLoopJoinExec` (really `NestedLoopJoinStream`) produces one output batch for each probe side input batch. However it is possible for each row of probe-side input to produce build-side length output rows. This can lead to some very large output batches being produced.

Some queries are being unnecessarily terminated due to high resource usage due to this.

### To Reproduce

Using datafusion-cli:

```
> SHOW datafusion.execution.batch_size;
+---------------------------------+-------+
| name                            | value |
+---------------------------------+-------+
| datafusion.execution.batch_size | 8192  |
+---------------------------------+-------+
1 row(s) fetched. 
Elapsed 0.010 seconds.

> CREATE TABLE test AS VALUES (0), (1), (2), (3), (4), (5), (6), (7), (8), (9);
0 row(s) fetched. 
Elapsed 0.035 seconds.

> EXPLAIN ANALYZE WITH test_t AS (SELECT concat(t1.column1, t2.column1, t3.column1, t4.column1, t5.column1) AS v FROM test t1, test t2, test t3, test t4, test t5) SELECT * FROM test_t tt1 FULL OUTER JOIN test_t tt2 ON tt1.v<>tt2.v;
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| plan_type         | plan                                                                                                                                                                                                                                                                                |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Plan with Metrics | NestedLoopJoinExec: join_type=Full, filter=v@0 != v@1, metrics=[output_rows=9999900000, build_input_batches=10000, build_input_rows=100000, input_batches=10000, input_rows=100000, output_batches=10001, build_mem_used=2492500, build_time=35.770239ms, join_time=309.795829686s] |
|                   |   CoalescePartitionsExec, metrics=[output_rows=100000, elapsed_compute=4.001292ms]                                                                                                                                                                                                  |
|                   |     ProjectionExec: expr=[concat(CAST(column1@1 AS Utf8), CAST(column1@2 AS Utf8), CAST(column1@3 AS Utf8), CAST(column1@4 AS Utf8), CAST(column1@0 AS Utf8)) as v], metrics=[output_rows=100000, elapsed_compute=54.673797ms]                                                      |
|                   |       CrossJoinExec, metrics=[output_rows=100000, build_input_batches=1, build_input_rows=10, input_batches=1000, input_rows=10000, output_batches=10000, build_mem_used=224, build_time=31.793µs, join_time=9.555719ms]                                                            |
|                   |         MemoryExec: partitions=1, partition_sizes=[1], metrics=[]                                                                                                                                                                                                                   |
|                   |         RepartitionExec: partitioning=RoundRobinBatch(10), input_partitions=1, metrics=[fetch_time=1.579937ms, repartition_time=1ns, send_time=8.415125ms]                                                                                                                          |
|                   |           ProjectionExec: expr=[column1@1 as column1, column1@2 as column1, column1@3 as column1, column1@0 as column1], metrics=[output_rows=10000, elapsed_compute=375.839µs]                                                                                                     |
|                   |             CrossJoinExec, metrics=[output_rows=10000, build_input_batches=1, build_input_rows=10, input_batches=100, input_rows=1000, output_batches=1000, build_mem_used=224, build_time=4.541µs, join_time=567.211µs]                                                            |
|                   |               MemoryExec: partitions=1, partition_sizes=[1], metrics=[]                                                                                                                                                                                                             |
|                   |               ProjectionExec: expr=[column1@1 as column1, column1@2 as column1, column1@0 as column1], metrics=[output_rows=1000, elapsed_compute=35.377µs]                                                                                                                         |
|                   |                 CrossJoinExec, metrics=[output_rows=1000, build_input_batches=1, build_input_rows=10, input_batches=10, input_rows=100, output_batches=100, build_mem_used=224, build_time=1.917µs, join_time=52.879µs]                                                             |
|                   |                   MemoryExec: partitions=1, partition_sizes=[1], metrics=[]                                                                                                                                                                                                         |
|                   |                   CrossJoinExec, metrics=[output_rows=100, build_input_batches=1, build_input_rows=10, input_batches=1, input_rows=10, output_batches=10, build_mem_used=224, build_time=2.417µs, join_time=11.377µs]                                                               |
|                   |                     MemoryExec: partitions=1, partition_sizes=[1], metrics=[]                                                                                                                                                                                                       |
|                   |                     MemoryExec: partitions=1, partition_sizes=[1], metrics=[]                                                                                                                                                                                                       |
|                   |   ProjectionExec: expr=[concat(CAST(column1@1 AS Utf8), CAST(column1@2 AS Utf8), CAST(column1@3 AS Utf8), CAST(column1@4 AS Utf8), CAST(column1@0 AS Utf8)) as v], metrics=[output_rows=100000, elapsed_compute=524.070156ms]                                                       |
|                   |     CrossJoinExec, metrics=[output_rows=100000, build_input_batches=1, build_input_rows=10, input_batches=1000, input_rows=10000, output_batches=10000, build_mem_used=224, build_time=7.084µs, join_time=73.915678ms]                                                              |
|                   |       MemoryExec: partitions=1, partition_sizes=[1], metrics=[]                                                                                                                                                                                                                     |
|                   |       RepartitionExec: partitioning=RoundRobinBatch(10), input_partitions=1, metrics=[fetch_time=2.26374ms, repartition_time=1ns, send_time=28.111445436s]                                                                                                                          |
|                   |         ProjectionExec: expr=[column1@1 as column1, column1@2 as column1, column1@3 as column1, column1@0 as column1], metrics=[output_rows=10000, elapsed_compute=477.113µs]                                                                                                       |
|                   |           CrossJoinExec, metrics=[output_rows=10000, build_input_batches=1, build_input_rows=10, input_batches=100, input_rows=1000, output_batches=1000, build_mem_used=224, build_time=2.75µs, join_time=1.069152ms]                                                              |
|                   |             MemoryExec: partitions=1, partition_sizes=[1], metrics=[]                                                                                                                                                                                                               |
|                   |             ProjectionExec: expr=[column1@1 as column1, column1@2 as column1, column1@0 as column1], metrics=[output_rows=1000, elapsed_compute=94.708µs]                                                                                                                           |
|                   |               CrossJoinExec, metrics=[output_rows=1000, build_input_batches=1, build_input_rows=10, input_batches=10, input_rows=100, output_batches=100, build_mem_used=224, build_time=708ns, join_time=165.327µs]                                                                |
|                   |                 MemoryExec: partitions=1, partition_sizes=[1], metrics=[]                                                                                                                                                                                                           |
|                   |                 CrossJoinExec, metrics=[output_rows=100, build_input_batches=1, build_input_rows=10, input_batches=1, input_rows=10, output_batches=10, build_mem_used=224, build_time=583ns, join_time=9.25µs]                                                                     |
|                   |                   MemoryExec: partitions=1, partition_sizes=[1], metrics=[]                                                                                                                                                                                                         |
|                   |                   MemoryExec: partitions=1, partition_sizes=[1], metrics=[]                                                                                                                                                                                                         |
|                   |                                                                                                                                                                                                                                                                                     |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row(s) fetched. 
Elapsed 34.928 seconds.
```

In this (obviously contrived) example the `NestedLoopJoinExec` produces 9999900000 `output_rows` in just 10001 `output_batches` meaning the mean batch size is 999890.01 rows long. That is significantly bigger than the expected size of 8192.

### Expected behavior

`NestedLoopJoinExec` should produce output batches much nearer to the configured batch size in length. Reducing the memory used by output record batches.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by alihan-synnada**
## Which issue does this PR close?

Closes #12633

## Rationale for this change

A join operation chain can create a RecordBatch whose size is thousands or even millions of rows. 

## What changes are included in this PR?

Adds a new config called `enforce_batch_size_in_joins` that is disabled by default. Enabling the config restricts the maximum output batch size of join operators to `batch_size`. #12634 is similar but it splits the join indices and then builds the output batches, which causes performance issues. This PR splits the output batches after the join is processed.

Improves `adjust_indices_by_join_type` performance by optimizing `PrimitiveArray` concatenation using `MutableArrayData`

## Are these changes tested?

Includes unit tests for `BatchSplitter`

## Are there any user-facing changes?

Users can optionally enable `enforce_batch_size_in_joins` in cases where joins cause out-of-memory. No breaking changes

### CODE REVIEW

**Comment by alamb** [comment]
fyi @mhilton

**Comment by alamb** [comment]
I will review this later today

**Review by ozankabak — APPROVED** [review]
I reviewed this carefully and it looks good to me.

This doesn't cause any performance issues but solves the "growing batch sizes" problem in plans with cascaded joins

File: datafusion/physical-plan/src/joins/utils.rs [hunk 1]
```diff
@@ -1356,17 +1357,34 @@ pub(crate) fn append_right_indices(
...
             // the new right indices: right_indices + right_unmatched_indices
-            let new_left_indices = left_indices
-                .iter()
-                .chain(std::iter::repeat(None).take(unmatched_size))
-                .collect();
-            let new_right_indices = right_indices
-                .iter()
-                .chain(right_unmatched_indices.iter())
-                .collect();
+            let mut new_right_indices = MutableArrayData::new(
```
Comment (Dandandan) [inline datafusion/physical-plan/src/joins/utils.rs:1379]: I think we could use `Vec<u64>` and `Vec<u32>` instead of `MutableArrayData`

Comment (alihan-synnada) [reply datafusion/physical-plan/src/joins/utils.rs:1379]: I tried the following code but it's about 200% slower. Is there a more optimized way to use `Vec` in this context?

```
// the new left indices: left_indices + null array
let mut new_left_indices = Vec::with_capacity(left_size + unmatched_size);
new_left_indices.extend(left_indices.values().iter().map(|v| Some(*v)));
new_left_indices.append(&mut vec![None; unmatched_size]);
let new_left_indices = UInt64Array::from(new_left_indices);

// the new right indices: right_indices + right_unmatched_indices
let mut new_right_indices = Vec::with_capacity(right_size + unmatched_size);
new_right_indices.extend(right_indices.values().iter());
new_right_indices.extend(right_unmatched_indices.values().iter());
let new_right_indices = UInt32Array::from(new_right_indices);
```

**Comment by mhilton** [comment]
Unfortunately this doesn't address the actual problem with creating giant batches, which is they require a lot of memory and that memory isn't accounted for in any `MemoryPool`. Wiring a `MemoryReservation` into `BatchSplitter` would probably be enough to address this though.

**Comment by ozankabak** [comment]
> Wiring a MemoryReservation into BatchSplitter would probably be enough to address this though.

Thanks for bringing this to our attention. We will add this in a quick follow-on PR.

File: datafusion/physical-plan/src/joins/utils.rs (hunk 1 above)
Comment (Dandandan) [reply datafusion/physical-plan/src/joins/utils.rs:1379]: Hm you're right, sorry I missed that it was producing nulls, in that case this is not very efficient indeed.

Seems though we can just use https://docs.rs/arrow/latest/arrow/array/struct.PrimitiveBuilder.html then instead?

Comment (ozankabak) [reply datafusion/physical-plan/src/joins/utils.rs]: Good news: It runs much faster with `into_builder`.
Bad news: It seems like we actually exercise the `internal_err` (i.e. ref count > 2 to the underlying buffer) in some cases. We will debug and finalize (hopefully) tomorrow.

File: datafusion/physical-plan/src/joins/utils.rs [hunk 2]
```diff
@@ -1635,6 +1643,87 @@ pub(crate) fn asymmetric_join_output_partitioning(
     }
 }
 
+pub(crate) trait BatchTransformer: Debug + Clone {
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/utils.rs:1646]: I think some context would help here. Something like this perhaps:

```suggestion
/// Trait for incrementally generating Join output. 
///
/// This trait is used to limit some join outputs 
/// so it does not produce single large batches 
pub(crate) trait BatchTransformer: Debug + Clone {
```

File: datafusion/physical-plan/src/joins/symmetric_hash_join.rs [hunk 3]
```diff
@@ -502,29 +510,52 @@ impl ExecutionPlan for SymmetricHashJoinExec {
...
+                right: right_side_joiner,
+                column_indices: self.column_indices.clone(),
+                metrics: StreamJoinMetrics::new(partition, &self.metrics),
+                graph,
+                left_sorted_filter_expr,
+                right_sorted_filter_expr,
+                null_equals_null: self.null_equals_null,
+                state: SHJStreamState::PullRight,
+                reservation,
+                batch_transformer: BatchSplitter::new(batch_size),
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/symmetric_hash_join.rs:531]: Given the ovehead of a BatchTransformer is likely small (one function call per output batch). I suggest trying to use a `dyn` trait object here and in the other joins instead (e.g. `batch_transformer: Box<dyn BatchTransformer>`)

I suspect it would not make any noticable performance difference

**Review by alamb — COMMENTED** [review]
This is interesting -- thank you @alihan-synnada and @ozankabak 

I wonder if you have considered updating the join algorithms themselves to incrementally produce output (rather than generating one large RecordBatch and the slicing it up?) 

We found in the GroupBy that the slicing requires non trivial time -- see  https://github.com/apache/datafusion/issues/9562 and the POC by @Rachelint  in https://github.com/apache/datafusion/pull/11943

File: datafusion/physical-plan/src/joins/utils.rs (hunk 1 above)
Comment (Dandandan) [reply datafusion/physical-plan/src/joins/utils.rs]: Side note: I think we might be even better off in future to pass the (owned) primitive builders to the different methods instead of trying to convert the arrays to builders again, this probably saves some copies in other places as well.

File: datafusion/common/src/config.rs [hunk 4]
```diff
@@ -338,6 +338,12 @@ config_namespace! {
         /// if the source of statistics is accurate.
         /// We plan to make this the default in the future.
         pub use_row_number_estimates_to_optimize_partitioning: bool, default = false
+
+        /// Should DataFusion enforce batch size in joins or not. By default,
+        /// DataFusion will not enforce batch size in joins. Enforcing batch size
+        /// in joins can help to avoid out-of-memory errors when joining large
+        /// tables with a highly-selective join filter.
```
[the remark this answers is not in the document]
Comment (alihan-synnada) [reply datafusion/common/src/config.rs:345]: We profiled both approaches (generating multiple RecordBatches vs generating one RecordBatch and then slicing it) and figured out that multiple calls to `apply_join_filter_to_indices` and `adjust_indices_by_join_type` in the incremental computation case slows down the process severely, especially with smaller batch sizes (https://github.com/apache/datafusion/pull/12634#issuecomment-2393215346). Maybe we can try combining the two approaches such that we create multiple RecordBatches to be sliced per probe side batch.

Also `adjust_indices_by_join_type` is optimized now so it might be worth profiling again. The slowdown in `apply_join_filter_to_indices` comes from `arrow::compute::filter` so I don't know if it can be optimized further.

File: datafusion/physical-plan/src/joins/utils.rs [hunk 5]
```diff
@@ -1361,17 +1361,47 @@ pub(crate) fn append_right_indices(
...
+                left_indices.into_builder().unwrap_or_else(|left_indices| {
+                    let mut builder = UInt64Builder::with_capacity(
+                        left_indices.len() + right_unmatched_indices.len(),
+                    );
+                    debug_assert_eq!(
+                        left_indices.null_count(),
+                        0,
+                        "expected left indices to have no nulls"
+                    );
+                    builder.append_slice(left_indices.values());
```
Comment (Dandandan) [inline datafusion/physical-plan/src/joins/utils.rs:1379]: I wonder if at this point the left array `Arc` can be dropped  such that the right side can be converted to builder without issue.

File: datafusion/common/src/config.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (Dandandan) [reply datafusion/common/src/config.rs:345]: In my profiling experience, `take` (for selecting the values for columns to be filtered) is expensive as well  if there is a filter (e.g. in nested loop join). This is often more expensive than the filter operation.

**Comment by ozankabak** [comment]
I will go ahead and merge this soon unless someone catches a critical issue.

Here are the things to work on in the near future:
1. Add `MemoryReservation` to batch splitting to add rigorous memory accountability.
2. Exploring if we can pass builders into methods instead of passing arrays around and converting them into builders when possible.
3. Considering using  the`batch_transformer: Box<dyn BatchTransformer>` pattern if it doesn't regress performance

**Comment by alamb** [comment]
> I will go ahead and merge this soon unless someone catches a critical issue.

Thank you -- I agree this is better than what was on main

> 
> Here are the things to work on in the near future:
> 
> 1. Add `MemoryReservation` to batch splitting to add rigorous memory accountability.
> 2. Exploring if we can pass builders into methods instead of passing arrays around and converting them into builders when possible.
> 3. Considering using  the`batch_transformer: Box<dyn BatchTransformer>` pattern if it doesn't regress performance


I filed https://github.com/apache/datafusion/issues/13003 to track adding memory accounting
