### PR TITLE
fix: derive custom nullable for spark `make_dt_interval`

### LINKED ISSUE #19154: spark `make_dt_interval` need to have custom nullability
### Describe the bug

the UDF uses the default `is_nullable` which is always true which is not the case

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kumarUjjawal**
## Which issue does this PR close?

- Closes #19154 
- Part of #19144 

## What changes are included in this PR?

- Spark `make_dt_interval` now uses `return_field_from_args`

## Are these changes tested?

- All original test pass
- Added new test to nullability check

### CODE REVIEW

File: datafusion/spark/src/function/datetime/make_dt_interval.rs [hunk 1]
```diff
@@ -99,7 +101,16 @@ impl ScalarUDFImpl for SparkMakeDtInterval {
     ///
     /// [Sail compatibility doc]: https://github.com/lakehq/sail/blob/dc5368daa24d40a7758a299e1ba8fc985cb29108/docs/guide/dataframe/data-types/compatibility.md?plain=1#L260
     fn return_type(&self, _arg_types: &[DataType]) -> Result<DataType> {
-        Ok(DataType::Duration(Microsecond))
+        internal_err!("return_field_from_args should be used instead")
+    }
+
+    fn return_field_from_args(&self, args: ReturnFieldArgs) -> Result<FieldRef> {
+        let nullable = args.arg_fields.iter().any(|f| f.is_nullable());
```
Comment (martin-g) [inline datafusion/spark/src/function/datetime/make_dt_interval.rs]: This is not enough.
See https://github.com/apache/datafusion/pull/19236/files#diff-c1ad8cc4eaab5f736bb30342887defb1d018651dda5850924d8b4ed463bf2d8fR173
If `secs` is NAN/infinite then it is considered as a NULL.

Comment (kumarUjjawal) [reply datafusion/spark/src/function/datetime/make_dt_interval.rs]: Updated  so if any input is nullable or `secs` is a non‑finite literal , the output is marked nullable, otherwise it stays non‑nullable.

**Comment by kumarUjjawal** [comment]
> Thanks @kumarUjjawal for taking care on this

I'm happy to contribute.
