### PR TITLE
fix: Rewrite `date_trunc` and `from_unixtime` for the SQLite unparser

### LINKED ISSUE #15629: SQLite does not support `from_unixtime` or `date_trunc`
### Describe the bug

The scalars `from_unixtime` and `date_trunc` are unsupported in SQLite, and are not re-written into a supported format when using `SqliteDialect`.

### To Reproduce

Using the `SqliteDialect`, attempt a query which contains the `from_unixtime` or `date_trunc` scalars. The query is not re-written when unparsed, and the `from_unixtime` scalar does not exist in SQLite - so the query then fails.

### Expected behavior

The unparser should rewrite the scalar into a supported format, like `strftime()` for `date_trunc` or `datetime(col, 'unixepoch')` for `from_unixtime()`.

### Additional context

I have already implemented a fix in a fork, and will be opening a PR with a fix that implements the unparser rewrite for `SqliteDialect`.

### PR DESCRIPTION
**Pull request by peasee**
## Which issue does this PR close?

- Closes #15629

## Rationale for this change

SQLite does not support timestamp/date scalars like `to_timestamp`, `from_unixtime`, `date_trunc`, etc.

## What changes are included in this PR?

For the `SqliteDialect`:

* Updates `from_unixtime` to `datetime(expr, 'unixepoch')`, expecting the input to be in seconds.
* Updates `date_trunc` to use the `strftime` function to format the timestamp as a string depending on the truncation unit.
  * This is about as good as we can get with SQLite, given that dates and timestamps are all represented as strings in SQLite.

## Are these changes tested?

Yes. I've added new units tests in the unparser.

## Are there any user-facing changes?

No.

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Thank you @peasee !

@phillipleblanc  do you perhaps have some time to review this PR?

File: datafusion/sql/src/unparser/expr.rs [hunk 1]
```diff
@@ -2871,6 +2872,118 @@ mod tests {
...
+
+        for (dialect, expected) in [
+            (default_dialect, "from_unixtime(date_col)"),
+            (sqlite_dialect, "datetime(`date_col`, 'unixepoch')"),
+        ] {
+            let unparser = Unparser::new(dialect.as_ref());
+            let expr = Expr::ScalarFunction(ScalarFunction {
+                func: Arc::new(ScalarUDF::from(
+                    datafusion_functions::datetime::from_unixtime::FromUnixtimeFunc::new(
+                    ),
```
Comment (phillipleblanc) [inline datafusion/sql/src/unparser/expr.rs:2888]:
```suggestion
                    datafusion_functions::datetime::from_unixtime::FromUnixtimeFunc::new(),
```

**Review by phillipleblanc — APPROVED** [review]
Thanks @peasee! One minor comment on the test.

Context/Disclosure: I had also reviewed a similar PR into [our internal fork](https://github.com/spiceai/datafusion/pull/71) a few months ago and found we had not yet requested the upstream version of this.

File: datafusion/sql/src/unparser/expr.rs (hunk 1 above)
Comment (peasee) [reply datafusion/sql/src/unparser/expr.rs]: `cargo fmt` is unhappy with it on a single line 😞

Comment (peasee) [reply datafusion/sql/src/unparser/expr.rs]: I've updated to import the module, the shorter module path formats better

**Review by phillipleblanc — APPROVED** [review]
Thanks!

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Thank you @peasee and @phillipleblanc
