### PR TITLE
fix: implement custom nullability for spark abs function

### LINKED ISSUE #19162: spark `abs` need to have custom nullability
### Describe the bug

the UDF uses the default `is_nullable` which is always true which is not the case

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by batmnnn**
Fixes apache/datafusion #19162

The SparkAbs UDF was using the default is_nullable=true for all outputs, even when inputs were non-nullable. This commit implements return_field_from_args to properly propagate nullability from input arguments.

Changes:
- Add return_field_from_args implementation to SparkAbs
- Output nullability now matches input nullability
- Handle edge case where scalar argument is explicitly null
- Add tests for nullability behavior

## Which issue does this PR close?

Closes #19162

## Rationale for this change

[SparkAbs](cci:2://file:///Users/batman/datafusion/datafusion/spark/src/function/math/abs.rs:41:0-43:1) was always returning `nullable=true` even for non-nullable inputs.

## What changes are included in this PR?

Implement [return_field_from_args](cci:1://file:///Users/batman/datafusion/datafusion/expr/src/udf.rs:210:4-215:5) to propagate nullability from input arguments.

## Are these changes tested?

Yes, added 2 tests for nullability behavior.

## Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by batmnnn** [comment]
@martin-g @rluvaton can you please review this

File: datafusion/spark/src/function/math/abs.rs [hunk 1]
```diff
@@ -69,8 +70,32 @@ impl ScalarUDFImpl for SparkAbs {
...
-        Ok(arg_types[0].clone())
+    fn return_type(&self, _arg_types: &[DataType]) -> Result<DataType> {
+        internal_err!(
+            "SparkAbs: return_type() is not used; return_field_from_args() is implemented"
+        )
+    }
+
+    fn return_field_from_args(&self, args: ReturnFieldArgs) -> Result<FieldRef> {
+        if args.arg_fields.is_empty() {
+            return internal_err!("abs expects at least 1 argument");
```
Comment (martin-g) [inline datafusion/spark/src/function/math/abs.rs]: There is no really need for this check. The method won't be called at all if the signature does not match.

But if you prefer to have it then let's synchronise it with the `spark_abs()` error message:
```suggestion
            return internal_err!("abs takes exactly 1 argument, but got: {}", args.arg_fields.len());
```

File: datafusion/spark/src/function/math/abs.rs [hunk 2]
```diff
@@ -375,4 +400,92 @@ mod tests {
...
+        use datafusion_expr::ReturnFieldArgs;
+        use std::sync::Arc;
+
+        let func = SparkAbs::new();
+
+        // Non-nullable field with non-null scalar argument -> non-nullable result
+        let non_nullable: FieldRef = Arc::new(Field::new("col", DataType::Int32, false));
+        let out = func.return_field_from_args(ReturnFieldArgs {
+            arg_fields: &[Arc::clone(&non_nullable)],
+            scalar_arguments: &[None],
```
Comment (martin-g) [inline datafusion/spark/src/function/math/abs.rs]:
```suggestion
            scalar_arguments: &[Some(ScalarValue::Int32(Some(1)))],
```

**Comment by batmnnn** [comment]
thanks @martin-g

File: datafusion/spark/src/function/math/abs.rs [hunk 3]
```diff
@@ -69,8 +70,35 @@ impl ScalarUDFImpl for SparkAbs {
...
+
+        // If any scalar argument is explicitly null, output must be nullable
+        let scalar_null_present = args
+            .scalar_arguments
+            .iter()
+            .any(|opt_s| opt_s.is_some_and(|sv| sv.is_null()));
+
+        if scalar_null_present {
+            out_nullable = true;
+        }
```
Comment (Jefffrey) [inline datafusion/spark/src/function/math/abs.rs]: Is this scalar null check strictly required? If an input argument is scalar null, then the datatype of that field would already be nullable, right?

File: datafusion/spark/src/function/math/abs.rs [hunk 4]
```diff
@@ -69,8 +70,35 @@ impl ScalarUDFImpl for SparkAbs {
...
+        )
+    }
+
+    fn return_field_from_args(&self, args: ReturnFieldArgs) -> Result<FieldRef> {
+        if args.arg_fields.is_empty() {
+            return internal_err!(
+                "abs takes exactly 1 argument, but got: {}",
+                args.arg_fields.len()
+            );
+        }
```
Comment (Jefffrey) [inline datafusion/spark/src/function/math/abs.rs]:
```suggestion
```

We don't need this check, signature guards us

File: datafusion/spark/src/function/math/abs.rs (hunk 3 above)
Comment (batmnnn) [reply datafusion/spark/src/function/math/abs.rs]: You're right, in normal cases the field should already be nullable. Happy to remove this check if we're confident the schema is always correct at this point.

Comment (Jefffrey) [reply datafusion/spark/src/function/math/abs.rs]: Yes we should remove this check as it's unnecessary

**Comment by Jefffrey** [comment]
Thanks @batmnnn & @martin-g

**Comment by batmnnn** [comment]
thanks for guidance and help  @Jefffrey & @martin-g
