### PR TITLE
fix: UnnestExec preserves relevant equivalence properties of input

### LINKED ISSUE #15231: unnest should preserve the input's equivalence properties for uninvolved columns
Continuing the discussion from last comments in  #14991 

It looks like unnest's implementation does preserve the output ordering of the columns that aren't being unnested, but it doesn't preserve their equivalence properties. This leads to situation where ordering information is lost and results in unnecessary unordered aggregation (which also breaks streaming queries that unnest and re-aggregate columns).

### PR DESCRIPTION
**Pull request by vegarsti**
## Which issue does this PR close?
- Closes https://github.com/apache/datafusion/issues/15231.

## What changes are included in this PR?
- In `UnnestExec`'s `compute_properties` we now construct its`EquivalenceProperties` using what we can from the input plan, so that we preserve sort ordering of unrelated columns (and avoid unnecessary sorts further up in the plan).

## Are these changes tested?
- Adds test cases to the sqllogictests for `UnnestExec` in `unnest.slt`

## Are there any user-facing changes?
No

## Explanation
Given a struct or array value `col`, `unnest(col)` takes the N elements of `col` and "spreads" these onto N rows, where all other columns in the statement are preserved. Said another way, when we unnest a column we are inserting a lateral cross-join against its elements, which by construction:
- Duplicates every other column once for each array/map element
- Replaces the original collection column with one (or more) “element” columns
- Expands one input row into zero (if empty) or many output rows

E.g. (from `unnest.slt`):
https://github.com/apache/datafusion/blob/6d9b76e4a30f6234ffa3f8100b5d4c2735558ca6/datafusion/sqllogictest/test_files/unnest.slt#L699-L712

The [`EquivalenceProperties` struct](https://github.com/apache/datafusion/blob/66d6995b8f626f28f811489bd2cb552b6c64a85f/datafusion/physical-expr/src/equivalence/properties/mod.rs#L133-L146) has three types of properties:
1. equivalence groups (expressions with the same value)
2. ordering equivalence classes (expressions that define the same ordering)
3. table constraints - a set of columns that form a primary key or a unique key

In this PR we construct the `UnnestExec` node's `EquivalenceProperties` by using the input plan's equivalence properties for the columns that are not transformed - except for table constraints, which we discard entirely. The reasoning for discarding constraints is that because we're duplicating the other columns across rows, we are invalidating any uniqueness or primary-key constraint. We also need to some twiddling with the mapping of the projection (indices change due to the unnesting).

### CODE REVIEW

File: datafusion/physical-expr/src/equivalence/ordering.rs [hunk 1]
```diff
@@ -74,6 +74,11 @@ impl OrderingEquivalenceClass {
         result
     }
 
+    /// Returns the orderings in this ordering equivalence class.
+    pub fn orderings(&self) -> &[LexOrdering] {
```
Comment (vegarsti) [inline datafusion/physical-expr/src/equivalence/ordering.rs]: Needed this to pass the orderings in the next file diff. Let me know if this is not a good way to do it.

File: datafusion/physical-plan/src/unnest.rs [hunk 2]
```diff
@@ -101,8 +101,22 @@ impl UnnestExec {
         input: &Arc<dyn ExecutionPlan>,
         schema: SchemaRef,
     ) -> PlanProperties {
+        // Extract equivalence properties from input plan
+        let input_eq_properties = input.equivalence_properties();
+        let input_oeq_class = input_eq_properties.oeq_class();
+        let orderings = input_oeq_class.orderings().to_vec();
+        let eq_group = input_eq_properties.eq_group();
+        let constraints = input_eq_properties.constraints();
+
```
Comment (vegarsti) [inline datafusion/physical-plan/src/unnest.rs:169]: In the UnnestExec, we have `list_column_indices: Vec<ListUnnest>` and `struct_column_indices: Vec<usize>`. What I don't know is whether we need to explicitly remove these  from the new `EquivalenceProperties` object, or whether that happens "automatically", or whether it doesn't hurt that they are there.

File: datafusion/physical-plan/src/unnest.rs [hunk 3]
```diff
@@ -101,8 +101,22 @@ impl UnnestExec {
...
+        // Create new equivalence properties for the unnest plan based on the input plan
+        let mut eq_properties = EquivalenceProperties::new(schema);
+        eq_properties.add_orderings(orderings);
+        eq_properties
+            .add_equivalence_group(eq_group.to_owned())
+            .unwrap(); // We can unwrap this because we know this is a valid equivalence group
```
Comment (vegarsti) [inline datafusion/physical-plan/src/unnest.rs]: Let me know if this `unwrap` and reasoning seem wrong

File: datafusion/sqllogictest/test_files/unnest.slt [hunk 4]
```diff
@@ -941,3 +941,60 @@ where min_height * width1 = (
...
+10)------------------RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=1
+11)--------------------BoundedWindowAggExec: wdw=[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING: Field { name: "row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING", data_type: UInt64, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, frame: ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING], mode=[Sorted]
+12)----------------------LazyMemoryExec: partitions=1, batch_generators=[range: start=1, end=5, batch_size=8192]
+
+## Unnest without ordering
+query TT
+EXPLAIN WITH unnested AS (SELECT
+    random() AS generated_id,
+    unnest(array[value]) as ar
+  FROM range(1,5)) SELECT array_agg(ar) FROM unnested group by generated_id;
```
Comment (vegarsti) [inline datafusion/sqllogictest/test_files/unnest.slt]: Not sure I need to add this, there is another explain test case above: 
https://github.com/apache/datafusion/blob/9b27952303d38f9991475e9feb1d81ccac9d4f65/datafusion/sqllogictest/test_files/unnest.slt#L593-L608

**Comment by vegarsti** [comment]
Tagging @alamb, maybe you can trigger CI? 🙏🏻

File: datafusion/physical-plan/src/unnest.rs (hunk 2 above)
Comment (vegarsti) [reply datafusion/physical-plan/src/unnest.rs:169]: Since we have the correct schema, what may happen is that it thinks it has an ordering on some column `col` (because we copy the properties from the input), but we have unnested `col` so it no longer exists. Not sure what the impact of that would be.

File: datafusion/physical-plan/src/unnest.rs [hunk 5]
```diff
@@ -51,8 +51,8 @@ use futures::{Stream, StreamExt};
 use log::trace;
 
 /// Unnest the given columns (either with type struct or list)
-/// For list unnesting, each rows is vertically transformed into multiple rows
-/// For struct unnesting, each columns is horizontally transformed into multiple columns,
+/// For list unnesting, each row is vertically transformed into multiple rows
+/// For struct unnesting, each column is horizontally transformed into multiple columns,
```
Comment (vegarsti) [inline datafusion/physical-plan/src/unnest.rs:58]: Grammar fix

File: datafusion/sqllogictest/test_files/unnest.slt (hunk 4 above)
Comment (asubiotto) [reply datafusion/sqllogictest/test_files/unnest.slt]: I think it's fine to only have a single EXPLAIN test case for the ordering

File: datafusion/physical-plan/src/unnest.rs (hunk 2 above)
Comment (asubiotto) [reply datafusion/physical-plan/src/unnest.rs:169]: I think rather than creating a new equivalence properties object and trying to set all known fields, I would follow an approach similar to what filter does: https://github.com/apache/datafusion/blob/4bc66c80d560581f527dee5774fb4f0479786d3e/datafusion/physical-plan/src/filter.rs#L267

Which basically clones the full input equivalence properties and then modifies it. In this case I believe we should just remove the orderings on the columns we're unnesting.

I'm not very familiar with this code so not sure how to express this exactly.

**Review by asubiotto — COMMENTED** [review]
Nice!

File: datafusion/sqllogictest/test_files/unnest.slt (hunk 4 above)
Comment (vegarsti) [reply datafusion/sqllogictest/test_files/unnest.slt]: Yeah, makes sense! Will remove

File: datafusion/physical-plan/src/unnest.rs (hunk 2 above)
Comment (vegarsti) [reply datafusion/physical-plan/src/unnest.rs:169]: Yeah, that makes more sense. I guess this is essentially what I'm doing here, except cloning is a lot better.

I haven't figured out how to remove the ordering of the columns we're unnesting yet, though 🤔

Comment (vegarsti) [reply datafusion/physical-plan/src/unnest.rs:169]: Oh I remember now: I tried cloning but this doesn't work as this doesn't have the correct `Schema` (the `UnnestExec` necessarily has a different schema than the input plan). This fails on other test cases, in `sort_merge_join.slt`:

```
1. query failed: DataFusion error: Internal error: Input field name __unnest_placeholder(range(Int64(0),Int64(10))) does not match with the projection expression __unnest_placeholder(range(Int64(0),Int64(10)),depth=1).
This issue was likely caused by a bug in DataFusion's code. Please help us to resolve this by filing a bug report in our issue tracker: https://github.com/apache/datafusion/issues
[SQL] select * from (
with t as (
    select id, id % 5 id1 from (select unnest(range(0,10)) id)
), t1 as (
    select id % 10 id, id + 2 id1 from (select unnest(range(0,10)) id)
)
select * from t right join t1 on t.id1 = t1.id and t.id > t1.id1
) order by 1, 2, 3, 4
at .../datafusion/datafusion/sqllogictest/test_files/sort_merge_join.slt:603

2. query failed: DataFusion error: Internal error: Input field name __unnest_placeholder(make_array(Int64(0),Int64(1),Int64(2),Int64(3),Int64(4),Int64(5),Int64(6),Int64(7),Int64(8),Int64(9))) does not match with the projection expression __unnest_placeholder(make_array(Int64(0),Int64(1),Int64(2),Int64(3),Int64(4),Int64(5),Int64(6),Int64(7),Int64(8),Int64(9)),depth=1).
This issue was likely caused by a bug in DataFusion's code. Please help us to resolve this by filing a bug report in our issue tracker: https://github.com/apache/datafusion/issues
[SQL] select * from (
with t as (
    select id_a id_a_1, id_a % 5 id_a_2 from (select unnest(make_array(5, 6, 7, 8, 9, 0, 1, 2, 3, 4)) id_a)
), t1 as (
    select id_b % 10 id_b_1, id_b + 2 id_b_2 from (select unnest(make_array(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)) id_b)
)
select * from t full join t1 on t.id_a_2 = t1.id_b_1 and t.id_a_1 > t1.id_b_2
) order by 1, 2, 3, 4
at .../datafusion/datafusion/sqllogictest/test_files/sort_merge_join.slt:624
```

Comment (vegarsti) [reply datafusion/physical-plan/src/unnest.rs:169]: Another option I tried now is this, but `with_new_schema` fails because the schema needs to be aligned (same number of columns, same types).

```
        let eq_properties = input
            .equivalence_properties()
            .clone()
            .with_new_schema(schema)
            .unwrap();
```

Comment (vegarsti) [reply datafusion/physical-plan/src/unnest.rs:169]: I will have a look at this recently merged PR which did an overhaul on EquivalenceProperties https://github.com/apache/datafusion/pull/16217, maybe something to learn there.

Comment (asubiotto) [reply datafusion/physical-plan/src/unnest.rs:169]: I'm not quite sure what the recommended approach here would be. Maybe one of the datafusion maintainers will be able to shed light on this when they review. Otherwise there might be someone on the discord familiar with this that could help: https://discord.gg/vvhe8G6s

Comment (vegarsti) [reply datafusion/physical-plan/src/unnest.rs:169]: Good idea, posted on Discord! https://discord.com/channels/885562378132000778/1166447479609376850/1400462595797815498

Comment (vegarsti) [reply datafusion/physical-plan/src/unnest.rs:169]: @ozankabak Do you have any pointers? I can't see that any of the structs related to equivalence properties expose any functionality for removing a column from it, is there another way to go about this?

**Comment by vegarsti** [comment]
I discovered [`EquivalenceProperties.project`](https://github.com/apache/datafusion/blob/b4e7147c85b52addd687e5524e6ebbc5ad7d675d/datafusion/physical-expr/src/equivalence/properties/mod.rs#L1127-L1144), which seems to do what we need: We can get the unnest plan's equivalence properties by doing `input_eq_properties.project(unnested_columns, schema)`, i.e. discarding the properties of the columns that are being unnested.

I have updated the PR doing that.

Equivalence properties are
1. equivalence groups (expressions with the same value)
2. ordering equivalence classes (expressions that define the same ordering)
3. table constraints - these can be primary key or unique

I am pretty sure that this takes care of 1 and 2, since we now have no equivalence properties for the columns. I am not yet sure about 3, though - if the original expression uses a column that is a primary key, after the unnest we will have multiple rows with the same column. Does that mean we need to remove that constraint from the eq properties? It kinda sounds like yes, but I need to see exactly what it's being used for.

File: datafusion/physical-plan/src/unnest.rs (hunk 2 above)
Comment (vegarsti) [reply datafusion/physical-plan/src/unnest.rs:169]: Linking to new approach using `EquivalenceProperties.project`: https://github.com/apache/datafusion/pull/16985#issuecomment-3148121449

**Comment by vegarsti** [comment]
> I discovered [`EquivalenceProperties.project`](https://github.com/apache/datafusion/blob/b4e7147c85b52addd687e5524e6ebbc5ad7d675d/datafusion/physical-expr/src/equivalence/properties/mod.rs#L1127-L1144), which seems to do what we need: We can get the unnest plan's equivalence properties by doing `input_eq_properties.project(unnested_columns, schema)`, i.e. discarding the properties of the columns that are being unnested.
> 
> I have updated the PR doing that.
> 
> Equivalence properties are
> 
> 1. equivalence groups (expressions with the same value)
> 2. ordering equivalence classes (expressions that define the same ordering)
> 3. table constraints - these can be primary key or unique
> 
> I am pretty sure that this takes care of 1 and 2, since we now have no equivalence properties for the columns. I am not yet sure about 3, though - if the original expression uses a column that is a primary key, after the unnest we will have multiple rows with the same column. Does that mean we need to remove that constraint from the eq properties? It kinda sounds like yes, but I need to see exactly what it's being used for.

After reading some more I have now updated it so that we remove any constraint from the properties. I've updated the PR description.

I think this is semantically sound now.

FYI @alamb and @asubiotto

File: datafusion/physical-plan/src/unnest.rs [hunk 6]
```diff
@@ -99,10 +105,38 @@ impl UnnestExec {
...
+        // Create the unnest equivalence properties by copying the input plan's equivalence properties
+        // for the unaffected columns.
+        // Except for the constraints, which are removed entirely because the unnest operation invalidates
+        // any global uniqueness or primary-key constraints.
+        let input_eq_properties = input.equivalence_properties();
+        let projection_mapping =
+            ProjectionMapping::from_indices(&non_unnested_indices, &schema).unwrap();
+        let eq_properties = input_eq_properties
+            .project(&projection_mapping, schema.clone())
+            // Remove any existing constraints
```
Comment (asubiotto) [inline datafusion/physical-plan/src/unnest.rs]: nit: remove this comment, I think you were clear enough above.

**Review by asubiotto — APPROVED** [review]
Nice work! This LGTM, I'll leave it to @alamb for a final review and CI kickoff.

File: datafusion/physical-plan/src/unnest.rs (hunk 6 above)
Comment (vegarsti) [reply datafusion/physical-plan/src/unnest.rs]: Thanks, yeah!

**Comment by vegarsti** [comment]
Would love your eyes on this as well @berkaysynnada @ozankabak since I know you all wrote the EquivalenceProperties module.

**Comment by vegarsti** [comment]
Thanks for triggering CI! I'm embarrassed I hadn't seen the clippy error, I will fix it asap.

The command that failed was
```
cargo clippy --all-targets --workspace --features avro,pyarrow,integration-tests -- -D warnings
```

**Comment by vegarsti** [comment]
> Thanks for tagging for CI! I'm embarrassed I hadn't seen the clippy error, I will fix it asap.

Fixed now: `schema.clone()` to `Arc::clone(&schema)`

**Comment by vegarsti** [comment]
@alamb Can you please trigger CI? 😄

**Comment by vegarsti** [comment]
Sorry to bug you again @alamb, do you have time to review this today or tomorrow? 👀  Do let me know if there's anything that I can do to make it easier to review.

**Comment by alamb** [comment]
> Sorry to bug you again @alamb, do you have time to review this today or tomorrow? 👀 Do let me know if there's anything that I can do to make it easier to review.

Hi @vegarsti  - sorry I didn't see this earlier. I will try and review it over the next day or two

Maybe @berkaysynnada or @suremarc has some time to review as well

**Comment by vegarsti** [comment]
Friendly ping @alamb 😄

File: datafusion/sqllogictest/test_files/unnest.slt [hunk 7]
```diff
@@ -941,3 +941,33 @@ where min_height * width1 = (
 )
 ----
 4 7 4 28
+
+## Unnest with ordering on unrelated column is preserved
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/unnest.slt:945]: I did verify that this test fails without the code change in this PR, but it wasn't clear to me why (the new plan has a sort, which the original did not)

```diff
diff --git a/datafusion/sqllogictest/test_files/unnest.slt b/datafusion/sqllogictest/test_files/unnest.slt
index 6d5151e1d..eb4abaffc 100644
--- a/datafusion/sqllogictest/test_files/unnest.slt
+++ b/datafusion/sqllogictest/test_files/unnest.slt
@@ -960,14 +960,13 @@ logical_plan
 08)--------------TableScan: range() projection=[value]
 physical_plan
 01)ProjectionExec: expr=[array_agg(unnested.ar)@1 as array_agg(unnested.ar)]
-02)--AggregateExec: mode=FinalPartitioned, gby=[generated_id@0 as generated_id], aggr=[array_agg(unnested.ar)], ordering_mode=Sorted
-03)----SortExec: expr=[generated_id@0 ASC NULLS LAST], preserve_partitioning=[true]
-04)------CoalesceBatchesExec: target_batch_size=8192
-05)--------RepartitionExec: partitioning=Hash([generated_id@0], 4), input_partitions=4
-06)----------AggregateExec: mode=Partial, gby=[generated_id@0 as generated_id], aggr=[array_agg(unnested.ar)], ordering_mode=Sorted
-07)------------ProjectionExec: expr=[generated_id@0 as generated_id, __unnest_placeholder(make_array(range().value),depth=1)@1 as ar]
-08)--------------UnnestExec
-09)----------------ProjectionExec: expr=[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING@1 as generated_id, make_array(value@0) as __unnest_placeholder(make_array(range().value))]
-10)------------------RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=1
-11)--------------------BoundedWindowAggExec: wdw=[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING: Field { name: "row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND
UNBOUNDED FOLLOWING", data_type: UInt64, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, frame: ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING], mode=[Sorte
d]
-12)----------------------LazyMemoryExec: partitions=1, batch_generators=[range: start=1, end=5, batch_size=8192]
+02)--AggregateExec: mode=FinalPartitioned, gby=[generated_id@0 as generated_id], aggr=[array_agg(unnested.ar)]
+03)----CoalesceBatchesExec: target_batch_size=8192
+04)------RepartitionExec: partitioning=Hash([generated_id@0], 4), input_partitions=4
+05)--------AggregateExec: mode=Partial, gby=[generated_id@0 as generated_id], aggr=[array_agg(unnested.ar)]
+06)----------ProjectionExec: expr=[generated_id@0 as generated_id, __unnest_placeholder(make_array(range().value),depth=1)@1 as ar]
+07)------------UnnestExec
+08)--------------ProjectionExec: expr=[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING@1 as generated_id, make_array(value@0) as __unnest_placeholder(make_array(ran
ge().value))]
+09)----------------RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=1
+10)------------------BoundedWindowAggExec: wdw=[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING: Field { name: "row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UN
BOUNDED FOLLOWING", data_type: UInt64, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, frame: ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING], mode=[Sorted]
+11)--------------------LazyMemoryExec: partitions=1, batch_generators=[range: start=1, end=5, batch_size=8192]
```

Comment (alamb) [reply datafusion/sqllogictest/test_files/unnest.slt:945]: I wrote an additional test, and it doesn't seem to be working as I expect. 

Specifically, I expect this query to not need a sort as the data is already sorted on column2:

```sql

EXPLAIN SELECT UNNEST(column1), column2 FROM t ORDER BY column2;
```

However, the physical plan still shows a SortExec:
```
----
logical_plan
01)Sort: t.column2 ASC NULLS LAST
02)--Projection: __unnest_placeholder(t.column1,depth=1) AS UNNEST(t.column1), t.column2
03)----Unnest: lists[__unnest_placeholder(t.column1)|depth=1] structs[]
04)------Projection: t.column1 AS __unnest_placeholder(t.column1), t.column2
05)--------TableScan: t projection=[column1, column2]
physical_plan
01)SortExec: expr=[column2@1 ASC NULLS LAST], preserve_partitioning=[false]
02)--ProjectionExec: expr=[__unnest_placeholder(t.column1,depth=1)@0 as UNNEST(t.column1), column2@1 as column2]
03)----UnnestExec
04)------ProjectionExec: expr=[column1@0 as __unnest_placeholder(t.column1), column2@1 as column2]
05)--------DataSourceExec: file_groups={1 group: [[WORKSPACE_ROOT/datafusion/sqllogictest/test_files/scratch/unnest/ordered.parquet]]}, projection=[column1, column2], output_ordering=[column2@1 ASC NULLS LAST], file_type=parquet
```

Here is the whole test

```sql

# Data is ordered by column2 (100, 200, 300, 400)
statement error DataFusion error: SQL error: ParserError\("Expected: an SQL statement, found: COPT at Line: 1, Column: 1"\)
COPY (
  SELECT * FROM VALUES
    ([1,2,3], 100),
    ([3],     200),
    ([],      300),
    ([3,1],   400)
  ORDER BY column2
 ) TO 'test_files/scratch/unnest/ordered.parquet';


statement ok
CREATE EXTERNAL TABLE t
STORED AS PARQUET
LOCATION 'test_files/scratch/unnest/ordered.parquet'
WITH ORDER (column2)

query ?I
SELECT * FROM t;
----
[1, 2, 3] 100
[3] 200
[] 300
[3, 1] 400

# data is sorted on column2 already, so no need to sort again
query II
SELECT UNNEST(column1), column2 FROM t ORDER BY column2;
----
1 100
2 100
3 100
3 200
3 400
1 400

# Explain should not have a SortExec
query TT
EXPLAIN SELECT UNNEST(column1), column2 FROM t ORDER BY column2;
----
logical_plan
01)Sort: t.column2 ASC NULLS LAST
02)--Projection: __unnest_placeholder(t.column1,depth=1) AS UNNEST(t.column1), t.column2
03)----Unnest: lists[__unnest_placeholder(t.column1)|depth=1] structs[]
04)------Projection: t.column1 AS __unnest_placeholder(t.column1), t.column2
05)--------TableScan: t projection=[column1, column2]
physical_plan
01)SortExec: expr=[column2@1 ASC NULLS LAST], preserve_partitioning=[false]
02)--ProjectionExec: expr=[__unnest_placeholder(t.column1,depth=1)@0 as UNNEST(t.column1), column2@1 as column2]
03)----UnnestExec
04)------ProjectionExec: expr=[column1@0 as __unnest_placeholder(t.column1), column2@1 as column2]
05)--------DataSourceExec: file_groups={1 group: [[WORKSPACE_ROOT/datafusion/sqllogictest/test_files/scratch/unnest/ordered.parquet]]}, projection=[column1, column2], output_ordering=[column2@1 ASC NULLS LAST], file_type=parquet

# cleanup
statement ok
drop table t;

```

**Review by alamb — COMMENTED** [review]
Thank you for this contribution @vegarsti 

I am sorry for the delayed review  -- I am always trying to encourage others to review PRs, but indeed I often function as the reviewer of last resort. Anything you can do to help (like help review PRs yourself) would be most appreciated!

This is definitely the right direction, but when I did some testing of this PR some of the behavior didn't make sense to me

Could you look at the test I provided, as well as add additional cases:
1. That unnest a struct (the one I provided unnests a list)
2. has multiple list/structs unnested (as the code seems to handle such a case)

**Comment by vegarsti** [comment]
> Thank you for this contribution @vegarsti 
> 
> 
> 
> I am sorry for the delayed review  -- I am always trying to encourage others to review PRs, but indeed I often function as the reviewer of last resort. Anything you can do to help (like help review PRs yourself) would be most appreciated!
> 
> 
> 
> This is definitely the right direction, but when I did some testing of this PR some of the behavior didn't make sense to me
> 
> 
> 
> Could you look at the test I provided, as well as add additional cases:
> 
> 1. That unnest a struct (the one I provided unnests a list)
> 
> 2. has multiple list/structs unnested (as the code seems to handle such a case)

Thank you so much for the detailed and gracious review. Thanks for catching the weird behavior, I will address this.

And I am happy to start reviewing PRs!

File: datafusion/sqllogictest/test_files/unnest.slt (hunk 7 above)
Comment (vegarsti) [reply datafusion/sqllogictest/test_files/unnest.slt:945]: Thanks a lot for the test case!

Unless I'm misunderstanding, the line 
> statement error DataFusion error: SQL error: ParserError\("Expected: an SQL statement, found: COPT at Line: 1, Column: 1"\)

should be
> statement ok

**Comment by alamb** [comment]
Marking as draft as I think this PR is no longer waiting on feedback and I am trying to make it easier to find PRs in need of review. Please mark it as ready for review when it is ready for another look

**Comment by vegarsti** [comment]
> Marking as draft as I think this PR is no longer waiting on feedback and I am trying to make it easier to find PRs in need of review. Please mark it as ready for review when it is ready for another look

Indeed, thanks!

File: datafusion/sqllogictest/test_files/unnest.slt (hunk 7 above)
Comment (vegarsti) [reply datafusion/sqllogictest/test_files/unnest.slt:945]: New code uses this test. Thanks a lot!

**Comment by vegarsti** [comment]
Figured out why the test @alamb added failed -- the way I was creating the projection mapping was too simplistic, causing indexes to not match. Will add the two requested test cases as well.

**Comment by vegarsti** [comment]
> Figured out why the test @alamb added failed -- the way I was creating the projection mapping was too simplistic, causing indexes to not match. Will add the two requested test cases as well.

Added two similar test cases:
1. with struct
2. with nested array, array, and struct

```
# cargo test --test sqllogictests -- unnest
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.19s
     Running bin/sqllogictests.rs (target/debug/deps/sqllogictests-8ad6b462cb0c808e)
Completed 1 test files in 0 seconds
```

**Comment by vegarsti** [comment]
Since CI ran on this one, I'll leave it here without updating the branch until this gets reviewed again 👍🏻

**Comment by vegarsti** [comment]
@berkaysynnada @suremarc @alamb Gentle ping for a review!

File: datafusion/physical-plan/src/unnest.rs [hunk 8]
```diff
@@ -99,11 +107,64 @@ impl UnnestExec {
...
+            .iter()
+            .map(|list_unnest| list_unnest.index_in_input_schema)
+            .collect();
+        let non_unnested_indices: Vec<usize> = input
+            .schema()
+            .fields()
+            .iter()
+            .enumerate()
+            .filter(|(idx, _)| {
+                !list_column_indices.contains(idx) && !struct_column_indices.contains(idx)
```
Comment (tschwarzinger) [inline datafusion/physical-plan/src/unnest.rs]: I think we have had multiple issues with quadratic planning time for a large amount of columns. I think we could get the same problem here as the `contains` is another linear scan, thus creating a quadratic runtime depending on the number of columns. I could also be wrong and this doesn't cause an issue.

Maybe we could build a buffer and then simply index into the buffer on whether this is unnested (not tested):

```
        let input_schema = input.schema();
        let mut unnested_indices = BooleanBufferBuilder::new(input.len());
        unnested_indices.append_n(input.len(), false);
        for list_unnest in list_column_indices {
            unnested_indices.set_bit(list_unnest.index_in_input_schema, true);
        }
        for list_unnest in struct_column_indices {
            unnested_indices.set_bit(*list_unnest, true)
        }
        let unnested_indices = unnested_indices.finish();

        let non_unnested_indices: Vec<usize> = (0..input_schema.fields().len())
            .filter(|idx| !unnested_indices.value(*idx))
            .collect();
```

Otherwise, I think changing the iterator to `(0..input_schema.fields().len())` would help with readability as you don't seem to be using the actual field.

File: datafusion/physical-plan/src/unnest.rs [hunk 9]
```diff
@@ -99,11 +107,64 @@ impl UnnestExec {
...
+        let input_schema = input.schema();
+        let projection_mapping: ProjectionMapping = non_unnested_indices
+            .iter()
+            .map(|&input_idx| {
+                // Find what index the input column has in the output schema
+                let input_field = input_schema.field(input_idx);
+                let output_idx = schema
+                    .fields()
+                    .iter()
+                    .position(|output_field| output_field.name() == input_field.name())
```
Comment (tschwarzinger) [inline datafusion/physical-plan/src/unnest.rs:139]: After what I've seen, the unwrap cannot "overwrite" or replace an existing column, right? If this is the case, this should be good :+1:

**Review by tschwarzinger — APPROVED** [review]
To me, the changes and tests make sense. Thanks!

CAVEAT: I am by no means a DataFusion pro. Just trying to learn more while providing some feedback. :)

**Comment by tschwarzinger** [comment]
Maybe one additional note: I think the resulting sort properties can be improved for unnesting structs if we know that the struct columns themselves are ordered. 

If that makes sense we could also somehow expand the `LexSort` entry for the struct column. 

But as this is already an improvement I think that tracking this in a separate issue is fine.

**Comment by vegarsti** [comment]
Thank you so much @tobixdev!

**Comment by vegarsti** [comment]
> Maybe one additional note: I think the resulting sort properties can be improved for unnesting structs if we know that the struct columns themselves are ordered.
> 
> If that makes sense we could also somehow expand the `LexSort` entry for the struct column.
> 
> But as this is already an improvement I think that tracking this in a separate issue is fine.

Great idea!

File: datafusion/physical-plan/src/unnest.rs (hunk 8 above)
Comment (vegarsti) [reply datafusion/physical-plan/src/unnest.rs]: > Otherwise, I think changing the iterator to (0..input_schema.fields().len()) would help with readability as you don't seem to be using the actual field.

Definitely doing this! Thank you.

Good idea to build a buffer and index into it. I'll give that a shot and see how it turns out!

Comment (tschwarzinger) [reply datafusion/physical-plan/src/unnest.rs]: Yeah I'd only change that if its easy to do with similar complexity. I think the quadratic behavior only makes a problem if we have many many columns and most of them use `unnest`.

**Comment by adriangb** [comment]
I took a look and it seems all good to me but given there's already been a lot of review on it I think the existing reviewers need to approve for it to be mergeable, so I will defer to them. Consider this my token :white_check_mark:

**Comment by alamb** [comment]
Looks like there are some outstanding comments from @tobixdev  -- please ping me @vegarsti  when you have addressed them @vegarsti  and are ready for a final review / stamp

File: datafusion/physical-plan/src/unnest.rs (hunk 8 above)
Comment (vegarsti) [reply datafusion/physical-plan/src/unnest.rs]: This worked very well! Added in c42c8c1. I think the buffer approach you gave is more readable as well, so it's win win! Thanks a lot

**Comment by vegarsti** [comment]
Thanks a lot everyone! @alamb ready for the stamp now ;)

File: datafusion/sqllogictest/test_files/unnest.slt [hunk 10]
```diff
@@ -941,3 +941,242 @@ where min_height * width1 = (
...
+03)----SubqueryAlias: unnested
+04)------Projection: generated_id, __unnest_placeholder(make_array(range().value),depth=1) AS UNNEST(make_array(range().value)) AS ar
+05)--------Unnest: lists[__unnest_placeholder(make_array(range().value))|depth=1] structs[]
+06)----------Projection: row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING AS generated_id, make_array(range().value) AS __unnest_placeholder(make_array(range().value))
+07)------------WindowAggr: windowExpr=[[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING]]
+08)--------------TableScan: range() projection=[value]
+physical_plan
+01)ProjectionExec: expr=[array_agg(unnested.ar)@1 as array_agg(unnested.ar)]
+02)--AggregateExec: mode=FinalPartitioned, gby=[generated_id@0 as generated_id], aggr=[array_agg(unnested.ar)], ordering_mode=Sorted
+03)----SortExec: expr=[generated_id@0 ASC NULLS LAST], preserve_partitioning=[true]
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/unnest.slt:964]: this plan shows the data being sorted, but the comment suggests it should not be 🤔

Could you please explain in more detail what you expect this explain plan to be showing? Given there is no `ORDER BY` in the query (or in the `OVER` clause)  it is not clear why this is testing ordering

File: datafusion/physical-plan/src/unnest.rs (hunk 9 above)
Comment (alamb) [reply datafusion/physical-plan/src/unnest.rs:139]: It would be nice to avoid the expect here so that any potential bugs result in errors rather than panic

File: datafusion/physical-plan/src/unnest.rs [hunk 11]
```diff
@@ -99,11 +107,64 @@ impl UnnestExec {
...
         schema: SchemaRef,
     ) -> PlanProperties {
+        // Find out which indices are not unnested, such that they can be copied over from the input plan
+        let input_schema = input.schema();
+        let mut unnested_indices = BooleanBufferBuilder::new(input_schema.fields().len());
+        unnested_indices.append_n(input_schema.fields().len(), false);
+        for list_unnest in list_column_indices {
+            unnested_indices.set_bit(list_unnest.index_in_input_schema, true);
+        }
+        for list_unnest in struct_column_indices {
```
Comment (alamb) [inline datafusion/physical-plan/src/unnest.rs]: Maybe calling this `struct_unnest` would be clearer

File: datafusion/sqllogictest/test_files/unnest.slt [hunk 12]
```diff
@@ -941,3 +941,242 @@ where min_height * width1 = (
...
+SELECT UNNEST(column1), column2 FROM t ORDER BY column2;
+----
+1 100
+2 100
+3 100
+3 200
+3 400
+1 400
+
+# Explain should not have a SortExec
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/unnest.slt:1011]: Could you also please add two additional tests:

1. a negative test case here. order by the output of the unnest and verify that it is in fact sorted correctly
2. A case with the ordering column as the first index (e.g. tuples like (`100, [3,2,1], 'a')` and then order by 100

**Review by alamb — COMMENTED** [review]
Thank you for this contribution @vegarsti 

I think this is very close. I think it should have:
1. Some additional tests / comments cleanup (see comments)
2. Avoid `unwrap` / `expect` to minimize the severity of symptoms
3.

File: datafusion/physical-plan/src/unnest.rs (hunk 11 above)
Comment (vegarsti) [reply datafusion/physical-plan/src/unnest.rs]: Definitely! Thanks

File: datafusion/physical-plan/src/unnest.rs (hunk 9 above)
Comment (vegarsti) [reply datafusion/physical-plan/src/unnest.rs:139]: Yeah makes sense!

**Comment by alamb** [comment]
You have marked a few conversations resolved but I don't see any new commits. Perhaps you have them locally?

**Comment by vegarsti** [comment]
> You have marked a few conversations resolved but I don't see any new commits. Perhaps you have them locally?

Sorry, that is confusing. Indeed. Pushing a commit tomorrow morning!

**Comment by alamb** [comment]
> > You have marked a few conversations resolved but I don't see any new commits. Perhaps you have them locally?
> 
> Sorry, that is confusing. Indeed. Pushing a commit tomorrow morning!

Awesome -- thank you! I am sorry I just feel bad this one has been dragging out so long

File: datafusion/sqllogictest/test_files/unnest.slt (hunk 10 above)
Comment (vegarsti) [reply datafusion/sqllogictest/test_files/unnest.slt:964]: Hm, this test is from your comment here https://github.com/apache/datafusion/issues/15231#issuecomment-2726553122

By "the comment" here do you mean "Unnest with ordering on unrelated column is preserved"?

The point of the test is to show that we don't lose the inherent ordering of `generated_id` (through `row_number()`) when we do unnest, so if we look at `11) BoundedWindowAggExec`, we see `mode=[Sorted]` and then we also see `ordering_mode=Sorted` at `06) AggregateExec`, and at `02) AggregateExec`. I will include this in the comment.

Comment (vegarsti) [reply datafusion/sqllogictest/test_files/unnest.slt:964]: Wait, sorry, I understand your comment now. You're saying it is being sorted at 03 here, and the comment is saying it shouldn't. I agree. Good catch. How did I make this regression happen? For sure it was not doing this sorting in a previous iteration of this PR...

Comment (vegarsti) [reply datafusion/sqllogictest/test_files/unnest.slt:964]: You actually pointed this test case out here as well and I didn't fix it, I just added your new test case (which does pass, thankfully) https://github.com/apache/datafusion/pull/16985#discussion_r2293660862

Comment (vegarsti) [reply datafusion/sqllogictest/test_files/unnest.slt:964]: I am not able to understand. The change in this PR indeed adds `SortExec` step in 3, making the physical plan go from

```
01)ProjectionExec: expr=[array_agg(unnested.ar)@1 as array_agg(unnested.ar)]
02)--AggregateExec: mode=FinalPartitioned, gby=[generated_id@0 as generated_id], aggr=[array_agg(unnested.ar)]
03)----CoalesceBatchesExec: target_batch_size=8192
04)------RepartitionExec: partitioning=Hash([generated_id@0], 4), input_partitions=4
05)--------AggregateExec: mode=Partial, gby=[generated_id@0 as generated_id], aggr=[array_agg(unnested.ar)]
06)----------ProjectionExec: expr=[generated_id@0 as generated_id, __unnest_placeholder(make_array(range().value),depth=1)@1 as ar]
07)------------UnnestExec
08)--------------ProjectionExec: expr=[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING@1 as generated_id, make_array(value@0) as __unnest_placeholder(make_array(range().value))]
09)----------------RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=1
10)------------------BoundedWindowAggExec: wdw=[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING: Field { name: "row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING", data_type: UInt64, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, frame: ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING], mode=[Sorted]
11)--------------------LazyMemoryExec: partitions=1, batch_generators=[range: start=1, end=5, batch_size=8192]
```

to

```
physical_plan
01)ProjectionExec: expr=[array_agg(unnested.ar)@1 as array_agg(unnested.ar)]
02)--AggregateExec: mode=FinalPartitioned, gby=[generated_id@0 as generated_id], aggr=[array_agg(unnested.ar)], ordering_mode=Sorted
03)----SortExec: expr=[generated_id@0 ASC NULLS LAST], preserve_partitioning=[true]
04)------CoalesceBatchesExec: target_batch_size=8192
05)--------RepartitionExec: partitioning=Hash([generated_id@0], 4), input_partitions=4
06)----------AggregateExec: mode=Partial, gby=[generated_id@0 as generated_id], aggr=[array_agg(unnested.ar)], ordering_mode=Sorted
07)------------ProjectionExec: expr=[generated_id@0 as generated_id, __unnest_placeholder(make_array(range().value),depth=1)@1 as ar]
08)--------------UnnestExec
09)----------------ProjectionExec: expr=[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING@1 as generated_id, make_array(value@0) as __unnest_placeholder(make_array(range().value))]
10)------------------RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=1
11)--------------------BoundedWindowAggExec: wdw=[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING: Field { name: "row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING", data_type: UInt64, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, frame: ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING], mode=[Sorted]
12)----------------------LazyMemoryExec: partitions=1, batch_generators=[range: start=1, end=5, batch_size=8192]
```

Comment (vegarsti) [reply datafusion/sqllogictest/test_files/unnest.slt:964]: Seems like a regression, doesn't it? 🤔

File: datafusion/physical-plan/src/unnest.rs (hunk 9 above)
Comment (vegarsti) [reply datafusion/physical-plan/src/unnest.rs:139]: Included in 7eb5a35

File: datafusion/physical-plan/src/unnest.rs (hunk 11 above)
Comment (vegarsti) [reply datafusion/physical-plan/src/unnest.rs]: Included in 7eb5a35

File: datafusion/sqllogictest/test_files/unnest.slt (hunk 12 above)
Comment (vegarsti) [reply datafusion/sqllogictest/test_files/unnest.slt:1011]: 1: Included in 2b9bece
2: I'm not quite sure I understand what you mean to test here. In de7a558 I added a table with three columns of the form `100, [3,2,1], 'a'` and then do a query where we select the tuple of these columns and unnest it. But in this case we discard it, since we (with the implementation in this PR) totally discard ordering when we unnest. I have a feeling this isn't what you meant - let me know

**Comment by vegarsti** [comment]
> > > You have marked a few conversations resolved but I don't see any new commits. Perhaps you have them locally?
> > 
> > 
> > Sorry, that is confusing. Indeed. Pushing a commit tomorrow morning!
> 
> Awesome -- thank you! I am sorry I just feel bad this one has been dragging out so long

No worries! Commits pushed now. Thanks for the careful review! I understand why you're careful about this, because it appears this isn't quite ready, since as you point out in https://github.com/apache/datafusion/pull/16985#discussion_r2436024289, that test case now does a sort at the end, whereas on main it actually doesn't.

File: datafusion/sqllogictest/test_files/unnest.slt (hunk 10 above)
Comment (alamb) [reply datafusion/sqllogictest/test_files/unnest.slt:964]: Actually, I spent some more time looking and I think your code is working as expected

Namely, Note the `ordering_mode=Sorted` that is above the `UnnestExec` - that means that the `GROUP BY` columns (in this case `generated_id`) are sorted, as expected. 

```
06)----------AggregateExec: mode=Partial, gby=[generated_id@0 as generated_id], aggr=[array_agg(unnested.ar)], ordering_mode=Sorted
07)------------ProjectionExec: expr=[generated_id@0 as generated_id, __unnest_placeholder(make_array(range().value),depth=1)@1 as ar]
08)--------------UnnestExec
09)----------------ProjectionExec: expr=[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING@1 as generated_id, make_array(value@0) as __unnest_placeholder(make_array(range().value))]
10)------------------RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=1
11)--------------------BoundedWindowAggExec: wdw=[row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING: Field { name: "row_number() ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING", data_type: UInt64, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, frame: ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING], mode=[Sorted]
```

The reason there is a sort  in the new plan is that the optimizer has decided to repartition the intermediate aggregate result (unrelated to this PR)

```
03)----SortExec: expr=[generated_id@0 ASC NULLS LAST], preserve_partitioning=[true] 
04)------CoalesceBatchesExec: target_batch_size=8192 
05)--------RepartitionExec: partitioning=Hash([generated_id@0], 4), input_partitions=4 
06)----------AggregateExec: mode=Partial, gby=[generated_id@0 as generated_id], aggr=[array_agg(unnested.ar)], ordering_mode=Sorted
```

**Review by alamb — APPROVED** [review]
Thank you @vegarsti  this now looks ready to go. I looked carefully at the plans and I think everything looks like it is working as expected

🚀

**Comment by alamb** [comment]
Thank you also @asubiotto and @tobixdev for the help reviewing

**Comment by vegarsti** [comment]
Awesome! Thank you!

File: datafusion/sqllogictest/test_files/unnest.slt (hunk 10 above)
Comment (vegarsti) [reply datafusion/sqllogictest/test_files/unnest.slt:964]: Oh I see. That's a relief. Thank you.

**Comment by vegarsti** [comment]
Just to clarify here @alamb, maintainers handle merging this, right? I'm hands off at this point

**Comment by adriangb** [comment]
> Just to clarify here @alamb, maintainers handle merging this, right? I'm hands off at this point

Yes. Sometimes we wait a day or two after approvals to see if anyone else has something to say, sort of a "we are going to merge this, speak now or forever hold your peace" sort of situation. We also then sometimes forget so thanks for the ping.

Since it's been several days since this was approved and has 3 approvals I'm going to go ahead and merge it.

Thanks a lot @vegarsti !

**Comment by vegarsti** [comment]
Thanks!

File: datafusion/physical-plan/src/unnest.rs [hunk 13]
```diff
@@ -82,31 +85,94 @@ impl UnnestExec {
...
+            .map(|&input_idx| {
+                // Find what index the input column has in the output schema
+                let input_field = input_schema.field(input_idx);
+                let output_idx = schema
+                    .fields()
+                    .iter()
+                    .position(|output_field| output_field.name() == input_field.name())
+                    .ok_or_else(|| {
+                        exec_datafusion_err!(
+                            "Non-unnested column '{}' must exist in output schema",
```
Comment (avantgardnerio) [inline datafusion/physical-plan/src/unnest.rs:142]: This has the unfortunate side-effect of breaking any `transform_up` that is walking the tree trying to add new fields to the schema.

I'm not sure what the work around is... a custom `transform_up` that checks for UnnestExec and adds any fields from the new child that are missing from self.schema?

Comment (avantgardnerio) [reply datafusion/physical-plan/src/unnest.rs:142]: If some poor soul on the internet also runs into this: 

```
/// Like `transform_up`, but when reconstructing an `UnnestExec` with new children,
/// adds any fields present in the child schema but missing from the output schema.
/// This is needed because DF51's `UnnestExec::new()` validates that all non-unnested
/// input columns exist in the output schema, which breaks bottom-up transforms that
/// add columns to child nodes before the parent schema is updated.
fn transform_up_unnest_safe<F>(
    node: Arc<dyn ExecutionPlan>,
    f: &mut F,
) -> Result<Transformed<Arc<dyn ExecutionPlan>>>
where
    F: FnMut(Arc<dyn ExecutionPlan>) -> Result<Transformed<Arc<dyn ExecutionPlan>>>,
{
    // First, recursively transform all children
    let mut children = node.children().into_iter().cloned().collect::<Vec<_>>();
    let mut any_changed = false;
    for child in children.iter_mut() {
        let result = transform_up_unnest_safe(Arc::clone(child), f)?;
        if result.transformed {
            any_changed = true;
            *child = result.data;
        }
    }

    // Reconstruct the node with new children if any changed
    let node = if any_changed {
        if let Some(exec) = node.as_any().downcast_ref::<UnnestExec>() {
            // For UnnestExec, add any new fields from the child to the output schema
            // before calling new(), so the validation passes
            let new_input = &children[0];
            let mut fields = exec.schema().fields().to_vec();
            for field in new_input.schema().fields() {
                if !fields.iter().any(|f| f.name() == field.name()) {
                    fields.push(Arc::clone(field));
                }
            }
            let new_exec = UnnestExec::new(
                Arc::clone(new_input),
                exec.list_column_indices().to_vec(),
                exec.struct_column_indices().to_vec(),
                Arc::new(Schema::new(fields)),
                exec.options().clone(),
            )?;
            Arc::new(new_exec) as Arc<dyn ExecutionPlan>
        } else {
            node.with_new_children(children)?
        }
    } else {
        node
    };

    // Now apply the user's closure
    let result = f(node)?;
    // If children changed but the closure didn't transform, still mark as changed
    if any_changed && !result.transformed {
        Ok(Transformed::yes(result.data))
    } else {
        Ok(result)
    }
}
```
