### PR TITLE
fix: HashJoin panic with dictionary-encoded columns in multi-key joins

### LINKED ISSUE #20437: Panic in HashJoin with dictionary-encoded column in multi-column join key
## Describe the bug

When executing a hash join with multiple join keys where one column is dictionary-encoded with fewer unique values than rows, DataFusion panics with:

```
InvalidArgumentError("Incorrect array length for StructArray field \"c1\", expected N got M")
```

## To Reproduce

```sql
-- Small table with dictionary-encoded region (2 rows, 1 unique value)
CREATE TABLE small AS
SELECT id, arrow_cast(region, 'Dictionary(Int32, Utf8)') as region
FROM (VALUES (1, 'west'), (2, 'west')) AS t(id, region);

CREATE TABLE large AS
SELECT id, region, value
FROM (VALUES (1, 'west', 100), (2, 'west', 200), (3, 'east', 300)) AS t(id, region, value);

-- Multi-column join triggers panic
SELECT s.id, s.region, l.value
FROM small s
JOIN large l ON s.id = l.id AND s.region = l.region;
```

## Expected behavior

Query returns 2 rows:
```
+----+--------+-------+
| id | region | value |
+----+--------+-------+
| 1  | west   | 100   |
| 2  | west   | 200   |
+----+--------+-------+
```

## Actual behavior

Panic:
```
thread 'main' panicked at arrow-array/src/array/struct_array.rs:91:46:
called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Incorrect array length for StructArray field \"c1\", expected 3 got 2")
```

## Root cause

In [`flatten_dictionary_array`](https://github.com/apache/datafusion/blob/52.1.0/datafusion/physical-plan/src/joins/hash_join/inlist_builder.rs#L37-L45) introduced by #18393:

```rust
fn flatten_dictionary_array(array: &ArrayRef) -> ArrayRef {
    downcast_dictionary_array! {
        array => {
            flatten_dictionary_array(array.values())
        }
        _ => Arc::clone(array)
    }
}
```

The function calls `array.values()` which returns the dictionary's unique values array, not the full array of values.

When building a StructArray for multi-column join keys, [`StructArray::try_new_with_length()`](https://github.com/apache/arrow-rs/blob/master/arrow-array/src/array/struct_array.rs#L160-L166) detects the length mismatch:

```rust
if a.len() != len {
    return Err(ArrowError::InvalidArgumentError(format!(
        "Incorrect array length for StructArray field {:?}, expected {} got {}",
        f.name(), len, a.len()
    )));
}
```

### PR DESCRIPTION
**Pull request by Tim-53**
## Which issue does this PR close?

- Closes #20437

## Rationale for this change
`flatten_dictionary_array` returned only the unique values rather then the full expanded array when being called on a `DictionaryArray`. When building a `StructArray` this caused a length mismatch panic. 

## What changes are included in this PR?
Replaced `array.values()` with `arrow::compute::cast(array, value_type)` in `flatten_dictionary_array`, which properly expands the dictionary into a full length array matching the row count.

## Are these changes tested?

Yes, both a new unit test aswell as a regression test were added.

## Are there any user-facing changes?

Nope

### CODE REVIEW

File: datafusion/core/tests/sql/joins.rs [hunk 1]
```diff
@@ -299,3 +299,52 @@ async fn unparse_cross_join() -> Result<()> {
 
     Ok(())
 }
+
+// Issue #20437: https://github.com/apache/datafusion/issues/20437
+#[tokio::test]
```
Comment (jonathanc-n) [inline datafusion/core/tests/sql/joins.rs]: We want to keep unit tests at a minimum when possible. Use sqllogictests instead here

**Review by jonathanc-n — APPROVED** [review]

File: datafusion/physical-plan/src/joins/hash_join/inlist_builder.rs [hunk 2]
```diff
@@ -33,15 +33,16 @@ pub(super) fn build_struct_fields(data_types: &[DataType]) -> Result<Fields> {
         .collect()
 }
 
-/// Flattens dictionary-encoded arrays to their underlying value arrays.
+/// Casts dictionary-encoded arrays to their underlying value type, preserving row count.
 /// Non-dictionary arrays are returned as-is.
-fn flatten_dictionary_array(array: &ArrayRef) -> ArrayRef {
-    downcast_dictionary_array! {
-        array => {
+fn flatten_dictionary_array(array: &ArrayRef) -> Result<ArrayRef> {
```
Comment (adriangb) [inline datafusion/physical-plan/src/joins/hash_join/inlist_builder.rs:38]: Shall we rename the function?

Comment (alamb) [reply datafusion/physical-plan/src/joins/hash_join/inlist_builder.rs:38]: It seems to me like it still flattens dictionaries. why would we rename it?

File: datafusion/physical-plan/src/joins/hash_join/inlist_builder.rs [hunk 3]
```diff
@@ -130,4 +133,41 @@ mod tests {
             )
         );
     }
+
+    #[test]
+    fn test_build_multi_column_inlist_with_dictionary() {
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/hash_join/inlist_builder.rs:138]: I am not sure this unit test adds much value -- it just basically reiterates how the current function works  (it is testing some intermediate state

I double checked that the .slt test fails without the code in this PR

File: datafusion/physical-plan/src/joins/hash_join/inlist_builder.rs [hunk 4]
```diff
@@ -33,15 +33,16 @@ pub(super) fn build_struct_fields(data_types: &[DataType]) -> Result<Fields> {
...
-/// Flattens dictionary-encoded arrays to their underlying value arrays.
+/// Casts dictionary-encoded arrays to their underlying value type, preserving row count.
 /// Non-dictionary arrays are returned as-is.
-fn flatten_dictionary_array(array: &ArrayRef) -> ArrayRef {
-    downcast_dictionary_array! {
-        array => {
+fn flatten_dictionary_array(array: &ArrayRef) -> Result<ArrayRef> {
+    match array.data_type() {
+        DataType::Dictionary(_, value_type) => {
+            let casted = cast(array, value_type)?;
```
Comment (alamb) [inline datafusion/physical-plan/src/joins/hash_join/inlist_builder.rs:41]: I messed around with this PR and I don't really understand why the code is flattening arrays at all

I removed the flattening code entirely and all the code seems to pass.  I'll make a follow on PR

Comment (alamb) [reply datafusion/physical-plan/src/joins/hash_join/inlist_builder.rs:41]: Just deleting the code seems to have worked
- https://github.com/apache/datafusion/pull/20505

**Comment by alamb** [comment]
I also made a backport PR here
- https://github.com/apache/datafusion/pull/20512

File: datafusion/physical-plan/src/joins/hash_join/inlist_builder.rs (hunk 4 above)
Comment (alamb) [reply datafusion/physical-plan/src/joins/hash_join/inlist_builder.rs:41]: I should have followed my instincts a bit more. It turns out we found another issue with this code at InfluxData
- https://github.com/apache/datafusion/issues/20696

Thankfully the following PR fixes it: 
- https://github.com/apache/datafusion/pull/20505
