### PR TITLE
fix: `regexp_replace` fails when pattern or replacement is a scalar `NULL`

### LINKED ISSUE #11410: regexp_replace fails when pattern or replacement is a scalar NULL
### Describe the bug

regexp_replace fails to produce correct number of rows if either `pattern` or `replacement` arg is a scalar NULL.  

I think this is due to https://github.com/apache/datafusion/blob/7a23ea9bce32dc8ae195caa8ca052673031c06c9/datafusion/functions/src/regex/regexpreplace.rs#L316 `fetch_string_arg` not passing the correct length to the `_regexp_replace_early_abort` function - when this specific arg is a scalar, its "array len" is just 1, and the abort function creates a 1-len array as the result.

### To Reproduce

Normal case - values are valid scalars or array nulls:
```
> select regexp_replace(col, 'a', 'c') from (values ('a'), ('b')) as tbl(col);
+---------------------------------------------+
| regexp_replace(tbl.col,Utf8("a"),Utf8("c")) |
+---------------------------------------------+
| c                                           |
| b                                           |
+---------------------------------------------+
2 row(s) fetched. 
Elapsed 0.001 seconds.

> select regexp_replace(col, ncol, 'c') from (values ('a', NULL), ('b', NULL)) as tbl(col, ncol);
+--------------------------------------------+
| regexp_replace(tbl.col,tbl.ncol,Utf8("c")) |
+--------------------------------------------+
|                                            |
|                                            |
+--------------------------------------------+
```

**Failing case** - pattern or replacement is a scalar NULL:
```
> select regexp_replace(col, NULL, 'c') from (values ('a'), ('b')) as tbl(col);
Internal error: UDF returned a different number of rows than expected. Expected: 2, Got: 1.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker

> select regexp_replace(col, 'a', NULL) from (values ('a'), ('b')) as tbl(col);
Internal error: UDF returned a different number of rows than expected. Expected: 2, Got: 1.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Weijun-H**
## Which issue does this PR close?

Closes #11410

### CODE REVIEW

File: datafusion/functions/src/regex/regexpreplace.rs [hunk 1]
```diff
@@ -282,22 +282,23 @@ pub fn regexp_replace<T: OffsetSizeTrait>(args: &[ArrayRef]) -> Result<ArrayRef>
 
 fn _regexp_replace_early_abort<T: OffsetSizeTrait>(
     input_array: &GenericStringArray<T>,
+    sz: &usize,
```
Comment (jonahgao) [inline datafusion/functions/src/regex/regexpreplace.rs:285]: I think passing `sz` by value would be more efficient.

See: https://rust-lang.github.io/rust-clippy/master/index.html#/trivially_copy_pass_by_ref

```sh
$ cargo clippy -- -W clippy::trivially_copy_pass_by_ref
warning: this argument (8 byte) is passed by reference, but would be more efficient if passed by value (limit: 8 byte)
   --> datafusion/functions/src/regex/regexpreplace.rs:285:9
    |
285 |     sz: &usize,
    |         ^^^^^^ help: consider passing by value instead: `usize`

```

**Review by jonahgao — APPROVED** [review]
Looks good to me!

**Comment by alamb** [comment]
Thank you @Weijun-H  and @jonahgao
