### PR TITLE
fix: Fix three bugs in query decorrelation

### LINKED ISSUE #20315: Ambiguous reference to __always_true with multiple correlated scalar subqueries
### Describe the bug

When a SQL query contains multiple correlated scalar subqueries in the SELECT clause, the `scalar_subquery_to_join` optimizer rule fails with:
```
Schema error: Ambiguous reference to unqualified field __always_true
```

### To Reproduce

```rust
// Reproduction case for DataFusion bug: Ambiguous reference to __always_true
// with multiple correlated scalar subqueries

use datafusion::arrow::array::{Float64Array, StringArray};
use datafusion::arrow::datatypes::{DataType, Field, Schema};
use datafusion::arrow::record_batch::RecordBatch;
use datafusion::datasource::MemTable;
use datafusion::prelude::*;
use std::sync::Arc;

#[tokio::main]
async fn main() -> datafusion::error::Result<()> {
    println!("DataFusion Multiple Correlated Scalar Subqueries Bug Reproduction\n");

    // Create a simple table with region and duration columns
    let schema = Arc::new(Schema::new(vec![
        Field::new("region", DataType::Utf8, false),
        Field::new("duration", DataType::Float64, false),
    ]));

    let region = StringArray::from(vec!["US", "EU", "US", "EU", "APAC"]);
    let duration = Float64Array::from(vec![10.0, 20.0, 15.0, 25.0, 30.0]);

    let batch = RecordBatch::try_new(schema.clone(), vec![Arc::new(region), Arc::new(duration)])?;

    // Create session context
    let config = SessionConfig::new().with_target_partitions(1);
    let ctx = SessionContext::new_with_config(config);

    // Register the table
    let table = MemTable::try_new(schema, vec![vec![batch]])?;
    ctx.register_table("activity", Arc::new(table))?;

    println!("=== Test 1: Single correlated scalar subquery (WORKS) ===");
    let sql_single = "
        SELECT
            region,
            SUM(duration) as total_duration,
            (SELECT COUNT(*) FROM activity WHERE region = a.region) as count
        FROM activity a
        GROUP BY region
    ";

    match ctx.sql(sql_single).await {
        Ok(df) => match df.collect().await {
            Ok(results) => {
                println!("Single subquery works!");
                println!(
                    "Results: {} rows\n",
                    results.iter().map(|b| b.num_rows()).sum::<usize>()
                );
            }
            Err(e) => println!("Execution error: {}\n", e),
        },
        Err(e) => println!("Planning error: {}\n", e),
    }

    println!("=== Test 2: Multiple correlated scalar subqueries (FAILS) ===");
    let sql_multiple = "
        SELECT
            region,
            SUM(duration) as total_duration,
            (SELECT COUNT(*) FROM activity WHERE region = a.region) as count,
            (SELECT MAX(duration) FROM activity WHERE region = a.region) as max_duration
        FROM activity a
        GROUP BY region
    ";

    match ctx.sql(sql_multiple).await {
        Ok(df) => match df.collect().await {
            Ok(results) => {
                println!("Multiple subqueries work!");
                println!(
                    "Results: {} rows\n",
                    results.iter().map(|b| b.num_rows()).sum::<usize>()
                );
            }
            Err(e) => {
                println!("Execution error:");
                println!("{}\n", e);
            }
        },
        Err(e) => {
            println!("❌ Planning error: {}\n", e);
        }
    }

    println!("=== Test 3: Multiple subqueries with different tables (for comparison) ===");
    // Create a second table
    let schema2 = Arc::new(Schema::new(vec![
        Field::new("region", DataType::Utf8, false),
        Field::new("revenue", DataType::Float64, false),
    ]));

    let region2 = StringArray::from(vec!["US", "EU", "APAC"]);
    let revenue = Float64Array::from(vec![100.0, 200.0, 150.0]);

    let batch2 = RecordBatch::try_new(schema2.clone(), vec![Arc::new(region2), Arc::new(revenue)])?;

    let table2 = MemTable::try_new(schema2, vec![vec![batch2]])?;
    ctx.register_table("sales", Arc::new(table2))?;

    let sql_different_tables = "
        SELECT
            region,
            SUM(duration) as total_duration,
            (SELECT COUNT(*) FROM activity WHERE region = a.region) as activity_count,
            (SELECT MAX(revenue) FROM sales WHERE region = a.region) as max_revenue
        FROM activity a
        GROUP BY region
    ";

    match ctx.sql(sql_different_tables).await {
        Ok(df) => match df.collect().await {
            Ok(results) => {
                println!("Multiple subqueries on different tables work!");
                println!(
                    "Results: {} rows\n",
                    results.iter().map(|b| b.num_rows()).sum::<usize>()
                );
            }
            Err(e) => println!("Execution error: {}\n", e),
        },
        Err(e) => println!("Planning error: {}\n", e),
    }

    Ok(())
}

```
This outputs errors for the 2 lasts queries like : 
```
Optimizer rule 'scalar_subquery_to_join' failed
caused by
Schema error: Ambiguous reference to unqualified field __always_true
```

### Expected behavior

The query should execute successfully, returning aggregated results with the scalar subquery values.
It's working with single correlated subquery.

### Additional context

_No response_

### LINKED ISSUE #21205: IN subqueries can return incorrect results
### Describe the bug

```sql
  CREATE TABLE t1(id INTEGER) AS VALUES (1), (2), (3);
  CREATE TABLE t2(id INTEGER) AS VALUES (1), (2), (3);

  -- Expected: 0 rows (no value can satisfy id = id AND id > id)
  -- Actual: returns all 3 rows
  SELECT * FROM t1 WHERE t1.id IN (
      SELECT t2.id FROM t2 WHERE t2.id > t1.id
  );
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### LINKED ISSUE #21206: Spurious error when subquery column alias clashes with outer query identifier
### Describe the bug

```
  CREATE TABLE t1(id INTEGER) AS VALUES (1), (2), (3);
  CREATE TABLE t2(id INTEGER, outer_id INTEGER) AS VALUES (10, 1), (20, 1), (30, 2);

  -- Expected: (1, 2), (2, 1), (3, 0)
  -- Actual: "Ambiguous reference to unqualified field id"
  SELECT t1.id,
    (SELECT count(*) AS id FROM t2 WHERE t2.outer_id = t1.id) AS cnt
  FROM t1
  ORDER BY t1.id;
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by neilconway**
## Which issue does this PR close?

- Closes #21205.
- Closes #21206.
- Closes #20315.

## Rationale for this change

This PR fixes three separate bugs in query decorrelation:

1. When removing duplicate filters as part of pulling up `IN` subqueries, an operator precedence error meant that we would consider two filters to be duplicates even if they involved different operators (e.g., `=` and `>`).
2. When generating the `CASE` used to implement "count bug" handling, we referenced the subquery output column without qualifying it by the subquery alias. This could result in name-collisions with unrelated identifiers in the parent query.
3. After generating the `CASE` used for "count bug" handling, we rewrote the parent query to replace references to the subquery output column with the generated `CASE` expression. This rewrite only matched on unqualified column name only, which meant that unrelated parent query identifiers that happened to share the same column name as subquery aggregate aliases could been rewritten by mistake.

The first and third issues could result in incorrect query results; the second would only cause spurious errors, as far as I can see.

## What changes are included in this PR?

* Fix all three bugs
* Add SLT tests
* Add a `debug_assert!` to document/check that `remove_duplicated_filter` is called with a commutative operator

## Are these changes tested?

Yes.

## Are there any user-facing changes?

No, except in the sense that they fix user-visible bugs.

### CODE REVIEW

**Comment by neilconway** [comment]
This needs backporting, in my opinion. @alamb @comphead

File: datafusion/optimizer/src/decorrelate.rs [hunk 1]
```diff
@@ -461,19 +461,30 @@ fn collect_local_correlated_cols(
 }
 
 fn remove_duplicated_filter(filters: Vec<Expr>, in_predicate: &Expr) -> Vec<Expr> {
+    // We assume below that swapping the order of operands to an operator does
+    // not change behavior, which is true only if the operator is commutative.
+    debug_assert!(
```
Comment (alamb) [inline datafusion/optimizer/src/decorrelate.rs]: it might be nicer here to use an internal error which is somewhat nicer to handle for other libraries (they can handle the error and return something nicer)-- there is even a macro for that : https://docs.rs/datafusion/latest/datafusion/common/macro.assert_or_internal_err.html

Comment (neilconway) [reply datafusion/optimizer/src/decorrelate.rs]: Thanks, fixed.
