### PR TITLE
Disallow duplicated qualified field names

### LINKED ISSUE #11408: LEFT/RIGHT OUTER JOIN failed to detect ambiguous column reference (SQLancer-NoREC)
### Describe the bug

Table reference in this query is ambiguous, and should be rejected by the planner.
`select t1.v1 from t1 left outer join t1 on true;`
Now it can be run successfully, see the reproducer:
(It can also be reproduced if 'left outer join' is changed to 'left join' 'right join' 'right outer join')
```
> create table t1(v1 int);
0 row(s) fetched.
Elapsed 0.068 seconds.

> insert into t1 values (1);
+-------+
| count |
+-------+
| 1     |
+-------+
1 row(s) fetched.
Elapsed 0.054 seconds.

> select t1.v1 from t1 left outer join t1 on true;
+----+
| v1 |
+----+
| 1  |
+----+
1 row(s) fetched.
Elapsed 0.016 seconds.

> select v1 from t1 left outer join t1 on true;
Schema error: Ambiguous reference to unqualified field v1
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

found by SQLancer https://github.com/apache/datafusion/issues/11030

### LINKED ISSUE #11464: `DFSchema::check_names` allows ambiguous references.
### Describe the bug

Constructing a schema with duplicate identical qualified names does not produce an error. I think it should, or we should extend the documentation of `DFSchema::check_names` to explain why those are allowed and where they are needed. 

### To Reproduce

```rust
use arrow_schema::{DataType, Field};
use datafusion_common::DFSchema;
use datafusion_sql::TableReference;
use std::sync::Arc;


#[test]
fn df_schema_check() {
    let t = || TableReference::bare("t");
    let schema = DFSchema::new_with_metadata(
        vec![
            (Some(t()), Arc::new(Field::new("a", DataType::Int64, true))),
            (Some(t()), Arc::new(Field::new("a", DataType::Utf8, false))),
        ],
        Default::default(),
    );
    schema.expect_err("duplicate t.a columns");
}
```

### Expected behavior

Reading through the comments, I would expect to see an error thrown by the `join` method in this case.

### Additional context

I found this while working on #11456.

### PR DESCRIPTION
**Pull request by eejbyfeldt**
## Which issue does this PR close?

Closes #11464
Closes #11408

## Rationale for this change

In https://github.com/apache/datafusion/pull/6091 we relaxed and allowed duplicated qualified fields in order to support duplicated group bys. This leads to some confusion and bugs as we do not allow for unqualified duplicated names. This makes the necessary changes to still support duplicated group by while still disallowing duplicated qualified names.

## What changes are included in this PR?

Revert allowing duplicated qualified names from #6091

Deduplicate group by exprs when creating output schema for LogicalPlan::Aggregate.

Remove test case `with_column_self_join` as this test no fails already at the join, I don't think it possible to modify to fulfill it old purpose.

The old logic in `plan_table_with_joins` would create schemas with duplicated fields as it would end up with multiple copies for the first table when there are multiple joins. I am not 100% this is the right fix, but it passes all existing test cases.

## Are these changes tested?
Existing test cases.

## Are there any user-facing changes?
Since this adds new restrictions it possible that it will break downstream users depending on the old behavior.

### CODE REVIEW

**Comment by jonahgao** [comment]
I think this is the right way; DuckDB has a [RemoveDuplicateGroups](https://github.com/duckdb/duckdb/blob/12e9777cf6283f44710b2610ba3d3735a1208751/src/include/duckdb/optimizer/remove_duplicate_groups.hpp#L20C7-L20C28) that does the same thing.

There might be a minor issue with volatile expressions, such as `group by random(), random()`, but I think we can disregard it for now.

File: datafusion/sql/src/planner.rs [hunk 1]
```diff
@@ -197,9 +197,9 @@ impl PlannerContext {
 
     /// extends the FROM schema, returning the existing one, if any
     pub fn extend_outer_from_schema(&mut self, schema: &DFSchemaRef) -> Result<()> {
-        self.outer_from_schema = match self.outer_from_schema.as_ref() {
-            Some(from_schema) => Some(Arc::new(from_schema.join(schema)?)),
-            None => Some(Arc::clone(schema)),
+        match self.outer_from_schema.as_mut() {
+            Some(from_schema) => Arc::make_mut(from_schema).merge(schema),
+            None => self.outer_from_schema = Some(Arc::clone(schema)),
```
Comment (eejbyfeldt) [inline datafusion/sql/src/planner.rs:202]: @aalexandrov Can you help verify that this is correct? 

I am not fully following your comment here: https://github.com/apache/datafusion/pull/11456#discussion_r1677146980 At least in the current code merge will still have both values for `j1_id` since they will have differnt qualifiers.

File: datafusion/core/src/dataframe/mod.rs [hunk 2]
```diff
@@ -3337,52 +3337,6 @@ mod tests {
         Ok(())
     }
 
-    // Table 't1' self join
-    // Supplementary test of issue: https://github.com/apache/datafusion/issues/7790
```
Comment (alamb) [inline datafusion/core/src/dataframe/mod.rs:3341]: why is this test removed?

Comment (eejbyfeldt) [reply datafusion/core/src/dataframe/mod.rs:3341]: Should have explained that more in the description. Before it tests that calling `with_column` after a self join without alias will fail in a certain way. After this change it will fail already at the self join. So there is no way to make it test what it testsed before and I belive the self join already has test coverage elsewhere.

File: datafusion/expr/src/utils.rs [hunk 3]
```diff
@@ -260,7 +252,11 @@ pub fn grouping_set_to_exprlist(group_expr: &[Expr]) -> Result<Vec<&Expr>> {
         }
         Ok(grouping_set.distinct_expr())
     } else {
-        Ok(group_expr.iter().collect())
+        Ok(group_expr
+            .iter()
```
Comment (comphead) [inline datafusion/expr/src/utils.rs:256]: wondering if can get rid of double collection iteration?

**Comment by comphead** [comment]
we need probably to check how it works if provided the schema and catalog

File: datafusion/sql/src/planner.rs [hunk 4]
```diff
@@ -197,9 +197,9 @@ impl PlannerContext {
 
     /// extends the FROM schema, returning the existing one, if any
     pub fn extend_outer_from_schema(&mut self, schema: &DFSchemaRef) -> Result<()> {
-        self.outer_from_schema = match self.outer_from_schema.as_ref() {
-            Some(from_schema) => Some(Arc::new(from_schema.join(schema)?)),
-            None => Some(Arc::clone(schema)),
+        match self.outer_from_schema.as_mut() {
+            Some(from_schema) => Arc::make_mut(from_schema).merge(schema),
```
Comment (alamb) [inline datafusion/sql/src/planner.rs:201]: TIL `Arc::make_mut` 📓

**Review by alamb — COMMENTED** [review]
Thank you @eejbyfeldt -- I reviewed this code and the tests and it looks good to me. 

@comphead  what do yoy mean by this comment:

> we need probably to check how it works if provided the schema and catalog

Do you mean we should add a test with different schemas?

File: datafusion/expr/src/logical_plan/plan.rs [hunk 5]
```diff
@@ -3069,6 +3070,8 @@ fn calc_func_dependencies_for_aggregate(
         let group_by_expr_names = group_expr
             .iter()
             .map(|item| item.schema_name().to_string())
+            .collect::<IndexSet<_>>()
+            .into_iter()
```
Comment (jonahgao) [inline datafusion/expr/src/logical_plan/plan.rs:3074]: Can we directly remove duplicates from [`group_expr`](https://github.com/jonahgao/datafusion/commit/6eba7f6de31d9e464e5b2fccdf2cc4985f1b8fb6#diff-f69e720234d9da6cb3a4a178d3a5575fcd34f68191335a8c2465a172e8c4e6f1R2953) so that we don't need to perform duplicate removal here again?

**Review by jonahgao — APPROVED** [review]
LGTM, I left a small suggestion, but I don't think it's necessary.

File: datafusion/expr/src/utils.rs (hunk 3 above)
Comment (alamb) [reply datafusion/expr/src/utils.rs:256]: The double iteration is used to deduplicate the values

File: datafusion/expr/src/logical_plan/plan.rs (hunk 5 above)
Comment (alamb) [reply datafusion/expr/src/logical_plan/plan.rs:3074]: I played around with trying to make this work and I found it was not easy  -- perhaps we can do it as a follow on PR?

**Comment by comphead** [comment]
> Thank you @eejbyfeldt -- I reviewed this code and the tests and it looks good to me.
> 
> @comphead what do yoy mean by this comment:
> 
> > we need probably to check how it works if provided the schema and catalog
> 
> Do you mean we should add a test with different schemas?

I was thinking about playing with fully qualified columns, like schema/catalog etc

**Comment by alamb** [comment]
> > Thank you @eejbyfeldt -- I reviewed this code and the tests and it looks good to me.
> > @comphead what do yoy mean by this comment:
> > > we need probably to check how it works if provided the schema and catalog
> > 
> > 
> > Do you mean we should add a test with different schemas?
> 
> I was thinking about playing with fully qualified columns, like schema/catalog etc

Let's do it as a follow on so this PR doesn't hang out unmerged for too long.

**Comment by alamb** [comment]
Thanks again @eejbyfeldt  @jonahgao and @comphead
