### PR TITLE
Fixed issue with md5 not support LargeUtf8 correctly

### LINKED ISSUE #13444: Error running crypto functions on `Dictionary` arrays such as `md5`
### Describe the bug

A regression appears to have been introduced in 
- https://github.com/apache/datafusion/pull/13407

T

### To Reproduce

This used to work in DataFusion 42.0.0 but doesn't in DataFusion 43.0.0:

```
DataFusion CLI v43.0.0
> create table t as values (arrow_cast('Foo', 'Dictionary(Int32, LargeUtf8)'));
0 row(s) fetched.
Elapsed 0.013 seconds.

> select md5(column1) from t;
Arrow error: Compute error: Internal Error: Cannot cast Utf8View to StringArray of expected type
```

### Expected behavior

Query should complete

### Additional context

I found this while writing tests in https://github.com/apache/datafusion/pull/13443 -- Feel free to take those tests to work on this issue

Those tests fail like this:

```
External error: query failed: DataFusion error: Arrow error: Invalid argument error: column types must match schema types, expected LargeUtf8 but found Utf8 at column index 0
[SQL] select md5(ascii_1) from test_basic_operator;
at test_files/string/./string_query.slt.part:1381
at test_files/string/large_string.slt:93
```

### PR DESCRIPTION
**Pull request by Omega359**
## Which issue does this PR close?

- Closes #13444
- Closes https://github.com/apache/datafusion/pull/13443

## Rationale for this change

Bug fix for md5 not working as expected with largeutf8 input

## What changes are included in this PR?

Code, tests.

## Are these changes tested?

Yes

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/functions/src/crypto/md5.rs [hunk 1]
```diff
@@ -64,11 +64,11 @@ impl ScalarUDFImpl for Md5Func {
     fn return_type(&self, arg_types: &[DataType]) -> Result<DataType> {
         use DataType::*;
         Ok(match &arg_types[0] {
-            LargeUtf8 | LargeBinary => LargeUtf8,
+            LargeUtf8 | LargeBinary => Utf8,
```
Comment (alamb) [inline datafusion/functions/src/crypto/md5.rs:67]: 👍

Comment (alamb) [reply datafusion/functions/src/crypto/md5.rs:67]: Maybe as a follow on it should really be LargeUtf8 but then we would have to change the function I suppose

**Review by alamb — APPROVED** [review]
Thanks @Omega359  -- this looks like a good improvement to me

**Comment by alamb** [comment]
Since this is a small code / bug fix merging it in now
