### PR TITLE
`TableProvider` to skip files in the folder which non relevant to selected reader

### LINKED ISSUE #16460: Make `datafusion` read parquet folders if non parquet files exists
> Create test data
> ```
> ls -la /tmp/t1
> 
> -rw-r--r--@  1 xxx  wheel   12 Jun  6 08:35 .part-00000-e248d995-5eac-404e-a2ed-0eb16e27c005-c000.snappy.parquet.crc
> -rw-r--r--@  1 xxx  wheel  455 Jun  6 08:35 part-00000-e248d995-5eac-404e-a2ed-0eb16e27c005-c000.snappy.parquet
> ```
> 
> -  should realize this is a folder and rewrite as `/tmp/t1/*.parquet`
> ```
> DataFusion CLI v47.0.0
> CREATE EXTERNAL TABLE t1 STORED AS PARQUET location '/tmp/t1';
> Parquet error: Parquet error: Invalid Parquet file. Corrupt footer
> ```
>  

 _Originally posted by @comphead in [#13456](https://github.com/apache/datafusion/issues/13456#issuecomment-2949696136)_

### PR DESCRIPTION
**Pull request by comphead**
## Which issue does this PR close?

- Closes #16460 .

### CODE REVIEW

File: datafusion/core/src/datasource/listing_table_factory.rs [hunk 1]
```diff
@@ -125,6 +125,13 @@ impl TableProviderFactory for ListingTableFactory {
             // specifically for parquet file format.
             // See: https://github.com/apache/datafusion/issues/7317
             None => {
+                // if the folder then rewrite a file path as 'path/*.parquet'
```
Comment (comphead) [inline datafusion/core/src/datasource/listing_table_factory.rs:128]: this is an actual fix

Comment (alamb) [reply datafusion/core/src/datasource/listing_table_factory.rs:128]: This will mean a directory of files like `foo/my_file.parquet.snappy` would not be readable anymore -- I think that spark creates files like `my_file.snappy.parquet` so it should be ok

Comment (comphead) [reply datafusion/core/src/datasource/listing_table_factory.rs:128]: it should be ok, compressed files are usually `*.codec.parquet` and more broad wildcard `*.parquet` should read them. My local test I did against `part-00000-9b95f137-d11f-44b6-84b7-d49c95bc7c5b-c000.snappy.parquet`
