### PR TITLE
Fallback to Utf8View for `Dict(_, Utf8View)` in `type_union_resolution_coercion`

### LINKED ISSUE #14581: coercion of input types in `coalesce` leads to type unsupported arrow cast
### Describe the bug

Tested on datafusion `main` at 5239d1ac.

It looks like coercion of input types in `coalesce` (and probably other similar expressions) it's possible to end up with a common type of `Dictionary(..., Utf8View)`, but `arrow` does not support casting to that type.

### To Reproduce

``` sql
select coalesce(arrow_cast('', 'Utf8View'), arrow_cast('', 'Dictionary(UInt32, Utf8)'));
```

leads to

```
Arrow error: Cast error: Unsupported output type for dictionary packing: Utf8View
```

### Expected behavior

I would expect either:
- datafusion's coercion rules to not select a type which is not supported to go inside a dictionary (`Utf8View`), OR
- dictionary packing a `Utf8View` should be supported

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jayzhan211**
## Which issue does this PR close?

- Closes #14581.

## Rationale for this change

utf8view is good enough, there is no reason we need `dict(_, utf8view)`.

### CODE REVIEW

File: datafusion/expr-common/src/type_coercion/binary.rs [hunk 1]
```diff
@@ -537,8 +537,15 @@ fn type_union_resolution_coercion(
         }
         (DataType::Dictionary(index_type, value_type), other_type)
         | (other_type, DataType::Dictionary(index_type, value_type)) => {
-            let new_value_type = type_union_resolution_coercion(value_type, other_type);
-            new_value_type.map(|t| DataType::Dictionary(index_type.clone(), Box::new(t)))
+            match type_union_resolution_coercion(value_type, other_type) {
+                // Dict(k, Utf8View) is redundant, Utf8View is good enough
+                Some(DataType::Utf8View) => Some(DataType::Utf8View),
```
Comment (davidhewitt) [inline datafusion/expr-common/src/type_coercion/binary.rs:542]: Possibly also true for binary views (even if I didn't report in my original issue)?

**Review by davidhewitt — COMMENTED** [review]
Thanks for fixing this!

**Review by alamb — COMMENTED** [review]
Could we get some tests for this as well?

**Comment by jayzhan211** [comment]
It seems binary view is problematic, so I remove it for now. Add it if there is test covered

**Review by alamb — APPROVED** [review]
Thank you @jayzhan211 and @davidhewitt
