### PR TITLE
fix: `array_distinct` inner nullability causing type mismatch

### LINKED ISSUE #17416: Unexpected "type mismatch" when filtering bool list column using `array_distinct` and `make_array`
### Describe the bug

The following filter expression generates a `InternalError("type mismatch")` for a column of type `List[nullable Bool]` (aka inner nullability is `false`):

```
.filter(array_distinct(col(column_name)).eq(make_array(vec![lit(false)])))
```

### To Reproduce

This test fails as per the comments. Note that the return value of `run_test` strictly is what `collect()` returns—no short circuiting happens. That's where the unexpected error occurs.

```rust
use std::sync::Arc;

use arrow::array::{ArrayRef, BooleanArray, ListArray, RecordBatch};
use arrow::buffer::OffsetBuffer;
use arrow::datatypes::{DataType, Field, Schema};
use datafusion::catalog::MemTable;
use datafusion::error::DataFusionError;
use datafusion::logical_expr::{col, lit};
use datafusion::prelude::{SessionContext, array_distinct, make_array};

async fn run_test(
    inner_nullable: bool,
    outer_nullable: bool,
) -> Result<Vec<RecordBatch>, DataFusionError> {
    // Some data
    let column_name = "bool_column";

    let values = BooleanArray::from(vec![true, false, true, true, false, false, true, false]);
    let offsets = OffsetBuffer::new(vec![0i32, 1, 2, 4, 6, 8].into());
    let bool_lists = ListArray::try_new(
        Arc::new(Field::new("item", DataType::Boolean, inner_nullable)),
        offsets,
        Arc::new(values),
        None,
    )
    .expect("failed to create a bool list array");

    let array = Arc::new(bool_lists) as ArrayRef;
    let field = Field::new(column_name, array.data_type().clone(), outer_nullable);
    let schema = Arc::new(Schema::new(vec![field]));

    let ctx = SessionContext::new();
    ctx.register_table(
        "test_table",
        Arc::new(
            MemTable::try_new(
                Arc::clone(&schema),
                vec![vec![
                    RecordBatch::try_new_with_options(schema, vec![array], &Default::default())
                        .expect("failed to create the record batch"),
                ]],
            )
            .expect("failed to create mem table"),
        ),
    )
    .expect("failed to register table");

    //
    let filter_expr = array_distinct(col(column_name)).eq(make_array(vec![lit(false)]));

    // no filtering
    ctx.table("test_table")
        .await
        .unwrap()
        .filter(filter_expr)
        .unwrap()
        .collect()
        .await
}

#[tokio::test]
async fn internal_error_repro() {
    assert!(run_test(true, true).await.is_ok());
    assert!(run_test(true, false).await.is_ok());

    assert!(dbg!(run_test(false, true).await).is_ok()); // FAILS: InternalError("type mismatch")
    assert!(dbg!(run_test(false, false).await).is_ok()); // FAILS: InternalError("type mismatch")
}
```

### Expected behavior

My expectation would be that this filter expression should work regardless of the nullability.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dqkqd**
## Which issue does this PR close?

- Closes #17416.

## Rationale for this change

`array_distinct`'s inner return type is always `nullable`,
however `general_array_distinct` maintain input nullability,
causing type mismatch error.

I believe the same error happens for `array_union` and `array_intersect` (in `set_ops.rs`).
I can include the fix for those in this PR or maybe another separated PR.

## What changes are included in this PR?

- Match return type nullability for `array_distinct`.

## Are these changes tested?

Yes.
I tried to add unit tests checking return types (similar to #15901),
but it wasn't clear to me whether the added tests could verify
the issue #17416. So I switched to the integration test.

- Added test for `List` with inner `nullability = true / false`.
- I did not added tests for `LargeList`, I don't think it needed
because the code path for the return type is identical to `List`.

## Are there any user-facing changes?

I don't think so.

### CODE REVIEW

File: datafusion/core/tests/dataframe/mod.rs [hunk 1]
```diff
@@ -6479,3 +6479,87 @@ async fn test_duplicate_state_fields_for_dfschema_construct() -> Result<()> {
 
     Ok(())
 }
+
+#[tokio::test]
+async fn array_distinct_on_list_with_inner_nullability_causing_type_mismatch(
```
Comment (dqkqd) [inline datafusion/core/tests/dataframe/mod.rs]: I don't like this test, I wish I could write `slt`. 
But I don't know how to construct a nullable array from sql.

Maybe with this improvement from `arrow-rs` (https://github.com/apache/arrow-rs/issues/8351), 
we can write something like this in the future:
`select arrow_cast([1,2,3], 'List(Int64)')` (for nullable = false)
and
`select arrow_cast([1,2,3], 'List(nullable Int64)')` (for nullable = true)

(then lots of tests with nested data type can be rewritten into `slt` tests)

**Comment by dqkqd** [comment]
I verified the added test fail without the changes:

```
    running 1 test
    test dataframe::array_distinct_on_list_with_inner_nullability_causing_type_mismatch ... FAILED

    failures:

    failures:
        dataframe::array_distinct_on_list_with_inner_nullability_causing_type_mismatch

    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 766 filtered out; finished in 0.29s

  stderr ───

    thread 'dataframe::array_distinct_on_list_with_inner_nullability_causing_type_mismatch' panicked at datafusion/core/tests/dataframe/mod.rs:6554:46:
    called `Result::unwrap()` on an `Err` value: Internal("Function 'array_distinct' returned value of type 'List(Field { name: \"item\", data_type: Int32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} })' while the following type was promised at planning time and expected: 'List(Field { name: \"item\", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} })'")
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

  Cancelling due to test failure:
────────────
     Summary [   0.331s] 1 test run: 0 passed, 1 failed, 1690 skipped
        FAIL [   0.298s] datafusion::core_integration dataframe::array_distinct_on_list_with_inner_nullability_causing_type_mismatch
error: test run failed
```

File: datafusion/functions-nested/src/set_ops.rs [hunk 2]
```diff
@@ -290,10 +290,14 @@ impl ScalarUDFImpl for ArrayDistinct {
...
-                Ok(DataType::new_large_list(field.data_type().clone(), true))
-            }
+            List(field) => Ok(DataType::new_list(
+                field.data_type().clone(),
+                field.is_nullable(),
+            )),
+            LargeList(field) => Ok(DataType::new_large_list(
+                field.data_type().clone(),
+                field.is_nullable(),
+            )),
```
Comment (dqkqd) [inline datafusion/functions-nested/src/set_ops.rs]: I looked at a similar PR for `map_values`: #15901,
but I wasn't sure should I switch to `return_field_from_args`

Comment (Jefffrey) [reply datafusion/functions-nested/src/set_ops.rs]: Actually would this just be as simple as:

```rust
fn return_type(&self, arg_types: &[DataType]) -> Result<DataType> {
    Ok(arg_types[0].clone())
}
```

?

File: datafusion/core/tests/dataframe/mod.rs (hunk 1 above)
Comment (Jefffrey) [reply datafusion/core/tests/dataframe/mod.rs]: We could also place this test in `set_ops.rs` itself to get closer to the function, for example `array_has`:

https://github.com/apache/datafusion/blob/b98cad616ad9c69df9a425fc7473b799ffc258ee/datafusion/functions-nested/src/array_has.rs#L753-L791

File: datafusion/functions-nested/src/set_ops.rs (hunk 2 above)
Comment (dqkqd) [reply datafusion/functions-nested/src/set_ops.rs]: Thank you, I applied the suggestion.

File: datafusion/functions-nested/src/set_ops.rs [hunk 3]
```diff
@@ -563,3 +555,54 @@ fn general_array_distinct<OffsetSize: OffsetSizeTrait>(
...
+            arg_fields: vec![input_field.clone().into()],
+            number_rows: 1,
+            return_field: input_field.clone().into(),
+            config_options: Arc::new(ConfigOptions::default()),
+        })?;
+
+        assert_eq!(
+            result.data_type(),
+            udf.return_type(&[input_field.data_type().clone()])?
+        );
```
Comment (dqkqd) [inline datafusion/functions-nested/src/set_ops.rs]: `ScalarUdf::invoke_with_args` has a data type check in debug mode:
https://github.com/apache/datafusion/blob/b98cad616ad9c69df9a425fc7473b799ffc258ee/datafusion/expr/src/udf.rs#L241-L249

But I think it is better to have an explicit assertion in the test code.

File: datafusion/core/tests/dataframe/mod.rs (hunk 1 above)
Comment (dqkqd) [reply datafusion/core/tests/dataframe/mod.rs]: I added a test in `set_ops.rs`, but it seems quite different with the issue description.
At first glance, to the issue description, I thought the error was caused by the data type mismatch between
`array_distinct` and `make_array`.
But the actual error was due to the type mismatch in the `array_distinct` itself.

Comment (dqkqd) [reply datafusion/core/tests/dataframe/mod.rs]: I prefer deleting the test in `core/tests/dataframe` (because it is not related to dataframe at all),
but I'm not sure if adding only one test in `set_ops.rs` can capture the whole picture in the issue description.

**Comment by dqkqd** [comment]
I verified the new test added fail without code changes:

```

    running 1 test
    test set_ops::tests::test_array_distinct_inner_nullability_result_type_match_return_type::case_2 ... FAILED

    failures:

    failures:
        set_ops::tests::test_array_distinct_inner_nullability_result_type_match_return_type::case_2

    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 11 filtered out; finished in 0.00s

  stderr ───

    thread 'set_ops::tests::test_array_distinct_inner_nullability_result_type_match_return_type::case_2' panicked at datafusion/functions-nested/src/set_ops.rs:607:9:
    assertion `left == right` failed
      left: List(Field { name: "item", data_type: Int32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} })
     right: List(Field { name: "item", data_type: Int32, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} })
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

File: datafusion/core/tests/dataframe/mod.rs (hunk 1 above)
Comment (Jefffrey) [reply datafusion/core/tests/dataframe/mod.rs]: I think the test as is is sufficient; this is a minor fix and having a whole DataFrame test case might be a little overkill 😅

**Comment by dqkqd** [comment]
> Looks good, though I wonder if it is necessary to pull in rstest just for this single case?

I was thinking to add more cases (e.g. `DataType::LargeList`), and more tests (for `array_union`, `array_intersect`).

But it might be unnecessary, those can be removed later in favor of equivalent `slt` tests, once we have a way to
construct nested data types with different inner nullability in sql.

**Comment by Jefffrey** [comment]
Thanks @dqkqd

**Comment by dqkqd** [comment]
Thanks @Jefffrey for reviewing.
