### PR TITLE
Fix functions with Volatility::Volatile and parameters

### LINKED ISSUE #13000: Volatility::Volatile does not work for functions with arguments
### Describe the bug

For functions whose signature contains Volatility::Volatile and arguments, invoke is called once and without _number_rows

### To Reproduce
```
**TABLE:**
"+-------+", //
"| value |", //
"+-------+", //
"| val_1 |", //
"| val_2 |", //
"| val_3 |", //
"| val_4 |", //
"| val_5 |", //
"| val_6 |", //
"| val_7 |", //
"+-------+",
```

```
SELECT random(1, 10) AS r, table.value AS value FROM table;
```
**random(a, b)** is a function that returns a random value in the range from a to b. This function has the following signature:
**Signature::exact(_vec![DataType::Int32, DataType::Int32],_ _Volatility::Volatile_)**

### Expected behavior
```
"+-----------+", //
"| r | value |", //
"+-----------+", //
"| 7 | val_1 |", //
"| 1 | val_2 |", //
"| 7 | val_3 |", //
"| 3 | val_4 |", //
"| 8 | val_5 |", //
"| 4 | val_6 |", //
"| 2 | val_7 |", //
"+-----------+",
```

### Received behavior
```
"+-----------+", //
"| r | value |", //
"+-----------+", //
"| 7 | val_1 |", //
"| 7 | val_2 |", //
"| 7 | val_3 |", //
"| 7 | val_4 |", //
"| 7 | val_5 |", //
"| 7 | val_6 |", //
"| 7 | val_7 |", //
"+-----------+",
```

### PR DESCRIPTION
**Pull request by agscpp**
## Which issue does this PR close?

Closes #13000.

## Rationale for this change

These changes will allow functions to be implemented that produce a unique result for each call given the same input.

### CODE REVIEW

File: datafusion/expr/src/udf.rs [hunk 1]
```diff
@@ -469,6 +480,21 @@ pub trait ScalarUDFImpl: Debug + Send + Sync {
...
+    /// and with arguments
+    fn invoke_batch(
+        &self,
+        _args: &[ColumnarValue],
+        _number_rows: usize,
+    ) -> Result<ColumnarValue> {
+        not_impl_err!(
+            "Function {} does not implement invoke_batch but called",
+            self.name()
+        )
```
Comment (alamb) [inline datafusion/expr/src/udf.rs:495]: 🤔  It seems like the ideal outcome would be for all ScalarUDFs to implement this method (as it covers `invoke`, `invoke_no_args` as well).

Would you be open to changing this so it uses a default implementation like this?

```suggestion
  if _args.empty() { 
    self.invoke_no_args(number_rows) 
  } else {
    self.invoke(args)
  } 
```

Then the function implementation could decide what to do with that information

File: datafusion/core/tests/user_defined/user_defined_scalar_functions.rs [hunk 2]
```diff
@@ -483,6 +485,188 @@ async fn test_user_defined_functions_with_alias() -> Result<()> {
...
+        ctx.register_udf(ScalarUDF::from(get_new_str_udf));
+
+        let result =
+            plan_and_collect(&ctx, "select add_index_to_string(t.a) AS str from t") // with dynamic function parameters
+                .await?;
+        let expected = [
+            "+-----------+", //
+            "| str       |", //
+            "+-----------+", //
+            "| 1. test_1 |", //
```
Comment (alamb) [inline datafusion/core/tests/user_defined/user_defined_scalar_functions.rs:595]: what is the meaning of the trailing `//` ?

Also, it seems like the indexes repeat (multiple with 1) imply invoke is run multiple times - perhaps we could set `target_partitions` to 1 on the SessionContext so the data wasn't repartitioned?

File: datafusion/core/tests/user_defined/user_defined_scalar_functions.rs [hunk 3]
```diff
@@ -483,6 +485,188 @@ async fn test_user_defined_functions_with_alias() -> Result<()> {
     Ok(())
 }
 
+struct AddIndexToStringScalarUDF {
```
Comment (alamb) [inline datafusion/core/tests/user_defined/user_defined_scalar_functions.rs:488]: Perhaps we can add some comments here explaining what this is:

```suggestion
/// Volatile UDF that should be append a different value to each row
struct AddIndexToStringScalarUDF {
```

File: datafusion/physical-expr/src/scalar_function.rs [hunk 4]
```diff
@@ -143,7 +143,10 @@ impl PhysicalExpr for ScalarFunctionExpr {
         // evaluate the function
         let output = match self.args.is_empty() {
             true => self.fun.invoke_no_args(batch.num_rows()),
-            false => self.fun.invoke(&inputs),
+            false => match self.fun.signature().volatility {
```
Comment (alamb) [inline datafusion/physical-expr/src/scalar_function.rs:146]: If you modified invoke_batch as above, we could change this code to simply call `self.fun.invoke_batch()` always

**Review by alamb — COMMENTED** [review]
Thank you @agscpp  -- this makes a lot of sense and I think is quite close. I left some API comments for your consideration. Let me know!

File: datafusion/expr/src/udf.rs [hunk 5]
```diff
@@ -467,7 +478,28 @@ pub trait ScalarUDFImpl: Debug + Send + Sync {
     /// to arrays, which will likely be simpler code, but be slower.
     ///
     /// [invoke_no_args]: ScalarUDFImpl::invoke_no_args
-    fn invoke(&self, _args: &[ColumnarValue]) -> Result<ColumnarValue>;
+    fn invoke(&self, _args: &[ColumnarValue]) -> Result<ColumnarValue> {
```
Comment (alamb) [inline datafusion/expr/src/udf.rs:481]: Nice! -- as a follow on PR I think we should deprecate the other two functions (`invoke_no_args` and `invoke`) telling people to use `invoke` instead

Is this ok with you @jayzhan211 ?

File: datafusion/core/tests/user_defined/user_defined_scalar_functions.rs [hunk 6]
```diff
@@ -483,6 +485,196 @@ async fn test_user_defined_functions_with_alias() -> Result<()> {
...
+            "| 1. test_2 |",
+            "| 2. test_2 |",
+            "| 4. test_1 |",
+            "| 3. test_2 |",
+            "+-----------+",
+        ];
+        assert_batches_eq!(expected, &result);
+
+        let result =
+            plan_and_collect(&ctx, "select add_index_to_string('test') AS str from t") // with fixed function parameters
```
Comment (alamb) [inline datafusion/core/tests/user_defined/user_defined_scalar_functions.rs:615]: nice

**Review by alamb — APPROVED** [review]
Thank you @agscpp  -- this looks great to me

File: datafusion/expr/src/udf.rs (hunk 5 above)
Comment (findepi) [reply datafusion/expr/src/udf.rs:481]: > as a follow on PR I think we should deprecate the other two functions (`invoke_no_args` and `invoke`) telling people to use `invoke` instead

did you mean `invoke_batch`?

yes, it would be great to have only one invoke entry-point

File: datafusion/expr/src/udf.rs [hunk 7]
```diff
@@ -467,7 +478,28 @@ pub trait ScalarUDFImpl: Debug + Send + Sync {
...
+
+    /// Invoke the function with `args` and the number of rows,
+    /// returning the appropriate result.
+    ///
+    /// The function should be used for signatures with [`datafusion_expr_common::signature::Volatility::Volatile`]
+    /// and with arguments.
+    fn invoke_batch(
+        &self,
+        _args: &[ColumnarValue],
+        _number_rows: usize,
```
Comment (findepi) [inline datafusion/expr/src/udf.rs:496]: These are not unused, let's remove leading `_` from arg names

File: datafusion/expr/src/udf.rs [hunk 8]
```diff
@@ -467,7 +478,28 @@ pub trait ScalarUDFImpl: Debug + Send + Sync {
...
+            "Function {} does not implement invoke but called",
+            self.name()
+        )
+    }
+
+    /// Invoke the function with `args` and the number of rows,
+    /// returning the appropriate result.
+    ///
+    /// The function should be used for signatures with [`datafusion_expr_common::signature::Volatility::Volatile`]
+    /// and with arguments.
```
Comment (findepi) [inline datafusion/expr/src/udf.rs:492]: Only for these?

if yes => the function should be named appropriate `invoke_volatile`)
if no => remove the comment

File: datafusion/core/tests/user_defined/user_defined_scalar_functions.rs [hunk 9]
```diff
@@ -483,6 +485,196 @@ async fn test_user_defined_functions_with_alias() -> Result<()> {
...
+        let expected = [
+            "+---------------+",
+            "| str           |",
+            "+---------------+",
+            "| 1) test_value |",
+            "+---------------+",
+        ];
+        assert_batches_eq!(expected, &result);
+    }
+    {
```
Comment (findepi) [inline datafusion/core/tests/user_defined/user_defined_scalar_functions.rs:644]: Nit: consider separating test cases into separate test functions, this would given them descriptive names

File: datafusion/core/tests/user_defined/user_defined_scalar_functions.rs [hunk 10]
```diff
@@ -483,6 +485,196 @@ async fn test_user_defined_functions_with_alias() -> Result<()> {
     Ok(())
 }
 
+/// Volatile UDF that should be append a different value to each row
+struct AddIndexToStringScalarUDF {
```
Comment (findepi) [inline datafusion/core/tests/user_defined/user_defined_scalar_functions.rs:489]: The volatility is important, let's reflect it in the function name -- it's this function's main purpose, not an attribute it happens to have.


`AddIndexToStringVolatileScalarUDF`

File: datafusion/core/tests/user_defined/user_defined_scalar_functions.rs [hunk 11]
```diff
@@ -483,6 +485,196 @@ async fn test_user_defined_functions_with_alias() -> Result<()> {
     Ok(())
 }
 
+/// Volatile UDF that should be append a different value to each row
```
Comment (findepi) [inline datafusion/core/tests/user_defined/user_defined_scalar_functions.rs:488]:
```suggestion
/// Volatile UDF that should append a different value to each row
#[derive(Debug)]
```

File: datafusion/core/tests/user_defined/user_defined_scalar_functions.rs [hunk 12]
```diff
@@ -483,6 +485,196 @@ async fn test_user_defined_functions_with_alias() -> Result<()> {
...
+impl std::fmt::Debug for AddIndexToStringScalarUDF {
+    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
+        f.debug_struct("ScalarUDF")
+            .field("name", &self.name)
+            .field("signature", &self.signature)
+            .field("fun", &"<FUNC>")
+            .finish()
+    }
+}
+
```
Comment (findepi) [inline datafusion/core/tests/user_defined/user_defined_scalar_functions.rs:514]: Leverage `#[derive(Debug)]`, to ensure all fields are part of debug.

```suggestion
```

File: datafusion/core/tests/user_defined/user_defined_scalar_functions.rs [hunk 13]
```diff
@@ -483,6 +485,196 @@ async fn test_user_defined_functions_with_alias() -> Result<()> {
...
+                        // When calling a function with mutable arguments, the result is returned with ".".
+                        // Example: SELECT add_index_to_string(table.value) FROM table;
+                        index.to_string() + ". " + value
+                    })
+                    .collect()
+            }
+            _ => unimplemented!(),
+        };
+        Ok(ColumnarValue::Array(
+            Arc::new(StringArray::from(answer)) as ArrayRef
```
Comment (findepi) [inline datafusion/core/tests/user_defined/user_defined_scalar_functions.rs:572]:
```suggestion
            Arc::new(StringArray::from(answer))
```

File: datafusion/core/tests/user_defined/user_defined_scalar_functions.rs [hunk 14]
```diff
@@ -483,6 +485,196 @@ async fn test_user_defined_functions_with_alias() -> Result<()> {
...
+
+                        // When calling a function with mutable arguments, the result is returned with ".".
+                        // Example: SELECT add_index_to_string(table.value) FROM table;
+                        index.to_string() + ". " + value
+                    })
+                    .collect()
+            }
+            _ => unimplemented!(),
+        };
+        Ok(ColumnarValue::Array(
```
Comment (findepi) [inline datafusion/core/tests/user_defined/user_defined_scalar_functions.rs:571]: Is it OK for this function to return array also when it's invoked with `ColumnarValue::Scalar` only?

**Review by findepi — APPROVED** [review]

File: datafusion/core/tests/user_defined/user_defined_scalar_functions.rs (hunk 14 above)
Comment (findepi) [reply datafusion/core/tests/user_defined/user_defined_scalar_functions.rs]: I was thinking about https://github.com/apache/datafusion/pull/12922

**Comment by alamb** [comment]
Thank you @agscpp and @findepi  🚀
