### PR TITLE
Minor: Change no-statement error message to be clearer

### LINKED ISSUE #11393: `This context requires a statement!` error message can be confusing
### Describe the bug

When a query which contains no SQL statements inside it is processed, datafusion returns an error which states `The context requires a statement!` - this can be seen [here](https://github.com/apache/datafusion/blob/main/datafusion/core/src/execution/session_state.rs#L556-L560). This error string can be confusing as it doesn't exactly point directly to what the issue is or what the user could do to get around this error.

### To Reproduce

_No response_

### Expected behavior

There should be a much clearer error message that tells the user information which is more actionable, that they can then use to fix their query/usage of datafusion.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by itsjunetime**
## Which issue does this PR close?

Closes #11393 .

## Rationale for this change

This is a much clearer error message than previously existed in its place. 

## What changes are included in this PR?

This changes the error message and adds two tests: one to cover this exact use case (of no statements being provided) and another to cover the instance of multiple statements being provided (which returns an error right before the check to see if any statements were provided at all), since there were no tests for that error case.

## Are these changes tested?

Yes, running `cargo test` in the root of the repo produces no failures.

## Are there any user-facing changes?

I think this qualifies as a user-facing change, but I don't think it violates any invariants or changes any use-cases (or anything like that) in a way that would require any documentation changes. I may be wrong, though - clarification on if this qualifies as a 'user-facing change' would be appreciated.

### CODE REVIEW

**Comment by alamb** [comment]
Thanks @itsjunetime ! I started the CI on this PR -- once that passes I think this PR will be good to go.

**Comment by alamb** [comment]
@itsjunetime  it appears that the CI job https://github.com/apache/datafusion/actions/runs/9877944034/job/27282735257?pr=11394 failed

I think you can resolve this by doing `cargo fmt` and pushing the result

**Comment by itsjunetime** [comment]
@alamb thank you for catching that - I guess I forgot to run it earlier. All should be good now.

**Comment by alamb** [comment]
> @alamb thank you for catching that - I guess I forgot to run it earlier. All should be good now.

LOL -- well the CI checks caught it, I just figured I would point it out in case you hadn't seen it (I am not really sure how other people have their github alert settings configured. I get a 🚒 hose so miss stuff sometimes)

File: datafusion/core/tests/sql/sql_api.rs [hunk 1]
```diff
@@ -113,6 +113,40 @@ async fn unsupported_statement_returns_error() {
...
+
+    // Give it a string that contains multiple statements
+    let plan_res = state
+        .create_logical_plan(
+            "INSERT INTO test (x) VALUES (1); INSERT INTO test (x) VALUES (2)",
+        )
+        .await;
+    assert_eq!(
+        plan_res.unwrap_err().strip_backtrace(),
+        "This feature is not implemented: The context currently only supports a single SQL statement"
```
Comment (alamb) [inline datafusion/core/tests/sql/sql_api.rs:146]: thank you for adding additional test coverage

**Review by alamb — APPROVED** [review]
Thanks @itsjunetime -- this looks like a nice improvement to me

**Comment by alamb** [comment]
🚀
