### PR TITLE
Fix invalid schema for unions in ViewTables

### LINKED ISSUE #15134: Invalid schema for unions in ViewTable
### Describe the bug

When a ViewTable is created, the plan is run through the `Analyzer` with the `ExpandWildcardRule` and `TypeCoercion` rules. When this ViewTable is later inlined, it is run though the `Analyzer` again, but this second pass of `TypeCoercion` can drop the qualifier information in the `DFSchema` for fields of a union if a field had previously been cast.

### To Reproduce

Below is a test case that demonstrates the error
```rust
    #[test]
    fn test_coerce_union() -> Result<()> {
        let left_plan = Arc::new(LogicalPlan::EmptyRelation(EmptyRelation {
            produce_one_row: false,
            schema: Arc::new(
                DFSchema::try_from_qualified_schema(
                    TableReference::full("datafusion", "test", "foo"),
                    &Schema::new(vec![Field::new("a", DataType::Int32, false)]),
                )
                .unwrap(),
            ),
        }));
        let right_plan = Arc::new(LogicalPlan::EmptyRelation(EmptyRelation {
            produce_one_row: false,
            schema: Arc::new(
                DFSchema::try_from_qualified_schema(
                    TableReference::full("datafusion", "test", "foo"),
                    &Schema::new(vec![Field::new("a", DataType::Int64, false)]),
                )
                .unwrap(),
            ),
        }));
        let union = LogicalPlan::Union(Union::try_new_with_loose_types(vec![
            left_plan, right_plan,
        ])?);
        let analyzed_union = Analyzer::with_rules(vec![Arc::new(TypeCoercion::new())])
            .execute_and_check(union, &ConfigOptions::default(), |_, _| {})?;
        let top_level_plan = LogicalPlan::Projection(Projection::try_new(
            vec![wildcard()],
            Arc::new(analyzed_union),
        )?);
        let expanded_plan =
            Analyzer::with_rules(vec![Arc::new(ExpandWildcardRule::new())])
                .execute_and_check(
                    top_level_plan,
                    &ConfigOptions::default(),
                    |_, _| {},
                )?;

        let expected = "Projection: datafusion.test.foo.a\n  Union\n    Projection: CAST(datafusion.test.foo.a AS Int64) AS a\n      EmptyRelation\n    EmptyRelation";
        assert_analyzed_plan_eq(Arc::new(TypeCoercion::new()), expanded_plan, expected)
    }
```

This will fail with:
```
Error: Context("type_coercion", SchemaError(FieldNotFound { field: Column { relation: Some(Full { catalog: "datafusion", schema: "test", table: "foo" }), name: "a" }, valid_fields: [Column { relation: None, name: "a" }] }, Some("")))
```

### Expected behavior

The above test should succeed.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Friede80**
## Which issue does this PR close?

- Closes #15134

## Rationale for this change

At the core, if a `Union` goes through the `TypeCoercion` analyzer twice, the schema can drop the qualifier information for fields that were cast in the first pass of `TypeCoercion`. To preserve this information, this PR changes `coerce_union_schema` to start from the schema of the `Union` instead of the schema of the first child. 

## Are these changes tested?

Yes

## Are there any user-facing changes?

Yes, this changes the signature of `coerce_union_schema` so that the schema carried by the `Union` is available.

Before:
```rust
pub fn coerce_union_schema(inputs: &[Arc<LogicalPlan>]) -> Result<DFSchema>
```

After:
```rust
pub fn coerce_union_schema(union_plan: &Union) -> Result<DFSchema>
```

### CODE REVIEW

**Comment by Friede80** [comment]
There seems to have been quite a few cracks at this particular situation:
https://github.com/apache/datafusion/issues/5410
https://github.com/apache/datafusion/pull/11082
https://github.com/apache/datafusion/pull/14538
https://github.com/apache/datafusion/pull/10707

The trouble seems to stem from the decision to maintain `TableReference` qualifiers in unions for disambiguation. This makes it very difficult to know when these qualifiers should or shouldn't be passed through at different points in the optimizer. Unless there are well specified semantics around this that I'm missing, I think it would be better go back to the assumption that qualifiers never persist through a union. And we can continue to support field disambiguation by generating unique column names as is done in DuckDB ([deduplicating-identifiers](https://duckdb.org/docs/stable/sql/dialect/keywords_and_identifiers.html#deduplicating-identifiers))

**Comment by alamb** [comment]
> There seems to have been quite a few cracks at this particular situation:
> 
> * [Join two tables with the same schema, then union throws `SchemaError(DuplicateUnqualifiedField )` #5410](https://github.com/apache/datafusion/issues/5410)
> * [Strip table qualifiers from schema in `UNION ALL` for unparser #11082](https://github.com/apache/datafusion/pull/11082)
> * [feat: Implement UNION ALL BY NAME #14538](https://github.com/apache/datafusion/pull/14538)
> * [Strip table qualifiers from schema in `UNION ALL` #10707](https://github.com/apache/datafusion/pull/10707)
> 
> The trouble seems to stem from the decision to maintain `TableReference` qualifiers in unions for disambiguation. This makes it very difficult to know when these qualifiers should or shouldn't be passed through at different points in the optimizer. Unless there are well specified semantics around this that I'm missing, I think it would be better go back to the assumption that qualifiers never persist through a union. And we can continue to support field disambiguation by generating unique column names as is done in DuckDB ([deduplicating-identifiers](https://duckdb.org/docs/stable/sql/dialect/keywords_and_identifiers.html#deduplicating-identifiers))

Maybe @jonahgao  can offer an opinion on this suggestion

File: datafusion/expr/src/logical_plan/plan.rs [hunk 1]
```diff
@@ -2843,13 +2845,21 @@ impl Union {
                     )?
                 };
                 let nullable = fields.iter().any(|field| field.is_nullable());
-                let mut field = Field::new(name, data_type.clone(), nullable);
+
+                // Generate unique field name
+                let name = if let Some(count) = name_counts.get_mut(&base_name) {
+                    *count += 1;
```
Comment (jonahgao) [inline datafusion/expr/src/logical_plan/plan.rs:2851]: Make sense to me👍. But it doesn't work for this case:
```sh
> create table t1(a int);
0 row(s) fetched.
Elapsed 0.005 seconds.

> create table t2(a int);
0 row(s) fetched.
Elapsed 0.007 seconds.

> select * from t1,t2 union all select * from t1,t2;
type_coercion
caused by
Schema error: Schema contains duplicate unqualified field name
```
The above query works on the main branch.

File: datafusion/optimizer/src/analyzer/type_coercion.rs [hunk 2]
```diff
@@ -930,7 +930,7 @@ fn coerce_case_expression(case: Case, schema: &DFSchema) -> Result<Case> {
 /// This method presumes that the wildcard expansion is unneeded, or has already
 /// been applied.
 pub fn coerce_union_schema(inputs: &[Arc<LogicalPlan>]) -> Result<DFSchema> {
-    let base_schema = inputs[0].schema();
+    let base_schema = inputs[0].schema().as_ref().clone().strip_qualifiers();
```
Comment (jonahgao) [inline datafusion/optimizer/src/analyzer/type_coercion.rs:933]: I think we can achieve the same effect by modifying the following line, but avoid cloning the schema.
https://github.com/apache/datafusion/blob/69b0648b12ce3dc6e4e31e13424ea96dbd2dc8fd/datafusion/optimizer/src/analyzer/type_coercion.rs#L1000

Change `qualifier.cloned()` to `None`.

File: datafusion/expr/src/logical_plan/plan.rs (hunk 1 above)
Comment (jonahgao) [reply datafusion/expr/src/logical_plan/plan.rs:2851]: It seems like `TypeCoercion` undoes the renaming efforts here.
Maybe `TypeCoercion` should only modify the data types of union inputs, rather than field names 🤔

File: datafusion/expr/src/logical_plan/builder.rs [hunk 3]
```diff
@@ -776,8 +777,32 @@ impl LogicalPlanBuilder {
             &missing_cols,
             is_distinct,
         )?;
+
+        let mut sort_exprs = normalize_sorts(sorts, &plan)?;
+        if matches!(&plan, LogicalPlan::Union(_))
```
[the remark this answers is not in the document]
Comment (Friede80) [reply datafusion/expr/src/logical_plan/builder.rs:782]: I agree it feels strange and I wouldn't mind getting rid of this, but I put it in for backwards compatibility, because currently if you ran:
```sql
select t1.a from t1 union all select t2.a from t2 order by t1.a
```
it would work. But after this PR, it would fail without this pass

File: datafusion/optimizer/src/analyzer/type_coercion.rs (hunk 2 above)
Comment (Friede80) [reply datafusion/optimizer/src/analyzer/type_coercion.rs:933]: Oh good catch, that is nicer.

File: datafusion/expr/src/logical_plan/plan.rs (hunk 1 above)
Comment (Friede80) [reply datafusion/expr/src/logical_plan/plan.rs:2851]: oh right, because the union schema is discarded during coercion. My initial attempt to fix this issue propagated the union schema through, but I removed it when I decided not to maintain qualifiers, but I think adding that back would resolve this.

Comment (Friede80) [reply datafusion/expr/src/logical_plan/plan.rs:2850]: Addressed in https://github.com/apache/datafusion/pull/15135/commits/612c217d13b86647b7438b6fd1054c0d8c27f766

File: datafusion/expr/src/logical_plan/builder.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (jonahgao) [reply datafusion/expr/src/logical_plan/builder.rs:782]: Since we stripped qualifiers, it should be reasonable that `order by t1.a` fails. I tested this behavior in PostgreSQL, and it works that way.
```sh
psql=> select a from t1 union all select a from t2 order by t1.a;
ERROR:  missing FROM-clause entry for table "t1"
LINE 1: select a from t1 union all select a from t2 order by t1.a;
                                                             ^
psql=> select a from t1 union all select a from t2 order by a;
 a
---
(0 rows)
```
Moreover, it seems like a bug to me if `order by not_exist_table.a` executes successfully.

[the remark this answers is not in the document]
Comment (Friede80) [reply datafusion/expr/src/logical_plan/builder.rs:782]: I'm with you. I'll take it out

**Review by jonahgao — APPROVED** [review]
LGTM👍, thank you @Friede80

**Comment by alamb** [comment]
Thank you @jonahgao and @Friede80
