### PR TITLE
fix: CASE with NULL

### LINKED ISSUE #11258: `CASE` with `NULL` branch does not coerce when passed to aggregate function
### Describe the bug

Type coercion doesn't seem to handle NULL in a `CASE` branch when used inside of an aggregate.

### To Reproduce

In Datafusion CLI:
```
> CREATE TABLE example(data double precision);
0 row(s) fetched.
Elapsed 0.005 seconds.

> SELECT sum(CASE WHEN data is NULL THEN NULL ELSE data + 1 END) FROM example;
Error during planning: Execution error: User-defined coercion failed with Execution("Sum not supported for Null") No function matches the given name and argument types 'sum(Null)'. You might need to add explicit type casts.
        Candidate functions:
        sum(UserDefined)
```

### Expected behavior

`NULL` type should coerce to the `ELSE` branch type.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Weijun-H**
## Which issue does this PR close?

Closes #11258

### CODE REVIEW

File: datafusion/expr/src/expr_schema.rs [hunk 1]
```diff
@@ -112,7 +112,23 @@ impl ExprSchemable for Expr {
...
+                    return Ok(then_type);
+                }
+
+                let else_type = case
+                    .else_expr
+                    .as_ref()
+                    .map_or(Ok(DataType::Null), |e| e.get_type(schema))?;
+
+                match (then_type.clone(), else_type.clone()) {
+                    (DataType::Null, DataType::Null) => Ok(DataType::Int64),
```
Comment (jonahgao) [inline datafusion/expr/src/expr_schema.rs:127]: There might be a problem with the following expression.
```sql
CASE data WHEN 1 THEN NULL WHEN 2 THEN 3.3 ELSE NULL END;
```
Its type being float would be more reasonable.

Another more general fix might be to ensure that type coercion has already been performed before calling `get_type`, but I am not sure if that can be achieved. Therefore, the current solution is okay for me.

File: datafusion/expr/src/expr_schema.rs [hunk 2]
```diff
@@ -112,7 +112,23 @@ impl ExprSchemable for Expr {
...
+                if !then_type.is_null() {
+                    return Ok(then_type);
+                }
+
+                let else_type = case
+                    .else_expr
+                    .as_ref()
+                    .map_or(Ok(DataType::Null), |e| e.get_type(schema))?;
+
+                match (then_type.clone(), else_type.clone()) {
```
Comment (jonahgao) [inline datafusion/expr/src/expr_schema.rs:126]:
```suggestion
                match (&then_type, &else_type) {
```
I think we can avoid these clones.

File: datafusion/expr/src/expr_schema.rs (hunk 1 above)
Comment (Weijun-H) [reply datafusion/expr/src/expr_schema.rs]: added a test for it

File: datafusion/expr/src/expr_schema.rs [hunk 3]
```diff
@@ -112,7 +112,22 @@ impl ExprSchemable for Expr {
...
+                }
+
+                let else_type = case
+                    .else_expr
+                    .as_ref()
+                    .map_or(Ok(DataType::Null), |e| e.get_type(schema))?;
+                if !else_type.is_null() {
+                    return Ok(else_type);
+                }
+                Ok(DataType::Int64)
```
Comment (jonahgao) [inline datafusion/expr/src/expr_schema.rs:129]: Although I think returning `DataType::Int64` can make it work fine, because after type coercion it always returns `then_type`. But it is still strange, the type of `CASE data WHEN 1 THEN NULL WHEN 2 THEN 'FOO' ELSE NULL END` is  `DataType::Int64`.

How about returning the first non-NULL type among the `then`  and `else` expressions?

Comment (Weijun-H) [reply datafusion/expr/src/expr_schema.rs:129]: Current implementation will return the first non-NULL type among the then and else expressions.

``` shell
> select arrow_typeof(CASE data WHEN 1 THEN NULL WHEN 2 THEN 'FOO' ELSE NULL END )from example;
+------------------------------------------------------------------------------------------------------+
| arrow_typeof(CASE example.data WHEN Int64(1) THEN NULL WHEN Int64(2) THEN Utf8("FOO") ELSE NULL END) |
+------------------------------------------------------------------------------------------------------+
| Utf8                                                                                                 |
| Utf8                                                                                                 |
| Utf8                                                                                                 |
| Utf8                                                                                                 |
+------------------------------------------------------------------------------------------------------+
```

Comment (jonahgao) [reply datafusion/expr/src/expr_schema.rs:129]: This is because `type_coercion` will convert their types to `Utf8`.
```sh
| logical_plan after type_coercion                           | Projection: arrow_typeof(CASE CAST(example.data AS Int64) WHEN Int64(1) THEN CAST(NULL AS Utf8) WHEN Int64(2) THEN Utf8("FOO") ELSE CAST(NULL AS Utf8) END)                                                                                                                                                                                    |
|                                                            |   TableScan: example
```
You can check this [test](https://github.com/jonahgao/datafusion/blob/d9ff0cafd01614fe850ef4c12ba67761613336e8/datafusion/expr/src/expr_schema.rs#L677). It does not perform type coercion.

File: datafusion/expr/src/expr_schema.rs [hunk 4]
```diff
@@ -112,7 +112,24 @@ impl ExprSchemable for Expr {
...
             Expr::Literal(l) => Ok(l.data_type()),
-            Expr::Case(case) => case.when_then_expr[0].1.get_type(schema),
+            // Expr::Case(case) => case.when_then_expr[0].1.get_type(schema),
+            Expr::Case(case) => {
+                for (_, then_expr) in &case.when_then_expr {
+                    let then_type = then_expr.get_type(schema)?;
+                    if !then_type.is_null() {
+                        return Ok(then_type);
+                    }
+                }
```
Comment (Weijun-H) [inline datafusion/expr/src/expr_schema.rs:122]: return first non-null then type @jonahgao

File: datafusion/expr/src/expr_schema.rs (hunk 3 above)
Comment (Weijun-H) [reply datafusion/expr/src/expr_schema.rs:131]: done

File: datafusion/expr/src/expr_schema.rs [hunk 5]
```diff
@@ -112,7 +112,24 @@ impl ExprSchemable for Expr {
...
+
+                let else_type = case
+                    .else_expr
+                    .as_ref()
+                    .map_or(Ok(DataType::Null), |e| e.get_type(schema))?;
+                if !else_type.is_null() {
+                    return Ok(else_type);
+                }
+                Ok(DataType::Int64)
```
Comment (jonahgao) [inline datafusion/expr/src/expr_schema.rs:131]:
```suggestion
                case.else_expr
                    .as_ref()
                    .map_or(Ok(DataType::Null), |e| e.get_type(schema))
```

We can directly return the datatype of `else_expr`.

File: datafusion/expr/src/expr_schema.rs [hunk 6]
```diff
@@ -112,7 +112,24 @@ impl ExprSchemable for Expr {
             Expr::OuterReferenceColumn(ty, _) => Ok(ty.clone()),
             Expr::ScalarVariable(ty, _) => Ok(ty.clone()),
             Expr::Literal(l) => Ok(l.data_type()),
-            Expr::Case(case) => case.when_then_expr[0].1.get_type(schema),
+            // Expr::Case(case) => case.when_then_expr[0].1.get_type(schema),
```
Comment (jonahgao) [inline datafusion/expr/src/expr_schema.rs:115]:
```suggestion 
```

**Review by jonahgao — APPROVED** [review]
Looks good to me 👍, thanks @Weijun-H

**Comment by alamb** [comment]
Thanks @Weijun-H  and @jonahgao
