### PR TITLE
bug: Always use 'indent' format for explain verbose

### LINKED ISSUE #17480: `EXPLAIN VERBOSE` only works when format is set to (non-default) 'indent'
### Describe the bug

On the `datafusion-cli`, `tree` was made the default explain format in [this PR](https://github.com/apache/datafusion/pull/15427). Now, when we use `EXPLAIN VERBOSE`, we simply get the regular output of `explain format tree`, which isn't verbose.

### To Reproduce

cd `datafusion-cli`
`cargo run`
```sql
> explain verbose select max(1 + 3);
+---------------+-------------------------------+
| plan_type     | plan                          |
+---------------+-------------------------------+
| physical_plan | ┌───────────────────────────┐ |
|               | │       AggregateExec       │ |
|               | │    --------------------   │ |
|               | │           aggr:           │ |
|               | │  max(Int64(1) + Int64(3)) │ |
|               | │                           │ |
|               | │        mode: Single       │ |
|               | └─────────────┬─────────────┘ |
|               | ┌─────────────┴─────────────┐ |
|               | │     PlaceholderRowExec    │ |
|               | └───────────────────────────┘ |
|               |                               |
+---------------+-------------------------------+
```

To workaround this, the user has to manually set the format option to `indent` to get the desired verbose explain output
```sql
set datafusion.explain.format = 'indent';
> explain verbose select max(1 + 3);
```

### Expected behavior
Since only `indent` is supported for `explain verbose`, I think it would be nice to just override the explain format to `indent` when verbose is specified.
```
+------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| plan_type                                                  | plan                                                                                                                          |
+------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------+
| initial_logical_plan                                       | Projection: max(Int64(1) + Int64(3))                                                                                          |
|                                                            |   Aggregate: groupBy=[[]], aggr=[[max(Int64(1) + Int64(3))]]                                                                  |
|                                                            |     EmptyRelation: rows=1                                                                                                     |
| logical_plan after resolve_grouping_function               | SAME TEXT AS ABOVE                                                                                                            |
| logical_plan after type_coercion                           | SAME TEXT AS ABOVE
| analyzed_logical_plan                                      | SAME TEXT AS ABOVE                                                                                                            |
| logical_plan after eliminate_nested_union                  | SAME TEXT AS ABOVE                                                                                                            |
| logical_plan after simplify_expressions                    | Projection: max(Int64(1) + Int64(3))
...
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by petern48**
## Which issue does this PR close?

- Closes #17480

## Rationale for this change

`datafusion-cli` uses `tree` format by default. In order to get proper explain verbose results, the user has to manually set the format to `indent`

## What changes are included in this PR?

This PR makes it so the format is overrided to `indent` whenever `explain verbose` is specified.

## Are these changes tested?

Added test

## Are there any user-facing changes?

Yes

### CODE REVIEW

File: datafusion/sql/src/statement.rs [hunk 1]
```diff
@@ -1714,7 +1714,12 @@ impl<S: ContextProvider> SqlToRel<'_, S> {
             let options = self.context_provider.options();
             let format = format.as_ref().unwrap_or(&options.explain.format);
 
-            let format: ExplainFormat = format.parse()?;
+            // verbose mode only supports indent format
+            let format: ExplainFormat = if verbose {
+                ExplainFormat::Indent
+            } else {
+                format.parse()?
```
Comment (findepi) [inline datafusion/sql/src/statement.rs:1721]: If the both verbose and format are given, we shall ignore neither.
if format requested by the user is not supported, an error should be raised

**Review by findepi — APPROVED** [review]

**Review by xudong963 — APPROVED** [review]

File: datafusion/sql/src/statement.rs (hunk 1 above)
Comment (petern48) [reply datafusion/sql/src/statement.rs:1721]: 1. If both verbose and format are given, we actually return an error. The code below is a few lines above. I think this still makes sense since verbose only supports one format.

```rust
        if verbose && format.is_some() {
            return plan_err!("EXPLAIN VERBOSE with FORMAT is not supported");
        }
```

2. We already raise an error if the format is not supported (the logic is in a different file).

```sql> explain format treee select 1;
Error during planning: Invalid explain format. Expected 'indent', 'tree', 'pgjson' or 'graphviz'. Got 'treee'
```

**Comment by alamb** [comment]
Thanks everyone!
