### PR TITLE
Pass the input schema to stats_projection for ProjectionExpr

### LINKED ISSUE #17122: Column::bounds_check goes into error path from ProjectionExpr::partition_statistics()
### Describe the bug

When computing partition_statistics during evalutaion - flamegraph shows a lot of time spend in bounds_check() which happens as part of a Column::data_type() call.

Image

Almost all of the time in bounds_check() is also spend in fmt() which suggests that this goes into the error branch:
```rust
impl Column {
    fn bounds_check(&self, input_schema: &Schema) -> Result<()> {
        if self.index < input_schema.fields.len() {
            Ok(())
        } else {
            internal_err!(
                "PhysicalExpr Column references column '{}' at index {} (zero-based) but input schema only has {} columns: {:?}",
                self.name,
                self.index,
                input_schema.fields.len(),
                input_schema.fields().iter().map(|f| f.name()).collect::<Vec<_>>()
            )
        }
    }
}
```

All occurrences that I hand checked from my example were originating from `ProjectionExec::partition_statistics()` 

### To Reproduce

Run with RUST_BACKTRACE enabled.

### Expected behavior

data_type() method should not trigger bounds_check() to go to an error path for the column.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by hareshkh**
## Which issue does this PR close?

- Closes #17122 

## Rationale for this change

`bounds_check()` requires input schema, while `schema` field is the output schema.

### CODE REVIEW

**Comment by alamb** [comment]
Thank you for this fix @hareshkh  🙏 


can you please add a test so we don't accidentally break this again in the future?

**Comment by hareshkh** [comment]
@alamb - Added a test, checked that it fails if the wrong schema is supplied. Can you please take a pass again?

Also, when this fix merges, is it possible to cherry-pick it on top of 48.0.1 - to release maybe a 48.0.2?

File: datafusion/physical-plan/src/projection.rs [hunk 1]
```diff
@@ -1230,4 +1232,83 @@ mod tests {
...
+            ),
+        ];
+
+        let projection = ProjectionExec::try_new(exprs, input).unwrap();
+
+        let stats = projection.partition_statistics(None).unwrap();
+
+        assert_eq!(stats.num_rows, Precision::Exact(10));
+        assert_eq!(stats.column_statistics.len(), 2, "Expected 2 columns in projection statistics");
+        assert_eq!(stats.total_byte_size.is_exact().unwrap_or(false), true);
```
Comment (alamb) [inline datafusion/physical-plan/src/projection.rs]: I verified this test covers the change by running the test without the code change and it fails like this

```
assertion `left == right` failed
  left: false
 right: true

Left:  false
Right: true
```

**Comment by alamb** [comment]
> @alamb - Added a test, checked that it fails if the wrong schema is supplied. Can you please take a pass again?
> 
> Also, when this fix merges, is it possible to cherry-pick it on top of 48.0.1 - to release maybe a 48.0.2?

We can consider doing a 48.0.2 release - 

If you want to do so can you please file a new ticket to discuss the possibility here
- https://github.com/apache/datafusion/issues/16486

It seems like this might be something we want to include in the upcoming `49.0.1` release at least
 - #17036

**Comment by hareshkh** [comment]
@alamb : Yes, once this PR merges, I can create a PR to the `branch-49`

**Comment by alamb** [comment]
> @alamb : Yes, once this PR merges, I can create a PR to the `branch-49`

Merged! Thank you.

**Comment by alamb** [comment]
Made a backport PR: 
- https://github.com/apache/datafusion/pull/17174
