### PR TITLE
fix: sqllogictest cannot convert <subquery> to Substrait

### LINKED ISSUE #16281: [substrait] [sqllogictest] Cannot convert <subquery> to Substrait
### Describe the bug

~30 sqllogictest cases are failing in Substrait round-trip mode because of the following error:
```
query failed: DataFusion error: This feature is not implemented: Cannot convert <subquery> to Substrait
```

### To Reproduce

```
cargo test --test sqllogictests -- --substrait-round-trip subquery.slt:1007
```

### Expected behavior

The sqllogictest passes in Substrait round-trip mode

### Additional context

This is part of a broader initiative to improve the reliability of Substrait-to-DataFusion logical plan conversions.
- https://github.com/apache/datafusion/issues/16248

### PR DESCRIPTION
**Pull request by kumarUjjawal**
## Which issue does this PR close?

- Closes #16281

## Rationale for this change

The sqllogictest for the substrait was failing for subquery.

```
query failed: DataFusion error: This feature is not implemented: Cannot convert <subquery> to Substrait
```

## What changes are included in this PR?

- added support for `ScalarSubquery` and `Exists` expressions in the Substrait producer.

## Are these changes tested?
Yes

### CODE REVIEW

**Comment by kumarUjjawal** [comment]
@gabotechs if you could take a look.

**Comment by gabotechs** [comment]
I'm struggling to find the time to take a look at this one. I'm requesting back up now!

File: datafusion/substrait/src/logical_plan/producer/expr/mod.rs [hunk 1]
```diff
@@ -139,16 +139,16 @@ pub fn to_substrait_rex(
...
-        Expr::ScalarSubquery(expr) => {
-            not_impl_err!("Cannot convert {expr:?} to Substrait")
-        }
+        Expr::ScalarSubquery(expr) => producer.handle_scalar_subquery(expr, schema),
         #[expect(deprecated)]
         Expr::Wildcard { .. } => not_impl_err!("Cannot convert {expr:?} to Substrait"),
         Expr::GroupingSet(expr) => not_impl_err!("Cannot convert {expr:?} to Substrait"),
         Expr::Placeholder(expr) => not_impl_err!("Cannot convert {expr:?} to Substrait"),
         Expr::OuterReferenceColumn(_, _) => {
+            // OuterReferenceColumn requires tracking outer query schema context for correlated
```
Comment (kadinrabo) [inline datafusion/substrait/src/logical_plan/producer/expr/mod.rs:151]: I'm still getting a lot of `This feature is not implemented: Cannot convert OuterReferenceColumn` errors when running the tests so maybe this PR can partially close the issue instead of completely? Unless you're still working on it

File: datafusion/substrait/src/logical_plan/producer/expr/subquery.rs [hunk 2]
```diff
@@ -70,3 +71,70 @@ pub fn from_in_subquery(
...
+                            tuples: Some(subquery_plan),
+                        }),
+                    ),
+                ),
+            },
+        ))),
+    };
+
+    // Handle negated EXISTS (NOT EXISTS)
+    if exists.negated {
```
Comment (kadinrabo) [inline datafusion/substrait/src/logical_plan/producer/expr/subquery.rs]: There's no `PREDICATE_OP_NOT_EXISTS` in the spec so I think this a reasonable workaround. Minor note, the consumer hardcodes `negated:false` so I don't think `NOT EXISTS`/`NOT IN` will round-trip correctly ([Exists](https://github.com/apache/datafusion/blob/dededf7c78d587afc662c8a06fb949a0bf4d457f/datafusion/substrait/src/logical_plan/consumer/expr/subquery.rs#L92)/[InSubquery](https://github.com/apache/datafusion/blob/dededf7c78d587afc662c8a06fb949a0bf4d457f/datafusion/substrait/src/logical_plan/consumer/expr/subquery.rs#L57))

File: datafusion/substrait/src/logical_plan/producer/expr/mod.rs (hunk 1 above)
Comment (kumarUjjawal) [reply datafusion/substrait/src/logical_plan/producer/expr/mod.rs:151]: Yeah for the remaining issues I intend to open follow up PRs. My goal is to resolve all the issue related to substrait in the next few weeks.

File: datafusion/substrait/src/logical_plan/producer/expr/subquery.rs (hunk 2 above)
Comment (kumarUjjawal) [reply datafusion/substrait/src/logical_plan/producer/expr/subquery.rs]: I had look into it earlier, I was hoping to open a seperate discussion so not to clutter this PR.

File: datafusion/substrait/src/logical_plan/producer/substrait_producer.rs [hunk 3]
```diff
@@ -361,6 +364,31 @@ pub trait SubstraitProducer: Send + Sync + Sized {
...
+
+    fn handle_exists(
+        &mut self,
+        exists: &Exists,
+        schema: &DFSchemaRef,
+    ) -> datafusion::common::Result<Expression> {
+        from_exists(self, exists, schema)
+    }
+
+    fn handle_outer_reference_column(
```
Comment (benbellick) [inline datafusion/substrait/src/logical_plan/producer/substrait_producer.rs]: Am I correct that this is dead code? Maybe was intended to be added to the match in `datafusion/substrait/src/logical_plan/producer/expr/mod.rs`, but is now being left for later.

File: datafusion/substrait/src/logical_plan/producer/expr/field_reference.rs [hunk 4]
```diff
@@ -76,6 +76,22 @@ pub(crate) fn try_to_substrait_field_reference(
     }
 }
 
+/// Convert an outer reference column to a Substrait field reference.
+/// Outer reference columns reference columns from an outer query scope in correlated subqueries.
+/// We convert them the same way as regular columns since the subquery plan will be
+/// reconstructed with the proper schema context during consumption.
+pub fn from_outer_reference_column(
```
Comment (benbellick) [inline datafusion/substrait/src/logical_plan/producer/expr/field_reference.rs:83]: Is this also deadcode (once the single deadcode caller is deleted)?

File: datafusion/substrait/src/logical_plan/producer/substrait_producer.rs (hunk 3 above)
Comment (kumarUjjawal) [reply datafusion/substrait/src/logical_plan/producer/substrait_producer.rs]: Good catch! Thanks

File: datafusion/substrait/src/logical_plan/producer/expr/field_reference.rs (hunk 4 above)
Comment (kumarUjjawal) [reply datafusion/substrait/src/logical_plan/producer/expr/field_reference.rs:83]: Yes true.

File: datafusion/substrait/src/logical_plan/producer/expr/subquery.rs [hunk 5]
```diff
@@ -70,3 +71,70 @@ pub fn from_in_subquery(
...
+        let function_anchor = producer.register_function("not".to_string());
+
+        #[expect(deprecated)]
+        Ok(Expression {
+            rex_type: Some(RexType::ScalarFunction(ScalarFunction {
+                function_reference: function_anchor,
+                arguments: vec![FunctionArgument {
+                    arg_type: Some(ArgType::Value(substrait_exists)),
+                }],
+                output_type: None,
```
Comment (benbellick) [inline datafusion/substrait/src/logical_plan/producer/expr/subquery.rs]: I'm not sure if this is done consistently across the codebase, but this technically makes this substrait invalid. F[rom the documentation](https://github.com/substrait-io/substrait/blob/95f8f350328f63bf44be63f28eb67680983edbb1/proto/substrait/algebra.proto#L1245-L1246): 
```proto
    // Must be set to the return type of the function, exactly as derived
    // using the declaration in the extension.
    Type output_type = 3;
```

Comment (benbellick) [reply datafusion/substrait/src/logical_plan/producer/expr/subquery.rs]: (I wish that the `substrait-rs` library were at a state where it could handle this for you, but it just isn't there yet)

**Comment by kumarUjjawal** [comment]
@kosiew since you have worked with substrait, could you take a look whenever you get time. Thanks!

File: datafusion/substrait/src/logical_plan/producer/expr/subquery.rs [hunk 6]
```diff
@@ -70,3 +71,70 @@ pub fn from_in_subquery(
...
+                args: vec![],
+                options: vec![],
+            })),
+        })
+    } else {
+        Ok(substrait_exists)
+    }
```
Comment (kosiew) [inline datafusion/substrait/src/logical_plan/producer/expr/subquery.rs]: this is duplicated in 
- fn from_in_list
- fn from_in_subquery

and should be extracted into a helper for consistency

File: datafusion/substrait/src/logical_plan/producer/utils.rs [hunk 7]
```diff
@@ -85,3 +85,35 @@ pub(crate) fn to_substrait_precision(time_unit: &TimeUnit) -> i32 {
         TimeUnit::Nanosecond => 9,
     }
 }
+
+/// Wraps an expression with a `not()` function if `negated` is true.
+/// This is used for negated IN, EXISTS, and other predicates.
+pub(crate) fn negate_if_needed(
```
Comment (kosiew) [inline datafusion/substrait/src/logical_plan/producer/utils.rs]: 👍

**Comment by kumarUjjawal** [comment]
Thansk @kosiew

**Comment by alamb** [comment]
@gabotechs do you have some time to give this PR a review?

File: datafusion/substrait/src/logical_plan/producer/substrait_producer_imports_temp.txt
Comment (gabotechs) [inline datafusion/substrait/src/logical_plan/producer/substrait_producer_imports_temp.txt:1]: 🤔 What is this file?

File: datafusion/substrait/src/logical_plan/producer/utils.rs [hunk 8]
```diff
@@ -85,3 +85,34 @@ pub(crate) fn to_substrait_precision(time_unit: &TimeUnit) -> i32 {
...
+    producer: &mut impl SubstraitProducer,
+    expr: Expression,
+    negated: bool,
+) -> Expression {
```
Comment (gabotechs) [inline datafusion/substrait/src/logical_plan/producer/utils.rs:93]: A function that does nothing if one if it's arguments is false suggests that there's a better way of modeling this:

```rust
fn do_something_if_last_arg_is_true(first_arg, second_arg, third_arg) {
    if !third_arg {
        return
    }
    ...
}
```

seems a like an unnecessary convoluted way of writing an if statement.

File: datafusion/substrait/src/logical_plan/producer/substrait_producer_imports_temp.txt
Comment (kumarUjjawal) [reply datafusion/substrait/src/logical_plan/producer/substrait_producer_imports_temp.txt:1]: 😬 I was doing some cli copy, i will remove it.

**Comment by alamb** [comment]
Thanks @kumarUjjawal @kosiew and @gabotechs
