### PR TITLE
fix concat ws simplify

### LINKED ISSUE #14212: Bug when `concat_ws` simplified to `concat`
### Describe the bug

Using `concat_ws` with an emply delimiter uses the first expr as the delimiter.

### To Reproduce

`SELECT concat_ws('','a','b','c')`
`bac`

### Expected behavior

`SELECT concat_ws('','a','b','c')`
`abc`

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cht42**
## Which issue does this PR close?

Closes #14212

### CODE REVIEW

File: datafusion/functions/src/string/concat_ws.rs [hunk 1]
```diff
@@ -317,7 +318,19 @@ fn simplify_concat_ws(delimiter: &Expr, args: &[Expr]) -> Result<ExprSimplifyRes
             match delimiter {
                 // when the delimiter is an empty string,
                 // we can use `concat` to replace `concat_ws`
-                Some(delimiter) if delimiter.is_empty() => simplify_concat(args.to_vec()),
+                Some(delimiter) if delimiter.is_empty() => {
```
Comment (cht42) [inline datafusion/functions/src/string/concat_ws.rs:321]: `simplify_concat` will return the orginial if no simplification is done which in our case calling `concat_ws` with the args and not the delimiter
https://github.com/apache/datafusion/blob/acf66d66537221ee7501a3be2e08c065a49efd4b/datafusion/functions/src/string/concat.rs#L371

**Review by Blizzara — APPROVED** [review]
Thanks! (disclaimer: I work with @cht42)

File: datafusion/sqllogictest/test_files/expr.slt [hunk 2]
```diff
@@ -465,6 +465,11 @@ SELECT concat_ws('|','a',NULL,NULL)
 ----
 a
 
+query T
+SELECT concat_ws('','a','b','c')
```
Comment (jonahgao) [inline datafusion/sqllogictest/test_files/expr.slt:469]: I tested this query on the [main](https://github.com/apache/datafusion/commit/2f283277d523404401b206e5b98819a0126341b8) branch, and it gave the same result. Am I overlooking something🤔?
```sh
DataFusion CLI v44.0.0
> SELECT concat_ws('','a','b','c');
+---------------------------------------------------+
| concat_ws(Utf8(""),Utf8("a"),Utf8("b"),Utf8("c")) |
+---------------------------------------------------+
| abc                                               |
+---------------------------------------------------+
1 row(s) fetched.
Elapsed 0.009 seconds.
```

Comment (Omega359) [reply datafusion/sqllogictest/test_files/expr.slt:469]: I did the same test as @jonahgao using a checkout from a week or so ago, same result as above.

Comment (cht42) [reply datafusion/sqllogictest/test_files/expr.slt:469]: yes my bad, if i use literal it works, should be with columns

Comment (cht42) [reply datafusion/sqllogictest/test_files/expr.slt:469]: updated the tests with the failing scenario

**Review by jonahgao — APPROVED** [review]
LGTM, thanks @cht42
