### PR TITLE
fix: Pick correct columns in Sort Merge Equijoin

### LINKED ISSUE #18804: Panic in Sort Merge Equijoin when tables have different columns count
Related to #18787 

### Describe the bug

During sort merge join, with a filter, and the columns count of the left/right relations are different, the extracted columns is off which leads to datafusion error such as:

```
DataFusion error: Arrow error: Invalid argument error: number of columns(2) must match number of fields(4) in schema
```

### To Reproduce

Following sqltests are failing

```
statement ok
set datafusion.optimizer.prefer_hash_join = false;

statement ok
DROP TABLE IF EXISTS t1;

statement ok
CREATE TABLE t1(a int, b int) AS VALUES (1, 100), (2, 200), (3, 300);

statement ok
DROP TABLE IF EXISTS t2;

statement ok
CREATE TABLE t2(a int, b int, c int) AS VALUES (4, 101, 1001), (3, 201, 2001), (2, 250, 3001);

statement ok
DROP TABLE IF EXISTS t3;

statement ok
CREATE TABLE t3(x int) AS VALUES (1);

query IIIII
SELECT * FROM t2 RIGHT JOIN t1 on t1.a = t2.a AND t1.b < t2.b
----
NULL NULL NULL 1 100
2 250 3001 2 200
NULL NULL NULL 3 300

query IIIII
SELECT * FROM t1 LEFT JOIN t2 on t1.a = t2.a AND t1.b < t2.b
----
1 100 NULL NULL NULL
2 200 2 250 3001
3 300 NULL NULL NULL

# Small table for LeftMark

# LeftMark equijoin with different columns count
query III rowsort
SELECT t2.a, t2.b, t2.c
FROM t2
WHERE t2.a > 3 OR t2.a IN (SELECT t3.x FROM t3 WHERE t2.b < 150)
----
4 101 1001
```

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tglanz**
## Which issue does this PR close?

- Closes #18804.

## What changes are included in this PR?

Take correct columns

## Are these changes tested?

Yes, 

- added rust tests to hit invalid code paths
- sqltests
- fuzz tests enhancement to fuzzify columns count

Fuzz tests are taken from @rluvaton 's #18788 , excluding those this PR doesn't fix:

```
    fuzz_cases::join_fuzz::test_right_anti_join_1k_binary_filtered
    fuzz_cases::join_fuzz::test_right_anti_join_1k_filtered
    fuzz_cases::join_fuzz::test_right_semi_join_1k_filtered
```

## Are there any user-facing changes?

### CODE REVIEW

File: datafusion/physical-plan/src/joins/sort_merge_join/stream.rs
Comment (rluvaton) [inline datafusion/physical-plan/src/joins/sort_merge_join/stream.rs]: I think this should also be changed to:
```suggestion
                    .take(left_columns_length)
```

**Comment by rluvaton** [comment]
I was able to reproduce the bug when changing the sort_merge_join.slt to have 3 columns in `t2` rather than 2 like in `t1` (below is the diff I changed in the `sort_merge_join.slt` file).

Can you please update the description and update/add tests (I would update the sort_merge_join.slt like in the diff below to make sure all tests are testing that. make sure to add a comment on why 3 columns and t1 2).

<details>
<summary>Updated the slt file to reproduce the error</summary>

```diff
diff --git a/datafusion/sqllogictest/test_files/sort_merge_join.slt b/datafusion/sqllogictest/test_files/sort_merge_join.slt
--- a/datafusion/sqllogictest/test_files/sort_merge_join.slt	(revision f3980641660997345af6061dc3b34f365020bd07)
+++ b/datafusion/sqllogictest/test_files/sort_merge_join.slt	(date 1763411346050)
@@ -26,7 +26,7 @@
 CREATE TABLE t1(a text, b int) AS VALUES ('Alice', 50), ('Alice', 100), ('Bob', 1);
 
 statement ok
-CREATE TABLE t2(a text, b int) AS VALUES ('Alice', 2), ('Alice', 1);
+CREATE TABLE t2(a text, b int, c int) AS VALUES ('Alice', 2, 77), ('Alice', 1, 66);
 
 # inner join query plan with join filter
 query TT
@@ -64,83 +64,83 @@
 ----
 
 # left join without join filter
-query TITI rowsort
+query TITII rowsort
 SELECT * FROM t1 LEFT JOIN t2 ON t1.a = t2.a
 ----
-Alice 100 Alice 1
-Alice 100 Alice 2
-Alice 50 Alice 1
-Alice 50 Alice 2
-Bob 1 NULL NULL
+Alice 100 Alice 1 66
+Alice 100 Alice 2 77
+Alice 50 Alice 1 66
+Alice 50 Alice 2 77
+Bob 1 NULL NULL NULL
 
 # left join with join filter
-query TITI rowsort
+query TITII rowsort
 SELECT * FROM t1 LEFT JOIN t2 ON t1.a = t2.a AND t2.b * 50 <= t1.b
 ----
-Alice 100 Alice 1
-Alice 100 Alice 2
-Alice 50 Alice 1
-Bob 1 NULL NULL
+Alice 100 Alice 1 66
+Alice 100 Alice 2 77
+Alice 50 Alice 1 66
+Bob 1 NULL NULL NULL
 
-query TITI rowsort
+query TITII rowsort
 SELECT * FROM t1 LEFT JOIN t2 ON t1.a = t2.a AND t2.b < t1.b
 ----
-Alice 100 Alice 1
-Alice 100 Alice 2
-Alice 50 Alice 1
-Alice 50 Alice 2
-Bob 1 NULL NULL
+Alice 100 Alice 1 66
+Alice 100 Alice 2 77
+Alice 50 Alice 1 66
+Alice 50 Alice 2 77
+Bob 1 NULL NULL NULL
 
 # right join without join filter
-query TITI rowsort
+query TITII rowsort
 SELECT * FROM t1 RIGHT JOIN t2 ON t1.a = t2.a
 ----
-Alice 100 Alice 1
-Alice 100 Alice 2
-Alice 50 Alice 1
-Alice 50 Alice 2
+Alice 100 Alice 1 66
+Alice 100 Alice 2 77
+Alice 50 Alice 1 66
+Alice 50 Alice 2 77
 
 # right join with join filter
-query TITI rowsort
+query TITII rowsort
 SELECT * FROM t1 RIGHT JOIN t2 ON t1.a = t2.a AND t2.b * 50 <= t1.b
 ----
-Alice 100 Alice 1
-Alice 100 Alice 2
-Alice 50 Alice 1
+Alice 100 Alice 1 66
+Alice 100 Alice 2 77
+Alice 50 Alice 1 66
 
-query TITI rowsort
+query TITII rowsort
 SELECT * FROM t1 RIGHT JOIN t2 ON t1.a = t2.a AND t1.b > t2.b
 ----
-Alice 100 Alice 1
-Alice 100 Alice 2
-Alice 50 Alice 1
-Alice 50 Alice 2
+Alice 100 Alice 1 66
+Alice 100 Alice 2 77
+Alice 50 Alice 1 66
+Alice 50 Alice 2 77
 
 # full join without join filter
-query TITI rowsort
+query TITII rowsort
 SELECT * FROM t1 FULL JOIN t2 ON t1.a = t2.a
 ----
-Alice 100 Alice 1
-Alice 100 Alice 2
-Alice 50 Alice 1
-Alice 50 Alice 2
-Bob 1 NULL NULL
+Alice 100 Alice 1 66
+Alice 100 Alice 2 77
+Alice 50 Alice 1 66
+Alice 50 Alice 2 77
+Bob 1 NULL NULL NULL
 
-query TITI rowsort
+query TITII rowsort
 SELECT * FROM t1 FULL JOIN t2 ON t1.a = t2.a AND t2.b * 50 > t1.b
 ----
-Alice 100 NULL NULL
-Alice 50 Alice 2
-Bob 1 NULL NULL
-NULL NULL Alice 1
+Alice 100 NULL NULL NULL
+Alice 50 Alice 2 77
+Bob 1 NULL NULL NULL
+NULL NULL Alice 1 66
 
-query TITI rowsort
+query TITII rowsort
 SELECT * FROM t1 FULL JOIN t2 ON t1.a = t2.a AND t1.b > t2.b + 50
 ----
-Alice 100 Alice 1
-Alice 100 Alice 2
-Alice 50 NULL NULL
-Bob 1 NULL NULL
+Alice 100 Alice 1 66
+Alice 100 Alice 2 77
+Alice 50 NULL NULL NULL
+Bob 1 NULL NULL NULL
 
 statement ok
 DROP TABLE t1;
```

</details>

**Comment by tglanz** [comment]
Thanks @rluvaton, Sure

**Comment by tglanz** [comment]
Fuzz tests are taken from @rluvaton 's #18788 , excluding those this PR doesn't fix:

```
    fuzz_cases::join_fuzz::test_right_anti_join_1k_binary_filtered
    fuzz_cases::join_fuzz::test_right_anti_join_1k_filtered
    fuzz_cases::join_fuzz::test_right_semi_join_1k_filtered
```

**Review by rluvaton — APPROVED** [review]
Thank you @tglanz LGTM.

Hope to see you contributing again soon
