### PR TITLE
fix dml logical plan output schema

### LINKED ISSUE #10393: For DML plans, `LogicalPlan::schema` returns the input schema instead of output schema
This inconsistency would typically go unnoticed, unless you call `.schema()` on a DML logical plan.

Fixed in https://github.com/apache/datafusion/pull/10394

### PR DESCRIPTION
**Pull request by leoyvens**
Previously, `LogicalPlan::schema` would return the input schema for DML plans, rather than the expected output schema. It is typical for the output to be the `count` of rows affected by the DML statement, so the code assumes that.

See `fn dml_output_schema` for a test.

## Which issue does this PR close?

Closes #10393.

## Rationale for this change
Current behaviour is wrong.

## Are these changes tested?
Yes there is a test `fn dml_output_schema`.

## Are there any user-facing changes?
The bug being fixed is visible to users of the DataFrame API.

### CODE REVIEW

**Review by comphead — COMMENTED** [review]
Thanks @leoyvens for your contribution, please add more details to the issue description

File: datafusion/core/tests/sql/sql_api.rs [hunk 1]
```diff
@@ -58,6 +58,19 @@ async fn unsupported_dml_returns_error() {
     ctx.sql_with_options(sql, options).await.unwrap();
 }
 
+#[tokio::test]
```
Comment (comphead) [inline datafusion/core/tests/sql/sql_api.rs:61]: its better to have this test in one of `.slt` files which runs end to end tests

File: datafusion/expr/src/logical_plan/dml.rs [hunk 2]
```diff
@@ -70,9 +71,28 @@ pub struct DmlStatement {
     pub op: WriteOp,
     /// The relation that determines the tuples to add/remove/modify the schema must match with table_schema
     pub input: Arc<LogicalPlan>,
+    /// The schema of the output relation
+    pub output_schema: DFSchemaRef,
 }
 
 impl DmlStatement {
+    pub fn new(
```
Comment (comphead) [inline datafusion/expr/src/logical_plan/dml.rs:79]: for the pub methods please add a proper description

**Comment by comphead** [comment]
I checked current behavior 

```
> CREATE TABLE test (x int)
;
0 row(s) fetched. 
Elapsed 0.017 seconds.

> INSERT INTO test VALUES (1);
+-------+
| count |
+-------+
| 1     |
+-------+
1 row(s) fetched. 
Elapsed 0.015 seconds.

> INSERT INTO test VALUES (3);
+-------+
| count |
+-------+
| 1     |
+-------+
1 row(s) fetched. 
Elapsed 0.005 seconds.

```

I'm not even sure why we output anything after DDL/DML... I'd probably prefer no output like in duckdb

```
D create table x (id int);
D insert into x values(1);
```

File: datafusion/core/tests/sql/sql_api.rs (hunk 1 above)
Comment (leoyvens) [reply datafusion/core/tests/sql/sql_api.rs:61]: I suspect this might not be caught in a `.slt` test as this issue is not visible in the pretty-printed logical plan, and doesn't affect the physical plan or execution at all, afaict.

Comment (leoyvens) [reply datafusion/core/tests/sql/sql_api.rs:61]: Actually I see some slt tests failing on CI, I should look into that.

Comment (leoyvens) [reply datafusion/core/tests/sql/sql_api.rs:61]: Curiously, this was in fact tested in many sqllogictests. Because the tests do in fact cover checking that the physical output schema matches the logical output schema, which is pretty cool.

Let me know if you want to keep this Rust test as well, or if you rather that I remove it. It does test more behaviour than what the slts can test.

**Comment by leoyvens** [comment]
@comphead Thank you for your review, I have addressed the outstanding comments. I have no opinion on desired behaviour, this PR is just trying to make things consistent.

File: datafusion/sqllogictest/test_files/insert.slt [hunk 3]
```diff
@@ -259,7 +259,7 @@ statement error Error during planning: Column count doesn't match insert query!
 insert into table_without_values(id) values(4, 'zoo');
 
 # insert NULL values for the missing column (name)
-query IT
+query I
```
Comment (comphead) [inline datafusion/sqllogictest/test_files/insert.slt:262]: does it fail with old value?

File: datafusion/core/tests/sql/sql_api.rs (hunk 1 above)
Comment (alamb) [reply datafusion/core/tests/sql/sql_api.rs:61]: I think keeping the rust level test is a good idea as it makes explicit the expected output schema

File: datafusion/sqllogictest/test_files/aggregate.slt [hunk 4]
```diff
@@ -3260,7 +3260,7 @@ SELECT STRING_AGG(column1, '|') FROM (values (''), (null), (''));
 statement ok
 CREATE TABLE strings(g INTEGER, x VARCHAR, y VARCHAR)
 
-query ITT
+query I
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/aggregate.slt:3263]: 👍

**Review by alamb — APPROVED** [review]
Thank you @leoyvens  and @comphead  -- this is a very nice contribution 🏆
