### PR TITLE
Change `flatten` so it does only a level, not recursively

### LINKED ISSUE #13757: `flatten` should be single-step, not recursive
### Describe the bug

per https://github.com/apache/datafusion/pull/13706 the list functions are modeled after DuckDB[^1]

per  https://duckdb.org/docs/sql/functions/list.html#flattenlist_of_lists, `flatten` should flatten one level, not recursive

[^1]: i would prefer a more established point of reference with close alignment to the SQL standard, but this issue is not about this

### To Reproduce

```
query ???
select flatten(arrow_cast(make_array([[1.1]], [[2.2]], [[3.3], [4.4]]), 'LargeList(LargeList(LargeList(Float64)))'));
----
[1.1, 2.2, 3.3, 4.4]
```

### Expected behavior

```
query ???
select flatten(arrow_cast(make_array([[1.1]], [[2.2]], [[3.3], [4.4]]), 'LargeList(LargeList(LargeList(Float64)))'));
----
[[1.1], [2.2], [3.3], [4.4]]
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by delamarch3**
## Which issue does this PR close?

- Closes #13757

## Rationale for this change
Parity with the `flatten` implementation in duckdb.

## What changes are included in this PR?

Remove the recursion in `flatten_internal` so that only the top level elements are flattened.

## Are these changes tested?

Existing sqllogictests have been updated.

## Are there any user-facing changes?
Yes, `flatten` no longer recursively flattens the array

### CODE REVIEW

File: datafusion/functions-nested/src/flatten.rs [hunk 1]
```diff
@@ -102,25 +101,21 @@ impl ScalarUDFImpl for Flatten {
...
-                ),
-            }
-        }
+        let data_type = match &arg_types[0] {
+            List(field) | FixedSizeList(field, _) => match field.data_type() {
+                List(field) | FixedSizeList(field, _) => List(Arc::clone(field)),
+                _ => arg_types[0].clone(),
+            },
+            LargeList(field) => match field.data_type() {
+                LargeList(field) => LargeList(Arc::clone(field)),
```
Comment (Weijun-H) [inline datafusion/functions-nested/src/flatten.rs:110]:
```suggestion
                List(field) | FixedSizeList(field, _) | LargeList(field) => {
                    LargeList(Arc::clone(field))
                }
```

File: datafusion/functions-nested/src/flatten.rs [hunk 2]
```diff
@@ -77,7 +77,6 @@ impl Flatten {
     pub fn new() -> Self {
         Self {
             signature: Signature {
-                // TODO (https://github.com/apache/datafusion/issues/13757) flatten should be single-step, not recursive
                 type_signature: TypeSignature::ArraySignature(
                     ArrayFunctionSignature::RecursiveArray,
```
Comment (findepi) [inline datafusion/functions-nested/src/flatten.rs:81]: Is this signature still applicable?

Maybe we should switch to Array, and mark RecursiveArray as deprecated?

**Comment by cht42** [comment]
Hey @delamarch3 are you still tracking merging this ? interested in this new behavior

**Comment by delamarch3** [comment]
Hi @cht42, I'm just waiting for another review.

@findepi could you take another look at this when you get the chance please?

**Comment by cht42** [comment]
Maybe @alamb or @Weijun-H can review ?

**Review by Weijun-H — APPROVED** [review]
Thanks @delamarch3 👍  , I think the pr looks good. Waiting for other comments.

File: datafusion/functions-nested/src/flatten.rs [hunk 3]
```diff
@@ -146,14 +145,61 @@ pub fn flatten_inner(args: &[ArrayRef]) -> Result<ArrayRef> {
...
+                        inner_field,
+                        offsets,
+                        inner_values,
+                        None,
+                    );
+
+                    Ok(Arc::new(flattened_array) as ArrayRef)
+                }
+                LargeList(_) => {
+                    let (inner_field, inner_offsets, inner_values, _) =
```
Comment (cht42) [inline datafusion/functions-nested/src/flatten.rs:189]:
```suggestion
                    let (inner_field, inner_offsets, inner_values, nulls) =
```

File: datafusion/functions-nested/src/flatten.rs [hunk 4]
```diff
@@ -146,14 +145,61 @@ pub fn flatten_inner(args: &[ArrayRef]) -> Result<ArrayRef> {
...
+                        as_large_list_array(&values)?.clone().into_parts();
+                    let offsets = get_offsets_for_flatten::<i64>(inner_offsets, offsets);
+                    let flattened_array = GenericListArray::<i64>::new(
+                        inner_field,
+                        offsets,
+                        inner_values,
+                        None,
```
Comment (cht42) [inline datafusion/functions-nested/src/flatten.rs:196]:
```suggestion
                        nulls,
```

**Review by cht42 — COMMENTED** [review]
Hey, noticed that null handling is not managed properly in the current implementation. Might as well fix it here directly

**Comment by delamarch3** [comment]
Thanks for the reviews!

**Comment by cht42** [comment]
@alamb can we get this merged please ?
