### PR TITLE
fix(substrait): Do not add implicit groupBy expressions in `LogicalPlanBuilder` or when building logical plans from Substrait

### LINKED ISSUE #14348: [substrait] Synthetically added grouping expressions in Aggregates can cause mismatched output columns
### Describe the bug

In https://github.com/apache/datafusion/pull/8356, support was added so that functionally dependent expressions on unique columns can also be available for output. This was achieved by synthetically adding said expressions as additional grouping expressions in the logical plan builder.

However, in Substrait plans, we use pre-defined, ordinal-based field references. These ordinals are indexes into the combined input + output expressions. By increasing the number of expressions in the input, you can expect that these ordinals will point to new, unexpected expressions -- thus altering the final output.

Given a sample plan without the added grouping:
Image

The sample plan with the added grouping produces something semantically different:
Image

### To Reproduce

Create a new test file in `datafusion/substrait/tests/testdata/test_plans/multi_layer_aggregation.substrait.json` with the following Substrait JSON:

```
{
  "extensionUris": [{
    "extensionUriAnchor": 1,
    "uri": "/functions_aggregate_generic.yaml"
  }, {
    "extensionUriAnchor": 2,
    "uri": "/functions_arithmetic.yaml"
  }, {
    "extensionUriAnchor": 3,
    "uri": "/functions_string.yaml"
  }],
  "extensions": [{
    "extensionFunction": {
      "extensionUriReference": 1,
      "functionAnchor": 0,
      "name": "count:any"
    }
  }, {
    "extensionFunction": {
      "extensionUriReference": 2,
      "functionAnchor": 1,
      "name": "sum:i64"
    }
  }, {
    "extensionFunction": {
      "extensionUriReference": 3,
      "functionAnchor": 2,
      "name": "lower:str"
    }
  }],
  "relations": [{
    "root": {
      "input": {
        "project": {
          "common": {
            "emit": {
              "outputMapping": [2, 3]
            }
          },
          "input": {
            "aggregate": {
              "common": {
                "direct": {
                }
              },
              "input": {
                "aggregate": {
                  "common": {
                    "direct": {
                    }
                  },
                  "input": {
                    "read": {
                      "common": {
                        "direct": {}
                      },
                      "baseSchema": {
                        "names": [
                          "product"
                        ],
                        "struct": {
                          "types": [
                            {
                              "string": {
                                "nullability": "NULLABILITY_REQUIRED"
                              }
                            }
                          ],
                          "nullability": "NULLABILITY_REQUIRED"
                        }
                      },
                      "namedTable": {
                        "names": [
                          "sales"
                        ]
                      }
                    }
                  },
                  "groupings": [{
                    "groupingExpressions": [{
                      "selection": {
                        "directReference": {
                          "structField": {
                            "field": 0
                          }
                        },
                        "rootReference": {
                        }
                      }
                    }],
                    "expressionReferences": []
                  }],
                  "measures": [{
                    "measure": {
                      "functionReference": 0,
                      "args": [],
                      "sorts": [],
                      "phase": "AGGREGATION_PHASE_INITIAL_TO_RESULT",
                      "outputType": {
                        "i64": {
                          "typeVariationReference": 0,
                          "nullability": "NULLABILITY_REQUIRED"
                        }
                      },
                      "invocation": "AGGREGATION_INVOCATION_ALL",
                      "arguments": [{
                        "value": {
                          "selection": {
                            "directReference": {
                              "structField": {
                                "field": 0
                              }
                            },
                            "rootReference": {
                            }
                          }
                        }
                      }],
                      "options": []
                    }
                  }],
                  "groupingExpressions": []
                }
              },
              "groupings": [{
                "groupingExpressions": [{
                  "selection": {
                    "directReference": {
                      "structField": {
                        "field": 0
                      }
                    },
                    "rootReference": {
                    }
                  }
                }],
                "expressionReferences": []
              }],
              "measures": [{
                "measure": {
                  "functionReference": 1,
                  "args": [],
                  "sorts": [],
                  "phase": "AGGREGATION_PHASE_INITIAL_TO_RESULT",
                  "outputType": {
                    "i64": {
                      "typeVariationReference": 0,
                      "nullability": "NULLABILITY_NULLABLE"
                    }
                  },
                  "invocation": "AGGREGATION_INVOCATION_ALL",
                  "arguments": [{
                    "value": {
                      "selection": {
                        "directReference": {
                          "structField": {
                            "field": 1
                          }
                        },
                        "rootReference": {
                        }
                      }
                    }
                  }],
                  "options": []
                }
              }],
              "groupingExpressions": []
            }
          },
          "expressions": [{
            "scalarFunction": {
              "functionReference": 2,
              "args": [],
              "outputType": {
                "string": {
                  "typeVariationReference": 0,
                  "nullability": "NULLABILITY_NULLABLE"
                }
              },
              "arguments": [{
                "value": {
                  "selection": {
                    "directReference": {
                      "structField": {
                        "field": 0
                      }
                    },
                    "rootReference": {
                    }
                  }
                }
              }],
              "options": []
            }
          }, {
            "selection": {
              "directReference": {
                "structField": {
                  "field": 1
                }
              },
              "rootReference": {
              }
            }
          }]
        }
      },
      "names": ["lower(product)", "product_count"]
    }
  }],
  "expectedTypeUrls": []
}
```

Note: this was generated from a SQL query of the form:
```
SELECT lower(product), sum(count) as product_count FROM (
    SELECT product, count(product) as count
    FROM sales
    GROUP BY product
)
GROUP BY product;
```

Add a test in `datafusion/substrait/tests/cases/logical_plans.rs`:

```
#[tokio::test]
async fn multi_layer_aggregation() -> Result<()> {
    let proto_plan =
        read_json("tests/testdata/test_plans/multi_layer_aggregation.substrait.json");
    let ctx = add_plan_schemas_to_ctx(SessionContext::new(), &proto_plan)?;
    let plan = from_substrait_plan(&ctx.state(), &proto_plan).await?;

    assert_eq!(
        format!("{}", plan),
        "Projection: lower(sales.product) as lower(product), sum(count(sales.product)) as product_count\
        \n  Aggregate: groupBy=[[sales.product]], aggr=[[sum(count(sales.product))]]\
        \n    Aggregate: groupBy=[[sales.product]], aggr=[[count(sales.product)]]\
        \n      TableScan: sales"
    );

    Ok(())
}
```

Test should succeed. But instead will fail with:
```
assertion `left == right` failed

left: 
"Projection: sum(count(sales.product)) AS lower(product), lower(sales.product) AS product_count
    Aggregate: groupBy=[[sales.product, count(sales.product)]], aggr=[[sum(count(sales.product))]]
      Aggregate: groupBy=[[sales.product]], aggr=[[count(sales.product)]]
         TableScan: sales"

right: 
"Projection: lower(sales.product) as lower(product), sum(count(sales.product)) as product_count
    Aggregate: groupBy=[[sales.product]], aggr=[[sum(count(sales.product))]]
      Aggregate: groupBy=[[sales.product]], aggr=[[count(sales.product)]]
        TableScan: sales"
```

### Expected behavior

The translated LogicalPlan must preserve the semantics of the Substrait plan.

Not trying to prescribe a particular solution here. There may be a few possible approaches:
* If we introduce new expression(s), we must produce a new remapping that takes into account the added expression(s).
* The Substrait -> LogicalPlan translation layer should never modify the original intent of the plan. In other words, maybe in this particular scenario, the additional grouping should not be introduced by the Substrait consumer. Instead, allow the Substrait producer to be responsible for introducing the extra grouping if the same PK Aggregate feature is desired.
* For this particular query structure, another viable fix may be to not add functionally dependent expressions into the grouping set if they are never referenced or projected.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by anlinc**
## Which issue does this PR close?

Closes #14348 

## Rationale for this change

Substrait plans are intended to be interpreted literally. When you see plan nodes like:

```
"project": {
  "common": {
    "emit": {
      "outputMapping": [0, 3]
    }
  },
...
}
```
The output mapping (e.g. `[0, 3]`) contains ordinals representing the offset of the target expression(s) within the [input, output] list. If the DataFusion LogicalPlanBuilder is introducing additional input expressions, this violates the plan's intent and will produce the incorrect output mappings. Please see the issue for a concrete example.

## What changes are included in this PR?

* Introduce new `add_implicit_group_by_exprs` option to the logical plan builder. It is disabled by default.
   * The option is enabled _only_ in the DataFrame and SQL paths.

## Are these changes tested?

Added a multilayer aggregation Substrait example. The first aggregation produces a unique column with a functional dependency. Despite this, the second aggregation must not introduce any additional grouping expressions.

There should be no changes in the non-Substrait paths.

## Are there any user-facing changes?
No.

## Appendix
This is a continuation of https://github.com/apache/datafusion/pull/14553.

### CODE REVIEW

File: datafusion/expr/src/logical_plan/builder.rs [hunk 1]
```diff
@@ -63,6 +64,32 @@ use indexmap::IndexSet;
...
+        }
+    }
+}
+
+impl LogicalPlanBuilderOptions {
+    pub fn new() -> Self {
+        Default::default()
+    }
+
+    pub fn with_add_implicit_group_by_exprs(mut self, add: bool) -> Self {
```
Comment (alamb) [inline datafusion/expr/src/logical_plan/builder.rs:87]:
```suggestion
    /// Should the builder add functionally dependent expressions as additional aggregation groupings.
    pub fn with_add_implicit_group_by_exprs(mut self, add: bool) -> Self {
```

File: datafusion/expr/src/logical_plan/builder.rs [hunk 2]
```diff
@@ -63,6 +64,32 @@ use indexmap::IndexSet;
 /// Default table name for unnamed table
 pub const UNNAMED_TABLE: &str = "?table?";
 
+#[derive(Debug, Clone)]
```
Comment (alamb) [inline datafusion/expr/src/logical_plan/builder.rs:67]:
```suggestion
/// Options for [`LogicalPlanBuilder`]
#[derive(Debug, Clone)]
```

**Review by alamb — APPROVED** [review]
Thank you @anlinc 

I think this looks great to me

cc @Blizzara @vbarua

**Comment by alamb** [comment]
Hi @anlinc  

It looks like there is a small clippy failure with this PR:

https://github.com/apache/datafusion/actions/runs/13507870042/job/37742937287?pr=14860

File: datafusion/expr/src/logical_plan/builder.rs [hunk 3]
```diff
@@ -63,6 +63,26 @@ use indexmap::IndexSet;
 /// Default table name for unnamed table
 pub const UNNAMED_TABLE: &str = "?table?";
 
+/// Options for [`LogicalPlanBuilder`]
+#[derive(Default, Debug, Clone)]
+pub struct LogicalPlanBuilderOptions {
+    /// Flag indicating whether the plan builder should add
+    /// functionally dependent expressions as additional aggregation groupings.
+    add_implicit_group_by_exprs: bool,
```
Comment (Blizzara) [inline datafusion/expr/src/logical_plan/builder.rs:71]: Is the default now `false`? That's a breaking change I guess? Is that fine, or should we make the default be `true` to maintain earlier behavior?

File: datafusion/substrait/tests/cases/roundtrip_logical_plan.rs [hunk 4]
```diff
@@ -308,6 +308,17 @@ async fn aggregate_grouping_rollup() -> Result<()> {
     ).await
 }
 
+#[tokio::test]
+async fn multilayer_aggregate() -> Result<()> {
+    assert_expected_plan(
+        "SELECT a, sum(partial_count_b) FROM (SELECT a, count(b) as partial_count_b FROM data GROUP BY a) GROUP BY a",
```
Comment (Blizzara) [inline datafusion/substrait/tests/cases/roundtrip_logical_plan.rs:314]: I'm still a bit confused by this. Why does the original plan created from SQL already contain the implicit groupBy's here?

File: datafusion/expr/src/logical_plan/builder.rs (hunk 3 above)
Comment (anlinc) [reply datafusion/expr/src/logical_plan/builder.rs:71]: Yes, the default is now `false`. 

My intuition was that this made the most sense as I'd prefer a composable base builder that suits all needs, that allows opt-ins to advanced features and optimizations.

File: datafusion/substrait/tests/cases/roundtrip_logical_plan.rs (hunk 4 above)
Comment (anlinc) [reply datafusion/substrait/tests/cases/roundtrip_logical_plan.rs:314]: This test goes SQL -> Logical Plan ->  Substrait Plan -> Logical Plan.

There were no additional groupBys added between `SQL -> Logical Plan ->  Substrait Plan`.

(Prior to this PR) Additional groupBys were added between `Substrait Plan -> Logical Plan`, violating the round trip plan expectations.

File: datafusion/expr/src/logical_plan/builder.rs (hunk 3 above)
Comment (vbarua) [reply datafusion/expr/src/logical_plan/builder.rs:71]: I lean towards having the default behaviour be `false` for this, even if it's a breaking change, because it makes the builder less surprising IMO. Specifically, when invoking the builder for an aggregate with a specific set of grouping expressions, my expectation is that it should produce an aggregate with those specific grouping expressions. If I wanted additional grouping expressions, I would have included them.

There's definitely room and value for optimizations like what is going on here, but I think those need to be opt-in to avoid situation like this were the plan builder tries to be smart along one specific axis and inadvertently shoots you in the foot in another. In the past, I think we've leaned towards having the builder be as straightforward as possible and then handling optimizations in the optimizer.

**Review by vbarua — APPROVED** [review]
Changes look good to me overall. Thanks for working on this @anlinc

File: datafusion/expr/src/logical_plan/builder.rs (hunk 3 above)
Comment (alamb) [reply datafusion/expr/src/logical_plan/builder.rs:71]: I agree it would be less surprising, but I think we should consider it in a follow on PR. This PR fixes the issue with substrait and is a good change on its own. I have filed a follow on ticket to track the idea:
- https://github.com/apache/datafusion/issues/14878

**Comment by alamb** [comment]
Thanks @anlinc  and @Blizzara and @vbarua  for the reviews
