### PR TITLE
fix: Unaccounted spill sort in row_hash

### LINKED ISSUE #20313: Unaccounted sort in row_hash
### Describe the bug

In row_hash.rs, there is a (potentially) massive unaccounted sort in the spill() function
We never verify that we have this memory to perform this sort, which for something like a 1GB batch - which is very much a possibility, as we've run out of memory and are therefor spilling - will peak at about 2GB of memory usage.
This can easily spiral out of control and end up with the operating system killing the process.

### To Reproduce

Create a single Complete/Final AggregateExec.
Provide a 1GB memory pool.
Provide Data whose aggregate expressions will output > 1GB.
You'll reach a spill, data will be sorted using sort_batch, causing a peak of > 2GB while both the input and output batches are alive.

### Expected behavior

Ideally, checking if we can reserve memory for such a spill, if so, do it.
If not, fallback to a lazy sorting stream that will only take batch_size at a time, causing longer memory holding of the original batch but lower peak.

For now: erroring if the memory is unavailable.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by EmilyMatt**
## Which issue does this PR close?

- Closes #20313 .

## Rationale for this change

We must not use that much memory without reserving it.

## What changes are included in this PR?

Added a reservation before the sort, made a shrink call for the group values after the emit and updated the reservation so the reservation will be possible.

Moved the sort to use sort_chunked so we can immediately drop the original batch and shrink the reservation to the used sizes, added a new spill method for iterators, so we can use an accurate memory accounting.

If said reservation did not succeed, fallback to an incrementing sort method which holds the original batch the whole time, and outputs one batch at the time, this requires a much smaller reservation.
Made the reservation much more robust(otherwise the fuzz tests were failing now that we actually reserve the memory in the sort)

## Are these changes tested?

Current tests should still function, but memory should be reserved.
Added test that specifically verifies that we error on this when we shouldn't do the sort.
Modified the tests that used to test the splitting function in the spill to test the new iter spilling function

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/physical-plan/src/sorts/stream.rs [hunk 1]
```diff
@@ -276,3 +280,105 @@ impl<T: CursorArray> PartitionedStream for FieldCursorStream<T> {
...
+/// spill when there is not enough memory for an eager sort (which requires ~2x
+/// peak memory to hold both the unsorted and sorted copies simultaneously).
+///
+/// On the first call to `next()`, a sorted index array (`UInt32Array`) is
+/// computed via `lexsort_to_indices`. Subsequent calls yield chunks of
+/// `batch_size` rows by `take`-ing from the original batch using slices of
+/// this index array. Each `take` copies data for the chunk (not zero-copy),
+/// but only one chunk is live at a time since the caller consumes it before
+/// requesting the next. Once all rows have been yielded, the original batch
+/// and index array are dropped to free memory.
```
Comment (rluvaton) [inline datafusion/physical-plan/src/sorts/stream.rs:294]: `take` explicitly note that it will try to avoid allocation when not necessary, although current implementation may allocate when `slice` would have being possible, it is not guaranteed, and due to the fact that you rely on `take` to not do zero copy, please add a test to make sure that the memory is reduced after each call to `next` (which if `take` implementation no longer do deep copy this test will fail):
> ```
> /// Note that this kernel, similar to other kernels in this crate,
> /// will avoid allocating where not necessary. Consequently
> /// the returned array may share buffers with the inputs
> ```
https://github.com/apache/arrow-rs/blob/3a019d0104668146c44c9da4dca0c5aed0a5324c/arrow-select/src/take.rs#L55-L57

File: datafusion/physical-plan/src/sorts/sort.rs [hunk 2]
```diff
@@ -850,11 +850,13 @@ pub(crate) fn get_reserved_bytes_for_record_batch_size(
...
-        batch.get_sliced_size()?,
-    ))
+pub(crate) fn get_reserved_bytes_for_record_batch(batch: &RecordBatch) -> Result<usize> {
+    batch.get_sliced_size().map(|sliced_size| {
+        get_reserved_bytes_for_record_batch_size(
+            get_record_batch_memory_size(batch),
+            sliced_size,
+        )
+    })
 }
```
Comment (rluvaton) [inline datafusion/physical-plan/src/sorts/sort.rs:861]: Seems like only the visibility was meant to be changed, could you please revert the rest of the changes?

Comment (EmilyMatt) [reply datafusion/physical-plan/src/sorts/sort.rs:861]: I believe this is preferable

File: datafusion/physical-plan/src/sorts/stream.rs (hunk 1 above)
Comment (EmilyMatt) [reply datafusion/physical-plan/src/sorts/stream.rs:294]: afaik slice() will only be used for NullArray, I think the comment is anachronistic.
Regardless, added a test

File: datafusion/physical-plan/src/aggregates/row_hash.rs [hunk 3]
```diff
@@ -1110,17 +1129,85 @@ impl GroupedHashAggregateStream {
...
+                        sorted_iter,
+                        "HashAggSpill",
+                    )?;
+
+                // Shrink the memory we allocated for sorting as the sorting is fully done at this point.
+                self.reservation.shrink(sort_memory);
+
+                spillfile
+            }
+        };
```
Comment (rluvaton) [inline datafusion/physical-plan/src/aggregates/row_hash.rs]: `sort_batch_chunked` seems to be the same as `IncrementalSortIterator`  but only do collect in the end.
I would only have `IncrementalSortIterator` as I don't see a benefit of having the `sort_batch_chunked` branch and it will simplify the code

File: datafusion/physical-plan/src/sorts/stream.rs [hunk 4]
```diff
@@ -276,3 +280,166 @@ impl<T: CursorArray> PartitionedStream for FieldCursorStream<T> {
...
+    /// underlying buffer length would match the original array's length; a true
+    /// copy will have a buffer sized to fit only the chunk.
+    #[test]
+    fn incremental_sort_iterator_copies_data() -> Result<()> {
+        let original_len = 10;
+        let batch_size = 3;
+
+        // Build a batch with a single Int32 column of descending values
+        let schema = Arc::new(Schema::new(vec![Field::new("a", DataType::Int32, false)]));
+        let col_a: Int32Array = (0..original_len as i32).rev().collect();
```
Comment (rluvaton) [inline datafusion/physical-plan/src/sorts/stream.rs]: I would do the entire array the same so the data is sorted no matter the default sort expr

File: datafusion/physical-plan/src/sorts/stream.rs [hunk 5]
```diff
@@ -276,3 +280,166 @@ impl<T: CursorArray> PartitionedStream for FieldCursorStream<T> {
...
+                        chunk.num_rows(),
+                        "array len should equal chunk row count"
+                    );
+                    assert_ne!(
+                        arr.len(),
+                        original_len,
+                        "array len must differ from original batch length \
+                     (data should be copied, not sliced)"
+                    );
+                });
```
Comment (rluvaton) [inline datafusion/physical-plan/src/sorts/stream.rs:429]: This doesn't test that the underlying data was freed, you should check the underlying buffer pointer

File: datafusion/physical-plan/src/sorts/stream.rs [hunk 6]
```diff
@@ -276,3 +280,159 @@ impl<T: CursorArray> PartitionedStream for FieldCursorStream<T> {
...
+                let chunk = result?;
+                total_rows += chunk.num_rows();
+
+                // Every output column must be a fresh allocation whose length
+                // equals the chunk size, NOT the original array length.
+                chunk.columns().iter().zip(batch.columns()).for_each(|(arr, original_arr)| {
+                    let (_, scalar_buf, _) = arr.as_primitive::<Int32Type>().clone().into_parts();
+                    let (_, original_scalar_buf, _) = original_arr.as_primitive::<Int32Type>().clone().into_parts();
+
+                    assert!(!scalar_buf.inner().ptr_eq(original_scalar_buf.inner()), "Expected a copy of the data for each chunk, but got a slice that shares the same buffer as the original array");
```
Comment (rluvaton) [inline datafusion/physical-plan/src/sorts/stream.rs]: `ptr_eq` will give false for sliced, it should use `data_ptr` for the underlying data

File: datafusion/physical-plan/src/sorts/stream.rs [hunk 7]
```diff
@@ -276,3 +280,159 @@ impl<T: CursorArray> PartitionedStream for FieldCursorStream<T> {
...
+/// computed via `lexsort_to_indices`. Subsequent calls yield chunks of
+/// `batch_size` rows by `take`-ing from the original batch using slices of
+/// this index array. Each `take` copies data for the chunk (not zero-copy),
+/// but only one chunk is live at a time since the caller consumes it before
+/// requesting the next. Once all rows have been yielded, the original batch
+/// and index array are dropped to free memory.
+///
+/// The caller must reserve `sizeof(batch) + sizeof(one chunk)` for this iterator,
+/// and free the reservation once the iterator is depleted.
+pub(crate) struct IncrementalSortIterator {
```
Comment (rluvaton) [inline datafusion/physical-plan/src/sorts/stream.rs:298]: since `sort_batch_chunked` does the same thing but return `Vec<RecordBatch>` I would update it to use this iterator
