### PR TITLE
fix: Optimize `!~ '.*'` case to `col IS NULL AND Boolean(NULL)` instead of `Eq ""`

### LINKED ISSUE #20701: bug: regexp simplify optimization incorrect simplifies `.*` pattern to `Eq ""` operation
### Describe the bug

see PR

### To Reproduce

```sql
WITH t(col) AS (
    VALUES
      ('foo'::text),
      (''::text),
      (NULL::text)
  )
  SELECT
    col,
    col !~ '.*' AS not_match_dot_star
  FROM t;
```

Current output

```sql
DataFusion CLI v52.1.0
> WITH t(col) AS (
    VALUES
      ('foo'::text),
      (''::text),
      (NULL::text)
  )
  SELECT
    col,
    col !~ '.*' AS not_match_dot_star
  FROM t;
+------+--------------------+
| col  | not_match_dot_star |
+------+--------------------+
| foo  | false              |
|      | true               |
| NULL | NULL               |
+------+--------------------+
3 row(s) fetched.
Elapsed 0.038 seconds.
```

### Expected behavior

Output should be like postgres. Specifically

```sql
+------+-----------------+
| a    | baseline_result |
+------+-----------------+
| foo  | false           |
|      | false           |
| NULL | NULL            |
+------+-----------------+
```

Here is postgres repro

```sql
psql (14.21 (Homebrew), server 11.16 (Debian 11.16-1.pgdg90+1))
Type "help" for help.

postgres=#   WITH t(col) AS (
    VALUES
      ('foo'::text),
      (''::text),
      (NULL::text)
  )
  SELECT
    col,
    col !~ '.*' AS not_match_dot_star
  FROM t;
 col | not_match_dot_star
-----+--------------------
 foo | f
     | f
     |
(3 rows)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by petern48**
## Which issue does this PR close?

- Closes #20701

## What changes are included in this PR?

A pre-existing optimization rule for the `!~ .*` (regexp not match) case rewrote the plan to `Eq ""`, which would return empty strings as part of the result. This is incorrect and doesn't match the output without the optimization rule.

Instead, this PR rewrites the plan to simply `col IS NULL AND Boolean(NULL)` or, in other words, "NULL if col is NULL else false."

I've confirmed this behavior matches the result of running queries manually with the optimization rule turned off.

## Are these changes tested?

Fixed expected output in tests. Added new tests for nulls

## Are there any user-facing changes?

Yes, a minor bug fix. When querying `s !~ .*`, empty strings will no longer be included in the result which is consistent with the behavior without the optimization rule.

### CODE REVIEW

File: datafusion/optimizer/src/simplify_expressions/regex.rs [hunk 1]
```diff
@@ -39,7 +39,7 @@ const ANY_CHAR_REGEX_PATTERN: &str = ".*";
 /// - partial anchored regex patterns (e.g. `^foo`) to `LIKE 'foo%'`
 /// - combinations (alternatives) of the above, will be concatenated with `OR` or `AND`
 /// - `EQ .*` to NotNull
-/// - `NE .*` means IS EMPTY
+/// - `NE .*` to false (.* matches non-empty and empty strings, and NULL !~ '.*' results in NULL so this can never be true)
```
Comment (alamb) [inline datafusion/optimizer/src/simplify_expressions/regex.rs]: I think it is only false in the context of filters (and this code can currently be used for both filters and regular expressions)

I think `null !~ '.*'` is actually `null` (not `false`)

I think a correct rewrite is 
```sql
CASE 
  WHEN col IS NOT NULL THEN FALSE 
  ELSE NULL
END
```

File: datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs [hunk 2]
```diff
@@ -883,17 +883,17 @@ mod tests {
         "
         )?;
 
-        // Test `!= ".*"` transforms to checking if the column is empty
+        // Test `!~ ".*"` transforms to false
```
Comment (alamb) [inline datafusion/optimizer/src/simplify_expressions/simplify_exprs.rs]: can we please also add a test explicitly for a null input?

File: datafusion/optimizer/src/simplify_expressions/regex.rs (hunk 1 above)
Comment (petern48) [reply datafusion/optimizer/src/simplify_expressions/regex.rs]: ah thanks, i didn't realize this code applied to cases outside of filters. I've fixed it and updated the PR title and description.

note: the optimizer would further rewrite the `CASE` expr into `IS NOT NULL AND NULL` when I ran the tests, so I rewrote it directly to that instead

edit: should've been `IS NULL AND NULL` 😬

File: datafusion/optimizer/src/simplify_expressions/regex.rs [hunk 3]
```diff
@@ -68,12 +68,11 @@ pub fn simplify_regex_expr(
...
     if pattern == ANY_CHAR_REGEX_PATTERN {
         let new_expr = if mode.not {
-            // not empty
-            let empty_lit = Box::new(string_scalar.to_expr(""));
+            let null_bool = lit(ScalarValue::Boolean(None));
             Expr::BinaryExpr(BinaryExpr {
-                left,
-                op: Operator::Eq,
-                right: empty_lit,
+                left: Box::new(left.is_not_null()),
```
Comment (alamb) [inline datafusion/optimizer/src/simplify_expressions/regex.rs]: I think this case should be `is_null` rather than `is_not_null`

I think this because when  `left` is null, The expression `null !~ '.*'` should  also evaluate to `null`

However, as written (`col IS NOT NULL AND NULL`) will evaluate
```sql
col IS NOT NULL AND NULL
-->  FALSE AND NULL
-->  FALSE 
```

If the transformation is `col IS NULL AND NULL` 🤯  then:

```sql
col IS NULL AND NULL
-->  true AND NULL
-->  NULL 
```

As expected

File: datafusion/sqllogictest/test_files/simplify_expr.slt [hunk 4]
```diff
@@ -44,10 +44,10 @@ query TT
 explain select b from t where b !~ '.*'
 ----
 logical_plan
-01)Filter: t.b = Utf8View("")
+01)Filter: t.b IS NOT NULL AND Boolean(NULL)
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/simplify_expr.slt]: I think we should  add a test that actually executes `col !~ .*` for a column that has `'foo'`, `''`, and `null`

Specifically like this (the ::text is needed for postgres):

```sql
-- Reproducer for regex simplification of `col !~ '.*'`
-- Input values: 'foo', '', NULL

WITH t(col) AS (
    VALUES
      ('foo'::text),
      (''::text),
      (NULL::text)
  )
  SELECT
    col,
    col !~ '.*' AS not_match_dot_star
  FROM t;

```


Should result in 
```sql
+------+-----------------+
| a    | baseline_result |
+------+-----------------+
| foo  | false           |
|      | false           |
| NULL | NULL            |
+------+-----------------+
```

Here is what current datafusion does

```sql
andrewlamb@Andrews-MacBook-Pro-3:~/Software/datafusion2$ datafusion-cli
DataFusion CLI v52.1.0
> WITH t(col) AS (
    VALUES
      ('foo'::text),
      (''::text),
      (NULL::text)
  )
  SELECT
    col,
    col !~ '.*' AS not_match_dot_star
  FROM t;
+------+--------------------+
| col  | not_match_dot_star |
+------+--------------------+
| foo  | false              |
|      | true               |
| NULL | NULL               |
+------+--------------------+
3 row(s) fetched.
Elapsed 0.038 seconds.
```

Here is what postgres says

```sql
postgres=#   WITH t(col) AS (
    VALUES
      ('foo'::text),
      (''::text),
      (NULL::text)
  )
  SELECT
    col,
    col !~ '.*' AS not_match_dot_star
  FROM t;
 col | not_match_dot_star
-----+--------------------
 foo | f
     | f
     |
(3 rows)
```

I think this branch will not get the right value for `col IS NULL`

**Review by alamb — COMMENTED** [review]
Thank you @petern48

**Comment by alamb** [comment]
Thanks again for working on this @petern48  -- here is a proposed PR to fix the logic in this PR
- https://github.com/petern48/datafusion/pull/1

What do you think?

File: datafusion/optimizer/src/simplify_expressions/regex.rs (hunk 3 above)
Comment (petern48) [reply datafusion/optimizer/src/simplify_expressions/regex.rs]: Yes, definitely agree!

**Comment by petern48** [comment]
Appreciate the little bump to get this moving again. So sorry for the delay. I didn't mean to keep you waiting. I definitely agree with your suggestion. I was cramming for a deadline, and wanted to wait until I had more time to investigate something a bit further.

I vaguely remember just copy-pasting the `IS NOT NULL` part from the optimized output, so I had a small suspicion that the `CASE` statement was rewritten incorrectly to `IS NOT NULL`. Though I just manually checked it again, and it seems to optimize properly to `IS NULL`. Maybe I just wrote the case statement incorrectly, too 🤷. Anyway, lesson learned. I need to slow down a bit nowadays 🤦 , haha. Thanks for bearing with me.

**Comment by alamb** [comment]
No worries -- thank you so much for helping push this along (crazy corner cases are always tricky)
