### PR TITLE
test: allow external_access_plan run on windows

### LINKED ISSUE #13530: warning: variant `UTF8` is never constructed
### Describe the bug

When I run cargo clippy on my Windows machine, I get the following warning:

```text
warning: variant `UTF8` is never constructed
  --> datafusion\core\tests\parquet\mod.rs:89:5
   |
71 | enum Scenario {
   |      -------- variant in this enum
...
89 |     UTF8,
   |     ^^^^
   |
   = note: `Scenario` has derived impls for the traits `Clone` and `Debug`, but these are intentionally ignored during dead code analysis
   = note: `#[warn(dead_code)]` on by default
``` 

I get the same warning when triggering the [CI](https://github.com/apache/datafusion/actions/runs/11973258052/job/33381817585?pr=13315) task `cargo test (win64)` as well.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zhuliquan**
## Which issue does this PR close?

Closes #13530.

## Rationale for this change

I always receive this warning when running `cargo clippy`, and I would like to get rid of it.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
I suspect it is not used when not all features are activated 🤔

**Comment by alamb** [comment]
Thanks @zhuliquan  - it would also be really nice to figure out how you are running the code/tests to see this error. Maybe there is some better way we can come up with to fix it

**Comment by findepi** [comment]
we should really avoid `#[allow(dead_code)]` for stuff used only sometimes, because we won't know when this can be removed/

This is used in `external_access_plan`  which is disabled on windows.
Maybe we should try enabling it?

**Comment by zhuliquan** [comment]
> we should really avoid `#[allow(dead_code)]` for stuff used only sometimes, because we won't know when this can be removed/
> 
> This is used in `external_access_plan` which is disabled on windows. Maybe we should try enabling it?

Yeah, I enable it
```rust
let new_file_name = if cfg!(target_os = "windows") {
    // Windows path separator is different from Unix
    file_name.replace("\\", "/")
} else {
    file_name.clone()
};
```

**Comment by alamb** [comment]
🤔  the test now seems to be failing 

I wonder if it has to do with how the temp files are created 🤔

**Comment by zhuliquan** [comment]
> 🤔 the test now seems to be failing
> 
> I wonder if it has to do with how the temp files are created 🤔
 
I noticed that the char '%' appears in the directory, and the Windows system seems to be unable to find the file.

```
thread 'parquet::external_access_plan::two_selections' panicked at datafusion\core\tests\parquet\external_access_plan.rs:289:10:
called `Result::unwrap()` on an `Err` value: ParquetError(External(NotFound { path: "C:\\Users\\RUNNER%7E1\\AppData\\Local\\Temp\\user_access_planObCLIR.parquet", source: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." } }))

```

So I fix below code to avoid char '%'.

1. replacing '\\' to '/' when `target_os` is `windows`. 
https://github.com/apache/datafusion/blob/b65d2a3a770596bc33d90f11a908ae29065068bf/datafusion/core/tests/parquet/external_access_plan.rs#L323-L328
Because, `Path::new` will replace '\\' to '\\%5C' in `PartitionedFile::new`.
https://github.com/apache/datafusion/blob/b65d2a3a770596bc33d90f11a908ae29065068bf/datafusion/core/tests/parquet/external_access_plan.rs#L330
and
https://github.com/apache/datafusion/blob/b65d2a3a770596bc33d90f11a908ae29065068bf/datafusion/core/src/datasource/listing/mod.rs#L90-L93

2. using current dir as temp file dir (Because `temp` dir in CI is located at `C:\\Users\\RUNNER%7E1` and other loading parquet cases which are run ok on windows also use data in `../../parquet-testing/data`), and remove temp file at the end of the case run.
https://github.com/apache/datafusion/blob/b65d2a3a770596bc33d90f11a908ae29065068bf/datafusion/core/tests/parquet/external_access_plan.rs#L392
and
https://github.com/apache/datafusion/blob/b65d2a3a770596bc33d90f11a908ae29065068bf/datafusion/core/tests/parquet/external_access_plan.rs#L366

3. For sake of removing temp file at the end of each case run, I remove singleton mode of TestData in `get_test_data`
https://github.com/apache/datafusion/blob/b65d2a3a770596bc33d90f11a908ae29065068bf/datafusion/core/tests/parquet/external_access_plan.rs#L382-L419


5.

**Comment by zhuliquan** [comment]
> > > 🤔 the test now seems to be failing
> > > I wonder if it has to do with how the temp files are created 🤔
> > 
> > 
> > I suspect that the specific char '%7E' (i.e. '~') appears in the directory, and the Windows system seems to be unable to handle this.
> > ```
> > thread 'parquet::external_access_plan::two_selections' panicked at datafusion\core\tests\parquet\external_access_plan.rs:289:10:
> > called `Result::unwrap()` on an `Err` value: ParquetError(External(NotFound { path: "C:\\Users\\RUNNER%7E1\\AppData\\Local\\Temp\\user_access_planObCLIR.parquet", source: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." } }))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So I fix below code to avoid the specific char which begin with '%'.
> > 
> > 1. replacing '' to '/' when `target_os` is `windows`.
> >    https://github.com/apache/datafusion/blob/b65d2a3a770596bc33d90f11a908ae29065068bf/datafusion/core/tests/parquet/external_access_plan.rs#L323-L328
> >    
> >    Because, `Path::new` will replace '\' to '\%5C' (i.e. '\') in `PartitionedFile::new`.
> >    https://github.com/apache/datafusion/blob/b65d2a3a770596bc33d90f11a908ae29065068bf/datafusion/core/tests/parquet/external_access_plan.rs#L330
> >    
> >    and
> >    https://github.com/apache/datafusion/blob/b65d2a3a770596bc33d90f11a908ae29065068bf/datafusion/core/src/datasource/listing/mod.rs#L90-L93
> > 2. using current dir as temp file dir (Because `temp` dir in CI is located at `C:\\Users\\RUNNER%7E1` and other loading parquet cases which are run ok on windows also use data in `../../parquet-testing/data`), and remove temp file at the end of the case run.
> >    https://github.com/apache/datafusion/blob/b65d2a3a770596bc33d90f11a908ae29065068bf/datafusion/core/tests/parquet/external_access_plan.rs#L392
> >    
> >    and
> >    https://github.com/apache/datafusion/blob/b65d2a3a770596bc33d90f11a908ae29065068bf/datafusion/core/tests/parquet/external_access_plan.rs#L366
> > 3. For sake of removing temp file at the end of each case run, I remove singleton mode of TestData in `get_test_data`
> >    https://github.com/apache/datafusion/blob/b65d2a3a770596bc33d90f11a908ae29065068bf/datafusion/core/tests/parquet/external_access_plan.rs#L382-L419

I fix this code to avoid convert special characters
https://github.com/apache/datafusion/blob/aaa2e4b648b6e9e1cc66de6f10e07fc2bc25eac1/datafusion/core/src/datasource/listing/mod.rs#L92-L95

File: datafusion/core/tests/parquet/external_access_plan.rs [hunk 1]
```diff
@@ -369,45 +379,43 @@ struct TestData {
     file_size: u64,
 }
 
-static TEST_DATA: OnceLock<TestData> = OnceLock::new();
+static _TEST_DATA: OnceLock<TestData> = OnceLock::new();
 
 /// Return a parquet file with 2 row groups each with 5 rows
-fn get_test_data() -> &'static TestData {
-    TEST_DATA.get_or_init(|| {
```
Comment (alamb) [inline datafusion/core/tests/parquet/external_access_plan.rs:376]: The reason to use the `TEST_DATA` thing was to avoid creating the same file over and over again.

Do we need to remove `TEST_DATA`? 

It seems like the core difference is the use of `tempfile_in` rather than the change from static

**Review by alamb — COMMENTED** [review]
Thanks @zhuliquan -- i have one more question. I don't think it is necessary to fix but it would be nice to get a resolution

File: datafusion/core/tests/parquet/external_access_plan.rs (hunk 1 above)
Comment (alamb) [reply datafusion/core/tests/parquet/external_access_plan.rs:376]: If we aren't going to use `TEST_DATA` anymore perhaps we can remove it (rather than name it starting with `_` to avoid a compiler error) 🤔

Comment (zhuliquan) [reply datafusion/core/tests/parquet/external_access_plan.rs:376]: > The reason to use the `TEST_DATA` thing was to avoid creating the same file over and over again.
> 
> Do we need to remove `TEST_DATA`?
> 
> It seems like the core difference is the use of `tempfile_in` rather than the change from static

There is no chance for delete TEST_DATA. Because there is no main test function to lead minor test cases.

**Review by alamb — APPROVED** [review]
Looks like an improvement to me -- thanks @zhuliquan
