### PR TITLE
Auto detect hive column partitioning with ListingTableFactory / `CREATE EXTERNAL TABLE`

### LINKED ISSUE #17049: Auto detecting partitions with `ListingTableFactory` on  Hive partitioned datasets
### Describe the bug

When using a `ListingTableFactory` (i.e. using the `datafusion-cli`) tables that leverage Hive partitioning do not yield the expected  columns derived from the hive key/value pairs (and other such oddities).

### To Reproduce

A publicly accessible S3 bucket hosting Hive partitioned parquet data can be used to show the issues. The general structure of the data can be seen below:
```console
$ aws s3 ls s3://overturemaps-us-west-2/release/2025-07-23.0/
                           PRE theme=addresses/
                           PRE theme=base/
                           PRE theme=buildings/
                           PRE theme=divisions/
                           PRE theme=places/
                           PRE theme=transportation/
```
```console
$ aws s3 ls s3://overturemaps-us-west-2/release/2025-07-23.0/ --recursive
2025-07-22 14:42:50 1073537247 release/2025-07-23.0/theme=addresses/type=address/part-00000-57f746d8-98a1-4faa-94c2-4f084343ecac-c000.zstd.parquet
2025-07-22 14:43:06 1013189887 release/2025-07-23.0/theme=addresses/type=address/part-00001-57f746d8-98a1-4faa-94c2-4f084343ecac-c000.zstd.parquet
. . .
```

Here are a couple of examples off odd behavior when trying to access this data.
```sql
DataFusion CLI v49.0.0
> SET datafusion.execution.listing_table_ignore_subdirectory to false;
0 row(s) fetched.
Elapsed 0.001 seconds.

> CREATE EXTERNAL TABLE overture_maps
STORED AS PARQUET LOCATION 's3://overturemaps-us-west-2/release/2025-07-23.0/';
0 row(s) fetched.
Elapsed 0.645 seconds.

> describe overture_maps;
+-------------+-----------+-------------+
| column_name | data_type | is_nullable |
+-------------+-----------+-------------+
+-------------+-----------+-------------+
0 row(s) fetched.
Elapsed 0.001 seconds.
```
In the above example no schema has been detected at all, either from Hive keys or the underlying parquet data itself, in spite of ensuring the listing table can traverse subdirectories.

```sql
> CREATE EXTERNAL TABLE overture_maps
STORED AS PARQUET LOCATION 's3://overturemaps-us-west-2/release/2025-07-23.0/theme=addresses/';
0 row(s) fetched.
Elapsed 0.911 seconds.

> select column_name, is_nullable from information_schema.columns where table_name='overture_maps';
+----------------+-------------+
| column_name    | is_nullable |
+----------------+-------------+
| id             | YES         |
| geometry       | YES         |
| bbox           | YES         |
| country        | YES         |
| postcode       | YES         |
| street         | YES         |
| number         | YES         |
| unit           | YES         |
| address_levels | YES         |
| postal_city    | YES         |
| version        | YES         |
| sources        | YES         |
+----------------+-------------+
12 row(s) fetched.
Elapsed 0.005 seconds.

> select column_name, is_nullable from information_schema.columns where table_name='overture_maps' and column_name='type';
+-------------+-------------+
| column_name | is_nullable |
+-------------+-------------+
+-------------+-------------+
0 row(s) fetched.
Elapsed 0.006 seconds.
```
Next, when a path to a subdirectory is given to create the table, the underlying parquet schema is successfully detected, however the columns corresponding to the Hive keys are still missing.

### Expected behavior

When accessing a hive partitioned dataset with no explicit schema set, and having subdirectory traversal enabled, I would expect to get a table that can be queried/filtered on both the columns represented in the parquet schema as well as the hive partitions.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by BlakeOrth**
## Which issue does this PR close?
- Closes #17049

## What changes are included in this PR?
 - Fixes an issue in the `ListingTableFactory` where hive columns are not detected and incorporated into the table schema when an explicit schema has not been set by the user
 - Fixes an issue where subdirectories that do not follow Hive formatting (e.g. key=value) could be erroneously interpreted as contributing to the table schema

## Are these changes tested?
Yes, the PR includes both unit tests and `sqllogic` tests that exercise the fixes

## Are there any user-facing changes?
I think there's a possibility for the changes to impact users of the `ListingTableFactory`. In my mind the behavior represented here is what I would think the "expected" behavior should be, but there's a good possibility users are relying on the previous behavior and could get unexpected results if this PR is merged.

cc @alamb

### CODE REVIEW

File: datafusion/core/src/datasource/listing/table.rs [hunk 1]
```diff
@@ -802,6 +802,9 @@ impl ListingOptions {
                     .rev()
                     .skip(1) // get parents only; skip the file itself
                     .rev()
+                    // Partitions are expected to follow the format "column_name=value", so we
+                    // should ignore any path part that cannot be parsed into the expected format
+                    .filter(|s| s.contains('='))
```
Comment (BlakeOrth) [inline datafusion/core/src/datasource/listing/table.rs:807]: This code is necessary to prevent regressions exposed by existing `sqllogic` tests. Here's the failures from existing tests for this PR if this fix is not included

```
Completed 345 test files in 17 seconds                                                                                                                                      External error: 6 errors in file /home/blake/open_source_src/datafusion-BlakeOrth/datafusion/sqllogictest/test_files/parquet.slt

1. statement failed: DataFusion error: Error during planning: Found mixed partition values on disk [[], ["subdir"]]
[SQL] CREATE EXTERNAL TABLE listing_table_folder_0
STORED AS PARQUET
LOCATION 'test_files/scratch/parquet/test_table/';
at /home/blake/open_source_src/datafusion-BlakeOrth/datafusion/sqllogictest/test_files/parquet.slt:306


2. query failed: DataFusion error: Error during planning: table 'datafusion.public.listing_table_folder_0' not found
[SQL] select count(*) from listing_table_folder_0;
at /home/blake/open_source_src/datafusion-BlakeOrth/datafusion/sqllogictest/test_files/parquet.slt:315


3. query failed: DataFusion error: Error during planning: table 'datafusion.public.listing_table_folder_0' not found
[SQL] select count(*) from listing_table_folder_0;
at /home/blake/open_source_src/datafusion-BlakeOrth/datafusion/sqllogictest/test_files/parquet.slt:324


4. statement failed: DataFusion error: Error during planning: Found mixed partition values on disk [[], ["subdir"]]
[SQL] CREATE EXTERNAL TABLE listing_table_folder_1
STORED AS PARQUET
LOCATION 'test_files/scratch/parquet/test_table';
at /home/blake/open_source_src/datafusion-BlakeOrth/datafusion/sqllogictest/test_files/parquet.slt:330


5. query failed: DataFusion error: Error during planning: table 'datafusion.public.listing_table_folder_1' not found
[SQL] select count(*) from listing_table_folder_1;
at /home/blake/open_source_src/datafusion-BlakeOrth/datafusion/sqllogictest/test_files/parquet.slt:339


6. query failed: DataFusion error: Error during planning: table 'datafusion.public.listing_table_folder_1' not found
[SQL] select count(*) from listing_table_folder_1;
at /home/blake/open_source_src/datafusion-BlakeOrth/datafusion/sqllogictest/test_files/parquet.slt:348
```

**Review by alamb — COMMENTED** [review]
THanks @BlakeOrth 

I played with this PR for a while, and I think this PR basically enables automatic partition detection for *all* listing tables which is quite cool.

For example with the following setup:

```sql
DataFusion CLI v49.0.0
> copy (values ('foo'), ('bar')) to '/tmp/table/a=1/file1.parquet';

+-------+
| count |
+-------+
| 2     |
+-------+
1 row(s) fetched.
Elapsed 0.034 seconds.

> copy (values ('baz')) to '/tmp/table/a=1/file2.parquet';
+-------+
| count |
+-------+
| 1     |
+-------+
1 row(s) fetched.
Elapsed 0.002 seconds.

> create external table t stored as parquet location '/tmp/table';
0 row(s) fetched.
Elapsed 0.010 seconds.
```

On main, no partition columns are recognized:

Main
```sql
> select * from t;
+---------+
| column1 |
+---------+
| foo     |
| bar     |
| baz     |
+---------+
3 row(s) fetched.
Elapsed 0.012 seconds.
```

This PR
```sql
> select * from t;
+---------+---+
| column1 | a |
+---------+---+
| baz     | 1 |
| foo     | 1 |
| bar     | 1 |
+---------+---+
3 row(s) fetched.
Elapsed 0.015 seconds.
```

I think this change is actually a quite a nice improvement but is really a feature, not a bug fix, and I think the code you have here actually looks good :trophy:


In order to proceed I think we need a few things:
1. More tests (see below)
2. Add a [configuration setting](https://datafusion.apache.org/user-guide/configs.html#) to disable this new behavior (let people opt out of automatic partition inference). Perhaps `datafusion.execution.infer_partitioning`, similarly to `datafusion.execution.collect_statistics`
3. Document the behavior (with an example) in https://datafusion.apache.org/user-guide/sql/ddl.html#create-external-table
4. Add a note to the upgrade guide https://datafusion.apache.org/library-user-guide/upgrading.html


## New tests
I looked around and it seems we don't actually have any tests focused on reading hive partitioned datasets in .slt, nor automatically detecting hive partitions on table creation

Would you be willing to write some tests in a new file, such as `datafusion/sqllogictest/test_files/listing_table_partitions.slt`  (following the naming convention of `datafusion/sqllogictest/test_files/listing_table_statistics.slt`)

I think you could start with my example SQL commands above and write the related tests

I know this is a lot. I am sorry for the delayed feedback. Please let me know what you think.

**Comment by alamb** [comment]
FYI @adrian and @nuno-faria

**Comment by BlakeOrth** [comment]
@alamb 
> I know this is a lot. I am sorry for the delayed feedback. Please let me know what you think.

No worries on the delay, I can absolutely fill in the extra blanks. I just have a couple of quick questions on how to proceed.

> 1. More tests (see below)

The `sqllogic` test I added actually does work on a hive partitioned table. I setup a "readback" using an existing table that's created with the following setup:
https://github.com/apache/datafusion/blob/cb571d9e2e7da39da2aec5ca50283b9d1d8ffe46/datafusion/sqllogictest/test_files/insert_to_external.slt#L155-L160

This results in the following directory/file structure:
```console
datafusion/sqllogictest/test_files/scratch/insert_to_external/insert_to_partitioned$ tree .
.
├── a=10
│   ├── b=100
│   │   └── ImzsRq5BY2218Z0v.csv
│   └── b=200
│       └── ImzsRq5BY2218Z0v.csv
├── a=20
│   ├── b=100
│   │   └── ImzsRq5BY2218Z0v.csv
│   └── b=200
│       └── ImzsRq5BY2218Z0v.csv
└── a=30
    └── b=300
        └── YGMRSbmO08FmNfDs.csv

9 directories, 5 files
```

The existing tests prior to this PR all passed because the table was created with an explicit schema, so DataFusion recognized/parsed all the partition columns. The test I implemented for this PR starts a new table, and fails on `main` with the following errors:

```diff
1. query result mismatch:
[SQL] describe partitioned_insert_test_readback;
[Diff] (-expected|+actual)
-   c Int64 YES
-   a Dictionary(UInt16, Utf8) NO
-   b Dictionary(UInt16, Utf8) NO
+   c Int64 YES
at /home/blake/open_source_src/datafusion/datafusion/sqllogictest/test_files/insert_to_external.slt:184


2. query failed: DataFusion error: Schema error: No field named a. Valid fields are partitioned_insert_test_readback.c, partitioned_insert_test_readback.c.
[SQL] select * from partitioned_insert_test_readback order by a,b,c;
at /home/blake/open_source_src/datafusion/datafusion/sqllogictest/test_files/insert_to_external.slt:191


3. query failed: DataFusion error: Schema error: No field named b. Valid fields are partitioned_insert_test_readback.c.
[SQL] select count(*) from partitioned_insert_test_readback where b=100;
at /home/blake/open_source_src/datafusion/datafusion/sqllogictest/test_files/insert_to_external.slt:201
```

I believe this sequence of tests successfully exercises both the creation of hive partitioned tables, as well as the expected outcome when reading that data.

I'm happy to move this test, and the associated test setup, to a new file and/or augment it with the SQL commands you've laid out above. Given the above explanation, let me know if you'd still prefer to proceed with a new test file or if what's already there is sufficient.

> 2. Add a [configuration setting](https://datafusion.apache.org/user-guide/configs.html#) to disable this new behavior (let people opt out of automatic partition inference). Perhaps datafusion.execution.infer_partitioning, similarly to datafusion.execution.collect_statistics

I think it's prudent to note that the changes here only effect the `ListingTableFactory` and low level `ListingTable` users wouldn't experience any change. Is an `execution` option stil the right place for the configuration setting? `datafusion.execution.listing_table_factory_infer_partitions` with a default of `true`?

> 3. Document the behavior (with an example) in https://datafusion.apache.org/user-guide/sql/ddl.html#create-external-table
> 4. Add a note to the upgrade guide https://datafusion.apache.org/library-user-guide/upgrading.html

No questions here, I can take care of this.

**Comment by alamb** [comment]
> I believe this sequence of tests successfully exercises both the creation of hive partitioned tables, as well as the expected outcome when reading that data.
> 
> I'm happy to move this test, and the associated test setup, to a new file and/or augment it with the SQL commands you've laid out above. Given the above explanation, let me know if you'd still prefer to proceed with a new test file or if what's already there is sufficient.

I think give we are about to add non trivial new functionality (even if the code is not new), we should make the tests I suggested

> I think it's prudent to note that the changes here only effect the ListingTableFactory and low level ListingTable users wouldn't experience any change. Is an execution option stil the right place for the configuration setting?

Yes, I think so (unless you can find another location for Listingtable settings -- maybe we should make a new category 🤔 )

**Comment by nuno-faria** [comment]
Thanks for the changes @BlakeOrth.
I also believe that automatically resolving the partitioning is the best approach. Like @alamb said, it would be nice to document and add an option to toggle this off if needed. In addition to adding documentation at https://datafusion.apache.org/user-guide/sql/ddl.html#create-external-table, I think we should also have additional documentation here: https://datafusion.apache.org/user-guide/cli/datasources.html#create-external-table.

One thing to note is that I believe that `CREATE EXTERNAL TABLE` now has a different behavior from `SessionContext::register_parquet`, which still requires partitions to be manually specified. I also feel `register_parquet` could use a form of automatic partition detection, maybe in a flag passed to `ParquetReadOptions`.

**Comment by alamb** [comment]
> One thing to note is that I believe that `CREATE EXTERNAL TABLE` now has a different behavior from `SessionContext::register_parquet`, which still requires partitions to be manually specified. I also feel `register_parquet` could use a form of automatic partition detection, maybe in a flag passed to `ParquetReadOptions`.

yes please!

Would it help if I made a "mini" epic and broke this project down into some smaller parts / tickets so people could work on it in parallel?

(I am on vacation this week, so my responses will be delayed(

**Comment by nuno-faria** [comment]
> Would it help if I made a "mini" epic and broke this project down into some smaller parts / tickets so people could work on it in parallel?

I think that would be a good idea.

> (I am on vacation this week, so my responses will be delayed(

I also think it could wait since its not urgent.

**Comment by BlakeOrth** [comment]
@alamb @nuno-faria I believe I touched all the asks from the previous round of feedback with the latest commit. I referenced a recent PR by @nuno-faria where the parquet metadata cache option was added to help guide me through getting a new config option pushed into all the correct locations. That PR had changes in the various `proto` directories, but I looked and it didn't seem like this option belongs to a set of options that are serialized, so I didn't think there were any changes necessary there. Please let me know if I missed anything!

File: datafusion/sqllogictest/test_files/listing_table_partitions.slt [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+query TTT
+select * from multi_part where b=200; 
+----
+baz 1 200
+
+statement count 0
+set datafusion.execution.listing_table_factory_infer_partitions = false;
+
+statement count 0
+create external table infer_disabled
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/listing_table_partitions.slt:64]: nice

**Comment by BlakeOrth** [comment]
I've made just a couple very small changes to the docs with this most recent commit to fix a spelling error (I love the fact CI runs spell check here! :heart: ) and fixes a small copy/paste issue in the docs that I caught while looking at the final diff.

**Comment by alamb** [comment]
Thank you @BlakeOrth and @nuno-faria
