### PR TITLE
fix: serialize listing table without partition column

### LINKED ISSUE #15718: Partitioned `ListingTable` read fails after logical plan ser/de
### Describe the bug

Partitioned `ListingTable` logical plan round trip fails to produce valid schema after deserialisation with:

```
Error: SchemaError(DuplicateQualifiedField { qualifier: Bare { table: "hive_style" }, name: "year" }, Some(""))
```

### To Reproduce

```rust
        let session_state = ctx.state();
        let data = format!("{test_data}/hive_style/");
        let listing_table_url = ListingTableUrl::parse(data)?;

        let table_partition_cols = vec![
            ("year".to_owned(), DataType::Int64),
            ("month".to_owned(), DataType::Int64),
        ];

        let file_format = ParquetFormat::new()
            .with_enable_pruning(true)
            .with_skip_metadata(true);

        let listing_options = ListingOptions::new(Arc::new(file_format))
            .with_table_partition_cols(table_partition_cols);

        let config = ListingTableConfig::new(listing_table_url)
            .with_listing_options(listing_options)
            .infer_schema(&session_state)
            .await?;

        ctx.register_table("hive_style", Arc::new(ListingTable::try_new(config)?))?;
        //
        // Limit: skip=0, fetch=1
        //  Projection: hive_style.year, hive_style.month
        //   TableScan: hive_style
        //
        let plan = ctx
            .sql("SELECT year, month FROM hive_style LIMIT 1")
            .await?
            .logical_plan()
            .clone();

        let expected = [
            "+------+-------+",
            "| year | month |",
            "+------+-------+",
            "| 2024 | 1     |",
            "+------+-------+",
        ];

        // works as expected
        let result = ctx
            .execute_logical_plan(plan.clone())
            .await?
            .collect()
            .await?;
        assert_batches_eq!(expected, &result);

        let bytes = logical_plan_to_bytes(&plan)?;

        // logical plan from bytes fails
        //
        // Error: SchemaError(DuplicateQualifiedField { qualifier: Bare { table: "hive_style" }, name: "year" }, Some(""))
        let plan = logical_plan_from_bytes(&bytes, &ctx)?;

        let result = ctx.execute_logical_plan(plan).await?.collect().await?;
        assert_batches_eq!(expected, &result);
```

### Expected behavior

Expected correct deserialisation 

### Additional context

I believe schema used at https://github.com/apache/datafusion/blob/7ff6c7e68540c69b399a171654d00577e6f886bf/datafusion/proto/src/logical_plan/mod.rs#L1127 should not contain partitioned columns, as original table does not have them. 

we should probably add new test to cover this case at https://github.com/apache/datafusion/blob/7ff6c7e68540c69b399a171654d00577e6f886bf/datafusion/proto/tests/cases/roundtrip_logical_plan.rs#L265

More details about original bug can be found at https://github.com/apache/datafusion-ballista/issues/1239

### PR DESCRIPTION
**Pull request by chenkovsky**
## Which issue does this PR close?

- Closes #15718.

## Rationale for this change

partition columns should exclude file schema in listing table

## What changes are included in this PR?

1. update partition column type in proto
2. remove partition columns from ListingTableScanNode schema.

## Are these changes tested?

UT

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by milenkovicm** [comment]
Thanks @chenkovsky i think changes make sense, very clean implementation

**Review by milenkovicm — APPROVED** [review]

File: datafusion/proto/src/logical_plan/mod.rs [hunk 1]
```diff
@@ -458,23 +458,24 @@ impl AsLogicalPlan for LogicalPlanNode {
...
+                    .table_partition_cols
+                    .iter()
+                    .map(|col| {
+                        let arrow_type =
+                            col.arrow_type.as_ref().unwrap().try_into().map_err(|e| {
+                                proto_error(format!(
+                                    "Received an unknown ArrowType: {}",
+                                    e
+                                ))
+                            })?;
```
Comment (alamb) [inline datafusion/proto/src/logical_plan/mod.rs:471]: I think it would be good to avoid an unwrap here as that will panic rather than returning an error on invalid protobuf

```suggestion
                        let Some(arrow_type) = col.arrow_type.as_ref() else {
                            return Err(proto_error(format!(
                                "Missing Arrow type in partition columns"
                            )));
                        };
                       let arrow_type = DataType::try_from(arrow_type).map_err(|e| {
                            proto_error(format!("Received an unknown ArrowType: {}", e))
                        })?;
```

**Review by alamb — APPROVED** [review]
Thanks @chenkovsky  and @milenkovicm . I have one suggestion for your consideration, but I think this is better than what is on main

**Comment by alamb** [comment]
Thanks again @chenkovsky
