### PR TITLE
Fix: Do not normalize table names when deserializing from protobuf

### LINKED ISSUE #18122: Table names are normalized when roundtripping through protobuf
### Describe the bug

Using `datafusion-proto` to serialize a plan such as:

```
Filter: WOW_SUCH_TABLE.a > Int64(10) AND WOW_SUCH_TABLE.B < Int64(100)
  TableScan: WOW_SUCH_TABLE projection=[a, B], partial_filters=[WOW_SUCH_TABLE.a > Int64(10), WOW_SUCH_TABLE.B < Int64(100)]
```

And then deserializing it results in a different plan:

```
Filter: wow_such_table.a > Int64(10) AND wow_such_table.B < Int64(100)
  TableScan: WOW_SUCH_TABLE projection=[a, B], partial_filters=[wow_such_table.a > Int64(10), wow_such_table.B < Int64(100)]
```

Note that the `TableReference` in the `TableScan` is intact, but the expression's `Column` is now normalized (downcased). This has nothing to do with `enable_ident_normalization`, because we're well past the SQL parser at this point.

The issue seems to be here:

https://github.com/apache/datafusion/blob/8e1d13a9c6e989b8a6216c6752a34fb3e0494e0f/datafusion/proto-common/src/from_proto/mod.rs#L145

Because that calls `Column::new`, which takes an `Into<TableReference>`; and `impl From<String> for TableReference` normalizes.

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by drin**
## Which issue does this PR close?

Closes #18122

## Rationale for this change

Existing behavior is to use the `relation` field of `ColumnRelation` message to construct a `TableReference` ([mod.rs#L146][fromcol_proto], [mod.rs#L171][tryfrom_proto]). However, the `relation` field
is a string and `From<String> for TableReference` always calls
parse_identifiers_normalized with `ignore_case: False`, which always
normalizes the identifier to lower case ([TableReference::parse_str][parse_str]).

For a description of the bug at a bit of a higher level, see #18122.

## What changes are included in this PR?

This PR introduces the following:
1. An implementation `From<protobuf::ColumnRelation>` and `From<&protobuf::ColumnRelation>` for
`TableReference`.
2. Updated logic in `TryFrom<&protobuf::DFSchema>` for `DFSchema` and in `From<protobuf::Column>` for `Column` that correctly leads to the new `From` impls for `TableReference` to be invoked.
3. A new method, `TableReference::parse_str_normalized`, that parses an identifier without normalizing it, with some logic from `TableReference::parse_str` being refactored to accommodate code reuse.

## Are these changes tested?

Commit a355196 adds a new test case, `roundtrip_mixed_case_table_reference`, that tests the desired behavior.

The existing behavior (without the fix in 0616df2 and with the extra line `println!("{}", server_logical_plan.display_indent_schema());`):
```
cargo test "roundtrip_mixed_case_table_reference" --test proto_integration -- --nocapture
   Compiling datafusion-proto v48.0.1 (/Users/aldrinm/code/bauplanlabs/datafusion/octalene-datafusion/datafusion/proto)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 1.56s
     Running tests/proto_integration.rs (target/debug/deps/proto_integration-775454d70979734b)

running 1 test

thread 'cases::roundtrip_logical_plan::roundtrip_mixed_case_table_reference' panicked at datafusion/proto/tests/cases/roundtrip_logical_plan.rs:2690:5:
assertion `left == right` failed
  left: "Filter: TestData.a = Int64(1) [a:Int64;N]\n  TableScan: TestData projection=[a], partial_filters=[TestData.a = Int64(1)] [a:Int64;N]"
 right: "Filter: testdata.a = Int64(1) [a:Int64;N]\n  TableScan: TestData projection=[a], partial_filters=[testdata.a = Int64(1)] [a:Int64;N]"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test cases::roundtrip_logical_plan::roundtrip_mixed_case_table_reference ... FAILED

failures:

failures:
    cases::roundtrip_logical_plan::roundtrip_mixed_case_table_reference

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 112 filtered out; finished in 0.09s
```

With the fix implemented (0616df2):
```
running 1 test
Filter: TestData.a = Int64(1) [a:Int64;N]
  TableScan: TestData projection=[a], partial_filters=[TestData.a = Int64(1)] [a:Int64;N]
test cases::roundtrip_logical_plan::roundtrip_mixed_case_table_reference ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 112 filtered out; finished in 0.06s
```

## Are there any user-facing changes?

None.

[fromcol_proto]: https://github.com/apache/datafusion/blob/50.2.0/datafusion/proto-common/src/from_proto/mod.rs#L146
[tryfrom_proto]: https://github.com/apache/datafusion/blob/50.2.0/datafusion/proto-common/src/from_proto/mod.rs#L171
[parse_str]: https://github.com/apache/datafusion/blob/50.2.0/datafusion/common/src/table_reference.rs#L273

### CODE REVIEW

**Comment by drin** [comment]
This is my first PR in rust and datafusion, so please let me know if there's any style/design changes needed (I just realized I didn't run a linter either)

**Comment by drin** [comment]
We also want this fix to be applied to branch-48, which I've done in #18188. Let me know if this is not the correct way to do this and I can delete that PR.

File: datafusion/common/src/table_reference.rs [hunk 1]
```diff
@@ -269,24 +269,48 @@ impl TableReference {
...
+        Self::from_vec(table_parts)
+             .unwrap_or(Self::Bare { table: s.into() })
+    }
 
+    /// Compose a [`TableReference`] from separate parts. The input vector should contain
+    /// at most three elements in the following sequence:
+    /// ```no_rust
+    /// [<catalog>, <schema>, table]
+    /// ```
+    pub fn from_vec(mut parts: Vec<String>) -> Option<Self> {
```
Comment (colinmarc) [inline datafusion/common/src/table_reference.rs]: I think this could be `from_parts(parts: &[impl AsRef<str>])` and copy out of the slice to be a little bit more flexible. We don't need the `Vec` itself (and in fact we destroy it here, which could be surprising to the caller).

File: datafusion/proto-common/src/from_proto/mod.rs [hunk 2]
```diff
@@ -138,11 +138,23 @@ where
     }
 }
 
+impl From<protobuf::ColumnRelation> for TableReference {
```
Comment (colinmarc) [inline datafusion/proto-common/src/from_proto/mod.rs:141]: I think this isn't quite right - usually `From` is just for equivalent types, but here we're ignoring half of the input type. I would just call `parse_str_normalized` from the `impl From<protobuf::Column> for Column` definition.

File: datafusion/proto-common/src/from_proto/mod.rs [hunk 3]
```diff
@@ -138,11 +138,23 @@ where
...
+    fn from(rel: protobuf::ColumnRelation) -> Self {
+        Self::parse_str_normalized(rel.relation.as_str(), true)
+    }
+}
+
+impl From<&protobuf::ColumnRelation> for TableReference {
```
Comment (colinmarc) [inline datafusion/proto-common/src/from_proto/mod.rs]: Same goes for this, but for future reference: you usually don't need to implement a separate `From` for a borrowed type, and it's code smell if you do (the caller should be forced to use clone explicitly)

File: datafusion/common/src/table_reference.rs (hunk 1 above)
Comment (drin) [reply datafusion/common/src/table_reference.rs]: what're your thoughts as far as this being the inverse of [to_vec](https://github.com/drin/datafusion/blob/aadb94e905c8a9b14a2d2c3f830745c19f0564f4/datafusion/common/src/table_reference.rs#L317-L322) just below?

File: datafusion/proto-common/src/from_proto/mod.rs (hunk 3 above)
Comment (drin) [reply datafusion/proto-common/src/from_proto/mod.rs]: This was to match the pattern seen for [From<&protobuf::Column>](https://github.com/drin/datafusion/blob/aadb94e905c8a9b14a2d2c3f830745c19f0564f4/datafusion/proto-common/src/from_proto/mod.rs#L161-L165), but I can remove it

File: datafusion/proto-common/src/from_proto/mod.rs (hunk 2 above)
Comment (drin) [reply datafusion/proto-common/src/from_proto/mod.rs:141]: wait, this isn't ignoring any part of the type, [protobuf::ColumnRelation](https://github.com/drin/datafusion/blob/aadb94e905c8a9b14a2d2c3f830745c19f0564f4/datafusion/proto-common/src/generated/prost.rs#L3-L6) only has a single `relation` field.

File: datafusion/common/src/table_reference.rs (hunk 1 above)
Comment (drin) [reply datafusion/common/src/table_reference.rs]: actually, a little LLM magic explained `&[]` syntax and I see the intended wider surface now (even though this specific case means an extra copy and the vec will go away anyways)

Comment (drin) [reply datafusion/common/src/table_reference.rs]: okay, I played around with things quite a bit (probably too much), and what felt right to me was to change the method comments and add a new method, `from_slice`, which is exactly what you proposed as `from_parts`. This way there's clearly 2 ways to construct "from identifier parts": (1) from a slice (flexible, but copies) and (2) from a vec (narrow, zero-copy).

I know that the performance hit is small because it only copies 1-3 times (O(1)), but the idea of it occurring for every identifier in a query is painful for large queries especially since the string is already copied from what is deserialized in the protobuf.

**Comment by drin** [comment]
Also, just for clarification, I changed `from_vec` to use `pop` instead of `remove` since shifting elements every time seemed unnecessary, plus it actually makes sense to me when reading the code to see the consistency that every extra part is an extra prefix and table name is always the last field.

**Comment by drin** [comment]
I ran `dev/linter.sh` for formatting. I added an extra commit for miscellaneous changes to satisfy the linter (unrelated to the core of this PR).

File: datafusion/common/src/table_reference.rs [hunk 4]
```diff
@@ -269,24 +269,64 @@ impl TableReference {
...
+
+        Self::from_vec(table_parts).unwrap_or_else(|| Self::Bare { table: s.into() })
+    }
 
+    /// Copy from a slice of identifier parts to compose a [`TableReference`]. The input slice
+    /// should contain 1 <= N <= 3 elements in the following sequence:
+    /// ```no_rust
+    /// [<catalog>, <schema>, table]
+    /// ```
+    pub fn from_slice(parts: &[impl AsRef<str>]) -> Option<Self> {
```
Comment (Jefffrey) [inline datafusion/common/src/table_reference.rs]: Is this meant to be used somewhere?

File: datafusion/common/src/table_reference.rs [hunk 5]
```diff
@@ -269,24 +269,64 @@ impl TableReference {
...
+            _ => None,
+        }
+    }
+
+    /// Consume a vector of identifier parts to compose a [`TableReference`]. The input vector
+    /// should contain 1 <= N <= 3 elements in the following sequence:
+    /// ```no_rust
+    /// [<catalog>, <schema>, table]
+    /// ```
+    pub fn from_vec(mut parts: Vec<String>) -> Option<Self> {
```
Comment (Jefffrey) [inline datafusion/common/src/table_reference.rs]: Maybe we should keep it private until we have a need to expose it? Or would it be generally useful enough to users to make it public now?

File: datafusion/common/src/table_reference.rs (hunk 4 above)
Comment (drin) [reply datafusion/common/src/table_reference.rs]: it was just in response to feedback from @colinmarc to be a flexible equivalent to `from_vec`. I can remove it if you'd prefer.

File: datafusion/common/src/table_reference.rs (hunk 5 above)
Comment (drin) [reply datafusion/common/src/table_reference.rs]: I just made it public because that always makes sense to me. But this logic was only being done in parse_str previously, and if anyone ever calls parse_identifiers_normalized then this logic is the next step for getting a TableReference. whether that's generally useful, I would have no idea (too new to the ecosystem)

Comment (Jefffrey) [reply datafusion/common/src/table_reference.rs]: imo given this PR is focused on fixing a proto bug, we should keep this private unless we need to expose it, to minimize our already somewhat large public API

File: datafusion/common/src/table_reference.rs (hunk 4 above)
Comment (Jefffrey) [reply datafusion/common/src/table_reference.rs]: If it's not in use I'd prefer it to be removed 👍

File: datafusion/common/src/table_reference.rs (hunk 5 above)
Comment (drin) [reply datafusion/common/src/table_reference.rs]: changed to private! (I assume just removing the `pub` does this)

File: datafusion/common/src/table_reference.rs (hunk 4 above)
Comment (drin) [reply datafusion/common/src/table_reference.rs]: removed

**Comment by drin** [comment]
@Jefffrey thanks for reviewing!

**Comment by Jefffrey** [comment]
Thanks @drin 👍
