### PR TITLE
fix: Nested arrays should not get a field in lookup

### LINKED ISSUE #18744: [Avro] Structs inside nested lists with custom fields are not found in lookup
### Describe the bug

Currently the field name in the lookup is hardcoded as "element", which is the parquet convention, arrow uses "item" in its convention, but when actual reading happen, the constructed name actually uses the list's field name, which means for "normal" list arrays(where the item is "item"), the lookup will never match.
This also goes against the avro behaviour, where lists should not have a name anyway, which might cause issues in the future as lookup evolves(using refs and such)

### To Reproduce

Create a reader with the following schema:
```
{
          "type": "record",
          "name": "root",
          "fields": [
            {
              "name": "items",
              "type": {
                "type": "array",
                "items": {
                  "type": "record",
                  "name": "item_record",
                  "fields": [
                    {
                      "name": "id",
                      "type": "long"
                    },
                    {
                      "name": "name",
                      "type": "string"
                    }
                  ]
                }
              }
            }
          ]
        }
```

Reading will fail as the schema lookup will use "element"

### Expected behavior

Lists should not have sub names at all, and this should be read successfully.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by EmilyMatt**
## Which issue does this PR close?

- Closes #18744 .

## Rationale for this change

Fixes a critical bug, as well as behaves more like avro expects in regards to arrays.

## What changes are included in this PR?

Removed the sub label from arrays in general

## Are these changes tested?

Yes

## Are there any user-facing changes?

Not really

### CODE REVIEW

File: datafusion/datasource-avro/src/avro_to_arrow/arrow_array_reader.rs [hunk 1]
```diff
@@ -1720,4 +1716,91 @@ mod test {
...
+            false,
+        )]));
+
+        let mut reader = ReaderBuilder::new()
+            .with_schema(arrow_schema)
+            .with_batch_size(10)
+            .build(std::io::Cursor::new(bytes))
+            .unwrap();
+
+        // This should fail because schema_lookup will have "items.element.id" and "items.element.name"
```
Comment (martin-g) [inline datafusion/datasource-avro/src/avro_to_arrow/arrow_array_reader.rs]: `This should fail ...` but it passes!
Maybe reword it to "This was failing before #18745 because ..." ?

Comment (EmilyMatt) [reply datafusion/datasource-avro/src/avro_to_arrow/arrow_array_reader.rs]: You're right, thank you^

**Review by Weijun-H — APPROVED** [review]
