### PR TITLE
fix: fixes trig function order by

### LINKED ISSUE #11552: Query with `order by acos(sin(v1))` panic (SQLancer)
### Describe the bug

Reproducer in datafusion-cli:
```
DataFusion CLI v40.0.0
> create table t1(v1 int);

0 row(s) fetched.
Elapsed 0.073 seconds.

> SELECT * FROM t1 ORDER BY ACOS(SIN(v1));
thread 'main' panicked at /Users/yongting/Desktop/code/my_datafusion/arrow-datafusion/datafusion/common/src/scalar/mod.rs:1089:9:
assertion failed: datatype.is_primitive()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### To Reproduce

_No response_

### Expected behavior

_No response_

### Additional context

Found by SQLancer https://github.com/apache/datafusion/issues/11030

### PR DESCRIPTION
**Pull request by tshauck**
## Which issue does this PR close?

Closes #11552

## Rationale for this change

The `assert!(datatype.is_primitive());` is getting hit in `new_negative_one`, but as far as I can tell isn't needed. There's a match statement right below that handles the datatype.

Without the assert these functions seem to work properly. That said, I'm a little confused why it's working exactly. The datatypes coming through are `Datatype::Null` which caused the assertion error but seemingly isn't causing errors in the match statement.

I'm also working on a branch https://github.com/apache/datafusion/compare/main...tshauck:arrow-datafusion:add-unary-udf-bounds?expand=1 that I think is a more complete way to solve this problem because currently unary functions don't report their bounds which I think is what ordering relies on to get its data type and means nested trig functions can work for ordering.

## What changes are included in this PR?

Removed `datatype.is_primative()` asserts where the datatype is immediately matched on. I think it'd generally be better to handle unexpected datatypes that way for the error propagation vs asserting, which can lead to panics at query time.

## Are these changes tested?

I added tests from the ticket that were reported as panicking.

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/common/src/scalar/mod.rs [hunk 1]
```diff
@@ -1063,7 +1063,6 @@ impl ScalarValue {
 
     /// Create an one value in the given type.
     pub fn new_one(datatype: &DataType) -> Result<ScalarValue> {
-        assert!(datatype.is_primitive());
```
Comment (alamb) [inline datafusion/common/src/scalar/mod.rs:1066]: removing the assert (as any unhandled type will cause a runtime error) makes a lot of sense to me.

**Review by alamb — APPROVED** [review]
Thanks @tshauck  👨‍🍳  👌
