### PR TITLE
fix(datasource): keep stats absent when collect_stats is false

### LINKED ISSUE #2976: Bug: fix case where `num_rows` and `total_byte_size` are not defined (stat should be None instead of Some(0))
I'd love to create a pull request if there isn't any problem.
https://github.com/apache/arrow-datafusion/compare/master...thomas-k-cameron:arrow-datafusion:stat-should-be-None-instead-of-Some(0)

**Describe the bug**
Some fields of `Statistics` could return `Some(0)` when the value is not available.

TODO comment says that some fields are supposed to be `None` instead of `Some(0)` under some circumstances but the value is set to `Some(0)` even when it is supposed to have `None`.

```rust
/// Get all files as well as the file level summary statistics (no statistic for partition columns).
/// If the optional `limit` is provided, includes only sufficient files.
/// Needed to read up to `limit` number of rows.
/// TODO fix case where `num_rows` and `total_byte_size` are not defined (stat should be None instead of Some(0))
pub async fn get_statistics_with_limit(
    all_files: impl Stream<Item = Result<(PartitionedFile, Statistics)>>,
    file_schema: SchemaRef,
    limit: Option<usize>,
) -> Result<(Vec<PartitionedFile>, Statistics)>
```

**To Reproduce**
I haven't ran into any breaking bugs yet, however, the functions is used in a method provided by one of the method implemented on `ListingTable` struct and `Some(0)` is returned when the `options.collect_stat` is set to `false` (aka when it is not supposed to be available).

And it appears that it is generating 

`Statistics` is passed to a method implemented on `Arc<dyn FileFormat>` so chance of someone running into a bug is not zero.

Also, `pub async fn get_statistics_with_limit` is a exported function.

**Expected behavior**
returns `None` instead of `Some(0)`.

**Alternatives Considered**
1. Turn `Some(0)` to `None`.
However, this solution would be rather labour intensive as the field is being used by everywhere (over 200 occurrence)
Also anyone using it cannot determine is the size is 0 or the value is just not available
2. Assign `None` in ListingTable::async fn list_files_for_scan<'a>
`ListingTable::async fn list_files_for_scan<'a>` is the only function  calling `get_statistics_with_limit`. It can be fixed by assigning `None` to statistics.
However, `get_statistics_with_limit` is being exported so I didn't think it really solves the problem.
3. Return a number that was available
The `Statistics` struct is basically an aggregate of all `Statistics` struct passed onto the function.
Some values may have fields that is not `None`. 
Considering that `Statistics` is not meant to always return a accurate value, I think this could work too.

**Additional context**
Is it suppose to run get_statistics_with_limit when `options.collect_stat` is set to `false`?

Thank you very much for reading my issue and please let me know if I'm getting it wrong.

### PR DESCRIPTION
**Pull request by kumarUjjawal**
## Which issue does this PR close?

- Closes #2976
- Part of #8227

## Rationale for this change

  `get_statistics_with_limit` was copying first-file row/byte stats even when`collect_stats=false`. This could return `Exact(0)` instead of `Absent` (unknown stats).

## What changes are included in this PR?

 Summary stats are only initialized and merged when `collect_stats=true`. Also fixes first-file column `byte_size` initialization in the `collect_stats=true` path, and adds regression tests for both paths and limit behavior.

## Are these changes tested?

Yes

### CODE REVIEW

File: datafusion/datasource/src/statistics.rs [hunk 1]
```diff
@@ -320,16 +320,19 @@ pub async fn get_statistics_with_limit(
...
-        num_rows = file_stats.num_rows;
-        total_byte_size = file_stats.total_byte_size;
-        for (index, file_column) in
-            file_stats.column_statistics.clone().into_iter().enumerate()
-        {
-            col_stats_set[index].null_count = file_column.null_count;
-            col_stats_set[index].max_value = file_column.max_value;
-            col_stats_set[index].min_value = file_column.min_value;
-            col_stats_set[index].sum_value = file_column.sum_value.cast_to_sum_type();
+        if collect_stats {
```
Comment (kosiew) [inline datafusion/datasource/src/statistics.rs]: Thanks for fixing the returned summary here. I think this introduces a separate issue in the `limit` path though.

`get_statistics_with_limit` still relies on `num_rows` to decide whether it can stop early. With `collect_stats=false`, `num_rows` now stays `Absent`, so `conservative_num_rows` falls back to `usize::MIN` and we keep scanning the stream instead of stopping early.

Before this change, a known first-file row count could still let us stop after the first file. With this patch, even something like `limit=0` can continue reading later files.

Could we preserve a separate row-count accumulator, or at least keep the first-file row count around for the limit check, while still returning a bare `Statistics` value when `collect_stats` is false? I think we should also add a regression test for `collect_stats=false` with a limit so this behavior is locked in.

Comment (kosiew) [inline datafusion/datasource/src/statistics.rs]: Small refactor suggestion. It may be worth extracting the "seed stats from first file" logic into a helper that can optionally populate the summary accumulator.

This block and the later merge loop now both need to stay in sync on fields like `byte_size` and the `sum_value` casting. Pulling that into one place would make future stats-field additions a bit less likely to drift.

**Comment by kumarUjjawal** [comment]
Thanks @kosiew I have made the changes as requested, please take a look when you get the time.
