### PR TITLE
Avoid pushdown of volatile functions to tablescan

### LINKED ISSUE #13268: Filters on `RANDOM()` are applied incorrectly when pushdown_filters is enabled.
### Describe the bug

When running a query like
```
SELECT * FROM table WHERE RANDOM() < 0.1;
```

I get different results depending on the value of `"datafusion.execution.parquet.pushdown_filters"`. When this setting is turned off, I get the results I expect, roughly 10% of the rows in the table. When it is turned on, I think I'm seeing 1% of the rows in the table.

I suspect I'm seeing these results because pushdown with `TableProviderFilterPushDown::Inexact` is applying this filter at both the parquet level and a `FilterExec: random() <= 0.1`. This results in the `RANDOM()` filter being evaluated twice, which causes fewer rows to be sampled.

### To Reproduce

This can be reproduced with `datafusion-cli` version 42.2.0:

Without `pushdown_filters`
```
> create external table data stored as parquet location '/Users/adam.faulkner/Downloads/parquet_data/';
> select COUNT(*) from data WHERE RANDOM() < 0.1;
+----------+
| count(*) |
+----------+
| 605572   |
+----------+
1 row(s) fetched.
Elapsed 0.043 seconds.
```

With `pushdown_filters` (note that you must re-create the table with the updated setting):
```
> set datafusion.execution.parquet.pushdown_filters=true;
0 row(s) fetched.
Elapsed 0.002 seconds.

> create external table data stored as parquet location '/Users/adam.faulkner/Downloads/parquet_data/';
0 row(s) fetched.
Elapsed 0.007 seconds.

> select COUNT(*) from data WHERE RANDOM() < 0.1;
+----------+
| count(*) |
+----------+
| 60152    |
+----------+
1 row(s) fetched.
Elapsed 0.045 seconds.
```

### Expected behavior

I would expect that a filter on `RANDOM()` would be applied only once, so that `RANDOM() < 0.1` means that only 10% of all rows will be sampled.

It would be acceptable if `RANDOM()` was no longer eligible for pushdown, though I suspect this leaves a negligible amount of performance on the table compared to the alternative.

It feels like the "right" solution is to somehow guarantee that `RANDOM()` always returns the same value for a given row and query evaluation, perhaps by "caching" its values. 

### Additional context

In my custom TableProvider, I tried using ``TableProviderFilterPushDown::Exact` for these filters, and I get the results that I expect. However, it seems that this is only because my filter is really simple.

### PR DESCRIPTION
**Pull request by theirix**
## Which issue does this PR close?

When using pushdown filters, the planner pushes the volatile `random()` filter to the table source, so it executes in scan (for example, in parquet) and in the query engine, which leads to weird results.

Closes #13268.

## Rationale for this change

It's impossible to evaluate volatile filters in different layers.

## What changes are included in this PR?

- Improvement for rule optimiser to avoid passing volatile filters to scan
- Unit test

## Are these changes tested?

- Unit tests
- Regression tests
- Manual test

As proposed in the original issue, I tried `alltypes_tiny_pages_plain.parquet` sample file containing 7300 lines:

```sql
set datafusion.execution.parquet.pushdown_filters=true;
create external table data stored as parquet location 'alltypes_tiny_pages_plain.parquet';
```

Running a query 
```sql
select COUNT(*) from data WHERE RANDOM() < 0.1;
```
with `datafusion-cli` gives an answer of 726, which is pretty close to the expected 730.

New plan
```
+---------------+---------------------------------------------------------------------------------+
| plan_type     | plan                                                                            |
+---------------+---------------------------------------------------------------------------------+
| logical_plan  | Aggregate: groupBy=[[]], aggr=[[count(Int64(1)) AS count(*)]]                   |
|               |   Filter: random() < Float64(0.1)                                               |
|               |     TableScan: data projection=[]                                               |
| physical_plan | AggregateExec: mode=Final, gby=[], aggr=[count(*)]                              |
|               |   CoalescePartitionsExec                                                        |
|               |     AggregateExec: mode=Partial, gby=[], aggr=[count(*)]                        |
|               |       CoalesceBatchesExec: target_batch_size=8192                               |
|               |         FilterExec: random() < 0.1                                              |
|               |           RepartitionExec: partitioning=RoundRobinBatch(8), input_partitions=1  |
|               |             ParquetExec: file_groups={1 group: [[sample.parquet]]} 							|
|               |                                                                                 |
+---------------+---------------------------------------------------------------------------------+
```

Before the change plan was
```
| ParquetExec: file_groups={1 group: [[alltypes_tiny_pages_plain.parquet]]}, predicate=random() < 0.1 |
```
## Are there any user-facing changes?

No breaking changes.

### CODE REVIEW

File: datafusion/optimizer/src/push_down_filter.rs [hunk 1]
```diff
@@ -998,7 +998,19 @@ impl OptimizerRule for PushDownFilter {
                         filter_predicates.len());
                 }
 
-                let zip = filter_predicates.into_iter().zip(results);
+                let zip =
+                    filter_predicates
+                        .into_iter()
+                        .zip(results)
+                        .map(|(expr, res)| {
+                            let filter_pushdown_type = if expr.is_volatile() {
```
Comment (jonahgao) [inline datafusion/optimizer/src/push_down_filter.rs:1006]: nit: We could skip checking volatile if it’s already unsupported.
```rust
                let zip =
                    filter_predicates
                        .into_iter()
                        .zip(results)
                        .map(|(pred, mut res)| {
                            if !matches!(res, TableProviderFilterPushDown::Unsupported)
                                && pred.is_volatile()
                            {
                                // Do not push down predicate with volatile functions to scan
                                res = TableProviderFilterPushDown::Unsupported
                            }
                            (pred, res)
                        });
```

Comment (findepi) [inline datafusion/optimizer/src/push_down_filter.rs:1006]: shouldn't we check `is_volatile` before calling `scan.source.supports_filters_pushdown(...)`?

Comment (theirix) [reply datafusion/optimizer/src/push_down_filter.rs]: As I understand, we can ask a table source to tell if the filter is supported even for volatile expressions.

I thought the main difference is which call is more expensive. `supports_filters_pushdown` for different sources often provides blanket all-supported or all-unsupported for all predicates. So we can save `is_volatile` calls by filtering out `Unsupported` values before. In contrast, if we check for volatility first and only then ask the source if the filters are supported, we can waste `is_volatilty` calls. If the `supports_filters_pushdown` is more costly, let's reverse it, of course.

I pushed a change to check the volatility after filtering out unsupported predicates. If we prefer the inverse order, I could refactor this optimiser quite a bit to:
- Get a subset of supported predicates
- Apply the `is_volatile` filter to it
- Build `new_scan_filters` and `new_predicate`

Comment (jayzhan211) [reply datafusion/optimizer/src/push_down_filter.rs]: If there is possible that any table source can support volatile function then this checking should happen in `supports_filters_pushdown`.

Otherwise, we should check `is_volatile` before `supports_filters_pushdown`, so those table source don't need to care about whether the function is volatile or not.

Given that volatile has no deterministic result, I think it doesn't make sense to pushdown filter with those function, therefore I think we can check volatility beforehand

**Review by jayzhan211 — APPROVED** [review]
👍
