### PR TITLE
Fix panic in array_agg(distinct) query

### LINKED ISSUE #10486: [Regression]  Query using ARRAY_AGG(DISTINCT) causes panic
### Describe the bug

Beginning in v37.0.0, a previously-working query is found to result in a panic:

```
panicked at /Users/username/.cargo/registry/src/index.crates.io-6f17d22bba15001f/datafusion-physical-expr-37.1.0/src/aggregate/array_agg_distinct.rs:158:99:
:
assertion `left == right` failed: state array should only include 1 row!
  left: 4
 right: 1
```

### To Reproduce

The following query is known to trigger the panic, alongside the accompanying parquet payloads contained in the attached .zip file.

```sql
SELECT
        asm.floor,
        CONCAT(bi.name, '_', bi.asm_range_lower, ' - ', bi.asm_range_upper) AS name_with_range,
        ARRAY_AGG(DISTINCT s.code) AS codes,
        COUNT(DISTINCT asm.id) AS assembly_count,
        COUNT(DISTINCT s.id) AS item_qty
    FROM 'batch_items.parquet' bi
        INNER JOIN 'target_items.parquet' s
            ON s.id = bi.target_id
        INNER JOIN 'assemblies.parquet' asm
            ON s.assembly_id = asm.id
    GROUP BY
        asm.floor_ordinal,
        asm.floor,
        bi.batch_name,
        bi.name,
        bi.asm_range_lower,
        bi.asm_range_upper
    ORDER BY
        asm.floor_ordinal,
        bi.batch_name,
        bi.name,
        bi.asm_range_lower;
```
[failing-query-assets.zip](https://github.com/apache/datafusion/files/15295240/failing-query-assets.zip)

### Expected behavior

_No response_

### Additional context

I've confirmed that the issue does not present in v36.0.0 or earlier, and is present in v37.0.0 up to v38.0.0.  The issue doesn't present when omitting `ARRAY_AGG(DISTINCT ...)` from my queries.

### PR DESCRIPTION
**Pull request by jayzhan211**
## Which issue does this PR close?

Closes #10486 .

### CODE REVIEW

File: datafusion/physical-expr/src/aggregate/array_agg_distinct.rs [hunk 1]
```diff
@@ -153,12 +153,11 @@ impl Accumulator for DistinctArrayAggAccumulator {
             return Ok(());
         }
 
-        let array = &states[0];
-
-        assert_eq!(array.len(), 1, "state array should only include 1 row!");
```
Comment (dmitrybugakov) [inline datafusion/physical-expr/src/aggregate/array_agg_distinct.rs:158]: Is it okay that we just delete the assertion?

File: datafusion/physical-expr/src/aggregate/array_agg_distinct.rs [hunk 2]
```diff
@@ -153,12 +153,11 @@ impl Accumulator for DistinctArrayAggAccumulator {
...
-        // Unwrap outer ListArray then do update batch
-        let inner_array = array.as_list::<i32>().value(0);
-        self.update_batch(&[inner_array])
+        states[0]
+            .as_list::<i32>()
+            .iter()
+            .flatten()
```
Comment (alamb) [inline datafusion/physical-expr/src/aggregate/array_agg_distinct.rs:159]: what does the flatten do? Discard `Option`?

File: datafusion/sqllogictest/test_files/aggregate.slt [hunk 3]
```diff
@@ -198,6 +198,73 @@ statement error This feature is not implemented: LIMIT not supported in ARRAY_AG
...
+    select 1, 3
+    UNION ALL
+    select 1, 2
+    ---- The order is non-deterministic, verify with length
+) select array_length(array_agg(distinct a.foo)), sum(distinct 1) from A a group by a.id;
+----
+3 1
+
+# It has only AggregateExec with FinalPartitioned mode, so `merge_batch` is used
+# If the plan is changed, whether the `merge_batch` is used should be verified to ensure the test coverage
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/aggregate.slt:219]: 💯  for the explanatory comments about why this explain is here

File: datafusion/sqllogictest/test_files/aggregate.slt [hunk 4]
```diff
@@ -198,6 +198,73 @@ statement error This feature is not implemented: LIMIT not supported in ARRAY_AG
 SELECT array_agg(c13 LIMIT 1) FROM aggregate_test_100
 
 
+# Test distinct aggregate function with merge batch
```
Comment (alamb) [inline datafusion/sqllogictest/test_files/aggregate.slt:201]: I ran the test without the changes in this PR and it panic'd as expected:

```shell
cargo test --test sqllogictests
...
thread 'tokio-runtime-worker' panicked at datafusion/physical-expr/src/aggregate/array_agg_distinct.rs:158:9:
assertion `left == right` failed: state array should only include 1 row!
  left: 5
 right: 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Review by alamb — APPROVED** [review]
Thank you for the quick work @jayzhan211  -- very nice

File: datafusion/physical-expr/src/aggregate/array_agg_distinct.rs (hunk 2 above)
Comment (jayzhan211) [reply datafusion/physical-expr/src/aggregate/array_agg_distinct.rs:159]: yes

File: datafusion/physical-expr/src/aggregate/array_agg_distinct.rs (hunk 1 above)
Comment (jayzhan211) [reply datafusion/physical-expr/src/aggregate/array_agg_distinct.rs:158]: yes, because it is no longer true, this PR is dealing with the array that has len more than one

**Comment by jayzhan211** [comment]
Thanks @alamb !
