### PR TITLE
fix: Prefer numeric in type coercion for comparisons

### LINKED ISSUE #15161: Incorrect cast of integer columns to utf8 when comparing with utf8 constant
### Describe the bug

A comparison like `column1 < '10'` (where `column1` is an int64) will cast `column1` to utf8 instead of casting the utf8 constant to an integer.

Typically string constants in a sql query are treated as unknown, and preference should be on casting the "unknown" value to a target type.

### To Reproduce

```
DataFusion CLI v46.0.0
> create table t1 as (values (1), (2), (3));
0 row(s) fetched. 
Elapsed 0.026 seconds.

> select * from t1 where column1 < '10';
+---------+
| column1 |
+---------+
| 1       |
+---------+
1 row(s) fetched. 
Elapsed 0.015 seconds.

> select * from t1 where column1 < 'hello';
+---------+
| column1 |
+---------+
| 1       |
| 2       |
| 3       |
+---------+
3 row(s) fetched. 
Elapsed 0.007 seconds.

> select arrow_typeof(column1) from t1 limit 1;
+--------------------------+
| arrow_typeof(t1.column1) |
+--------------------------+
| Int64                    |
+--------------------------+
1 row(s) fetched. 
Elapsed 0.010 seconds.

> explain select * from t1 where column1 < '10';
+---------------+-------------------------------------------------------+
| plan_type     | plan                                                  |
+---------------+-------------------------------------------------------+
| logical_plan  | Filter: CAST(t1.column1 AS Utf8) < Utf8("10")         |
|               |   TableScan: t1 projection=[column1]                  |
| physical_plan | CoalesceBatchesExec: target_batch_size=8192           |
|               |   FilterExec: CAST(column1@0 AS Utf8) < 10            |
|               |     DataSourceExec: partitions=1, partition_sizes=[1] |
|               |                                                       |
+---------------+-------------------------------------------------------+
2 row(s) fetched. 
Elapsed 0.009 seconds.
```

### Expected behavior

`column1` not to be cast to a string.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by neilconway**
## Which issue does this PR close?

- Closes #15161.

## Rationale for this change

In a comparison between a numeric column and a string literal (e.g., `WHERE int_col < '10'`), we previously coerced the numeric column to be a string type. This resulted in doing a lexicographic comparison, which results in incorrect query results.

Instead, we split type coercion into two situations: type coercion for comparisons (including `IN` lists, `BETWEEN`, and `CASE WHEN`), where we want string->numeric coercion, and type coercion for places like `UNION` or `CASE ... THEN/ELSE`, where DataFusion's traditional behavior has been to tolerate type mismatching by coercing values to strings.

Here is a (not necessarily exhaustive) summary of the behavioral changes (old -> new):

```
  Comparisons (=, <, >, etc.):
    float_col = '5'      : string (wrong: '5'!='5.0')  -> numeric
    int_col > '100'      : string (wrong: '325'<'100') -> numeric
    int_col = 'hello'    : string, always false        -> cast error
    int_col = ''         : string, always false        -> cast error
    int_col = '99.99'    : string, always false        -> cast error
    Dict(Int) = '5'      : string                      -> numeric
    REE(Int) = '5'       : string                      -> numeric
    struct(int)=struct(str): int field to Utf8  -> str field to int

  IN lists:
    float_col IN ('1.0') : string (wrong: '1.0'!='1') -> numeric
    str_col IN ('a', 1)  : coerce to Utf8       -> coerce to Int64

  CASE:
    CASE str WHEN float  : coerce to Utf8       -> coerce to Float

  LIKE / regex:
    Dict(Int) LIKE '%5%' : coerce to Utf8       -> error (matches int)
    REE(Int) LIKE '%5%'  : coerce to Utf8       -> error (matches int)
    Dict(Int) ~ '5'      : coerce to Utf8       -> error (matches int)
    REE(Int) ~ '5'       : error (no REE)       -> error (REE added)
    REE(Utf8) ~ '5'      : error (no REE)       -> works (REE added)
```

## What changes are included in this PR?

* Update `comparison_coercion` to coerce strings to numerics
* Remove previous `comparison_coercion_numeric` function
* Add a new function, `type_union_coercion`, and use it when appropriate
* Add support for REE types with regexp operators (this was unsupported for no good reason I can see)
* Add unit and SLT tests for new coercion behavior
* Update existing SLT tests for changes in coercion behavior
* Fix the ClickBench unparser tests to avoid comparing int fields with non-numeric string literals

## Are these changes tested?

Yes. New tests added, existing tests pass.

## Are there any user-facing changes?

Yes, see table above. In most cases the new behavior should be more sensible and less error-prone, but it will likely break some user code.

### CODE REVIEW

**Comment by neilconway** [comment]
TODOs:
* [x] ClickBench queries are broken (see below)
* [ ] We might be able to remove some/all of the special-case logic in `cast_literal_to_type_with_op` (see #15110)
* [x] Decide whether type union coercion is well-motivated, or if we want to remove it (keep)

**Comment by neilconway** [comment]
One example of a weird behavior that we get with the new coercion rules proposed here:

```
> create table t1 (a text, b int, c float);
0 row(s) fetched.
Elapsed 0.018 seconds.

> explain select * from t1 where a < 5;
+---------------+-------------------------------+
| plan_type     | plan                          |
+---------------+-------------------------------+
| physical_plan | ┌───────────────────────────┐ |
|               | │         FilterExec        │ |
|               | │    --------------------   │ |
|               | │         predicate:        │ |
|               | │    CAST(a AS Int64) < 5   │ |
|               | └─────────────┬─────────────┘ |
|               | ┌─────────────┴─────────────┐ |
|               | │       DataSourceExec      │ |
|               | │    --------------------   │ |
|               | │          bytes: 0         │ |
|               | │       format: memory      │ |
|               | │          rows: 0          │ |
|               | └───────────────────────────┘ |
|               |                               |
+---------------+-------------------------------+
1 row(s) fetched.
Elapsed 0.016 seconds.
```

This follows from the "coerce string to numeric" change in general, but it's a bit weird. I think we should probably reject queries like this entirely, on the basis of a type mismatch.

If we did that and nothing else, we'd break a ton of queries (e.g., anything comparing a numeric column with a string literal). But we could fix that up by treating comparisons with string literals specially (e.g., "if x OP y mismatch in types, check if either x or y is a string literal; if so, try to coerce it to a numeric type"). So that's an alternative approach worth considering.

**Comment by neilconway** [comment]
The [ClickBench queries](https://github.com/apache/datafusion/blob/c699361cb4ae13276ca4bd936d3ed4d3cffe78e6/datafusion/core/tests/sql/unparser.rs#L109) are just weird: they have expressions like `"EventDate" >= '2013-07-01'`, where `EventDate` is a `uint16`. Previously, `EventDate` would be cast to a string and the comparison would have been done lexicographically, which is wrong but didn't fail. Now we'll try to coerce the string literal to a numeric, which fails. So this is intended behavior -- the ClickBench queries need fixing up some other way.

**Comment by AlonSpivack** [comment]
Thanks for putting this PR together @neilconway!
Splitting out `type_union_coercion` is definitely the right architectural move. 

Regarding your dilemma about `text_col < 5`: 
I strongly agree with your intuition that we should **reject these queries entirely** with a clear type-mismatch/planning error, rather than trying to add special-case fallback logic. If a user actually wants to compare a string column to a number, they should be required to add an explicit `CAST`.

**Comment by neilconway** [comment]
@AlonSpivack The challenge with rejecting `text_col < 5` under this approach is that in `comparison_coercion`, we've already lost the fact that we're comparing a column with a literal. All we see is a comparison between a string-typed value and a numeric-typed value, which this approach would allow.

If we want to reject `text_col < 5` and similar expressions, I think we need to remove the `comparison_coercion` logic for coercing string -> numeric and the like. We'd then have two options:

1. Introduce an "unknown" type. All string literals would have unknown type, and then would be coerced into a concrete type depending on the context in which they are used. This is roughly what Postgres does.
2. Don't introduce a distinct type, but just add some (perhaps ad-hoc) rules for coercing binary expressions where exactly one operand is a string literal and the other operand is a numeric-typed column reference.

(1) is probably more principled, but I think it's too big of a change to undertake on short notice.

(2) sounds plausible to me at first blush, but it needs more consideration.

**Comment by AlonSpivack** [comment]
Hey @neilconway ,
thanks for moving so quickly on this. Splitting the coercion rules between comparison_coercion and type_union_coercion is definitely the right architectural foundation, and it aligns with what @alamb suggested previously about context-aware coercion.

Regarding the bad query plans you mentioned (like CAST(text_col AS Int64) < 5) and the ClickBench issues:

I think we should tackle this in two separate PRs to respect the project's architecture:

PR 1 (This PR - Type Level): Your current approach (coercing string→numeric for comparisons) is correct at the type-abstraction level. Generating a CAST here is the right logical step to ensure mathematical correctness. As @alamb noted in the past (e.g., on PR #15482), type coercion rules should be based strictly on (DataType, DataType) pairs, not on checking for Expr::Literal. So mixing literal evaluation into this specific phase would be architecturally incorrect.

PR 2 (Follow-up - Optimizer Level): Once this PR lands, I'd like to submit a follow-up PR targeting the simplifier (specifically extending cast_literal_to_type_with_op in unwrap_cast.rs). Since the simplifier is expected to be expression-aware, we can safely intercept the CAST there:

Early Literal Folding: Fold Literal(Utf8("10")) → Literal(Int64(10)) at planning time when compared against a numeric column. This gives zero runtime cost and restores performance/predicate pushdown.

Fail-Fast for Invalid Literals: Throw an instant plan_err! for unparseable literals like int_col < 'hello' instead of deferring to a runtime CAST failure.

Expanded Coverage: Extend this logic beyond =/!= to handle <, >, <=, >=, and include Float types.

This two-phase approach gets the critical bug (#15161) fixed quickly, keeps the type coercion pure, and handles the performance/AST-awareness in the correct optimizer pass.

Happy to help with the follow-up PR. Thanks again for driving this fix!

**Comment by neilconway** [comment]
@AlonSpivack I wrote up an alternative approach to fixing it, and some comments back on the [issue](https://github.com/apache/datafusion/issues/15161#issuecomment-3936788737); it might be better to continue further discussion there since there's two PRs now.

File: datafusion/expr-common/src/type_coercion/binary.rs [hunk 1]
```diff
@@ -859,11 +886,15 @@ pub fn try_type_union_resolution_with_struct(
...
+/// When comparing numeric values and strings, the string value will be coerced
+/// to the numeric type. For example when comparing `'2' > 1` where `1` is
+/// `Int32`, `'2'` will be coerced to `Int32` for comparison.
+///
+/// For type unification contexts (see [`type_union_coercion`]), use
+/// [`type_union_coercion`] instead, which prefers strings as the safe widening
+/// type.
 pub fn comparison_coercion(lhs_type: &DataType, rhs_type: &DataType) -> Option<DataType> {
-    if lhs_type.equals_datatype(rhs_type) {
+    if lhs_type == rhs_type {
```
Comment (cetra3) [inline datafusion/expr-common/src/type_coercion/binary.rs]: Is there a reason for this change? Shouldn't we prefer `equals_datatype` here

File: datafusion/core/tests/sql/unparser.rs [hunk 2]
```diff
@@ -107,6 +107,14 @@ struct TestQuery {
 
 /// Collect SQL for Clickbench queries.
 fn clickbench_queries() -> Vec<TestQuery> {
+    // q36-q42 compare UInt16 "EventDate" column with date strings like '2013-07-01'.
+    // With numeric-preferring comparison coercion, these fail because a date string
+    // can't be cast to UInt16. These queries use ClickHouse conventions where
+    // EventDate is stored as a day-offset integer.
+    //
+    // TODO: fix this
+    const SKIP_QUERIES: &[&str] = &["q36", "q37", "q38", "q39", "q40", "q41", "q42"];
```
Comment (cetra3) [inline datafusion/core/tests/sql/unparser.rs]: Is there a world where we can make the appropriate changes and get these queries working?

File: datafusion/expr-common/src/type_coercion/binary.rs (hunk 1 above)
Comment (neilconway) [reply datafusion/expr-common/src/type_coercion/binary.rs]: Yes, I think `equals_datatype` is right here.

File: datafusion/core/tests/sql/unparser.rs (hunk 2 above)
Comment (neilconway) [reply datafusion/core/tests/sql/unparser.rs]: I think I have a solution, similar to what we do when we're actually running the queries -- load the data into a `xyz_raw` table and then define a view `xyz` that does the appropriate transform, basically.

**Comment by neilconway** [comment]
> LGTM but obviously need to work out what to do about those clickbench queries

Thanks for the review, @cetra3 !

**Comment by neilconway** [comment]
@alamb @adriangb @comphead FYI, I revised this PR and I think the current version is ready for review. Potentially a candidate for 53, if there's time.

File: datafusion/core/src/physical_planner.rs [hunk 3]
```diff
@@ -3436,16 +3436,16 @@ mod tests {
 
     #[tokio::test]
     async fn in_list_types() -> Result<()> {
-        // expression: "a in ('a', 1)"
-        let list = vec![lit("a"), lit(1i64)];
```
Comment (adriangb) [inline datafusion/core/src/physical_planner.rs:3578]: I guess the point of this change is that `a in ('a', 1)` now is an error? It would be great to move that to another test that explicitly checks the error, if it is plan time or execution time, etc.

File: datafusion/expr-common/src/type_coercion/binary.rs [hunk 4]
```diff
@@ -843,102 +842,100 @@ pub fn try_type_union_resolution_with_struct(
...
+/// The lower precision type is widened to the higher precision type
+/// (e.g., `Int32` vs `Int64` → `Int64`).
+///
+/// # Numeric / String comparisons
+///
+/// Prefers the numeric type (e.g., `'2' > 1` where `1` is `Int32` coerces
+/// `'2'` to `Int32`).
+///
+/// For type unification contexts (UNION, CASE THEN/ELSE), use
+/// [`type_union_coercion`] instead.
```
Comment (adriangb) [inline datafusion/expr-common/src/type_coercion/binary.rs:891]: Worth including a bit more here, e.g. rationale, why we have different behavior (matches Postgres, etc?)

**Comment by AdamGS** [comment]
@adriangb this seems reasonable, but so far we've tried to not do any type coercion internally, we've already had some issues with decimals, I suspect this might trigger more of these cases, and we'll need to do some rewriting to match the types.

**Comment by milenkovicm** [comment]
I'm not sure if i can give meaningful contribution in this case, ballista is relaying on datafusion for this behaviour. 

would we need to capture change of behaviour somewhere, like upgrade guide ?

**Comment by adriangb** [comment]
> I'm not sure if i can give meaningful contribution in this case, ballista is relaying on datafusion for this behaviour.
> 
> would we need to capture change of behaviour somewhere, like upgrade guide ?

Yes I think we should make an upgrading guide entry @neilconway.

If Ballista just uses DataFusion semantics and you are okay with this change then nothing to do on your end 😃

**Comment by milenkovicm** [comment]
Maybe sending an email to dev list for visibility would make sense, would it?

File: datafusion/expr-common/src/signature.rs [hunk 5]
```diff
@@ -158,7 +158,7 @@ pub enum Arity {
 pub enum TypeSignature {
     /// One or more arguments of a common type out of a list of valid types.
     ///
-    /// For functions that take no arguments (e.g. `random()` see [`TypeSignature::Nullary`]).
+    /// For functions that take no arguments (e.g. `random()`), see [`TypeSignature::Nullary`]).
```
Comment (martin-g) [inline datafusion/expr-common/src/signature.rs]:
```suggestion
    /// For functions that take no arguments (e.g. `random()`), see [`TypeSignature::Nullary`].
```

File: datafusion/expr-common/src/signature.rs [hunk 6]
```diff
@@ -184,38 +184,39 @@ pub enum TypeSignature {
...
     /// the types will both be coerced to `i64` before the function is invoked.
     ///
     /// If the `nullif('1', 2)` function is called with `Utf8` and `i64` arguments
-    /// the types will both be coerced to `Utf8` before the function is invoked.
+    /// the types will both be coerced to `Int64` before the function is invoked
+    /// (numeric is preferred over string).
     ///
     /// Note:
-    /// - For functions that take no arguments (e.g. `random()` see [`TypeSignature::Nullary`]).
+    /// - For functions that take no arguments (e.g. `random()`), see [`TypeSignature::Nullary`]).
```
Comment (martin-g) [inline datafusion/expr-common/src/signature.rs]:
```suggestion
    /// - For functions that take no arguments (e.g. `random()`), see [`TypeSignature::Nullary`].
```

File: datafusion/expr-common/src/signature.rs [hunk 7]
```diff
@@ -246,7 +247,7 @@ pub enum TypeSignature {
     /// For example, if a function is called with (utf8, large_utf8), all
     /// arguments will be coerced to  `LargeUtf8`
     ///
-    /// For functions that take no arguments (e.g. `random()` use [`TypeSignature::Nullary`]).
+    /// For functions that take no arguments (e.g. `random()`), use [`TypeSignature::Nullary`]).
```
Comment (martin-g) [inline datafusion/expr-common/src/signature.rs]:
```suggestion
    /// For functions that take no arguments (e.g. `random()`), use [`TypeSignature::Nullary`].
```

File: datafusion/expr/src/type_coercion/other.rs [hunk 8]
```diff
@@ -17,38 +17,58 @@
...
-    when_or_then_types: &[DataType],
-    case_or_else_type: Option<&DataType>,
+    then_types: &[DataType],
+    else_type: Option<&DataType>,
 ) -> Option<DataType> {
-    let case_or_else_type = match case_or_else_type {
-        None => when_or_then_types[0].clone(),
-        Some(data_type) => data_type.clone(),
+    let (initial_type, remaining) = match else_type {
+        None => (&then_types[0], &then_types[1..]),
```
Comment (martin-g) [inline datafusion/expr/src/type_coercion/other.rs]:
```suggestion
        None => then_types.split_first()?,
```
this would be more safe since it returns None if the slice has no items

File: datafusion/expr-common/src/type_coercion/binary.rs (hunk 4 above)
Comment (neilconway) [reply datafusion/expr-common/src/type_coercion/binary.rs:891]: Done, although I added the comment to `type_union_coercion` instead.

FWIW our behavior here does not match Postgres; for example, Postgres rejects queries like "SELECT 1 UNION SELECT 'a'", which we allow. I started going down the path of rejecting those queries in #20456, but that will break more user code, so I figured it would be best to defer for now. Another construct we allow that Postgres doesn't is `text_col <> int_col` -- again, I'd argue that is probably better to reject, but I didn't take that on as part of this PR.

File: datafusion/core/src/physical_planner.rs (hunk 3 above)
Comment (neilconway) [reply datafusion/core/src/physical_planner.rs:3578]: That's right; and good point, I updated the test to expicitly check for the type mismatch error.

**Comment by neilconway** [comment]
@adriangb @martin-g Thank you for the reviews!

I added a section to the upgrade guide for this change.

**Comment by neilconway** [comment]
@alamb @adriangb @martin-g I wanted to check in on this -- is there anything else that we need to do here before landing this?

**Comment by adriangb** [comment]
I have not heard any push back or alternative proposals in [Discord](https://discord.com/channels/885562378132000778/1166447479609376850/1474493692118302934) or the [mailing list](https://lists.apache.org/thread/5od7k7hmlzfv36p7jco65x29755xlkt8).

From my perspective this is good to go. Let's give Andrew and Martin a day or so to chime in, if there's no feedback to address by then we can go ahead and merge this. Thanks for your work @neilconway.

File: docs/source/library-user-guide/upgrading/53.0.0.md
Comment (martin-g) [inline docs/source/library-user-guide/upgrading/53.0.0.md:1]: This should probably be moved to 54.0.0.md now

File: datafusion/sqllogictest/test_files/string_numeric_coercion.slt [hunk 9]
```diff
@@ -0,0 +1,496 @@
...
+SELECT t1.l FROM t_list_int t1, t_list_str t2 WHERE t1.l = t2.l;
+----
+[20, 30]
+
+# List in UNION uses type union coercion (string preferred).
+# The integer list elements are cast to Utf8.
+query ? rowsort
+SELECT l FROM t_list_int UNION ALL SELECT l FROM t_list_str;
+----
+[1, 5, 10]
```
Comment (martin-g) [inline datafusion/sqllogictest/test_files/string_numeric_coercion.slt:447]: Here all results are numeric strings and it is hard to tell whether the integers were cast to Utf8. 
Let's check the results' type to be sure that it is a List(Utf8) and not List(Int64)

File: datafusion/core/tests/expr_api/mod.rs [hunk 10]
```diff
@@ -342,20 +342,25 @@ fn test_create_physical_expr_nvl2() {
...
-    // https://github.com/apache/datafusion/issues/14944
-    create_simplified_expr_test(col("i").eq(lit("202410")), "CAST(i@1 AS Utf8) = 202410");
-    create_simplified_expr_test(lit("202410").eq(col("i")), "CAST(i@1 AS Utf8) = 202410");
+    // string column vs int literal: id (Utf8) is cast to Int32
+    create_expr_test(col("id").eq(lit(1i32)), "CAST(id@0 AS Int32) = 1");
+    create_expr_test(lit(1i32).eq(col("id")), "1 = CAST(id@0 AS Int32)");
+    // int column vs string literal: the string literal is cast to Int64
+    create_expr_test(col("i").eq(lit("202410")), "i@1 = CAST(202410 AS Int64)");
+    create_expr_test(lit("202410").eq(col("i")), "CAST(202410 AS Int64) = i@1");
+    // when simplified, the literal cast is constant-folded
```
Comment (martin-g) [inline datafusion/core/tests/expr_api/mod.rs]: Here it says `the literal cast is constant-folded` but the expected_expr is still a `CAST(...)`, not just a constant.

File: datafusion/expr-common/src/type_coercion/binary.rs [hunk 11]
```diff
@@ -1707,7 +1636,8 @@ fn coerce_list_children(lhs_field: &FieldRef, rhs_field: &FieldRef) -> Option<Fi
     ))
 }
 
-/// Coercion rules for list types.
+/// Coerce two list types by coercing their element types via
+/// [`type_union_resolution`].
 fn list_coercion(lhs_type: &DataType, rhs_type: &DataType) -> Option<DataType> {
```
Comment (martin-g) [inline datafusion/expr-common/src/type_coercion/binary.rs]: Is it intentional that `list_coercion()` does not use `coerce_fn` as `struct_coercion()` and `map_coercion()` ?
Currently it delegates to `type_union_resolution()` which uses `string_numeric_coercion()` (a numeric preferring) even for UNION, CASE THEN/ELSE

File: datafusion/sqllogictest/test_files/string_numeric_coercion.slt [hunk 12]
```diff
@@ -0,0 +1,496 @@
...
+# List element coercion should reject mixed
+# numeric/string categories (same as array literals)
+# -------------------------------------------------
+
+# Array literal with mixed numeric/string elements errors
+query error Cannot cast string 'a' to value of Int64 type
+SELECT [1, 'a'];
+
+# MAP with mixed-category list keys should also error
+query error
```
Comment (martin-g) [inline datafusion/sqllogictest/test_files/string_numeric_coercion.slt]: Why there is no expected error message here ?

File: datafusion/sqllogictest/test_files/string_numeric_coercion.slt [hunk 13]
```diff
@@ -0,0 +1,496 @@
...
+SELECT MAP {[1,2,3]:1, ['a', 'b']:2};
+
+# MAP with mixed-category list values should also error
+query error
```
Comment (martin-g) [inline datafusion/sqllogictest/test_files/string_numeric_coercion.slt]: and here

File: datafusion/expr-common/src/type_coercion/binary.rs [hunk 14]
```diff
@@ -748,7 +747,7 @@ fn type_union_resolution_coercion(
                 .or_else(|| list_coercion(lhs_type, rhs_type))
                 .or_else(|| temporal_coercion_nonstrict_timezone(lhs_type, rhs_type))
                 .or_else(|| string_coercion(lhs_type, rhs_type))
-                .or_else(|| numeric_string_coercion(lhs_type, rhs_type))
+                .or_else(|| string_numeric_coercion(lhs_type, rhs_type))
```
Comment (martin-g) [inline datafusion/expr-common/src/type_coercion/binary.rs]: Shouldn't this be `string_numeric_union_coercion`, i.e. string-preferred coercion for UNION ?

File: datafusion/optimizer/src/analyzer/type_coercion.rs
Comment (martin-g) [inline datafusion/optimizer/src/analyzer/type_coercion.rs:522]: Is this check related to the changes in this PR ?

File: datafusion/expr-common/src/type_coercion/binary.rs (hunk 14 above)
Comment (neilconway) [reply datafusion/expr-common/src/type_coercion/binary.rs]: This is a good and subtle point that should be called out. The previous behavior actually already implemented numeric-preferring coercion in this case: this applied to situations like `VALUES` lists, array literals, or `COALESCE` expressions. So the prior behavior was not super consistent -- we implemented type-union-like behavior in some "type union-y" situations but not in others. Arguably, it would be more self-consistent to change this situation to be string-preferring, for consistency with the rest of this PR, but I think there are two good reasons not to do so:

 1. Further change to query behavior
 2. I'd like to see us eventually move toward stricter typing behavior, not looser, and this would be a step in the wrong direction that IMO we would eventually want to revert anyway, which would mean another breaking change.

File: datafusion/expr-common/src/type_coercion/binary.rs (hunk 11 above)
Comment (neilconway) [reply datafusion/expr-common/src/type_coercion/binary.rs]: Fixed to use `coerce_fn`.

File: datafusion/optimizer/src/analyzer/type_coercion.rs
Comment (neilconway) [reply datafusion/optimizer/src/analyzer/type_coercion.rs:522]: You mean, does this code need to be updated as part of this PR? I'd argue no -- the pre-existing behavior here was strict and not to do type coercion, which IMO makes sense.

**Comment by neilconway** [comment]
@martin-g Thanks for the great code review!

**Comment by neilconway** [comment]
@adriangb @alamb @martin-g Just checking in here -- do we think this is ready to land?

**Review by adriangb — APPROVED** [review]
I think this is ready to go. At a high level this is a great change, there is ongoing work after this but we should merge this and continue with that in other PRs not stall this, it's a big enough change as is.

CI is being a bit weird though - can you merge in main or rebase and lets have it do a full run and be green? Then I think we can merge tomorrow if there is no further feedback.

Image

**Comment by neilconway** [comment]
@adriangb Thanks! I merged in the latest main and it seems CI is happy again.

**Comment by adriangb** [comment]
Thanks @neilconway !!

**Comment by neilconway** [comment]
Thanks for the reviews and discussion! @adriangb @martin-g @alamb @milenkovicm @cetra3 @AlonSpivack
