### PR TITLE
Fix parquet filter_pushdown: respect parquet filter pushdown config in scan

### LINKED ISSUE #16588: Wrong results when `pushdown_filters` is enabled (starting in 48.0.0)
### Describe the bug

> There are a *lot* of linked issues and discussions here, so it's quite possible that I missed an existing bug report, but I wanted to report an issue I encountered when enabling `datafusion.execution.parquet.pushdown_filters`.

 _Originally posted by @ianthetechie in [#3463](https://github.com/apache/datafusion/issues/3463#issuecomment-3012612655)_

### To Reproduce

> 
> I've put together an MRE that demonstrates it with what seems like a trivial query (I initially had something MUCH more complex in a real app, but even this gets wrong results): https://github.com/ianthetechie/datafusion-predicate-pushdown-mre.
> 

### Expected behavior

> I am expecting the number to be 72, but the count comes to 1245 with `datafusion.execution.parquet.pushdown_filters` set to `true`.  

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adriangb**
- Fixes #16588

### CODE REVIEW

**Comment by adriangb** [comment]
I'm trying to understand why this isn't caught by `datafusion/sqllogictest/test_files/parquet_filter_pushdown.slt`. Might have to wait until tomorrow.

**Comment by adriangb** [comment]
I can confirm this new test fails without the change:

```
❯ cargo test -p datafusion-sqllogictest --test sqllogictests -- parquet_filter_pushdown
   Compiling datafusion-datasource-parquet v48.0.0 (/Users/adriangb/GitHub/datafusion-clone/datafusion/datasource-parquet)
   Compiling datafusion v48.0.0 (/Users/adriangb/GitHub/datafusion-clone/datafusion/core)
   Compiling datafusion-substrait v48.0.0 (/Users/adriangb/GitHub/datafusion-clone/datafusion/substrait)
   Compiling datafusion-sqllogictest v48.0.0 (/Users/adriangb/GitHub/datafusion-clone/datafusion/sqllogictest)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 4.69s
     Running bin/sqllogictests.rs (target/debug/deps/sqllogictests-5b94bf3a17202ad3)
Completed 1 test files in 0 seconds                                                                                                                                                                                                                                      External error: 1 errors in file /Users/adriangb/GitHub/datafusion-clone/datafusion/sqllogictest/test_files/parquet_filter_pushdown.slt

1. query result mismatch:
[SQL] select a from t where b > 2 ORDER BY a;
[Diff] (-expected|+actual)
+   bar
    baz
    foo
+   foo
    NULL
    NULL
    NULL
at /Users/adriangb/GitHub/datafusion-clone/datafusion/sqllogictest/test_files/parquet_filter_pushdown.slt:120



Error: Execution("1 failures")
error: test failed, to rerun pass `-p datafusion-sqllogictest --test sqllogictests`
```

File: datafusion/datasource-parquet/src/source.rs [hunk 1]
```diff
@@ -343,9 +343,7 @@ impl ParquetSource {
     }
 
     /// If true, the predicate will be used during the parquet scan.
-    /// Defaults to false
-    ///
-    /// [`Expr`]: datafusion_expr::Expr
+    /// Defaults to false.
```
Comment (alamb) [inline datafusion/datasource-parquet/src/source.rs:346]: How did this result in wrong results? 

Is it because the planner assumed filters would be pushed down but they weren't?

**Review by alamb — COMMENTED** [review]
Thank you @adriangb 🙏 

I don't understand how this fixes wrong results. I am out of time today but will check on this first thing tomorrow

File: datafusion/datasource-parquet/src/source.rs (hunk 1 above)
Comment (adriangb) [reply datafusion/datasource-parquet/src/source.rs:346]: Well this bit is just a comment 😛 

But this produced wrong results because we'd return `Supported(filter)` up to the parents -> `FilterExec` removed from the plan but `ParquetOpener.pushdown_filters = false` -> pruning did not actually happen during the scan.

File: datafusion/datasource-parquet/src/source.rs [hunk 2]
```diff
@@ -647,6 +651,7 @@ impl FileSource for ParquetSource {
             None => conjunction(allowed_filters.iter().cloned()),
         };
         source.predicate = Some(predicate);
+        source = source.with_pushdown_filters(pushdown_filters);
```
Comment (adriangb) [inline datafusion/datasource-parquet/src/source.rs:654]: @alamb this is the relevant LOC that fixes things

File: datafusion/datasource-parquet/src/source.rs [hunk 3]
```diff
@@ -625,7 +623,13 @@ impl FileSource for ParquetSource {
...
             return Ok(FilterPushdownPropagation::unsupported(filters));
         };
-        // Can we push down the filters themselves into the scan or only use stats pruning?
+        // Determine if based on configs we should push filters down.
+        // If either the table / scan itself or the config has pushdown enabled,
+        // we will push down the filters.
+        // If both are disabled, we will not push down the filters.
+        // By default they are both disabled.
+        // Regardless of pushdown, we will update the predicate to include the filters
+        // because even if scan pushdown is disabled we can still use the filters for stats pruning.
```
Comment (ianthetechie) [inline datafusion/datasource-parquet/src/source.rs:632]: I had wondered about this; thanks for updating this comment!

**Review by ianthetechie — APPROVED** [review]
I can confirm as well that it works when pointing at this branch using my original code. Thanks!

**Review by alamb — APPROVED** [review]
Thank you @adriangb  and @ianthetechie 

With his and several other issues, I think we should make a 48.0.1 release:

- https://github.com/apache/datafusion/issues/16486

I will begin work on that later today

**Comment by alamb** [comment]
Thank you @adriangb  -- I plan to backport this to the `branch-48`and include it in a patch release

**Comment by alamb** [comment]
Backport PR:
- https://github.com/apache/datafusion/pull/16656
