### PR TITLE
fix: sqllogictest runner label condition mismatch

### LINKED ISSUE #16282: [substrait] [sqllogictest] table 'datafusion.public.aggregate_test_100_by_sql' not found
### Describe the bug

~20 sqllogictest cases are failing in Substrait round-trip mode because of the following error:
```
statement failed: DataFusion error: Error during planning: table 'datafusion.public.aggregate_test_100_by_sql' not found
```

### To Reproduce

```
cargo test --test sqllogictests -- --substrait-round-trip pg_compat_null.slt:73
```

### Expected behavior

The sqllogictest passes in Substrait round-trip mode

### Additional context

This is part of a broader initiative to improve the reliability of Substrait-to-DataFusion logical plan conversions.
- https://github.com/apache/datafusion/issues/16248

### PR DESCRIPTION
**Pull request by lliangyu-lin**
## Which issue does this PR close?

- Closes #16282.

## Rationale for this change

The onlyif condition in sqllogictest test files are `DataFusion`
* https://github.com/apache/datafusion/blob/main/datafusion/sqllogictest/test_files/pg_compat/pg_compat_null.slt#L51
* https://github.com/apache/datafusion/blob/main/datafusion/sqllogictest/test_files/pg_compat/pg_compat_union.slt#L49

But current runner attaches `Datafusion` or `DatafusionSubstraitRoundTrip` which doesn't exists in any of the test files. Hence, causing the statement / query to be skipped.

## What changes are included in this PR?

* Update label in the test files to make sure statement / query is being run for datafusion.

## Are these changes tested?

Yes
* `cargo test --test sqllogictests -- --substrait-round-trip pg_compat_null.slt` (passing)
* `cargo test --test sqllogictests -- --substrait-round-trip pg_compat_union.slt` (no longer seeing the table not found exeception, but #16271 still exists)
* `cargo test --test sqllogictests -- --substrait-round-trip pg_compat_simple.slt` (no longer seeing the table not found exeception)
* `cargo test --test sqllogictests -- --substrait-round-trip pg_compat_window.slt` (no longer seeing the table not found exeception)

## Are there any user-facing changes?

No

### CODE REVIEW

**Comment by alamb** [comment]
@gabotechs  do you have time to review this PR?

**Comment by alamb** [comment]
Thank you @lliangyu-lin  🙏

File: datafusion/sqllogictest/bin/sqllogictests.rs [hunk 1]
```diff
@@ -243,7 +243,7 @@ async fn run_test_file_substrait_round_trip(
     };
     setup_scratch_dir(&relative_path)?;
 
-    let count: u64 = get_record_count(&path, "DatafusionSubstraitRoundTrip".to_string());
+    let count: u64 = get_record_count(&path, "DataFusion".to_string());
```
Comment (gabotechs) [inline datafusion/sqllogictest/bin/sqllogictests.rs]: We are going to need to keep the `"DatafusionSubstraitRoundTrip"` engine name for the future, we'll want to be able to ignore some statements based on it, something like:

```
skipif DatafusionSubstraitRoundTrip
```

Instead of changing the engine name, I'd go to the relevant tests in

https://github.com/apache/datafusion/blob/58cc4e1289451b30adca4721fd6eb5a36b26a2cd/datafusion/sqllogictest/test_files/pg_compat/pg_compat_null.slt#L51

And do the following replacement:
```
- onlyif DataFusion
+ skipif postgres
```

That way we maintain the ability to skip specific statements in `DatafusionSubstraitRoundTrip` mode, while prompting any engine other than `postgres` to actually try to comply with that test

Comment (lliangyu-lin) [reply datafusion/sqllogictest/bin/sqllogictests.rs]: Thanks for the context! Updated to `skipif postgres`. In this case, do we still need to change the label `Datafusion` -> `DataFusion`? Since there are no more test files with condition `onlyif DataFusion`.

Comment (gabotechs) [reply datafusion/sqllogictest/bin/sqllogictests.rs]: I'd be nice to keep the label as DatafusionSubstraitRoundTrip so that we can use it in the future for skipping tests failing on Substrait roundtrip mode 👍

Comment (lliangyu-lin) [reply datafusion/sqllogictest/bin/sqllogictests.rs]: Oh I guess my question was regarding the label `DataFusion` and `Datafusion` being used in the test files, which might be a typo, and not about `DatafusionSubstraitRoundTrip`. 
But I saw `Datafusion` label is still being used in other test files, so I removed my changes.

**Review by gabotechs — APPROVED** [review]
Nice! LGTM 👍  cc @alamb

**Comment by alamb** [comment]
run extended tests
