### PR TITLE
fix: trunc function with precision uses round instead of trunc semantics

### LINKED ISSUE #19793: Trunc function with precision uses `round`  instead of `trunc` semantics
### Describe the bug

The  trunc function with a precision argument incorrectly uses rounding semantics instead of truncation.

When calling [trunc(value, precision)] where `precision > 0`, the function uses `f64::round()` internally instead of `f64::trunc()`, causing values to be rounded to the nearest digit rather than truncated towards zero.

### To Reproduce

```sql
SELECT trunc(3.76, 1);
```

### Expected behavior

Should be truncated towards zero instead of rounds to nearest.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kumarUjjawal**
## Which issue does this PR close?

- Closes #19793.

## Rationale for this change

The helper functions `compute_truncate32` and `compute_truncate64` incorrectly use `.round()` instead of `.trunc()`, causing incorrect results:
- `trunc(3.76, 1)` returned `3.8` (wrong - rounded)
- `trunc(3.76, 1)` should return `3.7` (correct - truncated)

## What changes are included in this PR?

- Change `.round()` to `.trunc()` in `compute_truncate32` and `compute_truncate64`
- Update unit test expected values to reflect correct truncation behavior

## Are these changes tested?

Yes. Unit tests updated and pass.

### CODE REVIEW

File: datafusion/functions/src/math/trunc.rs [hunk 1]
```diff
@@ -238,9 +238,8 @@ mod test {
 
         assert_eq!(floats.len(), 5);
         assert_eq!(floats.value(0), 15.0);
-        assert_eq!(floats.value(1), 1_234.268);
```
Comment (martin-g) [inline datafusion/functions/src/math/trunc.rs:241]: why is this assertion removed ?

Comment (kumarUjjawal) [reply datafusion/functions/src/math/trunc.rs:241]: Oops, I might have accidently deleted the line during editing.

**Comment by Jefffrey** [comment]
Thanks @kumarUjjawal & @martin-g
