### PR TITLE
Don't preserve functional dependency when generating UNION logical plan

### LINKED ISSUE #12980: Functional dependency shouldn't be preserved in UNION logical plan
### Describe the bug

When the datafusion logical planner build the `AGGREGATE` plan, it adds additional columns in the group_expr based on the functional dependencies. However, for queries that are aggregating upon table obatined through `UNION` operation, the functional dependency is still preserved in the schema of UNION plan, while the functional dependency no longer retains after the UNION. This causes wrong column being added as group_by column in aggregation plan

### To Reproduce

Query involves aggregation on UNION will cause the issue. For example, the query below:

```SQL
with t1 as (
    select i_manufact_id, count(*) as extra from item
    group by i_manufact_id
),
t2 as (
    select i_manufact_id, count(*) as extra from item
    group by i_manufact_id
)
select i_manufact_id, sum(extra)
 from  (select * from t1
        union all
        select * from t2) tmp1
 group by i_manufact_id
 order by i_manufact_id;
```

This will lead to a logical plan that involves wrong extra column in Aggregate
`Aggregate: groupBy=[[tmp1.i_manufact_id, tmp1.extra]], aggr=[[sum(tmp1. extra)]]       `

### Expected behavior

UNION logical plan shouldn't retain functional dependencies from the tables involved in UNION. In the example below, both Table1 and Table2 has the functional dependency `col1 -> col2`. However, when `select * from table1 UNION select * from table2`, the functional dependency `col1 -> col2` no longer holds.
Table 1:
```
col1 | col2
-----|-----
a    | 1
b    | 2
```
Table 2:
```
col1 | col2
-----|-----
a    | 2
b    | 4
```

### Additional context

This bug is causing wrong results for running TPCDS query 33, 56, 60, 66 - duplicated groups are presented in results

### PR DESCRIPTION
**Pull request by Sevenannn**
## Which issue does this PR close?

Closes #12980 

## Rationale for this change

When the datafusion logical planner build the AGGREGATE plan, it adds additional columns in the group_expr based on the functional dependencies. However, for queries that are aggregating upon table obatined through UNION operation, the functional dependency is still preserved in the schema of UNION plan, while the functional dependency no longer retains after the UNION. This causes wrong column being added as group_by column in aggregation plan

## What changes are included in this PR?

- Changes to eliminate functional dependency when building `UNION` logical plan
- Unit test to verify the changes

## Are these changes tested?

Yes, unit test `test_aggregate_with_union` is added to verify the change

## Are there any user-facing changes?

Aggregation based upon UNION results will not produce wrong results with duplicated groups

### CODE REVIEW

**Comment by sgrebnov** [comment]
LGTM 👍

File: datafusion/core/src/dataframe/mod.rs [hunk 1]
```diff
@@ -2623,6 +2623,54 @@ mod tests {
...
+                "| d  | 126        |",
+                "| e  | 121        |",
+                "+----+------------+"
+            ],
+            &df_results
+        );
+
+        Ok(())
+    }
+
```
Comment (berkaysynnada) [inline datafusion/core/src/dataframe/mod.rs:2673]: I tried this test before this PR, and it fails as @Sevenannn explained. The current result matches what postgre provides

File: datafusion/expr/src/logical_plan/builder.rs [hunk 2]
```diff
@@ -1402,7 +1402,12 @@ pub fn validate_unique_names<'a>(
 pub fn union(left_plan: LogicalPlan, right_plan: LogicalPlan) -> Result<LogicalPlan> {
     // Temporarily use the schema from the left input and later rely on the analyzer to
     // coerce the two schemas into a common one.
-    let schema = Arc::clone(left_plan.schema());
+
+    // Functional Dependencies doesn't preserve after UNION operation
+    let schema = (**left_plan.schema()).clone();
+    let schema =
+        Arc::new(schema.with_functional_dependencies(FunctionalDependencies::empty())?);
+
```
Comment (berkaysynnada) [inline datafusion/expr/src/logical_plan/builder.rs:1410]: Is clearing out all dependencies the right fix? Could we retain some if they do not harm?

**Review by berkaysynnada — APPROVED** [review]
Thanks for the fix @Sevenannn. I have just one comment to consider. Otherwise, LGTM

File: datafusion/expr/src/logical_plan/builder.rs (hunk 2 above)
Comment (alamb) [reply datafusion/expr/src/logical_plan/builder.rs:1410]: I'll wait to merge this PR until tomorrow to give @Sevenannn  a chance to respond

Comment (Sevenannn) [reply datafusion/expr/src/logical_plan/builder.rs:1410]: Hi @berkaysynnada, thanks for the review! I don’t think any FD persists when performing UNION on 2 tables.

A simple example would be UNION table t1 with another table t2 which only has 1 row, there always exists such data in t2 which could break the FDs in t1 / t2 after the UNION.

In this case, clearing FDs would be the right fix since we don’t want FDs to get wrongly retained and affect later plans, e.g. aggregation.

Please let me know if you have any further questions regarding this PR, thanks!

**Comment by alamb** [comment]
Thanks again @Sevenannn  and @sgrebnov and @berkaysynnada
