### PR TITLE
bug: Fix edge cases in array_slice

### LINKED ISSUE #10548: `array_slice` can't correctly handle NULL parameters or some edge cases
### Describe the bug

These queries will give errors or incorrect results.

### To Reproduce

Run queries in CLI:
```sh
DataFusion CLI v38.0.0

> select array_slice([1,2,3], 1, NULL);
Internal error: could not cast value to arrow_array::array::primitive_array::PrimitiveArray<arrow_array::types::Int64Type>.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker

> select array_slice([1,2,3], -100, 1) r;
+----+
| r  |
+----+
| [] |
+----+
1 row(s) fetched.
Elapsed 0.006 seconds.

> select array_slice([1,2,3], 1, 1, -1) r;
+----+
| r  |
+----+
| [] |
+----+
```

### Expected behavior

The results of DuckDB look correct to me.
```sh
v0.10.3-dev779 d26007417b

D select array_slice([1,2,3], 1, NULL);
┌────────────────────────────────────────────────┐
│ array_slice(main.list_value(1, 2, 3), 1, NULL) │
│                    int32[]                     │
├────────────────────────────────────────────────┤
│                                                │
└────────────────────────────────────────────────┘
D select array_slice([1,2,3], -100, 1);
┌────────────────────────────────────────────────┐
│ array_slice(main.list_value(1, 2, 3), -100, 1) │
│                    int32[]                     │
├────────────────────────────────────────────────┤
│ [1]                                            │
└────────────────────────────────────────────────┘
D select array_slice([1,2,3], 1, 1, -1) r;
┌─────────┐
│    r    │
│ int32[] │
├─────────┤
│ [1]     │
└─────────┘
```

### PR DESCRIPTION
**Pull request by jkosh44**
This commit fixes the following edge cases in the array_slice function so that it's semantics match DuckDB:

  - When begin < 0 and -begin > length, begin is clamped to the beginning of the list.
  - When step < 0 and begin = end, then the result should be a list with the single element found at index begin/end.

- Fixes #10548

## Which issue does this PR close?

- Closes #10548.

## Are these changes tested?
Yes

## Are there any user-facing changes?

Yes, the behavior of `array_slice` has changed.

### CODE REVIEW

File: datafusion/functions-nested/src/extract.rs [hunk 1]
```diff
@@ -487,7 +487,17 @@ where
...
         let adjusted_zero_index = if index < 0 {
             if let Ok(index) = index.try_into() {
-                index + len
+                // When index < 0 and -index > length, index is clamped to the beginning of the list.
+                // Otherwise, when index < 0, the index is counted from the end of the list.
+                //
+                // Note, we actually test the contrapositive, index < -length, because negating a
+                // negative will panic if the negative is equal to the smallest representable value
+                // while negating a positive is always safe.
+                if index < (O::zero() - O::one()) * len {
```
Comment (jkosh44) [inline datafusion/functions-nested/src/extract.rs:496]: If anyone knows a simpler way of negating `len`, please let me know.

Comment (alamb) [reply datafusion/functions-nested/src/extract.rs:496]: I played around with it and I could not find anything better than this

**Comment by jkosh44** [comment]
> I think this PR is nicely implemented, commented and tested 🏆

Thank you!

**Review by jonahgao — APPROVED** [review]
I tested some other edge cases that I had collected before, and they all passed. Thank you @jkosh44 very much.
