### PR TITLE
Fix Infer prepare statement type tests 

### LINKED ISSUE #15577: Fix PREPARE statement tests
@qstommyshu pointed out on  https://github.com/apache/datafusion/pull/15567#discussion_r2028790675

That tests that imply they are testing PREPARE are actually not (likely a mistake)

I actually looks to me like it is a mistake in the test 🤔 

Perhaps the test should be something like 

```rust
    let sql = "PREPARE SELECT id, age FROM person WHERE age BETWEEN $1 AND $2";
```

Instead of 
```rust
    let sql = "SELECT id, age FROM person WHERE age BETWEEN $1 AND $2";
```

(maybe we can fix this in a follow on PR -- I will file a ticket)

_Originally posted by @alamb in https://github.com/apache/datafusion/pull/15567#discussion_r2028790675_

### PR DESCRIPTION
**Pull request by brayanjuls**
## Which issue does this PR close?

- Closes #15577

## Rationale for this change

This intent to correct issues on the prepare statements infer type tests. Currently they are not correctly asserting the expected behavior specially when we try to validate types. 

## What changes are included in this PR?

- Restore the original naming.
- Include the "PREPARE" statement clause without type. 
- Update insta snapshots.
- Pending: Get the inferred types part of the plan.

## Are these changes tested?

Yes

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/sql/tests/sql_integration.rs [hunk 1]
```diff
@@ -4673,16 +4675,17 @@ fn test_infer_types_from_predicate() {
...
+    let sql = "PREPARE my_plan AS SELECT id, age FROM person WHERE age BETWEEN $1 AND $2";
 
     let plan = logical_plan(sql).unwrap();
     assert_snapshot!(
         plan,
         @r#"
-    Projection: person.id, person.age
-      Filter: person.age BETWEEN $1 AND $2
-        TableScan: person
+    Prepare: "my_plan" []
```
Comment (brayanjuls) [inline datafusion/sql/tests/sql_integration.rs:4685]: Currently when the logical plan is created it does not include the type inferred, this result in some issues when we try to  call the function `plan.with_param_values(param_values)` as it tries to extract the type from the plan but it is empty. Are we expecting the plan to contain the type at this time? if so probably there is another bug we need to investigate.

Comment (brayanjuls) [reply datafusion/sql/tests/sql_integration.rs:4685]: @alamb @qstommyshu any advice on where to look to debug why the plan is not properly generating the inferred type?

Comment (qstommyshu) [reply datafusion/sql/tests/sql_integration.rs:4685]: Hi @brayanjuls , I've taken a look at your tests. The reason why this happen is there is no parameters being passed to the sql, but the sql itself contains positional arguments like `$1` and `$2`, please refer to https://datafusion.apache.org/user-guide/sql/prepared_statements.html#inferred-types. 

The simple way you can fix it is by adding the position arguments type to the `sql` like how it was done in [`test_prepare_statement_to_plan_one_param`](https://github.com/apache/datafusion/blob/main/datafusion/sql/tests/sql_integration.rs). If you want to dig into the details about it, you can check [how planner parse `PREPARE` statement](https://github.com/apache/datafusion/blob/main/datafusion/sql/src/planner.rs) and transfer it into a logical plan.

Comment (brayanjuls) [reply datafusion/sql/tests/sql_integration.rs:4685]: but wouldn't that mean the type is not being inferred, but instead we are explicitly declaring it? 

Thanks, I would check the planner parser.

Comment (qstommyshu) [reply datafusion/sql/tests/sql_integration.rs:4685]: I didn't check the details for "PREPARE" statement yet, but I think the type inference behaviour depends on how the planner parser is implemented, it could be either way.

**Comment by qstommyshu** [comment]
Hi @brayanjuls,

Thanks for the clever fix! For this issue, I suggest we keep our changes limited to the test file. Modifying [datafusion/sql/src/statement.rs](https://github.com/apache/datafusion/pull/15743/files#diff-bb98aeaec478d9576e33911f252745961f57e38d25f6e9d13803894dfbad25d5) would constitute a user-facing API change—let’s open a new issue for that and address it in its own PR.

@alamb What do you think?

File: datafusion/sql/src/statement.rs [hunk 2]
```diff
@@ -710,6 +710,25 @@ impl<S: ContextProvider> SqlToRel<'_, S> {
...
+                                _ => None,
+                            })
+                            .collect::<Vec<DataType>>();
+                        data_types.sort();
+                        planner_context.with_prepare_param_data_types(data_types.clone());
+                        data_types
+                    }
+                    false => data_types,
+                };
+
```
Comment (qstommyshu) [inline datafusion/sql/src/statement.rs:731]: This will introduce `explicitly declaring data types` to datafusion, maybe we should create a new issue/PR for this change?

Comment (alamb) [reply datafusion/sql/src/statement.rs:731]: yes, I agree making the behavior change in a separate PR might be better

Perhaps we could add a method on the `Prepare` struct that would return the parameter types (or walk over the expressions in the plan calling infer types if the parameter types are not specified)

https://docs.rs/datafusion/latest/datafusion/logical_expr/struct.Prepare.html#structfield.data_types

So then the test would look like

```rust
#[test]
fn test_infer_types_from_join() {
    let sql =
        "SELECT id, order_id FROM person JOIN orders ON id = customer_id and age = $1";

    let plan = logical_plan(sql).unwrap();
    assert_snapshot!(
        plan,
        @r#"
    Projection: person.id, orders.order_id
      Inner Join:  Filter: person.id = orders.customer_id AND person.age = $1
        TableScan: person
        TableScan: orders
    "#
    );

    // NEW: verify the parameter types
    let LogicalPlan::Prepare(prepare) = plan else {
      panic!("Expected prepare, got {plan:?}");
    };

    // call new function to create or infer the datatypes
    assert_eq!(prepare.get_or_infer_datatypes(), vec![DataType::Int32]);
```

File: datafusion/sql/src/statement.rs [hunk 3]
```diff
@@ -710,6 +710,25 @@ impl<S: ContextProvider> SqlToRel<'_, S> {
                     *statement,
                     &mut planner_context,
                 )?;
+
+                //Get inferred data_types from the plan if it is empty in the prepare statement
+                let data_types = match data_types.is_empty() {
```
Comment (alamb) [inline datafusion/sql/src/statement.rs:715]: is there a reason to use a match rather than just if/else?

```suggestion
                let data_types = if data_types.is_empty() {
```
...
?

**Review by alamb — COMMENTED** [review]
Thank you @brayanjuls and @qstommyshu

File: datafusion/sql/tests/sql_integration.rs [hunk 4]
```diff
@@ -4695,34 +4698,37 @@ fn test_infer_types_from_between_predicate() {
...
+    match plan_with_params {
+        Ok(plan_p) => assert_snapshot!(
+            plan_p,
+            @r"
+        Projection: person.id, person.age
+          Filter: person.age BETWEEN Int32(10) AND Int32(30)
+            TableScan: person
+        "
+        ),
+        Err(err) => print!("error: {:?}", err),
```
Comment (kczimm) [inline datafusion/sql/tests/sql_integration.rs:4711]: If `LogicalPlan::with_param_values` fails, we want this test to fail, right?

File: datafusion/sql/src/statement.rs (hunk 2 above)
Comment (kczimm) [reply datafusion/sql/src/statement.rs:731]: `LogicalPlan` variants other than `Prepare` can have `Expr::Placeholder` present, though.

File: datafusion/sql/src/statement.rs [hunk 5]
```diff
@@ -710,6 +710,25 @@ impl<S: ContextProvider> SqlToRel<'_, S> {
...
+                                (_, Some(v)) => Some(v.clone()),
+                                _ => None,
+                            })
+                            .collect::<Vec<DataType>>();
+                        data_types.sort();
+                        planner_context.with_prepare_param_data_types(data_types.clone());
+                        data_types
+                    }
+                    false => data_types,
+                };
```
Comment (kczimm) [inline datafusion/sql/src/statement.rs:730]: If you make `data_types` mutable above, you can do something like this which is a bit more terse:

```suggestion
                if data_types.is_empty() {
                    for dt in plan.get_parameter_types()?.into_values().into_iter() {
                        if let Some(dt) = dt {
                            data_types.push(dt);
                        }
                    }
                    data_types.sort();
                    planner_context.with_prepare_param_data_types(data_types.clone());
                }
```

File: datafusion/sql/src/statement.rs (hunk 2 above)
Comment (brayanjuls) [reply datafusion/sql/src/statement.rs:731]: thanks for the feedback I really appreciate it, I will create a new issue and move the statement changes to a different PR. I will only put back the original function names and include the `PREPARE` clause in this PR.

File: datafusion/sql/src/statement.rs (hunk 3 above)
Comment (brayanjuls) [reply datafusion/sql/src/statement.rs:715]: No, if/else will do.

File: datafusion/sql/src/statement.rs (hunk 5 above)
Comment (brayanjuls) [reply datafusion/sql/src/statement.rs]: I like it, it looks simpler, thanks!

File: datafusion/sql/tests/sql_integration.rs (hunk 4 above)
Comment (brayanjuls) [reply datafusion/sql/tests/sql_integration.rs:4711]: good catch! I changed this just because I was debugging, this will fail if we do not declare or infer the types in the `prepare`.

File: datafusion/sql/src/statement.rs [hunk 6]
```diff
@@ -710,6 +710,7 @@ impl<S: ContextProvider> SqlToRel<'_, S> {
                     *statement,
                     &mut planner_context,
                 )?;
+
```
Comment (qstommyshu) [inline datafusion/sql/src/statement.rs:713]: Please remove this empty line

File: datafusion/sql/tests/sql_integration.rs [hunk 7]
```diff
@@ -4607,82 +4607,58 @@ fn test_prepare_statement_to_plan_params_as_constants() {
...
-
-    assert_snapshot!(
-        plan_with_params,
-        @r"
-    Projection: person.id, orders.order_id
-      Inner Join:  Filter: person.id = orders.customer_id AND person.age = Int32(10)
-        TableScan: person
-        TableScan: orders
-    "
-    );
```
Comment (qstommyshu) [inline datafusion/sql/tests/sql_integration.rs:4641]: Great! I see your inferred type changes is in another issue. This part of the test shouldn't be removed in this issue, right? You can add new inferred type tests in #16019 along with your changes

File: datafusion/sql/tests/sql_integration.rs [hunk 8]
```diff
@@ -4607,82 +4607,58 @@ fn test_prepare_statement_to_plan_params_as_constants() {
...
-    let plan_with_params = plan.with_param_values(param_values).unwrap();
-
-    assert_snapshot!(
-        plan_with_params,
-        @r"
-    Projection: person.id, person.age
-      Filter: person.age = Int32(10)
-        TableScan: person
-    "
-    );
```
Comment (qstommyshu) [inline datafusion/sql/tests/sql_integration.rs:4672]: Same for here

File: datafusion/sql/tests/sql_integration.rs [hunk 9]
```diff
@@ -4692,75 +4668,46 @@ fn test_infer_types_from_between_predicate() {
...
-    let plan_with_params = plan.with_param_values(param_values).unwrap();
-
-    assert_snapshot!(
-        plan_with_params,
-        @r"
-    Projection: person.id, person.age
-      Filter: person.age BETWEEN Int32(10) AND Int32(30)
-        TableScan: person
-    "
-    );
```
Comment (qstommyshu) [inline datafusion/sql/tests/sql_integration.rs:4707]: and here

File: datafusion/sql/tests/sql_integration.rs [hunk 10]
```diff
@@ -4692,75 +4668,46 @@ fn test_infer_types_from_between_predicate() {
...
-    Projection: person.id, person.age
-      Filter: person.age = (<subquery>)
-        Subquery:
-          Projection: max(person.age)
-            Aggregate: groupBy=[[]], aggr=[[max(person.age)]]
-              Filter: person.id = UInt32(10)
-                TableScan: person
-        TableScan: person
-        "
-    );
```
Comment (qstommyshu) [inline datafusion/sql/tests/sql_integration.rs:4749]: and here

File: datafusion/sql/tests/sql_integration.rs [hunk 11]
```diff
@@ -4806,22 +4740,6 @@ fn test_insert_infer() {
...
-    ];
-    let plan_with_params = plan.with_param_values(param_values).unwrap();
-    assert_snapshot!(
-        plan_with_params,
-        @r#"
-    Dml: op=[Insert Into] table=[person]
-      Projection: column1 AS id, column2 AS first_name, column3 AS last_name, CAST(NULL AS Int32) AS age, CAST(NULL AS Utf8) AS state, CAST(NULL AS Float64) AS salary, CAST(NULL AS Timestamp(Nanosecond, None)) AS birth_date, CAST(NULL AS Int32) AS 😀
-        Values: (UInt32(1) AS $1, Utf8("Alan") AS $2, Utf8("Turing") AS $3)
-    "#
-    );
```
Comment (qstommyshu) [inline datafusion/sql/tests/sql_integration.rs:4824]: and here

File: datafusion/sql/tests/sql_integration.rs [hunk 12]
```diff
@@ -4770,32 +4717,19 @@ fn test_update_infer() {
...
-
-    assert_snapshot!(
-        plan_with_params,
-        @r"
-    Dml: op=[Update] table=[person]
-      Projection: person.id AS id, person.first_name AS first_name, person.last_name AS last_name, Int32(42) AS age, person.state AS state, person.salary AS salary, person.birth_date AS birth_date, person.😀 AS 😀
-        Filter: person.id = UInt32(1)
-          TableScan: person
-        "
-    );
```
Comment (qstommyshu) [inline datafusion/sql/tests/sql_integration.rs:4786]: and here

**Review by qstommyshu — CHANGES_REQUESTED** [review]

File: datafusion/sql/tests/sql_integration.rs (hunk 7 above)
Comment (brayanjuls) [reply datafusion/sql/tests/sql_integration.rs:4641]: I removed them because without the inferred type changes the tests will fail because of the validation linked below, which happen after we call `plan.with_param_values(param_values).unwrap();` in the tests, thats one of the reason I needed to introduce the inferred type changes. 

https://github.com/apache/datafusion/blob/967384e16257bab4deb48bbeff38507ea13c4abd/datafusion/common/src/param_value.rs#L33-L44

**Review by qstommyshu — APPROVED** [review]

File: datafusion/sql/tests/sql_integration.rs (hunk 7 above)
Comment (kczimm) [reply datafusion/sql/tests/sql_integration.rs:4641]: I've no preference here.

**Review by alamb — APPROVED** [review]
Thank you @brayanjuls @qstommyshu and @kczimm 

I reviewed this PR more carefully and now in retrospect I think the tests added in this PR (`test_prepare_...`) are useful and valid (they cover `PREPARE`)

However, I think the original tests are also useful as they cover type inference / parameter filling for queries that are not in a PREPARE statement (for example how some systems fill in bind parameters)

In order to avoid this PR from dragging on, I pushed a commit that 
1. Leave the original tests the way they are
2. Add the new tests

Would someone be willing to make a PR to move the `prepare` and `infer` tests into a new module (sql_integration.rs at 5000 lines is pretty massive) so it is easier to reason about them? Perhaps into `cases/parameters.rs`? I filed a ticket:
- https://github.com/apache/datafusion/issues/16056

I also think it would be super helpful to refactor these tests now that we have the `insta` framework to avoid some of the repetition. I filed
- https://github.com/apache/datafusion/issues/16057 to track
