### PR TITLE
Project sort expressions in StreamingTable

### LINKED ISSUE #19717: `StreamingTable` does not project physical sort expressions
### Describe the bug

When performing a `scan` using a `StreamingTable` that contains sort expressions, if the projection does not include one of the sort columns it leads to an error.

`PhysicalExpr Column references column 'b' at index 1 (zero-based) but input schema only has 1 columns: [\"a\"]`

### To Reproduce

```

#[tokio::test]
async fn test_sort_with_streaming_table() -> Result<()> {
    let batch = record_batch!(
            ("a", Int32, [1, 2, 3]),
            ("b", Int32, [1, 2, 3])
    )?;

    let ctx = SessionContext::new();

    let sort_order = vec![
        SortExpr::new(
            Expr::Column(datafusion_common::Column::new(
                Option::<TableReference>::None,
                "a",
            )),
            true,
            false,
        ),
        SortExpr::new(
            Expr::Column(datafusion_common::Column::new(
                Option::<TableReference>::None,
                "b",
            )),
            true,
            false,
        ),
    ];
    let schema = batch.schema();
    let batches = Arc::new(DummyStreamPartition {
        schema: schema.clone(),
        batches: vec![batch],
    }) as _;
    let provider = StreamingTable::try_new(schema.clone(), vec![batches])?
        .with_sort_order(sort_order);
    ctx.register_table("test_table", Arc::new(provider))?;

    let sql = "SELECT a FROM test_table group by a";
    ctx.sql(sql).await?.show().await?;

    Ok(())
}
```

### Expected behavior

The above test should pass.

### Additional context

I think this can probably be resolved in `StreamingTable::scan`. We can project the schema before calling `create_physical_sort_exprs`

### PR DESCRIPTION
**Pull request by timsaucer**
## Which issue does this PR close?

- Closes #19717

## Rationale for this change

If we have a `StreamingTable` that has both physical sort expressions and projection, we will get errors when trying to execute the plan if the sort expressions are not included in the projection.

## What changes are included in this PR?

When we have both projection and physical sort expressions, project the schema and the sort expressions.

## Are these changes tested?

Unit test added.

## Are there any user-facing changes?

No

### CODE REVIEW

File: datafusion/catalog/src/streaming.rs [hunk 1]
```diff
@@ -105,7 +104,18 @@ impl TableProvider for StreamingTable {
...
-            create_physical_sort_exprs(&self.sort_order, &df_schema, eqp)?
+            let original_sort_exprs =
+                create_physical_sort_exprs(&self.sort_order, &df_schema, eqp)?;
+
+            if let Some(p) = projection {
+                let schema = Arc::new(self.schema.project(p)?);
+                LexOrdering::new(original_sort_exprs)
+                    .and_then(|lex_ordering| project_ordering(&lex_ordering, &schema))
+                    .map(|lex_ordering| lex_ordering.to_vec())
+                    .unwrap_or_default()
```
Comment (kosiew) [inline datafusion/catalog/src/streaming.rs:119]: A comment explaining the projection adjustment will be helpful here

**Comment by alamb** [comment]
Shall we merge it?

Thank you for the review @kosiew

**Comment by timsaucer** [comment]
Yes. I just pushed the requested code comments, and I'll merge after CI finishes.

**Comment by timsaucer** [comment]
Thank you @kosiew and @alamb

**Comment by alamb** [comment]
🎉 -- keeping the code flowing
