### PR TITLE
Fix name tracker

### LINKED ISSUE #17508: Improve substrait NameTracker so it doesn't require uuids
the following PR adds uuids to certain substrait identifiers to disambiguate them, but this may make the plans non reproducable. @Blizzara has some ideas how how we can avoid the UUIDs
- https://github.com/apache/datafusion/pull/17299

FWIW, I looked a bit at what it'd take to fix the tracker. I think a core of the issue is that DF checks name ambiguity in two ways: there's the AmbiguousColumn exception you're running into, and then there is a `validate_unique_names()` function which gets called on the creation of the Project. The former needs unique non-qualified names, while the latter needs unique schema names (which _can_ be qualified). 

An easy fix for the former would be to change `name_for_alias()` into `qualified_name()._1` here https://github.com/apache/datafusion/blob/1d9e13845021c2e82a012c2e83938c2a7661f295/datafusion/substrait/src/logical_plan/consumer/utils.rs#L398. However, that then regresses the latter check (including in the test case for this PR), since there will then be a project node with an expr `CAST(B.C as Utf8)` with a qualified name ([no qualifier], "B.C") and a schema name "B.C", as well as a reference to the original column `B.C` with a qualified name ("B", "C") and also schema name "B.C". As the qualified name's name parts are different, it wouldn't be renamed (after the change I propose), and then it'd fail the `validate_unique_names()` check. So maybe for a proper fix, NameTracker would need to track **both the schema name and the name-part of the qualified name**, and rename until both are unique.

(A simple example of the behavior of the CAST and validate_unique_names() is that `SELECT data.a, CAST(data.a as string) from data;` also fails in datafusion-cli.)

_Originally posted by @Blizzara in https://github.com/apache/datafusion/pull/17299#discussion_r2330926518_

### PR DESCRIPTION
**Pull request by xanderbailey**
## Which issue does this PR close?

- Closes #17508

## Rationale for this change

The previous implementation used UUID-based aliasing as a workaround to prevent duplicate names for literals in Substrait plans. This approach had several drawbacks:
- Non-deterministic plan names that made testing difficult (requiring UUID regex filters)
- Only addressed literal naming conflicts, not the broader issue of name deduplication
- Added unnecessary dependency on the `uuid` crate
- Didn't properly handle cases where the same qualified name could appear with different schema representations

## What changes are included in this PR?

  1. Enhanced NameTracker: Refactored to detect two types of conflicts:
    - Duplicate schema names: Tracked via schema_name() to prevent validate_unique_names failures (e.g., two Utf8(NULL) literals)
    - Ambiguous references: Tracked via qualified_name() to prevent DFSchema::check_names failures when a qualified field (e.g., left.Utf8(NULL)) and unqualified field (e.g., Utf8(NULL)) share the same column name
2. **Removed UUID dependency**: Eliminated the `uuid` crate from `datafusion/substrait`
3. **Removed literal-specific aliasing**: The UUID-based workaround in `project_rel.rs` is no longer needed as the improved NameTracker handles all naming conflicts consistently
4. **Deterministic naming**: Name conflicts now use predictable `__temp__N` suffixes instead of random UUIDs

Note: This doesn't fully fix all the issues in #17508 which allow some special casing of `CAST` which are not included here.
## Are these changes tested?

Yes:
- Updated snapshot tests to reflect the new deterministic naming (e.g., `Utf8("people")__temp__0` instead of UUID-based names)
- Modified some roundtrip tests to verify semantic equivalence (schema matching and execution) rather than exact string matching, which is more robust
- All existing integration tests pass with the new naming scheme

## Are there any user-facing changes?

Minimal. The generated plan names are now deterministic and more readable (using `__temp__N` suffixes instead of UUIDs), but this is primarily an internal representation change. The functional behavior and query results remain unchanged.

### CODE REVIEW

**Comment by xanderbailey** [comment]
Thanks for the review, I have a couple of failing test cases here that I need to look into. Will take a look on Monday and report back.

File: datafusion/substrait/src/logical_plan/consumer/utils.rs [hunk 1]
```diff
@@ -396,9 +424,22 @@ impl NameTracker {
...
+            self.insert(&expr);
+            return Ok(expr);
+        }
+
+        // Name collision - need to generate a unique alias
+        let schema_name = expr.schema_name().to_string();
+        let mut counter = 0;
+        loop {
+            let candidate_name = format!("{schema_name}__temp__{counter}");
+            let candidate_expr = expr.clone().alias(candidate_name.clone());
```
Comment (hareshkh) [inline datafusion/substrait/src/logical_plan/consumer/utils.rs]: This clone could be avoided by checking in the hashsets directly

**Review by hareshkh — APPROVED** [review]

File: datafusion/substrait/src/logical_plan/consumer/utils.rs [hunk 2]
```diff
@@ -396,10 +433,25 @@ impl NameTracker {
...
+            self.insert(&expr);
+            return Ok(expr);
         }
+
+        // Name collision - need to generate a unique alias
+        let schema_name = expr.schema_name().to_string();
+        let mut counter = 0;
+        let candidate_name = loop {
+            let candidate_name = format!("{schema_name}__temp__{counter}");
+            // .alias always produces an unqualified name so check for conflicts accordingly.
```
Comment (dd-annarose) [inline datafusion/substrait/src/logical_plan/consumer/utils.rs:446]: could we use `alias_qualified()` instead of `alias` or does that complicate things too much?

Comment (xanderbailey) [reply datafusion/substrait/src/logical_plan/consumer/utils.rs:446]: Yeah great question, looked at that and I think it complicates things and I can't find a reason to change it. I.e. I couldn't write a failing test that it would fix so thought it was best to keep it as is. WDYT?

Comment (dd-annarose) [reply datafusion/substrait/src/logical_plan/consumer/utils.rs:446]: let's keep it as is then

**Comment by xanderbailey** [comment]
@LiaCastaneda are you able to give this a look, seems like @dd-annarose and @hareshkh are good with it but I know you're also invested in the substrait work. 

Hoping this will fix a number of the ambiguous reference errors we're seeing.

File: datafusion/substrait/src/logical_plan/consumer/utils.rs [hunk 3]
```diff
@@ -396,10 +433,25 @@ impl NameTracker {
...
+        if !self.would_conflict(&expr) {
+            self.insert(&expr);
+            return Ok(expr);
         }
+
+        // Name collision - need to generate a unique alias
+        let schema_name = expr.schema_name().to_string();
+        let mut counter = 0;
+        let candidate_name = loop {
+            let candidate_name = format!("{schema_name}__temp__{counter}");
```
Comment (LiaCastaneda) [inline datafusion/substrait/src/logical_plan/consumer/utils.rs:445]: There is also some logic to rename aliases to make them unique (used for avoiding duplicate names in join schemas [here](https://github.com/apache/datafusion/blob/468b690d71350bc19c7e7bafd5dc61800973d91e/datafusion/expr/src/logical_plan/builder.rs#L1591) and [here](https://github.com/apache/datafusion/blob/468b690d71350bc19c7e7bafd5dc61800973d91e/datafusion/expr/src/logical_plan/builder.rs#L1760)) This generates plans with `:N` suffixes like [this](https://github.com/apache/datafusion/blob/468b690d71350bc19c7e7bafd5dc61800973d91e/datafusion/substrait/tests/cases/consumer_integration.rs#L614), but this operates on Arrow `Fields` rather than `Expr`, so it can't be easily unified with the `__temp__` mechanism. Maybe a future consistency improvement could standardize on one naming convention (using `__temp__{N}` everywhere), though probably the current distinction may be intentional (`__temp__` = substrait conversion, `:N` = standard deduplication)? 
(I'm not suggesting any change with this, it's an open question if it makes sense)

**Review by LiaCastaneda — APPROVED** [review]
Thanks for looking into this! 🙇‍♀️ I think this is a neat and easy to follow solution
cc @gabotechs or @alamb -- I think this PR makes sense. would either of you be able 
to review whenever you have time?

**Comment by gabotechs** [comment]
Thanks @xanderbailey for the PR, and @dd-annarose, @hareshkh and @LiaCastaneda for the reviews.
